### ISSUE TITLE
implement DragEnabled on SignalPlotXY

### ISSUE THREAD

**Issue by breakwinz** [ScottPlot/ScottPlot#1002]
Hi. It would be very useful if there was an option to enable dragging on a signalplotXY. 
For example im drawing several signalplotsXY on a single formsplot. I am then calculating the standard deviation Y for every point of X and drawing a 1 standard deviation signalPlotXY in a thick and clear line.

It would be quite useful if it were possible to enable a drag feature on a signalplot in horizontal or vertical direction as such:

var std_line_positive = FormsPlot1.Plot.AddSignalXY(x_std[], y_positive_std[]);
var std_line_negative = FormsPlot1.Plot.AddSignalXY(x_std[], y_negative_std[])

std_line_positive.DragEnabledVertical = true; <---- doesnt exist
std_line_negative.DragEnabledVertical = true;<---- doesnt exist

this would allow the user to click and drag the two signalplot lines and "all it does" in the background is shifting the y-values up and down. Similarly if there is DragEnabledHorizontal then the x values can be shifted up and down (left and right on graph)

Here is a beautiful paint image to explain. Bottom and top brown lines are the standard deviation i have calculated for all the signalplots in the middle. I want to be able to shift them up and down graphically

![image](https://user-images.githubusercontent.com/81701546/116723947-f3e70b00-a9d7-11eb-804c-4aa9ebf24c5b.png)

Is this something that would be easy/difficuly to implement?

Many thanks

**Comment by StendProg** [comment]
Hi @breakwinz,

First of all, you can solve your problem in another way. You can simply bind SignalXY.OffsetY to some slider in the interface, and move `Signal` using it.

As for the implementation of `IDraggable` for a `SignalXY`, this is not a trivial task, but a solvable one. The main difficulties will be with `IsUnderMouse()` method, especially if we take into account the `snap`.
The problem is that it would be logical to  also add `IDraggable` to many other `Plotables`, and this is already a rather voluminous task.
I'll see what can be done for `SignalXY` the other day.

**Comment by StendProg** [comment]
I ran into certain difficulties, the problem is that it is impossible to move the SignalXY l using existed `DragTo()`, you also need to know from what point the dragging was.
The very architecture of dragging plottables does not allow dragging anything other than horizontal/vertical lines. It is necessary to change the approach itself, I cannot promise that I will do it in the near future, but I will try to do it.

**Comment by breakwinz** [comment]
@StendProg  Thank you for looking into this. Would have been a very nice feature. But as you suggested I have gotten around it using a slider/offset interface for now which is very usefull as well.

**Comment by StendProg** [comment]
Working on it, of course there is still a lot of work, but there are already some successes, the draggable scatter:

![DraggableScatter](https://user-images.githubusercontent.com/53831487/120384093-65471000-c32e-11eb-8202-7349fbf7a68c.gif)

Signals, with their millions of points, will take a long time to optimize mouse-signal intersection detection.

**Comment by swharden** [comment]
Hi @breakwinz, thank you for opening this issue! Your "beautiful paint image" actually does a great job of explaining the goal. Thanks for describing your idea so clearly!

---

@StendProg your implementation of this concept in #1111 is very interesting! I assume it works as shown, but I am ***extremely hesitant*** to continue adding new mouse interactions to ScottPlot. Very popular plotting libraries like matplotlib don't support these types of features, and I'm afraid that if we support this today next week someone will ask for resizable bar plots, then adjustable errorbars, then the ability to drag individual points in signal plots, and there will be no end to the custom requests 😅

Simulating mouse interaction with a static bitmap is really hard. Aside from the basics (pan/zoom), everyone will probably want their application to do something different, so it's hard to make a "one size fits all" solution.

Also, when signal/scatter plots are zoomed in most of their shape is the connecting lines (not the points). It seems very complicated to add proper support for dragging angled lines (especially when the points may not be in order). If only the corners are draggable, users may find this confusing (especially if the points are hidden and only lines are shown), and in cases like step plots.

Your original answer https://github.com/ScottPlot/ScottPlot/issues/1002#issuecomment-830765628 is probably the best answer, and should be the official stance for ScottPlot when similar requests arise in the future: _"ScottPlot displays plots as Bitmaps. Although mouse interaction is supported for pan/zoom, plot types that display data are not intended to be mouse interactive. Users who wish to modify the plot based on mouse actions are encouraged to place controls outside the ScottPlot that modify the plot or its data as needed._

What do you think of this opinion? I am happy to hear alternative suggestions if you have ideas or use cases I have not thought of! Your code in #1111 was very interesting to review, and some of these helper algorithms may be very helpful to use in the future.
