### ISSUE TITLE
Add option to heatmaps for customizing smoothing/interpolation

### ISSUE THREAD

**Issue by xichaoqiang** [ScottPlot/ScottPlot#1003]
This is a heatmap demo in the cookbook. 
It seems that different pixels are assigned different color values. This seems to be very low resolution.

![image](https://user-images.githubusercontent.com/30900789/116807752-73571480-ab67-11eb-87a2-6b07ce84a30c.png)

This is another heatmap demo from Microsoft .This kind of heat map appears to have a high resolution.
https://github.com/microsoft/InteractiveDataDisplay.WPF

![image](https://user-images.githubusercontent.com/30900789/116807799-c03aeb00-ab67-11eb-9fa2-ddd6cb46c187.png)

**Comment by bclehmann** [comment]
The resolution of the heatmap is dependent on the input data. The heatmap in the demo is 100x100, which is quite low for normal images.

Heatmaps from experimental data often are low resolution, for example if this were data from pressure sensors you would need 10 000 sensors for a 100x100 image, which is quite a bit.

However, since the data is from a function one could absolutely bump up the resolution. I think the demo might have been written back when heatmaps had poor performance on large inputs.

**Comment by xichaoqiang** [comment]
Yes heatmap need more smooth.

My data size is 400 x 400.This is my wanted spectrum. 

![图片](https://user-images.githubusercontent.com/30900789/116834279-dd1b0100-abef-11eb-819c-3a93e48be045.png)

**Comment by swharden** [comment]
Re-stating the issue, a 400x400 heatmap is currently being displayed as square pixels, but @xichaoqiang expects the default appearance to be smooth.

@bclehmann adding an interpolation option to the heatmap module may be the way to achieve this effect when resizing the heatmap to its final size

https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics.interpolationmode
https://docs.microsoft.com/en-us/dotnet/api/system.drawing.drawing2d.interpolationmode

I feel like we discussed interpolation before... but I guess not in the context of final heatmap image resizing. Let's expose some type of option to let the user control the final interpolation mode. Maybe something as simple as `public bool Smooth=true`? You could use an `enum InterpolationMode`, but let's avoid passing in a System.Drawing object to make that dependency easier to cut one day.

https://github.com/ScottPlot/ScottPlot/blob/6dd7005e5f736e2e0a4abb3d0214f22735ac1974/src/ScottPlot/Plottable/Heatmap.cs#L209

Here's a useful chart of [interpolation modes from matplotlib](https://matplotlib.org/stable/gallery/images_contours_and_fields/interpolation_methods.html)
![image](https://user-images.githubusercontent.com/4165489/116835187-6c43fc80-ab8f-11eb-942f-0a15dfd3cb3f.png)

**Comment by xichaoqiang** [comment]
Thanks for your reply.

**Comment by xichaoqiang** [comment]
And can you help me to check another closed issue? I have some new question,too. @swharden

**Comment by bclehmann** [comment]
I think custom interpolation is better than a boolean smooth. I think a custom enum that has nearest neighbour (default), bilinear, and bicubic is probably sufficient?

**Comment by StendProg** [comment]
Hi all,

`CoordinatedHeatmap` already have `Interpolation` property.

~If you want to implement interpolation for `Heatmap`, we need take to account this fixes:~
They are already present in `Hetmap`, well, you still need to keep that in mind.

https://github.com/ScottPlot/ScottPlot/blob/6dd7005e5f736e2e0a4abb3d0214f22735ac1974/src/ScottPlot/Plottable/CoordinatedHeatmap.cs#L26
https://github.com/ScottPlot/ScottPlot/blob/6dd7005e5f736e2e0a4abb3d0214f22735ac1974/src/ScottPlot/Plottable/CoordinatedHeatmap.cs#L33-L34

I don't remember the details, but without them bilinear interpolation looked incorrect.

**Comment by swharden** [comment]
For reference, here are the interpolation modes available in System.Drawing:

![Test_BitmapInterpolation_ShowAllModes_Bicubic](https://user-images.githubusercontent.com/4165489/119923699-27b64180-bf40-11eb-8f93-752899cc6f11.png)![Test_BitmapInterpolation_ShowAllModes_HighQualityBicubic](https://user-images.githubusercontent.com/4165489/119923713-300e7c80-bf40-11eb-90be-ff6a64cbd58e.png)![Test_BitmapInterpolation_ShowAllModes_Bilinear](https://user-images.githubusercontent.com/4165489/119923719-343a9a00-bf40-11eb-898c-dad5a901119d.png)![Test_BitmapInterpolation_ShowAllModes_HighQualityBilinear](https://user-images.githubusercontent.com/4165489/119923741-41578900-bf40-11eb-8b3b-e5999a6472db.png)![Test_BitmapInterpolation_ShowAllModes_NearestNeighbor](https://user-images.githubusercontent.com/4165489/119923663-166d3500-bf40-11eb-9595-594908a4bd0f.png)

**Comment by swharden** [comment]
Note that `InterpolationMode` doesn't seem to work on Linux or MacOS in Azure Pipelines (#1085)

This is extremely surprising considering how many blog posts there are "demonstrating" it. https://devblogs.microsoft.com/dotnet/net-core-image-processing/ and https://www.hanselman.com/blog/how-do-you-use-systemdrawing-in-net-core are some big ones. It doesn't throw an exception, but the interpolation mode isn't being respected.

I tried modifying `SmoothingMode`, `CompositingQuality`, and `CompositingMode` to be like examples I found online but this did not work. I'm relying on my `Bitmap` hashing algorithm to do the comparison but I haven't inspected the actual images.

This may be worth more investigation and possible an issue on https://github.com/dotnet/runtime

**Comment by swharden** [comment]
Heatmap smoothing (using high quality bicubic interpolation) can now be enabled like this:

```cs
Random rand = new(0);
double[,] data = ScottPlot.DataGen.Random2D(rand, 4, 5);

var plt = new ScottPlot.Plot(400, 300);
var hm = plt.AddHeatmap(data);
hm.Smooth = true;
```

![image](https://user-images.githubusercontent.com/4165489/119928097-e5453280-bf48-11eb-9ee8-e4015c095dc4.png)


This feature will be in the next version of ScottPlot on NuGet in the next few days. 

Thanks for creating this issue @xichaoqiang! 👍 🚀

**Comment by xichaoqiang** [comment]
> Heatmap smoothing (using high quality bicubic interpolation) can now be enabled like this:
> 
> ```cs
> Random rand = new(0);
> double[,] data = ScottPlot.DataGen.Random2D(rand, 4, 5);
> 
> var plt = new ScottPlot.Plot(400, 300);
> var hm = plt.AddHeatmap(data);
> hm.Smooth = true;
> ```
> 
> ![image](https://user-images.githubusercontent.com/4165489/119928097-e5453280-bf48-11eb-9ee8-e4015c095dc4.png)
> 
> This feature will be in the next version of ScottPlot on NuGet in the next few days.
> 
> Thanks for creating this issue @xichaoqiang! 👍 🚀

Thanks,really good job.
