### ISSUE TITLE
Which version of System.Drawing.Common should ScottPlot depend on?

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1004]
A new version of the [System.Drawing.Common package](https://www.nuget.org/packages/System.Drawing.Common) is released with every major .NET version

***Which version should ScottPlot depend on? How often (if ever) should it be changed?***

Currently ScottPlot 4.0 depends on `4.7.0` and ScottPlot 4.1 depends on `5.0.0`, but these weren't chosen intentionally

Both could be upgraded to the latest (`5.0.2`) but I'm not sure if this would fix problems or cause more pain

Alternatively I could make it so each build target uses the version-matched System.Drawing.Common

Related: #993, #924, #655

**Comment by bukkideme** [comment]
Hi!

@swharden , you wrote it is hard to recreate this issue. For me, it is very easy, please see the steps below to reproduce the issue, using a .NET Framework 4.7.2 WinForm project (VS2019 v16.9.4 Community):

1. Create a Winform .NET FrameWork 4.7.2 project from VS
2. Install ScottPlot 4.0.48 WinForm using nuget package manager
[WindowsFormsApp1_472.zip](https://github.com/ScottPlot/ScottPlot/files/6411787/WindowsFormsApp1_472.zip)
[WindowsFormsApp1_472.zip](https://github.com/ScottPlot/ScottPlot/files/6411789/WindowsFormsApp1_472.zip)


3. Pull a FormsPlot control to the UI. Everything works as it should
4. Notice that after installing ScottPlot in nuget manager, the manager tells you to update System.Drawing.Common from 4.7 to 5.0.2 latest version. Do it.
5. Close solution, close VS2019.
6. Restart VS2019, open solution
7. Notice that you cannot open the Form1.cs [Design] anymore, you get the earlier mentioned version collision error msgs.

Attempt to fix this issue:

1. Go to nuget packages, and downgrade System.Drawing.Common back to v4.7.
2. Close and reopen solution/project.
3. Now you can open the designer (Form1.cs [Design]), it works again
4. Try to run the code.
5. You get System.IO.FileLoadException ("„System.Drawing.Common, Version=4.0.0.2, Culture=neutral, .....cannot be loaded....")

I imagine if you do not update System.Drawing.Common from 4.7, we are safe... However, it looks like if you do so, there is no way back (I did not try GIT if that would be a solution to recover to working state).
This is serious for an existing project. I am thinking what would be the less painful route to fix the above issue if we accidentaly let System.Drawing.Common to update to latest...?

Here is the used solution zipped (state at step 5. second list):
[WindowsFormsApp1_472.zip](https://github.com/ScottPlot/ScottPlot/files/6411786/WindowsFormsApp1_472.zip)

Thanks!

**Comment by swharden** [comment]
Thank you for these detailed instructions! I followed them but was unable to reproduce the error on my machine. I'm using Visual Studio Community 2019 (version 16.9.4) like you

Here's a really boring video demonstrating everything works as expected on my machine. Do you see anything I'm doing different from you?

https://user-images.githubusercontent.com/4165489/116820852-2104fc00-ab45-11eb-9cb7-a7f6a3a2e806.mp4

**Comment by swharden** [comment]
Your ZIP crashes on my system with the same error, but upgrading to System.Drawing.Common 4.7.2 fixes it. Does this fix it for you too?

If so, perhaps a solution to smooth things out would be just to target .NET 4.7.2 and newer for everything (both ScottPlot and System.Drawing.Common)

I'm reminded that [support for .NET Framework 4.5.2, 4.6, and 4.6.1 will end on April 26, 2022](https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework)

**Comment by bukkideme** [comment]
Ok, I installed System.Drawing.Common 4.7.2.
What is very strange, now the application CAN run, however, the designer still crashes! I opened/closed VS and the project too. 
Same problem still: designer crashes.
Why are these differences between your and mine PC? Same VS, should be same behaviour... OS here at this rig is: 
Win10 Home, 19041.928 build.

![kép](https://user-images.githubusercontent.com/51174971/116821838-c9ce4e00-ab7b-11eb-9f68-3974349c5a38.png)

![kép](https://user-images.githubusercontent.com/51174971/116821845-d9e62d80-ab7b-11eb-901b-795eb4cc000c.png)

**Comment by swharden** [comment]
> I installed System.Drawing.Common 4.7.2 SDK https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net472-developer-pack-offline-installer now the application CAN run

This is pretty helpful to know! It seems some of these errors are caused by not having the SDK installed, so maybe that could be advice to offer in the future for people who have similar issues

> the designer still crashes!

What about creating a new project from scratch and trying those same steps again?

**Comment by bukkideme** [comment]
You misunderstood, I downgraded back to System.Drawing.Common 4.7.2 in the nugget manager, did not install the .NET Framework SDK 4.7.2.

Now as a next test, I installed also the 4.7.2 SDK, and the designer was still crashing. I did a PC restart. Did not help, the previously created project's designer still crashing.

Ok, now I create a brand new Winform project from scratch, and "accidentally" upgrade System.Drawing.Common to 5.0.2. Close project, open VS and project. Code runs, designer still crashes.
Downgraded System.Drawing.Common back to 4.7.2. Closed VS, reopened solution.
Code runs, designer still crashes! :(

It looks like I cannot manage to find a proper fix. This is bad. Right now I do not have the time to install all those SDKs what you have on your PC, maybe another SDK version is required too to avoid this bug??

So right now with these SDKs I have still the designer bug:

![kép](https://user-images.githubusercontent.com/51174971/116822797-28e29180-ab81-11eb-9737-f2494ec8abb6.png)

**Comment by swharden** [comment]
> It looks like I cannot manage to find a proper fix. This is bad. 

Thanks for all your input so far! These issues are really difficult to troubleshoot. Design time / VS issues are the worst!

> all those SDKs

It looks like you already have the important SDK (4.7.2), and I don't think installing more SDKs would really help here

**Comment by bukkideme** [comment]
Some more tests with the same project:

1. Downgraded System.Drawing.Common from 4.7.2 to 4.7.1. Result: Designer works now! But now code run crashes, haha! :) "System.IOFileLoadException, System.Drawing.Common, Version=4.0.0.2 cannot be loaded..."
2. Downgraded System.Drawing.Common from 4.7.1 to 4.7.0. Result: same as above!

By the way, inside my project, the path for System.Drawing.Common under "References" is:
C:\Users\*****\source\repos\WindowsFormsApp1_newTry_with_SDK\packages\System.Drawing.Common.4.7.0\lib\net461\System.Drawing.Common.dll

My knowledge is quite limited in this area (too :) ). I wonder, why there is "net461" in the path? Should not be 4.7.2?

**Comment by bukkideme** [comment]
It looks like I have found a fix/workaround. Actually I do not really understand why it works, and why it needs to be done. 
Maybe some expert can explain it to me :)

I opened **App.config** in Notepad++ and edited the "bindingRedirect ..." line. See the edited line, and below the edited one, the original commented out. 
Is this a VisualStudio bug? Maybe when we downgrade a nuget package, VS does not properly propagate changes toward App.config???

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Drawing.Common" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
		<?bindingRedirect oldVersion="0.0.0.0-4.0.0.2" newVersion="4.0.0.2"?>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by swharden** [comment]
I've been working on this the whole time too - so confusing! I downloaded the latest System.Drawing.Common 5.0.2 package from NuGet, renamed ".nupkg" to ".zip", extracted it, then loaded the `lib\net461\System.Drawing.Common.dll` into dnSpy

![image](https://user-images.githubusercontent.com/4165489/116824163-beb4f700-ab56-11eb-99f1-494ab464bc11.png)

I'm reminded there are many different types of versions. With this specific package...

* Package Name: `System.Drawing.Common`
* Package Version: `5.0.2`
* It multi-targets .NET Core (`netcoreapp3.0`) and .NET Framework
* The assembly version is `4.0.0.2` (note that System.Drawing is `4.0.0.0`)
* The assembly file version is `4.6.29719.01`

I think that explains some of this stuff (why 461 is in the DLL path, and why the DLL is referred to as 4.0.0), although I still don't know how to fix the main problem here

> I opened App.config in Notepad++ and edited the "bindingRedirect ..." line. See the edited line, and below the edited one, the original commented out. Now designer works, code runs!

I downloaded your original zip and modified `App.config` by deleting the `bindingRedirect` line... but now I get the error message and it sounds like you don't 🤣 we can't win here!

**Comment by bukkideme** [comment]
> I downloaded your original zip and modified App.config by deleting the bindingRedirect line... but now I get the error message and it sounds like you don't 🤣 we can't win here!

Did you first downgrade Sys.Drawing.Common to 4.7.0? Close VS. Then modify the app config as i did. Still crashes?

**Comment by swharden** [comment]
Hey I think we may have figured this out!

* System.Drawing.Common 4.x uses assembly version `4.0.0.1`
* System.Drawing.Common 4.x uses assembly version `4.0.0.2`

When you install version 5 it adds this line to App.config
```xml
<bindingRedirect oldVersion="0.0.0.0-4.0.0.2" newVersion="4.0.0.2" />
```

...but if you downgrade versions to 4.x (the `4.0.0.1` assembly) you'll be messed-up because you won't have `4.0.0.2` around

Maybe this means the best solution here is to keep ScottPlot depending on an older version of System.Drawing.Common (461?) and let people upgrade if/as their other projects need to.

**Comment by swharden** [comment]
> Did you first downgrade Sys.Drawing.Common to 4.7.0? Close VS. Then modify the app config as i did. Still crashes? Edit: i did not delete the binding line, but modified it.

Actually it does work now. I closed VS, deleted the `bin` and `obj` folders, edited App.config to delete the `bindingRedirect` line, then opened the project in Visual Studio and it worked.

I think we've converged on a solution here! 🥳
