### ISSUE TITLE
Plot property Missing in Avalonia - QuickStart Guide.

### ISSUE THREAD

**Issue by jamsoft** [ScottPlot/ScottPlot#1006]
### Your Environment
- ScottPlot Version: 4.0.48
- Operating System:Windows
- Is it a GUI app? What platform? Avalonia

**Indicate what you have tried:**
The [quick start](https://swharden.com/scottplot/quickstart/#avalonia-quickstart) guides uses code like:

```
AvaPlot avaPlot1 = this.Find<AvaPlot>("AvaPlot1");

double[] dataX = new double[] { 1, 2, 3, 4, 5 };
double[] dataY = new double[] { 1, 4, 9, 16, 25 };
avaPlot1.Plot.AddScatter(dataX, dataY);
```

However, the .Plot property doesn't exist and plt doesn't have the `AddScatter` method. Is there an updated sample or guide?

**Comment by StendProg** [comment]
Hi @jamsoft,

There are a lot of API changes in 4.1.
Use 4.0.47 cookbook as a reference.  https://swharden.com/scottplot/cookbooks/4.0.47/#plottypes-scatter-scatter-plot-quickstart
Or upgrade to 4.1 beta.
`avaPlot1.plt.PlotScatter(dataX, dataY)` is that you need.
