### ISSUE TITLE
Is it not possible to style SignalXY plottables?

### ISSUE THREAD

**Issue by breakwinz** [ScottPlot/ScottPlot#1016]
### Your Environment
- ScottPlot Version: 4.1.12
- Operating System: W10
- Is it a GUI app? What platform? Winforms, c#

Is it not possible to style the `SignalXY ` plottables? I have tried both `SignalXY` and `SignalXYConst`

When I set things such a LineStyle, LineWidth. Nothing changes, the only thing I seem to be able to change is the color.

Additionally in the cookbook for SignalXY there are no examples which change the style. Hence my suspicion?

**Comment by StendProg** [comment]
Hi @breakwinz,

A similar question regarding `Signal` has already been discussed
https://github.com/ScottPlot/ScottPlot/issues/929#issuecomment-811150243

Key points:
>The Signals uses a trick

>This trick actually works absolutely correctly only with solid lines that are 1 pixel thick

> I would just advise against using dash lines for drawing Signals. and distinguish them by color

In the case of `Signal`, there is a `LowDensityMode` in which the use of line styles is quite acceptable.
In the case of `SignalXY`, both low and high density are often present in one frame. And they are drawn with one pen.

> When I set things such a LineStyle, LineWidth. Nothing changes, the only thing I seem to be able to change is the color.

The `LineStyle` is hardcoded  as `solid`, but you can still specify the thickness using `LineWidth` (I checked).

`LineStyle` derivered from `Signal` but never used.

If despite all of the above, I could not dissuade you, and you still want to use `LineStyle` for `SignalXY`, let me know, implementation looks like a very simple task.

**Comment by StendProg** [comment]
I maked #1017,

If you don't want to wait until it gets into the release, you can make corrections yourself, there is only one line (You will have to rebuild the package yourself, there is nothing we can do about it.).

**Comment by breakwinz** [comment]
@StendProg  This works great. Thank you
