### ISSUE TITLE
Can not get back to auto tick scaling after ManualTickPositions used 

### ISSUE THREAD

**Issue by Serzl** [ScottPlot/ScottPlot#1019]
- ScottPlot Version: 4.1.13-beta
- WinForms,

When doing manual configuration of X axis (ManualTickPosition and TickLabelStyle) I have faced with the issue of not being able to go back to automatic tick configuration.
Meaning, that when ConfigureManualScale() function is called, configuration of Ticks stays permanent. Subsequent call of ConfigureAutoScale() does not change ticks, grid or the manual labels used.

I have tried to do reconfiguration in multiples ways. The only way I have managed to get it back to somewhat normal is by using:
```cs
F_Plot.Reset()
```
However, that seem to reset plot entirely, including all the color configurations. So does not seems like an appropriate way of doing things.

Perhaps I am missing a particular function that takes care of reconfiguration, or is it some known issue?
Would be glad for any suggestions!

Basic code used:

```cs
// Manually Configure Ticks Position
private void ConfigureManualScale() {
    double[] ticksPos = new double[2] { 1, 2 };
    string[] ticksFreq = new string[2] { "33", "44" };

    F_Plot.Plot.XAxis.ManualTickPositions(ticksPos, ticksFreq);
    F_Plot.Plot.XAxis.TickLabelStyle(rotation: 45, fontSize: 9);
}

// Going Back to Auto Tick Selection (Does Not Works as intended)
private void ConfigureAutoScale() {
    F_Plot.Plot.AxisAuto();
    F_Plot.Plot.XAxis.RecalculateAxisSize();

}
```

**Comment by StendProg** [comment]
Hi @Serzl,

To disable manual tick position, you need to call it again with null arguments:
```c#
  F_Plot.Plot.XAxis.ManualTickPositions(null, null);
```
or you can use `Plot.XTicks()` to on and off manual ticks, it have default null arguments:
```c#
F_Plot.Plot.XTicks(ticksPos, ticksFreq); // enable manual tick positions

F_plot.Plot.XTicks();  // disable manual tick positions

```

**Comment by Serzl** [comment]
Hi @StendProg,

Thank you for a quick reply!
Yours suggested solution worked as intended.

Perhaps it is worthwhile to add a little section or a note in the Cookbook related to disabling manual tick selection?
