### ISSUE TITLE
How to enable engineering notation for tick labels (multiplier notation)

### ISSUE THREAD

**Issue by garyblythe** [ScottPlot/ScottPlot#1026]
The current functionality of the TickLabelNotation is really nice for maximizing graph size and minimizing label space consumption. It would be even nicer, for my use case at least, to have a switch setting to limit the powers to Engineering Notation (i.e., multiples of 3), with the digits limited to > -1000 and < 1000

**Comment by swharden** [comment]
Hi @garyblythe, thanks for the suggestion!

> ticks that are multiples of 3, with the digits limited to > -1000 and < 1000

Do you have an example plot showing this type of notation? It might be helpful at better understanding this use case.

I added this topic to the triaged task list (#1028) and refactoring the tick system and adding new functionality is very high in the list of upcoming projects. However this isn't an immediate focus of active work, so I'll close this issue and follow-up when work on this goal begins.

**Comment by garyblythe** [comment]
Scott,
Thanks for the quick response. It's just a small adaptation to what you're already doing with the TickLabelNotation multiplier parameter, using only powers of 10^3.

![Engineering Notation](https://user-images.githubusercontent.com/27743318/118518359-e5ddfd80-b6ec-11eb-854c-9322b249ec96.png)

**Comment by swharden** [comment]
Gotcha! Actually this was in ScottPlot 4.0 and I'm not sure if it was taken out in 4.1 or what, but I'll look back into this when I work on the tick system (a high priority triaged task #1028)

https://swharden.com/scottplot/cookbooks/4.0.47/#customize-ticks-multiplier-notation

https://swharden.com/scottplot/cookbooks/4.0.47/#customize-ticks-offset-notation

**Comment by swharden** [comment]
lol, actually it's in 4.1 but broken

https://swharden.com/scottplot/cookbooks/4.1.13-beta/category/advanced-axis-features/#multiplier-notation

https://swharden.com/scottplot/cookbooks/4.1.13-beta/category/advanced-axis-features/#offset-notation

I'll take a closer look at this sooner than later to see if I can fix it easily

**Comment by swharden** [comment]
I was mistaken! This is working:

```cs
var plt = new ScottPlot.Plot(400, 300);
plt.AddLine(-1e5, -1e10, 1e5, 1e10);
plt.SaveFig("default.png");
plt.XAxis.TickLabelNotation(multiplier: true);
plt.YAxis.TickLabelNotation(multiplier: true);
plt.SaveFig("multiplier.png");
```

Standard Tick Labels | Multiplier Notation
---|---
![image](https://user-images.githubusercontent.com/4165489/119068357-07234000-b9b2-11eb-9821-7a955d264611.png)|![image](https://user-images.githubusercontent.com/4165489/119068367-0c808a80-b9b2-11eb-81e8-4bbfddecbf55.png)

The cookbook examples are working too, but they're just being demonstrated on one axis, so I overlooked it. I'll modify them to make it more obvious.
