### ISSUE TITLE
add MarkerShape for PlotRadar

### ISSUE THREAD

**Issue by SaeedTaghavi** [ScottPlot/ScottPlot#1031]
there is no feature to add control MarkerShape in PlotRadar!
it would be cool and interesting to add this feature.

**Comment by swharden** [comment]
Hi @SaeedTaghavi, thanks for the suggestion! Do you want to try to implement this and make a pull request?

You can observe how markers are drawn by referencing the scatter plot:
https://github.com/ScottPlot/ScottPlot/blob/0dc97e96470d5858fc85cb7312c1f1dcc3398ad4/src/ScottPlot/Plottable/ScatterPlot.cs#L266-L269

Then modify the radar plot's render method to place markers at the corners similarly:
https://github.com/ScottPlot/ScottPlot/blob/0dc97e96470d5858fc85cb7312c1f1dcc3398ad4/src/ScottPlot/Plottable/RadarPlot.cs#L150-L244

Then you can show-off this functionality by demonstrating it in a cookbook recipe like this:
https://github.com/ScottPlot/ScottPlot/blob/0dc97e96470d5858fc85cb7312c1f1dcc3398ad4/src/cookbook/ScottPlot.Cookbook/Recipes/Plottable/Radar.cs#L7-L29

If you're interested in contributing I'd be happy to help! If not I'll probably close this issue but add it to the triage list (#1028) and possible open it back up again in the future when I have a little more time.

**Comment by SaeedTaghavi** [comment]
tank you for your reply @swharden  
I love to implement this .
Thank you for the explanation.

**Comment by swharden** [comment]
> I love to implement this

Sounds great! I'll keep an eye out for a pull request, and feel free to reach out if you have any questions 👍 

I'll leave this issue open for now, but if after a while there isn't any movement I'll close it and add it to the triage list (#1028)
