### ISSUE TITLE
Link vertical draggable axis

### ISSUE THREAD

**Issue by EmanuelFeru** [ScottPlot/ScottPlot#1032]
### Your Environment
- ScottPlot Version: 4.1.13 Beta
- Operating System: W10
- GUI app WinForms

**Questions:**
* How to link 2 vertical lines in 2 different plots?
* How to dynamically display the X coordinate (ideally I want the current `index` in the data and display the Y data value)?

**What I want to achieve:**
![image](https://user-images.githubusercontent.com/24780745/118472074-bb01a280-b708-11eb-9d23-0505b96c1847.png)

**Comment by EmanuelFeru** [comment]
I implemented the code below using `.Dragged` Handle
Positive:
* it works, the values are updated correctly

Negative:
* Because I had to use `formsPlot2.Render();` The line for the 2nd plot suffer responsiveness, which means it lags behind the 1st line that drives it.
* If I don't use `formsPlot2.Render();`, then the 2nd plot is not updated and Red line does not move until I interract with the 2nd plot.

```cs
        ScottPlot.Plottable.VLine hLine1;
        ScottPlot.Plottable.VLine hLine2;

        // Add Draggable Vertical Axis Line
        hLine1 = formsPlot1.Plot.AddVerticalLine(1000, color: Color.Red);
        hLine1.DragEnabled = true;
        hLine1.Dragged += OnAxisDragged;

        hLine2 = formsPlot2.Plot.AddVerticalLine(1000, color: Color.Red);
        hLine2.DragEnabled = true;

        private void OnAxisDragged(object sender, EventArgs e)
        {
            label1.Text = "Line position = " + hLine1.X.ToString();
            hLine2.DragTo(hLine1.X, 0, true);
            formsPlot2.Render();
        }
```

**Comment by StendProg** [comment]
Hi @EmanuelFeru,

> I implemented the code below using .Dragged Event Handler

I would advise you to make the next replacement so that the 2nd Plot does not trigger an extra event when it is not needed.
```c#
    label1.Text = "Line position = " + hLine1.X.ToString();

    // hLine2.DragTo(hLine1.X, 0, true);
    hLine2.X = hLine1.X;

    formsPlot2.Render();
```

You can try `formsPlot2.Render(skipIfCurrentlyRendering: true)` to reduce lags.

> Is it possible to only Render the vertical line

Actually not, I've experimented with this, but it hasn't been updated for a long time. #687

> hLine1.X.ToString() works but for some reason hLine1.XAxisIndex.ToString() returns 0. I was expecting to return the index. Any idea why?

This is Axis index(primary, secondary etc) not index in signal. 
Nobody except you knows how the signal and the vertical line correlate, so you will have to calculate the index in the signal manually.

**Comment by EmanuelFeru** [comment]
@StendProg thank you for the quick reply. I confirm that with:
```cs
formsPlot2.Render(skipIfCurrentlyRendering: true)
```
it works better. There is still some lag if I do abrupt movements or if I put the plots in full screen, but clearly less than before. I believe that it is possible to improve the user experience here, since it is only a line to render. For now I will continue with your suggestion. 

If there are more sugeestions to improve the user experience please let me know. Thanks again.

**Comment by EmanuelFeru** [comment]
Just some aditional remarks:
* because the `formsPlot2` skips some rendering, sometimes the Red line in Plot2 get's stuck, then if I move the Plot1 line it recovers and gets in sync with Plot1 red line.
* I also tryied with the Anti-aliasing disabled, but I get the similar behavior
```cs
formsPlot1.Configuration.Quality = ScottPlot.Control.QualityMode.Low;   // Disable Anti-aliasing
formsPlot1.Configuration.Quality = ScottPlot.Control.QualityMode.Low;   // Disable Anti-aliasing
```

**Comment by StendProg** [comment]
If I understand everything correctly, you have a relatively fast first plot, and a relatively slow second.
You want to drag the vertical line on the first plot and not have additional delays on it despite being linked to the second.

For this case, I have a solution:
1. Enable RenderQueue in init section of your app
```c#
formsPlot2.Configuration.EnableRenderQueue = true;
```
2. Replace `formsPlot2.Render()` with `formsPlot2.RenderLowThenImmediateHighQuality()`

Updates of the second plot will occur asynchronously with a delay, but there's nothing you can do about it, but there are no lags when interacting with 1 plot.
It would be more correct to call `RenderHighQuality()`, but at the moment the `FormsPlot` has no forwarding to existed backend method.
![FastLink](https://user-images.githubusercontent.com/53831487/118516758-48f88000-b73f-11eb-839f-93f8560c7042.gif)

**Comment by EmanuelFeru** [comment]
I will check your suggestions soon and let you know.

To clarify a bit more what I want to achieve is to have the 2  Red vertical lines in sync. I want to eventually move either the Plot1 line or the Plot2 line and the other line to be in sync (similar to Link axis demo #1025). I want to use this to display the Y values for all signals in Plot1 and Plot2 corresponding to where the Red line is.

**Comment by EmanuelFeru** [comment]
For some reason the `formsPlot2.Configuration.EnableRenderQueue` is not available for me. I use the 4.1.13 Beta pre-release.
![image](https://user-images.githubusercontent.com/24780745/118524197-2f0a6d80-b73e-11eb-9a34-dc1448fcaad2.png)

With `formsPlot2.RenderLowThenImmediateHighQuality()` I get more or less same effect as with normal `formsPlot2.Render()`.
https://user-images.githubusercontent.com/24780745/118525595-a5f43600-b73f-11eb-8072-2e92a000f38a.mov

**Comment by StendProg** [comment]
My bad:
```c#
  formsPlot2.Configuration.UseRenderQueue = true;
```

**Comment by EmanuelFeru** [comment]
I corrected it. It works ok when I move slowly, but when I move fast the Plot2 red line just jumps from Old position to End position. I guess it just doesn't have time to refresh in between. See here a quick recording:

https://user-images.githubusercontent.com/24780745/118527429-9544bf80-b741-11eb-89bb-dc7abb26790f.mov

**Comment by StendProg** [comment]
Yes, that's right, you will receive low quality updates at the highest possible speed, and a guaranteed high-quality render at the end, which always corresponds to exactly the last position. First plot lag is determined only by the lag of the very first plot, and no additions due to the linked second one. You can try enable RenderQueue ( formsPlot1.Configuration.UseRenderQueue = true;) for the first plot too. This will make the interaction a little more pleasant.

I maked #1034. which adds additional methods, you can try fiddling with them when they are released.

**Comment by EmanuelFeru** [comment]
With `formsPlot1.Configuration.UseRenderQueue = true;` is a bit better. However, best effect I had it with:
`formsPlot2.Render(skipIfCurrentlyRendering: true);`


> I maked #1034. which adds additional methods, you can try fiddling with them when they are released.

I have seen your pull request. I will try to play a bit more when is available. 

Thanks a lot for your help. What do you suggest, should we close this topic? For me it is ok for now to continue. I will actually add a Red line also to the 3rd Plot and link it with the 2 other :) I will see how it goes.

**Comment by EmanuelFeru** [comment]
I re-opened the Question just to share my final result. Then I will close it.
This is my code to the 3 vertical axes in 3 plots:
```cs
namespace DataViewer
{
    public partial class Form1 : Form
    {

        readonly FormsPlot[] FormsPlots;    // to link plots

        readonly ScottPlot.Plottable.VLine[] vLines;    // to link plots
        ScottPlot.Plottable.VLine vLine1;
        ScottPlot.Plottable.VLine vLine2;
        ScottPlot.Plottable.VLine vLine3;
        double Ts = 0.5;

        public Form1()
        {
            InitializeComponent();

            // Generate some random Y data
            Random rand = new Random(0);
            int pointCount = 5_000;
            double[] ys1;
            double[] ys2;

            // formsPlot1
            ys1 = ScottPlot.DataGen.RandomWalk(rand, pointCount);
            ys2 = ScottPlot.DataGen.RandomWalk(rand, pointCount);
            formsPlot1.Configuration.Quality = ScottPlot.Control.QualityMode.Low;   // Disable Anti-aliasing
            formsPlot1.Configuration.UseRenderQueue = true;                         // Use Queue render: needed for Red Vertical syncronization
            formsPlot1.Reset();
            formsPlot1.Plot.AddSignal(ys1, 1/Ts);
            formsPlot1.Plot.AddSignal(ys2, 1/Ts);
            formsPlot1.Plot.AxisAuto();
            formsPlot1.Render();

            // formsPlot2
            ys1 = ScottPlot.DataGen.RandomWalk(rand, pointCount);
            ys2 = ScottPlot.DataGen.RandomWalk(rand, pointCount);
            formsPlot2.Configuration.Quality = ScottPlot.Control.QualityMode.Low;
            formsPlot2.Configuration.UseRenderQueue = true;
            formsPlot2.Reset();
            formsPlot2.Plot.AddSignal(ys1, 1/Ts);
            formsPlot2.Plot.AddSignal(ys2, 1/Ts);
            formsPlot2.Plot.AxisAuto();
            formsPlot2.Render();

            // formsPlot3
            ys1 = ScottPlot.DataGen.RandomWalk(rand, pointCount);
            ys2 = ScottPlot.DataGen.RandomWalk(rand, pointCount);
            formsPlot3.Configuration.Quality = ScottPlot.Control.QualityMode.Low;
            formsPlot3.Configuration.UseRenderQueue = true;
            formsPlot3.Reset();
            formsPlot3.Plot.AddSignal(ys1, 1 / Ts);
            formsPlot3.Plot.AddSignal(ys2, 1 / Ts);
            formsPlot3.Plot.AxisAuto();
            formsPlot3.Render();


            // Link Axes: Create a list of plot controls we can easily iterate through later
            FormsPlots = new FormsPlot[] { formsPlot1, formsPlot2, formsPlot3 };
            foreach (var fp in FormsPlots)
                fp.AxesChanged += OnAxesChanged;

            // Add and Link Draggable Vertical Axis Line            
            vLine1 = formsPlot1.Plot.AddVerticalLine(5, color: Color.Red);
            vLine1.DragEnabled = true;

            vLine2 = formsPlot2.Plot.AddVerticalLine(5, color: Color.Red);
            vLine2.DragEnabled = true;

            vLine3 = formsPlot3.Plot.AddVerticalLine(5, color: Color.Red);
            vLine3.DragEnabled = true;

            vLines = new ScottPlot.Plottable.VLine[] { vLine1, vLine2, vLine3 };
            foreach (var vl in vLines)
                vl.Dragged += OnAxisDragged;

        }

        private void OnAxisDragged(object sender, EventArgs e)
        {
            ScottPlot.Plottable.VLine changed_Line = (ScottPlot.Plottable.VLine)sender;

            var FormsPlotAndvLines = FormsPlots.Zip(vLines, (fp, vl) => new { plots = fp, lines = vl });
            var newPosition = changed_Line.X;

            int idx;
            idx = (int)(newPosition / Ts);
            label1.Text = "Line index = " + idx.ToString();
            listViewSignals.Items[0].SubItems[1].Text = idx.ToString();

            foreach (var item in FormsPlotAndvLines)
            {
                if (item.lines == changed_Line)
                    continue;

                item.lines.X = newPosition;
                item.plots.RenderLowThenImmediateHighQuality();
            }
        }

        // Link axes method
        private void OnAxesChanged(object sender, EventArgs e)
        {
            FormsPlot changedPlot = (FormsPlot)sender;
            var newAxisLimits = changedPlot.Plot.GetAxisLimits();
            
            foreach (var fp in FormsPlots)
            {
                if (fp == changedPlot)
                    continue;

                // disable events briefly to avoid an infinite loop
                fp.Configuration.AxesChangedEventEnabled = false;
                fp.Plot.SetAxisLimits(newAxisLimits.XMin, newAxisLimits.XMax);
                fp.Render();
                fp.Configuration.AxesChangedEventEnabled = true;
            }            
        }
```

And here is the result:

Uploading Rec 0001.mp4…

I am happy with the result. @StendProg at the end I went with your last proposal because it turned out to be the best, meaning the line doesn't get stuck because some refreshes are skipped. So, I rather prefer that the 2 lines that follow lag a bit behind the mouse and lines that drives them (see video) but at the end gets to where the mouse is. 

If you have a suggestions or remarks even regarding implementation let me know.

**Comment by StendProg** [comment]
Hi @EmanuelFeru,
Thanks for share, i played a bit with your project:
1. Enable antialiasing back for each plot 
```c#
    // formsPlot1.Configuration.Quality = ScottPlot.Control.QualityMode.Low;   // Disable Anti-aliasing
```
2. Use `RenderDelayedHighQuality();` from #1034 for both `OnAxesDragged` and `OnAxesChanged` handlers
3. Set `20_000_000` points count for each signal instead of `5_000`.
4. Use `SignalConst` instead of `Signal`
5. Run standalone .net 5.0 Release version.
6. Run it full screen on 1920x1080.

It feels very smoth, but you can see a bit visual lag:

![FastLink](https://user-images.githubusercontent.com/53831487/118674767-b9b4a080-b802-11eb-9264-b18bc38e2bdc.gif)

**Comment by EmanuelFeru** [comment]
Wow the vertical lines in your case are almost instantaneous. I have to try it. But to understand correctly I don't have yet the  ` RenderDelayedHighQuality(`, right?

**Comment by StendProg** [comment]
Yes you are right, it is not yet available through the nuget package. You can build yours from source, or just wait, I think it will get into the next release in one form or another.

I tried to point out the key points that greatly affect performance. 
Debug mode slows everything down by 2 times, .NET 5.0 is faster than the .NET framework. `SignalConst` is absolutely not afraid of tens of millions of points.

**Comment by EmanuelFeru** [comment]
* I agree, I am considering to use `AddSignalConst` in case data is not changing
* I tryied building Release version (follwing the link below), and for me behaves exactly the same as Debug version
https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-building-an-application?view=vs-2019
* I am not sure how to check it but I think I am already using .NET 5.0
![image](https://user-images.githubusercontent.com/24780745/118683670-dd2b1b80-b801-11eb-9593-8ef84d8c2b78.png)
* could be that also my laptop is not the fastest available

**Comment by EmanuelFeru** [comment]
@swharden @StendProg + other contributors, I don't know what magic you guys did in the 4.1.14, I changed the old line from:
`item.fplot.RenderLowThenImmediateHighQuality();` for linking Verical Line Axis to
```cs
item.fplot.RenderRequest();
```
And it works amazing! Much better and smotther. See below the video, Thank you guys!!

https://user-images.githubusercontent.com/24780745/119254677-ef1d0d80-bbb7-11eb-9eed-3407b290d731.mp4

**Comment by StendProg** [comment]
Hi @EmanuelFeru,

I am very glad that we managed to solve the problem you described.
I wanted to write off that the fix got into the release, but it looks like you got ahead of me.

> I don't know what magic you guys did in the 4.1.14

This is in fact the same `RenderDelayedHighQuality();`, but wrapped in a nicer API.

This fix appeared directly thanks to you, it never occurred to me that the `RenderQueue` maded for internal needs could also be very useful for users handlers.
