### ISSUE TITLE
padding and data area in extremely small FormsPlot controls

### ISSUE THREAD

**Issue by WangYuXi-best** [ScottPlot/ScottPlot#1033]
I Create 32 ScottPlots in Winforms. I can open any by clicking mouse right. But I can't see any plotting data.

The following figure shows the winforms.
![image-20210517215250544](https://user-images.githubusercontent.com/53853502/118503247-0a71be00-b75d-11eb-9122-8f4df299469b.png)
I can open any by clicking the mouse right.
![image-20210517215551705](https://user-images.githubusercontent.com/53853502/118503361-24130580-b75d-11eb-83f8-310acad4abcc.png)

![image-20210517215637161](https://user-images.githubusercontent.com/53853502/118503377-270df600-b75d-11eb-894a-4ef943b35451.png)
Is there a limited size for ScottPlot?
ScottPlot Version: 4.0.48

My computer: Windows 10

**Comment by swharden** [comment]
> Is there a limited size for ScottPlot?

No, but there is some padding around the edges of the plots so maybe the data area isn't being shown.

What happens if you display only 5 plots? What about 10? Does this make it more obvious what the problem is?

Is the problem improved if you run `formsPlot1.plt.Frameless()`?

More ideas may be found on https://swharden.com/scottplot/faq/padding

**Comment by WangYuXi-best** [comment]
Hello, swharden. I can see the plots by displaying 10 plots. I think you are right. I have a question about the `formsPlot1.plt.Frameless()`. I can't find the code in the version of 4.0.48. Is it Updated?

**Comment by swharden** [comment]
Hi @WangYuXi-best, I'm glad you figured it out!

the `Framelss()` option is in ScottPlot 4.1 which is available on NuGet _if you enable searching for pre-release packages_

In ScottPlot 4.0 you can do something like this https://swharden.com/scottplot/cookbooks/4.0.47/#customize-figure-no-padding

```cs
plt.Ticks(false, false);
plt.Frame(false);
plt.TightenLayout(padding: 0);
```

**Comment by WangYuXi-best** [comment]
I have done it for my project. It displays the plot which I ask the question.

**Comment by swharden** [comment]
I'd expect this to work on ScottPlot 4.0...

```cs
formsPlot1.plt.Ticks(false, false);
formsPlot1.plt.Frame(false);
formsPlot1.plt.TightenLayout(padding: 0);
formsPlot1.Render();
```

Have you tried calling `Render()` to force a redraw after making the changes to the layout?

**Comment by WangYuXi-best** [comment]
Yes, I did. Here my code for doing it . 
     
           TableLayoutPanel` tlp = new TableLayoutPanel();
            tlp.Dock = DockStyle.Fill;
            splitContainer1.Panel2.Controls.Add(tlp);
            tlp.ColumnCount = 2;
            tlp.RowCount = 32;
            tlp.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 60f));
            tlp.ColumnStyles.Add(new ColumnStyle(SizeType.Percent));
            for (int i = 0; i < 32; i++)
            {
                tlp.RowStyles.Add(new RowStyle(SizeType.Percent, tlp.Width * 0.02f));
                tlp.CellBorderStyle = TableLayoutPanelCellBorderStyle.Inset;
                Button btn = new Button();
                btn.Text = "btn" + i.ToString();
                btn.Dock = DockStyle.Fill;
                btns.Add(btn);
                tlp.Controls.Add(btn, 0, i);
                FormsPlot frmplot = new FormsPlot();
                frmplot.Dock = DockStyle.Fill;
                frmplot.plt.Ticks(false, false);
                frmplot.plt.Frame(false);
                frmplot.plt.Grid(false);
                frmplot.plt.TightenLayout(padding: 0);
                frmplot.plt.AxisBounds(minX: -10, maxX: 10020);
                frmplot.Configure(recalculateLayoutOnMouseUp: false, lockHorizontalAxis: true, lockVerticalAxis: true);
                vLine = frmplot.plt.PlotVLine(0, Color.Red, 3);
                for (int j = 0; j < 10; j++)
                {
                    frmplot.plt.PlotVLine(j * 1000, color: Color.Black, lineStyle: LineStyle.DashDotDot);
                }
                LiveData.Add(new double[10000]);
                signals.Add(frmplot.plt.PlotSignal(LiveData[i]));
                frmplots.Add(frmplot);
                frmplot.Render();
                tlp.Controls.Add(frmplot, 1, i);
            }
            for (int i = 0; i < frmplots.Count; i++)
            {
                frmplots[i].Render();
            }

**Comment by swharden** [comment]
This isn't perfect (the last row of the table layout is too big), but it's close. I'm using ScottPlot 4.1 but 4.0 should be extremely similar.

```cs
int plotCount = 32;
var FormsPlots = new ScottPlot.FormsPlot[plotCount];

var tlp = new TableLayoutPanel()
{
    Dock = DockStyle.Fill,
    ColumnCount = 2,
    RowCount = plotCount,
    CellBorderStyle = TableLayoutPanelCellBorderStyle.Inset,
};
tlp.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 60f));
tlp.ColumnStyles.Add(new ColumnStyle(SizeType.Percent));

for (int i = 0; i < plotCount; i++)
{
    var rowStyle = new RowStyle(SizeType.Percent, 100f / plotCount);
    tlp.RowStyles.Add(rowStyle);

    var btn = new Button()
    {
        Text = $"Btn {i}",
        Dock = DockStyle.Fill,
        Margin = new Padding(0), // eliminate default space
        Padding = new Padding(0), // eliminate default space
    };
    tlp.Controls.Add(btn, 0, i);

    var frmplot = new ScottPlot.FormsPlot()
    {
        Dock = DockStyle.Fill,
        Margin = new Padding(0), // eliminate default space
    };
    frmplot.Plot.Frameless();
    frmplot.Plot.AddSignal(ScottPlot.DataGen.Sin(51));
    tlp.Controls.Add(frmplot, 1, i);
    FormsPlots[i] = frmplot;
}

Controls.Add(tlp);
```

![image](https://user-images.githubusercontent.com/4165489/118587776-2c723d00-b76b-11eb-9a37-91b7293d91bc.png)

Hopefully it gets you un-stuck!

**Comment by WangYuXi-best** [comment]
Amazingly! I am using ScottPlot 4.1 which has a better plot. But 4.0 has a worse plot.
ScottPlot4.1:
![image](https://user-images.githubusercontent.com/53853502/118593377-29fafc00-b7da-11eb-8b8e-3bcab900dd3e.png)
ScottPlot4.0:
![image](https://user-images.githubusercontent.com/53853502/118593918-1dc36e80-b7db-11eb-8774-bc810bf41e02.png)
The code for ScottPlot4.1 is the same as you , but for ScottPlot 4.0 has some difference.
             
               frmplot.plt.Ticks(false, false);
                frmplot.plt.Frame(false);
                frmplot.plt.TightenLayout(padding: 0);
                //frmplot.Plot.Frameless();
                frmplot.plt.PlotSignal(ScottPlot.DataGen.Sin(51));
                tlp.Controls.Add(frmplot, 1, i);
                FormsPlots[i] = frmplot;
                frmplot.Render();
