### ISSUE TITLE
Plot 'enum' signals

### ISSUE THREAD

**Issue by EmanuelFeru** [ScottPlot/ScottPlot#1035]
**What can we do to make ScottPlot better?**
It would be great to be able to plot `enum` data types. Basically, instead of ploting `double` on the Y axis to plot `enum` as a function of time. For example:
![image](https://user-images.githubusercontent.com/24780745/118722949-10cf6b00-b82d-11eb-8525-15ce75ded116.png)

where
```cs
enum State
{
    INACTIVE = 0,
    ACTIVE = 1,
    ERROR = 2
}
```

This is useful when visualizing states, where the meaning behind the signal values is easier to visualize than the value itself. How complex would be to implement something like this?

Thank you!

**Comment by swharden** [comment]
> How complex would be to implement something like this?

With some creative styling and leveraging the `AddScatterStep` command it looks like we can achieve this effect with the existing package 😎 

This example uses ScottPlot 4.1 beta (currently marked as pre-release)

```cs
State[] data = {
    State.Inactive,
    State.Active,
    State.Error,
    State.Inactive,
    State.Inactive
};
double[] dataValues = data.Select(x => (double)x).ToArray();
double[] dataTimes = ScottPlot.DataGen.Consecutive(data.Length);
string[] enumNames = Enum.GetNames(typeof(State));
double[] enumValues = Enum.GetValues(typeof(State)).Cast<State>().Select(x => (double)x).ToArray();

var plt = new ScottPlot.Plot(400, 200);
plt.AddScatterStep(
    xs: dataTimes,
    ys: dataValues,
    color: System.Drawing.Color.Red,
    lineWidth: 2);
plt.YTicks(positions: enumValues, labels: enumNames);
plt.XLabel("Time");
plt.YLabel("State");
plt.Grid(enable: false);
plt.Frame(top: false, right: false);
plt.SaveFig("enum.png", scale: 2);
```

![image](https://user-images.githubusercontent.com/4165489/118733011-8590ae00-b809-11eb-9034-8577c8d5e1e4.png)

I'm glad we were able to figure this one out! Enjoy using ScottPlot 🚀
