### ISSUE TITLE
Refactor: System.Drawing → Maui.Graphics

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1036]
* September, 2021: [System.Drawing.Common only supported on Windows](https://aka.ms/systemdrawingnonwindows)
* July, 2021: [Make System.Drawing.Common only supported on Windows](https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md)

Microsoft is sunsetting cross-platform support for `System.Drawing.Common` in .NET 6. This will be highly disruptive since ScottPlot currently uses `System.Drawing` extensively for rendering graphics.

This issue will track progress toward migrating to an alternative render system. This will likely be `Microsoft.Maui.Graphics` (which works on all platforms, not just in MAUI apps). `System.Drawing` will be totally removed from ScottPlot. 

This change will be associated with a major version increase (ScottPlot 5.0)

Related: #1413, #1431

**Comment by bclehmann** [comment]
> It would be nice if console applications could reference colors without having to explicitly install/use the System.Drawing.Common package.

Don't console apps already have to include System.Drawing.Common in order to use ScottPlot?

That said, I think this is a good plan, especially looking towards the future. It would be nice if it could have functions for decoding hex colour strings (i.e. `"#ff0000ff"`), as that's one of the things I want most in System.Drawing.Common, but that's just a wishlist, no pressure.

It would also be helpful to have a healthy dictionary of "known colours", whether that's just the predefined colours in System.Drawing.Common, or those in CSS, or those in Skia. For what it's worth, I think they all have the same predefined colours as it is.

**Comment by swharden** [comment]
> Don't console apps already have to include System.Drawing.Common in order to use ScottPlot?

I don't think so... I think you can make a new console project and just use NuGet to install ScottPlot, and it works as long as you never pass a System.Drawing.Color as an argument.

> nice if it could have functions for decoding hex colour strings

Yes! Quite a few similar helper functions would be very useful.

> one of the things I want most in System.Drawing.Common
```cs
System.Drawing.Color myColor = System.Drawing.ColorTranslator.FromHtml("#ff0000ff");
```

> dictionary of "known colours"
* System.Drawing: http://www.flounder.com/csharp_color_table.htm
* CSS: https://css-tricks.com/snippets/css/named-colors-and-hex-equivalents/
* SkiaSharp looks like the same list as System.Drawing https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skcolors?view=skiasharp-2.80.2

### Namespace Collision?

If we name the struct/class `Color`, it may collide if the user uses both `System.Drawing` and `ScottPlot`

If/when this is implemented though, it may be a pretty big API change.

Maybe both birds could be killed with one stone though - eliminating the System.Drawing dependency would allow the user to just use ScottPlot, and if we use the name `Color` it wouldn't require changes to existing code (well, except that code that passes `System.Drawing.Color.Red` instead of `Color.Red`). 

I don't think it's a good idea to maintain tons of overloads to accomodate both types of arguments.

This problem may not be easy to solve... Perhaps more frequent major releases (ScottPlot 5) would make it more acceptable to make top-level breaking changes like this. I'm not opposed to major versions with a moderate release cadence, allowing this flexibility.

Lots to consider here!

**Comment by swharden** [comment]
Requiring everyone to stop passing `System.Drawing.Color` and instead start passing `ScottPlot.Drawing.Color` is a pretty big change. 

I added this topic to the triage list #1028 and will consider this for ScottPlot 5 when I work toward cutting the System.Drawing.Common dependency.

**Comment by swharden** [comment]
It looks like future versions of .NET are working toward standardizing color objects, so we can just use them when they come
* https://github.com/dotnet/runtime/issues/32418
* https://github.com/dotnet/Microsoft.Maui.Graphics/issues/48

`Microsoft.Maui.Graphics` is especially interesting... It has `Maui` in the namespace, but it should work anywhere (WinForms, etc). It looks to be a common API that lets you draw using multiple rendering systems (GDI, SkiaSharp, etc.)

**Comment by greatawesome** [comment]
Also relevant is this: 

[Make System.Drawing.Common only supported on Windows](https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md)

System.Drawing.Common on non-Windows platforms is a dead end as of this year.

Maui.Graphics may end up being the MS replacement. For replacing System.Drawing, I've had success using the Drawing functionality from [Eto.Forms](https://github.com/picoe/Eto). The [Eto.Drawing](https://github.com/picoe/Eto/tree/develop/src/Eto/Drawing) API is similar enough to System.Drawing that it makes porting easy, and it uses native drawing underneath. But it isn't as full featured as System.Drawing, and it wouldn't open up as many target platforms/frameworks as something like Skia or Maui.Graphics would.

**Comment by bclehmann** [comment]
> System.Drawing.Common on non-Windows platforms is a dead end as of this year.

Well, that's a big change, maybe #1028 should have priorities adjusted?

As for Eto.Drawing, I'm not sure that we want to ship such a large dependency just for a small part of it, even ignoring the feature-parity discussion. The ease of porting argument is intriguing, although I wonder if Maui.Graphics would share that. Maui.Graphics isn't mature yet and does not encourage its use, but that presumably would change when .NET 6 drops.

This makes me think that as it stands now, our best option is still Skia. We have until November 2022 until Microsoft fully pulls the plug, and I think that there will probably be less-than-official adapters for System.Drawing.Common. Perhaps by whatever time we start moving from GDI+ there will be other good options.

**Comment by zii-dmg** [comment]
No need to replace System.Drawing.Color. It is not in System.Drawing.Common, not depends on GDI+ and it is cross platform.
[Docs](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.color?view=net-5.0) and [source code](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Drawing.Primitives/src/System/Drawing/Color.cs) says Color type is in System.Drawing.Primitives.dll.

**Comment by bclehmann** [comment]
Aye, but we need to ditch System.Drawing.Common anyways. So it makes sense to either use what the new library uses (e.g. SkiaSharp uses `SKColor`), or to create our own colour abstractions so that CLI applications don't need a (direct) dependency on whichever graphics library we choose.

Also, it's kinda weird to move to Skia (or whichever we do decide to move to) and then create code to adapt System.Drawing colours to Skia colours. Even though we technically could.

**Comment by greatawesome** [comment]
The main problem with Skia is the large native dependency on some platforms.  The benefit is that it has good performance and wide platform support.

One managed alternative would be ImageSharp.

Oxyplot has the ability to use a few different back-ends (including Skia and ImageSharp), so you could go that route. It might mean creating an abstraction over multiple back-ends, which essentially creates yet another drawing API.

The nice thing about Maui.Graphics is that they'd provide that intermediate API for you, while supporting a wide mix of back-ends and front end views. Biggest criticism I've head is that they're creating yet another graphics API when there were already a lot of .NET APIs out there. Its long term viability will depend on how well it is adopted.

Some of the community might even stick with System.Drawing after MS tries to sunset it. The main reason System.Drawing.Common exists in the first place is widespread demand for it. Before MS created an official version, the CoreCompat folks were already providing much the same thing. Even if the community doesn't keep a fork going, the version Microsoft releases this year will be available for quite a while. It probably isn't an immediate rush to get away from it, but it makes sense for it to be on the radar.

**Comment by swharden** [comment]
Hi everyone! Wow, this is a very important discussion.

I'll re-open this issue so we can track this topic while I figure out the best way to proceed. There's a lot to study here. This is important but not moving super fast, so I'll still spend the immediate future closing-out some of the lingering issues/PRs and continue to research how to proceed for the long term.

It's been a long term goal to explore other rendering systems as alternatives to System.Drawing.Common, so this may be a great indication that now's a good time to start working in that direction. If nothing else, it may be time to prioritize abstracting the System.Drawing dependency so this change will be easier to make in the future.

ImageSharp would be my preferred option (I really like the idea of using a .NET package that targets .NET Standard) but the last time I tried to use ImageSharp is was extremely slow at drawing anti-aliased lines, preventing mouse-interactive plots (one of ScottPlot's best features!). It looks like they've put a lot of work into ImageSharp since then though, so I look forward to evaluating that again and perhaps performance has improved.

I'm really crossing my fingers for Maui.Graphics... I hope this decision gets easier to make as that project matures! It seems it's too early to evaluate where that will land.

**Comment by swharden** [comment]
After looking into this deeper and thinking about it some more, here are my thoughts:

**When the time is right I'll lean away from `System.Drawing` and toward SkiaSharp by way of `Microsoft.Maui.Graphics.Skia`.** Skia is indeed large, but it is very performant, and high performance mouse-interactive plotting is ScottPlot's biggest strength over similar free libraries, so I'd like to prioritize performance when making this decision. Skia and OpenGL has not always been easy to set-up though (e.g., 32-bit vs 64-bit project issues). I am hoping the official support, Skia's wide use due to inclusion in Maui.Graphics, and the release of Visual Studio 2022 (with improved 64-bit support) will all combine to smooth some of SkiaSharp's rough edges and improve usability and developer experience for Skia-based controls.

**This will be a pretty big refactor, so a "feature freeze" may be required closer to the release of .NET 6 (this November)** to make it easier for me to move everything over to an abstract graphics system. Incrementing the major version number seems appropriate, and this may also be an opportunity to drop .NET Framework support. The possibility of forking the project into a new package entirely (named QuickPlot?) shouldn't be overlooked, especially if the `System.Drawing.CoreCompat` community will figure out how to continue to support modern .NET versions. The architectural strategies for all of this are interesting to contemplate, but I'll try to push-off those decisions until I make more progress clearing-out smaller open issues.

**Comment by bclehmann** [comment]
I think forking the repository is probably a bad idea, as all of the traffic, answered questions and links that ScottPlot has will need to be rebuilt, while we won't achieve anything that we wouldn't get from a new branch.

LiveCharts has recently created a new repository (idk if it's a fork or not) for version 2, so you could take a look and see what kind of hit to contributions or usage you might expect, although it's worth noting that v2 is still in beta, and v1 has been inactive for years. Still, ScottPlot may well fare worse as LiveCharts has substantially more users

**Comment by swharden** [comment]
> I think forking the repository is probably a bad idea, as all of the traffic, answered questions and links that ScottPlot has will need to be rebuilt, while we won't achieve anything that we wouldn't get from a new branch.

Excellent points! The argument _for_ forking a project is that the Maui.Graphics and System.Drawing projects would become fundamentally different libraries and no longer belong together. I don't think this is the case, and although Google would eventually catch-up you're right that the issues and discussions here are highly valuable and not worth leaving behind. Thanks for your feedback!

> LiveCharts has recently created a new repository

Whoa I did not see this until now! lol @ at the coincidence of the discussion - they just forked their project to change back-end rendering systems to SkiaSharp 🙃 

* old project: https://github.com/Live-Charts/Live-Charts
* new project: https://github.com/beto-rodriguez/LiveCharts2

I suspect they will continue to focus on things like chart appearance and animation over high density data display, but reviewing their project in detail (especially their user controls) may help provide insights into how to migrate ScottPlot toward Maui.Graphics / SkiaSharp (#1036)

**Comment by EmanuelFeru** [comment]
Nice to see the discussions on the Graphics to be used for future ScottPlot. Just as a short feedback, I agree that user interactivity even with many points is the strong point of ScotPlot, that is what made me choose it and I don't regret it. Going to a hardware accelerated renderer will really boost it at the level that any performance changes will be felt from user perspective. So, looking forward to it.

**Comment by EmanuelFeru** [comment]
I just found a tool used by comma.ai to plot things, it's called PlotJuggler: https://github.com/facontidavide/PlotJuggler
Any idea what engine is it using?

**Comment by bclehmann** [comment]
It uses Qt5. I wouldn't try to move to Qt, the bindings from C# are not amazing and its plotting capabilities are rather limited as it's supposed to be an entire UI framework. Qt does provide QPainter, as well as a 3D graphics API, so we wouldn't have to use `qwt_plot` and friends. Still, it's a bit much to choose a whole UI framework just for how it handles graphics (which is built on OpenGL anyways).

Plus I think ScottPlot is more valuable if it is vendor-neutral, most UI frameworks don't necessarily play nice when mixed with others. Which is especially important when almost no one uses Qt from C#.

**Comment by EmanuelFeru** [comment]
For curiosity, I gave it a try. The interactivity is ok, the grid is too dense in my opinion, and there is a strange effect when panning, like in this video:
https://youtu.be/DgcMeTpHZnE
Overall is ok, from speed point of view seems like in the same range with ScottPlot. I personally like more the mouse interaction in Scottplot.
Going to Maui graphics with hardware acceleration would most probably be superior to qt5 (if what I tested today is the capability of qt5).

**Comment by swharden** [comment]
## PlotJuggler and qwt_plot

Thanks for mentioning PlotJuggler - I hadn't seen it before! Also, wow starchart.cc is cool I hadn't seen that before either: https://starchart.cc/scottplot/scottplot

I have a little experience from several years ago using `qwt_plot` and I remember being impressed with how fast it was! If I recall they had left-click-drag and right-click-zoom which is was inspired the default ScottPlot behavior.

## OpenGL

> Qt is ... built on OpenGL anyways

Hopefully Maui Graphics / Skia will be an easy road toward cross-platform support for OpenGL 🤞 

## Qt is GPL/LGPL

https://doc.qt.io/qt-5/licensing.html I think this means if you use it in your application you have to open-source your app unless you pay for a commercial Qt license ☠️ This is one advantage of using .NET Core and ScottPlot - both are MIT licensed and can be used in commercial products without restriction or attribution. I recall this being a major disadvantage of the Qt framework.

**Comment by bukkideme** [comment]
"Unfortunately, .NET MAUI will not be ready for production with .NET 6 GA in November."
https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/

**Comment by swharden** [comment]
Dang, I didn't see that! Thanks for mentioning it @bukkideme 

I guess that explains why the [graphics controls](https://github.com/dotnet/Microsoft.Maui.Graphics) look primitive and [are not on NuGet](https://www.nuget.org/packages?q=Maui.Graphics) yet.

I was already thinking of de-prioritizing this until the Maui.Graphics project matures 😩

I'll continue to research this topic and note my findings on https://maui.graphics

**Comment by greatawesome** [comment]
I'm not sure that maui.graphics is part of the larger maui project, but it looks like they're hoping to release alongside them. 

In any case, cross platform System.Drawing will be in .NET 6, which is supported until 2024. It has never has been ideal for cross platform scenarios, but it buys some time.

**Comment by FoggyFinder** [comment]
> Microsoft.Maui.Graphics does not have a MAUI dependency and can be used on any of the supported platforms listed below.

**Comment by swharden** [comment]
> > Microsoft.Maui.Graphics does not have a MAUI dependency and can be used on any of the supported platforms listed below.

This is true! I already have Maui.Graphics controls mostly working for WPF and WinForms using existing NuGet packages and source code adapted from [the official project](https://github.com/dotnet/Microsoft.Maui.Graphics/tree/main/src) 😎 

These pages are a work in progress, but you can get the gist:
* https://maui.graphics/quickstart/wpf
* https://maui.graphics/quickstart/winforms

This is already pretty close to usable for ScottPlot. The WPF control uses Skia and the WinForms control uses GDI. The WinForms/GDI control doesn't currently support gradient fills but I hope support will get officially implemented soon. An alternative option is for me to make a Maui.Graphics.Skia control for WinForms. I would have expected the official project to have one, but I don't see it there (yet?). If/when a Skia WinForms control is ready it should be smooth sailing, and we don't have to wait until 2022

Solutions with code that compiles/runs can be found on https://github.com/swharden/Maui.Graphics

**Comment by swharden** [comment]
I'm going to close this issue for now, but I'm actively working on it. I got PRs merged into [dotnet/Microsoft.Maui.Graphics](https://github.com/dotnet/Microsoft.Maui.Graphics) 🤓 but it looks like they're still pretty far from having it production ready

I started collecting some notes here:
* https://maui.graphics
* https://maui.graphics/quickstart/winforms
* https://maui.graphics/quickstart/wpf

**Comment by swharden** [comment]
It's starting... ☠️

ScottPlot must not upgrade to System.Drawing.Common version 6 or above

![image](https://user-images.githubusercontent.com/4165489/137599404-5aab2708-9876-4fb8-877c-93e5d5691236.png)

**Comment by profix898** [comment]
> ... I'll lean away from System.Drawing and toward SkiaSharp by way of Microsoft.Maui.Graphics.Skia. Skia is indeed large, but it is very performant, and high performance mouse-interactive plotting is ScottPlot's biggest strength over similar free libraries ...

It would be awesome for ScottPlot to use Microsoft.Maui.Graphics and provide an IDrawable directly for static visualization. In many cases, having the plots rendered in a cross-platform but lightweight fashion gets you 90%. Having a fixed Skia dependency in the core plotting library would be a shame IMO. Especially for mobile, we should be able to avoid the large Skia payload and render directly on the native platform (that's the nice advantage you get from using the Maui.Graphics abstraction anyway).

You could still provide more specialized packages with performant and mouse-interactive controls for different platform (where it is probably Ok to have Skia in the mix), but please not in the core plotting library.

Just my two cents ...

**Comment by swharden** [comment]
I made a MVP version of ScottPlot in `/dev/ScottPlot5` to explore what a `Microsoft.Maui.Graphics` implementation would be like. It's somewhat unsurprising (a good thing) and similar to what a pure `SkiaSharp` implementation woudl be. The main API change is just that color arguments are `Maui.Graphics.Color` instead of `System.Drawing.Color`, and interactive controls have a `SKGLControl` with a `Paint` method that performs the render.

I'll close this issue for now because `Microsoft.Maui.Graphics` is still in preview, has important unsupported features (like custom font support and precise string measurement), and is still making large breaking changes. I'll open this issue and re-prioritize this when Maui matures.

For details see:
* https://github.com/ScottPlot/ScottPlot/pull/1647#issuecomment-1058725910
* #1691
