### ISSUE TITLE
How to change Line properties after it was plotted

### ISSUE THREAD

**Issue by EmanuelFeru** [ScottPlot/ScottPlot#1044]
### Your Environment
- ScottPlot Version: 4.1.13 Beta
- Operating System: W10
- WinForms

How to change properties for a specific signal after it was plotted? For example, I want to change the line tickness of only one signal or change its color to highlight the signal. I want to be able to do it dynamically based on user interraction.
```cs
formsPlot1.Plot.AddSignalConst(y1, lineWidth: 1);
formsPlot1.Plot.AddSignalConst(y2, lineWidth: 1);
formsPlot1.Render();

// change Line properties only of signal y1 here (e.g. make lineWidth: 3) 
formsPlot1.Render();

// after some user interraction, set the lineWidth to original value of 1
formsPlot1.Render();
```

I am a Matlab user and there it was very easy to change the line properties via the plot handle. I am looking to do something similar with ScottPlot.
```matlab
figure();
h1 = plot(x1, y1);
h2 = plot(x2, y2);
set(h1, 'Linewidth', 3);
```

I searched through the Cookbook/issues/discussions and I couldn't find an answer. Maybe I missed it.

**Comment by bclehmann** [comment]
You can do this:

```
var sigPlot = formsPlot1.Plot.AddSignalConst(y1, lineWidth: 1);
formsPlot1.Render();

// After Interaction
sigPlot.LineWidth = 3;
formsPlot1.Render();
```

You can see all of the public properties of `Plottable.SignalPlot` [here](https://swharden.com/scottplot/cookbooks/4.1.13-beta/api/plottable/signalplot/#fields).

**Comment by EmanuelFeru** [comment]
Awesome. This is exactly what I was looking for. Thanks!
