### ISSUE TITLE
How to customize the color Palette used for plottables

### ISSUE THREAD

**Issue by EmanuelFeru** [ScottPlot/ScottPlot#1058]
**ScottPlot Version:** 4.1.14

**Operating System:** Win10

**Application Type:** WinForms

**Questions:** 
- Is there a way to reset the Colors index for a plot back to 0? In #1032 last comment, you can see that because I add a red Vertical Axis line at the begining, the next signal gets an Orange color (index 1) instead of Blue (index 0).
- Is there a way to add custom signals color array (and maybe styles) inside ScotPlot? So ScottPlot will loop around those colors and styles.
**Edit**: I have seen this [Cookbook example](https://swharden.com/scottplot/cookbooks/4.1.14/category/plottable-scatter-plot/#all-marker-shapes) which is ok for one plot, but for multiple plots becomes difficult to keep track of the color index for each plot. This is why I believe something internal to ScottPlot is more elegant.

**Comment by swharden** [comment]
Hi @EmanuelFeru, thank you for this question! 

## Plot.Palette() is Broken

There is a Palette system which manages default colors for new plottables, but it looks to be incompletely implemented and not documented well. `Plot.Palette()` exists but doesn't seem to work as intended. 

I think I'll convert it from a method to a property, then add some tests to ensure it works as expected and some cookbook examples demonstrating how to use it. I'm pretty sure getting this working will fully address your issue, and give everyone access to very nice looking alternative default color sets.

Related #481

## Manually Manage Colors

An immediate fix for your problem is to manage the colors yourself by assigning line colors manually. Colors for the default palette (Category10) and more palettes can be accessed like this:

```cs
var pal = ScottPlot.Drawing.Palette.Category10;
for (int i = 0; i < pal.Count(); i++)
{
    System.Drawing.Color color = pal.GetColor(i);
    Console.WriteLine($"[{i}] = {color}");
}
```

**Comment by EmanuelFeru** [comment]
Hi @swharden, you got my point, that is what I am looking for to be able to define a custom ColorSet.

Until that becomes available, I will take your suggestions to manually manage the colors. Thank you!

**Comment by EmanuelFeru** [comment]
And for resetting the color index back to 0 do you have any suggestions? Or I do it by manually managing colors?

**Comment by swharden** [comment]
> resetting the color index back to 0

This isn't really feasible with the current design. Currently the default color for all new plottables is the Nth color in the palette where N is the number of plottables that have been plotted previously.

> manually managing colors

To reset at zero, managing colors manually is the way to go, but you can get help from the palette system:
```cs
var pal = ScottPlot.Drawing.Palette.Category10;

// start at zero
Color first = pal.GetColor(0);
Color second = pal.GetColor(1);
Color third = pal.GetColor(2);

// "reset" to zero
Color fourth = pal.GetColor(0);
Color fifth = pal.GetColor(1);
Color sixth = pal.GetColor(2);
```

**Comment by swharden** [comment]
I added cookbook examples demonstrating how to use colormaps... although I might adjust the architecture a bit before the next release. It was a little clunky, and I'd love to smooth it out before locking-in the API here. This is a great step in a positive direction, and I'm reminded that some of the palettes optimized for dark backgrounds are very useful!

![image](https://user-images.githubusercontent.com/4165489/119278122-54d9bb80-bbf1-11eb-8a8f-d1c71cdeea34.png)

**Comment by EmanuelFeru** [comment]
This info is sufficient for now. So, I will close the topic. Thank you Scott.

**Comment by swharden** [comment]
> Thank you Scott

Sure thing! Thanks for calling attention to this so we can make it easier for future users. It looks like this will be in the next release:

```cs
string[] customColors = { "#019d9f", "#7d3091", "#57e075", "#e5b5fa", "#009118" };
plt.Palette = new ScottPlot.Drawing.Palette(customColors);

for (int i = 0; i < 5; i++)
{
    double[] xs = DataGen.Consecutive(100);
    double[] ys = DataGen.Sin(100, phase: -i * .5 / 5);
    plt.AddScatterLines(xs, ys, lineWidth: 3);
}
```

![image](https://user-images.githubusercontent.com/4165489/119912333-452be100-bf29-11eb-9b5d-f11141eb817a.png)

**Comment by EmanuelFeru** [comment]
I love it!!! Thanks!
