### ISSUE TITLE
How to store the signals objects for later manipulation

### ISSUE THREAD

**Issue by EmanuelFeru** [ScottPlot/ScottPlot#1059]
## Question Template

**ScottPlot Version:** 4.1.14

**Operating System:** W10

**Application Type:** WinForms

**Question:** I am a bit stuck...not sure how to solve this. I have 3 independent plots and I want to store in an array or list all the signals object so I can manipulate them later. For example change linewith. color or remove a particular signal with:
```cs
formsPlot1.Plot.Remove(signalObjectToRemove);
```

___________
Until now, I used the line below to manipulate the signal immediately:
```cs
var sigPlot = plotDest.Plot.AddSignalConst(signals[idx].Values, 1 / Ts);
sigPlot.LineWidth = 3;
```
What I need is somethig like below (which I tried but it doesn't work):
```cs
signalsObject.Add(plotDest.Plot.AddSignalConst(signals[idx].Values, 1 / Ts));
// .....
// and in another location
signalsObject[index].LineWidth = 3;
// or
plotDest.Plot.Remove(signalsObject[index]);   // to delete a specific signal from the Plot
```

**Comment by bclehmann** [comment]
I don't think there's any reason you shouldn't be able to store signal plots in a list or similar, they're reference types so copying then into a list like this doesn't create any issues.

The only thing I can think of is you might have forgotten to call `Render()` after mutating them.

If that doesn't help I would ask for the sections of your code which pertain to rendering, the `signalsObject`, and anywhere you construct or modify plottables. Or send the whole thing if you're comfortable with that.

**Comment by EmanuelFeru** [comment]
Hi @bclehmann thank you for the answer.

When I define
```ca
private List<SignalPlotConst> signalsObject;
```
I have:
![image](https://user-images.githubusercontent.com/24780745/119271597-798a5f00-bc02-11eb-91ae-23bbc314d385.png)

Then later I do:
```cs
var sig = plotDest.Plot.AddSignalConst(signals[idx].Values, 1 / Ts);                                
signalsObject.Add(sig);
```
![image](https://user-images.githubusercontent.com/24780745/119271632-a2aaef80-bc02-11eb-8d30-85f4a531a076.png)

**Comment by breakwinz** [comment]
Try `private List<SignalPlotConst<double>> signalsObject;`

**Comment by EmanuelFeru** [comment]
Yes, it works with `private List<SignalPlotConst<double>> signalsObject;` Thanks a lot @breakwinz.

I have only one topic that needs clarification:
- How to store a List with different data types? Because I want to plot mixed signals in the same plot ,e.g., `AddSignal`, `AddSignalConst`, 'AddScatter', etc. And as I see they have different data types:
![image](https://user-images.githubusercontent.com/24780745/119273972-cb84b200-bc0d-11eb-81f4-946cea713e53.png)

**Comment by breakwinz** [comment]
You can do `Private List<ScottPlot.Plottable.IPlottable> _iplottables = new List<ScottPlot.Plottable.IPlottable>();`

You can now add any plottable to the list `_iplottables`

**Comment by EmanuelFeru** [comment]
Perfect! Tested and works.
