### ISSUE TITLE
[Question] Possible to add something that allows to check if one signalplotXY ever intersects another signalplotXY?

### ISSUE THREAD

**Issue by breakwinz** [ScottPlot/ScottPlot#1060]
Given I have two sets of `ScottPlot.Plottable.SignalPlotXYConst<double, double>>`

Is it possible to call any method/function inside scottplot that allows me to tell if they have ever intersected?

**Comment by swharden** [comment]
Hi @breakwinz,

This is not currently implemented with ScottPlot. We try to constrain the scope of ScottPlot to _plotting_ and not so much _data analysis_, so this type of analytical process is best managed in the user's code 👍
