### ISSUE TITLE
Add PlottableDragged and PlottableDropped event handlers to 4.1 controls

### ISSUE THREAD

**Issue by JS-BGResearch** [ScottPlot/ScottPlot#1072]
The property MouseDragPlottable has disappeared in v 4.1.14 when updating from v4.0.4

**Comment by swharden** [comment]
Hi @JS-BGResearch, thanks for pointing this out! The draggable object system has been refactored in 4.1, but it looks like those events never got properly implemented or exposed in this new version. I'll prioritize this and add a demo to ensure it's working as expected and documented clearly.

I'll probably create events named `PlottableDragged` and `PlottableDropped` and implement all events in the 4.0 API with obsolete decorators and messages that indicate the names of the new events that replaced them.

### Reference

ScottPlot 4.0 FormsPlot API:
* https://www.fuget.org/packages/ScottPlot.WinForms/4.0.48/lib/netcoreapp3.0/ScottPlot.WinForms.dll/ScottPlot/FormsPlot

ScottPlot 4.1 FormsPlot API:
* https://www.fuget.org/packages/ScottPlot.WinForms/4.1.14/lib/netcoreapp3.0/ScottPlot.WinForms.dll/ScottPlot/FormsPlot
* https://swharden.com/scottplot/cookbooks/4.1.14/docfx/api/ScottPlot.FormsPlot.html
* https://www.fuget.org/packages/ScottPlot/4.1.14/lib/netstandard2.0/ScottPlot.dll/ScottPlot.Control/Configuration

**Comment by swharden** [comment]
I just finished these changes. Here's a working demo with source code:

```cs
public Form1()
{
    InitializeComponent();

    formsPlot1.Plot.AddSignal(ScottPlot.DataGen.Sin(51));

    var vline1 = formsPlot1.Plot.AddVerticalLine(11, Color.Blue);
    vline1.DragEnabled = true;

    var vline2 = formsPlot1.Plot.AddVerticalLine(22, Color.Red);
    vline2.DragEnabled = true;

    formsPlot1.PlottableDragged += FormsPlot1_PlottableDragged;
    formsPlot1.PlottableDropped += FormsPlot1_PlottableDropped;
}

private void FormsPlot1_PlottableDragged(object sender, EventArgs e)
{
    if (sender is ScottPlot.Plottable.VLine vline)
        label1.Text = $"dragged {vline.Color} to X={vline.X:N3}";
}

private void FormsPlot1_PlottableDropped(object sender, EventArgs e)
{
    if (sender is ScottPlot.Plottable.VLine vline)
        label1.Text = $"dropped {vline.Color} at X={vline.X:N3}";
}
```

https://user-images.githubusercontent.com/4165489/119751438-2cf48d00-be69-11eb-8705-cc893c0bd7cb.mp4
