### ISSUE TITLE
WpfPlot: Hide error label by default

### ISSUE THREAD

**Issue by Superberti** [ScottPlot/ScottPlot#1073]
Hi,

first of all: ScottPlot is really impressive, thanks for this!

I have a WPF Apllication which uses Metro MahApps and is styled in many ways. If I resize the window you'll see the ErrorLabel flickering behind the plot like this (frame from a screen recording):

![ScottPlot](https://user-images.githubusercontent.com/16542302/119682448-2eab5a00-be43-11eb-8cd7-5b486e841a1e.png)

You won't see this error label in an non-styled application.
So it would be a nice idea to hide the ErrorLabel in the control's xaml file by default and to unhide it in the exception case in code behind.

Thanks and bye,
Oliver

**Comment by swharden** [comment]
Thanks for pointing this out @Superberti! I'll fix this right away and release a new package on NuGet today or tomorrow 👍

**Comment by Superberti** [comment]
Wow, that's really fast! Many thanks!!!
