### ISSUE TITLE
Font rendering error on Fedora Linux

### ISSUE THREAD

**Issue by matachi** [ScottPlot/ScottPlot#1079]
## Bug Report Template

**ScottPlot Version:** 4.1.15

**Operating System:** Fedora 34, Wayland, 64-bit

**Application Type:** console

**Bug Description:** The numbers in the chart aren't rendered correctly:

![test](https://user-images.githubusercontent.com/980838/119884435-ebc7b000-bf30-11eb-9ece-884892176835.png)

I installed `libgdiplus` as described in the README. Do I need to install something in addition to that? I don't know if a font is missing or something else is going wrong?

**Reproducing:**

```cs
namespace stocks
{
    class Program
    {
        static void Main(string[] args)
        {
            var dataX = new double[] { 1, 2, 3, 4, 5 };
            var dataY = new double[] { 1, 4, 9, 16, 25 };
            var plt = new ScottPlot.Plot();
            plt.AddScatter(dataX, dataY);
            plt.SaveFig("test.png");
        }
    }
}
```

**Comment by swharden** [comment]
Hi @matachi, thanks for sharing this issue! My guess is that this issue relates to not finding a font that your system can easily render.

## Is all text affected?

If you add a title and axis label, do those render correctly?
```cs
plt.Title("test");
plt.XLabel("test");
plt.YLabel("test");
```

## Does changing font help?
Try a font name definitely installed on your system
```cs
plt.XAxis.TickLabelStyle(fontName: "comic sans ms");
plt.YAxis.TickLabelStyle(fontName: "comic sans ms");
```

## Test for this

I can add a test for this that will run on Windows/MacOS/Linux as part of the CI pipeline. It will render the number 1 and the number 2 on otherwise identically bitmaps, and assert that the resulting bitmaps are different.

## Notes
Default font names are looked-up like this:

https://github.com/ScottPlot/ScottPlot/blob/efcc3ceaebf2b4af475a5dc46c6e21b696623eaa/src/ScottPlot/Drawing/InstalledFont.cs#L11-L20

https://github.com/ScottPlot/ScottPlot/blob/efcc3ceaebf2b4af475a5dc46c6e21b696623eaa/src/ScottPlot/Drawing/InstalledFont.cs#L22-L31

**Comment by matachi** [comment]
I added these lines to a project:
```c#
            plt.Title("Abcdefghijklmnopqrstquvwxyz");
            plt.XLabel("test");
            plt.YLabel("test");
```
And the chart looks like this:
![test](https://user-images.githubusercontent.com/980838/119888912-3a2b7d80-bf36-11eb-87b8-fc1330bf3d5b.png)
Funny that `z` appears in the title.

This didn't do any difference:
```c#
            plt.XAxis.TickLabelStyle(fontName: "comic sans ms");
            plt.YAxis.TickLabelStyle(fontName: "comic sans ms");
```
However, I don't think that's surprising, because I don't think Fedora has any of Microsoft's copyrighted fonts by default. On the other hand, I do have `DejaVu Serif` installed, and it neither works:
```c#
namespace stocks
{
    class Program
    {
        static void Main(string[] args)
        {
            var dataX = new double[] { 1, 2, 3, 4, 5 };
            var dataY = new double[] { 1, 4, 9, 16, 25 };
            var plt = new ScottPlot.Plot();
            plt.AddScatter(dataX, dataY);
            plt.Title("test");
            plt.XLabel("test");
            plt.YLabel("test");
            plt.XAxis.TickLabelStyle(fontName: "DejaVu Serif");
            plt.YAxis.TickLabelStyle(fontName: "DejaVu Serif");
            plt.SaveFig("test.png");
        }
    }
}
```
![test](https://user-images.githubusercontent.com/980838/119890040-9ba01c00-bf37-11eb-8e77-cc4aa509dea1.png)

I can see here that it's installed:
```bash
$ fc-list | grep deja
/usr/share/fonts/dejavu-sans-fonts/DejaVuSans-ExtraLight.ttf: DejaVu Sans,DejaVu Sans Light:style=ExtraLight
/usr/share/fonts/dejavu-sans-mono-fonts/DejaVuSansMono-BoldOblique.ttf: DejaVu Sans Mono:style=Bold Oblique
/usr/share/fonts/dejavu-serif-fonts/DejaVuSerifCondensed-Bold.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed Bold,Bold
/usr/share/fonts/dejavu-sans-fonts/DejaVuSansCondensed.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed,Book
/usr/share/fonts/dejavu-sans-fonts/DejaVuSansCondensed-Bold.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed Bold,Bold
/usr/share/fonts/dejavu-serif-fonts/DejaVuSerif-Bold.ttf: DejaVu Serif:style=Bold
/usr/share/fonts/dejavu-sans-fonts/DejaVuSans-Oblique.ttf: DejaVu Sans:style=Oblique
/usr/share/fonts/dejavu-serif-fonts/DejaVuSerifCondensed-BoldItalic.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed Bold Italic,Bold Italic
/usr/share/fonts/dejavu-sans-fonts/DejaVuSansCondensed-Oblique.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed Oblique,Oblique
/usr/share/fonts/dejavu-serif-fonts/DejaVuSerifCondensed.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed,Book
/usr/share/fonts/dejavu-sans-fonts/DejaVuSans.ttf: DejaVu Sans:style=Book
/usr/share/fonts/dejavu-serif-fonts/DejaVuSerif-Italic.ttf: DejaVu Serif:style=Italic
/usr/share/fonts/dejavu-sans-fonts/DejaVuSans-Bold.ttf: DejaVu Sans:style=Bold
/usr/share/fonts/dejavu-serif-fonts/DejaVuMathTeXGyre.ttf: DejaVu Math TeX Gyre:style=Regular
/usr/share/fonts/dejavu-sans-fonts/DejaVuSans-BoldOblique.ttf: DejaVu Sans:style=Bold Oblique
/usr/share/fonts/dejavu-sans-fonts/DejaVuSansCondensed-BoldOblique.ttf: DejaVu Sans,DejaVu Sans Condensed:style=Condensed Bold Oblique,Bold Oblique
/usr/share/fonts/dejavu-serif-fonts/DejaVuSerifCondensed-Italic.ttf: DejaVu Serif,DejaVu Serif Condensed:style=Condensed Italic,Italic
/usr/share/fonts/dejavu-serif-fonts/DejaVuSerif.ttf: DejaVu Serif:style=Book
/usr/share/fonts/dejavu-sans-mono-fonts/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
/usr/share/fonts/dejavu-serif-fonts/DejaVuSerif-BoldItalic.ttf: DejaVu Serif:style=Bold Italic
/usr/share/fonts/dejavu-sans-mono-fonts/DejaVuSansMono-Oblique.ttf: DejaVu Sans Mono:style=Oblique
/usr/share/fonts/dejavu-sans-mono-fonts/DejaVuSansMono-Bold.ttf
```

I added these lines of code for testing:
```c#
            var a = FontFamily.Families;
            foreach (var b in a)
            {
                Console.WriteLine(b.Name);
            }
```
And it prints:
```
D050000L
DejaVu Serif
MathJax_Vector-Bold
Noto Sans Meetei Mayek
Eeyek Unicode
Lohit Assamese
Lohit Gujarati
Droid Sans
P052
PakType Naskh Basic
Liberation Mono
Montserrat
STIX MathJax Symbols
Noto Sans Mandaic
URW Bookman
Symbola
Dyuthi
MathJax_Fraktur
Noto Sans Tagalog
URW Gothic
Droid Sans
MathJax_SansSerif
Fira Code
Noto Sans Meetei Mayek
Source Han Sans CN
Source Han Sans CN
Lohit Kannada
Noto Sans Tai Tham
Caladea
DejaVu Sans
Droid Sans
FreeMono
Padauk
Montserrat
Nimbus Roman
Lohit Devanagari
Comfortaa
FreeSerif
STIX
Carlito
Cantarell
Liberation Serif
Source Han Sans TW
Source Han Sans TW
STIX MathJax Operators
STIX MathJax Alphabets
Noto Sans Meetei Mayek
Comfortaa
Noto Sans Meetei Mayek
Noto Sans Tai Tham
Source Code Pro
Noto Sans Meetei Mayek
Liberation Sans
Montserrat
Source Han Sans CN
STIX
MathJax_WinIE6
Lohit Bengali
Tannenberg Fett
Mingzat
Montserrat
STIX MathJax Script
Montserrat
LKLUG
Z003
STIX MathJax Arrows
Noto Sans Meetei Mayek
Waree
STIX MathJax DoubleStruck
STIX MathJax Shapes
Rachana
Nimbus Sans
Fira Code
Courier 10 Pitch
DejaVu Serif
Lohit Gurmukhi
C059
Nimbus Sans Narrow
Utopia
Fira Code
STIX MathJax Fraktur
Nimbus Mono PS
Tannenberg Fett
Nuosu SIL
PT Sans
STIX MathJax Normal
Montserrat
Nimbus Sans
URW Bookman
NanumGothic
Lohit Tamil
MathJax_Caligraphic
Suruma
Lohit Odia
Source Code Pro
RaghuMalayalamSans
Khmer OS System
Source Han Sans TW
Source Han Sans TW
D050000L
C059
MathJax_AMS
MathJax_Vector
Bitstream Charter
Droid Sans
Droid Sans
STIX MathJax Variants
MathJax_Main
Android Emoji
Noto Sans Lisu
PT Sans
MathJax_Math
Estrangelo Edessa
Abyssinica SIL
FreeSans
VL Gothic
OpenSymbol
Cantarell
Droid Sans
Lohit Telugu
STIX MathJax Latin
STIX MathJax SansSerif
STIX MathJax Misc
Z003
Droid Sans
Montserrat
STIX MathJax Marks
AnjaliOldLipi
Noto Sans Lisu
MathJax_Script
MathJax_WinChrome
Montserrat
Source Han Sans CN
Nimbus Sans Narrow
Khmer OS Content
Nimbus Mono PS
Source Han Sans TW
MathJax_Typewriter
DejaVu Sans Mono
Source Code Pro
Droid Sans
STIX MathJax Size4
STIX MathJax Size5
STIX MathJax Size2
STIX MathJax Size3
STIX MathJax Size1
Nimbus Roman
Droid Sans
Droid Sans
Noto Sans Tai Tham
Noto Sans Lisu
Fira Code
Liberation Sans Narrow
STIX MathJax Main
Noto Sans Meetei Mayek
Meera
Cursor
Source Code Pro
Source Han Sans CN
Source Han Sans CN
PT Sans Caption
Cantarell
Cantarell
Source Code Pro
Jomolhari
P052
Standard Symbols PS
Droid Sans
Noto Sans Meetei Mayek
NanumGothic
Kaushan Script
URW Gothic
DejaVu Sans
Noto Sans Tai Viet
Noto Color Emoji
Nimbus Sans
NanumGothic
Source Han Sans TW
DejaVu Sans
Source Code Pro
DejaVu Math TeX Gyre
Fira Code
MathJax_Size3
MathJax_Size2
MathJax_Size1
STIX MathJax Monospace
MathJax_Size4
```
So it detects a lot of fonts, such as DejaVu Serif. So it's strange that it fails to render the texts.

**Comment by swharden** [comment]
## Reproducing the Bug

I suspect this is a System.Drawing bug, independent of ScottPlot... 

Does this console application fail for you?

```cs
using System;
using System.Drawing;

Bitmap bmp = new Bitmap(200, 100);
using var gfx = Graphics.FromImage(bmp);
gfx.Clear(Color.Navy);
Font fnt = new Font("Arial", 18);
gfx.DrawString("test123", fnt, Brushes.Yellow, 10, 10);
bmp.Save("test.bmp");
```

This is what I see:
![image](https://user-images.githubusercontent.com/4165489/119892627-5fa19280-bf08-11eb-8a5a-2d31330a9c93.png)

Your issue may be similar to this unsolved one:
https://stackoverflow.com/questions/58585414/system-drawing-common-drawstring-not-rendering-text-properly-in-linux

**Comment by matachi** [comment]
Interesting, if I build and run:
```c#
using System.Drawing; // provided by System.Drawing.Common NuGet package

Bitmap bmp = new Bitmap(200, 100);
using var gfx = Graphics.FromImage(bmp);
gfx.Clear(Color.Navy);
Font fnt = new Font("Arial", 18);
gfx.DrawString("test123", fnt, Brushes.Yellow, 10, 10);
bmp.Save("test.bmp");
```
Then it looks like this:
![image](https://user-images.githubusercontent.com/980838/119894585-0dc72f80-bf3d-11eb-9f08-69feffb9f258.png)

However, if I install `system.drawing.common`:
```bash
$ dotnet add package system.drawing.common
```
And rebuild and run the program, then it works:
![test2](https://user-images.githubusercontent.com/980838/119894426-e07a8180-bf3c-11eb-9409-ee9aa470f7ff.png)

And now if I return to this program:
```c#
namespace stocks
{
    class Program
    {
        static void Main(string[] args)
        {
            var dataX = new double[] { 1, 2, 3, 4, 5 };
            var dataY = new double[] { 1, 4, 9, 16, 25 };
            var plt = new ScottPlot.Plot();
            plt.AddScatter(dataX, dataY);
            plt.Title("test");
            plt.XLabel("test");
            plt.YLabel("test");
            plt.XAxis.TickLabelStyle(fontName: "DejaVu Serif");
            plt.YAxis.TickLabelStyle(fontName: "DejaVu Serif");
            plt.SaveFig("test.png");
        }
    }
}
```
Now it works:
![test](https://user-images.githubusercontent.com/980838/119894786-541c8e80-bf3d-11eb-9d65-0984efffc5a1.png)

Note that I don't need to import `System.Drawing`. Apparently it's sufficient that that NuGet package is installed. Strange though that these examples compile and run even if I don't have `System.Drawing` installed in the project.

**Comment by swharden** [comment]
Thanks for following-up! I'm glad we mostly got this figured out.

## Solution

To summarize our findings for future readers, it sounds like manually installing the [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/) NuGet package in your project fixed the ScottPlot rendering issue on Linux

**Comment by matachi** [comment]
Thank you very much for the help @swharden!

**Comment by matachi** [comment]
@swharden I wrote an answer on that Stackoverflow page as well, for anybody else who might stumble upon this in the future. Thanks for finding and providing a link to it.

**Comment by royalstream** [comment]
I had the same issue with .NET 6.0, macOS 12.1 and ScottPlot.Avalonia/4.1.29

Adding a reference to the latest version of **System.Drawing.Common** (6.0.0) causes a **PlatformNotSupportedException**

However, adding a reference to **5.0.2** did the trick:

`dotnet add package System.Drawing.Common -v 5.0.2
`

Thanks.

**Comment by mahkassem** [comment]
@royalstream I had a problem using `System.Drawing.Image.GetImageThumbnail` and your solution did work for me too.
Is this a change in v6.0.0 or is it a bug?

**Comment by swharden** [comment]
> Is this a change in v6.0.0 or is it a bug?

It wouldn't surprise me if this is indeed a change in .NET 6 -- it's the first version they're specifically stating they _don't_ support https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

**Comment by royalstream** [comment]
> > Is this a change in v6.0.0 or is it a bug?
> 
> It wouldn't surprise me if this is indeed a change in .NET 6 -- it's the first version they're specifically stating they _don't_ support https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

But I had the same issue with .NET 5.0
At least on my system (macOS), both Frameworks .Net 5.0 and .Net 6.0 reference the following DLL out of the box:

```
System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
/.nuget/packages/system.drawing.common/4.5.0/ref/netstandard2.0/System.Drawing.Common.dll
```

As soon as you add a reference to ScottPlot, it brings a slightly newer DLL to the party (causing the rendering issues): 

```
System.Drawing.Common, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
/.nuget/packages/system.drawing.common/4.6.1/ref/netcoreapp3.0/System.Drawing.Common.dll

```

Doing an upgrade to the latest version of System.Drawing.Common (6.0.0) doesn’t work on my setup.
So that’s why I had to settle for 5.0.2, but this is System.Drawing.Common’s version, not the Framework’s.
