### ISSUE TITLE
Provide an Update() method in RadarPlot

### ISSUE THREAD

**Issue by arthurits** [ScottPlot/ScottPlot#1086]
## Updating values in RadarPlot

**Feature description:** The `Update()` method in several `Plottables` is quite useful especially when plotting data continously. Unfortunately, the RadarPlot doesn't seem to implement any updating at all, which can become a nuisance for continous data plotting.

I first hoped to create a `RadarPlot` derived-control in order to implement the value updating using a simple and straightforward code:
```cs  
class ClassPlotRadar : ScottPlot.Plottable.RadarPlot
{
    public ClassPlotRadar(double[,] values, Color[] lineColors, Color[] fillColors, bool independentAxes, double[] maxValues = null)
        :base(values, lineColors, fillColors, independentAxes, maxValues)
    {
    }
    public void Update(double[,] values, double[] maxValues = null)
    {
        base.Norm = new double[values.GetLength(0), values.GetLength(1)];
        Array.Copy(values, 0, base.Norm, 0, values.Length);
        if (this.IndependentAxes)
            base.NormMaxes = base.NormalizeSeveralInPlace(base.Norm, maxValues);
        else
            base.NormMax = base.NormalizeInPlace(base.Norm, maxValues);
    }
}
```
Unfortunately, the above code doesn't work because `Norm`, `NormMaxes`, `NormMax`, `NormalizeSeveralInPlace`, and `NormalizeInPlace` are all defined as private.

So, as far as I understand, the only option is to resort to the "Clear and Replot" strategy suggested in #1042, althought the user-code becomes slightly cumbersome as the plot format has to be re-set each time new data is received and the `Clear()` method is called. Therefore, it would be useful if some updating options could be provided for `RadarPlot`.

**Comment by swharden** [comment]
> it would be useful if some updating options could be provided for RadarPlot

Hi @arthurits, thanks for the suggestion! It would be nice if more plot types had an `Update()` method to manage changing data (and provide validation / error checking), so I like the direction this is going.

## Restating the Issue

There is logic in the initializer that processes the data and populates private readonly variables, so you can't implement an `Update()` method that modifies them using inheritance.

https://github.com/ScottPlot/ScottPlot/blob/b1d26dc508f15cb4ff3a0c0feeae6ca803cfe769/src/ScottPlot/Plottable/RadarPlot.cs#L16-L18

https://github.com/ScottPlot/ScottPlot/blob/b1d26dc508f15cb4ff3a0c0feeae6ca803cfe769/src/ScottPlot/Plottable/RadarPlot.cs#L32-L48

## Implementation

It may be a good opportunity to do something like:
* Create `public void Update(double[,] values, double[] maxValues = null)` in the `RadarPlot` class
* Bonus points for XML documentation describing what that second argument does
* Move that normalization logic inside the `Update()` method and calling it in the initializer
* We can keep those arrays `private` (but no longer `readonly`)

## Contribution / Pull Request

If you want to try to make this modification and create a pull request I'd be happy to take a look! @bclehmann's (the original author of the radar plot module) might be able to provide some good feedback too.
