### ISSUE TITLE
How to keep Draggable axis always on top

### ISSUE THREAD

**Issue by EmanuelFeru** [ScottPlot/ScottPlot#1090]
**ScottPlot Version:** 4.1.15

**Operating System:** Win10

**Application Type:** WinForms

**Question:** Is there a way to always keep draggable axis on top? In my case, I add the draggable axis first and then interractively I add new signals. The draggable axis remains below and this is harder to visualize from user perspective.

![image](https://user-images.githubusercontent.com/24780745/120065998-998fa780-c074-11eb-8607-3fb61af4b025.png)

**Comment by swharden** [comment]
Thanks for raising this issue @EmanuelFeru!

I'm adding `Move`, `MoveFirst`, and `MoveLast` methods to `Plot` to make it easier to customize the render order.

After adding new signal plots call `MoveLast(myVerticalLine)` to raise it to the top.

```cs
AxisLine VLine;

public Form1()
{
    InitializeComponent();
    var sig1 = formsPlot1.Plot.AddSignal(ScottPlot.DataGen.Sin(51));
    sig1.LineWidth = 20;

    VLine = formsPlot1.Plot.AddVerticalLine(13);
    VLine.DragEnabled = true;
    VLine.LineWidth = 5;
}

private void button1_Click(object sender, EventArgs e) => formsPlot1.Plot.MoveFirst(VLine);

private void button2_Click(object sender, EventArgs e) => formsPlot1.Plot.MoveLast(VLine);
```

![move](https://user-images.githubusercontent.com/4165489/120120154-89a5bf80-c169-11eb-996f-bec6e2acc4ce.gif)
