### ISSUE TITLE
Some of example plots not rendered (rendering gets broken)

### ISSUE THREAD

**Issue by pavlexander** [ScottPlot/ScottPlot#1094]
## Bug Report
**ScottPlot Version:** 4.1.15 (trunk)
**Operating System:** Win10
**Application Type:** WinForms (example app)
**Bug Description:** When switching between plots in WinForms example application - some plots are not being rendered (corrupt rendering).
**Reproducing:** 

1, checkout main bracnh code (current version is 4.1.15)
2. set winforms app as startup project
3. run app in Debug mode
4. navigate to finance plots
5. start clicking on ope plot after another until plots stop rendering (example: "OHLC Chart", but there are more examples in other menus!)
6. p.s. switching to "SImple Moving Average SMA" plot or to "Scatter plot:" fixes the rendering issue temporary.
7. clicking on a broken plot will corrupt rendering again.

### See self-explanatory gif
![xcottplotbug02](https://user-images.githubusercontent.com/20644772/120103242-6114ca00-c157-11eb-8698-c97250a17ccd.gif)

**Comment by swharden** [comment]
Thanks for reporting this @pavlexander! 

I ran into this bug independently in #1098 and fixed it in #1099 and am about to merge it in 👍
