### ISSUE TITLE
linking heatmap plot to other plots

### ISSUE THREAD

**Issue by pavlexander** [ScottPlot/ScottPlot#1095]
## description

**ScottPlot Version:** 4.1.15 (trunk)
**Operating System:** Win10
**Application Type:** WinForms
**Question:** I can't find the way how to link the heatmap to a plot of other type... if I understand correctly - currently it's not possible to change the Xaxis of the heatmap, is this true? My main aim is to be able to link the heatmap to other plot.. is this possible somehow? Maybe in beta?

## code sample

In WinForms app I have 3 plots: candlesticks, bars, and heatmap.

I have followed the linking example:

            FormsPlots = new FormsPlot[] { formsPlot1, formsPlot2, formsPlot3 };
            foreach (var fp in FormsPlots)
                fp.AxesChanged += OnAxesChanged;

and slightly adjusted the code, so that only X-Axis would be in-sync:

        private void OnAxesChanged(object sender, EventArgs e)
        {
            FormsPlot changedPlot = (FormsPlot)sender;
            var newAxisLimits = changedPlot.Plot.GetAxisLimits();

            foreach (var fp in FormsPlots)
            {
                if (fp == changedPlot)
                    continue;

                // disable events briefly to avoid an infinite loop
                fp.Configuration.AxesChangedEventEnabled = false;
                //fp.Plot.SetAxisLimits(newAxisLimits);
                fp.Plot.SetAxisLimitsX(newAxisLimits.XMin, newAxisLimits.XMax);
                fp.Render();
                fp.Configuration.AxesChangedEventEnabled = true;
            }
        }

**without** X-axis linking - result looks like this:

![image](https://user-images.githubusercontent.com/20644772/120108895-cb396900-c16f-11eb-8ea9-033819f15633.png)

With linking - heatmap plot disappears to somewhere:

![image](https://user-images.githubusercontent.com/20644772/120108886-c1176a80-c16f-11eb-8ee1-929d852f018a.png)

I think it's because heatmap has no physical x-axis that other plots could link to.. Any advices on how to solve the issue are highly appreciated.

**Comment by pavlexander** [comment]
Strangely, if I remove the "bar plot" from linking, then sync starts to work...

![image](https://user-images.githubusercontent.com/20644772/120109600-c0cc9e80-c172-11eb-93f5-9b2c7ecf5892.png)

So 1 issue solved but then I have bar ploy sync issue.. Any advices?

For the sake of clarity attaching full reproducible code:

        public Form1()
        {
            InitializeComponent();

            int totalPoints = 60;
            
            var formsPlot = this.formsPlot1;
            var plt = formsPlot.Plot;
            OHLC[] prices = DataGen.RandomStockPrices(null, totalPoints);
            var candlePlot = plt.AddCandlesticks(prices);
            candlePlot.YAxisIndex = 0;
            
            var formsPlot2 = this.formsPlot2;
            var plt2 = formsPlot2.Plot;
            
            double[] values = DataGen.RandomNormal(0, totalPoints, 5, 10);
            double[] offsets = Enumerable.Range(0, values.Length)
                .Select(x =>
                {
                    var val = values[x];
                    if (val < 0)
                        return Math.Abs(val);
                    return 0;
                })
                .ToArray();


            var bar = plt2.AddBar(values);
            bar.ValueOffsets = offsets;
            bar.FillColorNegative = Color.Red;
            bar.FillColor = Color.Green;
            bar.YAxisIndex = 1;
            
            // order books
            var formsPlot3 = this.formsPlot3;
            var plt3 = formsPlot3.Plot;

            int orderBookPointsTotal = 26;
            int orderBookPoints = orderBookPointsTotal / 2;
            var sellBooks = new double[orderBookPoints, totalPoints];
            var buyBooks = new double[orderBookPoints, totalPoints];
            var gapGeneratorRand = new Random(0);
            for (int i = 0; i < totalPoints; i++)
            {
                var singleBookVolumes = DataGen.Random(new Random(), orderBookPointsTotal);
                if (gapGeneratorRand.Next(2) == 1)
                {
                    singleBookVolumes[10] = 0;
                    singleBookVolumes[11] = 0;
                    singleBookVolumes[12] = 0;
                    singleBookVolumes[13] = 0;
                    singleBookVolumes[14] = 0;
                    singleBookVolumes[15] = 0;
                }

                for (int j = 0; j < orderBookPoints; j++)
                    sellBooks[j, i] = singleBookVolumes[j];

                int idx = 0;
                for (int j = orderBookPoints; j < orderBookPointsTotal; j++)
                    buyBooks[idx++, i] = singleBookVolumes[j];
            }

            double[,] data2D = { { 1, 2, 3 },
                { 4, 5, 6 } };

            var sellsHeatPlot = plt3.AddHeatmap(sellBooks, Colormap.Amp);
            //var sellsHeatPlotCb = plt3.AddColorbar(sellsHeatPlot);

            double[] buyOffsets = Enumerable.Range(0, values.Length)
                .Select(x => (double)-orderBookPoints)
                .ToArray();

            //var buysHeatPlot = plt3.AddHeatmap(buyBooks, Colormap.Algae);
            //buysHeatPlot.AxisOffsets = buyOffsets;

            FormsPlots = new FormsPlot[] { formsPlot1, formsPlot2, formsPlot3 }; // no heatmap
            //FormsPlots = new FormsPlot[] { formsPlot1, formsPlot3 }; // no bar chart
            foreach (var fp in FormsPlots)
                fp.AxesChanged += OnAxesChanged;
        }

        private FormsPlot[] FormsPlots;

        private void OnAxesChanged(object sender, EventArgs e)
        {
            FormsPlot changedPlot = (FormsPlot)sender;
            var newAxisLimits = changedPlot.Plot.GetAxisLimits();

            foreach (var fp in FormsPlots)
            {
                if (fp == changedPlot)
                    continue;

                // disable events briefly to avoid an infinite loop
                fp.Configuration.AxesChangedEventEnabled = false;
                //fp.Plot.SetAxisLimits(newAxisLimits);
                fp.Plot.SetAxisLimitsX(newAxisLimits.XMin, newAxisLimits.XMax);
                fp.Render();
                fp.Configuration.AxesChangedEventEnabled = true;
            }
        }

A bonus question/feature request would be to add a configuration option for moving the "heatmap bar" outside of plot area. When you add a "bar" - essentially some of the plotting area is resized, so the synchronization ends up looing like this:

![image](https://user-images.githubusercontent.com/20644772/120109691-2e78ca80-c173-11eb-8afc-da4f5ba86733.png)

**Comment by pavlexander** [comment]
This is the latest experiment. Semi-successful. Seems like heatmap plot is living it's own life.. The axis are scaled differently. See gif.

        private void OnAxesChanged(object sender, EventArgs e)
        {
            FormsPlot changedPlot = (FormsPlot)sender;
            var newAxisLimits = changedPlot.Plot.GetAxisLimits();

            for (int i = 0; i < FormsCount; i++)
            {
                if (FormsPlots[i] == changedPlot)
                    continue;
                FormsPlots[i].Configuration.AxesChangedEventEnabled = false;
            }

            for (int i = 0; i < FormsCount; i++)
            {
                if (FormsPlots[i] == changedPlot)
                    continue;

                FormsPlots[i].Plot.SetAxisLimitsX(newAxisLimits.XMin, newAxisLimits.XMax);
                FormsPlots[i].Render();
            }

            foreach (var fp in FormsPlots)
            {
                if (fp == changedPlot)
                    continue;
                fp.Configuration.AxesChangedEventEnabled = true;
            }
        }

![xcottplotbug03](https://user-images.githubusercontent.com/20644772/120114434-dd270600-c187-11eb-8eff-c0a1415b583a.gif)

**Comment by swharden** [comment]
The problem is that `AddHeatmap()` automatically calls `AxisScaleLock(true)` which automatically stretches the horizontal axis to force heatmap squares to always be square (not rectangular). You can disable this behavior with an optional argument when adding this plot type.

The idea that just adding a plottable to the plot changes axis behavior is a bit surprising... maybe this behavior should be disabled by default. @bclehmann may want to weigh-in here. Even though many people may want to constrain axes to maintain square tiles, the idea that adding a plot has other side effects may be unexpected and hard to troubleshoot. 

## Example

```cs
public Form1()
{
    InitializeComponent();
    formsPlot1.AxesChanged += FormsPlot1_AxesChanged;

    var prices = ScottPlot.DataGen.RandomStockPrices(new Random(0), 50);
    formsPlot1.Plot.AddCandlesticks(prices);

    double[,] data = ScottPlot.DataGen.Random2D(new Random(0), 10, 50);
    formsPlot2.Plot.AddHeatmap(data, lockScales: false); // <-- disable this behavior
}

private void FormsPlot1_AxesChanged(object sender, EventArgs e)
{
    var limits = formsPlot1.Plot.GetAxisLimits();
    formsPlot2.Plot.SetAxisLimitsX(limits.XMin, limits.XMax);
    formsPlot2.Render();
}
```

![scalelock](https://user-images.githubusercontent.com/4165489/120119381-72fd6980-c165-11eb-9993-60bca335c4f7.gif)
