### ISSUE TITLE
Performance drops as window size increases

### ISSUE THREAD

**Issue by raburton** [ScottPlot/ScottPlot#1101]
## Bug Report Template

**ScottPlot Version:** 4.1.15

**Operating System:** Windows 10 x64

**Application Type:** WinForms

**Bug Description:** I have a Plot containing 4 SignalPlots each with <200,000 data points. The FormsPlot is docked to fill the window, as the window size (and therefore the FormsPlot size) is increased the rendering becomes slower. When the FormsPlot is 1238x498 the render time is ~60ms, when resized to 3822x1840 render time goes up to ~700ms. I assume this isn't normal. Your 5 million point demo doesn't seem to exhibit this behaviour.

**Reproducing:** Simple example below, but without the 18mb of data (in serialised xml format), I can upload this if it helps

```cs

// simple winform with FormsPlot object docked to fill window
        double[][] data = new double[4][];
        string[] yLabels = new string[] { "-2000", "", "0", "", "2000", "-2000", "", "0", "", "+2000", "-200", "", "0", "", "+200", "-200", "", "0", "", "+200" };
        double[] yLabelPos = new double[] { -200, -100, 0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700 };

        private void Form1_Load(object sender, EventArgs e) {
            System.Xml.Serialization.XmlSerializer x = new System.Xml.Serialization.XmlSerializer(data.GetType());
            System.IO.TextReader reader = new System.IO.StreamReader(@"c:\temp\data.xml");
            data = (double[][])x.Deserialize(reader);

            for (int i = 0; i < data[0].Length; i++) {
                data[2][i] /= 10;
                data[3][i] /= 10;
            }

            SignalPlot sp = formsPlot1.Plot.AddSignal(data[0], 200);
            sp.OffsetY = 1500;
            sp = formsPlot1.Plot.AddSignal(data[1], 200);
            sp.OffsetY = 1000;
            sp = formsPlot1.Plot.AddSignal(data[2], 200);
            sp.OffsetY = 500;
            sp = formsPlot1.Plot.AddSignal(data[3], 200);
            sp.OffsetY = 0;
            formsPlot1.Plot.YTicks(yLabelPos, yLabels);
            formsPlot1.Plot.SetAxisLimitsY(-300, 1800);
        }
```

**Comment by raburton** [comment]
Didn't realise you could attach files here, but it seems you can: [data.zip](https://github.com/ScottPlot/ScottPlot/files/6566888/data.zip)

**Comment by swharden** [comment]
Hi @raburton, thanks for reporting this!

Rather than working with 18MB text files, we can experiment using random data.

```cs
double[] data = ScottPlot.DataGen.RandomWalk(200_000);
```

I haven't looked into this yet, but is there a difference in speed between when you run in Debug mode with the debugger attached vs. running in Release mode without Visual Studio open?

**Comment by raburton** [comment]
Performance is broadly the same running release build outside VS.
Using RandomWalk data the performance seems to be fine, ~40ms in fullscreen, using the uploaded data it's about 400ms. So something to do with the scale/variability of the data? Would you expect that to be an issue?

**Comment by swharden** [comment]
> Using RandomWalk data the performance seems to be fine

This is a very useful finding! The render speed bottleneck here is `System.Drawing.Common` which begins to struggle with large fills and long lines (especially anti-aliased lines). This limitation is what causes frame rate to drop as images get larger and/or more/longer lines are added. 

ScottPlot already pushes the envelope of what this library can achieve in terms of performance, so unfortunately there's not much that can be done to improve it. I'm working toward eventually refactoring ScottPlot to be able to use SkiaSharp as an alternative render system (it supports GPU accelerated rendering using OpenGL) for large/complex images, but that's a way off.

Hope it helps!
Scott

**Comment by swharden** [comment]
Activating the render queue will render in another thread and not block the UI thread while interacting with the mouse. It probably won't increase the framerate, but it may make your application _feel_ smoother. Worth a try!

```cs
formsPlot1.Configuration.UseRenderQueue = true;
```

**Comment by raburton** [comment]
Ok, thanks for looking in to this for me. I'll probably start with the graph zoomed in instead of fully zoomed out then. If people want to zoom all the way out they'll probably expect it to slow down, rather than starting slow and getting faster as they zoom in. I'll try the render queue option as well.
