### ISSUE TITLE
Changing heatmap value offsets

### ISSUE THREAD

**Issue by pavlexander** [ScottPlot/ScottPlot#1104]
**ScottPlot Version:** 4.1.16
**Application Type:** WinForms
**Question:** Is it possible to set the value offsets for the heatmap plots? If not in the current version then maybe in next versions?

Following the default cookbook example - I tried setting the axis offsets like so:

            double[,] data2D = { { 1, 2, 3 }, { 4, 5, 6 } };
            var testHeatmapPlot = plt3.AddHeatmap(data2D);
            testHeatmapPlot.AxisOffsets = new double[] { -0.5, -2}; // this line

but the setting has no effect on the heatmap location. Even setting some unrealistic numbers such as -100 do not affect the behavior of heatmap plot.

There are 2 use-cases for this functionality
1. Being able to draw 2 or more heatmaps on the same plot area
2. bar/candlestick plots by default start drawing bars at location [-0.5; +0.5]. Heatmap is drawing at locations [0; 1]. So if you have 2 plots that correlate to each other - heatmap will always be shifted by 0.5. (p.s. now that I think about it, maybe it's easier to shift bar plots instead, as a temporary workaround :) )

Here is what I want to achieve (2 cases):

![image](https://user-images.githubusercontent.com/20644772/120157969-447e9d80-c1fc-11eb-8ff9-594867679898.png)

**Comment by swharden** [comment]
Hi @pavlexander,

It sounds like you're trying to display a heatmap that doesn't start at `(0, 0)`

I think this can be done with the "coordinated heatmap" plot type:
https://swharden.com/scottplot/cookbooks/4.1.16/category/plottable-heatmap/#coordinated-heatmap

The API is a little funny at the moment - it's surprising to have multiple heatmap types, and simplifying this is on the triage list #1028 - but I think this will meet your needs for now. Let me know if this isn't the case! 👍

**Comment by pavlexander** [comment]
@swharden thank you for help yet again! 

The result:

![image](https://user-images.githubusercontent.com/20644772/120210926-02278180-c239-11eb-9a84-e33a933b5476.png)
