### ISSUE TITLE
Add support for true Transparency

### ISSUE THREAD

**Issue by pavlexander** [ScottPlot/ScottPlot#1108]
Good day,

**Feature description:** By default when you set the Transparent background  color- it's not really a transparent color. Alpha channels are not supported by default. See image and code sample

```cs
            double[,] data2D = { { 1, 2, 3 }, { 4, 5, 6 } };
            formsPlot4.BackColor = Color.Transparent;
            formsPlot4.Plot.XAxis.IsVisible = false;
            formsPlot4.Plot.AddHeatmap(data2D);
            formsPlot4.Plot.Style(
                figureBackground: Color.Transparent, 
                dataBackground: Color.Transparent);
```

![image](https://user-images.githubusercontent.com/20644772/120281875-2b402480-c2c2-11eb-987c-304b87656af1.png)

Official guide from MS suggests invoking `SetStyle` method in constructor, to allow transparency (not sure if it solves the issue in this case):
```c#
this.SetStyle(ControlStyles.SupportsTransparentBackColor, true);
```
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-3.0/wk5b13s4(v=vs.85)?redirectedfrom=MSDN
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.controlstyles?view=net-5.0

Therefore my improvement suggestion is to add support for true transparency for inside and outside of plot area surfaces.

On a related topic - I don't know if it's intentional or not, but `formsPlot4.Plot.XAxis.IsVisible = false;` only starts working after you have added a plot (in my example - a heatmap). Same goes for plot styling rules:

```c#
            formsPlot4.Plot.XAxis.IsVisible = false;
            //formsPlot4.Plot.AddHeatmap(data2D);
            formsPlot4.Plot.Style(
                figureBackground: Color.Red, 
                dataBackground: Color.Green);
```

![image](https://user-images.githubusercontent.com/20644772/120284159-a4407b80-c2c4-11eb-94be-a3c4589e5e07.png)

It does not make sense, because you can clearly see the axis even before adding any series, so it should be possible to disable axis even if no plot/series is planned to be drawn..  If required I can create a separate bug report for it.

**Comment by bclehmann** [comment]
A clarification that this is about support for a transparent control, not transparent plottables. It was confusing the first time I read it.

**Comment by swharden** [comment]
Hi @pavlexander, thanks for the suggestions!

## Transparent Controls in Windows Forms WinForms

> Official guide from MS suggests invoking SetStyle method in constructor, to allow transparency (not sure if it solves the issue in this case):

I tried the recommendations but it doesn't work as expected. My understanding is that Windows Forms controls don't actually support transparency. This isn't a limitation of ScottPlot but rather Windows Forms. I don't think this problem exists in WPF.

### UserControl1

![image](https://user-images.githubusercontent.com/4165489/128095977-d543f68a-40d3-450d-bd3a-6a1343a1be95.png)

### Form1

```cs
public partial class UserControl1 : UserControl
{
    public UserControl1()
    {
        InitializeComponent();
        SetStyle(ControlStyles.SupportsTransparentBackColor, true);
        this.BackColor = Color.Transparent;
    }
}
```

designer view:
![image](https://user-images.githubusercontent.com/4165489/128095994-d926260e-a017-4580-bffd-f65cb7892d28.png)

runtime view:
![image](https://user-images.githubusercontent.com/4165489/128096033-2ea0d9af-b19e-46e5-9213-d758ec4e4905.png)


## X Axis Visibility

> I don't know if it's intentional or not, but formsPlot4.Plot.XAxis.IsVisible = false; only starts working after you have added a plot (in my example - a heatmap). Same goes for plot styling rules

I think this issue can be resolved by manually rendering at least once after modifying the configuration:

```cs
formsPlot4.Plot.XAxis.IsVisible = false;
formsPlot4.Render();
```
