### ISSUE TITLE
Frame: Unexpected behavior across Frame(), Frameless(), and AddRadar()

### ISSUE THREAD

**Issue by arthurits** [ScottPlot/ScottPlot#1112]
## Frame around RadarPlot

**Description:** When adding a `RadarPlot` the default settings give the plot a frameless appearance. Aesthetically, frame around the radar plot area might be preferred by some users, so the natural option is to call the `Frame()` method to draw the frame around. However, only the top and left frames are drawn, while the right and bottom are not.

**Code example:** The following code shows this unexpected behavior.

```cs
var plt = formsPlot1.Plot.AddRadar(_plotLux);
formsPlot1.Plot.Frame(visible: true);
```
![image](https://user-images.githubusercontent.com/63915486/120835431-9d379880-c564-11eb-8dea-ffbb378d2b7e.png)

This is not a big problem, since an approximated-framed `RadarPlot` (please note that the data area does not go right up to the edge of the plot) can actually be obtained, although it's slightly counterintuitive because the `AddRadar` function enables both the frame and the grid at the same time.
```cs
var plt = formsPlot1.Plot.AddRadar(_plotLux, disableFrameAndGrid: false);
formsPlot2.Plot.Grid(enable: false);
```
![image](https://user-images.githubusercontent.com/63915486/120840468-97dd4c80-c56a-11eb-9dd4-19f77682fc97.png)

**What's causing the issue?**
The `AddRadar` method doesn't allow for independently disabling the frame and the grid:
https://github.com/ScottPlot/ScottPlot/blob/c18fd8842a0551db462aaa4190d548a1e3965e48/src/ScottPlot/Plot/Plot.Add.cs#L729-L745

Going down the rabbit hole, the `Frameless()` function is implemented this way:
https://github.com/ScottPlot/ScottPlot/blob/6713c467c386cf729625fee2f18bfa3c9b2a8a1a/src/ScottPlot/Plot/Plot.Axis.cs#L94-L98

And the code for hiding each axis is:
https://github.com/ScottPlot/ScottPlot/blob/8d516f7b3a49dd5f23be552b85c7ed6cbdd05491/src/ScottPlot/Renderable/Axis.cs#L398-L406

It appears that hiding the axis also sets the private property `PixelSizePadding` to 0 (the one causing the issue). However, calling the `Frame()` method, as shown in the code at the very beginning, does not reset the value of this property, thus causing the bottom and right frames not to be drawn.
https://github.com/ScottPlot/ScottPlot/blob/6713c467c386cf729625fee2f18bfa3c9b2a8a1a/src/ScottPlot/Plot/Plot.Axis.cs#L77-L88

It's slightly counterintuitive that `Frame()` method just modifies the axis `Visible` property while the `Frameless()` method modifies the `Visible` and the three `PixelSize...` properties.

**Possible solutions:**

1. Call `AddRadar` disabling frame and grid; later enable the grid (as shown above). That's effective but counterintuitive. This keeps the plot's data area smaller than the plot control.
2. Modify the `Frame()` method in order to set back the three `PixelSize...` properties to their default values when the `visible` parameter is set to `true`. Note that the `PixelSize...` properties are private; and keep in mind that modifying them might cause unwanted side-effects.
3. Modify the `Frameless()` method so that `PixelSizePadding` is set equal to 1 (that's enough to allow the bottom and right borders to be drawn when calling `Frameless()` first and `Frame()` later). This is the most radical solution, but it might not be appropriate in other contexts.

**Comment by swharden** [comment]
Hi @arthurits, 

Sorry it took me so long to get to this one! It turned out to be pretty complex, but I arrived at a solution I feel good about. Long story short is that `Frame()` is now deprecated, and `Frameless()` accepts an optional argument which allows it to be reversed.

It may be a few more days before these changes get released on NuGet, but it looks like this issue is finally resolved. Thanks again for reporting it and for your extensive analysis!

`Frameless(true)` | `Frameless(false)`
---|---
![image](https://user-images.githubusercontent.com/4165489/128585448-864effe3-53fb-4034-a1bf-89611fae39ff.png)|![image](https://user-images.githubusercontent.com/4165489/128585452-aabd6ef1-5611-4966-8b04-36c63208cb70.png)

**Comment by swharden** [comment]
Following-up, I'm not 100% sure I've arrived at a final API. When calling `Frameless()` the title disappears, which some users may find astonishing. I'll consider how to proceed! Work is in #1192

If you want a title and a square frame around the plot it looks like this works

```cs
var plt = new ScottPlot.Plot(600, 400);

double[,] values = {
    { 78,  83, 84, 76, 43 },
    { 100, 50, 70, 60, 90 }
};

plt.AddRadar(values);

plt.Frameless(false); // required to make room for the title and axis lines

plt.Title("Illuminance Distribution");
plt.XAxis.Ticks(false);
plt.YAxis.Ticks(false);
plt.XAxis2.Ticks(false);
plt.YAxis2.Ticks(false);
```
