### ISSUE TITLE
ScottPlot.WPF DispatcherTimer memory leak

### ISSUE THREAD

**Issue by RamsayGit** [ScottPlot/ScottPlot#1115]
**ScottPlot Version:** 4.1.16

**Operating System:** Windows 10

**Application Type:** ScottPlot.WPF

**Bug Description:** 
I noticed a memory leak in my application using JetBrains Memory Profiler tool (dotMemory). I open and **close** many plots with their associated data during the application lifespan and the memory just keeps increasing indefinitely, I suspect a dispatcher timer created in WpfPlot.xaml.cs at line 43 (PlottableCountTimer) is the cause since it is never disposed after creation (unsubscribe from Tick event and call Stop function) therefore making it impossible to be collected by GC. I suggest making WpfPlot IDisposable to handle proper disposal of PlottableCountTimer.

Currently there is no disposal of `PlottableCountTimer_Tick`:

https://github.com/ScottPlot/ScottPlot/blob/3ead8c204116ea95baed60df6715b70cd668beab/src/controls/ScottPlot.WPF/WpfPlot.xaml.cs#L112-L114

**Comment by bclehmann** [comment]
I am able to replicate this as well. I forced GC in the Visual Studio profiler and several objects associated with `DispatcherTimer` persist:

![image](https://user-images.githubusercontent.com/8635304/121270950-e26b0b80-c87f-11eb-80ae-24ba512a8fc3.png)

Adding the following event handler to [`FrameworkElement.Unloaded`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.unloaded?view=net-5.0) removes these objects:

```cs
private void WpfPlot_Unloaded(object sender, System.Windows.RoutedEventArgs e)
{
    PlottableCountTimer.Tick -= PlottableCountTimer_Tick;
    PlottableCountTimer.Stop(); // I don't know if both these are necessary or just `Stop()`
}
```

I am unsure if this is the only memory leak, I am not particularly experienced with profiling. I'm also unsure if `Unloaded` is the right event to use for cleanup. I do still find it strange that `DispatcherTimer` doesn't implement `IDisposable` but c'est la vie.

**Comment by Orace** [comment]
According to [this SO response](https://stackoverflow.com/a/5111366/361177) and [this one](https://stackoverflow.com/a/25510873/361177), call `Stop()` on the timer is enough.
