### ISSUE TITLE
Ticks: Hide major tick marks but show major tick labels

### ISSUE THREAD

**Issue by kegesch** [ScottPlot/ScottPlot#1118]
## Features Suggestion

**Feature description:** Currently it is prevented to hide major axis ticks when the label of the ticks should be shown. It would be nice to hide them seperately). 

**Suggested Code example:** The method for this already exists and the parameters for this as well. However, the behaviour would be slightly different.

```cs
WpfPlot.Plot.YAxis.Ticks(true, false, true); // major, minor, major labels
```

**Current Implementation:** Currently the last param for major labels can only be used to hide the lables but keep the major ticks and not the other way round.https://github.com/ScottPlot/ScottPlot/blob/a22b3c36dc084f0bf4e0689e13be294799d72a34/src/ScottPlot/Renderable/Axis.cs#L308-L313

**Comment by swharden** [comment]
I'm adding a new `GetSettings()` method to axes which returns normally-private objects that have public methods you can mess with for deep customization. The warning message indicates the API may not be stable through future versions of this software. This should help you get un-stuck! You can sit major tick length to zero.

```cs
(var axisLabel, var axisTicks, var axisLine) = formsPlot1.Plot.YAxis.GetSettings(showWarning: false);
axisLabel.Label = "super custom";
axisTicks.MajorTickColor = Color.Orange;
axisTicks.MajorTickLength = 20;
axisTicks.MinorTickColor = Color.Blue;
axisTicks.MinorTickLength = 10;
axisLine.Width = 5;
```
![image](https://user-images.githubusercontent.com/4165489/128445117-aec0d9f9-9960-4d04-8feb-ff9bd85bcd65.png)

**Comment by swharden** [comment]
Hey @kegesch, thanks for this suggestion! I'm surprised it took me almost 2 months to get to 😅

I'm glad this issue inspired creation of the `GetSettings()` method, but after re-reading your original comment I agree there should be a more elegant way to do this and will implement the API you suggest. Thanks again for recommending it!

**Comment by swharden** [comment]
> Currently it is prevented to hide major axis ticks when the label of the ticks should be shown. It would be nice to hide them seperately)

Looks good now 👍 🚀 

```cs
// hide major tick marks (but not labels)
formsPlot1.Plot.YAxis.Ticks(major: false, minor: true, majorLabels: true);

// make ticks 0 to allow labels to be placed close to the edge of the plot
(_,var ticks, _) = formsPlot1.Plot.YAxis.GetSettings(showWarning: false);
ticks.MajorTickLength = 0;
```
![image](https://user-images.githubusercontent.com/4165489/128446474-45adb831-e8a8-4a51-98ff-2a649d660744.png)
