### ISSUE TITLE
Two vertical axis?

### ISSUE THREAD

**Issue by cosmicDustOfLightLength** [ScottPlot/ScottPlot#1119]
Hi,
Can you somehow set up two vertical axes?
Any ideas?
For example, I would like to have temperature and humidity in one graph.

![obraz](https://user-images.githubusercontent.com/71566296/121776715-bb1d8280-cb8e-11eb-987b-5812bddf31cc.png)
![obraz](https://user-images.githubusercontent.com/71566296/121776697-9cb78700-cb8e-11eb-9a90-702d092daf20.png)

**Comment by swharden** [comment]
Hi @cosmicDustOfLightLength, 

Yes, multiple Y axes are possible: https://swharden.com/scottplot/faq/multi-axis
