### ISSUE TITLE
Line Plot: Show position label on axis

### ISSUE THREAD

**Issue by EmanuelFeru** [ScottPlot/ScottPlot#1122]
**Feature description:** 

It would be very nice to have the posibility of tooltip for Draggable axis similar to crosshair tooltip #1093

```cs
VLine vLine = new VLine();
vLine = formsPlot.Plot.AddVerticalLine(0);
vLine.DragEnabled = true;
vLine.LabelEnabled = true;   // new

HLine hLine = new HLine();
hLine = formsPlot.Plot.AddHorizontalLine(0);
hLine.DragEnabled = true;
hLine.LabelEnabled = true;   // new
```

**Comment by swharden** [comment]
Hi @EmanuelFeru, by a "draggable axis" do you mean you want an axis (the axis line, tick, tick marks, label, etc) to be draggable by click-dragging it?

![image](https://user-images.githubusercontent.com/4165489/122063388-387b0a00-cdbe-11eb-973b-1c9fb77e383f.png)

If this is what you meant, it's a pretty complex task to make the _axes_ draggable so it seems unlikely to be achieved soon.

However, a new _plot type_ could be created (nearly identical to the draggable axis lines) that draws a line across the plot but also adds ticks and labels at certain positions to achieve a nearly identical effect. 

Alternatively the existing axis lines could be extended to add optional ticks and tick labels. This may be the easiest way to achieve this effect rapidly.

**Comment by swharden** [comment]
Hi @EmanuelFeru, after reading your message again an alternative interpretation is that you want the _crosshair axis label_ to be draggable such that click-dragging the label moves the crosshair line.

![image](https://user-images.githubusercontent.com/4165489/122064205-f900ed80-cdbe-11eb-8c8d-b09ebac8362f.png)

If you could clarify your suggestion it will be helpful in evaluating its feasibility 👍

**Comment by EmanuelFeru** [comment]
Hi Scott,

Yes, I meant the 2nd option, showing the cross hair label also in Draggable axis Vertical or Horizontal.

To be more clear, I don't need to drag the label, just dragging the axis (as it is now) and the lable to be displayed and following, exactly same as you did for the cross hair, but now for vertical or horizontal Draggable axis.

**Comment by swharden** [comment]
Thanks for the suggestion @EmanuelFeru! This one took me a while to get to, but I'm finally making progress. I'm combining this with crosshair refactoring #1173, and it looks like we'll have something pretty similar to this shortly:

```cs
var plt = new ScottPlot.Plot(400, 300);
plt.AddSignal(DataGen.Sin(51));
plt.AddSignal(DataGen.Cos(51));

var hline = plt.AddHorizontalLine(.85);
hline.LineWidth = 2;
hline.PositionLabel = true;
hline.PositionLabelBackground = hline.Color;
hline.DragEnabled = true;

var vline = plt.AddVerticalLine(23);
vline.LineWidth = 2;
vline.PositionLabel = true;
vline.PositionLabelBackground = vline.Color;
vline.DragEnabled = true;

Func<double, string> xFormatter = x => $"X={x:F2}";
vline.PositionFormatter = xFormatter;
```

![draggable](https://user-images.githubusercontent.com/4165489/128616405-30b0b5f6-ecf1-4257-bffb-8907b02dcd3e.gif)

**Comment by EmanuelFeru** [comment]
Looks very good, exactly what I need. Thank you!

**Comment by EmanuelFeru** [comment]
Very quick question Scott before I start coding, is there a performance impact due to drawing the `PositionLabel`?

**Comment by swharden** [comment]
> Very quick question Scott before I start coding, is there a performance impact due to drawing the PositionLabel?

Technically yes, but it's extremely minor. The difference is effectively negligible 👍
