### ISSUE TITLE
How to drag a point/points in scatter plot

### ISSUE THREAD

**Issue by telarita** [ScottPlot/ScottPlot#1124]
## Question Template

**ScottPlot Version:** 4.1.16

**Operating System:** Windows

**Application Type:** WPF

**Question:** How can I drag a point and a group of points in a scatter plot?

Thank you!

**Comment by swharden** [comment]
Hi @telarita, 

Points in scatter plots cannot be click-dragged at this time. Right now the only mouse-draggable plot types are axis lines (vertical line and horizontal line).

@StendProg created a related PR I have not reviewed yet (#1111) which allows whole plots to be dragged, but it doesn't look like individual points can be manipulated.
