### ISSUE TITLE
BarPlot: Rendering error when using horizontal orientation

### ISSUE THREAD

**Issue by ChrisAtVault** [ScottPlot/ScottPlot#1133]
## Bug Report Template

**ScottPlot Version:** 4.1.16

**Operating System:** Windows 10

**Application Type:** WinForms

**Bug Description:** In ticket  #461 someone complained about a bug regarding negative values in a bar plot and mentioned that waterfall charts are a generalization of grantt charts. Furthermore a picture was presented with a nice grantt chart was presented [https://user-images.githubusercontent.com/8635304/84607827-ae2b5d80-ae6c-11ea-9504-eff3e8d012b1.png](url). Seeing this picture i wanted to create a horizontal bar plot as some sort of grantt chart with the following result: 

![image](https://user-images.githubusercontent.com/79156810/123638902-f91dd600-d81f-11eb-8faa-b74b2223207e.png)

When reading the code below, it is clear that the x- and y-axis are completely off (or I might just be a random time traveler with bad numerical skills 😄  .)

**Reproducing:** Add ScottPlot.FormsPlot to a new Form and execute the following lines of code.

```cs
public enum Variants
{ 
    man = 1,
    rea = 2,
    lifg= 3,
}

public Form1()
{
    InitializeComponent();
    double[] values = new double[] { (double)Variants.man, (double)Variants.rea, (double)Variants.lifg };
    double[] dates = new double[] { DateTime.Now.AddDays(-1).ToOADate(), DateTime.Now.ToOADate(), DateTime.Now.AddDays(1).ToOADate() };
    double[] offset = new double[] { (double)Variants.man, (double)Variants.rea, (double)Variants.lifg };

    var bar = this.formsPlot1.Plot.AddBar(values, dates);
    bar.Orientation = ScottPlot.Orientation.Horizontal;
    bar.ValueOffsets = offset;
    this.formsPlot1.Plot.XAxis.DateTimeFormat(true);
}
```

**Comment by audun** [comment]
This isn't related to the type of plot, it's a problem with the axis. It's caused by the conversion from doubles between -1 and 1 to DateTime. See comments in PR #807 for an explanation.

**Comment by audun** [comment]
Sorry, I was a bit too quick and misread your code. Didn't see the `Now` and thought your dates were literally between -1 and 1. 

It appears that in the Orientation.Horizontal case the axes are switched. In your screenshot you can see the date conversions on the Y-axis. Setting the Y-Axis to DateTimeFormat instead results in:

![image](https://user-images.githubusercontent.com/454644/124795823-c75bec00-df50-11eb-8aeb-898e95e02949.png)

**Comment by swharden** [comment]
Hi @ChrisAtVault, I agree with @audun on this one.

If horizontal orientation is used, values will be on the horizontal axis (X), and positions will be on the vertical axis (Y).

If you want to define positions as `DateTime`, you need to make the Y axis a DateTime axis. Your original code example is incorrectly requesting the X axis to display using DateTime units.

```cs
var plt = new ScottPlot.Plot(400, 200);

double[] values = new double[] { 1, 2, 3 };
double[] offset = new double[] { 1, 2, 3 };

DateTime firstDay = new DateTime(1988, 9, 24);
DateTime[] dates = new DateTime[] { firstDay, firstDay.AddDays(1), firstDay.AddDays(2) };
double[] positions = dates.Select(x => x.ToOADate()).ToArray();

var bar = plt.AddBar(values, positions);
bar.Orientation = ScottPlot.Orientation.Horizontal;
bar.ValueOffsets = offset;

plt.YAxis.DateTimeFormat(true);
plt.SaveFig("demo.png");
```

![image](https://user-images.githubusercontent.com/4165489/128618513-466e872a-5fa0-4110-983d-6254fd8547f8.png)
