### ISSUE TITLE
Having trouble with setting Y axis values to the right

### ISSUE THREAD

**Issue by Identekit** [ScottPlot/ScottPlot#1136]
**ScottPlot Version:** 4.1.16
**Operating System:** Windows 10
**Application Type:** WPF

**Question:** I am trying to set up a simple plot with Y-Axis values on the right with axis limits at 20 and 80.  I am noticing that when values are on the left I see the expected values of 20 at the bottom left and 80 and the upper left. 
![Image 1](https://user-images.githubusercontent.com/57924280/123898230-d1ab3400-d919-11eb-942f-67c65d102122.png)

However, when I ad the code to move show the axes values on the right I only see values from -10 to 10 and they do not scale when dragged like when values are on the left. 
![Image 2](https://user-images.githubusercontent.com/57924280/123898274-e4be0400-d919-11eb-9c8c-79da9f20b754.png)

I'm not sure what I am doing wrong...I grabbed the code below from the cookbook.

```cs
wpfPlot.Plot.SetAxisLimitsY(20.0, 80.0);

// From cookbook
wpfPlot.Plot.YAxis.Ticks(false);
wpfPlot.Plot.YAxis.Grid(false);
wpfPlot.Plot.YAxis2.Ticks(true);
wpfPlot.Plot.YAxis2.Grid(true);
wpfPlot.Plot.YAxis2.Label("Value");
wpfPlot.Plot.XAxis.Label("Sample Number");
```

Please advise.
Thanks

**Comment by StendProg** [comment]
Hi @Identekit,

Unfortunately `wpfPlot.Plot.SetAxisLimitsY(20.0, 80.0)` сhanges only the limits of the primary axis, which is always left. Even if it is disabled.

To set limits for the secondary axis, you can use `wpfPlot.Plot.SetAxisLimits()`. It is a bit awkward because it forces you to set the X-axis limits as well. But you can set any limits for the secondary X-axis, without affecting the primary X.

Try this option, it should work for your example:
```c#
wpfPlot1.Plot.SetAxisLimits(0, 1, 20.0, 80.0, 1, 1);
```

**Comment by Identekit** [comment]
@StendProg,
Thank you, that seems to have been the trick.

I encountered another issue putting some horizontal lines on the plot.  It seems that the values for those lines are based off the left axis values.  So I also set left Y-Axis values to the same values to what I set using your suggestion.

```cs
wpfPlot.Plot.SetAxisLimitsY(20.0, 80.0);
wpfPlot.Plot.SetAxisLimits(0, 1, 20.0, 80.0, 1, 1);

// From cookbook
wpfPlot.Plot.YAxis.Ticks(false);
wpfPlot.Plot.YAxis.Grid(false);
wpfPlot.Plot.YAxis2.Ticks(true);
wpfPlot.Plot.YAxis2.Grid(true);
wpfPlot.Plot.YAxis2.Label("Value");
wpfPlot.Plot.XAxis.Label("Sample Number");
```

**Comment by Identekit** [comment]
@StendProg,
Thank you, that seems to have been the trick.

I encountered another issue putting some horizontal lines on the plot.  It seems that the values for those lines are based off the left axis values.  So I also set left Y-Axis values to the same values to what I set using your suggestion.

```cs
wpfPlot.Plot.SetAxisLimitsY(20.0, 80.0);
wpfPlot.Plot.SetAxisLimits(0, 1, 20.0, 80.0, 1, 1);

// From cookbook
wpfPlot.Plot.YAxis.Ticks(false);
wpfPlot.Plot.YAxis.Grid(false);
wpfPlot.Plot.YAxis2.Ticks(true);
wpfPlot.Plot.YAxis2.Grid(true);
wpfPlot.Plot.YAxis2.Label("Value");
wpfPlot.Plot.XAxis.Label("Sample Number");
```
