### ISSUE TITLE
Improve ScottPlot.MultiPlot

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1137]
Multiplot has been marked obsolete for a while, but there isn't a good alternative right now.

Feature ideas:
* multiple plots should have their layouts automatically aligned so the edges of plots line up
* easy way to share X and/or Y axes across plots
* improved addressing of plots
* non-fixed-size plots (perhaps multiple classes for vertically stacked, horizontally stacked, and tiled plots?)

**Comment by VladDuba** [comment]
Well, I build a prototype of EEG records viewer loading multiple channels from EDF. I addressed the issue of coordinated multiple plottable (per recording channel) by creating dynamically a Table Layout container placing a plottable to a cell of the table. The table and plots are all docked fully and thus evenly distributed (or as per columns / rows proportions) and resizing accordingly on a main window resize. The solution a bit "heavy" and axis areas of each plottable take too much client area. 
All of above means that what you suggest has a merit and it would be nice if the library will take care of the multiple plots layout.   
![image](https://user-images.githubusercontent.com/87284119/125211798-f3d87680-e276-11eb-9f18-29d6717700ce.png)

**Comment by VladDuba** [comment]
A different example with two Table layout containers (one embedded to a call(0,0) of another) to demonstrate the multiple plots arrangements with resizing by full dock properties.
![image](https://user-images.githubusercontent.com/87284119/125268398-ab9c7100-e2d5-11eb-825e-ed6c89b76179.png)

**Comment by swharden** [comment]
Thanks for your feedback @VladDuba! It's always awesome to see what people use this library to create.

Your implementation is excellent. Multi-plot applications can be easily created by laying-out multiple controls on a window. Axes and/or layouts can then be matched between different controls to help things line-up.

My goal was to be able to create single-image multi-plot figures as PNG files from console applications. I'd like to use ScottPlot to create figures similar to this one created in Python and save the output as a single image file from a console application.

![19702037_autoanalysis](https://user-images.githubusercontent.com/4165489/128097530-a9f54768-3d5c-41a0-b2dd-9ff0cf7aa71c.png)

I'll probably close this issue for now and revisit it after I refactor ScottPlot to use Microsoft.Maui.Graphics #1036
