### ISSUE TITLE
Is there a way to render window opened by "Open in New Window"?

### ISSUE THREAD

**Issue by CrackAndDie** [ScottPlot/ScottPlot#1146]
**ScottPlot Version:** 4.1.16

**Operating System:** Windows

**Application Type:** WPF

**Question:** I have a program where can be placed some Plots and they render in real time (like in **Live Data** example). But they are quite small, so user can right click on it and select option **Open in New Window**. But when it opens in a new window it doesn't render my real time data. So is there a way to render this opened window?

**Comment by StendProg** [comment]
Hi @CrackAndDie,

Unfortunately, no, basic controls have basic functionality, and the fact that the plot opened in a new window remains unchanged is exactly what is needed for most cases (IMHO).
In fact, the plot in the new window uses the plottable from the main one, and will automatically be synchronized with the main one, but only upon the event of user interaction with the chart in the new window. There is no way to programmatically trigger this event.

The solution for you may be to create a new window not using the context menu of the control, but some of your own logic, say, a separate button in the application:
```c#
private WpfPlotViewer newWindow=null;

public void SomeButtonClick(object Sender, EventArgs e)
{
  newWindow = new PlotViewer(wpfPlot1.Plot);
  newWindow.Show();
}
```
then you just need to call render for stored `newWindow` in those places where you want to be synchronized.
```c#
public void SomeUpdateMethod()
{
  ...

  newWindow.wpfPlot1.Render();

  ...
}
```

In this solution, there are obvious problems with creating multiple windows, or when the user closes the window. But I think you get the main point.
If you have any difficulties with solving these problems, write, we will try to solve them together.

**Comment by CrackAndDie** [comment]
Thank you very much for your answer. But now I have two more questions. I tried to add another ```menuItem``` in the already existing ```rightClickMenu```. Now, when I right-click on a plot, the default menu appears for a moment, and then mine. I need the functions from the default menu to be saved and one more button to create a rendering window. Is there a way to do this?
```cs
plot.RightClicked += DeployCustomMenu;

private void DeployCustomMenu(object sender, EventArgs e)
{
    MenuItem renderWindowMenuItem = new MenuItem() { Header = "Open in render window" };
    renderWindowMenuItem.Click += OpenRenderedWindow;

    ContextMenu rightClickMenu = new ContextMenu();
    rightClickMenu.Items.Add(renderWindowMenuItem);

    rightClickMenu.IsOpen = true;
}

private void OpenRenderedWindow(object sender, RoutedEventArgs e)
{
    // how to get plot on which I've clicked
}
```
Well, the second question. Can I *cast* a plot from a sender to get the plot on which the function was called? Or how can you even get a plot on which the click occurred? Thanks!

**Comment by StendProg** [comment]
As it seems to me, the simplest thing in this case will be to create your own Control. Either through inheritance, but the base control is not very ready for this. Or just copy all the code from https://github.com/ScottPlot/ScottPlot/blob/3ead8c204116ea95baed60df6715b70cd668beab/src/controls/ScottPlot.WPF/WpfPlot.xaml.cs.

Then you can edit the context menu what you want and the event will be called in the context of the Control from which you can easily access the Plot.

From the disadvantages of such a solution, you will be forced to update your control every time changes are made to wpfControl. But lately this happens very infrequently.

If you nevertheless decide to continue going your own way, then the first thing you need to do is to unsubscribe the basic context menu from the RightClicked event.
```c#
   plot.RightClicked -= plot.DefaultRightClickEvent;
```

Then create your own context menu completely, you can borrow the code from https://github.com/ScottPlot/ScottPlot/blob/3ead8c204116ea95baed60df6715b70cd668beab/src/controls/ScottPlot.WPF/WpfPlot.xaml.cs#L206-L231

But here comes the problem with the context that you described.
You can capture the plot that you have in the context of your application, but if there are several of them, then you will have to create your own menu for each, and capture a separete plot in each menu.
```c#
private void OpenRenderedWindow1(object sender, RoutedEventArgs e)
{
    // how to get plot on which I've clicked
   plot1.Render();
}
```

That is why creating your own control seems much easier for me.
In addition, if your extension of the context menu can be useful for most users, then we can add it to the code base of the main control, and forget about synchronization problems.

**Comment by CrackAndDie** [comment]
Thanks for your reply. It looks like I'll have to create just a ```button``` in my application to open a rendered window. It is unlikely that this function will be needed by other users, but nevertheless, if this function will be in the next versions of *Scottplot*, then I will be very grateful to you. Thank you for your help!
