### ISSUE TITLE
3D graphics request

### ISSUE THREAD

**Issue by saklanmazozgur** [ScottPlot/ScottPlot#1151]
Hello there,

ScottPlot is functional and perfect for 2D graphics. Unfortunately, I could not find 3D graphics for the project. Do you have 3D Graphics? Or what are the chances of it coming soon?

Thanks.

**Comment by bclehmann** [comment]
No, there are no 3D graphics capabilities (unless you consider things like heatmaps 3D, as they do convey 3 dimensions, just not 3 spacial dimensions).

It looks like a while ago Scott did get this question: https://github.com/ScottPlot/ScottPlot/issues/129. This is from before I was part of this project but I don't anticipate that too much has changed. 3D plotting is interesting and useful but also ultimately very difficult. You might be better served by Gnuplot or Matplotlib, both of which are very capable scientific plotting libraries, and I think they both have C# bindings. I am not aware of any C# library which does 3D plotting.

**Comment by saklanmazozgur** [comment]
Please don't be offended. I saw your reply late. I'll look into the relevant libraries. Thanks for your recommendations.

**Comment by bclehmann** [comment]
No worries. Good luck.
