### ISSUE TITLE
Pan and zoom each Y axis independently 

### ISSUE THREAD

**Issue by kkaiser41** [ScottPlot/ScottPlot#1158]
## Question Template

**ScottPlot Version:** 4.1.16

**Operating System:** Windows 10

**Application Type:** WinForms

**Question:** Describe your question here

When I have a signal plot with more than 1 Y axis is it possible to pan and zoom each Y axis independently? I saw and example of this in a discussion last year under ScottPlot 5 but there was no explanation on how to do this. I have check the cookbook and that showed me exactly how to make multiple Y axis but they are always locked together.

**Comment by kkaiser41** [comment]
This link shows the functionality I am trying to achieve. Any idea how to do this?

https://github.com/ScottPlot/ScottPlot/issues/162#issuecomment-704977569

**Comment by swharden** [comment]
I'll close this issue and work on it in #1179
