### ISSUE TITLE
ScottPlot not able to handle `NaN` data points

### ISSUE THREAD

**Issue by EmanuelFeru** [ScottPlot/ScottPlot#1161]
**ScottPlot Version:** 4.1.16
**Operating System:** Win10
**Application Type:** WinForms

**Bug Description:** At the moment it appears that ScottPlot is not able to handle data in which some data points are `NaN`. Expected behavior is that Scottplot will not display those points.

I have seen #546 to enable the diagnostic for every render. Is there a way to disable only the diagnostic for `NaN`? So, that the data is still displayed with missing points. I am using `AddSignalConst(..)` to plot my data.
If ScottPlot needs continuos line of data for speed, then is ok and I will use the Workaround below.

**Workaroung:** For now I check for `NaN` in my data and set those points to `0`. However, I would like to keep those `NaN` because it could be a question mark for the user to see this "anomaly" and take action to fix the system that generates the data.

Screenshoot with the error:
![image](https://user-images.githubusercontent.com/24780745/126298484-a262e619-d1ac-43ee-83a0-2a1f6fb23933.png)

Call stack:
![image](https://user-images.githubusercontent.com/24780745/126299626-a1d4733f-665c-4f6d-ae77-8882212d8795.png)

**Comment by StendProg** [comment]
Hi @EmanuelFeru,

There is no way to work with NaN in a `Signals` (this will require a bunch of additional checks and kill all performance), and I think that it is not needed. The best we can do is throw out the exeption when such data is found in diagnostic mode, and this has already been implemented.

As for your problem, you can solve it using `PlottableSignalXYConst`, by simply throwing out points containing NaN:
```
var XYPairs = YData.Select( (y, i) => (i, y)).Where( p => !Double.IsNaN(p.y));
var xs = XYPairs.Select( p => p.i).ToArray();
var ys = XYPairs.Select( p => p.y).ToArray();
plt.AddSignalXYConst(xs, ys);
```
Of course you will need to add the sampling rate and offset to the index (i) to X coordinate projection, but I think you get the point.

**Comment by EmanuelFeru** [comment]
Ok, I understand the background. Then we can close this one. Thank you.

**Comment by greatawesome** [comment]
There is some utility to handling NaN rather than tossing points out. In ZedGraph, using NaN as a data point causes a break/gap in the line, whereas just tossing out the point would mean you connect the previous and next points when drawing the line. Having a gap is a nice visible way to see that a data point is missing.

**Comment by swharden** [comment]
> There is some utility to handling NaN rather than tossing points out ... having a gap is a nice visible way to see that a data point is missing

Hi @greatawesome, this point is well-received! This topic comes up from time to time. Doing NaN checks and rendering multiple lines in scatter plots would degrade performance. This may change after the rendering system is refactored #1036 so I'll revisit this idea in ScottPlot 5! I'm adding this topic to the triage list to revisit then 👍 #1028

Connecting the dots (pun intended) this topic is addressed in the FAQ: https://swharden.com/scottplot/faq/nan
