### ISSUE TITLE
Performance: interactivity is slow if Visual.Render() is overridden

### ISSUE THREAD

**Issue by Xwilarg** [ScottPlot/ScottPlot#1162]
**Bug Description:** When display a huge amount of points, ScottPlot is lagging a lot, especially when you're trying to move in the graph

**Reproducing:**

```cs
AvaPlot plot = this.FindControl<AvaPlot>("Plot");
var random = new Random();
plot.Plot.AddScatter(
    xs: Enumerable.Range(0, 10000).Select(x => (double)x).ToArray(),
    ys: Enumerable.Range(0, 10000).Select(x => (double)random.Next()).ToArray()
);
```

### System Information
* **ScottPlot Version:** 4.1.16
* **Operating System:** Windows 11 / Ubuntu 20.04
* **Application Type:** Avalonia

**Comment by bclehmann** [comment]
It looks like your points are evenly spaced apart on the X-axis. This means you should be able to use a signal plot instead of a scatter plot. Signal plots are must faster for large data sets, they can easily handle sets in excess of 10 million points.

**Comment by Xwilarg** [comment]
Well this is just an example but basically I need to reproduce a manhattan plot and my points won't be evenly spaced

**Comment by FoggyFinder** [comment]
Can you attach a small test project?

**Comment by Xwilarg** [comment]
[Test-Performance.zip](https://github.com/ScottPlot/ScottPlot/files/6863938/Test-Performance.zip)
Here is one

**Comment by bclehmann** [comment]
I am unfamiliar with your overriding of `Visual.Render(DrawingContext context)` in `MainWindow.axaml.cs`. I wonder if `Visual.Render` is called everytime that the control needs to be redrawn. This is bad, because you're initializing a lot of data in this function.

I would move all of it to the constructor, or another function guaranteed to be called only once on startup.

**Comment by swharden** [comment]
Hi @Xwilarg, @bclehmann is correct I think the problem is that you should not override `Visual.Render()`. ScottPlot automatically decides when to re-render, making it more performant.

## Don't do this

```cs
public MainWindow()
{
    InitializeComponent();
}

public override void Render(DrawingContext context)
{
    AvaPlot plot = this.FindControl<AvaPlot>("Plot");
    var random = new Random();
    plot.Plot.AddScatter(
        xs: Enumerable.Range(0, 10000).Select(x => (double)x).ToArray(),
        ys: Enumerable.Range(0, 10000).Select(x => (double)random.Next()).ToArray()
    );
}
```

## Do this (it's a lot faster)

```cs
public MainWindow()
{
    InitializeComponent();

    AvaPlot plot = this.FindControl<AvaPlot>("Plot");
    var random = new Random();
    plot.Plot.AddScatter(
        xs: Enumerable.Range(0, 10000).Select(x => (double)x).ToArray(),
        ys: Enumerable.Range(0, 10000).Select(x => (double)random.Next()).ToArray()
    );
}
```

**Comment by swharden** [comment]
Also, FWIW, I'm a little confused about an AvaPlot being used in a Windows WPF project. I would have expected to see a WpfPlot 🤔 

I don't have much Avalonia experience though. Is this a mistake, or is there some cross-platform fanciness going on here?

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.10.6" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.6" />
    <PackageReference Include="Avalonia.Diagnostics" Version="0.10.6" />
    <PackageReference Include="ScottPlot.Avalonia" Version="4.1.16" />
   </ItemGroup>
</Project>
```
