### ISSUE TITLE
Controls: Remove timer-based auto-render system

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1165]
This issue tracks discussion/PRs related to removal of the automatic render system.

**Problem:** After adding data to a `Plot` in a user control, that control's `Render()` must be called to display the change. Currently there is an auto-render system which periodically checks the number of plottable objects and calls `Render()` if it changes. This timer system is prone to memory leaks and may also result in unwanted renders at inopportune times (#1117). 

```cs
formsPlot1.Plot.AddScatter(xs, ys);
formsPlot1.Render(); // <-- this line is required if automatic renders are disabled
```

**Upgrading:** If the auto-render functionality is removed, users who upgrade will have to add the `Render()` line themselves. To make this more obvious an error message will be displayed on the plot when the debugger is attached if the control is displayed but the user never called `Render()` on start-up.

![image](https://user-images.githubusercontent.com/4165489/126996033-c93d47a2-75b7-4a35-921d-b7a183636d96.png)

**Comment by gigios** [comment]
Sorry but for me it's not clear how update my code 🤔
First I initialize the plot by setting some properties and adding my 'signalplot' values, then I call the Render method (at the end of all the plot initialization).
Probably the problem on my side is that, when update the values data of my plot, I'm using the RenderRequest of the WpfPlot control.
If instead to use the RenderRequest I'm using the Render method the warning message disappear and the plot is shown correctly.

Is it wrong to use the method RenderRequest?

**Comment by swharden** [comment]
@gigios thank you for reporting this! This is a bug and I'll track its progress in #1251

A temporary fix is to disable the warning
```cs
formsPlot1.Configuration.WarnIfRenderNotCalledManually = false;
```
