### ISSUE TITLE
Bug with EqualScaleMode.ZoomOut, behaves like ZoomIn

### ISSUE THREAD

**Issue by noob765** [ScottPlot/ScottPlot#1171]
**Bug Description:** 
```cs
Plot.AddScatter(x, y);
Plot.AxisAuto();
Plot.AxisScaleLock(true, EqualScaleMode.ZoomOut);
```

It's my very first day playing with this so I won't claim to be an expert here but based on everything I've seen after cloning the project and going through the testing folder, I'm expecting the previous 3x lines to:

1. plot an xy scatter line

2. resize the axes in a zoom to fit fashion so as to make everything visible (in this case, all the line)

3. lock the axes at an x:y aspect ratio of 1:1 (so that circles are not ellipses and squares are not rectangles) ***WHILE MAINTAINING EVERYTHING ZOOMED TO FIT*** (the upper case part is the bug)

(1)-(2) work just fine. (3) locks the axes at 1:1 alright, but instead of ZoomingOut as the option says, ZoomsIn... so if I plot a thin flat but long line of noise, the end result is a very narrow view of a few points with the plot spilling big time on both ends. Manually zooming out reveals the whole line.

As I said, I cloned the repo so I peeked in to settings.cs, line 268 which is where EqualScaleMode.ZoomOut is handled:

https://github.com/ScottPlot/ScottPlot/blob/cabadfd153db0d563947977afa3965061c50dde5/src/ScottPlot/Settings.cs#L268-L273

I didn't single step that code directly, but I did replicate it in my app code trying to figure out what was going on. The answer is simple (though weird): If you're expecting X/YAxis.Dims.UnitsPerPx to be units per pix (ie, **positive**), then this should work but **both UnitsPerPix are negative!** (the scale is good, but the sign is... well, 'wrong'?). I'm assuming there's a good under the hood reason for this but the end result is that the Math.Max statement as line 269 must really be Math.Min (or more robust: max(abs(x), abs(y)) with abs on both 270 and 271 too to remove all signs)

In my replication code, If I replace 269 to Math.Min to get the largest negative number, everything behaves as expected... 
(though middle mouse zoom to fit doesn't work right so the fix should really be deep inside the package and not just a superficial homebrewed patch as I've done... This is when I registered for github and wrote all this)

Hopefully there's enough details in there to get you on track (I'm in the process of learning C# and this package is outstanding).

### System Information
* **ScottPlot Version:** 4.1.16
* **Operating System:** Win10 x64
* **Application Type:** WPF

**Comment by bclehmann** [comment]
I don't have time to look into this now, but if `UnitsPerPx` is negative that implies either `AxisDimensions.Span` or `AxisDimensions.DataSizePx` are negative.

`UnitsPerPx` getter:
```cs
public double UnitsPerPx => Span / DataSizePx;
```
https://github.com/ScottPlot/ScottPlot/blob/master/src/ScottPlot/Renderable/AxisDimensions.cs#L26

**Comment by bclehmann** [comment]
It appears that `DataSizePx` is negative on startup on both the X and Y axes. The issue does not appear if the plotting control was already loaded, even if you call `WpfPlot.Reset()`

The culprit is [`AxisDimensions.SetPadding`](https://github.com/ScottPlot/ScottPlot/blob/cdc376bed42804ba8fdf49b22cd07112173e925c/src/ScottPlot/Renderable/AxisDimensions.cs#L57-L61)

When `FigureSizePx` has not yet been initialized and the padding is non-zero we end up with a negative `DataSize`, which is causing your issue if you can call `AxisScaleLock` before `Resize` is called with proper arguments.

Constraining `SetPadding` to only run if `FigureSizePx` has ran results in this: 
![image](https://user-images.githubusercontent.com/8635304/127754288-8fdbce68-b3dd-425a-8ba8-690ac70bca5e.png)

This is still wrong, but I'm not sure what the cause is.

However, noting that this only happens on startup makes me think that you can work around this by delaying your plotting calls. For example, if you run them in the constructor maybe you should run them after `InitializeComponent` (or perhaps even later, I'm not sure quite what the order of execution is in WPF).

**Comment by noob765** [comment]
I just checked... in the problem as reported, all my calls are done after InitializeComponent(). In fact everything is deep inside a results update method that runs well after a ton of other stuff is in place.
For giggles, I tried a Plot.Reset() call before the plotting code: UnitsPerPx now reports as infinity on both axes, but the resulting visual is still zoomed in... (ie, no change).
My takeaway at this point is that while my original suggestion of max(abs(x), abs(y)) would probably solve the issue both on startup and thereafter (with both right and wrong states), it doesn't address the root cause which is really a negative pixel scaling coming from upstream. I'm relieved this wasn't an actual design decision, that said I'm afraid I just don't know enough about the innards of this thing to diagnose this in any more detail (at least not without a significant investment of energy to get a feel for how everything plays together. It's not like I'm comfortable with my current level of knowledge...).
Thanks for all the help

**Comment by bclehmann** [comment]
It still behaves incorrectly on startup even if we prevent negative numbers from being passed in. I suspect that the negative `UnitsPerPx` and the incorrect zooming behavior come from the same issue, `Resize` being fired on controls which do not yet have dimensions.

**Comment by noob765** [comment]
I did some more tests using the WpfControl demo (tweaked specifically to exercise the ZoomOut mode):
The problem is indeed that anything happening inside the control constructor works with a FigureSizePx =1, and that property stays that way until the UI renders after exiting the constructor.
A quick fix I found is to add an "Activated" event handler on the window which links to this:

private void WpfConfigWindow_Activated(object sender, EventArgs e)
        {
            wpfPlot1.Plot.AxisScaleLock(true, EqualScaleMode.ZoomOut);
            wpfPlot1.Render();
        }

The point is, this runs after the window shows up, and the result is more inline with expectations. (I checked: unfortunately, there's no Activated event on a UserControl. Would have been nice to work this into the plot itself). If there's no clean way to work this in the control itself, it would probably be nice to document it somewhere...

**Comment by swharden** [comment]
Hi @noob765, thanks for opening this issue! Sorry it took me so long to get to this one. Thanks for your input too @bclehmann.

> if I plot a thin flat but long line of noise, the end result is a very narrow view of a few points with the plot spilling big time on both ends. Manually zooming out reveals the whole line.

I'm trying to recreate this issue but am struggling. The images appear as I would expect them based on the enumeration passed in to `AxisScaleLock()`. How is the current behavior different than expectation? Is there a code example better than this one which does a better job demonstrating the issue?

```cs
[TestCase(EqualScaleMode.Disabled)]
[TestCase(EqualScaleMode.PreserveX)]
[TestCase(EqualScaleMode.PreserveY)]
[TestCase(EqualScaleMode.ZoomOut)]
public void Test_ScaleLock_1171(EqualScaleMode scaleMode)
{
    ScottPlot.Plot plt = new(400, 300);

    plt.AddSignal(DataGen.Sin(51));
    plt.AddSignal(DataGen.Cos(51));
    
    plt.AxisAuto();
    plt.AxisScaleLock(true, scaleMode);
    plt.Title(scaleMode.ToString());
    TestTools.SaveFig(plt, scaleMode.ToString());
}
```

![image](https://user-images.githubusercontent.com/4165489/130705891-0ec252c4-e6cb-43f3-bbb4-4b81a639ff31.png)
![image](https://user-images.githubusercontent.com/4165489/130705905-d88f9cef-3689-4f9c-a17d-373d627a842f.png)
![image](https://user-images.githubusercontent.com/4165489/130705928-ea7d03b9-fc16-4eaa-ae77-4c2deaa7597d.png)
![image](https://user-images.githubusercontent.com/4165489/130705917-09304784-92b5-4f18-845f-94c41c0210b5.png)

The behavior is described for each enumeration:
https://github.com/ScottPlot/ScottPlot/blob/6713c467c386cf729625fee2f18bfa3c9b2a8a1a/src/ScottPlot/Enums/EqualScaleMode.cs#L6-L32

**Comment by noob765** [comment]
Hi @swharden. If you look at my latest, the issue was actually waaaay deeper in that the plot was being rendered without any figure size available and that trickled down in the visual. Waiting for the window to show up did solve the issue. I saw something above about a PlotInitialized event (?) but I haven't had time to look into it.
So as far as the exact issue goes, I think this can be closed. I'm thinking new users might like a note about the sequence of things and the use of PlotInitialized... 
On to 1197... :)

**Comment by swharden** [comment]
> issue was actually waaaay deeper in that the plot was being rendered without any figure size available and that trickled down in the visual

Okay, now I understand. Since my test case was a console application, it explains my confusion why I was unable to recreate the issue. Tanks for clarifying!

> I saw something above about a PlotInitialized event (?) but I haven't had time to look into it.

#1191 (closed)

> So as far as the exact issue goes, I think this can be closed. 

> On to 1197... :)

See you there! 😉
