### ISSUE TITLE
Demo: Pan and zoom one axis at a time

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1179]
### Discussed in https://github.com/ScottPlot/ScottPlot/discussions/1176 and #1158

<div type='discussions-op-text'>

<sup>Originally posted by **kkaiser41** August  3, 2021</sup>
I am trying to independently pan and zoom individual axis on a multiple axis plot. The link below shows the functionality I am trying to achieve. Any ideas how to do this? https://github.com/ScottPlot/ScottPlot/issues/162#issuecomment-704977569

![](https://user-images.githubusercontent.com/4165489/91741604-f52f1200-eb82-11ea-9361-17641d9f2b96.gif)

</div>

**Comment by EmanuelFeru** [comment]
I might use multiaxes in the future. In the way I use it, I have always the legend with signals next to the plot, so what you have more or less applies to me:
* no signal selected, zoom all axes
* specific signals selected (can be multiple in my case), zoom the selected axes
![image](https://user-images.githubusercontent.com/24780745/128131311-df781575-8279-4bc9-b178-7dbaaa720d71.png)

I think the question is how to do it with just the plot... maybe then two modes:
*  Manual mode (user to provide selection in the code), this is the situation I have and what you presented.
      - This manual mode is useful because, in my case, to save space, I would prefer to only display the Y axis for the selected signal, e.g., if one signal is selected (show only one Y axis, all the other Y axes are hidden/not shown).
      - Default zoom (no axes selected): all axes zoomed together.
*  Auto mode (all Y axes shown):
      - Selection: user clicks the specific Y axis area, this selects the axis to be zoomed. With "Ctrl" key pressed, used can select more than one axis
      - Reset: With "Ctrl" key pressed, user clicks inside the plot area, then we go to Default zoom
      - Default zoom (no axes selected): all axes zoomed together.

**Comment by kkaiser41** [comment]
How are you zooming only the selected Y axis?

I feel like I am overlooking how to address each Y axis separately. From what I have seen so far pan and zoom are hooked to the primary axis.

I am new to ScottPlot so I apologize if I am just missing that part.

**Comment by swharden** [comment]
> How are you zooming only the selected Y axis?

The functionality shown in the screenshot is from an old beta version of ScottPlot. This functionality is not currently possible in ScottPlot, but I hope to add it shortly.

## Notes

Using panning as an example, the event is not axis aware:

https://github.com/ScottPlot/ScottPlot/blob/d7995506e4aec248bca11e0b95c368fb544d1a2e/src/ScottPlot/Control/EventProcess/Events/MousePanEvent.cs#L24-L29

The method it calls equally transforms all axes:

https://github.com/ScottPlot/ScottPlot/blob/d7995506e4aec248bca11e0b95c368fb544d1a2e/src/ScottPlot/Settings.cs#L390-L397

The method it calls equally transforms all axes:

https://github.com/ScottPlot/ScottPlot/blob/d7995506e4aec248bca11e0b95c368fb544d1a2e/src/ScottPlot/Settings.cs#L149-L170

## Possible Solution

Rather than listing which axes are active, axes may benefit from a flag indicating they are locked. Attempting to pan/zoom a locked axis produces no effect. Usage could look something like

```cs
formsPlot1.Plot.YAxis.Lock(true);
```

**Comment by swharden** [comment]
I'm making progress in #1210! It looks like the new API may be

```cs
formsPlot1.Plot.YAxis.LockLimits(true);
```

![multi](https://user-images.githubusercontent.com/4165489/129992775-9e4b06e6-356b-4526-b69d-da370b2bbadd.gif)

**Comment by wangyexiang** [comment]
Dear sir, how to reset the curve after pan or zoom? I want to show my original curve which is before pan or zoom by clicking one button.
