### ISSUE TITLE
Signal Plot: Is vertical orientation possible?

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1194]
**This issue will explore feasibility of creating vertical signal plots.** The signal plot type is one of the most complex, with many features that would have to be refactored (e.g., color by density) making this task very challenging. An alternative option is to create a new `VerticalSignal` plot type with minimal features.

### Discussed in https://github.com/ScottPlot/ScottPlot/discussions/1184

<div type='discussions-op-text'>

<sup>Originally posted by **gigios** August  5, 2021</sup>
First of all I apologize if the question has already been asked, but I have not found it 😊
I'm investigating the functionality of the library to be able to draw a graph with thousands of values (signal).
My problem is that I need to show 10 charts with the sample rate in the Y axis and values in X.
Exists a simple way to do this with the Signal plot?

What I need is similar to this photo
![image](https://user-images.githubusercontent.com/8749627/128358831-4ce44d32-4bf7-46f4-a010-5299beb3b063.png)

I need to replicate a similar visualization in my wpf app with the possibility to scroll all the signals in vertical and, if there are more than 10 charts, scroll also in horizontal (but the scroll I think is not a problem).

A possible solution could be rotate the Wpf Plot Control of 90 degree, but in this way I need also to rotate the Axis labels.

Thanks for any suggestion.</div>

**Comment by gigios** [comment]
I have added, [in the discussion](https://github.com/ScottPlot/ScottPlot/discussions/1184#discussioncomment-1148046), a first test of a possible workaround in the Wpf application, where it's very easy to rotate controls. I have only some troubles on place the axis labels in the correct position, but this is probably a my problem because it's the first time I'm using the 'ScottPlot' 😊

**Comment by gigios** [comment]
With the WPF workaround (LayoutTransform\RotateTransform in xaml) and the last version of the ScottPlot I'm able to 'simulate' a vertical orientation for the signal plot 👍
Now there is only a small problem related the position of the axis label because are too close to the chart. This probably depends how the rotation is applied to the label text.

This is the WpfSample, where I have rotated the control in the xaml (90 degree) and also the Axis Y2.
![image](https://user-images.githubusercontent.com/8749627/131335259-592062bc-e954-438d-a9e7-b526d7de8b08.png)

**Comment by swharden** [comment]
## Rotated ScottPlot Control

![image](https://user-images.githubusercontent.com/4165489/131932195-7308e0a3-5b2f-43e6-8751-396479dee99e.png)

```xaml
<DockPanel>
    <DockPanel.LayoutTransform>
        <RotateTransform 
            CenterX="0.5"
            CenterY="0.5" 
            Angle="90"/>
    </DockPanel.LayoutTransform>
    <ScottPlot:WpfPlot Name="WpfPlot1"/>
</DockPanel>
```

```cs
public MainWindow()
{
    InitializeComponent();

    WpfPlot1.Plot.AddSignal(ScottPlot.DataGen.Sin(51));
    WpfPlot1.Plot.AddSignal(ScottPlot.DataGen.Cos(51));

    // hide original vertical axis
    WpfPlot1.Plot.YAxis.Ticks(false);
    WpfPlot1.Plot.YAxis.Label("Title");

    // vertical axis (when rotated)
    WpfPlot1.Plot.XAxis.Ticks(true);
    WpfPlot1.Plot.XAxis.TickLabelStyle(rotation: 90);

    // horizontal axis (when rotated)
    WpfPlot1.Plot.YAxis2.Ticks(true);
    WpfPlot1.Plot.YAxis2.TickLabelStyle(rotation: 90);

    WpfPlot1.Render();
}
```

**Comment by gigios** [comment]
Perfect, thanks.
Do you think to release a new nuget update in a short time? Otherwise I will try to use directly the source code to do my additional tests 👍

**Comment by swharden** [comment]
> Perfect, thanks.

Sure thing! I'm happy with the outcome here.

> Do you think to release a new nuget update in a short time?

I'll make a NuGet release after I finish #1242 which I anticipate completing today or tomorrow 👍

**Comment by zeticabrian** [comment]
```
>     // horizontal axis (when rotated)
>     WpfPlot1.Plot.YAxis2.Ticks(true);
>     WpfPlot1.Plot.YAxis2.TickLabelStyle(rotation: 90);
 ```

Its great that teh tick labels can be rotated, but unfortunately this leaves the title for YAxis2 (the new horizontal axis) upside down. Is there any means to rotate the axis titles? 

My rotated implementation (left) compared with standard implementation (right):
![image](https://user-images.githubusercontent.com/22105695/160949834-5eae089c-e57f-4255-ad48-d3572d8effb2.png)

**Comment by swharden** [comment]
> Is there any means to rotate the axis titles?

Thanks for this question! Currently no, but it seems like an oversight. I created #1754 to address this deficiency and anticipate I can add this features in the next few days. I'll post updates on that issue page 👍
