### ISSUE TITLE
Axis: Secondary axis tick labels do not support rotation

### ISSUE THREAD

**Issue by gigios** [ScottPlot/ScottPlot#1201]
Seems that, when it's necessary to show the axis on the top or right edge of the chart, the TickLabelStyle rotation is ignored.
I have checked the source code and in the AxisTicksRender.cs is missing the management of the rotation for the edges top and right, if I undestand correctly, this could be the reason of the problem!

### System Details
* **ScottPlot Version:** 4.1.16
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** .NET 5.0

**Comment by swharden** [comment]
Thanks for reporting this @gigios!

Can you provide a little code sample and a picture of the output to make it easier to understand/recreate this error? I'm working through the issues from bottom to top so when I get to this one it will be very helpful if that information is already prepared. 

Thanks!

**Comment by gigios** [comment]
Hi @swharden, I have a small sample code that shown the 'problem'.
I have used the WpfPlot control, but this problem is not related the 'control'.

```csharp
       private void PlotChart()
        {
            var plt = WpfPlot1.Plot;

            plt.Clear();

            // plot sample data
            plt.AddSignal(DataGen.Sin(51));
            plt.AddSignal(DataGen.Cos(51));

            plt.XAxis.Label("Horizontal Axis");
            
            // Set the Y Axis (left edge)
            plt.YAxis.Ticks(true);
            plt.YAxis.Grid(true);
            plt.YAxis.Label("Vertical Axis 1");
            plt.YAxis.TickLabelStyle(rotation: 45);

            // Set the Y Axis 2 (right edge)
            plt.YAxis2.Ticks(true);
            plt.YAxis2.Grid(true);
            plt.YAxis2.Label("Vertical Axis 2");
            plt.YAxis2.TickLabelStyle(rotation: 45);

            //plt.SaveFig("ticks_rotatedY.png");
        }
```
As you can see in the code, I have replicated the properties applied to one axis to the other, to have the same identical settings.
In the screenshot you can see that only the left axis is correctly rotated of 45 degree.
![immagine](https://user-images.githubusercontent.com/8749627/129095809-78ed0f02-ec45-4b8d-a30f-2050c825dd7b.png)

The same problem happen also on the top axis ( X Axis 2).

I hope this example is useful for you 😊

**Comment by swharden** [comment]
Note to self: the issue is here, and this section needs refactoring. Every `TODO` is a debt you take out against your future self 😅 

https://github.com/ScottPlot/ScottPlot/blob/e7ababd235acc13979fbb9d4b9b60c5914e28eba/src/ScottPlot/Renderable/AxisTicksRender.cs#L87-L175

**Comment by gigios** [comment]
The fix works fine but there is again a small side effect, the wrong space from the text and the chart.
See: [issue 1194](https://github.com/ScottPlot/ScottPlot/issues/1194#issuecomment-908280488)

**Comment by swharden** [comment]
Thanks @gigios, fixed this by adding a special case to improve alignment when ticks are rotated exactly 90º. I'm adding a code sample now to #1194 which shows how rotated plots look.

## Rotation = 0º
![Test_Rotated_AllAxes_1](https://user-images.githubusercontent.com/4165489/131932030-a1e4693f-1ea1-4313-8673-7f92cd0246c9.png)

## Rotation = 45º
![Test_Rotated_AllAxes_2](https://user-images.githubusercontent.com/4165489/131932037-be65d02e-7026-4575-b44b-e2531c2ea377.png)

## Rotation = 90º
![Test_Rotated_AllAxes_3](https://user-images.githubusercontent.com/4165489/131932041-54a85a7c-bfd8-49ec-a54a-77f332a04b0e.png)
