### ISSUE TITLE
CrossHair: Remain the old API and only mark it as Obsolete

### ISSUE THREAD

**Issue by Maoyao233** [ScottPlot/ScottPlot#1206]
## Features Suggestion

**Feature description:** #1195 refactored `Crosshair` to use two `AxisLine`. It's a nice but breaking change which will cause existing code that uses the component to no longer work. I think it is possible to keep the old properties as methods and mark them as [Obsolete] to maintain compatibility. I can make a pull request if needed.

**Code example:**

```cs
public class Crosshair : IPlottable
{
        public bool IsVisible { get; set; } = true;
        public int XAxisIndex { get; set; } = 0;
        public int YAxisIndex { get; set; } = 0;

        public readonly HLine HorizontalLine = new();

        public readonly VLine VerticalLine = new();

        [Obsolete("Modify VerticalLine.IsVisible instead")]
        public bool IsVisibleX { get => VerticalLine.IsVisible; set => VerticalLine.IsVisible = value; }

        [Obsolete("Modify HorizontalLine.IsVisible instead")]
        public bool IsVisibleY { get => HorizontalLine.IsVisible; set => HorizontalLine.IsVisible = value; }

        // ...
}
```

**Comment by swharden** [comment]
Hi @Maoyao233 , 

Thank you for the suggestion! If you make a PR to add these properties back and mark them obsolete I would be happy to merge it in 👍
