### ISSUE TITLE
Default graf zoom with AxisSpan

### ISSUE THREAD

**Issue by Ddoupal** [ScottPlot/ScottPlot#1208]
I update ScottPlot to new version and now graph with axis span working quite differently. 

This is default zoom in old version.
![OldGraph](https://user-images.githubusercontent.com/72607479/129713111-324bd215-016a-469c-9527-cbd3a532f567.png)
And this is default zoom in new version.
![NewGraph](https://user-images.githubusercontent.com/72607479/129713115-ee80f38e-a9d0-4652-9b9d-510197650328.png)

```cs
WpfPlot1.Plot.AddVerticalSpan(26, 1000, criticalBrush);
WpfPlot1.Plot.AddVerticalSpan(23, 26, warningbrush);
WpfPlot1.Plot.AddVerticalSpan(18, 21, warningbrush);
WpfPlot1.Plot.AddVerticalSpan(-1000, 18, criticalBrush);
```

Is there a way to make a default zoom like in old verison, on Plot and not Span?
I try using SetAxisLimitsY, but on middle mouse click it zooms out and look like second picture again.

**Comment by EmanuelFeru** [comment]
I think you need to set `IgnoreAxisAuto = true` see #1160 and #1083 .

**Comment by Ddoupal** [comment]
Thanks. It works.
