### ISSUE TITLE
NuGet: Release a modern 4.0 package

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1209]
## Features Suggestion

**Feature description:** Describe your question here

I think the primary candidates for a potential 4.0.49 release are these:
- What has already been merged into `4.0-stable` but not published to NuGet
   - Judging from [this](https://github.com/ScottPlot/ScottPlot/compare/4.0.48...4.0-stable) it looks like three bugs were fixed but never published
- Some sort of encouragement to migrate, probably linking to [here](https://swharden.com/scottplot/faq/version-4.1/)
    - Logging to console? Warnings? Overlays which only show in designer view?

Let me know if you have any other ideas.

**Comment by swharden** [comment]
Hey @bclehmann, thanks for mentioning this!

## Package

It wasn't my intent to fix bugs and _not_ publish a package. I agree, this should be done! I'll leave this issue open to track that.

## Migration

We probably don't need to push too hard. If it's working for them user don't need to update, and if they want to update they'll discover the version change when they go to the NuGet page or see the latest cookbook.

Depending on how much of a can of worms #1036 is version 5 might be around the corner

### Migration via Documentation

I do want to improve the old cookbook pages to (1) show a large warning label that they're obsolete and (2) start auto-forwarding redundant old cookbook URLs to a central URL to improve google indexing. I find googling things keeps pointing people to old version URLs. Having a single `/cookbooks/4.1` URL that updates may be preferred over a bunch of little URLs with minor version numbers 🤔

### Misc. Website Comments

I also have www.ScottPlot.net that I don't currently advertise. I haven't really figured out what to do with the website yet... Part of me likes the idea of using GitHub pages to host it (based on Jekyll). I don't like the idea of hosting binaries and tons of cookbook files in a git repo though. I've also been thinking of throwing something together with netlify and leaning on their free tier for as long as I can. If it's not obvious, I never found a documentation/website system I'm totally satisfied with 😝 I've been piggybacking off my existing SiteGround hosting account (LAMP stack with a custom PHP/markdown system) but that's a little too custom to be robust. Probably a topic for another issue and a problem to solve on another day 🤷

**Comment by swharden** [comment]
https://www.nuget.org/packages/ScottPlot/4.0.49 👍

I added a pop-up readme to alert users to the version change
