### ISSUE TITLE
Setting span color hides plot lines beneath it

### ISSUE THREAD

**Issue by Terebi42** [ScottPlot/ScottPlot#1211]
**Issue:** Setting area color hides plot lines

```cs
var hspan = plt.AddHorizontalSpan( bottom.Data.Power, top80top.Data.Power, Color.LightGray );
var line = plt.AddLine( model.slope, model.offset, (gps.Min(), gps.Max()) );
```

### Lines going through shaded area

![image](https://user-images.githubusercontent.com/4165489/130001209-f29b7b13-8615-4b7b-824f-c4c16fc8e3aa.png)

### Lines hidden by shaded area

Only difference is adding the color parameter

![image](https://user-images.githubusercontent.com/4165489/130001224-39c01235-43d9-4f0a-992e-ef379d7642ca.png)

**Comment by bclehmann** [comment]
Minimal reproduction:
```cs
var line = plt.AddLine(1, 0.2, (-2, 2));
var hspan = plt.AddHorizontalSpan(0, 1, Color.LightGray);
```

You can fix this by replacing `Color.LightGray` with `Color.FromArgb(alphaValue, Color.LightGray)`, for example:

```cs

**Comment by bclehmann** [comment]
If you want the colour to be opaque you can also draw the lines after the span. They are drawn in the order they are added.
