### ISSUE TITLE
Scot Plot font size is so small and the performance is low

### ISSUE THREAD

**Issue by MohammadSadeghSalimian** [ScottPlot/ScottPlot#1219]
Scott Plot's performance decreases significantly when I plot it in WPF. The conditions are a bit better in Windows Form. However, since my monitor is a 4K the axis label is tiny, unable to be read in both WPF and Windows Form. 

```cs
Random rand = new Random(0);
int pointCount = 100_000;
double[] ys = new double[pointCount];
double[] xs = new double[pointCount];
for (int i = 1; i < ys.Length; i++)
{
    ys[i] = ys[i - 1] + rand.NextDouble() - .5;
    xs[i] = xs[i - 1] + rand.NextDouble();
}

WpfPlot.Plot.AddSignalXYConst(xs, ys);
WpfPlot.Plot.Style(ScottPlot.Style.Blue1);
WpfPlot.Plot.SaveFig("signalxyconst_quickstart.png");
```

![ScottPlot](https://user-images.githubusercontent.com/23130925/130355535-1576b555-fccc-47c0-9aee-e0fd3a1d87db.png)

**Comment by bclehmann** [comment]
The WPF control is DPI aware so the font should be the same as on an HD screen, although maybe font rendering doesn't yet respect DPI. Regardless, you can adjust the font size for the axes by following this example: https://swharden.com/scottplot/cookbooks/4.1.16/category/plottable-text/#custom-fonts

As for performance, I don't think 100 000 points should be too much for signalXY, although I haven't used signalXY very much. I also wouldn't expect a noticable difference between equivalent code in WPF and WinForms. This makes me think you're accidentally calling `AddSignalXY` and reallocating that array on every render or something.

If you could show more detailed source code (with any edits you'd like to preserve anonymity or similar) that may help us fix your performance issues.

**Comment by MohammadSadeghSalimian** [comment]
> 
> 
> The WPF control is DPI aware so the font should be the same as on an HD screen, although maybe font rendering doesn't yet respect DPI. Regardless, you can adjust the font size for the axes by following this example: https://swharden.com/scottplot/cookbooks/4.1.16/category/plottable-text/#custom-fonts
> 
> As for performance, I don't think 100 000 points should be too much for signalXY, although I haven't used signalXY very much. I also wouldn't expect a noticable difference between equivalent code in WPF and WinForms. This makes me think you're accidentally calling `AddSignalXY` and reallocating that array on every render or something.
> 
> If you could show more detailed source code (with any edits you'd like to preserve anonymity or similar) that may help us fix your performance issues.
The problem with font can be solved when I change the font size to a greater number. However, the main problem is a significant decrease in performance.
I found out the performance significantly decreases when the size of the chart increases. I mean WPF is well working with 4K resolution and changes the size of the windows based on your display settings. ScottPlot is based on pixels and drawings are not vector base. In many examples of the codes in the cookbook the Plot resolution is always set to 600x400. WPF changes it and when it expands to near 4K size the performance significantly decreases. To overcome this problem I found a way, although it is not the best it can work. I set the ChartViewwer size to a small size and put it inside a ViewBox, the performance significantly grew, although the display quality is not desired. By the way, I set the program to run with my primary GPU which is an Nvidia GeForce 1060. The performance was low too. 
``

            WpfPlot.Plot.Style(ScottPlot.Style.Default);
            
            WpfPlot.Configuration.AllowDroppedFramesWhileDragging = true;
            
            WpfPlot.Configuration.Quality = QualityMode.Low;
            
            //WpfPlot.Plot.XAxis.Label("X", size: 60f, bold: true);
            //WpfPlot.Plot.YAxis.Label("Y", size: 60f, bold: true);
            //WpfPlot.Plot.XAxis.TickLabelStyle(fontSize:40f);
            //WpfPlot.Plot.YAxis.TickLabelStyle(fontSize:40f);

**Comment by bclehmann** [comment]
I was more interested in the context you were calling plotting functions and/or allocating the array. Is it in the constructor or another function guaranteed to only run once?

**Comment by swharden** [comment]
> I was more interested in the context you were calling plotting functions and/or allocating the array. Is it in the constructor or another function guaranteed to only run once?

This is a good point, but I suspect `AddSignalConst()` is only being called once otherwise the line would flicker color and/or not appear blue.

> my monitor is a 4K

I think this is the core of the performance issue. 

ScottPlot currently uses System.Drawing for rendering and its performance degrades as bitmap _area_ increases (not just the number of data points). A 4K monitor (3840x2160) will produce very large images, and I think we are simply running-up against the limitations of System.Drawing here.

There are plans to move toward more performant options that benefit from hardware acceleration (#1036), but for now unfortunately I don't think there's much more that can be done. Sorry I can't give a quick fix, but I hope the explanation helps!
