### ISSUE TITLE
How to place text at X/Y coordinates on different axes of multi-axis plots

### ISSUE THREAD

**Issue by Terebi42** [ScottPlot/ScottPlot#1223]
I have a bargraph, with a scatterplot over the top. The scatterplot is using a secondary axis. I would like to add labels to each point on the scatter to aid in reading the graph. I cannot see any option to turn this on globally (No scatter plot equivalent to ShowValuesAboveBars).

I can use AddText at x/y coordinates, but the x/y used are from the primary axis, not the secondary, so I can't get the text to line up against the scatter.

Help?

**Comment by swharden** [comment]
Hi @Terebi42,

> I have a bargraph, with a scatterplot over the top

> [There is] no scatter plot equivalent to ShowValuesAboveBars

This is correct. To add text at specific locations use the `AddText()` method. 

The cookbook has some examples of this:
https://swharden.com/scottplot/cookbooks/4.1.16/category/plottable-text/#text

You may want to customize the alignment and rotation to make the labels look as good as possible:
https://swharden.com/scottplot/cookbooks/4.1.16/category/plottable-text/#text-alignment-and-rotation

Hope it helps!

**Comment by swharden** [comment]
Hi @Terebi42, sorry if my first answer was incomplete.

> I can use AddText at x/y coordinates, but the x/y used are from the primary axis, not the secondary, so I can't get the text to line up against the scatter.

I think you can do something like this to place text using coordinates for the secondary axis:

```cs
var plt = new ScottPlot.Plot(600, 400);

// primary axis
var scatterA = plt.AddScatter(/* data */);
var myTextA = plt.AddText("hello", 5, 10);

// secondary axis
var scatterB = plt.AddScatter(/* data */);
var myTextB = plt.AddText("hello", 5, 10);
scatterB.YAxisIndex = 1;
myTextB.YAxisIndex = 1;
```
