### ISSUE TITLE
Zoom rectangle stays in the plot

### ISSUE THREAD

**Issue by Elgot** [ScottPlot/ScottPlot#1226]
## Bug Report

**Issue:** 
If another plot interaction is performed quickly enough after a rubber band zoom the selection rectangle stays in the plot.

![zoom](https://user-images.githubusercontent.com/13303792/131261045-ca10cf31-ea4d-4862-b900-3e49f83d8b35.gif)

**Reproducing:**
Zoom in using alt+mouse selection or mouse wheel-selection and then quickly drag the plot (or zoom by mouse wheel scrolling). 
`
### System Details
* **ScottPlot Version:** 4.1.17
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** .NET 5.0

**Comment by swharden** [comment]
> If another plot interaction is performed quickly enough after a rubber band zoom the selection rectangle stays in the plot.

Thanks for reporting this @Elgot! The best way I found to reproduce it is to middle-click-drag, then start scrolling the wheel while dragging and let-go.

I think I fixed this with 392aa3d but if you still have issues let me know 👍

**Comment by Elgot** [comment]
Thanks, it seems to work.
