### ISSUE TITLE
Linux Text Rendering Issues in Avalonia Demo

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1227]
## Bug Report

**Issue:** (Bug description goes here)
#1220 is visible in the most recent Avalonia demo (4.1.14).

As an aside, there are new plottables since 4.1.14, so we should probably release a newer demo.

**Reproducing:** (What do others have to do to reproduce the bug?)

Run the Avalonia demo on Linux.

### System Details
* **ScottPlot Version:** 4.1.14
* **Operating System:** Ubuntu Linux 20.04 through WSL 2 on Windows 10 19043.1165
* **Application Type:** Avalonia
* **.NET Version:** I actually don't know, whatever the demos were built with.

**Comment by swharden** [comment]
I think I solved this with @swharden d1f9914

I targeted the latest version

https://github.com/ScottPlot/ScottPlot/blob/d1f9914832e0269be235d3f5e0554e242a5a377e/src/demo/ScottPlot.Demo.Avalonia/Avalonia%20Demo.csproj#L11

...but I'm reminded that ScottPlot targets the oldest supported version

https://github.com/ScottPlot/ScottPlot/blob/d1f9914832e0269be235d3f5e0554e242a5a377e/src/ScottPlot/ScottPlot.csproj#L33

Do you think it matters? Hopefully #1036 will make this discussion obsolete soon 🤞

**Comment by bclehmann** [comment]
I don't know if it matters, but it is certainly resolved now.
