### ISSUE TITLE
SignalXY: Fill above/below does not render

### ISSUE THREAD

**Issue by ddrrrr** [ScottPlot/ScottPlot#1232]
the property "FillType" of SingalXY does not work.

this code is writing in winform:
```csharp
double[] data = DataGen.RandomWalk(1000);
double[] xs = new double[1000];
for (int i = 0; i < 1000; i++)
    xs[i] = i;

var sig = formsPlot1.Plot.AddSignalXY(xs, data);
sig.FillColor1 = Color.Blue;
sig.GradientFillColor1 = Color.Transparent;
sig.FillType = FillType.FillBelow;
```

**Comment by swharden** [comment]
Good catch @ddrrrr! Thanks for reporting this.

Clarifying the issue, fill above/below is supported for `Signal` plots but not `SignalXY` plots. I'll leave this issue open until this is corrected 👍 

https://swharden.com/scottplot/cookbooks/4.1.17/category/plottable-signal-plot/#fill-below
