### ISSUE TITLE
Legend is not shown unless a plottable's Label properly is populated

### ISSUE THREAD

**Issue by UV-Arpan** [ScottPlot/ScottPlot#1234]
**Issue:** Legend isn't appearing in plot even though I have added code for it.

**Reproducing:** 

    var rand = new Random(0);
    double[] values = DataGen.RandomWalk(rand, 100_000);

    int sampleRate = 20_000;
    formsPlot1.Reset();
    formsPlot1.Plot.AddSignal(values, sampleRate);
    formsPlot1.Plot.Benchmark(enable: true);
    formsPlot1.Plot.Title($"Signal Plot: 1 Million Points");
    formsPlot1.Plot.XLabel("Horizontal Axis Label");
    formsPlot1.Plot.YLabel("Vertical Axis Label");
    formsPlot1.Plot.XAxis.DateTimeFormat(true);
    formsPlot1.Plot.XAxis.TickLabelFormat("M\\/dd", dateTimeFormat: true);
    formsPlot1.Plot.Legend();
    formsPlot1.Render();
    formsPlot1.Plot.SaveFig("PlotTypes_Bar_MultipleBars.png");

### System Details
* **ScottPlot Version:** 4.1.17.0?
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** NET Framework 4.8

**Comment by bclehmann** [comment]
You have to do something like this to set the label which is shown in the legend:

```cs
var sigplot = formsPlot1.Plot.AddSignal(xs, ys);
sigplot.Label = "Label in legend";
```
