### ISSUE TITLE
Is .net version can use like bbox_to_anchor to control legend outside?

### ISSUE THREAD

**Issue by acer1204** [ScottPlot/ScottPlot#1256]
I have some data to draw a chart with ten line.
but there's name is to long.
if i use draw legend LowerRight, the legend text will cover line.
it's .net version can draw legend under the chart or not inside?

**Comment by swharden** [comment]
You can get the legend as a `Bitmap` then apply it to a `PictureBox` placed outside your plot somewhere in your application.

```cs
formsPlot1.Plot.AddSignal(DataGen.Sin(51), label: "sin");
formsPlot1.Plot.AddSignal(DataGen.Cos(51), label: "cos");
formsPlot1.Render();
pictureBox1.Image = formsPlot1.Plot.RenderLegend();
```

Let me know if this doesn't do the trick. Good luck! 👍 🚀
