### ISSUE TITLE
Controls: Render warning is unclear

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1264]
It's easy to confuse `formsPlot1.Render()` with `formsPlot1.Plot.Render()` as seen in #1263.

What can we do to make it more obvious how to do this correctly? 

![renderfail](https://user-images.githubusercontent.com/4165489/132141690-572a09bc-d9cb-4862-9c16-b4eec8502208.gif)

Related: #1245 #1165

**Comment by EmanuelFeru** [comment]
I just updated to ScottPlot 4.1.20 and I got this warning. So, I need to update my code to accommodate the new version. However, I see it is showing up in both Debug mode and Release mode? Can we make that it does not show up in Release mode? e.g., using the macro '#if !RELEASE'.
I think it's preferable that the user doesn't see an eventual mistake of the developer that is not critical.

**Comment by swharden** [comment]
> Can we make that it does not show up in Release mode?

Recently (#1245) the "automatic render timer" was removed, so the user is required to call `formsPlot1.Render()` after adding items to the plot or the plot will appear blank until the user interacts with it using the mouse.

> Can we make that it does not show up in Release mode?

If the warning is not shown an erroneous plot will be shown instead - one that is blank until the user resizes, pans, or zooms. Hiding the warning will just show a broken plot - I'm not sure which is worse 😅

Perhaps a more user-friendly message could be shown in release mode. Something like "click the plot to get started"? That's not great either 🤔

**Comment by EmanuelFeru** [comment]
Indeed maybe a more user friendly message is better in release mode, something like "Waiting for user interaction".

**Comment by swharden** [comment]
I also got an email indicating

> I am getting a disturbing yellow red message inside my graph that disappears before I can read it... Something about render()?

The message may be disappearing too fast in some cases 😩

**Comment by swharden** [comment]
> red message inside my graph that disappears before I can read it... Something about render()?

I can fix this by not showing the warning message if the list of plottables is empty

> reduce confusion between `control.Render()` and `control.Plot.Render()`

Investigating how similar libraries do this:

* [NPlot](https://github.com/mhowlett/nplot) uses `Refresh()` to update their control
 
* [ZedGraph](http://zedgraph.sourceforge.net/samples.html) also uses `Refresh()`

* [OxyPlot](https://github.com/oxyplot/oxyplot) has a `RefreshPlot()`

I'm thinking it may be best to rename `Render()` to `Refresh()` in ScottPlot's controls (but leave the old signature there and mark it obsolete). The English seems logical, as a refresh requests the plot to render under the hood 🤔

**Comment by swharden** [comment]
@bclehmann, regarding the discussion above and #1270 this seems like a pretty big (but non-breaking) API change... I'd like to get your thoughts before proceeding. Do you have an opinion on this one?

**Comment by bclehmann** [comment]
I'm not normally a fan of big renames, even if done in a non-breaking way. They increase the attention needed to keep up-to-date with the library and exercise it's best practices, but they don't normally have the same benefit that other changes would, as renames are mostly superficial. Most developers probably shouldn't devote much attention to keeping up with ScottPlot in comparison to, for example, WPF, which they may well use every day and even read patch notes for.

That said, you'll have to weigh the potential confusion of renaming a key function against the confusion from its current name. I would argue that it's not that confusing anyways, in many UI frameworks almost everything you touch has a `Render` method.

Another solution may be to introduce `InteractivePlot` as a facade which forwards all of `Plot` except for `Render`, to prevent anyone from calling `Render` on the wrong object. This can be done non-breakingly by adding a deprecated `Render` method to `InteractivePlot`. Another (breaking) way to structure this would be to add a class `BasePlot` which has everything except `Render`, and then `Plot` becomes `RenderablePlot`. You could even avoid constructing two objects, if you expose to the user a `BasePlot` which is actually an instance of the more derived class. Internally you cast it back to `RenderablePlot.

I am also unsure about the non-breakingness of the `Obsolete` attribute, does it raise a warning here or an error? I don't remember which is the default.

**Comment by bclehmann** [comment]
My opinion is that this should wait for a 4.2 or 5.0 release. It may be non-breaking in that it doesn't break code, but it is a breaking change in that it breaks people's mental model of the library.

**Comment by swharden** [comment]
> this should wait for a 4.2 or 5.0 release

Thanks! I'm glad I asked. 

In hindsight the removal of the automatic render system probably should have been a version bump itself... I thought the warning message would guide users to modifying their code as needed, but in retrospect needing users to change existing code is an obvious change in behavior and a version bump would have been appropriate there 😅

> it is a breaking change in that it breaks people's mental model of the library

I think I'll meet in the middle here and not mark anything obsolete (that would be alarming and break existing users models of the library), but I'll go ahead and add a `Refresh()` now since new users are likely to reach for a function of that name, and I'll update the documentation to recommend its use to help prepare new users for the switch when that time comes.

**Comment by arthurits** [comment]
> I can fix this by not showing the warning message if the list of plottables is empty

Although I'm late to the party, the yellow message can be quite disturbing, discouraging, and not user-friendly, especially when it's shown in the designer view. So, hiding the warning in that case could be an improvement.

![image](https://user-images.githubusercontent.com/63915486/133782616-f008c06f-3223-476e-9d0b-44fa464088b1.png)

**Comment by swharden** [comment]
> not user-friendly, especially when it's shown in the designer view
 
@arthurits, I agree! I did not intend for it to appear in designer view. I'll fix this tonight - thanks for reporting it.

> Can we make that it does not show up in Release mode? e.g., using the macro '#if !RELEASE'.

@EmanuelFeru, after thinking about this a few more days, I agree this message should be hidden in release mode. I will make this change and tonight and release an updated package on NuGet

**Comment by bclehmann** [comment]
>I agree this message should be hidden in release mode. 

We cannot do this with the `#if DEBUG`, as that's a compile-time thing and the library will always be compiled in release mode when distributed on NuGet.

The closest thing I can think of is showing an error if a debugger is attached. This can be detected with [`System.Diagnostics.Debugger.IsAttached`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debugger.isattached?view=net-5.0).

**Comment by bclehmann** [comment]
Avalonia has a designer too (by Visual Studio extension), I think you might need to edit that code as well.

**Comment by swharden** [comment]
The WPF and Forms controls have a special display when designer mode is active. I think this feature is missing from the Avalonia control, but it could be added. (#1274?) That discussion may be best in a new issue/PR

### WinForms Designer Plot

https://github.com/ScottPlot/ScottPlot/blob/b01b999a1134c294fa6f78e57f22c92d1c4c2d22/src/controls/ScottPlot.WinForms/FormsPlot.cs#L55

https://github.com/ScottPlot/ScottPlot/blob/b01b999a1134c294fa6f78e57f22c92d1c4c2d22/src/controls/ScottPlot.WinForms/FormsPlot.cs#L73-L93

**Comment by bclehmann** [comment]
There is designer mode detection in Avalonia, it's just further down: https://github.com/ScottPlot/ScottPlot/blob/b01b999a1134c294fa6f78e57f22c92d1c4c2d22/src/controls/ScottPlot.Avalonia/AvaPlot.axaml.cs#L179-L195

**Comment by Nexus452** [comment]
Hi,

I still get the warning asking to call Refresh, despite calling Render + Refresh :

`        public static void ShowModal(this Plot plt)
        {
            var frm = new FormsPlotViewer(plt) { WindowState = FormWindowState.Maximized };
            plt.Render();
            frm.Refresh();
            Application.Run(frm);
        }`

It's straight forward and I am not modifying the data or the plot in a parallel thread.
What am I doing wrong ?
I am using 4.1.21 version.

Thanks

**Comment by bclehmann** [comment]
I don't think `FormsPlotViewer` has a `Refresh` method, so I don't think that code should even compile.

**Comment by Nexus452** [comment]
Ok so this works :

        public static void ShowModal(this Plot plt)
        {
            var frm = new FormsPlotViewer(plt) { WindowState = FormWindowState.Maximized };
            frm.formsPlot1.Render();
            frm.formsPlot1.Refresh();
            Application.Run(frm);
        }
        
    It's a bit confusing I didn't realize that FormsPlotViewer was wrapping the FormsPlot and I needed to look for formsPlot1.
