### ISSUE TITLE
Hacktoberfest 2021 🎃🚀

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1274]
# ScottPlot is participating in Hacktoberfest 2021! 🎉🚀 
Hacktoberfest is an event that encourages contributions to open-source projects run by Digital Ocean. Participants who contribute to 4 merged pull requests may be eligible for a free T-shirt.

* **PR Quality Standards:** https://hacktoberfest.digitalocean.com/resources/qualitystandards

* **Information for Participants:** https://hacktoberfest.digitalocean.com/resources/participation

* **Maintainers:** https://hacktoberfest.digitalocean.com/resources/maintainers

# Recommended Projects for new Contributers

**Never contributed to open-source before?** Welcome! Hacktoberfest has a video on [making your first pull request](https://hacktoberfest.digitalocean.com/resources). We can figure this out together! 👍🚀 

## Improve color themes by submitting a `Style` or `Palette`

* ⚠️ See [**issue #1315: Hacktoberfest: Contribute a color style or palette**](https://github.com/ScottPlot/ScottPlot/issues/1315) for a step-by-step summary of how to contribute colors

![colorset2](https://user-images.githubusercontent.com/4165489/135541759-750eef9e-08bd-49bf-ae41-2b70197a26bc.gif)

## Improve the Website Documentation and FAQ
* [ScottPlot.NET](https://scottplot.net) content is on GitHub and can be edited with a PR: https://github.com/ScottPlot/ScottPlot.NET

## Improve the Cookbook
* The [ScottPlot Cookbook](https://scottplot.net/cookbook/4.1) has many short examples demonstrating how to use ScottPlot
* Cookbook recipes are here: [`src/cookbook/ScottPlot.Cookbook/Recipes`](https://github.com/ScottPlot/ScottPlot/tree/master/src/cookbook/ScottPlot.Cookbook/Recipes)
* If a cookbook recipe description contains a typo, feel free to fix it in a PR
* If you wish to create a new cookbook recipe, it will only be permitted if it adds substantial value beyond existing recipes. Because recipes are converted to web pages, there is pressure to keep the number of recipes limited. If you are unsure if your recipe idea will be merged, feel free to [open an issue](https://github.com/ScottPlot/ScottPlot/issues) and ask!

# Advanced Project Ideas

* **Syntax highlighting** would be great to have for the textboxes which show the source code in the cookbook of the demo applications (WinForms, WPF, and Avalonia, each may be separate PRs)

* **Heatmap:** support row/column labels, cell value labels, and palettes (#1273, #420)

* **L Scale Bar:** Add more styling options (#363)

* **Legend:** Add row/column support (#580)

* **Wiggle Plot** (#450)

* **Dendrogram** (#987)

* **Generate icons programmatically:** Use `System.Drawing` to render shapes (rectangle, oval, polygon, etc.) to generate `Bitmap` files programmatically so [these PNG icon files](https://github.com/ScottPlot/ScottPlot/tree/master/src/cookbook/ScottPlot.Cookbook/Images) do not have to be distributed with the cookbook. Implementation could be a new file `src/ScottPlot/Drawing/Icons.cs` which contains a static class that has static methods, each which draw a different icon and return it as a `Bitmap`. Bonus points if you can supply a size (width and height) and it's scaled properly.

**Comment by bclehmann** [comment]
Have you decided yet whether ScottPlot is going to participate?

**Comment by swharden** [comment]
Yeah, let's do it 😎

I'm going to refactor the style system tonight #1291 to make that easy to contribute to for first-time GitHub users. I may also put together a quick screencast showing how to clone the repo, make a change, and open a PR.

I'm not really sure what to expect with this year's hacktoberfest, but I suspect some users will be motivated to make a minimal qualifying contribution, so my plan is to provide an easy path for them to contribute something that is isolated and easy to review.

PS: It's started already? I thought I had until October 1! 😅

**Comment by bclehmann** [comment]
>  Participants who contribute to 5 merged pull requests may be eligible for a free T-shirt.

This is incorrect, it says the number is 4. I know that you can get a shirt by merging 4 PRs or approving 4 PRs, but I'm unsure if you can do 2 of one and 2 of the other.

**Comment by swharden** [comment]
> >  Participants who contribute to 5 merged pull requests may be eligible for a free T-shirt.
> 
> This is incorrect, it says the number is 4. I know that you can get a shirt by merging 4 PRs or approving 4 PRs, but I'm unsure if you can do 2 of one and 2 of the other.

Thanks for pointing that out! I corrected the issue by editing the comment.

I'm not sure about the approve/merge thing either. I've noticed the rules page changed since this morning. It makes me think they're still refining the rules 🤷
