### ISSUE TITLE
F# Docs/Demo?

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1276]
## Features Suggestion

**Feature description:** F# is gaining steam in scientific usage, so it might be worth giving a basic F# demo/quickstart.

**Code example:** I don't know any F# so I probably can't give a code example right now. However, from what I understand, interop with C# is trivial.

**Comment by swharden** [comment]
btw I started working on a C# markdown static site generator https://github.com/swharden/Statix it uses GitHub Actions to run tests, build the site, and deploy it to Azure blob storage. Hopefully before long I can use it to automatically generate/update the cookbook and package the demo application on every release 🤞
