### ISSUE TITLE
Open in new window - formsPlot in new window shows the yellow Refresh() warning 

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#1283]
Hello! I plot my graph using formsPlot1.Refresh(); and  formsPlot1.Plot.Render();.
Via the right mouse click menu, I use the "Open in New Window" option.
The data points are where they should be, but i get the yellow warning box in the middle:

![image](https://user-images.githubusercontent.com/51174971/134777315-78e1d12c-3424-4d41-8c73-709ef0a3bf89.png)

### System Details
* **ScottPlot Version:** 4.1.21
* **Operating System:** (Windows 10)
* **Application Type:** (WinForms)
* **.NET Version:** (NET Framework 4.7.2)

**Comment by bclehmann** [comment]
Looks like the same thing as here: https://github.com/ScottPlot/ScottPlot/issues/1264#issuecomment-925974571
