### ISSUE TITLE
Revisiting the logo/icon

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1297]
At the risk of [bikeshedding](https://en.wikipedia.org/wiki/Law_of_triviality)... The new website is looking great https://scottplot.net and if there's an opportunity to revisit the logo, this may be it.

I may keep the _NuGet package icon_ the same for the remaining lifetime of ScottPlot 4.1, but the new logo could go on the website and be used as an icon for ScottPlot 5.0

## Similar Projects

Software | Logo
---|---
Microsoft Charting| ![image](https://user-images.githubusercontent.com/4165489/135193194-aecab76c-8a43-4199-ade0-ad01c7b7e701.png)
NPlot | ![image](https://user-images.githubusercontent.com/4165489/135193580-11657372-3d4d-4133-91eb-0327b9677190.png)
ZedGraph | ![image](https://user-images.githubusercontent.com/4165489/135193644-2c7cedca-8d45-4800-a744-c13bba3561b3.png)
OxyPlot | ![image](https://user-images.githubusercontent.com/4165489/135193672-a9c0ebb5-0742-42b5-bb16-a269bc6b9f2c.png)
LiveCharts | ![image](https://user-images.githubusercontent.com/4165489/135195409-8b104adc-6e03-4f3b-9f68-ecd80ff592c5.png)
SciChart | ![image](https://user-images.githubusercontent.com/4165489/135194951-ebda056a-436d-4951-bf1e-fdd2ecf22fda.png)
PlotNet | ![image](https://user-images.githubusercontent.com/4165489/135195511-d80ecc2d-9020-428c-9c94-0671003a8029.png)
ggplot2 | ![image](https://user-images.githubusercontent.com/4165489/135194075-15478661-2bda-457c-938a-eb1edc6f667a.png)
matplotlib | ![image](https://user-images.githubusercontent.com/4165489/135194155-bc81999e-c1fb-4c9f-867f-d04ed8c4910a.png)
GnuPlot | ![image](https://user-images.githubusercontent.com/4165489/135194244-a0ce7d5e-3a0c-41a3-9bf4-52541fb46bda.png)
ScottPlot 3 | ![image](https://user-images.githubusercontent.com/4165489/135195078-efac4f53-ccfa-4fe2-a727-df2d373e4659.png)
ScottPlot 4 | ![image](https://user-images.githubusercontent.com/4165489/135194358-301b8cfb-cd11-42a1-9d7e-e1d43254ba3d.png)

The ScottPlot 4 logo started with the GitHub emoji 📈 and just added a couple extra lines

## Ideas

I find these colors commonly associated with C#, but I don't think it's official since I can't find a style guide indicating what the exact colors actually are. 

![image](https://user-images.githubusercontent.com/4165489/135194752-d136d63a-a725-4ce5-af1e-3998236a9f7b.png)

Related official guidelines are:
* https://github.com/dotnet/brand/tree/main/logo
* https://github.com/dotnet-bot

I opened InkScape and started poking around and am leaning toward something like this:

![image](https://user-images.githubusercontent.com/4165489/135194459-34d6d1d7-0b4b-4d74-b78a-9663e896003b.png)

**Comment by EmanuelFeru** [comment]
Looks awesome! I like it 🙂

**Comment by Rayffer** [comment]
Looks really great, flat and modern. Go for it

**Comment by swharden** [comment]
Thanks for the encouragement @EmanuelFeru and @Rayffer! 😄 

I'm using it for the favicon on the website https://scottplot.net and will slowly roll it out elsewhere

![image](https://user-images.githubusercontent.com/4165489/135380897-bd3bddb0-7f23-488f-ac02-65796f124bb7.png)
