### ISSUE TITLE
Violin Plot (suggestion for new plot type)

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1301]
## Features Suggestion

**Feature description:** Add a new Violin plottable.
![image](https://user-images.githubusercontent.com/8635304/135386339-ea11a669-e03d-4815-9979-dd4c7447cb20.png)

A violin plottable is like a box plot surrounded by a [kernel density estimation](https://en.wikipedia.org/wiki/Kernel_density_estimation) (KDE), which is analogous to a histogram that has been smoothed. There are variants that stack multiple KDEs to represent data in different confidence intervals.

There are also variants that are asymmetrical, showing KDEs for two different categories. These can include the box plot in the middle if the box plot is for the whole set, but the box is often not shown.
![image](https://user-images.githubusercontent.com/8635304/135387006-febda299-91aa-436c-91d9-a046000b4b8d.png)

I think this feature makes the most sense as an addition to population plots.

**Code example:** If applicable, use this space to demonstrate how you wish the new feature could be used in code.

```cs
var popPlot = plt.AddPopulations(multiSeries);
popPlot.Violin = true;
```

**Comment by swharden** [comment]
I'll close this for now since it's not being actively worked on, but it's added to the triage list #1028 👍

**Comment by bclehmann** [comment]
Yeah I avoided starting this because the math looks non-trivial, and then I forgot about it.
