### ISSUE TITLE
Update NuGet package readmes and URLs

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1307]
### NuGet Readme Pages
* Fix URLs (swharden.com/scottplot → scottplot.net)
- [x] https://github.com/ScottPlot/ScottPlot/blob/master/src/ScottPlot/README.md
- [x] https://github.com/ScottPlot/ScottPlot/blob/master/src/controls/ScottPlot.WinForms/README.md
- [x] https://github.com/ScottPlot/ScottPlot/blob/master/src/controls/ScottPlot.WPF/README.md
- [x] https://github.com/ScottPlot/ScottPlot/blob/master/src/controls/ScottPlot.Avalonia/README.md

### NuGet Pop-Up Readme Files
- [x] delete them

<details>
<summary>original bug report</summary>

## Bug Report

**Issue:** 
The following files are distributed over NuGet and they say that the user downloaded a pre-release version.
src/controls/ScottPlot.WPF/README.txt
src/controls/ScottPlot.WinForms/README.txt
src/controls/ScottPlot.Avalonia/README.txt

There is an up-to-date README.txt here: ScottPlot/src/ScottPlot/README.txt

We should probably either update the readmes or remove them, as we already have a markdown readme.

**Reproducing:** (What do others have to do to reproduce the bug?)
Download over NuGet and open the .nupkg (it's just a zip file with a different file extension), or navigate to the files in the source tree.

### System Details
* **ScottPlot Version:** 4.1.24 (probably all previous 4.1.x versions)
* **Operating System:** N/A
* **Application Type:** Everything except the core ScottPlot package
* **.NET Version:** N/A

</details>

**Comment by swharden** [comment]
Good catch! URLs should also be updated to point to https://ScottPlot.NET

**Comment by taha-ghadirian** [comment]
Hello @swharden, Could I work on this issue please?

**Comment by swharden** [comment]
> Hello @swharden, Could I work on this issue please?

Sure thing! Start a PR and I can review it when it's ready 👍

**Comment by swharden** [comment]
> We should probably either update the readmes or remove them, as we already have a markdown readme.

If you install the NuGet package using the visual package manager in Visual Studio the readme.txt file pops-up

I guess now that NuGet packages support readme.md files on their website there's less of a need for that... and the pop-up behavior could be considered disruptive. I'm on the fence about deleting those... but it's starting to sound like a good idea.

**Comment by bclehmann** [comment]
> If you install the NuGet package using the visual package manager in Visual Studio the readme.txt file pops-up

Huh, when you update does it open changelog.txt if it exists? That sounds more useful, I can't imagine many people install a library without having skimmed the readme or demos.

If the readme opening automatically is annoying that sounds like Visual Studio's job to fix (or the user's, if it's configurable). But since it has to be in plain text instead of markdown we would have to maintain and update a second version of the readme, which I'm not convinced is actually useful.

We could add a script that automatically ensures that the readmes stay in sync. Assuming the csproj attribute allows relative paths we could also have them all reference a readme.txt in the root directory, which would be less error-prone and wouldn't add an extra script to the build process.

**Comment by swharden** [comment]
Official documentation: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#add-a-readme-and-other-files

> Huh, when you update does it open changelog.txt if it exists?

Yeah, this pops-up if you install _or update_ using the visual package manager

![image](https://user-images.githubusercontent.com/4165489/135783222-56a43c9d-fccf-4dd3-8550-b6ce110b3c7e.png)

> I can't imagine many people install a library without having skimmed the readme or demos.

I wish I had better information about how people discover ScottPlot. It's possible people just search NuGet from inside Visual Studio for the word "plot". I guess even then the URL is prominently visible, so the pop-up text isn't necessary.

> we would have to maintain and update a second version of the readme ... We could add a script that automatically ensures that the readmes stay in sync ...

> I'm not convinced is actually useful

My thought is that is may be useful for astonishing announcements. Major API changes, deprecated versions, etc. 

After this discussion I think the best plan is to delete these readme files. Do you agree?

**Comment by bclehmann** [comment]
> After this discussion I think the best plan is to delete these readme files. Do you agree?

I agree; I don't know how many people install packages by the Visual Studio GUI tools, but I don't expect it's a majority. And I don't think that after installation is a useful time to confront someone with a readme anyways. As far as I know, the only purpose of distributing a readme with a .nupkg is for Visual Studio users.

**Comment by swharden** [comment]
@taha-ghadirian sorry for the confusion - I see you updated the front page readme #1316 which is a different topic than what this issue addresses (readme files distributed with NuGet packages)
