### ISSUE TITLE
Hacktoberfest: Contribute a color style or palette

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1315]
This issue describes how to submit a `Style` or `Palette` to ScottPlot and indicates expectations for pull request.

See the [**Hacktoberfest 2021 issue (#1274)**](https://github.com/ScottPlot/ScottPlot/issues/1274) for additional project ideas for new contributors.

![colorset2](https://user-images.githubusercontent.com/4165489/135541759-750eef9e-08bd-49bf-ae41-2b70197a26bc.gif)

## Rules for Submitting Pull Requests (PRs)
* ⚠️ Include a screenshot of the demo application displaying the style or palette you are contributing
* ⚠️ Run [autoformat.bat](https://github.com/ScottPlot/ScottPlot/blob/master/src/autoformat.bat) to auto-format your code before submitting it
* ⚠️ If colors were sourced from somewhere else, indicate the original source as a code comment

## How to Contribute a `Palette`

A `Palette` is a set of default colors that gets applied to data as it is added to the plot.

* Add a palette by creating a class in [`src/ScottPlot/Palettes/`](https://github.com/ScottPlot/ScottPlot/tree/master/src/ScottPlot/Palettes)
* Mimic the namespace and class structure of existing palettes like [Aurora.cs](https://github.com/ScottPlot/ScottPlot/blob/master/src/ScottPlot/Palettes/Aurora.cs)
* View your palette using the ScottPlot demo application and include a screenshot with your pull request

Palettes can be sourced from other similar libraries (but indicate source as a code comment):
  *  [matplotlib colormaps](https://matplotlib.org/stable/tutorials/colors/colormaps.html) (defined in [_cm.py](https://github.com/matplotlib/matplotlib/blob/d11b206420c21af74ab697d864b0e64dafec1a27/lib/matplotlib/_cm.py))
  * https://www.color-hex.com/color-palettes
  * https://color.adobe.com/explore

## How to Contribute a `Style`

A `Style` is a set of colors that control the way the plot looks (background color, tick label colors, grid line colors, etc.)

* Add a new `IStyle` class to this folder: [`src/ScottPlot/Styles`](https://github.com/ScottPlot/ScottPlot/tree/master/src/ScottPlot/Styles)
* Use an existing style for reference, for example: [`src/ScottPlot/Styles/Blue1.cs`](https://github.com/ScottPlot/ScottPlot/blob/master/src/ScottPlot/Styles/Blue1.cs)
* View your style using the ScottPlot demo application and include a screenshot with your pull request

## How to Run the Demo Application
* Install [Visual Studio](https://visualstudio.microsoft.com/downloads) (free)
* Open `src/ScottPlot.sln`
* In the `Solution Explorer`, right-click the `WinForms Demo` application and select `Set as Startup Project`
* Press `F5` to compile and launch the demo application
* The style browser can be launched using the button at the bottom of the list

Solution Explorer | Demo Application | Style Browser
---|---|---
![image](https://user-images.githubusercontent.com/4165489/135762253-a39cc548-9eb5-4ad3-b6d9-60312bd0dba5.png)|![image](https://user-images.githubusercontent.com/4165489/135762268-50772f0c-e960-4619-b7b2-0193808fc09b.png)|![colorset2](https://user-images.githubusercontent.com/4165489/135541759-750eef9e-08bd-49bf-ae41-2b70197a26bc.gif)

**Comment by KanishkKhurana** [comment]
hey @swharden please assign this issue to me ! 
this looks really fun and i would love to contribute to this !

**Comment by swharden** [comment]
Hi @KanishkKhurana you are welcome to contribute! More than one person can add colors so I don't need to assign this issue to you, but if you create a PR (pull request) I would be happy to review it. 

You are welcome to create multiple PRs if you wish to contribute multiple colorsets.

**Comment by KanishkKhurana** [comment]
great ! i'll start asap ! 
thank you so much !

**Comment by wbalbo** [comment]
Hi, I want to help too, I will make a PR soon, thanks!

**Comment by Gauravsinghrajputt** [comment]
Please assign me for doing this project ,
I want to do something different on it ,
So kindly assign me .

**Comment by swharden** [comment]
Hi @Gauravsinghrajputt, go for it! There are a lot of open PRs right now, but I intend to merge them all in over this weekend 🤞 🤞🤞

Note that the instructions above are from an outdated version of this software, but you can add new color palettes by creating new classes in the `ScottPlot5/Palettes` folder mimicking the style of this one

https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Palettes/Tsitsulin.cs

https://github.com/ScottPlot/ScottPlot/blob/743c9427e63692d31920cc424a0e62b12d6eec4a/src/ScottPlot5/ScottPlot5/Palettes/Tsitsulin.cs#L1-L33
