### ISSUE TITLE
Exception when zooming in on DateTime axis (ScottPlot 4.0)

### ISSUE THREAD

**Issue by riquich** [ScottPlot/ScottPlot#1323]
## Bug Report

**Issue:** System overflow exception occurs when zooming in for too much with datetime ticks on X axis. This is a very minor issue that should have low priority on fixing, I just stumbled across to this by chance. Thank you for your attention

**Reproducing:** Using configuration below, the issue can be reproduced by zooming in too much

```cs
/*Plot configuration is as given below*/
var examplePlot = new ScottPlot.Plot();
examplePlot .Ticks(dateTimeX: true, fontSize: 14, fontName: "Roboto", snapToNearestPixel: true);
examplePlot .SetCulture(shortDatePattern: "");
```

### System Details
* **ScottPlot Version:** (4.0.48)
* **Operating System:** (Windows 10 / video card: gtx1070-driver version: 471.96 / cpu: intel 6700k)
* **Application Type:** (WPF)
* **.NET Version:** (.net core 3.1)
![a](https://user-images.githubusercontent.com/34640902/135818621-73462f31-1434-4ea3-a78d-62c4e047c8c6.gif)

**Comment by swharden** [comment]
Thanks for reporting this @riquich!

This issue may be fixable, but ScottPlot 4.0 is obsolete and this bug is likely already fixed in ScottPlot 4.1

Is it possible for you to upgrade to the latest version on NuGet and see if the problem persists?

**Comment by riquich** [comment]
Hey Scott, I'll be soon upgrading and trying again to see if it is fixed and will let you know, thanks

**Comment by riquich** [comment]
Just finished upgrading and tried it. Seems like it has been fixed, thanks for the info. Sorry for the disturbance, I am closing the issue

**Comment by swharden** [comment]
> Seems like it has been fixed

Awesome, thanks for the update!

> Sorry for the disturbance, I am closing the issue

No worries! This will be here in case anyone searches the same issue in the future 👍
