### ISSUE TITLE
How to read a drawn plot's title properties(global/x&y axes)

### ISSUE THREAD

**Issue by riquich** [ScottPlot/ScottPlot#1327]
## Question Template

**ScottPlot Version:** 4.1

**Operating System:** Win10

**Application Type:** WPF

**Question:** In 4.0.* I was able to get current labels of the plots but now I cannot access them, is there any way to read those values? Thanks for the response in advance

```cs
// a code sample may improve communication

//It was accesible like below in 4.0
var examplePlot = new ScottPlot.Plot();
examplePlot .GetSettings();
settings.xLabel.text
settings.yLabel.text
settings.title.text
//But now they are not available not on XAxis/YAxis or settings itself
```

**Comment by swharden** [comment]
Hi @riquich, https://scottplot.net/faq/version-4.1 may help you with your transition

## To read an axis label back

```cs
string xAxisLabel = plt.XAxis.Label();
Console.WriteLine(xAxisLabel);
```

Note that the title is just the label for `XAxis2`

## To get the current axis limits for a plot

```cs
var limits = plt.GetAxisLimits();
Console.WriteLine(limits);
Console.WriteLine(limits.XMin);
```
