### ISSUE TITLE
Text and lines are blurry when display scaling is enabled

### ISSUE THREAD

**Issue by ktheijs** [ScottPlot/ScottPlot#1352]
## Bug Report

**Issue:** 
When using a display that has a scale factor other than 100% in Windows (see image) will result in bad scaling of the text.
![image](https://user-images.githubusercontent.com/12170304/136961978-ea5d6bd5-2202-43c9-80b7-350e8b6a32b0.png)

**Reproducing:** 

1. Set the scale factor of a display to something other than 100% (e.g. 200% as in the screenshot).
2. Make sure that this display is the main display.
3. Start your application. (Make sure that your application has at least one normal textblock and a plot. Both text sizes should be the same.)
4. => The size on screen of the textblock will be much larger than the text in the plot.

**Expected behavior:**
* The text sizes should be the same.

### System Details
* **ScottPlot Version:** 4.1.25
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** NET Framework 4.7.2

**Comment by swharden** [comment]
Hi @ktheijs, I haven't merged #1364 and published it yet but I hope to shortly. Part of what's slowing me down is figuring out the least confusing way to make it clear exactly what these toggles do. These will be the two options:

**Default option: stretch on scaled displays.** If display scaling is enabled to 150%, _stretch_ the bitmap by 1.5 times. This will allow the plot to feel natural, although stretched bitmaps are always slightly blurry.

**Alternate option: disable stretching on scaled displays.** Ignore display scaling and always show plots at 1:1 pixel scaling. This means text may appear smaller than expected on scaled displays. To compensate for this font size can be increased as desired: https://scottplot.net/cookbook/4.1/category/plottable-text/#custom-fonts

**Comment by swharden** [comment]
You can now do this to disable plot stretching on scaled displays:

```cs
WpfPlot1.Configuration.DpiStretch = false;
```

It's not on NuGet yet, but it will be shortly. Thanks again for the tip @ktheijs!

PS: I just realized the changelog isn't properly linking/showing thumbnails for all the users https://scottplot.net/changelog so I'll fix that soon too 😅
