### ISSUE TITLE
Colorbar: improve automatic tick placement

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1362]
A unitless colorbar is surprising.

```cs
var plt = new ScottPlot.Plot(600, 400);
plt.AddColorbar();
plt.SaveFig("colorbar_quickstart.png");
```

![image](https://user-images.githubusercontent.com/4165489/137409356-6f87c409-9653-4883-82df-cee1655092c3.png)

Adding tick labels doesn't look easy...

```cs
var plt = new ScottPlot.Plot(600, 400);

var cb = plt.AddColorbar();
cb.AddTick(0, "-123");
cb.AddTick(1, "+123");
cb.AddTick(.5, "0");
cb.AddTick(.25, "-61.5");
cb.AddTick(.75, "+61.5");

plt.SaveFig("colorbar_ticks.png");
```

![image](https://user-images.githubusercontent.com/4165489/137409477-84a02604-61b2-4c63-af5e-8c502f1b19ad.png)

**Comment by bclehmann** [comment]
Interestingly we calculated beginning and end values when colorbars were part of the heatmap, but I don't think that that was carried over: https://github.com/ScottPlot/ScottPlot/blob/master/src/ScottPlot/Plottable/Heatmap.cs#L91-L92
