### ISSUE TITLE
WPF Legend()  and AddScatterList

### ISSUE THREAD

**Issue by Sellecta** [ScottPlot/ScottPlot#1378]
When using AddScatterList in legends, it does not display graph lines in legends, others are fine.
![ScatterList](https://user-images.githubusercontent.com/12238562/137935458-db181509-0e8d-4681-ae19-8a7808bea072.png)

**Comment by bclehmann** [comment]
I'm having difficulty replicating this, what version of ScottPlot are you running?

**Comment by bclehmann** [comment]
It looks like this was fixed in #1190, which was part of [4.1.17](https://github.com/ScottPlot/ScottPlot/releases/tag/4.1.17), published in August.
