### ISSUE TITLE
Plot: AddMarker()

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1391]
It would be helpful to be able to `Plot.AddMarker()` or something similar to place a circle or square or other marker at a specific point on the plot. It could be a pass-through to `Plot.AddPoint()`

**Comment by bclehmann** [comment]
I think this is pretty redundant as `AddPoint` already exists and it takes a `MarkerShape` parameter. I think the idea is to simplify it in the case where you want a specific marker shape, but I don't think `AddPoint` is complicated as it is.
