### ISSUE TITLE
Palette: all Palettes (colorsets) should be public

### ISSUE THREAD

**Issue by Terebi42** [ScottPlot/ScottPlot#1394]
Can't do :   var colors = new ColorblindFriendly().hexColors;

**Comment by bclehmann** [comment]
May I ask what the usecase of this is? The colorsets are already exposed through [`GetRGB`](https://github.com/ScottPlot/ScottPlot/blob/master/src/ScottPlot/Palettes/IPalette.cs#L13).

I think letting them be writable would be a mistake, a user could attempt to modify the colorset and get strange results. I can't think of a concrete argument against making them public but readonly, however I don't know what that would achieve. There's a philosophical argument against any kind of leaking of implementation details; I don't think that argument has concrete advantages here, but it is often a sensible default.
