### ISSUE TITLE
ScatterPlotDraggable: experimental scatter plot with mouse-draggable points

### ISSUE THREAD

**Issue by EFeru** [ScottPlot/ScottPlot#1422]
## Features Suggestion

**Feature description:** It would be very nice if we could drag points in a plot to reposition them. The use-case that I have is to tune a look-up table and to get quickly a nice shape dragging points in plot comes very handy. At the moment I am changing values in a dataGridView next to it and Refresh plot accordigly. It works but it is time consuming.

Example use-case:
![image](https://user-images.githubusercontent.com/24780745/140175357-199ae9a7-822c-4c53-8ff1-1ab2307e48ad.png)

**Comment by swharden** [comment]
This may be hard, but I'd like to explore it! I'd probably create a new plot type like `ScatterPlotDraggable` and perhaps an interface like `IHasDraggablePoints`

My use case would be to have a more elegant way to create colormaps by dragging points on R/G/B curves (rather than having to lay-out separate controls for each draggable point). See discussion in #458

![](https://user-images.githubusercontent.com/4165489/84584391-e2057500-add1-11ea-8580-56628a887766.png)

**Comment by EFeru** [comment]
Are the sliders already available in ScottPlot or is something experimental?
It could be a solution for me as well. The only drawback would be:
- it occupies more space and
- probably it restricts the drag to only up and down. Of course ideally is to be able to drag the point freely within the previous point and next point X axis value.

**Comment by swharden** [comment]
That screenshot is from an experimental/throwaway app I made to manually adjust RGB levels to create a custom colormap curve. Adding true draggable points _on the plot_ would have made such an app much more elegant

**Comment by BambOoxX** [comment]
@swharden I just had a need for a plot with one draggable point among a vector of values, to serve as an overlay to another plot. Out of curiosity I will try and find an implementation for this issue. In the meantime I will send a PR for the aforementioned plottable.

**Comment by BambOoxX** [comment]
@swharden Here is a toy implementation for the `ScatterPlotDraggable`. It is based on `IPlottable` and `IDraggable` not `IHasPoints` at the moment


![image](https://user-images.githubusercontent.com/42067365/149639843-09603dc1-e4f6-441b-b12b-7b1132f7893e.png)


<details>
<summary>The source looks like this at the moment</summary>
```cs
using System;
using System.Linq;
using System.Drawing;
using ScottPlot.Drawing;
using System.Diagnostics;

namespace ScottPlot.Plottable
{
    /// <summary>
    /// The scatter plot renders X/Y pairs as points and/or connected lines.
    /// Scatter plots can be extremely slow for large datasets, so use Signal plots in these situations.
    /// </summary>
    public class ScatterPlotDraggable : IDraggable, IPlottable
    {
        public bool IsVisible { get; set; } = true;
        public int XAxisIndex { get; set; } = 0;
        public int YAxisIndex { get; set; } = 0;

        /// <summary>
        /// Horizontal position in coordinate space
        /// </summary>
        public double[] Xs { get; set; }

        /// <summary>
        /// Vertical position in coordinate space
        /// </summary>
        public double[] Ys { get; set; }


        public int PointCount => Xs.Length;

        public int CurrentIndex { get; set; } = 0;
        /// <summary>
        /// Marker to draw at this point
        /// </summary>
        public MarkerShape MarkerShape { get; set; } = MarkerShape.filledCircle;

        /// <summary>
        /// Size of the marker in pixel units
        /// </summary>
        public double MarkerSize { get; set; } = 10;

        /// <summary>
        /// Color of the marker to display at this point
        /// </summary>
        public Color Color { get; set; } = Color.Black;

        /// <summary>
        /// Text to appear in the legend (if populated)
        /// </summary>
        public string Label { get; set; }

        /// <summary>
        /// Indicates whether this line is draggable in user controls.
        /// </summary>

        public bool DragEnabled { get; set; } = false;

        /// <summary>
        /// Cursor to display while hovering over this line if dragging is enabled.
        /// </summary>
        public ScottPlot.Cursor DragCursor => ScottPlot.Cursor.Crosshair;

        /// <summary>
        /// If dragging is enabled the line cannot be dragged more negative than this position
        /// </summary>
        public double DragXLimitMin = double.NegativeInfinity;

        /// <summary>
        /// If dragging is enabled the line cannot be dragged more positive than this position
        /// </summary>
        public double DragXLimitMax = double.PositiveInfinity;

        /// <summary>
        /// If dragging is enabled the line cannot be dragged more negative than this position
        /// </summary>
        public double DragYLimitMin = double.NegativeInfinity;

        /// <summary>
        /// If dragging is enabled the line cannot be dragged more positive than this position
        /// </summary>
        public double DragYLimitMax = double.PositiveInfinity;

        /// <summary>
        /// This event is invoked after the line is dragged
        /// </summary>
        public event EventHandler Dragged = delegate { };

        /// <summary>
        /// The lower bound of the axis line.
        /// </summary>
        public double Min = double.NegativeInfinity;

        /// <summary>
        /// The upper bound of the axis line.
        /// </summary>
        public double Max = double.PositiveInfinity;

        public AxisLimits GetAxisLimits() => new AxisLimits(Xs.Min(), Xs.Max(), Ys.Min(), Ys.Max());

        public void ValidateData(bool deep = false)
        {
            Debug.Assert(CurrentIndex >= 0 && CurrentIndex <= PointCount - 1, $"CurrentIndex property is out of bounds, it should be in the [0 - {PointCount - 1} range");
            Debug.Assert(CurrentIndex <= Xs.Length - 1);
            Validate.AssertHasElements(nameof(Xs), Xs);
            Validate.AssertHasElements(nameof(Ys), Ys);
            Validate.AssertEqualLength("", Xs, Ys);
            if (deep)
            {
                Validate.AssertAllReal(nameof(Xs), Xs);
                Validate.AssertAllReal(nameof(Ys), Ys);
            }
        }

        public void Render(PlotDimensions dims, Bitmap bmp, bool lowQuality = false)
        {
            if (IsVisible == false)
                return;
            var LineWidth = 1;
            var LineStyle = ScottPlot.LineStyle.Solid;
            var MarkerSize = 10;
            var StepDisplay = false;
            using (var gfx = GDI.Graphics(bmp, dims, lowQuality))
            {
                using (var penLine = GDI.Pen(Color, LineWidth, LineStyle, true))
                {
                    //int from = MinRenderIndex ?? 0;
                    //int to = MaxRenderIndex ?? (Xs.Length - 1);
                    int from = 0;
                    int to = (Xs.Length - 1);
                    PointF[] points = new PointF[to - from + 1];
                    for (int i = from; i <= to; i++)
                    {
                        //float x = dims.GetPixelX(Xs[i] + OffsetX);
                        //float y = dims.GetPixelY(Ys[i] + OffsetY);
                        float x = dims.GetPixelX(Xs[i]);
                        float y = dims.GetPixelY(Ys[i]);
                        if (float.IsNaN(x) || float.IsNaN(y))
                            throw new NotImplementedException("Data must not contain NaN");
                        points[i - from] = new PointF(x, y);
                    }

                    // draw the lines connecting points
                    if (LineWidth > 0 && points.Length > 1 && LineStyle != LineStyle.None)
                    {
                        if (StepDisplay)
                        {
                            PointF[] pointsStep = new PointF[points.Length * 2 - 1];
                            for (int i = 0; i < points.Length - 1; i++)
                            {
                                pointsStep[i * 2] = points[i];
                                pointsStep[i * 2 + 1] = new PointF(points[i + 1].X, points[i].Y);
                            }
                            pointsStep[pointsStep.Length - 1] = points[points.Length - 1];
                            gfx.DrawLines(penLine, pointsStep);
                        }
                        else
                        {
                            gfx.DrawLines(penLine, points);
                        }
                    }

                    // draw a marker at each point
                    if ((MarkerSize > 0) && (MarkerShape != MarkerShape.none))
                        for (int i = 0; i < points.Length; i++)
                            MarkerTools.DrawMarker(gfx, points[i], MarkerShape, MarkerSize, Color);
                }


                PointF point = new PointF(dims.GetPixelX(Xs[CurrentIndex]), dims.GetPixelY(Ys[CurrentIndex]));

                //Graphics gfx = ScottPlot.Drawing.GDI.Graphics(bmp, dims, lowQuality);
                MarkerTools.DrawMarker(gfx, point, MarkerShape, (float)MarkerSize, Color);
            }
        }

        /// <summary>
        /// Move the line to a new coordinate in plot space.
        /// </summary>
        /// <param name="coordinateX">new X position</param>
        /// <param name="coordinateY">new Y position</param>
        /// <param name="fixedSize">This argument is ignored</param>
        public void DragTo(double coordinateX, double coordinateY, bool fixedSize)
        {
            if (!DragEnabled)
                return;

            if (coordinateX < DragXLimitMin) coordinateX = DragXLimitMin;
            if (coordinateX > DragXLimitMax) coordinateX = DragXLimitMax;
            if (coordinateX < DragYLimitMin) coordinateY = DragYLimitMin;
            if (coordinateX > DragYLimitMax) coordinateY = DragYLimitMax;

            Xs[CurrentIndex] = coordinateX;
            Ys[CurrentIndex] = coordinateY;

            Dragged(this, EventArgs.Empty);
        }

        /// <summary>
        /// Return True if the line is within a certain number of pixels (snap) to the mouse
        /// </summary>
        /// <param name="coordinateX">mouse position (coordinate space)</param>
        /// <param name="coordinateY">mouse position (coordinate space)</param>
        /// <param name="snapX">snap distance (pixels)</param>
        /// <param name="snapY">snap distance (pixels)</param>
        /// <returns></returns>
        public bool IsUnderMouse(double coordinateX, double coordinateY, double snapX, double snapY)
        {
            bool test = false;
            for (int i = 0; i < PointCount; i++)
            {
                test = Math.Abs(Ys[i] - coordinateY) <= snapY && Math.Abs(Xs[i] - coordinateX) <= snapX;
                if (test)
                {
                    CurrentIndex = i;
                    return test;
                }
            }
            return test;
        }

        public LegendItem[] GetLegendItems()
        {
            var singleItem = new LegendItem()
            {
                label = Label,
                markerShape = MarkerShape,
                markerSize = MarkerSize,
                color = Color
            };
            return new LegendItem[] { singleItem };
        }
    }
}
```
</details>

**Comment by swharden** [comment]
> toy implementation for the ScatterPlotDraggable

The more I think about this, the more I like it! It would become CPU-intense for plots with large numbers of points, but for small plots it seems like a neat way to get user input.

An option could be added to only allow movement in the X or Y direction (@EFeru's original suggestion), and then this seems ready to use.

@BambOoxX if you want to open a PR for this I'd be happy to review it and we can get @EFeru's feedback too

**Comment by swharden** [comment]
Tangentially related, look at the cool stuff this website does by letting users drag points in 3D space https://ciechanow.ski/curves-and-surfaces

Having this plot type may help further development of ScottPlot's interpolation module #459 and perhaps aid in detecting and fixing bugs, such as the open #1433

**Comment by BambOoxX** [comment]
> The more I think about this, the more I like it! It would become CPU-intense for plots with large numbers of points, but for small plots it seems like a neat way to get user input.

I figured that as `ScatterPlot`s are already advertised as less efficient than `SingalPlot`s people would not make so much fuss about the performance. Also, as the `DragEnabled` parameters allows to shortcut most operations, I am not sur how much the real penalty is (I did not test it on large datasets).
 
> An option could be added to only allow movement in the X or Y direction (@EFeru's original suggestion), and then this seems ready to use.
> @BambOoxX if you want to open a PR for this I'd be happy to review it and we can get @EFeru's feedback too

I actually tried that, but I have to add a `LockXdrag` and `LockYdrag` as the `DragEnabled` cannot be omitted. I will propose a PR.

**Comment by BambOoxX** [comment]
@swharden Here is the PR, with code inheritance already. It gets better !

**Comment by EFeru** [comment]
It's awesome what you have implemented in #1560. I really like it.

For my use case the best is if I can move the point on the Y axis (up down) and also on the X axis, but restricted between previous X point and next X point. If it is the first or last point then it is only restricted on one side on the X axis (first point only restricted by next point on X, last point only restricted by previous point on X). On the Y axis no restriction, so free movement.

Is that possible already?

**Comment by BambOoxX** [comment]
@EFeru Currently, you can move the points either totally freely, or along a single direction (X or Y) however, as this is a scatter plot, there is no constraint on the monotony of X coordinates. When you say
> but restricted between previous X point and next X point
do you mean that the currently dragged point cannot be moved along the X dimensions or that i should only be able to move between the two surrounding X values ?

**Comment by EFeru** [comment]
I mean in between the points, so as you said that X points are monotonically increasing.
I think it can be done on user side also, so not sure what where is the easiest to add this constraint user or ScottPlot.

**Comment by BambOoxX** [comment]
@EFeru I think it would be ill-advised for a `ScatterPlot` as they do not require monotonic ordering of the X coordinates, but one may think of a `SignalPlot`  with the same properties, where the X coordinates would be constrained.

**Comment by EFeru** [comment]
I agree. Will this be available for SignalPlot too or only ScatterPlot?

**Comment by BambOoxX** [comment]
As `SignalPlot` makes some assumptions on the X coordinates, I would say this should be the only type with this kind of properties. But @swharden  may have something to say about this.

**Comment by swharden** [comment]
Hi @EFeru and @BambOoxX,

> _For my use case the best is if I can move the point on the Y axis (up down) and also on the X axis, but restricted between previous X point and next X point_

I recall hearing a quote like, "the only constant in computer science is that the requirements will change" 😆

I think we can arrive at a solution!

> Will this be available for SignalPlot too or only ScatterPlot?

Let's do this only for ScatterPlot. Signal plots don't store X positions at all (they just store a `SampleRate` and `XOffset`)

## Implementation Recommendation

Notice the `DragTo()` method already does some limiting based on min and max limits

https://github.com/ScottPlot/ScottPlot/blob/a214b94102c107db3799197655b5255c464c7eda/src/ScottPlot/Plottable/DraggableMarkerPlot.cs#L55-L67

I'm thinking you can make a public field like `LimitXDraggingToAdjacentPoints` (oof, what's a better name than that lol)

Then add an extra logic check here something like:

```cs
if (CurrentIndex > 0)
    Xs[CurrentIndex] = Math.Max(Xs[CurrentIndex], Xs[CurrentIndex - 1]);

if (CurrentIndex < Xs.Length - 1)
    Xs[CurrentIndex] = Math.Min(Xs[CurrentIndex], Xs[CurrentIndex + 1]);
```

and stick it in here:

https://github.com/ScottPlot/ScottPlot/blob/a214b94102c107db3799197655b5255c464c7eda/src/ScottPlot/Plottable/ScatterPlotDraggable.cs#L66-L80

## Pull Request

Do one of you two want to give this a try? If so, I'll keep an eye out for a pull request! (no rush)

If not, I'll add this to the triage list #1028 and close this issue if I don't get to it in the next few weeks

**Comment by EFeru** [comment]
@swharden I think is ok only for ScatterPlot to do this. I see this feature to be used only when a few points are plotted, so performance will not be an issue. Sorry for changing the requirements it was not intentional, it just came alog the discussion. And you are right, it is quite common that requirements change while doing it :)

@BambOoxX I am not sure if you have a preference to look at this, because I think you know best the mechanism of draggable points.

**Comment by BambOoxX** [comment]
@EFeru  @swharden I will try to implement this during the week-end.

**Comment by BambOoxX** [comment]
For me as a `ScatterPlot` does not make assumptions about monotony sorting the arrays is required to provide this functionality, which has an impact on performance ...

**Comment by swharden** [comment]
> Sorry for changing

No worries! Sometimes use case details don't reveal themselves until you implement something part way and give it a spin. I'm confident we can reach a solution that works well here!

> I will try to implement this during the week-end.

Awesome, thanks @BambOoxX! While you're in there can you try this and see what you think?

```cs
var rand = new Random();
double[] xs = ScottPlot.DataGen.RandomWalk(rand, 10);
double[] ys = ScottPlot.DataGen.RandomWalk(rand, 10);
var scatter = new ScottPlot.Plottable.ScatterPlotDraggable(xs, ys);
formsPlot1.Plot.Add(scatter);

// so far so good, but this next bit seems to break things
double[] newXs = ScottPlot.DataGen.RandomWalk(rand, 10);
double[] newYs = ScottPlot.DataGen.RandomWalk(rand, 10);
scatter.Update(newXs, newYs)
```

I'm not totally sure what's going on here... dragging doesn't work right after the original arrays are replaced with new ones

**Comment by BambOoxX** [comment]
> I'm not totally sure what's going on here... dragging doesn't work right after the original arrays are replaced with new ones
That's because I had a `new` declaration of `Xs` and `Ys` fields which shadowed the original one. I fixed this in 7e5862260589b006e512013257ebc5a3ed3a2c8d.

There is however something I'm missing here with respect to @EFeru's demand : It feels like the `DragTo` event is actually called repeatedly during a drag even though the mouse button is not released. I think this leads to an overwrite of the `CurrentIndex` property but I can't be sure...

At c0ef523db59aaeae8964ece3adb4dd41b53de27f the surprising part is that the constrained drag works if one drags towards the upper right corner of the box, but doesn't work for the other sides. If one drags to the lower left corner of the box, the constraint is updated if one passes the lower left bound of the box. 

I let you have a bit of fun with it @swharden to see if you have an idea. My mind is getting a bit mixed into all the values and tests to perform this.

**Comment by swharden** [comment]
> I let you have a bit of fun with it @swharden to see if you have an idea. My mind is getting a bit mixed into all the values and tests to perform this.

I'll give this a go tomorrow! To prevent duplicating effort and also to tackle #1463 I'll try to implement this type of constrained dragging on `ScatterPlotList` and see if I can come-up with any insights that may be shared across plot types

**Comment by swharden** [comment]
## My Solution

I solved this in an interesting way. All these scatter plots are getting jumbled-up a bit, but I'm okay with that for now. Here's how I did it with the new `ScatterPlotListDraggable<T>` (oof, what a name!)

My overall goal was not to implement the drag limit logic in the scatter plot. As soon as we allow "limit point to adjacent points" someone else will have a slightly different use case and open an issue "how do I limit dragging to half a point?" and it will never end 😆 This solution lets users define their own logic as a `Func` and pass it into the plottable.

![screenshot-drag-clamp](https://user-images.githubusercontent.com/4165489/150697789-55974997-15b5-4874-bed8-1cac37e81be4.gif)


## Closing this issue but welcome refinements

I'm going to close this issue because the core problem has been solved (or at least documented) and I'm trying to keep the issues list small and concentrated on what I want to focus my firepower on, but I welcome refinement to draggable scatter plots any time!

@BambOoxX if you want to implement a similar strategy in `ScatterPlotDraggable`, go for it! If not I'll probably leave it like it is for now and refactor all the scatter plots some time in the future (#1028)
