### ISSUE TITLE
MarkerPlot: clip when outside data area

### ISSUE THREAD

**Issue by lucabat** [ScottPlot/ScottPlot#1423]
## Bug Report

**Issue:** 
I'm using a point and a crosshair to highlight a specific point in a graph.
The crosshair works as expected but the point is rendered also when it goes outside the axis ranges.
This happens when the user moves the axis around until the point goes outside the axes ranges 
(in the example below the point has coordinates (100,0)).

![vNhLLTphdV](https://user-images.githubusercontent.com/15679379/140530548-418ac9da-77a8-47ea-a50d-1fc3f621b911.png)

**Reproducing:** 

The point is added when the graph is initialized
 
![image](https://user-images.githubusercontent.com/15679379/140529635-76a6b655-3f72-4fb5-b484-c30b5e496f0e.png)

and then is just changed its coordinates in the following way (and its .IsVisible property to show/hide the point).
![image](https://user-images.githubusercontent.com/15679379/140530475-f4885b8d-a7ea-457c-ac65-e47e14066230.png)

Maybe I'm doing something wrong in how I use a point, but I've followed this example: 
https://scottplot.net/faq/mouse-position/#show-value-near-mouse-with-winforms

### System Details
* **ScottPlot Version:** 4.1.27
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** NET Framework 4.7.2

**Comment by PremekTill** [comment]
I have also ran into this problem, and after some testing and having checked the source code, I believe it to be a problem with the recently added MarkerPlot type. First of all, when testing with other plot types, MarkerPlot (including AddPoint, which was changed to create a MarkerPlot in 4.1.27) is the only plot type to go out of bounds, as seen in the following screenshot:

![marker_plot_bug](https://user-images.githubusercontent.com/94750559/142730257-121a0096-c738-4909-8313-f2ff4d72ec2d.png)

Second, after checking the source code, I have noticed that when rendering, most of the other Plottable types call the GDI.Graphics(Bitmap bmp, PlotDimensions dims, bool lowQuality = false, bool clipToDataArea = true) overload (see for example [here](https://github.com/ScottPlot/ScottPlot/blob/6c1a99837a5a412a69d463c2adde564941a080f5/src/ScottPlot/Plottable/BubblePlot.cs#L117)), whereas MarkerPlot only uses the GDI.Graphics(Bitmap bmp, bool lowQuality = false, double scale = 1.0) version, which does not check for bounds (see [here](https://github.com/ScottPlot/ScottPlot/blob/6c1a99837a5a412a69d463c2adde564941a080f5/src/ScottPlot/Plottable/MarkerPlot.cs#L68)). As such, I believe that simply changing MarkerPlot to call the correct overload might be enough to fix this bug, though I'm not familiar enough with the rest of the codebase to be completely sure, there might have been a reason for calling a different overload in the first place (maybe to prevent the marker size from scaling?).

**Comment by AndXaf** [comment]
Dear PremekTill,
I can tell that after I added the PlotDimensions to the second overload you are mentioning the plot area is fully respected - so perhaps it was just forgotten. See attachment:
[MarkerPlot.zip](https://github.com/ScottPlot/ScottPlot/files/7575418/MarkerPlot.zip)
