### ISSUE TITLE
MatchLayout() fails if the source plot was not previously rendered

### ISSUE THREAD

**Issue by AlgoExecutor** [ScottPlot/ScottPlot#1427]
## Bug Report

**Issue:** 

Hi @swharden & Team,

I saw you have adjusted `MatchLayout` a few days ago. Somehow it's not working right now, or I'm doing something wrong? 
At the moment the result looks like this:

![grafik](https://user-images.githubusercontent.com/79081847/141272160-b118299f-dee7-4b54-b531-06759afc4f3b.png)

You can see the layout for the X axis is not transferred from the first to the second chart. I thought MatchLayout was doing it all for me now? ;)
Thanks a lot!

**Reproducing:** 

```cs
...
int offset = 200;
var plotter = new ScottPlot.Plot(w, h-offset);
var volume = new ScottPlot.Plot(w, offset);

plotter.XLabel("");
plotter.YLabel("Price");
plotter.XAxis.DateTimeFormat(true);
plotter.Legend(true, Alignment.LowerLeft);
plotter.AxisAuto();

volume.YLabel("Volume");
volume.XLabel("Date");
volume.XAxis.DateTimeFormat(true);
volume.MatchLayout(plotter, true, false);
volume.AxisAuto();

Bitmap sheet = new Bitmap(w, h);
using (Graphics g = Graphics.FromImage(sheet))
{
    using (SolidBrush drawBrushBackground = new SolidBrush(Color.White))
    {
        g.FillRectangle(drawBrushBackground, new Rectangle(0, 0, w, h));
    }

    using (Bitmap chart = plotter.Render())
    {
        g.DrawImage(chart, 0, 0);
    }

    using (Bitmap chart = volume.Render())
    {
        g.DrawImage(chart, 0, h-offset);
    }
}
```

### System Details
* **ScottPlot Version:** 4.1.27
* **Operating System:** Windows Server 2019
* **Application Type:** Console
* **.NET Version:** NET Framework 4.8

**Comment by swharden** [comment]
Hi @AlgoExecutor, thanks for opening this issue! It took me a while to get to because I'm in the process of moving and it's been more disruptive than I originally expected.

It looks like this bug occurs when attempting to `MatchLayout()` before `Render()` has been called on the source plot. That first render is important because it's when the strings (ticks and axis labels) are rendered and used to determine how much padding each axis should get. Matching the axes _before_ the first render produces this unexpected behavior.

The quick fix is to do something like:

```cs
plotter.Render();
volume.MatchLayout(plotter, horizontal: true, vertical: false);
```

The true fix will be for me to add logic inside `MatchLayout()` to automatically request a render if one has not already been performed.

## Test Program

Here's a complete .NET 6 console app I used to better understand this issue:

```cs
using System.Drawing;
using ScottPlot;

Random rand = new(0);
OHLC[] prices = ScottPlot.DataGen.RandomStockPrices(rand, 100, TimeSpan.FromDays(1));
double[] volumes = ScottPlot.DataGen.Random(rand, 100);

Plot candlePlot = new(800, 400);
candlePlot.AddCandlesticks(prices);
candlePlot.YLabel("Price");

Plot volumePlot = new(800, 150);
volumePlot.AddBar(volumes);

candlePlot.Render();
volumePlot.MatchLayout(candlePlot, horizontal: true, vertical: false);

// render both plots as bitmaps and place them on the same sheet
using Bitmap candleBmp = candlePlot.Render();
using Bitmap volumeBmp = volumePlot.Render();
int sheetWidth = Math.Max(candleBmp.Width, volumeBmp.Width);
int sheetHeight = candleBmp.Height + volumeBmp.Height;
Bitmap outputBmp = new(sheetWidth, sheetHeight);
using Graphics gfx = Graphics.FromImage(outputBmp);
gfx.FillRectangle(Brushes.White, new Rectangle(0, 0, outputBmp.Width, outputBmp.Height));
gfx.DrawImage(candleBmp, 0, 0);
gfx.DrawImage(volumeBmp, 0, candleBmp.Height);
outputBmp.Save("output.png");
```

![output](https://user-images.githubusercontent.com/4165489/141922667-9ad2e9c5-5d74-4ce1-b10c-135847f23d88.png)

**Comment by AlgoExecutor** [comment]
Thank you for the quick solution! Works well. Oh yeah, moving is really not pleasant. You often find that you have accumulated too much stuff. Fingers crossed that you find many hard-working helpers ;)

**Comment by AlgoExecutor** [comment]
Sorry, one more thing. I get here some offset between the first and second chart at the beginning and end of the data.
This also impacts grid lines. Maybe you have a quick idea ;-)
Looks like this:

![grafik](https://user-images.githubusercontent.com/79081847/142077225-7c23d1ae-2a9d-4711-9f55-25df758a0180.png)

Modified your Code:

```
Random rand = new(0);
OHLC[] prices = ScottPlot.DataGen.RandomStockPrices(rand, 34, TimeSpan.FromMinutes(60));
double[] volumes = ScottPlot.DataGen.Random(rand, 34);

Plot candlePlot = new(1200, 600);
candlePlot.AddCandlesticks(prices);
candlePlot.YLabel("Price");

Plot volumePlot = new(1200, 200);
volumePlot.YLabel("Volume");
volumePlot.XLabel("Date");

var volume = volumePlot.AddBar(volumes,prices.Select(x=>x.DateTime.ToOADate()).ToArray());
volume.BarWidth = 1.0 / 24 ;


volumePlot.XAxis.DateTimeFormat(true);
candlePlot.XAxis.DateTimeFormat(true);


candlePlot.Render();
volumePlot.MatchLayout(candlePlot, horizontal: true, vertical: false);


// render both plots as bitmaps and place them on the same sheet
using Bitmap candleBmp = candlePlot.Render();
using Bitmap volumeBmp = volumePlot.Render();
int sheetWidth = Math.Max(candleBmp.Width, volumeBmp.Width);
int sheetHeight = candleBmp.Height + volumeBmp.Height;
Bitmap outputBmp = new(sheetWidth, sheetHeight);
using Graphics gfx = Graphics.FromImage(outputBmp);
gfx.FillRectangle(Brushes.White, new Rectangle(0, 0, outputBmp.Width, outputBmp.Height));
gfx.DrawImage(candleBmp, 0, 0);
gfx.DrawImage(volumeBmp, 0, candleBmp.Height);
outputBmp.Save("output.png");
```

**Comment by swharden** [comment]
> Maybe you have a quick idea ;-)

After the `MatchLayout` call you can call `MatchAxis()` and use arguments to indicate you just want to match the horizontal axes 👍
