### ISSUE TITLE
Linux: Method not found: 'Void ScottPlot.Plot.AxisAuto' exception

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [ScottPlot/ScottPlot#1431]
Hello,

## Bug Report

**Issue:** After upgrading my Console App from .NET 5 to .NET 6 and upgrading ScottPlot from 4.1.26 to 4.1.27 I've got the following exception:

```
Error: System.AggregateException: One or more errors occurred. (Method not found: 'Void ScottPlot.Plot.AxisAuto(Double, Double)'.) ---> System.MissingMethodException: Method not found: 'Void ScottPlot.Plot.AxisAuto(Double, Double)'
```

The fragment of code:

```cs
var plt = new Plot(width, height);
...
plt.Legend(location: Alignment.UpperCenter);
plt.YAxis.Label(yTitle);
plt.XAxis.Label(xTitle);
plt.XAxis.TickLabelStyle(null, null, 24);
plt.YAxis.TickLabelStyle(null, null, 24);
plt.Legend(location: Alignment.UpperCenter);
plt.AxisAuto(0.05, 0.5);   // <= EXCEPTION HERE
plt.SetAxisLimits(yMin: 0);

```

### System Details

* **ScottPlot Version:** 4.1.27
* **Operating System:** Ubuntu Linux 20.04.3 LTS.
* **.NET Version:** .NET 6.0

**Comment by swharden** [comment]
Hi @SvyatoslavRazmyslov, thank you for reporting this! I confirmed similar code works on my Windows system. I'll add a test shortly that allows me to test this code on Linux locally (and in GitHub Actions in the cloud). I'll also use this opportunity to update the CI system to build/test on .NET 6

For reference, here's a complete .NET 6 console application that produces the following output on Windows:
```cs
ScottPlot.Plot plt = new(600, 400);
plt.AddSignal(ScottPlot.DataGen.Sin(51), label: "sin");
plt.AddSignal(ScottPlot.DataGen.Cos(51), label: "cos");
plt.Legend(location: ScottPlot.Alignment.UpperCenter);
plt.YAxis.Label("vertical axis");
plt.XAxis.Label("horizontal axis");
plt.XAxis.TickLabelStyle(fontSize: 24);
plt.YAxis.TickLabelStyle(fontSize: 24);
plt.Legend(location: ScottPlot.Alignment.UpperCenter);
plt.AxisAuto(0.05, 0.5);   // <= EXCEPTION HERE ON LINUX?
plt.SetAxisLimits(yMin: 0);
plt.SaveFig("output.png");
```

![image](https://user-images.githubusercontent.com/4165489/141877439-34bf7fde-96e6-49e2-aa2a-9ba2455d6800.png)

**Comment by SvyatoslavRazmyslov** [comment]
Hi @swharden ,

```
plt.AxisAuto(0.05, 0.5);   // <= EXCEPTION HERE ON LINUX?
```
Yes. I use ScottPlot in cross platform app (Windows/LInux), so I get the exception this line only on Linux.

**Comment by swharden** [comment]
Hi @SvyatoslavRazmyslov, I added that code block as a test:

https://github.com/ScottPlot/ScottPlot/blob/0d45b49c56eba6bbe83e89c66ae74842d2919207/src/tests/Misc/OS.cs#L59-L77

The CI system (GitHub Actions) runs these tests on Windows, MacOS, and Linux. Can you provide more information about the exception that is thrown on your system?

I'll close this issue for now, but feel free to open a PR with a failing test and we can pick this topic up again 👍

**Comment by SvyatoslavRazmyslov** [comment]
Hi @swharden ,

How often the `System.Drawing.Common.dll` is used in this library?

```
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
   at System.Drawing.LibraryResolver.EnsureRegistered()
   at System.Drawing.SafeNativeMethods.Gdip.PlatformInitialize()
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipNewInstalledFontCollection(IntPtr& fontCollection)
   at ScottPlot.Drawing.InstalledFont.ValidFontName(String[] fontNames)
   at ScottPlot.Drawing.InstalledFont.Monospace()
   at ScottPlot.Renderable.Message..ctor()
   at ScottPlot.Renderable.BenchmarkMessage..ctor()
   at ScottPlot.Settings..ctor()
   at ScottPlot.Plot..ctor(Int32 width, Int32 height)
```

Microsoft has officially removed the compatibility with Linux from .NET 6.

**Comment by swharden** [comment]
Hi @SvyatoslavRazmyslov,

> Microsoft has officially removed the compatibility with Linux from .NET 6

Indeed! See the [dotnet designs](https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md) post for older information, but I now see [System.Drawing.Common only supported on Windows](https://aka.ms/systemdrawingnonwindows) is newer 👍 

> How often the System.Drawing.Common.dll is used in this library?

Many thousands of times 😅☠️ 

Cutting this dependency is my primary development effort at the moment (#1036, #1413, #1028). 

System.Drawing's best replacement is likely [Maui.Graphics](https://github.com/dotnet/Microsoft.Maui.Graphics) which was supposed to release this month with .NET 6 but got [pushed back to Q2 of 2022](https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/) when MAUI is anticipated to release, so we are stuck in a difficult place.

**Comment by swharden** [comment]
# Runtime Switch: EnableUnixSupport 

According [Microsoft's documentation](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action) you can hide this warning in .NET 6 by editing the [.NET runtime configuration settings](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/):

```json
{
   "runtimeOptions": {
      "configProperties": {
         "System.Drawing.EnableUnixSupport": true
      }
   }
}
```

According [Microsoft's documentation](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action), "_This configuration switch was added to give cross-platform apps that depend heavily on this package time to migrate to more modern libraries. However, non-Windows bugs will not be fixed. In addition, we may completely remove support for non-Windows platforms in a future release, even if you enable it using the runtime configuration switch._"
