### ISSUE TITLE
ShowValuesAboveBars Text does not get affected by Styles

### ISSUE THREAD

**Issue by JulianusIV** [ScottPlot/ScottPlot#1432]
## Bug Report

**Issue:** ShowValuesAboveBars Text does not get affected by Styles

**Reproducing:** Create a Plot, add a Bar using AddBar and set ShowValuesAboveBars to true, then set a style (for example Gray2)

```cs
// a code sample may improve communication
var plot = new ScottPlot.Plot();
plot.AddBar(data).ShowValuesAboveBars = true;
plot.Style(ScottPlot.Style.Gray2);
```

If you execute this code the Text for the ValuesAboveBars is still dark and barely visible

### Tested with:

- Gray2 
![grafik](https://user-images.githubusercontent.com/65790187/141524011-bad6da71-1f00-4010-80eb-a32a3fd7661b.png)
- Gray1
![grafik](https://user-images.githubusercontent.com/65790187/141523930-5f89dc62-9378-48d6-949a-4a6c0ee6e0a2.png)
- Black
![grafik](https://user-images.githubusercontent.com/65790187/141524090-e30788b7-cd34-459f-8f6d-9c1fad28784d.png)

### System Details
* **ScottPlot Version:** 4.1.27
* **ScottPlot WPF Version:** 4.1.27
* **Operating System:** Windows 10 21H1
* **Application Type:** WPF
* **.NET Version:** .NET 5.0

**Comment by swharden** [comment]
Hi @JulianusIV, thanks for reporting this!

After thinking about it a while I think this is the preferred behavior. Many plot types have fonts which the user can reach-in and customize as desired. This example shows how to customize the style of the values above bars to be consistent with a style. 

```cs
ScottPlot.Plot plt = new(600, 300);
plt.Style(ScottPlot.Style.Gray2);

double[] values = {2, 7, 5, 9, 1, 2, 4, 9, 1, 2, 4};
var bar = plt.AddBar(values);
bar.ShowValuesAboveBars = true;
bar.Font.Color = ScottPlot.Style.Gray2.TickMajorColor; // <-- customize as desired
bar.Font.Bold = true;
bar.Font.Size = 16;

plt.AxisAuto();
plt.SetAxisLimits(yMin: 0);
plt.SaveFig("output.png");
```

![image](https://user-images.githubusercontent.com/4165489/141923453-6b96c5c3-c87a-40cb-bb3f-34f5c8601833.png)

I hope you find this response helpful, and it may help others who end-up here seeking the same functionality as well 👍
