### ISSUE TITLE
Interpolation of more then 160 points triggers exception

### ISSUE THREAD

**Issue by allopatin** [ScottPlot/ScottPlot#1433]
## Bug Report

**Issue:**
When interpolating data arrays with more then 160 elements using PeriodicSpline or EndSlopeSpline a System.InvalidOperationException is triggered.
System.InvalidOperationException
  HResult=0x80131509
  Message=Operation is not valid due to the current state of the object.
  Source=ScottPlot
  StackTrace:
   at ScottPlot.Statistics.Interpolation.PeriodicSpline.CalcParameters()
   at ScottPlot.Statistics.Interpolation.PeriodicSpline..ctor(Double[] xs, Double[] ys, Int32 resolution)
   at Chart_Test.MainWindow..ctor() in C:\Users\hoot\source\repos\Chart_Test\Chart_Test\MainWindow.xaml.cs:line 35

**Reproducing:**
Generate an array of 161 data points and interpolate using `var esi = new PeriodicSpline(dataX, dataY, resolution: 10);` or `var esi = new EndSlopeSpline(dataX, dataY, resolution: 10);`.
This issue can also reproduced with NaturalSpline but the maximum length of the array is higher. I have tested 2048 data points and it triggers the same exception.

```cs
double[] dataX = new double[161];
double[] dataY = new double[161];
Random random = new Random();
for (int i = 0; i < 161; i++) {
    dataX[i] = -85 + i * 11.43;
    dataY[i] = random.Next(-30, -20);
}

var esi = new PeriodicSpline(dataX, dataY, resolution: 10);
ScatterPlot scatterPlot = new ScatterPlot(dataX, dataY);
ScatterPlot scatterPlotInterpolated = new ScatterPlot(esi.interpolatedXs, esi.interpolatedYs);
scatterPlot.MarkerSize = 0;
scatterPlotInterpolated.MarkerSize = 0;
scatterPlot.Color = System.Drawing.Color.Blue;
scatterPlotInterpolated.Color = System.Drawing.Color.Red;
WpfPlot1.Plot.Add(scatterPlot);
WpfPlot1.Plot.Add(scatterPlotInterpolated);
WpfPlot1.Plot.SetAxisLimitsX(-85, -85 + 11.43 * 4);
WpfPlot1.Plot.SetAxisLimitsY(-110, -20);
WpfPlot1.Refresh();
```

### System Details
* **ScottPlot Version:** 4.1.127
* **Operating System:** Windows 11
* **Application Type:** WPF
* **.NET Version:** NET Framework 4.6.1

**Comment by swharden** [comment]
Hi @allopatin, thank you for reporting this!

I have a few issues to resolve before this one, but I'll definitely work toward fixing this. It may be time to revisit the interpolation module to improve its API, performance, and resiliency. On one hand data interpolation is outside the scope of plotting so this module probably should not have been initially included with ScottPlot... but on the other hand it's already there, so it's worth maintaining and improving where possible.

Note: The initial module was added in #459 based off http://www.mosismath.com/NaturalSplines/NaturalSplines.html

Note: This is a fantastic resource https://ciechanow.ski/curves-and-surfaces

I'm copy/pasting this a lot lately: _Sorry for the delay! It took me an unexpectedly long time to get to this because I moved houses and it was a lot more disruptive than I predicted, then right after I got sick for several weeks. I'm doing better now and am happy to be picking this up again. Thanks for your patience along the way!_

**Comment by allopatin** [comment]
No problem, this issue is not that relevant in my case. Nevertheless I thought it was worth pointing out. Thanks for your work.

**Comment by swharden** [comment]
Restating the problem, it's not the _number_ of points, but rather something about your original dataset. Extremely sharp changes in slope really confuse this interpolation engine.

No worries - I have a better cubic interpolator I'll upload in a few minutes!

## Test Setup

```cs
(double[] xs, double[] ys) = GetSharpData(161);

ScottPlot.Plot plt = new();
var psi = new ScottPlot.Statistics.Interpolation.PeriodicSpline(xs, ys, resolution: 20);

plt.AddScatterPoints(psi.givenXs, psi.givenYs, label: "original");
plt.AddScatterLines(psi.interpolatedXs, psi.interpolatedYs, label: "interpolation");
plt.Legend();
```

## Sharp Data

This throws an exception

```cs
private (double[] xs, double[] ys) GetSharpData(int count)
{
    // this dataset has been reported to cause problems
    // https://github.com/ScottPlot/ScottPlot/issues/1433
    Random rand = new(0);
    double[] xs = new double[count];
    double[] ys = new double[count];
    for (int i = 0; i < count; i++)
    {
        xs[i] = -85 + i * 11.43;
        ys[i] = rand.Next(-30, -20);
    }
    return (xs, ys);
}
```

```
  Message: 
System.InvalidOperationException : Operation is not valid due to the current state of the object.

  Stack Trace: 
PeriodicSpline.CalcParameters() line 75
PeriodicSpline.ctor(Double[] xs, Double[] ys, Int32 resolution) line 27
Interpolation.Test_Interpolation_ProblematicData() line 68
```

## Smoother Data

This doesn't crash... but the interpolated spline is obviously wrong ☠️ 

![image](https://user-images.githubusercontent.com/4165489/150060344-35d98a59-4555-4dca-8c22-89967cd87fbb.png)

```cs
private (double[] xs, double[] ys) GetSmoothData(int count)
{
    Random rand = new(0);
    double[] xs = ScottPlot.DataGen.RandomWalk(rand, count);
    double[] ys = ScottPlot.DataGen.RandomWalk(rand, count);
    return (xs, ys);
}
```

## Conclusion

I think it's not the _number_ of points, it's something about the interpolation calculation that's crashing on this particular dataset. Also the math doesn't seem to be right in the existing module.

**Comment by allopatin** [comment]
Let me know if I should test something.

**Comment by swharden** [comment]
An improved interpolation module will be available in the next release! 👍 🚀 

In the mean time you can use the code from this web page to help you smoothly interpolate X/Y data

### https://swharden.com/blog/2022-01-22-spline-interpolation/

![spline-interpolation](https://user-images.githubusercontent.com/4165489/150661140-d37bf180-a970-4cf7-aca4-fb89b88e893c.gif)
