### ISSUE TITLE
Cookbook Recipe Showing Hatched Polygon Fill

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1441]
## Features Suggestion

**Feature description:** It looks like `Polygon` supports [`HatchStyle`](https://github.com/ScottPlot/ScottPlot/blob/master/src/ScottPlot/Plottable/Polygon.cs#L28) but we don't have a recipe. This could be used to show overlapping regions without transparency and blending. For example, this depiction of the max possible and min possible producer surpluses if a price floor is imposed (this is a remaking of a diagram from my prof's notes):
![image](https://user-images.githubusercontent.com/8635304/142050058-848353ae-2fbd-4bae-950b-6a82476a4e53.png)

**Comment by swharden** [comment]
rebuilt cookbook in the cloud: https://github.com/ScottPlot/ScottPlot.NET/runs/4612772207?check_suite_focus=true

recipe now appears on: https://scottplot.net/cookbook/4.1/category/plottable-fill/#hatched-fill
