### ISSUE TITLE
Heatmap: scale-locking (default behavior) is confusing

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1445]
This issue was originally posted by @dhgigisoave in #1435 and I spent a while debugging it myself...

## Restating the Problem

This code does not produce the output I would expect:
```cs
ScottPlot.Plot plt = new(600, 300);

double[,] data = ScottPlot.DataGen.Random2D(new Random(), rows: 100, columns: 100);
var hm = plt.AddHeatmap(data);
hm.XMin = 1;
hm.XMax = 2;

plt.SetAxisLimits(xMin: 1, xMax: 2);
plt.SaveFig("output.png");
```

![image](https://user-images.githubusercontent.com/4165489/142092901-7a5fa728-a21f-4611-a715-3f4c333b8a4a.png)

## The Fix

The problem is that `AddHeatmap()` is automatically calling `AxisScaleLock()`. This functionality can be disabled using an optional argument, but this behavior is hidden behind an optional argument and XML comment and I suspect most people will find the default behavior unexpected and astonishing.

```cs
var hm = plt.AddHeatmap(data, lockScales: false);
```
![image](https://user-images.githubusercontent.com/4165489/142093086-d364a4a1-441e-409d-adf7-95499149d78f.png)

## Change the default behavior? (Breaking change?)

I think the current default behavior is astonishing, so by definition changing the default behavior will be a breaking change 😅 

This is a change I'm highly inclined to consider though. Maybe `AddHeatmapSquare()` could be a method that also calls `AxisScaleLock()` but pops-up in intellisense when users reach for a function to add a heatmap. @bclehmann do you have any suggestions about this topic?

**Comment by bclehmann** [comment]
Are `XMin` and `XMax` are only needed in heatmaps that are mimicking the `CoordinatedHeatmap` behaviour? If so I think we can tell users to set `lockScales: false` in the deprecation warning. This isn't ideal, but it is the easiest, and it's non-breaking.

We could also change `lockScales` to be a `bool?` parameter instead of `bool`, which is null by default. We could treat null as true or as false depending on whether `XMin` or `XMax` are set.

**Comment by swharden** [comment]
> Are XMin and XMax are only needed in heatmaps that are mimicking the CoordinatedHeatmap behaviour?

They're only required if the user wants placement other than the default (bottom-left corner at the origin, 1 unit per pixel)

> We could also change lockScales to be a bool? parameter instead of bool, which is null by default. We could then treat null as true or as false depending on whether XMin or XMax are set

Excellent compromise! I'll do this 👍
