### ISSUE TITLE
.Net 6 WinForms support

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [ScottPlot/ScottPlot#1449]
I have been waiting for some control for charting in .Net 6 WinForms. This one seems the most active and responsive. Would like .Net 6 WinForms support for ScottPlot. Currently it errors out if you try to add it to the Toolbox pane. Not sure if there is a way to drop it in by code alone currently.

**Comment by swharden** [comment]
Related discussion: #1430 

Solved in issue: #1483
