### ISSUE TITLE
MacOS: warning about System.Drawing.Common version conflict

### ISSUE THREAD

**Issue by doctorb81** [ScottPlot/ScottPlot#1460]
**ScottPlot Version: 4.1.27

**Operating System: MacOS 11.5.2

**Application Type:** console

**Question:** 

Apologies for the potentially naive question, am new to this and trying to get ScottPlot to work in a VS 2019 for Mac project. I'm getting the version conflict below; if someone could help me out with this I'd be very grateful

```
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3277: Found conflicts between different versions of "System.Drawing.Common" that could not be resolved.
There was a conflict between "System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" and "System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51".
    "System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was chosen because it was primary and "System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was not.
    References which depend on "System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" [/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/Facades/System.Drawing.Common.dll].
```

**Comment by swharden** [comment]
Hi @doctorb81, sorry about the delay getting back to you on this.

I notice the message is a warning (not an error). Does the program run normally?

If you create a new program using `dotnet new console mydemo` and get ScottPlot with `dotnet add package scottplot` and try the [quickstart code](https://scottplot.net/quickstart/console/) do you have the same issue?

I typically find this error in larger multi-project solutions. Some more information about your project may be helpful here! Let me know if you've made any progress or have any updates.

If I don't hear anything in about a week I'll close this issue, but feel free to reply if/after it's been closed 👍
