### ISSUE TITLE
Can I make scatter plot with colorbar?

### ISSUE THREAD

**Issue by obnews** [ScottPlot/ScottPlot#1461]
## Question Template

**ScottPlot Version:** 4.1.27

**Operating System:** Windows 10

**Application Type:** WinForms, WPF

**Question:** Does ScottPlot suport scatter plot with colorbar? I cannot find any demo on this in Cookbook. It seems the colorbar only goes with heatmap plot. There is an example about the scatter plot with colorbar in matplotlib.
![2021-11-28_163557](https://user-images.githubusercontent.com/3361155/143789451-b300188d-cc24-4762-8ef9-c131ea8d81fb.png)

**Comment by obnews** [comment]
There another example with statistical distribution frequency, does this supported in ScottPlot?
![2021-11-28_195356](https://user-images.githubusercontent.com/3361155/143789610-088fdcfc-e895-4164-8ebc-ed5f1359c7a3.png)

**Comment by swharden** [comment]
Hi @obnews, this should help. I'll create a cookbook example to make this more discoverable. Regarding the histogram on the side, check out this example in the demo application: https://github.com/ScottPlot/ScottPlot/pull/1351

```cs
var plt = new ScottPlot.Plot(400, 300);

// decide which colormap to use and add it to the plot
var cmap = ScottPlot.Drawing.Colormap.Viridis;
plt.AddColorbar(cmap);

Random rand = new(0);
for (int i = 0; i < 100; i++)
{
    // place points randomly on the plot
    double x = ScottPlot.DataGen.RandomNormalValue(rand, mean: 0, stdDev: .5);
    double y = ScottPlot.DataGen.RandomNormalValue(rand, mean: 0, stdDev: .5);

    // color points by their distance from the origin
    double colorFraction = Math.Sqrt(x * x + y * y);
    System.Drawing.Color c = ScottPlot.Drawing.Colormap.Viridis.GetColor(colorFraction);

    plt.AddPoint(x, y, c);
}

plt.SaveFig("scatter-colorbar.png");
```

![image](https://user-images.githubusercontent.com/4165489/147169573-269f65ef-499e-43f5-8922-800a056a117e.png)

PS: Sorry for the delay! It took me an unexpectedly long time to get to this because I moved houses and it was a lot more disruptive than I predicted, then right after I got sick for several weeks. I'm doing better now and am happy to be picking this up again. Thanks for your patience along the way!

**Comment by obnews** [comment]
> 

Thanks. I think I'm getting what I needed.
Your example seems the colors are picked from the already implemented colorbar. Is it possible to plot a colorbar to reflect the values of the scatter points? Like the 'Heatmap with Colorbar' in Cookbook except the data are expressed by scatter points, not squares.

**Comment by swharden** [comment]
HI @obnews,

Yes I think this is possible. Note that the following function will return a `Color` based on any value from `0` to `1.0`

```cs
double colorFraction = 0.123;
Color myColor = ScottPlot.Drawing.Colormap.Jet.GetColor(colorFraction);
```

Knowing this you can scale your bubble colors such that `1.0` represents the maximum size. Something like this:
```cs
double[] values = /* your data */
double maxValue = values.Max();

foreach (double value in values)
{
    Color c = ScottPlot.Drawing.Colormap.Jet.GetColor(value / maxValue);
}
```

Does this help answer your question?

**Comment by obnews** [comment]
HI @swharden ,
It works fine, thanks again.
I made some adjustments to the maximum and minimum values of the colorbar, it now can reflects the real values of the data.
Here is the updated code:

```csharp
using System.Windows;
using System.Windows.Input;
using ScottPlot;
using ScottPlot.Plottable;
using System.Drawing;
using System;
using System.Reflection;
using System.Linq;

namespace WpfApp2_ScottPlot2
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            var plt = new ScottPlot.Plot(400, 300);
            var cb = plt.AddColorbar(ScottPlot.Drawing.Colormap.Jet);
            double[] xs = { 1, 2, 3, 4, 5 };
            double[] ys = { 12, 25, 3, 47, 14 };
            double[] values = { 2, 225, 43, 147, 44 };
            double maxValue = values.Max();
            cb.MinValue = values.Min();
            cb.MaxValue = values.Max();

            for (int i = 0; i < 5; i++)
            {
                plt.AddPoint(xs[i], ys[i], ScottPlot.Drawing.Colormap.Jet.GetColor(values[i] / maxValue));
            }
            new WpfPlotViewer(plt).Show();
        }
    }
}
```
