### ISSUE TITLE
How to show the figure in a Console Application，not save to disk？

### ISSUE THREAD

**Issue by wangyexiang** [ScottPlot/ScottPlot#1465]
Dear all，how to show the figure in a Console Application？Is there a show method like` plt.show()` of `matplotlib`? I want to show my figure，not to save it to the disk by calling the` SaveFig` method. Thx.

**Comment by bclehmann** [comment]
There is no such capability built in. You can obtain a bitmap of the plot and render it in a window of your own if you wish, or you can save it to disk and open the system photo viewer programmatically.

**Comment by wangyexiang** [comment]
> There is no such capability built in. You can obtain a bitmap of the plot and render it in a window of your own if you wish, or you can save it to disk and open the system photo viewer programmatically.

Thank you.@bclehmann

**Comment by swharden** [comment]
Hi @wangyexiang, this is a great question! 

Technically @bclehmann there is a way to launch a mouse-interactive plot from a console application. I tried to mimic what Python does with the matplotlib viewer:

![image](https://user-images.githubusercontent.com/4165489/147171627-47342a62-94a4-4b92-b555-27b57b9583d0.png)

## Program.cs
```cs
ScottPlot.Plot plt = new();
plt.AddSignal(ScottPlot.DataGen.Sin(51));
plt.AddSignal(ScottPlot.DataGen.Cos(51));
ScottPlot.FormsPlotViewer win = new(plt);
win.ShowDialog();
```

## MyConsoleApp.csproj
```xaml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="scottplot" Version="4.1.27" />
    <PackageReference Include="scottplot.winforms" Version="4.1.27" />
  </ItemGroup>

</Project>
```
