### ISSUE TITLE
RadialGaugePlot: System.Drawing throws OutOfMemoryException when drawing small arcs

### ISSUE THREAD

**Issue by arthurits** [ScottPlot/ScottPlot#1474]
## Bug Report

**Issue:** an "OutOfMemoryException" is fired whenever the `SweepAngle` property in any of the gauges's is equal or below 0.01.

![image](https://user-images.githubusercontent.com/63915486/145582333-be00dfc2-e435-4874-8ff3-6584502cdea7.png)

**Explanation:** according to [this post](https://stackoverflow.com/questions/14937057/reproducible-crash-using-graphics-drawarc/14939562#14939562) it seems that `DrawArc` doesn't handle very well the combination of pen width and small sweep angles.
https://github.com/ScottPlot/ScottPlot/blob/6c1a99837a5a412a69d463c2adde564941a080f5/src/ScottPlot/Plottable/RadialGauge.cs#L152-L159

**Reproducing:** using these values, the `DrawArc` function fails for sweep angles equal of below 0.01. However, using less values (less gauges, which result in a wider pen width does modify the 0.01 threshold limit.
```cs
var plt = new ScottPlot.Plot(600, 400);
double[] values = { 505, 590, 0.005, 0.005, 0.0005, 0.005, 0.005, 0.0005 };
plt.AddRadialGauge(values);
```

**Solution:** either check for values lower than 0.01 when creating the plot's `RadialGauge` instances

https://github.com/ScottPlot/ScottPlot/blob/6c1a99837a5a412a69d463c2adde564941a080f5/src/ScottPlot/Plottable/RadialGaugePlot.cs#L289-L308
```cs
SweepAngle = sweepAngles[index] <= 0.01 ? 0 :  sweepAngles[index],
```
or make the checking when calling `DrawArc` inside the `RenderGaugeForeground` function (it might be wiser to do the same inside `RenderBackground`):
```cs
gfx.DrawArc(
                pen,
                (center.X - radius),
                (center.Y - radius),
                (radius * 2),
                (radius * 2),
                (float)StartAngle,
                SweepAngle <= 0.01 ? 0 : (float)SweepAngle);
```

These suggestions are GDI+ dependant, meaning that they might not be needed whenever ScottPlot is ported to other graphics library.

### System Details
* **ScottPlot Version:** 4.1.27
* **Operating System:** Windows 11
* **Application Type:** WinForms
* **.NET Version:** .NET 6.0

**Comment by swharden** [comment]
Hi @arthurits, thanks for opening this issue. I may not have ever noticed this but wow, a hard exception in the render loop is not good!

For the fix I'd favor doing the angle check in the render method just before `gfx.DrawArc` and perhaps in a comment note that the check is specific to `System.Drawing`. When the rendering engine is replaced I'll certainly search the code base for the string "System.Drawing" so if it shows up in a comment I'll know to change it appropraitely.

Would you be up for making this change and opening a PR I can merge-in? If not, no worries, I can get to it in a few days. Thanks!

**Comment by arthurits** [comment]
Sure. No problem!

Although it's highly unlikely that very low sweep angles are passed to `gfx.DrawArc`, it could be the case when reading and plotting data from a sensor (that's certainly my case). So, it makes sense fixing this issue while the library relies on `System.Drawing`.

I'll open the PR with the suggested fix and comment note.
