### ISSUE TITLE
How to set xtick(ytick) direction?

### ISSUE THREAD

**Issue by wangyexiang** [ScottPlot/ScottPlot#1475]
Dear all, how to set the  direction of tick inward? For `matplotlib`, one can use` plt.rcParams['xtick.direction'] = 'in'` to set the  direction of tick inward.

**Comment by bclehmann** [comment]
Would you mind including a screenshot of the intended behaviour? I'm not entirely sure what you're asking for.

**Comment by wangyexiang** [comment]
> Would you mind including a screenshot of the intended behaviour? I'm not entirely sure what you're asking for.

Dear sir, I want to change the direction of tick, like this:
**original:**
![image](https://user-images.githubusercontent.com/23202109/146104190-e96d85d9-491c-4688-9ad3-c8aa3745961e.png)
**final:**
![image](https://user-images.githubusercontent.com/23202109/146104317-3047aaf6-3549-4821-a0d4-47ad748096f8.png)
 
Thank you sir.

**Comment by bclehmann** [comment]
I don't believe this is currently possible, but it may be a good feature for the future.

**Comment by wangyexiang** [comment]
> I don't believe this is currently possible, but it may be a good feature for the future.

OK，thank you sir for your reply. 
Now, we can set the width of axis by using `plt.XAxis.Line(width: 2);`, but how can we set the width of tick?

**Comment by bclehmann** [comment]
Again, I don't believe this is currently implemented.

**Comment by wangyexiang** [comment]
Dear sir, thank you sir for your reply.

**Comment by swharden** [comment]
I'll add a method to allow tick mark direction to be customized and release it with the next NuGet package. 

I'll also add a method to allow major vs. minor tick visibility to better solve #1457

![image](https://user-images.githubusercontent.com/4165489/147177112-4358bdf0-e9ba-4907-8616-80708cf6d526.png)

```cs
plt.XAxis.TickMarkDirection(outward: false);
plt.YAxis.TickMarkDirection(outward: false);
```
