### ISSUE TITLE
SignalXY: exception when filled area is 0px

### ISSUE THREAD

**Issue by chenxuuu** [ScottPlot/ScottPlot#1476]
## Bug Report

**Issue:** 

```log
System.ArgumentException: 矩形“{X=316,Y=0,Width=0,Height=547}”的宽度或高度不能等于零(width or height should not be 0)
```

**Reproducing:** 

I only find 1 way to reproduce this

when I scrolling mouse to make line smaller, it happend

![KenkBdGXTP](https://user-images.githubusercontent.com/10357394/146128414-5ddd7f57-abb7-4092-aafe-0e34f2a0b0c7.gif)

wpf code(project zip:[WpfApp2.zip](https://github.com/ScottPlot/ScottPlot/files/7716676/WpfApp2.zip))

```cs
private void Window_Loaded(object sender, RoutedEventArgs e)
{
        double[] data = DataGen.RandomWalk(100);
        double[] x = new double[100];
        for(int i=0;i<100;i++)
                x[i] = i;
        var line = Plot.Plot.AddSignalXY(x,data);
        line.FillBelow();
        Plot.Render();
        }
}
```

```xml
<WpfPlot Name="Plot"/>
```

---

and another way only reproduce once, when I render image without any mouse scroll. but I can't reproduce this now

### System Details
* **ScottPlot Version:** 4.1.27
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** NET Framework 4.7.2

**Comment by swharden** [comment]
Thank you for reporting this @chenxuuu! I'll create a failing test to demonstrate this issue, fix it with your PR, and release a updated NuGet package shortly 👍 

```cs
var plt = new ScottPlot.Plot(400, 300);
var line = plt.AddSignalXY(
    xs: ScottPlot.DataGen.Consecutive(100),
    ys: ScottPlot.DataGen.RandomWalk(100));
line.FillBelow();

for (int i=0; i<10; i++)
{
    plt.AxisZoom(.1, .1);
    plt.Render();
}
```

```
System.ArgumentException : Rectangle '{X=223,Y=0,Width=0,Height=300}' cannot have a width or height equal to 0.
```
