### ISSUE TITLE
ValueType for .NET framework 4.6.1

### ISSUE THREAD

**Issue by softempire** [ScottPlot/ScottPlot#1478]
I'm using ScottPlot with .NET Framework 4.6.1.

The method GetMouseCoordinates will return System.ValueTuple which is introduced in .NET framework 4.7 and I can't compile my program now. Is there a workaround available for the method?

**Comment by softempire** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple?view=net-6.0&viewFallbackFrom=netframework-4.6.1

**Comment by swharden** [comment]
Hi @softempire,

You can install the `System.ValueTuple` package from NuGet https://www.nuget.org/packages/System.ValueTuple in your .NET 4.6.1 app and your program should compile as expected.

Good luck!
Scott
