### ISSUE TITLE
Treemap: new plot type

### ISSUE THREAD

**Issue by zhaobingwang** [ScottPlot/ScottPlot#1479]
Can "Treemap" be supported? Similar to the echarts [Treemap ](https://echarts.apache.org/examples/zh/index.html#chart-type-treemap)

**Comment by swharden** [comment]
Hi @zhaobingwang, this is an interesting idea! Thank you for the suggestion. I'll investigate this topic and update this issue when I decide whether or not to implement it.

Resources:
* https://en.wikipedia.org/wiki/Treemapping
* https://www.d3-graph-gallery.com/treemap.html
* https://github.com/d3/d3-hierarchy/blob/main/README.md#treemap
* https://github.com/brendanmoore/svg-treemap
* http://pascallaurin42.blogspot.com/2013/12/implementing-treemap-in-c.html
* https://www.win.tue.nl/~vanwijk/stm.pdf

**Comment by swharden** [comment]
After thinking about this for a while I decided to de-prioritize creating this in favor of working on the render system (#1036). It's still a good idea for a potential feature, so the suggestion was added to the triage list (#1028) and anyone is welcome to create this plot type and open a pull request to contribute it to the rest of the project 👍

**Comment by swharden** [comment]
I'm re-opening this now because it would be great to be able to create tree maps showing the size of classes and namespaces in large code bases

e.g., lines of code (size) and cyclomatic complexity (color)
![image](https://user-images.githubusercontent.com/4165489/223590005-6892d1ce-3e2b-448a-962d-541cd63f95fd.png)

example from https://ndepend.com/docs/treemap-visualization-of-code-metrics

**Comment by swharden** [comment]
from https://www.win.tue.nl/~vanwijk/stm.pdf

![image](https://user-images.githubusercontent.com/4165489/223590911-0033fd2e-0bf1-4549-9169-79354ae1cc4b.png)

**Comment by swharden** [comment]
I wrote a blog post about this topic and have working code there that generates treemaps.

It shoudn't be too hard to extend it to make a new plot type.

https://swharden.com/blog/2023-03-07-treemapping/

![image](https://user-images.githubusercontent.com/4165489/223628479-d6290894-99d5-43ca-8dfb-b638b2576643.png)

**Comment by alexhelms** [comment]
Is there still any interest in adding this plot type? I have a use case but not sure I can commit time to adding it to ScottPlot. Thanks!
