### ISSUE TITLE
A way to append items to the default right click menu ?

### ISSUE THREAD

**Issue by BambOoxX** [ScottPlot/ScottPlot#1480]
**ScottPlot Version:** ScottPlot  4.1.2.7

**Operating System:** Windows 10

**Application Type:** WinForms

**Question:** 

After going through the cookbook and several examples, I was able to replace the default right-click menu with custom functionalities, but I can't figure a way to just append options to the existing default menu. 
This question seems fairly dumb, yet I did not find a way (or an example) on how to extend the functionalities of the right click instead of overriding them altogether.

Would you have a suggestion on how to do that ?

Side note, my main program is in vb.net and not C# so I may have entirely missed an obvious C# way to do this.

**Comment by swharden** [comment]
> After going through the cookbook and several examples, I was able to replace the default right-click menu with custom functionalities, but I can't figure a way to just append options to the existing default menu.

Hi @BambOoxX, 

It is not possible to _edit_ the default right-click menu but it is possible to replace it. https://scottplot.net/faq/right-click-menu

Here's the code for the default right-click menu, so it should be easy to implement these features yourself then just add one more at the end if you wish:

https://github.com/ScottPlot/ScottPlot/blob/b4f881945493e0afb45d7d43f4ea54ee6369252d/src/controls/ScottPlot.WinForms/FormsPlot.cs#L209-L230

Hope it helps!
Scott
