### ISSUE TITLE
WinForms 6 Support

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1483]
### Discussed in https://github.com/ScottPlot/ScottPlot/discussions/1430

Investigate whether a separate .NET 6 package is required for each of the controls

https://github.com/ScottPlot/ScottPlot/blob/d55bfbfb35cbd31c9ce0edb97d06e1a000fcf9d9/src/controls/ScottPlot.WinForms/ScottPlot.WinForms.NUGET.csproj#L4

**Comment by swharden** [comment]
Works on my system! More discussion in #1430 

https://user-images.githubusercontent.com/4165489/146845485-dccd6813-a3aa-427c-9784-1c8aefdfcafb.mp4

**Comment by swharden** [comment]
Following-up, I found that the `ScottPlot.sln` was not showing the `FormsPlot` in the toolbox. I'm still not totally sure why, but adding `net6.0-windows` as a `TargetFrameworks` for the control helped, and oddly _it had to be first in the list_ of target frameworks. After making this change it appeared in the toolbox 🤷 

```xml
  <PropertyGroup>
    <TargetFrameworks>net6.0-windows;net5.0-windows;net472</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
```

**Comment by bclehmann** [comment]
> oddly it had to be first in the list of target frameworks.

Very weird, is this already known about? Might be worth reporting to Microsoft.

**Comment by swharden** [comment]
> Might be worth reporting to Microsoft

I tried pretty hard to recreate this bug in a new solution created from scratch and I couldn't do it. I'm guessing it's a super niche corner case for complex solutions with mixed .NET framework and core projects... since I can't reproduce it, I probably won't report it 🤷 

> is this already known about?

I did find a few instances of posts about older versions of Visual Studio that noted something along the lines of, "when targeting multiple frameworks, Visual Studio designer just uses the first one in the list". It's probably a good rule of thumb to always order the newest target first... and hope people are using a modern version of Visual Studio 😅 #1500

I'm thinking of only targeting .NET 6 for the next major version of ScottPlot that drops System.Drawing dependency 😮 Multi-targeting has so many rough edges with regard to testing, building, packaging, and interacting with Visual Studio. I'd love to stop supporting msbuild, and be able to use the newer language features without too much hacking (records, nullable, spans, etc). I'm curious how much pushback we'd get.

**Comment by bclehmann** [comment]
> I'm thinking of only targeting .NET 6 for the next major version of ScottPlot that drops System.Drawing dependency 😮

Personally, I would at least wait until a release hits end-of-life before deprecating it. When I was interning I saw most projects were on .NET Core 3.1 or earlier. No one wanted to upgrade to .NET 5 unless they were going to use the new features, as 3.1 was an LTS and 5 was not (this was several months before .NET 6).

Honestly, even if one waits after EOL I think it's a little soon to drop support. Microsoft only gives 3 years for LTS releases, which is pretty short, and that isn't accounting for some failures in backwards compatibility. Tracking EOL honestly sounds like hell anyways with all the mishmash of .NET Framework/Core/Standard, and the different implementations of .NET Standard all have different EOL dates, because why not.

**Comment by swharden** [comment]
> Personally, I would at least wait until a release hits end-of-life before deprecating it

This could become a pretty important discussion topic worth considering carefully!

According to the [Lifecycle FAQ](https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework) .NET Framework through 4.6.1 will reach EOL soon (April 2022) but .NET Framework 4.8 is part of Windows 10 and its lifecycle policy will track its parent OS which is expected to EOL in 2025 😬

I don't love the idea, but maybe a version split would be acceptable, with updates limited to bugfixes and all development/features focused on the newer branch. It will be a huge burden lifted to drop MSBuild and the multi-targeting nuances. The switch gets a little more justification considering Microsoft is forcing our hand by deprecating cross-platform support for System.Drawing now.

An option still on the table is using _another_ level of abstraction, and passing an `IRenderer` throughout all the existing code. I'm exploring this idea currently as a less-disruptive way to transition to Maui.Graphics (and leave the door open for a raw Skia renderer or something different in the future).

As of this moment, I'm probably leaning toward maintaining a .NET Framework/.NET 5 ScottPlot 4 that uses System.Drawing, and a .NET 6+ ScottPlot 5 that doesn't. I'm still trying to buy a little more time watching Maui.Graphics mature to see if that will make the decision more obvious in the future.

**Comment by bclehmann** [comment]
I think a version split has the potential to claw back a lot of the time saved from dropping multi-targeting. While leaving a lot of users without the latest features.
