### ISSUE TITLE
Axis Auto fails to scale plots on the secondary axis

### ISSUE THREAD

**Issue by Niravk1997** [ScottPlot/ScottPlot#1497]
## Bug Report

**Issue:** (Axis Auto fails to scale plots on the secondary axis)

The AxisAuto method does not scale any plots on the secondary axis. Pressing the mouse scroll-wheel button also does not scale any plots on the secondary axis. This was working fine in the previous ScottPlot version.

![AxisAuto_SecondaryAxis_Fail](https://user-images.githubusercontent.com/52579388/147296181-635368a8-9ea2-4d9a-bb99-f116897442c7.gif)

### System Details
* **ScottPlot Version:** 4.1.27
* **Operating System:** (Windows 10)
* **Application Type:** (WPF)
* **.NET Version:** (NET Framework 4.7.2)

**Comment by karthikvijayjirlimath** [comment]
Try cleaning the solution in visual studio and then rebuild the solution.

**Comment by Niravk1997** [comment]
I just compiled the ScottPlot Demo (WPF, 4.1.28) from the source code, the bug is still present.

**Comment by swharden** [comment]
I identified the problem and fixed it with #1498 - Thanks for reporting it @Niravk1997! It will be fixed in the next release 👍
