### ISSUE TITLE
Colorbar: add additional options for placement/alignment

### ISSUE THREAD

**Issue by Niravk1997** [ScottPlot/ScottPlot#1524]
## Allow users to place the Colorbar on the left side of the plot

Would it be possible to allow users to change the default placement of the Colorbar? Like shown in the below picture.

![Colorbar on left side](https://user-images.githubusercontent.com/52579388/147844777-7bfb5bcc-5acb-4b07-b071-cecd6902be29.PNG)

**Comment by swharden** [comment]
I refactored the code a bit to enable one to easily place the colorbar on the left #1631

Thanks for the suggestion!

![image](https://user-images.githubusercontent.com/4165489/152089689-29241b6d-0129-45b8-b507-d3b516082571.png)

I didn't add logic to swap the position of the colorbar and ticks, but if this would be valuable for your application feed free to add that extra little logic to the `Colorbar.cs` file and create a pull request and I can merge it in expediently 👍
