### ISSUE TITLE
Drag zoom affects first and second axes in different manners 

### ISSUE THREAD

**Issue by BambOoxX** [ScottPlot/ScottPlot#1537]
## Bug Report

**Issue:**
I am unsure whether this is a true bug report or a wrong use of the tools on my part, so if it is (not a bug), sorry in advance for the inconvenience.

When plotting quantities on the first and second (at least Y) axes, zooming in and out using the scroll or the drag zoom affects plottables with different `AxisIndex` in different fashions, resulting in relative size between such plottables being different.

I would have expected that the zoom would not affect relative sizes between plottables, but just the axis limits (if such limits are free of course). 

Another remark, but this could take the form of a feature request, in addition/extension to the LockAxisLimits, it may be relevant to give the possibility to only lock one of the limits. This could be interesting in the case where power density or some bars are plotted and one wants to zoom to see small contributions, but not lose the fact that the lower limit has to remain 0.

See the screenshots below
- Initial plot 
![image](https://user-images.githubusercontent.com/42067365/148551965-bc343cd5-d252-4e72-9d3b-10354574197b.png)
- Drag zoom
![image](https://user-images.githubusercontent.com/42067365/148552085-63be4acb-ac84-43af-8e83-97273d2120a3.png)
- Result of zoom
![image](https://user-images.githubusercontent.com/42067365/148552135-e15cbf68-c5c2-4bf5-b612-2c6d03086d46.png)

Note that click the central mouse button returns to the correct initial plot

**Reproducing:** (What do others have to do to reproduce the bug?)

```cs
// a code sample may improve communication
namespace live_sandbox
{

    public static class Program
    {
        public static void Main()
        {
            // create a plot
            var plt = new ScottPlot.Plot();
            plt.AddSignal(ScottPlot.DataGen.Sin(51,5));
            plt.AddSignal(ScottPlot.DataGen.Sin(51, 5,0,0.5));
            plt.AddSignal(ScottPlot.DataGen.Sin(51, 5,0,0.25));
            plt.AddSignal(ScottPlot.DataGen.Sin(51, 5, 0, 0.125));

            var yaxis1plot = plt.AddScatterPoints(ScottPlot.DataGen.Sin(51), ScottPlot.DataGen.Cos(51));
            yaxis1plot.YAxisIndex = 1;
            plt.Add(yaxis1plot);


            // launch the plot in an interactive window
            var window = new ScottPlot.FormsPlotViewer(plt);
            window.ShowDialog();
        }
    }
}
```

### System Details
* **ScottPlot Version:** 4.1.29
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** NET Framework 4.7.2

**Comment by BambOoxX** [comment]
@swharden  While playing with the `LockLimits` / `SetAxisLimits` / `SetOuterViewLimits` settings, I think I achieved a reasonable behavior. I will just let this open for a day in case you think this is a true bug.

**Comment by bclehmann** [comment]
There is a problem in your code, you set `yaxis1plot.YAxisIndex = 1;` but you did not create a y-axis with index 1. It turns out that there is one created by ScottPlot which is why it didn't throw an error, but it doesn't have valid axis limits.

Now, even with that addressed, the problem still persists. I had a crack solving it but for whatever reason, I couldn't make the zoom look right on both sets of axes.

**Comment by bclehmann** [comment]
As an aside, it's a little bit weird that the user has to handle axisIndex, it seems like something that should be internal. It allows confusion and indexes to be accidentally reused, while also giving the user more work. Maybe an idea for a future release would be to automatically assign them.

**Comment by BambOoxX** [comment]
> There is a problem in your code, you set `yaxis1plot.YAxisIndex = 1;` but you did not create a y-axis with index 1. It turns out that there is one created by ScottPlot which is why it didn't throw an error, but it doesn't have valid axis limits. You can create a new axis with `plt.AddAxis(Renderable.Edge.Left, axisIndex: someNumberGreaterThanOne);`

@bclehmann Thanks for the tip, I mostly based my developments on the cookbook, and there seems to be no need to add the second axis explicitely, see https://scottplot.net/cookbook/4.1/category/multi-axis/#primary-axes. Or it may mean that the cookbook needs an update in that regard

**Comment by BambOoxX** [comment]
> As an aside, it's a little bit weird that the user has to handle axisIndex, it seems like something that should be internal. It allows confusion and indexes to be accidentally reused, while also giving the user more work. Maybe an idea for a future release would be to automatically assign them.

This may be work for a later update. As of now it does not seem to be possible to get all axes liked to a `Plot` only `XAxis`,`XAxis2` and `YAxis`,`YAxis2`

**Comment by bclehmann** [comment]
> As of now it does not seem to be possible to get all axes linked to a Plot only XAxis,XAxis2 and YAxis,YAxis2

The user is responsible for keeping track of any axes they create with `plt.AddAxis`, the function returns the created axis.

**Comment by BambOoxX** [comment]
> The user is responsible for keeping track of any axes they create with `plt.AddAxis`, the function returns the created axis.
I understand that, and it is probably for good reasons, but when dealing internally with events like `DragTo` there is currently no way of knowing on which axis the current draggable is. Every interaction of such type is assumed to happen on the (0,0) axis pair.

**Comment by bclehmann** [comment]
> there is currently no way of knowing on which axis the current draggable is

I hadn't thought about that, but I think if you have access to the plottable you can use the `xAxisIndex` and `yAxisIndex` to find which axis it is on. If you somehow lose a reference to one of the axes that you've added you can access the internal list with `plt.GetSettings().Axes`, although that's unadvised because the `Settings` class is not guaranteed to be stable between releases.

I accept that's a little clunky, perhaps @swharden has an idea how that could be improved.

**Comment by BambOoxX** [comment]
>I hadn't thought about that, but I think if you have access to the plottable you can use the `xAxisIndex` and `yAxisIndex` to find which axis it is on. 

With the current API, you can get the index, but you cannot retrieve the handle to the corresponding `Axis`. A method like a `getParentX/YAxis()` or a property pointing towards the correct axis would be helpful.

**Comment by BambOoxX** [comment]
Ok, after looking at the code, it seems related to the fact that `MouseZoomRect` only accounts for the firs set of axes

https://github.com/ScottPlot/ScottPlot/blob/b1c93cbbaf9ee3744430647dbdd74b19a9da29aa/src/ScottPlot/Settings.cs#L487-L510
