### ISSUE TITLE
How to match axes by origin (not limits)

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1543]
Is it possible to lock two Y axes together such that the zero position for both is always matched?

If so, a code example may be useful to share so others may be able to achieve this functionality in the future.

If not, consider extending the library to make this possible.

### Originally discussed in https://github.com/ScottPlot/ScottPlot/discussions/1539

<div type='discussions-op-text'>

<sup>Originally posted by **tonpimenta** January  7, 2022</sup>
Dear community,
I am plotting with two different Y Axis and I would like both origins 0 to be at same position (height). How can I do that? To set Yaxis2 origin to the same position as Yaxis!
Thanks in advance for the help 

![Capturar](https://user-images.githubusercontent.com/97309305/148761659-77339c84-3097-4510-aaf7-5f69a693bb7d.PNG)
</div>

**Comment by BambOoxX** [comment]
@swharden Here is a basic example which preserves the identity of the relative position of the zeros on two `YAxis`

![image](https://user-images.githubusercontent.com/42067365/149671961-df759c90-a0b4-49f0-9cdc-56fc446cbaa8.png)

<details>
```cs
using System;
using System.Drawing;
using System.Windows.Forms;
using ScottPlot;
using ScottPlot.Plottable;
using System.Linq;
using ScottPlot.Drawing;
using System.Collections.Generic;


namespace live_sandbox
{
    public partial class Program : Form
    {
        public static void Main()
        {
            // create a plot
            var plt = new ScottPlot.Plot();
            var rand = new System.Random();
            var dataX = ScottPlot.DataGen.Consecutive(51, 1, 0);
            var dataY = ScottPlot.DataGen.Random(rand,51, 1, 0.5);
            var dataY2 = ScottPlot.DataGen.NoisyLinear(rand,51,2,-5,0.3);

            var sig = new ScatterPlot(dataX,dataY);
            sig.YAxisIndex = 0;
            var sig2 = new ScatterPlot(dataX, dataY2);
            sig2.YAxisIndex = 1;
            plt.Add(sig);
            plt.Add(sig2);
            plt.YAxis2.Ticks(true);

            // launch the plot in an interactive window
            var window = new ScottPlot.FormsPlotViewer(plt);
            window.formsPlot1.AxesChanged += new EventHandler(formsPlot1_OnAxesChanged);

            window.ShowDialog();

            void formsPlot1_OnAxesChanged(object sender, EventArgs e)
            {
                // assumes master is YAxis and the slave is YAxis2
                var fplot = (FormsPlot)sender;
                fplot.Plot.YAxis2.Dims.SetAxis(
                    fplot.Plot.YAxis.Dims.Min / fplot.Plot.YAxis.Dims.Span * fplot.Plot.YAxis2.Dims.Span,
                    fplot.Plot.YAxis.Dims.Max / fplot.Plot.YAxis.Dims.Span * fplot.Plot.YAxis2.Dims.Span);
            }
        }
    }
}
```
</details>
