### ISSUE TITLE
New plot type: Strip Charts

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1551]
## Features Suggestion

**Feature description:** Strip charts are derived from scatter charts. I don't know if a convenience function is necessary, or maybe just something in the cookbook.

Example with points lined up: 
![image](https://user-images.githubusercontent.com/8635304/149260603-6bc47ea2-dd13-4743-b09e-38e91ca9adea.png)

Example with points randomly moved up/down:
![image](https://user-images.githubusercontent.com/8635304/149260656-41894faf-7e28-4c08-9ee2-010e825ac9a7.png)

**Code example:** Only applicable if we make a function or plottable for stripcharts.

**Comment by swharden** [comment]
This is a good idea! ... but I'm going to add this to the triage list (#1028) and try to focus more of my time/effort into #1036

**Comment by bclehmann** [comment]
I started working on this but then realized that a very similar capability is provided by the population plot:

```cs
            var popPlot = plt.AddPopulations(poulations);
            popPlot.DataFormat = ScottPlot.Plottable.PopulationPlot.DisplayItems.ScatterOnly;
            popPlot.DistributionCurve = false;
```

Results in this image:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/8635304/151724289-a050d67e-4d87-44e2-904e-e97b3b49faeb.png">
