### ISSUE TITLE
New plot type: Forest Plot

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1552]
## Features Suggestion

**Feature description:** Similar to #1551, forest plots are derivatives of scatter plots. They're often used to show several estimates of a value such as in the example below:
![image](https://user-images.githubusercontent.com/8635304/149260945-b2c53829-ec9c-4931-96f5-86631d66d858.png)

Apparently, they're also sometimes called Blobbograms, but I've never heard that before.

**Code example:** This could be a new plottable, a convenience function, or just a section in the cookbook.

**Comment by swharden** [comment]
This is a good idea! ... but I'm going to add this to the triage list (#1028) and try to focus more of my time/effort into #1036
