### ISSUE TITLE
Add Plot.Title as an alias for Plot.XAxis2

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1564]
Although the cookbook shows how to extensively customize the title, it's not intuitive https://scottplot.net/cookbook/4.1/category/plottable-text/#custom-fonts

Users who just find `Plot.Title()` don't have all the options they need. We could add this to the plot module to make it more discoverable:

```cs
Axis Title => XAxis2;
```

Suggested by Hendri via email

**Comment by bclehmann** [comment]
I don't think it's very intuitive that someone who uses `plt.Title` gets an `Axis` and not a string or a title-specific class.

A user trying to set the title might get confronted with something like `plt.Title.LockLimits()` by Intellisense, which seems really weird.

**Comment by swharden** [comment]
Good point! Maybe we can mark it obsolete with a message that the title is actual the label of the secondary X axis

**Comment by bclehmann** [comment]
I think the source of the weirdness is that an axis label is the title, conceptually they are different things.

Also, you could imagine someone struggling to have a label on XAxis2 and a plot title at the same time.

**Comment by swharden** [comment]
Oof... I can't `Title => XAxis2` because `Title()` already exists

I don't want to obsolete `Title()` because it's used in so many places

I'll add a note to the docstring indicating to interact with `XAxis2.Label()` for extensive options

> I think the source of the weirdness is that an axis label is the title, conceptually they are different things.

Thanks for your input @bclehmann! I definitely agree.

I will add an overload with more options to `Title()` just to help people along. This feels like digging myself deeper in this hole... but I think it's such a common use case it makes sense to make this as easy as possible.
