### ISSUE TITLE
Make the `LegendItems` property of a legend public

### ISSUE THREAD

**Issue by BambOoxX** [ScottPlot/ScottPlot#1578]
## Features Suggestion

Currently, if one wants to get the bitmap to a legend with e.g
```cs
var legend = FormsPlot.Plot.Legend();
var picture = legend.GetBitmap();
```
This call returns an error if no plot has a label. 
However, there is no way to actually know the number of items in the legend as this property is private. 
https://github.com/ScottPlot/ScottPlot/blob/a214b94102c107db3799197655b5255c464c7eda/src/ScottPlot/Renderable/Legend.cs#L166

One could think of two solutions :
- Either not return an error in case the legend is empty but return a `null` or an equivalent
- Or make the `LegendItems` list public so that one can check its length prior `GetLegendBitmap()`

Side note : Wouldn't it be relevant to switch from an `LegendItem[]` array to a `List<LegendItem>` as there is intrinsically variable amount of plots in a ScottPlot ?

**Comment by swharden** [comment]
> This call returns an error if no plot has a label.

Technically it returns a descriptive exception...

```
System.InvalidOperationException : The legend is empty (there are no visible plot objects with a label)
```

...but I agree this may be overkill! Returning a null `Bitmap` may make more sense than a hard exception.

> However, there is no way to actually know the number of items in the legend as this property is private.

Fair point! I'll expose `LegendItems` as you suggest

> Wouldn't it be relevant to switch from an LegendItem[] array to a List<LegendItem>

The reason I don't love the idea of `List` is because I don't want users to accidentally think they can get the list and `.Add()` to it on their own. Good line of thinking though!

In the case there are no items in the legend I'll set `LegendItems` to an empty array instead of null... and also add a `Count` field.

I'll make these changes in #1580 and check-in with you for your thoughts/input before I merge! 👍 🚀

**Comment by swharden** [comment]
> [when requesting the legend bitmap if there are no legend items] returning a null Bitmap may make more sense than a hard exception.

Oof, that isn't good because peoples' next line is often `bmp.Save()` which _then_ throws an exception

I could return a 1x1 transparent Bitmap if there are no plottables in the legend 🤷 

None of these options feel great

**Comment by swharden** [comment]
> I'll make these changes in #1580 and check-in with you for your thoughts/input before I merge! 👍 🚀

This is what I came up with. What do you think?

```cs
Bitmap bmp = plt.RenderLegend(); // never throws or returns null if legend is empty
bool has = plt.Legend().HasItems;
int cnt = plt.Legend().Count;
LegendItem[] = plt.Legend().GetItems();
```

**Comment by BambOoxX** [comment]
> Technically it returns a descriptive exception...
I'm not a big fan of putting everything into `Try` blocks so for me it is pretty much the same ! 

> ...but I agree this may be overkill! Returning a null `Bitmap` may make more sense than a hard exception.

Yes, If there is no label, the legend is empty, but that really should not return an exception.
 
> The reason I don't love the idea of `List` is because I don't want users to accidentally think they can get the list and `.Add()` to it on their own. Good line of thinking though!

Isn't it possible to make it `readonly` ? So that once it is created one cannot modify the array ?
 
> In the case there are no items in the legend I'll set `LegendItems` to an empty array instead of null... and also add a `Count` field.

That would be my line of thinking too 👍. Are you sure the `Count` field is required ? As the array already has a `Length` ?

**Comment by BambOoxX** [comment]
@swharden A side note to this specific property, I feel like the `GetDraggableUnderMouse` could be great to have as `public` too, don't you think ? For instance it is crucial if you want to be able to remove a `Vline` with some user action.

**Comment by swharden** [comment]
> Isn't it possible to make it readonly ? So that once it is created one cannot modify the array ?

I could return a `ImmutableList<LegendItem>` that would prevent the user from being able to add/clear it, but that's a bit of a weird data type and returning `LegendItem[]` achieves the same goal.

> I feel like the GetDraggableUnderMouse could be great to have as public too

This is an interesting point. I could move it from the control backend to the Plot module and make it public. I'll try this, and if it looks good I'll merge this in tonight!

**Comment by swharden** [comment]
> I feel like the GetDraggableUnderMouse could be great to have as public too

This now lives in the `Plot` module - thanks for the suggestion!

https://github.com/ScottPlot/ScottPlot/blob/6f56261a3837f6f925fdac7726c13a78e938eefe/src/ScottPlot/Plot/Plot.cs#L152-L179
