### ISSUE TITLE
Extend multi-axis support for getting pixels from coordinates

### ISSUE THREAD

**Issue by ChrisCC6** [ScottPlot/ScottPlot#1584]
## Features Suggestion

**Feature description:** Extend multi-axis support for getting pixels from coordinates

```cs
/// <summary>
/// Return the pixel for the given point in coordinate space
/// </summary>
/// <param name="x">horizontal coordinate</param>
/// <param name="y">vertical coordinate</param>
/// <param name="xAxisIndex">index of the horizontal axis to use</param>
/// <param name="yAxisIndex">index of the vertical axis to use</param>
/// <returns>pixel location</returns>
public (float xPixel, float yPixel) GetPixel(double x, double y, int xAxisIndex = 0, int yAxisIndex = 0)
{
    double xPixel = settings.GetXAxis(xAxisIndex).Dims.GetPixel(x);
    double yPixel = settings.GetYAxis(yAxisIndex).Dims.GetPixel(y);
    return (xPixel, yPixel);

}

/// <summary>
/// Return the horizontal pixel location given position in coordinate space
/// </summary>
/// <param name="x">horizontal coordinate</param>
/// <param name="xAxisIndex">index of the horizontal axis to use</param>
/// <returns>horizontal pixel position</returns>
public float GetPixelX(double x, int xAxisIndex = 0) => settings.GetXAxis(xAxisIndex).Dims.GetPixel(x);

/// <summary>
/// Return the vertical pixel location given position in coordinate space
/// </summary>
/// <param name="y">vertical coordinate</param>
/// <param name="yAxisIndex">index of the vertical axis to use</param>
/// <returns>vertical pixel position</returns>
public float GetPixelY(double y, int yAxisIndex = 0) => settings.GetYAxis(yAxisIndex).Dims.GetPixel(y);
```

**Comment by BambOoxX** [comment]
Haha, I actually did in my local branch of #1556 but I wasn't sure it was relevant !

**Comment by ChrisCC6** [comment]
Would be great having this. I need this to get the nearest plottable for a mouse-click, realizing a SelectedPlottable property.

P.S.: This library is a great kind of work. A little bit more mouse support for WPF would be great. I'm using it for a Data-Analysis App, allowing the user to add a generic number of plots in a scrollviewer. Sometimes it's hard creating some synced features between the single plots.
But all in all... Just my appreciation. Great work.

**Comment by BambOoxX** [comment]
@ChrisCC6 I just had had a crack at it. Have a look and check if you see something missing.

**Comment by ChrisCC6** [comment]
@BambOoxX 
Looks great!
BR Chris

**Comment by swharden** [comment]
@ChrisCC6, Thanks for the feature suggestion complete with working code!

@BambOoxX did a great job implementing it in #1587 - I'm merging it now and will publish a new package on NuGet this weekend

> This library is a great kind of work ... all in all... Just my appreciation. Great work.

Thank you for your encouraging words! I'm happy this library has become popular while remaining simple and light. I'm appreciative of the open-source community and the effort that lots of people have put into this project along the way, and I'm excited to see how this project continues to evolve! 🚀 It may even get decent WPF support one day 😉
