### ISSUE TITLE
Hello! How to enhance performance through multi-threading or enabling GPU（你好！ 怎么样通过多线程或者开启GPU增强性能）

### ISSUE THREAD

**Issue by JyenZhou** [ScottPlot/ScottPlot#1597]
![wx1](https://user-images.githubusercontent.com/37990159/150710122-33ba8e85-c427-4889-adcf-1245099d323c.png)
![wx2](https://user-images.githubusercontent.com/37990159/150710123-a5eb76ee-f368-4623-bfc8-b24eed6a047e.png)
![wx3](https://user-images.githubusercontent.com/37990159/150710124-5b0b334b-e084-4f01-8a61-8bc29fad2088.png)

Hello:
I used ScottPlot to create 10 polylines with 10,000 points on each line, and found that it was pretty jammed. It seems a little different from the official hype of a million points without pressure.
I checked the resource manager and found that the CPU usage ratio was not high, and the memory usage ratio was also very low. Meanwhile, THE GPU was not used. I searched about GPU and multi-threading on Github and did not find what I wanted. For example ScottPlot. DedicatedGPU. RunWithDedicatedGraphics (); Can't I use this code, and didn't search in the source code to (I am using WinForm version, the contributors are using WPF version https://github.com/ScottPlot/ScottPlot/pull/413). In addition, regarding multi-threading, my UI thread itself also does a lot of things, which should be part of the performance impact, I did not find the answer I want on Github. So I came to ask you, what should I do?

你好：
我使用ScottPlot创建了10条折线，每条线上面有10000个点，发现会很卡。  和官方宣传的百万个点没压力好像有点不大一样。
我查了下资源管理器，发现CPU占用比不高，内存占用比也很低，同时GPU是没有被使用的，我在github上搜索了下关于GPU和多线程没发现我想要的，是不是更新了，例如 ScottPlot.DedicatedGPU.RunWithDedicatedGraphics();这个代码我用不了，并且源码中也没搜索到 （我用的是WinForm版本，这个贡献者是不是用的是WPF  版本https://github.com/ScottPlot/ScottPlot/pull/413） 。另外关于多线程，我的UI线程本身也干了不少的事，这个应该也是影响性能的一部分，我在github更是没有找到我想要的答案。所以特来请教你们，我该怎么办？

**Comment by JyenZhou** [comment]
The first picture shows the resource usage in task Manager, which may not look obvious, so I repeat it here
第一张图片是任务管理器中的资源占用率，看着可能不明显，所以在这里重复声明下

**Comment by JyenZhou** [comment]
To correct the error：
 I used ScottPlot to create 7 polylines instead of the 10 I said above
纠正一下错误 ：
我使用ScottPlot创建了7条折线，而不是上面我说的10条折线

**Comment by swharden** [comment]
Hi @JyenZhou thank you for your question!

I'm writing on my phone so I'll be brief but I cam give a more thorough response tomorrow 

Scatter plots are not highly performing

Signal plots are

Consider using a signal plot and your problem may be resolved 👍

https://scottplot.net/faq/scatter-vs-signal/

https://scottplot.net/cookbook/4.1/category/quickstart/#signal-plot

**Comment by JyenZhou** [comment]
Hello @swharden, thank you so much for your Seconds back reply
This is actually a good idea, and I think it would be better if the Signal plots used multithreading and the GPU, as this method of improving performance should not conflict. 
I'm not in a hurry. I'm looking forward to your more comprehensive answer tomorrow。

**Comment by swharden** [comment]
Hi @JyenZhou,

I looked closer at your original screenshots and it looks like you have data which is not evenly-spaced on the horizontal axis. The standard "Signal Plot" expected a standard rate of data (e.g., a WAV file recorded at 44,100 Hz). However there is a special plot type called a "Signal Plot XY" that can execute highspeed renders of X/Y pairs _as long as the X values are in ascending order_.

https://scottplot.net/cookbook/4.1/category/plottable-signalxy/

```cs
double[] xs = { /* data */ };
double[] ys1 = { /* data */ };
double[] ys2 = { /* data */ };
double[] ys3 = { /* data */ };

wpfPlot1.Plot.AddSignalXY(xs, ys1);
wpfPlot1.Plot.AddSignalXY(xs, ys2);
wpfPlot1.Plot.AddSignalXY(xs, ys3);

wpfPlot1.Plot.Refresh();
```

I'm going to close this issue because I am confident this will solve your problem, but feel free to re-open it if you continue to have trouble. Good luck! 👍 🚀

**Comment by swharden** [comment]
Oh, one more thing

> better if the Signal plots used multithreading and the GPU

I agree with this! Unfortunately the existing rendering technology is not thread-safe. I'm working to replace this with a new library called `Microsoft.Maui.Graphics` which will be thread-safe and support OpenGL hardware acceleration. It's not ready yet, but hopefully soon #1036

**Comment by JyenZhou** [comment]
@simmdan 
I see, thank you very much for your help! In addition, I am looking forward to your updates. I will always pay attention to them.
