### ISSUE TITLE
WPF Live Data example from WPF Demo is not working 

### ISSUE THREAD

**Issue by alxkalinin** [ScottPlot/ScottPlot#1600]
## Bug Report

**Issue:** 

WPF Live Data plot from WPF Demo package is not working. The plot is not updating. But if you try to resize window, the plot update the content.

**Reproducing:**
1. Download "WPF Demo" from https://scottplot.net/demo/
2. Extract, run and select "Live Data" application.

Expected results:
Plot becomes updated in live

Actual results:
Plot is not updating. Only when you resize the window, plot update the content.

### System Details
* **ScottPlot Version:** 4.1.32
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** .NET 6.0

**Comment by alxkalinin** [comment]
Some addition. Same behavior is for couple of other examples: "ToggleVisibility", "WpfPlotConfig". Plot is updated only after the window resize.

**Comment by swharden** [comment]
Hi @alxkalinin thanks for sharing this concern. I made a quick video to demonstrate how these apps work on my computer. Are you experiencing something different? If so, what version of Windows are you running?

https://user-images.githubusercontent.com/4165489/150883371-30c6a723-a171-45f3-a57d-b56a55d2dcba.mp4

I'll close this issue for now, but if you can better demonstrate the issue or help me recreate it we can open it up again 👍

**Comment by alxkalinin** [comment]
Thank you for the feedback! It is strange, but on my PC it works differently. See video below.

I am a .NET Windows developer, so I can provide some kind of debug information in case you need more detailes.

https://user-images.githubusercontent.com/97022983/150930675-e2ced0d3-f601-4446-8e68-c1a716f54b60.mp4

**Comment by alxkalinin** [comment]
Finally, the issue is not in ScottPlott, but in .NET 6 environment on my PC. The problem is that the WritableBitmap not updating after updating the internal buffer.

The [WritableBitmap example ](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.imaging.writeablebitmap?view=windowsdesktop-6.0)from .NET documentation works exactly the same as a ScottPlott, not updating on my environment.

**Comment by alxkalinin** [comment]
Related to the https://github.com/dotnet/wpf/issues/3817

**Comment by alxkalinin** [comment]
Fixed by updating Intel Graphics driver up to the version "30.0.101.1121".
