### ISSUE TITLE
Docker: Text is rendered using unexpected font

### ISSUE THREAD

**Issue by winnieXY** [ScottPlot/ScottPlot#1608]
## Bug Report

**Issue:**
Creating a graph on different machines yield different graphs. The used fonts are different. 

on two different laptops the graph looks like this:
![grafik](https://user-images.githubusercontent.com/6831918/151201662-6331c9df-95de-4bbb-b997-99fff2fb17b7.png)

using a CI build on a docker instance (used image: mcr.microsoft.com/dotnet/framework/sdk:4.8) results in this image:
![grafik](https://user-images.githubusercontent.com/6831918/151201682-cea9d96d-103c-4206-b3fb-589abe7659d8.png)

As we need relyable and reproduceable images this is a no-go for us currently. Any ideas what is going wrong here?

**Reproducing:**
Use the test code below.

**Implementation:**
```cs
public static Plot PlotSqc(Component component)
        {
            Plot sqc = new Plot(plotwidth, plotheight);
            double i = 0;
            double[] xpoints = (from point in component.SelectedRange() select i++).ToArray();
            sqc.AddScatter(
                xpoints,
                component.SelectedRange().Select(x => x.Value).ToArray()
            );
            if (component.ShowPlotMean)
            {
                double[] meanval = (from piont in xpoints select component.Mean).ToArray();
                var sp = sqc.AddScatter(xpoints, meanval);
                sp.MarkerSize = 0;
                sp.LineStyle = LineStyle.Dash;

            }

            sqc.SetCulture(CultureInfo.InvariantCulture);
            sqc.Style(Style.Default);
            sqc.XAxis.Label(XLabel, Color.Black, 15, false, "calibri");
            sqc.XAxis.TickLabelStyle(Color.Black, "Calibri", 10);
            sqc.YAxis.Label(YLabel, Color.Black, 15, false, "calibri");
            sqc.YAxis.TickLabelStyle(Color.Black, "Calibri", 10);
            sqc.XAxis2.Label(component.Name, Color.Black, 15, true, "calibri");
            sqc.XAxis.ManualTickSpacing(Math.Round((i - 1) / 10, 0));
            sqc.SetAxisLimitsX(1,i-1);


            double resultSum = component.SelectedRange().Select(x => x.Value).Sum();
            double ymin = resultSum / component.SelectedRange().Count - component.StdDev * 3;
            double ymax = resultSum / component.SelectedRange().Count + component.StdDev * 3;
            sqc.SetAxisLimitsY(ymin,ymax); 

            return sqc;
        }
```
**Test Code:**
```cs
 [Test()]
        public void PlotSqcTest()
        {
            //Arrange
            Component component = new Component(1, "foo");
            List<DataPoint> points = new List<DataPoint>();

            double[] values = { 0.497, 0.998, 0.999, 1.002, 1.003, 1.001, 1.000, 0.996, 0.994, 1.003,
                0.997, 0.998, 0.999, 1.002, 1.003, 1.001, 1.000, 0.996, 0.994, 1.003,
                0.997, 0.999, 0.999, 1.002, 1.012, 1.002, 1.000, 0.996, 0.983, 2.003
            };
            points.AddRange((from value in values select new DataPoint(value)).ToList());
            component.DataPoints = points;
            component.StartPoint = 2;
            component.EndPoint = 29;
            component.Plot = Ploting.SQCPlot;

            //Act
            Plot plot = component.XyPlot;
            string path = plot.SaveFig("SGR_ComponentTests_sqctestcomp.jpg");

            //Assert
        }
```

### System Details
* **ScottPlot Version:** 4.1.27
* **Operating System:** Windows 10 / Docker image 
* **Application Type:** library
* **.NET Version:** NET Framework 4.8

**Comment by swharden** [comment]
Hi @winnieXY, thanks for reporting this. I don't have a quick answer but hopefully I can point you in the right direction! It would be great to have confirmed/working/quality rendering in Docker (especially known-working Docker images)

Let's start with a console app that is simpler to test.
```cs
var plt = new ScottPlot.Plot(300, 200);
plt.Title("Test Font", size: 36, fontName: "Comic Sans MS");
plt.SaveFig("testFont.png");
```

1) are you sure the font you're trying to render (Calibri) is available in that docker image? Not having the requested font on that system and automatically defaulting to a lousy font is my first guess as to what's going on here.

2) if you run the 3-line code above in the docker image does it still fail?

3) Related to #340, #1079, try installing the `System.Drawing.Common` NuGet package in your project and see if that fixes it

4) [InstalledFont.cs](https://github.com/ScottPlot/ScottPlot/blob/af561e3b7ed4989d4d236927f5aa8de907e79870/src/ScottPlot/Drawing/InstalledFont.cs) is what [Font.cs](https://github.com/ScottPlot/ScottPlot/blob/af561e3b7ed4989d4d236927f5aa8de907e79870/src/ScottPlot/Drawing/Font.cs) uses to try to retrieve font names that are available on the system. If the above don't work and you want to can edit the source to try to fix this I'd start here

**Comment by winnieXY** [comment]
This is a output from a powershell within that docker image:

1.) 
``` 
PS C:\> [System.Reflection.Assembly]::LoadWithPartialName("System.Drawing")

GAC    Version        Location
---    -------        --------
True   v4.0.30319     C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\Syste...


PS C:\> (New-Object System.Drawing.Text.InstalledFontCollection).Families

Name
----
Arial
Arial Black
Calibri
Calibri Light
Cambria
Cambria Math
Comic Sans MS
Consolas
Courier New
Ebrima
Gadugi
Georgia
Javanese Text
Leelawadee UI
Leelawadee UI Semilight
Lucida Console
Malgun Gothic
Microsoft Himalaya
Microsoft JhengHei
Microsoft JhengHei UI
Microsoft New Tai Lue
Microsoft PhagsPa
Microsoft Tai Le
Microsoft YaHei
Microsoft YaHei UI
Microsoft Yi Baiti
Mongolian Baiti
MV Boli
Myanmar Text
Nirmala UI
Nirmala UI Semilight
NSimSun
Segoe MDL2 Assets
Segoe Print
Segoe UI
Segoe UI Black
Segoe UI Emoji
Segoe UI Historic
Segoe UI Light
Segoe UI Semibold
Segoe UI Semilight
Segoe UI Symbol
SimSun
Times New Roman
Trebuchet MS
Verdana
Webdings
Wingdings
Yu Gothic Medium
Yu Gothic UI


PS C:\>
```

I've tryed Arial, Calibri and Comic Sans MS and played around with size and bold (true/false) but the actual used text font was always the same (only the size and the bold setting were respected). 

2.) I'll report back in a separate answer

3.) System.Drawing.Common is installed as nuget package in version 4.6.1 to the unit test project

4.) I'll have a look into it

**Comment by winnieXY** [comment]
2.) This is the image generated on the docker image (mcr.microsoft.com/dotnet/framework/sdk:4.8):
![grafik](https://user-images.githubusercontent.com/6831918/151314979-76d42257-5bfa-4e64-b858-96d33573149a.png)


This image is generated on my laptop:
![grafik](https://user-images.githubusercontent.com/6831918/151315097-38ee64cf-5b63-4d98-b691-a9c04cf149bc.png)


So yes - it is reproducable using this minimal example.

**Comment by winnieXY** [comment]
Well - I've a explanation - and scottplot is not the cause of this issue.

The autobuilder was using a recent version of the docker image - I had a outdated one on my laptop. In my image all fonts were present - in the recent ones is only lucida console installed as font. 

I've created a custom container using the neede fonts and now its working  as desired. 

Maybe it would be a good idea to bail out with an exception if the desired font is not available (if a font is explicitely requested). 
This would helped a lot to debug that issue actually. 

I would suggest the following behaviour:
 - if no font is specified pick the available one and continue without any error
 - if a font is specified which is not available throw an exception so that the user can handle that issue on its own. 

Silently ignore a setting and continue with a default is in my eyes the wrong behaviour in such a case.

**Comment by swharden** [comment]
> Well - I've a explanation - and scottplot is not the cause of this issue.

> I had a outdated [docker image] on my laptop

I'm glad you figured this one out!

> Maybe it would be a good idea to bail out with an exception if the desired font is not available (if a font is explicitly requested). This would helped a lot to debug that issue actually.

> Silently ignore a setting and continue with a default is in my eyes the wrong behaviour in such a case.

This is a difficult judgement call. I agree that crashing the application with a descriptive exception message would have helped you debug this issue... but on the other hand if someone makes an EXE they sell to clients, their app could hard-crash for something as simple as a client computer lacking a font. This is even more important considering the same code may be run on Linux/Windows/Mac systems, so a hard crash in production because of a font issue isn't my preferred behavior. It always falls back to something that can be displayed, all the way back to the system default font.

> if a font is specified which is not available throw an exception so that the user can handle that issue on its own.

I could add tools to the [`Font`](https://github.com/ScottPlot/ScottPlot/blob/master/src/ScottPlot/Drawing/Font.cs) class to make this at least easier to troubleshoot in the future. Something like 

```cs
bool IsInstalled(fontName) { /* */ }
```

or a special `Name` setter

```cs
public string RequiredFontName { set { /* set Name or throw if not installed */ } }
```

but respecting proper OO design probably it would be best if `Font` were not even constructible in an invalid state, so I'll keep thinking about some options here. I'll think about this soon as I start working on ScottPlot5 which uses a different rendering system #1036 

Thanks again for following-up with your solution!
