### ISSUE TITLE
Finance: Extend OHLC datatype to add volume (and create demo)

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [ScottPlot/ScottPlot#1611]
There seem to be many many breaking changes since the fantastic example of candlesticks and volume bars of this post. 

https://github.com/ScottPlot/ScottPlot/issues/181

Is there a updated version anywhere for 4.1.32. It says there is one in demos (in that thread) but I downloaded and compiled it and there aren't any that I can find?

**Comment by swharden** [comment]
Hi @SuperDaveOsbourne,

I don't think there is a demo that shows that, but hopefully the suggestions on this page can help you achieve your goal https://scottplot.net/faq/shared-axes/

Typically if a call is deprecated the message tells you the new method to use instead, so if you have old/working code it may be easy to get it working in the latest version

Hope it helps!
Scott

**Comment by swharden** [comment]
Hi @SuperDaveOsbourne, I made some progress here but it's not easy to add bars to the volume chart (yet?). See #1621 

![screenshot-finance-demo](https://user-images.githubusercontent.com/4165489/151732390-6097a7e2-c77a-44f1-8cd1-64ab94ec0507.gif)

A proper fix would probably be to create a new datatype OHLCV or something to better couple the volume with each OHLC point...

**Comment by swharden** [comment]
Hi @SuperDaveOsbourne I hacked in a way to extend a paired price/volume plots with growing data. This is pretty dirty but it works and is demonstrated in the WinForms demo. Hopefully this helps you work toward accomplishing your goal! 🚀 

![screenshot-finance-demo2](https://user-images.githubusercontent.com/4165489/151735627-94cd5351-408e-45b6-b479-1617fda6e7e1.gif)
