### ISSUE TITLE
Colorbar overlays YAxis2

### ISSUE THREAD

**Issue by ccopsey** [ScottPlot/ScottPlot#1637]
## Bug Report

**Issue:** When displaying both a colorbar and a YAxis2 the colorbar overlays the YAxis2

**Reproducing:** I don't think you need to do anything beyond adding both a colorbar and YAxis2 to your plot

In order to make space for the colorbar we need to add an minimum (constant) size to the YAxis2, but looking at the following it appears the colorbar is positioned using a hardcoded padding (10px) to the data area.  Ideally the colorbar would act like an extra axis and take part in the "measure" routine, both to assess its own width and the position of the YAxis2.

https://github.com/ScottPlot/ScottPlot/blob/2e60d96e9d04e21fc958a532dfd3dcaa639e2280/src/ScottPlot/Plottable/Colorbar.cs#L261

![image](https://user-images.githubusercontent.com/150505/152547296-77517129-9a31-4760-80b3-e0f38f2557f3.png)

### System Details
* **ScottPlot Version:** 4.1.32
* **Operating System:** Windows 10
* **Application Type:** Console
* **.NET Version:** .NET 6.0

**Comment by swharden** [comment]
Hi @ccopsey, thanks for reporting this, and narrowing-down the issue to the exact line of code! 🚀 

I'll fix this by storing that variable at the class level and making it public as `DataAreaPadding`. After I merge #1639 this code will produce the following output:

```cs
var plt = new ScottPlot.Plot(600, 400);

// add data to the primary Y axis
plt.AddSignal(ScottPlot.DataGen.Sin(51));

// add data to the secondary Y axis
var sig2 = plt.AddSignal(ScottPlot.DataGen.Cos(51));
sig2.YAxisIndex = 1;
plt.YAxis2.Ticks(true);

// add a colorbar and carefully define spacing
var cbar = plt.AddColorbar(space: 120);
cbar.DataAreaPadding = 40;

plt.SaveFig("demo.png")
```

![image](https://user-images.githubusercontent.com/4165489/152624852-531ebc93-c40f-4777-b0e0-1601a7e3ed60.png)
