### ISSUE TITLE
Pie chart doesn't have Axes?

### ISSUE THREAD

**Issue by tombohub** [ScottPlot/ScottPlot#1643]
## Bug Report

**Issue:** (Bug description goes here)
Pie chart and legend overlaps XAxis2.

In multiplot it's not consistent with other plots: 
![image](https://user-images.githubusercontent.com/3029412/152647863-e3f6de40-ca21-4939-ab98-16d96c9aeb6d.png)

Depending on plot size it's pie is covering the title: 
![image](https://user-images.githubusercontent.com/3029412/152647911-56581d02-d8b8-4d63-9618-4968c4b81ecd.png)
 

**Reproducing:** (What do others have to do to reproduce the bug?)

RoslynPad:
```cs
#r "nuget:ScottPlot/4.1.33"
using System.Drawing;
using ScottPlot;

var plt = new ScottPlot.Plot(300, 300);
plt.Title("Winners Losers Total");
double[] values = { 100, 50 };
string[] labels = { "Winners", "Losers" };
var pie = plt.AddPie(values);
pie.SliceLabels = labels;
pie.SliceFillColors = new Color[] { Color.ForestGreen, Color.Crimson };
var legend = plt.Legend();
legend.Location = Alignment.UpperRight;
plt.SaveFig("pie.png");
```

### System Details
* **ScottPlot Version:** 4.1.32
* **Operating System:** Windows10
* **Application Type:** console
* **.NET Version:** NET 6.0

**Comment by swharden** [comment]
Hi @tombohub, perhaps this produces output more consistent with expectations?

```cs
using System.Drawing;
using ScottPlot;

var plt = new ScottPlot.Plot(300, 300);

plt.Title("Winners Losers Total");
double[] values = { 100, 50 };
string[] labels = { "Winners", "Losers" };
Color[] colors = { Color.ForestGreen, Color.Crimson };

ScottPlot.Plottable.PiePlot pie = new (values, labels, colors);
plt.Add(pie);

var legend = plt.Legend();
legend.Location = Alignment.UpperRight;

// Install the ScottPlot.WinForms package and target net6.0-windows
new ScottPlot.FormsPlotViewer(plt).ShowDialog();
```

![image](https://user-images.githubusercontent.com/4165489/152667127-61b93285-de74-428c-a8e9-d518cc151795.png)

PS: Alt+PrtSc to screenshot windows with rounded corners in windows 11 shows colors through the corners 😝 

Notice that calling `AddPlottable()` performs some extra calls which satisfy the 99% of typical users intentions, but in your case this extra functionality seemed to be getting in the way:

https://github.com/ScottPlot/ScottPlot/blob/ff9377337487d085838bd3dc64bbb869fb419489/src/ScottPlot/Plot/Plot.Add.cs#L682-L698

Hope it helps!
Scott

**Comment by swharden** [comment]
To hide everything but the title label you can use the code above then manually hide the grid lines, axis border lines, and ticks. This will retain space for the title and prevent the circle from overlapping it.

```cs
plt.Grid(false);

plt.YAxis.Line(false);
plt.YAxis2.Line(false);
plt.XAxis.Line(false);
plt.XAxis2.Line(false);

plt.YAxis.Ticks(false);
plt.YAxis2.Ticks(false);
plt.XAxis.Ticks(false);
plt.XAxis2.Ticks(false);
```

**Comment by tombohub** [comment]
Hi @swharden , thanks for the help!


If I simply use `hideGridAndFrame = false` 

```cs
var pie = plt.AddPie(values, false);
```
I get the same as 
```cs
ScottPlot.Plottable.PiePlot pie = new(values, labels, colors);
plt.Add(pie);
```

The problem is still the legend overlaps the pie when save as image as you can see in photo: 
![image](https://user-images.githubusercontent.com/3029412/152704869-5c118fdb-865b-4bcc-add8-72a51b38dcf7.png)


In your WinForms example did you resize the window or is that default rendering?

**Comment by swharden** [comment]
> In your WinForms example did you resize the window or is that default rendering?

I was using the default rendering

> the legend overlaps the pie

You may do well to move the legend outside the plot. You can call `formsPlot1.Plot.GetLegendBitmap()` to get the legend image then perhaps display it in your window on a `Picturebox` or render it on your larger `Bitmap` or something.

Hope it helps!
Scott

**Comment by tombohub** [comment]
Thanks @swharden for reminding me we can render Legend separately.  I'll try to figure something out
