### ISSUE TITLE
Feature Request: show/hide line by clicking it in the legend

### ISSUE THREAD

**Issue by JyenZhou** [ScottPlot/ScottPlot#1648]
I want ScottPlot5 to be able to click on the diagram to hide and show the corresponding lines, instead of adding buttons outside the diagram, you can refer to this effect(我希望 ScottPlot5能够实现点击示意图能够隐藏和显示对应线条，而不是我需要在图表外部的地方添加按钮，你可以参考这个效果)https://www.highcharts.com.cn/demo/highcharts/line-basic   
![image](https://user-images.githubusercontent.com/37990159/152718387-839fad60-0c66-4e6a-a291-b938f50f3c06.png)
![image](https://user-images.githubusercontent.com/37990159/152718401-b7309cde-e2e8-420b-949a-2b479e5096d0.png)

**Comment by swharden** [comment]
Hi @JyenZhou,

It is possible to open the legend as a separate window and clicking items toggles whether they are shown or hidden. I do not think it is currently possible to click items in the legend to toggle their visibility _without_ popping the legend out as a separate window, but by reviewing the code in #1589 it may be possible for you to learn how to implement something similar in your app. 

![screenshot-detached-legend](https://user-images.githubusercontent.com/4165489/150699586-115b0d5c-c30e-42b6-8ecf-4310b8eae123.gif)

This section in particular may be useful for you to see how to show/hide a plot object based on what was clicked in the legend:

https://github.com/ScottPlot/ScottPlot/blob/ff9377337487d085838bd3dc64bbb869fb419489/src/controls/ScottPlot.WinForms/FormsPlotLegendViewer.cs#L55-L69

**Comment by ofirmagen** [comment]
@swharden Is this available for WPF as well?
