### ISSUE TITLE
Detachable legend doesn't work as expected in demo

### ISSUE THREAD

**Issue by grabul** [ScottPlot/ScottPlot#1651]
Demo built targeting net4.7.2

https://user-images.githubusercontent.com/80955161/153439080-b75a2b0e-0750-4497-ab5e-af5b07d8fa2d.MP4

**Comment by BambOoxX** [comment]
Hello ! What do you mean by *as expected* ?

**Comment by grabul** [comment]
Well I thought the legend in the canvas disappears if you detach it. Didn't know that you could have both. But if you have a context menu that says 'detach  legend' then as user I would assume that the legend on the canvas disapears... but anyway

**Comment by BambOoxX** [comment]
I started the developments for this functionality, and I agree with you on this point. If the menu states `Detach Legend` that should probably be the correct behavior. I planned to add some other interactive features to this detacheable legend (e.g. capability to highlight a specific plot, to change plot properties etc etc. I take note to change this behavior. Thanks for the suggestion.
If you have other ideas for improvements of this tool, though @swharden is a bit busy with v5 at the moment, I may be able to implement them.

**Comment by BambOoxX** [comment]
@grabul Just fixed the behavior in #1655
