### ISSUE TITLE
Plot: How to adjust order of plottables

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1656]
Is there a way to adjust the _order_ of plottables after they have already been added?

Question originally raised by @ricky5151 in #1654

**Comment by swharden** [comment]
A possible way to implement this would be to add a methods to the `Plot` module something like these:

```cs
public void Move(int currentPlottableIndex, int newPlottableIndex)
```

```cs
public void Move(Plottable plottable, int newPlottableIndex)
```

```cs
public void MoveToFront(Plottable plottable)
```

```cs
public void MoveToBack(Plottable plottable)
```

**Comment by BambOoxX** [comment]
@swharden Is it me or is this (pretty much) already implemented ? 

https://github.com/ScottPlot/ScottPlot/blob/ff9377337487d085838bd3dc64bbb869fb419489/src/ScottPlot/Plot/Plot.cs#L123-L144

**Comment by swharden** [comment]
> already implemented

Whoops! I guess my idea was so good, I already did it 🤣 

Thanks for pointing it out!

This is the solution to @ricky5151's question #1654
