### ISSUE TITLE
Controls: Add `DoubleClicked` event handler

### ISSUE THREAD

**Issue by bradmartin333** [ScottPlot/ScottPlot#1676]
**ScottPlot Version:** 4.1.29

**Operating System:** Win10

**Application Type:** WinForms

**Question:** I am allowing users to click points to remove them from the plot and they often enable the render time annotation and get confused. How can I override/unbind the DoubleClick event from the FormsPlot?

**Comment by bradmartin333** [comment]
Found it https://scottplot.net/faq/right-click-menu/

**Comment by swharden** [comment]
Actually, this is already possible like this 👍 

```cs
public Form1()
{
    InitializeComponent();
    formsPlot1.Configuration.DoubleClickBenchmark = false;
    formsPlot1.DoubleClick += FormsPlot1_DoubleClick;
}

private void FormsPlot1_DoubleClick(object sender, EventArgs e)
{
    System.Diagnostics.Debug.WriteLine("Custom double-click action");
}
```
