### ISSUE TITLE
How can I view plot with scrollBar?

### ISSUE THREAD

**Issue by xichaoqiang** [ScottPlot/ScottPlot#1680]
Hi @swharden , I want to implement the zoom function as shown below.
Scale horizontally or vertically. 

The three button in the Right and down side can control the figure scale.

But I can browse the whole picture through the scrollBar in the horizontal or vertical direction.
How to set it up in WPF?

![image](https://user-images.githubusercontent.com/30900789/154598550-b42c8759-65b7-421a-90e5-51714e47bddb.png)

**Comment by swharden** [comment]
Hi [xichaoqiang](https://github.com/xichaoqiang), I may be misunderstanding your goal, but if your goal is to have a very large graph that you can navigate around using the scroll bars this option may work:

Create a very large plot, save it as a PNG file, then display the PNG file in your WPF app as an image inside a `ScrollViewer`. You do not need to use the `ScottPlot.WPF` package or `WpfPlot` control to achieve this solution. Plots will be a static image and not be mouse-interactive, but you can navigate them using the scroll bars.

Does this help you achieve your goal?

**Comment by xichaoqiang** [comment]
In the below video, I control the figure scale with these button.
I think this is very easy to use.

https://user-images.githubusercontent.com/30900789/154603395-5f21def9-abac-4de5-89c9-8e51d35dd4bc.mp4

**Comment by swharden** [comment]
> How can I connect the zoom function with six buttons based on existed functions in the library?
> Like vertical and horizontal directional zoom In/Out/Reset?

```cs
formsPlot1.Plot.AxisZoom(xFrac: 1.5); // zoom in X
formsPlot1.Plot.AxisZoom(xFrac: 0.5); // zoom out X

formsPlot1.Plot.AxisZoom(yFrac: 1.5); // zoom in Y
formsPlot1.Plot.AxisZoom(yFrac: 0.5); // zoom out Y

formsPlot1.Plot.AxisAuto(); // reset zoom to fit the data
```

**Comment by swharden** [comment]
You may also find `AxisPan()` useful 👍

**Comment by xichaoqiang** [comment]
@swharden Thanks functions of AxisZoom 、AxisAutoX and AxisAutoY are very useful.

So I try to link scrollbar with AxisPan().

![动画](https://user-images.githubusercontent.com/30900789/154779836-2720b0bd-09b1-4fd5-9d3e-318ca27e830c.gif)
