### ISSUE TITLE
Finance. More effective data filling.

### ISSUE THREAD

**Issue by kv-gits** [ScottPlot/ScottPlot#1700]
For now we should create OHLC list or array to plot it. But some very often use-cases are not effective with this approach. 

Example.
I have a large amount of tohlcv data placed inside Microsoft.Data.Analysis Dataframe as double columns. I need to copy all of them in ScottPlot.OHLC constructor and create new array with the same capacity. Seems like a huge memory ineffectiveness. May be there is good idea to add additional constructor for candle chart, providing not OHLC array but 4 double arrays? Or some other type of lazy filling data without copying it?

**Comment by swharden** [comment]
Hi @kv-gits, your observations are correct! For large datasets it may not be convenient or performant to create a large number of `OHLC` objects just to pass them into a `FinancePlot`. Note that this this is only required once though, and you can always `Add()` a bar after it's initialized in a way which maintains performance, but your original problem is well stated.

## Create a custom plot type

>  May be there is ... some other type of lazy filling data without copying it?

One could omit the need to use the `OHLC` data type entirely and avoid all copying by creating a new plot type called something like `CandlePlotUsingArrays` that works on arrays that are passed into it. It could work like this:
```cs
ScottPlot.Plot plt= new(600, 400);
CandlePlotUsingArrays myCandles = new(opens, highs, lows, closings);
plt.Add(myCandles);
```

Creating a custom plot type is as easy as copying the code from an existing plot type and editing it to accomodate your special data format. The `FinancePlot` type is a good starting place, and probably only needs a few lines of modification to achieve this. Much of this code may be unnecessary for your application can be deleted too:

https://github.com/ScottPlot/ScottPlot/blob/9d0b93678f065e63ea91b9f01d44baf6494f6cbe/src/ScottPlot/Plottable/FinancePlot.cs#L1-L309

Hope it helps!
