### ISSUE TITLE
Wheel zoom is not available on win7

### ISSUE THREAD

**Issue by mYcheng-95** [ScottPlot/ScottPlot#1706]
## Bug Report

**Issue:** (Wheel zoom is not available on win7)

In the same application on win10 (ScottPlot-Demo-WinForms 1.4.33), the wheel zoom function is normal, but it is not available under win7. Other zooming methods are available in both versions.

### System Details
* **ScottPlot Version:** 4.1.33?
* **Operating System:** ( Windows 7.)
* **Application Type:** (WinForms)
* **.NET Version:** (NET Framework 4.8)

**Comment by swharden** [comment]
Thanks for reporting this @mYcheng-95!

It looks like this issue has popped-up before... #354

The fix is to edit FormsPlot's source to add:

```cs
pictureBox1.MouseEnter += (s, e) => pictureBox1.Focus();
```

in the initializer after this line:

https://github.com/ScottPlot/ScottPlot/blob/b9e33843081f50ae1897a2268d46ee112ba144cb/src/controls/ScottPlot.WinForms/FormsPlot.cs#L111

I don't have a Win7 computer I can test this on. Are you able to try making this change yourself and seeing if the mouse wheel acts as expected?

**Comment by mYcheng-95** [comment]
I tried this code.
```cs
 this.formsPlot1.MouseHover += (s, e) => this.formsPlot1.Focus();
```
and,the code is as follows:
```cs
this.formsPlot1.MouseWheel += new System.Windows.Forms.MouseEventHandler(this.formsPlot_MouseWheel);
this.formsPlot1.MouseHover += (s, e) => this.formsPlot1.Focus();
 private void formsPlot_MouseWheel(object sender, MouseEventArgs e)
        {
            if (Environment.OSVersion.Version.Major <= 7)
            {
                FormsPlot plot = sender as FormsPlot;

                double xFrac = (e.Delta > 0) ? 1.15 : 0.85;
                double yFrac = (e.Delta > 0) ? 1.15 : 0.85;
                double zoomToX = plot.Plot.GetCoordinateX(e.Location.X);
                double zoomToY = plot.Plot.GetCoordinateY(e.Location.Y);
                plot.Plot.AxisZoom(xFrac, yFrac, zoomToX, zoomToY);
                plot.Render();
            }
        }
```
But,The effect is not very satisfactory to me. First of all, I need to click on the control to get the focus for the event to take effect. When I move the mouse out of the area where the control is located, the wheel event still takes effect. I think I should give up win7 and hug win10.

**Comment by mYcheng-95** [comment]
Solve the problem at the root
![0BB77EAA](https://user-images.githubusercontent.com/30651076/155280935-a9997675-5917-4ae6-99d6-11d7b0360711.png)
