### ISSUE TITLE
Plot not refreshing on machine

### ISSUE THREAD

**Issue by CaptainBob81** [ScottPlot/ScottPlot#1726]
**Issue:** 

Hello! 

I have a very weird issue with the Scottplot package.
I have written a WPF program that works on my computer and several others. 
But the computer it is programmed for does not refresh the scottplot plot until you resize the program window itself.
I call the Refresh() method at all places where new information is added to the plot. 
I have also tried to call the Render() method but to no avail.
I can't drag the plot or perform any visual altering task and have it update in realtime. If I clear the plot I have to resize the program window in order to see the changes. It is enouch to just make the window a single pixel larger och smaller. 

**Reproducing:** 

I'm unsure how to reproduce this issue as it works on several other computers. It is just the one computer running the program. I have built it as release and publish it. I have tried to use a standalone version with hte .NET package included and also just the executables in a framework dependent version. In that case i have used the .NET 6.0.3 Desktop Runtime.
The program has been developed using .NET 6.0 and I have also tried to compile it using .NET 5.0 but with same result.

Im hoping that someone else regonizes this... I have no idea what could be causing this...

Sorry for the bad english.

Awesome software this scottplot.

### System Details
* **ScottPlot Version:** 4.1.33
* **Operating System:** Windows 10 Pro
* **Application Type:** WPF
* **.NET Version:** .NET Runtime 6.0.3 (Computer running the faulty version) .NET 6.0 (Developing computer) also tried .NET 5

**Comment by swharden** [comment]
Hi @CaptainBob81,

I recall somebody mentioning a similar issue before. It was related to a graphics driver problem affecting DirectX (WPF uses DirectX to display the window). The solution was to update the graphics driver.

https://github.com/ScottPlot/ScottPlot/issues/1600

Hope it helps!

**Comment by CaptainBob81** [comment]
UPDATE: 

Apparently it was the graphics drivers that needed to be updated on the new machine. The computer uses the Intel UHD 750 integrated card.

**Comment by CaptainBob81** [comment]
Haha holy cow I just clicked send! =) Thank you very much! Again awesome sotfware you have created!
