### ISSUE TITLE
Removing a ColorBar doesn't reset the YAxis PixelSizeMinimum

### ISSUE THREAD

**Issue by ccopsey** [ScottPlot/ScottPlot#1732]
## Bug Report

_YAxis can refer to YAxis or YAxis2 where relevent..._

**Issue:** Adding a ColorBar to a plot increases the YAxis `PixelMinimumSize`.  Subsequently removing the ColorBar doesn't reduce this value and consequently leaves a large margin between the YAxis and the edge of the bitmap.

The convenience method `Plot.AddColorbar()` calls `YAxis.SetSizeLimit(min: space)` but there is no equivalent method of resetting this value.  The workaround is to manually call `YAxis.SetSizeLimit(min: 5)` but this is fragile.  A public method to `ResetSizeLimit()` would be a good start.

**Reproducing:**

```cs
[Test]
public void Test()
{
    var plt = new ScottPlot.Plot();
    var bmp1 = TestTools.GetLowQualityBitmap(plt);
    var cb = plt.AddColorbar();
    plt.Remove(cb);
    var bmp2 = TestTools.GetLowQualityBitmap(plt);
    var before = new MeanPixel(bmp1);
    var after = new MeanPixel(bmp2);
    Assert.That(after.IsEqualTo(before));
}
```

### System Details
* **ScottPlot Version:** SHA 3581f8c5aaad0b0c46c4dcc87e15013ea71abb59
* **Operating System:** Windows 10
* **Application Type:** console, WPF
* **.NET Version:** .NET 5.0/6.0

**Comment by Xerxes004** [comment]
Introducing a `ResetSizeLimit` method would probably go against the [push towards statelessness](https://github.com/ScottPlot/ScottPlot/blob/3581f8c5aaad0b0c46c4dcc87e15013ea71abb59/dev/roadmap.md) inside the guts of the `Axis` class. What happens if a user creates a `Colorbar` then calls `ResetSizeLimit` with new values? `Axis` would have to keep track of all the previous size limits internally.

I think your workaround is a decent solution. It's a better idea to keep track of your own manipulations of the plot so that you can undo them later rather than having the plot do that for you. 

If I had to rewrite some of this `Axis` logic, I would probably add some notion of "please reserve XX pixels for me at edge YY of the plot" to the `IRenderable` interface. This would allow users to create their own renderables which could be displayed past the default edges of the plot, and also allow the render code to figure out exactly how big the canvas needs to be to fit everything.

**Comment by swharden** [comment]
Hi @ccopsey, thanks for raising this issue! 

Re-stating the concern, adding a colorbar adjusts the layout to make room for it but removing a colorbar does not put it back...

```cs
var plt = new ScottPlot.Plot(400, 300);
plt.Style(figureBackground: System.Drawing.ColorTranslator.FromHtml("#dadada"));

var cb = plt.AddColorbar();
plt.SaveFig("colorbar-added.png");

plt.Remove(cb);
plt.SaveFig("colorbar-added-then-removed.png");
```

colorbar | colorbar removed
---|---
![image](https://user-images.githubusercontent.com/4165489/159121228-2e8c329b-3cb3-4912-8cbf-e91f70d89297.png)|![image](https://user-images.githubusercontent.com/4165489/159121232-f00c4e2a-f1da-49ce-9433-d6a2e15d9cb4.png)

The core problem is that `AddColorbar()` assumes that the majority of people want to adjust the layout of their plot to accomodate the colorbar, but in this case the adjustment is made invisibly and without an automated way to adjust it back if the colorbar is removed.

https://github.com/ScottPlot/ScottPlot/blob/3581f8c5aaad0b0c46c4dcc87e15013ea71abb59/src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs#L238-L262

## Current Solution: Reset the Axis size limit manually

The default axis padding on the right is 5 pixels, so resetting this manually after removing the colorbar should do the trick

```cs
var plt = new ScottPlot.Plot(400, 300);
plt.Style(figureBackground: System.Drawing.ColorTranslator.FromHtml("#dadada"));

var cb = plt.AddColorbar();
plt.SaveFig("colorbar-added.png");

plt.Remove(cb);
plt.YAxis2.SetSizeLimit(min: 5);
plt.SaveFig("colorbar-added-then-removed.png");
```

colorbar | colorbar removed
---|---
![image](https://user-images.githubusercontent.com/4165489/159121783-f96d52c3-a231-4403-b3ae-8d484694bcdc.png)|![image](https://user-images.githubusercontent.com/4165489/159121784-0d168f03-3602-43e0-a51d-395c39b5630f.png)

## Proposed Solution: Methods for Resetting to Default Layout

I think methods like this would be helpful to add to the library. I will do this today. Thanks for the suggestion!

```cs
plt.YAxis2.ResetLayout(); // reset the spacing to the defaults
plt.ResetLayout(); // reset the spacing to the defaults for all axes
```

@Xerxes004 raised some good points about the preference toward stateliness (or at least trying to minimize the accumulation of state), and the added complexity that comes with trying to _automatically_ detecting changes and reacting to them. 

> If I had to rewrite some of this Axis logic, I would probably add some notion of "please reserve XX pixels for me at edge YY of the plot" to the IRenderable interface. This would allow users to create their own renderables which could be displayed past the default edges of the plot, and also allow the render code to figure out exactly how big the canvas needs to be to fit everything.

This is a good point too! ScottPlot5 will be an opportunity to redesign the layout system, and features like this will definitely make these types of tasks much more manageable in the future. I definitely want to improve the relationship between renderable/plottable objects and the ability of the layout to adjust to accomodate them.
* #1647 
* #1036
