### ISSUE TITLE
Avaolnia. Making crosshair label on right is buggy.

### ISSUE THREAD

**Issue by kv-gits** [ScottPlot/ScottPlot#1743]
## Bug Report

Making mouse tracking crosshair label on right is buggy. Horizontal line is on the zero and doesnt updated. Vertical line is ok.

```cs
avaPlot1 = this.Find<AvaPlot>("StatPlot");
Crosshair = avaPlot1.Plot.AddCrosshair(0, 0);
Crosshair.HorizontalLine.PositionLabelOppositeAxis = true;
Crosshair.YAxisIndex = 1;
Crosshair.XAxisIndex = 0;
fplot = new FinanceOptPlot(dm.klines.ToArray(), p);
fplot.YAxisIndex = 1;
avaPlot1.Plot.Add(fplot);
avaPlot1.Plot.XAxis.DateTimeFormat(true);
avaPlot1.Plot.YAxis.Ticks(false);
avaPlot1.Plot.YAxis2.Ticks(true);
```

```cs
private void OnMouseMove(object sender, PointerEventArgs e)
{
    int pixelX = (int)e.GetPosition(avaPlot1).X;
    int pixelY = (int)e.GetPosition(avaPlot1).Y;
    //System.Diagnostics.Debug.Print("Pixel x, y {0} {1}", pixelX, pixelY);
    (double coordinateX, double coordinateY) = avaPlot1.GetMouseCoordinates();

    Crosshair.X = coordinateX;
    Crosshair.Y = coordinateY;

    avaPlot1.Refresh();
    //Backend.MouseMove(GetInputState(e));
}
```

### System Details
* **ScottPlot.Avalonia Version:** 4.1.35?
* **Operating System:** (Windows 10)
* **Application Type:** (Avalonia, etc)
* **.NET Version:** (net 6.0)

**Comment by swharden** [comment]
> Horizontal line is on the zero and doesn't updated

It looks like your issues relates to the fact you are adding data to non-standard Y axis.

It seems the WinForms control's `GetMouseCoordinates()` has arguments for non-standard axes but the other controls (including Avalonia) do not. I'll update all these and pusblish a release tonight 👍 

https://github.com/ScottPlot/ScottPlot/blob/19d9e7e53538fbe31ab681dad68ce1548cf56630/src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs#L120

https://github.com/ScottPlot/ScottPlot/blob/19d9e7e53538fbe31ab681dad68ce1548cf56630/src/ScottPlot4/ScottPlot.WPF/WpfPlot.xaml.cs#L125

https://github.com/ScottPlot/ScottPlot/blob/19d9e7e53538fbe31ab681dad68ce1548cf56630/src/ScottPlot4/ScottPlot.Eto/PlotView.cs#L89

https://github.com/ScottPlot/ScottPlot/blob/19d9e7e53538fbe31ab681dad68ce1548cf56630/src/ScottPlot4/ScottPlot.Avalonia/AvaPlot.axaml.cs#L98
