### ISSUE TITLE
How to configure anti-aliasing for controls outside the ScottPlot

### ISSUE THREAD

**Issue by ZhuYajunFly** [ScottPlot/ScottPlot#1746]
ScottPlot Version:4.1.36
System : Win10   Winform .Net 4.8

Design:
![image](https://user-images.githubusercontent.com/52872318/160228161-5b84eaef-2a73-4e2f-ab7e-79adefd4cbf6.png)
![image](https://user-images.githubusercontent.com/52872318/160228268-2f954853-e50f-4208-8ce1-6290ae619cff.png)

Run:
![image](https://user-images.githubusercontent.com/52872318/160228195-47396d01-7f34-4cae-acc7-7fb083068b3e.png)
![image](https://user-images.githubusercontent.com/52872318/160228257-a5554bbb-44eb-44ae-adc9-697cbb018049.png)

You can find buttons text render changed，How can I fix it?Thank you Very much.

**Comment by swharden** [comment]
Hi @ZhuYajunFly,

It looks like the buttons are being drawn with anti-aliasing on and off, making them appear different

https://scottplot.net/faq/anti-aliasing/

It surprises me that just adding a ScottPlot in a window could change the appearance of controls though. If you want to experiment with this you can try forcing anti-aliasing to always be on with:

```cs
formsPlot1.Configuration.QualityMode = QualityMode.High
```

**Comment by ZhuYajunFly** [comment]
> Hi @ZhuYajunFly,
> 
> It looks like the buttons are being drawn with anti-aliasing on and off, making them appear different
> 
> https://scottplot.net/faq/anti-aliasing/
> 
> It surprises me that just adding a ScottPlot in a window could change the appearance of controls though. If you want to experiment with this you can try forcing anti-aliasing to always be on with:
> 
> ```cs
> formsPlot1.Configuration.QualityMode = QualityMode.High
> ```
I can write:
formsPlot1.Configuration.Quality = QualityMode.High;
Your code is fault;
formsPlot1.Configuration.QualityMode = QualityMode.High
![image](https://user-images.githubusercontent.com/52872318/160246846-abc84638-8424-4dd9-b7a6-acff6b777378.png)

formsPlot1.Configuration.Quality = QualityMode.High;,But it still not work.

**Comment by ZhuYajunFly** [comment]
> Hi @ZhuYajunFly,
> 
> It looks like the buttons are being drawn with anti-aliasing on and off, making them appear different
> 
> https://scottplot.net/faq/anti-aliasing/
> 
> It surprises me that just adding a ScottPlot in a window could change the appearance of controls though. If you want to experiment with this you can try forcing anti-aliasing to always be on with:
> 
> ```cs
> formsPlot1.Configuration.QualityMode = QualityMode.High
> ```

I used a UI libary.
![image](https://user-images.githubusercontent.com/52872318/160248026-1d390d24-2aed-43af-9aef-acad68db610e.png)
Only Both use SunnyUI and scottplot, the SunnyUI was effected.

**Comment by swharden** [comment]
Thank you for the additional information!

> Only Both use SunnyUI and scottplot, the SunnyUI was affected.

This sounds like a problem inside SunnyUI 

If you post an issue on https://gitee.com/yhuse/SunnyUI you may get better feedback

Good luck! 👍 🚀
