### ISSUE TITLE
Improve .NET Interactive notebook / Jupyter support

### ISSUE THREAD

**Issue by Regenhardt** [ScottPlot/ScottPlot#1772]
**ScottPlot Version:** Latest NuGet, 4.1.40

**Operating System:** Windows 10

**Application Type:** .NET Interactive Notebook

**Question:** How to display a plot in the interactive notebook?

In python's matplotlib you basically go:

```
fig.scatter(/*put data here*/9
```  
And the return of that displays as a plot.

I basically just copied an example from your page
```cs
// Install library from nuget
#r "nuget:ScottPlot"
// Get data
double[] dataX = new double[] { 1, 2, 3, 4, 5 };
double[] dataY = new double[] { 1, 4, 9, 16, 25 };
// make plot
var plt = new ScottPlot.Plot(400, 300);
// Output of this is just shown as a table
plt.AddScatter(dataX, dataY)
```  
This is the output:

![grafik](https://user-images.githubusercontent.com/10476293/162446125-f0dfd5a6-1443-4e80-8518-ec0460a74a2f.png)

**Comment by StendProg** [comment]
Hi @Regenhardt,

This code works for me:
```c
using System;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;
using Microsoft.DotNet.Interactive.Formatting;

// Install library from nuget
#r "nuget:ScottPlot"
// Get data
double[] dataX = new double[] { 1, 2, 3, 4, 5 };
double[] dataY = new double[] { 1, 4, 9, 16, 25 };
// make plot
var plt = new ScottPlot.Plot(400, 300);
// Output of this is just shown as a table
plt.AddScatter(dataX, dataY);

var bmp = plt.GetBitmap();
var memStream = new MemoryStream();
bmp.Save(memStream, ImageFormat.Png);
string base64str = Convert.ToBase64String(memStream.ToArray());
display(PocketViewTags.img[src: "data:image/png;base64," + base64str]);
```

Looks very bulky. The code for wrapping the bitmap into a Base 64 string could be added to the ScottPlot library helper method to simplify the task. If it is of course in demand.

**Comment by swharden** [comment]
Hi @StendProg, it's great to hear from you! Thanks so much for this information. I haven't used .NET netbooks before, but enjoyed learning about them this morning.

I added a new method to simplify inclusion of ScottPlot figures in Jupyter / .NET Interactive notebooks:

```cs
// Install the ScottPlot NuGet package
#r "nuget:ScottPlot"

// Plot some data
double[] dataX = new double[] { 1, 2, 3, 4, 5 };
double[] dataY = new double[] { 1, 4, 9, 16, 25 };
var plt = new ScottPlot.Plot(400, 300);
plt.AddScatter(dataX, dataY);

// Display the result as a HTML image
display(HTML(plt.GetImageHTML()));
```

There may be a more elegant way to do that final line, but I haven't found it yet.

I started a new quickstart page to make this easier to discover in the future:
https://scottplot.net/quickstart/notebook/

**Comment by Regenhardt** [comment]
This happened amazingly fast, thanks a lot!

**Comment by swharden** [comment]
Following-up, you can register a display type so it's even easier

```cs
#r "nuget:ScottPlot"
using Microsoft.DotNet.Interactive.Formatting;
Formatter.Register(typeof(ScottPlot.Plot), (plt, writer) => writer.Write(((ScottPlot.Plot)plt).GetImageHTML()), HtmlFormatter.MimeType);
```

![image](https://user-images.githubusercontent.com/4165489/166233822-c911a851-d1a6-486b-a72d-a11b619d14f4.png)

**Comment by neilyoung2008** [comment]
Could we add this feather  for  scottplot 5.x ？

**Comment by swharden** [comment]
> @swharden Could we add this feature for scottplot 5.x ？

I'll prioritize this and get it published in the next release 👍 

* #2385
