### ISSUE TITLE
How to display real-time data with different densities

### ISSUE THREAD

**Issue by chrismx000** [ScottPlot/ScottPlot#1782]
The data was created by  machine. Xs has different densities .Otherwise,i also need the nearest function.What should I do ？

**Comment by swharden** [comment]
Can you show an example of the type of plot you are trying to create?

These examples may help you achieve your goal:
* https://scottplot.net/cookbook/4.1/category/plottable-signal-plot/
* https://scottplot.net/cookbook/4.1/category/plottable-signal-plot/#display-data-density
* https://scottplot.net/cookbook/4.1/category/plottable-signalxy/
* https://scottplot.net/cookbook/4.1/category/plottable-signalxy/#different-densities

**Comment by chrismx000** [comment]
hello swharden ,I'm writing a data acquisition and analysis system.In my program I have a progress to collect the data from mang devices at intervals .But not strictly in accordance with the time.The data is displayed in real time.
Last night,I tried to use signalplotxy in LiveDataGrowing,but it throw an Exception "Xs must only contain ascending values";
Now I found the way to achieving my goal by using ScatterPlot.But I think it is not the best way ,Is it?

**Comment by swharden** [comment]
Hi @chrismx000, it sounds like you were almost there!

> it throw an Exception "Xs must only contain ascending values"

Yes, `SignalXY` requires that X values are always ascending (1, 2, 3, 4). They cannot descend (1, 2, 3, 0).

When you fix this I believe your issue will be resolved
