### ISSUE TITLE
How to improve performance of plots that update automatically

### ISSUE THREAD

**Issue by Kirill2Kirill** [ScottPlot/ScottPlot#1783]
I have a WinForms app, and Im using Scatter plot in it.
I often (every sec) receiving a lot of data updates by the sockets, which works in separated threads.
There is a 3-4 chart (scatter plots) on formsPlot at once.
This data update my models, and immediately transforms it in double-coordinates with this code (as an example):

```cs
public class Model
{
	public ScottPlotCoordinates Coordinates { get; set; }
        public decimal ValueA { get; set; }

	public void Update(*someclass* newInfo)
        {
        	ValueA = newInfo.ValueA;
        	Coordinates.Add(value: newInfo.ValueA, date: DateTime.Now);    
        }
}

public class ScottPlotCoordinates
{
        private List<double> _x { get; set; }
        private List<double> _y { get; set; }

	public (double[] x, double[] y) Coordinates
        {
        	get
        	{
                	if (_x.Count > 0)
                    		return (x: _x.ToArray(), y: _y.ToArray());
	
                		return (x: new double[1] { 0 }, y: new double[1] { 0 });
            	}
        }

	public void Add(decimal value, DateTime date)
        {
            	var oaDate = date.ToOADate();
            	var doubleValue = decimal.ToDouble(value);

            	_y.Add(doubleValue);
            	_x.Add(oaDate);
        }
}
```

Then with async methods its update the plot by the timer (every 3 sec) with this methods:
```cs
public async Task UpdateAsync()
{	
	await Task.Run(() =>
        {
                (var x, var y) = model.Coordinates;

	        MyScatterPlot.Update(x, y);

	        Render();

	}).ConfigureAwait(false);
}

public void Render()
{
	_formsPlot.Render(lowQuality: false, skipIfCurrentlyRendering: true);
}
```

And everything works fine, while arrays is not so big. After some length i see that the chart is slowing down.
Even when only one scatter plot is visible.
How can I fix it?
I think about using Signal plot but it's not resolving the main problem with slow redrawing.

P.S. i see slowing down in case of zooming in/out

P.P.S. mb some formsPlot.Configuration?

**Comment by Kirill2Kirill** [comment]
Its become much better with this: `_formsPlot.Configuration.UseRenderQueue = true;`

**Comment by swharden** [comment]
Hi @Kirill2Kirill,

You may find some tips on this page https://scottplot.net/faq/live-data/

For WinForms I recommend using a `Timer` to call `Render()` periodically. It's okay if your data updates in a different thread, but for WinForms it's ideal to trigger GUI updates from the GUI thread which `Timer` achieves.

It sounds like your plot may be slowing down as the number of data points increases. If this is the case, switching to a Signal plot will solve this issue.

Overall it sounds like may have solved your issue using the render queue, which is another option!

Hope it helps
Scott

**Comment by swharden** [comment]
I took a closer look at your code and realized that on every render you are creating a new `double[]` and calling `update()` with the new arrays

I also recommend not doing this for performance reasons

Instead use a single very large array and set the signal plot's `MinRenderIndex` and `MaxRenderIndex` to only display the parts of the array populated with real data. This will reduce a lot of your boilerplate code and be very fast.

That technique is demonstrated here:
https://scottplot.net/faq/live-data/#growing-data-with-partial-array-rendering
