### ISSUE TITLE
ScatterPlotDraggable restricts Y coordinates based on X values

### ISSUE THREAD

**Issue by m4se** [ScottPlot/ScottPlot#1795]

**Comment by StendProg** [comment]
Hi @m4se,

You described the problem and its solution, why not issue it as a pull request? You will gain valuable experience. In any case, thanks for the help.

**Comment by m4se** [comment]
I am not sure what valuable experience there would to be had from issuing the pull request.  As you can tell from my profile, I am very active on github.

**Comment by m4se** [comment]
I'll do a pull request when I have time available so I can get some of this valuable experience.

**Comment by m4se** [comment]
I figured I'd do my due diligence in looking into a bug that I found before I submitted it.  I did not expect my experience and time commitments to be questioned.

**Comment by swharden** [comment]
Hi @m4se, I see from your original comment that you located an active bug:

https://github.com/ScottPlot/ScottPlot/blob/065383a3b6182e35edbe39c2606528bd147bb013/src/ScottPlot4/ScottPlot/Plottable/ScatterPlotDraggable.cs#L71-L74

Those if statements are always checking `coordinateX` when really the last two should check `coordinateY`.

---

Although it is quick and easy for me to make small changes like this one, we have many first time contributors here, and in an effort to encourage the open-source community we often take extra time and effort to help walk people through making their first pull request. Submitting a PR to a public repository can be intimidating for newcomers, but helping someone go through the steps can give them the confidence to do it on their own in the future, making a positive and lasting impact for code and documentation across numerous projects for years to come.

I believe @StendProg had good intentions with their initial comment, and the suggestion to create a PR and note that the experience is valuable was coming from this perspective. Many of us are not native English speakers, and correctly encoding and decoding tone from text comments can be a challenge. My guess is that there was a mismatch between the message that was _intended_ and the message that was _received_ from the initial comment. I have found that everyone in our community has been super nice and helpful, and I'm happy to be a part of it 👍🚀
