### ISSUE TITLE
The type name InterpolateXY does not exist in the type Cubic

### ISSUE THREAD

**Issue by Damian666** [ScottPlot/ScottPlot#1796]
## Bug Report

**Issue:** (cant use interpolateXY on latest scottplot winforms)

**Reproducing:** (What do others have to do to reproduce the bug?)
see the screenshot
```cs
//Interpolate the whole damn thing
var nsi = new ScottPlot.Statistics.Interpolation.Cubic.InterpolateXY(xs, ys, 20);
```

### System Details
* **ScottPlot Version:** 4.1.41.0
* **Operating System:** (Windows 11)
* **Application Type:** (WinForms)
* **.NET Version:** (NET Framework 4.7.2
![Schermafbeelding 2022-04-22 111055](https://user-images.githubusercontent.com/2353938/164675937-b387a03e-a44d-4569-bb51-d939de2e8f26.png)
)

im pretty sure i did not mis anything, but it just wont recognize it. 
but if i use go to definition, its there just fine.

**Comment by StendProg** [comment]
Hi @Damian666,

You're trying to instantiate a static method, that's an error. Just remove the `new` operator.

**Comment by Damian666** [comment]
oh god... what a rookie mistake xD

thanx for pointing that out man.

ill close this then
