### ISSUE TITLE
How to select a dragEnabled line or span then delete it? 

### ISSUE THREAD

**Issue by ShenxuanLi** [ScottPlot/ScottPlot#1798]
I want to select  a dragEnabled line or span by mouse , and right click to show menu to delete it.
How to selet the dragEnabled line or span  by mouse ,and get their index ?

**Comment by swharden** [comment]
Hi @ShenxuanLi,

The controls have `PlottableDragged` and `PlottableDropped` events you can subscribe to. When they are invoked the object they pass is the plottable that was just interacted with. You can use this to launch a custom right-click menu for draggable items.
