### ISSUE TITLE
candlestick x timeseries

### ISSUE THREAD

**Issue by robcpettit** [ScottPlot/ScottPlot#1799]
Hi, using  

```cs
var fp = WpfPlot1.Plot.AddCandlesticks(ohlcs.ToArray());
fp.Sequential = true;
```

I get the the candlesticks  display looking thick enough, but the dates are wrong. Set to false the dates are correct but the candles are to thin. Is there any way to have correct dates with sequential.  I tried the example plot candlesticks, but I Couldn't get my data to work with it.

**Comment by swharden** [comment]
Hi @robcpettit 

> Is there any way to have correct dates with sequential

I do not think so. The `Sequential` flag is used to indicate your data is a sequence of integers (not dates). This is useful because most financial charts aren't _actually_ plotted using horizontal dates otherwise there would be gaps for weekends.

**Comment by swharden** [comment]
See https://scottplot.net/cookbook/4.1/category/plottable-finance for examples of how to create candlestick charts
