### ISSUE TITLE
Class Plottable CrossHair

### ISSUE THREAD

**Issue by FrancisMartin-VB** [ScottPlot/ScottPlot#1800]
ScottPlot 4.1.41 et visual studio 2022 avec Windows 10

CrossHair renvoie un LegendItem Null (CrossHair returns a Null LegendItem)
public LegendItem[] GetLegendItems() => null;
Cela provoque une erreur dans (This causes an error in) 
class FormsPlot
public void DefaultRightClickEvent(object sender, EventArgs e)
        {
            bool legendHasItems = Plot.GetPlottables()
                                    .SelectMany(x => x.GetLegendItems())
                                    .Where(x => !string.IsNullOrEmpty(x.label))
                                    .Any();
            var legend = Plot.Legend(enable: null, location: null);
            bool legendIsNotDetachedAlready = legend.IsDetached == false;
            detachLegendMenuItem.Visible = legendHasItems && legendIsNotDetachedAlready;
            DefaultRightClickMenu.Show(System.Windows.Forms.Cursor.Position);
        }
où x != null n'est pas tester avant son utilisation dans la clause Where de la requête (where x != null is not tested before it is used in the Where clause of the query)

**Comment by StendProg** [comment]
Hi @FrancisMartin-VB ,

This bug has already been described in #1791.
The fix has already been made and is awaiting acceptance #1794.
It will take some time before it is released.

**Comment by swharden** [comment]
Thank you for reporting this @FrancisMartin-VB! 

This bug has been fixed in version 4.1.42 which will be released today 👍
