### ISSUE TITLE
SignalXY sometimes not rendered on high density data

### ISSUE THREAD

**Issue by bernhardbreuss** [ScottPlot/ScottPlot#1803]
**Issue:**
SignalXY does sometimes not render on high density data when only partial data should be rendered due to X axis limits.
![grafik](https://user-images.githubusercontent.com/3415431/165444653-40b102b3-28fd-4bd0-bc88-8af54abad722.png)
When changing the X axis limits just slightly (e.g. by panning) the signal renders fine:
![grafik](https://user-images.githubusercontent.com/3415431/165444968-ed031d97-cb04-4d42-9b16-0223ef7854b7.png)

The interpolation of the `PointBefore` results in a infinite Y value which eventually results in a overflow exception (which is handled by ScottPlot):
```
System.OverflowException: Overflow error.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawLines(Pen pen, PointF[] points)
   at ScottPlot.Plottable.SignalPlotXYGeneric`2.Render(PlotDimensions dims, Bitmap bmp, Boolean lowQuality)
   at ScottPlot.Plot.RenderPlottables(Bitmap bmp, Boolean lowQuality, Double scaleFactor)
```

**Reproducing:**
```cs
double[] ys = new double[10000];
double[] xs = ys.Select(x => double.PositiveInfinity).ToArray();
double r = 0.0;
for (int i = 0; i < ys.Length; i++)
{
    r += 0.005;
    xs[i] = r;
    ys[i] = Math.Sin(r);
}
var signalXY = WpfPlot.Plot.AddSignalXY(xs, ys);
WpfPlot.Plot.AxisAutoY();
WpfPlot.Plot.XAxis.Dims.SetAxis(min: r - 10.0, r);
WpfPlot.Plot.Validate(deep: true);
WpfPlot.Refresh();
```

### System Details
* **ScottPlot Version:** 4.1.41
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** .NET 6.0

**Comment by StendProg** [comment]
Hi @bernhardbreuss,

Thanks for the detailed report. Your example helped to quickly reproduce the problem and find a solution. #1806

**Comment by swharden** [comment]
Hi @bernhardbreuss, thank you for reporting this! @StendProg did a fantastic job fixing this in #1806 which I'm merging now. 

I will release a new package on NuGet within the next few days which will contain this fix 👍
