### ISSUE TITLE
`Legend` is visible after a `Detach Legend` has been closed

### ISSUE THREAD

**Issue by BambOoxX** [ScottPlot/ScottPlot#1804]
Hello, @swharden, I jsut stumbled upon a bug remaining from the 4.1.33 -> 4.1.34 modifications. 

In 4.1.33, when a detached legend is closed, no legend appears in the plotting area. In 4.1.34 it's the opposite. I am sure it makes sense for most people to have it this way, but in my case, it' absolutely the contrary ^^ (I have very long legend lists that do not fit in the plotting are). 

The behavior is handled in https://github.com/ScottPlot/ScottPlot/blob/f012da1a9ecb7effc4c83ab2cdcd7a049d0ba675/src/ScottPlot4/ScottPlot.WinForms/FormsPlotLegendViewer.cs#L30-L36
where obviously, the former state of the legend prior to the detach is forgotten, and a visible legend is enforced. 

I am not totally sure how we should proceed to sotre the forme visibility state of the `Legend`. Would you have an idea ?

Cheer !

**Comment by swharden** [comment]
Thanks for pointing this out @BambOoxX!

I solved the issue (#1819) by detecting the initial visibility state of the legend in the viewer's construction, then I restore that state (whether it was visible or not) as it closes

**Comment by BambOoxX** [comment]
Nice, thanks for the help!
