### ISSUE TITLE
How to create multiple series bar graphs?

### ISSUE THREAD

**Issue by Terebi42** [ScottPlot/ScottPlot#1824]
By default if I add 2 series to a bar graph, they overlap, so the smaller value is hidden behind a bigger value.

I can add .5 to one of the series to offset them, but thats a bit annoying/confusing

The group thing seems like it probably works, but is a lot of work/change to how to add the bars, especially if the different series aren't fully populated (missing values in the array, as I would have to go through and fully populate each series with 0s

I just want regular bars next to each other, where each tick value might have multiple bars for  a given value.

**Comment by swharden** [comment]
Hi @Terebi42,

This sounds like a grouped bar chart. Does this example help you achieve your goal?
https://scottplot.net/cookbook/4.1/category/plottable-bar-graph/#grouped-bar-graphs

**Comment by Terebi42** [comment]
@swharden The output of that is probably something like what I want. But it seems that you pass the series all at once, and they all have to have the same dimensions.  But the underlying data isn't necessarily that way. 

I may make a helper function/class that lets you add in series one by one, and will generate the needed inputs for the group.

**Comment by swharden** [comment]
> I may make a helper function/class that lets you add in series one by one, and will generate the needed inputs for the group

It is a little extra work, but I think this is indeed the best solution to solve this problem!

Related: #1749 was never finished, but such a plot type may make tasks like this easier in the future

**Comment by Terebi42** [comment]
Heres what I came up with.  Doesn't solve all use cases, but should be easy to expand. 

Notably out of score : error bars. Non-numeric groups.

Usage : 

`
            var helper = new GroupedBarHelper();
            helper.AddSeries(frequency, buckets, "Offense");
            helper.AddSeries(frequency2, buckets2, "Defense"); //Notably buckets2 can be very different than buckets
            var output = helper.GenerateOutput();
            plt.AddBarGroups(output.Positions, output.Series, output.Values, output.Errors);
`

Feel free to treat the below as a contribution, if you think others would find it useful.

`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OmegaBot.Shared.Graphs
{
    public class HelperSeries
    {
        public double[] Values { get; set; }
        public double[] Positions { get; set; }
       // public string[] NonNumericGroups { get; set; }
        public string Name { get; set; }
    }

    public class GroupedBarOutput
    {
        public double[][] Values { get; set; }
        public string[] Positions { get; set; }
        public string[] Series { get; set; }
        public double[][] Errors { get; set; }

    }

    public class GroupedBarHelper
    {
        List<HelperSeries> _series = new List<HelperSeries>();
        public void AddSeries(double[] values, double[] positions, string name)
        { 
            var series = new HelperSeries { Name = name, Values = values, Positions = positions };
            _series.Add(series);
        }

    

        public GroupedBarOutput GenerateOutput()
        {
            var output = new GroupedBarOutput();

            var combinedPositions = _series.SelectMany(s => s.Positions).Distinct().OrderBy(s => s).ToArray();
            output.Positions = combinedPositions.Select(s=>s.ToString()).ToArray();
            output.Series = _series.Select(s => s.Name).ToArray();

            var values = new List<double[]>(_series.Count);
            var errors = new List<double[]>(_series.Count);

            foreach (var series in _series)
            {
                var seriesValues = new double[output.Positions.Length];
                values.Add(seriesValues);

                var seriesErrors = new double[output.Positions.Length];
                errors.Add(seriesErrors);

                int i = 0;
                foreach (var position in combinedPositions)
                {
                    var index = Array.IndexOf(series.Positions, position);
                    if (index ==-1)
                    {
                        seriesValues[i++] = 0;
                        continue;
                    }
                    else
                    {
                        var value = series.Values[index];
                        seriesValues[i++] = value;
                        continue;
                    }


                }
                output.Values=values.ToArray();
                output.Errors=errors.ToArray();



            }



            return output;

        }

    }
}

`
