### ISSUE TITLE
SignalPlotXY, xs must be ascending values, exception in 4.1.43 but not ever in 4.1.41

### ISSUE THREAD

**Issue by Niravk1997** [ScottPlot/ScottPlot#1832]
## Bug Report

**Issue:** xs must be ascending values exception in 4.1.43 but not ever in 4.1.41

**Reproducing:** The below code will always run in ScottPlot 4.1.41 but will always generate an exception in 4.1.43. The exception is "xs must be ascending values (index 1 >= 2".

```cs
public partial class MainWindow : Window
    {
        private ScottPlot.Plottable.SignalPlotXY Measurement_Plot;

        public MainWindow()
        {
            InitializeComponent();

            try
            {

                int Limit = 50;

                double[] X = new double[100];
                double[] Y = new double[100];

                for (int i = 0; i < Limit; i++)
                {
                    X[i] = DateTime.Now.ToOADate();
                    Y[i] = i;
                }

                for (int i = Limit; i < X.Length; i++)
                {
                    X[i] = Double.MaxValue;
                    Y[i] = i;
                }

                Graph.Plot.XAxis.DateTimeFormat(true);
                Measurement_Plot = Graph.Plot.AddSignalXY(X, Y);
                Measurement_Plot.MaxRenderIndex = Limit - 1;

                Graph.Plot.AxisAuto();
                Graph.Refresh();
            }
            catch (Exception Ex) 
            {
                MessageBox.Show(Ex.ToString());
                Console.WriteLine(Ex.ToString());
            }
        }
    }
```

ScottPlot 4.1.41 - will always run
![image](https://user-images.githubusercontent.com/52579388/166860582-f74f6fb2-a203-4d8a-a9fe-0e8d99854c0a.png)

ScottPlot 4.1.43 - exception
![image](https://user-images.githubusercontent.com/52579388/166860617-a4f8517d-a29d-443c-9f06-3f5c55459e28.png)

### System Details
* **ScottPlot Version:** 4.1.43
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** NET Framework 4.7.2

**Comment by swharden** [comment]
This was a good opportunity to improve the exception message too

![image](https://user-images.githubusercontent.com/4165489/166920700-ca0c349f-de48-4b71-bda2-dcff087ff82a.png)

... but there's probably still room for improvement 😅 the word "but" looks weird there
