### ISSUE TITLE
Plottable: IHittable

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1844]
It seems like there should be an `IClickable` though which would be similar to [`IDraggable`](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot/Plottable/IDraggable.cs) and have an `EventHandler` you could subscribe to that would fire when the object is clicked. 

This idea originated from #1843

**Comment by levimann24** [comment]
@swharden This would be awesome! I just added this internally to my program for vLines using the isUnderMouse check. Works great, but it would be nice to have the event.

**Comment by bclehmann** [comment]
I think this could be more complicated than `IDraggable`, as we can give more to the listener than just the coordinates it was dragged to, what we pass back can be dependent on the type of plot (or even where on the plot it's clicked).

For example, with ScatterPlots it would be useful to know which dot was clicked. So maybe ScatterPlot needs to implement `IClickable<ScatterClickEventArgs>`, where `ScatterClickEventArgs` looks like this:

```cs
public class ScatterClickEventArgs {
    double X { get; set; }
    double Y { get; set; }
    int index { get; set; }
    .
    .
    .
}
```

So something like this looks like a good way to go:
```cs
public interface IClickEventArgs {
    double MouseX { get; set; }
    double MouseY { get; set; }
    IPlottable Plottable { get; set; } // This should be generic as well, so we don't just return any IPlottable, but a ScatterPlot
                                                     // I left it as is because I wasn't sure if this would even make it into a final version
}

public interface IClickable<T> where T: IClickEventArgs
{
    EventHandler<T> OnClick { get; set; } 
}


// For example only
public class ScatterClickEventArgs: IClickEventArgs {
    public double MouseX { get; set; }
    public double MouseY { get; set; }
    public IPlottable Plottable { get; set; }

    public double X { get; set; }
    public double Y { get; set; }
    public int index { get; set; }
}

public class ScatterPlot: IClickable<ScatterClickEventArgs> {
    public double MouseX { get; set; }
    public double MouseY { get; set; }
    public IPlottable Plottable { get; set; }
    public EventHandler<ScatterClickEventArgs> OnClick { get; set; }
}
```

**Comment by StendProg** [comment]
In the end, only visual controls will deal with the processing of events and their generation. The ScottPlot library and console applications will not be able to use these features. Implementing full-fledged event generation capabilities for each Plottable is labor-intensive and will significantly increase their code base. It may be worth shifting all responsibility for generating events to controls (ControlBackend) and `Plottables` themselves should implement the minimum necessary support that depends only on them, something like this:
```c#
public interface IHittable
{
   public bool HitTest(double x, double y);
}

public class ScatterPlot : IHittable
{
...
  public bol HitTest(double x, double y);
...
}

public class ControlBackend
{
 public event EventHandler PlottableClicked(object sender, EventArgs e);
 public event EventHandler PlottableMouseDown(object sender, EventArgs e);
 public event EventHandler PlottableMouseUp(object sender, EventArgs e);
 etc.
 ...
}

```

@bclehmann Yes, you are right, a lot of improvements and additions immediately come to mind. But in order to move forward, sometimes it is better to start with a simple one and do the most basic first with an eye to the fact that later it would be easy to add all the proposed improvements.

**Comment by bclehmann** [comment]
I agree with @StendProg, I think what I suggested is a good long-term goal, but in the short term simply having click detection is probably enough. It'll also give us some experience and some time to figure out what should actually be sent with these events.

I think it's probably still good to go with the generic approach to reduce friction if/when we add more features, but I think it's fine if most/all of the implementing classes only surface mouseX and mouseY.

**Comment by swharden** [comment]
### Architecture 

Thanks for both of your input! I like the idea of starting simple and using experience to guide the final architecture, adopting complexity if/as needed. Passing a custom EventArgs classes would offer many features, but require adding a lot of up-front complexity.

I also like the idea of keeping logic in the plottables as simple as possible (just hit detection) and keeping responsibility for event handling as high up as possible in the user controls.

### Coordinate vs. Pixel Space

There is a challenge where in different circumstances hit detection may be desired based on coordinate units or pixel units. Using pixel units is challenging because plottables typically are not aware of pixel space (except when it is transiently passed into the render method). It may be best to ensure hit detection only supports coordinate units, and expects the user to perform the pixel-to-coordinate transformation on their end.

### Interface Segregation

I'm reminded that `IDraggable` already has a method that performs hit detection (using coordinate units, with a pixel unit snap size), so solving this problem may involve breaking this method out into the `IHittable` interface

https://github.com/ScottPlot/ScottPlot/blob/ef520f92bd50654cb30f1a3e51841bb9909a4dda/src/ScottPlot4/ScottPlot/Plottable/IDraggable.cs#L9

**Comment by StuartWilloughby** [comment]
@swharden Looking at the 4.1 codebase it looks like ```IHittable``` only got rolled out for the ```Tooltip``` class. Was looking to use it for other plot types, but it appears it was never implemented. Can you confirm?
