### ISSUE TITLE
Plot object editor: improve ListBox labels

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1846]
Suggested by @BambOoxX in #1842, if the plottable has a legend label use that, otherwise use the contents of its ToString() method

Labels are currently being populated like this (which uses ToString() for everything):
https://github.com/ScottPlot/ScottPlot/blob/ef520f92bd50654cb30f1a3e51841bb9909a4dda/src/ScottPlot4/ScottPlot.WinForms/PlotObjectEditor.cs#L16-L17

**Comment by BambOoxX** [comment]
@swharden I'm not sure I was totally clear. I was referring to not only the lable, but the complete legend item. This way, searching for a plot to edit is close to searching something in the legend (in terms of color, line style ...)

**Comment by swharden** [comment]
> @swharden I'm not sure I was totally clear. I was referring to not only the lable, but the complete legend item. This way, searching for a plot to edit is close to searching something in the legend (in terms of color, line style ...)

Thanks for clarifying! I created this issue to address the `ToString()` text that `IPlottable` objects provide which is a pretty different topic than the one you raised.

Regarding this issue though, there's not one place where `ToString()` is defined. In fact, all plottables have the option to customize their own override, so there's not the consistency required to ensure each plottable adds its legend text in its `ToString()` override. 

It may be possible by creating a `PlottableBase`, making every `IPlottable` inherit that, then add such functionality there... but that's a pretty extensive refactor for something pretty trivial. I'll close this issue without modification to the code base.
