### ISSUE TITLE
Axis: tick labels misplaced for plots with multiple horizontal axes

### ISSUE THREAD

**Issue by Shengcancheng** [ScottPlot/ScottPlot#1848]
When I use multiple X-axes, I find that I can't bind lines to my newly added x-axis. However, it is possible to bind using multiple y-axis.

### System Details
* **ScottPlot Version:** 4.1.123
* **Operating System:** (Windows 10.)
* **Application Type:** (WinForms)
* **.NET Version:** (NET Framework 4.6.1)

**Comment by bclehmann** [comment]
Hello, it would help if you could include some sample code and a screenshot of the result?

**Comment by Shengcancheng** [comment]
Thank you for your reply.I've put my code and screenshots of the run below and look forward to your response.
`var x3 = fPlot_Position.Plot.AddAxis(Edge.Top, axisIndex: 2);
            x3.Label("RPM");
            x3.Ticks(true);
            x3.Grid(true);
            x3.SetSizeLimit(0, 300);

            fPlot_Position.Plot.XAxis.Ticks(false);
            fPlot_Position.Plot.XAxis.Grid(false);
            fPlot_Position.Plot.XAxis2.Ticks(true);
            fPlot_Position.Plot.XAxis2.Grid(true);

            fPlot_Position.Plot.YAxis.SetSizeLimit(-2,2);
            fPlot_Position.Refresh();`
`fPlot_Position.Plot.Clear();
            fPlot_Position.Plot.AddScatter(ROParray, iarray, lineWidth: 2f, markerShape: ScottPlot.MarkerShape.none).XAxisIndex = 1;
            fPlot_Position.Plot.AddScatter(RPMarray, iarray, lineWidth: 2f, markerShape: ScottPlot.MarkerShape.none).XAxisIndex =2;
            fPlot_Position.Refresh();`
![4ZQX~~2(Y4KI~_}N2}9)UIA](https://user-images.githubusercontent.com/64383244/170256010-0b2577ae-c71e-40fa-9343-dc882b68580a.png)

**Comment by bclehmann** [comment]
This occurred because of a bug in how we handle multiple axes, I opened a PR to fix it: #1861
