### ISSUE TITLE
When I use some non-native control libraries at the same time, such as sunnyUI, the fonts of those controls will appear jagged.

### ISSUE THREAD

**Issue by liuhongran626** [ScottPlot/ScottPlot#1851]
When I use some non-native control libraries at the same time, such as sunnyUI, the fonts of those controls will appear jagged.

**Comment by bclehmann** [comment]
Hello, a screenshot and some sample code would be helpful in diagnosing your issue. As it is right now, I'm not sure what the text looks like or why it's wrong.

I will say, however, it seems likely that it's an issue with the third-party control library or its dependencies.

**Comment by swharden** [comment]
Hi @liuhongran626,  

I will echo this sentiment. A screenshot and/or steps which can help me reproduce this issue would be very helpful for assessing its severity or determining a fix
