### ISSUE TITLE
Powershell Support

### ISSUE THREAD

**Issue by CarloToso** [ScottPlot/ScottPlot#1856]
## Feature Suggestion

**Feature description:** I have been succesfully using ScottPlot a plotting library in Powershell (both 5 and 7) for quite some time, I don't know if you want to support this feature, anyway I have written a Powershell Quickstart sample.

**Code example:**

```ps1
#[1]
Add-Type -Path .\ScottPlot.dll

[double[]] $dataX = @( 1, 2, 3, 4, 5 )
[double[]] $dataY = @( 1, 4, 9, 16, 25 )
$plt = [ScottPlot.Plot]::new(400, 300)
[Void] $plt.AddScatter($dataX, $dataY)
[Void] $plt.SaveFig("$pwd\quickstart.png")


#[2]
Add-Type -AssemblyName System.Windows.Forms
Add-Type -Path .\ScottPlot.dll
Add-Type -Path .\ScottPlot.WinForms.dll

#https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.Designer.cs

#formsPlot1
$formsPlot1 = [ScottPlot.FormsPlot]::new()
$formsPlot1.Anchor = [System.Windows.Forms.AnchorStyles]::Bottom -bor [System.Windows.Forms.AnchorStyles]::Right -bor [System.Windows.Forms.AnchorStyles]::Top -bor [System.Windows.Forms.AnchorStyles]::Left 
$formsPlot1.BackColor = [System.Drawing.Color]::Transparent
$formsPlot1.Location = [System.Drawing.Point]::new(0, 12)
$formsPlot1.Margin = [System.Windows.Forms.Padding]::new(4, 3, 4, 3)
$formsPlot1.Name = "formsPlot1"
$formsPlot1.Size = [System.Drawing.Size]::new(808, 405)
$formsPlot1.TabIndex = 0

#Form1
$Form1 = [System.Windows.Forms.Form]::new()
$Form1.AutoScaleDimensions = [System.Drawing.SizeF]::new(7, 15)
$Form1.AutoScaleMode = [System.Windows.Forms.AutoScaleMode]::Font
$Form1.ClientSize = [System.Drawing.Size]::new(808, 417)
$Form1.Controls.Add($formsPlot1)
$Form1.Name = "Form1"
$Form1.StartPosition = [System.Windows.Forms.FormStartPosition]::CenterScreen
$Form1.Text = "FormsPlot Sandbox"

#https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot.Sandbox/WinFormsApp/Form1.cs

[Void] $formsPlot1.Plot.AddScatter([ScottPlot.DataGen]::Consecutive(51), [ScottPlot.DataGen]::Sin(51))
[Void] $formsPlot1.Plot.AddSignal([ScottPlot.DataGen]::Cos(51))
[Void] $formsPlot1.Plot.AddVerticalLine(25)
[Void] $formsPlot1.Plot.AddText("test 123", 20, .5)
[Void] $formsPlot1.Plot.AddMarker(15, -.5, [ScottPlot.MarkerShape]::openCircle, 20)

[Void] $Form1.ShowDialog()
```

**Comment by bclehmann** [comment]
I'm rather impressed, I actually didn't know that powershell supported .NET interop.

@swharden I wonder if this issue should be moved to https://github.com/ScottPlot/ScottPlot.NET, as that's where the quickstarts live?

Also, as an aside @CarloToso, if you do \```ps1 in your markdown, you'll get powershell syntax highlighting. For example:

\```ps1
[Void] $formsPlot1.Plot.AddScatter([ScottPlot.DataGen]::Consecutive(51), [ScottPlot.DataGen]::Sin(51))
[Void] $formsPlot1.Plot.AddSignal([ScottPlot.DataGen]::Cos(51))
[Void] $formsPlot1.Plot.AddVerticalLine(25)
[Void] $formsPlot1.Plot.AddText("test 123", 20, .5)
[Void] $formsPlot1.Plot.AddMarker(15, -.5, [ScottPlot.MarkerShape]::openCircle, 20)

[Void] $Form1.ShowDialog()
\```

Yields:
```ps1
[Void] $formsPlot1.Plot.AddScatter([ScottPlot.DataGen]::Consecutive(51), [ScottPlot.DataGen]::Sin(51))
[Void] $formsPlot1.Plot.AddSignal([ScottPlot.DataGen]::Cos(51))
[Void] $formsPlot1.Plot.AddVerticalLine(25)
[Void] $formsPlot1.Plot.AddText("test 123", 20, .5)
[Void] $formsPlot1.Plot.AddMarker(15, -.5, [ScottPlot.MarkerShape]::openCircle, 20)

[Void] $Form1.ShowDialog()
```

**Comment by CarloToso** [comment]
Thank you @bclehmann , I'll edit my markdown.

**Comment by swharden** [comment]
Hi @CarloToso, 

I would love to add a quickstart for PowerShell users, but I'm struggling to get this working myself. I'm not a strong PowerShell user myself. Can you provide insight into what I'm doing wrong?

Step 1: Download latest [ScottPlot NuGet package](https://www.nuget.org/packages/ScottPlot/) as `scottplot.4.1.45.nupkg`

Step 2: Rename `scottplot.4.1.45.nupkg` to `scottplot.4.1.45.nupkg.zip` and unzip

Step 3: Copy the .NET Standard 2.0 `ScottPlot.dll` into a new folder

Step 4: Open powershell in that folder

Step 5: Allow execution of unsigned code in this session only ([Set-ExecutionPolicy](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy))

```ps
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser
```

```ps
Get-ExecutionPolicy -List
```

```
        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    Unrestricted
 LocalMachine       AllSigned
```

Step 6: Unblock the ScottPlot DLL ([Unblock-File](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file))

```ps
Unblock-File -Path .\ScottPlot.dll
```

Step 7: Interact with ScottPlot

```ps
Add-Type -Path .\ScottPlot.dll
```

I get this error:

```
Add-Type : Could not load file or assembly 'file:///C:\Users\scott\Documents\temp\ps\ScottPlot.dll' or one of its
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Add-Type -Path .\ScottPlot.dll
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.AddTypeCommand
```

Am I going about this the wrong way?

**Comment by swharden** [comment]
Update: I think my issue related to not having the correct dependencies available (e.g., System.Drawing.Common) and also targeting .NET 6 where it seems PowerShell only supports lower versions of .NET Core at this time. I got this working by targeting .NET Framework using this sequence of events:

Step 1: Create a .NET 6 console app and add ScottPlot package

```ps
dotnet new console
dotnet add package scottplot
```

Step2: Modify csproj for multi-targeting. This requires disabling implicit usings and setting language verison to latest.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net6.0;net5.0;net48</TargetFrameworks>
    <ImplicitUsings>false</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="scottplot" Version="4.1.45" />
  </ItemGroup>

</Project>
```

Step 3: Build the project to get the latest DLLs of everything we need

```
dotnet build
```

Step 4: Inside the .NET Framework 4.8 folder (next to ScottPlot.dll) make a powershell script `myScript.ps1` containing:
```ps
Add-Type -Path .\ScottPlot.dll
[double[]] $dataX = @( 1, 2, 3, 4, 5 )
[double[]] $dataY = @( 1, 4, 9, 16, 25 )
$plt = [ScottPlot.Plot]::new(400, 300)
[Void] $plt.AddScatter($dataX, $dataY)
[Void] $plt.SaveFig("$pwd\quickstart.png")
```

Step 5: Run the script:
```ps
.\myScript.ps1
```

![quickstart](https://user-images.githubusercontent.com/4165489/172080637-2573df6b-2043-41e9-b60b-1a853a1d3671.png)

---

This seems pretty clunky 😅 Is there a better way to set this up? 

I could add this to the list of quickstarts, but it had so many rough edges to get up and running I probably don't want to advertise it as a recommended way to use this library. If nothing else, people searching for the topic will find the code here. 

If someone knows a simpler way to do all this, let me know and I can update the text (or add a real quickstart page) as needed 👍

**Comment by bclehmann** [comment]
FWIW I tried this using PowerShell Core (7.2.4) and I had no issues. I tried again on classic powershell (5.1.22000.653) and I ran into the same thing you did.

If we do add it to the quickstart it's probably worth noting that Powershell Core is the recommended way.

**Comment by swharden** [comment]
> Powershell Core is the recommended way

Wow, this was so much easier! I guess ***Windows PowerShell*** really lags behind ***PowerShellCore*** when it comes to support for modern .NET code. Thanks for pointing this out!

## PowerShell Quickstart

**Step 1: Get PowerShell Core** 

* Do not use Windows PowerShell
* PowerShell Core can run on Windows, Linux, and MacOS
* Download from https://github.com/PowerShell/PowerShell

**Step 2: Build an empty .NET app using ScottPlot**

* `dotnet new console`
* `dotnet add package scottplot`
* `dotnet build`

**Step 3: Create a PowerShell script**
* Enter the builder folder containing `ScottPlot.dll`
* Create `myScript.ps1` and copy the following contents into it
* Run the script using PowerShell Core (not Windows PowerShell)

```ps
Add-Type -Path .\ScottPlot.dll
[double[]] $dataX = @( 1, 2, 3, 4, 5 )
[double[]] $dataY = @( 1, 4, 9, 16, 25 )
$plt = [ScottPlot.Plot]::new(400, 300)
[Void] $plt.AddScatter($dataX, $dataY)
[Void] $plt.SaveFig("$pwd\quickstart.png")
```

![quickstart](https://user-images.githubusercontent.com/4165489/172080637-2573df6b-2043-41e9-b60b-1a853a1d3671.png)

**Comment by CarloToso** [comment]
From what I understand each Powershell version is built from a different .NET version (Windows Powershell [5.x] targets the Net Framework 4.8; Powershell Core [7.x] targets Net Core 6.0). When I use Powershell 5 (legacy and quite bad) I use the net461 version of ScottPlot and it loads just fine, when use Powershell 7 (newer and updated) i use the netstandard2.0 version of ScottPlot. On Linux and MacOS System.Drawing.Common has been deprecated in net6.0 so you have to add this line of code to your script `[System.AppContext]::SetSwitch("System.Drawing.EnableUnixSupport", $True)`

**Comment by swharden** [comment]
> It seems that the System.Drawing.EnableUnixSupport switch will be removed in net7
[https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only](https://github.com/ScottPlot/ScottPlot/issues/url)

Oof ☠️ 

I've got to resume work to cut the System.Drawing.Common dependency out of this library! #1036, #1647

Hopefully I can set aside some time to get ScottPlot 5 up and running sooner than later.

Thanks again CarloToso for all the PowerShell info here!
