### ISSUE TITLE
Zooming does not working

### ISSUE THREAD

**Issue by niklight44** [ScottPlot/ScottPlot#1858]
Problems with zooming my plot. 
It doesn't work. 
I can only see zooming effect when I  click right mouse button on the plot and press Open In New Window. To see next effect of my zooming I need to open new window again. 

```cs
// a code sample may improve communication
// Thats the code I use in my MainWindow.xaml.cs file
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace WpfApp1
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            
            double[] dataX = new double[] { 1, 2, 3, 4, 5 };
            double[] dataY = new double[] { 1, 4, 9, 16, 25 };
            Chart.Plot.AddScatter(dataX, dataY);
            Chart.Refresh();
        }
    }
}
```

### System Details
* **ScottPlot Version:** 4.1.45
* **Operating System:** (Windows 11)
* **Application Type:** (WPF)
* **.NET Version:** (.NET 6.0)

**Comment by bclehmann** [comment]
I'm unable to replicate this, would you mind sending the `MainWindow.xaml` file as well?

**Comment by swharden** [comment]
Hi @niklight44, 

Similarly, I cannot reproduce this issue. Feel free to re-open this issue with a screenshot or more information (e.g., the code of your `MainWindow.xaml`) to help others reproduce the issue originally described
