### ISSUE TITLE
WPF show/hide line by clicking it in the legend

### ISSUE THREAD

**Issue by chenlinhsfl** [ScottPlot/ScottPlot#1862]
In the WinForm,it has a way to do this, like #1589
but in the WPF,i don't find this function,how can i do in the WPF

**Comment by swharden** [comment]
Hi @chenlinhsfl, presently the pop-out legend editor is only available in the WinForms control.

It would be possible to create a WPF equivalent to the `FormsPlotLegendViewer` ([source code](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot.WinForms/FormsPlotLegendViewer.cs)), but I do not intend to prioritize this at this point in time.

I also think multi-window WPF applications are considered an anti-pattern, or at least are not considered idiomatic WPF, but I recognize this rule is is already broken in the "open in new window" WPF right-click menu option.

If you decide to implement this functionality yourself, feel free to share your control and I can include it as part of a future release of ScottPlot! You can create a pull request or just copy/paste your code in a response to this issue 👍
