### ISSUE TITLE
Bracket: GetAxisLimits doesn't include bracket corners or label

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1871]
## Bug Report

**Issue:**

With the right mix of input and window size, you can get `GetAxisLimits` to chop off the bracket corners (and presumably the label):
<img width="500" alt="image" src="https://user-images.githubusercontent.com/8635304/171787974-61dbf333-0750-462f-afcb-3e1ae7a0855b.png">

Excuse the blurry picture, I had to shrink the window a fair bit to replicate it.

**Reproducing:**

```cs
plt.AddBracket(0, 0, 1, 1, "Bracket");
```

### System Details
* **ScottPlot Version:** Not yet released
* **Operating System:** Windows
* **Application Type:** All
* **.NET Version:** .NET 6

**Comment by bclehmann** [comment]
I don't think there's a good way to fix this bug, as the space from the point to the bracket corner is in pixel units, not axis units. So specifying an axis limit that accommodates it is a little sus. So the best option might be to file it under <kbd>wontfix</kbd>.

I just figured that I'd bring it up in case you wanted to do something about it before releasing a new version. Even if the most reasonable option is just excluding brackets from axis calculation.

**Comment by swharden** [comment]
> I don't think there's a good way to fix this bug, as the space from the point to the bracket corner is in pixel units, not axis units

This is a similar problem to that recently described by #1844 and #1845 where there's no good way for a plottable to know where things are in pixel space. The solution I used there was to store dimensions after each render and recall them as needed, which isn't great.

The only alternative I can think of is to pass a `PlotDimensions` into `GetAxisLimits()`, but that invites a lot of complexity I'm not excited about. For now, I'll just leave things as they are.

> most reasonable option

I feel good about including the two coordinates in each bracket in the axis limit calculations, and in the cookbook where necessary I demonstrate how to zoom out a bit using `Margins()` to ensure edges/text isn't cut-off. It's not perfect, but seems to be a good compromise for now.
