### ISSUE TITLE
Add option to customize step orientation

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1894]
Scatter and Signal plots have a step mode which connects points with a corner rather than diagonal line.

Example:
* https://scottplot.net/cookbook/4.1/category/plottable-signal-plot/#step-display

An option should be added so the step is top-left instead of bottom-right

This feature was suggested by @dhgigisoave in #1811

**Comment by bclehmann** [comment]
> top-left instead of bottom-right

Wouldn't the top/bottom change if the curve is increasing or decreasing? So I think it would be better to just specify left or right

**Comment by swharden** [comment]
Plottables with a `StepDisplay` will now have  `StepDisplayRight` variable (defaults to `true`) which controls step orientation. Step to the right means a point's level will be maintained to the right until it rises or falls to meet the next corner.

`StepDisplayRight = true` | `StepDisplayRight = false`
---|---
![image](https://user-images.githubusercontent.com/4165489/174919936-1527ee5c-2f66-417e-91d5-86a91883ac18.png)|![image](https://user-images.githubusercontent.com/4165489/174919949-676e0c0c-4fbc-4e32-8ea2-cf0028113d7e.png)
