### ISSUE TITLE
How to set the offset of the 0 scale of the other Y axis from the 0 scale of the Y main axis?

### ISSUE THREAD

**Issue by Liuwenjie0720** [ScottPlot/ScottPlot#1904]
I want to set data on different axes of multiple images, and set their Y-axis at different positions to facilitate data comparison, but I can't find a way to set the Y-axis offset, and at the same time set the position of the "MarkerPlot" drawing after different axes are set Not right.

![image](https://user-images.githubusercontent.com/38679806/175447270-5756b8d4-52c5-40f4-919f-e722312c4c0e.png)

**Comment by swharden** [comment]
Hi @Liuwenjie0720, 

To be honest I am having a difficult time understanding your question. I'll try to answer to the best of my understanding, but if I don't answer your question properly please consider rephrasing it and maybe it will be more clear next time.

> I want to set data ... set their Y-axis at different positions to facilitate data comparison

Signal plots have an X and Y offset you can define
https://scottplot.net/cookbook/4.1/category/plottable-signal-plot/#signal-offset

However most plot types do not. If you want your data to be displayed at a different height, you must add that height into the data before plotting it.

> I can't find a way to set the Y-axis offset

It is unclear if your goal is to move the _data_ up and down on the axis, or if your goal is to _set the axis limits_ to view a different region of the coordinate system. If your goal is to set axis limits of a specific axis to a different range, that can be achieved using:

```cs
formsPlot1.Plot.SetAxisLimits(yMin: -10, yMax: 10, yAxisIndex: 2);
```

I think these answers will solve your problem so I will close this issue, but you are welcome to open it again if I misunderstood your question.

**Comment by Liuwenjie0720** [comment]
Hi @swharden 
![image](https://user-images.githubusercontent.com/38679806/176138399-a8a231cb-faa3-4649-9f9f-4350d9f7ebf9.png)

Thanks for replying to me while you are busy
I'm very sorry, I use the translation tool to communicate with you
There should be something wrong with my description,
I want to draw a logic analyzer type table
as shown in the picture above

If you use one Y-axis per data, the data will be cluttered
If each data is given a Y axis, then I need to adjust the 0 point of the other Y axis to achieve the things shown above

So my question is actually how to achieve the effect of the above picture without modifying the data
And I think the way I can implement this image should be related to the example "MultiAxisLock"
But I can't use code to adjust the position of each Y axis 0 point

**Comment by Liuwenjie0720** [comment]
`var sp2 = plt.AddSignal(ys, sampleRate, Color.Magenta);
sp2.OffsetY = 1000;`

问题 可以被关闭了 
谢谢您的回复
Question can be closed
Thanks for your reply
