### ISSUE TITLE
Instructions to build recipes.json do not work

### ISSUE THREAD

**Issue by AbeniMatteo** [ScottPlot/ScottPlot#1917]
## Bug Report

**Issue:**
Running the tests, as instructed, doesn't generate `recipes.json`.
![image](https://user-images.githubusercontent.com/634710/176434325-0d8af808-3cc9-49e3-a6c7-e290670eaddb.png)

**Reproducing:**
1. Build and start WinForms Demo
2. Select any plot
3. Follow the instructions shown where the source code should be

### System Details
* **ScottPlot Version:** 4.1.50
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** .NET 6.0

**Comment by swharden** [comment]
Thanks for reporting this! That message is out of date. 

Cookbook figures and text are now generated by running the cookbook generator - a console application in the solution explorer.

I'll fix this (and review your other PR) later today. Thanks!
