### ISSUE TITLE
Crash when attempting to open cookbook

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1932]
## Bug Report

**Issue:** Clicking "Launch Cookbook" crashes the demo. The rest of the demo seems unaffected.

**Reproducing:** (What do others have to do to reproduce the bug?)
Click "Launch Cookbook" after running the demo.

### System Details
* **ScottPlot Version:** 4.1.51 (hash d0473d6bd5bcd366afd2bee3b811bbbf656c970b)
* **Operating System:** Windows 11
* **Application Type:** WPF, WinForms, presumably Avalonia
* **.NET Version:** .NET Framework 4.8, presumably all others

**Comment by bclehmann** [comment]
Git bisect labels af1fe595840125c2b336712613854c7e47acc40e as the first bad commit, which added a .gitignored directory to the list of searched directories.

When I deleted that directory it worked fine, suggesting that I had out-of-date or corrupted files in there.

I saw a few other things in this commit that caused concern, however:
- Referring to a .NET 5 only build directory is probably unwise, I don't remember how the `recipes.json` file is generated, but it could perhaps be brought out of the build directory
- `FileInfo fi = new(Path.Combine(path, jsonFilePath));` is, to say the least, suspicious
   - `jsonFilePath` is an absolute path, so `Path.Combine(path, jsonFilePath)` should not return coherent results. MSDN seems to suggest that it will simply return `jsonFilePath` unaltered: [However, if an argument other than the first contains a rooted path, any previous path components are ignored, and the returned string begins with that rooted path component.](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.combine?view=net-6.0)
   - Therefore this should probably be `FileInfo fi = new(jsonFilePath);`

**Comment by bclehmann** [comment]
I also think that scanning multiple directories for the recipes.json seems odd, we control where it gets placed and I believe there's only one of them, so we shouldn't need to look for it, or try again to see if it's hiding someplace else.

I still haven't looked into how recipes.json is generated, there may well be a reason for this complexity, but it seems odd to me.

**Comment by swharden** [comment]
Hi @bclehmann, thanks for pointing these issues out! I definitely agree this bit of code is pretty rough. I'll refine this to make it more accurate and hopefully make it more clear what it's doing and why.

https://github.com/ScottPlot/ScottPlot/blob/d0473d6bd5bcd366afd2bee3b811bbbf656c970b/src/ScottPlot4/ScottPlot.Cookbook/RecipeJson.cs#L81-L109

**Comment by swharden** [comment]
> I still haven't looked into how recipes.json is generated

The cookbook is a .NET Standard project so it can't be directly executed to generate the images/JSON.

There's a little cookbook generator app that does this. I'll move the cookbook generator to the top level of the solution to make it easier to find and reason about.

**Comment by swharden** [comment]
In addition to fixing the issues pointed-out above, I moved the cookbook generator (website generator) logic back inside the test system so running the tests generates `recipes.json` #1933

This is simpler to figure out and doesn't require a separate project just to generate the cookbook source file
