### ISSUE TITLE
FormsPlot: Flickering while dragging

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1938]
Now that `Application.DoEvents()` is no longer being called (#1906, #1913, #1919) I am noticing flickering while dragging in the WinForms control. This example is a signal plot with about 20k points. Flickering does not correspond with garbage collection.

![flicker2](https://user-images.githubusercontent.com/4165489/178073121-7a66cb35-ff0d-4da6-b411-b602381717f0.gif)

I'll try to fix this within the next few days, but @AbeniMatteo if you have any suggestions let me know! I may try to solve this by drawing directly on the control (not a PictureBox) and manually implementing double buffering.

**Comment by AbeniMatteo** [comment]
Check [this comment](https://github.com/ScottPlot/ScottPlot/pull/1913#issuecomment-1168574757).

Flickering was present before removing `.DoEvents()` but not after.
Are you testing with 4.1.51 or [4.1.51b](https://github.com/ScottPlot/ScottPlot/pull/1928/files#diff-0e159da8e201163742881ea960f7dc3f2048b1f6f2a1647ae687e117737e8932)?

**Comment by swharden** [comment]
@AbeniMatteo thanks for pointing that out! I confirmed that was the problem. I didn't push a NuGet package after that change, and calling `pictureBox1.Invalidate()` when the bitmap changes is what was producing the flickering. I'll issue a new release tonight.

On the up side I have some code that flickers a lot and may be useful to test against in the future:

```cs
double[] data = ScottPlot.DataGen.Sin(10_000, 3);

for (int i = 0; i < 10; i++)
{
    var sig = formsPlot1.Plot.AddSignal(data);
    sig.OffsetY = i * .1;
}

formsPlot1.Refresh();
```

![flicker3](https://user-images.githubusercontent.com/4165489/178126623-be2b984e-a731-4d42-92cd-1c48e83a888b.gif)
