### ISSUE TITLE
RNGCryptoServiceProvider is obsolete

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1959]
This warning appears during builds:

```
Warning SYSLIB0023: 'RNGCryptoServiceProvider' is obsolete: 
To generate a random number, use one of the RandomNumberGenerator static methods instead.
```

The offending line is here:

https://github.com/ScottPlot/ScottPlot/blob/5ba58fea707f0727dfa3fb800c10731ef12b4213/src/ScottPlot4/ScottPlot/Statistics/Common.cs#L11

**Comment by bclehmann** [comment]
I don't even think this needs to be a secure random number, `System.Random` should be fine for any statistical purposes.

We aren't doing any cryptography so we might as well use what is presumably a faster RNG.

**Comment by swharden** [comment]
We probably don't need bleeding-edge performance _or_ security, so functionally it doesn't really matter, but your comment is useful in understanding the differences between the random number options.

I "fixed" this issue by silencing the warning 😅 

```cs
#pragma warning disable SYSLIB0023
```
