### ISSUE TITLE
ScottPlot5: Improve user control API

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#1968]
After merging #1964 the `IPlotControl` API and related code could still use some review and fine tuning.

* **Dead zone:** Let's figure out how to better handle the "dead zone" pixel area (where click-drag is not respected) and to ensure the zoom rectangle isn't drawn when returning back to the dead zone.
  * https://github.com/ScottPlot/ScottPlot/pull/1964#discussion_r923976640
  * https://github.com/ScottPlot/ScottPlot/pull/1964#discussion_r923977581

* **Custom interactions:** There's a new `IPlotInteractions` which lets users load a whole set of alternative plot bindings (which mouse buttons do what), but there's probably a more convenient API for this. Let's explore some options. 
  * https://github.com/ScottPlot/ScottPlot/pull/1964#pullrequestreview-1042809240

Overall, you can see I'm going for absolute simplicity when it comes to implementing user controls on new frameworks. Here's the entire WpfPlot control for ScottPlot 5:

https://github.com/ScottPlot/ScottPlot/blob/84ec8c9bd7617d54d7999fc79322d9dd0650b37f/src/ScottPlot5/controls/ScottPlot.WPF/WpfPlot.xaml.cs#L13-L127

**Comment by BambOoxX** [comment]
Hi Scott, just a quick reaction to your comment, 
> to ensure the zoom rectangle isn't drawn when returning back to the dead zone.

Some other plotting libraries tend to provide a zoom rectangle that only zooms in horizontal or vertical directions if the mouse is dragged along the horizontal or vertical direction only (within a given tolerance). At the moment, I think this is something that `ScottPlot` does not allow, unless you lock the limits of the axis, but that's not very flexible.
This could be another nice improvement for v5.

**Comment by bclehmann** [comment]
A good example of that is this jsfiddle in plotly: https://jsfiddle.net/Lb476dan/

I find that it switching between types of zooms can be a little fiddly and jarring. They also have a similar thing for only the X axis that I've seen in their financial charts: https://jsfiddle.net/2c8e7qnm/ (might have to scroll down, by default the preview window is pretty small on jsfiddle).

**Comment by swharden** [comment]
> This could be another nice improvement for v5

It would be nice to make this easier! I agree with @bclehmann the zoom example demonstrated in plotly is a bit jarring. 

Maybe we can get the best of both worlds by improving the behavior (and rectangle placement) when CTRL or ALT are held down, so it's easier to use the mouse to set axis limits for a single axis.

I'll create a demo of this soon so we can evaluate how it feels

**Comment by swharden** [comment]
Following-up about the zoom thing, I implemented it in #1978 and it feels pretty good to me! It may be worth porting this functionality over to ScottPlot4.

![zoom](https://user-images.githubusercontent.com/4165489/180583713-98f057d4-1045-4864-a8f3-0e5dc83c5355.gif)

Regarding the new API, it seems to be evolving nicely and we are moving the daily small talk to Discord (#1966) so I think this issue can be closed to focus attention to #1955
