### ISSUE TITLE
ScottPlot Addsignalxy has decimal point error

### ISSUE THREAD

**Issue by xlqsfj** [ScottPlot/ScottPlot#1973]
double[] dataX = new double[] { 0.102, 0.086, 0.08, 0.078, 0.077, 0.076 };
    double[] dataY1 = new double[] { 1.2, 0, 0, 0, 1,6 };
 plot.AddSignalXY(dataX, dataY1);
报： System.InvalidOperationException:“xs must not descend: xs[0]=0.102 but xs[1]=0.086”

* If you use addscatter, you won't use this, but big data is stuck

**Comment by swharden** [comment]
Hi @xlqsfj 

SignalXY charts require that your X values only get larger. This is what the exception message is trying to express.

In your data the second value is smaller than the first, resulting in this error.

You are correct that for Xs which do not all increase, Scatter plot is the best option 👍
