### ISSUE TITLE
Website: FAQ Live Data page has broken link

### ISSUE THREAD

**Issue by glenvn1971** [ScottPlot/ScottPlot#1976]
Hi,

Thank you for this useful plotting control.

I am trying to download the example code for https://scottplot.net/faq/live-data/ - 404 error appears.

How can I download the example code?

Thank you

**Comment by swharden** [comment]
Hi @glenvn1971, this should be the correct link on that page

https://github.com/swharden/ScottPlot-old-website/tree/main/src/faq/live-data/src/MaxRenderIndex-WinForms

Source of that page is here: https://github.com/scottplot/scottplot.net/blob/main/content/faq/live-data/index.md

I'll update it shortly. Thanks for pointing it out!

**Comment by bclehmann** [comment]
That new link is broken too

**Comment by swharden** [comment]
I'm a little confused... I didn't make any changes, but the link seems to work now? I think GitHub changed/fixed something about their auto-forwarding for URLs of renamed projects

**Comment by bclehmann** [comment]
ScottPlot-old-website isn't a public repo I don't believe. I can only see a repo called ScottPlot.NET, not the old website repo

**Comment by MareMare** [comment]
![image](https://user-images.githubusercontent.com/807378/183275172-796b72ce-1c33-44bc-a496-a5516ce8a103.png)

I think there are two problems.
The first relates to URLs, and the second to downloading repository folders.

### URL
Maybe the following link is incorrect?
https://github.com/ScottPlot/ScottPlot.NET/blob/e3c5f9197e9e922f2592fa5fa4153f484f41b039/content/faq/live-data/index.md?plain=1#L26

* Incorrect：
  `https://github.com/ScottPlot/Website/tree/main/src/faq/live-data/src/ChangingFixedSignal-WinForms`
* Correct:
  `https://github.com/ScottPlot/ScottPlot.NET/tree/main/content/faq/live-data/src/ChangingFixedSignal-WinForms`

### Download repository folders
I don't remember, but I think the `ChangingFixedSignal-WinForms` folder used to be downloaded as a ZIP file.

If you change the aforementioned URL to the correct (I think) address, it would look like this:
```md
* [**Download this example project**](https://github.com/ScottPlot/ScottPlot.NET/tree/main/content/faq/live-data/src/ChangingFixedSignal-WinForms)
```
[**Download this example project**](https://github.com/ScottPlot/ScottPlot.NET/tree/main/content/faq/live-data/src/ChangingFixedSignal-WinForms)

However, this would not download the file as a ZIP file, but simply display it in the browser.

To download the file as a ZIP file, another tool (https://download-directory.github.io/) can be used as follows:
```md
[To download the file as a ZIP file](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FScottPlot%2FScottPlot.NET%2Ftree%2Fmain%2Fcontent%2Ffaq%2Flive-data%2Fsrc%2FChangingFixedSignal-WinForms)
```
[To download the file as a ZIP file](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FScottPlot%2FScottPlot.NET%2Ftree%2Fmain%2Fcontent%2Ffaq%2Flive-data%2Fsrc%2FChangingFixedSignal-WinForms)

This would have downloaded the file named `ScottPlot ScottPlot.NET main content-faq_live-data_src_ChangingFixedSignal-WinForms.zip`.

What do you think?
