### ISSUE TITLE
Plot.MatchAxis: Unintended AxisAuto()

### ISSUE THREAD

**Issue by PlayCreatively** [ScottPlot/ScottPlot#1980]
https://github.com/ScottPlot/ScottPlot/blob/d79f1898eda169daf884077ef9c6fb1e0c46a269/src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs#L177

When I have two graphs linked together on only one axis, using `MatchAxis()`, and I'm stretching the graph (using the RMB), the axis that's not linked gets auto sized to fit the data in the window, and overrides my (stretching) input.

I don't believe this to be the desired result and should be fixed by removing [this](https://github.com/ScottPlot/ScottPlot/blob/d79f1898eda169daf884077ef9c6fb1e0c46a269/src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs#L177) line.

**Comment by swharden** [comment]
Hi @PlayCreatively, It looks like this worked its way into the code in PR #1351 but should be removed. Thanks for pointing it out!
