### ISSUE TITLE
Controls: Shift + ScrollWheel has unique behavior on MacOS

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#1989]
## Bug Report

**Issue:** MacOS maps vertical scrolling to horizontal scrolling by default when shift is held.

**Reproducing:**

Hold Shift and scroll with the mousewheel. The plot will not do anything.

### System Details
* **ScottPlot Version:** 5 (commit 7711e23f7f76b59bc3f36c076b3ca1e6686d2076)
* **Operating System:** MacOS
* **Application Type:** Avalonia
* **.NET Version:** Any

**Comment by bclehmann** [comment]
I think these are the possible solutions:

- Detect MacOS shenanigans and correct for it
    - This may not be possible with all the edge cases, because I believe users can disable the shift+scroll behaviour without us knowing about it.
- Treat horizontal scrolling as equivalent to vertical scrolling (perhaps for Mac only)
    - This isn't ideal or ideologically pure, but it's simple, avoids complexity and suffices for the forseeable future
- Don't fix it
   - This is bad for obvious reasons
- Don't make shift+mwheel a combination
   - This is equivalent to not fixing it except it also effects non-mac users
- Replace shift+mwheel with another combination (or perhaps with another combination on MacOS)
   - This should probably also involve changing shift+drag combinations for consistency's sake.

**Comment by swharden** [comment]
> Treat horizontal scrolling as equivalent to vertical scrolling (perhaps for Mac only)

I'm probably leaning toward this one, since we don't even detect/support horizontal scrolling currently.

I'll try to make the change in a new PR, but do you have a mac you could test it on?

**Comment by swharden** [comment]
Is this related to this code comment?

https://github.com/ScottPlot/ScottPlot/blob/cf633532b178616d9b4f79da6de39e5375ee7676/src/ScottPlot5/Controls/ScottPlot.Avalonia/AvaPlot.axaml.cs#L110-L113

**Comment by swharden** [comment]
I'm a bit confused... and I think this is resolved already.

Controls only have `OnMouseWheel()` and not separate horizontal vs. vertical functions. 

Feel free to open this again if I misunderstood!
