### ISSUE TITLE
Error is ambiguous

### ISSUE THREAD

**Issue by Xerxes004** [ScottPlot/ScottPlot#1994]
https://github.com/ScottPlot/ScottPlot/blob/7711e23f7f76b59bc3f36c076b3ca1e6686d2076/src/ScottPlot4/ScottPlot/Plottable/ScatterPlot.cs#L277

I ran into a bug where the dimensions during render have infinite values (see snippet below), but the error thrown (linked above) points to my data being bad instead. It seems like the `PlotDimensions` passed into Render should be validated before Render is called. I verified that all of my data is finite.

My current workaround is to verify those dimensions myself.

Contents of the dimensions passed to Render:

```
AxisLimits: {AxisLimits: x=[-39690.28947368427, 1547921.2894736843] y=[∞, -∞]}
DataHeight: 212.4375
DataOffsetX: 59.5351563
DataOffsetY: 35.1015625
DataWidth: 290.464844
Height: 290
PxPerUnitX: 0.00018295712099970096
PxPerUnitY: 0
ScaleFactor: 1
UnitsPerPxX: 5465.7615649824011
UnitsPerPxY: -Infinity
Width: 372
XCenter: 754115.5
XMax: 1547921.2894736843
XMin: -39690.289473684272
XSpan: 1587611.5789473685
YCenter: NaN
YMax: -Infinity
YMin: Infinity
YSpan: -Infinity
```

**Comment by swharden** [comment]
Wow! How did this happen? My guess is plottable data contained infinity, then AxisAuto() set axis limits to infinity, then the render system blew up?

I'll add a check for this in the Render() method - thanks for reporting it!

**Comment by Xerxes004** [comment]
> Wow! How did this happen? My guess is plottable data contained infinity, then AxisAuto() set axis limits to infinity, then the render system blew up?
> 
> I'll add a check for this in the Render() method - thanks for reporting it!

It's entirely possible that my software set the plot dimensions to some wacky value right when it started up, so the first Render couldn't handle it. I was previously catching and logging errors while working through some other implementation details, and started to see this right when I started actually handling those errors instead.
