### ISSUE TITLE
add palettes

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2005]
I saw some nice ones recently
* https://www.refactoringui.com/previews/building-your-color-palette
* https://github.com/nealmckee/penumbra
* https://fffuel.co/pppalette/

**Comment by BambOoxX** [comment]
I don't know if it exists for dotnet but I very much like the ones in colorbrewer

**Comment by swharden** [comment]
> I don't know if it exists for dotnet but I very much like the ones in colorbrewer

Good point! This opens up a can of worms lol. Short story is that those palettes have a sticky non-standard license which also spilled over into heatmap discussions (#420, #458). 

I feel like there was a recent discussion too as to whether a palette of colors can be copyrighted in a way that requires attribution but I'm struggling to locate it. 

I just want to make sure we proceed in such a way that does not result in ScottPlot's users having to pollute their code bases with colorbrewer license files. One of my favorite things about this library is that it's 100% MIT-licensed code, and I'd like to keep that part as clean and simple as possible.

All that said, colorbrewer palletes sure are a standard in the scientific field

**Comment by swharden** [comment]
Here's the issue where we discussed colorbrewer legality in depth: https://github.com/ScottPlot/ScottPlot/pull/1314

It looks like then we decided that _colors_ are not copyrightable, as long as we are not copy/pasting _code_ to implement them

#notalawyer 😅

**Comment by BambOoxX** [comment]
Wow, that's a very thorough analysis of the legal aspects... Given that the colorbrewer are available in numerous plotting libraries I don't think there is much risk re using them here, but I'm not a lawyer either!
