### ISSUE TITLE
IDraggable: Support snapping

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2007]
@agorath suggested in #2006 it would be nice to have a way to implement snapping in draggable axis lines.

This issue will explore the different ways this may be achieved. An ideal solution would require no code modification to the existing library. The solution described below gets pretty close!#2006 

## Snap on Drop

This can be realized using existing code like this using the current library on NuGet.

![snap](https://user-images.githubusercontent.com/4165489/183267195-1bd27048-39e0-40aa-ba45-c5a057736227.gif)

```cs
public partial class Form1 : Form
{
    ScottPlot.Plottable.VLine VLine1;
    ScottPlot.Plottable.HLine HLine1;

    double[] YSnapPositions = DataGen.Consecutive(11, 0.2, -1);
    double[] XSnapPositions = DataGen.Consecutive(11, 5D);

    public Form1()
    {
        InitializeComponent();

        formsPlot1.Plot.AddSignal(DataGen.Sin(51), 1, Color.Black);
        formsPlot1.Plot.AddSignal(DataGen.Cos(51), 1, Color.Gray);

        VLine1 = formsPlot1.Plot.AddVerticalLine(23, Color.Blue);
        VLine1.DragEnabled = true;

        HLine1 = formsPlot1.Plot.AddHorizontalLine(.2, Color.Green);
        HLine1.DragEnabled = true;

        formsPlot1.PlottableDropped += FormsPlot1_PlottableDropped;

        formsPlot1.Refresh();
    }

    private void FormsPlot1_PlottableDropped(object sender, EventArgs e)
    {
        (double mouseX, double mouseY) = formsPlot1.GetMouseCoordinates();

        if (sender is ScottPlot.Plottable.VLine vline)
        {
            vline.X = GetClosestPosition(mouseX, XSnapPositions);
            formsPlot1.Render();
        }
        else if (sender is ScottPlot.Plottable.HLine hline)
        {
            hline.Y = GetClosestPosition(mouseY, YSnapPositions);
            formsPlot1.Render();
        }
    }

    private double GetClosestPosition(double mouse, double[] snaps)
    {
        double closestDistance = double.MaxValue;
        double closestPosition = double.MaxValue;

        for (int i = 0; i < snaps.Length; i++)
        {
            double distance = Math.Abs(mouse - snaps[i]);
            if (distance < closestDistance)
            {
                closestDistance = distance;
                closestPosition = snaps[i];
            }
        }

        return closestPosition;
    }
}
```

## Remaining Challenge

If you try to use the `PlottableDragged` event handler, dragging plottables automatically calls `Render`, so while dragging a plottable using this method it's not possible to snap in real time without causing flickering. I'll see if I can solve this.

![snap2](https://user-images.githubusercontent.com/4165489/183267237-e807c56b-9942-4db0-83f0-680c07dc5826.gif)

## Welcome to ScottPlot! 

Hi @Agorath 👋 welcome to the group (and the Discord! #1966). Even if we don't merge #2006 I'm happy for this question and I'm excited to figure out a solution since I doubt you're the only one interested in this topic 🚀

**Comment by BambOoxX** [comment]
Hey @swharden, maybe I missed something here, but what do you mean by snapping exactly. I have an application where I drag lines as the example you show and I don't think I get any flickering.

**Comment by swharden** [comment]
> what do you mean by snapping exactly

In the above example, the blue line "snaps" to grid lines (X positions that are multiples of 5)

The video in #2006 shows the desired behavior implemented with a custom plottable... I'm exploring if it's possible to achieve this effect with the existing plottable

Hope it helps!

**Comment by swharden** [comment]
Okay I think I figured this one out! I'm going to close #2006 and solve this in a slightly different way that I think will be simpler and easier to extend in the future. I'm going to add a function to draggable axis lines and axis spans that you can override with your own custom snapping logic.

```cs
public Func<Coordinate, Coordinate> DragSnap
```

It can be used like this:

```cs
var vLine = formsPlot1.Plot.AddVerticalLine(23, Color.Blue);
vLine.DragEnabled = true;
vLine.DragSnap = SnapToNearestInteger;
```

```cs
public Coordinate SnapToNearestInteger(Coordinate position)
{
    return new Coordinate((int)position.X, (int)position.Y);
}
```

<details>

<summary>see full WinForms code example</summary>

```cs
public partial class Form1 : Form
    {
        ScottPlot.Plottable.VLine VLine;
        ScottPlot.Plottable.HLine HLine;

        double[] YSnapPositions = DataGen.Consecutive(11, 0.2, -1);
        double[] XSnapPositions = DataGen.Consecutive(11, 5D);

        public Form1()
        {
            InitializeComponent();

            formsPlot1.Plot.AddSignal(DataGen.Sin(51), 1, Color.Black);
            formsPlot1.Plot.AddSignal(DataGen.Cos(51), 1, Color.Gray);

            VLine = formsPlot1.Plot.AddVerticalLine(23, Color.Blue);
            VLine.DragEnabled = true;
            VLine.DragSnap = SnapToX;

            HLine = formsPlot1.Plot.AddHorizontalLine(.2, Color.Green);
            HLine.DragEnabled = true;
            HLine.DragSnap = SnapToY;

            formsPlot1.Refresh();
        }

        private Coordinate SnapToX(Coordinate mousePosition)
        {
            double x = GetClosestPosition(mousePosition.X, XSnapPositions);
            return new Coordinate(x, mousePosition.Y);
        }

        private Coordinate SnapToY(Coordinate mousePosition)
        {
            double y = GetClosestPosition(mousePosition.Y, YSnapPositions);
            return new Coordinate(mousePosition.X, y);
        }

        private double GetClosestPosition(double mouse, double[] snaps)
        {
            double closestDistance = double.MaxValue;
            double closestPosition = double.MaxValue;

            for (int i = 0; i < snaps.Length; i++)
            {
                double distance = Math.Abs(mouse - snaps[i]);
                if (distance < closestDistance)
                {
                    closestDistance = distance;
                    closestPosition = snaps[i];
                }
            }

            return closestPosition;
        }
    }
```

</details>

![snap3](https://user-images.githubusercontent.com/4165489/183267835-020a7b0a-dd4c-45dd-9136-c20359dff406.gif)

**Comment by swharden** [comment]
One last follow-up before I merge #2008, I added the new functionality to `IPlottable` so it now supports axis lines, axis spans, vectors, draggable markers, draggable vectors, draggable scatter plot, and draggable text

I also changed `Coordinate` to simple `double` and broke the one function into two (separating X and Y functions)

```cs
// cookbook example
static double snapToNearestInteger(double coordinate)
{
    return Math.Round(coordinate);
}

plt.AddSignal(DataGen.Sin(51, mult: 5));
plt.AddSignal(DataGen.Cos(51, mult: 5));

var hLine = plt.AddHorizontalLine(2);
hLine.DragEnabled = true;
hLine.DragSnapY = snapToNearestInteger;

var vLine = plt.AddVerticalLine(30);
vLine.DragEnabled = true;
vLine.DragSnapX = snapToNearestInteger;
```
