### ISSUE TITLE
Hacktoberfest 2022 🎃🚀

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2010]
### ScottPlot is participating in Hacktoberfest 2022! 🚀 

Our community is friendly to new developers and first-time contributors!

If you have questions about contributing, feel free to ask here the ScottPlot Discord at https://scottplot.net/discord

To get started visit: https://hacktoberfest.com/participation

### Contribute a New Color Palette

Color palettes are a collection of several colors. ScottPlot can be configured to use a custom palette to color new items as they are added to the plot. See [Cookbook: how to use a custom palette](https://scottplot.net/cookbook/4.1/category/palette/#nord) and the [full list of color palettes](https://scottplot.net/cookbook/4.1/colors/) for more information.

To create a new color palette:
* Create a new file in `src/ScottPlot4/ScottPlot/Palettes/`
* Mimic code from the Dark palette in [ScottPlot/Palettes/Dark.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot/Palettes/Dark.cs)
* A code comment at the top can indicate the contributor and/or the source of the palette
* See your palette in action by running the demo application

Ideas for new color palettes may be sourced from: 
* https://color.adobe.com/explore
* http://tsitsul.in/blog/coloropt/ (adding `xgfs_tarnish6` would be great)

### Contribute a New Style

Styles are like themes that describe colors of the plot background, grid lines, labels, etc. A light theme is the default, but users can customize themes.

* Create a new file in `src/ScottPlot4/ScottPlot/Styles/`
* Mimic code from [Blue1.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot/Styles/Blue1.cs)
* See your palette in action by running the demo application

### Add a Cookbook Recipe

The ScottPlot Cookbook (https://scottplot.net/cookbook/4.1/) is generated from code examples in `src/ScottPlot4/ScottPlot.Cookbook/Recipes`. To add a new cookbook recipe, edit one of the files and add a class.

Example cookbook recipe: [Scatter Plot Quickstart](https://scottplot.net/cookbook/4.1/category/quickstart/#scatter-plot)

Example code for that recipe: [Scatter.cs#L8-L29](https://github.com/ScottPlot/ScottPlot/blob/07ab190973cbf8697ff8bdc98b4e6475ce40ea03/src/ScottPlot4/ScottPlot.Cookbook/Recipes/Plottable/Scatter.cs#L8-L29)

### Improve Cookbook Recipe Documentation

Cookbook descriptions and code comments may contain typos or confusing language. Contributions improving the clarity of existing cookbook recipes are welcome! Code is in `src/ScottPlot4/ScottPlot.Cookbook/Recipes`

### Improve XML Docs

Many functions have poorly written XML docs or lack XML docs completely. Users interested in improving code documentation are welcome to add XML docs to any function or property! Summary-only XML docs for functions are often acceptable.

### Improve the Website
* The website repo: https://github.com/ScottPlot/ScottPlot.NET
* UI/UX designers: We could used improved looking download buttons for the demo page

### Advanced Ideas
* #2141
* #2156
* Add syntax highlighting to ScottPlot4's demo application
* Add methods to generate test data for 2D arrays in ScottPlot4's [DataGen.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot/DataGen.cs) 
* Extend ScottPlot5's Heatmap
* Extend ScottPlot5's Colormap
* Add functions to ScottPlot5's [Generate.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Generate.cs) 
* #2137
* Add a FAQ page to the website documenting how to create a custom plottable (implementing `IPlottable`) and inject it into a plot using `Add()` ([#10](https://github.com/ScottPlot/ScottPlot.NET/issues/10))

**Comment by zachesposito** [comment]
@swharden For
> Add methods to generate test data for 2D arrays in ScottPlot4's [DataGen.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot/DataGen.cs)

Do you have any specific use cases in mind? I'm not super familiar with plotting use cases but I see one of the main reasons to plot a 2D array is a heat map so I could add some methods that generate data similar to those shown in the heat map recipes here https://scottplot.net/cookbook/4.1/category/plottable-heatmap/#heatmap-quickstart
