### ISSUE TITLE
Can I change the text position of markerplot?

### ISSUE THREAD

**Issue by jingsupo** [ScottPlot/ScottPlot#2025]
Can I change the text position of markerplot? For example, I want to put the text in the upper right corner?

![Snipaste_2022-08-08_19-19-15](https://user-images.githubusercontent.com/7351235/183407164-14dcb4f6-b16a-4603-90a4-8db467cff12d.png)

**Comment by swharden** [comment]
Hi @jingsupo,

This is a difficult question to answer based on your title/description. Can you clarify what you are trying to do? 

It looks like you already discovered how to add text to the upper right corner. The code that you used to add "top right" to the plot can be customized to make the text red and say "MarkerPlot" instead, then is this your issue resolved?
