### ISSUE TITLE
No Properties?

### ISSUE THREAD

**Issue by dx7v2** [ScottPlot/ScottPlot#2026]
## Bug Report

**Issue:** No Properties

**Reproducing:** Basically, I do not see anything about data char except configuration, I do not have Axis'es etc. (Scott.Plot does not work because I use winforms)

```cs
// a code sample may improve communication
var formsPlot1 = new FormsPlot();
            formsPlot1.MajorGrid(Color.FromArgb(100, Color.Black));
            formsPlot1.XAxis.MinorGrid(true, Color.FromArgb(20, Color.Black));
            formsPlot1.YAxis.MajorGrid(2,LineStyle.Dash, Color.Magenta);
````

### System Details
* **ScottPlot Version:** 4.1.52?
* **Operating System:** Windows 8.1
* **Application Type:** Winforms
* **.NET Version:** NET Framework 4.6.1
![image](https://user-images.githubusercontent.com/107001892/183517795-b4c9ed36-033a-451f-b6da-ea8cbb4bfae0.png)

**Comment by swharden** [comment]
Hi @dx7v2, try `formsPlot1.Plot.MajorGrid`,  `formsPlot1.Plot.XAxis`, etc...

Let us know if that doesn't do the trick! Good luck 🚀

**Comment by dx7v2** [comment]
![image](https://user-images.githubusercontent.com/107001892/183727540-a91a6eb9-256c-404e-a2e4-572af0e26889.png)
It says there is no MajorGrid function in Plot property.
```cs
            this.formsPlot1.Plot.MajorGrid(Color.FromArgb(100, Color.Black));
````

**Comment by swharden** [comment]
> It says there is no MajorGrid function in Plot property.

Thanks for the correction!

```cs
formsPlot1.Plot.XAxis.MajorGrid(Color.FromArgb(100, Color.Black));
```

more examples in https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#log-scale-tick-density

**Comment by dx7v2** [comment]
This happens when I wrote the code you show.
![image](https://user-images.githubusercontent.com/107001892/184003920-68bcf6b7-7fa9-44d5-b4a6-fd29b172b64c.png)
