### ISSUE TITLE
WinUIPlot: Create a plot control for WinUI

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2039]
There should be a `ScottPlot.WinUI` project that contains a `WinUIPlot`

Creating a control should be pretty easy... basically copy the logic in the other controls, for example:

https://github.com/ScottPlot/ScottPlot/blob/282a94a386ed59e252d877f55defa02990548034/src/ScottPlot4/ScottPlot.WPF/WpfPlot.xaml#L1-L33

https://github.com/ScottPlot/ScottPlot/blob/282a94a386ed59e252d877f55defa02990548034/src/ScottPlot4/ScottPlot.WPF/WpfPlot.xaml.cs#L1-L335

**Comment by swharden** [comment]
This thread hasn't been active for a few days so I'll close it for now, but we can open it again when someone is free to move it forward 👍

**Comment by rafntor** [comment]
Please have a look at https://github.com/ScottPlot/ScottPlot/pull/2374 - I believe that solves it , albeit with a twist in that it is a multi-targeting control and not purely WinUI.
