### ISSUE TITLE
Palette: capitalization inconsistency and enum discussion

### ISSUE THREAD

**Issue by bradmartin333** [ScottPlot/ScottPlot#2046]
## Feature Suggestion

The recent palette refactor is great. It is almost a complete replacement for the wrapper I had in place so that users could select a palette. All that is missing is an enum to chose palettes from.

**Code example**

I took the [public Palettes from here](https://github.com/ScottPlot/ScottPlot/blob/fff45bd0a020cf55e1523f98307f7f980e91e872/src/ScottPlot4/ScottPlot/Palette.cs#L14) and used regex to make the enum.

![Capture](https://user-images.githubusercontent.com/19335151/184879816-0eaabba3-4f86-459d-bb44-5691c1c6f31c.PNG)

Users can select their palette with a dropdown and the enum value gets saved/loaded from settings

```cs
private PaletteHost.Palettes _Palette = (PaletteHost.Palettes)Properties.Settings.Default.SEYR_Palette;
[
    Category("User Parameters"),
    Description("Choose from ScottPlot palettes"),
    DisplayName("Plot Window Palette")
]
public PaletteHost.Palettes Palette 
{ 
    get => _Palette;
    set
    {
        _Palette = value;
        Properties.Settings.Default.SEYR_Palette = (int)_Palette;
        Properties.Settings.Default.Save();
    }
}
```

**Mini-bug**

The name matching method in my screenshot works (might be a performance hit, but I haven't noticed so far) - but, I did notice that [SnowStorm != Snowstorm](https://github.com/ScottPlot/ScottPlot/blob/fff45bd0a020cf55e1523f98307f7f980e91e872/src/ScottPlot4/ScottPlot/Palette.cs#L29). So, I just changed it to a lowercase `s` in the enum.

Similarly, spaces get in the way with `Colorblind Friendly`, but this works:
`IPalette thisPalette = ScottPlotPalettes.Where(x => x.Name.Replace(" ","") == palette.ToString()).First();`

**Thoughts**

I know this is all driven by old WinForms stuff, so no big deal if this is not addressed. I have been moving towards newer frameworks and SkiaSharp, so I am looking forward to ScottPlot 5!

**Comment by swharden** [comment]
> Would your task be easier if you called ScottPlot.Palette.GetPalettes() instead of creating a custom enum?

Actually, disregard this question... I think I was/am a little confused about exactly what your code was doing 😅

**Comment by swharden** [comment]
Following-up, the source project is entitled "Snow Storm" ([link](https://github.com/arcticicestudio/nord)) so I think I'll respect that capitalization and two-word name even though [_snowstorm_](https://www.dictionary.com/browse/snowstorm) is a word.

**Comment by jp2masa** [comment]
This wasn't fixed correctly I guess, this file is now duplicated:

- https://github.com/ScottPlot/ScottPlot/blob/c168325f37f1c79bfe9b13072cf8f2806ed9b221/src/ScottPlot4/ScottPlot/Palettes/SnowStorm.cs
- https://github.com/ScottPlot/ScottPlot/blob/c168325f37f1c79bfe9b13072cf8f2806ed9b221/src/ScottPlot4/ScottPlot/Palettes/Snowstorm.cs

**Comment by swharden** [comment]
> This wasn't fixed correctly I guess, this file is now duplicated:

Interesting! It doesn't show up as a duplicate on my Windows system because windows filenames are case-insensitive. I'll delete it from GitHub's web interface, and that should do the trick
