### ISSUE TITLE
Can I set clip path to figure?

### ISSUE THREAD

**Issue by xichaoqiang** [ScottPlot/ScottPlot#2049]
Sometime I only need part on figure, can I set the area to show it?

 matplotlib.axes.Axes.set_clip_path can do it?

Is there any function to do this?

https://matplotlib.org/3.2.2/gallery/images_contours_and_fields/image_clip_path.html

**Comment by swharden** [comment]
Not inside the plot, but it can return a Bitmap that you can clip

```cs
using System.Drawing;
using System.Drawing.Drawing2D;

// create a plot
ScottPlot.Plot plt = new(600, 400);
Random rand = new(0);
double[] xs = ScottPlot.DataGen.Random(rand, 1000);
double[] ys = ScottPlot.DataGen.Random(rand, 1000);
plt.AddScatterPoints(xs, ys);
plt.SaveFig("original.png");

// create a clipped figure
using Bitmap bmpSource = plt.GetBitmap();
using Bitmap bmpDest = new(600, 400);
using Graphics gfx = Graphics.FromImage(bmpDest);
gfx.SmoothingMode = SmoothingMode.AntiAlias;
GraphicsPath path = new();
path.AddEllipse(0, 0, 300, 300);
Region region = new Region(path);
gfx.SetClip(region, CombineMode.Replace);
gfx.DrawImage(bmpSource, 0, 0);
gfx.ResetClip();
gfx.DrawPath(Pens.Red, path);
bmpDest.Save("clipped.png");
```

original | clipped
---|---
![original](https://user-images.githubusercontent.com/4165489/185137302-7dca2996-bffc-476a-bfff-cc1828dbc27d.png)|![clipped](https://user-images.githubusercontent.com/4165489/185138301-d90d85ff-c38e-4cc2-b6a2-2f9d751011e8.png)

**Comment by xichaoqiang** [comment]
If I want clip the heatmap with my defined path. How can I do?

**Comment by xichaoqiang** [comment]
Or is there any way don't need save png?

**Comment by xichaoqiang** [comment]
Like this
![image](https://user-images.githubusercontent.com/30900789/185153428-dced2336-d1db-406e-838a-a4767163a48c.png)

**Comment by swharden** [comment]
> If I want clip the heatmap with my defined path

Thank you for clarifying this request! This is not possible presently, but I understand the feature request better now and think I can add it within the next few days. I'll follow-up in this issue when this feature has been added 👍

**Comment by swharden** [comment]
Additionally, note that heatmaps can contain "empty" squares. 
https://scottplot.net/cookbook/4.1/category/plottable-heatmap/#heatmap-with-empty-squares
If you want to achieve a similar "clipping" effect using the existing library, set the squares that lack data around the edges to `null`

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
Thank you.

**Comment by swharden** [comment]
I could add a feature like this to heatmap and image plots. What do you think?

```cs
public Form1()
{
    InitializeComponent();

    double[,] data = ScottPlot.DataGen.SampleImageData();

    var heatmap = formsPlot1.Plot.AddHeatmap(data, lockScales: false);

    Coordinate[] clipPoints =
    {
        new Coordinate(30, 15),
        new Coordinate(55, 40),
        new Coordinate(60, 45),
        new Coordinate(80, 60),
        new Coordinate(40, 95),
        new Coordinate(15, 90),
        new Coordinate(5, 50),
    };

    heatmap.ClippingPoints = clipPoints;

    formsPlot1.Refresh();
}
```

original | clipping
---|---
![image](https://user-images.githubusercontent.com/4165489/185254232-158e0900-890e-41b9-aa6c-28c23eb9b583.png)|![image](https://user-images.githubusercontent.com/4165489/185254197-099d8255-6db9-428d-9356-4db193422ba7.png)

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.Very good.

**Comment by swharden** [comment]
https://scottplot.net/faq/data-gaps/
