### ISSUE TITLE
Heatmap plots are always rendering using 'smooth' on Linux and ignoring the specified boolean.

### ISSUE THREAD

**Issue by trb5016** [ScottPlot/ScottPlot#2056]
## Bug Report

**Issue:**
Heatmap plots are always rendering using 'smooth' on Linux and ignoring the specified boolean.

Am curious if it's just me/my environment, or if it's a standard Linux issue.

**Reproducing:** Create a heatmap plottable on and run on Linux vs. Windows.  (See specific version info below)

**Thoughts:**
I saw in [this issue thread](https://github.com/ScottPlot/ScottPlot/issues/1003#issuecomment-850093369)  the mention that linux has some issues with the InterpolationMode.  I'm assuming it's something related to that?  (Though I would have expected it to not work at all, rather than go with a different interpolation mode?)

### System Details
* **ScottPlot Version:** 4.1.57
* **System.Drawing.Common:** 6.0.0
* **libgdiplus:** 2.10-10.el7
* **Operating System:** (RHEL7, Windows 10)
* **Application Type:** console
* **.NET Version:** (.NET 6.0)

**Comment by trb5016** [comment]
I ran some code that manually sets the InterpolationMode through all the enum options and it works as expected on Windows, it makes absolutely no difference on Linux, they're all the exact same resultant image.  (I think bilinear?)

So ultimately I guess this is a libgdiplus issue?  Any insight would be welcome, but otherwise feel free to close out.

**Comment by swharden** [comment]
>  InterpolationMode ... makes absolutely no difference on Linux

> So ultimately I guess this is a libgdiplus issue?

Unfortunately, yeah, I think this is the case 😩 

Related, https://github.com/ScottPlot/ScottPlot/issues/1003#issuecomment-850093369

Since it's a libgdiplus issue I don't think there's an easy solution. ScottPlot5 will use SkiaSharp and produce more consistent (and performant) renders across all platforms 🚀  
* #1966
* #1955
