### ISSUE TITLE
Linux: System.Drawing.Common font issues

### ISSUE THREAD

**Issue by cnelson04-beckman** [ScottPlot/ScottPlot#2059]
**Issue:** (Bug description goes here)

Text is rendering fine when running in windows but in Linux much of the text is just boxes, but on the Y-axis only, the x-Axis show no text. Also when I try to change the font, crashes the program, but only on Linux. Use Maven to compile the Linux code and using Ubuntux for Linux. 

So I was missing the Windows.Drawing. When I add version 6 it crashes
in my project file
 <PackageReference Include="System.Drawing.Common" Version="6.0.0" />

**Reproducing:** (What do others have to do to reproduce the bug?)

                    double[] dataX = list.Select(i => i.Item1.ToOADate()).ToArray();
                    double[] dataY = list.Select(i => i.Item2).ToArray();
                    plot.XAxis.TickLabelFormat("MM\\/dd\r\nHH:mm", dateTimeFormat: true);
                    plot.AddScatter(dataX, dataY, Color.Black);

Move this back to version 5 it works.

### System Details
* **ScottPlot Version:** 4.1.57
* **Operating System:** (Ubuntu Linux 20.04, Windows 10, MacOS 10.15, etc.) Ubuntu 20.04.4 LTS
* **Application Type:** (console, WinForms, WPF, Avalonia, etc) Avalonia
* **.NET Version:** (NET Framework 4.8? .NET 5.0?) 5.
![Linux Running](https://user-images.githubusercontent.com/100809531/185937330-f8dede02-c5e1-49c7-912e-4f8f48345f35.png)
![Windows Running](https://user-images.githubusercontent.com/100809531/185937345-08e68f54-c8e9-4f00-a602-3151a10d7cfc.png)
0

**Comment by swharden** [comment]
Hi @cnelson04-beckman do these additional steps help?

https://scottplot.net/faq/dependencies/#linux--macos

Related:
* #1729

**Comment by swharden** [comment]
I'm pretty sure https://github.com/ScottPlot/ScottPlot/issues/2059#issuecomment-1222480567 will adequately resolve this issue, but if not feel free to open this issue back up with additional details 👍

**Comment by swharden** [comment]
This seems to be a common problem so I created a FAQ page to help people find the solution when they search: https://scottplot.net/faq/linux-font/
