### ISSUE TITLE
How can I add signal in vertical direction ?

### ISSUE THREAD

**Issue by xichaoqiang** [ScottPlot/ScottPlot#2061]
Dear Scott

The addsignal fucntion is very powerful.

How every I want add signal in vertical direction .

How can I do? 

Best regards,
XI

**Comment by xichaoqiang** [comment]
My y value is evenly spaced. :(

**Comment by swharden** [comment]
Hi @xichaoqiang, 

The simplest solution is just to use a scatter plot. Those can plot vertically.

```cs
var plt = new ScottPlot.Plot(600, 400);
double[] xs = DataGen.Sin(51);
double[] ys = DataGen.Consecutive(51);
plt.AddScatter(xs, sin);
plt.SaveFig("test.png");
```

If a signal plot is really necessary, I think a previous user achieved this by rotating the plot (and all the text on it):
* #1194

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply. Vertical graph is very important for us.
