### ISSUE TITLE
Vertical baseline for AddFill()

### ISSUE THREAD

**Issue by geosc** [ScottPlot/ScottPlot#2062]
**ScottPlot Version:** 4.1.57

**Operating System:** Window 10 64-bit

**Application Type:** WPF

**Question:** 

Is there a function that I can fill the area between X values and a vertical baseline?

Currently, the "AddFill()" function seems only supports to fill the area between Y values and a horizontal baseline.

```cs
AddFill(xs, ys, baseline)
```

![捕获](https://user-images.githubusercontent.com/25169559/186398808-c0a79a80-2d43-4f06-8eae-b5ab4e0f1e67.PNG)

**Comment by swharden** [comment]
Hi @geosc, 

Thanks for raising this issue! That helper method makes it easy to achieve the common case (baseline filling to Y values), but I recognize it doesn't make it easy for users wanting to plot data vertically.

I hope this code will be useful! It shows how to plot a sine wave vertically shading between the curve and an arbitrary baseline.

```cs
double[] ys = ScottPlot.DataGen.Consecutive(51);
double[] xs = ScottPlot.DataGen.Sin(51, oscillations: 2);
double baselineX = 0.1;

var plt = new ScottPlot.Plot();
double[] ys2 = ScottPlot.Tools.Pad(ys, cloneEdges: true);
double[] xs2 = ScottPlot.Tools.Pad(xs, 1, baselineX, baselineX);
plt.AddPolygon(xs2, ys2);
plt.SaveFig("vertical.png");
```

![image](https://user-images.githubusercontent.com/4165489/187098024-09e4341b-80b1-42d8-b64c-df140d25eed0.png)

**Comment by geosc** [comment]
Thank you so much.




---- Replied Message ----
| From | Scott W ***@***.***> |
| Date | 8/29/2022 06:59 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [ScottPlot/ScottPlot] Vertical baseline for AddFill() (Issue #2062) |

Hi @geosc,

Thanks for raising this issue! That helper method makes it easy to achieve the common case (baseline filling to Y values), but I recognize it doesn't make it easy for users wanting to plot data vertically.

I hope this code will be useful! It shows how to plot a sine wave vertically shading between the curve and an arbitrary baseline.

double[] ys=ScottPlot.DataGen.Consecutive(51);
double[] xs=ScottPlot.DataGen.Sin(51, oscillations: 2);
doublebaselineX=0.1;

varplt=newScottPlot.Plot();
double[] ys2=ScottPlot.Tools.Pad(ys, cloneEdges: true);
double[] xs2=ScottPlot.Tools.Pad(xs, 1, baselineX, baselineX);
plt.AddPolygon(xs2, ys2);
plt.SaveFig("vertical.png");
