### ISSUE TITLE
VectorField: support for arbitrary vector positions

### ISSUE THREAD

**Issue by sjdemoor** [ScottPlot/ScottPlot#2064]
## Feature Suggestion

**Overload VectorField() signature to allow for a List of vectors** 

Current VectorField signature is:

```cs
public VectorField(
    Vector2[,] vectors, 
    double[] xs, 
    double[] ys, 
    Colormap colormap, 
    double scaleFactor, 
    Color defaultColor)
```

which assumes that data are arrayed in a uniformly spaced 2D array, i.e., *Vector2[,]*.

We are working with more or less randomly positioned vector data, which converts into a very sparse Vector2[,] matrix, which the current VectorField() function cannot process.  Being able to send a 1D array or <List> of doubleXY vectors (see code below) to the VectorField() function would allow the plotting of randomly positioned vectors.  The overloaded VectorField() signature would look like this:

```cs
public VectorField(
    doubleXY[] vectors, 
    double[] xs, 
    double[] ys, 
    Colormap colormap, 
    double scaleFactor, 
    Color defaultColor)
```

where; the "vectors", "xs" and "ys" arrays are linked lists of vectors, xPositions and yPositions respectively; and *doubleXY* is defined as follows:

### class doubleXY
```cs
public class doubleXY
{
    public double X { get; set; }
    public double Y { get; set; }

    public doubleXY()
    {
        X = 0;
        Y = 0;
    }

    public doubleXY(double x, double y)
    {
        X = x;
        Y = y;
    }

    public doubleXY(string x, string y)
    {
        X = 0;
        Y = 0;
        double tempX;
        if (double.TryParse(x, out tempX))
        {
            X = tempX;
        }
        double tempY;
        if (double.TryParse(y, out tempY))
        {
            Y = tempY;
        }
    }

    public override string ToString()
    {
        return String.Format("X: {0}, Y:{1}", X, Y);
    }

    public override bool Equals(Object obj)
    {
        //Check for null and compare run-time types.
        if ((obj == null) || !this.GetType().Equals(obj.GetType()))
        {
            return false;
        }
        else
        {
            doubleXY p = (doubleXY)obj;
            return (X == p.X) && (Y == p.Y);
        }
    }
}
```

**Comment by cliff-lane** [comment]
I have the same issue

**Comment by swharden** [comment]
Hi @sjdemoor (and @cliff-lane), thanks for the suggestion!

Re-stating the goal, presently vector fields require vectors to be in a grid, but you'd like to plot arbitrary vectors. I think this would be an excellent feature to add!

You point-out that the 2D array of vectors makes sense for rectangular grids, but not for arbitrary vectors. I agree. I'll create a new plot type to make this easier and update this issue when it is ready to use 👍 

Thanks again for the suggestion!

**Comment by sjdemoor** [comment]
@swharden , that would be awesome!  I had attempted to overload the 'VectorField()' function, but it was getting fairly messy rather quickly.  I think a new plot type would be a much cleaner solution.

Thanks for considering this feature request.
