### ISSUE TITLE
Layout: how to use entire height

### ISSUE THREAD

**Issue by pracplayopen** [ScottPlot/ScottPlot#2068]
**ScottPlot Version:** 4.0.48

**Operating System:**  ubuntu 20.1 ulyssa

**Application Type:** just an api that generates an image file

comment: used scottplot for a couple years. it's well made tool, thx for your efforts.

**Question:** 

does scottplot not automatically try to use the entire width height?

fromo experience, it seems that it usually does- but are there situations where it wouldn't?

situation:
1. generating several plots and inserting them into the final exported image.
1. the first 8 plots are generated in a loop with identical plot parameters
1. the plot size particularly is fixed, both width and height
1. certain plots even though they generate the correct size image... don't seem to utilize their full height?
1. here is code snippet

```cs
                var plt = new ScottPlot.Plot(w, ph); // ph is the height value for each plot in the loop
                var sig = plt.PlotBar(dates, sigdata, fill:true, fillColor:sigcolor,
                    negativeColor:sigcolor, outlineColor: sigcolor, valueColor: sigcolor, 
                    errorColor:sigcolor);
// draw plot to main image
                draw.DrawImage(plt.GetBitmap(true,false), 0, ph * pcnt++);
```

this generates the following image:
* only plots 1-8 are generated in the loop
* the plotheight value is shown in title as ph, all identical
* plot 8 is the clearest example of it not filling all the vertical space it has

![scottplot-height-not-scaled](https://user-images.githubusercontent.com/11450154/186984372-d87533ae-2427-4374-98af-8e7fa3a49063.png)

I scoured the docs to see if there is some way to force vertical scaling to something like 'fit image'.
On discord somebody suggested trying MatchLayout, even though all the heights are already identical.
This had no effect.

Wondering if this is an easy fix or what situations this can happen in?

thx

**Comment by swharden** [comment]
Hi @pracplayopen, 

Is your problem solved if you manually set the padding for your plots?

https://scottplot.net/cookbook/4.1/category/layout/#manual-data-area

```cs
var padding = new ScottPlot.PixelPadding(
    left: 150,
    right: 30,
    bottom: 100,
    top: 10);

plt.ManualDataArea(padding);
```

If you want to set the top and bottom padding to 0 you may also want to disable ticks

```cs
plt.XAxis.Ticks(false);
```

Let me know if this doesn't do the trick and I'll take a closer look 👍

**Comment by pracplayopen** [comment]
thanks for quick response.

so it looks like pixel padding might be a newer release (currently using 4.0.48, not 4.1).
tried upgrading but seems it is not backwards compatible as some calls won't compile.

as a test/isolation, did try disabling ticks in general.  that did 100% fix the height issue, all the plots are same size now.

problem is that- as is probably expected- this dropped correct date formatting on xaxis, it now shows the raw integer OAtime values (y-axis still looks same/correct).

is there a reason that even though every plot has same X axis values and same ticks setting (and both unaffected and affected plots often share same range values), same size... that some are still drawn differently?

if it's a bug that's cool it just means we need to upgrade.   but i don't quite get for same domain and range bounds, and literal same domain x values... why is one plot being drawn differently?

is there another way to affect this?  or even post-upgrade, will it have to be padded differently for different plots even though they are same size and bounds?  that's what is confusing.

**Comment by pracplayopen** [comment]
ah- ok so i think this is mostly a bug here.   and it's obvious from the screenshot- is that to save space only the last plot in this series (plot 8) has xaxis labels.   so it makes sense that is causing extra space, even though all bounds are same.

so was able to improve a lot by making xaxis font size same as titles.  however if could use a less-verbose date format, that would save more space.

tried using [cookbook 'format ticks with custom culture'](https://scottplot.net/cookbook/4.0/#customize-ticks---format-ticks-with-custom-culture) but this didn't change date format to a shorter form:

> plt.Ticks(dateTimeX: true, displayTicksX: islast, fontSize:titsz);

which helps
but can't get a shorter date to have any effect, always showing full month name and 4-digit year no matter what is  tried:

> // same result for both as if didn't use them at all
> plt.SetCulture(shortDatePattern:"M\\/dd"); // from the cookbook example
> plt.SetCulture(shortDatePattern:@"MM/dd/YY");

if you have any ideas appreciate it much

**Comment by swharden** [comment]
> but can't get a shorter date to have any effect, always showing full month name and 4-digit year no matter what is tried

Try using a custom tick formatter! It lets you control 100% the format of the tick labels

https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#custom-tick-formatter

Note that dates are "OADate" formatted, so to convert a `double` to a `DateTime` you call `x.ToOADate()`

**Comment by pracplayopen** [comment]
ok so since still running 4.0 for moment, don't think can use that.

instead was able to [use this issue to pass standard date/time formatting to axis labels](https://github.com/ScottPlot/ScottPlot/issues/554)

working now.
