### ISSUE TITLE
SignalPlot: MaxRenderIndex defaults to 0

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2069]
---------------------------------

**ScottPlot Version:** 4.1.57

**Operating System:** Win10 x64

**Application Type:** Winform

Hello! 
I just do not get it, why I only get a single marker when using a simple SignalPlot. Sure I miss something obvious :) 
vehicle.Piezo1 is a List<int>, and contains data. I have checked piezo1_Curve.Ys, also contains data.
Thanks!

In my Class:
```cs
public FormsPlot Chart { get; set; }
....
SignalPlot piezo1_Curve = new SignalPlot();
piezo1_Curve.Ys = vehicle.Piezo1.Select(x => (double)x).ToArray();
// add it to the plot
Chart.Plot.Add(piezo1_Curve);                
Chart.Render();
```
![image](https://user-images.githubusercontent.com/51174971/187047267-f94d21ae-5247-4daa-97e4-9a52985ce208.png)

Images or screenshots often help communication and are encouraged. You can copy/paste or drag/drop images into this box.

**Comment by swharden** [comment]
Hi @bukkideme 

Thank you for posting this issue - you revealed a trap that is not easy to figure out for newcomers!

If you're going to `new` a `SignalPlot` explicitly, `MaxRenderIndex` must bet set manually. This is not at all easy to figure out 🤦 

I should probably modify that field to default to `double.PositiveInfinity` to make it less confusing in the future

Related, this is all the stuff the `Plot.AddSignal()` method does

https://github.com/ScottPlot/ScottPlot/blob/5fd8246eeaf6206336cd00a4987b9b1a24507b99/src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs#L1158-L1176

**Comment by swharden** [comment]
lol @ `TODO: FIX THIS!!!` 🤣🤷

**Comment by bukkideme** [comment]
thanks! :)

**Comment by swharden** [comment]
After all that I'll probably leave it like it is, but hopefully I can make this less surprising in ScottPlot 5 👍
