### ISSUE TITLE
FAQ - Show value near mouse example, wrong type?

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2070]
https://scottplot.net/faq/mouse-position/#show-value-near-mouse-with-winforms

Hi!

HighlightedPoint should not be MarkerPlot instead of ScatterPlot?

formsPlot1.Plot.AddPoint(0, 0) method returns MarkerPlot, so for me
private readonly ScatterPlot HighlightedPoint; does not work, only if I use
private readonly MarkerPlot HighlightedPoint;

Thanks!

**Comment by swharden** [comment]
Good catch! The documentation fell out of date with the latest API 😩 

In ScottPlot 5 I'll do my best to generate all the docs from tests so they can't break (as long as the tests keep passing)

I'll leave this issue open until I'm able to fix that code example

**Comment by swharden** [comment]
Fixed in https://github.com/ScottPlot/ScottPlot.NET/pull/12
Thanks @bukkideme 🚀
