### ISSUE TITLE
HLine Dragged Event unexpected behaviour

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2071]
Hi!

I try to use a draggable HLine, but it seems the Dragged event also fires when I just move the mouse over the Plot.
Is this a bug, or I miss something?
Thanks!

```cs
using ScottPlot.Plottable;
using System;
using System.Drawing;
using System.Windows.Forms;

namespace WindowsFormsApp1
{
    public partial class Form1 : Form
    {
        HLine My_hLine;

        public Form1()
        {
            InitializeComponent();
            
        }

        private void Form1_Load(object sender, EventArgs e)
        {            
            My_hLine = formsPlot1.Plot.AddHorizontalLine(0, color: Color.Blue, width: 2);
            My_hLine.DragEnabled = true;
            My_hLine.Dragged += HLine_Dragged;
            formsPlot1.Render();
        }

        private void HLine_Dragged(object sender, EventArgs e)
        {
            MessageBox.Show($"{My_hLine.Y}");
        }
    }
}

```

### System Details
* **ScottPlot Version:** 4.1.57
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** NET Framework 4.8

**Comment by swharden** [comment]
Hi @bukkideme, you were really close! Try this instead

```cs
public partial class Form1 : Form
{
    ScottPlot.Plottable.HLine My_hLine;

    public Form1()
    {
        InitializeComponent();

        My_hLine = formsPlot1.Plot.AddHorizontalLine(0, color: Color.Blue, width: 2);
        My_hLine.DragEnabled = true;
        formsPlot1.PlottableDragged += FormsPlot1_PlottableDragged;
        formsPlot1.PlottableDropped += FormsPlot1_PlottableDropped;
        formsPlot1.Refresh();
    }

    private void FormsPlot1_PlottableDragged(object sender, EventArgs e)
    {
        Text = $"Dragged {My_hLine.Y}";
    }

    private void FormsPlot1_PlottableDropped(object sender, EventArgs e)
    {
        Text = $"Dropped {My_hLine.Y}";
    }
}
```

**Comment by bukkideme** [comment]
Hi @swharden !

So it means, we should not use the Events connected directly for the object, like the VLine or HLine? We can consider such usage as obsolate?

Well, I can get the plottable object via the "sender" parameter when I use the EventHandler PlottableDragged/Dropped, so I am fine with this.
Thanks very much!

**Comment by swharden** [comment]
> So it means, we should not use the Events connected directly for the object, like the VLine or HLine? We can consider such usage as obsolete?

It's technically okay to interact with the plottable's `Dragged` event, but keep in mind that it will fire any time the line is _moved_, and it is unaware when the line is _dropped_.

> Well, I can get the plottable object via the "sender" parameter when I use the EventHandler PlottableDragged/Dropped, so I am fine with this.

Good catch! Yeah, the sender is the item that was dragged or dropped. This is ideal for situations where there are multiple things which could be dragged or dropped 👍
