### ISSUE TITLE
Readme: supported platforms

### ISSUE THREAD

**Issue by rubyFeedback** [ScottPlot/ScottPlot#2088]
Would it be possible to add "supported platforms" or something in the main readme, to indicate whether
this works on linux as well? If it were to work on both windows and linux this would be quite ideal. I could
use gnuplot but I found it to be not hugely user friendly, so I am looking for alternatives. I use linux primarily
though, only my second computer uses Win10 and I am rarely using it usually.

**Comment by swharden** [comment]
Hi @rubyFeedback,

Thanks for pointing this out!

ScottPlot does work on Linux (and MacOS)

However, this information should be more explicitly stated. I'll add a note to the primary readme as you suggest.

Note that Linux and MacOS may require a couple extra setup steps:
* https://scottplot.net/faq/dependencies/
