### ISSUE TITLE
DateTimeTickUnits: The X-axis of `DateTime` mixture 24-hour and 12-hour notation.

### ISSUE THREAD

**Issue by MareMare** [ScottPlot/ScottPlot#2132]
**ScottPlot Version:** 4.1.58.0

**Operating System:** Windows10

**Application Type:** WinForms

**Question:** The X-axis of DateTime mixture 24-hour and 12-hour notation.

Zoom in on a graph displaying `DateTime` data on the X-axis with the mouse wheel or right-click.

~~In this case, the 24-hour and 12-hour displays show different times, depending on whether they zoom to the nearest second or include milliseconds.~~

It appears that 24-hour notation is used for zooms that display up to seconds, and 12-hour notation is used for zooms that also display milliseconds.

Is this as expected?

|pattern|Actual output|comment|
|--|:--:|--|
|(A) Zooms that display up to seconds.|1985/09/23<br>23:59:59| As expected.|
|(B) Zooms that also display milliseconds.|1985/09/23<br>11:59:59.5|The time format expects `23:59:59.5`.|

* In case (A):
  https://github.com/ScottPlot/ScottPlot/blob/07ab190973cbf8697ff8bdc98b4e6475ce40ea03/src/ScottPlot4/ScottPlot/Ticks/DateTimeTickUnits/DateTimeTickUnitBase.cs#L34-L39

* In case (B):
  https://github.com/ScottPlot/ScottPlot/blob/07ab190973cbf8697ff8bdc98b4e6475ce40ea03/src/ScottPlot4/ScottPlot/Ticks/DateTimeTickUnits/SecondsAndLess/DateTimeTickDecisecond.cs#L25-L30

Maybe `HH` is correct in (B) instead of `hh`?

![Animation](https://user-images.githubusercontent.com/807378/191654716-0ee5dd4e-900f-49fa-84c8-f2c204cbcd90.gif)

<details>
<summary>The reproduced code is as follows:</summary>
<div>

```cs
public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        ExecuteRecipe(formsPlot1.Plot);
    }

    private void ExecuteRecipe(Plot plt)
    {
        // original source: https://github.com/ScottPlot/ScottPlot/blob/07ab190973cbf8697ff8bdc98b4e6475ce40ea03/src/ScottPlot4/ScottPlot.Cookbook/Recipes/Axis.cs#L208-L222

        // create data sample data
        var myDates = new DateTime[1000]; // Change: 100 --> 1000
        for (var i = 0; i < myDates.Length; i++)
            myDates[i] = new DateTime(1985, 9, 24).AddMinutes(10 * i); // Change: .AddDays(7 * i) --> .AddMinutes(10 * i)

        // Convert DateTime[] to double[] before plotting
        var xs = myDates.Select(x => x.ToOADate()).ToArray();
        var ys = DataGen.RandomWalk(myDates.Length);
        plt.AddScatter(xs, ys);

        // Then tell the axis to display tick labels using a time format
        plt.XAxis.DateTimeFormat(true);
    }
}
```

</div>
</details>

**Comment by bclehmann** [comment]
Interesting, this is a bug.

Fixing it could be a can of worms however, as using the "long time" here is not guaranteed to be 12 or 24 hour time, depending on locale. This means that regardless of whether we standardize on 12 or 24 hour time, it's a breaking change, although arguably it's broken already. I don't think we can leave it as is so I guess we just have to be clear in patchnotes. https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot/Ticks/DateTimeTickUnits/DateTimeTickUnitBase.cs#L37

Similarly, the format string we use for milliseconds overrides the locale. I think this is necessary, unfortunately, as there isn't a locale-aware way to add milliseconds, your options are the locale's long and short time, there is no "longer" time. Perhaps this is an indication that we should add an escape-hatch for users to specify their own format. This escape hatch may already exist, I'm not as familiar with this code as @swharden.

Time formats are less diverse than date formats (some of which use non-gregorian calendars), but I still think we should allow for different formatting. Especially as 12-hour clocks should have AM/PM in their own language.

**Comment by MareMare** [comment]
Hi @bclehmann, Thank you for your reply.

I thought it was simply a matter of unifying the 24-hour notation, but I see that is not the case...


> Perhaps this is an indication that we should add an escape-hatch for users to specify their own format. 

Perhaps a change is needed to allow user-specific `DateTimeUnitFactory` classes to be specified. (I may be missing the point...)
https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot/Ticks/TickCollection.cs#L251

**Comment by bclehmann** [comment]
I think `DateTimeUnitFactory` could be changed like this:

```cs
public IDateTimeUnit Create(DateTimeUnit kind, CultureInfo culture, int maxTickCount, int? manualSpacing)
{
    switch (kind)
    {
        case DateTimeUnit.ThousandYear:
            return this.CreateTickThousandYear(culture, maxTickCount, manualSpacing);
        case DateTimeUnit.HundredYear:
           .
           .
           .
    }
}
```

Where `CreateTickThousandYear is either a Func<DateTimeTickUnitBase, CultureInfo, int, int?>` that the user sets or a virtual method that the user can override. Then they can pass in their own `DateTimeUnitFactory` instance. I'm leaning towards a virtual method so that users can easily create classes per locale like `FrenchDateTimeUnitFactory`, `GermanDateTimeUnitFactory`, etc etc.

However here the user would still have to override 12 `DateTimeUnit` classes just to change some formatting rules, which seems excessive. Perhaps we have a struct like this that they can pass in:

```
public struct DateTimeFormatStrings 
{
    public readonly string ThousandYear { get; set; }
    public readonly string HundredYear { get; set; }
    public readonly string TenYear { get; set; }
    public readonly string Year { get; set; }
    .
    .
    .
    public readonly string Centisecond { get; set; }
    public readonly string Millisecond { get; set; }
}
```

On the other hand, perhaps I'm overthinking this, it's undeniably an issue to force `en-US` on everyone, but also I can't find anyone reporting any issues around this, whether it's for dates or for numbers: https://github.com/ScottPlot/ScottPlot/issues?q=locale 

So I think for the timebeing I'm just going to create a PR that enforces 24-hour clock, and then at some point we might circle back on letting people write their times differently.

**Comment by bclehmann** [comment]
I actually have a better option, we can check if the configured locale uses 24 hour time and swap out `hh` for `HH`. Otherwise we leave it as is. It's a hack, but it's not as breaking (or broken) a breaking change.

**Comment by MareMare** [comment]
Sorry for the late reply.

> However here the user would still have to override 12 DateTimeUnit classes just to change some formatting rules, which seems excessive.

Yeah, you are right. I was a bit shallow in my thinking.

> So I think for the timebeing I'm just going to create a PR that enforces 24-hour clock, and then at some point we might circle back on letting people write their times differently.

Thank you for creating the PR.
