### ISSUE TITLE
Low quality VLine.PositionLabel

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2136]
**ScottPlot Version:** 4.1.58

**Operating System:** Win10 x64

**Application Type:** Winforms

Hi!

I wonder why the VLine.PositionLabel looks low quality, despite I use `Chart.Configuration.Quality = ScottPlot.Control.QualityMode.LowWhileDragging;` for my Plot? The rest of the plot is high quality.
Thanks!

![image](https://user-images.githubusercontent.com/51174971/192190117-95928f42-415a-4361-b258-5df257dc6bfe.png)

**Comment by swharden** [comment]
Hi @bukkideme, to clarify, is this (the text) what you are saying appears low quality?

![image](https://user-images.githubusercontent.com/4165489/193425856-65d9c8de-5d25-4a46-a236-67025b29faa8.png)

![image](https://user-images.githubusercontent.com/4165489/193425879-88fce02d-5b37-4b17-9b39-e774ca1d789a.png)

This may be a limitation of System.Drawing rendering text. You could try increasing the font size... does that help?

Feel free to open this up again if you think there's still a ScottPlot bug here 👍

**Comment by bukkideme** [comment]
Yes, making the font bigger gave the desired result. Thanks!

![image](https://user-images.githubusercontent.com/51174971/193621324-ad06626b-5967-4215-b027-c1e798485420.png)
