### ISSUE TITLE
Signal: add "smooth" option for low density mode

### ISSUE THREAD

**Issue by xxc-yqxz** [ScottPlot/ScottPlot#2137]
The website says you can add a smooth property to a scatter plot, so how do you set a smooth property to a signal plot?

**Comment by swharden** [comment]
Hi @xxc-yqxz, signal plots currently do not have a smooth option. I'll explore whether this feature is possible to add and update this topic as I learn more 👍

**Comment by swharden** [comment]
If someone wants to challenge this fix (#2010) I would be happy to review it in good time. Here is some information to make it easier:

Scatter plots have a "smooth" option that lets users adjust tension. See cookbook: https://scottplot.net/cookbook/4.1/category/plottable-scatter-plot/#scatter-plot-with-smooth-lines

That functionality was added here:
* https://github.com/ScottPlot/ScottPlot/pull/1878

Similarly, radar plots can be smooth, added here:
* https://github.com/ScottPlot/ScottPlot/issues/2065

The place to add similar logic in the scatter plot class is here:
https://github.com/ScottPlot/ScottPlot/blob/822a3fb2e2e775ef426a79d3da454623aa9a59c8/src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs#L369

It's okay if `FillToInfinity()` is not updated to support smooth lines. That functionality may be added later in a separate PR.

**Comment by rosdyana** [comment]
@swharden Could you please review my PR #2174 , thanks
