### ISSUE TITLE
UI/UX: Improve GitHub Banner

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2142]
## Issue

ScottPlot's banner logo doesn't look good when displayed on GitHub (it's cropped poorly)

## Fix

To fix, start with this SVG ([banner.svg](https://github.com/ScottPlot/ScottPlot.NET/blob/main/static/images/brand/banner.svg)) and make it an image of dimensions `1280×640px` but ensure the icon and text fits inside the region displayed when clipped by GitHub

Save the output SVG and PNG here in `/dev/icon/v5` (use a new unique filename, don't overwrite any existing files)

## Screenshot (current image that looks bad)

As seen on: https://github.com/topics/hacktoberfest2022

![image](https://user-images.githubusercontent.com/4165489/193424696-6c3ad389-7ef1-44f3-a900-336bc9c6211f.png)

## Details

It looks bad because on full-size displays the image gets cropped vertically. Whatever image is created must also look good at 275px high

![image](https://user-images.githubusercontent.com/4165489/193464656-e02b8a49-3e74-43d2-be78-24288c6ba747.png)

**Comment by Anshumansengar** [comment]
Hey @swharden, I would Like to work on it can You assign it to me?

**Comment by mohdimran25** [comment]
Hey @swharden , I am happy to help you on this issue. Assign it to me.

**Comment by swharden** [comment]
Hi @Anshumansengar and @mohdimran25, you can both attempt this and create a pull request. Add your github username to the filenames to ensure they don't conflict. I'm happy to accept/merge both images, and the one I like best I'll select for the GitHub banner

Also note there are contribution ideas on #2010
