### ISSUE TITLE
Plot.AddBarSeries: accept array too

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2146]
presently it only accepts `List<T>` but it would be nice to optionally pass in a traditional array too

https://github.com/ScottPlot/ScottPlot/blob/4008bdf2c569277fcf839a5761d40d5c272b60bb/src/ScottPlot4/ScottPlot/Plot/Plot.Add.cs#L236-L241

spillover from #2145

**Comment by KonH** [comment]
@swharden Hello! Please take a look at PR - https://github.com/ScottPlot/ScottPlot/pull/2160
