### ISSUE TITLE
BarPlot: Tick labels should be displayed below negative bars

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2148]
Presently negative labels are displayed on top of bars

https://scottplot.net/cookbook/4.1/category/plottable-bar-graph/#values-above-bars

![test](https://user-images.githubusercontent.com/4165489/193726363-6eb7d95c-fb5f-48ff-a4d4-182e10c7c3bd.png)

... but it kind of makes sense when the flag is "show values above bars"

The API should extended to allow negative bars to show labels _below_ them

New functionality could be added here:

https://github.com/ScottPlot/ScottPlot/blob/4008bdf2c569277fcf839a5761d40d5c272b60bb/src/ScottPlot4/ScottPlot/Plottable/BarPlot.cs#L83-L87

**Comment by bclehmann** [comment]
Note that after #2152 this applies to `BarSeries` as well
