### ISSUE TITLE
How to set IsVisible for additional axes

### ISSUE THREAD

**Issue by phil100vol** [ScottPlot/ScottPlot#2151]
**Feature Suggestion:**
Setting the visibility of additional axes more than the primary and secondary axes. Right now I can set it by `XAxis.IsVisible` or `XAxis2.IsVisible` (YAxis and YAxis2 vice versa). There is no XAxis3 or above.

**Feature description:**
Setting the IsVisible property with an index of the plots axes.

**Code example:** 
CustomPlot.Plot.SetXAxisIsVisible(int XAxisIndex, bool IsVisible)
CustomPlot.Plot.SetYAxisIsVisible(int YAxisIndex, bool IsVisible)

**Comment by swharden** [comment]
Also, the cookbook recipe https://scottplot.net/cookbook/4.1/category/multi-axis/#additional-y-axis may offer some hints on how to do this.

Briefly:

```cs
var yAxis3 = plt.AddAxis(Renderable.Edge.Left, axisIndex: 2);
yAxis3.IsVisible = true; // save this and modify it later as needed
```

I think this is enough to solve your problem, but if not let me know and we can re-open this issue 👍

**Comment by phil100vol** [comment]
Hi,

saving the new axis was the neeaded hint. Of course now I can make it visible or not

Thank you
