### ISSUE TITLE
Website: document how to disable right-click menu in the pop-up viewer

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2154]
Here is a full console application demonstrating how to disable the default right-click menu in a pop-up plot viewer

```cs
ScottPlot.Plot plt = new ();
plt.AddSignal(ScottPlot.DataGen.Sin(51));
plt.AddSignal(ScottPlot.DataGen.Cos(51));

ScottPlot.FormsPlotViewer viewer = new(plt);
viewer.formsPlot1.RightClicked -= viewer.formsPlot1.DefaultRightClickEvent;
viewer.ShowDialog();
```

(Thanks @shovelbox for asking about this in #2140)

It would be great if we could document this usage on the FAQ page that discusses right-click menus: 

https://scottplot.net/faq/right-click-menu/

Source code for that page is here:

https://github.com/scottplot/scottplot.net/blob/main/content/faq/right-click-menu/index.md

Once a PR is created and merged, the website will update automatically

**Comment by swharden** [comment]
https://scottplot.net/faq/right-click-menu/#console-applications 👍 🚀

**Comment by aspeculat0r** [comment]
Can you demonstrate this for Scottplot 5? I am using winforms Vb.Net. Unable to remove handles for right click

**Comment by vrdriver** [comment]
Hi @aspeculat0r , yes, this is the main reason I'm spending all this time upgrading to version 5.1 and I can't find a way to remove the right click popup options.
