### ISSUE TITLE
FunctionPlot: Optional X Limits

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2156]
Some functions should only be plotted between a range of X values.

Functions which return `null` throw exceptions and make rendering slow.

Public fields should be added so users can restrict function rendering to a range.

```cs
public double XMin = double.NegativeInfinity;
public double XMax = double.PositiveInfinity;
```

Then in the render function those values should be checked and rendering should be restricted to that range.

Presently the render function calculates X/Y pairs for every point from the full visible range of the plot:

https://github.com/ScottPlot/ScottPlot/blob/88bfe26255b22fdc795e1f18c903964eac3592be/src/ScottPlot4/ScottPlot/Plottable/FunctionPlot.cs#L37-L45

This feature may resolve the issue described by @phil100vol in #2138

**Comment by bclehmann** [comment]
I actually think we can implement this without throwing, simply replacing the throws with `continue` should be much faster and it wouldn't impact correctness.
