### ISSUE TITLE
Website documentation: Finance Plot FAQ page

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2164]
It's a pretty common task to plot candlesticks next to volume bars in a way that both move together.

There is a demo application that demonstrates this

https://github.com/ScottPlot/ScottPlot/blob/81735684448d35d0939712e1f5389d4e4e2c3e35/src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/FinanceDemo.cs#L13-L96

![image](https://user-images.githubusercontent.com/4165489/194777135-6dfdd0c3-671d-4c21-ad8c-c351878dd36d.png)

The "Multiple Plots with Share Axes" FAQ page is helpful, but not totally obvious how to use these concepts for good looking finance plots https://scottplot.net/faq/shared-axes/

It would be great if we had a FAQ page demonstrating how to create a finance chart using 2 plots that move together.

To create a new FAQ page, add a subfolder with an index.md file here https://github.com/ScottPlot/ScottPlot.NET/tree/main/content/faq

**Comment by anuragh2002** [comment]
Hey @swharden I would like to work on it. Can you please assign it to me? Also, do I need to create new FAQs or just make a FAQ page [index.md]?

**Comment by swharden** [comment]
Hi @anuragh2002, if you create a PR I will merge it in good time (I don't need to assign the issue to you)

> Also, do I need to create new FAQs or just make a FAQ page [index.md]?

Just create a single file `content/faq/finance/index.md` and mimic the format of the other FAQ pages (e.g., [https://raw.githubusercontent.com/ScottPlot/ScottPlot.NET/main/content/faq/axis/index.md](axes.md)) and that is all that is required to add a new page to the FAQ 👍 

If it's not perfect, that's okay, I can make a few modifications as needed before I merge it

**Comment by anuragh2002** [comment]
Hey @swharden I have created a pull request that will solve this issue, kindly merge it!

**Comment by swharden** [comment]
https://scottplot.net/faq/finance/ 👍
