### ISSUE TITLE
AxisLine: display label on additional axes

### ISSUE THREAD

**Issue by phil100vol** [ScottPlot/ScottPlot#2166]
hey ,

is it possible to show crosshair values (in my case y-value) on multiple axes?

At my wpf plot I got two added axes. The value of the crosshair shall be shown regarding to the axis index. The value are correct but the rendered positions are overlapping:

Current achieve: You can see the orange value behind the red one. 
![image](https://user-images.githubusercontent.com/47931182/194852781-b395679a-8a88-4903-baf3-1320a01002d4.png)

My goal is to place the red value at the red y axis and the orange one at the orange axis
![image](https://user-images.githubusercontent.com/47931182/194853849-47e8c7c7-3b57-44ca-9ec8-652127b5a0ce.png)

Unfortunatly i wast able to find some hint at the cookbook or ather resources.

Thanks 
Phil

**Comment by swharden** [comment]
Hi @phil100vol, sorry for the late reply on this one (#2034)

Does this cookbook example help solve your problem?
https://scottplot.net/cookbook/4.1/category/plottable-crosshair/#crosshairs-on-multiple-axes

**Comment by phil100vol** [comment]
Hi @swharden 

unfortunatly the cookbook doesn't solve the problem. I gave each crosshair unique yaxis index but the orange value is behind the red one.

Also some possibility i can force:
![image](https://user-images.githubusercontent.com/47931182/213448909-32fe438d-71b6-482c-bc07-de423096d936.png)

**Comment by swharden** [comment]
Hi @phil100vol, sorry about the delay here! This issue slipped off my radar for sure. Not having code that allowed me to reproduce this issue was the main reason I put this off, then it eventually got forgotten and burred under a bunch of ScottPlot 5 issues 😅 

## Reproducing

```cs
ScottPlot.Plot plt = new(600, 400);

var hlineA = plt.AddHorizontalLine(3);
hlineA.YAxisIndex = 1;
hlineA.PositionLabel = true;
hlineA.PositionLabelOppositeAxis = true;
hlineA.PositionLabelBackground = hlineA.Color;

var hlineB = plt.AddHorizontalLine(7);
hlineB.YAxisIndex = 2;
hlineB.PositionLabel = true;
hlineB.PositionLabelOppositeAxis = true;
hlineB.PositionLabelBackground = hlineB.Color;

plt.YAxis2.Ticks(true);
plt.AddAxis(ScottPlot.Renderable.Edge.Right);
plt.SetAxisLimits(yMin: -10, yMax: 10, yAxisIndex: 1);
plt.SetAxisLimits(yMin: -10, yMax: 10, yAxisIndex: 2);
plt.SaveFig("test.png");
```

![image](https://user-images.githubusercontent.com/4165489/228704120-35cb92af-7096-4a1e-a2f1-7fdaeb2a6968.png)

**Comment by swharden** [comment]
After looking at it closer, this is possible with the existing code:

```cs
ScottPlot.Plot plt = new(600, 400);

var hlineA = plt.AddHorizontalLine(3);
hlineA.YAxisIndex = 1;
hlineA.PositionLabel = true;
hlineA.PositionLabelOppositeAxis = true;
hlineA.PositionLabelBackground = hlineA.Color;

var hlineB = plt.AddHorizontalLine(7);
hlineB.YAxisIndex = 2;
hlineB.PositionLabel = true;
hlineB.PositionLabelOppositeAxis = true;
hlineB.PositionLabelBackground = hlineB.Color;

plt.YAxis2.Ticks(true);
var yAxis2 = plt.XAxis2;
var yAxis3 = plt.AddAxis(ScottPlot.Renderable.Edge.Right);
plt.SetAxisLimits(yMin: -10, yMax: 10, yAxisIndex: 1);
plt.SetAxisLimits(yMin: -10, yMax: 10, yAxisIndex: 2);

// this tells the lines which axes to draw the labels on
hlineA.PositionLabelAxis = yAxis2;
hlineB.PositionLabelAxis = yAxis3;
```

![image](https://user-images.githubusercontent.com/4165489/228705141-4e9e6659-93e1-4589-a50b-b07777d8c33d.png)
