### ISSUE TITLE
Incorrect marker shape displayed in legend

### ISSUE THREAD

**Issue by szescxz** [ScottPlot/ScottPlot#2172]
## Bug Report

**Issue:**
Incorrect marker shape displayed in legend when using `SignalXYConst`. All plottables are displayed as `filledCircle`.
![scatter_markerShape](https://user-images.githubusercontent.com/49463229/194979462-1cd130d0-39d8-41fe-89a6-bbdb0bb49de6.png)

**Reproducing:**
Simply replace `AddScatter` with `AddSignalXYConst` in [this cookbook example](https://scottplot.net/cookbook/4.1/category/plottable-scatter-plot/#all-marker-shapes):

```cs
var plt = new ScottPlot.Plot(600, 400);

int pointCount = 51;
double[] xs = DataGen.Consecutive(pointCount);

string[] markerShapeNames = Enum.GetNames(typeof(MarkerShape));
for (int i = 0; i < markerShapeNames.Length; i++)
{
    Enum.TryParse(markerShapeNames[i], out MarkerShape ms);
    double[] ys = DataGen.Sin(pointCount, 2, -i);
    var sp = plt.AddSignalXYConst(xs, ys); // <- replace this line
    sp.LineWidth = 2;
    sp.LineColor = Color.FromArgb(50, sp.LineColor);
    sp.MarkerSize = 7;
    sp.MarkerShape = ms;
    sp.Label = ms.ToString();
}

plt.Grid(enable: false);
var legend = plt.Legend();
legend.FontSize = 10;

plt.SaveFig("scatter_markerShape.png");
```

### System Details
* **ScottPlot Version:** 4.1.58
* **Operating System:** Windows 11
* **Application Type:** WinForms
* **.NET Version:** NET Framework 4.8

**Comment by bclehmann** [comment]
Thanks for reporting this, it looks like it affects all signal plots (i.e. `Signal`, `SignalXY`, and their const variants).

**Comment by szescxz** [comment]
> Thanks for reporting this, it looks like it affects all signal plots (i.e. `Signal`, `SignalXY`, and their const variants).

Seems like it, also appreciate for your quick PR.
But why only `ScatterPlot` is unaffected? I'm a little bit worried that there are probably more places worth to look at.

**Comment by bclehmann** [comment]
I looked through all the plottables, and I didn't find any other problems.

All the signal plots were impacted because they all share a base class which had the incorrect behaviour. The other plottables either don't have markers in their legend entries, or they have the correct marker shape in their legend entries.
