### ISSUE TITLE
Normal distribution: generation algorithm

### ISSUE THREAD

**Issue by arthurits** [ScottPlot/ScottPlot#2189]
I've been using functions `RandomNormal` from `DataGen.cs` and `Population` from `Population.cs` in order to visualize the distribution of a given variable
https://github.com/ScottPlot/ScottPlot/blob/0be0921e508656e19323642974a8c5d441bc686a/src/ScottPlot4/ScottPlot/Statistics/Population.cs#L40-L44

I'm no expert whatsoever in statistical algorithms, but it seems that both functions make use of `RandomNormalValue` where some kind of Box-Muller algorithm is implemented to generate gaussian numbers:

https://github.com/ScottPlot/ScottPlot/blob/0be0921e508656e19323642974a8c5d441bc686a/src/ScottPlot4/ScottPlot/DataGen.cs#L195-L200

However, the gaussian data generated seems to be sistematically underestimated as shown below, where the grey vertical line represents the mean and the bell curve appears to be slightly offsetted to the left.
![image](https://user-images.githubusercontent.com/63915486/197342246-e8dea69c-9597-475d-ac22-f2da03238428.png)

There's an [article in Wikipedia](https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform#Basic_form) where the Box-Mueller algorithm is explained. It states that 
_Suppose U1 and U2 are independent samples chosen from the uniform distribution on the unit interval (0, 1)._

Since `Random.NextDouble()` does in fact return the value 0, the current computation of both `u1` and `u2` will eventually return some 1s.

Therefore, I've been using the following modification of `RandomNormalValue`:

```cs
public double SampleGaussian(Random random, double mean, double stdDev)
    {
        double u1 = NextDouble(random);
        double u2 = NextDouble(random);

        double y1 = Math.Sqrt(-2.0 * Math.Log(u1)) * Math.Sin(2.0 * Math.PI * u2);    // Math.Cos is also fine
        return mean + stdDev * y1;

        double NextDouble(Random random)
        {
            return ((double)random.Next(1, Int32.MaxValue)) / Int32.MaxValue;    // random.Next includes 1 and exludes Int32MaxValue
        }
    }
```
This modification provides a more visually mean-centered gaussian curve:
![image](https://user-images.githubusercontent.com/63915486/197345539-21483fe2-499e-4fb9-89ad-5b7da2fb174b.png)

**Comment by bclehmann** [comment]
I wonder if we should be using `Double.MaxValue`? It may have worse performance because it'll return a subnormal, and we might well just end up getting it rounded to zero, but `Int32.MaxValue` is really rather small as far as doubles are concerned.

It might need some experimentation to see quite how large we can go without getting floating pointed, it may be quite a ways under Double.MaxValue.

**Comment by arthurits** [comment]
> I wonder if we should be using `Double.MaxValue`?

I believe the problem could be that there is no Random method returning values between 1 and `Double.MaxValue`.
How about using `Int64.MaxValue` instead along with a call to `Random.NextInt64`?

**Comment by bclehmann** [comment]
I'd value your feedback on #2206, it's simpler and seems to be faster, but I'd like some reassurance that it gives the results you think it should.

It looks like it should be correct to me, but I'd appreciate another set of eyes.

**Comment by arthurits** [comment]
Sure!
It looks great and straightforward. I left a minor observation in #2206 for your consideration.

**Comment by bclehmann** [comment]
> I left a minor observation in https://github.com/ScottPlot/ScottPlot/pull/2206 for your consideration.

Hey I can't see anything, did it maybe fail to send?

**Comment by swharden** [comment]
> I left a minor observation in https://github.com/ScottPlot/ScottPlot/pull/2206 for your consideration.

> Hey I can't see anything, did it maybe fail to send?

Thanks again for everyone's input on this! I think it's in an okay state and merged it, but if there was an unresolved concern/idea we can open it up in a new PR 👍

**Comment by arthurits** [comment]
> Hey I can't see anything, did it maybe fail to send?

I'm not sure what happened but I probably messed it, although I can see it:
![image](https://user-images.githubusercontent.com/63915486/198948774-11d9152c-f4ed-48e5-a146-cb4db197f358.png)

The point was that there is no need for this:
```cs
return 1.0 - subtrahend;
```

since `subtrahend` already returns values in the open interval (0, 1). So, it would be even more straightforward to simply return `subtrahend`:

```cs
return subtrahend;
```

**Comment by bclehmann** [comment]
Ah, since it says "Pending" it means it was part of a review, and it looks like you didn't complete the review (there's a menu with "Approve", "Request Changes", and "Reject" that you have to click on). Alternatively, you can leave a comment without starting a review, and then the comment will be applied immediately.

At any rate thank you for noticing that, I guess I was a little bit on autopilot :/

**Comment by arthurits** [comment]
My bad @bclehmann! I totally messed the whole comments/review options. I'll pay more attention the next time.
Anyways, it's good to see that @swharden already merged it.
