### ISSUE TITLE
Cookbook: Signal plot with date axis

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2196]
How to enable a DateTime axis is demonstrated with scatter plots https://scottplot.net/cookbook/4.1/category/axis-and-ticks/#plotting-datetime-data

A similar cookbook recipe should be added to demonstrate this for signal plots.

(idea came from #2192)

**Comment by zachesposito** [comment]
Hello happy Hacktoberfest! I can take care of this

**Comment by swharden** [comment]
@zachesposito sure thing! I'll keep an eye out for a PR and am prepared to move quickly if it looks good! Let us know if you hit any snags along the way and we can help out. We are on Discord too https://scottplot.net/discord/
