### ISSUE TITLE
Dynamic scatterline (SMA, Bollinger) issue

### ISSUE THREAD

**Issue by xenedia** [ScottPlot/ScottPlot#2199]
Hi,

I used the scottplot on my own project. there was dynamic candlestick and SMA lines. dynamic candlesticks working good but SMA lines does not calculated and showed as expected.  SMA lines working good on first load but when the new candlesticks was added SMA graphics are incorrect like below. I couldn't find a solution to fix this SMA or Bollinger graphics. could this be an issue or  am i doing something wrong?

```
//definition
private List <OHLC> grafik;
private FinancePlot mcp;
private ScatterPlot scp20;


// first load
mcp = formsPlot1.Plot.AddCandlesticks(grafik.ToArray());
var (xs, ys) = mcp.GetSMA(20);
scp20 = formsPlot1.Plot.AddScatterLines(xs, ys, Color.LightCoral, 1);

// timer
grafik.Add(ohlc);
if (scp20 != null) formsPlot1.Plot.Remove(scp20);
var (xs, ys) = mcp.GetSMA(20);
scp20 = formsPlot1.Plot.AddScatterLines(xs, ys, Color.LightCoral, 1);
formsPlot1.Refresh();
```

<img width="566" alt="image" src="https://user-images.githubusercontent.com/373347/198233776-2dab7cd5-4343-47f0-b494-e391aff4d13d.png">

### System Details
* **ScottPlot Version:** 4.1.58
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:**  .NET 6.0

**Comment by bclehmann** [comment]
It looks like both times you calculate the SMA you're using the same candlestick:
```cs
var (xs, ys) = mcp.GetSMA(20);
```

But you don't actually mutate `mcp`, at least not in the code I can see, noting that calling `grafik.ToArray()` will create a copy, so `mcp` won't see the changes you made to `grafik`.

I will note that the `GetSMA` function assumes the coordinates in `FinancePlot.OHLCs` are sorted, so if they're not in strictly ascending order you could have the SMA graph change directions like it appears to here, as well as calculate incorrect Y values. It appears that we don't ever indicate or enforce that unsorted OHLCs are invalid, so this looks like something we should fix.
