### ISSUE TITLE
Ticks: Improve tick label rotation and alignment options

### ISSUE THREAD

**Issue by Terebi42** [ScottPlot/ScottPlot#2202]
The tick rotation takes a value in degrees. "45" rotates the label to read from the lower left to the upper right.   I would like to read from the top left to the lower right, because long labels get cut off the edge of the graph, and the most important elements in my graph are on the far left. (so if labels on the far right are cut off, thats the better choice)

![image](https://user-images.githubusercontent.com/11640679/198733798-40d0ce8a-75ee-462f-acae-cdf8f2bc6642.png)

You can set a negative degree value, which rotates correctly, but uses the end of the label as the "anchor", so the label ends up under the bars.  

![image](https://user-images.githubusercontent.com/11640679/198733916-09814006-0d3e-4787-8b18-5285abb16f21.png)

If the rotation is negative, the label location should be offset by the length of the label. (or rotate using the start of the label instead of the tail)

**Comment by swharden** [comment]
Hi @Terebi42, this issue has been setting here for a long time and is unlikely to get significant attention soon so I'm going to close it now. Tick customization support will be improved and simplified in ScottPlot 5, so I'm going to focus my upcoming effort there

If you or someone else wants to improve rotated tick label styling in ScottPlot 4, this is the region of the code where a flag could be added to change the behavior. Be warned though, this is one of the most complex (poorly written) functions to work in, and modifications require testing functionality on all 4 axes

https://github.com/ScottPlot/ScottPlot/blob/63bb3e82e9aa13c2881e6d3aea1db8fb8b30cd74/src/ScottPlot4/ScottPlot/Renderable/AxisTicksRender.cs#L78-L210
