### ISSUE TITLE
ScottPlot4 Legend: ability to get bitmap with outline and shadow

### ISSUE THREAD

**Issue by DmitryZhelnin** [ScottPlot/ScottPlot#2212]
## Feature Suggestion

**Feature description:** Add new method or modify the old one to get full bitmap of a `Legend`. Current implementation of `Legend.GetBitmap(bool lowQuality = false, double scale = 1.0)` returns bitmap with cropped outline and without a shadow.

![изображение](https://user-images.githubusercontent.com/4993430/199276607-dc5a6cbd-68e0-4e5a-83a7-985437ab30fc.png)

I've tried to modify this lines of code

https://github.com/ScottPlot/ScottPlot/blob/c48e9b9cd2ff24b40664c7c6e6fcef93b4cc025c/src/ScottPlot4/ScottPlot/Renderable/Legend.cs#L86-L87

to include shadow offset

```cs
int width = (int)Math.Ceiling(totalLabelWidth * scale + ShadowOffsetX);
int height = (int)Math.Ceiling(totalLabelHeight * scale + ShadowOffsetY);
```

With this modifications the result bitmap is

![изображение](https://user-images.githubusercontent.com/4993430/199278005-7127d18e-9049-4462-b146-ae6c777fafde.png)

## Motivation
I've been trying to implement popup with current values under mouse cursor. The idea is to use `Legend` object that does not belong to the plot, render this object to bitmap and show under the mouse pointer. With listed modifications I was able to get this result

![popup](https://user-images.githubusercontent.com/4993430/199280772-5a45840b-10a9-4bff-98d4-e9deecf58340.gif)

## Workaround
As a workaround I can create my own extension method for the `Legend` object, copy all the source code for bitmap generation and make listed modifications.

**Comment by bclehmann** [comment]
`Legend.RenderOnBitmap` has arguments `shadow` and `outline`, which I presume do what they do on the tin, but they're not actually exposed anywhere. This may just be a simple tweak for us.

**Comment by DmitryZhelnin** [comment]
Yes, but this arguments should be taken into account earlier, when the size of bitmap is calculated.

**Comment by swharden** [comment]
Hi @DmitryZhelnin, thanks for offering this suggestion! Sorry for my late reply (#2304)

Considering the push to finish ScottPlot 5 and the relatively niche use case described here, I'll probably not be focusing personally on implementing this feature (although I recognize its value for your application). If you solve this in an elegant way and want to create a PR to share your work with others I would be happy to review it!

I'm really amused to see the screenshot here. I never would have thought to move the legend around like this. What a cool effect! Totally unexpected use of GetLegendBitmap(), but it looks great 🚀

**Comment by swharden** [comment]
> returns bitmap with cropped outline and without a shadow

Also to justify this a bit, I think the most common use case is that people get the legend bitmap with the goal of placing it outside the plot area (perhaps elsewhere in the window in a different control). 

This is why border and shadow is not included (or accounted for in sizing) by default.

At least that was the "common use case" I had in mind while making it. As your animated screenshot shows, _actual_ use cases in the wild don't always match predictions!
