### ISSUE TITLE
Rendering issue with SignalPlotXYConst 

### ISSUE THREAD

**Issue by damien-ls** [ScottPlot/ScottPlot#2222]
## Bug Report

**Issue:** 

SignalPlotXYConst will draw vertical lines to "0" as the displayed data density is increased (perhaps more than 1 point per pixel?), even if there are no 0 values in the dataset. 

It is particularly obvious when zooming in or out, but will also appear without zooming.

SignalPlotXY does not seem to have this behavior.

Link to video: https://we.tl/t-DcuO4fKvjh

**Reproducing:** (What do others have to do to reproduce the bug?)

```cs

            Chart.Configuration.AllowDroppedFramesWhileDragging = true;
            Chart.Configuration.LeftClickDragPan = true;
            Chart.Configuration.Quality = ScottPlot.Control.QualityMode.Low;


            plot = Chart.Plot;

            plot.Style(figureBackground: System.Drawing.Color.Transparent);
            plot.Style(dataBackground: System.Drawing.Color.Transparent);


            plot.XAxis.Label("Time [seconds]");
            plot.YAxis.Label("Temperature [°C]");
            plot.SetAxisLimits(xMin: 0);


                serie = new MySerie();
                serie.signalPlotXY = plot.AddSignalXYConst(serie.XData, serie.YData, color);
                serie.signalPlotXY.StepDisplay = false;
                serie.signalPlotXY.MaxRenderIndex = 0;
                serie.signalPlotXY.MarkerShape = MarkerShape.none;


// Adding points:
            serie.signalPlotXY.MaxRenderIndex = serie.CurrentPosition;
            serie.XData[serie.CurrentPosition] = ((TimeSpan)(DateTime.Now - StartTime)).TotalSeconds;
            serie.YData[serie.CurrentPosition] = value;
            serie.CurrentPosition++;



             Chart.RefreshRequest();
```

### System Details
* **ScottPlot Version:** 4.1.58.0
* **Operating System:** (Windows 10)
* **Application Type:** (WPF)
* **.NET Version:** (NET Framework 4.8)

**Comment by bclehmann** [comment]
```cs
serie.XData[serie.CurrentPosition] = ((TimeSpan)(DateTime.Now - StartTime)).TotalSeconds;
serie.YData[serie.CurrentPosition] = value;
```

You're not allowed to mutate the data in a `SignalPlotXYConst`, it has to stay the same as it was when you called the constructor. This is obviously less flexible than the regular `SignalPlotXY`, but it allows some performance improvements.

**Comment by swharden** [comment]
> You're not allowed to mutate the data in a SignalPlotXYConst

Actually, I think `SignalPlotXYConst` has some functions you can call to mutate the data, but you have to mutate the data using the various `Update()` functions (not by editing the values in the array directly)

e.g.,

```cs
serie.Update(serie.CurrentPosition, value);
```

I think this information solves this problem. If not, feel free to re-open this issue! 👍

**Comment by damien-ls** [comment]
Thanks for the update, perhaps it would be helpful to indicate it on the doc as it is not very clear.

**Comment by swharden** [comment]
> Thanks for the update, perhaps it would be helpful to indicate it on the doc as it is not very clear.

Good suggestion! I created #2240 to track progress improving this documentation 👍
