### ISSUE TITLE
Polar Heatmap: new plot type?

### ISSUE THREAD

**Issue by xichaoqiang** [ScottPlot/ScottPlot#2229]
@swharden 

Dear Sir

Is there any way to plot heatmap in polar coordinates?

Like figure shown below.
![image](https://user-images.githubusercontent.com/30900789/200165278-68c7c731-bfdf-4ea0-959d-7ef8b345868e.png)

Best regards,
Xi

**Comment by bclehmann** [comment]
We don't have much support for polar axes, but we do have a utility function (demonstrated [here](https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#polar-coordinates)) for converting to cartesian coordinates, which should work with any of our plots.

You can then turn those cartesian coordinates into `double[,]` arrays that heatmaps can use, assuming your data is individual points that you want to aggregate into the intensity of a region. We have two options for this:
- Density-based: https://scottplot.net/cookbook/4.1/category/plottable-heatmap/#interpolation-by-density
- Gaussian: https://scottplot.net/cookbook/4.1/category/plottable-heatmap/#gaussian-interpolation

Lastly, if you want to constrain the heatmap to a circle, you have two options:
- Empty squares: https://scottplot.net/cookbook/4.1/category/plottable-heatmap/#heatmap-with-empty-squares
- Clipping to a polygon: https://scottplot.net/cookbook/4.1/category/plottable-heatmap/#heatmap-clipping

**Comment by swharden** [comment]
Thinking out loud, the circular axis ticks here seem like a special case... I wonder if a circular heatmap could merit its own plot type?

Maybe the logic for drawing those circular axes could be reused as well 🤔
