### ISSUE TITLE
How can I use a button instead of the wheel to zoom?

### ISSUE THREAD

**Issue by mYcheng-95** [ScottPlot/ScottPlot#2235]
I want to use the button / keyboard to control zooming, for example: when I click button A / key A, the graph enlarges; when I click button B / button B, the graph zooms out. Is there a way to do this?

**Comment by swharden** [comment]
Hi @mYcheng-95 

> when I click button A the graph enlarges

In your button's OnClicked handler add something like:

```cs
formsPlot1.Plot.AxisZoom(1.5, 1.5); // zoom in
formsPlot1.Refresh(); // redraw the plot
```

> when I press key A the graph enlarges

Add a function to catch keypresses and if the key is `A` run the same code as above

I hope this helps!

An advanced answer is to create your own user control and copy/paste ScottPlot's control code into it and modify it as needed. [FormsPlot.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs)
