### ISSUE TITLE
How to format small numbers on Y axis?

### ISSUE THREAD

**Issue by acidos** [ScottPlot/ScottPlot#2249]
**ScottPlot Version:** 4.1

**Operating System:** Win10

**Application Type:** WinForms

Hi, my signal plot's data consisting of very small values:
```
-1.219278671525E-08
-1.904506266977E-08
-1.795656488308E-08
-1.808794826859E-08
-1.312815987203E-08
-1.203966208533E-05
-9.728229606593E-09
-1.245663160779E-08
-6.635178084107E-09
-1.318047987319E-08
-1.688095082787E-08
-1.650144217677E-08
-1.531465922054E-08
-2.05826354956E-08
-2.474275660723E-08
-3.815847801452E-08
```

Y axis is unable to show ticks with this precision by default. I've tried to play with TickLabelNotation without much success. Exp is going up, but the main part of the number is losing precision.
How can I display on Y axis ticks with x.yyyyyyyyyyyy precision and exp on top?

**Comment by swharden** [comment]
Hi @acidos, 

Can you provide a picture to demonstrate the issue or a code sample to help somebody else reproduce the issue?

Do you think this issue related to floating point math errors, or actual formatting issues? This is where a picture/reproducibility would help

Looking forward to learning more!
Scott

**Comment by swharden** [comment]
> a picture/reproducibility would help

This can move the conversation forward

```cs
double[] values =
{
    -1.219278671525E-08,
    -1.904506266977E-08,
    -1.795656488308E-08,
    -1.808794826859E-08,
    -1.312815987203E-08,
    -1.203966208533E-05,
    -9.728229606593E-09,
    -1.245663160779E-08,
    -6.635178084107E-09,
    -1.318047987319E-08,
    -1.688095082787E-08,
    -1.650144217677E-08,
    -1.531465922054E-08,
    -2.05826354956E-08,
    -2.474275660723E-08,
    -3.815847801452E-08,
};

ScottPlot.Plot plt = new();
plt.AddSignal(values);
plt.SaveFig("demo.png");
```

![demo](https://user-images.githubusercontent.com/4165489/200964655-a67c6c70-aa1a-4500-939b-e4699be949c8.png)

It sounds like you're not a fan of the short exponential notation, so here's how to insert your own custom tick mark formatter that converts the `double` to `string` however you like.

```cs
ScottPlot.Plot plt = new();
plt.AddSignal(values);
Func<double, string> formatter = (y) => y.ToString("0:0.0000000");
plt.YAxis.TickLabelFormat(formatter);
plt.SaveFig("demo.png");
```

![demo](https://user-images.githubusercontent.com/4165489/200965813-14c72368-d51f-4e20-b2f0-b988041d65b2.png)

Re-open the issue if this doesn't do the trick, but I think it should help you reach a solution!

**Comment by acidos** [comment]
Hi Scott,
This is the code:
```
scottPlot.Plot.Clear();
            SignalPlot = scottPlot.Plot.AddSignal(data);
            scottPlot.Plot.Title("FDI2056 Integration Result");
            scottPlot.Plot.XLabel("Samples");
            scottPlot.Plot.YLabel(yAxisLabel);
            scottPlot.Plot.YAxis.TickLabelNotation(multiplier: true, offset: true, exponential: true);
            scottPlot.Refresh();
```
<img width="793" alt="image" src="https://user-images.githubusercontent.com/298480/200964626-811fc787-6ce5-4f32-aa44-b59c8fcc3e2a.png">

<img width="793" alt="image" src="https://user-images.githubusercontent.com/298480/200964769-a51851bc-930b-468a-9d5c-9f3f22a7574b.png">

First few points have the values:
```
8.875068776486E-09
2.370440579959E-08
3.876943638459E-08
5.259969988821E-08
6.858059557731E-08
8.836522275004E-08
```
<img width="799" alt="image" src="https://user-images.githubusercontent.com/298480/200965197-cdf64282-3c9b-4255-b462-bb78170bac0e.png">

So I would expect to see Y ticks with greater precision as I zoom in. If I zoom in much, I see that the 
- line changed direction
- floating point errors appeared
- one more zoom level and the line is gone from the view

<img width="799" alt="image" src="https://user-images.githubusercontent.com/298480/200965722-239f03b6-304a-4c98-ac7e-7387c35ef13e.png">

I think this is more formatting issue.

**Comment by swharden** [comment]
> So I would expect to see Y ticks with greater precision as I zoom in. If I zoom in much, I see that the
> * line changed direction
> * floating point errors appeared
> * one more zoom level and the line is gone from the view

Indeed, you correctly identified this as a floating point math issue! The data values are so close together that the math converting them from coordinate space to pixel space is getting drowned in floating point math errors.

A good solution is to scale your input data as much as possible (e.g., by 10<sup>9</sup>) then use the custom tick formatter method described in my previous comment to translate that large number into a small number so the label is correct.

Unfortunately I can't offer a better solution because the rendering system (System.Drawing/GDI) uses fixed precision floating point math, so we will always be fighting that limitation. 

Let me know if that doesn't do the trick!
