### ISSUE TITLE
Palette: need a set of light colors

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2266]
Looking over our colors https://scottplot.net/cookbook/4.1/colors/ there doesn't seem to be a pastel palette suitable for placing black text on top of filled areas

**Comment by arthurits** [comment]
Hi @swharden,

Here are two very light 9-color palettes I've just created ([Light palettes for ScottPlot.zip](https://github.com/ScottPlot/ScottPlot/files/10054819/Light.palettes.for.ScottPlot.zip)) in case they fit what you are looking for.

* "Pale spectrum" ("Light spectrum", "Pale rainbow" or "Light rainbow")
![imagen](https://user-images.githubusercontent.com/63915486/202994818-ded80c88-7f4a-4d60-9f38-705817f14189.png)
#fce5e6 #fff8e7 #fffce8 #eff5e4 #e7f2e6 #ddf0f5 #e6f2fc #e6eaf7 #eee0f0

* "Light ocean"
![imagen](https://user-images.githubusercontent.com/63915486/203003455-4fbce8d5-4428-4bfe-b321-302bd0f9ebd4.png)
#dfedd9 #dbecdc #dbede4 #daeeec #daeef3 #dae6f2 #dadef1 #dedaee #e5daed


Although I'd say there's no copyright (I'm not 100% sure), other light palettes you can find online are:
[Soft light](https://www.schemecolor.com/soft-light.php)
![imagen](https://user-images.githubusercontent.com/63915486/202997585-a4ff2288-a33b-4812-8a8b-6f8754df0cc1.png)
#FFFAE6 #F9ECD9 #F7E3CC #F7CEE2 #CCCAF0 #CFDFEF

[Light earthy palette](https://www.schemecolor.com/beautiful-light-colors.php)
![imagen](https://user-images.githubusercontent.com/63915486/202997889-ca2b5f8b-8eab-4e88-803b-578b9f20c5ad.png)
#ACDDDE #CAF1DE #E1F8DC #FEF8DD #FFE7C7 #F7D8BA

[Light and pale](https://www.schemecolor.com/light-and-pale.php)
![imagen](https://user-images.githubusercontent.com/63915486/202998436-4881fd8f-0ac9-4b9d-a247-b570fef33281.png)
#CBE4F9 #CDF5F6 #EFF9DA #F9EBDF #F9D8D6 #D6CDEA

[Pale and pale](https://www.schemecolor.com/pale-and-pale.php)
![imagen](https://user-images.githubusercontent.com/63915486/202998611-01ee916f-f89c-4a0f-ace1-9db2c21eb89b.png)
#C4E8DF #D8F6D6 #EEFBDD #FFFFE6 #FFEEDD #FFE4DD

[Pale earth](https://www.twitter.com/ColorsPalettes/status/859467535682613249)
![imagen](https://user-images.githubusercontent.com/63915486/202996854-b75603c3-d9ff-4e07-9a67-0c5dd36e43c5.png)
#ddbc9d #e3c3a8 #e8cab3 #edd1bf #f2d8ca #f6dfd6 #f9e7e1 #fcefec

[Pastel green](https://twitter.com/ColorsPalettes/status/861694715992961024?cxt=HHwWgMC7ueuxrfUXAAAA)
![imagen](https://user-images.githubusercontent.com/63915486/202996193-ade587c4-82fe-4c8c-8dbd-0d380984f882.png)
#c2c2c2 #c8c9c4 #cfd0c7 #d6d7cb #dfdecf #e8e4d5 #f1eade #f9f1e9

**Comment by swharden** [comment]
Resolved by #2271, #2272, #2273
