### ISSUE TITLE
Broken visual then Collapse/Visible Plot

### ISSUE THREAD

**Issue by Worldmasters** [ScottPlot/ScottPlot#2269]
I found a strange bug. There is a control that displays a graph. If I run the program and change the graphics with the mouse wheel, then everything is fine. But if I do a Collapse for the graph to hide and then Visible, then the graph freezes and completely ignores the axes change. What could it be?

In the code, I just change the display and fill in two lines so that one of the two graphs can be shown.

```cs
LeftRightPlot.Visibility = Visibility.Hidden;
UpDownPlot.Visibility = Visibility.Visible;

UpDownPlot.SetValue(Grid.RowSpanProperty, 2);
UpDownPlot.SetValue(Grid.RowProperty, 0);
```

![image](https://user-images.githubusercontent.com/54429272/203927119-ba6074ff-fbe9-49b2-bd1f-2a26906d2b55.png)

**Comment by swharden** [comment]
Hi @Worldmasters, thank you for reporting this!

Unfortunately I cannot reproduce the issue you describe. This code works for me

```cs
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        WpfPlot1.Plot.AddSignal(ScottPlot.DataGen.Sin(51));
        WpfPlot1.Plot.AddSignal(ScottPlot.DataGen.Cos(51));

        WpfPlot1.Visibility = Visibility.Hidden;
        WpfPlot1.Visibility = Visibility.Visible;

        WpfPlot1.SetValue(Grid.RowSpanProperty, 2);
        WpfPlot1.SetValue(Grid.RowProperty, 0);

        WpfPlot1.Refresh();
    }
}
```

If you can provide the C# and XAML necessary to allow me to recreate this issue, I would be happy to take a closer look 👍
