### ISSUE TITLE
Signal: Rolling Plot

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2279]
A common use case of charting libraries is to show a strip chart where a live incoming signal scrolls in along a fixed-width signal

For an example, see the super basic [Arduino serial plotter](https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-serial-plotter) app

* It's not efficient to do this with the existing Signal plot because copying all that data in fixed-length arrays is slow
* It's not feasible using lists because it is likely items will be removed _during_ renders causing indexing errors
* It is possible to do with huge arrays and moving min/max render index, but this is inconvenient
* A new type of signal plot that uses a rolling buffer (with an integer to keep track of the rollover index) is probably the best solution

![](https://docs.arduino.cc/14cb1a81430656c7ae945f10c0f4e32c/random_plotter.gif)

Note: I'll experiment by working in https://github.com/swharden/SeriPlot

**Comment by greatawesome** [comment]
This is where ZedGraph's RollingPointPairList was handy, along with their generic IPointList interface for providing points to the graph using whatever data structure the user wanted.

**Comment by swharden** [comment]
This is related enough to #2377 that I'll close this and follow-up there
