### ISSUE TITLE
Too big gaps in non-minute candles chart

### ISSUE THREAD

**Issue by pavlexander** [ScottPlot/ScottPlot#2281]
## Bug Report

**Issue:** When drawing non-minute candlestick charts - the gap in between candles is too big

**Reproducing:**

```cs
target.Plot.AddCandlesticks(candles);
target.Plot.XAxis.DateTimeFormat(true);
```

### System Details
* **ScottPlot Version:** 4.1.59
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** .NET 5.0

## Examples

When 1 minute chart is drawn candles look like this:

![image](https://user-images.githubusercontent.com/20644772/205623189-fb63c71a-531a-42e5-9734-75577fd8b445.png)

When you draw a 1 hour chart **(candles are evenly distributed 60 minutes apart)**, the graph looks like this:

![image](https://user-images.githubusercontent.com/20644772/205624046-501fbee1-0946-42ad-958b-3f2ec07c94da.png)

and if zoomed

![image](https://user-images.githubusercontent.com/20644772/205623415-30d0b4a4-a005-47a3-875e-be537c6b3df0.png)

![image](https://user-images.githubusercontent.com/20644772/205624121-865f6ca0-ed4b-47e0-b69a-51908600752e.png)

I think it makes no sense to display such huge space gaps in between hourly candles.. It makes the graph impossible to use, unless zoomed in. (Actually, even if you zoom it-in it is still hard to use it because candles are too far apart)

**Comment by Xerxes004** [comment]
I haven't tried this myself, but can you set the minimum spacing to be 1 hr and see if that helps?

**Comment by pavlexander** [comment]
@Xerxes004 it says that date-time ticks are not supported

![image](https://user-images.githubusercontent.com/20644772/207077266-9fa400b3-d1eb-4155-9dbb-fa8a1494e05f.png)

**Comment by Xerxes004** [comment]
Ah, makes sense. You may need to set your own labels using ManualTickSpacing for now.

**Comment by swharden** [comment]
Hi @pavlexander and the group, I'm just now getting to this - sorry for the delay (#2304)

Your only contains two lines of code and is not enough for me to reproduce the issue you describe. 

If I write code like this, it looks good

```cs
public Form1()
{
    InitializeComponent();

    DateTime candleStart = new(2023, 1, 1);
    TimeSpan candleWidth = TimeSpan.FromHours(1);

    List<OHLC> candles = new();
    for (int i = 0; i < 20; i++)
    {
        OHLC ohlc = new(10, 15, 5, 12, candleStart, candleWidth);
        candles.Add(ohlc);
        candleStart += candleWidth;
    }

    formsPlot1.Plot.AddCandlesticks(candles.ToArray());
    formsPlot1.Plot.XAxis.DateTimeFormat(true);

    formsPlot1.Refresh();
}
```

![image](https://user-images.githubusercontent.com/4165489/209175576-f6965390-9b60-446b-9b82-c04893f0d5f0.png)

Hopefully that's enough to get you un-stuck!
