### ISSUE TITLE
Image: support transparency

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2285]
Hi!

I wonder if it is possible to plot a second int[,] 2D array over a heatmap, with Alpha opacity, and RGB color?
So this second "heatmap" is actually not a heatmap, but a fixed color overlay, where there are some NULL values where we want total transparency (full view of the underlaying real heatmap), and fixed values representing the RBG color. 

I understand that, I could somehow hack together the heatmap's colorbar in a way, so when I clip the int[,] finite values they get the required color, but then this will affect the real heatmap too.

Maybe someone can bring up some workaround? Maybe a new Plottable type could be useful, like a limited heatmap? Or a special Heatmap with fixed color? --> Plot.AddFixColorMap(boolArray, double alpha, double red, double blue, double green); 
Where bool[,] boolArray is a bool matrix, with False values at positions where we want total transparency, and the given opacity alpha level and color at the True values to render?

I also consider to create a special Bitmap, and plot it over the heatmap, but this might not be the best approach? -->
https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-use-a-color-matrix-to-set-alpha-values-in-images?view=netframeworkdesktop-4.8

Thanks for any suggestions! :)

**Comment by swharden** [comment]
I'll merge #2313 into this issue and track progress here:

Add an `Alpha = 1.0` property to the `Image` plot type.

* https://scottplot.net/cookbook/4.1/#image

This may also allow overlaying a semitransparent image above a heatmap which may help @bukkideme in #2277

**Comment by swharden** [comment]
Somewhere along the line this feature was added

```cs
double?[,] values = {
    { 1, 7, 4, 5 },
    { 9, 3, 2, 4 },
    { 1, 4, 5, 8 },
    { 7, 2, 4, 2 }
};

double?[,] opacities = {
    { 1, 1, 1, 1 },
    { 1, 0, 1, 0 },
    { 1, .75, .5, 0 },
    { 1, .8, .6, .4 }
};

var hm = plt.AddHeatmap(values);
hm.Update(values, opacity: opacities);
```

![image](https://user-images.githubusercontent.com/4165489/230603732-a5faba8c-e5db-4f09-82d1-669117b0f28c.png)

I added it to the changelog because I don't think it was properly reported or documented in the cookbook previously ecb40cc6b753d00e94fddade03420cb994168e34
