### ISSUE TITLE
Signal Plot colors problem

### ISSUE THREAD

**Issue by Nuliax7** [ScottPlot/ScottPlot#2288]
**ScottPlot Version:** 4.1.59

**Operating System:** Windows 11

**Application Type:** WPF

**Question:** 
The last color set changes everything.
For example: if white is indicated for the line, and red is indicated for the marker on the next line, then the entire line and markers will be red. Or vice versa, if you first specify the marker in red and the line is white, then everything will be white.
This happens if Signal Plot is selected.
Is this the right behavior? As expected, the different specified colors should be displayed differently. Looks like a bug.

```cs
var plot = Chart.Plot.AddSignalXYConst(times, prices); 
plot.MarkerColor = Color.Red;
plot.Color = Color.White;
```

![изображение](https://user-images.githubusercontent.com/61284630/206254717-4aeb7ee0-c9af-4a78-be8b-b49689765c55.png)

-----------------------------------------------

```cs
var plot = Chart.Plot.AddSignalXYConst(times, prices); 
plot.Color = Color.White;
plot.MarkerColor = Color.Red;
```
![изображение](https://user-images.githubusercontent.com/61284630/206255501-99af8e48-d2c2-48a4-b0d0-48f42f3d6ea4.png)

I tried to set the color for other properties, the behavior is the same.

**Comment by StendProg** [comment]
Hi @Nuliax7,
It looks like it was originally intended.
And it looks like you are the first one who had the idea to set different colors.
Different properties share one color:
https://github.com/ScottPlot/ScottPlot/blob/c168325f37f1c79bfe9b13072cf8f2806ed9b221/src/ScottPlot4/ScottPlot/Plottable/SignalPlotBase.cs#L67-L69

**Comment by Nuliax7** [comment]
@StendProg, 
Thanks for the reply. There are still doubts that this was intended. Otherwise, why then so many properties, and at least in ScatterPlot it works differently (normally).

**Comment by swharden** [comment]
Thanks for the suggestion @Nuliax7! I'm making the change now to allow lines and markers to be colored independently and will add this example to the cookbook

```cs
double[] values = DataGen.Sin(51);
var sig = plt.AddSignal(values);

sig.LineColor = Color.LightBlue;
sig.LineWidth = 3;
sig.MarkerColor = Color.Blue;
```

![image](https://user-images.githubusercontent.com/4165489/209181711-beb5f0bd-7fa5-45b3-b263-0a532914a80f.png)
