### ISSUE TITLE
Axis: tick labels overlap for extremely small plots

### ISSUE THREAD

**Issue by Xerxes004** [ScottPlot/ScottPlot#2289]
## Bug Report

**Issue:** Without changing tick density, labels can overlap when the plot is squashed small enough

**Reproducing:** Start the Live Data (Growing) WPF demo and squash down the window

![image](https://user-images.githubusercontent.com/9276814/206538665-f7c5945f-496d-420b-9de0-c045bd9fa0f9.png)

### System Details
* **ScottPlot Version:** 4.1.59
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** .NET 6 / .NET 7

**Comment by swharden** [comment]
Made some great progress here! #2577 It'll be in the next release today or tomorrow 🚀 

![resize](https://user-images.githubusercontent.com/4165489/230748464-02954335-0328-4b18-a2ca-db0dd970d1cb.gif)
