### ISSUE TITLE
Cookbook: set maximum axis limits

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2290]
It appears there is a bug in Cookbook.
The following example does not limit the axis.
![image](https://user-images.githubusercontent.com/26789352/206600355-6671ca3c-02de-4132-b849-525656d5c3be.png)

Please update the source code.

This example does work but there is no source code attached.
![image](https://user-images.githubusercontent.com/26789352/206600576-aebce653-822f-4a04-b58d-bcb7292bef43.png)

I tried to limit the axis for several hours but had no luck.

**Comment by swharden** [comment]
Hi @dusko23, thanks for reporting this! I will definitely fix this in the cookbook.

Note that the demo code you refer to is here:
https://github.com/ScottPlot/ScottPlot/blob/c168325f37f1c79bfe9b13072cf8f2806ed9b221/src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/AxisLimits.cs#L11-L25

**Comment by dusko23** [comment]
Thanks :-)

**Comment by swharden** [comment]
> Thanks :-)

Glad you got it working! 

I'm going to re-open this issue to remind me to make this more discoverable in the cookbook 👍

**Comment by swharden** [comment]
https://scottplot.net/faq/axis/

**Comment by swharden** [comment]
https://scottplot.net/faq/axis/#set-boundaries-on-the-axis-limits
