### ISSUE TITLE
Add option to limit how far the user can zoom in

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2291]
It appears that there is an issue when zooming in.
This is what I get.

**OK**
![image](https://user-images.githubusercontent.com/26789352/206863391-875e7b68-91ec-43d3-a26a-0792a0b4041c.png)
**OK**
![image](https://user-images.githubusercontent.com/26789352/206863414-d6c2524c-2e7f-4de2-8d8f-ef29e7f47c97.png)
**OK**
![image](https://user-images.githubusercontent.com/26789352/206863443-a1528532-613c-413e-b981-209bc3a92656.png)
**OK**
![image](https://user-images.githubusercontent.com/26789352/206863493-97726c9e-03dc-4f2d-b340-1e7ad8fa892e.png)

**NOT OK**
![image](https://user-images.githubusercontent.com/26789352/206863522-07a5ed05-cc5d-4e96-8338-064b137893ad.png)

**NOT OK**
![image](https://user-images.githubusercontent.com/26789352/206863570-b7d3c80f-7710-4333-a2b6-e2b46f32adfe.png)

**NOT OK. ALSO, PLOT ALSO BECOMES INVISIBLE**
![image](https://user-images.githubusercontent.com/26789352/206863643-babdd401-0659-4969-8805-3c9cdc49c241.png)

**I am aware that this is down to the submillimeter level.
However, users zoom like crazy sometimes.
It would be good to have the option to set a PLOT parameter to limit ZOOM IN.
Like MaximumZoomLevelValuePerPixel**

**Comment by swharden** [comment]
Thank you for opening this issue @dusko23! This has been a problem for many years, and your idea of a `MaximumZoomLevelValuePerPixel` is a good solution, and the one I think I will implement. I will close this issue but track progress toward this goal in #2250 🚀
