### ISSUE TITLE
Removing Items

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2292]
Adding items like diagrams, and tooltips is easy.
However, I did not find a way to remove all tooltips for example.
Clearing everything and drawing again works but does not feel good.

As well it appears that it is not possible to get a collection of added plot objects and related properties.
I hope I am wrong :-)

It would be good that every object added to the plot gets ID defined by the developer.
And after getting a collection of objects it would be much easier to manage things.

By the same token having all object's properties and data at hand it would be much easier to create a proper PDF using 3rd party library.

**Comment by swharden** [comment]
## Removing a plottable

Try something like this

```cs
var thingThatWasAdded = formsPlot1.Plot.AddTooltip();
```

Be sure to store that thing that was returned. Keep track of it, and you can selectively remove it later. Something like:

```cs
formsPlot1.Plot.Remove(thingThatWasAdded);
formsPlot1.Refresh();
```

## Iterating plottables

> As well it appears that it is not possible to get a collection of added plot objects and related properties.

I think you can do something like this

```cs
foreach(var plottable in formsPlot1.Plot.GetPlottables()){
  
}
```

**Comment by dusko23** [comment]
Thanks, that works like charm :-)
If I may I would suggest adding one more item to Quickstart.
Something like Dynamic Adding, Removing, Querying, and Changing Plotables (objects inside Plot Area).
I believe most ScottPlot users are concentrated on what the final Plot looks like.
However, in a mapping system, the interaction between maps and plots is very intensive and parameters are flowing in both directions.

**Comment by dusko23** [comment]
Is there any Plotable property (apart from the Label) to distinguish between Plotables?
I was searching for a Tag Property but it appears there is none.

**Comment by dusko23** [comment]
foreach(var plottable in formsPlot1.Plot.GetPlottables()){

- Please give some hints on how to get Xs and Ys values.
- I have spotted GUID object in the structure.
- Is this GUID created when data is added to ScottPlot?
- Is this GUID Unique?

  
}

**Comment by swharden** [comment]
> If I may I would suggest adding one more item to Quickstart.
> Something like Dynamic Adding, Removing, Querying, and Changing Plotables (objects inside Plot Area)

Maybe adding these links here will help others discover them more easily in the future
* https://scottplot.net/cookbook/4.1/category/quickstart/#remove-a-plottable
* [FAQ: Creating, Adding, and Modifying Plottable objects](https://scottplot.net/faq/plottable)

> Is there any Plotable property (apart from the Label) to distinguish between Plotables?
> I was searching for a Tag Property but it appears there is none.

Correct. Users are encouraged to create their own data structures to pair custom objects with plottables. This question has been asked a few times, so I'll create a page for it on the FAQ site
* #2114 
* #694
* #695
* #757

> Please give some hints on how to get Xs and Ys values.

I recommend not trying to get X and Y values out of plot objects. When you added them to the plot you passed in an array, so the best way to access the data is to index the data from that array. I don't recommend using GUI objects to _store_ data.

That said, `AddScatter()` returns an object which has `Xs` and `Ys` properties to can access and modify
