### ISSUE TITLE
Plot: `PanCenter(coordinate)` and how to change mouse button actions in ScottPlot 4

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2293]
RightClickDragZoom should be divided into two separate properties.
I would like to disable the right button zoom but would definitely like to pan with the right button.

My target scenario:

- **The left mouse click** places a tooltip.
- **Right mouse down and drag** performs panning.

Currently, I can pan with the left mouse. RightClickDragZoom is set to False to get rid of Zoom.
However, the left click generates a tooltip as well.
To clear a tooltip I clear everything.
ScotttPlot starts from scratch and the tooltip is typically out of the display area after a clean start.

I googled a lot and did not find a way to center a plot at specified x and y.
Like myPLOT.Plot.Center(X as double, Y as double)

**Comment by swharden** [comment]
## Remapping Mouse Actions in ScottPlot 4

> would definitely like to pan with the right button

Hi @dusko23, this is not possible with the stock ScottPlot 4 controls but will be possible with the ScottPlot 5 controls

To achieve this effect in ScottPlot 4 you can copy the code of the FormsPlot and create your own, changing the contents of the section of code that maps mouse actions to plot actions

https://github.com/ScottPlot/ScottPlot/blob/063328cc6da34b72c25c9ca97f7e96cf59e9af62/src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs#L208-L221

Questions like this are commonly asked here, so I created a new FAQ page to help make this answer more discoverable. 

* https://scottplot.net/faq/buttons/

@bclehmann this is a private method so we can do what we want with it... I wonder if it's worth putting an interface here or even making this overridable so users could customize this in ScottPlot 4? Now may be a good time to stick that in...

## How to Center a Plot on a Point

> I googled a lot and did not find a way to center a plot at specified x and y.
> Like myPLOT.Plot.Center(X as double, Y as double)

There isn't currently a way to do this, but it would be easy to add a function that does this. Something like:
```cs
myPlot.PanCenter(xCenter, yCenter);
```

I'll leave this issue open to further explore both ideas

**Comment by bclehmann** [comment]
> wonder if it's worth putting an interface here or even making this overridable so users could customize this in ScottPlot 4?

In theory I suppose it could be useful, but this method is hardly really built for that, it creates an object that is reasonably likely to be extended (or at least would be if control code wasn't so large and fragile) and it's not immediately clear under what circumstances (or with what assumptions) it would be called.

In addition, there's only really one reasonable implementation, it sets `LeftWasJustPressed` if left was just pressed, to use it to customize behaviour requires giving it a semantically incorrect implementation. This is more about how we assumed buttons always mapped to the same actions, so any attempt to separate them out with simple tricks like this is always going to be unintuitive.

So, yes in theory making it `protected virtual` could solve the problem, but it would be kind of a pain to use, fairly limited, and difficult to document. And importantly, `GetInputState` could very easily pick up extra responsibilities (or be removed entirely), so making it `protected virtual` would require us to either create workarounds if the user creates funky overridden behaviour, or for us to declare such usage unsupported, which isn't ideal.

**Comment by swharden** [comment]
Great points! Thanks for your input

Making it `protected virtual` is probably the best option... but I really don't like the idea of people depending on that API not to change, so the best option still isn't good enough to merit action.

Let's keep the recommended solution "copy/paste the control source code and modify behavior as desired" as described on the new FAQ page https://scottplot.net/faq/buttons/ and this is another example of a task that gets way easier in ScottPlot 5

I'll kee this issue open to remind me to make a `PanCenter()` function

**Comment by dusko23** [comment]
Hi,
I think that we are facing the same problem as Microsoft did when creating Windows.
Things as above happen when GUI is merged into the business logic. Hard-coded Context Menu in this case.
It took loads of effort to separate the two.
However, in the case above it is easy to solve.

When it comes to the mouse events they must be fully exposed to the developer.
It means no popup menu when the mouse button is pressed.
Instead, a method (or function) should be available and the user can call that when the mouse button is pressed. 
By the same token, I would suggest creating Visible Property for each Context menu item. If the user wants to show some of those items he(she) sets the relevant property to True and calls the function to show the Context menu. If the user wants to show his own Context menu then the user just creates one and shows that. Without any overriding, skipping or disabling hard-codded one.
Again, by the same token, I would suggest exposing methods of existing hard-coded Context menu items Click Events as functions. That would enable the developer to fully customize the look and feel including language translation. That is probably the best solution to the above problems.
Merging GUI with business logic is problematic. Should be kept separated at all times.
Hope that makes sense.

**Comment by swharden** [comment]
Hi @dusko23, thanks for your message! Here are some tips which may help you or others who find this issue page in the future:

## Exposing Mouse Events

> a method should be available and the user can call that when the mouse button is pressed

All ScottPlot controls have event handlers like `LeftClicked` that users can interact with to achieve custom actions

https://github.com/ScottPlot/ScottPlot/blob/f3b4f1b4b813915e453707956bca6a467935815a/src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs#L36-L40

https://github.com/ScottPlot/ScottPlot/blob/f3b4f1b4b813915e453707956bca6a467935815a/src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs#L196

## Customizing the Right-Click Menu

> I would suggest creating Visible Property for each Context menu item. If the user wants to show some of those items he(she) sets the relevant property to True and calls the function to show the Context menu. If the user wants to show his own Context menu then the user just creates one and shows that. Without any overriding, skipping or disabling hard-codded one.

Instead of masterminding a right-click menu and expecting users to customize it, I went with the simpler option. I give the developer a basic default right-click menu, and if they want something custom they can replace it with their own. This gives the developer full control and does not require studying a custom GUI API.

https://scottplot.net/faq/right-click-menu/

Hope this helps!
Scott

**Comment by swharden** [comment]
```cs
ScottPlot.Plot plt = new();

plt.AddMarker(-1, -1, size: 20);
plt.AddMarker(-1, 1, size: 20);
plt.AddMarker(1, 1, size: 20);
plt.AddMarker(1, -1, size: 20);

plt.SetAxisLimits(-3, 3, -3, 3);

TestTools.SaveFig(plt, "before");

plt.AxisPanCenter(1, 1); // <-- new command

TestTools.SaveFig(plt, "after");
```

before | after
---|---
![image](https://user-images.githubusercontent.com/4165489/209347821-201cd990-d06e-4d7e-8a41-7b45226c784d.png)|![image](https://user-images.githubusercontent.com/4165489/209347832-b2af2be8-0db7-4ef9-9df8-a7a425b43e45.png)

**Comment by dusko23** [comment]
Hi,
I have looked at
https://scottplot.net/faq/right-click-menu/
My code is written in VB.net and the only way (to my knowledge) to get rid of right-click event is this
![image](https://user-images.githubusercontent.com/26789352/209351093-957f39cf-59d2-45bc-a3e5-6d38afc76871.png)
But the handler is not removed.
Still pops up.
Any idea what should I try?

**Comment by swharden** [comment]
Maybe you can remove all events using reflection?

* https://stackoverflow.com/questions/24025623/how-to-remove-all-event-handlers-from-a-control-in-vb-net
* https://stackoverflow.com/questions/91778/how-to-remove-all-event-handlers-from-an-event
* https://stackoverflow.com/questions/1150250/removing-all-event-handlers-in-one-go
* https://stackoverflow.com/questions/26576547/how-to-remove-all-event-handlers-from-an-event
