### ISSUE TITLE
Manual drawing tool

### ISSUE THREAD

**Issue by SARPSARP090** [ScottPlot/ScottPlot#2294]
Sorry for my bad english. I met Scottplot a long time ago. I like it very much and it's equipped with really nice features. However, I could not find the manual line drawing feature that I needed when designing a program for us traders. How can I add a manual plotting tool on "formsPlot1", as indicated by the arrows in the screenshot from the Tradingwiev website?

![AVAXUSDT_2022-12-11_11-25-52](https://user-images.githubusercontent.com/89920711/206894069-33449d0f-0788-48e7-8c72-83d311cc775f.png)
![scot](https://user-images.githubusercontent.com/89920711/206894077-df5b52ea-6e18-4a8a-ae6a-6c7e6bb2a769.PNG)

**Comment by swharden** [comment]
Hi @SARPSARP090,

You can place lines programmatically
```cs
formsPlot1.Plot.AddLine(x1, y1, x2, y2);
```

To draw using the mouse you have to use events yourself and determine the location of the mouse when the plot is clicked https://scottplot.net/faq/mouse-position/

**Comment by SARPSARP090** [comment]
I'll try this right away and get back to you. Thank you very much for the quick reply.
