### ISSUE TITLE
FormsPlot detached legend fails for horizontal legends

### ISSUE THREAD

**Issue by rotger** [ScottPlot/ScottPlot#2300]
In a windows form plot, when you show a legend, you can right click the plot and detach the legend. This allow to hide / show / edit series when you click on them. This is very useful feature.

Bug:  This doesn't work when the legend is set to show horizontally.

Cookbook: [horizontal legend orientation](https://scottplot.net/cookbook/4.1/category/misc/#legend-orientation)

**Comment by swharden** [comment]
Thanks for sharing this issue @rotger!

Here's some code to help reproduce the issue

```cs
public Form1()
{
    InitializeComponent();

    var func1 = new Func<double, double?>((x) => 5 * Math.Sin(x) * Math.Sin(x / 2));
    var func2 = new Func<double, double?>((x) => 4 * Math.Sin(x) * Math.Sin(x / 3) - 1);

    var fp1 = formsPlot1.Plot.AddFunction(func1);
    fp1.FillType = FillType.FillBelow;
    fp1.Label = "func1";

    var fp2 = formsPlot1.Plot.AddFunction(func2);
    fp2.FillType = FillType.FillBelow;
    fp2.Label = "func2";


    var leg = formsPlot1.Plot.Legend();
    leg.Orientation = ScottPlot.Orientation.Horizontal;

    formsPlot1.Refresh();
}
```

![image](https://user-images.githubusercontent.com/4165489/209234895-fe19eb79-2a05-4245-a790-28b54f29bf80.png)

It looks good, but the mouse hit detection is wrong. I think the fix here is to ensure the legend is always vertical in the pop-up window.
