### ISSUE TITLE
How to customize the display range of X-axis and Y-axis?

### ISSUE THREAD

**Issue by ffsquarehy** [ScottPlot/ScottPlot#2301]
original title: 如何自定义X轴和Y轴的显示范围？

**Comment by chenxuuu** [comment]
cookbook里写了，仔细看看吧

https://scottplot.net/cookbook/4.1/category/quickstart/#axis-labels-and-limits

**Comment by swharden** [comment]
Thank you @chenxuuu! 谢谢你
