### ISSUE TITLE
Annotation: add support for center positioning

### ISSUE THREAD

**Issue by EFeru** [ScottPlot/ScottPlot#2302]
**ScottPlot Version:** 4.1.59

**Operating System:** W10

**Application Type:** WinForms

**Question:** Hi, is there a way to place annotation in the middle of the axes? So, top-middle, bottom-middle, left-middle, right-middle (see picture below in green). I show a Delta caluculation in my plot and it feels more natural to place it in the middle.

I already looked if there is a method to get the plot limits in pixels and caculate the middle myself, however couldn't find one. The closest I could get is to get the Axis limits in data coordinate, calculate middle and then convert it to pixel coordinate. However, I think I am over-doing it this way. Let me know what you think.
```cs
AxisLimits ax = formsPlot.Plot.GetAxisLimits();
double middleXPixel = formsPlot.Plot.GetPixelX(ax.XCenter);
formsPlot.Plot.AddAnnotation("Delta", middleXPixel, -10);  // Position to Lower-middle
```

![image](https://user-images.githubusercontent.com/24780745/208074736-52b6f642-8a30-4099-b889-82c13b13ccda.png)

**Comment by swharden** [comment]
Hi @EFeru, thanks for this question! I agree that the current annotation positioning system is weird and confusing, and also doesn't support center alignment.

Supporting this properly would involve changing how annotations are aligned. Presently everything is in weird positive and negative pixel units. Ideally it should be defined by a member of an `AnnotationPosition` enumeration containing all 9 positions (The 4 represented by yellow labels, 4 more represented by green arrows, and one in the center for good measure).

Annotation objects could have a `AnnotationPosition?` property which would be ignored if null, but respected and override the weird X/Y units used by the current position system. There are advanced text alignment tools already to help with that (see how the Text plot type handles alignment).

I probably won't work on this for a little while (#2304) but if you or someone else wants to have a go at it, I would be happy to review a PR that works toward this!

https://scottplot.net/cookbook/4.1/category/plottable-text/#text-alignment-and-rotation

https://github.com/ScottPlot/ScottPlot/blob/f3b4f1b4b813915e453707956bca6a467935815a/src/ScottPlot4/ScottPlot/Plottable/Annotation.cs#L7-L87

**Comment by EFeru** [comment]
That is fine by me. Take your time. I am not sure if I will be able to look at the topic myself due to other tasks I have to do. However, I do feel that I should give something back. Scottplot proved for me an extremely helpful library.

**Comment by swharden** [comment]
Thanks for pointing this out @EFeru! Revisiting this plottable I'm frustrated by how confusing the X/Y positioning system is 😝 

A better design would be to have an `Alignment` enumeration (with members like `TopLeft`, `TopCenter`, `BottomRight`, etc.) and distance from the edge could be defined with a `public float Padding`.

I'm motivated to solve this in a non-breaking way, so I may mark the X/Y fields `obsolete` and guide existing users to use whatever new positioning system I come up with.
