### ISSUE TITLE
Avalonia 11

### ISSUE THREAD

**Issue by petryaevve** [ScottPlot/ScottPlot#2321]
## Feature Suggestion
Upgrade to Avalonia 11 version
**Feature description:** Describe your idea here
Update Avalonia version for 11 preview.

**Comment by swharden** [comment]
Hi @petryaevve, 

It looks like the current release of Avalonia is 0.10.18
https://www.nuget.org/packages/Avalonia/

I think the plan is to only target the latest _released_ version of Avalonia, but I'm happy to collect notes of people who have adapted ScottPlot to work with preview versions too.

Related
* #2183
