### ISSUE TITLE
Candlestick: How to display thousands of values

### ISSUE THREAD

**Issue by Papercut110** [ScottPlot/ScottPlot#2325]
first of all, many thanks for the project, an extremely useful thing
and question is - I am loading 10,000 candles, please tell me if there is an opportunity to scale the chart in such a way that the last 100 candles are displayed, for example?

**Comment by swharden** [comment]
Hi @Papercut110,

## Plotting Thousands of Candles

> I am loading 10,000 candles

This may be a problem. Have you ever seen a candlestick chart with this many candles before? If so, please share a screenshot and I will be happy to help you achieve this with ScottPlot

In reality I think this is never performed. Assume your screen is 1920 pixels wide. A full-screen candlestick chart with 10k candles would cram 5 candles into each pixel column. The result is interpretable. 

For victualing so much financial data, it seems you need something that is either not a candlestick chart, or you need to bin your data into larger candles (e.g., each candle represents 100 candles)

If you do this, I invite you to share your code here so others interested in binning candles can benefit from your code. It may also be useful to add that code into a method in the `OHLC` data type. Perhaps it could be used like this:

```cs
OHLC[] severalCandles = /* a portion of your data */
OHLC binnedCandle = new OHLC(severalCandles); // create this new constructor
```

That new constructor could be added here

https://github.com/ScottPlot/ScottPlot/blob/b1b82e40799c57ed22f125adbffc633ef57bc903/src/ScottPlot4/ScottPlot/Plottable/DataStructures/OHLC.cs#L1-L82

## Example Code

This code may be helpful for evaluating what different candle charts looks like

```cs
Random rand = new(0);
OHLC[] candles = DataGen.RandomStockPrices(rand, 50);
formsPlot1.Plot.AddCandlesticks(candles);
formsPlot1.Plot.Title($"{candles.Length:N0} candles");
formsPlot1.Refresh();
```

![image](https://user-images.githubusercontent.com/4165489/209446792-ba41a931-8a0f-4d9a-89ed-16302585ae66.png)

![image](https://user-images.githubusercontent.com/4165489/209446814-05bb651f-6de8-45b1-a235-de4b72b395ac.png)

**Comment by mjpz** [comment]
Hi papercut110, 

I get a few hundred up to some thousands of candles from a web service and use FormsPlot to visualize them. 

assuming you are using sequential ohlc         

```
                              // number of candlesToShow
public void Position(OHLC[] ohlc, int candlesToShow, Plot plot)
{
    int iLeft = ohlc.Length - candlesToShow;
    int iRight = ohlc.Length;
    
    var candles = ohlc.TakeLast(candlesToShow);
    
    double yMax = candles.Max(c => c.High);
    double yMin = candles.Min(c => c.Low);

    // optional some room above and below
    yMax *= 1.1;
    yMin *= 0.9;

    var al = new AxisLimits(iLeft, iRight, yMax, yMin);
    
    plot.SetAxisLimits(al);
}

```
Thanks Scott for your great work!

**Comment by mjpz** [comment]
just recalled, use

```
 double iLeft = ohlc.Length - candlesToShow - 0.5;
 double iRight = ohlc.Length + 0.5;
```
to show whole candles. Maybe the x values must be corrected by -1, I have currently no IDE :)

**Comment by mjpz** [comment]
this works like expected
```
    public static void SetInitialView(FinancePlot financePlot, int candlesToShow, Plot plot)
    {
      double iLeft = financePlot.OHLCs.Count - candlesToShow - 0.5;
      double iRight = financePlot.OHLCs.Count - 0.5;

      var candles = financePlot.OHLCs.TakeLast(candlesToShow);

      double yMax = candles.Max(c => c.High);
      double yMin = candles.Min(c => c.Low);

      // optional some room above and below
      yMax *= 1.01;
      yMin *= 0.99;

      var al = new AxisLimits(iLeft, iRight, yMin, yMax);

      plot.SetAxisLimits(al, 0, 0);
    }

```

**Comment by swharden** [comment]
Following-up on this, I'll close the issue because it seems like the core issue here is resolved but there's room for future contribution: It may be useful to have a static method for combining OHLCs (e.g., convert a large collection of hourly OHLCs to daily OHLCs). Something like:


```cs
public static OHLC[] GetHourlyOHLCs(OHLC[] anyOhlcs) 
{
    /* */
}

public static OHLC[] GetDailyOHLCs(OHLC[] anyOhlcs) 
{
    /* */
}

public static OHLC[] GetMonthlyOHLCs(OHLC[] anyOhlcs) 
{
    /* */
}
```
