### ISSUE TITLE
Can ScottPlot compile in Visual Studio 2019?

### ISSUE THREAD

**Issue by mkane7** [ScottPlot/ScottPlot#2330]
I am looking to download the source from github and step thru the winform demos after running the executable demos.  Will ScottPlot4.sln compile in Visual Studio 2019 ?

**Comment by bclehmann** [comment]
Hello, it should work fine and without modification on Visual Studio 2022 (and presumably Rider), as the issues come from newer language features. There is a post on developing with VS19, as well as I believe a python script to automate the changes: https://scottplot.net/faq/environment/

If you only need to compile, I believe `dotnet build` should work fine.
