### ISSUE TITLE
Cookbook: show scatter plot with labels

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2333]
something like this:

```cs
double[] xs = { 1, 2, 3, 4, 5 };
double[] ys = { 1, 4, 9, 16, 25 };
var sp = plt.AddScatter(xs, ys);

string[] labels = {"label1","label2","label3" ,"label4","label5"};
sp.DataPointLabels = labels;
```

Related:
* https://github.com/ScottPlot/ScottPlot/pull/2155
* https://github.com/ScottPlot/ScottPlot/discussions/2141

**Comment by swharden** [comment]
```cs
var plt = new ScottPlot.Plot(600, 400);

double[] xs = { 18.5, 20.6, 22.3, 24.5, 26.6, 15, 15 };
double[] ys = { 1.43, 1.48, 1.6, 1.59, 1.53, 1.52, 1.6 };
string[] labels = { "A", "B", "C", "D", "E", "F", "G" };

var sp = plt.AddScatter(xs, ys);
sp.DataPointLabels = labels;
sp.DataPointLabelFont.Size = 24;

plt.SetAxisLimits(12, 28, 1.3, 1.7);
plt.SaveFig("scatter_labels.png");
```

![image](https://user-images.githubusercontent.com/4165489/230791416-129939ed-e08c-4ed9-a0e1-d9c29ed7784e.png)

**Comment by Youngolo** [comment]
> It seems that this property is not supported on version 5. How can I obtain the same result with version 5?
@defra91, did you resolve the DataPointLabels issue in ScottPlot 5.0? Need help!
