### ISSUE TITLE
Controls: Allow right-click menu text to be customized

### ISSUE THREAD

**Issue by YNBTools** [ScottPlot/ScottPlot#2335]
**Feature description:** The language of the right-click menu can be customized.

![Snipaste_2022-12-29_11-14-21](https://user-images.githubusercontent.com/32679861/209898727-591a4520-a3d5-4e45-9ad6-1f2cc254dec6.jpg)

**Example:**

```cs
this.ScottPlot.SetToolStripMenuItemText(ScottPlotMenuItem menuitem,string text);

enum ScottPlotMenuItem
{
  copyMenuItem,
  saveImageMenuItem,
  autoAxisMenuItem,
  ...
}

// Change "Save Image As..." to "保存图像为..."
this.ScottPlot.SetToolStripMenuItemText(ScottPlotMenuItem.saveImageMenuItem,"保存图像为...");
```

**Comment by swharden** [comment]
Hi @YNBTools, thank you for this suggestion! I will leave this issue open to remind me to explore options for customizing the text in the labels.

For now, the best way to customize the right-click window is to replace the default one with your own as described here: https://scottplot.net/faq/right-click-menu/

**Comment by swharden** [comment]
There hasn't been movement on this issue so I'm going to close it, but the best current solution for this is for developers who want to customize the right-click menu to create their own as described by https://scottplot.net/faq/right-click-menu/

**Comment by YNBTools** [comment]
Thanks
