### ISSUE TITLE
Colorbar should have a Label property

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2341]
Hi!

I wonder if a label property should be introduced for colorbars or not? I have a feeling, as X/Y-axis can have labels, a colorbar (which is like a "Z-axis") should have optional label text to show?
What do you think?
Thanks!

**Comment by swharden** [comment]
I think this is a good idea! It may take me a while to get to (#2304) but I like the idea of adding this feature for sure.

**Comment by swharden** [comment]
I'm about to merge this new feature, and it can be used like this:

```cs
var plt = new ScottPlot.Plot(400, 300);
plt.XLabel("Horizontal Axis");
plt.YLabel("Vertical Axis");

var cmap = ScottPlot.Drawing.Colormap.Turbo;

var cb = plt.AddColorbar(cmap);
cb.Label = "Turbo Colormap";
cb.LabelFont.Size = 18;
cb.LabelFont.Bold = true;
```

![image](https://user-images.githubusercontent.com/4165489/230792247-5ba447f5-8942-4164-8182-ab66ad1216e5.png)
