### ISSUE TITLE
Axis Tick Width Setting

### ISSUE THREAD

**Issue by SaltyTears** [ScottPlot/ScottPlot#2353]
## Global/Individual Axis Tick Width Setting

**Feature description:** 

The Axis lines have Width settings
plot.XAxis.Line(width: 2);

However, there is no setting to set the width of the ticks (Major/Minor)

**Code example:** 

```cs
Individual Axis
plot.XAxis.TickWidth(2);
plot.YAxis.TickWidth(4);

```

**Comment by swharden** [comment]
Hi @SaltyTears, this just got added and will be in the next release

```cs
ScottPlot.Plot plt = new();
plt.XAxis.AxisTicks.MajorTickLength = 10;
plt.XAxis.AxisTicks.MinorTickLength = 5;
```

**Comment by swharden** [comment]
(Those `AxisTicks` objects have lots of properties that can be customized)
