### ISSUE TITLE
Finance: Renko Chart

### ISSUE THREAD

**Issue by SARPSARP090** [ScottPlot/ScottPlot#2354]
Hello. Thank you very much for developing the Scottplot. However, there is one thing I failed to achieve. I haven't been able to draw the "renko" chart, a kind of financial candles, with your library. Do you have the opportunity to share a Renko candle sample? I have attached the sample image below. Thank you
![Ekran Alıntısı](https://user-images.githubusercontent.com/89920711/211093005-4fd27022-d4ed-4a3c-985c-736bbe7f7f17.PNG)

**Comment by swharden** [comment]
Hi @SARPSARP090, I was not familiar with Renko charts until now

Example: https://www.tradingview.com/support/solutions/43000502284-renko-charts/

We could create a function that takes date/price data as an arrays of `OHLC[]` and generate Renko bricks from them... the difficulty is that Renko Charts have a non-linear horizontal axis. This may be difficult for ScottPlot's horizontal tick mark system (which expects axes to always have evenly-spaced tick marks).

It may take me a while to get to this issue, but I will leave it open and when I am able to look into it further I will follow-up here with messages about what I find!

If someone else wants to contribute a function something like this, I would happy to review a PR:

```cs
public static OHLC[] GetRenkoCandles(OHLC[] prices, double brickSize) { /* ... */ }
```

I'm not totally sure how nonlinear time axes would work out though... Maybe a the above function could be paired with custom manual tick labels https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#manual-tick-labels

**Comment by swharden** [comment]
Hi @SARPSARP090, this issue hasn't had any progress in a while so I'm going to close it, but it's up for grabs if someone wants to have a go at creating this. The recently created FAQ page about how to create new plot types will be very useful for someone looking to add a Renko Chart for ScottPlot:

https://scottplot.net/faq/custom-plot-type/

**Comment by SARPSARP090** [comment]
wonderful, thank's
