### ISSUE TITLE
Add an example of how to change color of value labels

### ISSUE THREAD

**Issue by Hermholtz** [ScottPlot/ScottPlot#2357]
## Feature Suggestion

**Feature description:** With regard to #1432, please add an example of how to change value color to https://scottplot.net/cookbook/4.1/category/plottable-bar-graph/#values-above-bars
(copy/paste of the example from [this comment in #1432](https://github.com/ScottPlot/ScottPlot/issues/1432#issuecomment-969859993) would be just fine).

Thanks in advance.

**Comment by swharden** [comment]
Hi @Hermholtz! Sorry it took so long for me to get to this one. I hope this code example helps you achieve the effect you are looking for!

![image](https://user-images.githubusercontent.com/4165489/217970752-c66e29f3-a5a8-4779-acc7-60414798e95e.png)

```cs
// This is the data we will plot
double[] values = { 10, 23, 13, 7, 9 };

// Create a palette to use for bar and label colors
IPalette myPalette = new ScottPlot.Palettes.Aurora();

// Add a BarSeries to the plot
BarSeries barSeries = plt.AddBarSeries();

// iterate values
for (int i = 0; i < values.Length; i++)
{
    // add a bar to the bar series
    Bar bar = new()
    {
        Value = values[i],
        Position = i,
        FillColor = myPalette.GetColor(i),
        LineColor = Color.Black,
        LineWidth = 1,
    };
    barSeries.Bars.Add(bar);

    // add a label and customize it as desired
    var txt = plt.AddText(values[i].ToString(), i, values[i]);
    txt.Color = myPalette.GetColor(i);
    txt.Font.Alignment = Alignment.LowerCenter;
    txt.Font.Size = 24;
    txt.Font.Bold = true;
}

plt.SetAxisLimits(-1, 5, 0, 30);
```
