### ISSUE TITLE
Suggestion: Add 3D drawing capability

### ISSUE THREAD

**Issue by LHTXQ** [ScottPlot/ScottPlot#2358]
## Feature Suggestion

3D bar charts, dot charts, and color charts are very useful, and no WPF control library seems to provide such functionality at the moment, hopefully ScottPlot will, even if it is only a crude, low-performance temporary solution.
I know this issue has already been discussed in #129 and #1151 , but I hope contributors will consider it again.

Add 3D drawing features like this: 
![image](https://user-images.githubusercontent.com/38943319/211707953-89c5d236-5348-437f-948a-0debbd71342c.png)
![image](https://user-images.githubusercontent.com/38943319/211706338-9866d19d-1a0b-43ab-81ba-808bc6f5d7a7.png)
![image](https://user-images.githubusercontent.com/38943319/211707204-07587fae-9e2e-41ab-8d45-edebf53dd38f.png)

This is just a simple 3D plot, I think ScottPlot could do better.

**Code example:** 
Please see: https://github.com/PawelTroka/Computator.NET/tree/master/Computator.NET.Charting

**Plot example:** 
Please see: https://gnuplot.sourceforge.net/demo/

**Comment by swharden** [comment]
Thanks for this suggestion @LHTXQ! I don't intend to focus on this soon, but I would welcome a pull request if someone is interested in getting this started.

I'll close this issue for now, but add some links to connect similar requests in case we decide to start working on this some day in the future:

* #2358
* #1151
* #1127

**Comment by sopgenorth** [comment]
@swharden Do you have any suggestions for where to start with adding 3D plotting? I'm becoming interested in adding 3D plots to this great library. For one, it seems that SkiaSharp used in ScottPlot5 only does 2D graphics, so openGL would need to be used more directly (perhaps with openTK).

**Comment by swharden** [comment]
> Do you have any suggestions for where to start with adding 3D plotting?

I think there's a really simple way to get started -- don't worry about 3D technologies. You can create amazing 3D charts by drawing straight lines using a 2D graphics library.

Using isometric projection you can create a few lines to draw a 3D cube, then calculate where in that cube to place dots or lines.

It doesn't have to be mouse-interactive! Just _something_ 3D may be helpful to someone. It may be a good strategy to get a simple 3D chart working, then users can extend it with advanced functionality like different types of projection or the ability to rotate the view angle with the mouse.

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/87db95b0-7a84-46c3-922e-52f9acbc15fa)

This looks interesting!

https://www.youtube.com/watch?v=yoP-HwtBncY

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/99b4c5c0-ec20-4fd3-ac1e-8260d82cfff9)

**Comment by swharden** [comment]
@bukkideme in the Discord suggested we take a look at code from https://github.com/helix-toolkit/helix-toolkit (MIT licensed)

**Comment by bukkideme** [comment]
When I have the time, actually I will need to put together a 3D representation of a heatmap. In our project we rely on a Winforms framework developed in our company. So I will need to use hosting control in Winforms UI to host the WPF 3D control and use the above helix toolkit. If I get something working, i can share it here. 

I wonder what would be the actual goal here? Develop a native "only-ScottPlot" 3D library, or maybe we could just give option like via wrapper methods, to use HelixToolkit lib? Of course then the user needs to download the Helix nuget as well....I think using a ready made library as an option from ScottPlot could work, no?

**Comment by swharden** [comment]
> When I have the time, actually I will need to put together a 3D representation of a heatmap. 

This would be super awesome! My last comment was overly technical 🤪 but any progress you make toward a 3D project would be great! 🚀 🚀 🚀 

I'd probably start by not modifying existing ScottPlot source code, but instead creating a little sandbox app to demonstrate the basic concepts, then integration can be worked out later after we know a little more about the implementation

**Comment by swharden** [comment]
Getting something like this running would be a great start!

https://scottplot.net/test/cube/

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/2fa0d130-5f2e-4ee8-ba42-4ea0e6f6d1e4)

**Comment by swharden** [comment]
Following-up, here's a super basic project that shows some basic 2D/3D conversion with projection using C# [test3.zip](https://github.com/ScottPlot/ScottPlot/files/15209883/test3.zip)

![3d](https://github.com/ScottPlot/ScottPlot/assets/4165489/bcdcf4db-db0c-4aad-b8e6-41bd5b28783b)

**Comment by swharden** [comment]
Here's a simpler code example evolved from the previous zip file

![3d2](https://github.com/ScottPlot/ScottPlot/assets/4165489/4e2e3ca9-84da-4e40-b2ae-1ab2ba505193)

```cs
namespace test3;

internal class Axis3D
{
    public double RotationX { get; set; } = 0.0;
    public double RotationY { get; set; } = 0.0;
    public double RotationZ { get; set; } = 0.0;

    public static Color GetRandomColor()
    {
        int red = Random.Shared.Next(256);
        int green = Random.Shared.Next(256);
        int blue = Random.Shared.Next(256);
        return Color.FromArgb(255, red, green, blue);
    }

    public static RectangleF GetBoundingRectangleF(PointF[] points)
    {
        float left = points.Select(x => x.X).Min();
        float right = points.Select(x => x.X).Max();
        float bottom = points.Select(x => x.Y).Max();
        float top = points.Select(x => x.Y).Min();
        float width = right - left;
        float height = bottom - top;
        return new RectangleF(left, top, width, height);
    }

    public Bitmap GetBitmap(int width, int height)
    {
        Point3D[] originalPoints3d =
        [
            new (0, 0, 0), // origin
            new (1, 0, 0), // x line
            new (0, 1, 0), // y line
            new (0, 0, 1), // z line

            new (0.25, 0, 0), // x stub (4)
            new (0, 0.25, 0), // y stub
            new (0, 0, 0.25), // z stub

            new (0.25, 0.25, 0), // xy mid (7)
            new (0, 0.25, 0.25), // yz mid
            new (0.25, 0, 0.25), // xz mid
        ];

        Point3D CameraTarget = new(0, 0, 0);
        Point3D Camera = new(
            x: CameraTarget.X,
            y: CameraTarget.Y,
            z: CameraTarget.Z + 200);

        //Apply Rotations, moving the cube to a corner then back to middle

        Point3D[] points3D = originalPoints3d.ToArray();
        Point3D point0 = new(0, 0, 0); //Used for reference
        points3D = Math3D.Zoom(points3D, 100);
        points3D = Math3D.Translate(points3D, CameraTarget, point0);
        points3D = Math3D.RotateX(points3D, RotationX); //The order of these
        points3D = Math3D.RotateY(points3D, RotationY); //rotations is the source
        points3D = Math3D.RotateZ(points3D, RotationZ); //of Gimbal Lock
        points3D = Math3D.Translate(points3D, point0, CameraTarget);

        double focalFactor = width * .5;

        //Convert 3D Points to 2D
        Point imageCenter = new(width / 2, height / 2);
        PointF[] points2D = new PointF[points3D.Length];
        for (int i = 0; i < points2D.Length; i++)
        {
            Point3D point3D = points3D[i];
            bool pointIsAboveCamera = point3D.Z >= Camera.Z;
            if (pointIsAboveCamera)
            {
                points2D[i].X = (float)(-(point3D.X - Camera.X) / (-0.1f) * focalFactor) + imageCenter.X;
                points2D[i].Y = (float)((point3D.Y - Camera.Y) / (-0.1f) * focalFactor) + imageCenter.Y;
            }
            else
            {
                points2D[i].X = (float)((point3D.X - Camera.X) / (point3D.Z - Camera.Z) * focalFactor + imageCenter.X);
                points2D[i].Y = (float)(-(point3D.Y - Camera.Y) / (point3D.Z - Camera.Z) * focalFactor + imageCenter.Y);
            }
        }

        Bitmap bmp = new(width, height);
        using Graphics gfx = Graphics.FromImage(bmp);
        gfx.Clear(Color.White);
        gfx.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.AntiAlias;
        gfx.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAlias;

        // origin frame
        gfx.DrawLine(Pens.Red, points2D[0], points2D[1]);
        gfx.DrawLine(Pens.Green, points2D[0], points2D[2]);
        gfx.DrawLine(Pens.Blue, points2D[0], points2D[3]);

        // XY corner
        gfx.DrawLine(Pens.Black, points2D[4], points2D[7]);
        gfx.DrawLine(Pens.Black, points2D[7], points2D[5]);

        // YZ corner
        gfx.DrawLine(Pens.Black, points2D[5], points2D[8]);
        gfx.DrawLine(Pens.Black, points2D[8], points2D[6]);

        // XZ corner
        gfx.DrawLine(Pens.Black, points2D[4], points2D[9]);
        gfx.DrawLine(Pens.Black, points2D[9], points2D[6]);

        using Font font = new("Arial", 12, FontStyle.Regular);
        gfx.DrawString("X", font, Brushes.Red, points2D[1]);
        gfx.DrawString("Y", font, Brushes.Green, points2D[2]);
        gfx.DrawString("Z", font, Brushes.Blue, points2D[3]);

        return bmp;
    }
}
```

**Comment by swharden** [comment]
Wow, once the 3D translation system is in place, it's easy to create 3d grids and 3d scatter plots

![3d3](https://github.com/ScottPlot/ScottPlot/assets/4165489/ee29259d-cebe-4424-8c5b-05b1c7267830)

**Comment by swharden** [comment]
I'm merging #3774 now so the ScottPlot 5 solution now has a `Sandbox.WinForms3D` project if you want to have a go at improving the behavior or adding new plot types! It's still pretty thin, but I think the basics are in place so it should be easy to pick up and hit the ground running 🚀 

![3d4](https://github.com/ScottPlot/ScottPlot/assets/4165489/bf6b19e9-83fe-4de0-9940-a4a1153ad022)
