### ISSUE TITLE
System.Drawing.Common no longer supported on MacOS

### ISSUE THREAD

**Issue by sleytus2** [ScottPlot/ScottPlot#2359]
ScottPlot newbie here -- an amazing, amazing charting library...

We're using ScottPlot to develop a Windows / MacOS app that acquires and charts RF spectrum data.  We develop on Windows using Avalonia.  Everything was going smoothly until we began building and testing on MacOS -- and that is when we ran into the problem with System.Drawing.Common.  In the short-term we will downshift to .NET 6 and use the 'EnableUnixSupport' project setting.

I was wondering whether you've seen IronDrawing's replacement for System.Drawing.Common and have considered this as a possible solution -- it's pretty new.  Here are a couple of links:

https://ironsoftware.com/open-source/csharp/drawing/docs/
https://github.com/iron-software/IronSoftware.System.Drawing

EDIT: I've substituted IronSoftware.Drawing for System.Drawing in our .NET 7 Avalonia application and everything builds and runs fine, with one exception:  ColorTranslator.FromHtml(x)).ToArray();

EDIT: I lied -- it doesn't work. IronSoftware.Drawing can replace System.Drawing for the app -- however, ScottPlot must use System.Drawing internally.  I'm going to try rebuilding ScottPlot with IronSoftware.Drawing to remove all dependencies on System.Drawing.

EDIT: This isn't going to work -- that is, substituting IronSoftware.Drawing for System.Drawing in ScottPlot -- because IronSoftware's library is missing too many graphical elements.

```

**Comment by BambOoxX** [comment]
As far as I know, the main purpose of ScottPlot 5 is exactly to remove all dependencies to System.Drawing and replace it with SkiaSharp. 
So I guess your best choice is to wait for the first full fledged v5 release.

**Comment by sleytus2** [comment]
@BambOoxX -- thanks for the quick response.  After some poking around we'd come to the same conclusion.  Still -- ScottPlot v4 is an unbelievable piece of software.  Shame on Microsoft for pulling the rug out from under System.Drawing...

**Comment by swharden** [comment]
Following-up, it looks like ScottPlot4's dependency on System.Drawing.Common means it's only supported on MacOS projects targeting .NET 6

Non-windows / cross-platform projects targeting .NET 7 or later require ScottPlot5

I recognize ScottPlot5's feature list and documentation isn't as great as ScottPlot 4, but it's getting there! I hope to tilt work toward it more and more and hopefully its progress will accelerate 🚀 

* https://scottplot.net/versions/
* #2304
