### ISSUE TITLE
SignalPlot add last point to the plot

### ISSUE THREAD

**Issue by Johann-Schmid** [ScottPlot/ScottPlot#2361]
Hi...for a project i use ScottPlot...the tool is great...Thx...in the project i get every 20ms a new INT value. Now i want add this new value to my SignalPlot. Current i use a array with 500 points and I use the SignalPlot.Refresh() function to plot the new value, but this functions plots the complete graph. To plot the graph take about 100ms, that's to long. So is there a function in SignalPlot to plot a single value than the complete 500 points...?? Thx

I read something about PlotScatter in this post, but I think Angle_Angle1_Graphi.Render() renders the complete 2000 points and not only the last one

https://github.com/ScottPlot/ScottPlot/discussions/777#discussioncomment-366986

```cs
private void button_Click(object sender, RoutedEventArgs e)
{
    Scatter = Angle_Angle1_Graphic.plt.PlotScatter(xs, ys);
    dispactherTimer.Start();
}

double[] xs = new double[20000];
double[] ys = new double[20000];
int i = 0;

Scatter.xs = xs;
Scatter.ys = ys;
Angle_Angle1_Graphic.plt.AxisAuto();
Angle_Angle1_Graphic.Render();
```

**Comment by ChrisAtVault** [comment]
Hey @Johann-Schmid,
as far as I am concerned that feature does not exists. Instead I'd suggest that you use a [SignalConst](https://scottplot.net/cookbook/4.1/category/plottable-signalconst/). You can try this quick and dirty sample below - all you need to do is:

1.  Create a new Form and name it Form1
2.  Add a FormsPlot to said Form
3.  Copy paste below code into Form1.cs 

Hope this helps.

**Example:**
```
        private readonly SignalPlotConst<double> sig;
        private int idx = 1;

        public Form1()
        {
            InitializeComponent();
            var values = Enumerable.Range(0, 1_000_000).Select(v => double.NaN).ToArray();
            values[0] = 3;
            this.sig = new SignalPlotConst<double>();
            sig.MaxRenderIndex = 0;
            sig.Ys = values;
            this.formsPlot1.Plot.Add(sig);
            this.formsPlot1.Refresh();
            var timer = new Timer
            {
                Interval = 100
            };

            timer.Start();
            timer.Tick += TimerOnTick;
        }

        private void TimerOnTick(object? sender, EventArgs e)
        {
            var rand = new Random().Next(-10, 10);
            // update a single point
            sig.Update(idx, rand);
            sig.MaxRenderIndex = idx;
            formsPlot1.Plot.Benchmark();
            formsPlot1.Plot.AxisAuto();
            formsPlot1.Refresh();
            this.idx += 1;
        }
```

**Comment by swharden** [comment]
This is a great question and a common use case which isn't supported well in ScottPlot

I'm going to prioritize working on a "data logger" plot type which has optimizations of signal plots but is designed for growing data. 

* #2377

In the mean time, there are some suggestions for growing datasets on the FAQ page

* https://scottplot.net/faq/live-data/
