### ISSUE TITLE
ScottPlot5: Document dependencies on Linux (and MacOS)

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#2366]
I _believe_ most people should be able to get away with just `dotnet add package SkiaSharp.NativeAssets.Linux`.

However, based on the discussion in the discord from Jakub, in docker it looks like you need to include this in your dockerfile:
```
RUN apt-get update
RUN apt-get install -y libfreetype6
RUN apt-get install -y libfontconfig1
RUN apt-get install -y fontconfig
```

Taking care to ensure this runs in whichever stage is deployed, rather than intermediate build stages or CI.

**Comment by jakubbloksa** [comment]
I would like to add, that it is possible that only fontconfig is really needed (haven't tested it, yet). Additionally, I had a problem when I added mentioned code snippet in dockerfile as it was. For me, it was needed to put it in the final step 
```FROM base AS final```. Also, the package might differ based on what version od .NET sdk image you are using and if it's Debian vs Alpine. Seen that here https://stackoverflow.com/questions/74063162/deploy-skiasharp-on-a-container-running-net-6-alpine-linux
