### ISSUE TITLE
Blury Chart

### ISSUE THREAD

**Issue by Barros32** [ScottPlot/ScottPlot#2370]
## Bug Report

**Issue:** I have a blury chart and don't know why.
 If I open the same chart in a new window using "Open a new window" the chart in the new window looks OK, check the picture below:
![Capture](https://user-images.githubusercontent.com/47422259/215124186-770e86df-c824-498f-841b-b9b5ce081121.PNG)

```cs

        public PlcTagSignalChart()
        {
            InitializeComponent();

            Plot = Chart.Plot;
            Plot.Title("PlcTag Chart");

          
            // sample data
            double[] sin = DataGen.Sin(51);
            double[] cos = DataGen.Cos(51);

            // plot the data
            var y1 = Plot.AddSignal(sin,label:"Tag 1");
            var y2 = Plot.AddSignal(cos,label:"Tag 2"); 

            Plot.Margins(0, 0);

            Plot.Style(ScottPlot.Style.Light1);

            var legend = Plot.Legend(enable: true);
            legend.Orientation = ScottPlot.Orientation.Vertical;

            Chart.Configuration.DpiStretch = false;
            Chart.Configuration.Quality = ScottPlot.Control.QualityMode.High;

            Plot.XLabel("T[s]");

            Chart.Refresh();

        }



XAML

<UserControl x:Class="ProjectX.UI.App.PlcTagSignalChart"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:ProjectX.UI.App"
             mc:Ignorable="d" 
             d:DesignHeight="200" d:DesignWidth="800" BorderThickness="{StaticResource SharedBorderThickness}" BorderBrush="{StaticResource SharedBorderColor}" Margin="1">

    <Grid>
        <WpfPlot x:Name="Chart" />
    </Grid>

</UserControl>


```

### System Details
* **ScottPlot Version:** 4.1.60
* **Operating System:** Windows 10
* **Application Type:**  WPF
* **.NET Version:** NET 6

**Comment by Barros32** [comment]
After adding a border thinkness to container control works!

<UserControl
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:ProjectX.App.Controls"
             xmlns:ViewModels="clr-namespace:ProjectX.App.ViewModels" 
             x:Class="ProjectX.App.Controls.SignalChartContainer"
             mc:Ignorable="d" Style="{StaticResource UserControlBase}" Margin="1" BorderBrush="{StaticResource SharedBorderColor}" BorderThickness="{StaticResource SharedBorderThickness}">
   
    <UserControl.DataContext>
        <ViewModels:SignalChartContainerVM/>
    </UserControl.DataContext>

    <Grid>
        <ScrollViewer>

            <ItemsControl ItemsSource="{Binding Charts}"/>

        </ScrollViewer>
    </Grid>

</UserControl>

**Comment by swharden** [comment]
I wonder if the problem was `Margin="1"` squeezing the chart smaller than it wants to be and making it blurry?

**Comment by axiba04** [comment]
I also encountered a similar problem, in a usercontrol, I placed a UniformGrid, in which there are 4 wpfPlot, when I change the Columns property of the UniformGrid, the 4 wpfPlot seem to have different clarity.

**Comment by axiba04** [comment]
![2024-09-21_172431](https://github.com/user-attachments/assets/07ae0e09-7cbf-4048-8955-13800e99435e)
![2024-09-21_172631](https://github.com/user-attachments/assets/df5b490c-620a-4cfa-a6c6-14fd4bbf6915)
These are the pictures shown.

**Comment by axiba04** [comment]
<UserControl
    x:Class="TestMachine.Views.TestView"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:ScottPlot="clr-namespace:ScottPlot.WPF;assembly=ScottPlot.WPF"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="clr-namespace:TestMachine.Views"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:s="https://github.com/canton7/Stylet"
    xmlns:telerik="http://schemas.telerik.com/2008/xaml/presentation"
    xmlns:tools="clr-namespace:TestMachine.Tools"
    d:DesignHeight="900"
    d:DesignWidth="1600"
    mc:Ignorable="d">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="80" />
            <RowDefinition Height="2.5*" />
            <RowDefinition />
            <RowDefinition />
        </Grid.RowDefinitions>
        <UniformGrid Grid.Row="1" Columns="2">
            <ScottPlot:WpfPlot />
            <ScottPlot:WpfPlot />
            <ScottPlot:WpfPlot />
            <ScottPlot:WpfPlot />
        </UniformGrid>
    </Grid>
</UserControl>

**Comment by axiba04** [comment]
``` xaml
<UserControl
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:ProjectX.App.Controls"
             xmlns:ViewModels="clr-namespace:ProjectX.App.ViewModels" 
             x:Class="ProjectX.App.Controls.SignalChartContainer"
             mc:Ignorable="d" 
             Style="{StaticResource UserControlBase}" 
             Margin="1" 
             BorderBrush="{StaticResource SharedBorderColor}" 
             BorderThickness="{StaticResource SharedBorderThickness}">
   
    <UserControl.DataContext>
        <ViewModels:SignalChartContainerVM/>
    </UserControl.DataContext>

    <Grid>
        <ScrollViewer>
            <ItemsControl ItemsSource="{Binding Charts}"/>
        </ScrollViewer>
    </Grid>

</UserControl>
```
