### ISSUE TITLE
Histograms - handling of outliers

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2387]
Hi!
Just a quick question: how does the recent histogram implementation handles outliers data? So when I manually set min and max limits, and i get values outside this interval.
I did not find info regarding this here: https://scottplot.net/cookbook/4.1/category/statistics/#histogram

For sure i can check it in the code, but i thought i might ask as well here :)
Thanks very much! :)

**Comment by bukkideme** [comment]
As I see inside the Common.cs, that the outliers are skipped if the min/max are fixed values. I wonder, if optionally we could not skip outliers, but either increase the first (if val < min) or the last bin (if val > max) counts. In such case, we could indicate maybe in a out bool parameter whether the histogram got "clipped". Then the next question would be that, how we could nicely indicate that we have outliers.

Hmm, maybe a better approach is to keep skipping the outliers, but at least return their counts, like "int countBelowMin", "int countAboveMax". Having at least these values, we can let the user decide how it should be indicated in the chart that we have counts outside the pre specified range...?
What do you think?

```
// place values in histogram
            double[] hist = new double[binCount];
            for (int i = 0; i < values.Length; i++)
            {
                if (values[i] < min || values[i] > max)
                {
                    continue;
                }

                if (values[i] == max)
                {
                    hist[hist.Length - 1] += 1;
                    continue;
                }

                double distanceFromMin = values[i] - min;
                int binsFromMin = (int)(distanceFromMin / binWidth);
                hist[binsFromMin] += 1;
            }
```

**Comment by bukkideme** [comment]
Interesting how they handle the outliers in LabVIEW, "outside" cluster:

[https://www.ni.com/docs/en-US/bundle/labview/page/ptbypt/general_histogram_ptbypt.html](https://www.ni.com/docs/en-US/bundle/labview/page/ptbypt/general_histogram_ptbypt.html)

**Comment by swharden** [comment]
> For sure i can check it in the code, but i thought i might ask as well here :)

I have to check the code to answer this too 🙃 

> Interesting how they handle the outliers in LabVIEW

I haven't looked at the code yet, but typically I aim to mimic behavior of Python's numpy and/or matplotlib

* https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html
* https://jiffyclub.github.io/numpy/reference/generated/numpy.histogram.html
* https://stackoverflow.com/questions/15837810/making-pyplot-hist-first-and-last-bins-include-outliers

> check the code

~~Ah! It looks like there's an optional argument that indicates what to do with outliers. I think this answers your question, but if not feel free to re-open this issue.~~

https://github.com/ScottPlot/ScottPlot/blob/3bbae635ac4ef0b8d61292c07fd3a84753b3dc70/src/ScottPlot4/ScottPlot/Statistics/Histogram.cs#L77-L87

but, whoops! That module is marked obsolete... looking deeper

https://github.com/ScottPlot/ScottPlot/blob/3bbae635ac4ef0b8d61292c07fd3a84753b3dc70/src/ScottPlot4/ScottPlot/Statistics/Common.cs#L335-L344

It looks like this method does not have that optional argument to control behavior of outliers.

Presently they are ignroed:
https://github.com/ScottPlot/ScottPlot/blob/3bbae635ac4ef0b8d61292c07fd3a84753b3dc70/src/ScottPlot4/ScottPlot/Statistics/Common.cs#L370-L373

If you'd like to create a PR that adds an extra argument to cause outliers to accumulate in the edge bins, I'd be happy to merge it!

**Comment by bukkideme** [comment]
Since the Common and Common.Histogram are static, so I cannot make public fields/props to access outlier counts for the user. I think the static Histogram() method could have two optional out arguments:  minOutliers, maxOutliers.
