### ISSUE TITLE
Best practice to have minimal and fixed gap between Figure and Data rectangle (Winform)

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2394]
I hope someone knows a nice approach for this.
This is also a Winform question, about docking and scaling of a control in the UI.
I would like to have a dynamic Winform window, for this I use splitContainers, so that the ScottPlot formsPlot control is Dock=Fill inside the dynamic splitContainer Panel. 
This works nice, however when the main Winform window is not XY scaled as the Data area in the formsPlot, of course we will have empty gaps at left and right inside the Figure rectangle, for example.
I wonder what is the best practice in such case? My goal is that, the plot should fill the largest possible area, but not having plot parts are very far at left and right for example when the full data is zoomed to be shown.

I am reading about https://scottplot.net/cookbook/4.1/category/layout/#data-margins , but I am not sure if this will be a real fix for my issue...?
I paste here some screenshots, to explain what I am dealing with.
Maybe instead of the Dock=Fill option, I should use an other control accommodation option in the splitcontainer panel? 
thanks for any suggestions! :)

First screenshot shows an ideal aspect ratio of the Form window, so the data and figure rectangles are nicely matching in aspect ratios.
Second example is showing the general case.

![image](https://user-images.githubusercontent.com/51174971/219701822-1a039398-5fae-44ee-a8df-656391a492f8.png)

![image](https://user-images.githubusercontent.com/51174971/219702785-f962c887-3ab2-4960-8ea0-149d7bf42f00.png)

**Comment by StendProg** [comment]
1. Do you want your `FormsPlot.DataRect` always stay square?
2.  To whom do you want to give the freed space on the sides in example 2? Other controls or the `Formsplot.FigureRect`.

The simplest way is to calculate the aspect ratio for the FormsPlot in the ideal case. And then, in the parent container's resize handler, set the FormsPlot size to preserve ideal aspect ratio. This won't work perfectly (the size of the FigurePanels depends on the text).

If you go further, you can dynamically repeat all layout calculations that are made inside the FormsPlot.Plot and calculate the ideal Aspect Ratio every time on the fly (the key element is that DataReсt must be square), and adjust the size of the control with this aspect ratio.

**Comment by bukkideme** [comment]
Hi!

Thanks for the hints!
Some feedback:
1. DataRect should be in the same aspect ratio as the heatplot inside.
2. I can give the freed space to the formsplot FigureRect, and i will deal with how to better size the splitcontainer panels later. What is important, i want to have the axis and the colorbar "attached" to the sides of the DataRect. I wonder what would be the best trick to get this effect: the X, the Y and the Colorbar should be always at the sides of the DataRect exactly.

**Comment by StendProg** [comment]
If you are ready to give extra space to the Figure, then this is easy to do using `Plot.ManualDataArea`
say you have:
FormsPlot.Width
FormsPlot.Height
TitlePanelMaxHeight
LeftAxisPanelMaxWidth
BottomAxisPanelMaxHeight
RightColorBarMaxWidth
heatPlotAspectRatio say 2
```c#
DataAreaWidth = FormsPlotWidth - LeftAxisPanelMaxWidth - RightColorBarBaxWidth;
DataAreaHeight = FormsPlotHeight - TitlePanelMaxHeight - BottomAxisPanelMaxHeight;


if (DataAreaWidth >= DataAreaHeigth * heatPlotAspectRatio)
{

 extraWidth = DataAreaWidth - DataAreaHeight * heatPlotAspectRatio;
 extraHeight = 0;
}
if (DataAreaWidth < DataAreaHeight * heatPlotAspectRatio)
{
  extraHeight = DataAreaHeight / heatPlotAspectRatio;
  extraWidth = 0;
}

Plot.ManualDataArea(
left: LeftAxisPanelMaxWidth + extraWidth,
right: RightColorBarMaxWidth,
top: TitlePanelMaxHeigh,
bottom: bottomAxisPanelMaxHeight + extraHeight)
// or you can add half of extra space to both top and bottom, left and right
```

All you need is to decide on the maximum allowable panel sizes suitable for your numbers. And add these calculations to the Formsplot resizing handler. Also in a function that generates a hetmap and can change its aspect ratio.

**Comment by bukkideme** [comment]
@StendProg , thanks for the example! I will try to find time, and give feedback how it worked :)
thanks again!

**Comment by swharden** [comment]
Thanks for helping with this one [StendProg](https://github.com/StendProg)!

> I will try to find time, and give feedback how it worked :)

If you are unable to reach a solution, feel free to re-open this issue and we can take a closer look together 🚀
