### ISSUE TITLE
Mouse UP Event not Firing

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2406]
## Bug Report

**Issue:** Mouse UP Event not Firing (and Mouse Click as well)

Mouse Event which is a basic event of any object does not fire the MouseUp Event. Basic Events should be triggered in any case. New events could be introduced instead. There are two extra mouse events PlottableDragged, and PlottableDrop, but no PlottableMouseUp and PlotableMouseDown. Developers expect normal events to stay at their disposal and not to be consumed by internal component logic. I understand,  that PlottableDrag and Drop were probably introduced to help users to implement drag-drop.
However, there are tons of drag-drop examples using standard DragEnter, DragOwer, DragDrop, and DragLeave events.

I would like to use LeftMouseEvents the following way.
(I had to get rid of the right mouse click because I don't want Plot logic displaying options that make no sense for my program.)
I want to use LeftMouse Down and Up Events to implement panning (in the case where points down and up are more than 3 pixels apart) and provide my business logic when points down and up are equal or less than 3 pixels apart.
My program is written in vb.net
Any chance to getting Mouse UP Event at my disposal?

### System Details
* **ScottPlot Version:** 4.1.123?
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** net 4.7

**Comment by dusko23** [comment]
From good programming practice, I would tag it as a bug in the concept of how events are presented to the end developer.
From a general perspective is a suggestion/future request.
Hope this clarifies my contribution.

**Comment by bclehmann** [comment]
You mentioned `PlottableDrag` and `PlottableDrop`, which are specifically for when a plottable (e.g. a point on a scatterplot) is dragged/dropped. Are you asking for an event that fires when a plottable is clicked?

If you're just looking for knowing when the plotting window is clicked then you should be fine with [`FormsPlot.MouseUp`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.mouseup?view=windowsdesktop-7.0) which is inherited by all WinForms controls.

In fact, this is enough to implement logic that fires when a plottable is clicked, you can listen for normal mouse events on the FormsPlot control and then loop through the plottables checking if they're under the mouse. All draggable plottables (those that implement `IDraggable`) have an `IsUnderMouse` method that you can use. It's obviously less convenient than a first-party solution baked into the library, but it should be capable of what I think you're asking.

**Comment by dusko23** [comment]
Thanks for your comment.
The thing is that your suggestion
![image](https://user-images.githubusercontent.com/26789352/220273679-507e75e6-ee49-480b-a94a-96388bc66ed5.png)
does not work. The event is not fired.
And that is the problem I am seeking a solution to in the first place.
Are there any reasons why the MouseUp event (inside the control) might not be fired?
MouseDown and MouseMove work as expected,

**Comment by bukkideme** [comment]
It works fine for me...maybe there is some other issue in your code?
```
private void formsPlot1_MouseUp(object sender, MouseEventArgs e)
        {
            MessageBox.Show("formsPlot1_MouseUp() event fired!");
        }
```

![image](https://user-images.githubusercontent.com/51174971/220338129-7cc2f818-3557-4886-8262-8835aff02f2f.png)

**Comment by dusko23** [comment]
Thanks all for the suggestions.
It was my bad :-(
In a desperate attempt to get rid of the right button click popping out of the context menu I removed the mouse-up event handler and forgot about it. All is working fine now.
If anybody could provide a code snippet in vb.net to get rid of the context menu would be just great.

**Comment by Xerxes004** [comment]
Check out [this snippet](https://github.com/ScottPlot/ScottPlot/blob/065383a3b6182e35edbe39c2606528bd147bb013/src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/FormsPlotConfig.cs#L77-L90) from the WinForms demo, it probably does exactly what you need.

```C#
private void InitializeRightClickMenu()
{
    // remove both possible right-click actions
    formsPlot1.RightClicked -= formsPlot1.DefaultRightClickEvent;
    formsPlot1.RightClicked -= CustomRightClickEvent;


    if (cbRightClickMenu.Enabled == false)
        return;


    if (cbCustomRightClick.Checked)
        formsPlot1.RightClicked += CustomRightClickEvent;
    else
        formsPlot1.RightClicked += formsPlot1.DefaultRightClickEvent;
}
```

**Comment by dusko23** [comment]
I tried to replicate a code snippet but I can not access formsPlot1.RightClicked
Here is my code in VB.net
My Plot object is named pathPROFILE.

![image](https://user-images.githubusercontent.com/26789352/220573322-cece9cb9-746d-4b7c-8e26-ba7dacf72ea7.png)

Neither can be found in Configuration
![image](https://user-images.githubusercontent.com/26789352/220576099-b82c1356-eca2-4f0e-9434-222f7d28a038.png)

I am not sure what I am missing here.
A working example in vb.net using a Plot object in design time is very welcome.

**Comment by Xerxes004** [comment]
@dusko23 check this out and see if it helps. I was able to remove the default right click event and add my own using the following code. I would recommend checking out the [official Microsoft documentation](https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/events/#addhandler-and-removehandler) for how to add and remove event handlers from your controls.

```VB.NET
' MyForm.vb
Imports ScottPlot

Public Class MyForm
    Private Sub MyForm_Load(sender As Object, e As EventArgs) Handles MyCoolPlot.Load
        RemoveHandler MyCoolPlot.RightClicked, AddressOf MyCoolPlot.DefaultRightClickEvent
    End Sub

    Private Sub MyForm_RightClick(sender As Object, e As EventArgs) Handles MyCoolPlot.RightClicked
        MessageBox.Show("This is a custom right-click action")
    End Sub
End Class
```

**Comment by dusko23** [comment]
Thanks, that worked like charm.
![image](https://user-images.githubusercontent.com/26789352/220672856-095f0742-5aac-4e58-90f0-1da6e0a2785c.png)

The issue was that the Plot object does not reveal all events in design time.
![image](https://user-images.githubusercontent.com/26789352/220675524-8f65ffa8-6df7-45ec-b017-91b7dfd5dcd1.png)
I would like to learn why.

So, this was a sort of blind date :-) 
I do use adding and removing handlers a lot. 
Thanks
