### ISSUE TITLE
Pie: Refresh() throws argument exception when called from inside a WPF initializer

### ISSUE THREAD

**Issue by KC7465128305** [ScottPlot/ScottPlot#2415]
The following is the three lines of code:

```cs
double[] values = { 778, 283, 184, 76, 43 };
WpfPlot1.Plot.AddPie(values);
WpfPlot1.Refresh();
```

When `WpfPlot1.Refresh()` is called is when the program throw the exception.

I am using version 4.1.60

**Comment by KC7465128305** [comment]
Note that it only crashes when plotting a Pie chart.  I don't have any issue when plotting a Scatter, Signal, Bar or  BarSeries chart for example.

**Comment by swharden** [comment]
Hi @KC7465128305, thanks for reporting this! I successfully reproduced this error in the WPF control (note that it doesn't affect other controls).

It seems this error is caused when the WPF control calls `Refresh()` inside the window's constructor, before it's had a chance to be displayed and properly measured.

An immediate fix is to call `Refresh()` after the window finishes loading. The following code works, but I'll see if I can come up with something more elegant:

```cs
using System.Windows;

namespace WpfApp;

/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        double[] values = { 778, 283, 184, 76, 43 };
        WpfPlot1.Plot.AddPie(values);
        this.Loaded += (s, e) => WpfPlot1.Refresh();
    }
}
```

**Comment by KC7465128305** [comment]
Thanks very much!!!
