### ISSUE TITLE
SP5: Cache typefaces to improve Linux performance

### ISSUE THREAD

**Issue by nightfog-git** [ScottPlot/ScottPlot#2419]
Hello, 
I'm experiencing some problems with ScottPlot version 5 on linux, the rendering time is too big. If you enable the performance meter with double click, it shows 70-100 ms time and 10-15 fps on an empty plot. To run on linux I use an Avalonia gui, with custom-made control (this is not important, the root of the bug is plot.Render(SKSurface).
You may found a reproduction sample application on [this repo](https://github.com/nightfog-git/ScottPlot-AvaloniaTest).

I've looked at the code and conclude, that `Extensions/SkiaSharpExtensions -> ApplyToPaint(this FontStyle fontStyle, SKPaint paint)` is the root of the problem, and the exact call is `SKTypeface.FromFamilyName(fontStyle.Name, skfs)`.
For some unknown reason this call takes about 4ms, and that function is called by axes measure and panel rendering 17 times each rendering time!
To test my assumptions, I've replaced the var assignment with 
`SKTypeface typeface = (_typeface == null) ? SKTypeface.FromFamilyName(fontStyle.Name, skfs) : _typeface;`
and declared a static _typeface nearby at class level (`private static SKTypeface? _typeface = null;`). That is, I just cached the call's result. And, it began to work as expected! The frame rate became the same as I saw on Windows, 200+.
So, it seems some caching layer is needed to negate the slow call on Linux. I don't know the reasons, but I've checked that on two different distributions with the same outcome.

### System Details
* **ScottPlot Version:** 5.0.1-beta
* **Operating System:** Ubuntu Linux 22.04.1 LTS, ArchLinux current
* **Application Type:** Avalonia (actually didn't matter)
* **.NET Version:** .NET 6.0, 7.0

**Comment by StendProg** [comment]
HI @nightfog-git,
The requested font may not be available on your system. The search takes a long time and eventually returns the default font.
Check that the requested and returned font match. Try changing the requested font to one that is exactly on your system.

**Comment by nightfog-git** [comment]
I've checked that, the requested one is Numbus Sans, and `SKTypeface.FromFamilyName` returns the object with the same `FamilyName`. The font file is physically present in /usr/share/fonts/gsfonts.

**Comment by swharden** [comment]
Thanks for reporting this @nightfog-git! 

For added context, the `SKTypeface.FromFamilyName()` call here is what you say is slow on Linux:

https://github.com/ScottPlot/ScottPlot/blob/8bf79deee6501d4bcdd7e1548034444cb9d43bda/src/ScottPlot5/ScottPlot5/Extensions/SkiaSharpExtensions.cs#L91-L102

ScottPlot 5 has a static FontService class:

https://github.com/ScottPlot/ScottPlot/blob/ebde30ccb26dc2bacc2c9cc97e90bbe9bcb3c055/src/ScottPlot5/ScottPlot5/FontService.cs#L1-L68

It sounds like we could extend it by adding a system to call `SKTypeface.FromFamilyName()` and cache the results, then ensure that all font code only retrieves `SKTypeface` through that caching service.

It may take me a few days to get to it, but I'll definitely work to improve this! When it's ready to try I'll follow-up here and you can confirm whether or not performance on Linux improved. Thanks again for reporting this issue!

**Comment by swharden** [comment]
Related, some of these font services fail in some configurations of .NET Framework apps (e.g., in VS designer, #2491)

When this topic is investigated further, .NET Framework 4.6.2 tests should be added to ensure everything works

It may be worth considering whether or not to keep supporting .NET Framework in ScottPlot 5 🔥 

We should at least wrap DLL calls like these in exception handlers so they fail with a more descriptive error message indicating how to fix it (e.g., target .NET Core)

![image](https://user-images.githubusercontent.com/4165489/229324099-465c953e-a283-4429-ae8c-7cd72816565e.png)
