### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2425]
Hi!

Just a question: when is the next nuget release for 4.1 planned? Just curious :) 
thanks!

**Comment by swharden** [comment]
Probably today or tomorrow 🤞

It's not very planned ... Just sort of whenever the changelog is getting thick and when all the biggest fires have been put out 😅

**Comment by swharden** [comment]
Actually I have a better answer.

I'm trying to close-out all the open issues tagged "next up" before I push the next release
