### ISSUE TITLE
PopulationPlot: throws on Resize

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2429]
### Discussed in https://github.com/ScottPlot/ScottPlot/discussions/2384

<div type='discussions-op-text'>

<sup>Originally posted by **Sprenk** February 11, 2023</sup>
PopulationPlot throws on Resize - works fine at larger plot areas, but not smaller (both are reasonable)

PopulationPlot Renders OK, but will throw an exception when form is resized a bit smaller

**I confirm the data is fine...** about 320 points per group, and the datapoints are floatinpoint numbers around e-5 with variation that starts to drop from 0.5% to 0.05%... not sure if that is an issue... and I Have about 10 groups.  Data Looks fine... but  the plot will render fine with say 500x800 or so... but if it is resized to 200 by 300  - hard to tell, but it will except... 

I can also reproduce if I clear and add populations at the 200x300 size or so... and I've added one of the latter groups, so **it seems to be a function of a tight grouping of elements**?  I'm also plotting the distribution cureve and the standard dev bars

I can catch the exception in the latter case, but don't know how to catch in the resize case **(Version 4.1.60 for winforms)**

```xaml
<PackageReference Include="ScottPlot.WinForms" Version="4.1.60" />
```

```
GRPC-Debugger Error: 0 : **System.ArgumentException: Parameter is not valid.**
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawLines(Pen pen, PointF[] points)
   at ScottPlot.Plottable.PopulationPlot.Distribution(PlotDimensions dims, Bitmap bmp, Boolean lowQuality, Population pop, Random rand, Double popLeft, Double popWidth, Color color, Position position, LineStyle lineStyle)
   **at ScottPlot.Plottable.PopulationPlot.Render(PlotDimensions dims, Bitmap bmp, Boolean lowQuality)**
   at ScottPlot.Plot.RenderPlottables(Bitmap bmp, Boolean lowQuality, Double scaleFactor)
   at ScottPlot.Plot.Render(Bitmap bmp, Boolean lowQuality, Double scale)
   at ScottPlot.Control.ControlBackEnd.Render(Boolean lowQuality, Boolean skipIfCurrentlyRendering)
   at GRPC_Debugger.Plotting.LearnForm.PlotPerformance() in D:\Code\ssd_workbench\GRPC-Debugger\Plotting\LearnForm.cs:line 86
```

</div>

**Comment by swharden** [comment]
Hi @Sprenk, I was able to reproduce this issue using the following code.

```cs
using System;
using ScottPlot;
using System.Windows.Forms;

namespace WinFormsApp
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            Random rand = new(0);
            var popSeries = new ScottPlot.Statistics.PopulationSeries[10];
            for (int i = 0; i < popSeries.Length; i++)
            {
                double[] values = DataGen.RandomNormal(rand, 320);
                ScottPlot.Statistics.Population[] populations = { new(values) };
                popSeries[i] = new(populations, $"Pop {i + 1}");
            }

            var multiSeries = new ScottPlot.Statistics.PopulationMultiSeries(popSeries);

            formsPlot1.Plot.AddPopulations(multiSeries);
            formsPlot1.Refresh();
        }
    }
}
```

PS: The population plot API is incredibly confusing 😝 I hope we can make this a lot more straightforward in the ScottPlot5!

**Comment by Sprenk** [comment]
Thanks so much Scott!
I worked on a project similar to yours years ago and really appreciate your
api and how well it works.  Thanks for the quick turn around!

Ciao,

Rick Sprenkle

Rick Sprenkle
Adjunct Professor - Endicott University - ***@***.*** - +1
978.821.7404 cell
Software Engineering | Advanced Web Development | Managing Information
Systems | Network Security
