### ISSUE TITLE
Heatmap: Improve support for datasets with >10M columns

### ISSUE THREAD

**Issue by leGusz** [ScottPlot/ScottPlot#2438]
How can I  create a heatmap beyond 10 Million values?  Using a very large dataset of size similar to 32k x 26k columns and rows
In this example I am using some random data created and I commonly find this exception

![code_sample_VB net](https://user-images.githubusercontent.com/126713697/222243805-460b9f9d-b50a-4eb7-8ebd-d74922936a81.JPG)

Addtitionally, I attach an example of a very large dataset 

https://drive.google.com/drive/folders/1nTLX5hkQowqwnaogATYP6nts5pjOfxZi?usp=sharing

**ScottPlot Version: 4.1

**Operating System: Win 10

**Application Type: Winforms, VB.net

**Comment by swharden** [comment]
Hi @leGusz, 

Right now the best way to do this is to down-scale the data yourself before plotting it as a heatmap.

Here's an example downscaling function:
https://github.com/ScottPlot/ScottPlot/pull/2497#issuecomment-1475277336

A half-size downscaling option was recently added:
* #2497

If someone creates one with more features (e.g., arbitrary scaling size) I'd be happy to merge it in! I created an issue to track progress there: #2518

**Comment by leGusz** [comment]
Thank you very much, I am really enjoying ScottPlot, your support and the community are awesome. I will try this method to downscale the data before plotting
