### ISSUE TITLE
Heatmap: How to display log-scaled data (with colormap)?

### ISSUE THREAD

**Issue by DevJins** [ScottPlot/ScottPlot#2440]
I want to express it in Scottle plot like the picture below. I tried referring to the sample code, but it doesn't seem to work.

![image](https://user-images.githubusercontent.com/96853438/222315467-d67d808d-67df-4298-8d49-fa992c71cf03.png)

list
1. The name of XAxis2 is fixed. (ex : 1u, 10u, 100u, 1m, 10m 100m, 1)
2. Type is log scale.
3. Background color is expressed in a specific range (ex : 1u~12u → green,  12u~8m → yellow ...)

I've been trying this and that for the 2day, but I can't find a way.

---------------------------------
**ScottPlot Version: 4.1

**Operating System: Win 11

**Application Type: Winforms

**Comment by swharden** [comment]
Thanks for this question @DevJins! I'll follow-up in a few days and hopefully have a solution 🤞 

Note that I'm using this function to help me create sample data:

```cs
// create sample heatmap data with values from 0 to 10M
double[,] data = ScottPlot.DataGen.SampleImageData();
for (int i = 0; i < data.GetLength(0); i++)
    for (int j = 0; j < data.GetLength(1); j++)
        data[i, j] *= 100_000_000;
```

**Comment by DevJins** [comment]
I found a way.

# Field
private List<TestProperty> listTest;

# Contructor void Form1()
            listTest= new List<TestProperty>();
            listTest.Add(new TestProperty() { minColor = -6.0, maxColor = -4.5, colorType = Color.Green });
            listTest.Add(new TestProperty() { minColor = -4.5, maxColor = -2.3, colorType = Color.Yellow });
            listTest.Add(new TestProperty() { minColor = -2.3, maxColor = -1.0, colorType = Color.Orange });
            listTest.Add(new TestProperty() { minColor = -1.0, maxColor = 1, colorType = Color.Red }); 


# Method void ViewPlot()

            pltBottom.YAxis.Ticks(false);
            pltBottom.YAxis.Grid(false);

            pltBottom.Grid(onTop: true);
            frmPlotBottom.Reset(pltBottom);

            List<double> logXs1 = new List<double>() { 0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 1 };
            List<double> logYs = new List<double>() { 0, 0, 0, 0, 0, 0, 0 };

            pltBottom.XAxis.TickLabelFormat((double x) => ConvertSI(x));

            foreach (var item in listTest)
            {
                pltBottom.AddHorizontalSpan(item.minColor, item.maxColor, item.colorType);
            }
            double value = Math.Log10(0.000178);
            pltBottom.AddMarker(value, 0, MarkerShape.filledTriangleUp, 20, Color.Black);

            pltBottom.XAxis.MinorLogScale(true);
            pltBottom.XAxis.MajorGrid(true, Color.FromArgb(80, Color.Black));
            pltBottom.XAxis.MinorGrid(true, Color.FromArgb(50, Color.Black));
            pltBottom.XAxis.MajorGrid(true, Color.FromArgb(80, Color.Black));

            pltBottom.SetAxisLimits(-6.0, 0, 0, 1);

            frmPlotBottom.Refresh();


# Method string ConvertSI(double data)

            double convertData = Math.Pow(10, data);

            char[] incPrefixes = new[] { 'k', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y' };
            char[] decPrefixes = new[] { 'm', '\u03bc', 'n', 'p', 'f', 'a', 'z', 'y' };

            int degree = (int)Math.Floor(Math.Log10(Math.Abs(convertData)) / 3);
            double scaled = convertData * Math.Pow(1000, -degree);

            char? prefix = null;
            switch (Math.Sign(degree))
            {
                case 1: prefix = incPrefixes[degree - 1]; break;
                case -1: prefix = decPrefixes[-degree - 1]; break;
            }

            return scaled.ToString() + prefix;


# Class class TestProperty

        public double minColor { get; set; }
        public double maxColor { get; set; }
        public Color colorType { get; set; }


* Thanks it helped a lot.
* result
![image](https://user-images.githubusercontent.com/96853438/222376849-abaada87-5187-4643-bef6-1f3d41691d63.png)
