### ISSUE TITLE
Demo: cookbook button throws exception

### ISSUE THREAD

**Issue by FannyAtGitHub** [ScottPlot/ScottPlot#2443]
Hi!

I downloaded the latest ScottPlot WinForms demo and unfortunately the integrated 'Launch ScottPlot Cookbook' demo won't work. There is an exception because the System.Drawing.Common.dll seems to be old. (Requires verion 5.0.0.0 but the zip-File contains only 4.6.x). 
![image](https://user-images.githubusercontent.com/126788297/222446179-f046a8c0-5198-439b-afc1-7d3f5d628a25.png)

I guess you can fix this easily and fast. :)

Cheers,
Fanny

**Comment by swharden** [comment]
I think I narrowed this down to an issue loading the icon file.

Note that this project multi-targets .NET 6 and .NET Framework 4.8, and I was testing the .NET 6 version, but the deployment script was packaging and deploying the .NET Framework version to the website which is what this bug sneak through

![image](https://user-images.githubusercontent.com/4165489/222584747-3aeadd70-33bd-457a-ae86-44f0e0e9900a.png)

**Comment by swharden** [comment]
Actually I think this was a problem too.

https://github.com/ScottPlot/ScottPlot/blob/181be953b0544f520a57fd29ae881ad1df02a4d6/src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/FormCookbook.resx#L60

**Comment by swharden** [comment]
I think it works now! Thanks so much for reporting this @FannyAtGitHub 

https://scottplot.net/demos/ScottPlot-Demo-WinForms.zip?nocache
