### ISSUE TITLE
Heatmap: Flip horizontally

### ISSUE THREAD

**Issue by Neopentane1** [ScottPlot/ScottPlot#2444]
**ScottPlot Version:**4.1.61

Would it be possible to include a flag for the heatmap to flip it horizontally? There is one for flipping vertically and it would be great for completeness.

**Comment by swharden** [comment]
@Neopentane1 I don't think this is possible, but it would be a great addition to ScottPlot!

Do you want to make the code change and submit it as a pull request? If so, I would be happy to review it and merge quickly so it can be in the next release!

Looking at how `FlipVertically` is implemented, I'm sure you can squeeze in a similar `FlipHorizontally` option:

https://github.com/ScottPlot/ScottPlot/blob/181be953b0544f520a57fd29ae881ad1df02a4d6/src/ScottPlot4/ScottPlot/Plottable/Heatmap.cs#L171-L174

https://github.com/ScottPlot/ScottPlot/blob/181be953b0544f520a57fd29ae881ad1df02a4d6/src/ScottPlot4/ScottPlot/Plottable/Heatmap.cs#L461-L464

Related:

* #1864 

PS: I tried flipping it like this but it did not work:
```cs
var plt = new ScottPlot.Plot(600, 400);
double[,] imageData = ScottPlot.DataGen.SampleImageData();
var hm = plt.AddHeatmap(imageData);
hm.XMax = 0;
hm.XMin = imageData.Length;
plt.SaveFig("flip.png");
```
