### ISSUE TITLE
Doctor , hlep, How to Skip null time?

### ISSUE THREAD

**Issue by gdszljl** [ScottPlot/ScottPlot#2451]
[https://github.com/gdszljl/Application/blob/master/Snipaste_2023-03-03_21-49-48.jpg](https://github.com/gdszljl/Application/blob/master/Snipaste_2023-03-03_21-49-48.jpg)
Doctor , hlep, How to Skip null time?

**Comment by bukkideme** [comment]
Hi! You can manually define axis ticks:
https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#manual-tick-labels

**Comment by gdszljl** [comment]
thinks

**Comment by gdszljl** [comment]
> Hi! You can manually define axis ticks: https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#manual-tick-labels

https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#manual-and-automatic-tick-labels

**Comment by gdszljl** [comment]
> Hi! You can manually define axis ticks: https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#manual-tick-labels

just the same, yes or no?

**Comment by bukkideme** [comment]
Both can work, try it.
