### ISSUE TITLE
2D Histogram

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2453]
We recently added a new Histogram class (#2389, #2403) but it would be great if we could achieve similar functionality in two dimensions. 

Histograms would be built by accumulating X/Y pairs into binned ranges. Histogram output could be plotted as heatmaps, with color representing the count in each 2D bin.

An example use case would be for visualizing [flow cytometry](https://en.wikipedia.org/wiki/Flow_cytometry) data

![image](https://user-images.githubusercontent.com/4165489/222923875-a710bf1a-33d2-4c15-aa9f-6af1574d10db.png)

**Comment by agillet76** [comment]
Hi,
I would love to use this feature. 
I currently developing an app in C#/Avalonia that need to represent such data set.
Are you going to implement it in a new release? 
Is there another way to do it currently with ScottPlot 4.1?

**Comment by swharden** [comment]
I got set back being sick for several weeks 🤧 but I'm starting to get better now and will be picking this up soon, possibly before the next release.

I'm curious, what is the use case for your 2D histogram? The only use case that comes to mind for me is flow cytometry, but I'm curious what others may be interested in using this for.

**Comment by agillet76** [comment]
Hi Scott,
Thanks for replying. 
I am supporting the development of an instrument control software for a microfluidic device for doing assay for drug discoveries,
We need to plot some signals data ([PMT](https://en.wikipedia.org/wiki/Photomultiplier_tube)) for each droplet detected.
I am porting a legacy application written in LabView to C#
Here is an example of a plot in labview.
![image](https://github.com/ScottPlot/ScottPlot/assets/92173569/b56aebd6-d90f-4cde-a333-d4e141f8d96e)

It is only about 5 min worth of data, we will be running the apps for  hours.
If you are curious about our technologies, check our website: https://1859.ai/

I was able to implement the plot with the current Scottplot 4.1 code
Here is a screenshot
![image](https://github.com/ScottPlot/ScottPlot/assets/92173569/c6603199-d1cb-4042-9042-6db0cde78823)

here is the code, might not be the most efficient way to do it though, so having the 2D Histogram feature available would be great.
`       var binsX = 1500;
        var binsY = 1500;
        var min = 0.0;
        var max = 5.0;

        // Calculate the bin edges for the x and y axes
        var histX = new ScottPlot.Statistics.Histogram(min, max, binsX);
        histX.AddRange(dropletsData.Select(p => p.Max1InVolts));
        double[] xEdges = histX.Bins;
        var histY = new ScottPlot.Statistics.Histogram(min, max, binsY);
        histY.AddRange(dropletsData.Select(p => p.Max2InVolts));
        double[] yEdges = histY.Bins;

        // Create an empty 2D array to store the bin counts
        // needed nullable array to represent empty bin as transparent 
        // https://scottplot.net/cookbook/4.1/category/plottable-heatmap/#heatmap-with-empty-squares
        double?[,] counts = new double?[binsX, binsY];


        // Loop through each point and increment the appropriate bin
        foreach (var point in dropletsData)
        {
            int xBin = Array.BinarySearch(xEdges, point.Max1InVolts);
            if (xBin < 0)
                xBin = ~xBin - 1;

            int yBin = Array.BinarySearch(yEdges, point.Max2InVolts);
            if (yBin < 0)
                yBin = ~yBin - 1;
            counts[yBin, xBin] ??= 0;
            counts[yBin, xBin]++;
        }
        AvaPlot.Plot.Clear();
        var heatmap = AvaPlot.Plot.AddHeatmap(counts, ScottPlot.Drawing.Colormap.Turbo);
        heatmap.Update(counts, min: 1);
        heatmap.Smooth = true;
        heatmap.FlipVertically=true; // needed to match with LabView ScatterPlot
        var cb = AvaPlot.Plot.AddColorbar(heatmap);
        cb.Label = "Droplets";
        heatmap.XMin = 0.0;
        heatmap.XMax = 5.0;
        heatmap.YMin = 0.0;
        heatmap.YMax = 5.0;
        AvaPlot.Plot.SetAxisLimits(min, max, min, max);
        AvaPlot.Plot.XAxis.SetBoundary(min, max);
        AvaPlot.Plot.YAxis.SetBoundary(min, max);`

**Comment by swharden** [comment]
I got pretty far on this tonight (#2639). It needs some work to refine the API, but we're getting pretty close! I added a cookbook example in the code base (it's not on the website or in NuGet yet), but it's looking like this:

```cs
// create the experimental plot type and add it to the plot
ScottPlot.Plottable.BinnedHistogram hist2d = new(100, 100);
AvaPlot.Plot.Add(hist2d);

// add sample data
Coordinate[] flowData = DataGen.FlowCytometry();
hist2d.AddRange(flowData);

// add a colorbar
AvaPlot.Plot.AddColorbar(hist2d.Colormap);
```

![binned-histogram](https://github.com/ScottPlot/ScottPlot/assets/4165489/52c948bc-88e9-48f9-a8f9-0c2d5e013fc5)

**Comment by swharden** [comment]
This is done now (#2639) and here's how to use it:

```cs
// create a binned histogram
var hist2d = plt.AddBinnedHistogram(100, 100);

// data is a collection of X/Y points
Coordinate[] flowData = DataGen.FlowCytometry();

// add X/Y points to the histogram
hist2d.AddRange(flowData);
```

**Comment by agillet76** [comment]
Thanks Scott.
This looks great. I will give it a try in the next few days. 
Just got back from a break.
I also excited to see the following" ScatterDataLogger: Experimental plot type for live incoming data " I am going to be tested it as well as we have the need for that type of plotting in my application ( plotting livestream of data signal from an fpga)

**Comment by swharden** [comment]
I'm re-opening this issue to track progress toward adding this plot type into ScottPlot 5
