### ISSUE TITLE
Plot.Clear does not remove Extra Y axis

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2456]
## Bug Report

**Issue:** Plot.Clear does not remove the Extra Y axis

**Reproducing:**Add one scattered plot, add another one and introduce the Extra Y axis, Clear the Plot, and populate Plot again.

Within my system, I add 3 scattered plots using the default Y axis.
Next, I add one more scattered plot introducing the new Y-axis to the left of the original one.

If I clear the Plot object and draw all 4 scattered plots I see two Extra Y axis placed left of the original Y axis.
Repeating the procedure Clear Add plots just piles up Extra Y axes to the left.
Not sure what might be an issue here. I would expect that Plot.Clear actually clears everything.
X-axis data for all 4 scattered plots are identical.

### System Details
* **ScottPlot Version:** 4.1.6.1?
* **Operating System:** Windows 10
* **Application Type:** Winforms
* **.NET Version:** 4.7

**Comment by bukkideme** [comment]
The Plot.Clear is not for axis manipulation, so it is not for removing extra axis. You can use it to clear away other plot elements. 
Imagine, you setup a certain axis configuration. After that, you plot data, and clear data regularly. Then it would be very inconvenient if the Clear() method cleared away your extra axis too. 

If you want to remove your extra Y axis, I think you just need to not add again and again new ones. If you need to hide it sometimes, you can make it invisible.

**Comment by dusko23** [comment]
It appears that it would be good to have a function to clear everything. So please treat my post as a suggestion instead of a bug.
Based on experiences of other libraries I expected that **Clear** does what its name suggests.
That not being the case a method **.ClearEverything** would be nice to have.
As far as plots are concerned there is a method **RemoveAt** 
Using the try-and-error approach I found that there is a function that removes Axes.
![image](https://user-images.githubusercontent.com/26789352/223334604-d7e167ab-553a-4481-9727-4927cc1f5199.png)
It requires an Axis itself. Giving the option to define an index as well would be nice to have (**RemoveAt**).

Your suggestion to not add it if has already been added does not work for me. As well it complicates the source code a lot.
I could use a method **.RemoveAxis** 

**Please tell me how could I get hold of an Axis object where the index is known.**

**Comment by bukkideme** [comment]
I think the existing options in ScottPlot give us total control over axis displays and handling. What feature you describe, you can easily develop yourself. 

> Your suggestion to not add it if has already been added does not work for me. As well it complicates the source code a lot.

I would then consider refactoring the code. It does not sound optimal that you add and remove axis at every new plot iteration. You setup all the axis you need, then you keep them. If you need to hide one of them, it is simple. Why would you need to remove and add again and again axis to your plot, I do not see any benefit in such approach. Maybe if you describe your application in more details, people can give a better suggestion.

> Please tell me how could I get hold of an Axis object where the index is known.

```
Axis yAxis2 = formsPlot1.Plot.AddAxis(Edge.Left);
yAxis2.Hide(); //hide or do whatever you need with this axis later!
```
Store the returned "Axis" variable in a field, or whatever is convenient for your code, so you can access the axis and have full control over it!

**Comment by dusko23** [comment]
I just did the following (the code is in VB.net) and works just fine.
Definition
![image](https://user-images.githubusercontent.com/26789352/223348591-f131cd4f-3a7f-465d-a199-642a737149bb.png)

Removing and Adding SpeedYaxis
![image](https://user-images.githubusercontent.com/26789352/223348911-55dd28c1-2dac-435a-b00d-4f40fa198d53.png)

I am new to scottplot and going through all the details it offers is too much because I need just simple functionality. Therefore I try to implement the minimum required by also following the logic of other 3rd party libraries I use.
 I use scottplot library to show gpx profile, speed, and altitude difference between gpx altitude and dmt altitude. 

I will follow your suggestion to keep the axis fixed. Thanks for the suggestion.

**There is one functionality I could not figure out.**
When the plot is populated I would like to programmatically zoom to plotables extent. After that user zooms in/out freely.
How do I do that?

**Comment by bukkideme** [comment]
> There is one functionality I could not figure out.
> When the plot is populated I would like to programmatically zoom to plotables extent. After that user zooms in/out freely.
> How do I do that?

[https://scottplot.net/cookbook/4.1/category/multi-axis/#setting-multi-axis-limits](https://scottplot.net/cookbook/4.1/category/multi-axis/#setting-multi-axis-limits)

**Comment by swharden** [comment]
Hi @dusko23 and the group! I'm a little late to this discussion, but I hope you'll find the following useful:

## Fully Reset a Plot

> It appears that it would be good to have a function to clear everything

This may do the trick!

```cs
formsPlot1.Reset();
```

## Programmatically Zoom to a Plottable's Data Area

> When the plot is populated I would like to programmatically zoom to plotables extent. After that user zooms in/out freely.
How do I do that?

```cs
// create a plottable
double[] data = DataGen.Sin(51);
var sig = formsPlot1.Plot.AddSignal(data);

// ask the plottable how large its data is
var sigLimits = sig.GetAxisLimits();

// resize the plot area according to that size
formsPlot1.Plot.SetAxisLimits(sigLimits);

// force a redraw, then users can use the mouse to pan/zoom freely
formsPlot1.Refresh();
```
