### ISSUE TITLE
Pie: how to show different text in slice labels and legend

### ISSUE THREAD

**Issue by vietanhbui** [ScottPlot/ScottPlot#2459]
**ScottPlot Version:** 4.1.52

**Operating System:** Windows

**Application Type:** WinForms

**Question:** How to custom label of legend item

I want to custom my legend from this: 
![image](https://user-images.githubusercontent.com/43196820/223342200-9e85c8ee-8876-4538-ab4a-a443e2effd6b.png)
to this:
区間1 => test1
区間2 => test2
Tks

**Comment by swharden** [comment]
Thanks for this question @vietanhbui!

I'm adding a feature to the next release to let you independently define slice labels and legend labels:

```cs
double[] values = { 778, 43, 283, 76, 184 };
string[] SliceLabels = { "Cat", "Dog", "Snake", "Frog", "Fox" };
string[] LegendLabels = { "Meow", "Woof", "Ssst", "Ribbit", "RingDing" };

ScottPlot.Plot plt = new(400, 300);

var pie = plt.AddPie(values);
pie.SliceLabels = SliceLabels;
pie.ShowLabels = true;

pie.LegendLabels = LegendLabels;
plt.Legend();
```

![image](https://user-images.githubusercontent.com/4165489/228707977-eb00c7a4-5167-4bb2-a4bd-32f02c024b63.png)
