### ISSUE TITLE
SP5: The specified window isn't an OpenGL window

### ISSUE THREAD

**Issue by chenxuuu** [ScottPlot/ScottPlot#2465]
## Bug Report

**Issue:** when I run a test project with .net framework 4.6.2 and set to build x64 taeget, it will crash

```log
System.Windows.Markup.XamlParseException:“对类型“SkiaSharp.Views.WPF.SKGLElement”的构造函数执行符合指定的绑定约束的调用时引发了异常。”
GraphicsContextException: The specified window isn't an OpenGL window
```

( I tested it is ok on .net 6.0 )

**Reproducing:** 

1. follow WPF demo in this repo, create a WPF .net framework project
2. add nuget pack to this project, version 5.0.2 beta
3. add `<ScottPlot:WpfPlot Name="WpfPlot" />` to `MainWindow.xaml`
4. add a target `x64` and change `Any CPU` to this
5. run, then crash at `InitializeComponent()`

whole project here: [ScottPlotTest.zip](https://github.com/ScottPlot/ScottPlot/files/10917496/ScottPlotTest.zip)

### System Details
* **ScottPlot Version:** 5.0.2 beta
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** .net framework 4.6.2

---

last version(5.0.1 beta) works well

**Comment by chenxuuu** [comment]
it's GLWpfControl's bug

**Comment by StendProg** [comment]
Hi @chenxuuu,

I tested it on `sandbox/wpf` and test project you provided.
Both works fine for me.
Perhaps you have problems with the OpenGL configuration on your computer.
Try to reproduce the error using WinForms control.

**Comment by chenxuuu** [comment]
@StendProg default target is `Any CPU`, change it to `x64` then you will reproduce this.

I tested on my laptop and desktop computer.

**Comment by StendProg** [comment]
@chenxuuu 
Yes, I understand what could be the problem. 
I definitely ran the build under x64 and .NetFramework 4.6.2.  Both debug and release versions. There are no any issues for me.

**Comment by chenxuuu** [comment]
https://user-images.githubusercontent.com/10357394/223733746-ef8ace0b-aaf6-41c3-ae82-0482a31ad169.mp4
