### ISSUE TITLE
Can drag a point and reload plot

### ISSUE THREAD

**Issue by YishilNota** [ScottPlot/ScottPlot#2466]
e.g.   before（10,100） after （10,80）
using drag events or something(override...)

![pic](https://user-images.githubusercontent.com/48040405/223684822-acb8f812-3d79-4b50-91c5-15ae16c25eae.png)

**Comment by YishilNota** [comment]
![pic](https://user-images.githubusercontent.com/48040405/223684822-acb8f812-3d79-4b50-91c5-15ae16c25eae.png)

**Comment by swharden** [comment]
Hi @YishilNota! I think this is possible. Check out the draggable marker cookbook demo: https://scottplot.net/cookbook/4.1/category/plottable-marker/#draggable-marker

It should be possible to set the bounding box that limits where markers can be dragged.

If you need a more custom draggable object (like a line you can bend or something) you can create a custom plot type as described on https://scottplot.net/faq/custom-plot-type/

I'm creating an issue to track updating that FAQ page to demonstrate how to create mouse-interactive custom plot types (#2528)
