### ISSUE TITLE
SP5: AxisScaleLock

### ISSUE THREAD

**Issue by StendProg** [ScottPlot/ScottPlot#2467]
## Feature Suggestion

SP5 AxisScaleLock.

This feature has not yet been implemented for SP 5.
For me, and I think many others, this is a very popular feature.
I am well aware that the to-do list for SP5 is huge.
I could work on this feature, but I don't think I'm going far from just adopting SP4 AxisScaleLock. 
Maybe there are some new ideas how to implement it in SP5?

**Comment by swharden** [comment]
Hi @StendProg! 

> to-do list for SP5 is huge

indeed 😅

You are welcome to try implementing this! I would be happy to review a PR.

PS: I'm still waiting to review #2446 until I have a longer block of free time to inspect it and continue to explore options for code sharing across controls (#2399)

> how to implement it in SP5?

I have no preference! As long as the user-facing API is simple, we can always change it later if we think of a better way.

# Related Code

For my reference, this is how ScottPlot 4 does it

https://github.com/ScottPlot/ScottPlot/blob/065383a3b6182e35edbe39c2606528bd147bb013/src/ScottPlot4/ScottPlot/Enums/EqualScaleMode.cs#L3-L44

https://github.com/ScottPlot/ScottPlot/blob/065383a3b6182e35edbe39c2606528bd147bb013/src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs#L615-L626

https://github.com/ScottPlot/ScottPlot/blob/5183ed13016ee54e680d04daac9961a6f968bc1c/src/ScottPlot4/ScottPlot/Settings.cs#L328-L380

The only difference I'd recommend for ScottPlot 5 is to have a user-facing method that accepts the enum as a single argument (not separate bool and enum).

Thanks for your work on this @StendProg! 🚀
