### ISSUE TITLE
Function GetCoordinateX does not Give Correct Result

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2468]
## Bug Report

**Issue:** **Function GetCoordinate does not give the correct result until the populated plot area is clicked.**
![image](https://user-images.githubusercontent.com/26789352/223764972-c88115b0-2ab5-4ee7-b55d-b322679166c8.png)

**Reproducing:** Open plot windows form and plot scatter plot. Please don't click the plot area. On mouse_move (no buttons pressed) calculate the X coordinate.
The result will always be NaN.
After you click the plot area mouse_move will provide the correct X coordinate.
![image](https://user-images.githubusercontent.com/26789352/223766171-4d934bef-72c5-4c08-9358-bcbbeb690c1a.png)

There may be a way around I am not aware of.
However, the calculation should give correct results without extra tricks :-)
Also, setting focus on the plot object is not available.  Like **plot.Select**

### System Details
* **ScottPlot Version:** 4.1.6.1
* **Operating System:** Win 10
* **Application Type:** (console, WinForms, WPF, Avalonia, etc)
* **.NET Version:** (NET Framework 4.7)

**Comment by swharden** [comment]
Hi @dusko23, 

> Issue: Function GetCoordinate does not give the correct result until the populated plot area is clicked.

This works as expected on my end! Can you provide code that reproduces the issue you describe?

```cs
using System.Windows.Forms;

namespace WinFormsApp
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            formsPlot1.Plot.AddSignal(ScottPlot.DataGen.Sin(51));
            formsPlot1.Plot.AddSignal(ScottPlot.DataGen.Cos(51));
            formsPlot1.Refresh();

            formsPlot1.MouseMove += FormsPlot1_MouseMove;
        }

        private void FormsPlot1_MouseMove(object sender, MouseEventArgs e)
        {
            Text = $"{formsPlot1.Plot.GetCoordinate(e.X, e.Y)}";
        }
    }
}
```

> Also, setting focus on the plot object is not available. Like plot.Select

Thanks for noting this! I don't think anyone's asked about focusing before. Do you have a suggestion for how to add this feature? This is the control:

https://github.com/ScottPlot/ScottPlot/blob/fd51846e017748ebe7af8918adaba6e78af787ec/src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs#L1-L276

**Comment by swharden** [comment]
Hi @dusko23, because of #2540 I'm about to roll this back...

The best way to prevent NaN from occurring before you plot things is as follows. Note that you can do this now with the existing library, and a code change / new release is not required:


```cs
using System;
using System.Windows.Forms;

namespace WinFormsApp
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            formsPlot1.Plot.SetAxisLimits(-10, 10, -10, 10); // set initial axis limits at least once manually

            formsPlot1.MouseMove += FormsPlot1_MouseMove;
        }

        private void FormsPlot1_MouseMove(object sender, MouseEventArgs e)
        {
            Text = $"{formsPlot1.Plot.GetCoordinate(e.X, e.Y)}";
        }
    }
}
```
