### ISSUE TITLE
Centering a Plot object on Specific Point

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2469]
**ScottPlot Version:**  4.1.6.1

**Operating System:** Windows 10

**Application Type:**  WinForms

**Question:** I would like programmatically center the plot to a point that is defined by X, Y, and Yaxix index.
The zoom level should remain the same.
How do I do that?

**Comment by swharden** [comment]
>  I would like programmatically center the plot to a point that is defined by X, Y, and YAxis index.
The zoom level should remain the same.
How do I do that?

Let me know if this doesn't do the trick

```cs
ScottPlot plt = new();
plt.AxisZoom(1, 1, 3, 2); // center on the point x=3 and y=2 with no change in zoom
```

additional optional arguments can specify X and Y axis index

If you want to create a PR to add functionality into the `Plot` module (in [Plot/Plot.Axis.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs)) I would be happy to merge it in!

```cs
// suggested functionality:
plt.AxisPanTo(3, 2); // center on the point x=3 and y=2 with no change in zoom
```

**Comment by dusko23** [comment]
**I tried this**
![image](https://user-images.githubusercontent.com/26789352/223886051-1b203dc3-aa62-4c25-921b-e9f518d5b231.png)
**and this**
![image](https://user-images.githubusercontent.com/26789352/223886464-b4e49237-e8da-49ea-9a14-937241ecc228.png)
**and this**
![image](https://user-images.githubusercontent.com/26789352/223887057-c154e0c4-bf1d-4f2e-9d73-969a8f16cfe6.png)

The event is properly triggered. X and Y are calculated correctly.
But Plot does not move :-(
Any idea?

**Comment by swharden** [comment]
Hi @dusko23, 

After panning, call `pathPLOT.Refresh()` to force a redraw. Does that solve your problem?

I'm going to close this issue because there's not code I can copy/paste to reproduce this problem, but feel free to comment if you have additional questions 👍
