### ISSUE TITLE
Dynamic Cursor Object over Entire Plot Area

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2470]
**ScottPlot Version:** 4.1.6.1

**Operating System:** Windows 10

**Application Type:**  WinForms 

**Question:** I have created a function that shows a cursor on the mouse move when the X coordinate is in a specific range.
The result looks like this:
![image](https://user-images.githubusercontent.com/26789352/223773629-cbb6d193-32a9-42a7-b684-4881f07868e4.png)
Cursor lines are constructed using labels.
Is there a more elegant way to implement a similar effect?
Pushing labels around on mouse_move is the last resort. 

`

**Comment by swharden** [comment]
Check out the ScottPlot demo, especially for WinForms. There should be a crosshair demo and/or mouse tracking demo.

https://scottplot.net/demo/

The app probably has a link to the source code, but if not that's here

https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/MouseTracker.cs

**Comment by swharden** [comment]
You may also find this page helpful:

* https://scottplot.net/faq/mouse-position/
