### ISSUE TITLE
Trimming Y axis to Actual Min Max Values

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2471]
**ScottPlot Version:** 4.1.6.1

**Operating System:** Win 10

**Application Type:**  WinForms 

**Question:** Is it possible to trim the length of the Y-axis in multi-Yaxis mode?
The thing is that showing the Y-axis and its values makes no sense if displayed Y-axis values are out of the scatter Y values.

**Comment by swharden** [comment]
> Is it possible to trim the length of the Y-axis in multi-Yaxis mode?

I think this will help:

```cs
plt.SetAxisLimits(); // optional arguments define which limits are set and also which axis index to use
```

Feel free to open this issue back up if I misunderstood your question

**Comment by swharden** [comment]
There's also

```
var dataLimits = plt.GetDataLimits();
plt.SetAxisLimits(dataLimits);
```
