### ISSUE TITLE
Polyglot Notebooks

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2472]
It looks like .NET Interactive Notebooks rebranded to Polyglot Notebooks when I wasn't looking 😅

https://devblogs.microsoft.com/dotnet/dotnet-interactive-notebooks-is-now-polyglot-notebooks/

This issue will track updating the docs (and quickstart?) to reflect the current notebook product.

https://scottplot.net/quickstart/notebook/

**Comment by GeorgeS2019** [comment]
@swharden 

I get this as output, 
Likewise for plt.Display()
No chat.

<img src="https://user-images.githubusercontent.com/49812372/224785231-af594ea6-0bf9-43e8-9bc4-4c547b332961.png" width="500" height="400">

**Comment by swharden** [comment]
> @swharden 
> 
> I get this as output, 
> Likewise for plt.Display()
> No chat.
> 
> <img src="https://user-images.githubusercontent.com/49812372/224785231-af594ea6-0bf9-43e8-9bc4-4c547b332961.png" width="500" height="400">
> 
> 
> 

I think you need the other block of code at the top of the quick start page https://scottplot.net/quickstart/notebook/

**Comment by swharden** [comment]
https://devblogs.microsoft.com/dotnet/announcing-polyglot-notebooks-harness-the-power-of-multilanguage-notebooks-in-visual-studio-code/
