### ISSUE TITLE
SP5: ShowContextMenu still work in PlotActions.NonInteractive()

### ISSUE THREAD

**Issue by minjjKang** [ScottPlot/ScottPlot#2475]
## Feature Suggestion

**Description:** ShowContextMenu is still working in below
```cs
// plot == ScottPlot.WPF.WpfPlot
plot.Interaction.Actions = Scottplot.Control.PlotActions.NonInteractive();

// -> MouseRightButtonDown, ShowContextMenu is still working
```

**Code example:** I change code like below, and its working correctly.

**src/ScottPlot5/ScottPlot5/Control/Interaction.cs**
```cs
// ~~~
        if (!isDragging && (button == Inputs.ClickContextMenuButton))
        {
            // Control.ShowContextMenu(position); // before
            Actions.ShowContextMenu(Control, position); // After
        }
// ~~~
```

**Comment by swharden** [comment]
Thanks for reporting this @minjjKang! I will implement the fix you suggest 🚀 

The section that must be modified is here:
https://github.com/ScottPlot/ScottPlot/blob/32896522327192af322c2f3c0129e1205ecf5799/src/ScottPlot5/ScottPlot5/Control/Interaction.cs#L133-L136
