### ISSUE TITLE
AddHorizontalLine,but no label show

### ISSUE THREAD

**Issue by tomuGo** [ScottPlot/ScottPlot#2476]
## Bug Report

**Issue:**    Plot.AddHorizontalLine(x:0, label:"Hor") ,but no label show

**Reproducing:** 

```cs
public partial class PoltTest : Window
    {
        public PoltTest()
        {
            InitializeComponent();
            WpfPlot _wpfPlot = new WpfPlot();
            _wpfPlot.Margin = new Thickness(13, 42, 30, 20);
            _wpfPlot.HorizontalAlignment = HorizontalAlignment.Left;
            _wpfPlot.Width = 630;
            _wpfPlot.Configuration.Zoom = true;
            _wpfPlot.Configuration.Pan = true;
            _wpfPlot.Background = AppSolidColors.HexFFEEF8FF;
            _wpfPlot.Plot.Layout(right: 0.3f, top: 0.3f);
            _wpfPlot.Plot.XAxis2.IsVisible = false;
            _wpfPlot.Plot.XAxis.IsVisible = false;
            _wpfPlot.Plot.YAxis.IsVisible = false;
            _wpfPlot.Plot.YAxis2.IsVisible = false;
            _wpfPlot.Plot.AddHorizontalLine(0,label:"Hor");
            _wpfPlot.Plot.AddVerticalLine(0,label:"Ver");
            ChartGrid.Children.Add(_wpfPlot);
            double[] xs = new[] { 1d, 2d, 3d, 4d, 5d };
            double[] ys = new[] { 1d, 2d, 3d, 4d, 5d };
            _wpfPlot.Plot.AddScatter(xs, ys, markerShape: MarkerShape.none);
            _wpfPlot.Dispatcher.Invoke(() => { _wpfPlot.Refresh(); });
            
        }
    }
```
![image](https://user-images.githubusercontent.com/24789356/223968322-bc76bd56-e267-4b4b-8aae-8ec083300bf7.png)

### System Details
* **ScottPlot Version:** 4.1.60
* **Operating System:** win11
* **Application Type:** wpf
* **.NET Version:**net6

**Comment by swharden** [comment]
Hi @tomuGo, 

Try this and let me know if it doesn't do the trick! 👍 🚀 

```cs
_wpfPlot.Plot.Legend();
```

**Comment by tomuGo** [comment]
thanks for reply! it worded,but its not what i wanted.

**Comment by tomuGo** [comment]
@swharden  .thanks for reply ! It worked, but its not what i wanted.I want the HorizontalLineLabel near this HorizontalLine,just like axis

![image](https://user-images.githubusercontent.com/24789356/224466489-8ded8ad0-96b2-442b-b877-54e3351c99da.png)

**Comment by swharden** [comment]
Hi @tomuGo, you can enable position labels on axis lines. This may help you achieve the effect you are seeking!

https://scottplot.net/cookbook/4.1/category/plottable-axis-line-and-span/#position-labels
