### ISSUE TITLE
Multi-Axis: How to center all Y axes vertically so the 0 positions align

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2477]
**ScottPlot Version:** 4.1.6.1

**Operating System:** Windows 10

**Application Type:** Winforms

I have 4 plotables.
3 of them represent Altitude (GSP altitude, DMT altitude, and DELTA (the difference between the two)
I would like to show Y = 0 starting at the same Y pixel for all plotables.
The picture below shows an offset I would like to get rid of.
![image](https://user-images.githubusercontent.com/26789352/224003381-ea7c3c8a-0667-4791-88e5-7a57e937e08a.png)
Is there a way?

**Comment by bukkideme** [comment]
Hi! I do not think there is a direct technique to do this. And this is not a limitation of ScottPlot, this kind of request I think is a bit unusual :) How can you expect the zero point would match if the scales are totally different on the two axis?

I can only tell you what I would do: I would scale the two datasets together, and use a common, single Y-axis for them. You can indicate the scaling factors at the Axis title or wherever it is convenient.

**Comment by dusko23** [comment]
Thank you for your response.
It is not about scale. It is about the Y pixel value where Y =0 horizontal line for each Y axis is rendered on canvas.

Please have a look at the MultiAxix example.
I have manually "Zeroed" all Y axes.

![image](https://user-images.githubusercontent.com/26789352/224399393-6f63823b-9a9c-4b4b-9d42-6c05191ea635.png)

This was done manually.
A code snippet on how to do it programmatically is welcome. 
There are cases where Y = 0 gives immediate information. Visual search where each potable has its Y = 0 line does not feel good.

**Comment by bukkideme** [comment]
I already understood your request, that you want to position the zero label at the same vertical pixel position. However this is not supported in ScottPlot as much as i know. For me, it was never a requirement to set the zero label positions at the same vertical level. When I use multiple Y axis, I want actually the opposite: i want totally independent Y axis. 

I think you could write a logic where you compare the min/max values of the 3 axis after any scale change. Then you need to have a reference, like the primary Y axis, and set the min/max values of the two others with a smart calculation so you get the zero label always at the same vertical pixel position...

**Comment by bukkideme** [comment]
Hey, I have just found a previous discussion regarding to this! :)

https://github.com/ScottPlot/ScottPlot/discussions/1566

**Comment by dusko23** [comment]
Hi, thanks for the tip.
Bottom line is that my starting idea was this

ZOOM OUT
![image](https://user-images.githubusercontent.com/26789352/224420643-62e86e81-baa2-4d21-aee2-e3ee425e4d37.png)


ZOOM IN 1
![image](https://user-images.githubusercontent.com/26789352/224421256-dfafe1d6-a7d0-450d-8625-8abe6a95b2f1.png)

ZOOM IN 2 (Featuring Extra Tick - One tick beyond min-max)
![image](https://user-images.githubusercontent.com/26789352/224422072-2f9dbd67-3d46-42bf-b40a-758b85b9c92a.png)

OR EVEN THIS (FINE TUNNING DESIGN WHILE WRITING :-))
![image](https://user-images.githubusercontent.com/26789352/224424261-86268d78-f49b-4c82-b550-3e8e70fde22d.png)


It means that the numbers on the Y-axis do not go beyond the min-max value (plus one major tick label more on both ends).
If 3 plotables belong to a common axis I would calculate cumulative min-max and apply the same interval to all three plotables. Unlabeled part of Y axis can be completely deleted. As well Y-axis name is not shown if the plot interval does not contain min-max interval.
This way tick labels clutter is removed and much clearer to read. Yzero is not needed in this case :-)

**Comment by swharden** [comment]
To help get this moving, here's a standalone code sample (console app) that demonstrates the issue described here

```cs
using System.Drawing;

ScottPlot.Plot plt = new();

// plot something on the primary Y axis
double[] dataA = ScottPlot.DataGen.Sin(51, mult: 0.1, offset: .02);
var yAxisA = plt.YAxis;
yAxisA.Color(Color.Green);
var signalA = plt.AddSignal(dataA);
signalA.Color = Color.Green;
var hLineA = plt.AddHorizontalLine(0, signalA.Color, 3, ScottPlot.LineStyle.Solid);
hLineA.Color = Color.Green;

// plot something on an additional Y axis
double[] dataB = ScottPlot.DataGen.Cos(51, mult: 10, offset: -2);
var yAxisB = plt.AddAxis(ScottPlot.Renderable.Edge.Left, 2);
yAxisB.Color(Color.Blue);
var signalB = plt.AddSignal(dataB);
signalB.Color = Color.Blue;
signalB.YAxisIndex = 2;
var hLineB = plt.AddHorizontalLine(0, Color.Blue, 3, ScottPlot.LineStyle.Dash);
hLineB.YAxisIndex = 2;
hLineB.Color = Color.Blue;

// launch the plot in an interactive window
ScottPlot.FormsPlotViewer viewer = new(plt)
{
    Width = 600,
    Height = 400,
    StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
};
viewer.ShowDialog();
```

The goal is to have the green and blue horizontal lines always overlap

![lines](https://user-images.githubusercontent.com/4165489/224447974-bafcad99-68df-4be5-8837-082c24bac025.gif)

**Comment by dusko23** [comment]
I have solved the issue described (my case).
Scenario:
Two Y axis. 3 plots per Y-axis.
An option is given to show both axis or either of them. It means that the user can happily live with one Y axis only.
The second Y axis becomes the primary Y axis when needed.  Y-axis not needed is hidden
