### ISSUE TITLE
AxisPanCenter Not Working

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2482]
Desperately trying for ages to Center the Plot to a specific coordinate.
The code below does not move the Plot.
The coordinates are correct. 

VB
![image](https://user-images.githubusercontent.com/26789352/224453176-519369ed-ec93-4be8-92c5-5b7386aa119b.png)

C#
![image](https://user-images.githubusercontent.com/26789352/224453232-0d791c5d-78da-47a6-9388-21f37c76f961.png)

Absolutely have no idea what I am missing here.
A workable example in a cookbook would be just great.

**Comment by swharden** [comment]
You may need to tell the plot control to redraw itself after changing the axis limits like that.

Does this help?

```cs
pathPlot.Refresh();
```

**Comment by dusko23** [comment]
The suggestion does not give the desired result.
However, I have checked my initial plot settings and started changing the parameters there.
And the change shown below did the magic.
Before it was set to **True**.

![image](https://user-images.githubusercontent.com/26789352/224505370-28d73d11-cc3c-451b-bd23-eee2ae136cc1.png)

However, I don't understand why it is related to not moving in the first place. The graph should move if I am able to zoom and pan manually.
A refresh is not needed because the viewport has moved.

This being solved another issue popped out.
Please look at the picture below and tell me what I need to do to lower the dynamic of Speed Related plotables?
I assume it has something to do with scaling the  Speed Axix. But not sure what exactly to do in order to decrease Y values by 50% for example.

![image](https://user-images.githubusercontent.com/26789352/224505294-0150dfd8-1d6a-4b6a-a0aa-630bbbddebf9.png)

**Comment by dusko23** [comment]
Upss, Refresh is needed. Just discovered. My bad ;-)

When I center a plot to a specific X and Y a Marker is added.

![image](https://user-images.githubusercontent.com/26789352/224513166-6e3601cd-7ec6-4fa0-b838-38428dc02ed6.png)


How do I remove all markers without clearing and repopulating the plot?
