### ISSUE TITLE
How can I mask out erroneous and missing data while plotting a curve?

### ISSUE THREAD

**Issue by mYcheng-95** [ScottPlot/ScottPlot#2486]
I would like to use SignalXY to break the abnormal data in the line chart. Is there any other way to achieve this?
For the middle and end sections of the chart as shown in the following image:
![image](https://user-images.githubusercontent.com/30651076/224868807-d1aefe5e-d973-428f-a264-d398a5e0630f.png)

**Comment by bukkideme** [comment]
Hi!
As i see there is option to visualize "gap" to handle such case, if you use ScatterPlot:
https://scottplot.net/faq/nan/#data-gaps-with-nan

However, i do not see such option if you use SignalPlotXY...

**Comment by mYcheng-95** [comment]
> Hi! As i see there is option to visualize "gap" to handle such case, if you use ScatterPlot: https://scottplot.net/faq/nan/#data-gaps-with-nan
> 
> However, i do not see such option if you use SignalPlotXY...

Thank you very much. This option is not available in SignalPlotXY. I think I can change SignalPlotXY to ScatterPlot

**Comment by bukkideme** [comment]
Be aware that a ScatterPlot is not as fast as a SignalPlot. So it depends on your usage, required rendering speed and amount of data. Give it a try, anyway!
