### ISSUE TITLE
Save Plot Image Using Memory Stream

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2487]
It appears that there is no option to save the plot image to the memory stream as PNG type.
It would be good to have this option to avoid the following sequence:

- writing to the disk,
- reading image files to the memory stream,
- deleting files,
- saving memory stream byte array as a blob in SQLite (for example)

**Comment by bukkideme** [comment]
What kind of memory stream you talk about? You mean simply memory, no?
Actually you can do save the whole Plot in memory. Check out the API documentation: https://scottplot.net/doc/v4/api/ScottPlot.Plot.html#ScottPlot_Plot_Copy

Plot MySavedPlot = formsPlot1.Plot.Copy();

**Comment by StendProg** [comment]
Hi @dusko23,
You can easily render a plot to an in-memory bitmap.
And then convert it to the format you prefer.
Just check how save to file works. First step is in-memory bitmap.
https://github.com/ScottPlot/ScottPlot/blob/15b9959020eddda5319e8145ff2e2b44d52c02ef/src/ScottPlot4/ScottPlot/Plot/Plot.Render.cs#L265

**Comment by dusko23** [comment]
Thanks for pointing that out.
I was following CookBook and only saving files are shown.

**Comment by swharden** [comment]
Hi @dusko23, thanks for the question! (and thanks StendProg for your answer)

This also works:

```cs
ScottPlot.Plot plt = new(600, 400);
plt.AddSignal(ScottPlot.DataGen.Sin(51));
plt.AddSignal(ScottPlot.DataGen.Cos(51));

byte[] bytes = plt.GetImageBytes();

using MemoryStream ms = new();
ms.Write(bytes);

using FileStream fs = new("out.png", FileMode.Create, System.IO.FileAccess.Write);
ms.WriteTo(fs);
```
