### ISSUE TITLE
Reducing Dynamic of a Particular Plotable in MultiYAxix Environment

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2488]
Showing nicely distributed plots in a Multi Y Axis environment can be tricky.

Here is an example of how Altitudes (Yaxis)  and Speeds (Yaxis2) are shown without a trick.
![image](https://user-images.githubusercontent.com/26789352/224968432-0f185576-ce59-4bbe-af2c-a29bc2bca8dd.png)

In order to decrease displayed dynamics of Speed plotables (50% for example) the following code snippet is used.

![image](https://user-images.githubusercontent.com/26789352/224968951-e1f6b435-5f7b-41f1-b18c-09e71af50cba.png)

Where SpeedMAX represents a Double array of the maximum value of all speeds multiplied by 2.

This is the result where the speed dynamic is visually reduced by 50%.
![image](https://user-images.githubusercontent.com/26789352/224969498-40c41cdc-fa84-4047-85a3-878f58e87661.png)

It applies to a single Y axis as well.

**Comment by swharden** [comment]
Hi @dusko23, thank you for sharing this code and screenshots!

I want to make sure I correctly understand your message. This is information you are sharing to help others, correct? There is not a question here that I am missing?

Assuming this is the case, I'm going to turn this issue into a Discussion and mark it _Show and Tell_ but let me know if I misunderstood!
