### ISSUE TITLE
Histogram: does not support BinSize < 1

### ISSUE THREAD

**Issue by Margulieuxd** [ScottPlot/ScottPlot#2490]
## Bug Report

**Issue:** 
HistogramDemo.cs generates live data in the range of 0-1; while the histogram is attempted to be generated with parameters min:0, max:1, bincount:40. 

Within histogram.cs, the binsize is limited to a minimum size of 1, meaning all the data falls within one bin.

### System Details
* **ScottPlot Version:** 4.1.61
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** (NET Framework 4.8? .NET 6.0?)

**Comment by Margulieuxd** [comment]
I got it to work for myself by moving the ending parenthesis to be:

> BinSize = Math.Max(1, (max - min)) / binCount;

I think this line was changed in the last update to account for if max-min = 0.

I've not done a commit and haven't tested the edge cases to see if this is the appropriate fix.

**Comment by swharden** [comment]
Thanks for reporting this @Margulieuxd!

The line of code we are discussing is here:
https://github.com/ScottPlot/ScottPlot/blob/b4d3b8f7bd0a5a44998f16f9581197ef2ebda078/src/Shared/ScottPlot/Statistics/Histogram.cs#L91

> BinSize field is a double, and should not be restricted to a min value of 1. Looks like a bug indeed. I can make a fix and a PR, after my pending PR is merged :)

@bukkideme I can take care of it real quick right now - thanks for offering though! Note that it's possible to create multiple pull requests simultaneously 😉 

> I've not done a commit and haven't tested the edge cases to see if this is the appropriate fix.

I recall there are some pretty good histogram tests in place, so if they all pass I feel okay about it! I'll add a new test to demonstrate this bug, and ensure the fix solves it 👍

**Comment by swharden** [comment]
> I think this line was changed in the last update to account for if max-min = 0

I'll make it throw an exception if users do that 🔥
