### ISSUE TITLE
Bubble Plot: Bubble size is pixels (not coordinates)

### ISSUE THREAD

**Issue by marcelpel** [ScottPlot/ScottPlot#2492]
Bubble Plots not zooming or resizing correctly.  See attached images:
1.  Normal plot as it should be.
2.  Window resized (same plot as above)
3.  Normal plot but zoomed to one point in the data.

In all cases the circle size remains the same while the XY scale changes.  This means depending on zoom in or out the diameter relative to the XY axis is changing.  The relative size and location of the circles should be constant so the plot looks the same regardless of scale.

![BubblePlot_asDrawn](https://user-images.githubusercontent.com/93227729/225366612-e8cfbdfa-a034-4ddd-8ecf-0a505a49cc33.jpg)
![BubblePlot_AsDrawn_Zoom2OnePoint](https://user-images.githubusercontent.com/93227729/225366626-7af0078f-fb49-41e0-b2bd-22743eae6429.jpg)
![BubblePlot_WindowResize](https://user-images.githubusercontent.com/93227729/225366646-60f25fc4-9a9d-49ec-bd47-bb564175363c.jpg)

**Comment by swharden** [comment]
Hi @marcelpel,

The size of bubbles is in pixel units (not coordinate units) so it makes sense they do not change their size as users zoom in and out.

However, it would be good to add a flag that indicates the size of bubbles should be in coordinate units. I will add this now.

WARNING: Be prepared for unexpected behavior though. As you zoom in, circular bubbles will appear as ovals, which is a behavior that I think most people will find unexpected.

**Comment by swharden** [comment]
I'm adding a `RadiusIsPixels ` flag (defaults `true`) and creating a cookbook example

![bubbles](https://user-images.githubusercontent.com/4165489/229326803-e1432e30-55b1-4067-9a24-bdde93798804.gif)

**Comment by marcelpel** [comment]
Thanks for the follow up on this.

Will this work with window resizing as well?  Assuming if plotted to coordinate axes it will not matter if zoomed or scaled.

The axes could be locked proportionally to prevent ovals but that is likely problematic due to issues with screen size and window resizing versus zooming.

Nice demo attached!

Marc

**Comment by swharden** [comment]
> Will this work with window resizing as well?

Indeed!

> The axes could be locked proportionally

Yes, this is an opt-in feature. 

```cs
plt.AxisScaleLock(true, EqualScaleMode.PreserveLargest);
```

It's commented-out in the cookbook example:

https://scottplot.net/cookbook/4.1/category/plottable-bubble/#bubble-size
