### ISSUE TITLE
Plot.MatchAxis only matches axisindex=0

### ISSUE THREAD

**Issue by Margulieuxd** [ScottPlot/ScottPlot#2495]
## Bug Report

**Issue:** 
Plot.MatchAxis only affects axisIndex=0. When using stacked plots, and a secondary x-axis, it does not pan with the primary axis. So when using two traces on one plot, and two traces on a second plot (extension of the demo): When panning on one plot, all traces of that plot will move, but on the second plot, all traces using primary axis on the second plot will pan but the trace with the secondary axis will remain stationary.

### System Details
* **ScottPlot Version:** 4.1.61
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** (NET Framework 4.8? .NET 6.0?)

**Comment by swharden** [comment]
Thanks for reporting this @Margulieuxd!

Note that the function is located here:

https://github.com/ScottPlot/ScottPlot/blob/b3f5ad5d887a27e8c612cb13af49e70b560e6ac5/src/ScottPlot4/ScottPlot/Plot/Plot.Axis.cs#L171-L187

I may be able to fix this tomorrow, but if someone gets to it first I'd be happy to review a PR!
