### ISSUE TITLE
Please help a newbe

### ISSUE THREAD

**Issue by CBrauer** [ScottPlot/ScottPlot#2498]
Hey,

I cannot seem to get a simple scatter plot to work.  The documentation does not agree with Microsoft VS 2023 IntelliSence in my application.  Here is a picture of my complete reproducible program:

![image](https://user-images.githubusercontent.com/1317234/226213179-679b029b-764d-4d40-90e9-1cf826508206.png)

``
When I run the program, I get the following plot:
![plot](https://user-images.githubusercontent.com/1317234/226213878-67d84563-69de-45fe-a2dd-4e399fb42dad.jpg)

As you can see the plot is empty.  The scale labels are too small.
I tried to use the example at: https://scottplot.net/cookbook/4.0/#plottypes-scatter---scatter-plot-quickstart but your code no longer works.

Any help will be greatly appreciated;
Charles

**Comment by swharden** [comment]
Hi @CBrauer, make sure you are using a ScottPlot 4 (version 4.1.x), not ScottPlot 5

https://scottplot.net/versions/

Once you're using ScottPlot 4.1, all the cookbook examples should work well for you 🚀 

https://scottplot.net/cookbook/4.1/

I hope this helps you get underway!

**Comment by swharden** [comment]
Also the Windows Forms quickstart may be useful

https://scottplot.net/quickstart/winforms/
