### ISSUE TITLE
How do I reverse the Y-axis?

### ISSUE THREAD

**Issue by yunotyu** [ScottPlot/ScottPlot#2499]
I want the origin to be in the top left corner。

**Comment by bukkideme** [comment]
This might help you: https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#descending-ticks
The example shows how to invert X axis, but the same could be done for Y I guess.

**Comment by yunotyu** [comment]
> This might help you: https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#descending-ticks The example shows how to invert X axis, but the same could be done for Y I guess.
Nice,Thanks.

**Comment by yunotyu** [comment]
OK
