### ISSUE TITLE
SP5: Add tick label formatter to `ITickGenerator`

### ISSUE THREAD

**Issue by chhh** [ScottPlot/ScottPlot#2500]
**ScottPlot Version:**
5.0.2-beta

**Operating System:**
Win10

**Application Type:**
console (i'm plotting off screen)

**Question:** Describe your question here
I'm plotting Scatters with 2 series. They share x-axis (bottom), but have different y-axes (left and right).
Secondary Y axis (on the right) is created as `ScottPlot.Axis.StandardAxes.RightAxis axYRight = new();`
**The problem**: All the labels for ticks on that axis turn out to be rendered the same. If the values on the axis are below 1000, then I see some values after decimal point, but for values over 1000 - they're all rendered the same (the variance for that axis is very small, it's common to have values like `2000.0001, 2000.0002...`

Here's an example (**notice right y-axis labels**):
![MzTrace_09448_MZ=1068 92](https://user-images.githubusercontent.com/107902/226822992-0e612834-d543-4e17-ab56-0ac64636d076.png)

In v4 there was a way to set custom format for axis tick labels. I can't find an equivalent for v5.

I think it won't add too much of an overhead to compare the printed labels (strings) and increase the formatting precision until at least some labels are different (or all labels are different). Is there such functionality already available? Or is it a good project for contribution to the project?

**Comment by swharden** [comment]
Hi @chhh, ScottPlot5 being actively developed and isn't well documented yet. However check out the `ITickGenerator`

https://github.com/ScottPlot/ScottPlot/blob/b3f5ad5d887a27e8c612cb13af49e70b560e6ac5/src/ScottPlot5/ScottPlot5/ITickGenerator.cs#L1-L20

If you make a class then implement `ITickGenerator`, you can use your custom tick generator to totally control the position and text of ticks

However, I'm looking at how complicated tick generation is and I now realize you don't want to be doing all this lol: 

https://github.com/ScottPlot/ScottPlot/blob/b3f5ad5d887a27e8c612cb13af49e70b560e6ac5/src/ScottPlot5/ScottPlot5/TickGenerators/NumericAutomatic.cs#L1-L165

I'll rework the ScottPlot 5 API to make it easier to inject their own tick _formatters_ without having to reinvent the whole tick generation system. Thanks for asking this question!
