### ISSUE TITLE
Horizontal Axis Scrollbar

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2501]
**Using ScatterPlot**
I tried to find a way to stretch the X-axis.
When a scatter plot is drawn all of the data are shown inside the plot area.
Now, I would like to stretch the X-axis without resizing the plot object.
It means that a part of the X-axis will be outside the visible area.
It would be perfect if a horizontal slider is shown in order to horizontally pan using the slider.

I have tried resizing the plot object programmatically.
It works as expected.  However, the X-axis label disappears after a couple of resizes.
X-label should appear at the center of the X-axis.
![ScalingXaxis](https://user-images.githubusercontent.com/26789352/227018468-49f28972-b77b-433d-81a7-a7939d1a2064.gif)

If I would put a plot object in the panel, the horizontal slider will appear when plot object is wider than the panel.
However, is there any other way how to achieve the result I need?

**Comment by bukkideme** [comment]
I think you create more trouble with such approach than what you win with it. You stretch your control, so its right side will be unreachable in your UI, as I understand. This will create all sort of issues. Why would you want such unusual usage of a UI control? 
If your container where your Plot is sitting, is always visible, just set the Plot as docked, and then the labels will be always visible at any resized step...

**Comment by bukkideme** [comment]
https://user-images.githubusercontent.com/51174971/227255511-19766fe1-b17b-4fe1-b314-48f34b232e7f.mp4

**Comment by swharden** [comment]
> I think you create more trouble with such approach than what you win with it

I agree with this overall sentiment... 

> I have tried resizing the plot object programmatically. It works as expected.

This is good news! It sounds like you have solved your core problem as far as axis limits are concerned.

> However, the X-axis label disappears after a couple of resizes.

Maybe we can add an option to left-align the axis label if it's not already in there. I'd be happy to review a PR if you want to try to add this!

This could be achieved by editing all instances of `HorizontalAlignment.Center` in this file:

https://github.com/ScottPlot/ScottPlot/blob/33fca4cbcb884161d61e05615604b008a0e7aac1/src/ScottPlot4/ScottPlot/Renderable/AxisLabel.cs#L148

Exposing a `HorizontalAlignment` property that defaults to `Center` would preserve the present behavior but also allow users to customize that behavior.

> It would be perfect if a horizontal slider is shown in order to horizontally pan using the slider.

This is an interesting effect and it seems useful to demonstrate this on an FAQ page or as a demo added to the demo app. I'll leave this issue open until I can put this in.

> #2501

Just gonna say that I've been waiting a long time for project 2501 🙃 

https://www.youtube.com/watch?v=roUmza6tdjw

**Comment by swharden** [comment]
Hi @dusko23, I hope this code example helps set you on a patch toward a solution that works for you!

![2501](https://user-images.githubusercontent.com/4165489/229327699-c9a7997a-dc37-4d17-a89e-577f3a2d08d7.gif)

```cs
public partial class Form1 : Form
{
    ScottPlot.Plottable.SignalPlot MySignal;

    public Form1()
    {
        InitializeComponent();

        MySignal = formsPlot1.Plot.AddSignal(ScottPlot.DataGen.Sin(1_000, oscillations: 3));
        formsPlot1.Refresh();
    }

    private void hScrollBar1_Scroll(object sender, ScrollEventArgs e)
    {
        double visibleSpan = 100;
        double fraction = (double)hScrollBar1.Value / hScrollBar1.Maximum;
        double scrollableSpan = MySignal.PointCount * MySignal.SamplePeriod - visibleSpan;
        double xMin = fraction * scrollableSpan;
        double xMax = xMin + visibleSpan;
        formsPlot1.Plot.SetAxisLimitsX(xMin, xMax);
        formsPlot1.Refresh();
    }
}
```

**Comment by dusko23** [comment]
Hi, this works for your case because you are using the signal. I use a scatterplot where the sample period does not apply.

I played further with Plotables Properties and discovered that important property was Missing.
a **TAG**
Like Plotable.Tag = "anything"
"anything" can be literary anything. It is 100% to the user. Plottable just holds that reference. 

That would save a lot of work for further ScottPlot development.
A unique ID is such an example.
The user adds an ID to his class which also holds the unique string.
Or just declare Plotable.Tag = new GUID.ToString (VB notation) if he wants to trade a precious Tag Property for a simple String. 
There is no need that ScottPlot to be aware of everything about how ScottPlot can be used. 

Tag is an important property that enables keeping user business logic design independent of ScottPlot.

I have read discussion #694
[Sedighzade](https://github.com/Sedighzade) made some good points.
No need to add any Interface. Just a pure Property named **Tag** which holds a reference to the Object, whatever Object represents.

Instead of populating ListBoxes while adding Plotables to the whole lot, it would be better to have the option to iterate in a loop through all plotables and populate lists as needed regarding scenarios that can be completely SCottPlot independent.

Adding Tag property which holds a reference to the Object, whatever it represents will set ScottPlot development free of many future desires that have nothing to do with ScottPlot Logic as such :-)

**Comment by swharden** [comment]
> I use a scatterplot where the sample period does not apply.

Good point! In this case you can use the scatter plot's `GetAxisLimits()` method to get the min/max values in every direction

> Adding Tag property which holds a reference to the Object

This idea comes up from time to time. It makes sense for GUIs, but not for console applications. Because users create all different types of GUIs, I leave the door open for users to solve this problem in the best suited to the particular GUI framework they are using.

* #694 
* #695
* #2114

The recommended way to pair arbitrary data with plot types or controls is to use a dictionary, as described in https://github.com/ScottPlot/ScottPlot/issues/2114#issuecomment-1238760801

**Comment by dusko23** [comment]
Thanks, Scott, I see where are you coming from.
I was suggesting to add Tag because it is the standard thing to have at hand. Every Microsoft Windows GUI element has got one. It makes life easier for everyone. In general, I see no reason why you should not add a tag to every object you create. It can not sleep out of control because it already would (it is 100% up to the user only what he does with a tag :-)
The only way I can see a tag could be a problem is if you would decide to provide serialization/deserialization of the Plotables. Imagine binary writing Plotables to sqlite and populating a Plot by reading from sqlite, deserializing, and adding deserialized plotables to Plot. That would be nice for many use cases.

The console application shows the Plot and the end of the day. So it is not GUI less I think. However, Tag might not be used. But that is fine and causes no harm.

Currently, I am using SCottPlot the simple way, just to enable a simple display and analysis of the data shown.
Clicking Plot I perform actions that relate to the data ScottPlot holds and show GUI effects elsewhere. SCottPlot just serves as Event Trigger (MouseMove, MuseUp/Down) in this case.

When creating a more intensive GII with loads of business logic I will create a Class when one item of the class will be Plotable object. The wrapper will be a list of these Classes and the problem of Tag is solved for good. Using Dictionary has its own limits.

So far so good. Excellent work you have done and I like using SCottPlot. Just need more time to get used to the naming of things. Perhaps using ChatGPT4 from side might help :-)

There is one thing I would like to mention/suggest.
It would be good to have the option to define axis objects as separate GUI objects.
To be placed outside the plot object.
These objects will just reference Plot Axis objects while the Axis of originated Plot object could be left hidden. 
Could also serve as a slider :-)
