### ISSUE TITLE
Disable Panning Outside Data Area

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2503]
**Using ScatterPlot**
How to disable Panning/Zooming Outside Data Area seems to be a mystery to me.
Trying Axis limits but no luck.
Plot.SetViewLimits expose exactly what I would probably need but it is obsolete.

Could not figure out how to disable the user to pan outside the plot area without data.
For example:
X line represents DISTANCE.
DISTANCE can not have negative values.
Therefore panning/zooming the graf to display negative X ticks makes no sense.
Panning/zooming above X maximum values also makes no sense.
The same applies to Y values. Panning/zooming outside Y min max values makes no sense as well.
A simple code snippet of how to do that is highly appreciated.

**Comment by bukkideme** [comment]
_"Therefore panning/zooming the graf to display negative X ticks makes no sense.
Panning/zooming above X maximum values also makes no sense."_

Well, it depends on your requirements :) I like to have the option to zoom/pan outside my data limits, for example when I want to bring some data parts at the lower or higher limits, to the center. Why is it a problem for you?

**Comment by swharden** [comment]
Hi @dusko23, does this help?

https://scottplot.net/faq/axis/#set-boundaries-on-the-axis-limits

```cs
formsPlot1.Plot.SetOuterViewLimits(0, 50, -1, 1);
```

It's hard to document in the cookbook because the cookbook isn't interactive (it's a console application), and the page linked to above is the only place it's written

Let me know if this doesn't do the trick!

**Comment by dusko23** [comment]
Thanks, Scott that works like charm. very happy :-)
Currently, there is only one issue remaining for my project.
Please look at #2483

**Comment by swharden** [comment]
> Thanks, Scott that works like charm. very happy :-)

Great to hear! 🚀🚀🚀 

> Currently, there is only one issue remaining for my project:
> *  https://github.com/ScottPlot/ScottPlot/issues/2483

I'm working from oldest to newest and #2483 is 5 away, so I think I can get to it pretty soon 🤞
