### ISSUE TITLE
Legend is out of the chart window

### ISSUE THREAD

**Issue by alexly2048** [ScottPlot/ScottPlot#2504]
**ScottPlot Version:** 4.1.61.0

**Operating System:** Window 10

**Application Type:** WPF

**Question:** In my project, it had 43 different series and when it show the lengend, the legend is out of the scope of the chart window, it only shows 10-33 series and some lengends can't be displayed on the chart area.   I had searched with the searching engine, but it seems that there no methods to resolve this problem.
![legends](https://user-images.githubusercontent.com/16357510/227138470-b56cb44b-6619-43b6-a5d3-07955ef51938.png)

**Comment by bukkideme** [comment]
I think this huge number of legend entries are not really good to show on the plot itself. This is just not practical at this level, it is a big mess. I advise you to develop your own "legend UI" as a separate control.
When I had to show lots of curves on a single Plot, for example, I used to make a separate Listbox with checkboxes, labels and other useful items. When you interact with the Listbox, you can use some Events to show/hide, highlight, etc the curves on your Plot.

**Comment by alexly2048** [comment]
Thank you very much. In my project, it must put the series in one chart. I will put the legend in one seperate control as description in Q&A #1280.

**Comment by swharden** [comment]
Note that there's also `GetLegendBitmap()` which will let you get the legend as a bitmap then display it elsewhere in your window

```cs
Bitmap bmp = formsPlot1.Plot.GetLegendBitmap();
pictureBox1.Image = bmp;
```
