### ISSUE TITLE
Support for Avalonia 11

### ISSUE THREAD

**Issue by PremekTill** [ScottPlot/ScottPlot#2507]
## Feature Suggestion

**Feature description:**

Hello :)

The Avalonia framework is moving closer to releasing v11 from preview, with many improvements over the previous version. Currently, there is a feature freeze in place to iron out some of the remaining bugs and hopefully move to a RC and full release as soon as possible ([https://github.com/AvaloniaUI/Avalonia/discussions/10599](https://github.com/AvaloniaUI/Avalonia/discussions/10599)).

Unfortunately, there are quite a few breaking changes between the versions, meaning that the current AvaPlot cannot be used in v11 as-is ([https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes](https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes)). Fortunately, for ScottPlot 5, the relevant changes are mostly some namespace shuffling and a switch from SaveFileDialog to IStorageProvider, which provides better support for mobile and browser APIs.

I have tried my hand on getting ScottPlot 5's AvaPlot to work with Avalonia 11 in [my fork](https://github.com/PremekTill/ScottPlot/tree/avalonia_11) (currently only tested on Win10 with very simple stationary plots). If there is interest, I can submit a PR to prepare the changes for the eventual release of v11 and test them a bit more.

However, there are some questions which should probably be discussed first: should the changes be made to both ScottPlot 4 and 5? Should we support both v0.10 and v11, or only one of them? There seems to be more code which might need changing in ScottPlot 4, but it should still be fairly doable. From my point of view, an interesting solution could be too keep ScottPlot 4 at 0.10.18 and drop it from ScottPlot 5, which would only support the latest version - this way, ScottPlot 4 would be there to support legacy apps, whereas ScottPlot 5 would stay at the cutting edge. For most apps with more than basic UI, the porting process from Avalonia 0.10 to 11 will likely be a lot more involved than from ScottPlot 4 to 5, so I wouldn't expect that many to decide to upgrade Avalonia but find upgrading ScottPlot to be a dealbreaker. This also depends on the planned release schedule for ScottPlot 5, which I am not familiar with.

**Comment by swharden** [comment]
Hi @PremekTill, thanks for this thoughtful message! As you point out it will require effort for users moving from Avalonia 10 to 11, so getting the timing right is important. My gut reaction is to keep things simple and move everything (ScottPlot 4 and 5) to Avalonia 11 once it is out of preview.

I'd feed better leaving ScottPlot 4 on the older version if ScottPlot 5 were more feature complete. 😅 Its release date has yet to be determined. I'm aggressively closing ScottPlot 4 issues now to try to clear some time for me to focus on ScottPlot 5. I think the best action is for me to re-evaluate how to best proceed after Avalonia 11 is out of preview. I know you put a lot of work into this (including preparing a fork!), so if you find it's been released let's open this issue back up and pick this up then! 🚀 

You'll find a few people are interested in this topic, so maybe this is an effort that would benefit from some coordination? When the time comes, we have a Discord if it would help #1966 

Related issues:
* #2507
* #2321
* #2184
* #2183
