### ISSUE TITLE
WpfPlot: UserControl → CustomControl

### ISSUE THREAD

**Issue by KroMignon** [ScottPlot/ScottPlot#2509]
## Feature Suggestion

At this time, WPF version of ScottPlot uses `UserControl`.
This introduce some limitations:
1. Appearance of an `UserControl` cannot be changed using a `Template`. Even though it has a property for `Template`, but it is of no use, as you cannot change the appearance of `UserControl` through this property.

2. `UserControl` is derived from `ContentControl`, thus if you change the content of an `Usercontrol` the entire UI will be replaced with that content.

3. As `UserControl` has both `XAML` and code behind. But as `XAML` can be used only once for entire inheritance hierarchy, you cannot use `XAML` for any class that inherits from your `UserControl`. This is actually because `Application.LoadComponent` loads up the `XAML` once and is incompatible with inheritance. Thus when loading the `XAML`, the `IComponentConnector` interface is used to hook events and fields from `XAML`, hence you cannot replace `XAML` from your base class. 

I would like to change this to use `CustomControl`, this would remove those limitation.

**Feature description:**

As the ScottPlot WPF control is quiet simple this is not a big deal to achieve, I have already did it locally because I need it for my application.

This way, I can specialize the "base" control for example to add support for Crossbar, and not have to copy/past the crossbar code on each view on which I use it (I am a lazy developer ;-) )

I have also changed the events to use `RoutedEvent` instead of `event`, to be able to use them on `XAML` side.

If there is any interest about this, I could submit my changes as PR (need to learn how to do it, it would be my first PR!)

Best regards

Fabrice

**Comment by swharden** [comment]
Hi @KroMignon, thank you for this suggestion! I agree that a `CustomControl` sounds like a good idea. However, I'm not a WPF expert and it sounds like you have a lot of experience with WPF, so I value your opinion on how to best proceed.

Can this change be made in a way that is non-breaking to all the people who are already using the WpfPlot control? Would a PR be as simple as 3 modified files: a new WpfPlot.cs and deleted WpfPlot.xaml and WpfPlot.xaml.cs?

Thanks for your advice!

PS: Congratulations in advance on what may be your first pull request! 🚀 I'm happy to help answer any questions that may pop-up along the way.
