### ISSUE TITLE
SP5: Solution file error

### ISSUE THREAD

**Issue by KroMignon** [ScottPlot/ScottPlot#2525]
## Bug Report

**Issue:** 

Cannot build the solution, when opening solution (or any solution filter), Visual Studio reports following error:
![image](https://user-images.githubusercontent.com/3978902/228802231-00beb9c2-7a04-48ee-b00c-0449b859e385.png)

and after some delay, visual studio restarts and try to reload the solution.

I can not sea any other error. Maybe I miss to install something?
Building Scottplot4 solution works fine.

**Reproducing:**

Just open the solution, for example ScottPlot5-wpf.slnf, with Visual Studio 2022 Version 17.5.3 / 64 bit

### System Details
* **ScottPlot Version:** 5.1
* **Operating System:** Windows 10
* **Application Type:** WPF

**Comment by swharden** [comment]
I've been noticing this too! Oof, Visual Studio 🙄 

> Building Scottplot4 solution works fine.

This is why I've been hesitant to solve this issue 😅 

I'll look into it later tonight though. Thanks for creating this issue!

**Comment by swharden** [comment]
Hi @KroMignon, this was a weird one! I fixed it by editing the .sln file and deleting all the lines nested below:

```
GlobalSection(ProjectConfigurationPlatforms) = postSolution
```

then I opened the solution file in Visual Studio, saved it, and closed it... now it works

* #2529

### 🤷🤷🤷
