### ISSUE TITLE
Primary X is Distance Secondary X is DateTime 

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2536]
Hi, just wonder how to add a secondary X-Axis to represent Time.
I have GPS Altitudes, Digital model altitudes, and speeds (Horizontal, Vertical, and 3D).
Speeds are calculated based on the time between two consecutive points.
Like this:
![image](https://user-images.githubusercontent.com/26789352/229245910-465d3603-8dce-4841-ad0e-44fb34e07318.png)

I would like to add a secondary X-axis **on the top** to represent time.
Each point on the primary X-axis (distance) represents a point that has a dateTime value as well.

**Questions I have:**

- How to populate the secondary X-axis?
- What to do with Y-axis ( I don't need it)?
- How do I format Ticks on the secondary X-axis to be displayed nicely when zooming in/out (down to seconds at high zooms, minutes to moderate zooms, and hours otherwise)?
- I don't want to show the full date. Just hours, minutes, and seconds.
- The finest Tick is 15 30 and 45. Representing either minutes or seconds.  Depending on the zoom level.
- Labels shown slanted by 45 degrees.

**Comment by swharden** [comment]
Axis labels can be rotated: https://scottplot.net/cookbook/4.1/category/axis-and-ticks/#rotated-x-ticks

Axis tick labels can be customized: https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#custom-tick-formatter (but if you're managing labels, don't call `XAxis.DateTimeFormat()`)

setup the two X axes:
```cs
var xAxisA = formsPlot1.Plot.XAxis;
var xAxisB = formsPlot1.Plot.AddAxis(ScottPlot.Renderable.Edge.Bottom);
xAxisB.DateTimeFormat(true);
```

hide the Y axes:
```cs
formsPlot1.Plot.YAxis.Ticks(false);
formsPlot1.Plot.YAxis2.Ticks(false);
```

To limit how far the user can zoom in, tie into the `formsPlot1.AxesChanged` event and if it's zoomed in more than you want then zoom out. I intend to add a flag in a future release that will let the user define how far in users can zoom in or out which will make this easier: 2250

**Comment by swharden** [comment]
Regarding your custom formatter, use a `double[]` for the horizontal axis and convert to/from `DateTime` using ToOADate and FromOADate https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tooadate
