### ISSUE TITLE
Background color when copying to clipboard

### ISSUE THREAD

**Issue by Neopentane1** [ScottPlot/ScottPlot#2537]
## Bug Report

**Issue:** 
I have a plot with a background color. When I go to copy the plot image, I want to change the plot background color to transparent, copy the image, then change the color back to its original color. However, whenever I do this, using the minimum code below, the copied image always has a light gray background instead of transparent.

**Reproducing:** 
 
Code for the button on a generic C# WinForms with a ScottPlot (FormsPlot1):

    FormsPlot1.BackColor = Color.LightGray;
    FormsPlot1.Refresh();
    
    FormsPlot1.BackColor = Color.Transparent;
    FormsPlot1.Refresh();
    
    Clipboard.SetImage(FormsPlot1.Plot.Render());
    
    FormsPlot1.BackColor = Color.LightGray;
    FormsPlot1.Refresh();

Should I be doing this a different way? Thanks!

### System Details
* **ScottPlot Version:** 4.1.61
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** .NET 7.0

**Comment by swharden** [comment]
Hi @Neopentane1!

I think this happens because the plot has a transparent background, and what you're doing is changing the color of the Form beneath it

I bet you can do something like this:
```cs
FormsPlot1.Style(figureBackground: Color.LightGray);
```

Let me know if that doesn't do the trick!

**Comment by swharden** [comment]
Whoops, I meant:

```cs
FormsPlot1.Plot.Style(figureBackground: Color.LightGray);
```

**Comment by Neopentane1** [comment]
Hey Scott,
That didn't work for me.

I have the test form below:
[image: image.png]

using ScottPlot;

namespace ScottPlotTest
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {

            FormsPlot1.Reset();

            // Commenting this line out generates a plot with a white
background.
            // Including this line generates a plot with a gray background.
            FormsPlot1.Plot.Style(figureBackground: Color.Transparent);

            FormsPlot1.Refresh();

            Clipboard.SetImage(FormsPlot1.Plot.Render());

        }

    }
}

================================
If I leave the indicated line uncommented, I get:
[image: image.png]

If I comment out the line, I get:
[image: image.png]

The underlying panel container for the plot is white. Based on these tests,
I do not believe that the plot is being correctly styled.

Let me know if you have additional insight. Thanks!

-Eric

**Comment by swharden** [comment]
Hi @Neopentane1, this works for me!

```cs
public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();
        formsPlot1.Plot.Style(figureBackground: Color.LightSkyBlue);
        formsPlot1.Refresh();
    }

    private void button1_Click(object sender, EventArgs e)
    {
        Bitmap bmp = formsPlot1.Plot.Render();
        Clipboard.SetImage(bmp);
    }
}
```

![image](https://user-images.githubusercontent.com/4165489/229638500-6cbea44d-6705-4825-be1d-aa651953692b.png)
