### ISSUE TITLE
List of Plot Focused Plot Points

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#2542]
The process requires remembering the specific appearance of the Plot object.
While panning and zooming the Plot object I would like to create a list of objects. Like, clicking the Plot object will create a new Object where an object(class) holds the following structure:

- X=Primary Xaxis Value (GetCoordinateX)
- Y=Primary Yaxis Value (GetCoordinateY)
- Z=Current Plot Zoom Level

Each time an element from the list is clicked Plot Object is Centered to X, Y, and zoomed to Z.

I have no idea:
- how to populate the Z value
- which function to call to Center the Plot based on X, Y, and Z value.

**Comment by swharden** [comment]
Hi @dusko23, I think this WinForms code demonstrates how to do this, but let me know if this doesn't do the trick! 👍 

```cs
// startup sequence
formsPlot1.Plot.AddSignal(ScottPlot.DataGen.Sin(51));
formsPlot1.Plot.AddSignal(ScottPlot.DataGen.Cos(51));
formsPlot1.Refresh();

formsPlot1.LeftClicked += (s, e) =>
{
    // show the coordinates for the clicked point
    (double x, double y) = formsPlot1.GetMouseCoordinates();
    System.Diagnostics.Debug.WriteLine($"Clicked: {x}, {y}");

    // show the zoom level
    AxisLimits z = formsPlot1.Plot.GetAxisLimits();
    System.Diagnostics.Debug.WriteLine($"Zoom: {z}");

    // center where the mouse was clicked
    formsPlot1.Plot.AxisPanCenter(x, y);
    formsPlot1.Refresh();
};
```
