### ISSUE TITLE
Signal Update LastIndex wrong value

### ISSUE THREAD

**Issue by Angeld10** [ScottPlot/ScottPlot#2578]
## Bug Report

**Issue:** Updating a signal of the same size causes the exception: 'lastIndex cannot exceed the dimensions of the existing Ys array'. I believe the Update method with 1 parameter is passing newData.Length as the lastIndex parameter to the Update method with 4 parameters. The latter method is comparing lastIndex to oldData.Length - 1 which will never match if both arrays are the same size.

**Reproducing:** Generate signal of any size. AddSignal to a plot, Update using same signal.

```cs
double[] y = ScottPlot.DataGen.Sin(100, 2, 0, 1, 0);
var scatterPlot = plotWindow.Edit.Plot.AddSignal(y);
scatterPlot.Update(y);
```

![updateException](https://user-images.githubusercontent.com/122924730/230755209-964b4e59-9cfb-4a7b-af4a-a2bfe24e737c.png)

### System Details
* **ScottPlot.WPF Version:** 4.1.62
* **Operating System:** Windows 11
* **Application Type:** WPF
* **.NET Version:** NET Framework 4.8

**Comment by swharden** [comment]
Thanks for reporting this @Angeld10! I fixed this issue in #2579 and will publish a new package later today 👍
