### ISSUE TITLE
How to fix a grid area so that it does not change size due to scaling?

### ISSUE THREAD

**Issue by mYcheng-95** [ScottPlot/ScottPlot#2586]
**ScottPlot Version:**  4.1.63

**Operating System:** win10 22H2

**Application Type:** WPF

**Question:**
 When I tried to zoom in/out on the chart, I noticed that as I changed the zoom level, the length of the tick labels also changed, which caused the actual area of the entire grid region to change, and the coordinate axis to move (especially on the vertical axis).
I have tried many methods, but none of them can achieve satisfactory results, including limiting the length of axis labels by formatting and adjusting the `Plot.Layout`'s left value.
  But these methods cannot fundamentally solve the problem, because the size of the dataset cannot limit the scale of the zoom. I looked at the zooming of `echarts` and found that no matter how it is zoomed, its coordinate axis will not shift, so it will not cause the graph area to become smaller and smaller with the zoom. How can I achieve this effect in `scottPlot`?

The following two images show that with the change of the scaling size, it is obvious that there is a significant displacement of the Y-axis.
![image](https://user-images.githubusercontent.com/30651076/231398296-a97ba0bb-5ab2-49c4-9662-44444e398097.png)

![image](https://user-images.githubusercontent.com/30651076/231398232-211d3c6b-ca31-4a51-b40d-973fdb6ba4dc.png)

The following two images show a comparison of zooming in echarts, where the Y-axis remains in a fixed position without any offset regardless of the zoom level.
![image](https://user-images.githubusercontent.com/30651076/231399170-375e516e-b7e2-4da7-9c50-846990d81f77.png)

![image](https://user-images.githubusercontent.com/30651076/231399049-7bfe6c43-1873-4b10-810b-89675c4f41bc.png)

**Comment by swharden** [comment]
Hi @mYcheng-95, thank you for this question and the excellent screenshots!

## Layout

It looks like you already discovered the layout options which allow users to define a fixed width for each axis: https://scottplot.net/cookbook/4.1/category/layout/#plot-layout

```cs
formsPlot1.Plot.Layout(left: 100);
```

## Offset Notation

It looks like eCharts reduces the size of the tick labels by using an _offset notation_ which is a feature you can enable with ScottPlot: https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#offset-notation

```cs
formsPlot1.Plot.YAxis.TickLabelNotation(offset: true);
```

![image](https://user-images.githubusercontent.com/4165489/231924027-8b2fd88f-23fd-464d-b9ea-1099fb811ba0.png)

Let me know if this does not resolve your issue 👍

**Comment by mYcheng-95** [comment]
I see. Could you please explain in more detail what you are trying to achieve and what specific problems you are facing with the current approach? I might be able to suggest alternative solutions based on that.
On the one hand, it will cause the `YAxis` title to shift to the left. On the other hand, it may lead to some confusion when displaying the plot.
I see. Even with `Plot.PixelPadding` to fix the borders, the `yAxis` still moves. Although you have tried to use `TickLabelFormat`, there are still some flaws.
![image](https://user-images.githubusercontent.com/30651076/231980307-ec819be0-5150-473c-a5a5-ae34fec60c32.png)

![image](https://user-images.githubusercontent.com/30651076/231980170-1b072b0a-4f29-452e-ac81-be14db5d86fc.png)
