### ISSUE TITLE
Distinguishing between data plots and plot component objects.

### ISSUE THREAD

**Issue by mYcheng-95** [ScottPlot/ScottPlot#2593]
## Feature Suggestion
I want to be able to distinguish between data plots and their corresponding components within the `IPlottable[]` array in the code, so that I can more easily obtain the desired data plots.
**Feature description:** 
I want to implement a `tooltip` similar to `echarts` in `MyTooltip`. To do this, I obtained the `IPlottables` object of the plot and parsed it in `MyTooltip` in the hope of obtaining the corresponding `IPlottable` object, such as scatter, etc. However, I found that the `Crosshair` object could also be obtained by me! I cannot distinguish them, which leads me to not know how to draw them. If I force the `label` to be passed in, I can refer to the method in `Legend` to obtain the curve object, but I cannot achieve this, and I found that if I do not pass in the `label` parameter when drawing the curve, the `Legend` will also not be drawn. I have tried removing the `series` name in `echarts` and directly using the line color as the label for its tooltip.

**Comment by swharden** [comment]
> I want to implement a tooltip similar to echarts

I'm not familiar with echarts so I googled it and found their tooltips look like this

https://echarts.apache.org/examples/en/editor.html?c=line-sections

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/0f424feb-db3f-4a53-a4b4-81bc6b8f3da6)

> I found that the Crosshair object could also be obtained by me

I think only certain plot types implement the interface allowing them to be "found" by a mouse hover. I think the interface is `IHittable`, and plot types that implement it can be engaged with the mouse.

Tooltip should be one of those. Check out the ScottPlot demo "hittable demo"

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/dd0e9920-2bb1-4b5b-a9a9-d4937a7ba964)

https://github.com/ScottPlot/ScottPlot/blob/5a823d4709fbff32c40e2c7189a17f5e3a582bed/src/ScottPlot4/ScottPlot/Plottable/Tooltip.cs#L65

I think you could get the list of plottables then for reach on that implements `IHittable` try the `HitTest()` and it will return `true` if it's under the mouse.

These resources may also be useful:
* https://scottplot.net/faq/mouse-position/
* https://scottplot.net/faq/custom-plot-type/#mouse-interactivity

Hope it helps!
Scott
