### ISSUE TITLE
FinancePlot.GetBollingerBands(): add `sdCoeff` argument

### ISSUE THREAD

**Issue by Minu476** [ScottPlot/ScottPlot#2594]
```cs
GetBollingerBands(int N, double sdCoeff = 2)
```

this modification allow passing values other than default sdCoeff=2

**Comment by swharden** [comment]
Hi @Minu476, thank you for opening this issue!

Re-stating the suggestion, Bollinger bands typically report `mean ± 2*SD`, but an option should be added to allow customizing the `2` coefficient

I like the idea! I'll add that into the next release. Relevant code is here:

https://github.com/ScottPlot/ScottPlot/blob/5a823d4709fbff32c40e2c7189a17f5e3a582bed/src/ScottPlot4/ScottPlot/Plottable/FinancePlot.cs#L278-L294

I notice that the core functions that calculate the Bollinger bands already accept `sdCoeff` as an optional argument, so the solution here is to add a `BollingerSD` property to the `FinancePlot` to allow it to be customized.

I'll add this in today and include it in the next release 👍
