### ISSUE TITLE
How do I keep axis limits when removing the last plottable?

### ISSUE THREAD

**Issue by FannyAtGitHub** [ScottPlot/ScottPlot#2598]
**ScottPlot Version:** 4.1.63
**Application Type:** WinForms

**Question:** 
Is there any way to keep axis limits when plottables are removed as the last/only plottable object?

I understand the concept of resetting the axis limits when all plottables are removed. 
But sometimes I would like to prevent this behaviour e.g. when annotations or horizontal/vertical lines are removed and there might not be any 'real' data in the plot yet.
Is there any way to do so? It would help a lot because the possible workarounds are quite annoying to handle (e.g. dummy plottables or checking if the removed object is last and resetting the limits manually).

Thanks in advance for any helpful replies! :)

**Comment by swharden** [comment]
Hi @FannyAtGitHub, sorry about the delayed response! Something like this should work:

```cs
var originalLimits = formsPlot1.Plot.GetAxisLimits();
formsPlot1.Plot.Clear();
formsPlot1.Plot.SetAxisLimits(originalLimits);
```
