### ISSUE TITLE
SP4: Margin error between axis label & tick labels when using ManualTickPositions

### ISSUE THREAD

**Issue by szescxz** [ScottPlot/ScottPlot#2605]
## Bug Report

**Issue:**
| A.jpg | B.jpg |
|---|---|
| ![](https://user-images.githubusercontent.com/49463229/233815600-15315890-d61d-468d-b3a3-40e470e24929.jpg) | ![](https://user-images.githubusercontent.com/49463229/233815606-bb42d894-a40d-455c-a29b-3950442c2f56.jpg) |

~~_Similar to #699?_~~ Seems like my issue is a duplicate of #2603. Right now I'm using suggestions at https://github.com/ScottPlot/ScottPlot/issues/699#issuecomment-762378100 as a workaround.

**Reproducing:**

```cs
using ScottPlot;
Plot plot;

plot = new Plot();
plot.Title("Automatic Tick Positions");
plot.LeftAxis.Label("Left Axis Label", size: 50);
plot.LeftAxis.TickLabelStyle(fontSize: 50);
plot.SaveFig("A.jpg");

plot = new Plot();
plot.Title("Manual Tick Positions");
plot.LeftAxis.Label("Left Axis Label", size: 50);
plot.LeftAxis.TickLabelStyle(fontSize: 50);
plot.LeftAxis.ManualTickPositions(new double[] { 10, 0, -10 }, new string[] { "10", "0", "-10" });
plot.SaveFig("B.jpg");
```

### System Details
* **ScottPlot Version:** 4.1.63
* **Operating System:** Windows 11
* **Application Type:** console
* **.NET Version:** .NET 6.0

<details>
  <summary><h3>Another related bug that might also worth noting</h3></summary>

If I comment out the second `plot = new Plot();` then the margin is "correct", however I'm still feeling off about this:
```cs
using ScottPlot;
Plot plot;

plot = new Plot();
plot.Title("Automatic Tick Positions");
plot.LeftAxis.Label("Left Axis Label", size: 50);
plot.LeftAxis.TickLabelStyle(fontSize: 50);
plot.SaveFig("A.jpg");

//plot = new Plot();
plot.Title("Manual Tick Positions");
plot.LeftAxis.Label("Left Axis Label", size: 50);
plot.LeftAxis.TickLabelStyle(fontSize: 50);
plot.LeftAxis.ManualTickPositions(new double[] { 10, 0, -10 }, new string[] { "10", "0", "-10" });
plot.SaveFig("B.jpg");
```
![](https://user-images.githubusercontent.com/49463229/233815976-f1134754-e838-4c3f-bd58-43cbd4992b0e.jpg)
</details>

**Comment by swharden** [comment]
Thanks for reporting this @szescxz! Definitely looks like a bug. I'll fix and discuss in #2603
