### ISSUE TITLE
SP4: Poor automatic layout behavior for empty tick labels

### ISSUE THREAD

**Issue by szescxz** [ScottPlot/ScottPlot#2606]
**ScottPlot Version:** 4.1.63

**Operating System:** Windows 11

**Application Type:** WPF

**Question:**
As the title says.
My current approach is to use `TickLabelFormat`, making it returns an empty string when it's a decimal:

```xaml
<WpfPlot x:Name="plotControl" />
```

```cs
plotControl.Plot.BottomAxis.MinimumTickSpacing(0.5);
plotControl.Plot.BottomAxis.TickLabelFormat((d) => d % 1 == 0 ? d.ToString() : string.Empty);
```

However this approach causes inconsistency on layout when zooming with mouse wheel:
![](https://user-images.githubusercontent.com/49463229/233836118-7f9fa513-b9ec-41f4-b138-a2368db4cff9.gif)

**Comment by swharden** [comment]
Hi @szescxz, thanks for this question!

I found an even simpler solution:

```cs
plotControl.Plot.YAxis.Ticks(major: true, minor: true, majorLabels: false);
plotControl.Plot.XAxis.Ticks(major: true, minor: true, majorLabels: false);
```

**Comment by swharden** [comment]
> hide labels for decimal ticks

Oops, I realize now I misunderstood the question 😅 

My "solution" hides all tick labels, and I missed your custom tick formatter 🤦 reopening 😅

**Comment by swharden** [comment]
Thanks again for reporting this! I believe this is now solved by #2634

```cs
using ScottPlot;
ScottPlot.Plot plt = new();
plt.BottomAxis.MinimumTickSpacing(0.5);
plt.BottomAxis.TickLabelFormat((d) => d % 1 == 0 ? d.ToString() : string.Empty);
plt.Launch.FormsPlot();
```

**Comment by szescxz** [comment]
> My "solution" hides all tick labels, and I missed your custom tick formatter 🤦 reopening 😅

Yeah, with current ScottPlot implementation, I think using the custom tick formatter is the only way to mimic a ruler, where only integer ticks are labeled:
![https://commons.wikimedia.org/wiki/File:Steel_ruler_closeup.jpg](https://upload.wikimedia.org/wikipedia/commons/8/86/Steel_ruler_closeup.jpg)

Therefore, the first solution you've come up with (hiding labels by tick type) isn't feasible unless ScottPlot is able to provide 3 types of ticks instead of 2 (major & minor).

**Comment by swharden** [comment]
> Therefore, the first solution you've come up with (hiding labels by tick type) isn't feasible

Hopefully #2634 solved it. I'll publish a new package on NuGet tonight and you can let me know if it doesn't perform as expected.

> mimic a ruler

In case you hadn't seen it, https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#ruler-mode

Thanks again for this issue!
