### ISSUE TITLE
SP5: ScottPlot5 fails on Debian Linux 11

### ISSUE THREAD

**Issue by chrisxfire** [ScottPlot/ScottPlot#2607]
## Bug Report

**Issue:**
```
System.TypeInitializationException: The type initializer for 'ScottPlot.FontService' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKFontManager' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libSkiaSharp.so: cannot open shared object file: No such file or directory
/home/chris/src/blsrpt/bin/Debug/net7.0/libSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/home/chris/src/blsrpt/bin/Debug/net7.0/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libSkiaSharp: cannot open shared object file: No such file or directory
/home/chris/src/blsrpt/bin/Debug/net7.0/libSkiaSharp: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/liblibSkiaSharp: cannot open shared object file: No such file or directory
/home/chris/src/blsrpt/bin/Debug/net7.0/liblibSkiaSharp: cannot open shared object file: No such file or directory`
```

**Reproducing:** (What do others have to do to reproduce the bug?)

Run ScottPlot5 on Debian Linux 11.  This issue persists even if `libfreetype6`, `libfontconfig1`, and `fontconfig` are installed.

See https://github.com/mono/SkiaSharp/issues/1341 which recommends using `SkiaSharp.NativeAssets.Linux.NoDependencies` instead of `SkiaSharp`.

### System Details
* **ScottPlot Version:** 5.0.4-beta
* **Operating System:** Debian Linux 11
* **Application Type:** Console
* **.NET Version:** .NET 7.0.5

**Comment by swharden** [comment]
Thanks for reporting this @chrisxfire!

The key line in your error message seems to be:

```
System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies
```

There are lots of recommended fixes on this issue:

* https://github.com/mono/SkiaSharp/issues/1341

I lol'd seeing my icon in the list of responses 😆 

It looks like currently I'm just including `SkiaSharp.NativeAssets.Linux` but according to [this guy](https://github.com/mono/SkiaSharp/issues/1341#issuecomment-945041751) I should also include `SkiaSharp.NativeAssets.Linux.NoDependencies`

https://github.com/ScottPlot/ScottPlot/blob/af235f5759be061940630ec54360cdd892f79fdb/src/ScottPlot5/ScottPlot5/ScottPlot.csproj#L54-L56

I'll give that a try and publish a release and see if it fixes your problem! We can re-open this issue if it doesn't.
