### ISSUE TITLE
Set zoom to auto Y fill.

### ISSUE THREAD

**Issue by BizUnity** [ScottPlot/ScottPlot#2612]
Hello;

I'm currently creating an open source [Technical Analysis library](https://github.com/BizUnity/StockPlot) and I have a question.
When I zoom using the MouseWheel; How can I ensure in the price area (Finance Plot) that the value take all the available Y space please?
You can see at the image when I zoom there is a lot of space bellow the lowest price value, and I'd like to automatically fill this space.
![zoom](https://user-images.githubusercontent.com/128179084/235666645-5b3befaf-bf96-4376-adb0-bcb5cc6a5dde.gif)

Thanks a lot in advance, and for your amazing work!

**Comment by mjpz** [comment]
rough idea

monitor the FormsPlot AxesChanged event

use the current AxisLimits X values to calculate the new Y min and max values

set the new AxisLimits (which raise again the AxesChanged event)

**Comment by swharden** [comment]
## StockPlot
https://github.com/BizUnity/StockPlot

Very cool! 🚀🚀🚀

## Contributing Additional Technical Indicators

If you code any additional technical indicators, I'd love to roll them into the [Finance.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot/Statistics/Finance.cs) so feel free to create a PR some day that adds any functions you think would be useful into that class.

## Auto-Scaling to Visible Data

> When I zoom using the MouseWheel; How can I ensure in the price area (Finance Plot) that the value take all the available Y space please?

You can use the `OnAxesChanged` event as described on https://scottplot.net/faq/shared-axes/ and whenever it is triggered call `formsPlot1.Plot.AxisAutoY();`

Let me know if that doesn't do the trick, and good luck continuing to develop your app!

**Comment by BizUnity** [comment]
Work like a charm! Thank you Scott!
Will definitly add a few indicators on your file :)
