### ISSUE TITLE
SP5: Roadmap and Support for .NET MAUI

### ISSUE THREAD

**Issue by jldearmas** [ScottPlot/ScottPlot#2620]
I'll be starting in some days to develop the software for an EIT project, and I would like to use ScottPlot library, so I have a pair of questions:
- Is there some kind of Roadmap with deadlines for Version 5.0?
- Will be support for .NET MAUI?

**Comment by hellfo** [comment]
It looks like Oxyplot supports MAUI, and expect ScottPlot to support it too

**Comment by swharden** [comment]
Hi @jldearmas, 

I am currently not committing to any deadlines, but I am working hard on bringing ScottPlot 5 to feature parity with ScottPlot 4, and will then focus on expanding platform support. As a hobby open source maintainer who doesn't work in tech, ScottPlot is the project that currently garners most of my attention, but it's still something I only work on in my free time and it's difficult to predict when these features will be complete.

However, if someone is familiar with MAUI and wants to create the control, I would be happy to review a PR and merge it in. 

Creating a MAUI control should be pretty straightforward by mimicking the functionality of one of the other controls, such as the WinForms control:

https://github.com/ScottPlot/ScottPlot/blob/521bbcf76cd26ac64fd15155011e4bf48967ccc4/src/ScottPlot4/ScottPlot.WinForms/FormsPlot.cs#L1-L276

PS: Blazor support is something I am very interested in supporting soon, and some progress has been made on this front #2380

**Comment by jldearmas** [comment]
Thank you so much for your response.

I also interested in Blazer.

I have no so much experience with MUAI yet, but with Xamarin, so I will try
to get sometime to work in the Control.

Best regards

JL
