### ISSUE TITLE
how can i create a marker with MouseEvent

### ISSUE THREAD

**Issue by allen3371** [ScottPlot/ScottPlot#2621]
I want to show a red circle marker on th chart,and when i click the marker, show some thing 

i read the cookbook ,but i can't find the solution 

can you help me ?

thanks!

**Comment by swharden** [comment]
Hi @allen3371,

Check out the ScottPlot Demo app and its source code. It demonstrates how mouse-interactive behaviors can be achieved. https://scottplot.net/demo/

Also you may find this page useful: https://scottplot.net/faq/mouse-position/
