### ISSUE TITLE
WinForms: demonstrate fixed-ratio plot control while resizing

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2628]
The goal is to mimic MATLAB behavior as described by @liuhongran626 in https://github.com/ScottPlot/ScottPlot/discussions/2618

I believe this can be achieved by placing the `FormsPlot` inside a `Panel` and using it's `SizeChanged` event to trigger resizing the plot and requesting a repaint

The solution could be demonstrated using a bit of WinForms code (does not require modification of ScottPlot code)

**Comment by bukkideme** [comment]
Do not we have such option already? Like the "formsPlot1.Plot.AxisScaleLock(true, EqualScaleMode.PreserveSmallest);" ?

**Comment by swharden** [comment]
It looks like this is possible by putting a plot control inside a container and having it resize to a fixed ratio whenever the container resizes.

## Before
![before](https://github.com/ScottPlot/ScottPlot/assets/4165489/708b9e2b-584e-4b4e-8d43-52e78093729a)

## After

I made the Panel outline 3D for this demo, but you could make the outline invisible.

![after](https://github.com/ScottPlot/ScottPlot/assets/4165489/7d7159b4-9756-4eca-992b-8bb006b4e8e4)

## Implementation

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/73b4066e-471d-40e2-933b-ede638af5c85)

```cs
public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        formsPlot1.Plot.AddSignal(ScottPlot.Generate.Sin());
        formsPlot1.Plot.AddSignal(ScottPlot.Generate.Cos());
        formsPlot1.Refresh();

        panel1.SizeChanged += Panel1_SizeChanged;
        Panel1_SizeChanged(null, null);
    }

    private void Panel1_SizeChanged(object sender, EventArgs e)
    {
        double targetAspectRatio = 16.0 / 9.0;
        double panelAspectRatio = (double)panel1.Width / panel1.Height;
        bool isTall = panelAspectRatio < targetAspectRatio;

        if (isTall)
        {
            Text = "tall panel";
            formsPlot1.Width = panel1.Width;
            formsPlot1.Height = (int)(formsPlot1.Width / targetAspectRatio);
            int yOffset = (panel1.Height - formsPlot1.Height) / 2;
            formsPlot1.Location = new(0, yOffset);
        }
        else
        {
            Text = "wide panel";
            formsPlot1.Height = panel1.Height;
            formsPlot1.Width = (int)(formsPlot1.Height * targetAspectRatio);
            int xOffset = (panel1.Width - formsPlot1.Width) / 2;
            formsPlot1.Location = new(xOffset, 0);
        }
    }
}
```
