### ISSUE TITLE
live data crash on mouse wheel scroll

### ISSUE THREAD

**Issue by Jordant190** [ScottPlot/ScottPlot#2630]
exception: "System.ArgumentException: 'mouse wheel was scrolled but neither direction is set'" on live data example when mouse wheel is excessively zoomed in and out. Have tried render locking, forcing zoom in only one direction, and slowing down mouse wheel scroll. Found bug in my own code and replicated in live data demo. If mouse wheel delta value is low, did not see issue or if slowly moved. But if control is used by another user, they won't know to avoid issue so looking for a fix.

**Comment by swharden** [comment]
Hi @Jordant190, thanks for reporting this! 

I fixed this issue (#2600 #2626) and will publish an updated package to NuGet tonight, but let me know if it doesn't work as expected after the upgrade 👍
