### ISSUE TITLE
Add a property 'ScaleY' , similar with the 'OffsetY', for the Signal class.

### ISSUE THREAD

**Issue by MyZQL** [ScottPlot/ScottPlot#2642]
## Feature Suggestion

**Feature description:**
 I want to dynamically set a plot scale (i.e. multiply 'ys' by a specific number before rendering) for a Signal without modifying its raw data 'ys', but currently it seems there is no built-in method to make it. 
**Code example:**

```cs
// a code sample may improve communication
var plt = new ScottPlot.Plot();
var signal = plt.AddSignal(dataY);
signal.OffsetY = 10.0;
signal.ScaleY = 5.0;
plt.Refresh();
```

**Comment by Guillaume-Deville** [comment]
Hello @MyZQL, I tried to implement your feature to the signal object.
But since I am pretty new to this, I will need a feedback from Scott.
