### ISSUE TITLE
AxisTicks: add TickWidth option

### ISSUE THREAD

**Issue by SaltyCam** [ScottPlot/ScottPlot#2643]
## Feature Suggestion

Please add ability to change the TickWidth

Example:

```cs
formsPlot1.XAxis.AxisTicks.TickWidth = 10;
```

**Comment by swharden** [comment]
https://github.com/scottplot/scottplot/blob/main/src/ScottPlot4/ScottPlot/Renderable/AxisTicksRender.cs#L61

**Comment by swharden** [comment]
resolved in #2654
