### ISSUE TITLE
Image: add anti-aliasing option

### ISSUE THREAD

**Issue by mYcheng-95** [ScottPlot/ScottPlot#2649]
**ScottPlot Version:** 4.1.64

**Operating System:** win10

**Application Type:** console

**Question:** My image is a heatmap generated from a large dataset (directly using heatmap function affects efficiency due to the large amount of data). The width of the image is approximately 49,000 pixels, and I have set the height to 1000 pixels. When I add this image in Plt, I need to change the height of the image by stretching it, but the default anti-aliasing property causes abnormalities in the image when zoomed in. How can I disable this anti-aliasing property?

Here is a screenshot of the image after being zoomed in using Plt:
![image](https://github.com/ScottPlot/ScottPlot/assets/30651076/bf5d0d17-26c3-4416-a957-9bb228b2ce2a)

Here is a screenshot of the image after being saved as a file and then zoomed in:
![image](https://github.com/ScottPlot/ScottPlot/assets/30651076/bef28661-3c32-4f96-8dd1-0408ecde5d8c)

**Comment by swharden** [comment]
Hi @mYcheng-95, thanks for raising this issue!

Note that `AddHeatmap()` has options for enabling/disabling anti-aliasing: https://scottplot.net/cookbook/4.1/category/plottable-heatmap/#smooth-heatmap

However it sounds like you are using `AddImage()` which currently does not have such an option. I'll add an `AntiAlias` configuration option to images to make this possible in the next release 👍
