### ISSUE TITLE
FormsPlotViewer: Support bidirectional syncing

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2653]
Hi!

The actual behaviour of the "Open in new window" is that, we get a new window with the content of the parent window. However, when we update the actual plot, change its content, etc, these changes only gets updated in the opened secondary window, if we mouse click inside the ScottPlot control inside this secondary window.

I wonder how we could make this useful feature more interactive? Of course the developer can just make her/his own right click menu, and create a custom secondary window, but we already have this feature, we could improve it? 
As I see a FormsPlotViewer.cs class is used in this case, but I do not understand yet why the changes only propagate from the parent to the child Plot when we click inside the secondary child plot? Do you think we could make it do this update automatic? 
Regards!

edit: i had a question about the opposite, some time ago, how to make it NOT reflecting the changes inside the parent Plot :) Here it is: https://github.com/ScottPlot/ScottPlot/issues/2493

**Comment by bukkideme** [comment]
Actually we could have a bool SyncChildWindow property, and its default value would be false: the recent behaviour?
And if we set it true, the secondary window would auto sync its content to the parent FormsPlot?

Anyway, I see also benefits in the recent, actual behaviour: the "open in new window" acts as a natural "snapshot" maker, and it will only update its content, if we click inside. But I imagine, more control over this behaviour, and some more examples in the Cookbook, would give usefull options to the users...?

**Comment by swharden** [comment]
> Do you think we could make it do this update automatic?

Yeah! I think the same strategy used here can be used to update axis limits and force a redraw to the original plot any time the pop-out plot has its axes changed. https://scottplot.net/faq/shared-axes/

If you give this a try and get something working, I'd be happy to add a sync property somewhere. Maybe even as an optional argument to the constructor?

**Comment by swharden** [comment]
I hacked this in just now and it works pretty well! If you want to refine this and create a PR, I'd be happy to review it! 

Bonus points if you do it for all the controls (not just WinForms). It should be pretty easy once you get the first one figured out.

![new-window](https://github.com/ScottPlot/ScottPlot/assets/4165489/3c5a2197-691b-482c-9942-32227916abe8)

```cs
public partial class FormsPlotViewer : Form
{
	private readonly FormsPlot ParentControl;

	// CALL THIS OVERLOAD WHEN CREATING A NEW WINDOW FROM SCRATCH
	public FormsPlotViewer(ScottPlot.Plot plot, int windowWidth = 600, int windowHeight = 400, string windowTitle = "ScottPlot Viewer")
	{
		InitializeComponent();
		Width = windowWidth;
		Height = windowHeight;
		Text = windowTitle;

		formsPlot1.Reset(ParentControl.Plot);
		formsPlot1.Refresh();
	}

	// CALL THIS OVERLOAD WHEN LAUNCHING A NEW WINDOW FROM AN EXISTING FORM
	public FormsPlotViewer(FormsPlot parent, int windowWidth = 600, int windowHeight = 400, string windowTitle = "ScottPlot Viewer", bool sync = true)
	{
		InitializeComponent();
		Width = windowWidth;
		Height = windowHeight;
		Text = windowTitle;

		ParentControl = parent;
		formsPlot1.Reset(ParentControl.Plot);
		formsPlot1.Refresh();

		if (sync)
			formsPlot1.AxesChanged += (s, e) => ParentControl.Refresh();
	}
}
```

**Comment by bukkideme** [comment]
Hi! I hope i will find some time in the next days to have a look. So i guess in this case the "binding" is two directional, yes? 
Also, what happens if we update and refresh the content in the parent, it should automatically update the child window too. But i will have a look anyway :)
And yes, an option in the constructor would be great. Or also make it a property which can be changed during runtime?
Thanks!

**Comment by bukkideme** [comment]
Hi!

I started to think about how to do this. First, we would need bi-directional event handling. So if we change axis at the child, then we refresh the parent too. 
But this is not enough. What about growing/changing plot data or plot style, etc at the parent? Then the AxesChanged event is not enough, so for example plot data changes will be not updated at the child formsPlot. 

What about if we introduce a "Refreshed" Event? This event would broadcast any plot refresh/render occasions, and the FormsPlotViewer instance would subscribe for this Event. In this way, we could always refresh the child, the formsPlot inside the FormsPlotViewer class.

What do you think? I hope find time today to put together some example for this.

**Comment by bukkideme** [comment]
This came to my mind, it works in my tests. I make a PR.

Created a new event in FormsPlot.cs:
```
/// <summary>
/// This event is invoked any time the bitmap changed or updated.
/// </summary>
public event EventHandler BitmapChangedOrUpdated;
```

And this is the FormsPlotViewer class modification: 

```
`public partial class FormsPlotViewer : Form
    {
        private readonly FormsPlot ParentControl;
        public enum SyncType { NoSync, SyncToParent, SyncFromParent };

        public FormsPlotViewer(ScottPlot.Plot plot, int windowWidth = 600, int windowHeight = 400, string windowTitle = "ScottPlot Viewer")
        {
            InitializeComponent();
            Width = windowWidth;
            Height = windowHeight;
            Text = windowTitle;

            formsPlot1.Reset(plot);
            formsPlot1.Refresh();
        }

        // CALL THIS OVERLOAD WHEN LAUNCHING A NEW WINDOW FROM AN EXISTING FORM
        public FormsPlotViewer(FormsPlot parent, int windowWidth = 600, int windowHeight = 400, string windowTitle = "ScottPlot Viewer", SyncType syncType = SyncType.NoSync)
        {
            InitializeComponent();
            Width = windowWidth;
            Height = windowHeight;
            Text = windowTitle;

            ParentControl = parent;
            formsPlot1.Reset(ParentControl.Plot);
            formsPlot1.Refresh();

            switch (syncType)
            {
                case SyncType.NoSync:
                    break;

                case SyncType.SyncToParent:
                    formsPlot1.AxesChanged += (s, e) => ParentControl.Refresh();
                    break;

                case SyncType.SyncFromParent:
                    parent.BitmapChangedOrUpdated += (s, e) => formsPlot1.Refresh();
                    break;
            }            
        }
    }`
```
