### ISSUE TITLE
cannot find method: System.ValueTuple

### ISSUE THREAD

**Issue by John1911603424** [ScottPlot/ScottPlot#2661]
**Issue:** System.MissingMethodException:“ cannot find method:“System.ValueTuple`2<Double,Double> ScottPlot.Control.ControlBackEnd.GetMouseCoordinates(Int32, Int32)”

**Reproducing:**

```cs
// a code sample may improve communication
private void FormsPlot_MouseMove(object sender, MouseEventArgs e)
{
    FormsPlot formPlot = (FormsPlot)sender;
    Crosshair crosshair = CrosshairsByPlot[formPlot];
    (double coordinateX, double coordinateY) = formPlot.GetMouseCoordinates();

    tst_xCoordinate.Text = $"{coordinateX:0.00000000}";
    tst_yCoordinate.Text = $"{coordinateY:0.00000000}";

    formPlot.Refresh(lowQuality: true, skipIfCurrentlyRendering: true);
}
```

### System Details
* **ScottPlot Version:** 4.1.123?
* **Operating System: Windows 11
* **Application Type: WinForms
* **.NET Version: NET Framework 4.7.2 and 4.8

**Comment by swharden** [comment]
Hi @John1911603424 thanks for reporting this!

However, not being able to locate `System.ValueTuple` seems like an environment problem of some type, and not a ScottPlot problem. Googling for this error message I find lots of suggestions for how to resolve it:

https://stackoverflow.com/questions/8058832/system-missingmethodexception-method-not-found

> This is a problem which can occur when there is an old version of a DLL still lingering somewhere around. Make sure that the latest assemblies are deployed and no duplicated older assemblies are hiding in certain folders. Your best bet would be to delete every built item and rebuild/redeploy the entire solution.

> I had a unit test project which was pulling in our companies internal EF Nuget data access package and that code pulled in an external package whose version was way behind the current version.
> The issue was that the Nuget settings for the top level package was set to the least version; and the lower level/older version won, and that was used during the operations....
> Hence it silently got the wrong version for a common assembly used by both the package and the app.

> I resolved this issue by installing the correct .NET Framework version on the server. The website was running under version 4.0 and the assembly it was calling to was compiled for 4.5. After installation of .NET Framework 4.5 and upgrading the website to 4.5, all works fine.

> Restarting Visual Studio actually fixed it for me. I'm thinking it was caused by old assembly files still in use, and performing a "Clean Build" or restarting VS should fix it.

**Comment by John1911603424** [comment]
Thanks. I have solved this problem.
