### ISSUE TITLE
Support for Avalonia 11.0.0-preview8 and later

### ISSUE THREAD

**Issue by Developer-Alexander** [ScottPlot/ScottPlot#2664]
## Feature Suggestion

**Feature description:** 
Please support Avalonia 11.0.0-preview8 and upcoming versions in the future.

**Comment by swharden** [comment]
To keep things simple, the ScottPlot targets the latest _release_ version of Avalonia (not the latest _preview_ version)

Related issues:
* #2507
* #2321
* #2184
* #2183
