### ISSUE TITLE
Index 

### ISSUE THREAD

**Issue by FremderMuc** [ScottPlot/ScottPlot#2669]
Hello, I'm new to Scottplot and need - after a long search - help:

```cs
SigPlotXY = fPlotrb1.Plot.AddSignalXYConst(X, Y, Color.Red);
            fPlotrb1.Plot.XAxis.DateTimeFormat(true);
```

after zooming into a certain area, I need the index of the visible window

```cs
var limits = fPlotrb1.Plot.GetAxisLimits();
```
here I unfortunately only get the DateTime data from XMin and XMax

I just want to calculate the min and max values for the visible area...

```cs
fPlotrb1.Plot.AxisAutoY(0,0); ' <- only XMin and Xmax from visible area** 
```

what i must do :-) and sorry for my english :-) i come from ZedGraph 

and i not found how i can use the data with INDEX ?

thanks for help

Ritsch from munich

**Comment by swharden** [comment]
Hi @FremderMuc, this code example should answer your question

```cs
public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        double[] data = ScottPlot.Generate.RandomWalk(100_000);
        var signal = formsPlot1.Plot.AddSignal(data);
        formsPlot1.Refresh();

        formsPlot1.AxesChanged += (s, e) =>
        {
            var limits = formsPlot1.Plot.GetAxisLimits();
            int index1 = (int)(limits.XMin * signal.SampleRate);
            int index2 = (int)(limits.XMax * signal.SampleRate);
            Text = $"View is from index {index1} to index {index2}";
        };
    }
}
```

![index](https://github.com/ScottPlot/ScottPlot/assets/4165489/595af653-ba61-4657-a761-43d435c952eb)
