### ISSUE TITLE
How to plot several different live data with signalPlot?

### ISSUE THREAD

**Issue by back2childhood** [ScottPlot/ScottPlot#2671]
### I need to display several different live data, and I choose signalPlot to achieve my project. The following is part of my project, I am confused about what's wrong with my code. Every time I run the code, there is only one line in the FormPlot.........Please help me about this trouble, thanks a lot!
```c#
        private static SignalPlot realTimeSignalPlot;
        private static SignalPlot realTimeSignalPlot2;
        private static SignalPlot realTimeSignalPlot3;

        static int points = 10000;

        double[] values1 = new double[points];
        double[] values2 = new double[points];
        double[] values3 = new double[points];
    {
            formsPlot1.Plot.Title("Real-time map");
            formsPlot1.Plot.XLabel("angle(°)");
            formsPlot1.Plot.YLabel("scope(dB)");
            formsPlot1.Refresh();

            realTimeSignalPlot = formsPlot1.Plot.AddSignal(values1, label: "test1");
            realTimeSignalPlot2 = formsPlot1.Plot.AddSignal(values2, label: "test2");
            realTimeSignalPlot3 = formsPlot1.Plot.AddSignal(values3, label: "test3");

            realTimeSignalPlot.MaxRenderIndex = 0;
            realTimeSignalPlot2.MaxRenderIndex = 0;
            realTimeSignalPlot3.MaxRenderIndex = 0;
            formsPlot1.Plot.Legend();
            //formsPlot1.Refresh();

            for(int i = 0; i < 10; ++i)
            {
                hLine[i] = formsPlot1.Plot.AddHorizontalLine(0);
                hLine[i].IgnoreAxisAuto = true;
                hLine[i].PositionLabel = true;
            }
            vLine = formsPlot1.Plot.AddVerticalLine(0);
            vLine.IgnoreAxisAuto = true;
            vLine.PositionLabel = true;

            timer.Enabled = true;
            timer.Interval = 20;
            timer.Elapsed += new System.Timers.ElapsedEventHandler(random);

            Thread th = new Thread(random);
            th.IsBackground = true;
            th.Start();
        }

        void random()
        {
            for (int i = 0; i < 9999; i++)
            {
                values1[i] = new Random().NextDouble();
                values2[i] = new Random().NextDouble();
                values3[i] = new Random().NextDouble();

                if (formsPlot1.InvokeRequired)
                {
                    Action action = delegate ()
                    {
                        formsPlot1.Refresh();
                    };
                    this.formsPlot1.Invoke(action);
                }
                else
                {
                    formsPlot1.Plot.AxisAutoX();
                    formsPlot1.Plot.AxisAutoY();
                    formsPlot1.Refresh();
                }

                realTimeSignalPlot.MaxRenderIndex++;
                realTimeSignalPlot2.MaxRenderIndex++;
                realTimeSignalPlot3.MaxRenderIndex++;
            }
        }
```

**Comment by back2childhood** [comment]
![image](https://github.com/ScottPlot/ScottPlot/assets/97512873/f9ecdd94-abe8-49a7-a647-78f7138dfced)

**Comment by StendProg** [comment]
Hi @back2childhood ,

You can try init random generator only once at startup.
```c#
private Random rnd = new Random();

...

values1[i] = rnd.NextDouble();
values2[i] = rnd.NextDouble();
```

**Comment by back2childhood** [comment]
> Hi @back2childhood ,
> 
> You can try init random generator only once at startup.
> 
> ```cs
> private Random rnd = new Random();
> 
> ...
> 
> values1[i] = rnd.NextDouble();
> values2[i] = rnd.NextDouble();
> ```

amazing! that really works! Thank you!! 
But now I have two new questions: 
* first, when I tap the right click and choose `zoom to fit data`， my software will be non-response, the only way to close the window is forced-quit. Do you have any idea?
* second, I use `formsPlot1.Plot.AxisAutoX();   formsPlot1.Plot.AxisAutoY();` in my code but it doesn't work, I still need to scroll the chart by myself.

I hope you can give me some idea about those two question.

**Comment by back2childhood** [comment]
> > Hi @back2childhood ,
> > You can try init random generator only once at startup.
> > ```cs
> > private Random rnd = new Random();
> > 
> > ...
> > 
> > values1[i] = rnd.NextDouble();
> > values2[i] = rnd.NextDouble();
> > ```
> 
> amazing! that really works! Thank you!! But now I have two new questions:
> 
> * first, when I tap the right click and choose `zoom to fit data`， my software will be non-response, the only way to close the window is forced-quit. Do you have any idea?
> * second, I use `formsPlot1.Plot.AxisAutoX();   formsPlot1.Plot.AxisAutoY();` in my code but it doesn't work, I still need to scroll the chart by myself.
> 
> I hope you can give me some idea about those two question.



https://github.com/ScottPlot/ScottPlot/assets/97512873/2b185511-99b9-41c0-aa60-2a4799a15edb

this video is the wrong about the question.

**Comment by back2childhood** [comment]
> > Hi @back2childhood ,
> > You can try init random generator only once at startup.
> > ```cs
> > private Random rnd = new Random();
> > 
> > ...
> > 
> > values1[i] = rnd.NextDouble();
> > values2[i] = rnd.NextDouble();
> > ```
> 
> amazing! that really works! Thank you!! But now I have a new questions:
> 
> * I cant zoom and move the chart, left click and scroll doesn't have any action. Do you have any idea?
> 
> I hope you can give me some idea about this question.


https://github.com/ScottPlot/ScottPlot/assets/97512873/1b0290d4-f716-4b72-b019-10ba8b096edd



this video is the wrong about the question.

**Comment by mYcheng-95** [comment]
Removing the following two lines of code should suffice:
```
formsPlot1.Plot.AxisAutoX();
formsPlot1.Plot.AxisAutoY();
```

**Comment by back2childhood** [comment]
> Removing the following two lines of code should suffice:
> 
> ```
> formsPlot1.Plot.AxisAutoX();
> formsPlot1.Plot.AxisAutoY();
> ```

that works, but it can't automatically move to fit. lol ..

**Comment by mYcheng-95** [comment]
> > Removing the following two lines of code should suffice:
> > ```
> > formsPlot1.Plot.AxisAutoX();
> > formsPlot1.Plot.AxisAutoY();
> > ```
> 
> that works, but it can't automatically move to fit. lol ..

换个思路，也许你可以使用鼠标移入移出事件来控制这两行代码是否有效

**Comment by mYcheng-95** [comment]
@back2childhood 
> > Removing the following two lines of code should suffice:
> > ```
> > formsPlot1.Plot.AxisAutoX();
> > formsPlot1.Plot.AxisAutoY();
> > ```
> 
> that works, but it can't automatically move to fit. lol ..
你可以换个思路，使用鼠标移入移出事件来控制是否执行这两行代码

**Comment by back2childhood** [comment]
> Hi @back2childhood ,
> 
> You can try init random generator only once at startup.
> 
> ```cs
> private Random rnd = new Random();
> 
> ...
> 
> values1[i] = rnd.NextDouble();
> values2[i] = rnd.NextDouble();
> ```


> @back2childhood
> 
> > > Removing the following two lines of code should suffice:
> > > ```
> > > formsPlot1.Plot.AxisAutoX();
> > > formsPlot1.Plot.AxisAutoY();
> > > ```
> > 
> > 
> > that works, but it can't automatically move to fit. lol ..
> > 你可以换个思路，使用鼠标移入移出事件来控制是否执行这两行代码

好滴哈，我再琢磨琢磨
