### ISSUE TITLE
Arrow: allow position modification

### ISSUE THREAD

**Issue by MyZQL** [ScottPlot/ScottPlot#2673]
I want to dynamically adjust the postion of an arrow, but its Base and Tip are read-only fields. 

How about making them editable?

```cs
var plotCtrl = new ScottPlot.Plot();
var myArrow = plotCtrl.Plot.AddArrow(xBase, yBase, xTip, yTip);
plotCtrl.Reflesh();
myArrow.Base.X = xBaseNew;
myArrow.Base.Y = yBaseNew;
myArrow.Tip.X = xTipNew;
myArrow.Tip.Y = yTipNew;
plotCtrl.Reflesh();
```

**Comment by swharden** [comment]
Thanks for the suggestion @MyZQL! I removed the readonly designator in #2709 and arrows positions will be mutable in the next release 🚀
