### ISSUE TITLE
Regarding the issue with Tick Labels

### ISSUE THREAD

**Issue by mYcheng-95** [ScottPlot/ScottPlot#2681]
**ScottPlot Version:** 4.1.64

**Operating System:** win10

**Application Type:** wpf

**Question:** Is there any solution to keep the Y-axis ticks always showing the top and bottom labels within the display range?
The tick labels are displayed as follows when not scaled:
![image](https://github.com/ScottPlot/ScottPlot/assets/30651076/6b0e5cc3-8e96-48ce-8974-6a67ab7f460d)
After some scaling, the current tick labels are not directly visible within the display range, as shown in the following image.
![image](https://github.com/ScottPlot/ScottPlot/assets/30651076/a641ef54-d327-42b8-939e-b3d8fc3a428b)
How can I ensure that the corresponding tick values are always displayed at the top and bottom of the axis?

**Comment by swharden** [comment]
Hi @mYcheng-95, this code example demonstrates one strategy for achieving this effect:

```cs
public partial class Form1 : Form
{
    double lastMin = 0;
    double lastMax = 0;

    public Form1()
    {
        InitializeComponent();

        formsPlot1.Plot.AddSignal(ScottPlot.Generate.Sin());
        formsPlot1.Plot.AddSignal(ScottPlot.Generate.Cos());

        formsPlot1.AxesChanged += (s, e) =>
        {
            var limits = formsPlot1.Plot.GetAxisLimits();

            // do this to prevent an infinite loop
            if (limits.YMin == lastMin && limits.YMax == lastMax)
                return;
            lastMin = limits.YMin;
            lastMax = limits.YMax;

            double[] positions = { limits.YMin, limits.YMax };
            string[] xLabels = { limits.YMin.ToString("0.00"), limits.YMax.ToString("0.00") };
            formsPlot1.Plot.YAxis.ManualTickPositions(positions, xLabels);
            formsPlot1.Refresh();
        };

        formsPlot1.Refresh();
    }
}
```

![edges](https://github.com/ScottPlot/ScottPlot/assets/4165489/e7e96405-8e02-4a84-85e7-bca362102eab)
