### ISSUE TITLE
Heatmap: nonlinear / user-defined colormaps

### ISSUE THREAD

**Issue by SMsiberg** [ScottPlot/ScottPlot#2689]
**ScottPlot Version:** 4.1.64

**Operating System:** Windows 10

**Application Type:** VB console app

Hello, I am going to plot data using a heatmap. The range of my data is from -32768 to 200, but the more significant data are in the interval [50; 100]. **I would like to know if it is possible to define the interval for each color in the colorbar.** 

For example, in my case I have this set of color:

```
{Color.Gray, Color.Blue, Color.Green, Color.Yellow, Color.Gold, Color.Red}
```

May I define that a data (lets call it "z") is shown in gray if it is minor than a limit value "a" (z < a => color = gray), while if a < z < b => color = blue, and so on? with these limits which are dinamic, for example:

```
{"-32768", "55", "70", "75", "80", "85", "95", "200"}
```

## Code

I can do this by pre-processing the data with a script if-else function, but it is not the most elegant solution...
Below an extract of the code (sorry for variables Italian names)
Thank you for your help!

```vb
Dim carta As Plot
carta = New ScottPlot.Plot(4000, 1000)
'Definisco la matrice dei dati
Dim dati(99, 399) As Double
Dim x, y As Int16
Dim z As Integer
'Limiti assi x, y, z
Dim xMax As Int16 = 400
Dim yMax As Int16 = 100

'[...] read data...

Dim colori(6) As Color
colori = {Color.Gray, Color.Blue, Color.Green, Color.Yellow, Color.Gold, Color.Red}
Dim tratti(7) As Double
tratti = {-32768, 55, 70, 75, 80, 85, 95, 200}
Dim etichette(7) As String
etichette = {"-32768", "55", "70", "75", "80", "85", "95", "200"}
Dim mappa As ScottPlot.Drawing.Colormap
mappa = New ScottPlot.Drawing.Colormap(colori)
Dim barra As ScottPlot.Plottable.Colorbar
barra = carta.AddColorbar(mappa)
barra.MaxValue = 200
barra.SetTicks(tratti, etichette, -32768, 200)
carta.XAxis.SetBoundary(0, xMax)
carta.YAxis.SetBoundary(0, yMax)  
carta.AddHeatmap(dati, mappa)
carta.SaveFig(percorsoHTML & ".png")
```

## Result
![Carta](https://github.com/ScottPlot/ScottPlot/assets/75787922/b76c6774-f034-414a-89b7-a22cd81ec498)

## Desired result
![Grafico 2D](https://github.com/ScottPlot/ScottPlot/assets/75787922/7edf1127-08ca-4eba-bf50-2866bf3685ff)

**Comment by swharden** [comment]
Hi @SMsiberg, 

I looked into this further and found that this isn't easy to achieve in ScottPlot 4 because colormaps are expected to be linear. Technically it's possible to make a custom colormap, but it seems like a complicated way to achieve this effect.

I'll add a note so that ScottPlot 5 has support for user-defined nonlinear colormaps 👍
