### ISSUE TITLE
Switch Row/Column of Radar Chart

### ISSUE THREAD

**Issue by vietanhbui** [ScottPlot/ScottPlot#2691]
**ScottPlot Version:** 4.1.52

**Operating System:** Windows

**Application Type:** WinForms

**Question:** Switch Row/Column of Radar Chart

How to Switch Row/Column of radar plot like excel:
![image](https://github.com/ScottPlot/ScottPlot/assets/43196820/69185b39-6358-4cbd-a72b-15f2719b9aac)
![image](https://github.com/ScottPlot/ScottPlot/assets/43196820/59dcffbb-e21b-464f-a916-d38e97f4d133)
![image](https://github.com/ScottPlot/ScottPlot/assets/43196820/cad098c7-1a6f-4e9f-87a9-46e09e24a7a9)

**Comment by swharden** [comment]
Hi @vietanhbui,

The excel chart in the second screenshot looks bad/confusing. Is that really the effect you wish to achieve? Regardless, here are how to create two similar charts:

## Original

```cs
double[,] values = {
    {7,8,8,6,5},
    {8,0,6,8,8},
};

string[] labels = { "a", "b", "c", "d", "e" };

ScottPlot.Plot plt = new(600, 400);
var radar = plt.AddRadar(values);
radar.CategoryLabels = labels;
plt.Legend(location: ScottPlot.Alignment.UpperRight);
plt.Frameless();
plt.Grid(enable: false);
plt.SaveFig("radar_quickstart.png");
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/3d0607a8-958a-4535-b3dd-c114c1fc30e7)


## Switched

```cs
double[,] values = {
    {7,8},
    {8,0},
    {8,6},
    {6,8},
    {5,8},
};

string[] labels = { "a", "b", "c", "d", "e" };

ScottPlot.Plot plt = new(600, 400);
var radar = plt.AddRadar(values);
radar.GroupLabels = labels;
plt.Legend(location: ScottPlot.Alignment.UpperRight);
plt.Frameless();
plt.Grid(enable: false);
plt.SaveFig("radar_quickstart.png");
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/1f342828-f9bc-4326-9e80-0abdcf7f887d)
