### ISSUE TITLE
AddCircle draws lineStyle incorrectly

### ISSUE THREAD

**Issue by Marc-Frank** [ScottPlot/ScottPlot#2692]
## Bug Report

**Issue:** Circles with lineStyle Dash are drawn solid and with lineStyle Dot are drawn only partially

**Reproducing:**
`formsPlot1.Plot.AddCircle(x: 1.0f,y: 1.0f,radius: 0.5f,color: Color.Gray,lineWidth: 1,lineStyle: ScottPlot.LineStyle.Dash);`
![image](https://github.com/ScottPlot/ScottPlot/assets/74321912/141359a4-a050-46c0-8f25-e2676a923b2d)

`formsPlot1.Plot.AddCircle(x: 1.0f,y: 1.0f,radius: 0.5f,color: Color.Gray,lineWidth: 1,lineStyle: ScottPlot.LineStyle.Dot);`
![image](https://github.com/ScottPlot/ScottPlot/assets/74321912/8b260f6f-c2a1-42fd-a43b-c4fc5a216a7d)

### System Details
* **ScottPlot Version:** 4.1.64
* **Operating System:** Windows 11
* **Application Type:** WinForms
* **.NET Version:** .NET 7.0

**Comment by bukkideme** [comment]
The bug i think originates from the pen.DashPattern = new float[] { 2.0F, 4.0F }; line. When we increase the lineWidth to 4 for example, the whole circle appears again. I think the scaling goes wrong with the pen width and the DashPattern values. Maybe we should somehow dynamically change the DashPattern float[] values using the actual lineWidth value, so the patterns would be more visible, and no rendering artifacts? But my knowledge is not enough in this area to figure out, what would be the best approach.
For sure, this works too fine: 

```
else if (lineStyle == LineStyle.Dot)
                pen.DashPattern = new float[] { 8F, 16F };
```


Original:


````
public static System.Drawing.Pen Pen(System.Drawing.Color color, double width = 1, LineStyle lineStyle = LineStyle.Solid, bool rounded = false)
        {
            var pen = new System.Drawing.Pen(color, (float)width);

            if (lineStyle == LineStyle.Solid || lineStyle == LineStyle.None)
            {
                /* WARNING: Do NOT apply a solid DashPattern!
                 * Setting DashPattern automatically sets a pen's DashStyle to custom.
                 * Custom DashStyles are slower and can cause diagonal rendering artifacts.
                 * Instead use the solid DashStyle.
                 * https://github.com/ScottPlot/ScottPlot/issues/327
                 * https://github.com/ScottPlot/ScottPlot/issues/401
                 */
                pen.DashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            }
            else if (lineStyle == LineStyle.Dash)
                pen.DashPattern = new float[] { 8.0F, 4.0F };
            else if (lineStyle == LineStyle.DashDot)
                pen.DashPattern = new float[] { 8.0F, 4.0F, 2.0F, 4.0F };
            else if (lineStyle == LineStyle.DashDotDot)
                pen.DashPattern = new float[] { 8.0F, 4.0F, 2.0F, 4.0F, 2.0F, 4.0F };
            else if (lineStyle == LineStyle.Dot)
                pen.DashPattern = new float[] { 2.0F, 4.0F };`
```

**Comment by swharden** [comment]
Good find @bukkideme! Probably the simplest way to fix this issue is to add support for custom dash patterns. Since there's already an open issue for that I'll close this issue and track progress over in #2690
