### ISSUE TITLE
SP5 How to add Markers and labels programatically?

### ISSUE THREAD

**Issue by Tilation** [ScottPlot/ScottPlot#2693]
**ScottPlot Version:** 5

**Operating System:** Linux

**Application Type:** console

**Question:** I need to darw a Scatter and then if values are inside a range, color them accordingly, in SP4 is very easy and I just add markers, but how can I do this on SP5?

The most important thing is conditional coloring of the markers and the labels.

Example of labels in SP4: 
![image](https://github.com/ScottPlot/ScottPlot/assets/48564654/595e1a63-a074-437a-8759-c1f9a641265c)

**Comment by Tilation** [comment]
Nevermind, I just added it to the codebase, I will be creating a pull request soon with goodies.
Leaving this open so I can link to the pr and track it.

**Comment by swharden** [comment]
Hi @Tilation, thanks for your work on this! I welcome code contributions for new plot types. The resources on this page may be helpful: https://scottplot.net/faq/custom-plot-type/

I'll close this issue for now, but you're welcome to reference it if you open a PR in the future 🚀 

Best,
Scott

**Comment by swharden** [comment]
... after thinking a little more about it, I really like this idea! Thinking out loud:

Consider naming the new plot type `MarkerList` 

It could have methods like `Add()`, `RemoveAt()`, and `Clear()`, 

The `Add()` method could have optional methods that control marker size, color, shape, etc.
