### ISSUE TITLE
Multiple Y axes

### ISSUE THREAD

**Issue by ChrisCatCP** [ScottPlot/ScottPlot#2695]
how can i create Multiple Yaxes  like this?
![image](https://github.com/ScottPlot/ScottPlot/assets/68489543/b1d652dc-3698-430f-9d38-0e512cf34e9c)

**Comment by bukkideme** [comment]
In such case, i usually create multiple FormsPlots, and then i sync their X axis together.
More info here: 
https://scottplot.net/faq/shared-axes/

**Comment by ChrisCatCP** [comment]
thanks, this is very helpful to me
