### ISSUE TITLE
SP5  How to bind WinUIPlot.Plot in WinUI3?

### ISSUE THREAD

**Issue by lnf83515** [ScottPlot/ScottPlot#2698]
* ScottPlot Version: 5.0.5 beta
* Operating System: Windows11 22621.1848
* Application Type: WinUI3

### ViewModel
```cs
public partial class MainViewModel : ObservableRecipient
{
    public ScottPlot.Plot MyPlot;
    public MainViewModel()
    {
        MyPlot = new();
    }
}
```

### View
```xaml
<Page
    x:Class="MultiChargerTest.Views.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:ScottPlot="using:ScottPlot.WinUI"
    mc:Ignorable="d">

    <Grid x:Name="ContentArea">
        <ScottPlot:WinUIPlot  />
    </Grid>
</Page>
```

### Question
I want to bind MyPlot from ViewModel to View.

So I tried:

```xaml
<ScottPlot:WinUIPlot  Plot="{x:bind ViewModel.MyPlot, Mode=OneWay}" /> 
```

but it failed because Plot property have only get method.

![image](https://github.com/ScottPlot/ScottPlot/assets/59425312/98828af7-2606-425b-b1ac-1f0beb2c9f65)

How can I bind the ScottPlot.WinUI.WinUIPlot.Plot property in WinUI?

**Comment by pjt33** [comment]
The short answer is that it's not really MVVM: you have to invert the usual way of thinking and use an OnLoad to insert the data into the plot. There may be a way of setting up some kind of adapter, but even then you would need to take into account that there won't be notifications propagated when the plot in your viewmodel changes.

**Comment by lnf83515** [comment]
@pjt33 Thankyou for your answer. I understand.
The problem is I need plot a lot of data (1M samples/s), many channels.
If I insert data every page moves, its too slow.
I'll try to find another way.

**Comment by swharden** [comment]
Thanks for your insight @pjt33! I think this answers @lnf83515's question, but feel free to re-open this issue if there is more to discuss 👍 

I'll focus on getting the WinUI docs on the website soon (#2717)
