### ISSUE TITLE
Colorbar: adjust the layout to make space for long tick labels

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2703]
currently large tick labels roll off the plot

```cs
var cb = formsPlot1.Plot.AddColorbar();
double[] fractions = { 0, .5, 1 };
string[] labels = { "AAAAAAAAAA", "BBBBBBBBBBBBBBB", "CCCCCCCCCCCCCCCCCCC" };
cb.SetTicks(fractions, labels);
formsPlot1.Render();
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/042bd9a8-4ba0-4f87-a520-98a8d29dee90)

**Comment by bukkideme** [comment]
I did not figure out yet how the automatic spacing of the plot X axis works. When we render the plot, and render Colorbar, the backend should recognize the X size required for the Colorbar (+ticks and label), so it should auto size to make space. No?

**Comment by swharden** [comment]
> it should auto size to make space

I agree, but the way ScottPlot4's axis system is makes it difficult for the size to adjust automatically. Rather than putting a lot of effort into restructuring how ScottPlot4's layout system works, I'll make a compromise here and give users a method they can call manually to resize the layout and ensure all tick labels are visible.

**Comment by swharden** [comment]
Because of a chicken and egg problem, automatic layout adjustment can only be called after at least one render, so the usage will look like this. It's also a little weird but you have to pass in the plot you wish you modify.

```cs
public Form1()
{
    InitializeComponent();

    var cb = formsPlot1.Plot.AddColorbar();
    double[] fractions = { 0, .5, 1 };
    string[] labels = {
        "Testing long message 1",
        "Testing long message 2",
        "Testing long message 3",
    };
    cb.SetTicks(fractions, labels);
    formsPlot1.Render();

    // automatic layout resizing must be called AFTER a render
    cb.ResizeLayout(formsPlot1.Plot);
    formsPlot1.Render();
}
```

Because:
* To measure the total width we have to know the tick labels
* To know the tick labels we have to generate them first
* To generate tick labels we need to know the height
* We only know the height after a render is requested

Altogether this should be considered as a helper function rather than a built-in feature... but it works!
