### ISSUE TITLE
SP4 ScatterPlotList: GetAxisLimits fails if data contains NaN (even if `NanBehavior` is not `Throw`)

### ISSUE THREAD

**Issue by oldteacup** [ScottPlot/ScottPlot#2707]
When the NanBehavior property of ~~ScatterPlot~~ ScatterPlotList is not Throw, GetAxisLimits cannot get AxisLimits normally

I think the problem is this place, it should be ` !double.IsNaN(value) `. I don't know if my change is correct?

![image](https://github.com/ScottPlot/ScottPlot/assets/62321246/c77f2d50-7071-41f6-8834-22a4815cf7f9)

**Comment by swharden** [comment]
Thanks for reporting this @oldteacup! I also appreciate you identifying the bug and offering the solution. I made this fix in #2729 and it will be in the next release! 🚀
