### ISSUE TITLE
set alignment of toolTip

### ISSUE THREAD

**Issue by LXX1029** [ScottPlot/ScottPlot#2712]
Hi,
 I'd added two vertical line in my plot , they are dragged by left mouse button.The first line can't dragged behind the second line,so...sometime,the tooltip of the two lines will overlap.for example:
![20230703173420](https://github.com/ScottPlot/ScottPlot/assets/51777355/54d435dd-24fe-4ff2-8240-07f8a93fe29c)
I want to keep tooltip is always left of the first line and other tooltip is always right of the second line.I looked at how the text was set up, but decided it didn't look as good as the tooltip. Looking forward to reply

**Comment by bukkideme** [comment]
The orientation of the tooltip cannot be changed. In such cases I just simply bring the active or last operated element's tooltip to the front, so the other will not overlap it.

You can put a simple method call inside your event handlers, subscribed for your vertical lines' drag or other similar event. For example you can put this inside the event:

`formsPlot1.Plot.MoveLast(tooltip);`

**Comment by LXX1029** [comment]
This is undeniably a great set of chart controls, and I look forward to adding this property setting to the new version. I wish you all the best. Thank you.
