### ISSUE TITLE
SP5: Remove the negative area from graph in the Y-Axis, disabling decimal ticks

### ISSUE THREAD

**Issue by ahmad-qamar** [ScottPlot/ScottPlot#2713]
**ScottPlot Version:** 5.0.5-beta
**Question:** I was working on SP4 for a Scatter Graph before realizing it's not useable on Linux, and therefore migrated to SP5, however I haven't been able to replicate the functionality of a few functions as of yet in the newer version. 

The first function that I require from SP4 is to remove the negative area of the graph which I was doing with `Plot.YAxis.SetBoundary(-.1)` beforehand. I have tried to do this a few times with `Plot.LeftAxis.Range.Set(-.1, 1000)`, setting Min/Max values but nothing have seemed to work as it did in SP4.

Second issue is to remove the decimal range/ticks on the graph, for which I've tried implementing `ScottPlot.TickGenerators.NumericFixedInterval`, but then the automatic spacing isn't in place and wouldn't work for larger values. I simply had to use `plt.YAxis.MinimumTickSpacing(1)` with SP4 on the other hand.

It'd be really appreciated if someone can guide me on how this can be done over in SP5, thanks!

**Comment by swharden** [comment]
Hi @ahmad-qamar, 

ScottPlot 5 is not released yet and its API is continuing to change as I work on it, so it's possible these features are not available yet or that if I tell you how to do it today it may no longer function as expected tomorrow.

Backing up, **ScottPlot 4 works on Linux if you target .NET 6** and if that's possible for your app it is probably the best solution.

https://scottplot.net/faq/dependencies/

I'll close this issue for now, but after ScottPlot 5 is out of preview (and the cookbook and demo apps are complete) if you still can't figure out how to achieve these behaviors let me know and we can open this issue back up 👍
