### ISSUE TITLE
SP4 WPF: Strong randomized data slows windows resize down

### ISSUE THREAD

**Issue by mikeKuester** [ScottPlot/ScottPlot#2716]
## Bug Report

**Issue:**  Strong randomized data slows windows resize down.
I need a scatter or signalXY plot with a lot of data points (> 3,000,000). Drawing the chart is ok, but if the windows is resized (e.g. maximized), it takes very long, depending of the displayed data.

**Reproducing:** 
- Create a new WPF App
- Add WpfPlot Control to XAML
- Add code to `Loaded` event
- Resize the window by clicking the maximize button several times
- Increase the `randFactor` and resize again

The computer needs ~ 5s for a resize with a `randFactor` of 10, but ~ 20s with a `randFactor` of 1000.

Update: I added `Benchmark(true)` and got this measures for a `randFactor` = 1000:
- initial render: 1,99 s
- maximize: 30,1 s
- back to normal size: 9,24 s

```xaml
<WpfPlot HorizontalAlignment="Stretch" VerticalAlignment="Stretch"
         x:Name="ResultChart" Loaded="ResultChart_Loaded"/>
```

```cs
private void ResultChart_Loaded(object sender, RoutedEventArgs e)
{
    // create some random data
    int numberOfWells = 1536;
    int numberOfDatapoints = 3000;
    double randFactor = 10.0;  // increase this number for example to 1000.0
    for (int well = 0; well < numberOfWells; well++)
    {
        double[] xs = new double[numberOfDatapoints];
        double[] ys = new double[numberOfDatapoints];
        for (int index = 0; index < numberOfDatapoints; index++)
        {
            xs[index] = index;
            ys[index] = Random.Shared.NextDouble() * randFactor + index + index;
        }
        ResultChart.Plot.AddScatterLines(xs, ys, lineStyle: ScottPlot.LineStyle.Solid);
    }

    const bool lowQuality = true;
    ResultChart.Refresh(lowQuality);
}
```

### System Details
* **ScottPlot Version:** 4.1.64?
* **Operating System:** Windows 10 21H2
* **Application Type:** WPF
* **.NET Version:** .NET 7

**Comment by swharden** [comment]
Hi @mikeKuester, thanks for reporting this!

Unfortunately the poor performance is a limitation of System.Drawing which ScottPlot 4 uses to draw lines. As the data becomes more random the lines become longer, cover more pixels, and take longer to render.

ScottPlot 5 offers great performance improvements by dropping System.Drawing in favor of SkiaSharp which uses OpenGL for much more performant charting. It's still in preview, but public so you can give it a try. I'm ramping-up development on it now and hope to have it reach feature parity with ScottPlot 4 soon.

Hope it helps!
Scott

**Comment by mikeKuester** [comment]
Hi @swharden ,
thanks for your fast response (and for ScottPlot of course).

I tried ScottPlot 5.0.5-beta and it's much faster:
- initial render: 0,5 s
- maximize: ~2 s
- back to normal size: ~2 s

This looks very promising for the future :D  

It takes me a bit of time to find the right methods, so if anyone look into this issue:

```xaml
<Window x:Class="ScottPlot5.MainWindow"
    ...     
    xmlns:scottPlot="clr-namespace:ScottPlot.WPF;assembly=ScottPlot.WPF"
    ... >
    <Grid>
        <scottPlot:WpfPlot HorizontalAlignment="Stretch" VerticalAlignment="Stretch"
            x:Name="ResultChart" Loaded="ResultChart_Loaded" />
    </Grid>
</Window>
```

```csharp
        private void ResultChart_Loaded(object sender, RoutedEventArgs e)
        {
            ResultChart.Plot.Benchmark.IsVisible = true;
            ResultChart.Plot.AutoScale();

            // create some random data
            int numberOfWells = 1536;
            int numberOfDatapoints = 3000;
            double randFactor = 1000.0;  // increase this number for example to 1000.0
            for (int well = 0; well < numberOfWells; well++)
            {
                double[] xs = new double[numberOfDatapoints];
                double[] ys = new double[numberOfDatapoints];
                for (int index = 0; index < numberOfDatapoints; index++)
                {
                    xs[index] = index;
                    ys[index] = Random.Shared.NextDouble() * randFactor + index + index;
                }
                var scatter = ResultChart.Plot.Add.Scatter(xs, ys);
                scatter.MarkerStyle.IsVisible = false;
            }

            ResultChart.Refresh();
        }
```
