### ISSUE TITLE
SP5: Need WinUI Quickstart

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2717]
I want to help @lnf83515 resolve #2698 but there isn't a great resource in place to help new WinUI users get started and I don't know much about WinUI myself.

If someone more familiar with WinUI gets to this before I do, it would be fanastic to have a WinUI Quickstart for ScottPlot 5 on the website!

I created a page to get it started, but it's currently empty:
* https://scottplot.net/quickstart/winui/
* https://github.com/scottplot/scottplot.net/blob/main/content/quickstart/winui/index.md

The WinUI package is on NuGet and everything so this may be pretty easy:
* https://www.nuget.org/packages/ScottPlot.WinUI/5.0.5-beta

Additional Resources:

* https://learn.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app

**Comment by lnf83515** [comment]
Hi @swharden , Can you update the WinUI Quickstart?
It's very similar to WPF

Step1: Make new WinUI project.
![image](https://github.com/ScottPlot/ScottPlot/assets/59425312/800d9ef4-27ca-426f-98a5-c85109474006)

Step2: Open nuget manager and install the ScottPlot.WinUI.  (need to check 'Include prerelease')
![image](https://github.com/ScottPlot/ScottPlot/assets/59425312/37bca5e4-665a-4e13-b70c-509a8194536d)

Step3:  Add this to the root element of XAML file:
`xmlns:ScottPlot="using:ScottPlot.WinUI"`

Step4:  Add WinUIPlot to layout:
`<ScottPlot:WinUIPlot x:Name="WinUIPlot1"/>`

Step5: Plot some data in XAML.CS file
```
            double[] sin = Generate.Sin(51);
            double[] cos = Generate.Cos(51);
            WinUIPlot1.Plot.Add.Signal(sin);
            WinUIPlot1.Plot.Add.Signal(cos);

            WinUIPlot1.Refresh();
```

![image](https://github.com/ScottPlot/ScottPlot/assets/59425312/34896da8-fa39-4f6c-904b-435966f762fa)
MainWindow.xaml

![image](https://github.com/ScottPlot/ScottPlot/assets/59425312/cb5cc2d7-2af7-4099-8183-36a1b2098c0a)
MainWindow.xaml.cs

![image](https://github.com/ScottPlot/ScottPlot/assets/59425312/f27d3f7e-3e8e-4302-b5ea-6f73d1dc73aa)
result

**Comment by lnf83515** [comment]
Additionaly, There is two problems using ScottPlot.WinUI on my system.

- On project property, if Target OS version is 10.0.20348.0 or lower then the project build fails.
Its works on 10.0.22200.0 or higher.
![image](https://github.com/ScottPlot/ScottPlot/assets/59425312/6ece9ef3-b9e4-408d-b4fd-a4acdb219b23)

- ScottPlot works on Gird layout, but its not works on stackpanel
![image](https://github.com/ScottPlot/ScottPlot/assets/59425312/01daa678-c718-4029-a1b4-f80fb98b02eb)
![image](https://github.com/ScottPlot/ScottPlot/assets/59425312/f00c2bf3-e208-4829-8b3f-91dc8b650d83)

Im not sure if this is a bug or problem with my system.

My system information is below.
Windows11 22H2 OS Build 22621.1848
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.6.4
WindowsAppSdk 1.3.230602002
ScottPlot.WinUI 5.0.5-beta
.net v6.0.314 and .net v7.0.305

**Comment by KroMignon** [comment]
@lnf83515 
> ScottPlot works on Gird layout, but its not works on stackpanel

This is not a ScottPlot bug, this is bug in your XAML code.
A Grid will try to take as much space as it can, but the StackPanel will only use the required space according to the items it holds.
To overcome this, you can force StackPanel to take all space:
```
<StackPanel Margin="0,0,0,0" VerticalAlignment="Stretch" HorizontalAlignment="Stretch" Width="Auto" Height="Auto">
    <ScottPlot:WinUIPlot />
</StackPanel>
```

Or force ScottPlot dimensions:
```
<StackPanel>
    <ScottPlot:WinUIPlot MinWidth="640" MinHeight="480"/>
</StackPanel>
```

**Comment by lnf83515** [comment]
@KroMignon 

Thanks for your comment.
I already tried strech, but it didn't work. (I think it works but not shown)
![image](https://github.com/ScottPlot/ScottPlot/assets/59425312/f0f8e16d-7079-472d-8867-6b3bca44621e)

Force width and height is working.
But other controls (like button) are working without setting width and height.
![image](https://github.com/ScottPlot/ScottPlot/assets/59425312/fb5cac86-1554-4799-835f-731d1c209b3d)

I'll test more diffrent cases.

**Comment by swharden** [comment]
Is the ScottPlot.WinUI package description good?

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/ce5552ee-6d5f-4dce-9849-c77f4540402d)

https://github.com/ScottPlot/ScottPlot/blob/0376f523dc1082a4af5a7f3273037caeefebd758/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WinUI/ScottPlot.WinUI.csproj#L16

I always find the relationship between WinUI and Uno confusing. Should this say something better, or is it good?

**Comment by swharden** [comment]
Thanks everyone! I updated the quickstart page. Take a look and let me know if you have any suggestions for improvements! (There's an edit button at the bottom of the page)

https://scottplot.net/quickstart/winui/

resolved by https://github.com/ScottPlot/ScottPlot.NET/commit/442375b123c1f0e3d7a9db491251276a9111e0d5
