### ISSUE TITLE
SP5: WPFplot not working after WindowClosingEvent canceled (#2700)

### ISSUE THREAD

**Issue by minjjKang** [ScottPlot/ScottPlot#2718]
Its same issue - #2700 

## Bug Report

**Issue:** WPFplot dispose after WindowClosingEvent canceled

**Reproducing:** 

Hi.

What I meant by "not working" is that it is impossible to refresh the plot including interaction.
sorry for i didn't write details.

I wrote the same code as you shared and ran two applications, Scottplot4 and Scottplot5.
```C#
// Scottplot 5
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        plot.Plot.Add.Signal(ScottPlot.Generate.Sin());
        plot.Plot.Add.Signal(ScottPlot.Generate.Cos());

        this.Closing += MainWindow_ClosingEvent;
    }

    private void MainWindow_ClosingEvent(object? sender, CancelEventArgs e)
    {
        e.Cancel = true;
    }
}
```

```C#
// Scottplot 4
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        double[] dataX = new double[] { 1, 2, 3, 4, 5 };
        double[] dataY = new double[] { 1, 4, 9, 16, 25 };

        plot.Plot.AddScatter(dataX, dataY);
        plot.Refresh();

        this.Closing += MainWindow_ClosingEvent;
    }
    private void MainWindow_ClosingEvent(object? sender, CancelEventArgs e)
    {
        e.Cancel = true;
    }
}
```

and, There is a video of the problem below:
    https://youtube.com/shorts/GhnFCOVjh8c?feature=share

Interaction and refresh are works well.
after, Press X to proceed with window closing and cancel the event,
It works fine on Scottplot4, Not in Scottplot5.

### System Details
* **ScottPlot Version:** 5.0.3-beta
* **Operating System:** Windows 11
* **Application Type:** WPF
* **.NET Version:** .NET5

**Comment by swharden** [comment]
Thanks for following-up @minjjKang! I'm going to copy this information into https://github.com/ScottPlot/ScottPlot/issues/2700 to keep this discussion all in one place, and I'll respond over there 👍
