### ISSUE TITLE
X Ticks TimeStamp offset

### ISSUE THREAD

**Issue by GuiWolff** [ScottPlot/ScottPlot#2719]
How to add time only to the X ticks?

Starting from 00:00, receive an offset and become 00:30.

**Comment by swharden** [comment]
Hi @GuiWolff,

There isn't very much information in your question so it is difficult to give you a good answer. Can you share a screenshot of what you have now and paste some code that lets us recreate your issue? I'll close this issue for now, but feel free to re-open it if you share additional information.

A custom tick formatter may solve your problem:
https://scottplot.net/cookbook/4.1/category/advanced-axis-features/#custom-tick-formatter
