### ISSUE TITLE
Oscilloscope: new plot type(s) for streaming data

### ISSUE THREAD

**Issue by heartacker** [ScottPlot/ScottPlot#2721]
I think we need some DataStreamer-like plotting types that mimic oscilloscope displays

_Originally posted by @heartacker in https://github.com/ScottPlot/ScottPlot/issues/2641#issuecomment-1621770223_

## 1. WipeFade

old data will fade in one cycle

![image](https://github.com/ScottPlot/ScottPlot/assets/1876302/f952008d-a106-4a34-87fc-f42df4c37cec)

## 2. Fade

old data fades after a fixed-time

![image](https://github.com/ScottPlot/ScottPlot/assets/1876302/0b8403fe-a5c6-41b4-8047-505061379f91)

## 3. EyeHeat

one color hot/cold or colorful depth

![image](https://github.com/ScottPlot/ScottPlot/assets/1876302/2f576960-b93b-415b-b872-af78749ed940)

## 4. Histogram

![image](https://github.com/ScottPlot/ScottPlot/assets/1876302/3ebce0a7-cfec-407e-ad4f-8efcca94c123)

**Comment by Niravk1997** [comment]
All of this can be implemented externally. 1, 2 and 3 can be implemented by having multiple plots with same color but with varying levels of transparency (Alpha value).

Four is interesting. Oscilloscope usually call this feature intensity graded or color graded display. Some manufacturers implement this using a heatmap. See links below.
[Anritsu Realtime Spectrum Analyzer PDF, page 17](https://dl.cdn-anritsu.com/en-us/test-measurement/files/Technical-Notes/White-Paper/11410-01138B.pdf)
[Python Intensity Graded FFT Plots](https://teaandtechtime.com/python-intensity-graded-fft-plots/)
[DSO/DPO :  Gradient - displaying  the  Data](http://www.hit.bme.hu/~papay/edu/DSOdisp/gradient.htm)

Scottplot 4's heatmap performance is lacking, hopefully version 5 will be an improvement. Below is what I can achieve.![Animation](https://github.com/ScottPlot/ScottPlot/assets/52579388/f0ec094a-05c0-4680-9ecc-516a52674fda)

**Comment by swharden** [comment]
Wow! @Niravk1997 thanks for sharing your screenshots. It's amazing to see what people build using ScottPlot!

> All of this can be implemented externally

It's good news that these are achievable. If a custom plot type would help make it easier for users to achieve this type of functionality, I'd be happy to include that in ScottPlot.

Alternatively, code samples and documentation that clarify how others can achieve these effects may be useful to add as discussions on GitHub or pages on the website.

I'll close this issue for now, but I welcome questions, comments or pull requests if others continue working on these new plot types.

**Comment by mehaifeng** [comment]
@Niravk1997 Hello, I'd like to ask you, in the last image you posted, is the oscilloscope function using the unmodified ScottPlot control? Is this an open-source project?

**Comment by Niravk1997** [comment]
I just made the project public, it needs Visual Syudio 2019 and a visa software (R&S®VISA or NI-Visa) to compile. The project is missing features and has bugs. It uses unmodified ScottPlot 4.

https://github.com/Niravk1997/NX-StarWave
https://github.com/Niravk1997/NX-StarWave/tree/main/src/.Net_Framework_4.7.2/Graphs/YT_Graphs/YT
