### ISSUE TITLE
Is ScottPlot.Avalonia only support windows platform?

### ISSUE THREAD

**Issue by mzy666888** [ScottPlot/ScottPlot#2734]
is this libs only windows platforms on Avalonia?

**Comment by swharden** [comment]
Hi @mzy666888, 

ScottPlot (including the Avalonia control) supports Linux However, Microsoft's System.Drawing.Common no longer supports Linux. The solution is to **target your app for .NET 6**

Linux users may also need to do a few extra steps: https://scottplot.net/faq/dependencies/#linux--macos

**Comment by mzy666888** [comment]
I use scottplot for android on windows platform. add the libs error.

**Comment by swharden** [comment]
@mzy666888 can you share the content of your project's csproj file?

**Comment by mzy666888** [comment]
![image](https://github.com/ScottPlot/ScottPlot/assets/2587129/44710bde-c5d8-4385-8a52-4bbe17d8dd7c)

five csproj, the `AvaloniaAllApp.Android` for android, the `AvaloniaAllApp.Desktop` for windows, etc.
the `AvaloniaAllApp` for other four project use.
```
<ItemGroup>
    <ProjectReference Include="..\AvaloniaAllApp\AvaloniaAllApp.csproj" />
  </ItemGroup>
```

add `scottplot` `Scottplot.Avalonia` on  `AvaloniaAllApp`
![image](https://github.com/ScottPlot/ScottPlot/assets/2587129/be43be4c-bb76-4f0a-842a-6ecb74d36d3f)

```
xmlns:ScottPlot="clr-namespace:ScottPlot.Avalonia;assembly=ScottPlot.Avalonia
```

build error
![image](https://github.com/ScottPlot/ScottPlot/assets/2587129/cb763f5f-a2d6-4057-aa07-e32929a9bcd5)

if unload the project `AvaloniaAllApp.Browser`, build right.
