### ISSUE TITLE
SP4 Heatmap: XML docs error

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2738]
/// <summary>
        /// **Width** of each cell composing the heatmap
        /// </summary>
        public double CellHeight { get; set; } = 1;

**Comment by swharden** [comment]
Thanks for reporting this @bukkideme!

Here's the location of that typo:

https://github.com/ScottPlot/ScottPlot/blob/39ba44370e7194e2c6acd56e98cf580a58ffed01/src/ScottPlot4/ScottPlot/Plottable/Heatmap.cs#L58-L61

**Comment by swharden** [comment]
resolved in #2827
