### ISSUE TITLE
SP5: Improve support for Chinese characters

### ISSUE THREAD

**Issue by heartacker** [ScottPlot/ScottPlot#2746]
wpf app
ScottPlot Version="5.0.6-beta"
![image](https://github.com/ScottPlot/ScottPlot/assets/1876302/10031489-5f57-46d6-9668-e5f3d0b0b827)

**Comment by heartacker** [comment]
> Hi @heartacker, thanks for reporting this! It's the first time I've seen it on ScottPlot 5
> 
> Are you using MacOS or Linux by chance? Those operating systems may have to install a few extra packages to get fonts to work correctly: 
> * https://scottplot.net/faq/linux-font/
> * https://scottplot.net/faq/dependencies/
> 
> Related:
> * #1649
> * #1729

window 11

**Comment by swharden** [comment]
> windows 11

I guess this is good news -- it means I can also work to fix this on my Windows 11 system 👍

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/62abcc47-cd48-4f61-98ab-7133e2b88d46)

What font is this? Can you copy/paste that line of code here so I can try to recreate the bug with your same font/text? I'm now guessing it's a font/internationalization issue.

**Comment by swharden** [comment]
Note to self, "CJK" refers to a collection of Chinese, Japanese and Korean characters

https://en.wikipedia.org/wiki/CJK_characters

**Comment by heartacker** [comment]
This is Chinese in fact in my pic :D

**Comment by swharden** [comment]
> This is Chinese in fact

lol, oops! Google told me it was Japanese 😝

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/59911956-5942-422c-8b82-3257127f65d3)

Thanks for the correction!

Is this text closer?

```
频率信号削减1/32
```

If you can share that line of your source code, I can copy/paste it exactly to confirm I get it working

**Comment by swharden** [comment]
this looks even worse on my system!

```cs
ScottPlot.Plot plot = new();
plot.Add.Signal(ScottPlot.Generate.Sin());
plot.Add.Signal(ScottPlot.Generate.Cos());
plot.TopAxis.Label.Text = "频率信号削减1/32";
plot.SavePng("test.png", 400, 300);
```

![test](https://github.com/ScottPlot/ScottPlot/assets/4165489/c62c2528-b3d2-4da8-923f-f4b80165ddfa)

**Comment by swharden** [comment]
It appears to be font dependent...

@heartacker can you use code like this and give it a font you know supports Chinese characters? Does it still produce an error?

```cs
plot.TopAxis.Label.Font.Name = "Consolas";
plot.TopAxis.Label.Text = "频率信号削减1/32";
```

![test](https://github.com/ScottPlot/ScottPlot/assets/4165489/612bbc61-6a79-492f-bb34-1d45a552eb11)

Related:
* https://github.com/mono/SkiaSharp/issues/401
* https://stackoverflow.com/questions/48053615/passing-the-current-platform-font-into-sktypeface/48141139#48141139

**Comment by swharden** [comment]
This seems to work. I should figure out how to make this easier to figure out 😅 

```
formsPlot1.Plot.TopAxis.Label.Font.Name = SKFontManager.Default.MatchCharacter('频').FamilyName;
```

![test](https://github.com/ScottPlot/ScottPlot/assets/4165489/6e708ef1-1ed5-46b3-9f3c-6478c16bf062)

**Comment by bclehmann** [comment]
> I'll use a strategy like this to determine a better default font for intentional users

This could be difficult due to Han Unification, most CJK characters are unified in unicode (i.e. share one codepoint) across languages even when they look different. A little bit like considering the Latin 'L' to be the same as the Greek 'λ' or Cyrillic 'Л'. Historically and linguistically they're related and they make the same sound, but they aren't the same letter. It was a (failed) attempt by westerners to hold onto their naïve dream of a 16-bit character set without surrogate pairs. 

Effectively this means you ought to use a font that matches the language, or you have to use a font that has multiple variants so that the program can do locale trickery to figure out which character it ought to use. I don't know if we get that locale trickery for free with Skia or not. Even in this case this means mixing Chinese and Japanese will result in one of them being incorrect unless they use different fonts.

My impression as someone that doesn't speak any of the relevant languages is that text is still readable (though still wrong) when using a font designed for the wrong language, since characters with larger differences aren't supposed to be unified. Though it has happened several times where Unicode has had to de-unify characters because they were too dissimilar (or sometimes completely unrelated).

**Comment by swharden** [comment]
After looking into it a bit in the Live Coding room in the Discord (#1966) @bclehmann and I found that the default fonts are selected from this hard-coded list. We can improve the way the default fonts are chosen, and also allow users to modify this list to favor particular fonts.

https://github.com/ScottPlot/ScottPlot/blob/e9dbc1dc29f069a221d0501a19f525bb7915a065/src/ScottPlot5/ScottPlot5/FontService.cs#L25

**Comment by swharden** [comment]
I'm merging #2753 which will let users do this to reset the default font to one that best support any given character:

```cs
ScottPlot.FontService.SetDefaultFont('频');
```

Note that an overload allows users to set the font using a font name too:

```cs
ScottPlot.FontService.SetDefaultFont("Times New Roman");
```

Thanks for raising this issue @heartacker!

**Comment by heartacker** [comment]
thanks 
and I think Scott.Plot default font should be the System/APP By default
for example 
Soctt plot should respect the wpf app default font by default
```
<Window FontFamily="MS Yahei">

<sp5:WpfPlot name="WpfPlot ">
</Window>
```

except setting by this or code
```
<Window FontFamily="MS Yahei">

<sp5:WpfPlot FontFamily="Monospace" name="WpfPlot">
</Window>
```

**Comment by heartacker** [comment]
I still believe that we should render correctly for all of user, not be beautiful firstly

**Comment by swharden** [comment]
> I still believe that we should render correctly for all of user, not be beautiful firstly

Hi @heartacker, thank you for your persistence! I thought of a way I can do this better: I'll default to "Open Sans" only if the system default is "Segoe UI". If that is not the system default font (like on your computer), the default will be the system default font 👍

**Comment by heartacker** [comment]
waiting for  an  new release to test it

**Comment by swharden** [comment]
> waiting for an new release to test it

Hi @heartacker 

I'm not sure when I'm going to publish the next release on NuGet yet, but you can always use the latest version of ScottPlot in your apps if you build it from the source code in this repository https://scottplot.net/faq/environment/

**Comment by heartacker** [comment]
@swharden I TEST IN MY WINDOWS1-CHINESE
the defult is Segoe UI,

![image](https://github.com/ScottPlot/ScottPlot/assets/1876302/4611981d-d859-4567-9f4e-7f83d82e7c39)


and the default font is also NG
![image](https://github.com/ScottPlot/ScottPlot/assets/1876302/ac211e15-f923-40ea-99db-e5ac3d2e0afa)

maybe we need to find the root cause

**Comment by swharden** [comment]
Thanks @heartacker for your PR #2769

I learned more about this issue! The method described above works for console apps, but not for interactive controls because the interactive control font selection happens as the program starts-up (before the user can give it a custom font)

Here's some test code which demonstrates the best fonts my system chose for each of the following langauges:

```cs
string chinese = "测试";
string japanese = "試験";
string korean = "테스트";
string msg = $"Chinese: {chinese} " +
    $"Japanese: {japanese} " +
    $"Korean: {korean}";

Plot plt1 = new();
plt1.Title($"[{Fonts.Default}] {msg}");
plt1.SaveTestImage(600, 400, "default");

Fonts.Default = Fonts.Detect(chinese) ?? Fonts.System;
Plot plt2 = new();
plt2.Title($"[{Fonts.Default}] {msg}");
plt2.SaveTestImage(600, 400, "chinese");

Fonts.Default = Fonts.Detect(japanese) ?? Fonts.System;
Plot plt3 = new();
plt3.Title($"[{Fonts.Default}] {msg}");
plt3.SaveTestImage(600, 400, "japanese");

Fonts.Default = Fonts.Detect(korean) ?? Fonts.System;
Plot plt4 = new();
plt4.Title($"[{Fonts.Default}] {msg}");
plt4.SaveTestImage(600, 400, "korean");
```

### English
![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/d4dc9184-bec7-4d3f-bad3-131eff70a7c3)


### Chinese
![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/ea00b606-9368-47f6-be47-3cda86881547)

### Japanese
![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/bcbe3a71-298a-4365-94b5-187311023ed6)

### Korean
![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/a5124469-f175-465c-bbe1-e842298e06be)

**Comment by swharden** [comment]
Thanks again for your persistence on this @heartacker!

I'm adding a method that can be called to update the plot more easily, and I'm confirming it works in WPF too 🚀

![lang](https://github.com/ScottPlot/ScottPlot/assets/4165489/06d13093-fc08-4cda-86df-349e418d3452)

```cs
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();

        WpfPlot.Plot.Add.Signal(Generate.Sin());
        WpfPlot.Plot.Add.Signal(Generate.Cos());

        WpfPlot.Refresh();
    }

    private void SetLabelText(string text)
    {
        WpfPlot.Plot.Style.SetFontFromText(text);
        WpfPlot.Plot.Title(text, 24);
        WpfPlot.Plot.YLabel(text, 24);
        WpfPlot.Plot.XLabel(text, 24);
        WpfPlot.Refresh();
    }

    private void English_Click(object sender, RoutedEventArgs e) => SetLabelText("Test");

    private void Chinese_Click(object sender, RoutedEventArgs e) => SetLabelText("测试");

    private void Japanese_Click(object sender, RoutedEventArgs e) => SetLabelText("試験");

    private void Korean_Click(object sender, RoutedEventArgs e) => SetLabelText("테스트");
}
```

```xaml
<Window x:Class="Sandbox.WPF.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:ScottPlot="clr-namespace:ScottPlot.WPF;assembly=ScottPlot.WPF"
        xmlns:local="clr-namespace:Sandbox.WPF"
        mc:Ignorable="d"
        WindowStartupLocation="CenterScreen"
        Title="ScottPlot 5 - WPF Sandbox" Height="300" Width="500">
    <DockPanel>
        <StackPanel DockPanel.Dock="Bottom">
            <StackPanel Orientation="Horizontal">
                <Button Content="English" Click="English_Click" Margin="5" Padding="5" />
                <Button Content="Chinese" Click="Chinese_Click" Margin="5" Padding="5" />
                <Button Content="Japanese" Click="Japanese_Click" Margin="5" Padding="5" />
                <Button Content="Korean" Click="Korean_Click" Margin="5" Padding="5" />
            </StackPanel>
        </StackPanel>
        <ScottPlot:WpfPlot x:Name="WpfPlot" />
    </DockPanel>
</Window>

```

**Comment by heartacker** [comment]
avalonia  has the same issue but it  is to fix in the framework in AVALONIA 11


https://github.com/AvaloniaUI/Avalonia/issues/7037#issuecomment-1366554499

https://github.com/AvaloniaUI/Avalonia/issues/8070

**Comment by woaidianqian** [comment]
ScottPlot.Plot myPlot = new();

myPlot.Font.Set(SKFontManager.Default.MatchCharacter('汉').FamilyName);
it works！
