### ISSUE TITLE
SP5: add support for display scaling

### ISSUE THREAD

**Issue by heartacker** [ScottPlot/ScottPlot#2747]
## Bug Report

**Issue:** (Bug description goes here)
plot is very small in high DPI screen with Windows 150% 

SP4 is ok

![image](https://github.com/ScottPlot/ScottPlot/assets/1876302/13a85f84-89b3-4805-864e-4b3497a18334)

### System Details
      <PackageReference Include="ScottPlot.WPF" Version="5.0.6-beta" />

设备名称	ROG-heartacker
处理器	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
机带 RAM	24.0 GB (23.7 GB 可用)
设备 ID	A98F8F10-1FED-4DAF-8210-976C498347E4
产品 ID	00330-80128-19810-AA801
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

版本	Windows 11 pro Insider Preview
版本	22H2
安装日期	‎2023/‎3/‎9
操作系统版本	25314.1000
体验	Windows Feature Experience Pack 1000.25314.1000.0

**Comment by swharden** [comment]
Hi @heartacker, I hope the information on this page helps you achieve a solution! 

https://scottplot.net/faq/dpi-scaling/

We can re-open this issue if there is more to discuss

**Comment by swharden** [comment]
Oh, I just realized this issue is about ScottPlot 5 (not 4) ... yes, it's still an issue 😅 

I'll leave this issue open until it is resolved 👍

**Comment by swharden** [comment]
Related, this module served a purpose at one point in time but may no longer be required

https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot/Control/DisplayScale.cs

**Comment by swharden** [comment]
This is how ScottPlot4 determines DPI scaling

https://github.com/ScottPlot/ScottPlot/blob/23ef14015d8ca5abdd9dea7b8413062aa309dcd4/src/ScottPlot4/ScottPlot/Drawing/GDI.cs#L22-L32

This measurement makes its way through to `DpiStretchRatio` in the ScottPlot4 controls

https://github.com/ScottPlot/ScottPlot/blob/23ef14015d8ca5abdd9dea7b8413062aa309dcd4/src/ScottPlot4/ScottPlot.WPF/WpfPlot.cs#L148-L149

There should be a ScottPlot5/SkiaSharp equivalent

**Comment by KroMignon** [comment]
> There should be a ScottPlot5/SkiaSharp equivalent

I am not really aware about SkiaSharp, but as far as I can see, then property [`SKCanvasView.IgnorePixelScaling`](https://learn.microsoft.com/en-us/dotnet/api/skiasharp.views.ios.skcanvasview.ignorepixelscaling) seems to be the _best_ way to handle DPI with SkiaSharp.

**Comment by heartacker** [comment]
> > There should be a ScottPlot5/SkiaSharp equivalent
> 
> I am not really aware about SkiaSharp, but as far as I can see, then property [`SKCanvasView.IgnorePixelScaling`](https://learn.microsoft.com/en-us/dotnet/api/skiasharp.views.ios.skcanvasview.ignorepixelscaling) seems to be the _best_ way to handle DPI with SkiaSharp.
> 

great

**Comment by swharden** [comment]
Following-up, detecting the large size of the control and increasing text size to compensate is probably the best action to take

https://scottplot.net/faq/dpi-scaling/#increase-text-size

```cs
Fonts.Default = Fonts.Detect('频') ?? Fonts.System;

ScottPlot.Plot plt = new();
plt.Add.Signal(Generate.Sin());
plt.Add.Signal(Generate.Cos());

plt.TopAxis.Label.Text = "频率信号削减1/32";
plt.TopAxis.Label.Font.Size = 36;

plt.BottomAxis.Label.Text = "Horizontal Axis";
plt.BottomAxis.Label.Font.Size = 24;
plt.BottomAxis.TickFont.Size = 24;

plt.LeftAxis.Label.Text = "Vertical Axis";
plt.LeftAxis.Label.Font.Size = 24;
plt.LeftAxis.TickFont.Size = 18;
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/0bf1d41b-5b1e-4ab2-802f-36a8fb23277e)

**Comment by heartacker** [comment]
## Creat/Save
If we just want to create a plot and export and save it as pic like png, then I don't think it probably matters about DPI-scale.

## GUI APP

But when we use it in a GUI application, we should follow the DPI-scale first and should not let the user change the font

## BTW

Also,In high DPI Screen, all the elements of the plot except the font are very small, and the lines will be very thin, which is a fundamental problem.

If so, we have to change all staff's Size to make it show correctly

**Comment by heartacker** [comment]
oh, I think we should change the DPI-SCALING in the GUI control package,
1. base plot
   user just want to create picture with Absolute/exact size,
2. app control, 
   user create picture and show them in the screen, the visuality is most important, 
   user want  600*800 pic, and we should show them in screen with the DPI-Scaling size

**Comment by swharden** [comment]
Hi @heartacker, thanks again for your persistence on this one! I discovered that with SkiaSharp it's very easy to scale everything with a simple action. I'll add functionality like this into ScottPlot 5:

```cs
Plot plt = new();
plt.ScaleFactor = 2;
```

ScaleFactor = 1 | ScaleFactor = 2
---|---
![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/2fdbf374-d824-4bc9-ac04-1ce84971de9d)|![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/15febbe8-158e-43a3-8ae5-c511d0ca9276)


... then I'll have the user controls detect DPI scaling and automatically set that value

**Comment by heartacker** [comment]
plt.ScaleFactor = 2; > ``` >  > ScaleFactor = 1 ScaleFactor = 2 > ! [image](https://user-images.githubusercontent.com/4165489/253753585-2fdbf374-d824-4bc9-ac04-1ce84971de9d.png) ! [image](https://user-images.githubusercontent.com/4165489/253753604-15febbe8-158e-43a3-8ae5-c511d0ca9276.png) > ... then I'll have the user controls detect DPI scaling and automatically set that value 

Thanks very much，:D

Maybe we should spend some time to improve all(winform/wpf/av11.etc) of the GUI control

**Comment by swharden** [comment]
> Maybe we should spend some time to improve all(winform/wpf/av11.etc) of the GUI control

Thanks for the suggestion! I created https://github.com/ScottPlot/ScottPlot/issues/2760 to track progress for each of the controls
