### ISSUE TITLE
SP5: WPF control designer view looks bad

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2762]
It would be great if we could display something more useful instead of this...

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/e2aa75d9-c2cd-48d8-84c4-8caa8e8be7ff)

**Comment by KroMignon** [comment]
@swharden It would be hard to change, because it is the way `SKElement` was designed in SkiaSharp.

I found an opened issue at SkiaSharp [#2110](https://github.com/mono/SkiaSharp/issues/2110), to allow rendering during design, but it was not implemented in the source code.

**Comment by swharden** [comment]
Thanks for your research ingo this @KroMignon!
