### ISSUE TITLE
SP5 Scatter Plot: Extreme zoom results in poor performance

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2765]
I think there are floating point errors or some type of overflow related to points that lie outside the canvas area

**Comment by bukkideme** [comment]
Hi! I experienced memory overflow, beside background color change in SP4, when zooming in extremely into a painted circle. I have no idea if the two things are related?

In my application, i need to display a circle which has a physical size of radius as 150k microns. I need to be able to zoom in to see the microns level. 
Steps below. 1. Plot. 2. Start to zoom in. 3. After a certain level, the fill color will disappear and background color becomes default. 4. Further zoom too quick will result in a memory exception inside the System.Drawing DLL.

By the way, is there an easy way to disable further zoom in, for example when we reach a 5x5 microns (in my code example) zoom display axis size?
Test code:

```
var circle = formsPlot1.Plot.AddCircle(0, 0, 150_000, color: Color.Blue, lineWidth: 3);
            circle.Color = Color.LightSalmon;
            formsPlot1.Plot.AxisScaleLock(true);
            formsPlot1.Plot.AxisAuto();
            formsPlot1.Plot.Render();
            formsPlot1.Refresh(); 
```

![image](https://github.com/ScottPlot/ScottPlot/assets/51174971/d2f2e000-bb7b-4648-bb01-b8f7cfbdfbcb)

![image](https://github.com/ScottPlot/ScottPlot/assets/51174971/1f1d70e9-95ec-49ab-8ddc-1bc11b02dc08)

**Comment by swharden** [comment]
Following-up on this, I can't reproduce the issue with ScottPlot 5. I'm less inclined to put a lot of time into fixing this in ScottPlot 4, but a stopgap solution could be to scale-up values before plotting them.
