### ISSUE TITLE
The heatmap displays abnormally when resizing the window.

### ISSUE THREAD

**Issue by mYcheng-95** [ScottPlot/ScottPlot#2771]
## Bug Report

 I have drawn a heatmap with a large dataset, and I encounter an issue when resizing the window. This results in inconsistent display of the heatmap in different window sizes.
![2023-07-19 17-05-1020237191717462](https://github.com/ScottPlot/ScottPlot/assets/30651076/6468b8e4-052b-45b9-9806-b82b64b6ea73)

### System Details
* **ScottPlot Version:** 4.1.65/4.1.64?
* **Operating System:**Windows 10
* **Application Type:**  WPF
* **.NET Version:** NET Framework 4.8

**Comment by swharden** [comment]
Hi @mYcheng-95

This has taken a long time to get to because code isn't provided which allows me to reproduce the issue

Perhaps setting the heatmap's `smooth` property to `true` can fix this issue

**Comment by mYcheng-95** [comment]
Hi @swharden 
My dataset consists of 150 rows and over 8000 columns. The plotting is done using the default settings, and no smoothing is applied (I need to ensure that the plot does not use smoothing). I can provide you with the file containing this dataset.
This is the file address of my data: [output.txt](https://github.com/mYcheng-95/dataset/blob/main/output.txt)
