### ISSUE TITLE
SP4: Improve radial gauge scaling to reduce whitespace

### ISSUE THREAD

**Issue by tinuskotze** [ScottPlot/ScottPlot#2772]
## Bug Report

**Issue:** (Bug description goes here)
Scaling of RadialGauge done incorrectly. Really visible with GaugeCount>=8 with a lot of white space around the graph which changes with the number of gauges added. Screenshot of included code without the modifications
![radialgauge_quickstart1](https://github.com/ScottPlot/ScottPlot/assets/86287658/1c3b73c1-aa82-4d60-b39b-8c9043d60bb6)
Screenshot with the modifications using code Below:
![radialgauge_quickstart3a](https://github.com/ScottPlot/ScottPlot/assets/86287658/b4a423f3-5115-46af-b1d3-d507f19163f1)
Screenshot with the modification on original example from CookBook
![radialgauge_quickstart3](https://github.com/ScottPlot/ScottPlot/assets/86287658/cd5985f9-838d-43c7-9f85-c44f84b4064a)

**Reproducing:** (What do others have to do to reproduce the bug?)
Execute code sample below which is from the CookBook with a 4 additional gauges.

Problem seem to be caused by GetAxisLimits() in RadialGaugePlot.cs
Current Code: 

```cs
double radius = GaugeCount / 4;
```

Proposed Resolution: 

```cs
double radius = 1 + 0.5d / GaugeCount - SpaceFraction / GaugeCount/4;
```
As part of resolution remove 

```cs
pxPerUnit scaling in Render() (if (GaugeCount == 3)....)
```

![ProposedChanges](https://github.com/ScottPlot/ScottPlot/assets/86287658/0bf5f59b-77a0-4d50-8fb9-e62cab6515ee)

```cs
var plt1 = new ScottPlot.Plot(600, 400);
plt1.AddRadialGauge(new double[] { 100, 80, 65, 45, 20, 10, 10, 10, 10 });
plt1.SaveFig("c:\\temp\\radialgauge_quickstart1.png");
```

### System Details
* **ScottPlot Version:** 4.1 Stable (Nuget)
* **Operating System:** Windows 11
* **Application Type:** WinForms
* **.NET Version:** NET Framework 4.8

**Comment by swharden** [comment]
Thanks @tinuskotze for your detailed description of this issue and recommending the code to fix it!

I implemented your suggestion in fab53e2 and it will be in the next release 🚀
