### ISSUE TITLE
SP5 Color: WithAlpha() should have an overload that accepts a float

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2776]
Something like

```cs
/// <summary>
/// Return the color with an alpha from 0 (transparent) to 1 (opaque)
/// </summary>
public static Color WithAlpha(this Color color, double alpha=1)
{
    /* ... */
}
```

goes here

https://github.com/ScottPlot/ScottPlot/blob/1a4568c469b6e705846399ae6f13e8930c7a8d86/src/ScottPlot5/ScottPlot5/Color.cs#L66

**Comment by mjpz** [comment]
Something like this?

```
namespace ScottPlot
{
  public static class ColorExtensions
  {
    /// <summary>
    /// Return the color with an alpha from 0 (transparent) to 1 (opaque)
    /// </summary>
    public static Color WithAlpha(this Color color, double alpha = 1)
      => new(color.Red, color.Green, color.Blue, (byte)(alpha * 255));
  }
}
```

**Comment by swharden** [comment]
> Something like this?

Close! You can edit the source file directly to add your function just after line 66

By editing the file directly, you do not need an extension method.

https://github.com/ScottPlot/ScottPlot/blob/1a4568c469b6e705846399ae6f13e8930c7a8d86/src/ScottPlot5/ScottPlot5/Color.cs#L66

If you make this change as a pull request I would be happy to review it and merge it in! 🚀

**Comment by mjpz** [comment]
> 

`public static Color WithAlpha(this Color color, double alpha=1)`

using this is an Extension AFAIK

**Comment by mjpz** [comment]
`public readonly Color WithAlpha(double alpha) => new(Red, Green, Blue, (byte)(alpha * 255));
`

more like this?

**Comment by swharden** [comment]
Thanks @mjpz! This looks great 🚀
