### ISSUE TITLE
How to ensure that the labels won't overlap when resizing the window?

### ISSUE THREAD

**Issue by mYcheng-95** [ScottPlot/ScottPlot#2777]
**ScottPlot Version:** 4.1.65
**Operating System:**Windows 10
**Application Type**: WPF
**.NET Version**: NET Framework 4.8

At the beginning, my window size is about 450, and when resizing it to around 1200, there is a chance that label overlapping occurs. How can I avoid this?

![7c900f57b980e1f60f85d382c7a0308](https://github.com/ScottPlot/ScottPlot/assets/30651076/549e22e7-6acc-4c6c-8b39-1a5f89db50a5)
![51fe84a73e2b3a6f9812043efeecd41](https://github.com/ScottPlot/ScottPlot/assets/30651076/8c3472a2-09b8-4841-a4c7-61601595ecd4)

**Comment by swharden** [comment]
Hi @mYcheng-95,

The ideal axis tick density is handled automatically in ScottPlot. I'm guessing you disabled that in favor of manual tick positions/labels to create the screenshot above. If this is the case, the solution is to not use manual tick labels.

There are lots of cookbook examples for customizing tick labels and using DateTime ticks on https://scottplot.net/cookbook/4.1/

If you are unable to reach a solution there, another option is to use a function to regenerate a number of ticks that you control every time the axis scale changes. You can use the `OnAxesChanged` event as demonstrated on https://scottplot.net/faq/shared-axes/ to do this.

Hope it helps! 🚀
Scott
