### ISSUE TITLE
SP5: Pixel constructor overload that accepts `double`

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2780]
Presently there is just a constructor that accepts `float`

https://github.com/ScottPlot/ScottPlot/blob/1a4568c469b6e705846399ae6f13e8930c7a8d86/src/ScottPlot5/ScottPlot5/Pixel.cs#L8-L12

Add an overload which casts X and Y to `float` and assigns appropriately

**Comment by Silent0Wings** [comment]
do you mean like this ?
public void Pixel(double x,double y)
        {
           X=(float)(x);
           Y=(float)(y);
         }

**Comment by swharden** [comment]
> do you mean like this ?

Indeed! 

If you create a pull request including this change I will be happy to merge it 🚀
