### ISSUE TITLE
SP5: `CoordinateRect` needs a `Coordinates Center` property

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2789]
Add a line below this

https://github.com/ScottPlot/ScottPlot/blob/1a4568c469b6e705846399ae6f13e8930c7a8d86/src/ScottPlot5/ScottPlot5/CoordinateRect.cs#L15-L16

something like

```cs
public Coordinates Center => new(XCenter, YCenter);
```

**Comment by tijin-abe-thomas** [comment]
Hey, Could I work on this issue?

**Comment by swharden** [comment]
Hi @tijin-abe-thomas, indeed! If you create a PR I will be happy to review and merge it quickly 🚀
