### ISSUE TITLE
Plot line is not visible at the axis limits

### ISSUE THREAD

**Issue by mocakturk** [ScottPlot/ScottPlot#2808]
**ScottPlot Version:** 4.1.65

**Operating System:** Windows 10

**Application Type:** WinForms

**Question:** Hello,
I noticed a rendering problem after migrating our project to ScottPlot from ComponentOne...
The lines are not visible over the axis line. I'm sure there is a solution for this. But I couldn't find....

For example:

```cs
double[] dataX = new double[] { 0, 2, 3, 4, 5 };
double[] dataY = new double[] { 0, 4, 9, 16, 25 };
var plot = formsPlot1.Plot.AddScatterList(Color.Red);
plot.StepDisplay = true;
formsPlot1.Plot.SetAxisLimitsX(0, 5);
formsPlot1.Plot.SetAxisLimitsY(0, 25);
```
<img width="326" alt="p1" src="https://github.com/ScottPlot/ScottPlot/assets/106665359/40113155-f5d7-44bf-927c-926a7f079cc8">

My expected behavior is:
<img width="326" alt="p2" src="https://github.com/ScottPlot/ScottPlot/assets/106665359/40ac662a-2e92-4015-abc3-9f0696c4785d">
I don't want to change axis min/max values to make the lines visible. Min/max values are important for me to align other components next to plot. (I draw X and Y axis using my own component)

It is OK for me to give some padding between data area and axis area. But I cannot achieve this:
<img width="326" alt="p3" src="https://github.com/ScottPlot/ScottPlot/assets/106665359/92c53b57-26d9-428c-938e-75ade54ad40e">

Actually, I don't need axes:
<img width="326" alt="p4" src="https://github.com/ScottPlot/ScottPlot/assets/106665359/5f7c4e2a-617d-45cd-8f07-0ad28ef8a9f5">

Any solution is accepted other than changing axis min/max values.

Thank you,
Murat

**Comment by swharden** [comment]
Hi @mocakturk,

I actually think this is the intended behavior.

Consider where the grid line is for x=5 ... it's right where the tick mark is, under the vertical black line

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/30293487-732d-46c3-88ec-1ec732d828d4)

I think your final ascending step is underneath the black line... and I think this is its correct location.

## Sample Code

```cs
double[] dataX = new double[] { 0, 2, 3, 4, 5 };
double[] dataY = new double[] { 0, 4, 9, 16, 25 };

ScottPlot.Plot plot = new(400, 300);

var scatter = plot.AddScatterList();
scatter.AddRange(dataX, dataY);
scatter.StepDisplay = true;

plot.SetAxisLimits(0, 5, 0, 25);
plot.SaveFig("test.png");
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/a155b02c-2955-4908-8bed-a91becad42d5)

## Solutions

If you really want to see that final line, two ideas come to mind:

### Solution 1: pan 1 pixel

Pan the plot by a single pixel left. The tick mark for the x=5 position will look weird (it will be 1 pixel away from the edge of the screen), but you will be able to see your step. This is pretty hacky, but it works:

```cs
double[] dataX = new double[] { 0, 2, 3, 4, 5 };
double[] dataY = new double[] { 0, 4, 9, 16, 25 };

ScottPlot.Plot plot = new(400, 300);

var scatter = plot.AddScatterList();
scatter.AddRange(dataX, dataY);
scatter.StepDisplay = true;

plot.SetAxisLimits(0, 5, 0, 25);

plot.Render();
plot.GetSettings(showWarning: false).MouseDown(100, 100);
plot.GetSettings(showWarning: false).MousePan(99, 100);

plot.SaveFig("test.png");
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/c75bd840-64e7-43d1-802b-1b9eb4d76740)

### Solution 2: thick line

Set your scatter plot's `LineWidth` to a large number and it will bleed away from beneath the frame and into the data area

```cs
double[] dataX = new double[] { 0, 2, 3, 4, 5 };
double[] dataY = new double[] { 0, 4, 9, 16, 25 };

ScottPlot.Plot plot = new(400, 300);

var scatter = plot.AddScatterList();
scatter.AddRange(dataX, dataY);
scatter.StepDisplay = true;
scatter.LineWidth = 5;

plot.SetAxisLimits(0, 5, 0, 25);
plot.SaveFig("test.png");
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/80329722-437c-4d84-9d54-414d6a07bb26)

Thanks for this great question! I'm happy we found some solutions 🚀
