### ISSUE TITLE
SP4 Heatmap: Add `Rotate` property

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2814]
Bitmaps can be rotated:
https://scottplot.net/cookbook/4.1/category/plottable-image/#image-rotation

It would be convenient, if beside the horizontal and vertical flips, we could also rotate the Heatmap before rendering it.
There are some questions:
1. what would be the default rotation direction? Clockwise or anti-clockwise?
2. If flip(s) and rotation are also specified, activated, what should be the natural order? Always first flip then rotate, or the other way?

**Comment by bukkideme** [comment]
ok, regarding to 1., we should be consistent with the Image class:

/// <summary>
        /// Rotate the image clockwise around its primary corner (defined by Alignment) by this number of degrees
        /// </summary>
      `  public double Rotation { get; set; }`

**Comment by bukkideme** [comment]
Regarding to point 2., i feel it is better to first perform the flips, then the rotation should be the last step before rendering...
I make some tests, and if it works, i make a PR.

**Comment by bukkideme** [comment]
https://github.com/ScottPlot/ScottPlot/pull/2815

**Comment by swharden** [comment]
Hi @bukkideme, thanks for #2815! I'm merging it in now.

Note that you get really funky behavior if you use rotation without `lockScales: true`

There's probably some way to fix it... maybe by doing some type of trigonometry to figure out the actual `dataRect` `Width` and `Height` after rotation. I'm not super inspired to figure that out, but if you get that working I'd be happy to merge that in as a future PR.

Thanks again! 🚀

**Comment by swharden** [comment]
Answering your original questions, 
> what would be the default rotation direction? Clockwise or anti-clockwise?

I like clockwise

> If flip(s) and rotation are also specified, activated, what should be the natural order? Always first flip then rotate, or the other way?

Probably flip first, rotate last.

Flipping makes sense in terms of a 2D array. Flipping when rotation is arbitrary (12.3 degrees) is a little more confusing.

I think both decisions you made were great!
