### ISSUE TITLE
Control Backend: Add support for multitouch pan and zoom

### ISSUE THREAD

**Issue by ZNAIHE** [ScottPlot/ScottPlot#2828]
Hi @swharden 

I want to implement the pinch zoom function on the chart on the touch screen, but currently only the chart can be touched and dragged.I tried multi-touch with the IsManipulationEnabled = true property setting, but then touch dragging doesn't work. How can I achieve this function?

```cs
ScottPlot.WpfPlot wpfPlot1 = new ScottPlot.WpfPlot();
wpfPlot1.IsManipulationEnabled = true;
wpfPlot1.ManipulationDelta += WpfPlot1_ManipulationDelta;
```

```cs
private void WpfPlot1_ManipulationDelta(object sender, ManipulationDeltaEventArgs e)
{
    if (e.Manipulators.Count() == 2) 
    {
        double scale = e.DeltaManipulation.Scale.X;

        FrameworkElement element = e.OriginalSource as FrameworkElement;

        if (element != null)
        {
            element.Width *= scale;
            element.Height *= scale;
        }
    }
}
```

**ScottPlot Version:** 4.1.57
**Operating System:** Windows 10
**Application Type:** WPF

**Comment by swharden** [comment]
Hi @ZNAIHE, thanks for this question! I will leave this issue open to track progress for built-in support for multitouch zooming. 

For now I think you can achieve this effect by adding this into your function:

```cs
// when multi-touch first starts, save the original axis limits at the class level
ScottPlot.AxisLimits OriginalLimits = plt.GetAxisLimits();
```

```cs
// every time a manipulation occurs, reset the axis limits to the original ones 
plt.SetAxisLimits(OriginalLimits);

// then zoom in according to the scale
plt.AxisZoom(scaleX, scaleY);
```

Note that you probably want to separate X and Y scales, but you don't have to.

Let me know if this does the trick!

**Comment by ZNAIHE** [comment]
Thank you for your answer. This method can roughly realize the zoom function, but it is not compatible with the original left-click drag function. Hopefully it will be compatible with multi-touch zooming.

**Comment by swharden** [comment]
Hi @ZNAIHE, thanks for looking into it! 

Note that there are both `AxisPan()` and `AxisZoom()` methods available

If you need to disable the built-in pan and zoom behavior, this is possible with the settings in the `WpfPlot1.Configuration` configuration object, many of which are described on https://scottplot.net/faq/configuration/

Does this help you reach a solution? If so let me know and I can create a FAQ page clarifying how others can achieve multitouch pan and zoom as well.

Thanks for your feedback!

**Comment by bukkideme** [comment]
Hi @swharden ! 
Since we also develop apps containing ScottPlot plots targeting touchscreen monitors, it would be great to have such FAQ page! :)  
Actually i never tried so far how i could play with a ScottPlot formsplot control zoom/etc on a touchscreen monitor, but i will have a look soon!
thanks!

**Comment by swharden** [comment]
Hi @bukkideme and @ZNAIHE,

I think adding multitouch support is a fantastic idea.

However, there hasn't been much movement on this issue in a while and I'm going to spend the next several weeks bringing ScottPlot 5 up to its release, so I'm unlikely to work on this myself in short order.

If someone posts some example code showing how to support multi-touch in one or more of the user controls, I'd be happy to adapt that code into the ScottPlot (4 and 5) controls. If someone wants to create a PR demonstrating any control, that would be a great start!
