### ISSUE TITLE
SP4 DataLogger: Add option to allow "fill below" type line styles

### ISSUE THREAD

**Issue by 2638662731** [ScottPlot/ScottPlot#2832]
![image](https://github.com/ScottPlot/ScottPlot/assets/64895402/de111190-911a-4acb-b2fb-751d65e3f11e)
Hello, how does the X-axis display time for the DataLogger column in the demo

**Comment by 2638662731** [comment]
Can this instance be filled with colors using FillBelow? How can I do it if possible? And can the properties that can be used in SignalPlot such as Smooth be used?

**Comment by swharden** [comment]
Hi @2638662731, thanks for opening this issue!

Your requests are possible, but I do not think I will take my time to implement these features right now. #2706

However, by comparing the source code of `DataLogger` and `SignalPlot` you can create your own plot type `ShadedDataLogger` that has this feature.

This is how you can create a custom plot type in your own application:
https://scottplot.net/faq/custom-plot-type/

If you get this working you are welcome to share the code of your new plot type here (or in a pull request) and others with the same goal can use it too 👍
