### ISSUE TITLE
SP5: frequent typeface lookups result in poor performance on Linux

### ISSUE THREAD

**Issue by taya92413** [ScottPlot/ScottPlot#2833]
## Bug Report

**Issue:** 
Very poor performance, only 10-20FPS
Referring to #2419 could solve the performance issue, but I am not sure about the problems encountered on .NET Framework, so it was not ultimately resolved.

#2419 method:
Modify source code 
Path: `ScottPlot-main\src\ScottPlot5\ScottPlot5\Extensions\SkiaSharpExtensions.cs`
Add a static SKTypeface to avoid searching for SKTypeface every time rendering occurs.
Finally build the .dll

```cs
    //Add
    private static SKTypeface? _typeface = null;

    public static void ApplyToPaint(this FontStyle fontStyle, SKPaint paint)
    {
        SKFontStyleWeight weight = fontStyle.Bold ? SKFontStyleWeight.Bold : SKFontStyleWeight.Normal;
        SKFontStyleSlant slant = fontStyle.Italic ? SKFontStyleSlant.Italic : SKFontStyleSlant.Upright;
        SKFontStyleWidth width = SKFontStyleWidth.Normal;
        SKFontStyle skfs = new(weight, width, slant);

        //SKTypeface typeface = SKTypeface.FromFamilyName(fontStyle.Name, skfs);

        //Add choose one of the two, they are the same
        SKTypeface typeface = _typeface ?? (_typeface = SKTypeface.FromFamilyName(fontStyle.Name, skfs));
        //SKTypeface typeface = (_typeface == null) ? _typeface = SKTypeface.FromFamilyName(fontStyle.Name, skfs) : _typeface;


        paint.Typeface = typeface;
        paint.TextSize = fontStyle.Size;
        paint.Color = fontStyle.Color.ToSKColor();
        paint.IsAntialias = fontStyle.AntiAlias;
    }
```

Low performance picture:
<img width="600" alt="螢幕擷取畫面 2023-08-04 095502" src="https://github.com/ScottPlot/ScottPlot/assets/35124424/e94bb86b-6858-49b8-840b-4ac9e5f18e32">

**Reproducing:** 
a code sample
Xaml:
```Xaml
<ScottPlot:AvaPlot Name="AvaPlot1" />

```
C#:
```cs
   double[] dataX = { 1, 2, 3, 4, 5 };
   double[] dataY = { 1, 4, 9, 16, 25 };

   AvaPlot avaPlot1 = this.Find<AvaPlot>("AvaPlot1");
   avaPlot1.Plot.Add.Scatter(dataX, dataY);
   avaPlot1.Refresh();
```

### System Details
* **ScottPlot Version:** 5.0.6 beta
* **Operating System:** Ubuntu20.04、Ubuntu22.04、WSL
* **Application Type:** Avalonia11.0.2
* **.NET Version:**  .NET 6.0、.NET 7.0

**Comment by swharden** [comment]
resolved in #2848

@taya92413 should be fixed in the next release (5.0.8-beta) but are you able to test if it works for you now using the source code in the main branch of this repository? I your problem is resolved but would love confirmation before publishing the next package if you're able to take a look. Thanks!
