### ISSUE TITLE
Is there any kind of support for browser based apps?

### ISSUE THREAD

**Issue by zborowa** [ScottPlot/ScottPlot#2835]
**ScottPlot Version:** 5.x

**Operating System:** Cross-platform

**Application Type:** Avalonia UI or Uno Platform desktop and browser

**Question:** My question is related to the support of browser-based applications. Now that ScottPlot's rendering engine is Skia I wanted to know about the support for desktop and browser plots. Examples of other libraries that also use Skia and support rendering on the desktop and the browser are [LiveCharts2](https://www.lvcharts.com/docs/avalonia/2.0.0-beta.900/gallery) and [Micrcharts](https://github.com/AvaloniaCommunity/Avalonia.Microcharts).
Is there any plan or workaround to make the plots work in the browser? I'm trying to choose between Avalonia UI or Uno Platform for my next project but a proper scientific plotting library is a must.

**Comment by oktrue** [comment]
@zborowa SP5 already support Avalonia WASM browser version. I also added sample project Sandbox.Avalonia.Browser in #2830. You can test it after merge.

**Comment by oktrue** [comment]
But there is a problem with colors in Avalonia WASM version which we discuss in #2818

**Comment by swharden** [comment]
> SP5 already supports Avalonia WASM browser version

Indeed! ScottPlot 5 (currently in preview, not yet recommended for production applications) supports running in the browser.

ScottPlot 4 (the current release / stable version) does not

I hope to get ScottPlot 5 out of preview within the next few months (definitely before the release of .NET 8 in November)

https://scottplot.net/versions/

**Comment by zborowa** [comment]
Thank you for the quick response! If I understand correctly the current 5.0.6-beta does not support the browser yet because I'm getting the following error `Parameter types of pinvoke callback method 'System.Int32 SetMinMaxSize(System.Void*, Avalonia.Native.Interop.AvnSize, Avalonia.Native.Interop.AvnSize)' needs to be blittable.` but potentially the next beta should be able to support it. I've verified that the Color test from @oktrue indeed works in the browser (and has the color problem).
I think that 5.0.6-beta is also mistagged in the source control as 4.0.6-beta.

**Comment by swharden** [comment]
> support the browser

As of a few hours ago the main branch has 2 projects that run in the browser: Avalonia and WinUI, both are in the "sandbox" folder of the main solution

> mistagged in the source control as 4.0.6-beta

Thanks for letting me know! I'll be more careful in the future 😅

**Comment by agneszitte** [comment]
Hi @zborowa. just a quick update on this old issue, in case you or anyone else might still need it.

There is now an [Uno Platform](https://platform.uno/) Getting Started documentation available for ScottPlot: https://scottplot.net/quickstart/unoplatform/. This allows you to use ScottPlot charts on multiple platforms, including WebAssembly for running charts on the web.

You can also check out the related blog post with more details: [Introducing ScottPlot Support for Uno Platform](https://platform.uno/blog/introducing-scottplot-support-for-uno-platform/).
