### ISSUE TITLE
SP4 Avalonia: The plot and ticks get sharp

### ISSUE THREAD

**Issue by Xpyctajleb** [ScottPlot/ScottPlot#2858]
## Bug Report

**Issue:** 
The plot and ticks get sharp when I press any mouse button and move the cursor. DpiStretch=false doesn't fix this.
![2](https://github.com/ScottPlot/ScottPlot/assets/5584312/74adc300-43ea-4a26-955f-91e293cffc75)

### System Details
* **ScottPlot Version:** 4.1.65
* **Operating System:** Windows 11
* **Application Type:** Avalonia 11
* **.NET Version:** .NET 6.0

**Comment by BambOoxX** [comment]
I think this is due to the default non anti aliased rendering default during interaction.
See https://scottplot.net/faq/anti-aliasing/

**Comment by swharden** [comment]
Indeed! I think behavior can be changed using something like: 

```cs
formsPlot1.Configuration.Quality = QualityMode.LowWhileDragging; // default for performance
```

```cs
formsPlot1.Configuration.Quality = QualityMode.High; // always high quality
```

**Comment by Xpyctajleb** [comment]
It works! Thank you!
