### ISSUE TITLE
Adding multiple Signal plots can decrease performance

### ISSUE THREAD

**Issue by Chfei1** [ScottPlot/ScottPlot#2861]
**ScottPlot Version:** 4.1.66

**Operating System:** Windows

**Application Type:** WPF

**Question:** Adding multiple Signal plots can decrease performance.

```cs
// a code sample may improve communication
  var wpfPlot = new WpfPlot();
for (int k = 0; k < 50; k++)
            {
                double[] data = Generate.RandomWalk(10000);
                wpfPlot .AddSignalConst(data);
                wpfPlot .Plot.AddSignalConst(data);
            }
wpfPlot.Refresh(true);
```
Is there any solution?
![Snipaste_2023-08-10_13-37-26](https://github.com/ScottPlot/ScottPlot/assets/17043383/dea4ba39-33dc-4b31-9829-a85b23c51c68)

**Comment by swharden** [comment]
Hi @Chfei1, 

I modified the code a little bit but performance is fantastic. Here's a console app:

```cs
ScottPlot.Plot plt = new();
ScottPlot.RandomDataGenerator gen = new();
for (int k = 0; k < 50; k++)
{
    double[] data = gen.RandomWalk(10_000);
    plt.AddSignalConst(data);
}

// display it in a Windows Form
Form form = new() { Width = 600, Height = 400 };
ScottPlot.FormsPlot formsPlot1 = new() { Dock = DockStyle.Fill };
formsPlot1.Reset(plt);
formsPlot1.Refresh();
form.Controls.Add(formsPlot1);
form.ShowDialog();
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/ee7073b5-a992-4125-b612-593f7770e299)

Let me know if generating random data this way does not improve performance in the way you expect 👍

**Comment by Chfei1** [comment]
thanks,However, the larger the window, the lower the performance.

**Comment by swharden** [comment]
> thanks,However, the larger the window, the lower the performance.

This is consistent with expectations. The laeger the bitmap, the longer it takes to render in memory.

ScottPlot 5 is still in preview but it offers hardware accelerated rendering for vastly improved performance over what System.Drawing (what ScottPlot 4 uses) can achieve. I look forward to it getting out of preview soon!
