### ISSUE TITLE
SP4: ScatterPlotDraggable `IsUnderMouse()` crashes after calling `ScatterPlot.Update()`

### ISSUE THREAD

**Issue by onur-akaydin** [ScottPlot/ScottPlot#2870]
## Bug Report

**Issue:** ScatterPlotDraggable.IsUnderMouse method crashes after calling ScatterPlotDraggable.Update method

**Reproducing:** 

Calling ScatterPlotDraggable.Update method with a new pair of Xs and Ys arrays, "larger" than the existing ones, then waiting for any event that is triggering ScatterPlotDraggable.IsUnderMouse method (i.e. a mouse down event) will eventually crash. Because in ScatterPlotDraggable, Xs and Ys are defined as NEW double arrays, IsUnderMouse references to them, however ScatterPlot.Update() method updates the other Xs and Ys arrays in the base class.

```cs
myScatterPlotDraggable.Update(newXsWithLargerSize, newYsWithLargerSize);
// make a mouse interaction
```

I found a solution by removing Xs and Ys properties from ScatterPlotDraggable, and changing the relevant set accessors in ScatterPlot class to "protected set"

In ScatterPlotDraggable.cs:
```cs
//public new double[] Xs { get; private set; }
//public new double[] Ys { get; private set; }
```

In ScatterPlot.cs:
```cs
public double[] Xs { get; protected set; }
public double[] Ys { get; protected set; }
```

But I'm not sure if there is a side effect to doing it like this.

### System Details
* **ScottPlot Version:** 4.1.65.0
* **Operating System:** Windows 11
* **Application Type:** WPF
* **.NET Version:** .NET 7.0

**Comment by swharden** [comment]
Hi @onur-akaydin, thank you for reporting this!

Considering how long this issue has been open and how I'm focusing the next several weeks on ScottPlot 5 (#2984) it's unlikely I'm going to be able to look into this soon, so I'll close this issue but I welcome contributions if others have a recommendation.

Note that the method that crashes is here:
https://github.com/ScottPlot/ScottPlot/blob/c7ce83274728f35977dc7d4c55aadc56ed8ee997/src/ScottPlot4/ScottPlot/Plottable/ScatterPlotDraggable.cs#L101-L114

...so an an alternative fix that is less likely to produce side effects would be to wrap that in some logic that catches index exceptions and returns `false` if they occur. If someone opens a PR with this fix I'm happy to review it!

**Comment by swharden** [comment]
Following-up, I see this issue may also be causing #2969

I'll prioritize this fix higher than other ScottPlot 4 fixes and try to get it resolved before the next release 👍
