### ISSUE TITLE
SP5: `CoordinateRect` needs methods for expanding to include `Coordinates`

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2871]
needs methods to expand to include a point or rectangle, something like

```cs
CoordinateRect rect1 = new(-10, 10, -10, 10);

Coordinates coord = new(13. 42);

CoordinateRect rect2 = rect1.Expanded(coord);
```

notably the values are mutable, so perhaps this could run in place

https://github.com/ScottPlot/ScottPlot/blob/42987b60b6fb90e94d0fb67a60c7dfafc73d8d9a/src/ScottPlot5/ScottPlot5/Primitives/CoordinateRect.cs#L8-L13

**Comment by aespitia** [comment]
Is the idea here that rect1 grows to a size to include the coordinate, and returns a new rectangle?

**Comment by swharden** [comment]
Correct! That's my thinking of what would be most useful

**Comment by aespitia** [comment]
I've never contribued before, so apparently I don't know how to make a pull request for this repo.  Is this something like what you had in mind?

public CoordinateRect Expanded(Coordinates point) {
        double exLeft = Left;
        double exRight = Right;
        double exBottom = Bottom;
        double exTop = Top;

        if (!Contains(point))
        {
            if (point.X < Left) exLeft = point.X;
            if (point.X > Right) exRight = point.X;
            if (point.Y < Bottom) exBottom = point.Y;
            if (point.Y > Top) exTop = point.Y;
        }

        return new CoordinateRect(exLeft, exRight, exBottom, exTop);
    }

**Comment by swharden** [comment]
> Is this something like what you had in mind?

Indeed! 

> I don't know how to make a pull request for this repo

If you feel like figuring it out you can probably find a YouTube video that walks through the steps, and I'm happy to support you along the way by answering any questions that may pop up! If it ends up being too much work or you don't want to create your own pull request, let me know and I can create the pull request myself 👍

**Comment by swharden** [comment]
> Is this something like what you had in mind?

Maybe it could be even simpler with something like:

```cs
return new CoordinateRect(
    left: Math.Min(Left, point.Left),
    right: Math.Max(Right, point.Right),
    bottom: Math.Min(Bottom, point.Bottom),
    top: Math.Max(Top, point.Top),
);
```

**Comment by swharden** [comment]
> YouTube video

Here's one that describes how to use GitHub Desktop (a GUI for git) 

https://www.youtube.com/watch?v=8x6V5IOuXog

**Comment by aespitia** [comment]
Thanks, yes, I do know how to make PRs in my own repos, but I guess I wasn't sure how to do it against another repo, do I need permissions, or do I fork it into my own repo and then somehow link it to this?  

I do like your update to simplify the logic as well, good call.

**Comment by aespitia** [comment]
PR is in

https://github.com/ScottPlot/ScottPlot/pull/2890
