### ISSUE TITLE
SP5: `ExpandingAxisLimits` needs `Width` and `Height`

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2872]
ExpandingAxisLimits needs Width and Height properties

https://github.com/ScottPlot/ScottPlot/blob/42987b60b6fb90e94d0fb67a60c7dfafc73d8d9a/src/ScottPlot5/ScottPlot5/Primitives/ExpandingAxisLimits.cs#L8-L11

**Comment by KalliopiPliogka** [comment]
I would like to work on this!
