### ISSUE TITLE
SP5: LayoutEngines.Matched should be public

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2881]
https://github.com/ScottPlot/ScottPlot/blob/42987b60b6fb90e94d0fb67a60c7dfafc73d8d9a/src/ScottPlot5/ScottPlot5/LayoutEngines/Matched.cs#L6

**Comment by proplunger** [comment]
Hi, I've made changes. Here's my PR
https://github.com/proplunger/ScottPlot/pull/1

**Comment by swharden** [comment]
Hi @proplunger, thank you so much for this! I'm disappointed it took me so long to merge this in, but I'm happy to do it today. Thanks again!
