### ISSUE TITLE
SP5: Improve legend support for the `FillY` plot type

### ISSUE THREAD

**Issue by msroest** [ScottPlot/ScottPlot#2886]
## Feature Suggestion

**Feature description:**
I'm attempting to create a FillY plot with 2 series 1 for power usage and 1 for Solar power generated I'm currently able to get it to look the way I'm wanting by using the FillY and setting the second series to all 0's so it just fills from my data point to the x-axis.  However I would like to still have a Legend and it appears that the FillY doesn't have a Label to set and is hardcoded to always return no LegendItems
https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Plottables/FillY.cs#L8
vs Scatter
https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs#L28

I can't imagine I'm the only one who wants to do something like this;
What I'm currently getting:
![generation](https://github.com/ScottPlot/ScottPlot/assets/91028/2cd4fd18-b978-4039-a326-1b8440a4818b)

Scatter with the same plot but with legend:
![generation-1](https://github.com/ScottPlot/ScottPlot/assets/91028/d50a8b62-d24d-4bb9-90f1-2bd5ec22fca4)

**Comment by swharden** [comment]
Hi @msroest, thanks for this suggestion! I agree it's a good idea to add legend support. If someone is available to make a pull request, they can probably help make this happen faster than I can!

You correctly identified the line of code requiring modification:
https://github.com/ScottPlot/ScottPlot/blob/42987b60b6fb90e94d0fb67a60c7dfafc73d8d9a/src/ScottPlot5/ScottPlot5/Plottables/FillY.cs#L8

And by adding logic like scatter plot, FillY plots will appear in the legend too:
https://github.com/ScottPlot/ScottPlot/blob/42987b60b6fb90e94d0fb67a60c7dfafc73d8d9a/src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs#L28-L34

I'll leave this issue open until this is resolved. If no one fixes it after a week or two, I'll fix it myself before the next release 👍

**Comment by msroest** [comment]
Hey @swharden,
  Thanks for the note that you'd be up for the support, I'll take a shot at trying to submit a PR here over the next few days.
