### ISSUE TITLE
SP5:how to AddHorizontalLine in sp5

### ISSUE THREAD

**Issue by DrZhong** [ScottPlot/ScottPlot#2888]
---------------------------------

**ScottPlot Version:5.

**Operating System:** ???

**Application Type:** (console, WinForms, WPF, etc...)

**Question:**  How to AddHorizontalLine or AddVerticalLine in SP5

```cs
 // add axis lines
plt.AddHorizontalLine(.85);
plt.AddVerticalLine(23);
```

**Comment by swharden** [comment]
Hi @DrZhong, 

ScottPlot 5 is not released yet (it's a preview package, lacking many features and documentation). This feature will be added before the release for sure 👍 https://scottplot.net/versions/
