### ISSUE TITLE
Anti-Aliasing in 4.1

### ISSUE THREAD

**Issue by Xpyctajleb** [ScottPlot/ScottPlot#2891]
**ScottPlot Version:** 4.1
**Application Type:** Avalonia
**Question:** 
How to disable anti-aliasing completely?

```cs
plt.AntiAlias(figure: false, data: false, legend: false); //4.0, doesn't work now

**Comment by swharden** [comment]
Hi @Xpyctajleb, I think it's something like:

```cs
AvaPlot1.Configuration.QualityMode = Low;
```

https://scottplot.net/faq/anti-aliasing/

**Comment by Xpyctajleb** [comment]
For AvaPlot works Configuration.Quality, not QualityMode, but it works though! Thank you!
`AvaPlot1.Configuration.Quality = ScottPlot.Control.QualityMode.Low;`
