### ISSUE TITLE
SP4:  LegendViewer is throwing an unmanaged exception error.

### ISSUE THREAD

**Issue by LapinFou** [ScottPlot/ScottPlot#2895]
# Bug Report

**Issue:**
Index out of limit error occurs when playing with the detached legend viewer.

**Reproducing:**
1. Download the **Windows Forms demo** from here: https://scottplot.net/demo/
2. Click on the **Launch ScottPlot Cookbook** button
3. Choose the **Legend Orientation** demo from the _Legend_ category
4. Right click on choose the **Detach Legend** option
5. Left click into the **Legend Viewer** to unselect the `sin` and `cos` plots
6. Left click in the empty interactive plot windows
7. Left click into the **Legend Viewer** on the `sin` or `cos` plot

### System Details
* **ScottPlot Version:** 4.1.67
* **Operating System:** Windows 10 Pro
* **Application Type:** WinForms

**Comment by LapinFou** [comment]
![image](https://github.com/ScottPlot/ScottPlot/assets/1685030/0c60d3c2-72e5-418e-a60c-6f345e3a77cd)

**Comment by swharden** [comment]
Thanks so much for this detailed bug report @LapinFou! I was able to resolve this issue and the fix will be in the next release 🚀
