### ISSUE TITLE
New plot type for draggable rich text 

### ISSUE THREAD

**Issue by DaveMartel** [ScottPlot/ScottPlot#2905]
## As discussed on Discord, I would love to see a rich text draggable plotable

**As a minimum I need to be able to specify certain characters to be superscripted or subscripted. Better yet I would like to be able to add the various other font styling attributes, such as italic, bold, strike through. Finally to top it off (to match my functionality in an application I am rewriting), I would ideally like to be able to set character color, on a character by character basis...

Something like this (if I can manage to attach an image)
![Capture2](https://github.com/ScottPlot/ScottPlot/assets/24892075/dc21264f-43a6-491a-9c97-c5ebcc1ca5ed)

**Comment by DaveMartel** [comment]
Just as a thought, I wonder whether it might be an idea to provide the label text in "Markdown" format. It would certainly (I think handle my requirements. It handles italics, bold strikethrough, superscript, subscript in an easy format to parse for rendering.

I do not necessarily need to change fonts mid label. However of course others might disagree. I think then we might need to move to RTF (though that starts to get a project), or else set up custom ways of specifying attributes for spans of characters

**Comment by swharden** [comment]
Hi @DaveMartel, thanks for this suggestion!

This seems useful indeed, and figuring out how to do this has the potential to help a lot of people. I think the best solution is to use a third party library to generate a transparent bitmap (PNG, BMP, etc.) from the rich text. I suspect there are libraries that can do this from RTF or HTML formatting. Then you could add the text as an image to a plot using `AddImage()`, and although it doesn't exist yet we could create a `DraggableImage` plot type.

I'm focusing on some core features of ScottPlot 5 for the next few weeks and this issue hasn't any movement in a while so I'll close it for now, but if someone makes progress on this front I'd be happy to add their code into the library myself or review a PR if someone opens it 👍 

Related: https://scottplot.net/faq/custom-plot-type/

**Comment by KennyTK** [comment]
Commenting to express interest in label text with "Markdown" formatting. I use units in my labels and would like to be able to follow conventions for italicizing. 
https://physics.nist.gov/cuu/pdf/typefaces.pdf

**Comment by swharden** [comment]
Hi @DaveMartel and @KennyTK, 

It's been a while since this topic was discussed here but I wanted to follow-up and note that `LabelStyle` got an `Image` property in #4517, so this feature should now be supported.
