### ISSUE TITLE
Changing xAxis offset of wpfplot based on another plottable position (horizontal scroll programmatically)

### ISSUE THREAD

**Issue by ompcj4u** [ScottPlot/ScottPlot#2906]
I generated an array of double based on an audio file using NAudio and add it to the **wpfplot.Plot** using **AddSignal**. After that I added a **VLine** as a timeline to the plot, so every time the use play the audio, timeline position will change to the corresponding time based on audio time as you can see in the pictures below.

![image](https://github.com/ScottPlot/ScottPlot/assets/6485310/4013cc61-5f17-48f6-a3a6-ab145e927190)

![image](https://github.com/ScottPlot/ScottPlot/assets/6485310/657ec7ca-5091-4a14-9d82-0dfa24828327)

The problem is when timeline reaches to the end of visible area of waveline, I need to scroll wpfPlot based on the position of VLine so user can follow the timeline and waveline together. Is there any way to scroll the plot horizontally? 

![image](https://github.com/ScottPlot/ScottPlot/assets/6485310/a0cd71e7-da45-4478-8a94-1e5566f91267)

**Comment by swharden** [comment]
> Is there any way to scroll the plot horizontally?

Hi @ompcj4u, indeed! You can call the plot's `GetAxisLimits()` and interact with that object to determine the left and right sides of the view, figure out how much you want to scroll, then call `SetAxisLimits()` with the values you think are best.

Alternatively the plot has an `AxisPan()` method you could call.

In both cases be sure to call the control's `Refresh()` method to force the screen to redraw after setting the axis limits.

Hope it helps! 🚀
