### ISSUE TITLE
Keep track of DataMin and DataMax only for shown data in DataStreamer

### ISSUE THREAD

**Issue by nv-kn** [ScottPlot/ScottPlot#2910]
## Feature Suggestion

**Feature description:**
 It would be nice to have an option to keep track of minimum and maximum data only of the currently shown data points of a DataStreamer and scale the y axis to pretty much wrap the current data closely. 

I would find it useful because when keeping track of some streaming data from lets say a sensor, the data can vary a lot over time, but I only want to see the close differences in the last couple of hundred data points, so if there were some significant outliers in the history, the graph is not very detailed. 

I understand that this would probably come with some performance loss, but I think the option to have the feature would be cool.

**Comment by swharden** [comment]
Hi @nv-kn, thanks for this suggestion!

The `DataStreamer` actually has classes that implement `IDataStreamerView` to control how the autoscaling works https://github.com/ScottPlot/ScottPlot/tree/main/src/ScottPlot4/ScottPlot/Plottable/DataStreamerViews

You could create a `ScrollAndZoomOntoLastNPoints` class (or something with a less crazy name lol) that does the exact logic you describe, then assign it to your DataStreamer's `Renderer` property

https://github.com/ScottPlot/ScottPlot/blob/c7ce83274728f35977dc7d4c55aadc56ed8ee997/src/ScottPlot4/ScottPlot/Plottable/DataStreamer.cs#L65-L68

You could try this in your own code without modifying ScottPlot's source code, and if you create a class that has this functionality that works well for you, feel free to share the code in this issue or create a pull request and we can include it with ScottPlot as an opt-in feature!
