### ISSUE TITLE
Can not add multiple color bars to a scatter plot

### ISSUE THREAD

**Issue by vietanhbui** [ScottPlot/ScottPlot#2911]
**Issue:** Can not add multi color bar in scatter plot

```cs
formsPlot1.Plot.AddColorbar();
formsPlot1.Plot.AddColorbar(rightSide: false);
formsPlot1.Plot.AddColorbar(rightSide: false);
formsPlot1.Plot.AddColorbar();
```
![image](https://github.com/ScottPlot/ScottPlot/assets/43196820/77445baa-7696-4827-86eb-8b216e44371d)

**Comment by swharden** [comment]
Hi @vietanhbui, unfortunately this is a limitation of ScottPlot 4 and it is unlikely to be added as a new feature soon

However I am working hard on ScottPlot 5 now and hope to release it in a few weeks, and it will indeed support the option to add multiple colorbars! #2984
