### ISSUE TITLE
Obsolate method info in FAQ page

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#2912]
https://scottplot.net/faq/axis/#set-boundaries-on-the-axis-limits
SetOuterViewLimits is obsolate.

**Comment by swharden** [comment]
Thanks @bukkideme, good catch! Wow it took me a long time to get to this one 😅 

I'd appreciate it if you could spot-check to make sure I captured your suggestion!

https://scottplot.net/faq/axis/#set-boundaries-on-the-axis-limits
