### ISSUE TITLE
SP5: `Line` plot type

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2915]
I'm about to merge #2901 which provides methods like `Add.Line()` to place a line on the plot, but the way it does it is by creating a scatter plot with only two points. This gets the job done for now, but a special `Line` plot type just for straight lines seems like a better option. A primitive that represents a single line would also be useful to have.

**Comment by Gray-lab** [comment]
I gave this a shot and created both a Line primitive and a Line plot type, along with some cookbook recipes for testing. What I created allows the user to define a line using endpoints and styling. I think it would be quite easy to do something similar for an Arrow plot type.
