### ISSUE TITLE
AvaPlot does not respect the size of its container

### ISSUE THREAD

**Issue by Developer-Alexander** [ScottPlot/ScottPlot#2923]
## Bug Report

**Issue:** 
With ScottPlot.Avalonia 5.0.8-beta the size of AvaPlot does not match to its containing container (e.g. a cell of a grid). Instead it is drawn exceeding the boundaries of its containing container or much smaller. I have seen both cases. Sometime the plot is flickering due to frequent chenges of the size.

**Comment by sunwayking** [comment]
There is a workaround for ScottPlot.Avalonia 5.0.8-beta. Put AvaPlot into a UserControl, then it should be aware of parent size.

**Comment by swharden** [comment]
Hi @Developer-Alexander, thanks for pointing this out!

If either of you (or @bclehmann, the original AvaPlot's author) wish to back-port this solution to ScottPlot 4, I'd be happy to review a pull request!

For now I'll close this issue so I can put more development focus into ScottPlot 5 #2984

**Comment by JohnSmith20211124** [comment]
@swharden 
This bug can be fixed by calling 
`context.Custom(new CustomDrawOp(new Rect(Bounds.Size), Plot));`
in the Render()-Method of AvaPlot.cs, instead of calling
`context.Custom(new CustomDrawOp(Bounds, Plot));`

Tested with: ScottPlot.Avalonia 5.0.8-beta
