### ISSUE TITLE
Issue trying to drag labels that have been rotated. The underlying hit_test code seems like it is at fault

### ISSUE THREAD

**Issue by DaveMartel** [ScottPlot/ScottPlot#2925]
## Bug Report

**Issue:** Trying to drag Text plottable when the text is rotated is not as expected. When I rotate a 4 line text label aligned bottom left by 45 degrees, and the try to click on it to drag nothing happens (well I pan the graph). I have to guess a location someway below and to the left of the rotated label to grab it. It seems the mouse down hit test may be using the rectangle for the text when not rotated.

**Reproducing:** 
The code below should be pasted in to something like a button click and suitable place on the WinForm to place the plot provided. After that it is somply a case of trying to pick up and drag the label...

```cs
            // a code sample. derived/modified from one of the ScottPlot demos
            ScottPlot.FormsPlot formsPlot1 = new ScottPlot.FormsPlot();
            var plt = formsPlot1.Plot;  
            tabPage3.Controls.Add(formsPlot1);    //This is simply used to add the form to a container in my test application. Pick anything you can on a WinForm form
            plt.Clear();

            // plot sample data: 4 data points
            double[] xs = { 0, 10, 50, 100 };
            double[] ys = { 1, 11, 51, 101 };

            plt.AddSignalXY(xs, ys);

            // These shortcuts are the easiest way to set axis labels
            plt.XLabel("Horizontal Axis");
            plt.YLabel("Vertical Axis");
            plt.Title("Axis Customization");

            // Axes labels can be further customized for any axis
            plt.YAxis.Label("Vertical Axis", Color.Magenta, size: 24, fontName: "Comic Sans MS");

            // This method will set the color of axis labels, lines, ticks, and tick labels
            plt.XAxis.Color(Color.Green);

            // Here is where we set up our rotated draggable label. 3 lines of text
            string Stats = "1111111111\r\n22222222\r\n33333333333333\r\n";

            // Place it in the middle of the graph, aligned to bottom right corner
            ScottPlot.Plottable.Text statsTxt = plt.AddText(Stats, 50, 50, 10, Color.Red);
            statsTxt.Alignment = Alignment.LowerRight;

            // Now rotate it 45 degrees, and enable dragging
            statsTxt.Rotation = 45;
            statsTxt.DragEnabled = true;

            // refresh the plot
            formsPlot1.Refresh();

            // Now interactively try to grab the label to drag it. You have to click somewhere in the region
            // of x=30, y=40, which is a long way from where the text is rendered

```

### System Details
* **ScottPlot Version:** 4.1.67?
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** (.NET 6.0?)

**Comment by DaveMartel** [comment]
![image](https://github.com/ScottPlot/ScottPlot/assets/24892075/447bc1a5-fb99-4e2b-92c1-ef17637314a2)

**Comment by swharden** [comment]
Hi @DaveMartel, thanks for reporting this! I really appreciate the extensive code example that allows users to reproduce this issue too.

There hasn't been movement on this issue for a while and I'm focusing pretty hard on ScottPlot 5 (#2984, #2706) so I'll probably leave this feature unsupported, but I welcome contributions if you or someone from the community gives figures out how to do better hit detection and shares the solution in the form of a pull request!

This blog post may be useful: https://swharden.com/blog/2022-02-01-point-in-rectangle/
