### ISSUE TITLE
SP4: Avalonia ClipToBounds

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2926]
A fix was made to ScottPlot 5 to improve rendering issues in multi-control windows #2920 

Should this fix also be applied to ScottPlot 4?

https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot4/ScottPlot.Avalonia/AvaPlot.axaml.cs

**Comment by oktrue** [comment]
@swharden no this fix is neccessary only for SP5 because of it's rendering mechanism (directly to control's SKCanvas).

**Comment by swharden** [comment]
Awesome, thanks for the quick feedback! I really appreciate your Avalonia insights 😄
