### ISSUE TITLE
Maui support?

### ISSUE THREAD

**Issue by HuaFangYun** [ScottPlot/ScottPlot#2930]
Is there any plan to support maui?

**Comment by swharden** [comment]
Hi @HuaFangYun, 

Indeed! However I don't intend to do this personally for at least the next several weeks. ScottPlot 5 has been designed with a control backend that makes it really easy to add support for new controls, so a Maui control should be pretty easy to get off the ground! I recommend looking at the WPF and WinUI plot controls as a reference, and if you or someone else from the open source community creates a Maui control I'd be happy to review a PR and include it in the next release!
