### ISSUE TITLE
SP5: GetLegendBitmap()

### ISSUE THREAD

**Issue by lichen95** [ScottPlot/ScottPlot#2934]
Can Legend support being placed outside the chart

**Comment by swharden** [comment]
Hi @lichen95, thanks for this suggestion! I'll leave this issue open to track progress toward adding a method like `GetLegendBitmap()` so users can retrieve an _image_ they can place outside the plot control and anywhere in their Window

**Comment by swharden** [comment]
Re-opening this issue because it seems `GetLegendImage()` and/or `GetLegendSvg()` are not memory safe, as they crash the `dotnet test` runner. Interestingly they do not crash tests run inside visual studio (unless they're run in debug mode).
