### ISSUE TITLE
SP5: add Text plot type

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2939]
similar to ScottPlot 4's https://scottplot.net/cookbook/4.1/#text

**Comment by Gray-lab** [comment]
@swharden I would love to give this a shot this weekend. I believe it requires a new `Plottables` class implementing `IPlottable`, possibly using the `Label` primitive to draw the text. After that I should be able to just add another method to `PlottableAdder` for adding the Text plot to the Plot. Does that sound right to you?

**Comment by Gray-lab** [comment]
@swharden That makes sense - thank you for the explanation! I will look at the Arrow and Marker plot types to see if I can implement one of those so I start getting familiar with more of the codebase.

**Comment by swharden** [comment]
If it helps, here's what a PR looks like that adds a new plot type: https://github.com/ScottPlot/ScottPlot/pull/3044

* Create the plot type
* Create a `Plot.Add.NewThing()` helper method
* Create a cookbook recipe page for the plot type

The cookbook recipes are a type of test, so unless the plottable does something really complicated I'm fine not added unit tests for now 👍

**Comment by swharden** [comment]
Oh yeah, a `Line` plot type which has a `Coordinates Start` and `Coordinates End` (and/or `x1`, `x2`, `y1`, and `y2`) would be nice to have (#2915) and is very similar to an `Arrow` plot type

**Comment by swharden** [comment]
... going through all the open issues and spotting more plot types that would be useful to have and shouldn't be too hard to get off the ground! There's also `Marker` which is like a scatter plot with a single point #2806

**Comment by Gray-lab** [comment]
I have been busy with finals, but am done now. Excited to start on these different plot types!
