### ISSUE TITLE
SP5: Strategy needed for plottables to render after axes are drawn

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2945]
An example use case is an axis line which has a label outside the plot area.

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/94af6888-bc2c-47e8-b6f0-765d5b3666c7)

One possible strategy is to have an opt-in interface that `IPlottable` objects can implement, something like `IRenderAfterAxes` or something.

Another strategy is to have `ILayeredRender` which has a numerical `int Layer`, then all objects implementing this interface are sorted at render time and rendered in order

**Comment by StendProg** [comment]
The first option is the easiest and most appropriate (in my opinion). Such Plottables will be rare and there is no sense to make a whole subsystem of layers for them.
