### ISSUE TITLE
SP5: Improve Signal line drawing

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2949]
Extend work started in #2935 to create code that draws lines more carefully and has features like edge interpolation. It can later be used by SignalXY plots too.

Here is relevant code from ScottPlot4:

https://github.com/ScottPlot/ScottPlot/blob/85e982e6f5a669dd897aad7c7f6d83b467efd828/src/ScottPlot4/ScottPlot/Plottable/SignalPlotXYGeneric.cs#L198-L227

EDIT: see https://github.com/ScottPlot/ScottPlot/pull/2935#issuecomment-1766873268 for more information

![SignalExample](https://github.com/ScottPlot/ScottPlot/assets/53831487/44e8d1ad-ff56-4d54-acde-469865392634)

**Comment by swharden** [comment]
Hi @StendProg, I'm continuing the discussion from #2935 here

> You failed to reproduce the effect I described earlier because the X ranges for the pixel columns overlap (which should not be the case) and the data points can be included in both columns.

I created some new methods to simplify creating square wave patterns to test and I updated the WinForms sandbox app to demonstrate the following:

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/9f234524-12bd-4e29-a28a-64d2f9dee0a4)

![step2](https://github.com/ScottPlot/ScottPlot/assets/4165489/19a32f60-0274-44ed-83cb-277ca8d4ddb0)

https://github.com/ScottPlot/ScottPlot/blob/4d772dae2644d575cd3a69a13a7a5b341667a9fe/src/ScottPlot5/ScottPlot5%20Sandbox/Sandbox.WinForms/Form1.cs#L5-L20

I don't observe any artifacts on my system - how can this code be modified to help me better understand the issue?

**Comment by StendProg** [comment]
I got your example and set noise level to 0.001:
```c#
    Generate.AddNoiseInPlace(noisy, 0.001);
```
![image](https://github.com/ScottPlot/ScottPlot/assets/53831487/ba295fdd-0c3a-4606-b974-282eb3b0b795)


In this code, the indices of the data points are obtained by rounding. And one and the same data point will fall into neighboring Pixel columns, maybe it is so intended, but it seems incorrect to me:
https://github.com/ScottPlot/ScottPlot/blob/4d772dae2644d575cd3a69a13a7a5b341667a9fe/src/ScottPlot5/ScottPlot5/DataSources/SignalSource.cs#L19-L49

**Comment by swharden** [comment]
Thanks for the feedback @StendProg! 

## Rendering

I think #2955 solved the rendering issue using this repeating strategy:
* draw a diagonal line between the previous column's last Y and this column's first Y
* draw a vertical line from this column's bottom to its top

This strategy seems to work for my test cases, but let me know if you are aware of issues that persist.

https://github.com/ScottPlot/ScottPlot/blob/a14b29e91f0ce5539dd4ebf947b926a9c4fc155c/src/ScottPlot5/ScottPlot5/Plottables/Signal.cs#L117-L128

## Rounding

> the indices of the data points are obtained by rounding. And one and the same data point will fall into neighboring Pixel columns

Thank you for noting this! I'll re-open this issue and address it with a follow-up PR 👍

**Comment by minjjKang** [comment]
Hello.

in RenderHighDensity after this changes, 
Noise occurs in the signal when YOffset is setted.
This noise is seen in the position before the YOffset is changed.

It seems SignalSource.GetPixelColumn does not refer YOffset..
https://github.com/ScottPlot/ScottPlot/blob/c7ce83274728f35977dc7d4c55aadc56ed8ee997/src/ScottPlot5/ScottPlot5/DataSources/SignalSource.cs#L77-L84

I solved this by modifying as follows.
```
float yEnter = axes.GetPixelY(Ys[i1] + YOffset);
float yExit = axes.GetPixelY(Ys[i2] + YOffset);
```
