### ISSUE TITLE
SP4: Axis.ManualTicks(Tick[] ticks)

### ISSUE THREAD

**Issue by FannyAtGitHub** [ScottPlot/ScottPlot#2957]
## Feature Suggestion

**Feature description:** 
The concept of major and minor ticks is great and the concept of manual tick positions is very much appreciated as well. So why not putting them together?

I mainly work with logarithmic plots. I need to use manual tick positions especially when zooming in - as there are no automatic ticks provided any more when the data range is 'too small'. (I skip adding an example plot with no ticks on the axis.)
Manual major ticks and labels work very well for these small range logarithmic plots.

If I understand correctly, in order to add minor ticks the only option right now would be to add more major manual ticks but with empty labels. The result is not great as the major and 'minor' ticks have an identical look and the grid lines are of the same color. So the lines are not easily distinguishable.
![image](https://github.com/ScottPlot/ScottPlot/assets/126788297/f810cd9c-60e8-4d63-b08f-50c92123ee51)
(Note: Just to clarify as this has been a subject to discussions before. This is a logarithmic plot. One might expect the minor grid lines need to be distributed in 'a more logarithmic way' but this is not the case. The space between minor ticks just gradually shrinks over the range of one full magnitude. Here, a range a lot smaller than a magnitude is plotted.)

Right now there is only major ticks (with labels) in my plots and minor ticks are just missing. With this the axis is a little empty. Particularly in logarithmic plots minor grid lines would be a wonderful orientation helper.

This is an example where I think minor ticks would help the viewer a whole lot when viewing the data:
![image](https://github.com/ScottPlot/ScottPlot/assets/126788297/bb866428-b27b-4e68-9d29-40ea71d5cefd)

So please add this feature!

**Code example:** 
I suggest a similar way as adding manual major tick positions.
Example:
```cs
_plot.YAxis.ManualTickPositions(majorTicks, majorTickLabels);
_plot.YAxis.ManualMinorTickPositions(minorTicks);
```

**Comment by swharden** [comment]
Hi @FannyAtGitHub, thanks for this suggestion!

It would be great if the user could construct a collection of `Tick` objects (defining which are major, minor, labels, etc) and then pass them in. I'm thinking the API could look like this to compliment the existing `GetTicks()` method:

```cs
Tick[] ticks = /* your logic here */

formsPlot1.Plot.YAxis.SetTicks(ticks);
```

If you or someone else want to try to implement this and create a PR, I'd be happy to review it! Otherwise this issue may sit here for a little while until I'm able to get to it myself.

I think the way I'd approach it is to edit `TickGenerator.cs` and add a `Tick[]? manualTicks { get; set; } = null;` which can be set, and if the user sets it the returned ticks will always be those manual ones and not the ones generated by the major or minor tick generators

**Comment by swharden** [comment]
I'm merging #3047 now and will publish an updated NuGet package later today. It will allow this:

```cs
ScottPlot.Plot plt = new(400, 300);
plt.AddSignal(DataGen.Sin(51));
plt.AddSignal(DataGen.Cos(51));

// use a helper class to build a colelction of major and minor ticks
ScottPlot.Ticks.ManualTickCollection tc = new();
tc.AddMajor(0, "zero");
tc.AddMajor(20, "twenty");
tc.AddMajor(50, "fifty");
tc.AddMinor(22);
tc.AddMinor(25);
tc.AddMinor(32);
tc.AddMinor(35);
tc.AddMinor(42);
tc.AddMinor(45);

// get the tick array and apply it to the axis
ScottPlot.Ticks.Tick[] ticks = tc.GetTicks();
plt.BottomAxis.SetTicks(ticks);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/dc9a9b60-be95-4ab0-97e8-bc13076eff80)

Thanks again for your question @FannyAtGitHub! Although users will have to add logic that calls `Plot.GetAxisLimits()` and figures out how many ticks and where to place them, at least now there's a smooth way to manually define major and minor ticks 🚀
