### ISSUE TITLE
How to set the colours for the PopulationMultiSeries boxes and scatter points.

### ISSUE THREAD

**Issue by Em3a-c** [ScottPlot/ScottPlot#2967]
**ScottPlot Version:** ScottPlot.WPF 4.1.67

**Operating System:** Windows

**Application Type:** WPF

**Question:** 
Hi,

Me and the team I work with, have recently started using ScottPlot in the software that we write, and it's amazing how quick and easy it is to get a plot rendering, using your library.

There's a slight limitation I've noticed, when using the PopulationMultiSeries, where it appears that we ignore the alpha channel of the colours passed in, when we draw the boxes, I think we preserve transparency for the scatter points, (that we can optionally draw).

Following a strict colour palette is quite important for our software, is there any way with the current library, to set the colours of the boxes and the points, to a collection of colours that we'd like to use, where these colours may/may not contain transparency?

I've provided a small snippet of code, showing how I am creating the PopulationMultiSeries, and a screenshot of the rendered plot.
Ideally, we'd like to control the colours of the boxes and the points, but I am unsure if this can be done?

Thanks for your help,

Emma

```cs
public void CreatePopulationMultiSeries(WpfPlot plot)
{
   plot.Plot.Title("Plot title");
   plot.Plot.Legend();

   var seriesColours = new Color[] { Color.FromArgb(100, 255, 0, 0), Color.Blue, Color.Green };
   var groupNames = new[] { "Group A", "Group B", "Group C" };
   var seriesData = new[]
   {
       new[]
       {
           new []{1.0, 2.0, 3.0},
           new []{2.0, 3.0, 4.0},
           new []{5.0, 6.0, 7.0}
       },
       new[]
       {
           new []{8.0, 9.0, 10.0},
           new []{11.0, 12.0, 13.0},
           new []{14.0, 15.0, 16.0}
       }
   };

   // Setup the X axis ticks
   plot.Plot.XTicks(groupNames);

   var populations = seriesData.Select(series => series.Select(seriesData => new Population(seriesData)).ToArray()).ToArray();
   var populationSeries = populations.Select((p, i) => new PopulationSeries(p, seriesLabel: $"Series {i}")).ToArray();
   var populationMultiSeries = new PopulationMultiSeries(populationSeries.ToArray());

   var populationPlot = plot.Plot.AddPopulations(populationMultiSeries);
  
   // Set the colours
   for (var i = 0; i < populationPlot.MultiSeries.seriesCount; i++)
   {
       populationPlot.MultiSeries.multiSeries[i].color = seriesColours[i];
   }

   plot.Refresh();
}
```

```xml
<WpfPlot x:Name="PlotName"  />
```

Screenshot for the above code:
![image](https://github.com/ScottPlot/ScottPlot/assets/60915240/c114ecba-4edb-4288-ac66-27c1c1b092ed)

**Comment by swharden** [comment]
Hi @Em3a-c, thanks for reporting this!

I narrowed down the issue to this one line of code, where the alpha value `128` is always applied:
https://github.com/ScottPlot/ScottPlot/blob/16eec73098cb932332a42b19d18a3ab1cccd14a2/src/ScottPlot4/ScottPlot/Plottable/PopulationPlot.cs#L186

A good solution here would be to modify this class to create something like:
```cs
public byte MarkerAlpha { get; set; } = 128; // semitransparent by default
```

Then the user could reach in and set its alpha to opaque if they want to define the exact color of the markers:
```cs
var populationPlot = plot.Plot.AddPopulations(populationMultiSeries);
populationPlot.MarkerAlpha = 255; // opaque
```

I'll leave this issue open for a few days in case you or someone from the open source community wants to make this change and create a pull request. If there's no movement for a while, I'll make this change myself right before the next release.

Thanks again for the suggestion! 👍

**Comment by Gray-lab** [comment]
@swharden I am looking at this one right now and I think adding `MarkerAlpha` only covers half the the issue that @Em3a-c brought up.  It would be good to also be able to override the alpha of the boxes.

Currently `boxAlpha` is set based on the `DataFormat` field in the switch statement on line 156:
https://github.com/ScottPlot/ScottPlot/blob/16eec73098cb932332a42b19d18a3ab1cccd14a2/src/ScottPlot4/ScottPlot/Plottable/PopulationPlot.cs#L155-L167
I think doing something like this might allow for `boxAlpha` to be overridden while maintaining the `DataFormat` logic:
``` c#
public byte? BoxAlphaOverride { get; set; } = null;
```
And then later, after the switch statement:
``` c#
// Overide boxAlpha with public field BoxAlphaOverride if the field has been set
if (BoxAlphaOverride.HasValue)
    boxAlpha = BoxAlphaOverride.Value;
```
The downside is that if the box alpha is overriden then `DataFormat` might not work as expected, since it uses the alpha to hide the boxes in the case `DisplayItems.ScatterOnly`. What do you think - is that an acceptable tradeoff?

Another approach might be to instead directly use the alpha values from the series color, but I am not sure how to reconcile that with the default values or with the `DataFormat` logic.

**Comment by swharden** [comment]
> I think doing something like this might allow for boxAlpha to be overridden while maintaining the DataFormat logic

Hi @Gray-lab, I like the use of the nullable byte there as a way to opt-in to a custom alpha! I agree with you that sampling the alpha value from the series color is a bit confusing.

Overall I'm happy with pretty much any solution here as long as the public properties have XML docs that make it clear how they work, and as long as these changes don't modify the existing/default behavior.

Thanks for looking into this!

**Comment by swharden** [comment]
Hi @Em3a-c and @Gray-lab, this has been solved in #3013 so in the next release you can do something like this:

```cs
populationPlot.BoxAlphaOverride = 150;
populationPlot.MarkerAlpha = 75;
```

Setting either value to `255` will cause boxes or markers to render the exact color that was passed in

I think this solves the original goal, but if not let me know and we can take another look!

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/f06f5422-0040-4729-8abd-ad7b5d5f52f9)

**Comment by Gray-lab** [comment]
@Em3a-c thanks for the further detail. You are right, the current implementation does not support the use case you demonstrate. If @swharden is open to adding this functionality I think we could do what you suggest and add Boolean overrides to enable using the whole argb color. My feeling is that if we do this, we would get rid of the MarkerAlpha and BoxAlphaOverride fields, as there isn't a great reason to have two ways of doing the same thing.

**Comment by swharden** [comment]
Hi @Gray-lab, thanks for the additional information and implementation suggestion - I like it! Maybe something like

```cs
public bool AutomaticOpacity { get; set; } = true;
```

If disabled, the opacity of the bars and markers is exactly that of the `Color` passed in

Technically there's one use case that isn't covered with this strategy though ... What if users want different opacities for the bars and markers 😅

To solve that use case technically we could add something like this:

```cs
public double MarkerOpacity { get; set; } = 0.5;
```

Then the markers are always that fraction of transparency relative to the `Color` of their bar, even if there bar has some transparency built in...

There are lots of possible ways to work toward a solution here. If you want to try something out and create a pull request, I'd be happy to take a look!

**Comment by swharden** [comment]
Hi @Em3a-c, after merging #3018 this image can be created with the following code:

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/0722d793-cf0f-45eb-bd92-da95a764ce2f)

Do you think this adequately resolves this issue? If so, the new feature will be in the next release!

```cs
// Define population data (3 groups, 2 series per group)
double[][][] seriesData = new[] {
    new[] { new []{1.0, 2.0, 3.0}, new []{2.0, 3.0, 4.0}, new []{5.0, 6.0, 7.0} },
    new[] { new []{8.0, 9.0, 10.0}, new []{11.0, 12.0, 13.0}, new []{14.0, 15.0, 16.0} }
};

// Build the population plot and add it to the graph
Statistics.Population[][] populations = seriesData.Select(series => series.Select(seriesData => new Statistics.Population(seriesData)).ToArray()).ToArray();
Statistics.PopulationSeries[] populationSeries = populations.Select((p, i) => new Statistics.PopulationSeries(p, seriesLabel: $"Series {i}")).ToArray();
Statistics.PopulationMultiSeries populationMultiSeries = new(populationSeries.ToArray());
var populationPlot = plt.AddPopulations(populationMultiSeries);

// Add group and series labels
plt.XTicks(new string[] { "Group A", "Group B", "Group C" });
plt.Legend();

// Define specific colors for each group
populationSeries[0].color = Color.FromArgb(alpha: 100, red: 255, green: 0, blue: 0);
populationSeries[1].color = Color.FromArgb(alpha: 255, red: 0, green: 0, blue: 255);

// Manually define transparency for boxes and markers - alpha values will now be set using the series colors
populationPlot.AutomaticOpacity = false;

// Make scatter markers 75% as opaque as box plots
populationPlot.MarkerOpacityRatio = 0.75;
```

**Comment by Em3a-c** [comment]
Hi @swharden & @Gray-lab,

Yes, this issue is now resolved, and works perfectly for the test case I raised.

Thanks so much for looking at and fixing this issue up,

It's much appreciated! 👍
