### ISSUE TITLE
SP4 ScatterPlotDraggable: Bug after `Update()`

### ISSUE THREAD

**Issue by SasKayDE** [ScottPlot/ScottPlot#2969]
## Bug Report

**Issue:**
After updating the X and Y values of a ScatterPlotDraggable object programmatically by calling the Update(Xnew, Ynew) and Refresh(), the plot is visualized correctly, considering the updated Xnew and Ynew values, but the draggable point coordinates are not updated and remain at the previous positions Xold, Yold, indicated by the DragCursor still appearing at the positions Xold, Yold.

**Reproducing:**

Correct/expected behavior after initialization:

```cs
// Initialization with initial dataX, dataY
myScatterPlotDraggable = new ScatterPlotDraggable( dataX, dataY ) { DragEnabled = true, DragCursor = ScottPlot.Cursor.Hand };
myFormsPlot.Plot.Add( myScatterPlotDraggable );
myFormsPlot.Refresh();
```

Change of the X and Y data programmatically results in the described/unexpected behavior:

```cs
// change of X and Y values (keeping the array sizes)
myScatterPlotDraggable.Update( Xnew, Ynew );
myFormsPlot.Refresh();
```

While debugging it has been observed that the changed values (in this example Ys[1]) are not updated consistently in the attributes "Ys (ScottPlot.Plottable.ScatterPlot)" and "Ys" of the myScatterPlotDraggable object after calling myScatterPlotDraggable.Update( Xnew, Ynew );

![image](https://github.com/ScottPlot/ScottPlot/assets/16592829/e268cb59-c211-4723-b2ed-2c993f174424)

The result is a plotted point at 1800 (Ynew[1]) and a draggable point at 1024 (Yold[1]).

### System Details
* **ScottPlot Version:** 4.1.68
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** .NET 6.0

**Comment by SasKayDE** [comment]
Same root cause, different observation:
When increasing the array size of Xnew and Ynew and calling myScatterPlotDraggable.Update() an exception is thrown when the ScatterPlotDraggable tries to refresh/render the plot because only Xs and Ys of the base class is updated, but not Xs andYs of the ScatterPlotDraggable class. The following snapshot shows the myScatterPlotDraggable object after calling myScatterPlotDraggable.Update() with the Xnew and Ynew array increased from 5 to 6 elements:

![image](https://github.com/ScottPlot/ScottPlot/assets/16592829/b7f5060f-fc64-4a53-a015-92733d855c00)

**Comment by swharden** [comment]
Thanks for reporting this @SasKayDE, I'll look into it more closely before the next ScottPlot 4 release

Note that the issue may also be causing the problem described by #2870
