### ISSUE TITLE
SP5: Improve support for DateTime ticks on vertical axes

### ISSUE THREAD

**Issue by sunwayking** [ScottPlot/ScottPlot#2970]
## Feature Suggestion

1. Vertical DateTimeAxis is needed
2.  AxisBase.DrawTicksVerticalAxis is programmed to draw single line of text. Usually, like AxisBase.DrawTicksHorizontalAxis well dealing with multiple lines of text, it's very important to be supported for vertical axis.
3. Because Heatmap use a relative coordinate system in fact, it's not support DateTimeAxis. Maybe better to redesign data interface and coordinate system for Heatmap.

**Comment by swharden** [comment]
Hi @sunwayking, thanks for reporting these issues! I'll convert this issue to one that specifically improves support for ticks on vertical axes, including DateTime ticks and improved multi-line tick label spacing.

Regarding the heatmap, I intend to significantly rework the ScottPlot 5 heatmap API, and will definitely aim to make it easier to use in combination with DateTime ticks.

Thanks again for your suggestions. I'll follow-up here when more progress is made!

**Comment by swharden** [comment]
Following-up, 

> Vertical DateTimeAxis is needed

This works:

```cs
formsPlot1.Plot.LeftAxis.TickGenerator = new ScottPlot.TickGenerators.DateTimeAutomatic();
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/cf9a7303-b5be-4a99-b1d5-4009e0ebd202)

> dealing with multiple lines of text

I think the custom tick label formatter can be used to customize things like like breaking

> Heatmap use a relative coordinate system

Heatmaps will be largely refactored soon, but I'll keep in mind it's important to support DateTime axes

**Comment by bukowa** [comment]
I can't access `LeftAxis` via `formsPlot1.Plot`
