### ISSUE TITLE
ScottPlot5 NET Framework 4.6.2

### ISSUE THREAD

**Issue by yizushijie** [ScottPlot/ScottPlot#2971]
**I** want to use ScottPlot5 for signal waveform display, but I found that it does not work under NET Framework 4.6.2; Whether I drag and drop controls or generate controls, he always reports an error. Does ScottPlot5 currently not support the NET Framework 4.6.2 environment; I work normally under NET7.0 with the same configuration; Compiled class library, check Support for NET Framework 4.6.2. What should I do? ScottPlot5 can work in the NET Framework 4.6.2 environment,
![image](https://github.com/ScottPlot/ScottPlot/assets/8426253/943461bd-6a3a-430f-ac7b-7d47544727c4)

**Comment by swharden** [comment]
Hi @yizushijie, thanks for reporting this!

I googled for `system.runtime.interopservices.comexception 0x80004005` and found some interesting pages reporting a similar error

* https://github.com/MicrosoftEdge/WebView2Feedback/issues/978
* https://learn.microsoft.com/en-us/answers/questions/433127/my-program-works-correctly-within-the-visual-studi
* https://community.esri.com/t5/water-resources-questions/i-am-having-this-error-while-using-arch-hydro-and/td-p/672997

I think the solution may be to ensure you are using the latest version of Visual Studio! Note that Visual Studio 2023 community is free for small projects and open source developers.
