### ISSUE TITLE
SP4: DataLogger should support `LineStyle`

### ISSUE THREAD

**Issue by vf19961226** [ScottPlot/ScottPlot#2972]
## Bug Report

**Issue:** LineStyle doesn't work on DataLogger. I change the line style to another, but the plot still has shown "solid" style and the legend has changed to the line style I selected. As shown below. 

![image](https://github.com/ScottPlot/ScottPlot/assets/77768660/5228579a-2b72-40df-bf3f-3f612143cd7c)

**Reproducing:** The C# code is as follows.

```cs
ScottPlot.Plottable.DataLogger line = formsPlot1.Plot.AddDataLogger(color: Color.Red, lineWidth: 1, label: "Line1");
line.Add(1, 100);
line.Add(2, 200);
line.MarkerSize = 5;
line.LineStyle = ScottPlot.LineStyle.Dot;
formsPlot1.Plot.Legend();

formsPlot1.Refresh();
```

### System Details
* **ScottPlot Version:** 4.1.68
* **Operating System:** Windows 10 Professional
* **Application Type:** Winforms
* **.NET Version:** .NET Framework 4.6.2

**Comment by swharden** [comment]
Thanks for reporting this @vf19961226!

I recommend taking a look at how some of the other plot types support custom line styles when the `Pen` is created, like the `AxisLine` code:

https://github.com/ScottPlot/ScottPlot/blob/16eec73098cb932332a42b19d18a3ab1cccd14a2/src/ScottPlot4/ScottPlot/Plottable/AxisLine.cs#L163

The `DataLogger` could be modified to use this same strategy here:
https://github.com/ScottPlot/ScottPlot/blob/16eec73098cb932332a42b19d18a3ab1cccd14a2/src/ScottPlot4/ScottPlot/Plottable/DataLogger.cs#L200

It looks like `LineStyle.Solid` is always passed by accident!

I'll leave this open for a few days in case you or someone else wants to create a pull request to fix this issue. If there's no movement for a while, I'll fix it myself before the next release. Thanks again for reporting this!

**Comment by Gray-lab** [comment]
@swharden @vf19961226 If no one else wants to grab this one I am happy to make the change and try to add a test for it too.

**Comment by swharden** [comment]
Hi @Gray-lab, that would be awesome! Things don't move too fast around here so the issues marked "good first issue" are pretty much first-come-first-serve, so go for it and if you have any questions let me know!

**Comment by Gray-lab** [comment]
@swharden Great, thank you!
