### ISSUE TITLE
Avalonia display exception in Linux

### ISSUE THREAD

**Issue by zichen-ye** [ScottPlot/ScottPlot#2977]
![image](https://github.com/ScottPlot/ScottPlot/assets/71861331/289bf037-bcca-4ee0-86d8-47e3fd02c57d)

```csharp
myPlot.XAxis.Label.Text = "Horizontal Axis";
myPlot.YAxis.Label.Text = "Vertical Axis";
myPlot.TitlePanel.Label.Text = "Plot Title";
```

The above code is invalid in ScottPlot.Avalonia.(Linux)

**Comment by swharden** [comment]
Hi @zichen-ye, unfortunately I think this issue is incomplete.

What is the exception message?

Can you provide the full code for your avalonia source code file? https://scottplot.net/faq/repro/

I'm happy to re-open this issue if there is a little more information about what the problem is 👍
