### ISSUE TITLE
SP4 DataStreamer: Add support for step display

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#2982]
The DataStreamer plot type displays live data as described on https://scottplot.net/faq/live-data/

The DataStreamer's render method connects points with straight lines:
https://github.com/ScottPlot/ScottPlot/blob/c7ce83274728f35977dc7d4c55aadc56ed8ee997/src/ScottPlot4/ScottPlot/Plottable/DataStreamerViews/Wipe.cs#L48-L52

It could be possible to add a `bool StepMode` property to `IDataStreamerView`, and add conditional logic to draw data points using steps instead of straight lines. Logic could be copied from the `ScatterPlot` class which does that here:

https://github.com/ScottPlot/ScottPlot/blob/c7ce83274728f35977dc7d4c55aadc56ed8ee997/src/ScottPlot4/ScottPlot/Plottable/ScatterPlot.cs#L463-L475

### Discussed in https://github.com/ScottPlot/ScottPlot/discussions/2980

<div type='discussions-op-text'>

<sup>Originally posted by **yusp75** November 19, 2023</sup>
I use scottplot in c# winforms, and I use the Dataterstreamer plot.
I want to show 0 or 1 value as stepline jus like this.
But how to do with this?
![stepline](https://github.com/ScottPlot/ScottPlot/assets/19420083/3653da82-f995-4dd3-ab16-813484263db7)

</div>

**Comment by swharden** [comment]
Due to my recent focus on ScottPlot 5 (#2984, #2706) it's unlikely I'll get to this myself, but the information above should be helpful for anyone interested in implementing this themselves. I would be happy to review a pull request if somebody achieves this functionality! 👍

**Comment by yusp75** [comment]
In my case, I copy the source to project,  and hack the Render function of Scroll.cs(D:\Users\y\source\repos\MyPlc2\ScottPlot\Plottable\DataStreamerViews\Scroll.cs), like this:

` //if (points.Length > 1)
  //    gfx.DrawLines(pen, points);
  //step line 2023.11.21
  if (points.Length > 1)
  {
      if (StepDisplay)
      {
          PointF[] pointsStep = GetStepDisplayPoints(points, true);
          gfx.DrawLines(pen, pointsStep);
      }
      else
      {
          gfx.DrawLines(pen, points);
      }
  }` 
![stepline](https://github.com/ScottPlot/ScottPlot/assets/19420083/308d09d2-080c-4da3-9627-fe21f16aaa35)

**Comment by swharden** [comment]
Thanks for following-up @yusp75! Your solution is fantastic - to achieve a step display you can edit the data streamer view classes and replace this code:
https://github.com/ScottPlot/ScottPlot/blob/c7ce83274728f35977dc7d4c55aadc56ed8ee997/src/ScottPlot4/ScottPlot/Plottable/DataStreamerViews/Scroll.cs#L36-L37

With this code:
```cs
if (points.Length > 1)
{
    if (StepDisplay)
    {
        PointF[] pointsStep = GetStepDisplayPoints(points, true);
        gfx.DrawLines(pen, pointsStep);
    }
    else
    {
        gfx.DrawLines(pen, points);
    }
}
```
