### ISSUE TITLE
SP4 Plottable.Text: `LastRenderRectangleCoordinates` should be public

### ISSUE THREAD

**Issue by DaveMartel** [ScottPlot/ScottPlot#2994]
## Bug? Report

Issue: ScottPlot4 Plottable.Text LastRenderRectangleCoordinates scoping not declared (i.e. not private, protected or public). It is the only tying in the whole class that is not, and this looks like an oversight.

It would be **really** useful if it could be made at least protected so that anyone overriding the Rendering can update it. Without being able to update those coordinates, IsUnderMouse() will not return correct values.

### System Details
* **ScottPlot Version:** 4.1.68
* **Operating System:** Windows 10 
* **Application Type:** (WinForms)
* **.NET Version:** (.NET 6.0?)

**Comment by swharden** [comment]
Hi @DaveMartel

The code in question is here:
https://github.com/ScottPlot/ScottPlot/blob/1883934d2973b65bc394955e36381c76e66176a5/src/ScottPlot4/ScottPlot/Plottable/Text.cs#L35

If you want to create a PR that makes this property public, I'd be happy to merge it in before the next release!

**Comment by DaveMartel** [comment]
Scott,

Thanks. I may not get to it today, as I have not yet fully got my head around getting the source code in a format that I can go through this with. I am just using the package pulled through Nuget, although I also pulled the source code to be able to look through stuff. Sad to say I have never even created a  PullRequest as our workflow at work is somewhat different. Just 2 main developers, working on their own projects, so despite having all the power of git we tend to only work on our own repos and most just use push and pull from BitBucket.

I will try and get this done soon though.

**Comment by swharden** [comment]
Hi @DaveMartel, no worries! Take as long as you need to look into it, and if you have any questions let me know and I'm happy to help. If you get stuck or decide you don't want to fuss with the pull request, let me know and I can resolve this issue myself before the next release 👍

**Comment by DaveMartel** [comment]
@swharden I would like to get this working, as I think it would be useful for me, and hopefully some of the other additions I am making could be useful going forward.

I am struggling to get this working. I have cloned the repo, created a branch "2994" and made the change. I have committed it locally (I mostly use Tortoise git). TortoiseGit docs indicate that at this point that I should be pushing pack and then issuing a pull request. However I can't get the push to work.

![image](https://github.com/ScottPlot/ScottPlot/assets/24892075/52fdf6c0-e832-42e6-95c8-ed84cd8abcb5)


I am wondering whether I should really be doing this exclusively using the GitHub tools, but that seems a bit against the spirit of git

I am also wondering if it is an account issue. My Github account uses a personal email address. The computer I cloned the repo from is set up for work and uses a different account. So perhaps this account can not push back.

**Comment by swharden** [comment]
Hi @DaveMartel, it looks like you're pretty close!

It sounds like you cloned the repo locally, but it's unclear whether your cloned repo is on GitHub. If you create your own ScottPlot fork on GitHub, you should have push access to your fork, then after your changes appear online you can create a pull request using the GitHub web interface

> I am wondering whether I should really be doing this exclusively using the GitHub tools, but that seems a bit against the spirit of git

I understand the feeling! Concepts like branching, committing, and pushing are core git concepts and it makes sense to use the git tools you're comfortable with to achieve that. However, _pull requests_ are an online activity that lets one user recommend changes in another user's repository, and pull requests are a GitHub concept (not part of git), so using some GitHub tooling to make that happen makes sense.

I recognize the process is pretty confusing for newcomers, but once you go through the process once it starts to feel less intimidating. I hope this helps!

**Comment by DaveMartel** [comment]
OK. I forked in GitHub, Cloned that down to my local machine created "2994" branch, made the one word change. Tested. Have now pushed it successfully back to GitHub (using TortoiseGit). GitHub spotted the push, and gave me the Pull request option. That is now in progress, doing its automated checks. Linux has passed and Windows is under way.

Well there is something new for me for the end of my working day... :-)

**Comment by DaveMartel** [comment]
Now I just need to set myself up so that I can actually use my working repo for building the main project (rather than the NuGet one), although I will do some more thinking first.

I am actually quite please with the draggable items I have added. Have also added an IHighlightable interface, and I am using that to give more obvious feedback on what items have been selected (e.g. so I can delete polygons I add to heatmaps using the "Delete key". I am also able to move things around using cursor keys once selected. Drag handles to allow re-sizing of the rectangle, by edge, or corner... dragging polygon vertex, etc.  This is all in order to allow me to classify features and set up for multi-image cross-sections through materials.

**Comment by swharden** [comment]
Hi @DaveMartel, I'm happy to see you got it all worked out! The pull request #2997 looks great and merged successfully 🚀 

It sounds like you're getting a lot of good use out of ScottPlot! Our Discord community is pretty active #1966 so you may benefit from popping in there to see what other developers are using ScottPlot for, or to ask questions in an environment where people may be able to answer them before I can.

Either way, it sounds like you're making great progress. Thanks again for the pull request, and feel free to reach out if you have any further questions or ideas for improvements!

Scott

**Comment by DaveMartel** [comment]
@swharden I have been asking quite a few things in discord over the last few days... :-)

**Comment by swharden** [comment]
Glad to hear you found the Discord! I was sick much of the last month and I'm still behind on emails and discord messages, but I'll be there a little more often over the next few weeks
