### ISSUE TITLE
SP4/SP5: Add a pre-render event that emits plot dimensions

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3077]
Add an event inside the render loop that gets evoked just before items are rendered. It should emit a `PlotDimensions` so users could inject custom code to modify plot objects based on the size and scale of the plot.

An example use case is text whose font size changes based on the zoom level.

This features should be added to ScottPlot 4 and ScottPlot 5.

Thanks GooBad from the Discord #1966 for this idea

GooBad's example:
![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/b432bab1-5029-47bf-91f9-b110ec46b70c)

**Comment by swharden** [comment]
Done! This will be possible in the next release

![scaling-text](https://github.com/ScottPlot/ScottPlot/assets/4165489/cd148a41-bdd0-4074-ac69-6d33f90a6fc5)

```cs
public partial class Form1 : Form
{
    List<ScottPlot.Plottables.Text> TextPlots = new();

    public Form1()
    {
        InitializeComponent();

        for (int x = 0; x < 50; x += 1)
        {
            string text = ((char)('A' + (x % 26))).ToString();
            Coordinates location = new(x, Math.Sin(x / 20.0));
            var tp = formsPlot1.Plot.Add.Text(text, location);
            TextPlots.Add(tp);
        }

        formsPlot1.Plot.RenderManager.RenderStarting += (object? s, RenderPack rp) =>
        {
            AxisLimits limits = rp.Plot.GetAxisLimits();
            double pxPerUnitX = rp.DataRect.Width / limits.HorizontalSpan;
            double pxPerUnitY = rp.DataRect.Height / limits.VerticalSpan;
            float pxPerUnit = (float)Math.Min(pxPerUnitX, pxPerUnitY);

            foreach (var textPlot in TextPlots)
            {
                textPlot.Label.FontSize = pxPerUnit;
            }
        };
    }
}
```

**Comment by bukowa** [comment]
That looks great!
