### ISSUE TITLE
SP5 Label: Add support for multi-line strings

### ISSUE THREAD

**Issue by raburton** [ScottPlot/ScottPlot#3087]
## Bug Report

**Issue:** Ticks labels can't handle \n char

**Reproducing:** Include a \n char in a tick label. With v4 you got a two line label, in v5 you get tofu instead of the new line. Sorry if this doesn't count a as a bug, not sure what's supposed to work in v5 vs v4. If not a bug, please accept as enhancement request.

```cs
private string[] yLabels = new string[] { "Line1\nLine2" };
private double[] yLabelPos = new double[] { 0 };

signalPlot.LeftAxis.TickGenerator = new ScottPlot.TickGenerators.NumericManual(yLabelPos, yLabels);
```

### System Details
* **ScottPlot Version:** 5.0.10-beta
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** .NET 8.0

**Comment by swharden** [comment]
Hi @raburton, thanks for reporting this!

I'm remembering that SkiaSharp can't draw multi-line text, so I'll have to write the code to break multiple lines into multiple labels and draw them individually 😱 

Related is this post I made a while back: https://swharden.com/csdv/skiasharp/drawtext-rectangle/

I'll refactor this issue to track progress toward improving multiline support for ScottPlot's `Label` class which should fix this issue 👍

**Comment by swharden** [comment]
Hi @raburton, thanks for reporting this! There's a lot of improvement that still could be made to how text is managed in ScottPlot, but for now basic multiline support has been added 👍
