### ISSUE TITLE
VerticalLine has a marker that cant be hidden

### ISSUE THREAD

**Issue by raburton** [ScottPlot/ScottPlot#3091]
## Bug Report

**Issue:** VerticalLine has a marker that can't be hidden, which sits just below the x axis.

**Reproducing:** See code.

```cs
plot.Add.VerticalLine(0, 1, Colors.Red);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/433543/216fb218-3c67-45b4-8980-9bff99f326cf)

### System Details
* **ScottPlot Version:** 5.0.10-beta
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** .NET 8.0

**Comment by swharden** [comment]
Thanks for reporting this @raburton! It has been fixed in ab54249604ec0ee0e222f1fadcadfcaa94821030 and will be in the next release 🚀
