### ISSUE TITLE
Grouped Bar Plot documentation sample code doesn't work

### ISSUE THREAD

**Issue by raburton** [ScottPlot/ScottPlot#3092]
## Bug Report

The documentation here for Grouped Bar Plot just doesn't work: https://scottplot.net/cookbook/5.0/Bar/GroupedBarPlot/

There is no ScottPlot.Bar class, or Plot.Add.Bars method.

**Comment by swharden** [comment]
Hi @raburton, I suspect you are reading documentation for ScottPlot 5 but trying to interact with the ScottPlot 4 package which has a slightly different API.

Here are the docs you're likely looking for: https://scottplot.net/cookbook/4.1/#plottable-bar-graph

**Comment by raburton** [comment]
No, I'm really using v5 and the sample code doesn't compile.

![image](https://github.com/ScottPlot/ScottPlot/assets/433543/7afea0d9-3f5f-4b5f-938b-75cf2487f9df)

**Comment by swharden** [comment]
Hi @raburton, I need a little more information to be able to help you out.

Are you running ScottPlot from NuGet, or from the source code on this GitHub repo? What version of ScottPlot are you using? 

Documentation on https://scottplot.net/cookbook/5.0/Bar/ describes the API for `ScottPlot 5.0.10-beta` on NuGet, and other versions may have a different API.

**Comment by swharden** [comment]
Following-up, I'm about to push some changes to the ScottPlot 5 website to fix sitemap issues (#3119) but as a result the new cookbook recipes online will definitely no longer agree with the package on NuGet. 

Consistent with the warning message on top of all the documentation pages, the ScottPlot 5.0 package is still a pre-release and its API is not stable, but you can refer to the source code of the cookbook recipes in this repository which should always be consistent with the features of ScottPlot available from source in this repository.

**Comment by raburton** [comment]
That screenshot with the compile errors is using 5.0.10 beta nuget package.

**Comment by raburton** [comment]
> Documentation on https://scottplot.net/cookbook/5.0/Bar/ describes the API for `ScottPlot 5.0.10-beta` on NuGet, and other versions may have a different API.

I'm using ScottPlot 5.0.10-beta from nuget, and these examples don't work. Even the first simplest one:
myPlot.Add.Bars(values);
There is no Plot.Add.Bars method.

**Comment by raburton** [comment]
That's fair enough. I wasn't complaining, just reporting the issue but it's obviously on your radar already.
