### ISSUE TITLE
SP5: Add lock and unlock render actions to improve support for multi-threading environments

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3095]
Following discussion with @bclehmann in the Discord (#1966), let's add some empty actions that get invoked at the start and end of each render which advanced users could add their own code into to wait for an optical lock state to be achieved before rendering and stay locked until after rendering.

This functionality should go in the RenderManager class https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Rendering/RenderManager.cs

**Comment by bclehmann** [comment]
As a basic summary of our discussion:

For users on multithreaded platforms the plot may be mutated and be rendered on separate threads, which can cause unexpected issues. A pre-render action could be a mechanism to ensure plot mutation happens right before rendering on the same thread, eliminating the possibility for interleaving by essentially eliminating multithreading. Note that if someone puts an expensive pre-render action it may delay rendering by a lot, perhaps we should advise them to trigger a render once they've registered an action to avoid paying this cost at an inopportune time.

For users who specifically want multithreading, this gives them an opportunity to get their ducks in a row before rendering starts. For example, if they use locks to synchronize their threads they can wait on their locks in this action. This ensures that once the later actions start running there is no possibility for interleaving.

**Comment by swharden** [comment]
Done! Here's an example use:

```cs
formsPlot1.Plot.RenderManager.PreRenderLock += (s, e) =>
{
    // code here must complete before the frame renders
    System.Threading.Thread.Sleep(100);
};
```
