### ISSUE TITLE
SP5: Polygon LineStyle is overriden by Hatch

### ISSUE THREAD

**Issue by faguetan** [ScottPlot/ScottPlot#3099]
## Bug Report

**Issue:** When setting FillStyle for polygon to Hatch, it is not possible then to style the stroke (border) of the said polygon. It seems that LineStyle is somehow overridden by FillStyle.

**Reproducing:** Create a polygon, set FillStyle to use Hatch. Set LineStyle for this polygon. You can see that the stroke is there, but its not visible if LinePattern set to solid (depending on the stroke size the size of the visible polygon grows). If polygon FillStyle set to just color fill, then stroke begins to respect it's Color property.

### System Details
* **ScottPlot Version:** 5.0.10-beta
* **Operating System:** Windows 10
* **Application Type:** Avalonia
* **.NET Version:** .NET 7.0

**Comment by swharden** [comment]
Thanks for reporting this! Clarifying the issue,

```cs
ScottPlot.Plot myPlot = new();

Coordinates[] vertices = new Coordinates[]
{
    new Coordinates(0,   0.25),
    new Coordinates(0.3, 0.75),
    new Coordinates(1,   1),
    new Coordinates(0.7, 0.5),
    new Coordinates(1,   0)
};

var p = myPlot.Add.Polygon(vertices);

p.LineStyle = new LineStyle()
{
    Width = 10,
    Color = Colors.Red,
    Pattern = LinePattern.Dash
};
```

looks good

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/dfaabfeb-65e7-43f0-8508-8af9f838603c)

but changing the fill changes the outline somehow

```cs
p.FillStyle.Hatch = new ScottPlot.Hatches.Dots();
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/07c86f61-dd2b-41d9-968a-d6245fed73b4)

**Comment by swharden** [comment]
Figured it out! The shader applied by the hatch wasn't reset before the line is drawn. The code will work properly in the next release. Thanks again for reporting this one! 

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/5638eb83-8f5c-470a-b58b-05b1a8df6413)
