### ISSUE TITLE
SP5 FixedPadding: Labels misaligned & right ticks missing

### ISSUE THREAD

**Issue by albyoo** [ScottPlot/ScottPlot#3104]
## Bug Report

**Issue:** The first render of a plot with a `FixedLayout` padding results in the label overlapping the ticks. The right axis has all ticks missing. Upon resizing the left label repositions correctly, however, the right axis ticks are still missing.

First Render:
![image](https://github.com/ScottPlot/ScottPlot/assets/139430929/6106f539-63db-479a-ac98-75a14e75c188)

After Resizing:
![image](https://github.com/ScottPlot/ScottPlot/assets/139430929/d2ecb255-b678-462f-aff1-3281e8ac2622)

Expected:
![image](https://github.com/ScottPlot/ScottPlot/assets/139430929/a8ecc4a1-57da-458a-b28a-f3ea7c4ed87f)

**Reproducing:** 

```cs
// Create new fixed padding layout engine
myPlot.LayoutEngine = new FixedPadding(new PixelPadding(100));

// plottables use the standard X and Y axes by default
var sig1 = myPlot.Add.Signal(ScottPlot.Generate.Sin(51, mult: 0.01));
sig1.Axes.XAxis = myPlot.XAxis; // standard X axis
sig1.Axes.YAxis = myPlot.YAxis; // standard Y axis
myPlot.YAxis.Label.Text = "Primary Y Axis";

// add a new plottable and tell it to use the right Y axis
var sig2 = myPlot.Add.Signal(ScottPlot.Generate.Cos(51, mult: 100));
sig2.Axes.XAxis = myPlot.XAxis; // standard X axis
sig2.Axes.YAxis = myPlot.RightAxis; // right Y axis
myPlot.RightAxis.Label.Text = "Secondary Y Axis";
```

### System Details
* **ScottPlot Version:** 5.0.11
* **Operating System:** Windows 11
* **Application Type:** WinForms
* **.NET Version:** .NET 7.0

**Comment by swharden** [comment]
Got it fixed! This will work better in the next release. Thanks for reporting this @albyoo!

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/e41fcffb-64d0-47d9-a97a-55f176125320)

**Comment by swharden** [comment]
Note that the API is about to change to something simpler

```cs
myPlot.Layout.Fixed(new PixelPadding(100));
```

**Comment by albyoo** [comment]
Thanks @swharden! I've been having a break during the holidays period 🏖️
