### ISSUE TITLE
Odd zoom behaviour in multi channel DataStreamer

### ISSUE THREAD

**Issue by jwilo** [ScottPlot/ScottPlot#3108]
ScottPlot 4.1.69
Win 10, 22H2 19045
WinForms, .NET 8

This issue may be related to that described in #2865 released in SP5, though the example of using SharedAxes appears to be for multiple plots, not multiple channels on the same plot.

If multiple channels are plotted on a single DataStreamer plot, as per below, then the zooming behaviour effectively 'fragments' the displayed data, different depending on whether drag zoom, or scroll zoom is used.

```
ScottPlot.Plottable.DataStreamer[] Channels = new ScottPlot.Plottable.DataStreamer[16];

for (int channel = 0; channel < 16; channel++)
{
   Channels[channel] = formsPlot1.Plot.AddDataStreamer(1000);
   Channels[channel].SamplePeriod = 0.001; // optional, without setting this the X axis will display sample count (i.e. 0-1000), rather than 0-1 second
   Channels[channel].ViewScrollLeft();
   Channels[channel].ManageAxisLimits = true;
}
```

Demonstration data below

![ManageAxisLimitsTrueNoZoom](https://github.com/ScottPlot/ScottPlot/assets/89950407/8037e818-cdfc-44f4-960f-54f0acc75f84)

Zooming on the data using drag zoom, note that one channel zooms - but the other doesn't

![ManageAxisLimitsTrueDragZoom](https://github.com/ScottPlot/ScottPlot/assets/89950407/29efdfa7-0b64-4869-8460-a21cf9edc9aa)

Zooming on the data using scroll zoom, neither channel zooms - and every third or so screel wheel indent, 1 of the channels now appears to have a false offset, which isn't actually there in the data

![ManageAxisLimitsTrueScrollZoom](https://github.com/ScottPlot/ScottPlot/assets/89950407/cdb44543-2d55-412c-bdf5-38fc6eeeaded)

**Comment by swharden** [comment]
Hi @jwilo, thanks for reporting this!

Unfortunately this issue doesn't contain a reproducible code example I can copy/paste into an application on my end to see what's going on, but looking over the code that was supplied I think this may be the issue:

```cs
Channels[channel].ManageAxisLimits = true;
```

If you have 16 `DataStreamer` objects and they're all trying to set axis limits at the same time, I would expect that you may find some very confusing behavior! If you set all those to `false`, I suspect panning and zooming will function more consistent with expectation
