### ISSUE TITLE
SP5: Make Plot Interactions more extensible

### ISSUE THREAD

**Issue by albyoo** [ScottPlot/ScottPlot#3110]
## Feature Suggestion

Currently to override the plot interactions, the Interaction class must be overriden to handle custom functionality. A lot of the Interaction's members are private, which makes it more difficult to extend the base functionality.

**Feature description:** Add an interaction interface, similar to the IPlotExtensions experimented with here https://github.com/ScottPlot/ScottPlot/commit/a4ded384c82078f08bc4b251d7d3bde416e3fc31

Additionally, it would be nice to make all the private members on `Interaction` protected.

**Code example:**

```cs
public interface IPlotInteraction
{
    ContextMenuItem[] ContextMenuItems { get; }

    string DefaultSaveImageFilename { get; }

    /// <summary>
    /// Disable all mouse interactivity
    /// </summary>
    void Disable();

    /// <summary>
    /// Enable mouse interactivity using the default mouse actions
    /// </summary>
    void Enable();

    /// <summary>
    /// Enable mouse interactivity using custom mouse actions
    /// </summary>
    void Enable(PlotActions customActions);

    void OnMouseMove(Pixel newPosition);

    void KeyUp(Key key);

    void KeyDown(Key key);

    void MouseDown(Pixel position, MouseButton button);

    void MouseUp(Pixel position, MouseButton button);

    void DoubleClick();

    void MouseWheelVertical(Pixel pixel, float delta);
}
```

**Comment by swharden** [comment]
resolved in #3111
