### ISSUE TITLE
Is it appropriate to use ScottPlot as the canvas for an image processing software?

### ISSUE THREAD

**Issue by Fokatu** [ScottPlot/ScottPlot#3117]
The data that needs to be displayed are two-dimensional arrays or three-dimensional arrays with different data type; the operations involved include adjusting the window width and level, drawing profile diagrams, drawing ROI, etc., similar to ImageJ.

I also noted that Image support is not latest version. Why?
Thanks!

**Comment by swharden** [comment]
Hi @Fokatu,

ScottPlot is really designed for displaying _data_ on a Cartesian plane. It's not really intended to be an image manipulation tool. You can probably push ScottPlot to do things like draw ROIs, but to be honest I think it would be easier to just use SkiaSharp by itself for this and not worry with ScottPlot's axis systems.

I created a little library to make it a bit easier to work with raster images (especially high-bit-depth scientific TIF images):
https://github.com/swharden/RasterSharp

and I used it in an internal app: 
https://github.com/swharden/ScanAGator
![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/c1b7f2dd-a83e-4759-82da-08620d981459)

Hope it helps!
Scott
