### ISSUE TITLE
Bad performance on 2k, 4k monitors

### ISSUE THREAD

**Issue by Lyakabynka** [ScottPlot/ScottPlot#3126]
**Issue:**
I tried plotting candlestick chart first and on my 2k resolution monitor it performed not well when I tried moving around the graph, but when I tried using FullHD it worked good, with no lags and FPS was above 60.

Then, I thought it might be because of candlesticks, but even without any data FPS was nearly 30.
After resizing the window into a smaller one, performance went back and I saw 60+ FPS.

**Reproducing:**

Open any Scottplot graph in 2k+ resolution. Move around data grid. Observe issue.

```cs
// InternalTabContent.cs

public partial class InternalTabContent : UserControl
{
    private IList<IOHLC> prices;
    
    public InternalTabContent()
    {
        InitializeComponent();

        var myPlot = WpfPlot1.Plot;

        prices = RandomDataGenerator.Generate.RandomOHLCs(3000);
        myPlot.Add.Candlestick(prices);
        
        WpfPlot1.Refresh();
    }
}

// InternalTabContent.cs.xaml

<ScottPlot:WpfPlot x:Name="WpfPlot1" Grid.Row="1"/> // just add anywhere in your xaml
```

### System Details
* **ScottPlot Version:** Any version.
* **Operating System:** Windows 10.
* **Application Type:** WPF.
* **.NET Version:** .NET 8.

**Comment by Lyakabynka** [comment]
Update:

For those, who are using Dragablz library.
AllowsTransparency="False" on DragablzWindow fixes lags.
Spent 2 days on this.

**Comment by swharden** [comment]
> For those, who are using Dragablz library. AllowsTransparency="False" on DragablzWindow fixes lags. Spent 2 days on this.

Thanks for following-up! Wow that would have taken me two days too 😅 Hopefully others searching for this topic will benefit from these messages!
