### ISSUE TITLE
Hidden Colorbar

### ISSUE THREAD

**Issue by shipulinkn** [ScottPlot/ScottPlot#3131]
Hello,
Could you help me solve an issue with the hidden Colorbar?
If add the plottables of the previously created Heatmap and Colorbar Plot to the FormsPlot.Plot that the Colorbar is hidden under the right side of the form and the ticks are hidden too. While the FormsPlot is in the Dock.Fill

```cs
Plot plot = new Plot();

private void CreatePlot(double[,] arr)
{
	var hm = plot.AddHeatmap(arr, colormap: ScottPlot.Drawing.Colormap.Jet, lockScales: true);
	plot.AddColorbar(hm);
	plot.AddHorizontalLine(0);
	plot.AddVerticalLine(0);
}

private void ShowPlot()
{
	var fp = FormsPlot.Plot;
	var plottables = plot.Plot.GetPlottables();
	foreach (var plottable in plottables)
	{
	    fp.Add(plottable);
	}

	FormsPlot.Refresh();
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/51188556/0f7abd19-5686-441d-98bc-3954bd4f9e95)

**Comment by swharden** [comment]
Hi @shipulinkn, 

I think the solution is to call 
```cs
var hm = plot.AddHeatmap(arr, colormap: ScottPlot.Drawing.Colormap.Jet, lockScales: true);
FormsPlot.Plot.AddColorbar(hm);
FormsPlot.Plot.AddHorizontalLine(0);
FormsPlot.Plot.AddVerticalLine(0);
FormsPlot.Refresh();
```

The part of your code where you are maintaining a `Plot` which is not your `FormsPlot.Plot` is probably the cause of this issue

**Comment by shipulinkn** [comment]
I think it's not convenient to create a plot right before displaying it. Sometimes, you might not need to display it at all and can just save the image.

Perhaps there is a more efficient way to transfer a plot to `FormsPlot` instead of this?
```
var fp = FormsPlot.Plot;
var plottables = plot.Plot.GetPlottables();
foreach (var plottable in plottables)
{
   fp.Add(plottable);
}
````

**Comment by swharden** [comment]
Hi @shipulinkn, I may be misunderstanding what you are trying to achieve, but the issue may be that you created a `new Plot()` and this is not recommended for plot controls. Plot controls come with their own plot. If you only interact with `FormsPlot.Plot` and never create your own, is your problem solved?

Check out the code example on https://scottplot.net/quickstart/winforms/

**Comment by swharden** [comment]
```cs
private void CreateAndShowPlot(double[,] arr)
{
	var hm = FormsPlot.Plot.AddHeatmap(arr, colormap: ScottPlot.Drawing.Colormap.Jet, lockScales: true);
	FormsPlot.Plot.AddColorbar(hm);
	FormsPlot.Plot.AddHorizontalLine(0);
	FormsPlot.Plot.AddVerticalLine(0);
	FormsPlot.Refresh();
}
```

**Comment by shipulinkn** [comment]
Thank you for your advice. The correct way to proceed is by using FormsPlot instead of creating and pulling a Plot and pulling it to any procedure.
