### ISSUE TITLE
Release ScottPlot 5.0 in Jan, 2024 🚀

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3146]
ScottPlot 5 may not be feature complete with ScottPlot 4, but it's pretty useful for most applications, and now that cross-platform support for ScottPlot 4 is dead I think it's still an improvement and the timing is right.

ScottPlot 4 will continue to be supported, and the website should do a good job of making all of this clear and discoverable.

**Comment by swharden** [comment]
... I decided to push the release back a few days to give me a little more time to improve the website and documentation before I flip the switch and make ScottPlot 5 the new default version on NuGet.

I could release it today (all the major features I wanted before the release are in there now), but the API could use a little more refinement and some of the changes are pretty big (especially #3140) and I want to make sure the documentation and website is all up to date and ready to go before I flip the switch

**Comment by raburton** [comment]
Where people are using features in SP4 that aren't in SP5, should we open a feature request issue, or is there a planned todo list we can check against, etc? I appreciate the ideal solution would be to implement it ourselves and create a PR, but I'm sure most people are using this library don't have the time or skills to do so (and consequently are very grateful for your efforts in producing and maintaining it!)

**Comment by swharden** [comment]
Hi @raburton, opening an issue would be great! I'll probably slowly chip away at adding features on my own, but getting feedback from others will be helpful for knowing which features to prioritize

**Comment by swharden** [comment]
I'm really glad I waited a few more days... the new improvements from #3154 are fantastic!

Signal and Scatter plots now support any data type (not just double), including DateTime arrays! 🤯
