### ISSUE TITLE
SP5: remove IOHLC and use OHLC structs

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3147]
Originally implemented in #2404, I don't think we're gaining a lot anymore by using this abstraction. I think having an OHLC-creating _data source_ interface is the best way to let users have their own financial data generators.

**Comment by intellogy** [comment]
I was going to suggest creating IOHLC interface to allow use of existing list data without re-marshalling into List of OHLC (concrete), but I see IOHLC existed and now is removed.

If I have my own POCO list with item properties of different names than your OHLC class, as well containing additional item quote properties beyond o-h-l-c, how do I use my existing IEnumerable list to work with ScottPlot.Plot.Add.OHLC()?

What is the OHLC-creating data source interface you mention above?

Thanks!!!
