### ISSUE TITLE
GetAxisLimits returns bad values.

### ISSUE THREAD

**Issue by CBrauer** [ScottPlot/ScottPlot#3149]
I am trying to develop an App using ScottPlot, version 5, on a Windows Form test program.
Using the Designer of my Visual Studio 2022, I dragged a  `ScottPlot.WinForms.FormsPlot formsPlot1` onto the test Form.
I then added the following code:

```
using ScottPlot;
using System.Diagnostics;

namespace testAddText;
public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        var nPoints = 100;
        var X = Generate.Consecutive(nPoints);
        var Y = Generate.Sin(nPoints);
        formsPlot1.Plot.Add.Scatter(X, Y);
        
        var limits = formsPlot1.Plot.GetAxisLimits();
        var left = limits.Rect.Left;
        var center = limits.Rect.HorizontalCenter;
        var right = limits.Rect.Right;
        Debug.WriteLine($"left: {left}, center: {center}, right: {right}");
    }
}
```

My project configuration is:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;ARM32;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ScottPlot.WinForms" Version="5.0.11-beta" />
  </ItemGroup>
</Project>
```

The Debug print returns "`left: ∞, center: NaN, right: -∞`".
I am trying to center text at the bottom of the plot.

Charles

**Comment by swharden** [comment]
Hi @CBrauer, thanks for reporting this!

The plot will have no axis limits (infinity) unless `SetAxisLimits()` or `AutoScale()` is called. This is the behavior you observed.

If the user doesn't call either of those methods, the plot will call `AutoScale()` automatically when it is first rendered, so calling `GetAxisLimits()` after a button click or something will probably return values more consistent with what you were expecting.
