### ISSUE TITLE
SP5 Signal: improve support for additional datatypes

### ISSUE THREAD

**Issue by angulion** [ScottPlot/ScottPlot#3154]
## SignalSource at the moment only supports Double. UInt16, perhaps other common types would be welcomed.

**Feature description:** Implementation of SignalUInt16 / SignalUShort or something like SP4's SignalGeneric<T>

**Code example:** 
Something like:

```cs
// a code sample may improve communication
ushort[] mySignal  = GetDataFromSource();
var signalplot = ScottPlot.Add.Signal(mySignal);
```

**Comment by swharden** [comment]
Thanks for this suggestion @angulion! I'm about to merge in a fix which will allow you to do this:

```cs
UInt16[] values = { 1, 3, 2, 4 };
double period = 1.0;
ScottPlot.DataSources.SignalSourceUInt16 source = new(values, period);

ScottPlot.Plot plt = new();
plt.Add.Signal(source);
plt.SaveFig("demo.png", 600, 400);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/dd470f98-6a4a-4f75-8fa2-0fb6b03673f5)

**Comment by swharden** [comment]
Check out 51b490efd4f50bb980ce7535f0827ac12a7cfe21 for details

I pretty much just copied the standard signal data source that uses `double` and made it use `UInt16` instead

I'll follow-up by creating a generic version too so it's there in case people want to use it... maybe I can use compiler flags to support fast generic math in .NET 7 and above

**Comment by swharden** [comment]
Nice! Adding support for generics was way easier than I expected. There's room for optimization, but this will work in the next commit:

```cs
List<UInt16> values = new() { 1, 3, 2, 4 };
ScottPlot.Plot plt = new();
plt.Add.Signal(values);
```


```cs
UInt16[] values = new() { 1, 3, 2, 4 };
ScottPlot.Plot plt = new();
plt.Add.Signal(values);
```

**Comment by swharden** [comment]
Wow! Even this works now:

```cs
float[] xs = { 1, 2, 3, 4 };
UInt16[] ys = { 1, 3, 2, 4 };

ScottPlot.Plot plt = new();
plt.Add.Scatter(xs, ys);
```

Thanks @angulion for encouraging me to look further into this. This wasn't too hard to add into the library and having generic support for Signal and Scatter plots is a huge win! 🚀

**Comment by swharden** [comment]
Wow, DateTime support works now that generics are supported! This improvement is the gift that keeps on giving

```cs
DateTime firstDay = new(2024, 01, 01);
DateTime[] days = Generate.DateTime.Days(365, firstDay);
double[] values = Generate.RandomWalk(days.Length);

ScottPlot.Plot plt = new();
plt.Add.Scatter(days, values);
plt.Axes.DateTimeTicks(Edge.Bottom);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/9021b47e-fd62-4343-b61b-c12e8fcf6203)
