### ISSUE TITLE
SP5: Error Bars seems to not be drawing correct

### ISSUE THREAD

**Issue by wolfcomp** [ScottPlot/ScottPlot#3155]
## Bug Report

**Issue:** 
Something with Error Bars seems to not be correct when using the same data for Scatter. 
Unsure if this is specifically due to me using OADate format for the plot.

**Reproducing:** 
This particular case https://github.com/wolfcomp/PDPWebsite/blob/master/Backend/Universalis/History.cs#L279-L284
The data loaded is from this [query](https://universalis.app/api/v2/history/seraph/10335?entriesToReturn=500) gotten from Universalis

### System Details
* **ScottPlot Version:** 5.0.11
* **Operating System:** Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-83-generic x86_64)
* **Application Type:** ASP.NET Core
* **.NET Version:** .NET 7

### Images
Without error bars:
![plot1](https://github.com/ScottPlot/ScottPlot/assets/4028289/003c190d-e4e8-4b85-aea9-ebbb45f0ca26)
With error bars:
![plot2](https://github.com/ScottPlot/ScottPlot/assets/4028289/de1ef1b5-cd32-4437-b99a-42c513ab053b)
Only error bars:
![plot3](https://github.com/ScottPlot/ScottPlot/assets/4028289/e2aee046-7a4f-4e84-b7a2-c58592771954)

**Comment by swharden** [comment]
Thanks for reporting this @wolfcomp! I found the bug and am fixing it now. In the next release this code will work:

```cs
ScottPlot.Plot plt = new();

double[] sales = { 123, 456, 789 };
double[] salesError = { 50, 150, 350 };
DateTime[] dates = { new(2024, 01, 01), new(2024, 01, 02), new(2024, 01, 03) };
double[] dateXs = dates.Select(x => x.ToOADate()).ToArray();

plt.Add.Scatter(dateXs, sales);
plt.Add.ErrorBar(dateXs, sales, salesError);

plt.SavePng("test.png", 400, 300);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/f0673e36-dbd8-4b45-a7b7-d21f180480bc)
