### ISSUE TITLE
SP5 Add support for Polygon gradient fill

### ISSUE THREAD

**Issue by faguetan** [ScottPlot/ScottPlot#3157]
## Feature Suggestion

**Feature description:** Would be really nice to have not only solid color fill for polygons, but also linear gradients.

**Comment by swharden** [comment]
Thanks for this suggestion @faguetan! I just merged #3298 and added a cookbook recipe showing how to use it. There's room for improvement still, but I'll mark this issue as resolved and we can loop back around to refine it in the future

**Comment by faguetan** [comment]
Awesome! Thank you, @KroMignon and @swharden !
