### ISSUE TITLE
SP5 Signal: Add MinRenderIndex MaxRenderIndex support

### ISSUE THREAD

**Issue by raburton** [ScottPlot/ScottPlot#3158]
## Feature Suggestion

**Feature description:** Add MinRenderIndex MaxRenderIndex support to SignalPlot, as in v4
Needed for some of the examples here: https://scottplot.net/faq/live-data/

Some code I knocked up to do this temporarily:
https://gist.github.com/raburton/53a5838f3fa52f27ffba8d924d34848e

**Comment by swharden** [comment]
Thanks for this suggestion @raburton! I'm merging #3171 in now which will allow code like this:

```cs
double[] values = Generate.RandomWalk(1000);

var sigAll = myPlot.Add.Signal(values);
sigAll.Label = "Full";
sigAll.Data.YOffset = 80;

var sigLeft = myPlot.Add.Signal(values);
sigLeft.Label = "Left";
sigLeft.Data.YOffset = 60;
sigLeft.Data.MaximumIndex = 700;

var sigRight = myPlot.Add.Signal(values);
sigRight.Label = "Right";
sigRight.Data.YOffset = 40;
sigRight.Data.MinimumIndex = 300;

var sigMid = myPlot.Add.Signal(values);
sigMid.Label = "Mid";
sigMid.Data.YOffset = 20;
sigMid.Data.MinimumIndex = 300;
sigMid.Data.MaximumIndex = 700;

myPlot.ShowLegend(Alignment.UpperRight);
myPlot.Axes.Margins(top: .5);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/de5b9a82-2efc-4840-997a-cb5d8ec10196)
