### ISSUE TITLE
SP5 Signal: Support `List<double>` to allow users to add to signal plot data

### ISSUE THREAD

**Issue by raburton** [ScottPlot/ScottPlot#3159]
## Feature Suggestion

ISignalSource uses IReadOnlyList for it's data, which makes dynamic changes to the plot more difficult e.g. having to replace SignalSourceDouble with a custom data source. While that's possible, it shouldn't be necessary just to edit the data.

Not all the functions of SignalSourceDouble are trivial (or obviously documented) in order to make your own version and it introduces extra maintenance problems. I copied SignalSourceDouble, modified it enough to get read/write access to the data, and then wondered the an upgrade to 5.0.11-beta didn't fix the YOffset bug, only to eventually realise the fix for that was in SignalSourceDouble and so I needed to port it to my alternate version.

This is a bit of a design and API change, but I don't understand why it made read only in the first place, was being editable a problem in v4?

**Comment by swharden** [comment]
Hi @raburton, thanks for the suggestion! I'll ensure this is possible and create a demo for this shortly. I recently modified scatter plots to accept `double[]` or `List<double>`, so I can try to get signal plots to support arrays and lists too.

**Comment by swharden** [comment]
Hi @raburton, this feature was added recently (#3154) and will be in the next release! 🚀
