### ISSUE TITLE
SP5: Implement `SignalXY`

### ISSUE THREAD

**Issue by ChristianWeigand** [ScottPlot/ScottPlot#3163]
SignalPlotPerformanceXY is still misssing, I think this is a type of Plot, which is very important.

**Comment by swharden** [comment]
Thanks for reporting this @ChristianWeigand! At this moment only Signal (and not SignalXY) is in ScottPlot 5, but I consider it a high priority task to get it added. It's unlikely to be done in time for the release today, but it will definitely make it into the next one. Thanks again for bringing our attention to this!

**Comment by swharden** [comment]
Following-up, I got it working in ScottPlot 5 in #3163 🚀 

If you're in a pinch you can copy/paste the class there and use it in the current version of ScottPlot

I'm going to keep working to improve support for generic data types, so it may be a few days before I merge it in and publish an updated NuGet package.

![signalxy](https://github.com/ScottPlot/ScottPlot/assets/4165489/4fb43d4e-0887-4dc5-823b-c1cafd7f3c99)

```cs
// generate sample data with gaps
List<double> xList = new();
List<double> yList = new();
for (int i = 0; i < 5; i++)
{
    xList.AddRange(Generate.Consecutive(1000, first: 2000 * i));
    yList.AddRange(Generate.RandomSample(1000));
}
double[] xs = xList.ToArray();
double[] ys = yList.ToArray();

// add a SignalXY plot
formsPlot1.Plot.Add.SignalXY(xs, ys);
formsPlot1.Refresh();
```
