### ISSUE TITLE
Heatmap pixel value

### ISSUE THREAD

**Issue by skn41** [ScottPlot/ScottPlot#3165]
## Feature Suggestion

It would be nice to have a feature that allows to get pixel value at a specific coordinate. Something like this:
```cs
double v = MyHeatmap.GetValueAt(x, y);
```

**Comment by swharden** [comment]
This will be in the next release! Thanks again for the suggestion @skn41 

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        double[,] data = SampleData.MonaLisa();
        var hm = formsPlot1.Plot.Add.Heatmap(data);

        formsPlot1.Refresh();

        formsPlot1.MouseMove += (s, e) =>
        {
            Coordinates coordinates = formsPlot1.Plot.GetCoordinates(e.X, e.Y);
            (int x, int y) = hm.GetIndexes(coordinates);
            double value = hm.GetValue(coordinates);

            Text = double.IsNaN(value)
                ? "None"
                : $"data[{y}, {x}] = {value}";
        };
    }
}
```

![getvalue](https://github.com/ScottPlot/ScottPlot/assets/4165489/6e550acb-8056-4e23-a365-35bddf68dc21)

**Comment by swharden** [comment]
Actually @skn41 if you get the chance, it may be worth double-checking to make sure results match expectations at the very edges... I'd hate for it to be one cell off and not notice 😅

**Comment by shipulinkn** [comment]
> This will be in the next release! Thanks again for the suggestion @skn41

Thank you for resolving the issue promptly.
