### ISSUE TITLE
SP5 Plottables: review exposed properties

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3168]
Favor exposing and interacting with properties directly at the level of the Plottable instead of encouraging users to reach in and directly interact with the `LineStyle`, `MarkerStyle`, and `Label` they may have.

This makes it easy to refactor those complicated classes in the future as needs evolve without breaking peoples' code for customizing plottables

_EDIT: After a discussion in Discord (#1966) with raburton we decided to expose both_

**Comment by raburton** [comment]
see also #3178
