### ISSUE TITLE
Financial Chart YAxis

### ISSUE THREAD

**Issue by CBrauer** [ScottPlot/ScottPlot#3175]
## Feature Suggestion

Financial charts usually have the chart price label on the right side of the chart.

For example: https://diagrammm.com/candlestick_chart

> **Axis Position and Grid**
> The Candlestick Chart is a financial chart and usually, the greatest interest is in the data located on the right side of the chart. Thus, if there is only one Y-axis, it should be located on the right side. As the chart is high density packed with the data it is fine to make Y-axis on both sides, left and right. In addition, the horizontal lines grid allows easily to estimate the value of each element on the chart.

I tried to move the Candlestick chart's Y-Axis from the left to the right in ScottPlot 5, but there does not seem to be an easy way to do that.

Please consider a Cookbook tutorial on how to fix the Y-Axis labeling on the Candlestick chart.
Or better still, make the Y-Axis on the right the default.

Charles

**Comment by swharden** [comment]
It looks like this works

```
var prices = Generate.RandomOHLCs(30);
var candles = formsPlot1.Plot.Add.Candlestick(prices);

candles.Axes.YAxis = formsPlot1.Plot.Axes.Right;
candles.Axes.YAxis.Label.Text = "Price";

formsPlot1.Plot.Axes.DateTimeTicks(Edge.Bottom);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/1342bc7d-0b78-45d5-9869-838e92f46002)

**Comment by CBrauer** [comment]
Thanks Scott. That was very fast.
