### ISSUE TITLE
SP5: LockedVertical / LockedHorizontal not working right

### ISSUE THREAD

**Issue by raburton** [ScottPlot/ScottPlot#3179]
## Bug Report

**Issue:** Using the code from the end of #3160, gives strange results. See screen shots below for various combinations and results.

**Reproducing:** Try code below, uncommenting the locking lines as required.

```cs
private void Form1_Load(object sender, EventArgs e) {

    double[] positions1 = { 1, 4, 7, 10, 13, 16, 19 };
    double[] values1 = { 1, 4, 7, 10, 13, 16, 19 };
    double[] positions2 = { 2, 5, 8, 11, 14, 17, 20 };
    double[] values2 = { 2, 5, 8, 11, 14, 17, 20 };

    BarPlot Plot1 = formsPlot1.Plot.Add.Bars(positions1, values1);
    BarPlot Plot2 = formsPlot1.Plot.Add.Bars(positions2, values2);

    formsPlot1.Plot.Axes.AutoScale();
    //formsPlot1.Plot.Axes.Rules.Add(new LockedVertical(formsPlot1.Plot.Axes.Left));
    //formsPlot1.Plot.Axes.Rules.Add(new LockedHorizontal(formsPlot1.Plot.Axes.Bottom));
}
```

Code as above, no axes locked:
![image](https://github.com/ScottPlot/ScottPlot/assets/433543/ac4071a6-079f-4c86-a3c5-62c0d1a2cb2d)

Vertical axis locked:
![image](https://github.com/ScottPlot/ScottPlot/assets/433543/5ffad515-f43b-493e-b96b-54f0ad93cc09)

Horizontal axis locked:
![image](https://github.com/ScottPlot/ScottPlot/assets/433543/f4826715-157a-4f9b-ba1c-14b37155f95d)

Both locked:
![image](https://github.com/ScottPlot/ScottPlot/assets/433543/bdac194f-045d-49b9-8101-557b938fe9de)

### System Details
* **ScottPlot Version:** 5.0.12-beta
* **Operating System:** Windows 10
* **Application Type:** WinForms
* **.NET Version:** .NET 8.0

**Comment by swharden** [comment]
Thanks for reporting this! I figured out the problem is that the rules always copy the axis limits from the previous render onto the next, but if the plot never rendered then this weird bug occurs. I'll fix it now and it'll be in the next release 👍

**Comment by swharden** [comment]
This is pretty obscure, but technically it works with the current library if you call:

```cs
formsPlot1.Plot.Render();
```

instead of 

```cs
formsPlot1.Plot.Axes.AutoScale();
```
