### ISSUE TITLE
SP5: Chinese label text show as rectangles

### ISSUE THREAD

**Issue by prime167** [ScottPlot/ScottPlot#3181]
![图片](https://github.com/ScottPlot/ScottPlot/assets/3722845/ff92a532-494e-4e7d-8bc7-85d247ec1631)

---------------------------------

```cs
WpfPlot1.Plot.Axes.Bottom.Label.Text = "时间 Time";
WpfPlot1.Plot.Axes.Left.Label.Text = "已占用 Used (GB)";
```

### System Details
* **ScottPlot Version:** 5.0.13-beta
* **Operating System:** Windows 10 21H1
* **Application Type:** WPF
* **.NET Version:** .NET 8.0.1

**Comment by heartacker** [comment]
https://github.com/ScottPlot/ScottPlot/issues/2746

**Comment by prime167** [comment]
dup with #2746
