### ISSUE TITLE
SP5 Scatter Plot: Performance decreases in version 5.0.11

### ISSUE THREAD

**Issue by Smonze** [ScottPlot/ScottPlot#3183]
## Bug Report

**Issue:** In the 5.0.10 version I can easily plot 1000 Scatter plots with 1000 points each with around 4FPS
All higher version take literally forever. Performance drastically detoriates after more than 100 Scatter plots

**Reproducing:** (What do others have to do to reproduce the bug?)

```cs
// a code sample may improve communication
var rnd = new Random();
int numberOfPlots = 1000;
int max = 1024;

WpfPlot1.Plot.Clear();

for (int n = 0; n < numberOfPlots; n++)
    // XYPlot data
    double[] dataX = new double[max];
    double[] dataY = new double[max];
    for (int i = 0; i < max; i++)
    {
        dataX[i] = i;
        dataY[i] = 1000.0 * rnd.NextDouble();
    }

    // ScottPlot
    var scatter = WpfPlot1.Plot.Add.Scatter(dataX, dataY);
    scatter.MarkerStyle.IsVisible = false;
    scatter.LineStyle.Width = 1.0F;
    scatter.LineStyle.Pattern = LinePattern.Solid;
    scatter.LineStyle.AntiAlias = true;
}

WpfPlot1.Refresh();
```

### System Details
* **ScottPlot Version:** 5.0.11 Beta and higher
* **Operating System:** Windows 10)
* **Application Type:**  WPF
* **.NET Version:** (NET Framework 4.8)

**Comment by swharden** [comment]
FYI, here's a full reproducible code sample for WinForms, and yeah the performance is awful... 15x slowdown!

ScottPlot 5.0.10 | ScottPlot 5.0.13
---|---
0.242 sec | 3.688 sec

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        int pointsPerPlot = 1024;
        int numberOfPlots = 1_000;

        for (int n = 0; n < numberOfPlots; n++)
        {
            double[] dataX = Generate.Consecutive(pointsPerPlot);
            double[] dataY = Generate.RandomWalk(pointsPerPlot);

            var scatter = formsPlot1.Plot.Add.Scatter(dataX, dataY);
            scatter.MarkerStyle.IsVisible = false;
            scatter.LineStyle.Width = 1.0F;
            scatter.LineStyle.Pattern = LinePattern.Solid;
            scatter.LineStyle.AntiAlias = true;
        }

        formsPlot1.Plot.RenderManager.RenderFinished += (s, e) =>
        {
            Text = formsPlot1.Plot.LastRender.Elapsed.ToString();
        };
    }
}
```

**Comment by swharden** [comment]
I found that what is happening is that when coordinate range was split into separate objects in 30f83a5470c230d09271482ad07626eb95a1e1f9 that the render system is getting confused about whether or not axis limits have been set and it's running "AutoScale()" before every frame, resulting in the bottleneck.
