### ISSUE TITLE
SP5: Add international font detection to labels

### ISSUE THREAD

**Issue by prime167** [ScottPlot/ScottPlot#3184]
![image](https://github.com/ScottPlot/ScottPlot/assets/3722845/d22e673b-e9e7-4194-90ba-172ff124ff10)

**Issue:** 

* Left Label show Chinese as rectangles
* .Bold = false does not work

**Reproducing:** 

```cs
        WpfPlot1.MouseDoubleClick += WpfPlot1_MouseDoubleClick;
        WpfPlot1.Plot.Benchmark.IsVisible = false;
        WpfPlot1.Plot.Axes.DateTimeTicks(Edge.Bottom);

        WpfPlot1.Plot.Style.SetFontFromText("中文");
        WpfPlot1.Plot.Title("测试");

        WpfPlot1.Plot.Axes.Bottom.Label.Text = "时间";
        WpfPlot1.Plot.Axes.Left.Label.Text = "已占用 (GB)"; // does not work
        WpfPlot1.Plot.Axes.Bottom.Label.Alignment = Alignment.MiddleCenter;
        WpfPlot1.Plot.Axes.Bottom.Label.Rotation = 0;
        WpfPlot1.Plot.Axes.Bottom.Label.AntiAlias = true;
        WpfPlot1.Plot.Axes.Bottom.Label.Bold = false;

        WpfPlot1.Plot.Axes.Left.Label.OffsetX = -8;
        WpfPlot1.Plot.Axes.Left.Label.Alignment = Alignment.MiddleCenter;
        WpfPlot1.Plot.Axes.Left.Label.AntiAlias = true;
        WpfPlot1.Plot.Axes.Left.Label.Bold = false; // does not work
        WpfPlot1.Refresh();
```

### System Details
* **ScottPlot Version:** 5.0.14-beta
* **Operating System:** Windows 10
* **Application Type:** WPF
* **.NET Version:** .NET 8.01

**Comment by swharden** [comment]
Hi @prime167, this works for me. Does it work for you?

```cs
formsPlot1.Plot.Style.SetFontFromText("时间");
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/add26ff9-71c9-4cfa-a8ae-0769e8204e3d)

**Comment by swharden** [comment]
... this issue points out something interesting though: If two labels require different fonts, `Plot.Style.SetFontFromText()` is not a good solution because it applies the same font to everything. Labels themselves should have a `SetFontFromText()` method. I'll add this feature as I work on #3180

**Comment by prime167** [comment]
I used WPF. It does not work either. Both "时间" and "中文" are all Chinese. I will try again when you finish #3180

**Comment by swharden** [comment]
I made good progress! I'm about to merge this in, then you can use it like this. All `Label` objects will have a `SetBestFont()` you can call individually. I'm also improving `Fonts.Detect()` to use all characters instead of just the first character.

```cs

List<(string, string)> samples = new()
{
    ( "English", "Test" ),
    ( "Chinese", "测试" ),
    ( "Japanese", "試験" ),
    ( "Korean", "테스트" ),
};

Plot myPlot = new();
myPlot.HideGrid();

for (int i = 0; i < samples.Count; i++)
{
    string language = samples[i].Item1;
    string text = samples[i].Item2;

    var txtSample = myPlot.Add.Text(text, 1, i);
    txtSample.Size = 22;
    txtSample.FontName = Fonts.Detect(text); // this works
    txtSample.Label.SetBestFont(); // this also works

    var txtLanguage = myPlot.Add.Text(language, 0, i);
    txtLanguage.Size = 22;

    var txtFont = myPlot.Add.Text(txtSample.FontName, 2, i);
    txtFont.Size = 22;
}

myPlot.Axes.SetLimits(-.5, 4.5, -.5, 3.5);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/f512f775-7760-4155-92e9-6911b61fde1d)

**Comment by swharden** [comment]
I'm also adding a helper method to make this easier 🚀 

```cs
myPlot.Title("测试"); // Chinese
myPlot.YLabel("試験"); // Japanese
myPlot.XLabel("테스트"); // Korean
myPlot.Style.DetectFonts();
```

**Comment by prime167** [comment]
![图片](https://github.com/ScottPlot/ScottPlot/assets/3722845/6c3e95dd-7643-4229-830e-8277c3141c81)

I have updated to 5.0.16, only XLabel() method works.
WpfPlot1.Plot.Title("测试"); originally worked, but became rectangle now.

This is my repo:
https://github.com/prime167/DiskSpaceHistory

**Comment by swharden** [comment]
Use int32 instead of char for better UTF32 support

https://learn.microsoft.com/en-us/dotnet/api/skiasharp.skfontmanager.matchcharacter?view=skiasharp-2.88#skiasharp-skfontmanager-matchcharacter(system-string-system-int32)

**Comment by swharden** [comment]
Closing this to track progress in #3220
