### ISSUE TITLE
SP5: Rotation of tick labels

### ISSUE THREAD

**Issue by barnettben** [ScottPlot/ScottPlot#3185]
## Feature Suggestion

I would like to be able to rotate tick text in SP5, but that API has changed since 4.1.x and I am unsure if this is possible already or not yet added.

The appearance I want to recreate is the same as this 4.1 example:
https://scottplot.net/cookbook/4.1/recipes/ticks_rotated/

## Explanation

I posted a question on Discord asking if this is already possible in SP5, and was asked to open a ticket here for a new cookbook example page. So here we are 🙂.

**Comment by swharden** [comment]
Thanks for the suggestion @barnettben! This feature will be available in the next release

```cs
myPlot.Axes.Bottom.TickLabelStyle.Rotation = -45;
myPlot.Axes.Bottom.TickLabelStyle.OffsetY = -8;
myPlot.Axes.Bottom.TickLabelStyle.Alignment = Alignment.MiddleRight;
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/7b2a7adf-8e8d-464b-922e-7245b55cbe55)
