### ISSUE TITLE
SP5 boundaries on axes

### ISSUE THREAD

**Issue by Milyczekpolsl** [ScottPlot/ScottPlot#3191]
## Feature Suggestion

Feature description: Hi, it would be helpful to provide an example code for SP5 (or implement if this functionality doesn't exist) showing how to set boundaries on axes so you won't be able to navigate outside of them without stretching the plot like it's in winforms example.

**Comment by swharden** [comment]
Thanks for the suggestion @Milyczekpolsl! I just made the change and improved the demo app. I think it's a lot better now, but I welcome feedback for any additional improvements you think would be helpful! I'll release a new NuGet package with this update today or tomorrow 🚀
