### ISSUE TITLE
SP5: Scatter Plot AutoScale issue

### ISSUE THREAD

**Issue by CBrauer** [ScottPlot/ScottPlot#3194]
I am using ScottPLot beta 5.0.14

I found that the following code works;
```cs
ScottPlot.Version.ShouldBe(5, 0, 14);
formsPlot1.Plot.ScaleFactor = 2;
formsPlot1.Plot.Clear();
scatter1 = formsPlot1.Plot.Add.Scatter(X, Y, color: Colors.Black);

var fontSize = 12;
formsPlot1.Plot.Title(symbol, fontSize);
if (changePoint <= 0)
{
    formsPlot1.Refresh();
    return;
}
var xMarker = X[changePoint];
var yMarker = Y[changePoint];
crossHair = formsPlot1.Plot.Add.Crosshair(xMarker, yMarker);
crossHair.IsVisible = true;
formsPlot1.Plot.Axes.AutoScale();
formsPlot1.Refresh();
```

Without:

`formsPlot1.Plot.Axes.AutoScale();`

the scatter did not draw.

The Cookbook for scatter needs to add;

`formsPlot1.Plot.Axes.AutoScale();`

Charles

**Comment by swharden** [comment]
Hi @CBrauer, thanks for reporting this! Unfortunately I can't reproduce this issue and the code sample you provided is not complete and I am unsure what the values of `X`, `Y`, `symbol`, and `changePoint` are supposed to be.

Here a winforms app I created to mimic your code sample, and it works as expected. Can this be modified to demonstrate the behavior you describe?

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        double[] xs = Generate.Consecutive(51);
        double[] ys = Generate.Sin(51);

        formsPlot1.Plot.Add.Scatter(xs, ys);
        formsPlot1.Plot.Add.Crosshair(xs[10], ys[10]);

        //formsPlot1.Plot.Axes.AutoScale(); // not required?
        formsPlot1.Refresh();
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/c51d577b-d372-4211-9edf-1acd68072fdb)

**Comment by swharden** [comment]
Following-up, I think this code example reproduces the behavior you initially described.

After plots have already been displayed, axes will not be modified unless the mouse engages with it or unless `SetLimits()` or `AutoScale()` is called manually.

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();
    }

    private void btnClear_Click(object sender, EventArgs e)
    {
        formsPlot1.Plot.Clear();
        formsPlot1.Refresh();
    }

    private void btnAddScatter_Click(object sender, EventArgs e)
    {
        double mult = 1 + formsPlot1.Plot.PlottableList.Count;
        double phase = Generate.RandomData.RandomNumber();
        double[] xs = Generate.Consecutive(51);
        double[] ys = Generate.Sin(51, mult, phase: phase);
        formsPlot1.Plot.Add.Scatter(xs, ys);
        formsPlot1.Plot.Axes.AutoScale(); // required since the plot was already displayed
        formsPlot1.Refresh();
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/7420a5bd-b5aa-4589-a502-e22ea6ca632b)
