### ISSUE TITLE
How ScottPlot remove rendered in xxx ms (xxx.xx Hz)?

### ISSUE THREAD

**Issue by yunotyu** [ScottPlot/ScottPlot#3206]
![Snipaste_2024-01-15_09-50-13](https://github.com/ScottPlot/ScottPlot/assets/53213484/606c424e-29b9-40ef-81e6-95a4c53f618a)
![Snipaste_2024-01-15_09-50-13](https://github.com/ScottPlot/ScottPlot/assets/53213484/5d60bcdf-a4f1-4463-a558-1403ac81935f)

**Comment by swharden** [comment]
Hi @yunotyu, double-click the plot to show/hide that behavior

Alternatively you can:

```cs
formsPlot1.Plot.Benchmark.IsVisible = false;
```
