### ISSUE TITLE
SP5: Multiline tick labels

### ISSUE THREAD

**Issue by raburton** [ScottPlot/ScottPlot#3208]
## Feature Suggestion

**Feature description:** Could you please add multi-line tick labels (works in v4). Would need to be centred around the tick, which may complicate implementation. Thanks.

**Code example:**

```cs
double[] data = new double[100];
for (int i = 0; i < data.Length; i++) data[i] = 100;

Signal sp = formsPlot1.Plot.Add.Signal(data);

formsPlot1.Plot.Axes.Left.TickGenerator = new ScottPlot.TickGenerators.NumericManual(new double[] { 0, 100 }, new string[] { "0", "Marker\nLine"});
```

![image](https://github.com/ScottPlot/ScottPlot/assets/433543/407bea67-8d0a-4569-b589-ff838d3a113f)

**Comment by swharden** [comment]
Thanks for reporting this @raburton! This relates to #3180 but I'll leave both issues open until this fix is made.

**Comment by swharden** [comment]
Also related, the rectangle used for string measurement and alignment isn't currently respecting line breaks

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/cc9507c5-cd55-44ed-adea-ceb8788c0512)

**Comment by swharden** [comment]
Note to self, this is a simpler way to reproduce this issue

```cs
Plot plt = new();

plt.Add.Signal(Generate.Sin());
plt.Add.Signal(Generate.Cos());

ScottPlot.TickGenerators.NumericManual ticker = new();
ticker.AddMajor(-.5, "one line");
ticker.AddMajor(+.5, "two\nlines");

plt.Axes.Left.TickGenerator = ticker;
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/f754832d-f042-41b6-850d-c7e8ad97dd84)

**Comment by swharden** [comment]
Following-up, it looks like multiline support is present for horizontal ticks:
https://github.com/ScottPlot/ScottPlot/blob/e2c65cce5758cb1e902b29ebefcf96f411fd4aa1/src/ScottPlot5/ScottPlot5/AxisPanels/AxisBase.cs#L155-L165

but not vertical ticks:
https://github.com/ScottPlot/ScottPlot/blob/e2c65cce5758cb1e902b29ebefcf96f411fd4aa1/src/ScottPlot5/ScottPlot5/AxisPanels/AxisBase.cs#L196-L197

**Comment by raburton** [comment]
Thank you.
