### ISSUE TITLE
A question about table creation

### ISSUE THREAD

**Issue by Kendo1207** [ScottPlot/ScottPlot#3209]
**Question:** (Ask your question here)
I am a beginner in coding and I want to create different tables through a For loop, but I have found that tables are only based on the data generated by the last For loop (all tables have the same data)
**ScottPlot Version:** (What NuGet package are you using?)
5.0.16
**Code Sample:** 
```cs
 for (int i = 0; i < access_listBoxCheckedItemsCount; i++)
 {
     for (int j = 0; j < recordNum[fileCount]; j++)
     {
         xData[j] = data[j, 1];
         yData[j] = data[j, 2 + access_CheckedIndices[i]];
     }
     access_Plt= new FormsPlot();
     access_Plt.Plot.Add.Scatter(xData, yData);
     access_Plt.Refresh();
     flowLayoutPanel1.Controls.Add(access_Plt);                  
 }
```
![image](https://github.com/ScottPlot/ScottPlot/assets/93170789/95853b6f-ad3c-4a6d-9c32-aaf6c8e2e467)

**Comment by swharden** [comment]
Hi @Kendo1207, thanks for your question! I think this code sample will help. 

I started by dropping 3 `FormsPlot` controls onto my Form

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/ab94f3f2-a6c7-48e5-9c0e-79a3b099f9f8)

Then I assigned data to them individually:

```cs
formsPlot1.Plot.Add.Scatter(Generate.Consecutive(51), Generate.Sin(51));
formsPlot2.Plot.Add.Scatter(Generate.Consecutive(51), Generate.Cos(51));
formsPlot3.Plot.Add.Scatter(Generate.Consecutive(51), Generate.RandomWalk(51));
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/6095caf6-d53d-44b9-afb9-1bceb0a09cca)

I suspect your issue relates to how you're using `new FormsPlot()`, or what's in `access_listBoxCheckedItemsCount`, `recordNum`, or `access_CheckedIndices`. If you can make your app simpler by avoiding that `new` statement and not having the nested loops I think you will be able to find a solution. Feel free to open this issue back up again if your have additional questions - good luck!
