### ISSUE TITLE
SP5: Add `WpfPlotViewer` or document equivalent functionality

### ISSUE THREAD

**Issue by chaojian-zhang** [ScottPlot/ScottPlot#3212]
**Issue:** It's unfortunate but in an application I have we depend on `ScottPlot.WpfPlotViewer()` and that class is removed in SP5. 

**ScottPlot Version:** 5.0.16

**Code Sample:** 

```cs
// In console application
ScottPlot.Plot plt = new ScottPlot.Plot();
new ScottPlot.WpfPlotViewer(plt).ShowDialog();
```

Throws an exception: `The type or namespace name 'WpfPlotViewer' does not exist in the namespace 'ScottPlot' (are you missing an assembly reference?)`

In [What's New](https://scottplot.net/faq/version-5.0/) it's not mentioned that this should happen.

(In that case I think the issue https://github.com/ScottPlot/ScottPlot/issues/308 is no longer valid)

**Comment by swharden** [comment]
Hi @chaojian-zhang, thanks for your suggestion!

> we depend on ScottPlot.WpfPlotViewer() and that class is removed in SP5

I would like to add this feature to ScottPlot 5 or add documentation to clarify how users can achieve this functionality themselves. I'm really happy that you brought this to my attention. I'll look into this now and follow-up here later today!

> In [What's New in ScottPlot 5](https://scottplot.net/faq/version-5.0/) it's not mentioned that this should happen.

There is a banner that indicates that ScottPlot 4 has many features, is still supported, and existing projects that use ScottPlot 4 don't have to upgrade. You are correct though that this missing feature isn't addressed specifically.

**Comment by swharden** [comment]
Hi @chaojian-zhang, I found some solutions that work using the existing version of ScottPlot:

### Launch a new window from a Console application
```cs
public class Program
{
    [STAThread]
    static void Main()
    {
        ScottPlot.Plot plt = new();
        plt.Add.Signal(ScottPlot.Generate.Sin());
        plt.Add.Signal(ScottPlot.Generate.Cos());

        ScottPlot.WPF.WpfPlot wpfPlot = new();
        wpfPlot.Reset(plt);
        System.Windows.Window win = new() { Content = wpfPlot };
        win.ShowDialog();
    }
}
```

### Launch a new window from the right-click menu
```cs
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        WpfPlot1.Plot.Add.Signal(Generate.Sin());
        WpfPlot1.Plot.Add.Signal(Generate.Cos());

        WpfPlot1.Menu.Add("Launch in New Window", (wpfPlot) => LaunchPlotViewer(wpfPlot.Plot));
    }

    static void LaunchPlotViewer(Plot plot)
    {
        WpfPlot wpfPlot = new();
        wpfPlot.Reset(plot);

        Window win = new() { Content = wpfPlot };
        win.ShowDialog();
    }
}
```

**Comment by swharden** [comment]
I'll update the library so this will be possible from console apps:

```cs
ScottPlot.WinForms.FormsPlotViewer.Launch(myPlot);
ScottPlot.WPF.FormsPlotViewer.Launch(myPlot);
```

**Comment by swharden** [comment]
information from this issue has been added to the website:
https://scottplot.net/faq/launch-console/

**Comment by chaojian-zhang** [comment]
Outstanding efficiency!
