### ISSUE TITLE
SP5 RenderManager: `EnableRendering` flag

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3213]
~For consistency it would be nice to add the `RenderLock()` and `RenderLock()` methods for consistency with previous behavior to compliment the `PreRenderLock` event handler added in #3095~

Update: I'm going to add a `EnableRendering` flag to allow this:

```cs
void MyDangerousOperation(){

    // disable new renders
    formsPlot1.Plot.RenderManager.EnableRendering = false;

    // wait for the current render to finish
    while (formsPlot1.Plot.RenderManager.IsRendering) {}

    // perform your dangerous operation
    myScatterPlot.DataSource.Clear();

    // permit new renders
    formsPlot1.Plot.RenderManager.EnableRendering = true;

    // force the plot to redraw
    formsPlot1.Refresh();
}
```

Note that `EnableRendering` _skips_ renders while `PreRenderLock` _hangs_ renders

**Comment by swharden** [comment]
https://scottplot.net/faq/async/

**Comment by kagerouttepaso** [comment]
Thank you for the update. However, I am unable to use `formsPlot1.Plot.Rendermanager.EnableRenderring = true;` as you have implemented the `EnableRenderring` flag as private in the modified code.
