### ISSUE TITLE
SP5: Implement rich text panels

### ISSUE THREAD

**Issue by CBrauer** [ScottPlot/ScottPlot#3222]
I would like to propose a multi-line text display that we can put at the bottom of charts.
This is like a rich TextBox. Let me show you an example.

![multi-line](https://github.com/ScottPlot/ScottPlot/assets/1317234/aae4bb4a-3a6a-44f2-add1-d403ead393bf)

Note the coloring of the text.  At the present time, Microsoft does not have an easy way to do this.
This is done by "graphical Text". At present, I use SkiaSharp to create the display. And it is ugly.
Charles

**Comment by swharden** [comment]
Hi @CBrauer, thanks for the feedback! What's the advantage of including this on the plot vs. adding a rich textbox beneath the plot?

It would be nice to have this feature so people exporting plots as images can have text beneath it.

> Note the coloring of the text

1 in 12 males (myself included) is red colorblind, so I'd guess some text is red and some is black? 🤣

**Comment by swharden** [comment]
Following-up, it looks like this may not be possible without taking on a non-Microsoft dependency, e.g., https://github.com/toptensoftware/RichTextKit

However we can add a feature to let users add an _image_ beneath the plot, then they are free to generate that image with such a dependency.

**Comment by CBrauer** [comment]
Hi Scott,

I just read your example at https://scottplot.net/cookbook/5.0/Text/. 
Maybe we could build a multi-line label below the x-axis by using a modified version of ScottPlot Text.

Charles

**Comment by swharden** [comment]
I think this will be possible in the next release (5.0.22) as we have improved support for multi-line labels. One can add additional axes and hide the ticks to realize a plot with extra text on the side. If you create a minimal code example demonstrating this behavior, share it here and we can create a cookbook recipe from it to help others realize the same solution!

https://scottplot.net/changelog/

**Comment by KennyTK** [comment]
> Following-up, it looks like this may not be possible without taking on a non-Microsoft dependency, e.g., https://github.com/toptensoftware/RichTextKit
> 
> However we can add a feature to let users add an _image_ beneath the plot, then they are free to generate that image with such a dependency.

Doing some digging on what this might entail. The text image would ideally be bitmap or SVG depending on the desired output.

**Comment by swharden** [comment]
Hey @CBrauer and the group,

It's been a while since this topic was discussed here but I wanted to follow-up and note that `LabelStyle` got an `Image` property in #4517, so this feature should now be supported.
