### ISSUE TITLE
WpfPlot.LeftClickedPlottable event

### ISSUE THREAD

**Issue by MarekJur** [ScottPlot/ScottPlot#3232]
WpfPlot.LeftClickedPlottable - no information about hitted element in event (sender and event args)

**Comment by swharden** [comment]
Hi @MarekJur, this code should work with the existing library. I'll add it to the demo app to make it more discoverable.

```cs
formsPlot1.MouseMove += (s, e) =>
{
    Pixel mousePixel = new(e.X, e.Y);
    Coordinates mouseCoordinates = formsPlot1.Plot.GetCoordinates(mousePixel);
    Text = $"X={mouseCoordinates.X:N3}, Y={mouseCoordinates.Y:N3}";
};

formsPlot1.MouseDown += (s, e) =>
{
    Pixel mousePixel = new(e.X, e.Y);
    Coordinates mouseCoordinates = formsPlot1.Plot.GetCoordinates(mousePixel);
    Text = $"X={mouseCoordinates.X:N3}, Y={mouseCoordinates.Y:N3} (mouse down)";
};
```

See the code of the "show value under mouse" demo to learn how to interact with data that has been plotted

https://scottplot.net/demo/#show-value-under-mouse

**Comment by swharden** [comment]
You may find the "draggable axis line" informative too https://scottplot.net/demo/#interactive-plottables
