### ISSUE TITLE
SP5: Are hand-drawn style charts possible?

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3239]
### Discussed in https://github.com/ScottPlot/ScottPlot/discussions/3219

<div type='discussions-op-text'>

<sup>Originally posted by **prime167** January 17, 2024</sup>
Currently, ScottPlot support customize drawing style like backgroud color, font, line style
https://scottplot.net/cookbook/4.1/#style
https://scottplot.net/cookbook/5.0/Styling/

and V4 has some pre-define style like [this](https://scottplot.net/cookbook/4.1/category/style/#blue2-style)
`plt.Style(Style.Blue2);`

I think we can add another level of style: like professional(current style), [hand drawn](https://www.google.com/search?q=hand+drawn+style+chart&newwindow=1&sca_esv=599052157&pws=0&gl=us&ei=63unZZ61N8XekPIP2pGRoA0&ved=0ahUKEwje1pHV7eODAxVFL0QIHdpIBNQQ4dUDCBA&uact=5&oq=hand+drawn+style+chart&gs_lp=Egxnd3Mtd2l6LXNlcnAiFmhhbmQgZHJhd24gc3R5bGUgY2hhcnQyBRAhGKABMgUQIRigATIFECEYoAEyBRAhGKABMgUQIRigATIFECEYnwVIlA5QngdY9AxwAXgBkAEAmAGOA6ABhAmqAQUyLTIuMrgBA8gBAPgBAcICChAAGEcY1gQYsAPCAggQABgWGB4YD8ICCxAAGIAEGIoFGIYDwgIFECEYqwLiAwQYACBBiAYBkAYE&sclient=gws-wiz-serp) It would be fun and useful.

![image](https://github.com/ScottPlot/ScottPlot/assets/3722845/8d1e529b-770b-4df5-88ec-ff976a35e77d)

Python:
* [cutecharts](https://github.com/cutecharts/cutecharts.py)
* [matplotlib.pyplot.xkcd](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.xkcd.html)

Javascript: 
* [chart.xkcd](https://github.com/timqian/chart.xkcd)

Commercial product
* [LiveGap](https://livegap.com/charts/)</div>

**Comment by swharden** [comment]
Hi @prime167, let's continue the discussion here. I like the idea of looking into this! If there's an easy way to make SkiaSharp draw curvy lines instead of solid lines, this may be somewhat feasible with a global flag that changes the behavior of this method and its adjacent methods:

https://github.com/ScottPlot/ScottPlot/blob/9e17d5b9f2c16da0e8c4ac71040f666a0eb4c7b6/src/ScottPlot5/ScottPlot5/Drawing.cs#L75-L88

If someone wants to look into this and create a pull request (or paste some code here) demonstrating how to draw handwriting-style lines using SkiaSharp I'd be happy to review it, but until I clear out some of the other high priority issues it may take me a while before I can look into this personally

**Comment by aespitia** [comment]
modifying some samples from ChatGPT, this seems to draw a shaky line.  this was edited to work in LinqPad

void Main()
{
	var random = new Random();			
	var bitmap = new Bitmap(800, 600);
	using (var surface = SKSurface.Create(new SKImageInfo(bitmap.Width, bitmap.Height)))
	{
		var canvas = surface.Canvas;

		canvas.Clear(SKColors.White);

		var paint = new SKPaint
		{
			IsAntialias = true,
			Color = SKColors.Black,
			StrokeWidth = 3,
			Style = SKPaintStyle.Stroke
		};

		float startX = 50;
		float startY = 50;
		float endX = bitmap.Width - 50;
		float endY = bitmap.Height - 50;

		// Simulate shaky line
		SKPath path = new SKPath();
		path.MoveTo(startX, startY);

		float previousX = startX;
		float previousY = startY;

		float segments = 100; // Number of segments along the line

		for (int i = 0; i < segments; i++)
		{
			float t = (i + 1) / segments;
			float x = startX * (1 - t) + endX * t;
			float y = startY * (1 - t) + endY * t;

			// Add random deviation
			x += (float)(random.NextGaussian() * .5);
			y += (float)(random.NextGaussian() * .5);

			path.LineTo(x, y);

			previousX = x;
			previousY = y;
		}

		canvas.DrawPath(path, paint);

		// Convert SKImage to System.Drawing.Bitmap
		using (var img = surface.Snapshot())
		using (var data = img.Encode())
		using (var stream = data.AsStream())
		{
			stream.Position = 0;
			bitmap = (Bitmap)System.Drawing.Image.FromStream(stream);
		}
	}

	Util.Image(bitmap).Dump();
}

**Comment by sdpenner** [comment]
Here's an idea. 

Apparently, there is a feature in Skia to do what Alphonso mentioned above.  Similar to creating dashed lines, you can create a discrete path effect with a length and amount of deviation from straight that you desire.

I messed around with a hatching option as well.  The line looks good, but the hatching algo could use some work.  The hatch pattern and density will need to change based upon the fill color of the object being painted.

```c#
        private void OnPaintSurface(object sender, SKPaintSurfaceEventArgs e)
        {
            // the the canvas and properties
            SKCanvas canvas = e.Surface.Canvas;
            int canvasWidth = e.Info.Width;
            int canvasHeight = e.Info.Height; 

            int rectWidth = canvasWidth / 8;
            int rectHeight = canvasHeight / 8;
            int rectCenterX = canvasWidth / 2 - rectWidth / 2;
            int rectCenterY = canvasHeight / 2 - rectHeight / 2;

            // make sure the canvas is blank
            canvas.Clear(SKColors.White);

            SKPath hatchPath = new SKPath();
            hatchPath.AddCircle(0, 0, 1.5f);

            SKPaint fillPaint = new SKPaint
            {
                Color = Colors.DarkSlateGray.ToSKColor(),
                IsAntialias = true,
                Style = SKPaintStyle.Fill,
                Shader = SKShader.CreatePerlinNoiseTurbulence(2, 2, 1, 0f),
                PathEffect = SKPathEffect.Create2DPath(SKMatrix.CreateScale(7,7), hatchPath),
            };

            SKPathEffect effect = SKPathEffect.CreateDiscrete(8, 1);

            SKPaint outlinePaint = new SKPaint
            {
                Color = Colors.DarkSlateGray.ToSKColor(),
                IsAntialias = true,
                Style = SKPaintStyle.Stroke,
                StrokeWidth = 2,
                PathEffect = effect
            };

            canvas.DrawRect(rectCenterX, rectCenterY, rectWidth, rectHeight, fillPaint);
            canvas.DrawRect(rectCenterX, rectCenterY, rectWidth, rectHeight, outlinePaint);
        }
```
![image](https://github.com/ScottPlot/ScottPlot/assets/40821256/a513838d-0528-4149-98cf-f727bf9252ea)

**Comment by aespitia** [comment]
did not know you can include images lol, this is what the shaky line stuff above produces
![image](https://github.com/ScottPlot/ScottPlot/assets/105309364/8ac4d09b-75fe-4e12-8080-c072e3202d7f)

**Comment by sdpenner** [comment]
Here's a result using the discrete effect from Skia.  Seems like we are on to something...

![image](https://github.com/ScottPlot/ScottPlot/assets/40821256/6396ddf6-0853-450c-a5eb-d6f7d9b0830c)

```c#
        void OnPaintLine(SKCanvas canvas, SKPoint windowSize)
        {
            // make sure the canvas is blank
            canvas.Clear(SKColors.White);

            SKPathEffect effect = SKPathEffect.CreateDiscrete(8, 1);

            SKPaint outlinePaint = new SKPaint
            {
                Color = Colors.DarkSlateGray.ToSKColor(),
                IsAntialias = true,
                Style = SKPaintStyle.Stroke,
                StrokeWidth = 2,
                PathEffect = effect
            };

            SKPoint topLeft = new SKPoint(windowSize.X / 4, windowSize.Y / 4);
            SKPoint bottomRight = new SKPoint(topLeft.X * 3, topLeft.Y * 3);
            canvas.DrawLine(topLeft, bottomRight, outlinePaint);
        }
```

**Comment by sdpenner** [comment]
I played around with some line plots for grins.  I haven't looked at how any of the other plots will look, yet.  

Thoughts?

![image](https://github.com/ScottPlot/ScottPlot/assets/40821256/920ea761-4508-4c55-8652-4bdb88e03aee)

**Comment by swharden** [comment]
Okay I'm just now seeing this... and I love it 😍 

I'll leave this issue open since I don't personally have the time to implement this right now, but if someone creates a PR I'd be happy to review it and we can refine it as needed!

**Comment by swharden** [comment]
@sdpenner did some awesome work adding this feature to ScottPlot 5 in #3486. I'm going to close that PR for now, but I'll leave this issue open and when I have a little more time to work on that PR I'll open it up again and add this feature throughout ScottPlot 5 👍

**Comment by swharden** [comment]
Can this effect be added by creating a new PR that only modifies a single file? I suspect a single bool could toggle this behavior in the `Drawing` class 🤔 

https://github.com/ScottPlot/ScottPlot/blob/c04332e7ecb05113b45b90a75089598ae3201295/src/ScottPlot5/ScottPlot5/Drawing.cs#L14-L60

**Comment by swharden** [comment]
To clarify my goal, I'd love to solve this with a PR that doesn't modify more than a file or two (or take much time to review). 

#3486 was pretty extensive, resulting in it never getting merged 😅
