### ISSUE TITLE
How to highlight plottables in 5.0

### ISSUE THREAD

**Issue by TetheredSun** [ScottPlot/ScottPlot#3246]
In ScottPlot 4.*, I utilised the `IHighlightable` interface to highlight the plottable nearest the mouse. In 5.0, I cannot find any equivalent.

**ScottPlot Version: 5.0**

For example, the code below no longer works in 5.0. Is there any way I can reproduce the same functionality in 5.0?
```cs
 IPlottable[] plottables = scottPlot.Plot.GetPlottables();

 for (int i = 0; i < plottables.Length; i++) {
     if (plottables[i] is not IHighlightable highlightable) continue;
     highlightable.IsHighlighted = i == index;
 }
 scottPlot.Refresh();
```

**Comment by swharden** [comment]
Hi @TetheredSun, thanks for raising this issue!

The demo application shows how to locate the point nearest the mouse and place a crosshair on it: https://scottplot.net/demo/#show-value-under-mouse

You could adapt that code to instead place a circular marker around the point, or use some other method to highlight it as desired

This strategy should work for you, but let me know if you hit any snags along the way 👍

**Comment by TetheredSun** [comment]
Dear @swharden 

Thank you very much for your prompt reply. I am working on an implementation that also works for `SignalConst` plots, not just `Scatter` ones.

Thank you again for this amazing library and your kind help.
