### ISSUE TITLE
Set axis intersection points

### ISSUE THREAD

**Issue by ZTaiIT1025** [ScottPlot/ScottPlot#3250]
The default coordinate axis intersection point is in the bottom left corner. Can we set the coordinate axis intersection point position to be in the middle of the chart by setting properties

**Comment by swharden** [comment]
> default coordinate axis intersection point is in the bottom left corner

Hi @ZTaiIT1025, thanks for this suggestion! Unfortunately I don't understand the behavior you're looking for. Can you share a screenshot or code sample that more clearly indicates how the current system is unable to produce the behavior you'd like to see?

I'll close this issue for now, but we can re-open it if/when there's enough information for me to get started working on a solution. 

Thanks!
Scott
