### ISSUE TITLE
SP5 Signal: vertical orientation

### ISSUE THREAD

**Issue by manaruto** [ScottPlot/ScottPlot#3253]
Is it possible to draw vertical lines in signalxy plots, i know i can acheive the same using scatterplot, but what if i want the performance of signalpotxy?

I'm interested in achieving a similar effect in WinForms as described in this issue, where a control is rotated in WPF. Is this possible with ScottPlot in a WinForms application? If so, could you please provide some guidance or examples? Thanks!

i am using SP5 and winforms

https://github.com/ScottPlot/ScottPlot/issues/1194

**Comment by swharden** [comment]
Thanks for the suggestion @manaruto! I just added this feature and it will be in the next release

```cs
var sig1 = myPlot.Add.SignalXY(xs, ys);
sig1.Data.Rotated = true;
```

**Comment by j1730** [comment]
> 谢谢你的建议！我刚刚添加了这个功能，它将在下一个版本中出现
> 
> ```cs
> var sig1 = myPlot.Add.SignalXY(xs, ys);
> sig1.Data.Rotated = true;
> ```
Dear author,

Thank you for your dedication. While using ScottPlot, I have encountered a couple of issues and would like to bring them to your attention:

1. Feature Request: When setting Rotated = true;, the current behavior allows value to be displayed only from the bottom to the top. I would like to suggest supporting the option to display value from the top to the bottom.

2. Issue: When setting Rotated = true and simultaneously adjusting the YOffset property, there seems to be a display error.
> ```cs
>var _wave = formsPlot.Plot.Add.SignalXY(timeAxis, data2[i], Color.FromHex("#000000"));
>_wave.Data.YOffset = 1;
>//_wave.Data.Rotated = true;
>_wave.Axes.XAxis = formsPlot.Plot.Axes.Top;
>_wave.Axes.YAxis = formsPlot.Plot.Axes.Left;
> ```
![Snipaste_2024-02-05_11-26-22](https://github.com/ScottPlot/ScottPlot/assets/155717777/4dca6d2f-bc73-4fab-9273-d1f75e193602)
> ```cs
>var _wave = formsPlot.Plot.Add.SignalXY(timeAxis, data2[i], Color.FromHex("#000000"));
>_wave.Data.YOffset = 1;
>_wave.Data.Rotated = true;
>_wave.Axes.XAxis = formsPlot.Plot.Axes.Top;
>_wave.Axes.YAxis = formsPlot.Plot.Axes.Left;
> ```
![2](https://github.com/ScottPlot/ScottPlot/assets/155717777/8b836e8c-c3ab-44b0-9b1e-7d710ec732de)



These issues impact my user experience, and I hope they can be addressed in future releases. Your time and hard work are greatly appreciated.

Best regards,

The above translation is from chatGPT
