### ISSUE TITLE
ScottPlot 5  IDraggable

### ISSUE THREAD

**Issue by daimenspace** [ScottPlot/ScottPlot#3256]
i want to use ScottPlot5 to replace  ScottPlot4.X
but I don't find Interface  IDraggable
if  the IDraggable in ScottPlot5  is on the way?

**Comment by swharden** [comment]
Hi @daimenspace, thanks for this issue! This is possible in ScottPlot 5, but `IDraggable` is not required. I'll create a demo specific to scatter plots #3248, but for now you may find the information you need by looking at the draggable axis line demo https://scottplot.net/demo/#interactive-plottables
