### ISSUE TITLE
SP5: Remove OpenTK

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3262]
OpenTK was added to allow OpenGL plottables (#2565), but OpenGL plottables have caused some confusing issues (#3008, #3007, #2950), and they have minimal performance improvements over the standard plottables. 

OpenTK throws warnings like this frequently too:

> Warning	NU1701	Package 'OpenTK 3.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net8.0'. This package may not be fully compatible with your project.

This issue will track removing OpenTK, FormsPlotGL, and WpfPlotGL from the standard control packages. This functionality may get added back into separate packages, or maintained here for extremely advanced users.

**Comment by swharden** [comment]
Actually, OpenTK is a dependency of `SkiaSharp.Views.WindowsForms` and `SkiaSharp.Views.WPF` so there's not much that can be done.

```xml
<!-- ignore warnings about OpenTK getting restored restored using .NET Framework -->
<NoWarn>NU1701</NoWarn>
```

**Comment by eawestwig** [comment]
How much do I need to worry about those warnings about those libraries not being fully compatible with .net 8?

**Comment by eawestwig** [comment]
For this issue: https://github.com/ScottPlot/ScottPlot/issues/3262#issue-2092824377

How much should I be worried about these warning messages from the compiler?
