### ISSUE TITLE
Add a new Bar Style

### ISSUE THREAD

**Issue by enumer** [ScottPlot/ScottPlot#3263]
I would like a horizantal bar to show a device status. The device state is the state value of the time series. I need to show it like this
![image](https://github.com/ScottPlot/ScottPlot/assets/20962283/dde4cf96-fd84-4b04-ae99-58ab0d0b2a66)
The background color is set to black, and there is no need to display the Y axis, and the device status is represented by different colors or styles. Can you implement the base Bar control with different colors in the legend, and support the extension for me to achieve the latter two different styles of display.

**Comment by swharden** [comment]
Hi @enumer, I'm adding `AddRectangle()` to the next release, allowing you to add shapes wherever you wish on the plot

```cs
using ScottPlot;

Plot plt = new();
plt.Style.DarkMode();

Color[] colors = { Colors.Red, Colors.Green, Colors.Yellow, Colors.LightGray };

double x = 0;
for (int i = 0; i < 10; i++)
{
    double width = Random.Shared.Next(1, 5);
    x += width;
    double y = Random.Shared.Next(1, 3);

    CoordinateRect cr = new(x, x + width, y, y + 1);
    var rp = plt.Add.Rectangle(cr);
    rp.LineStyle.Width = 0;
    rp.FillStyle.Color = colors[Random.Shared.Next(colors.Length)];
}

plt.SavePng("test.png", 600, 300);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/c526107e-9e67-49b5-96ef-9bccd805c8a3)
