### ISSUE TITLE
SP5 Cookbook: Add additional information to DateTime axis recipes

### ISSUE THREAD

**Issue by chaojian-zhang** [ScottPlot/ScottPlot#3267]
**Question:** Those two pages are all great on their own: https://scottplot.net/cookbook/5.0/DateTimeAxes/DateTimeAxisQuickstart/ and https://scottplot.net/cookbook/5.0/LinePlot/, however it's not clear how to mix the two. For instance, I have a scatter, and I just wish to add a single line on that scatter.
On page https://scottplot.net/faq/datetime/ it says "Use LINQ and DateTime.ToOATime() to convert DateTime[] to double[] before plotting" - do you mean [`DateTime.ToOADate`](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tooadate?view=net-8.0)? Fundamentally, I think date times are converted to numbers before plotting, but it's not clear from the documentation or source code (`ScottPlot.PlottableAdder.Scatter<T1, T2>(T1[] xs, T2[] ys, Color? color = null)` and `ScatterSourceGenericArray`) how this is done.

**ScottPlot Version:** 5.0.17

**Code Sample:** 

Solution is kind of implied on https://scottplot.net/faq/datetime/ and I tried this:

```C#
namespace ConsoleApp1
{
    internal class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            ScottPlot.Plot plot = new ();
            plot.Add.Signal(ScottPlot.Generate.Sin());
            plot.Add.Line(0, 0, 1, 1);
            plot.Add.Scatter(new DateTime(2003, 10, 01).ToOADate(), 4);

            plot.Axes.DateTimeTicks(ScottPlot.Edge.Bottom);

            ScottPlot.WPF.WpfPlot wpfPlot = new();
            wpfPlot.Reset(plot);
            System.Windows.Window win = new() { Content = wpfPlot };
            win.ShowDialog();
        }
    }
}
```

And it works well. 

I suggest:

1. Fix function name: `ToOATime()` should be `ToOADate()`
2. Making an update to https://scottplot.net/cookbook/5.0/Scatter/ScatterDateTime/ to **add an example how to mix it with regular double values on x axis**
3. Somewhere in the documentation or in code (for curious minds) (or as a comment to this issue) explain how the generic automatically converts `DateTime` to `double`?

This is great library and I've been bugging you guys lately😂  
Thanks!

**Comment by swharden** [comment]
Hi @chaojian-zhang, thanks so much for bringing this up! I'll work to make that FAQ page describe the newer/simpler way to manage dates with ScottPlot.

For now, note that this is possible, and it doesn't require converting dates to doubles:

```cs
DateTime[] dates = Generate.DateTime.Days(100);
double[] ys = Generate.RandomWalk(100);
plot.Add.Scatter(dates, ys);
```

https://scottplot.net/cookbook/5.0/DateTimeAxes/

**Comment by swharden** [comment]
following-up, the information on https://scottplot.net/faq/datetime/ is specific to ScottPlot 4.1, but the current version of ScottPlot is 5.0 which has better support for DateTime which is why we don't need to do the complicated conversion to double anymore.

That FAQ page is out of date, and there's a banner at the top indicating that, but I'll make it a priority to update it and close this issue after I do 👍

**Comment by swharden** [comment]
> 1. Fix function name: `ToOATime()` should be `ToOADate()`

Done! 🚀

> 2. Making an update to https://scottplot.net/cookbook/5.0/Scatter/ScatterDateTime/ to **add an example how to mix it with regular double values on x axis**

> 3. Somewhere in the documentation or in code (for curious minds) (or as a comment to this issue) explain how the generic automatically converts `DateTime` to `double`?

Since 2 and 3 are similar, we can solve both by creating a cookbook recipe demonstrating how to convert `DateTime[]` to `double[]` using `ToOADate()` and demonstrate plotting the two types of data together

**Comment by chaojian-zhang** [comment]
Awesome as usual!

**Comment by swharden** [comment]
I'm adding this cookbook recipe

```cs
// create an array of DateTimes one hour apart
int numberOfHours = 72;
DateTime[] dateTimes = new DateTime[numberOfHours];
DateTime startDateTime = new(2024, 1, 1);
TimeSpan deltaTimeSpan = TimeSpan.FromHours(1);
for (int i = 0; i < numberOfHours; i++)
{
    dateTimes[i] = startDateTime + i * deltaTimeSpan;
}

// create an array of doubles representing the same DateTimes one hour apart
double[] dateDoubles = new double[numberOfHours];
double startDouble = startDateTime.ToOADate(); // days since 1900
double deltaDouble = 1.0 / 24.0; // an hour is 1/24 of a day
for (int i = 0; i < numberOfHours; i++)
{
    dateDoubles[i] = startDouble + i * deltaDouble;
}

// now both arrays represent the same dates
myPlot.Add.Scatter(dateTimes, Generate.Sin(numberOfHours));
myPlot.Add.Scatter(dateDoubles, Generate.Cos(numberOfHours));
myPlot.Axes.DateTimeTicks(Edge.Bottom);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/382e465f-0dcc-438c-959f-fc199f69739b)

**Comment by bukowa** [comment]
How does it work with bars? `Plot.Add.Bars`
