### ISSUE TITLE
Controls: how to dispose properly?

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3271]
For applications which dynamically create and dispose of plot controls, what is the best way to ensure memory is properly freed?

Question from Marvin in the Discord

**Comment by devbotas** [comment]
Implement `IDisposable` interface? End-user is still responsible for remembering to call `Dispose()`, though.

However if plot control does not use timers or other unmanaged resources, GC will eventually clean it up. The caveat is that it is not always clear if unmanaged resources are in use.

**Comment by swharden** [comment]
@devbotas is correct, and `ScottPlot.Plot` implements `IDisposable` so you can call `Plot.Dispose()` as a control is being removed... but when/how that happens seems to be platform specific.

It's worth noting that disposing this stuff is the job of the garbage collector and it's done automatically. We probably don't need to be managing this ourselves. However, we probably can, so let's look into it:

**WinForms:** We can call `Plot.Dispose()` when the [`OnHandleDestroyed`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.onhandledestroyed?view=windowsdesktop-8.0&redirectedfrom=MSDN#System_Windows_Forms_Control_OnHandleDestroyed_System_EventArgs_) event is invoked

**WPF:** There doesn't seem to be a similar event or override for WPF controls. There's the [`Unloaded`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.unloaded?view=windowsdesktop-8.0) event which is close, but a control can be unloaded from one thing and loaded into another, so it's not a good idea to manually dispose the plot in response to that event. I'm not sure what to do for WPF.

I'm a bit scared to take any action right now. I think if users want to remove controls programmatically and don't want the garbage collector to dispose of the items, users can manually call things like `formsPlot1.Plot.Dispose()` and hope no additional render requests come in
