### ISSUE TITLE
How to change label format when DateTime XAxis in v5 ?

### ISSUE THREAD

**Issue by stratdev3** [ScottPlot/ScottPlot#3272]
Hi,

In v4 i have the following code to change the default label of datetime from iso "yyyy-mm-dd" to "MMMM" month name.

```cs
plt.XAxis.TickLabelFormat("MMMM", dateTimeFormat: true);
plt.SetCulture(CultureInfo.CreateSpecificCulture("fr"));
```

I don't see anythong related in the v5 cookbook and `ScottPlot.TickGenerators.DateTimeFixedInterval()` does not have a `LabelFormatter` property the [NumericAutomatic ](https://scottplot.net/cookbook/5.0/CustomizingTicks/) has.

So : Does it supported in v5 ?

Thanks for help

**Comment by swharden** [comment]
Thanks for this question @stratdev3! I'm adding the following cookbook example:

```cs
// plot sample DateTime data
DateTime[] dates = Generate.DateTime.Days(100);
double[] ys = Generate.RandomWalk(100);
myPlot.Add.Scatter(dates, ys);
myPlot.Axes.DateTimeTicksBottom();

// add logic into the RenderStarting event to customize tick labels
myPlot.RenderManager.RenderStarting += (s, e) =>
{
    Tick[] ticks = myPlot.Axes.Bottom.TickGenerator.Ticks;
    for (int i = 0; i < ticks.Length; i++)
    {
        DateTime dt = DateTime.FromOADate(ticks[i].Position);
        string label = $"{dt:MMM} '{dt:yy}";
        ticks[i] = new Tick(ticks[i].Position, label);
    }
};
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/4417349b-30f9-4ad9-86d4-b17f95115719)

**Comment by stratdev3** [comment]
@swharden Thanks for your answer, that's perfect !

At least, i don't know if it's a regression but the label is crop when using with rotation.

v4 : OK
![image](https://github.com/ScottPlot/ScottPlot/assets/115271718/9611ddd4-480b-40ec-80da-c018d8442ada)

v5 : ERROR, **image crop, we don't see labels when rotated**
![image](https://github.com/ScottPlot/ScottPlot/assets/115271718/4f6c5ff1-56a9-4fc3-af2f-96200fa6361f)

Your thought ?

**Comment by swharden** [comment]
Thanks for reporting this!

I think there's a layout tool you can use to add more padding similar to this in ScottPlot 4 https://scottplot.net/cookbook/4.1/recipes/layout_plot/

But it really should be documented in the cookbook. I'll figure it out later and follow up here 👍

**Comment by swharden** [comment]
Maybe try

```cs
ScottPlot.Plot myPlot = new();
myPlot.Add.Scatter(dataX, dataY);

myPlot.Layout(bottom: 50); // Add 50 units of padding to the bottom

myPlot.SavePng("quickstart.png", 400, 300);
```

**Comment by stratdev3** [comment]
i will explore that and i close the issue as the main problem is solved.

Thanks for your time and opensourcing your project 🙏
