### ISSUE TITLE
Copyright: remove year (2018) or replace with a range (2018-2024)?

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3285]
This topic is minutia, but the fact the license is dated 2018 (when this repository was first made public) made me consider what the date should be. Should it be updated every year? If there are no code changes, no, but if there are code changes in later years it seems that the copyright date should be update to reflect that, but updating license files all the time seems incorrect.

It seems MIT licensed official dotnet libraries have no date
* https://github.com/dotnet/maui/blob/main/LICENSE.txt
* https://github.com/dotnet/runtime/blob/main/LICENSE.TXT

According to the [U.S. Code § 401 - Notice of copyright: Visually perceptible copies](https://www.law.cornell.edu/uscode/text/17/401):
_The year date may be omitted where ... accompanying text matter ... is reproduced in ... useful articles_ which I think is covered by the date of the latest commit? I guess the git history could be modified so maybe that's not it.

I wish I knew more about this topic. I won't make any changes to the copyright notice without knowing more.

**Comment by swharden** [comment]
... one more idea, we can use a range (suggested by this Using a date range from the first year of publication, then at the beginning of every year. website)

`Copyright (c) 2018-2024 <NAME>`

**Comment by swharden** [comment]
The [Free Software Foundation (FSF) has some guidance](https://www.gnu.org/licenses/gpl-howto.html) which is probably more authoritative

> The copyright notice should include the year in which you finished preparing the release (so if you finished it in 1998 but didn't post it until 1999, use 1998). You should add the proper year for each past release; for example, “Copyright 1998, 1999 Terry Jones” if some releases were finished in 1998 and some were finished in 1999. If several people helped write the code, use all their names.
> 
> For software with several releases over multiple years, it's okay to use a range (“2008-2010”) instead of listing individual years (“2008, 2009, 2010”) if and only if every year in the range, inclusive, really is a “copyrightable” year that would be listed individually; and you make an explicit statement in your documentation about this usage.

**Comment by swharden** [comment]
I'm going to close this for now and not burn more energy thinking about it

It probably doesn't matter because the copyright notice is distinct from the license (MIT)

I like the fact the license file is unmodified since the creation of this repository, so I'll leave things as they are

**Comment by swharden** [comment]
> We don't put dates in our licenses.
> -[Rich Lander](https://github.com/richlander), .NET Team

https://github.com/microsoft/dotnet/issues/181

**Comment by swharden** [comment]
Related, https://github.com/PowerShell/DscResources/issues/298

**Comment by swharden** [comment]
Related, https://opensource.guide/legal/

**Comment by swharden** [comment]
Ha, this is all over the place https://github.com/github/choosealicense.com/commits/gh-pages/LICENSE.md

**Comment by swharden** [comment]
Related, I opened https://github.com/github/choosealicense.com/pull/1182 to update the copyright notice for choosealicense.com which is out of date (ironic, lol) but maybe pointing out this issue there will gain some visibility.

**Comment by nivintw** [comment]
Just wanted to say thanks; I happened across this randomly while trying to think this through for my own license files / copyright years. It's super valuable to see your thoughts and the links you posted.

**Comment by swharden** [comment]
> Just wanted to say thanks; I happened across this randomly while trying to think this through for my own license files / copyright years. It's super valuable to see your thoughts and the links you posted.

Yay! I'm happy you found this useful 😁
