### ISSUE TITLE
SP5: Slice Labels

### ISSUE THREAD

**Issue by sterenas** [ScottPlot/ScottPlot#3295]
Pie charts currently don't support slice labels just like SP4 has. A pie chart without value/% labels is difficult to interpret. SP4 has the following available, perhaps bring SP5 to parity on this is a good first shot:
 .SliceLabels = labels
 .ShowPercentages = True
 .SliceLabelPosition = 0.62

**Comment by swharden** [comment]
Thanks for the suggestion @sterenas! This is being added into the next release

```cs
PieSlice slice1 = new() { Value = 5, FillColor = Colors.Red, Label = "Red" };
PieSlice slice2 = new() { Value = 2, FillColor = Colors.Orange, Label = "Orange" };
PieSlice slice3 = new() { Value = 8, FillColor = Colors.Gold, Label = "Yellow" };
PieSlice slice4 = new() { Value = 4, FillColor = Colors.Green, Label = "Green" };
PieSlice slice5 = new() { Value = 8, FillColor = Colors.Blue, Label = "Blue" };
List<PieSlice> slices = new() { slice1, slice2, slice3, slice4, slice5 };

// setup the pie to display slice labels
var pie = myPlot.Add.Pie(slices);
pie.ExplodeFraction = .1;
pie.ShowSliceLabels = true;
pie.SliceLabelDistance = 1.3;

// styling can be customized for individual slices
slice5.LabelStyle.FontSize = 22;
slice5.LabelStyle.ForeColor = Colors.Magenta;
slice5.LabelStyle.Bold = true;
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/7ee4d6fd-d475-4d12-aa72-96fb46da8ed3)

**Comment by sterenas** [comment]
Scott, are we mixing slice labels with the legend here?  In SP4 we can show the label values or percentages per slice and a different legend (see enclosed screenshot), this fix seems to allow showing the legend with the pie slice but not the actual values/percentages?  Please let me know if it's not clear and I'll ellaborate.

![image](https://github.com/ScottPlot/ScottPlot/assets/6345155/78081e15-01b8-4567-aa63-ce3cc2a883a5)

**Comment by Martin12350** [comment]
The PieSlice actually has both properties, but unfortunately the one affects the second :/
```cs
public class PieSlice : LabelStyleProperties, IHasLegendText, IHasLabel
{
   public string Label { get => LegendText; set => LegendText = value; }
   public string LegendText { get => LabelStyle.Text; set => LabelStyle.Text = value; }
   ...
}
```
So now there is no way, to have Label with value and Legend with text, as shown in the picture.

**Comment by LeaFrock** [comment]
> but unfortunately the one affects the second

Is it a bug that should be fixed?
