### ISSUE TITLE
SP5 WinUI: Error on SKXamlCanvas.OnUnloaded

### ISSUE THREAD

**Issue by hockerschwan** [ScottPlot/ScottPlot#3299]
**Issue:**
1. Open window
1. Pan and close window
1. System.NullReferenceException: 'Object reference not set to an instance of an object.'
```cs
// SKXamlCanvas.cs
private void OnUnloaded(object sender, RoutedEventArgs e)
{
    loadUnloadCounter--;
    if (loadUnloadCounter == 0)
    {
        base.XamlRoot.Changed -= OnXamlRootChanged; // <- base.XamlRoot is null
        FreeBitmap();
    }
}
```

If you just open window and close it immediately, this won't happen.

**ScottPlot Version:**
ScottPlot.WinUI 5.0.20

**Code Sample:**
```xaml
<Window
    ...
    xmlns:SP5="using:ScottPlot.WinUI">
    <Grid>
        <SP5:WinUIPlot x:Name="WinUIPlot1" />
    </Grid>
</Window>
```
```cs
public MainWindow()
{
    InitializeComponent();

    WinUIPlot1.Plot.Add.Signal(Generate.Sin(51));
    WinUIPlot1.Plot.Add.Signal(Generate.Cos(51));
    WinUIPlot1.Refresh();
}
```

https://github.com/ScottPlot/ScottPlot/assets/80553357/d9f75d0b-20b2-4c28-a6c6-7c6e11d5da7e

**Comment by hockerschwan** [comment]
If you just open window and close it immediately, this won't happen.

**Comment by swharden** [comment]
Thanks for pointing out this issue @hockerschwan! I'll ping @rafntor (the creator of the WinUI control) to see if they have any suggestions

**Comment by rafntor** [comment]
This looks to me like an error outside ScottPlot, in SkiaSharp - [here](https://github.com/mono/SkiaSharp/blob/9274aeec807fd17eec2a3266ad4c2475c37d8a0c/source/SkiaSharp.Views/SkiaSharp.Views.WinUI/SKXamlCanvas.cs#L137).

I dont see what we could do to fix it, unless maybe require a newer version of Skia - if that solves anything? (I notice the current code in Skia is changed so it could potentially help to bump that dependency .. but I am just guessing here)

**Comment by swharden** [comment]
> This looks to me like an error outside ScottPlot, in SkiaSharp

Oof, that's not an easy fix from our end! Thanks so much for looking into this. Maybe it's worth opening an issue over at https://github.com/mono/SkiaSharp/issues ?

> require a newer version of Skia

I'll ensure that ScottPlot continues to use the latest version of the SkiaSharp controls 👍 

Thanks again for your feedback!

**Comment by swharden** [comment]
> maybe require a newer version of Skia

It looks like we use wildcard versions to always build using the latest version published on NuGet 🤷 

https://github.com/ScottPlot/ScottPlot/blob/ddfe61b5552509a5dafe1d90bc9a7f52e76712a7/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WinUI/ScottPlot.WinUI.csproj#L50

https://github.com/ScottPlot/ScottPlot/blob/ddfe61b5552509a5dafe1d90bc9a7f52e76712a7/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WinUI/ScottPlot.WinUI.csproj#L57

The good news is that when SkiaSharp fixes the bug, ScottPlot will get the fix automatically 😅
