### ISSUE TITLE
SP5 WinForms: Designer crashes on .NET Framework

### ISSUE THREAD

**Issue by MaxFun** [ScottPlot/ScottPlot#3300]
**Issue:** (Describe the bug here) When dragging the 'FormsPlot' from ScottPlot.WinForms in the toolbox, I get the following error

![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/599393db-1093-4a73-9ff0-423ea8122a52)
![Error Image 1-25-24](https://github.com/ScottPlot/ScottPlot/assets/3932952/233c198b-7cc1-445f-a070-f3c5bb297c57)

Any suggestions how to fix?

Running Windows 11 Pro 23H2
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.8.5 

**ScottPlot Version:** (What NuGet package are you using?) ScottPlot.WinForms 5.0.20

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
ScottPlot.Plot myPlot = new();
/* code to reproduce the bug */
myPlot.SavePng("bug.png");
```

**Comment by KroMignon** [comment]
@MaxFun according to the error dialog, it seems that Visual Studio cannot find Skia DLLs.

A workaround for this issue is the add the control manually ==> https://scottplot.net/faq/add-winforms-programmatically/

**Comment by MaxFun** [comment]
Tried the workaround it has an error, 
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/ce36c0a2-e391-4eac-8d15-c895bacd9c3a)
Does this mean ScottPlot no longer works with .NET Framework ?

**Comment by swharden** [comment]
Hi @MaxFun, 

ScottPlot supports .NET Framework back to 4.6.2

The problem is that the C# syntax in your code is newer than the C# version your project is using. If your project has a .csproj file you can edit it and add `<LangVersion>12</LangVersion>` https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#edit-the-project-file

Or you can modify that line to use the old syntax:
```cs
FormsPlot formsPlot1 = new FormsPlot() { Dock = DockStyle.Fill };
```

**Comment by swharden** [comment]
@MaxFun also, I suspect the fix can be applied automatically if you click the link shown in your screenshot

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/cd143f94-d21d-4b0f-86b0-bf21c41b65f5)

**Comment by MaxFun** [comment]
There seem to be some confusion. The project was band new, started from scratch. 
Just test, I started another new project
Windows 11 Pro Version	23H2
Microsoft Visual Studio Community 2022 (64-bit) - Version 17.8.5
.NET Framework 4.8.1 

![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/ace81a08-6ced-41e7-ab57-d7559321aea6)

On the Form1.cs[Design] I added a label, toolbox and a timer1. From the toolbox I dragged a FormPlot from the ScottPlot.WinForms and got the error 
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/fdcf6578-2b6f-4d2a-97b5-7d9b3df5c9dc)

Next I tried the workaround for this issue of adding the control manually ==> https://scottplot.net/faq/add-winforms-programmatically/

Got the The same error
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/7d02b77e-dd23-494f-85a6-97c35c99d115)

Did the potential fix
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/59787299-c074-476f-8a79-34283d8af390)

and got the same error
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/90e8f708-0f91-4a6f-a4f7-42b92219d976)

Tried to zip the solution folder, but it was to big to attach(63MB)

Any suggestions?

**Comment by swharden** [comment]
Hi @MaxFun, thanks for coming back with additional detail! I was able to recreate this issue...

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/9d7fb332-939b-4ff7-9687-9e6b15dcd567)

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/4ef4afbf-eb70-4bd7-84a6-3e5382c9371b)

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/cf278f1b-88d1-4f55-a302-e0e7eef03de9)

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/f0c23b04-7aaf-4853-a869-30cb71b4ff76)

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Warning		Found conflicts between different versions of "System.Runtime.InteropServices.RuntimeInformation" that could not be resolved.
There was a conflict between "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
    "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
    References which depend on "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Users\scott\source\repos\WindowsFormsApp31\packages\System.Runtime.InteropServices.RuntimeInformation.4.3.0\lib\net45\System.Runtime.InteropServices.RuntimeInformation.dll].
        C:\Users\scott\source\repos\WindowsFormsApp31\packages\System.Runtime.InteropServices.RuntimeInformation.4.3.0\lib\net45\System.Runtime.InteropServices.RuntimeInformation.dll
          Project file item includes which caused reference "C:\Users\scott\source\repos\WindowsFormsApp31\packages\System.Runtime.InteropServices.RuntimeInformation.4.3.0\lib\net45\System.Runtime.InteropServices.RuntimeInformation.dll".
            System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL
    References which depend on "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [].
        C:\Users\scott\source\repos\WindowsFormsApp31\packages\ScottPlot.5.0.20\lib\net462\ScottPlot.dll
          Project file item includes which caused reference "C:\Users\scott\source\repos\WindowsFormsApp31\packages\ScottPlot.5.0.20\lib\net462\ScottPlot.dll".
            ScottPlot, Version=5.0.20.0, Culture=neutral, PublicKeyToken=86698dc10387c39e, processorArchitecture=MSIL
            ScottPlot.WinForms, Version=5.0.20.0, Culture=neutral, PublicKeyToken=86698dc10387c39e, processorArchitecture=MSIL
        C:\Users\scott\source\repos\WindowsFormsApp31\packages\SkiaSharp.2.88.7\lib\net462\SkiaSharp.dll
          Project file item includes which caused reference "C:\Users\scott\source\repos\WindowsFormsApp31\packages\SkiaSharp.2.88.7\lib\net462\SkiaSharp.dll".
            SkiaSharp, Version=2.88.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756, processorArchitecture=MSIL
            ScottPlot, Version=5.0.20.0, Culture=neutral, PublicKeyToken=86698dc10387c39e, processorArchitecture=MSIL
            ScottPlot.WinForms, Version=5.0.20.0, Culture=neutral, PublicKeyToken=86698dc10387c39e, processorArchitecture=MSIL
            SkiaSharp.Views.Desktop.Common, Version=2.88.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756, processorArchitecture=MSIL
            SkiaSharp.Views.WindowsForms, Version=2.88.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756, processorArchitecture=MSIL	WindowsFormsApp31				
```

**Comment by swharden** [comment]
This issue may have been present for a while. It looks like even the .NET Framework sandbox app doesn't use the designer view...

https://github.com/ScottPlot/ScottPlot/blob/ddfe61b5552509a5dafe1d90bc9a7f52e76712a7/src/ScottPlot5/ScottPlot5%20Sandbox/Sandbox.WinFormsFramework/Form1.cs#L7-L25

Maybe we can fix this by not trying to render anything in the designer view for .NET Framework projects

**Comment by MaxFun** [comment]
Thanks for responding.
Being a hobbies programmer, not sure what you mean by "not trying to render anything in the designer view". Is there another way to render ScottPlots?

**Comment by swharden** [comment]
Hi @MaxFun, some of the notes are above are to help me figure out where the issue is. The main points are:

ScottPlot 5 crashes in .NET Framework WinForms _designer view_. The designer view is the preview window that's displayed in Visual Studio that lets you drag/drop controls on the window. Interestingly ScottPlot 5 works fine if you add it into your program "programmatically", as described below, and in a way that never lets it display in the visual studio designer view.

This works:

```cs
using System.Windows.Forms;

namespace WindowsFormsApp32
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            var fp = new ScottPlot.WinForms.FormsPlot() { Dock = DockStyle.Fill };
            Controls.Add(fp);
        }
    }
}
```

I'll add a note about this on https://scottplot.net/quickstart/winforms/ and leave this issue open to try to arrive at a better long term solution. Thanks again for pointing out this issue!

**Comment by swharden** [comment]
@MaxFun one more tip, if you can create a .NET application (not a .NET Framework application) it should work right out of the box! 👍 ".NET Framework" is an older style of .NET which doesn't have as many features

**Comment by MaxFun** [comment]
Thanks, the manually defining the plot worked great,  how I will have to learn how to set all the parameters.
Plan to try the  .NET application next which should be a lot less work.
Thanks again

**Comment by swharden** [comment]
I think this may have been solved by 587560dfbd14054def578a0fc360c4c0f6c665ab but I'm going to open this issue back up to remind me to follow-up after the next release is published on NuGet to be sure

**Comment by MaxFun** [comment]
Tried the .NET application and having a problem of the plot not ever showing data or title or axis names. Tried to adding rendering but get an error
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/6a613328-607e-4b71-bda7-e25c034cfeb7)

The code seem to be running, counter is counting just no plots. 
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/ca5387c5-ade2-4a2c-bf6b-a2e102bc7a09)

Any suggestions?

C#
Windows Application
.NET 8.0

**Comment by KroMignon** [comment]
@MaxFun you have done a little mistake.

The `render()` function of each `IPlottable` item is called by the root object (the `FormsPlot` instance in case of WinForm application).

The right call to refresh the plot would be `SenTempPlot.Refresh();`

**Comment by MaxFun** [comment]
I tried that first,  SenTempPlot.Refresh(); and it gave the same error message, so I commented it out and and tried sig1.Refresh(); which gave the same error message.
My code is in C# Windows Application .NET 8.0,  not WinForm  if I understand correctly.
Any recommendations?

**Comment by KroMignon** [comment]
I know, it is a little bit complicated, there are many backends!

First the .NET version you want to use:
- .NET Framework: 4.8.x
- .NET Core: 6.x or newer

Then the graphic backend:
- None / Console, only requires [ScottPlot](https://www.nuget.org/packages/ScottPlot) NuGet package
- Windows Forms ==> [ScottPlot.WinForms](https://www.nuget.org/packages/ScottPlot.WinForms)
- WPF ==> [ScottPlot.WPF](https://www.nuget.org/packages/ScottPlot.WPF)
- WinUI ==> [ScottPlot.WinUI](https://www.nuget.org/packages/ScottPlot.WinUI/)
- etc.

According to your screenshot, you have choose `WinForms` backend. Is this correct?
So I guess `SenTempPlot` is an instance of `ScottPlot.WinForms.FormsPlot` or what is it else?

**Comment by MaxFun** [comment]
This is the project's properties, I see it is Windows Forms which I assume is WinForms. 
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/97eb9aca-ab11-4f99-8231-2515597148da)

 This the NuGet package I installed
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/a2bf1a04-de1a-4624-9b90-42d78e648508)

I assume when I drug the "FormPlot(ScottPlot.WinForms)" from the toolbox, it is an instance of ScottPlot.WinForms.FormsPlot.

So am I using the correct stuff for ScottPlot?

**Comment by MaxFun** [comment]
Built a new C# Windows Forms App .NET 8.0 in VS2022
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/608a74e4-a101-49e3-b7d3-f77908cd155a)
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/5e7fb4d8-dbe0-4169-a36a-f81e00412214)
Installed ScottPlot.WinForms 5.0.21 from NuGet
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/7fcbdba0-73bf-4569-a9ec-12b6fb4517d3)
Dragged FormsPlot(ScottPlot.WinForms) from toolbox to Form1.cs(Design)
Added Scatter Plot code from https://scottplot.net/cookbook/5.0/ScottPlotQuickstart/QuickstartScatter/ 
ScottPlot.Plot myPlot = new();

double[] dataX = { 1, 2, 3, 4, 5 };
double[] dataY = { 1, 4, 9, 16, 25 };
myPlot.Add.Scatter(dataX, dataY);
myPlot.SavePng("demo.png", 400, 300);

Ran in debug
![image](https://github.com/ScottPlot/ScottPlot/assets/3932952/6e807edf-2a95-4cf3-8f48-a7703334aaa6)
There were no plotted points

**Comment by KroMignon** [comment]
Hello @MaxFun, I hope you are not too much frustrated.
I try to explain in a better way now (sorry I am not a English native speaker).

`ScottPlot` can be used ***without*** any graphic backend, like you have done with this code example:
```csharp
ScottPlot.Plot myPlot = new();

double[] dataX = { 1, 2, 3, 4, 5 };
double[] dataY = { 1, 4, 9, 16, 25 };
myPlot.Add.Scatter(dataX, dataY);
myPlot.SavePng("demo.png", 400, 300);
```
This will create a local `Plot` instance add scatter signal and save the result into a file (`demo.png`).

But this is ***not*** what you want to do!
You want to use a WinForm graphical control to display the plot output!
So you ***have to use the `Plot` from the `ScottPlot.WinForms.FormsPlot`*** (the control you have dragged on the Form).

Lets assume the control is called `formsPlot1`, the code would be:
```csharp

double[] dataX = { 1, 2, 3, 4, 5 };
double[] dataY = { 1, 4, 9, 16, 25 };

formsPlot1.Plot.Clear(); // remove all previous plottables

formsPlot1.Plot.Add.Scatter(dataX, dataY);
formsPlot1.Refresh();
```

**Comment by KroMignon** [comment]
> Thanks, that worked in the sample Scott Plot code project.

Yes I know, but what I try to explain to you is that the example codes are **not** directly usable in WPF / WinForms / WinUI, etc.
They are just here to show how to use a specific feature of `ScottPlot`, without any dependency to any possible backend.

> I will try using the Clear and Refresh in my original project

Once again, you are using `ScottPlot.WinForms` to show a plot on a Form.
The control `ScottPlot.WinForms.FormsPlot` contains a property called `Plot` which is an instance of `ScottPlot.Plot`.
You only have to setup this property to plot your data:
That's where the _magic_ happens 😉

**Comment by MaxFun** [comment]
I'm confused. I have use ScottPlots.WiinForms for years and built many projects with ScottPlot which worked and still run. 
I don't understand how to use " ScottPlot.WinForms.FormsPlot". 
What has change from early last year. What do you mean by "You only have to setup this property", what is this property, how do I set it up and how do I tell it which plot is being setup.

**Comment by KroMignon** [comment]
> I don't understand how to use "ScottPlot.WinForms.FormsPlot".
> What has change from early last year. 

If you have already used `ScottPlot.WinForms.FormsPlot`, using ScottPlot 5 should not be that complicated.

> What do you mean by "You only have to setup this property", what is this property, how do I set it up and how do I tell it which plot is being setup.

I have to apologies, my English is not very fluent, I sometimes not use the best words to describe things.

To say it in short sentences:
- `ScottPlot.Plot` is the main class which allows drawing grid, scatters, text, legend, etc.
- With `ScottPlot.Plot` you can draw this into a file (Bitmap, PNG, SVG...)
- `ScottPlot.WinForms.FormsPlot` is a WinForm control which **contains** an instance of `ScottPlot.Plot` and draw it on the control surface

All I want to say is that the code you have extract from the cookbook, use a new instance of `ScottPlot.Plot`. There is no reason why it should be rendered by the `ScottPlot.WinForms.FormsPlot` control.

If you want a `ScottPlot.WinForms.FormsPlot` instance to render a plot, you have to setup this instance.

Is it now comprehensible?

**Comment by MaxFun** [comment]
I will try what I think I understand.
Thanks for the help

**Comment by KroMignon** [comment]
> After ScottPlot 5 the above in a winfom project do not work and have to be modified

Yes, that is "normal" as `ScottPlot` 5 is a major rework of `ScottPlot` 4 with many of API breaks.

Maybe you have missed this page on documentation https://scottplot.net/faq/version-5.0/
You will find the major changes, but ScottPlot 5 is still under massive changes and many features from ScottPlot 4 are still not supported.

**Comment by MaxFun** [comment]
Thanks for the information

**Comment by BambOoxX** [comment]
> I think this may have been solved by [587560d](https://github.com/ScottPlot/ScottPlot/commit/587560dfbd14054def578a0fc360c4c0f6c665ab) but I'm going to open this issue back up to remind me to follow-up after the next release is published on NuGet to be sure

I just encountered this with ScottPlot 5.0.35 targeting .NET framework 4.8

**Comment by swharden** [comment]
Following-up, the recommended actions to take to solve this issue are here: https://scottplot.net/faq/add-winforms-programmatically/

**Comment by lk-davidegironi** [comment]
I've been able to upgrade my SP4 to SP5 on my <TargetFrameworks>net7.0-windows;net48</TargetFrameworks> application.
Still I have one working on the error list, related to OpenTK.GLControl, is there a way to solve it?

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Warning (active)	NU1701	Package 'OpenTK.GLControl 3.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0-windows7.0'. This package may not be fully compatible with your project.	LKCONLoopLib (net48), LKCONLoopLib (net7.0-windows)	D:\Projects\LKCON-ProtoSTM\VS\LKCONProtoSTM\LKCONLoopLib\LKCONLoopLib.csproj	1		
```
