### ISSUE TITLE
Error with WPF application

### ISSUE THREAD

**Issue by slotinvo** [ScottPlot/ScottPlot#3301]
**Question:** After updating to the latest version, my WPF application received an error: 

```
The file or assembly 'ScottPlot.WPF, Version=5.0.20.0, Culture=neutral, PublicKeyToken=null" 
or one of its dependencies could not be loaded. The specified file cannot be found.
```

Please tell me what could be the problem? I am using the library connection according to the instructions on your site.

**Comment by swharden** [comment]
Hi @slotinvo, 

If you follow the instructions on https://scottplot.net/quickstart/wpf/ and that error still occurs, it may be because you are using a very old version of Visual Studio. I suspect if you use the latest free version of Visual Studio Community it will function as expected.
