### ISSUE TITLE
Cookbook: add recipe to demonstrate Legend.Orientation 

### ISSUE THREAD

**Issue by sterenas** [ScottPlot/ScottPlot#3302]
With plt
      .Add.Bars(bars)
       .Legend.Orientation = Orientation.Horizontal
      .Legend.IsVisible = True
...
Works in SP4. SP5 is missing the ability to set Horizontal Legend Orientation which is very handy to prevent the legend to hide data.

**Comment by swharden** [comment]
Hi @sterenas, thanks for this suggestion! Legends do have an `Orientation` property now, but I'll leave this issue open to track creation of a cookbook recipe demonstrating this feature

**Comment by aespitia** [comment]
looks like horizontal legend orientation recipe is already in the cookbook

https://scottplot.net/cookbook/5.0/Legend/

**Comment by swharden** [comment]
https://scottplot.net/cookbook/5.0/Legend/LegendOrientation/
