### ISSUE TITLE
SP5: Add support for shading below/above line series plots

### ISSUE THREAD

**Issue by slotinvo** [ScottPlot/ScottPlot#3318]
**Question:** Hello! Version 4.1 had a FillBelow feature for signal grafics (https://scottplot.net/cookbook/4.1/recipes/signal_fillbelow/). Please tell me how to achieve the same graphics stylization in version 5.0?

**ScottPlot Version:** 5.0.20

**Code Sample:** var signal = ResultPlot.Plot.Add.SignalXY(dataX, dataY, ScottPlot.Color.FromHex(hexValue));

```cs
```

**Comment by swharden** [comment]
Hi @slotinvo, thanks for your question! That feature is not yet supported in ScottPlot 5 but I'll leave this issue open to track progress toward implementing it 👍

**Comment by swharden** [comment]
related: #3380

**Comment by swharden** [comment]
This feature was added in 829496b8e6cecffb38a68671ec36c389571fb236 and will be available in the next release 🚀 

```cs
var sp = myPlot.Add.Scatter(xs, ys);
sp.FillY = true;
sp.FillYValue = 0;
sp.FillYAboveColor = Colors.Green.WithAlpha(.2);
sp.FillYBelowColor = Colors.Red.WithAlpha(.2);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/835f2f89-7a89-4b8f-b7e0-416c5c93bf67)
