### ISSUE TITLE
Multi-Plot in ScottPlot 5.0

### ISSUE THREAD

**Issue by mrchipset** [ScottPlot/ScottPlot#3321]
Hi all,

I have found how to plot and handle multi-plot in ScottPlot 4.x. But it seems not suitable for 5.0.
[multiplot-faq-scott-plot](https://scottplot.net/faq/multiplot/)

Does anyone know the way to draw multi-plot with shared axes like this one with ScottPlot 5.0?
![image](https://github.com/ScottPlot/ScottPlot/assets/36813506/e96dbe16-4cf8-433c-befa-9b7c9862b177)

**Comment by swharden** [comment]
Hi @mrchipset, thanks for this question! The preferred strategy for multiple plots in ScottPlot 5 is to place multiple plot controls in your window and synchronize them as described on https://scottplot.net/faq/shared-axes/

There's an example for ScottPlot 5 on https://scottplot.net/demo/#shared-axes
