### ISSUE TITLE
Bar width control in pixel is not available

### ISSUE THREAD

**Issue by yosez** [ScottPlot/ScottPlot#3325]
I am using ScottPlot to build a WPF project. I am using BarSeries to create a bar plot, and it is required that the bar width should be set to a fixed pixel value (the width of the bar doesn't change when the window resizes), which is not supported by version 4.x of ScottPlot. I have been trying to solve this problem for almost one day, but I have found it difficult to do so, especially when I resize the window. I suggest that if possible, you could provide a feature to set the width of a bar with a pixel value. Thank you so much.

**Comment by swharden** [comment]
Hi @yosez, thanks for this question! I'm not sure if this feature was available when you first asked it, but this works now:

```cs
namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        double[] values = ScottPlot.Generate.RandomSample(10, 5, 25);
        var barPlot = formsPlot1.Plot.Add.Bars(values);

        formsPlot1.Plot.RenderManager.RenderStarting += (object? s, ScottPlot.RenderPack rp) =>
        {
            // this gets called just before each render
            double unitsPerPixel = barPlot.Axes.XAxis.Width / rp.DataRect.Width;
            float targetPixelWidth = 20;
            double barWidthUnits = targetPixelWidth * unitsPerPixel;

            foreach (var bar in barPlot.Bars)
            {
                bar.Size = barWidthUnits;
            }
        };
    }
}
```

![bar-width](https://github.com/ScottPlot/ScottPlot/assets/4165489/99f84f89-4b45-40bc-981d-f6f1d08582da)
