### ISSUE TITLE
How to show inverted x axis labels in v.5

### ISSUE THREAD

**Issue by jon-rizzo** [ScottPlot/ScottPlot#3330]
**Question:** I have created a plot with an inverted X axis.  Unfortunately, when I do this, the x axis labels are not shown. Is there a trick to getting these labels to appear? 

**ScottPlot Version:** 5.0.21

**Code Sample:** The v5 demo of inverted axes shows this behavior.  The v4 demo shows how to make the inverted (descending) axis labels to appear, but I can't figure out how to do this in v5.  

```cs
ScottPlot.Plot myPlot = new();

myPlot.Add.Signal(Generate.Sin());
myPlot.Add.Signal(Generate.Cos());

myPlot.Axes.AutoScaler.InvertedX = true;

myPlot.SavePng("demo.png", 400, 300);

```

**Comment by BrianAtZetica** [comment]
Resolved in my pull request #3401 (for my duplicate issue #3397)
