### ISSUE TITLE
Blazor support in SP4

### ISSUE THREAD

**Issue by bjschwarz** [ScottPlot/ScottPlot#3332]
**Question:** 
I ran into a show stopping issue when implementing SP5 in our app. The problem I reached is that SP5 uses SkiaSharp and SkiaSharp is not supported on blazor hybrid setups. So It will not work on the app in a mobile environment I get the error "SkiaSharp currently only works on web assembly".  The issue is linked here [https://github.com/mono/SkiaSharp/issues/1834](https://github.com/mono/SkiaSharp/issues/1834)

I am trying to figure out how to use SP4 in the blazor app but I haven't been able to find any documentation on how to set it up in a blazor file. Is this available in the repo somewhere but taken off of the website? Thanks!

**ScottPlot Version:**
4.1.71

**Comment by swharden** [comment]
Hi @bjschwarz, thanks for this observation!

Yes, I believe the interactive ScottPlot control only works in Blazor WebAssembly sites.

However, ScottPlot can plot data and generate images as PNG and JPG `byte[]` streams, so in theory I imagine you could dynamically generate images that you serve to the client.

I opened #3484 to track updating the ScottPlot.net website to make this information more discoverable 👍

**Comment by swharden** [comment]
> any documentation on how to set it up in a blazor file

It's not extensively documented yet, but this could help:
* https://swharden.com/tmp/sp/06/
* https://github.com/ScottPlot/ScottPlot/tree/main/src/ScottPlot5/ScottPlot5%20Sandbox/Sandbox.Blazor.WebAssembly

**Comment by swharden** [comment]
> I am trying to figure out how to use SP4

I'm just now realizing you may be asking about ScottPlot 4 😅 

ScottPlot 4 is definitely not supported in Blazor WebAssembly, but similar to the comment above it does have methods to let you generate plots as images and stream them to the client as static PNG or JPEG files.
