### ISSUE TITLE
How to add a Legend to DataLogger？

### ISSUE THREAD

**Issue by Yangjunfengx** [ScottPlot/ScottPlot#3336]
**Question:** (Ask your question here)

How to add a Legend to DataLogger？
There seems to be no Label property under the DataLogger class
There is a Label property under the Scatter class

**ScottPlot Version:** (What NuGet package are you using?)

5.0.21

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

**Comment by yusp75** [comment]
LegendItem item = new()
{
    LineColor = color,
    MarkerColor = color,
    LineWidth = 2,
    Label = name
};
Legends.Add(item);
Plot.ShowLegend(Legends, location: Alignment.UpperLeft);

**Comment by Yangjunfengx** [comment]
Thanks
