### ISSUE TITLE
PowerShell: How to use ScottPlot 5?

### ISSUE THREAD

**Issue by braggpeaks** [ScottPlot/ScottPlot#3343]
**Issue:** I get
`MethodInvocationException: Exception calling ".ctor" with "0" argument(s): "The type initializer for 'ScottPlot.Fonts' threw an exception."`
when trying to run the sample code.
Adding the .dll seems to have worked, I got type completion for e.g. [ScottPlot.Plot] in console and when using 
`Add-Type -Path .\ScottPlot.dll -PassThru`
I see all types loaded.

**ScottPlot Version:** 5.0.21 on PowerShell 7.4.0

**Code Sample:**

```ps
Add-Type -Path .\ScottPlot.dll
$plt = [ScottPlot.Plot]::new()
```

For the install I had to add this source (line 2), otherwise it did not find the package.

```
dotnet new console
dotnet nuget add source --name nuget.org https://api.nuget.org/v3/index.json
dotnet add package scottplot
dotnet build
```

What am I missing? Thank you.

**Comment by swharden** [comment]
Hi @braggpeaks, thanks for this question! It looks like you're following steps on https://scottplot.net/quickstart/powershell/

I'll see if @CarloToso has any input on this one... they have more experience than I do using ScottPlot with PowerShell!

I'll also rename this issue to hopefully attract attention from other PowerShell users 👍

**Comment by CarloToso** [comment]
@swharden @braggpeaks I was able to get it to work correctly; I'll write a guide later
