### ISSUE TITLE
UPDATE from 4.1 to 5.0

### ISSUE THREAD

**Issue by acorti79ITA** [ScottPlot/ScottPlot#3344]
**Question:** 
I updated the library form version 4.1.71 to 5.0.21 but some istructions seem not available.
Or sorry i didn't found in the cookbook

**ScottPlot Version:** 5.0.21

**Code Sample:** 
These two:

fpMain.Plot.XAxis.SetBoundary(0, 10);
fpMain.Plot.YAxis.SetBoundary(0);

And
fpMain.Plot.GetPlottables()[idxInput].IsVisible = true;

Thanks Alex

**Comment by FlyingChubbyFish** [comment]
try ``` fpMain.Plot.Axes... ```

**Comment by swharden** [comment]
This page summarizes the major differences between ScottPlot 4 and ScottPlot 5: https://scottplot.net/faq/version-5.0/
