### ISSUE TITLE
Change colorbar axis color in ScottPlot 5.0.

### ISSUE THREAD

**Issue by scalavia** [ScottPlot/ScottPlot#3346]
Is there a way to change axis color in a heatmap colorbar?
I found documentation for 4.1 but I can't find any information regarding this for 5.0.

**Comment by Excustic** [comment]
Hi, found a way:

        // Save the ColorBar object in a variable
        var bar = plot.Plot.Add.ColorBar(hm);
        // Create a new Heatmap and insert some arbitrary data like SampleData.MonaLisa()
        Heatmap hm1 = new Heatmap(data);
        // Adjust the colormap of this new heatmap to whatever you like, if you want to customize insert an array of colours + 1 more since it displays length-1 colours.
        hm1.Colormap = new ScottPlot.Colormaps.Custom(new Color[]{ new Color(1,1,1), new Color(124,124,124), new Color(240,240,240), new Color(240, 240, 240) });
        // Assign the ColorBar object you saved in a variable the new heatmap as its new source, this way it will insert the new colormap.
        bar.Source = hm1;

**Comment by swharden** [comment]
Thanks for the response @Excustic! If you think ScottPlot would benefit from a new cookbook recipe demonstrating this topic, I'd be happy to review a pull request!

I plan to work on the colorbar system soon (#3294) and definitely plan to have some more colorbar recipes on the website soon
