### ISSUE TITLE
Heatmap: add support for transparent cells

### ISSUE THREAD

**Issue by waacton** [ScottPlot/ScottPlot#3349]
**ScottPlot Version:** 5.0.21

**Question:** Can a polygon be used as a mask?

I'm using ScottPlot to demonstrate how my [colour library](https://github.com/waacton/Unicolour) can be used with ScottPlot to generate the classic CIE xy [chromaticity diagram](https://en.wikipedia.org/wiki/CIE_1931_color_space#CIE_xy_chromaticity_diagram_and_the_CIE_xyY_color_space), which was much easier than I expected 🎉

![xy-plot-without-imaginary](https://github.com/ScottPlot/ScottPlot/assets/3903062/901d60bf-b962-4e9e-a8f7-94c6f96fcee4)

My approach is brute force: convert every coordinate inside that black boundary to an RGB colour and draw a line around it, and that works fine. The only downside is that it's expensive to calculate if a coordinate is within that black boundary or not. My library will support it but it takes a couple of minutes for a million points.

For demonstration purposes, it would be a lot quicker for me to plot _all_ points and then use the black boundary polygon as a mask, with everything outside the boundary removed. Is this possible?

![xy-plot-with-imaginary](https://github.com/ScottPlot/ScottPlot/assets/3903062/da5ac687-6911-41e9-8e6c-b712fffeccad)

I'm not even sure if it's something that a plotting library should support, but thought it was worth asking in case I missed something!

**Comment by swharden** [comment]
Hi @waacton, thanks for this question! As a colorblind scientist interested in generating perceptually uniform gradients, I appreciate the work of people who understand color 😄 

I'd love to help you find a solution here! ScottPlot 4 had a feature that allowed polygons to clip heatmaps: https://scottplot.net/cookbook/4.1/recipes/heatmap_clipping/

If we added clipping support to heatmaps, do you think it would do the trick? 

If you are inspired to give it a go, I'd be happy to review a pull request! If you're not interested in trying to make this change yourself, we could see if @BrianAtZetica is interested (they recently added some great features to heatmaps which will be in the next release)

**Comment by swharden** [comment]
... following-up, wow! I just looked over https://github.com/waacton/Unicolour and the stuff you're doing there is fantastic!

@KroMignon recently added basic RGB color interpolation (#3443), but it would be awesome to some day use some of these color theory concepts to make a perceptually-even interpolated ranges of colors for palettes (for categorical data) and colormaps (for continuous data).

**Comment by waacton** [comment]
Thanks for the kind words @swharden!

I'd be more than happy to contribute to ScottPlot with colour palettes and colourmap generation if there was something you could direct me towards, would love to contribute if I can.

You could also use [Unicolour](https://github.com/waacton/Unicolour) directly for interpolating through non-RGB spaces (e.g. `Oklch` should be largely perceptually uniform while also transitioning through hue) since it handles all the edge cases I can think of, but of course depends on how you feel about third party libraries, whether it impacts performance too much, etc.

Re: clipping, I would let @BrianAtZetica have a go first if they're willing since I don't know how different heatmaps are to just "a whole bunch" of basic plottables, and whether it would need a new concept of 'layers' of plottables and so on 😅. However, if I get some time and the ticket is still open, I might dive into that part of the codebase and take a look.

**Comment by BrianAtZetica** [comment]
@swharden. I'm also a colorblind scientist with a passion of perceptually ballanced colour scales! In my field (geophysics) seeing false boundaries in a colourscale leads to bad interpretation of data. Since becoming aware of perceptually balanced colour scales from a blog by Matteo Niccoli (https://mycartablog.com/2013/02/21/perceptual-rainbow-palette-the-method/) I've spread the use of his CubeYB colour pallete across our company. 

But I digress. Thanks a lot for the mention, and suggestion that I might tackle heatmap cropping. I was thinking its quite a stretch for my capabiltiies, but I do love a challenge. 

I've just submitted PR #3499, which introduces transparancy to heatmaps. I think this could be used for cropping. In fact, it could be used imediately, if the logic of testing which cells are inside the polygon is performed outside of ScottPlot). If we want the enclosure test to be done within ScottPlot, then there is more work to do. 

I dont think I'll tackle that in the near future, but could perhaps have a go over the next 2 to 3 weeks if not picked up by someone else.

**Comment by swharden** [comment]
> transparancy to heatmaps. I think this could be used for cropping

Hi @BrianAtZetica, thanks for the added context! That blog article is pretty cool. I love the pyramid figure and how it demonstrates "false hotspots".

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/8ed6820f-5575-4f3b-b4f0-e788f79ef16b)

I saw something similar a while back where cardiologists looking at ESS angiograms were less effective at diagnosing heart disease using a rainbow colormap (the software default) vs. a perceptually uniform one. Bad colormaps can literally kill people! 🤯

> transparency to heatmaps

This got me thinking, maybe we could use a regular colormap and make `double.NaN` values in the 2D array transparent? That would be a pretty easy fix without dealing with polygons and cropping logic. I'm not sure what NaN values do now, but if we modified the heatmap class to make NaN cells transparent, that may be an easy fix!

**Comment by sdpenner** [comment]
I was just looking into this issue.  Is this already implemented, or is something more required?

```CS
                // Make NaN cells transparent
                if (double.IsNaN(Intensities[y, xIndex]))
                {
                    argb[rowOffset + x] = nanCellArgb;
                    continue;
                }
```

**Comment by swharden** [comment]
> I was just looking into this issue. Is this already implemented, or is something more required?

https://scottplot.net/cookbook/5.0/Heatmap/HeatmapTransparentCells/ 👍
