### ISSUE TITLE
SP4 DataStreamer: CountTotalOnLastRender is never updated

### ISSUE THREAD

**Issue by raburton** [ScottPlot/ScottPlot#3351]
CountTotalOnLastRender is always -1 in SP4, it's not updated in the Render method (looks like it will work in SP5, though haven't tested it).

**Comment by swharden** [comment]
Thanks for reporting this @raburton!

For context, the variable in question is here:
https://github.com/ScottPlot/ScottPlot/blob/ad66085d2086fbe3c744f5cb43cd04620517830d/src/ScottPlot4/ScottPlot/Plottable/DataStreamer.cs#L47

**Comment by raburton** [comment]
> It should be incremented at the end of this function:

I don't think it should incremented, or in that function.
CountTotalOnLastRender should be set to CountTotal at the bottom of the Render method:
https://github.com/ScottPlot/ScottPlot/blob/ad66085d2086fbe3c744f5cb43cd04620517830d/src/ScottPlot4/ScottPlot/Plottable/DataStreamer.cs#L203

In the same way as in v5:
https://github.com/ScottPlot/ScottPlot/blob/ad66085d2086fbe3c744f5cb43cd04620517830d/src/ScottPlot5/ScottPlot5/Plottables/DataStreamer.cs#L142-L146

**Comment by raburton** [comment]
Is v4 now out of support?

**Comment by swharden** [comment]
> Is v4 now out of support?

No, but my understanding is that very few people are actively developing with it, so I'm focusing virtually all of my effort on adding features to the current version of ScottPlot.

It's still supported though, so if someone creates a pull request to add this feature I would be happy to review it, merge it in, and publish a new package on NuGet 🚀
