### ISSUE TITLE
Rotating text to match a trend line

### ISSUE THREAD

**Issue by jon-rizzo** [ScottPlot/ScottPlot#3354]
It would be very useful if it was possible to tie a label's rotation to the slope of plot at a particular X/Y or between two specific data points (or even between ALL data points).  This would allow developers to place labels that "follow" a line, even if the view is resized/rescaled. 

![labels](https://github.com/ScottPlot/ScottPlot/assets/42001610/39060729-cf85-4597-809d-df81102ffb31)

**Comment by swharden** [comment]
Wow! This is a neat effect, but a bit of a niche use case. One way it could be achieved is to create a new plot type `ScatterPlotLabels` that has reference to a Scatter plot, and when its `Render()` method is called it reads the scatter plot's data to determine where to put labels and draws them. A flag could switch between labeling line segments vs. labeling points. 

There's some good information about creating custom plot types here https://scottplot.net/faq/custom-plot-type/ and although I don't intend to put my time into creating this plot type in the near future, I'd be happy to review a pull request and merge one in if you or someone else from the community creates it! 🚀
