### ISSUE TITLE
AvaPlot 5.0.21 - LockVerticalAxis not working on MacOS

### ISSUE THREAD

**Issue by rogerc** [ScottPlot/ScottPlot#3355]
Hi Scott,

Thanks for releasing ScottPlot. Great effort.

I'm using SP 5.0.21  with Avalonia on a Mac.  I've noticed that the API to LockVerticalAxis has changed in SP5 as its not in the Configuration object anymore. Is there a way to lock the vertical axis without having to use a key binding? Using the Candlestick plot.

I've tried setting the key binding  by casting the Interaction property to the object but doesnt seem to do anything.

```c#
((ScottPlot.Control.Interaction)GR0C0.Interaction).Inputs.LockVerticalAxisKey = ScottPlot.Control.Key.Alt;
```

Tried replacing the property but didnt do anything either. 
``` c#
var interaction = ((ScottPlot.Control.Interaction)avaPlot.Interaction);
interaction.Inputs.LockVerticalAxisKey = ScottPlot.Control.Key.Alt;
avaPlot.Interaction = interaction;
```

Is the _IPlotInteraction_ interface missing the _InputBindings_ property on purpose?

Thanks

Roger

**Comment by rogerc** [comment]
screenshot below shows the intellisense  not showing the option for Configuration.
![Screenshot 2024-02-10 at 13 36 38](https://github.com/ScottPlot/ScottPlot/assets/955105/1f50d5de-85e0-4a74-b7cf-bcc0ef4ad329)

**Comment by swharden** [comment]
Hi @rogerc, thanks for this question!

Axis locking behavior is now provided as an "axis rule". This system lets users create their own custom rules as well. Check out https://scottplot.net/demo/#axis-rules for more information and example source code 🚀
