### ISSUE TITLE
[Solved] ScottPlot 5 Linux TypeFace issues due to missing DLL

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3357]
> The type initializer for 'SkiaSharp.SKTypeface' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies.

I got this message when using ScottPlot 5 in an Azure Functions app running on a Linux server. Here's the full message, and it's a mess:

> Result: Failure Exception: System.TypeInitializationException: The type initializer for 'ScottPlot.Fonts' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKTypeface' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/libSkiaSharp.so: cannot open shared object file: No such file or directory /home/site/wwwroot/libSkiaSharp.so: cannot open shared object file: No such file or directory /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/liblibSkiaSharp.so: cannot open shared object file: No such file or directory /home/site/wwwroot/liblibSkiaSharp.so: cannot open shared object file: No such file or directory /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/libSkiaSharp: cannot open shared object file: No such file or directory /home/site/wwwroot/libSkiaSharp: cannot open shared object file: No such file or directory /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/liblibSkiaSharp: cannot open shared object file: No such file or directory /home/site/wwwroot/liblibSkiaSharp: cannot open shared object file: No such file or directory at SkiaSharp.SkiaApi.sk_typeface_ref_default() at SkiaSharp.SKTypeface..cctor() --- End of inner exception stack trace --- at SkiaSharp.SKTypeface.get_Default() at ScottPlot.Fonts.InstalledSansFont() at ScottPlot.Fonts..cctor() --- End of inner exception stack trace --- at ScottPlot.Fonts.get_Default() at ScottPlot.Label..ctor() at ScottPlot.Panels.TitlePanel..ctor() at ScottPlot.AxisManager..ctor(Plot plot) at ScottPlot.Plot..ctor() at ScottPlotStats.Plot.DownloadCount(CountDatabase db, Int32 width, Int32 height) in /home/runner/work/ScottPlotStats/ScottPlotStats/src/ScottPlotStats/Plot.cs:line 20 at ScottPlotStats.Functions.UpdateNugetStatsFunction.CreatePlots(CountDatabase db, BlobContainerClient containerClient) in /home/runner/work/ScottPlotStats/ScottPlotStats/src/ScottPlotStats.Functions/UpdateNugetStatsFunction.cs:line 80 at ScottPlotStats.Functions.UpdateNugetStatsFunction.Run(TimerInfo myTimer) in /home/runner/work/ScottPlotStats/ScottPlotStats/src/ScottPlotStats.Functions/UpdateNugetStatsFunction.cs:line 27 at lambda_method1(Closure, UpdateNugetStatsFunction, Object[]) at Microsoft.Azure.Functions.Worker.Invocation.VoidMethodInvoker'2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\VoidMethodInvoker.cs:line 22 at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker'2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31 at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45 at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13 at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77 at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88 Stack: at ScottPlot.Fonts.get_Default() at ScottPlot.Label..ctor() at ScottPlot.Panels.TitlePanel..ctor() at ScottPlot.AxisManager..ctor(Plot plot) at ScottPlot.Plot..ctor() at ScottPlotStats.Plot.DownloadCount(CountDatabase db, Int32 width, Int32 height) in /home/runner/work/ScottPlotStats/ScottPlotStats/src/ScottPlotStats/Plot.cs:line 20 at ScottPlotStats.Functions.UpdateNugetStatsFunction.CreatePlots(CountDatabase db, BlobContainerClient containerClient) in /home/runner/work/ScottPlotStats/ScottPlotStats/src/ScottPlotStats.Functions/UpdateNugetStatsFunction.cs:line 80 at ScottPlotStats.Functions.UpdateNugetStatsFunction.Run(TimerInfo myTimer) in /home/runner/work/ScottPlotStats/ScottPlotStats/src/ScottPlotStats.Functions/UpdateNugetStatsFunction.cs:line 27 at lambda_method1(Closure, UpdateNugetStatsFunction, Object[]) at Microsoft.Azure.Functions.Worker.Invocation.VoidMethodInvoker'2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\VoidMethodInvoker.cs:line 22 at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker'2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 31 at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45 at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13 at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77 at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88

**Comment by swharden** [comment]
https://stackoverflow.com/a/75402971 suggests "You can try install `SkiaSharp.NativeAssets.Linux.NoDependencies` NuGet package instead of `SkiaSharp`" 

Presently ScottPlot does this:
https://github.com/ScottPlot/ScottPlot/blob/4b0c2def9c34c4d575b49eff0a3a40464bd5e0f4/src/ScottPlot5/ScottPlot5/ScottPlot.csproj#L39-L52

... so maybe a fix is to use logic to _not_ install the `SkiaSharp` package on linux systems

**Comment by swharden** [comment]
Related/alternative strategy to consider, 

https://github.com/Azure/Azure-Functions/issues/622#issuecomment-1172470499

```xml
<Target Name="CopyFilesAfterPublish" AfterTargets="AfterPublish">
  <Copy SourceFiles="$(TargetDir)runtimes/linux-x64/native/libSkiaSharp.so" DestinationFolder="$([System.IO.Path]::GetFullPath('$(PublishDir)'))/bin/" />
</Target>
```

**Comment by swharden** [comment]
Was able to recreate this issue in GitHub Actions

```
Test method ScottPlotStats.Test.PlottingTests.Test_Plot_CountsOverTime threw exception: 
System.TypeInitializationException: The type initializer for 'ScottPlot.Fonts' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SkiaSharp.SKTypeface' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/libSkiaSharp.so: cannot open shared object file: No such file or directory
/home/runner/work/ScottPlotStats/ScottPlotStats/src/ScottPlotStats.Test/bin/Release/net8.0/libSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/home/runner/work/ScottPlotStats/ScottPlotStats/src/ScottPlotStats.Test/bin/Release/net8.0/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/libSkiaSharp: cannot open shared object file: No such file or directory
/home/runner/work/ScottPlotStats/ScottPlotStats/src/ScottPlotStats.Test/bin/Release/net8.0/libSkiaSharp: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/liblibSkiaSharp: cannot open shared object file: No such file or directory
/home/runner/work/ScottPlotStats/ScottPlotStats/src/ScottPlotStats.Test/bin/Release/net8.0/liblibSkiaSharp: cannot open shared object file: No such file or directory

  Stack Trace:
      at SkiaSharp.SkiaApi.sk_typeface_ref_default()
   at SkiaSharp.SKTypeface..cctor()
--- End of inner exception stack trace ---
    at SkiaSharp.SKTypeface.get_Default()
   at ScottPlot.Fonts.InstalledSansFont()
   at ScottPlot.Fonts..cctor()
--- End of inner exception stack trace ---
    at ScottPlot.Fonts.get_Default()
   at ScottPlot.Label..ctor()
   at ScottPlot.Panels.TitlePanel..ctor()
   at ScottPlot.AxisManager..ctor(Plot plot)
   at ScottPlot.Plot..ctor()
   at ScottPlotStats.Plot.DownloadCount(CountDatabase db, Int[32](https://github.com/swharden/ScottPlotStats/actions/runs/7858566196/job/21443711087#step:6:33) width, Int32 height) in /home/runner/work/ScottPlotStats/ScottPlotStats/src/ScottPlotStats/Plot.cs:line 18
   at ScottPlotStats.Test.PlottingTests.Test_Plot_CountsOverTime() in /home/runner/work/ScottPlotStats/ScottPlotStats/src/ScottPlotStats.Test/PlottingTests.cs:line 9
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by swharden** [comment]
I found a solution!

Linux users must add the `ScottPlot` package _and_ the `SkiaSharp.NativeAssets.Linux.NoDependencies` package

```xml
<ItemGroup>
    <PackageReference Include="ScottPlot" Version="5.0.21" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.*" />
</ItemGroup>
```

**Comment by IntegerMan** [comment]
For anyone else who gets here specifically looking to use it in a Polyglot Notebook on Linux, your step will be similar to @swharden's but you'll use a NuGet import instead:

```
#r "nuget:ScottPlot"
#r "nuget:SkiaSharp.NativeAssets.Linux.NoDependencies"
```

Note that you'll probably have to restart the notebook if you've already loaded ScottPlot previously

**Comment by swharden** [comment]
* https://github.com/ScottPlot/ScottPlot.NET/commit/236d90ae126440da939b89780694ba083bb7cf5a
* https://scottplot.net/quickstart/notebook/

**Comment by swharden** [comment]
Also, adding `SkiaSharp.NativeAssets.Linux.NoDependencies` may not be needed if #3481 delivers those files as anticipated 🤞
