### ISSUE TITLE
Problem with updated version 5.0.21

### ISSUE THREAD

**Issue by dusko23** [ScottPlot/ScottPlot#3362]
I have just updated to the new version 5.0.21

- ScotPlot
- ScotPlot.WinForms

Until now all updates were smooth.
This one seems to be problematic.
Please tell me what to do.

Below is a list of errors I got.

![image](https://github.com/ScottPlot/ScottPlot/assets/26789352/3234eb63-cfca-4c4c-b68a-aabfe5428439)

**Comment by yusp75** [comment]
using ScottPlot.WinForms;

By view the source code, you can find the right way to use it.

**Comment by dusko23** [comment]
I don't understand what you are suggesting.
I have been using ScottPlot for about two years. 
I made about 3 or 4 updates using NuGet, and everything was OK.
Yesterday I updated to
![image](https://github.com/ScottPlot/ScottPlot/assets/26789352/2aafc61b-95d4-4f13-b674-aca9b9cef4ce)
and immediate effect were errors I am getting now.
Please tell what might be the problem and what is the cure.

**Comment by KroMignon** [comment]
> Please tell what might be the problem and what is the cure.

I guess you are moving from ScottPlot 4.1.xx to 5.0.21.
ScottPlot 5 is a major rework and there are a lot of changes / API breaks in all modules.

You should also be aware that ScottPlot 5 is not function complete for now and there are many features which are still missed in v5.

Take a look at this [page](https://scottplot.net/faq/version-5.0/) for more details.

**Comment by dusko23** [comment]
Thanks for clearing up.
Yes, I have installed 5.0.21 from 4.x and run into problems.
It would be easier for the users if NuGet GUI would display Big and BOLD:

THIS VERSION IS MAJOR UPGRADE WITH LOADS OF API BREAKS.
YOUR EXISTING CODE WILL NOT WORK.
BE CAREFUL OF WHAT YOU ARE DOING. 
YOU WILL NEED TO DEVELOP MOST OF THE EXISTING FUNCTIONALITY FROM SCRATCH.

NuGet suggests version 5.0.21 as an upgrade.
But it is not an upgrade. It is a completely different product and should be shown as such in the NuGet environment.
It would mean that the Upgrade button from 4.X to 5.0.21 should not be there.

I have successfully reverted to the previous version and will stick to it.
I am aware that the support for 4.X will no longer be available at some point.

**Comment by swharden** [comment]
> NuGet suggests version 5.0.21 as an upgrade.
> But it is not an upgrade. It is a completely different product and should be shown as such in the NuGet environment.

I agree! The NuGet manager built into Visual Studio does not give library authors any way to alert the user "This is a new major version and may contain breaking changes". There are many banners that say this on https://ScottPlot.net, but that only helps people who find the website. 

I definitely consider this a deficiency of Visual Studio's NuGet interface.

**Comment by swharden** [comment]
If anyone ends up here from Google:

**1. Users do now need to upgrade existing projects from ScottPlot 4 to ScottPlot 5.**

**2. Upgrading is possible, but requires code changes described on https://scottplot.net/faq/version-5.0/**
