### ISSUE TITLE
Contour plot

### ISSUE THREAD

**Issue by jon-rizzo** [ScottPlot/ScottPlot#3365]
It would be awesome if ScottPlot could plot contours to help a user visualize Z values, similar to what you would see on a topographic map. I have a project that could benefit from this.  OxyPlot can do this, but I prefer ScottPlot!

**Comment by swharden** [comment]
Hi @jon-rizzo, thanks for the suggestion! This came up before in #2230, #2185, and #129. I probably won't put my personal time into creating this plot type right now, but I added some resources in those linked issues to help someone else add that feature, and if anyone opens a pull request I would be happy to review it! 🚀
