### ISSUE TITLE
FormsPlot: DPI scaling causes mouse tracking issues

### ISSUE THREAD

**Issue by Luukeluuke** [ScottPlot/ScottPlot#3366]
**Issue:** 
If you have selected a text scaling of e.g. 125% in Windows, elements such as the crosshair are no longer displayed in the correct places. They are displayed slightly offset.

**ScottPlot Version:**
ScottPlot.WPF 5.0.21

**Code Sample:**
```cs
private Crosshair? _tradeChartCrosshair;
TradeChart.MouseMove += (_, e) =>
{
    Point p = e.GetPosition(TradeChart);
    Coordinates mouseCord = TradeChart.Plot.GetCoordinates(new(p.X, p.Y));

    if (_tradeChartCrosshair is not null)
    {
        _tradeChartCrosshair.Position = mouseCord;
        TradeChart.Refresh();
    }
};
```

It would also be great if you could make the ticks on the axes independent of the Windows text scaling.

**Comment by swharden** [comment]
I think this has since been resolved
![tracker](https://github.com/user-attachments/assets/2211704d-5345-4068-8067-6ceb20ecd9c0)
