### ISSUE TITLE
Customizing NaN behavior in ScottPlot 5

### ISSUE THREAD

**Issue by FlyingChubbyFish** [ScottPlot/ScottPlot#3368]
**Question:** How to plot data with gaps in ScottPlot 5?
To customize NaN behavior, like in SocttPlot 4, using OnNaN property.

**ScottPlot Version:** 5.0.21

```cs
// In ScottPlot 4!!
scatter.OnNaN = ScottPlot.Plottable.ScatterPlot.NanBehavior.Gap;
```

**Comment by swharden** [comment]
Hi @FlyingChubbyFish, thanks for this question! This will be supported, but isn't yet. Progress will be tracked in #3276 👍
