### ISSUE TITLE
SP5: RandomDataGenerator.RandomNormalSample throws System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by DominicBeer** [ScottPlot/ScottPlot#3369]
https://github.com/ScottPlot/ScottPlot/blob/4b0c2def9c34c4d575b49eff0a3a40464bd5e0f4/src/ScottPlot5/ScottPlot5/RandomDataGenerator.cs#L143C26-L143C29

Should be < not <= 

I will probably make a fix and PR for this as it is a very simple fix. Will also likely add a test of some sort.

**Comment by swharden** [comment]
resolved in #3370
