### ISSUE TITLE
LockedVertical right axis or secondary axis doesn't work

### ISSUE THREAD

**Issue by Boris-Lebeau** [ScottPlot/ScottPlot#3374]
Hi Scott, thanks a lot for your great and useful work.

I have noticed a bug ever reported on Locked axis (horizontal or vertical) on SP5. I think there is another consequence of this bug : a problem when locking the right vertical axis (or locking a secondary axis) :

```cs
var sig1 = myPlot.Add.Signal(Generate.Sin(mult: 1));
var sig2 = myPlot.Add.Signal(Generate.Cos(mult: 100));

sig1.Axes.YAxis = myPlot.Axes.Left;
sig2.Axes.YAxis = myPlot.Axes.Right;

// No problem if sideAxis = PlotA.Plot.Axes.Left;
var sideAxis = myPlot.Axes.Right;
var rule = new ScottPlot.AxisRules.LockedVertical(sideAxis);
myPlot.Axes.Rules.Add(rule);
```

The use of Render() not seems to solve the problem in this case. 

Thanks for you help.
Boris

**Comment by BendRocks** [comment]
Yes, I see the same on this in Avalonia. ScottPlot 5.0.21 Demo Axis Rules section works as expected under WinForms, but if I move that same code into an Avalonia app, the axis doesn't lock. @Boris-Lebeau, are you using Winforms or other?

PS. It looks like 5.0.22 which came out last week didn't publish (it's not on Nuget) and the changelog indicates _Warning: NuGet package date is missing._

**Comment by BendRocks** [comment]
I don't know if fixed in 5.0.22 or not.

For anyone looking to repro, you can take the Ava sandbox example and do it there. Every time the LockedVertical.Apply() is called, the axis limits are updated, but at some point after the YAxis range getting set in Apply(), they get changed by the mouse drag. And then for the next time Apply() is called, the wrong values are applied. Seems like the LockedVerticalAxis.Apply() needs to be called earlier in the pipeline.

```
public partial class MainView : UserControl
{
    public MainView()
    {
        InitializeComponent();

        AvaPlot.Plot.Add.Signal(Generate.Sin());
        AvaPlot.Plot.Add.Signal(Generate.Cos());
        AvaPlot.Refresh();

        AvaPlot.Plot.Axes.Rules.Clear();

        ScottPlot.AxisRules.LockedVertical leftAxisRule = new ScottPlot.AxisRules.LockedVertical(AvaPlot.Plot.Axes.Left);
        AvaPlot.Plot.Axes.Rules.Add(leftAxisRule);

        AvaPlot.Refresh();
    }
}
```

**Comment by BendRocks** [comment]
I spent some more time on this today. If you set a breakpoint in ```Render()``` (inside ```RenderManager.cs```) at the first ```foreach()``` and single step through there for the ```CalculateLayout()``` and ```RegenerateTicks()``` actions, then the ```LockedVertical()``` works as expected. Inside the ```Render()``` method, the thread is running on the ```DwmRenderTimerLoop``` thread. And of course we know the Winforms code works. 

So, it seems like there's a threading issue here. But I don't understand the internals of Avalonia enough to know what is expected. 

Issue [3374](https://github.com/ScottPlot/ScottPlot/pull/3373) might be related???

**Comment by swharden** [comment]
Thanks for reporting this! I looked into it a little farther, and the error is here... with a `TODO` indicating the issue 🤦 

https://github.com/ScottPlot/ScottPlot/blob/ad66085d2086fbe3c744f5cb43cd04620517830d/src/ScottPlot5/ScottPlot5/AxisRules/LockedVertical.cs#L18-L21

The `yMin` and `yTop` are coming from the wrong axis... I think there's a new object in `Plot.LastRender` that has axis-specific limits, allowing code similar to this to work:

```cs
 double yMin = rp.Plot.LastRender.AxisLimitsByAxis[YAxis].Bottom; 
 double yMax= rp.Plot.LastRender.AxisLimitsByAxis[YAxis].Top; 
 YAxis.Range.Set(yMin, yMax); 
```

If someone wants to test this out and create a pull request I'd be happy to review and merge it in good time! If there's no movement here for a while, I'll fix it myself eventually 👍

**Comment by BendRocks** [comment]
I tried the following in ```LockedVertical.cs```

```
        double yMin = rp.Plot.LastRender.AxisLimitsByAxis[YAxis].Min;
        double yMax = rp.Plot.LastRender.AxisLimitsByAxis[YAxis].Max;
        YAxis.Range.Set(yMin, yMax);
```

No luck. The ```AxisLimitsByAxis``` keep getting updated which makes locking not work. Since this works in Winforms, it seems the issue here is a bit more tricky, doesn't it?

**Comment by Boris-Lebeau** [comment]
Nice, I have tested this issue, ant it works fine for me in WPF.

Thanks a lot.
