### ISSUE TITLE
Axis: add an option to draw in the center of the plot

### ISSUE THREAD

**Issue by ZTaiIT1025** [ScottPlot/ScottPlot#3377]
The default coordinate axis intersection point is in the bottom left corner. Can we set the coordinate axis intersection point position to be in the middle of the chart by setting properties

![Snipaste_2024-02-18_09-27-23](https://github.com/ScottPlot/ScottPlot/assets/38967376/9474795e-4029-4951-8847-acc4bf61e753)

**Comment by swharden** [comment]
Adding this feature in the next release 🚀 

```cs
// create floating X and Y axes using one of the existing axes for reference
ScottPlot.Plottables.FloatingAxis floatingX = new(myPlot.Axes.Bottom);
ScottPlot.Plottables.FloatingAxis floatingY = new(myPlot.Axes.Left);

// hide the default axes and add the custom ones to the plot
myPlot.Axes.Frameless();
myPlot.HideGrid();
myPlot.Add.Plottable(floatingX);
myPlot.Add.Plottable(floatingY);

// add sample data last so it appears on top
myPlot.Add.Signal(Generate.Sin(51));
myPlot.Add.Signal(Generate.Cos(51));
```

![image](https://github.com/user-attachments/assets/7c90a51e-4d5d-4674-bb05-a83e5a9fc3c7)
