### ISSUE TITLE
Add Footprint Chart

### ISSUE THREAD

**Issue by sirinath** [ScottPlot/ScottPlot#3378]
Can you add the ability add footprint charts: https://www.google.com/search?q=footprint+chart

This can be generalised to add footprints to other charts like bar and error chats.

This is essentially adding window with another chart and / or tables next to or with the marker of existing larger chart.

**Comment by swharden** [comment]
Hi @sirinath, thanks for the suggestion! I don't intend to do this myself soon, but you can create your own plot types as descibred in:

https://scottplot.net/faq/custom-plot-type/

If you create this plot type, I invite you to share it here by copy/pasting the code in this issue thread or creating a pull request! 🚀
