### ISSUE TITLE
Demo: Improve scrollwheel zoom vs. scroll example

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#338]
I got an email from Zach suggesting that ScottPlot mouse interactivity is odd when using the WpfPlot control inside a ScrollViewer:

> I recently added a scroll bar to my wpf app and noticed that, when I try to zoom in on the ScottPlots, the scrolling action simultaneously zooms in on the plot (slightly) and moves the scroll bar. This makes it difficult to zoom in, because I need to unscroll the scroll bar each time I try to zoom in a bit, such that zooming in a lot requires a lot of unscrolling.
>
> This is likely something I need to do on my end to disable the scroll bar when mousing over the plot and not something that can be addressed within ScottPlot. DataGrids, which are native to wpf, have this functionality. 
>
> ![image](https://user-images.githubusercontent.com/4165489/78826547-adc79f80-79af-11ea-8ec9-86993a8dec4a.png)

It might be good to figure out how to do this and add an example for the demo application.

**Comment by swharden** [comment]
I now better understand this problem. Typically the mouse scroll wheel moves the ScrollViewer up and down. It still does, but those scroll events are also getting detected as scroll-wheel-zoom events.

I will fix this by adding something like:
```cs
wpfPlot.Configure(enableScrollWheelZoom: false);
```

**Comment by saklanmazozgur** [comment]
Hello, 

Is there a solution for this problem other than canceling the zoom in and out?

**Comment by swharden** [comment]
Hi @saklanmazozgur, 

## Defining the Problem

> Is there a solution for this problem other than canceling the zoom in and out?

You can use the mouse scroll wheel to _scroll_ or to _zoom_ but not both at the same time.

If you choose to make the wheel scroll the window up and down, it cannot be used for zoom.

If you choose to make the wheel zoom in and out, the wheel cannot be used to scroll the window.

## Current Solution

Users who want the scroll wheel to scroll the window up and down (rather than zoom in and out) can disable scroll wheel zoom.

The API changed a bit since this issue was first posted. There is an example of this concept in the ScottPlot demo application https://swharden.com/scottplot/demo/

```cs
wpfPlot.Configuration.ScrollWheelZoom = false; 
```

https://github.com/ScottPlot/ScottPlot/blob/1f68020e0c874140cd668752cf9769398727c3a8/src/demo/ScottPlot.Demo.WPF/WpfDemos/PlotInScrollViewer.xaml#L9-L15

https://github.com/ScottPlot/ScottPlot/blob/1f68020e0c874140cd668752cf9769398727c3a8/src/demo/ScottPlot.Demo.WPF/WpfDemos/PlotInScrollViewer.xaml.cs#L24-L38

![image](https://user-images.githubusercontent.com/4165489/129040374-b03b963a-4265-496b-b0e2-7b243725e661.png)

**Comment by saklanmazozgur** [comment]
Hello, my problem is that both are used. I want it to be like you mentioned. I only want the graphic to zoom in and out when hovering over the graphic.

I have uploaded a sample video. I can share the code if you want. I am using homepage structure in MaterialDesignInXamlToolkit. As an example, we can take reference there.

Since I can't upload the video, I'm sharing it on another site.

[Video Link](https://streamable.com/n75piv)

**Comment by swharden** [comment]
## Improve Demo

> I only want the graphic to zoom in and out when hovering over the graphic.

I think the demo shows how to make the scrollwheel scroll (not zoom).

I can extend the demo to also show how to make the scrollwheel zoom (not scroll).

This may make it easier to figure out how to solve this problem.

## Demonstrating the Issue

> Since I can't upload the video, I'm sharing it on another site.

GitHub supports videos in comments 😉 

https://user-images.githubusercontent.com/4165489/129747262-c5c68274-47bf-4f73-857d-b378e677691a.mp4

**Comment by swharden** [comment]
Hi @saklanmazozgur,

This was harder than I expected to figure out, but I arrived at a solution that seems to work well!

![scroll](https://user-images.githubusercontent.com/4165489/130171499-8e92e1af-7641-42fd-9fc2-1f7b20df3fbd.gif)

```xaml
<ScrollViewer PreviewMouseWheel="ScrollViewer_PreviewMouseWheel">
    <StackPanel>
        <ScottPlot:WpfPlot Height="300" Name="wpfPlot1"/>
        <ScottPlot:WpfPlot Height="300" Name="wpfPlot2"/>
        <ScottPlot:WpfPlot Height="300" Name="wpfPlot3"/>
    </StackPanel>
</ScrollViewer>
```

```cs
private void ScrollViewer_PreviewMouseWheel(object sender, MouseWheelEventArgs e)
{
    ScrollViewer myScrollViewer = (ScrollViewer)sender;

    if (ScrollRadio.IsChecked.Value)
    {
        // manually scroll the window then mark the event as handled so it does not zoom
        double scrollOffset = myScrollViewer.VerticalOffset - (e.Delta * .2);
        myScrollViewer.ScrollToVerticalOffset(scrollOffset);
        e.Handled = true;
        return;
    }

    if (ZoomRadio.IsChecked.Value)
    {
        // manually scroll (zero offset) to complete the scroll action, then proceed to zooming
        myScrollViewer.ScrollToVerticalOffset(myScrollViewer.VerticalOffset);
        return;
    }
}
```

**Comment by swharden** [comment]
Following-up, in WinForms the same thing can be achieved a different way:

![scroll2](https://user-images.githubusercontent.com/4165489/130173575-4b12b833-d0c6-4486-9f5a-badacb9f3ec3.gif)

```cs
public PlotsInScrollViewer()
{
    InitializeComponent();

    Random rand = new Random();
    formsPlot1.Plot.AddSignal(DataGen.RandomWalk(rand, 100));
    formsPlot2.Plot.AddSignal(DataGen.RandomWalk(rand, 100));
    formsPlot3.Plot.AddSignal(DataGen.RandomWalk(rand, 100));

    formsPlot1.MouseWheel += FormsPlot_MouseWheel;
    formsPlot2.MouseWheel += FormsPlot_MouseWheel;
    formsPlot3.MouseWheel += FormsPlot_MouseWheel;
}

private void FormsPlot_MouseWheel(object sender, MouseEventArgs e)
{
    ((HandledMouseEventArgs)e).Handled = rbZoom.Checked;
}

private void rbScroll_CheckedChanged(object sender, EventArgs e)
{
    formsPlot1.Configuration.ScrollWheelZoom = false;
    formsPlot2.Configuration.ScrollWheelZoom = false;
    formsPlot3.Configuration.ScrollWheelZoom = false;
}

private void rbZoom_CheckedChanged(object sender, EventArgs e)
{
    formsPlot1.Configuration.ScrollWheelZoom = true;
    formsPlot2.Configuration.ScrollWheelZoom = true;
    formsPlot3.Configuration.ScrollWheelZoom = true;
}
```

**Comment by saklanmazozgur** [comment]
I know there is video support in the comments, but when I try to upload a video, I keep getting an error. I didn't understand why. :)

Also thank you for the demo. I will implement it in my project.
