### ISSUE TITLE
FillY: add support for filling above and below with two different colors

### ISSUE THREAD

**Issue by xichaoqiang** [ScottPlot/ScottPlot#3380]
The PlotFillAboveBelow function is useful for me but it seems lack in ScottPlot5.

* https://scottplot.net/cookbook/4.1/category/plottable-fill/

**Comment by swharden** [comment]
ScottPlot 4 does this... https://scottplot.net/cookbook/4.1/category/plottable-fill/

ScottPlot 5 has this... https://scottplot.net/cookbook/5.0/FillY/

I bet FillY may be used in ScottPlot 5 to achieve the "fill above and below" effect. If not, it's pretty close, and maybe a small addition could help improve this support.

**Comment by Diddlik** [comment]
I use DataStreamer to get "Real-Time" chart for only last 250 points. Till now I did not found how to use it for DataStreamer.

**Comment by xichaoqiang** [comment]
I hope it can also support left and right filling.

**Comment by swharden** [comment]
This feature was added in 829496b8e6cecffb38a68671ec36c389571fb236 and will be available in the next release 🚀 

```cs
var sp = myPlot.Add.Scatter(xs, ys);
sp.FillY = true;
sp.FillYValue = 0;
sp.FillYAboveColor = Colors.Green.WithAlpha(.2);
sp.FillYBelowColor = Colors.Red.WithAlpha(.2);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/835f2f89-7a89-4b8f-b7e0-416c5c93bf67)

**Comment by xichaoqiang** [comment]
Thanks for this function, Scatter plots typically display data left-to-right,  is it possible to use this plot type to display data bottom-to-top like [SignalXY],with Data.Rotated = true;

![image](https://github.com/ScottPlot/ScottPlot/assets/30900789/5336153b-45e1-4a78-adf5-ae8041486da4)
