### ISSUE TITLE
Dragging the lines

### ISSUE THREAD

**Issue by MarekKantor60** [ScottPlot/ScottPlot#3382]
**Question:** Hello, the vertical and horizontal line does not longer have the Dragged event,  like in the scottplot 4 and if you set IsDraggable on true, u cant still move with the line. Are you going to add this funcionality, or should i use it different in scottplot 5 ?

**ScottPlot Version:** 5.0.21

**Comment by swharden** [comment]
Hi @MarekKantor60, I think the functionality you're looking for can be found in the demo app!

https://scottplot.net/demo/#draggable-axis-lines

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/c76bcd7f-f501-47f5-9b17-627b647c2c10)
