### ISSUE TITLE
Cookbook: need recipe to show how to hide axis ticks

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3383]
I found it difficult to achieve this effect, so adjust the API to make this easier. Disabling the axis entirely "collapses" it, then the left axis tick labels run off the graph to the bottom, so that strategy isn't the best. There should be an easy flag to allow all elements to be individually toggled on and off

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/486f6732-428b-4e56-b091-1f44f0afda48)

```cs
// this currently works but is a bit clunky
plot.Axes.Bottom.TickLabelStyle.IsVisible = false; // ignored?
plot.Axes.Bottom.TickLabelStyle.ForeColor = Colors.White;
plot.Axes.Bottom.MajorTickStyle.Length = 0;
plot.Axes.Bottom.MinorTickStyle.Length = 0;
```

... also demonstrate turning frame lines on and off

**Comment by shcreasey** [comment]
Yes, this would be great!  I had to experiment to find your work around above :)

**Comment by swharden** [comment]
> demonstrate turning frame lines on and off

```cs
namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        formsPlot1.Plot.Add.Signal(ScottPlot.Generate.Sin());
        formsPlot1.Plot.Add.Signal(ScottPlot.Generate.Cos());

        formsPlot1.Plot.Axes.Bottom.TickLabelStyle.IsVisible = false;
        formsPlot1.Plot.Axes.Bottom.MajorTickStyle.Length = 0;
        formsPlot1.Plot.Axes.Bottom.MinorTickStyle.Length = 0;

        formsPlot1.Plot.Axes.Bottom.FrameLineStyle.Width = 0;
        formsPlot1.Plot.Axes.Right.FrameLineStyle.Width = 0;
        formsPlot1.Plot.Axes.Top.FrameLineStyle.Width = 0;
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/fbbe74aa-6db3-4d4c-990e-aaee465d5cbe)

**Comment by Photogphred** [comment]
Seems to work great for the bottom. But I have a plot with 16 channels and it doesn't work. I even tried just one plot, no luck.

This is the code:

`			formsPlot1.Plot.Axes.Left.TickLabelStyle.IsVisible = false;
			formsPlot1.Plot.Axes.Left.MajorTickStyle.Length = 0;
			formsPlot1.Plot.Axes.Left.MinorTickStyle.Length = 0;
`

![Image](https://github.com/user-attachments/assets/9b039ecd-312b-427d-bd5a-d276f72a9767)

I tried this code when setting up my axes.

`			for (int i = 0; i < 16; i++)
			{
				Loggers[i] = formsPlot1.Plot.Add.DataLogger();
				Walkers[i] = new ScottPlot.DataGenerators.RandomWalker(i, multiplier: 0.01 * (i + 1));

				// assign each logger its own right Y-axis
				var axis = formsPlot1.Plot.Axes.AddLeftAxis();
				Loggers[i].Axes.YAxis = axis;
				axis.Color(Loggers[i].Color);

				axis.TickLabelStyle.IsVisible = false;
				axis.MajorTickStyle.Length = 0;
				axis.MinorTickStyle.Length = 0;
			}
`

Then I get this:

![Image](https://github.com/user-attachments/assets/4cc1a759-0f8d-4178-904e-34b7561cbc03)

Can't seem to find an API to do this.

Sorry about the bad formatting for the code. Not sure what I was doing wrong.
