### ISSUE TITLE
Show in Toolbox

### ISSUE THREAD

**Issue by Demasterpl** [ScottPlot/ScottPlot#3388]
**Issue:** (Describe the bug here)
This was already previously reported (https://github.com/ScottPlot/ScottPlot/issues/2535) but this does not seem to be implemented from what I can tell.

Previously in v4 there would be a section called "ScottPlot.WinForms" with a subitem called "FormsPlot" that I could drag and add that to my winform application.

Now in v5's toolbox there is are groups SkiaSharp.Views and OpenTK groups. Subitems like GLControl, SKControl, and SKGLControl, all of which either give a gray or black square when added to a winform.

I also noticed that the file that was edited in the previously linked issue does not exist in the current v5 version of ScottPlot.

**ScottPlot Version:** (What NuGet package are you using?)
ScottPlot.WinForms 5.0.21

**Comment by swharden** [comment]
Hi @Demasterpl, I know the "it works on my machine" response is unsatisfying... but

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/02a8373b-6464-4553-8646-b65a36fa535e)

Are you using the latest version of Visual Studio? I think this is a VS issue, perhaps related to 32-bit/64-bit conflicts (more common with .NET Framework projects)

https://scottplot.net/faq/add-winforms-programmatically/ may be helpful for others experiencing this issue
