### ISSUE TITLE
heatmap size and placement lack in SP5

### ISSUE THREAD

**Issue by xichaoqiang** [ScottPlot/ScottPlot#3389]
![image](https://github.com/ScottPlot/ScottPlot/assets/30900789/b53a2f0f-7e37-4324-b3c4-6635367c87ba)

**Comment by swharden** [comment]
Thanks for this question @xichaoqiang!

This is possible in ScottPlot 5 by assigning the `Extent` property:

https://scottplot.net/cookbook/5.0/Heatmap/HeatmapInverted/

ScottPlot.Plot myPlot = new();

double[,] data = SampleData.MonaLisa();

var hm1 = myPlot.Add.Heatmap(data);
hm1.Extent = new(0, 65, 0, 100); // <-- like this

myPlot.SavePng("demo.png", 400, 300);
