### ISSUE TITLE
SP5: Stacked Bar - show value inside bar

### ISSUE THREAD

**Issue by tibormarchynzoom** [ScottPlot/ScottPlot#3391]
**Suggestion:** Stacked bar chart currently does not have option to show numeric value inside bar, so it's not possible to quickly see value and users need to look on bottom axis

**Comment by swharden** [comment]
Thanks for the suggestion @tibormarchynzoom! I'll close this issue and add this feature to #3426 to be sure label support is demonstrated in a new cookbook recipe 👍

**Comment by swharden** [comment]
Solved most of this in #3426, but I'm opening this back up to track adding a `TextAlignment` property to bars

**Comment by swharden** [comment]
Hi @tibormarchynzoom, I just added a feature which allows this:

```cs
ScottPlot.Bar bar = new()
{
    Value = nextBarBase + values[i],
    FillColor = categoryColors[i],
    ValueBase = nextBarBase,
    Position = x,
    Label = "Testing",
    CenterLabel = true, // new flag to center the label
};

myPlot.Add.Bar(bar);
```

Adding this code to the example in #3426 we get this:

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/2eff5c04-6f2d-4dd0-9f0f-3fa1a5b1e430)

**Comment by jaguarxii** [comment]
Great feature, thanks, I was trying to rotate the bar label but it seems not possible?

![image](https://github.com/user-attachments/assets/ff0a8854-b12f-4c4c-bde7-3c3143910380)

**Comment by swharden** [comment]
@jaguarxii this feels a bit hacky but it works

```cs
using ScottPlot;

Plot myPlot = new();

for (int i = 0; i < 10; i++)
{
    Bar bar = new()
    {
        Position = i,
        Value = Generate.RandomNumber(10, 20),
        Label = $"Bar #{1 + i}",
        CenterLabel = true,
        FillColor = Generate.RandomColor().Lighten(0.5)
    };

    var barPlot = myPlot.Add.Bar(bar);
    barPlot.ValueLabelStyle.Rotation = -90;
    barPlot.ValueLabelStyle.FontSize = 16;
}

myPlot.Axes.Margins(bottom: 0);
myPlot.SavePng("test.png", 600, 300).LaunchFile();
```

![test](https://github.com/user-attachments/assets/57792aba-2976-4d05-9afb-5da7e428f16d)

**Comment by jaguarxii** [comment]
Nice @swharden, do you know if it is possible to align the labels to the base of the bar, will it work on horizontal bars aswell ?

**Comment by swharden** [comment]
> is is possible to align the labels to the base of the bar?

> will it work on horizontal bars as well?

Hi @jaguarxii, I believe so! Give it a try and if you come up with a good code sample demonstrating it, paste it here and we can add it to the cookbook 👍

**Comment by jaguarxii** [comment]
Hi @swharden, the closest I get to place the labels to the "base" of the bar (in this case horizontal) is by setting the alignment to lowerRight, but not all labels are aligned.

I already tried to set the labeloffset by using the rect attribute, without any success

![image](https://github.com/user-attachments/assets/f1b57bfa-acdc-46c0-9a3f-c6be2dcfbc8f)

**Comment by swharden** [comment]
Hi @jaguarxii, thanks for following up! Adding a `Text` above a `Bar` is a good strategy. Thanks for sharing your code so others may be able to replicate this result!

It sounds like support for text alignment in horizontally arranged bars isn't great. The code that controls that behavior is here, so if someone wants to create a pull request to modify this behavior and improve support for text alignment in horizontal bars, I would be happy to review it and merge it in 👍 

https://github.com/ScottPlot/ScottPlot/blob/1f44931697efb5fcc0c8589057039256522e3ee9/src/ScottPlot5/ScottPlot5/Primitives/Bar.cs#L143-L161

In the mean time, it seems like you have a great solution! Thanks again for sharing
