### ISSUE TITLE
LockedVertical/LockedHorizontal  rule not working in AvaPlot 5.0.21

### ISSUE THREAD

**Issue by yaroslav-khomyak** [ScottPlot/ScottPlot#3393]
**Issue:** LockedVertical/LockedHorizontal rule has no effect in AvaPlot. Plot can be dragged and zoomed without restrictions.

When the rule is added, I'm experiencing stuttering while dragging the plot. It obviously tries to do something.

![image](https://github.com/ScottPlot/ScottPlot/assets/19666423/e08c0df6-334a-4496-bc31-2093b9372b24)

**ScottPlot Version:** 5.0.21

**Code Sample:** 

```cs
    public MainView()
    {
        InitializeComponent();

        plot.Plot.Add.Signal(Generate.RandomWalk(1000));

        LockedVertical rule = new(plot.Plot.Axes.Left);
        plot.Plot.Axes.Rules.Clear();
        plot.Plot.Axes.Rules.Add(rule);

        plot.Plot.Render();
    }
```

**Comment by yaroslav-khomyak** [comment]
I have workaround for this issue. 
I created a custom rule, which I add after autosizing is completed.

public class MyLockVertical(IYAxis yAxis) : IAxisRule
{
    readonly IYAxis YAxis = yAxis;
    readonly double Min = yAxis.Range.Min;
    readonly double Max = yAxis.Range.Max;

    public void Apply(RenderPack rp, bool beforeLayout)
    {
        YAxis.Range.Set(Min, Max);
    }
}

**Comment by swharden** [comment]
Hi @yaroslav-khomyak, I'm glad you found a fix! Being able to inject a custom axis rule really helped this situation where the default one was buggy 😅 

This issue is similar to that described in #3374. I'll close this issue and track progress toward fixing the core issue over there 👍
