### ISSUE TITLE
SP5 axes overflowing into the padding of the plot.

### ISSUE THREAD

**Issue by wsomegapoint** [ScottPlot/ScottPlot#3395]
**Issue:**
Hello! I am currently working on creating a heat map in Avalonia, with custom ticks on both the X and Y axes. It all works as expected, except for an issue where the axes appear to overflow into the padding of the plot. In the image below i expect the axes to stop drawing the tick labels at "test Y 61", but instead the ticks are extended to padding of the plot.

**ScottPlot Version:**
ScottPlot.Avalonia 5.0.21

**Code Sample:**
Both axes are generated like so:

```cs
AvaPlot avaPlot = new();

var heatMapPlot = new Heatmap(SampleData.MonaLisa());
avaPlot.Plot.Add.Plottable(heatMapPlot);

NumericManual ticksY = new();
for (var i = 0; i < 100; i++)
{
    ticksY.AddMajor(i, $"test Y {i}");
}
avaPlot.Plot.Axes.Left.TickGenerator = ticksY;
```

![image](https://github.com/ScottPlot/ScottPlot/assets/89082505/8856c6e3-cd51-49e3-8d81-d411d21ab13b)

**Comment by swharden** [comment]
Thanks for reporting this @wsomegapoint! I think this has been fixed and will be ready to use in the next release (should be on NuGet this weekend)

Related: #3425, #3427, #3395
