### ISSUE TITLE
SP5 Inverted Y axis loses labelling

### ISSUE THREAD

**Issue by BrianAtZetica** [ScottPlot/ScottPlot#3397]
**Issue:** When I invert the Y axis of a chart the Y-axis labels and horizontal grid lines are ommitted.

**ScottPlot Version:** ScottPlot.WPF v5.0.21

**Code Sample:** 
```cs
using ScottPlot;
using System.Drawing;

double[] dataX = { 1, 2, 3, 4, 5 };
double[] dataY = { 1, 4, 9, 16, 25 };

ScottPlot.Plot myPlot = new();
var trace = myPlot.Add.SignalXY(dataX, dataY);
myPlot.SavePng("quickstart1.png", 400, 300);

myPlot.Axes.SetLimits(left: 0, right: 6, bottom: 26, top: 0);
myPlot.SavePng("quickstart2.png", 400, 300);

```

quickstart1.png:
![quickstart1](https://github.com/ScottPlot/ScottPlot/assets/119825052/ca69a075-dffa-4779-95c4-3657e861a800)

quickstart2.png:
![quickstart2](https://github.com/ScottPlot/ScottPlot/assets/119825052/c146c15c-d3f7-4470-9b52-4556f16f4fba)

**Comment by swharden** [comment]
Fixed in #3401
