### ISSUE TITLE
SP5: It should have a method to add a control/self-defined control to a definited position in the chart

### ISSUE THREAD

**Issue by yosez** [ScottPlot/ScottPlot#3398]
I propose that ScottPlot should have a method to add a control/self-defined control to a set position in the chart. While I'm using ScottPlot, I want to assemble a custom control, and pin it on the chart, but there is not a function ready-made to be used. I suggest that this function could be passed with parameters of pixel positions as well as coordinate positions.
ScottPlot is really accessible, and thanks so much for your work.

**Comment by swharden** [comment]
Hi @yosez, thanks for this suggestion! This is possible without requiring modification to the ScottPlot library

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        button2.Visible = false;

        formsPlot1.Plot.Add.Signal(Generate.Sin());
        formsPlot1.Plot.Add.Signal(Generate.Cos());

        formsPlot1.Plot.RenderManager.AxisLimitsChanged += (s, e) =>
        {
            Coordinates coordinates = new(20, .5);
            Pixel px = formsPlot1.Plot.GetPixel(coordinates);
            button1.Location = new((int)px.X, (int)px.Y);
        };
    }
}
```

![button](https://github.com/ScottPlot/ScottPlot/assets/4165489/d8f15e9b-38ae-4b54-b248-d7b0738d1a23)

**Comment by yosez** [comment]
@swharden Thank you so much. It helps me a lot.
