### ISSUE TITLE
FillY: Add support for scatter plots with step display enabled

### ISSUE THREAD

**Issue by andyp-c** [ScottPlot/ScottPlot#3399]
The issue has to do with FillY between 2 scatter arrays. The arrays are set up with ConnectStyle.StepHorizontal. The problem is that if I try to fill the space between two scatter arrays using plt.Plot.Add.FillY, the Fill appears to assume the use of ConnectStyle.Straight. 
IMHO, the Fill should match up with the ConnectStyle. 

ScottPlot version is ScottPlot.WPF version 5.0.21. 

```cs
private void TestScottPlot5()
{
    double[] zeros = new double[10];
    double[] data = new double[10];
    double[] positions = new double[10];
    ScottPlot.WPF.WpfPlot myPlot = WpfPlot1;    // name of ScottPlot instance in the xml file 
    
    
    for (int i = 0; i < 10; i++)
    {
        positions[i] = i;
        zeros[i] = 0; 
        data[i] = Math.Sin(2.0 * Math.PI * (double)i / 10.0);
    }

    var scatterZeros = myPlot.Plot.Add.Scatter(positions, zeros);
    scatterZeros.ConnectStyle = ConnectStyle.StepHorizontal;

    var scatterData = myPlot.Plot.Add.Scatter(positions, data);
    scatterData.ConnectStyle = ConnectStyle.StepHorizontal;

    var xyy = myPlot.Plot.Add.FillY(scatterZeros, scatterData);
    xyy.FillStyle.Color = ScottPlot.Colors.Blue.WithAlpha(100);
}
```

**Comment by swharden** [comment]
Adding additional context to move this issue forward, this is the current behavior of the code above:

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/d5b8e995-6bc2-48f4-858f-c583baf2fd2d)

**Comment by swharden** [comment]
For more context, these are the lines of code that need to be modified to create a polygon that respects the step shape:

https://github.com/ScottPlot/ScottPlot/blob/fdd1dfdf0fd8d32ce3176337c2140f5f14e44a20/src/ScottPlot5/ScottPlot5/Plottables/FillY.cs#L31-L44

**Comment by aespitia** [comment]
if you set FillY=true, this seems to work already.

            double[] zeros = new double[10];
            double[] data = new double[10];
            double[] positions = new double[10];

            for (int i = 0; i < 10; i++)
            {
                positions[i] = i;
                zeros[i] = 0;
                data[i] = Math.Sin(2.0 * Math.PI * (double)i / 10.0);
            }

            var scatterZeros = myPlot.Add.Scatter(positions, zeros);
            scatterZeros.ConnectStyle = ConnectStyle.StepHorizontal;

            var scatterData = myPlot.Add.Scatter(positions, data);
            scatterData.ConnectStyle = ConnectStyle.StepHorizontal;
            
            scatterZeros.FillY = true;
            scatterData.FillY = true;   
            
            
![image](https://github.com/user-attachments/assets/f2ebd1d9-bb08-483d-9b57-853a86f02a92)
