### ISSUE TITLE
SP5 Plot.Style.SetBestFonts() does not change the font of legend

### ISSUE THREAD

**Issue by yui1227** [ScottPlot/ScottPlot#3403]
**Issue:** Plot.Style.SetBestFonts() does not change the font of legend. I need to change it manually.

**ScottPlot Version:** ScottPlot.WinForms v5.0.21

**Code Sample:** 

```cs
using ScottPlot;
Plot plt = new();
var signal = plt.Add.Signal(ScottPlot.Generate.Sin());
signal.Label = "正弦波";

plt.ShowLegend();
plt.Style.SetBestFonts();
plt.SavePng("bug.png",400,400);
plt.Legend.Font.Name = Fonts.Detect("正弦波");
plt.SavePng("fixed.png",400,400);
```
bug.png
![bug](https://github.com/ScottPlot/ScottPlot/assets/77109827/b0938a66-07bf-4a73-81b9-30db26b3792f)

fixed
![fixed](https://github.com/ScottPlot/ScottPlot/assets/77109827/aef53806-fdfd-4354-a8c3-a667b45bf2bd)

**Comment by swharden** [comment]
Thanks for reporting this @yui1227! I just updated it and it should work in the next release 🚀 

* #3440 
* #3488
