### ISSUE TITLE
DateTimeFixedInterval: Add option to snap to the first of each month

### ISSUE THREAD

**Issue by LBlacklink** [ScottPlot/ScottPlot#3408]
**Issue:**
Excuse me if I sound vague because it's pretty difficult to explain and I can't get my recording to work. If ticks are set to DateTimeFixedInterval (for TimeUnits.Day() for instance), then the first tick is always all the way on the left of the plot, with following ticks at the correct interval apart. This means that if you then pan over to either side, the ticks and gridlines do not move along with the graph. Instead, they stay stationary and snap to the next value as soon as the TimeUnit has been passed.
I considered that this may be intented behaviour, but I could not imagine in what case this would be useful. I would like the tick to be positioned at the start of the day and for this tick to move along with the points at this time when panning. Now it is not clear when a day starts or ends.
Using any other TimeUnit has the same issue.

**ScottPlot Version:**
ScottPlot.WinForms 5.0.21

**Code Sample:**

```cs
//This code is taken from the ScottPlot 5 Cookbook:
ScottPlot.Plot myPlot = new();

// plot data using DateTime units
DateTime[] dates = Generate.DateTime.Days(100);
double[] ys = Generate.RandomWalk(100);
myPlot.Add.Scatter(dates, ys);

// tell the plot to display dates on the bottom axis
myPlot.Axes.DateTimeTicksBottom();

//Only the following line has been added to the example:
myPlot.Axes.Bottom.TickGenerator = new DateTimeFixedInterval(new ScottPlot.TickGenerators.TimeUnits.Day(), 30);

myPlot.SavePng("demo.png", 400, 300);
```
This results in the following plot, note how the ticks start all the way to the left. I can't record video so I can't show how panning this in an interactable FormsPlot affects it
![demo](https://github.com/ScottPlot/ScottPlot/assets/25454414/dbeea5af-f12d-44eb-a634-5ec8d6d5bea5)

**Comment by swharden** [comment]
> pretty difficult to explain and I can't get my recording to work

This helps communicate the issue!

![dates](https://github.com/ScottPlot/ScottPlot/assets/4165489/c72fbcd5-30cb-4daa-b9a4-7dbbc9236466)

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        // plot data using DateTime units
        DateTime[] dates = Generate.DateTime.Days(100);
        double[] ys = Generate.RandomWalk(100);
        formsPlot1.Plot.Add.Scatter(dates, ys);

        // tell the plot to display dates on the bottom axis
        formsPlot1.Plot.Axes.DateTimeTicksBottom();

        //Only the following line has been added to the example:
        ScottPlot.TickGenerators.ITimeUnit timeUnit = new ScottPlot.TickGenerators.TimeUnits.Day();
        ScottPlot.TickGenerators.DateTimeFixedInterval gen = new(timeUnit, 30);
        formsPlot1.Plot.Axes.Bottom.TickGenerator = gen;
    }
}
```

Probably the best solution is to copy the `DateTimeFixedInterval` class and modify it to "snap" to the first of the month or something. You can then instantiate this class yourself and assign it as the tick generator. If you get this to work, it would be great if you could share your code and we can include that class with ScottPlot (or modify the `DateTimeFixedInterval` to include that snapping feature).

I think this is worth adding to ScottPlot, but I probably won't prioritize this feature for my short term effort. Hopefully you or someone from the community can figure this one out, and I will be happy to review a PR and merge it in good time! 🚀
