### ISSUE TITLE
SP5 Heatmap image flipping options

### ISSUE THREAD

**Issue by BrianAtZetica** [ScottPlot/ScottPlot#3418]
**Suggestion:** Heatmaps can be flipped vertically using the FlipVertically property. But this only helps to deal with different row orders in the stored 2D array. It would be helpful if one could also flip an image horizontally (dealing with the order values are stored in columns).

In addition to this, setting the extent of a HeatMap should facilitate a flip of the image. 
For example:

```cs
        double[,] data = SampleData.MonaLisa();
        var hm1 = WpfPlot1.Plot.Add.Heatmap(data);
        hm1.Extent = new(0, 64, 99, 0); // NOTE Bottom > Top
        WpfPlot1.Plot.Axes.SetLimits(-1, 65, -1, 100);
        WpfPlot1.Plot.Title("Image Should be Flipped Vertically");
        WpfPlot1.Plot.SavePng("MonaLisaInvertedY1.png", 650, 1000);

```

This will provide two tools for manipulating the flipping of an image. The tooling that is most appropriate will depend on the data-specific scenario and the programmer-specific mindset.

**Comment by swharden** [comment]
resolved in #3419
