### ISSUE TITLE
EtiquettePlot: new plot type that combines features from `Label` and `Arrow`

### ISSUE THREAD

**Issue by NicolasLairNET** [ScottPlot/ScottPlot#3420]
**Suggestion:** Add new plot for  allowing users to create draggable and linkable labels (etiquettes). These etiquettes can be associated with specific elements and offer customization options for appearance and positioning.

Example of use :
```cs
var etiquette = formsPlot1.Plot.Add.Etiquette("Curve informations", 100, 200);
etiquette.LinkPoint.X = etiquette.x + 10;
etiquette.Label.BorderColor = Colors.Blue;
etiquette.Label.BackColor = Colors.Blue.WithAlpha(.5);
etiquette.Label.Padding = 5;
etiquette.Label.FontSpacing = 3;
```
![image](https://github.com/ScottPlot/ScottPlot/assets/20141074/20a61a25-80e7-4514-a7b9-0985668af3fa)

**Comment by swharden** [comment]
Thanks for the idea @NicolasLairNET! I like this. I may not be able to get to it for a while, but if you or someone from the community wants to copy the `Text` plot type and modify it to add these features, I'd be happy to review a pull request!

* https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Plottables/Text.cs
* https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Plottables/Arrow.cs
* https://scottplot.net/faq/custom-plot-type/

**Comment by NicolasLairNET** [comment]
I started to work in this feature, but it's not ready yet.
