### ISSUE TITLE
ScottPlot5 Avalonia control is very slow on Linux

### ISSUE THREAD

**Issue by krabicka04** [ScottPlot/ScottPlot#3439]
**Question:** ScottPlot5 skiasharp is terribly slow on Linux (Debian 12 (linux-x64), i3-10105, Intel UHD Graphics 630).

**ScottPlot.Avalonia Version:** 5.0.21
**SkiaSharp.NativeAssets.Linux.NoDependencies Version:** 2.88.7
**Avalonia Version:** 11.0.6

**Code Sample:**

```xaml
<ScottPlot:AvaPlot Name="avaPlot1"/>
```

```cs
        avaPlot1.Plot.Title("UDP data graf");

        avaPlot1.Plot.XLabel("Time [s]");
        avaPlot1.Plot.ShowLegend();

        // create a timer to update the GUI
        _renderTimer = new DispatcherTimer();
        _renderTimer.Interval = TimeSpan.FromMilliseconds(20);
        _renderTimer.Tick += Render;
        _renderTimer.Start();
```
```cs
void Render(object sender, EventArgs e) {
avaPlot1.Refresh();
}
```

When I use ScottPlot4 or ScottPlot5 on Windows then the UI page with the Scottplot plot performance is smooth and fast. The Scottplot5 is even faster than Scottplot4 on Windows. When I use the same on Linux (same machine) then the application is terribly slow, regardless the refreshing render time period. Scottplot4 performance is satisfactory on Linux.

The rendering time (FPS) get by dobble-click in graph is more than 100 times worse on Linux.

- I am using **dotnet** 6.0.
Build command: `dotnet publish -r linux-x64 -c Debug -p:publishsinglefile=true --self-contained true` 

The following packages **libfreetype6**, **libfontconfig1** and **fontconfig** have been installed.

I am curious whether the Scottplot5 is using the GPU acceleration or what I am doing wrong.

Thank you for support.

**Comment by pkstrsk** [comment]
Hello, 
@krabicka04, I am experiencing the same behavior, rendering speed of 4 FPS (~300ms) on Debian. Have you solved this or managed to improve the performance?

BR

**Comment by swharden** [comment]
Hi @krabicka04 and @pkstrsk, thanks for reporting this issue! 

I'll leave this issue open for a while longer to encourage feedback, but since I don't run Linux on a desktop it's hard for me to evaluate this issue or work toward a fix. I can say that the Avalonia plot does not use OpenGL, so it's unlikely a  GPU issue.

This is the section of code that handles rendering in the Avalonia control. Maybe looking closer at this area can help identify where the slowdown is. Perhaps it's a SkiaSharp issue, or perhaps it's an async issue that can be fixed with a small code change. Closer inspection and benchmarking of these methods may offer a lot of insights

https://github.com/ScottPlot/ScottPlot/blob/ad66085d2086fbe3c744f5cb43cd04620517830d/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.Avalonia/AvaPlot.cs#L35-L75

**Comment by swharden** [comment]
If it helps, here's an official Avalonia SkiaSharp code demo

https://github.com/AvaloniaUI/Avalonia/blob/master/samples/RenderDemo/Pages/CustomSkiaPage.cs

**Comment by frodik13** [comment]
I installed version 5.0.18 and the graphics are displayed smoothly and without freezes, but when I install version 5.0.19 the graphics start to freeze a lot.

**Comment by 4tunecookies** [comment]
I am having the same issue and ran some testing.
- RHEL 8.8
- Avalonia version 11.0.7

With my application, downgrading to 5.0.18, the application is running at around 8% of a single core.  When upgrading > 5.0.18, the same exact application is maxing out a single core which is causing the plotting to essentially freeze.  

render speeds using same data stream for a signalXY
- 5.0.18 ~1 ms
- 5.0.21 ~300 ms

Almost seems like there is an infinite loop or some thread running without a sleep/wait in a render thread

**Comment by zii-dmg** [comment]
I took version 5.0.19 and replaced Label.cs from 5.0.18. The performance has become normal. At 5.0.19, you no longer set value of cache variable `CachedTypeface`, it is always null.

**Comment by pkstrsk** [comment]
@zii-dmg Amazing, I just tested it on a Raspberry Pi 5 and I get min 40FPS in rendering a large set of data (4-5MB). 

This is all I had to add in Label.cs to make it work:

`private SKTypeface? CachedTypeface = null;

private SKTypeface Typeface
{
    get
    {
        if (CachedTypeface is null)
        {
            CachedTypeface = Fonts.GetTypeface(FontName, Bold, Italic);
        }
        return CachedTypeface;
    }
}`

**Comment by zii-dmg** [comment]
As I understand in merged #3841 font cache already was reworked and fixed.

**Comment by pkstrsk** [comment]
Oh, I missed that then. Great it's fixed now.

**Comment by zii-dmg** [comment]
Fixed in [5.0.35](https://github.com/ScottPlot/ScottPlot/releases/tag/5.0.35) by #3841

**Comment by jpgarza93** [comment]
Are you guys seeing better performance on Linux?

**ScottPlot**: v5.0.39  

In my case, I see: 

In Linux Debian (i7 CPU) I see fonts render differently and a render frame rate of (1 FPS)
![image](https://github.com/user-attachments/assets/65aca6f8-2749-45f7-82ff-a10efb0671b0)

In Windows 10 (116 FPS)
![image](https://github.com/user-attachments/assets/7236f8c6-94b8-45ea-a84d-ccbc70fb48d0)

**Comment by jpgarza93** [comment]
I have found the issue. It is related to Axes Label.FontName.

Here is a fork where I created an Avalonia demo I could publish easily on Linux.

These 2 lines are the issue:
https://github.com/ScottPlot/ScottPlot/compare/main...jpgarza93:jpScottPlot:avalonia-demo#:~:text=plot.Axes.Bottom.Label.,Label.FontName%20%3D%20%22Consolas%22%3B

Works fine on Windows but not on Linux

**Comment by kebox7** [comment]
The reason for this behavior is generally clear.
1. The "Consolas" font is not native to Linux.
2. SystemFontResolver tries to find it in the system and does not find it (lines 84-92).
3. Then an default typeface is created (line 94), but (and this is the most important thing) it is not cached. That is, the default font is created every time we need to draw a text. Hence the loss in performance.

As for Windows, the "Consolas" font is native there and is perfectly found by SystemFontResolver and cached.

https://github.com/ScottPlot/ScottPlot/blob/743c9427e63692d31920cc424a0e62b12d6eec4a/src/ScottPlot5/ScottPlot5/Fonts.cs#L74-L95

**Comment by jpgarza93** [comment]
I agree the code is clear, but the potential issue of the FontName 'not being found' isn't immediately obvious from the API. This is a major oversight since it's not documented in the FontName description.

Why do we need to recreate it every time it's not found? Wouldn't it be more efficient to cache a default font when an instance of a missing FontName occurs?

**Comment by kebox7** [comment]
> Why do we need to recreate it every time it's not found?

It just so happened 🤷😊

> Wouldn't it be more efficient to cache the default FontName when an instance of a missing FontName occurs?

PR #4250 should just fix this situation.

**Comment by jpgarza93** [comment]
@kebox7 You're the best. Thanks!
