### ISSUE TITLE
Mouse wheel zoom should lock one axis when performed while mouse if over an axis

### ISSUE THREAD

**Issue by edwwsw** [ScottPlot/ScottPlot#3440]
This was a really nice feature in oxyplot's mouse wheel  zoom.  Mouse wheel zoom performs differently depending on there you are hovering.

If over the data grid, it does what you currently have implemented - zooms both x and y axis. 
If over the x axis , zoom only affects x axis, y zoom is locked.
If over the y axis, zoom only affects y axis, x zoom is locked.

**Comment by edwwsw** [comment]
Here's some  code that can do this as part of IPlotInteraction implementation.

        public void MouseWheelVertical(Pixel pixel, float delta)
        {
            if (!_Enabled)
            {
                return;
            }

            Coordinates hitpoint = PlotControl.Plot.GetCoordinates(pixel);
            CoordinateRect? gridrect = PlotControl.Plot.Axes?.GetLimits().Rect;
            bool lockx = false;
            bool locky = false;

            if (gridrect?.Contains(hitpoint) == false)
            {
                if (hitpoint.Y > gridrect?.Top || hitpoint.Y < gridrect?.Bottom)
                {
                    locky = true;
                }
                else
                {
                    lockx = true;
            
                }
            }


            if (delta > 0)
            {
                StandardActions.ZoomIn(PlotControl, pixel, new LockedAxes(lockx, locky));
            }
            else
            {
                StandardActions.ZoomOut(PlotControl, pixel, new LockedAxes(lockx, locky));
            }
        }

**Comment by swharden** [comment]
Thanks for reporting this @edwwsw! It is now fixed and I'd love your feedback after the next release 🚀 

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/b7102bc4-12a6-4257-b786-1a203694ef94)

I though this would be a quick fix... but #3488 got pretty complicated! That's a good indication that some future effort refactoring this system is merited 😄
