### ISSUE TITLE
CI: treat warnings as errors

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3442]
It's annoying to enable this during development, but as part of the CI checks performed when PRs are opened it would be great to fail the build if warnings are present to prevent them from accidentally ending-up in the main branch, then others who fork that have to work around them

**Comment by KroMignon** [comment]
You could `TreatWarningsAsErrors`, `WarningsAsErrors` and `WarningsNotAsErrors` in the project files to force error for given warnings. 

==> [C# Compiler Options to report errors and warnings](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings)

**Comment by swharden** [comment]
I found it's really annoying to add it at the csproj level because (1) I have lots of warnings while I'm developing and I don't want it to fail the build and (2) we have lots of csproj files...

However, I'm thinking we can `dotnet build /p:TreatWarningsAsErrors="true"` in our CI system 🤔
