### ISSUE TITLE
Setting Plot background to transparent makes app see-through where the plot renders.

### ISSUE THREAD

**Issue by jpgarza93** [ScottPlot/ScottPlot#3444]
**Issue:** (Describe the bug here)
Setting plot background data and figure to transparent creates a see-through application, instead of showing whatever color is behind.

**ScottPlot Version:**
ScottPlot.Avalonia 5.0.21

**Code Sample:** 
```cs
var transparent = ScottPlot.Colors.Transparent;
ScottPlot.Plot plot = new();

/* code to reproduce the bug */
plot.Style.Background(figure: transparent, data: transparent);
```

**Image Example**
I'll set only the `figure: transparent` to show the issue, you can see it becomes see-through and you can see my VS code behind:
![image](https://github.com/ScottPlot/ScottPlot/assets/79015116/14241485-d77c-4b39-8bbb-b4abd45605eb)

**Comment by swharden** [comment]
Hi @jpgarza93, thanks for this question! Unfortunately I think this is an Avalonia-specific issue (not a ScottPlot issue). The best solution is probably not to make the background transparent, but instead make it the same color as the Avalonia background.

Note that the background system was just updated, so there's a change this behavior may improve on the next release.  #3406, #3405

**Comment by jpgarza93** [comment]
I do recall this happening only on ScottPlott version upgrade from ScottPlot 5 beta to the latest. I am in the latest ScottPlot and Avalonia and the issue persists, just FYI :)

**Comment by chjrom** [comment]
If you remove render action `ClearCanvas` from `Plot.RenderManager` issue has gone.
Something like this:
```csharp
AvaPlot.Plot.RenderManager.RenderActions.RemoveAt(1);
```

**Comment by jpgarza93** [comment]
> If you remove render action `ClearCanvas` from `Plot.RenderManager` issue has gone. Something like this:
> 
> ```cs
> AvaPlot.Plot.RenderManager.RenderActions.RemoveAt(1);
> ```

That did it. Thank you very much
