### ISSUE TITLE
Controls: Zoom rectangle should respect axis rules

### ISSUE THREAD

**Issue by edwwsw** [ScottPlot/ScottPlot#3446]
Issue:  when locking say the X axis and drag zooming,  on mouse release the x axis gets moved the the last mouse X location.   I only want it to change the y zoom factor with this operation.     I believe I can work around this by writing a custom version of ZoomRectangleApply, so this isn't a show stopper. 

axis before release drag:  ![image](https://github.com/ScottPlot/ScottPlot/assets/14278121/75a0ddae-f2f6-44f6-bf3d-b684d54d4201)

after release: ![image](https://github.com/ScottPlot/ScottPlot/assets/14278121/7fca80d5-b808-40f7-b9c2-b3631d5e0397)

**Comment by swharden** [comment]
> I believe I can work around this by writing a custom version of ZoomRectangleApply, so this isn't a show stopper.

Following-up on this, if it's still an issue with the new user input processor (recently implemented) then let us know and we can open this up again and take a closer look! 

If someone from the community creates a PR demonstrating a fix, I would be happy to merge it quickly

Note too that there's recent movement regarding axis rules: #4422
