### ISSUE TITLE
RadarPlot in ScottPlot 5

### ISSUE THREAD

**Issue by nuelle16** [ScottPlot/ScottPlot#3448]
Hi!

Is there any plan to port even the RadarPlot to ScottPlot 5?

![image](https://github.com/ScottPlot/ScottPlot/assets/118738546/930bfaa6-0157-425b-b24d-837a7994126a)

Kind regards!

**Comment by swharden** [comment]
Hi @nuelle16, thanks for this suggestion! I'm going to close this issue and track progress in #3457 which I recently commented on with some information to help get started. I also mentioned it in the Discord #1966 

Although I personally don't intend to implement this feature in the short term, hopefully you or someone from the open source community can translate the ScottPlot 4 radar char to ScottPlot 5, and I'd be happy to review a pull request and merge it in good time! 🚀
