### ISSUE TITLE
ScottPlot4: `Text.IsUnderMouse` and `Text.IsPointtInsideRectangle` issue when X and Y ranges are very different

### ISSUE THREAD

**Issue by DaveMartel** [ScottPlot/ScottPlot#3449]
**Issue:** I have occasions where the Y axis of a scatter plot needs to run over a small range of values, but they are all very large (for example from 1.0e18 to 6.0E18). The X-axis is typically from 0 to 100. When I put a draggable text on the plot (maybe just with the text "Si"), and set DragEnabled, the mouse cursor indicates that the text is under the mouse almost wherever it is on the plot. This is clearly not correct. I have some exampes (can't give exact axis values) where the "active" area for the label is actually rather a complex shape. Unfortuntely this stops me interacting with the plot in almost any way, and I keep ending up moving the text when I don't want to. 

In the example code below once you run it, it sets up a simple scatter plot with a few points and the draggable label. Now move the mouse around and see how far away it is reporting as under the mouse...

**ScottPlot Version:** 4.1.71

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

Create a simple WinForms App, drop the following perocedure in the main form, and call it after InitializeComponent() in the fomr constructor.

```cs
/* code to reproduce the bug */
        private void DoTest()
        {
            double[] dataX = { 1, 2, 3, 4, 5, 6 };
            double[] dataY = { 1.0E18, 2.0E18, 3.0E18, 4.0E18, 5.0E18, 6.0E18 };
            formsPlot1.Plot.AddScatter(dataX, dataY);
            formsPlot1.Refresh();
            ScottPlot.Plottable.Text txt = new();
            txt.Label = "Si";
            txt.X = 3;
            txt.Y = 3.5e18;
            txt.DragEnabled = true;
            formsPlot1.Plot.Add(txt);
            formsPlot1.Refresh();
        }
```

Now move the mouse right down and out the bottom of the graph, and you can see that the text is still being reported as under the mouse. 

Unfortunately I can not screen shot that without some 3rd party tool (Snip hides mouse). But it should be very obvious to see the mouse in the shape of a hand pointing...

**Comment by DaveMartel** [comment]
I have read the link in text.cs, and understand how it would work for PointInRectangle for a rotated rectangle. In Text.cs it only operates on the render rectangle, which is a pure Rect, and not a set of coordinates. So I actually am not sure why the code is a complex as it is (unless this is just waiting to handle text rotation properly.

Anyway I think the final line is the issue for me 

After all of the various transforms the final line is 
``
            return difference < .001 * (rect.Height + rect.Width);
``

In the example above RectWidth is of the order of 0.2, and RectHeight is of the order of 1e17. Even using a double I don't think we have any precision to make that a viable calculation even though the numbers can be handled. 

Unless/until the "LastRenderRect" in text is a rotated refangular region, it would seem that a very simple PtInRect could be used instead...

**Comment by swharden** [comment]
> ScottPlot4

Following-up, I'm not putting much into adding features to ScottPlot 4 but I would be happy to review a PR if someone creates one, then after merging I can publish a new release 👍
