### ISSUE TITLE
ScottPlot 5: Add support for Radar chart

### ISSUE THREAD

**Issue by leandrobattochio** [ScottPlot/ScottPlot#3457]
**Question:** How can I plot a radar chart?

**ScottPlot Version:** 5.0.21

**Comment by Kleos-Dorron** [comment]
To plot a radar chart using ScottPlot version 5.0.21, you can follow these steps:

1.     Install ScottPlot version 5.0.21 if you haven't already.
2.     Prepare your data. Radar charts typically represent multivariate data with each variable as an axis.
3.     Create a new ScottPlot plot.
4.     Add radar chart data using the plt.PlotRadar method.
5.     Customize the radar chart appearance (e.g., axis labels, colours, markers).
6.     Render the plot.

Here's a simple example to illustrate these steps using python:
------------------------------------------------------------------------------------------------------
import scottplot as plt

# Sample data
values = [5, 3, 7, 2, 4]
labels = ["Category 1", "Category 2", "Category 3", "Category 4", "Category 5"]

# Create a new ScottPlot plot
sp = plt.plt(400, 400)

# Add radar chart data
sp.plot_radar(values, labels)

# Customize the radar chart appearance
sp.grid(enable=True, linestyle=':')
sp.frame(False)
sp.title("Radar Chart Example")
sp.axis(xlabel=None, ylabel=None)  # Disable axis labels (customize as needed)

# Render the plot
plt.show()
---------------------------------------------------------------------------------------------------------

> This code will create a radar chart with five categories and their corresponding values. You can adjust the values and labels arrays to represent your own data. Additionally, you can customize various aspects of the chart, such as the grid style, frame, title, and axis labels, to suit your needs.

**Comment by leandrobattochio** [comment]
Thank you for your reply but this seems like Python code, I'm using .NET. And also I couldn't find any of the methods you used in the .NET version.

**Comment by swharden** [comment]
This plot type is supported in ScottPlot 4.1 but not yet in 5.0. I'll adapt this issue to track progress toward adding this plot type in ScottPlot5 🚀 

* https://scottplot.net/cookbook/4.1/category/plottable-radar/
* https://scottplot.net/cookbook/4.1/category/plottable-coxcomb/

**Comment by swharden** [comment]
> Thank you for your reply but this seems like Python code

lol @leandrobattochio I question if that response was AI generated 😅

**Comment by swharden** [comment]
If someone from the open source community wants to give this a go, I bet you can get pretty far copy/pasting the ScottPlot 4 code into ScottPlot 5 and modifying as needed...

https://github.com/ScottPlot/ScottPlot/blob/5d23da49329e414cbabf32b698cd5834f570ca55/src/ScottPlot4/ScottPlot/Plottable/RadarPlot.cs#L1-L352

**Comment by bclehmann** [comment]
I believe this should be closed now that #3780 is merged?

**Comment by LeaFrock** [comment]
A small question (not a rush): When is the next version including this feature expected to be released?

**Comment by swharden** [comment]
> A small question (not a rush): When is the next version including this feature expected to be released?

I got pretty behind with life stuff the last few weekends 🤪 but I'm really optimistic the next release will be this weekend! 🚀
