### ISSUE TITLE
Feature request: Scatter-list-generic support for scottplot 5.0

### ISSUE THREAD

**Issue by MagicFawkes** [ScottPlot/ScottPlot#3463]
**Question:** 
When will be the feature "Scatter-list-generic"  available for Scottplot 5.0?
See link:
https://scottplot.net/cookbook/4.1/category/plottable-scatter-plot/#scatter-list-generic

**Comment by swharden** [comment]
I'm pretty sure this is already supported! The regular scatter plot can accept lists 🚀 

https://scottplot.net/cookbook/5.0/Scatter/ScatterGeneric/

**Comment by swharden** [comment]
https://scottplot.net/cookbook/5.0/Scatter/ScatterList/

**Comment by MagicFawkes** [comment]
> https://scottplot.net/cookbook/5.0/Scatter/ScatterList/

Thanks for reply it is working now, I have not realised, that I can use and dynamically extend the List<double> in runtime and after that I refresh the Plot new values with Scottplot.Refresh(). The List<double> can exchange the ScatterList :)
