### ISSUE TITLE
Show values using Pie chart from version 5

### ISSUE THREAD

**Issue by atmoraes1** [ScottPlot/ScottPlot#3485]
The Pie chart does not have the property ShowValues anymore, how to show values using the version 5?

![output](https://github.com/ScottPlot/ScottPlot/assets/139466904/91cf8587-3267-4c40-9ad2-6b8ba90991a5)

**Comment by swharden** [comment]
https://scottplot.net/cookbook/5.0/Pie/PieSliceLabels/

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/23935a72-e91f-450b-b1bb-7d2a3895ab21)

You can set `SliceLabelDistance` to a number less than `1` to have labels placed on the slices themselves
