### ISSUE TITLE
Demo: Add example for Scatter.GetNearest() using multiple scatter plots

### ISSUE THREAD

**Issue by RubensMigliore** [ScottPlot/ScottPlot#3503]
I successfully implemented suggestion for handling the MouseMove event in charts with only one dataset with ScottPlot 5 in VB .NET. However, I’m facing another situation with multiple curves being drawn, but MyCrosshair is only triggered for the last dataset. I suspect this problem is related to the following method that uses ‘PltPerfElev.Plot.LastRender’:

Dim nearest As DataPoint = splt.Data.GetNearest(mouseLocation, PltPerfElev.Plot.LastRender)

Is it possible to review the following code to present CrossHair for the entire dataset?

Here is my VB. NET implementation.
![Capturar-2](https://github.com/ScottPlot/ScottPlot/assets/104206448/80780cc0-6e87-48c4-b13c-79de50f05322)

```vv
 Private Sub MouseMoveHandler(
      s As Object, e As MouseEventArgs)

  Dim mousePixel As New Pixel(
      e.Location.X, e.Location.Y)
  Dim mouseLocation As Coordinates =
      PltPerfElev.Plot.GetCoordinates(mousePixel)
  Dim nearest As DataPoint = splt.Data.
      GetNearest(mouseLocation, PltPerfElev.Plot.LastRender)

  If nearest.IsReal Then
      MyCrosshair.IsVisible = True
      MyCrosshair.Position = nearest.Coordinates
      PltPerfElev.Refresh()
      lbPerfElev.Text = $"  X = {nearest.X:#,##0.0} m " &
          $"   -    Y = {nearest.Y:#,##0.0} cm"
  ElseIf MyCrosshair.IsVisible Then
      MyCrosshair.IsVisible = False
      PltPerfElev.Refresh()
      lbPerfElev.Text = $""
  End If
End Sub
```

**Comment by swharden** [comment]
Here's the C# version of that VB code (created using https://converter.telerik.com/). Providing the C# may help this question get answered quicker 👍 

```cs
private void MouseMoveHandler(object s, MouseEventArgs e)
{
    Pixel mousePixel = new Pixel(e.Location.X, e.Location.Y);
    Coordinates mouseLocation = PltPerfElev.Plot.GetCoordinates(mousePixel);
    DataPoint nearest = splt.Data.GetNearest(mouseLocation, PltPerfElev.Plot.LastRender);

    if (nearest.IsReal)
    {
        MyCrosshair.IsVisible = true;
        MyCrosshair.Position = nearest.Coordinates;
        PltPerfElev.Refresh();
    }
    else if (MyCrosshair.IsVisible)
    {
        MyCrosshair.IsVisible = false;
        PltPerfElev.Refresh();
    }
}
```

**Comment by swharden** [comment]
Re-stating the question: "How can I use the `Scatter.GetNearest()` if there are multiple scatter plots?"

It would be great if we could demonstrate how to achieve this by adding a new window to the demo application and noting the solution on https://scottplot.net/demo/

**Comment by jamaa** [comment]
I implemented something similar (in SP4 though). The code is very specific to the application it is in, so not really useful to share here. Basically, loop over all plottables, calling `GetPointNearest()` on each in turn, and then determine which one is closest to the mouse position by converting the nearest point's coordinates to a pixel location using `GetPixel()`. Then show the crosshair on the nearest one. 

I am willing to try my hand on a demo. I'll have a look at the demo application and see if I can add one there.

**Comment by swharden** [comment]
Hi @RubensMigliore, this is the code for the new demo app that shows how to display the point nearest the cursor across multiple scatter plots:

![multi](https://github.com/ScottPlot/ScottPlot/assets/4165489/6b10682e-a8ba-4cde-ae10-5cfcfefd129d)

```cs
using ScottPlot;
using ScottPlot.Plottables;
using ScottPlotCookbook.Recipes.PlotTypes;

namespace WinForms_Demo.Demos;

public partial class ShowValueOnHoverMultiple : Form, IDemoWindow
{
    public string Title => "Show Value Under Mouse, Multiple Series";

    public string Description => "How to sense where the mouse is in coordinate space " +
        "and retrieve information about the plottable and data the cursor is hovering over";

    List<ScottPlot.Plottables.Scatter> MyScatters = new();
    ScottPlot.Plottables.Crosshair MyCrosshair;
    ScottPlot.Plottables.Marker MyHighlightMarker;
    ScottPlot.Plottables.Text MyHighlightText;

    public ShowValueOnHoverMultiple()
    {
        InitializeComponent();

        // create 3 scatter plots with random points
        for (int i = 0; i < 3; i++)
        {
            double[] xs = Generate.RandomSample(30);
            double[] ys = Generate.RandomSample(30);
            ScottPlot.Plottables.Scatter scatter = formsPlot1.Plot.Add.ScatterPoints(xs, ys);
            scatter.Label = $"Scatter {i}";
            scatter.MarkerStyle.Size = 10;
            MyScatters.Add(scatter);
        }
        formsPlot1.Plot.ShowLegend();

        // Create a marker to highlight the point under the cursor
        MyCrosshair = formsPlot1.Plot.Add.Crosshair(0, 0);
        MyHighlightMarker = formsPlot1.Plot.Add.Marker(0, 0);
        MyHighlightMarker.Shape = MarkerShape.OpenCircle;
        MyHighlightMarker.Size = 17;
        MyHighlightMarker.LineWidth = 2;

        // Create a text label to place near the highlighted value
        MyHighlightText = formsPlot1.Plot.Add.Text("", 0, 0);
        MyHighlightText.Label.Alignment = Alignment.LowerLeft;
        MyHighlightText.Bold = true;
        MyHighlightText.OffsetX = 7;
        MyHighlightText.OffsetY = -7;

        // Render the plot
        formsPlot1.Refresh();

        // Evaluate points every time the mouse moves.
        // Indicate the nearest point by modifying the crosshair, text, marker, and window title.
        formsPlot1.MouseMove += (s, e) =>
        {
            // determine where the mouse is
            Pixel mousePixel = new(e.Location.X, e.Location.Y);
            Coordinates mouseLocation = formsPlot1.Plot.GetCoordinates(mousePixel);

            // get the nearest point of each scatter
            Dictionary<int, DataPoint> nearestPoints = new();
            for (int i = 0; i < MyScatters.Count; i++)
            {
                DataPoint nearestPoint = MyScatters[i].Data.GetNearest(mouseLocation, formsPlot1.Plot.LastRender);
                nearestPoints.Add(i, nearestPoint);
            }

            // determine which scatter's nearest point is nearest to the mouse
            bool pointSelected = false;
            int scatterIndex = -1;
            double smallestDistance = double.MaxValue;
            for (int i = 0; i < nearestPoints.Count; i++)
            {
                if (nearestPoints[i].IsReal)
                {
                    // calculate the distance of the point to the mouse
                    double distance = nearestPoints[i].Coordinates.Distance(mouseLocation);
                    if (distance < smallestDistance)
                    {
                        // store the index
                        scatterIndex = i;
                        pointSelected = true;
                    }
                }
            }

            // place the crosshair, marker and text over the selected point
            if (pointSelected)
            {
                ScottPlot.Plottables.Scatter scatter = MyScatters[scatterIndex];
                DataPoint point = nearestPoints[scatterIndex];

                MyCrosshair.IsVisible = true;
                MyCrosshair.Position = point.Coordinates;
                MyCrosshair.LineStyle.Color = scatter.MarkerStyle.Fill.Color;

                MyHighlightMarker.IsVisible = true;
                MyHighlightMarker.Location = point.Coordinates;
                MyHighlightMarker.MarkerStyle.Outline.Color = scatter.MarkerStyle.Fill.Color;

                MyHighlightText.IsVisible = true;
                MyHighlightText.Location = point.Coordinates;
                MyHighlightText.LabelText = $"{point.X:0.##}, {point.Y:0.##}";
                MyHighlightText.Color = scatter.MarkerStyle.Fill.Color;

                formsPlot1.Refresh();
                base.Text = $"Selected Scatter={scatter.Label}, Index={point.Index}, X={point.X:0.##}, Y={point.Y:0.##}";
            }

            // hide the crosshair, marker and text when no point is selected
            if (!pointSelected && MyCrosshair.IsVisible)
            {
                MyCrosshair.IsVisible = false;
                MyHighlightMarker.IsVisible = false;
                MyHighlightText.IsVisible = false;
                formsPlot1.Refresh();
                base.Text = $"No point selected";
            }
        };
    }
}
```

**Comment by RubensMigliore** [comment]
Hi, Scott. 

Great job! I appreciate your comments and the publication of the new source code. 

By converting to VB.NET and making some changes, I was successful in my attempt. I attach my complete code as well as the corresponding WinForm image in the hope that it will be useful to someone else.

Imports ScottPlot
Imports ScottPlot.Plottables
Imports ScottPlot.TickGenerators

Public Class FrmPerfElev

    Private MyScatters As List(Of Scatter) =
        New List(Of Scatter)()
    Private splt As Scatter

    Private MyMarker, MyHighlightMarker As Marker
    Private MyHighlightText As Text
    Private CrosshairElev As Crosshair

    Private ReadOnly Initializing As Boolean = True


#Region " Windows Form Designer generated code "

    Public Sub New()

        ' This is required by the Windows Form Designer
        InitializeComponent()
        ' Add any initialization after the InitializeComponent()

        Initializing = False
    End Sub

#End Region
    Private Sub FormLoad() Handles MyBase.Load
        MostraPerfElev()
    End Sub

    Private Sub cmCentralizarClick(
            sender As Object, e As EventArgs
        ) Handles cmCentralizar.Click
        MostraPerfElev()
    End Sub

    Private Sub MostraPerfElev()

        Dim result As DataRow()
        Dim myPalette = New Palettes.Category10()
        Dim _Hini, _Hfin, _CGini As Double
        Dim xPerfil(4), yPerfil(4) As Double

        With PltPerfElev.Plot
            .Clear()
            .Style.Background(figure:=Colors.White, data:=Colors.White)

            For k = 1 To NCab
                Dim EixoX As New List(Of Double)()
                Dim EixoY As New List(Of Double)()

                ' ***  cria linhas para cabos de protensão
                For i = 0 To NroSecCoord
                    With FrmInicial.dsInterno.Tables("TabCotas")
                        If .Rows(2 * k - 1)(i + 2) IsNot DBNull.Value Then
                            EixoX.Add(SecCoord(i))
                            EixoY.Add(CDbl(.Rows(2 * (k - 1))(i + 2)))
                        End If
                    End With
                Next i

                splt = PltPerfElev.Plot.Add.ScatterPoints(
                        EixoX.ToArray(), EixoY.ToArray())
                MyScatters.Add(splt)
                With splt
                    .Color = myPalette.GetColor(k - 1)
                    .Label = $"C{k}"
                    .LineWidth = 2
                    .LinePattern = LinePattern.Solid
                    .MarkerSize = 2
                    .MarkerStyle.Shape = MarkerShape.FilledCircle
                End With

                ' Desenha contorno 
                GeraElevacao(_Hini, _CGini, _Hfin, xPerfil, yPerfil)
                splt = .Add.Scatter(xPerfil, yPerfil)
                With splt
                    .Color = Colors.LightSlateGray
                    .LineWidth = 1
                    .LinePattern = LinePattern.Solid
                    .MarkerStyle.Shape = MarkerShape.None
                End With

                ' mostra pontos notáveis
                result = FrmInicial.dsInterno.Tables("PtosControleY").
                        Select($"Cabo = {k}", "Pto ASC")
                AcertaAncoragem(k, result.Length)
                For i = 0 To result.Length - 1
                    .Add.Marker(
                        x:=CDbl(result(i)("CoordXY")),
                        y:=CDbl(result(i)("CoordY")) * 100,
                        size:=Tam(i),
                        shape:=CType(Forma(i),
                        MarkerShape),
                        color:=myPalette.GetColor(k - 1))
                Next i
            Next k

            ' Create a marker to highlight the point under the cursor
            CrosshairElev = PltPerfElev.Plot.Add.
                Crosshair(-0.05 * ComprTotal, -0.05 * _Hfin)
            MyHighlightMarker = PltPerfElev.Plot.Add.Marker(0, 0)
            With MyHighlightMarker
                .Shape = MarkerShape.FilledCircle
                .Size = 17
                '.LineWidth = 2
                .MarkerStyle.Size = 2
                .Color = Colors.Orange
            End With

            ' Create a text label to place near the highlighted value
            MyHighlightText = PltPerfElev.Plot.Add.Text("", 0, 0)
            With MyHighlightText
                .Label.Alignment = Alignment.LowerLeft
                .Bold = True
                .Label.OffsetX = 7
                .Label.OffsetY = -7
            End With

            ' Render the plot
            PltPerfElev.Refresh()

            ' customize the axis labels
            .Axes.SetLimitsX(-0.05 * ComprTotal, 1.05 * ComprTotal)
            Dim Pot As Integer = GetMaxPowerOf10(1.05 * ComprTotal)
            Dim Intervalo As Integer = CInt(1.05 * ComprTotal / (8 * Pot)) * Pot
            With .Axes.Bottom
                .Label.Text = "Seções de coordenadas X (m)"
                .Label.FontSize = 12
                .Label.ForeColor = Colors.Black
                .Label.FontName = "Tahoma"
                .Label.Bold = False
                .TickGenerator = New NumericFixedInterval(Intervalo)
            End With

            .Axes.SetLimitsY(-0.05 * _Hfin, 1.1 * _Hfin)
            Pot = GetMaxPowerOf10(1.05 * _Hfin)
            Intervalo = CInt(1.05 * _Hfin / (4 * Pot)) * Pot
            With .Axes.Left
                .Label.Text = "Coordenadas Y (cm)"
                .Label.FontSize = 12
                .Label.ForeColor = Colors.Black
                .Label.FontName = "Tahoma"
                .Label.Bold = False
                .TickGenerator = New NumericFixedInterval(Intervalo)
            End With

            .ShowLegend()
            .Legend.Location = Alignment.UpperCenter
            .Legend.Orientation = Orientation.Horizontal

            ' ***  linha de CG
            Dim HlineCG = .Add.Line(0, _CGini, ComprTotal, _CGini)
            With HlineCG
                .LineColor = Colors.Magenta
                .LineWidth = 1
                .LinePattern = LinePattern.Dashed
            End With

            Dim CGtext = .Add.Text("CG", 0.9 * ComprTotal, _CGini)
            With CGtext.Label
                .FontSize = 12
                .ForeColor = Colors.Black
            End With

            ' ***  linha de Hfin
            Dim HlineHfin = .Add.Line(0, _Hfin, ComprTotal, _Hfin)
            With HlineHfin
                .LineColor = Colors.LightSlateGray
                .LineWidth = 1
                .LinePattern = LinePattern.Solid
            End With

            Dim HtextFin = .Add.Text("H final", 0.8 * ComprTotal, _Hfin)
            With HtextFin.Label
                .FontSize = 12
                .ForeColor = Colors.Black
            End With

            ' ***  linha de Hini
            If _Hfin > _Hini Then
                Dim HlineHini = .Add.Line(0, _Hini, ComprTotal, _Hini)
                With HlineHini
                    .LineColor = Colors.Orange
                    .LineWidth = 1
                    .LinePattern = LinePattern.Dashed
                End With
            End If

            Dim HtextIni = .Add.Text("H inicial", 0.9 * ComprTotal, _Hini)
            With HtextIni.Label
                .FontSize = 12
                .ForeColor = Colors.Black
            End With

            AddHandler PltPerfElev.MouseMove, AddressOf MouseMoveHandlerElev

        End With
        PltPerfElev.Refresh()
    End Sub


    Private Sub GeraElevacao(ByRef _Hini As Double,
            ByRef _CGini As Double, ByRef _Hfin As Double,
            xPerfil As Double(), yPerfil As Double())

        Dim i As Integer = SecRef + 1

        With FrmInicial.dsInterno.Tables("PropSec")
            _Hini = CDbl(.Rows(0)(i))   ' altura H inicial
            _CGini = CDbl(.Rows(1)(i))  ' CG inicial
            _Hfin = CDbl(.Rows(12)(i))  ' altura H  final
        End With

        ' ***  para desenhar linhas de perfil da viga
        ' extremidade inferior esquerda
        xPerfil(0) = 0
        yPerfil(0) = 0

        ' extremidade superior esquerda
        xPerfil(1) = 0
        yPerfil(1) = _Hfin

        ' extremidade superior direita
        xPerfil(2) = ComprTotal
        yPerfil(2) = _Hfin

        ' extremidade inferior direita
        xPerfil(3) = xPerfil(2)
        yPerfil(3) = 0

        ' retorna ao início 
        xPerfil(4) = 0
        yPerfil(4) = 0
    End Sub

    Private Sub MouseMoveHandlerElev(
            s As Object, e As MouseEventArgs)

        ' determine where the mouse is
        Dim mousePixel As Pixel = New Pixel(
            e.Location.X, e.Location.Y)
        Dim mouseLocation As Coordinates =
            PltPerfElev.Plot.GetCoordinates(mousePixel)

        ' get the nearest point of each scatter
        Dim nearestPoints As Dictionary(Of Integer, DataPoint) =
            New Dictionary(Of Integer, DataPoint)()
        For i = 0 To MyScatters.Count - 1
            Dim nearestPoint As DataPoint =
                MyScatters(i).Data.GetNearest(mouseLocation,
                    PltPerfElev.Plot.LastRender)
            nearestPoints.Add(i, nearestPoint)
        Next i

        ' determine which scatter's nearest point is nearest to the mouse
        Dim pointSelected As Boolean = False
        Dim scatterIndex As Integer = -1
        Dim smallestDistance As Double = Double.MaxValue

        For i = 0 To nearestPoints.Count - 1
            If nearestPoints(i).IsReal Then
                ' calculate the distance of the point to the mouse
                Dim distance As Double = nearestPoints(i).
                    Coordinates.Distance(mouseLocation)
                If distance < smallestDistance Then
                    ' store the index
                    scatterIndex = i
                    pointSelected = True
                End If
            End If
        Next i

        ' place the crosshair, marker and text over the selected point
        If pointSelected Then
            Dim scatter As Scatter = MyScatters(scatterIndex)
            Dim point As DataPoint = nearestPoints(scatterIndex)

            With CrosshairElev
                .IsVisible = True
                .Position = point.Coordinates
                .LineStyle.Color = Colors.Orange
            End With

            With MyHighlightMarker
                .IsVisible = True
                .Location = point.Coordinates
                .MarkerStyle.Outline.Color =
                   scatter.MarkerStyle.Fill.Color
                .Color = Colors.Orange
                .Size = 10
            End With

            With MyHighlightText
                .IsVisible = True
                .Location = point.Coordinates
                .LabelText = $"{point.X:#,##0.00}; {point.Y:#,##0.00}"
            End With

            lbPerfElev.Text = $"Coord. X = {point.X:#,##0.00} m" &
                $" - Coord. Y = {point.Y:#,##0.00} cm"

        End If
        Refresh()
    End Sub

End Class

![Capturar-2](https://github.com/ScottPlot/ScottPlot/assets/104206448/6bec103d-3cfa-46b0-bbdc-c2272f29bb1e)
