### ISSUE TITLE
Font: Automatic font detection is poor on Linux

### ISSUE THREAD

**Issue by atmoraes1** [ScottPlot/ScottPlot#3504]
Below is a difference between running on a Windows development machine and an ASPNET 8 Linux container.

The image is a chiseled one, so maybe some fonts are not available.

Windows:
![image](https://github.com/ScottPlot/ScottPlot/assets/139466904/69c6f93c-08bb-4df4-b90e-a5c6ff243066)

Linux container:
![output](https://github.com/ScottPlot/ScottPlot/assets/139466904/f435cec7-41fe-4f8d-99ee-ce014ad55068)

Is there any workaround to avoid installing external libs in the final docker image?

**Comment by swharden** [comment]
> The image is a chiseled one, so maybe some fonts are not available.

Could be! Try `myPlot.Style.SetBestFonts()` and cross your fingers, or use an adjacent method (I forgot the name) to use a specific font you know is available on your system

https://scottplot.net/cookbook/5.0/Internationalization/AutomaticFontDetection/

**Comment by swharden** [comment]
... also you may need to render once before trying to detect best fonts?

```cs
myPlot.Render(); // something like this
myPlot.Style.SetBestFonts();
```

**Comment by atmoraes1** [comment]
I've found a solution, 

1. When using the Linux.NoDependecies, SkiaSharp won't tie the FontConfig to the default SKFontManager. [GitHub comment](https://github.com/mono/SkiaSharp/issues/1131#issuecomment-583458725).
2. .NET images don't have fonts by default.

So, to have fonts for ScottPlot we just need to copy the fonts to /usr/share/fonts as described [here](https://github.com/mono/SkiaSharp/issues/1131#issuecomment-583458839)

An example of a resulting Dockerfile, note that is for .NET 8, so the dir creation and file copying should be done before changing the user context:
```dockerfile
#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
RUN mkdir /usr/share/fonts # <--- Create font dir with default read permission
COPY TestCharts/Fonts/ /usr/share/fonts/ # <--- Copy fonts
USER app
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["TestCharts/TestCharts.csproj", "TestCharts/"]
RUN dotnet restore "./TestCharts/TestCharts.csproj"
COPY . .
WORKDIR "/src/TestCharts"
RUN dotnet build "./TestCharts.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./TestCharts.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TestCharts.dll"]
```

After that the fonts will be picked up by SkiaSharp, if only one font is there, that'll be the default font.

![output](https://github.com/ScottPlot/ScottPlot/assets/139466904/21009a71-f423-47dd-82ba-7666cac15c36)
