### ISSUE TITLE
Please consider a TimeSpan array for the X-axis.

### ISSUE THREAD

**Issue by CBrauer** [ScottPlot/ScottPlot#3505]
Hey people,

In doing financial plots, especially for day-trading, the X-axis is for one day only. For the Stock Market, the time range is from 9:30 AM to 4;00 PM New York Time.

A DateTime format is too verbose. I propose a format like: “H:mm tt”.
Code like:
```cs
// Arrays for Scatter:
TimeSpan[] X = new TimeSpan[price.Length];
double[] Y = new double[price.Length];
for (int k = 0; k < price.Length; k++)
{
    // Convert to TimeSpan array with only hours and minutes
    TimeSpan[] tradeHourMinute = tradeTime.Select(time => new TimeSpan(time.Hour, time.Minute, 0)).ToArray();
    X[k] = tradeHourMinute[k];
    Y[k] = (double) price[k];
}
```
will not work at this time.
Please consider including a TimeSpan for the X-axis.

**Comment by swharden** [comment]
Hi @CBrauer, thanks for the suggestion!

I'm not sure it makes sense to display an array of `TimeSpan` on a horizontal axis. Taking your example, let's assume we wish to plot data in one-minute bins. Your `TimeSpan[] xs` would be an array of "one minute, one minute, one minute, one minute", which wouldn't be useful. `TimeSpan` only reports how long a range of time is, and isn't aware of a start of end time.

I think I understand what the goal is here though: you wish to plot financial data on arbitrary short time scales. All the cookbook examples currently show one-bar-per-day. I think the fix here is for me to add a cookbook example demonstrating financial plots with shorter time increments. I'll add that now 👍
