### ISSUE TITLE
I used WpfPlot.Plot.Add.Scatter to create a line plot, but two lines appeared instead

### ISSUE THREAD

**Issue by JackHuHappy** [ScottPlot/ScottPlot#3509]
```cs 
  private DispatcherTimer AddNewDataTimer;
  private DispatcherTimer UpdatePlotTimer;

  private int i = 1;
  readonly ScottPlot.Plottables.DataLogger Logger;
  private const int max = 100;
  private double[] YDatas=new double[max];
  private double[] XDatas = new double[max];
  private int nextIndex = 0;
  public MainWindow()
  {
      InitializeComponent();

      WpfPlot1.Plot.Add.Scatter(XDatas, YDatas);
      WpfPlot1.Interaction.Disable();
      WpfPlot1.Plot.HideGrid();


      AddNewDataTimer = new DispatcherTimer();
      AddNewDataTimer.Interval = TimeSpan.FromMilliseconds(50);
      AddNewDataTimer.Tick += new EventHandler(GetData);
      AddNewDataTimer.Start();

      UpdatePlotTimer = new DispatcherTimer();
      UpdatePlotTimer.Interval = TimeSpan.FromMilliseconds(50);
      UpdatePlotTimer.Tick += (s, e) =>
      {
          WpfPlot1.Plot.Axes.AutoScale();
          WpfPlot1.Refresh();
      };
      UpdatePlotTimer.Start();

  }

   private void GetData(object? sender, EventArgs e)
   {
       for (int j = 0; j < 10; j++)
       {
           if (nextIndex > 10)
           {
               return;
           }
           if (nextIndex == max)
           {
               Array.Copy(XDatas, 1, XDatas, 0, nextIndex - 1);
               Array.Copy(YDatas, 1, YDatas, 0, nextIndex - 1);
               XDatas[nextIndex - 1] = i;
               YDatas[nextIndex - 1] = i*0.2+0.1;
           }
           else
           {
               XDatas[nextIndex] = i;
               YDatas[nextIndex] = i * 0.2 + 0.1;
               nextIndex++;
           }
           i++;
       }
   }
}
```

![tmp](https://github.com/ScottPlot/ScottPlot/assets/128368577/2f458383-87b7-4241-a2e4-142cb3febcdf)

**Comment by JackHuHappy** [comment]
my development :wpf .donet 8

**Comment by JackHuHappy** [comment]
![image](https://github.com/ScottPlot/ScottPlot/assets/128368577/a6f3464b-a6fc-401e-a0f5-882a802bacb6)
this vesion is  scottplot 5.0.22; and scottplot 4.1.72 have this problem 
![image](https://github.com/ScottPlot/ScottPlot/assets/128368577/6ca24307-afac-4c13-b44a-ad61a4cb3a2b)

**Comment by JackHuHappy** [comment]
I found the cause of the issue. I'm rendering real-time data using a fixed-length array. The official example provided by the documentation is for rendering with a single y-axis. By changing the maximum rendering count of the scatter plot before refreshing the image, I can avoid the issue of uninitialized indices affecting the plot. However, there is no such setting in the scatter plot. I would like to know how to set the maximum rendering index in the scatter plot

**Comment by swharden** [comment]
Thanks for following-up with your solution @JackHuHappy!

We definitely plan to add min/max render index to ScottPlot 5's scatter plot, and hopefully this feature will be in an upcoming release soon! #3308
