### ISSUE TITLE
Create a full-featured financial charting demo

### ISSUE THREAD

**Issue by lakshmanven** [ScottPlot/ScottPlot#3511]
I am using scott plot 5. Can I create a plot similar to the attached chart. I will appreciate any help here. I am very new to Scott Plot. So, I am not sure how to do this.  
![Chart](https://github.com/ScottPlot/ScottPlot/assets/121567711/e2f87a7e-a882-4660-8e07-1947daa45672)

**Comment by lakshmanven** [comment]
This is basically a chart for stock prices for the last 10 years for different tickers. The price axis on RHS is logarithmic. The EPS axis LHS is linear. There are additional lines of information at the top and bottom. I can do without the volume graph at the bottom. That is a nice to have.

**Comment by lakshmanven** [comment]
To be precise, there are 2 lines of information above the chart, and 3 below.

**Comment by swharden** [comment]
@lakshmanven thanks for this suggestion! This topic just came up in the Discord #1966 and we definitely want to prioritize adding features to support the application style you screenshotted and demonstrate how to use them in a demo app. I'll use this open issue to track progress on this front! 🚀

**Comment by swharden** [comment]
See recent messages by "Damien-TradeForge" on the Discord #1966 "#support" channel

**Comment by lakshmanven** [comment]
Any updates on this?

**Comment by swharden** [comment]
> Any updates on this?

Yes! See the recent discussion on #4385 -- there is new enthusiasm for bringing the capabilities of ScottPlot closer toward those provided by apps like TradingView
