### ISSUE TITLE
Axes: How to disable the primary axes and reclaim that space

### ISSUE THREAD

**Issue by CBrauer** [ScottPlot/ScottPlot#3518]
Hi guys,

I'm concerned about wasted screen space around plots.

If I specify the Y-axis to be on the right side of the plot, there seems to be space on the left side where the default Y-axis is labeling used to be.  The same with Title space.

Here are plots that show arrows where the space is not reclaimed if it is not used. 

I propose that the plot rectangle show below, should be expanded closer to the left side of the canvas when the Y-axis is moved, and the plot box should be expanded up to the top edge when no Title is specified.

The arrows show where the waisted space is.

![Margin and Padding](https://github.com/ScottPlot/ScottPlot/assets/1317234/6383fe0c-5994-4971-bba9-13c2fd8743ce)

I also experimented with plot margins and padding.  The bottom plot has the additional code:

    `  formsPlot1.Margin = new Padding(40, 100, 100, 100);`

It is my understand that the four numbers represent left, top, right, bottom padding.
It appears that only the first number is used.  Is this a bug?

Charles

**Comment by swharden** [comment]
Hi @CBrauer, thanks for this question! I believe it has been fixed in ScottPlot 5.0.24 (#3608) but let me know if it doesn't perform as expected and we can open this issue back up and take a closer look 👍
