### ISSUE TITLE
SP4/SP5: Label "last render rectangle" is inaccurate when rotation is used

### ISSUE THREAD

**Issue by DaveMartel** [ScottPlot/ScottPlot#3519]
**Issue:** When a Text is rotated, the calculation of the LastRenderRectangleCoordinates is not correct. This leads to weird behaviour when trying to grab and drag. 

It is not easy to show this in a reproducible example that produces a screen shot, as it is dynamic behaviour. I am including a simple example that puts a plot and label in a state where it is almost impossible to drag the label. You can see this by moving the mouse over and near the label, and it only changes to a drag cursor in a very narrow band of pixels (I will try and show this area in a screen shot.

**ScottPlot Version:** 4.1.71

**Code Sample:

```cs
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            DoTest2();
        }

        private void DoTest2()
        {
            var txt = formsPlot1.Plot.AddText("01234567890123456789\r\n01234\r\n01", 0, 0, 12, Color.Red);
            txt.DragEnabled = true;
            txt.Rotation = 70;
            formsPlot1.Refresh();
        }
    }
```

When this is run the only area I can grab the label is shown here....

![image](https://github.com/ScottPlot/ScottPlot/assets/24892075/a504168a-f1fb-442b-8a31-f2ba3c917129)

in order to more carefully investigate this I put in some code to actually render the LastRenderRectangleCoordinates immediately after the label, and I animated rotation, and watched the LastRenderRectangleCoordinates change change shape and location is a graceful ballet. This is a screen grab of it around 60 deegrees...

![image](https://github.com/ScottPlot/ScottPlot/assets/24892075/7c973baa-d601-4a26-b74c-d7fcb3070502)

I proved to myself this rendering is correct, as the grab cursor only appears when the mouse is over the red box...

**Comment by swharden** [comment]
Thanks for reporting this @DaveMartel! I'm definitely going to fix this, but it's a can of worms so I'm trying to knock out some other open high priority issues before looping back to this one.

Related: https://swharden.com/blog/2022-02-01-point-in-rectangle/

![](https://swharden.com/static/2022/02/01/point-inside-rotated-rectangle.gif)

![](https://swharden.com/static/2022/02/01/rectangle-point-inside.png)

**Comment by swharden** [comment]
This likely remains unfixed but there hasn't been comment on it for several months so I'll close this open issue, but if someone hits this again and is inspired to fix it, I'd be happy to review a pull request in good time and merge it in so it will be in the next release 👍
