### ISSUE TITLE
SP5 the behavior of Bar.Label is weird when BarPlot.Horizontal is true

### ISSUE THREAD

**Issue by yui1227** [ScottPlot/ScottPlot#3520]
**Issue:** the behavior of Bar.Label is weird when BarPlot.Horizontal is true. the position of value is wrong.

**ScottPlot Version:** 5.0.22

**Code Sample:** 

```cs
using ScottPlot;

var plot = new Plot();

double[] values = { 1, 2, 3, 4, 5 };
var barPlot = plot.Add.Bars(values);

foreach (var bar in barPlot.Bars)
{
    bar.Label = $"{bar.Value}";
}

plot.Save("vert.png", 500, 500);
barPlot.Horizontal = true;
plot.Save("hori.png", 500, 500);
```
![vert](https://github.com/ScottPlot/ScottPlot/assets/77109827/0fd9292b-5a74-40dd-a2cd-b165b53d49f3)
![hori](https://github.com/ScottPlot/ScottPlot/assets/77109827/19232274-cf58-4aae-b8ae-d5bb49b8d810)

**Comment by swharden** [comment]
This is the code that needs to be modified:

https://github.com/ScottPlot/ScottPlot/blob/df89ed6e9286c4ccb4ef751ced541a4002a0f67f/src/ScottPlot5/ScottPlot5/Primitives/Bar.cs#L107-L108

An `if` condition should be add to place the label on the correct side given the value of `this.Orientation`

... also maybe logic should be added to support "negative" vs. "positive" bars too

**Comment by swharden** [comment]
Thanks for reporting this @yui1227! I'll drop this information here in case someone wants to try adding this feature before I'm able to get to it. If someone creates a PR, I'm happy to review it in good time! 🚀 

This is the code that needs to be modified:

https://github.com/ScottPlot/ScottPlot/blob/df89ed6e9286c4ccb4ef751ced541a4002a0f67f/src/ScottPlot5/ScottPlot5/Primitives/Bar.cs#L107-L108

An `if` condition should be add to place the label on the correct side given the value of `this.Orientation`

... also maybe logic should be added to support "negative" vs. "positive" bars too

**Comment by aespitia** [comment]
PR submitted for this

https://github.com/ScottPlot/ScottPlot/pull/3546
