### ISSUE TITLE
Scottplot 5.0  winform charts not working in .Net Framework 4.8

### ISSUE THREAD

**Issue by Aiken10** [ScottPlot/ScottPlot#3526]
Scottplot 5.0  winform charts not working in .Net Framework 4.8

**Comment by herogx** [comment]
Yes. I encounter the same issue with VS2017 winform.
I tried both 4.7 & 4.8, all failed

**Comment by swharden** [comment]
Hi @Aiken10 and @herogx,

I think this is a Visual Studio bug causing the control not to appear in the toolbox. The recommended solution is to add a `Panel` to your window where you want the plot to appear, then add the plot programmatically

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/56b17ca1-bb88-429c-bf27-5fb490a674e9)

```cs
using System.Windows.Forms;

namespace WindowsFormsApp33
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            var formsPlot1 = new ScottPlot.WinForms.FormsPlot() { Dock = DockStyle.Fill };
            panel1.Controls.Add(formsPlot1);

            double[] data = ScottPlot.Generate.Sin();
            formsPlot1.Plot.Add.Signal(data);
            formsPlot1.Refresh();
        }
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/6e480965-656d-472b-8611-0736c849294f)

Related: https://scottplot.net/faq/add-winforms-programmatically/
