### ISSUE TITLE
Legend: Add support for rows and columns

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3531]
Recent progress was made adding horizontal and vertical orientation, but plots with many items would benefit from legends with items that can wrap to accommodate a large number of labels.

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/93f1e187-0bda-4c01-86dd-11d83ba6c107)

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/987f8095-3408-4c05-8dc7-f18482bbd2be)

**Comment by swharden** [comment]
resolved in https://github.com/ScottPlot/ScottPlot/pull/3689

**Comment by AscendLiu** [comment]
@swharden Hello, may I ask how to display a large number of Legends, such as using controls like ScrollViewer

**Comment by AscendLiu** [comment]
> @swharden你好，请问如何显示大量的图例，比如使用ScrollViewer这样的控件

I referred to the example provided [src/ScottPlot5/ScottPlot5 Demos/ScottPlot5 WinForms Demo/Demos/LegendOutsideBitmap.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/LegendOutsideBitmap.cs)，now,It met my expectations

![image](https://github.com/user-attachments/assets/4a3f05ae-dabf-42b7-9382-512a5f80f2a4)
