### ISSUE TITLE
Axes: Improve support for log scaling (and add cookbook recipes)

### ISSUE THREAD

**Issue by IVANYYY** [ScottPlot/ScottPlot#3539]
I am wondering if ScottPlot library would be possible to add a function similar to the `ax.set_xscale('log')` function in the Python Matplotlib library. This function would allow for a quick switch of the X-axis or Y-axis scale to a logarithmic scale. Furthermore, when the scale is switched, the corresponding values would automatically be converted to their logarithmic values.

I believe this feature would greatly enhance the functionality and user-friendliness of the ScottPlot library. I look forward to hearing your thoughts on this suggestion.

**Comment by swharden** [comment]
Hi @IVANYYY, thanks for this question! It comes up a lot, but it's a good topic to address.

For now, users can manually log-transform their data and display it on a graph with log-scaled grid lines and minor ticks. https://scottplot.net/cookbook/5.0/CustomizingTicks/LogScaleTicks/

Implementing log scaling may be pretty difficult if it requires modifying every plot type to display things differently, but I'll leave this issue open to track researching whether this could be achieved by modifying the axis system somehow, so a single switch could be flipped and all data will be log-transformed in real time as it's plotted.

I'll also use this issue to track progress toward improving log-scale cookbook examples.

**Comment by swharden** [comment]
There's been pretty good progress recently adding custom grids that implement `IPlottable` and giving them methods to translate to and from Cartesian coordinates. See #4413 for implementation suggestions.

If someone creates a PR I'd be happy to review it. I'll close this for now since there hasn't been much movement in a while.
