### ISSUE TITLE
LegendItem: The `IsVisible` property should be settable

### ISSUE THREAD

**Issue by blahetal** [ScottPlot/ScottPlot#3541]
**Suggestion:** I am displaying a plot which has multiple lines, for each line I display a legend. User can hide some of the lines but legend for that line is still visible - I need to recreate the `Plot.Legend.ManualItems` every time I do this and add/remove the affected lines from/to legend.

```cs
Plot.Legend.ManualItems.Add(new() {
   Label = "label1",
   IsVisible = true // add something like this - the default would be true
});
```

later in code

```cs
Plot.Legend.ManualItems[0].IsVisible = false;
```

Thanks for considering this,
Libor

**Comment by swharden** [comment]
Thanks for this suggestion @blahetal!

There is an `IsVisible` property, but it's not user configurable...

https://github.com/ScottPlot/ScottPlot/blob/b12cb0c1ae5ddd76fe4e7a686fac79cc57519fbb/src/ScottPlot5/ScottPlot5/Primitives/LegendItem.cs#L19

I'll use this issue to track implementing the feature you suggest 👍
