### ISSUE TITLE
Legend: Add logic to return the `LegendItem` under the mouse

### ISSUE THREAD

**Issue by blahetal** [ScottPlot/ScottPlot#3542]
**Suggestion:** I would like to add a custom action when user clicks on an item in a legend. eg. I display N lines in a plot, each line has an entry in legend. By clicking on legend item I would like to hide/show/change the corresponding line.

**Comment by swharden** [comment]
@blahetal, thanks for this suggestion too! Indeed, ScottPlot 4 had similar functionality (albeit only for the WinForms control).

Probably the way I'd approach this is to add some state to `Legend.cs` that "remembers" where each legend item was rendered, storing the `PixelRect` for each `LegendItem`. Then a method like this could be added to that file:

```cs
// Returns the legend item at the given pixel (from the previous render).
// Returns null if no legend item is at that pixel.
public LegendItem? GetItem(Pixel px) 
{
  /* ... */
}
```

I may get to this eventually, but if you or someone else wants to have a go at this before I can, I would be happy to review a PR! 🚀

**Comment by swharden** [comment]
I'll close this since there hasn't been movement in a while, but if someone from the community wants to implement this I'd be happy to review a PR 👍
