### ISSUE TITLE
Legend: items are not hidden when plottables are hidden

### ISSUE THREAD

**Issue by pkstrsk** [ScottPlot/ScottPlot#3545]
**Issue:** Legend showing all added plottables, hidden or not

**ScottPlot Version:** 5.0.23

**Code Sample:** Default code from cookbook, styled a little

ScottPlot 5.0.21
![image](https://github.com/ScottPlot/ScottPlot/assets/14115952/a9ed9657-56b5-4e09-bcad-306ed95461cd)
![image](https://github.com/ScottPlot/ScottPlot/assets/14115952/1c14ccde-9898-49f1-8066-47a7dec59a58)

And after update to 5.0.23
![image](https://github.com/ScottPlot/ScottPlot/assets/14115952/03a48ecf-a9d6-4957-8547-f2194c51c0bb)

**Comment by blahetal** [comment]
I think this issue is related
https://github.com/ScottPlot/ScottPlot/issues/3541
