### ISSUE TITLE
Font alignment issues

### ISSUE THREAD

**Issue by VibrationAnalystCN** [ScottPlot/ScottPlot#3556]
**Several suggestions:**

1. The distance setting between the title and chart is unreasonable. If the title uses the default font size, the distance between the title and the chart is far, and there is more white space in the middle. If the title is in large font size, the spacing will be smaller. It is recommended to set a fixed distance between the bottom edge of the title and the upper edge of the chart, so that the title looks comfortable regardless of the font size used.

2. There is no gap between the upper edge of XLabel and the bottom edge of the horizontal axis value. It is recommended to set the gap.

3. **_Plot.Add.VerticalLine_** and **_Label.Text_**. Several VerticalLines may be set in a chart，can the corresponding Label.Text be aligned at the top??

4. If the vertical coordinate data is too small, there may be several zeros after the decimal point. Can we add the option of thousand scale units for the vertical axis (i.e. p, μ, m. K, M, etc.)? For this example, the vertical axis can be 0,1,2,3... 12,13, and the scale unit "m" can be added above 13.
![github建议](https://github.com/ScottPlot/ScottPlot/assets/165245736/66febce8-df7a-4d09-bc8e-1cf9a0860bfb)

**Comment by swharden** [comment]
1. layout issue was recently fixed in #3610 and will be in the next release
2. line height issues with international characters - I'll look into this further
3. vertical line label alignment - I'll look into this further
4. custom tick labels can be created using this strategy: https://scottplot.net/cookbook/5.0/CustomizingTicks/CustomTickFormatter/

**Comment by swharden** [comment]
Actually, both 2. and 3. may have been fixed in #3558 which will be in the next release too.

I'll close this issue assuming all issues are resolved in ScottPlot 5.0.24 when it comes out (probably later today), but feel free to re-open this issue if an issue persists.

**Comment by VibrationAnalystCN** [comment]
I received your email and will do the test recently.
Thank you for your contribution to the open source chart.
