### ISSUE TITLE
Add ColorBar Title

### ISSUE THREAD

**Issue by mawbydp** [ScottPlot/ScottPlot#3560]
**Suggestion:** (Describe your idea here)
Add custom title label for colorbars andd move the tickmakers closer to the color bar
![image](https://github.com/ScottPlot/ScottPlot/assets/91740023/c20ae0de-7bf0-44be-a63e-751d2c794abd)

**Comment by swharden** [comment]
Thanks for reporting this @mawbydp! It's similar to #3294 and definitely should be improved. I'm going to make both issues high priority and hopefully will have a fix soon in an upcoming release!

**Comment by swharden** [comment]
Hi @mawbydp, I think this has been fixed in #3610 and will be in the next release! 🚀 Thanks again for originally pointing this out.
