### ISSUE TITLE
DataStreamer: Scroll view causes the plot to zoom out only (not zoom in)

### ISSUE THREAD

**Issue by hazenjaqdx3** [ScottPlot/ScottPlot#3561]
**Issue:** When running a Datastream the Graph cannot be zoomed into further than the largest plotted data. Even though it has long dissapeared from the visible Data. (could there be a way to discharge the first data set in the DataStreamer Points arg? 

**ScottPlot Version:** 5.0.23

**Code Sample:** 

```cs

using ScottPlot;


namespace FinalFinal
{
    public partial class Form1 : Form
    {
        private BackgroundWorker UIWorker;

        public new List<double> dataX;
        public new List<double> dataY;
        public bool firstCon = false;

        public ScottPlot.Plottables.DataStreamer StreamX;
        public ScottPlot.Plottables.DataStreamer StreamY;

        public Int32 AverageX1;
        public Int32 AverageY1;

        public int DisplayX1 = 0;
        public int DisplayY1 = 0;

        public Form1()
        {
            InitializeComponent();

            if (firstCon == false)
            {
                initvoid();
            }

            UIWorker.DoWork += UIWorker_DoWork;
        }



        private void initvoid()
        {

            UIWorker = new BackgroundWorker();
            StreamX = formsPlot1.Plot.Add.DataStreamer(100000);
            StreamY = formsPlot1.Plot.Add.DataStreamer(100000);

            dataX = new List<double>();
            dataY = new List<double>();
            firstCon = true;

            StreamY.ViewScrollLeft();
            StreamX.ViewScrollLeft();
        }

        public void NewRealtimeData(Int32 X1, Int32 Y1)
        {
		// DISPLAYX1 AND DISPLAYY1 ARE JUST TWO VALUES WHICH I MEASURE WITH A SENSOR

            // Add X1 value to dataX list
            dataX.Add(DisplayX1);
            dataY.Add(DisplayY1);


            //If dataX list is full, add it to the Streamer
            if (dataX.Count >= 1000 && !UIWorker.IsBusy) // Adjust the threshold as needed
            {
                    UIWorker.RunWorkerAsync();
            }
        }

        private void UIWorker_DoWork(object sender, DoWorkEventArgs e)
        {
            if (IsHandleCreated)
            {
                Invoke(new Action(() =>
                {
                    if (chkX.Checked)
                    {
                        StreamX.AddRange(dataX.ToArray()); // Add dataX list to Streamer
                    }

                    if (chkY.Checked)
                    {
                        StreamY.AddRange(dataY.ToArray());
                    }

                    formsPlot1.Refresh();
                }));
            }

            dataX.Clear(); // Clear dataX list after adding to Streamer
            dataY.Clear();
        }
    }
}

```

This is a gif of what I mean (please ignore the two lines "Alarm") 
![SVWyh](https://github.com/ScottPlot/ScottPlot/assets/10399360/120903ce-a7de-499d-bc6f-57095709ed41)

Also I have a question regarding this / similar : 

I want to display the X/Y Points in a scatter Plot. How can I only show the 100 newest points and discard the older ones?

**Comment by zhhding** [comment]
have the sampe problem too.mark this.

**Comment by Xhichn** [comment]
`DataStreamer` tracks the min and max when new data comes in, which means the min can only get smaller and the max can only get bigger. It seems like we need to set axis limits manually for now to scale the plot down when using `DataStreamer` . 

Source for `Add` function in `DataStreamerSource`:
https://github.com/ScottPlot/ScottPlot/blob/7d54aac659fd3c61abec85c6cd79e9d3bb988a92/src/ScottPlot5/ScottPlot5/DataSources/DataStreamerSource.cs#L56C3-L68C6

**Comment by swharden** [comment]
I added a `ContinuouslyAutoscale` flag to support this behavior. It's a little disorienting for some datasets so it's an opt-in feature, but it should do well for the applications described here. This feature will be in the next release! 🚀 

![continuously-autoscale](https://github.com/ScottPlot/ScottPlot/assets/4165489/7e105965-ab5b-48db-a438-800e527bb079)

**Comment by swharden** [comment]
Confirmed it works well when multiple streamers are in use

![continuously-autoscale2](https://github.com/ScottPlot/ScottPlot/assets/4165489/3a0a39bf-edd9-4942-a375-13b3b6e397ee)
