### ISSUE TITLE
Cookbook: demonstrate multipeaked mountain

### ISSUE THREAD

**Issue by heartacker** [ScottPlot/ScottPlot#3563]
multipeaked mountain like this
**Suggestion:** (Describe your idea here)
![image](https://github.com/ScottPlot/ScottPlot/assets/1876302/d54e1560-55ba-4fb0-9e2a-bc3fbc124193)

**Comment by swharden** [comment]
Hi @heartacker, thanks for the suggestion! I'm adapting this issue to track adding an example like this to the cookbook. #3380 has to be completed first, then a chart like this will be possible 👍

**Comment by swharden** [comment]
```cs
double[] xs = ScottPlot.Generate.Consecutive(100);
ScottPlot.Colormaps.MellowRainbow cmap = new();

for (int i = 0; i < 10; i++)
{
    double yOffset = 9 - i * 0.5;
    double[] ys = Generate.Sigmoidal(xs.Length)
        .Select(y => y + yOffset)
        .ToArray();

    Generate.AddNoiseInPlace(ys, 0.1);

    var sig = myPlot.Add.ScatterLine(xs, ys);
    sig.LineColor = Colors.Black;
    sig.LineWidth = 1.5f;
    sig.FillY = true;
    sig.FillYValue = yOffset;
    sig.FillYAboveColor = cmap.GetColor(i, 10);
}

myPlot.HideGrid();
myPlot.Axes.MarginsX(0);
```

![image](https://github.com/user-attachments/assets/4b73712b-67f1-463e-8c96-c09883527005)
