### ISSUE TITLE
How do I change the styling of an AvaPlot in AvaloniaUI?

### ISSUE THREAD

**Issue by DoogeJ** [ScottPlot/ScottPlot#3564]
**Question:**
Hello, thank you so much for this awesome and promising looking library!

I have a silly question. I have a pretty black Avalonia form, but a very bright white chart. I would love to style this similar to my other controls, but I can't figure out how. Can you give me some hints?

**ScottPlot Version:**
ScottPlot.Avalonia 5.0.23

**Code Sample:**
Currently I just have the getting started stuff, so `<ScottPlot:AvaPlot Name="AvaPlot1"/>` in my window, and 

```
double[] dataX = { 1, 2, 3, 4, 5 };
double[] dataY = { 1, 4, 9, 16, 25 };

AvaPlot avaPlot1 = this.Find<AvaPlot>("AvaPlot1");
avaPlot1.Plot.Add.Scatter(dataX, dataY);
avaPlot1.Refresh();
```

in my initialization.

I might be overlooking things, but the Avalonia-specific documentation (https://scottplot.net/quickstart/avalonia/) seems very sparse, and none of the other documentation (like https://scottplot.net/cookbook/5.0/Styling/) seems to apply here.

**Comment by swharden** [comment]
Hi @DoogeJ, thanks for this question! The code here can help you customize the colors of your plot: https://scottplot.net/cookbook/5.0/Styling/

**Comment by DoogeJ** [comment]
> Hi @DoogeJ, thanks for this question! The code here can help you customize the colors of your plot: https://scottplot.net/cookbook/5.0/Styling/

Hi Scott,

Thanks for the fast answer - but if you read my question I already linked that page in there. Those styling options don't seem to be available for the AvaPlot.

**Comment by KroMignon** [comment]
> Thanks for the fast answer - but if you read my question I already linked that page in there. Those styling options don't seem to be available for the AvaPlot.

Hello @DoogeJ, first I have to say that I am not using Avalonia, my backend is WPF. But, as far as I can see, there are not that much different.

When talking about styling, there are 2 things you could possibly mean:
- styling on Avalonia (WPF) level: here it is the Control it self. Generally done on (A)XAML level
- styling on ScottPlot level: here it is the way the plot will be done. This can only be done on C# level. 

The Avalonia or WPF control will not expose any ScottPlot styling property on (A)XAML level.
You will have to do it on C# code level.
This has be done voluntary this way, to not made all controls as simple as possible.

**Comment by DoogeJ** [comment]
@KroMignon Thank you so much; I must have been sleepy at the time, but this helped a lot! 😅
