### ISSUE TITLE
WPF: How to set initial screen position?

### ISSUE THREAD

**Issue by loyvsc** [ScottPlot/ScottPlot#3565]
**Question:** How I can set initial screen position on the plot?

**ScottPlot Version:** WPF 5.0.21 (nuget)

**Comment by KroMignon** [comment]
>  How I can set initial screen position on the plot?

Maybe I am not really understand the question. Do you want to know how to set Window position on screen?

For WPF Window, you only have to set `WindowStartupLocation` property to wanted value:  [WPF documentation](https://learn.microsoft.com/en-us/dotnet/api/system.windows.window.windowstartuplocationl)

**Comment by loyvsc** [comment]
No, I want to change initial viewport position (for example, on the right side of the plot)

**Comment by swharden** [comment]
@loyvsc, I may not be understanding your question. ChatGPT says:

> WPF doesn't have a built-in general-purpose "viewport" control. However, the term is sometimes used loosely to refer to the visible area within a scrollable container like a ScrollViewer.

Perhaps your question is specific to Unity? If so, asking a question like this in a Unity forum may help you get a useful answer quickly. https://discord.com/invite/unity

**Comment by loyvsc** [comment]
By "viewport" I mean <WpfPlot/>. I want to change what the user sees after loading the component, so to speak, the initial position

**Comment by swharden** [comment]
If the quickstart is edited to contain the following code, does it solve your problem?

https://scottplot.net/quickstart/wpf/

```cs
double[] dataX = { 1, 2, 3, 4, 5 };
double[] dataY = { 1, 4, 9, 16, 25 };
WpfPlot1.Plot.Add.Scatter(dataX, dataY);
WpfPlot1.Plot.Axes.SetLimits(-10, 10, -30, 30); // this line changes what the user sees
WpfPlot1.Refresh();
```
