### ISSUE TITLE
NumericManual Returns empty ticks

### ISSUE THREAD

**Issue by keleutos2022** [ScottPlot/ScottPlot#3576]
**Issue:** (Describe the bug here) When I want to get the ticks I always get an empty array

**ScottPlot Version:** (What NuGet package are you using?) 5.0.23

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs


ScottPlot.Plot myPlot = new();


/* code to reproduce the bug */
myPlot.SavePng("bug.png");
        var ticksBottom = new NumericManual();
        for (int i = 0; i <= 10; i++)
        {
            ticksBottom.AddMajor(i,i.ToString());
        }
// Now the Tick Bottom Length is 0 
ticksBottom.Ticks.Length 




```

**Comment by swharden** [comment]
* https://scottplot.net/cookbook/5.0/CustomizingTicks/CustomTicks/
* https://scottplot.net/cookbook/5.0/CustomizingTicks/SetTicks/
