### ISSUE TITLE
Axis Spans: draw border even if line width is zero

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3579]
```cs
formsPlot1.Plot.Add.HorizontalSpan(0.25, 0.75, Colors.Black.WithAlpha(.1));
```
![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/51e31bf7-9615-45b8-bc6d-cfcf437762a5)

I think the error is in these two methods:
https://github.com/ScottPlot/ScottPlot/blob/5c02d82432cebe5018d22ebd8be41738e80f0ebc/src/ScottPlot5/ScottPlot5/Drawing.cs#L219-L228

They should return early if there is no line width or line color, like this:
https://github.com/ScottPlot/ScottPlot/blob/5c02d82432cebe5018d22ebd8be41738e80f0ebc/src/ScottPlot5/ScottPlot5/Drawing.cs#L232-L233

**Comment by aniketkumar7** [comment]
Is this works fine ?
public static void DrawRectangle(SKCanvas canvas, PixelRect rect, SKPaint paint, LineStyle lineStyle)
{
    if (paint.Color == SKColors.Transparent || lineStyle.LineWidth == 0)
        return;

    lineStyle.ApplyToPaint(paint);
    canvas.DrawRect(rect.ToSKRect(), paint);
}

public static void DrawRectangle(SKCanvas canvas, PixelRect rect, SKPaint paint)
{
    if (paint.Color == SKColors.Transparent || paint.StrokeWidth == 0)
        return;

    canvas.DrawRect(rect.ToSKRect(), paint);
}

we use SKColors.Transparent instead of Colors.Transparent because the SKPaint object uses SKColors for its Color property.

**Comment by aespitia** [comment]
> Is this works fine ?
> 
> ```
> public static void DrawRectangle(SKCanvas canvas, PixelRect rect, SKPaint paint, LineStyle lineStyle)
> {
>     if (paint.Color == SKColors.Transparent || lineStyle.LineWidth == 0)
>         return;
> 
>     lineStyle.ApplyToPaint(paint);
>     canvas.DrawRect(rect.ToSKRect(), paint);
> }
> ```
> 
> ```
> public static void DrawRectangle(SKCanvas canvas, PixelRect rect, SKPaint paint)
> {
>     if (paint.Color == SKColors.Transparent || paint.StrokeWidth == 0)
>         return;
> 
>     canvas.DrawRect(rect.ToSKRect(), paint);
> }
> ```
> 
> we use SKColors.Transparent instead of Colors.Transparent because the SKPaint object uses SKColors for its Color property.
> 
> Can I contribute to it?, I helps me a lot.

you should, it's been relatively easy contributing new updates.  here's a link to their notes on contributing.
https://scottplot.net/contributing/

**Comment by swharden** [comment]
Hi @aniketkumar7, thanks for looking into this! It's definitely a bug. In a pinch you can do this thought and it works:

```cs
var hs = formsPlot1.Plot.Add.HorizontalSpan(0.25, 0.75, Colors.Black.WithAlpha(.1));
hs.LineStyle.Width = 0;
hs.LineStyle.Color = Colors.Transparent;
```

However, correcting the bug can be achieved by changing this function:
https://github.com/ScottPlot/ScottPlot/blob/7d49a417b43b61827e3f660c2f77929e2d57be9b/src/ScottPlot5/ScottPlot5/Drawing.cs#L208-L212

... and it looks like you identified the fix! 🚀 If you contribute a pull request, I'd be happy to review it in good time and merge it in so it gets into the next release! 👍

**Comment by swharden** [comment]
> Can I contribute to it?, I helps me a lot.

I wish there were a good YouTube video "how to create a pull request with GitHub" that I could add to the top of the contributing page. @aniketkumar7 if you find such a resource, let me know and I can add it to help others!

**Comment by CoderPM2011** [comment]
> 我希望有一個很好的 YouTube 影片“如何使用 GitHub 建立拉取請求”，我可以將其添加到貢獻頁面的頂部。@aniketkumar7如果您找到這樣的資源，請告訴我，我可以添加它來幫助其他人！

Although there is no video, github has provided some instructions.
Maybe it's a good reference for beginners.

- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by swharden** [comment]
It appear this has since been resolved 👍
