### ISSUE TITLE
ScottPlot.WPF OpenTK dependency doesn't support .Net Framework 4.8

### ISSUE THREAD

**Issue by Trincity** [ScottPlot/ScottPlot#3580]
**Suggestion:** 
Update ScottPlot package dependencies to support .Net Framework 4.8

![image](https://github.com/ScottPlot/ScottPlot/assets/8442708/4bca8480-567b-4c47-ba99-916f5d7bbba9)

Current dependencies:
![image](https://github.com/ScottPlot/ScottPlot/assets/8442708/afd74e6f-4bae-446a-a264-edf99e15c3ab)

**Comment by swharden** [comment]
Hi @Trincity, thanks for reporting this! I created a sandbox app using WPF and .NET Framework 4.6.2 and found ScottPlot works as expected. ![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/33cf005a-ec38-4d8e-b156-400c72a0d043) 

I suspect that if you create a new app from scratch you will observe this too, suggesting that there may be an issue with your current project's build configuration.

Hope it helps! Projects with dependency-version-related build issues can be really tough to figure out sometimes. Good luck! 🚀

**Comment by Trincity** [comment]
@swharden Does it work on .Net Framework 4.8?

**Comment by swharden** [comment]
> @swharden Does it work on .Net Framework 4.8?

It is expected to work on .Net 4.6.2 and newer, but let me know if you discover otherwise!

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/6578f81a-a366-4ed2-af49-9823e7c025e5)

**Comment by Trincity** [comment]
I created a new WPF project and tried installing ScottPlot.WPF. I ran into this error message:
```
Installed OpenTK.Core 4.3.0 from https://api.nuget.org/v3/index.json with content hash Hu+4U+tvnQW++y8Gj4OggLVuhclLm1hVN9ZIc3e9d8uo15CWYOSycw+FQhaRH3aibFv1vFYgH+bMIHM509YwYg==.
  CACHE https://api.nuget.org/v3/vulnerabilities/index.json
  CACHE https://api.nuget.org/v3-vulnerabilities/2024.04.18.07.01.18/vulnerability.base.json
  CACHE https://api.nuget.org/v3-vulnerabilities/2024.04.18.07.01.18/2024.04.18.07.01.18/vulnerability.update.json
NU1100: Unable to resolve 'System.Drawing.Common (>= 4.7.3)' for 'net8.0-windows7.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, nuget.org.
Package restore failed. Rolling back package changes for 'WpfApp1'.
```

**Comment by swharden** [comment]
Thanks for reporting this @Trincity! How are you creating a new WPF project? 

The following works for me:
```
dotnet new wpf
dotnet add package scottplot.wpf
dotnet run
```

**Comment by swharden** [comment]
This works for me, does it work for you?
* open visual studio community (latest version)
* create new project
* WPF app (.net Framework)
* select 4.8
* right-click project, manage nuget packages, install ScottPlot.WPF, click accept
* use the code below

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/43a44a57-0f1a-46e1-9211-d6b1abc2e5fa)

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/f3d77b58-a375-4e50-a334-d441ed38f7f7)

```xml
<Window x:Class="WpfApp2.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp2" xmlns:wpf="clr-namespace:ScottPlot.WPF;assembly=ScottPlot.WPF"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <wpf:WpfPlot Name="WpfPlot1" />
</Window>
```

```cs
using System.Windows;

namespace WpfApp2
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            WpfPlot1.Plot.Add.Signal(ScottPlot.Generate.Sin());
            WpfPlot1.Plot.Add.Signal(ScottPlot.Generate.Cos());
        }
    }
}
```

**Comment by Trincity** [comment]
It appears that the difference I have is I'm using .Net 8.0. I thought I was using 4.8, but it doesn't appear so.

![image](https://github.com/ScottPlot/ScottPlot/assets/8442708/ea1397d8-5ba2-4218-b4e2-43ef81f789cc)
![image](https://github.com/ScottPlot/ScottPlot/assets/8442708/01718523-729a-490b-bc81-20a6181b3bd8)
![image](https://github.com/ScottPlot/ScottPlot/assets/8442708/84c5e8b3-4341-4332-8d1d-72224d2f778f)

**Comment by swharden** [comment]
> I'm using .Net 8.0

Nice! That makes life easier. The quickstart guide should work for you then 🚀 
https://scottplot.net/quickstart/wpf/

let me know it it doesn't go as expected!

**Comment by Trincity** [comment]
I can't seem to get the install to run though.
![image](https://github.com/ScottPlot/ScottPlot/assets/8442708/d4dc047e-65ca-47ce-a034-676c233f335a)

**Comment by swharden** [comment]
Hi @Trincity, this could be a visual studio bug.

Does it work if you create a new project and add ScottPlot from the console?
```cs
dotnet new wpf --name ScottPlotTest
dotnet add package scottplot.wpf
dotnet run
```

**Comment by Trincity** [comment]
`PS C:\Projects\ScotPlotPOC\ScottPlotTest> dotnet add package scottplot.wpf
  Determining projects to restore...
  Writing C:\Users\user\AppData\Local\Temp\tmpfzefdf.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
info : X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
info : Adding PackageReference for package 'scottplot.wpf' into project 'C:\Projects\ScotPlotPOC\ScottPlotTest\ScottPlotTest.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/index.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/index.json 556ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/page/1.0.0/4.1.17.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/page/1.0.0/4.1.17.json 121ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/page/4.1.18/5.0.7-beta.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/page/4.1.18/5.0.7-beta.json 272ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/page/5.0.8-beta/5.0.26.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/page/5.0.8-beta/5.0.26.json 116ms
info : Restoring packages for C:\Projects\ScotPlotPOC\ScottPlotTest\ScottPlotTest.csproj...
error: NU1100: Unable to resolve 'System.Drawing.Common (>= 4.7.3)' for 'net8.0-windows7.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, nuget.org.
info :   CACHE https://api.nuget.org/v3/vulnerabilities/index.json
info :   CACHE https://api.nuget.org/v3-vulnerabilities/2024.04.18.07.01.18/vulnerability.base.json
info :   CACHE https://api.nuget.org/v3-vulnerabilities/2024.04.18.07.01.18/2024.04.18.07.01.18/vulnerability.update.json
error: Package 'scottplot.wpf' is incompatible with 'all' frameworks in project 'C:\Projects\ScotPlotPOC\ScottPlotTest\ScottPlotTest.csproj'.`

**Comment by swharden** [comment]
Wow, ours are similar...

```ps
C:\Users\swharden\ScottPlotTest>dotnet add package scottplot.wpf
  Determining projects to restore...
  Writing C:\Users\swharden\AppData\Local\Temp\tmpfwl0ae.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
info : X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
info : Adding PackageReference for package 'scottplot.wpf' into project 'C:\Users\swharden\ScottPlotTest\ScottPlotTest.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/index.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/index.json 102ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/page/1.0.0/4.1.17.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/page/1.0.0/4.1.17.json 104ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/page/4.1.18/5.0.7-beta.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/page/4.1.18/5.0.7-beta.json 38ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/page/5.0.8-beta/5.0.26.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/scottplot.wpf/page/5.0.8-beta/5.0.26.json 100ms
info : Restoring packages for C:\Users\swharden\ScottPlotTest\ScottPlotTest.csproj...
info :   GET https://api.nuget.org/v3/vulnerabilities/index.json
info :   OK https://api.nuget.org/v3/vulnerabilities/index.json 62ms
info :   GET https://api.nuget.org/v3-vulnerabilities/2024.04.18.07.01.18/vulnerability.base.json
info :   GET https://api.nuget.org/v3-vulnerabilities/2024.04.18.07.01.18/2024.04.18.07.01.18/vulnerability.update.json
info :   OK https://api.nuget.org/v3-vulnerabilities/2024.04.18.07.01.18/vulnerability.base.json 15ms
info :   OK https://api.nuget.org/v3-vulnerabilities/2024.04.18.07.01.18/2024.04.18.07.01.18/vulnerability.update.json 31ms
info : Package 'scottplot.wpf' is compatible with all the specified frameworks in project 'C:\Users\swharden\ScottPlotTest\ScottPlotTest.csproj'.
info : PackageReference for package 'scottplot.wpf' version '5.0.26' added to file 'C:\Users\swharden\ScottPlotTest\ScottPlotTest.csproj'.
info : Writing assets file to disk. Path: C:\Users\swharden\ScottPlotTest\obj\project.assets.json
log  : Restored C:\Users\swharden\ScottPlotTest\ScottPlotTest.csproj (in 421 ms).
```

I think the line in your error message that is most relevant is:
```
error: NU1100: Unable to resolve 'System.Drawing.Common (>= 4.7.3)' for 'net8.0-windows7.0'. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, nuget.org.
```

Maybe your system is caching old packages? This command shows where:

```ps
dotnet nuget locals http-cache --list
```

This command should clear the cache:

```ps
dotnet nuget locals http-cache --clear
```

Maybe try clearing your cache and trying from the start again?

**Comment by swharden** [comment]
Also try

```ps
dotnet --list-sdks
```

and make sure you have a modern SDK on there (e.g., 8.0.x)

**Comment by Trincity** [comment]
> dotnet --list-sdks
8.0.101 [C:\Program Files\dotnet\sdk]

**Comment by swharden** [comment]
Perhaps another solution is https://www.arcticdba.se/posts/fighting-dotnet/

**Comment by swharden** [comment]
In VS pro:
Right click solution > manage nuget packages for solution > settings gear by package source > package source mapping > remove all
