### ISSUE TITLE
If a List<> (signal) contains no values or will be cleared, the graphic stuck on the zero cross point and the other signals are not be shown correctly!

### ISSUE THREAD

**Issue by MagicFawkes** [ScottPlot/ScottPlot#3584]
**Issue:** 
If a List<> (signal) contains no values or will be cleared, the graphic stuck on the zero cross point and the other signals are not be shown correctly
On Scottplot 4.1 it is working fine, if one of the ScottPlotList<> has no values, or will be cleared() in runtime, it is not stucking and the other signals will be shown correctly!

**ScottPlot Version:** 
ScottPlot.WPF 5.0.23

**Code Sample:** 

```cs
 ScottPlot.Plot myPlot = new();

 List<double> xs = new() {};
 List<double> ys = new() {};

 List<double> xs1 = new() { 6, 20, 30, 40, 50 };
 List<double> ys1 = new() { 1, 4, 9, 16, 25 };

 myPlot.Add.Scatter(xs, ys);
 myPlot.Add.Scatter(xs1, ys1);

 myPlot.SavePng("demo.png", 400, 300);
```

![demo](https://github.com/ScottPlot/ScottPlot/assets/107568517/288914ac-222a-4809-9ac7-8607dd420506)

**Comment by swharden** [comment]
Hi @MagicFawkes, I'm actually struggling to recreate this issue... I tried it in WinForms and also a console app.

```cs
ScottPlot.Plot myPlot = new();

List<double> xs = new() { };
List<double> ys = new() { };

List<double> xs1 = new() { 6, 20, 30, 40, 50 };
List<double> ys1 = new() { 1, 4, 9, 16, 25 };

myPlot.Add.Scatter(xs, ys);
myPlot.Add.Scatter(xs1, ys1);

var saved = myPlot.SavePng("demo.png", 400, 300);
saved.LaunchFile();
```

my output:
![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/91562916-30a2-4ae6-bfce-08b7160c9360)

Can you clarify what the issue is and/or how I can recreate it? Thanks!

**Comment by MagicFawkes** [comment]
Hi @swharden 
I have tried some things and have new information for you.

----------------------------------------------------------------------------
- If I install the SkiaSharp nuget package seperately over the nuget store, and set a reference to the compiled ScottPLot.dll file (Get from the Github Repository and compiled for .NET 8.0) then it is working --> see picture:

<img width="1187" alt="Working" src="https://github.com/ScottPlot/ScottPlot/assets/107568517/5959c793-665f-4529-ab2a-c3cd796034bf">

----------------------------------------------------------------------------
- If I install the ScottPlot  (5.0.23) nuget package directly from the store, which includes the SkiaSharp library (2.88.7), then it is not working --> see attached picture:

<img width="1247" alt="Not working" src="https://github.com/ScottPlot/ScottPlot/assets/107568517/242d7294-33c1-4c33-a22c-825dea9ce3fc">

----------------------------------------------------------------------------
It seems, there is a problem with the ScottPlot (5.0.23) nuget package setup

I hope this is helpful for you, please tell me, if you would need further information for analysis purposes.

Thank you.
