### ISSUE TITLE
WpfPlot: Need sample app to demonstrate display scaling

### ISSUE THREAD

**Issue by MagicFawkes** [ScottPlot/ScottPlot#3585]
**Issue:** 
Mouse position is shiftet if windows 11 screen scale is set to 125% (e.g. I use the application on a notebook), on 100% it is okay and works fine

**ScottPlot Version:** 
ScottPlot.WPF 5.0.23

**Code Sample:** 

```cs
    var position = System.Windows.Input.Mouse.GetPosition(WpfPlot1);
    var coordinates = WpfPlot1.Plot.GetCoordinates(new Pixel(position.X, position.Y));

    double x = coordinates.X;
    double y = coordinates.Y;
```

![AxisLineQuickstart](https://github.com/ScottPlot/ScottPlot/assets/107568517/0d44f29e-9ebf-4e58-bf19-a52bc7b071be)
![windows scale](https://github.com/ScottPlot/ScottPlot/assets/107568517/5392609a-db36-4aee-8c82-9dd1e5dbb9cd)

**Comment by swharden** [comment]
Hi @MagicFawkes, perhaps this will help! Adapted from #3550

```cs
double factor = PresentationSource.FromVisual(this).CompositionTarget.TransformToDevice.M11;
var position = System.Windows.Input.Mouse.GetPosition(WpfPlot1);
double x = position.X * factor;
double y = position.Y * factor;
var coordinates = WpfPlot1.Plot.GetCoordinates(x, y);
```

This seems to relate to #3465 which got closed by accident. A minimal WPF demo should be created to demonstrate WPF-specific functionality (like this)
