### ISSUE TITLE
FormsPlot: does not redraw after Dialog window opens second time

### ISSUE THREAD

**Issue by Kruno313** [ScottPlot/ScottPlot#3589]
I have a DialogWindow in WinForms (NET8) with FormsPlot on it. When I show the modal dialog first time, the plot draws itself.
But when I open the same dialog instance again, the dialog window shows but the FormsPlot does not draw it self on it.

This behaviour is reletad to V5.0.23.  Same code works with V4.1.73.
I have made a test solution (see attachment).
[ScottPlotTest.zip](https://github.com/ScottPlot/ScottPlot/files/14865031/ScottPlotTest.zip)

**Comment by bwedding** [comment]
I just submitted a PR for this if you want to look. Easy fix.

**Comment by Kruno313** [comment]
Is it meant to be in V5.0.24?
The 5.0.24 does not fix it (I updated the test sample and tried today).

**Comment by Kruno313** [comment]
Confirm this working with Version V5.0.26.
