### ISSUE TITLE
Axis Rules: limit rules do not function property on inverted axes

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3597]
@VisMotrix recently added support to the square axis rules in #3592, but the inner/outer boundary rules (demonstrated by the demo application) do not function as expected with inverted axes. I added "inverted axis" checkboxes to the demo app to demonstrate the isssue:

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/06e926e3-6264-4d9f-9c11-4899a9b49e18)

**Comment by CoderPM2011** [comment]
In `MaximumBoundary.cs`, when the axes are inverted, the condition seems to be invalid.

![image](https://github.com/ScottPlot/ScottPlot/assets/7456441/fcdb4ec4-7706-4933-8cbe-1107c7dce27f)

After further investigation, in `FractionalAutoScaler.cs`, when the axes are inverted, the maximum and minimum values are swapped.
This might be causing the issue.
