### ISSUE TITLE
Inconsistant type of Label properties (string, string?, Label, ...)

### ISSUE THREAD

**Issue by mikeKuester** [ScottPlot/ScottPlot#3599]
**Question:** What is your target for the Label property of the plottables? Even the three Signal.. types have a different implementation. That makes it hard to create an interface for that.

**ScottPlot Version:** 5.0.23

**Code Sample:** 

https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Plottables/Signal.cs
and
https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Plottables/SignalConst.cs
have a nullable string property
```cs
public string? Label { get; set; }
```

https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Plottables/SignalXY.cs
has a non-nullable string field
```cs
public string Label = string.Empty;
```

**Comment by swharden** [comment]
Following up, ScottPlot 5.0.27 (released a few weeks after this issue was opened) resolved this issue by using `string LegendText` as convention for plottables 👍
