### ISSUE TITLE
SignalXY: add support for markers

### ISSUE THREAD

**Issue by cris988** [ScottPlot/ScottPlot#3602]
**Question:** Why are marker missing in version 5 for SignalXY plot while in version 4 there is?

**ScottPlot Version:** 5.0.23

**Code Sample:** 

Version 4
```cs

var sig = plt.AddSignalXY(xs, ys);
sig.MarkerShape = MarkerShape.filledTriangleUp;
sig.MarkerSize = 10;

```

**Comment by swharden** [comment]
Thanks for pointing this out @cris988! Right now Signal plots support markers but SignalXY plots do not. Here's a WinForms app for testing:

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        double[] xs = Generate.Consecutive(100);
        double[] sin = Generate.Sin(100);
        double[] cos = Generate.Cos(100);

        var sig = formsPlot1.Plot.Add.Signal(sin);
        sig.Label = "Signal";
        sig.Marker.Shape = MarkerShape.FilledTriangleUp;
        sig.MaximumMarkerSize = 20;

        var sigxy = formsPlot1.Plot.Add.SignalXY(xs, cos);
        sigxy.Label = "SignalXY";

        /* Marker options are not yet supported ...*/
        //sig.Marker.Shape = MarkerShape.FilledTriangleUp;
        //sig.MaximumMarkerSize = 20;

        formsPlot1.Plot.ShowLegend();
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/e83a8ee7-0734-462b-9b88-5bc4e29dec17)

It should be pretty straightforward to copy/paste this functionality from the `Signal` class into the `SignalXY` class. If you or someone from the open source community want to give this a try and create a pull request, I'd be happy to review it in good time!

The key lines of code to reference from `Signal.cs` are:

https://github.com/ScottPlot/ScottPlot/blob/6c2419fa3794388cb004504903db9e82fa4ebc15/src/ScottPlot5/ScottPlot5/Plottables/Signal.cs#L16

https://github.com/ScottPlot/ScottPlot/blob/6c2419fa3794388cb004504903db9e82fa4ebc15/src/ScottPlot5/ScottPlot5/Plottables/Signal.cs#L24

https://github.com/ScottPlot/ScottPlot/blob/6c2419fa3794388cb004504903db9e82fa4ebc15/src/ScottPlot5/ScottPlot5/Plottables/Signal.cs#L122-L130

**Comment by swharden** [comment]
... although I'm now realizing that SignalXY plots don't have fixed horizontal point spacing so `pointsPerPx` isn't a thing. In this case, referencing how scatter plots do it is probably the best way. The solution may be a two-liner!

https://github.com/ScottPlot/ScottPlot/blob/6c2419fa3794388cb004504903db9e82fa4ebc15/src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs#L10

https://github.com/ScottPlot/ScottPlot/blob/6c2419fa3794388cb004504903db9e82fa4ebc15/src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs#L67
