### ISSUE TITLE
How to edit the Y Axis Precision

### ISSUE THREAD

**Issue by swaitvor** [ScottPlot/ScottPlot#3605]
I'm using scottplot5.0 in winforms

```cs
formplot2.Plot.Add.Scatter(xData, sensor1);
```

The input point is of the double type. However, the plot space is only displayed to integer bits. How can i set y axis to displayed to the thousandth?

**Comment by swaitvor** [comment]
This phenomenon occurs when the y-axis value of the added point is greater than 1000

**Comment by swharden** [comment]
Hi @swaitvor, you can use a custom tick formatter to control precision of tick labels

https://scottplot.net/cookbook/5.0/CustomizingTicks/CustomTickFormatter/

```cs
static string CustomFormatter(double position) => $"{position:N3}";
```

**Comment by swaitvor** [comment]
Thanks
