### ISSUE TITLE
ScatterSource: GetNearest() Crashes when MaxRenderIndex is set to certain values

### ISSUE THREAD

**Issue by Matthew-Chidlow** [ScottPlot/ScottPlot#3616]
**Issue:**
Calling GetNearest() on any of the ScatterSources types will always crash for any input data except if
you manually set MaxRenderIndex  to something at least 2 less than the number of actual points (this has other side effects so is only a temp work around which can be mitigated by adding dummy points).

I believe the issue is that the upper bounds on these for loops need to be exclusive not inclusive:
https://github.com/ScottPlot/ScottPlot/blob/43835fec0955b4a826dacdee9feb86a60d8ea346/src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceCoordinatesList.cs#L48
https://github.com/ScottPlot/ScottPlot/blob/43835fec0955b4a826dacdee9feb86a60d8ea346/src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceDoubleArray.cs#L47
https://github.com/ScottPlot/ScottPlot/blob/43835fec0955b4a826dacdee9feb86a60d8ea346/src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceGenericArray.cs#L56
https://github.com/ScottPlot/ScottPlot/blob/43835fec0955b4a826dacdee9feb86a60d8ea346/src/ScottPlot5/ScottPlot5/DataSources/ScatterSourceGenericList.cs#L56

**ScottPlot Version:** 5.0.24

**Code Sample:**

```cs
 new ScatterSourceDoubleArray(Array.Empty<double>(), Array.Empty<double>()).GetNearest(default, default);
```

**Comment by SongPing** [comment]
I found this great libary just for an hour.
And I also stumbled upon this bug
`for (int i = 0; i <= RenderIndexCount; i++) ...
`
it propertly should be:
`for (int i = 0; i < RenderIndexCount; i++) ...`

**Comment by SongPing** [comment]
That was fast !!!
Working in my case.
Thanks a lot!
