### ISSUE TITLE
Red and Blue color values being flipped with SkiaSharp on some systems

### ISSUE THREAD

**Issue by dutchie032** [ScottPlot/ScottPlot#3619]
**Issue:** argb mapping differences between Windows and Linux

**ScottPlot Version:**Scottplot.Blazor 5.0.23 (But most likely all)

**Code Sample:**

```cs
Color color = Color.FromHhex("<someHex>") //shows inverted red and blue color on some systems.
```

Possible Cause:
According to [this](https://learn.microsoft.com/en-us/dotnet/api/skiasharp.skimageinfo.platformcolortype?view=skiasharp-2.88) the order of colors changes. Can be checked with `SkiaImageInfo.PlatformColorType`

**Comment by dutchie032** [comment]
Not sure why, but cannot reproduce myself anymore after updates. 

Will close as "not reproduceable" for the time being.

**Comment by KroMignon** [comment]
Hello @dutchie032,

AFAIK, ScottPlot do **not** use hex notation to create `SKColor` instances but always pass each color and alpha channel.
Hex color codes are converted from custom `Color` and always in the same way, independently of used operating system.

I only use ScottPlot with Windows, can you show the result of this code with Linux and or IOs?
```chsarp

var plot = new ScottPlot.Plot();

var r1 = plot.Add.Rectangle(1, 3, 1, 3);
r1.FillStyle.Color = Colors.Blue;

var c1 = plot.Add.Circle(2, 2, 1);
c1.FillColor= Colors.Red;

var r2 = plot.Add.Rectangle(1.5, 2.5, 1.5, 2.5);
r2.FillStyle.Color = Colors.Green;

plot.SavePng("ColorTest.png", 320, 180);
```

My result is
![ColorTest](https://github.com/ScottPlot/ScottPlot/assets/3978902/d875a8be-c061-4ad4-8c7e-c927b992fe0f)
