### ISSUE TITLE
Axis Line Labels are being cropped on opposite axis

### ISSUE THREAD

**Issue by MCF** [ScottPlot/ScottPlot#3628]
This is visible in the output from the [AxisLine Label cookbook recipe](https://scottplot.net/cookbook/5.0/AxisLines/AxisLineLabel/).  

Current output from 5.0.25 is shown here:

![AxisLineLabel](https://github.com/ScottPlot/ScottPlot/assets/223530/60ddcfa9-e9ea-4bd0-a5b6-6bc73e5cce90)

**Comment by MCF** [comment]
Looks like this is either a change in behaviour or a regression between 5.0.23 and 5.0.25.

This is what the same plot looked like in 5.0.23:

![AxisLineLabel](https://github.com/ScottPlot/ScottPlot/assets/223530/c64f1261-19f7-4980-b06e-880a72a8a225)

**Comment by swharden** [comment]
Hi @MCF, this is actually the intended behavior. There was a long-running bug where axes that had no ticks or tick labels took up more space than needed, leaving large undesired amounts of padding on the top and right of graphs. Interestingly, this "bug" helped ensure there was always space for axis line labels on those edges of the graph. 

The solution is to adjust the layout to add padding on those edges using either `myPlot.Layout.Fixed()` or `myPlot.Axes.Right.MinimumSize`


I'll update the cookbook recipes to demonstrate this 👍
