### ISSUE TITLE
SP5 AvaPlot: Rendering artifacts on plot edges when rotated

### ISSUE THREAD

**Issue by PremekTill** [ScottPlot/ScottPlot#3633]
**Issue:** When placing an AvaPlot in a rotated panel, for certain AvaPlot sizes, there appears a border along what would be the left and upper edges of the AvaPlot canvas if it was not rotated. This border is not drawn fully, with some parts of the line being lighter or intermittent - it looks like some kind of rendering artifact (this is especially obvious in darker color schemes). This is even more problematic when changing the size of the plot (e.g. binding to the size of a window), since the artifacts only appear for certain sizes, causing a very noticeable flicker when dragging.

Upon further examination, this artifact is correlated with whatever is placed behind the window itself - when placed over a blue wallpaper, the line is blue, when placed over a combination of black and white backrgounds, the line is correspondingly black and white. Might be some kind of rounding error in the layout, which leads to an "empty gap" in the canvas, allowing whatever is behind to leak through? See the last two examples below.

**ScottPlot Version:** Tested for Scottplot Version 5.0.25, Avalonia Versions 11.0.4 and 11.1.0-beta1, OS Windows 10

**Code Sample:** Create a new project using one of the Avalonia templates, then place this as the content of the UserControl in MainView.axaml:

```xaml
  <Panel RenderTransform="rotate(90deg)" Name="ParentPanel" Margin="20">

    <avalonia:AvaPlot Width="{Binding #ParentPanel.Bounds.Height}" Height="{Binding #ParentPanel.Bounds.Width}" />

  </Panel>
```

For better visibility, set ```Background="AliceBlue"``` (or any other color) on the MainView UserControl. In the initial examples, I also set AxisLimits to (5, 10), but this does not affect the issue, neither does the screen coordinate aspect ratio of the AvaPlot.

**Examples:**

<img src="https://github.com/ScottPlot/ScottPlot/assets/94750559/a1635549-e2e6-4afe-876a-553d4f40416b" height="321">

Light mode (unwanted border on the top and right sides of the plot)

<img src="https://github.com/ScottPlot/ScottPlot/assets/94750559/5ad5bdf3-1f7b-4088-9336-e45acc387a4c" height="600">

Dark mode (fringing along the top and right edges of the plot)

![scottplot_fringing](https://github.com/ScottPlot/ScottPlot/assets/94750559/5d2fab87-cd0e-42f1-bbf7-14ea43801be0)

Flickering when dragging

<img src="https://github.com/ScottPlot/ScottPlot/assets/94750559/1a94a0ad-b2f5-41f0-8b8c-d39fb09e39a8" height="335">
<img src="https://github.com/ScottPlot/ScottPlot/assets/94750559/9e20b7fc-0e56-424d-9be6-d7ef7938c6c9" height="335">

Background leaking through

**Comment by chjrom** [comment]
Try add this code after `InitializeComponent` method:
```csharp
AvaPlot.Plot.RenderManager.RenderActions.RemoveAt(1);
```

**Comment by PremekTill** [comment]
Nice, this does seem to fix the issue, both in the trivial repro and in a real world app. Any idea what the root cause might be and how to fix it within SP itself? Looking at the RenderAction at index 1 (ClearCanvas), maybe some rounding error between the size of the canvas and the figure background (FigureRect) drawn in the next step?

**Comment by swharden** [comment]
> AvaPlot.Plot.RenderManager.RenderActions.RemoveAt(1);

It looks like it removes the `ClearCanvas()` action:

https://github.com/ScottPlot/ScottPlot/blob/2487c64b1761583d758be84b0d2d3c0011b97163/src/ScottPlot5/ScottPlot5/Rendering/RenderManager.cs#L13-L38

The same effect could probably be achieved by setting:

```cs
AvaPlot1.Plot.RenderManager.ClearCanvasBeforeEachRender = false;
```

**Comment by swharden** [comment]
... maybe we should enable this by default in the Avalonia control? We could add that line in the initialization sequence 🤔
