### ISSUE TITLE
Legend: improve support for labels with line breaks

### ISSUE THREAD

**Issue by aespitia** [ScottPlot/ScottPlot#3649]
Issue: If you make a chart with a line break in the label, the legend renders it as an unknown character

ScottPlot Version:  5.0.25

```cs
ScottPlot.Plot myPlot = new();

List<PieSlice> slices = new()
{
	new PieSlice() { Value = 5, FillColor = Colors.Red, Label = "Red has long\ntitle here" },
	new PieSlice() { Value = 2, FillColor = Colors.Orange, Label = "Orange" },
	new PieSlice() { Value = 8, FillColor = Colors.Gold, Label = "Yellow" },
	new PieSlice() { Value = 4, FillColor = Colors.Green, Label = "Green" },
	new PieSlice() { Value = 8, FillColor = Colors.Blue, Label = "Blue" },
};

var pie = myPlot.Add.Pie(slices);
pie.ExplodeFraction = .1;

myPlot.ShowLegend();

myPlot.SavePng("demo.png", 400, 300);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/105309364/db294ed3-79fe-4329-845f-3dd3d8e58a1a)

**Comment by swharden** [comment]
I looked into it, and oof, the legend items are manually rendered text and don't leverage the `Label` class with all its new string measurement features and multiline support. I'll start working on this now and wow, it'll be a big PR! 😅

**Comment by swharden** [comment]
Interestingly, I found a flag which indicates this may have been hacked-in before. 

I'm not going to even test if it works since it's getting refactored away, but it's there 🤷 

```cs
formsPlot1.Plot.Legend.AllowMultiline = true;
```

**Comment by aespitia** [comment]
I gave it a shot, it doesn't work.

**Comment by swharden** [comment]
Merging #3689 now 🚀 It's one of the biggest PRs I've worked on in a while 😅
