### ISSUE TITLE
SampleData: Dunning-Kruger effect

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3657]
I made the curve from the [Dunning-Kruger effect](https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect) trope/meme.

I spent way too much time on this, but got it pretty good, so I'm adding the formulas here for future reference. We can include this curve in some of the cookbook recipes.

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/f15d7486-e462-4413-a353-c8db12485087)

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/f02c6980-75a7-4713-9ee0-d21e7383581a)

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/fb4ad7dd-ce78-4ecb-b156-62d0018af6bd)

```cs
const double k1 = 152; // confidence velocity in stupidity
const double k2 = 0.22; // time of peak stupid
const double k3 = 4.2; // confidence velocity in enlightenment
const double k4 = 0.6; // delay until enlightenment starts
const double k5 = 0.6; // time enlightenment starts
const double k6 = 5; // rate of enlightenment

static double f1(double x) => Math.Exp(-k1 * Math.Pow(x - k2, 2));
static double f2(double x) => 1.0 / (1 + Math.Exp(-k3 * (x - k4)));
static double fr(double x) => 1.0 / (1 + Math.Exp(-k6 * (x - k5)));
static double dk(double x) => (1 - fr(x)) * f1(x) + fr(x) * f2(x);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/6239f71d-7662-4643-bb68-5d7224653ea2)

**Comment by swharden** [comment]
```cs
const double k1 = 152; // confidence velocity in stupidity
const double k2 = 0.22; // time of peak stupid
const double k3 = 4.2; // confidence velocity in enlightenment
const double k4 = 0.6; // delay until enlightenment starts
const double k5 = 0.6; // time enlightenment starts
const double k6 = 5; // rate of enlightenment

static double f1(double x) => Math.Exp(-k1 * Math.Pow(x - k2, 2));
static double f2(double x) => 1.0 / (1 + Math.Exp(-k3 * (x - k4)));
static double fr(double x) => 1.0 / (1 + Math.Exp(-k6 * (x - k5)));
static double dk(double x) => (1 - fr(x)) * f1(x) + fr(x) * f2(x);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/6239f71d-7662-4643-bb68-5d7224653ea2)

**Comment by erikjl** [comment]
This is amazing.  Also known ad the Gartner "hype cycle." Just missing the text labels like "trough of disillusionment"

**Comment by swharden** [comment]
> Just missing the text labels like "trough of disillusionment"

Those got added to the "draggable callout" demo! It came out great #3650

![callout](https://github.com/ScottPlot/ScottPlot/assets/4165489/6e1dcd39-8ee1-4d81-9312-3cde9ba90b68)
