### ISSUE TITLE
Blazor Cookbook: Add features and publish it to the website

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3664]
- [x] Give each recipe a distinct URL so it can be linked to directly
- [x] Improve the layout to support mobile views
- [x] Clicking a recipe fails for the first one you click
- [x] Menu horizontal slider needs to be hidden
- [x] The plot size is weird and doesn't adjust well to all screen sizes
- [x] Allow more pages than just cookbook recipes to be displayed in the menu
- [x] Recipe JSON is loaded after every click, but it should be loaded once when the app starts and passed around
- [x] A built-in search box would be great too
- [ ] Support multi touch on mobile
- [ ] More informative quickstart page
- [ ] Disable right-click context menu that launches when zooming
- [ ] Make the hamburger float instead of taking up a column
- [ ] Add icons to change the plot size
- [ ] Add icon to loading screen
- [ ] Add OpenGraph meta tags

**Comment by swharden** [comment]
### New live demo: https://swharden.com/tmp/sp/blazor/

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/00014c88-e370-41ec-a309-b6dad3a87b79)

**Comment by KroMignon** [comment]
Hello @swharden, looks nice 👍 

I see some annoying bugs:
- on mobile version, the dropdown menu is always open
- on mobile version, when selecting an item in dropdown menu, the menu is not hidden
- links for "performance tests" and "quick start" are absolute and not relative (which not work when app has not an absolute URL)
- there seems to be a mistake between 2 functions for the navigation bar:
    - on small displays (eg mobile devices): the menu is a top bar which can be dropdown with the burger icon (`collapseNavMenu`)
    - on large displays: the menu is a sidebar (on the left) which can be collapsed to save space on screen (`IconMenuActive`)
    - those functions seem to be merged is a not very good way

I will try to create a PR

**Comment by heartacker** [comment]
Would it be possible to add a web-based sandbox/playground environment, similar to a Notebook? This would allow users to directly execute some demos in the website

**Comment by swharden** [comment]
> Would it be possible to add a web-based sandbox/playground environment, similar to a Notebook? This would allow users to directly execute some demos in the website

I love this idea, but I suspect this is not possible because it would require a C# _compiler_ to also be available in the browser and I'm not sure if that's currently possible.

**Comment by heartacker** [comment]
https://github.com/ashmind/SharpLab

**Comment by swharden** [comment]
> https://github.com/ashmind/SharpLab

Thanks for sharing this project! It's awesome, but it doesn't run client-side in the browser right? It requires a server for the compilation?

**Comment by swharden** [comment]
Note to self: PR #3710 made improvements to the Blazor demo but wasn't merged yet. Take a closer look at that PR when this issue is picked up again.

**Comment by wanaylor** [comment]
Maybe this is not the right issue but I was looking through the examples in the cookbook and couldn't find an example of dynamically adding plots with, say, an add button. I thought if I had a list of plots I could just loop through them but this does not seem to work. Below is a toy page of what I am trying to do with a list of plots but get the following error `error CS1656: Cannot assign to 'plot' because it is a 'foreach iteration variable'`. What is the correct way to do this?

```
@page "/plots"

@using ScottPlot
@using ScottPlot.Blazor

<h1>ScottPlot 5 in Blazor</h1>
<div style="overflow-y:scroll; border-style: solid;">
    @foreach(BlazorPlot plot in plots)
    {
        <BlazorPlot @ref=plot Style="=width: 400px; height: 300px;" />
    }
    <BlazorPlot @ref=BlazorPlot Style="width: 400px; height: 300px;" />
</div>

@code {
    List<BlazorPlot> plots {get; set; }= new();
    BlazorPlot BlazorPlot { get; set; } = new();
    protected override void OnInitialized()
    {
        try
        {
            for (int i=0; i<3; i++)
            {
                Console.WriteLine("Adding plot to list...");
                var newPlot = new BlazorPlot();
                plots.Add(newPlot);
            }
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }
    }
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            try
            {
                foreach(BlazorPlot plot in plots)
                {
                    plot.Plot.Add.Signal(Generate.Sin());
                    plot.Plot.Add.Signal(Generate.Cos());
                }
                BlazorPlot.Plot.Add.Signal(Generate.Sin());
                BlazorPlot.Plot.Add.Signal(Generate.Cos());
           
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }
    }
}
```

**Comment by KroMignon** [comment]
@wanaylor in fact this has nothing to do with `ScottPlot`, this is a `Blazor` [child components rendering issue](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0#child-content-render-fragments).

The easiest way to solve it, is to use a local variable:
```csharp
    @for (var idx = 0; idx < plots.Count(); ++idx)
    {
        var idxRef = idx;
        <BlazorPlot @ref="plots[idxRef]" Style="width: 400px; height: 300px;" />
    }
```

**Comment by LeaFrock** [comment]
I'm in a difficult situation using ScottPlot in Blazor WASM right now 🤣 

I can provide some problems which I suggest Cookbook including.

1. C/J/K font detect will fail and break the character display.
2. No easy way to show data point label in Scatter-liked plots.
3. No events(such as `OnMouseMove`) similar to ones on other platforms(Winform/WPF), so I don't find the way to implement crosshair/text displaying with a picked point by mouse.

**Comment by swharden** [comment]
There isn't active momentum on this so I'll close this issue, but I'm _really_ interested in bringing the quality of the Blazor cookbook (and even a live Blazor quickstart!) high enough that we feel good about showcasing it on https://scottplot.net/quickstart/blazor/
