### ISSUE TITLE
SignalXY: GetColumnPixelsX floating point math error

### ISSUE THREAD

**Issue by mjazd** [ScottPlot/ScottPlot#3665]
**Issue:** This is a continuation of #3423 as #3495 didn't solve the issue I've initially reported. Some lines are not being renderend depending on the size of the image. Attached is one example, the issue also occurs at different image sizes and for different lines.

**ScottPlot Version:** ScottPlot v5.0.26

**Code Sample:**

```cs
var plot = new Plot();

plot.Axes.Left.MaximumSize = 40.5f;
plot.Axes.Left.MinimumSize = 40.5f;
plot.Axes.Right.MaximumSize = 19.5f;
plot.Axes.Right.MinimumSize = 19.5f;

plot.Add.SignalXY(
    new double[] { 1284, 1485 },
    new double[] { -2.373134328358208, -2.373134328358208 }
);

plot.Axes.SetLimits(0, 3801.1111111111113, -7.092537313432836, -0.7999999999999993);

plot.SavePng("682.png", 682, 186); // line not rendered
plot.SavePng("683.png", 683, 186); // line rendered correctly
```
682.png
![682](https://github.com/ScottPlot/ScottPlot/assets/161584436/c652a3b3-ec7f-480b-9cfe-c1d8bd18079b)

683.png
![683](https://github.com/ScottPlot/ScottPlot/assets/161584436/2da05b6d-9b1a-42b3-a6f4-886415286c19)

**Comment by swharden** [comment]
Thanks for reporting this! Interestingly, removing these lines fixes the issue...

```cs
//plot.Axes.Right.MaximumSize = 19.5f;
//plot.Axes.Right.MinimumSize = 19.5f;
```

```cs
using ScottPlot;

var plot = new Plot();

plot.Axes.Left.MaximumSize = 40.5f;
plot.Axes.Left.MinimumSize = 40.5f;
//plot.Axes.Right.MaximumSize = 19.5f;
//plot.Axes.Right.MinimumSize = 19.5f;

plot.Add.SignalXY(
    new double[] { 1284, 1485 },
    new double[] { -2.373134328358208, -2.373134328358208 }
);

plot.Axes.SetLimits(0, 3801.1111111111113, -7.092537313432836, -0.7999999999999993);
System.Diagnostics.Debug.WriteLine(plot.Axes.GetLimits());

plot.Title("682 bad");
plot.SavePng("682.png", 682, 186).LaunchFile();

plot.Title("683 okay");
plot.SavePng("683.png", 683, 186).LaunchFile();
```

**Comment by swharden** [comment]
This is so odd!
![sigxy](https://github.com/ScottPlot/ScottPlot/assets/4165489/448f7bf3-0186-4a4d-946e-23ad32efae7a)

``cs
using ScottPlot;
using ScottPlot.Plottables;
using ScottPlot.WinForms;

var plot = new Plot();

plot.Axes.Left.MaximumSize = 40.5f;
plot.Axes.Left.MinimumSize = 40.5f;
plot.Axes.Right.MaximumSize = 19.5f;
plot.Axes.Right.MinimumSize = 19.5f;

double[] xs = { 1284, 1485 };
double[] ys = [-2.373134328358208, -2.373134328358208];

var sig = plot.Add.SignalXY(xs, ys);
sig.LineWidth = 10;

plot.Axes.SetLimits(0, 3801.1111111111113, -7.092537313432836, -0.7999999999999993);

plot.SavePng("683.png", 683, 186).LaunchFile(); // line rendered correctly
plot.SavePng("682.png", 682, 186).LaunchFile(); // line not rendered
plot.SavePng("683.png", 683, 186).LaunchFile(); // line rendered correctly

FormsPlot formsPlot = new() { Dock = DockStyle.Fill };
formsPlot.Reset(plot);

Form form = new()
{
    StartPosition = FormStartPosition.CenterScreen,
    Width = 682,
    Height = 186,
};

form.SizeChanged += (s, e) =>
{
    plot.Axes.SetLimits(0, 3801.1111111111113, -7.092537313432836, -0.7999999999999993);
    form.Text = $"{formsPlot.Size}";
};

form.Controls.Add(formsPlot);

form.ShowDialog();
```

**Comment by swharden** [comment]
I think what is happening is floating a point math error going between pixel column (float) and coordinate (double) to determine "what data points are at this X pixel position" here

https://github.com/ScottPlot/ScottPlot/blob/0d2fcdb230a5f7f0f89beaeaf68005e74a0285d0/src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs#L153-L161

The result is certain rare combinations of image widths (float) and horizontal axis ranges (double) result in dropping data points. The example below shows the center point being dropped.

okay | bad
---|---
![683](https://github.com/ScottPlot/ScottPlot/assets/4165489/04d02781-fd56-4b4f-8e61-3b82073e82a4)|![682](https://github.com/ScottPlot/ScottPlot/assets/4165489/463d4245-a79e-46f3-a810-4b729b8c2943)


```cs
using ScottPlot;

var plot = new Plot();

plot.Axes.Left.MaximumSize = 40.5f;
plot.Axes.Left.MinimumSize = 40.5f;
plot.Axes.Right.MaximumSize = 19.5f;
plot.Axes.Right.MinimumSize = 19.5f;

double[] xs = [500, 1485, 2500];
double[] ys = [5, -5, 5];

var sig = plot.Add.SignalXY(xs, ys);
sig.LineWidth = 10;

plot.Axes.SetLimitsX(0, 3801.1111111111113);

plot.SavePng("683.png", 683, 186).LaunchFile(); // line rendered correctly
plot.SavePng("682.png", 682, 186).LaunchFile(); // line not rendered
```

**Comment by swharden** [comment]
Fixed! https://github.com/ScottPlot/ScottPlot/commit/06c877c26500ac5fc3717e8a7a1258949de681f5 Wow that was a confusing one to track down. Thanks so much for reporting this @mjazd! Your awesome code example that helped reproduce the bug made all the difference. The fix will be in the next release! 🚀
