### ISSUE TITLE
SP5 Datastreamer: Can the vertical gap in the sweep plot be customized / made wider?

### ISSUE THREAD

**Issue by mloppnow** [ScottPlot/ScottPlot#3668]
**Question:** I'm working on graphing a project with the DataStreamer plot type, using WipeRight. The 'sweep' bar that indicates the current position is quite thin - is there currently a way to make it wider, or is there a plan to?

**ScottPlot Version:** 5.0.23

**Comment by swharden** [comment]
Hi @mloppnow, I believe this is possible. I'll update the DataStreamer demo application to demonstrate this. See 38c80e4

![wipe](https://github.com/ScottPlot/ScottPlot/assets/4165489/c21a7162-7628-40f0-bc67-6747f79c030c)

**Comment by swharden** [comment]
Actually, I understand your suggestion better... _vertical gap_ (not vertical bar). I'll take a closer look now!

**Comment by mloppnow** [comment]
Thanks! Just to confirm - yes, changing the gap between old/new data is what I was wondering about.

**Comment by swharden** [comment]
Feature added! 🚀 I'll merge in a couple minutes. `Streamer.ViewWipeRight(0.1)` now has an optional argument that lets you indicate the fraction of old data to be blanked.

![gap](https://github.com/ScottPlot/ScottPlot/assets/4165489/a78c7780-b842-49e5-860c-ec6b5ec70478)
