### ISSUE TITLE
Is it possible to create a step area chart

### ISSUE THREAD

**Issue by timhatton** [ScottPlot/ScottPlot#3670]
**Question:** 
First of all, thank you for an excellent project. 

I am looking to create a stepped area chart. Something like the [one in Google charts](https://developers.google.com/chart/interactive/docs/gallery/steppedareachart).

![image](https://github.com/user-attachments/assets/b1611d31-8fe4-4c6c-9d86-2d698ea67989)

The use case is to display energy consumption per hour over the course of a day, week, month etc, and a stepped area chart feels the most natural way to represent this.

I can not see a way to do this in v5. In v4 it was possible to do a Signal Plot and set StepDisplay to true and use FillBelow.
In v5 I have looked at the following options, but neither quite allow what I'm looking for:

- adding a scatter plot with the values, another with zeroes, and then adding a FillY.  This give an "area chart" but, there is no way to set StepDisplay on the FillY. 
- adding a single scatter with the ConnectStyle = ConnectStyle.StepHorizontal gives the correct shape but there is no way to fill under the line. 

Would it be possible to have a FillBelow method similar to what was available in v4?

**ScottPlot Version:** (What NuGet package are you using?)

v5.0.26

**Comment by swharden** [comment]
This is a bit manual, but it's possible.

If someone wants to make this easier by creating a `StepArea` plot type, I'd be happy to review a pull request and merge it in quickly! https://scottplot.net/faq/custom-plot-type/ It could largely be a copy/paste job given the code below.

```cs
// prepare values for each line
double[] values1 = [8.4, 6.9, 6.5, 4.4];
double[] values2 = [7.9, 6.6, 6.4, 6.2];
double[] values3 = [6.2, 7.3, 5.5, 3.7];

// create a collection holding values for each line
double[][] allValues = [values1, values2, values3];

// calculate step points for each like by storing each point twice
double[] runningSum = new double[values1.Length];
for (int i = 0; i < allValues.Length; i++)
{
    // add values on top of the running sum to achieve stacking effect
    runningSum = DataOperations.SumVertically([runningSum, allValues[i]]);

    List<Coordinates> points = [];
    for (int j = 0; j < runningSum.Length; j++)
    {
        points.Add(new(j, runningSum[j]));
        points.Add(new(j + 1, runningSum[j]));
    }

    // plot the points as it is to show a line
    Coordinates[] lineCoordinates = [.. points];

    // add the start and end points
    points.Add(new(points.Last().X, 0));
    points.Add(new(points.First().X, 0));
    Coordinates[] fillCoordinates = [.. points];

    // add the polygon then top it with a line
    var line = myPlot.Add.ScatterLine(lineCoordinates);
    line.Color = ScottPlot.Palette.Default.GetColor(i);
    line.LineWidth = 2;

    var poly = myPlot.Add.Polygon(fillCoordinates);
    poly.FillColor = line.Color.Lighten(.5);
    poly.LineWidth = 0;
}

// reverse the order of everything so the smallest polygons
// (the first that were added) to be displayed on top and rendered last
myPlot.PlottableList.Reverse();

// use tight margins to prevent padding between the data and edge of the plot
myPlot.Axes.Margins(0, 0, 0, 0.1);

// add group labels
double[] positions = [0.5, 1.5, 2.5, 3.5];
string[] labels = { "Alfred", "Ralph", "Don", "James" };
myPlot.Axes.Bottom.SetTicks(positions, labels);
```

![image](https://github.com/user-attachments/assets/44021c9b-f46d-4977-acec-c1a925c0b055)
