### ISSUE TITLE
Legend: Create an `IPanel` for displaying legend outside the plot area

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3672]
Add a demo that shows how to use `Plot.GetLegendImage()` then `GetBitmapBytes()` to create a `Bitmap` and display it outside the plot area.

Discussed by @Graat and @mikeKuester in #3635

**Comment by mikeKuester** [comment]
@swharden, just to avoid a misunderstanding: When you write "outside the plot area", that's still part of the plot control though, right? Like the title? 
![image](https://github.com/ScottPlot/ScottPlot/assets/93646587/c4fee3bf-0caa-452d-98ce-e5c7b10b2753)

**Comment by swharden** [comment]
Thanks for the clarification @mikeKuester! I'll adapt this issue to track progress toward adding a "legend panel" that allows a legend to be displayed inside the control, but outside the data area.

For now, below is the recommended way to achieve this goal, and I'll add this demo to the demo app:

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/45882b79-b0c5-46e7-b860-3b503497f663)

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/9c58db0b-5137-4469-8089-cf2b71d0e61e)


```cs
using ScottPlot;
using ScottPlot.Extensions;

namespace WinForms_Demo.Demos;

public partial class LegendOutsideBitmap : Form, IDemoWindow
{
    public string Title => "Legend Outside the Plot (Bitmap)";

    public string Description => "Demonstrates how to display the " +
        "legend outside the plot by obtaining it as a Bitmap and " +
        "displaying it outside the plot control anywhere in your window.";

    public LegendOutsideBitmap()
    {
        InitializeComponent();

        int count = 20;
        for (int i = 0; i < 20; i++)
        {
            double[] ys = Generate.Sin(100, phase: i / (2.0 * count));
            var sig = formsPlot1.Plot.Add.Signal(ys);
            sig.Color = Colors.Category20[i];
            sig.LineWidth = 2;
            sig.Label = $"Line #{i + 1}";
        }

        formsPlot1.Plot.Legend.OutlineStyle.Width = 0;
        formsPlot1.Plot.Legend.BackgroundFill.Color = SystemColors.Control.ToColor();
        ScottPlot.Image legendImage = formsPlot1.Plot.GetLegendImage();
        byte[] legendBitmapBytes = legendImage.GetImageBytes(ImageFormat.Bmp);
        MemoryStream ms = new(legendBitmapBytes);
        Bitmap bmp = new(ms);
        pictureBox1.Image = bmp;
        pictureBox1.SizeMode = PictureBoxSizeMode.CenterImage;
        pictureBox1.BackColor = SystemColors.Control;
    }
}
```

**Comment by JakkuSakura** [comment]
```csharp
            ScottPlot.Panels.LegendPanel pan = new(AvaPlot.Plot.Legend)
            {
                Edge = Edge.Right,
                Alignment = Alignment.UpperCenter,
            };
            
            AvaPlot.Plot.Axes.AddPanel(pan);
```
will stuck my program.
`AvaPlot.Plot.ShowLegend(Edge.Right);`
will also stuck my program
