### ISSUE TITLE
SP5: Implement Population Plot from SP4

### ISSUE THREAD

**Issue by erikjl** [ScottPlot/ScottPlot#3676]
I found population plots to be a very a useful data validation visual to convince stubborn users of models bucketed/histogram-driven data characterization models. Specifically, I used 'uniform population series' overlaid on top of the model which was displayed as bar graph. It was very effective!

 https://scottplot.net/cookbook/4.0/#plottypes-populations---uniform-population-series

**Comment by FaisalMangattil** [comment]
This would be a great addition to the Scott-plot 5.
