### ISSUE TITLE
SkiaSharp: How to render text for right-to-left alphabets?

### ISSUE THREAD

**Issue by esmatullah-adel** [ScottPlot/ScottPlot#3677]
**Issue:** Persian text in Ticks is shown in reverse.

```cs
Tick[] ticks = new Tick[2];
ticks[0] = new Tick(type, "سیب");
ticks[1] = new Tick(type, "انگور");
```

**Comment by swharden** [comment]
Thanks for reporting this @esmatullah-adel! 

Clarifying the issue, we expect labels to look like this:
![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/943693f4-8846-42ca-8fa7-0b882025468c)

But the characters appear in reverse:
![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/1a14f30d-9383-40a6-b7dc-a3cd01aaa3ff)

```cs
using ScottPlot;

Plot plt = new();
plt.Add.Signal(Generate.Sin());
plt.Add.Signal(Generate.Cos());

ScottPlot.TickGenerators.NumericManual tickGen = new();
tickGen.AddMajor(20, "سیب");
tickGen.AddMajor(30, "انگور");

plt.Axes.Bottom.TickGenerator = tickGen;
plt.Axes.Bottom.TickLabelStyle.FontSize = 26;
plt.Axes.Bottom.TickLabelStyle.FontName = Fonts.Detect("انگور");
plt.Axes.Bottom.MinimumSize = 100;

plt.SavePng("test.png", 600, 300).LaunchFile();
```

**Comment by swharden** [comment]
Following-up, it looks like right-to-left font support is not currently available in SkiaSharp (the rendering system ScottPlot uses)

* https://github.com/mono/SkiaSharp/issues/272

The recommendation there is to use third party libraries for rendering text https://github.com/mono/SkiaSharp/issues/272#issuecomment-664669586

* https://github.com/toptensoftware/RichTextKit
* https://github.com/wouterst79/SkiaSharp.TextBlocks

Those packages look great, but are not officially supported by Microsoft, so in accordance with our [security goals](https://github.com/ScottPlot/ScottPlot/blob/main/SECURITY.md) we don't include packages like that with ScottPlot.

An intermediate option could be to use a third party package to render advanced text as an image, then add support for custom images for axis labels, tick labels, etc.

I'll close this now to help focus on other open high priority issues, but if you get as far as using one of these other libraries to render text as bitmaps let me know and I can open this issue up again and add support for bitmap labels on tick marks 👍 

Thanks again for reporting this issue!
