### ISSUE TITLE
Candlestick: draw horizontal line if open equals close

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3678]
antilles79 from the Discord (#1966) noted that candlestick plots have two issues:

- [ ] candles at X=0 have unexpected width
- [ ] candles where open equals close do not display a horizontal line

```cs
List<OHLC> price = new List<OHLC>();

price.Add(new OHLC(100, 103, 99, 102, new DateTime(1899, 12, 30), TimeSpan.FromDays(1)));
price.Add(new OHLC(100, 103, 99, 102, new DateTime(1899, 12, 31), TimeSpan.FromDays(1)));
price.Add(new OHLC(101, 103, 99, 101, new DateTime(1900, 1, 1), TimeSpan.FromDays(1)));
price.Add(new OHLC(100, 103, 99, 102, new DateTime(1900, 1, 2), TimeSpan.FromDays(1)));
price.Add(new OHLC(100, 103, 99, 102, new DateTime(1900, 1, 3), TimeSpan.FromDays(1)));

formsPlot1.Plot.Add.Candlestick(price);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/0891734d-f568-47e5-aec1-5f15b34777ea)

These issues can probably be resolved by editing this section of code:

https://github.com/ScottPlot/ScottPlot/blob/2a575c80b6a7a31d00ff57d8de956e288abc22dc/src/ScottPlot5/ScottPlot5/Plottables/CandlestickPlot.cs#L63-L109

**Comment by Lyakabynka** [comment]
I have also faces this issue and I will higly appreciate it if it will be considered soon.

Moreover, when close=high=low=open, they become invisible.

**Comment by swharden** [comment]
Fixed! This will be in the next release.

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/40dc9856-5070-4ba0-b610-8aefaac2941e)

**Comment by Lyakabynka** [comment]
Hello, Scott!

Thank you for solving this issue!
I wanted to ask: What if open=close=high=low? Do they become invisible as previously?

Thanks!
