### ISSUE TITLE
FormsPlot is not available on toolbox

### ISSUE THREAD

**Issue by bulent017** [ScottPlot/ScottPlot#3679]
My environment is window 11 64 bit, Visual studio 2022 (community), ScottPlot version 5.0.26. The "OpenTK" and "SkiaSharp.Views" apeared in the toolbox but "ScottPlot.WinForms" does not.
I also try old version of Visudl studio (e.g. vs2017, vs2019), however, the same problem occured. And I also install old version of ScottPlot, the "ScottPlot.WinForms" apeared in some cases, But if you add a FormsPlot to Winform app, it say "The FormsPlot can't be added in the toolbox", that's very weird
When I try to add ScottPlot.Winforms.dll to the toolbox manually, it doesn't work either.
![image](https://github.com/ScottPlot/ScottPlot/assets/96498139/ca232907-b839-420a-a4ab-d0edc40de10d)

**Comment by swharden** [comment]
> My environment is window 11 64 bit, Visual studio 2022 (community), ScottPlot version 5.0.26. The "OpenTK" and "SkiaSharp.Views" apeared in the toolbox but "ScottPlot.WinForms" does not.

Oof, I hate when that happens! That literally happened to me today and I never know why. Restarting Visual Studio usually fixes it so I assume it's a bug on their end 🤷 

The WinForms designer can be flaky. To get around it, you can add a control programmatically: 

* https://scottplot.net/faq/add-winforms-programmatically/#scottplot-5
* https://scottplot.net/faq/add-winforms-programmatically/#add-a-scottplot-inside-a-panel

**Comment by bulent017** [comment]
> > My environment is window 11 64 bit, Visual studio 2022 (community), ScottPlot version 5.0.26. The "OpenTK" and "SkiaSharp.Views" apeared in the toolbox but "ScottPlot.WinForms" does not.
> 
> Oof, I hate when that happens! That literally happened to me today and I never know why. Restarting Visual Studio usually fixes it so I assume it's a bug on their end 🤷
> 
> The WinForms designer can be flaky. To get around it, you can add a control programmatically:
> 
> * https://scottplot.net/faq/add-winforms-programmatically/#scottplot-5
> * https://scottplot.net/faq/add-winforms-programmatically/#add-a-scottplot-inside-a-panel

First of all, thank you for your interest. But I can't do it this way because I can't add the formsPlot component to the form. I can use the libraries I added, but the formsPlot component is not loaded. I tried a different version. It appears in the toolbox in 5.0.20, but this time the component is not added.

**Comment by cataclism** [comment]
Hey @swharden I tried what you said.

If I open the project is shown correctly, however when I try to copy it to my project the copy doesn't happen.

**Comment by cataclism** [comment]
Hey @swharden, The error is caused by the version of .NETFramework.

Below .NETFramework 4.8 it won't show up and we need to add it programmatically. (like in .NETFramework 4.6.2 as I use)

If I use .NETFramework 4.8 it shows up.

**Comment by swharden** [comment]
Thanks @cataclism for following-up with your solution! It sounds like this may be a Visual Studio bug where it doesn't properly display items in the toolbox for older versions of .NET Framework. Hopefully a future update will fix this, but for now it sounds like adding the control programmatically is the way to go 👍
