### ISSUE TITLE
How to Plot Real-Time Data Performatively

### ISSUE THREAD

**Issue by bulent017** [ScottPlot/ScottPlot#3681]
https://scottplot.net/faq/live-data/

There is an explanation in this link, but I couldn't understand it fully. Is Signal Plot the best performer in live streaming data?

**Comment by swharden** [comment]
Hi @bulent017, check out the demo app https://scottplot.net/demo/

It comes with source code, and there are a few demos specifically about how to display real time streaming data 👍
