### ISSUE TITLE
Unclear "obsolete" description in Crosshair.cs - use LineColor instead of Color

### ISSUE THREAD

**Issue by mikeKuester** [ScottPlot/ScottPlot#3683]
https://github.com/ScottPlot/ScottPlot/blob/5ed3178403e56283dfd583b05890893d1d9ab2f0/src/ScottPlot5/ScottPlot5/Plottables/Crosshair.cs#L22

It should be "Assign values to **Line**Color" instead of "Assign values to Color". There is no Color property in CrossHair.  

```csharp
public Color LineColor { set { HorizontalLine.LineColor = value; VerticalLine.LineColor = value; } }
```

I just updated the NuGet packages to 5.0.26 and tried to change it from `myCrosshair.LineStyle.Color` to `myCrosshair.Color` which doesn't work. ;)

**Comment by swharden** [comment]
Oof, yeah, some of these definitely should be updated... thanks for pointing this out!

https://github.com/ScottPlot/ScottPlot/blob/5ed3178403e56283dfd583b05890893d1d9ab2f0/src/ScottPlot5/ScottPlot5/Plottables/Crosshair.cs#L22-L26

**Comment by swharden** [comment]
In a pinch, this should work

```cs
myCrosshair.HorizontalLine.LineColor = Colors.Blue;
myCrosshair.VerticalLine.LineColor = Colors.Blue;
```

**Comment by mikeKuester** [comment]
No problem, that works also: 
```csharp
myCrosshair.LineColor = Colors.Blue;
```

But not the mentioned 
```csharp
myCrosshair.Color = Colors.Blue;
```

**Comment by KroMignon** [comment]
> But not the mentioned
> 
> ```cs
> myCrosshair.Color = Colors.Blue;
> ```

Because this is a typo in the `Obsolete` comment, it should be `LineColor` and not `Color` 😉 
`Color` would be too ambiguous:
- text forecolor?
- text backcolor?
- line color?
- ...
