### ISSUE TITLE
DataStreamer - plotting with dotted/dashed lines

### ISSUE THREAD

**Issue by mloppnow** [ScottPlot/ScottPlot#3685]
**Question:** When using the DataStreamer plot type (ViewWipeRight) with a dotted/dashed line, the dots/dashes of the old data move around as the new data is plotted. Presumably this is because the old data is being re-plotted, so the positions of the dots/dashes change. The effect is quite jarring. Is there a way to fix that, and/or is it just an artifact of how lines are rendered?

**ScottPlot Version:** 5.0.23

**Comment by swharden** [comment]
I suspect this has been fixed. The demo on https://scottplot.net/demo/5.0/#plot-streaming-data looks all right. If there's still an issue we can open this up again 👍
