### ISSUE TITLE
ScottPlot 5: port dragable axis lines from ScottPlot 4.1

### ISSUE THREAD

**Issue by EFeru** [ScottPlot/ScottPlot#3691]
First, congradulations with the release of ScottPlot 5! That is an impressive piece of work.

**Suggestion:**
Is it planned to port the functionality of draggable axis line from ScottPlot 4.1?
https://scottplot.net/cookbook/4.1/category/plottable-axis-line-and-span/#draggable-axis-lines

I think is a nice addition to have, however I am not sure how high in prority is compared to other topics.

**Comment by mikeKuester** [comment]
@EFeru Did you check the ScottPlot5 demo? https://scottplot.net/demo/#draggable-axis-lines

**Comment by EFeru** [comment]
Oh, sorry, I only looked in the cookbook. That is awesome, thanks for the remark I will close the topic.
