### ISSUE TITLE
Get the Y values of a Signal XY when dragging a vertical line across

### ISSUE THREAD

**Issue by zx000097** [ScottPlot/ScottPlot#3696]
**Question:** 
So, I have a Signal XY, and an additional Vertical Line that is draggable. My data points are big in numbers so I can't use the scatter plot. 
Now I am using the Mouse Move event to print something when I drag the line, following the example in the demo here. https://github.com/ScottPlot/ScottPlot/blob/d612ce2a6ff4ad68a90baa539ae47301f4a3edd4/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/DraggableAxisLines.cs 

Is it possible to also print the current Y value of the signalXY when I drag the vertical line? The X-coordinate should be known, which is the X value of the vertical line that I am dragging. I have looked through the documentation but have no luck. Cheers.

**ScottPlot Version:** 5.0.26

**Code Sample:** This is what I have, the val is obviously wrong. 

```cs
if (_plottableBeingDragged is VerticalLine vl)
{
    vl.X = rect.HorizontalCenter;
    DateTime dt = DateTime.FromOADate(vl.X);
    var points = Plot.GetPlottables<SignalXY>().First();
    var val = points.Axes.GetPixelY(vl.X);
    val = (float)points.Axes.GetCoordinateY(val);

    string label = $"Y:{val}";
    vl.Text = label;
}

Refresh();

```

![image](https://github.com/ScottPlot/ScottPlot/assets/63998848/b5e17941-1c25-4958-90c3-b1d759b86fec)

**Comment by shijianoo** [comment]
Do you know what to do right now? I also have the same needs as you, according to the X value to determine the Y value

**Comment by swharden** [comment]
The demo apps contain code that demonstrate this feature

![image](https://github.com/user-attachments/assets/a09972f7-6c62-4a2e-9f57-5a8aa0f605f6)

![image](https://github.com/user-attachments/assets/93b4b5d6-cc46-4720-8a3b-d8afd1bbffc6)

https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/ShowValueUnderMouseSignalXY.cs
