### ISSUE TITLE
Function Plot perforamance regression

### ISSUE THREAD

**Issue by Matthew-Chidlow** [ScottPlot/ScottPlot#3703]
**Issue:** A side effect of recently fixing issues with function is a performance regression.

This for loop:
https://github.com/ScottPlot/ScottPlot/blob/0263ad10a361672fd1867815c88f7d1e549260e4/src/ScottPlot5/ScottPlot5/Plottables/FunctionPlot.cs#L69
Used to just loop over the range of values visible within the bounds of the plot.

But after this commit: https://github.com/ScottPlot/ScottPlot/commit/af6e7c9b2d0349d1b51eecc831cfdf62e2d3dee2
Changed `MinX` and `MaxX`, the loop now iterators over the whole functions range.

Also since zooming in decreases the step size the loop runs more and more every time you zoom.

So if you have a lot of function plots, even with them all being off screen the more you zoom in the lower the fps.

Also, while fixing that might also want to fix the issue that the upper bound of that for loop isn't reached exactly, meaning that the function isn't always evaluated at MaxX, and if you have multiple functions which are supposed to be joined seamlessly this can create gaps when zoomed out which disappear as you zoom in.

**ScottPlot Version:** 5.0.26

**Comment by swharden** [comment]
Thanks for the tip @Matthew-Chidlow! I think this has been fixed in https://github.com/ScottPlot/ScottPlot/commit/b2d794de64069949f24c353a4bf569b2011d7dcf but if I'm overlooking something let me know and we can take a closer look.

>  if you have multiple functions which are supposed to be joined seamlessly this can create gaps when zoomed out which disappear as you zoom in

I think is fixed now too

```cs
namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        var func1 = new Func<double, double>((x) => Math.Sin(x));
        var func2 = new Func<double, double>((x) => Math.Sin(x));

        var fp1 = formsPlot1.Plot.Add.Function(func1);
        var fp2 = formsPlot1.Plot.Add.Function(func2);

        fp1.MaxX = 1;
        fp2.MinX = 1;
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/c52c83d9-d45f-4439-9ddc-616673d16a29)
