### ISSUE TITLE
SetAxisLimits 怎么使x轴固定12等份, 且最小值和最大值固定在x轴的两端

### ISSUE THREAD

**Issue by fff21** [ScottPlot/ScottPlot#3704]
**Question:** SetAxisLimits 怎么使x轴固定12等份, 且最小值和最大值固定在x轴的两端

**Translated:** How to fix the x-axis into 12 equal parts, and fix the minimum and maximum values ​​at both ends of the x-axis

**ScottPlot Version:** 4.1.70

![Snipaste_2024-04-22_17-10-26](https://github.com/ScottPlot/ScottPlot/assets/130143783/a3956320-482d-45e6-9798-48fc814f6c13)

```cs
ScottPlot.Plot myPlot = new();
/* a code sample may improve communication */


            numericDates = new double[dates.Length];

            // 获取图表中第一个数据点和最后一个数据点的时间戳
            DateTime firstTimestamp = dates[0];
            DateTime lastTimestamp = dates[dates.Length - 1];

            // 计算时间差并转换为小时数
            double totalHours = Math.Ceiling((lastTimestamp - firstTimestamp).TotalHours);

            for (int i = 0; i < dates.Length; i++)
            {
                numericDates[i] = dates[i].ToOADate();
            }

            plt.XAxis.DateTimeFormat(true);
            plt.SetAxisLimits(numericDates.Min(), numericDates.Max(), price1.Min(), 0);

 
![Snipaste_2024-04-22_17-10-26](https://github.com/ScottPlot/ScottPlot/assets/130143783/e858937e-f805-47bb-b6c5-fb3a6b013ddc)

myPlot.SavePng("bug.png");
```

**Comment by fff21** [comment]
![Snipaste_2024-04-22_17-10-26](https://github.com/ScottPlot/ScottPlot/assets/130143783/a3956320-482d-45e6-9798-48fc814f6c13)

**Comment by swharden** [comment]
Hi @fff21, you can decide where you want the 12 ticks and define them like this https://scottplot.net/cookbook/4.1/recipes/ticks_defined/

Good luck!
