### ISSUE TITLE
Vertical grid lines not correct drawn, when x axis is at the top

### ISSUE THREAD

**Issue by MichaelKuelshammer** [ScottPlot/ScottPlot#3714]
there is a gap between vertical grid lines and tickmarks,
after zooming in and out.

![VerticalGridLinesProblem](https://github.com/ScottPlot/ScottPlot/assets/29129371/2744c36b-6b28-4f00-8a57-3ebc37281f5b)

**Comment by MichaelKuelshammer** [comment]
I use ScottPlot 5 in WPF.

**Comment by MichaelKuelshammer** [comment]
<Window x:Class="WPFGraphs.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WPFGraphs"
        xmlns:ScottPlot="clr-namespace:ScottPlot.WPF;assembly=ScottPlot.WPF"
        mc:Ignorable="d"
        Title="Test window" Height="450" Width="800">
    <Grid x:Name="myGrid">
        <Grid.RowDefinitions>
            <RowDefinition></RowDefinition>
        </Grid.RowDefinitions>
    </Grid>
</Window>

**Comment by MichaelKuelshammer** [comment]
I attached parts of my source code
[MultipleAxisGrids.zip](https://github.com/ScottPlot/ScottPlot/files/15094847/MultipleAxisGrids.zip)

**Comment by swharden** [comment]
Thanks for reporting this @MichaelKuelshammer! Definitely a bug where the grid lines are drawn assuming the standard axis... Here's a simpler way to reproduce this issue.

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        var sig = formsPlot1.Plot.Add.Signal(Generate.Sin());
        sig.Axes.XAxis = formsPlot1.Plot.Axes.Top;
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/12f839c9-6c0c-4537-8991-0aa783f9fa44)

**Comment by swharden** [comment]
Actually @MichaelKuelshammer, mimicing the code below may solve your issue. If not, let's open this back up and we can take a closer look! 🚀 

```
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        var sig = formsPlot1.Plot.Add.Signal(Generate.Sin());
        sig.Axes.XAxis = formsPlot1.Plot.Axes.Top;

        // keep the default grid but change the axis it uses
        formsPlot1.Plot.Axes.DefaultGrid.XAxis = formsPlot1.Plot.Axes.Top;
    }
}
```

**Comment by MichaelKuelshammer** [comment]
Yes, it's working perfectly.

Thx for the fast answer.
