### ISSUE TITLE
Demo: show how to use a custom font

### ISSUE THREAD

**Issue by kebox7** [ScottPlot/ScottPlot#3722]
How can I use my own fonts in ScottPlot, which are located in application resources? For example, there is the [PDFsharp ](https://github.com/empira/PDFsharp) library. It has a font substitution mechanism that allows you to get a font in any available way. It looks something like this (very simplified):
```cs
using Avalonia.Platform;
using PdfSharp.Fonts;

namespace TestApp.Main;

internal sealed partial class PdfDocument {
    private sealed class CustomFontResolver : IFontResolver {
        public byte[]? GetFont(string faceName) {
            using (var memory = new MemoryStream()) {
                using (var asset = AssetLoader.Open(new Uri(faceName))) {
                    asset.CopyTo(memory);
                    memory.Position = 0;
                    return memory.ToArray();
                }
            }
        }

        public FontResolverInfo? ResolveTypeface(string familyName, bool isBold, bool isItalic) =>
            new($"avares://TestApp.Fonts/Assets/NotoSans-{(isBold ? "Bold" : "Regular")}.ttf");
    }
}
```
Is there something similar for ScottPlot?

**ScottPlot Version:** 5.0.25

**Comment by kebox7** [comment]
The issue was resolved, although not in the best way (using reflection).
```cs
public static class PlotHelper {
    private static readonly FieldInfo? LabelCachedTypeface = typeof(Label).GetField("CachedTypeface", BindingFlags.NonPublic | BindingFlags.Instance);
    private static readonly SKTypeface? CachedTypeface = CreateTypeface();

    public static void SetPlotTypeface(AvaPlot control) {
        if (LabelCachedTypeface is null || CachedTypeface is null) {
            return;
        }

        foreach (var axis in control.Plot.Axes.GetAxes()) {
            LabelCachedTypeface.SetValue(axis.TickLabelStyle, CachedTypeface);
        }
    }

    private static SKTypeface CreateTypeface() {
        using (var asset = AssetLoader.Open(new Uri("avares://TestApp.Fonts/Assets/NotoSans-Regular.ttf"))) {
            return SKTypeface.FromStream(asset);
        }
    }
}
```
This is working at the moment, but things may change in the future if the font caching implementation is revised  (See [1](https://github.com/ScottPlot/ScottPlot/blob/95f72aff5c7bbf7d42bb880c9d46e1a315c75e9a/src/ScottPlot5/ScottPlot5/Primitives/FontStyle.cs#L16-L17), [2](https://github.com/ScottPlot/ScottPlot/blob/95f72aff5c7bbf7d42bb880c9d46e1a315c75e9a/src/ScottPlot5/ScottPlot5/Primitives/Label.cs#L35-L38)). For a normal solution, it is necessary to review the implementation of some classes, at least:

- [Fonts](https://github.com/ScottPlot/ScottPlot/tree/main/src/ScottPlot5/ScottPlot5/Fonts.cs)
- [FontStyle](https://github.com/ScottPlot/ScottPlot/tree/main/src/ScottPlot5/ScottPlot5/Primitives/FontStyle.cs )
- [Label](https://github.com/ScottPlot/ScottPlot/tree/main/src/ScottPlot5/ScottPlot5/Primitives/Label.cs)
- [FontStyler](https://github.com/ScottPlot/ScottPlot/tree/main/src/ScottPlot5/ScottPlot5/Stylers/FontStyler.cs)

**Comment by swharden** [comment]
@kebox7 thanks for following-up with the solution! I'm going to re-open this issue and use it to track adding a custom font example to the demo app to make this more discoverable in the future 👍

**Comment by kebox7** [comment]
> EDIT: I can also try to rework the files you listed to add true custom font support instead of relying on reflection

@swharden It would be great! Cross-platform development often requires embedding fonts (so that they look the same everywhere), rather than using system fonts. The ability to get fonts in various ways (directly from a file, from resources, etc.) is an excellent extension of functionality.

**Comment by nicki419** [comment]
@kebox7 Could you share how you implemented the solution you provided? I have been trying for a while now, however, I was unable to implement your solution. :/ 
For Context, I'm just using a simple plot in an Avalonia UserControl

**Comment by kebox7** [comment]
Hi, @nicki419. I didn't need labels for the axes, so the font is not specified for them. But this can be easily modified, just change the method `SetPlotTypeface`:

```cs
public static void SetPlotTypeface(AvaPlot control) {
    if (LabelCachedTypeface is null || CachedTypeface is null) {
        return;
    }

    foreach (var axis in control.Plot.Axes.GetAxes()) {
        LabelCachedTypeface.SetValue(axis.LabelStyle, CachedTypeface); // <-- Added
        LabelCachedTypeface.SetValue(axis.TickLabelStyle, CachedTypeface);
     }
}
```

**Comment by swharden** [comment]
Thanks @kebox7 for your useful code samples here! I'm now adding a `FontFile` property to live alongside `FontName`, and if it's null (default) it's ignored but if it's populated, the specified font will be used. 

I also am adding a `SetTypeface()` method which can be useful for assets which may not be stored as files on disk, but note that it's cleared whenever other font properties are changed.

I see there's a TODO here to wrap all the font caching in its own class, and perhaps when that happens the API will be a bit more elegant, but for now it seems to be working and I'm creating a demo app too 👍 

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/081ae1bf-e256-43be-a5b4-c0634c45d460)

```cs
string fontPath = "Fonts/ShadowsIntoLight/ShadowsIntoLight-Regular.ttf";

formsPlot1.Plot.Title("Plot Using Custom Fonts");
formsPlot1.Plot.Axes.Title.Label.FontFile = fontPath;
formsPlot1.Plot.Axes.Title.Label.FontSize = 36;

formsPlot1.Plot.XLabel("Horizontal Axis");
formsPlot1.Plot.Axes.Bottom.Label.FontFile = fontPath;
formsPlot1.Plot.Axes.Bottom.Label.FontSize = 24;
formsPlot1.Plot.Axes.Bottom.TickLabelStyle.FontFile = fontPath;
formsPlot1.Plot.Axes.Bottom.TickLabelStyle.FontSize = 18;

formsPlot1.Plot.YLabel("Vertical Axis");
formsPlot1.Plot.Axes.Left.Label.FontFile = fontPath;
formsPlot1.Plot.Axes.Left.Label.FontSize = 24;
formsPlot1.Plot.Axes.Left.TickLabelStyle.FontFile = fontPath;
formsPlot1.Plot.Axes.Left.TickLabelStyle.FontSize = 18;
```

**Comment by jpgarza93** [comment]
Can we use `avares://` paths?

**Comment by jpgarza93** [comment]
Is there an example on how to load a font using `avares://` ?

**Comment by swharden** [comment]
> Is there an example of how to load a font using `avares://`?

Does this get the job done? https://github.com/ScottPlot/ScottPlot/issues/3722#issuecomment-2076781698
