### ISSUE TITLE
FillStyle: disable border by default

### ISSUE THREAD

**Issue by Fruchtzwerg94** [ScottPlot/ScottPlot#3723]
After the change 695cb78 fills are constanty showing a black border around them. Even if the LineStyle is changed, nothing changes.
It seems like the LineStyle should be forwareded to Fills internal Polygon instead of tjust keeping it and not using it.
What do you think? Currently I see no way to change the border around the fill since the [corresponding polygon is private](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Plottables/FillY.cs#L13).

![grafik](https://github.com/ScottPlot/ScottPlot/assets/29866610/888bfe53-094a-4601-8367-811e5e60397c)

**Comment by swharden** [comment]
Thanks for reporting this! It seems related to #3720 and will be fixed shortly 👍

**Comment by swharden** [comment]
resolved in #3726

**Comment by Fruchtzwerg94** [comment]
Thank you @swharden , love to see that. Works like a charm.
