### ISSUE TITLE
Curve Fitting: add basic functionality

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3724]
Advanced curve fitting procedures are probably best performed by a dedicated math library and may be out of scope of this plotting library. However, it may be convenient to have some basic curve fitting functionality, at least mimicking what Excel provides:

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/3379a42f-e87b-4bb7-b2ff-e7df75f455e3)

We already have linear curve fitting functionality, and simple moving average calculation functionality is already present to support financial charting, so rounding out the set may be worth pursuing. Curve fitters that output the values of each parameter but can also output a `Func<>` would be nice to have.

**Comment by drolevar** [comment]
@swharden Can you think of a scenario when it won't be appropriate to use Math.NET?

**Comment by swharden** [comment]
> @swharden Can you think of a scenario when it won't be appropriate to use Math.NET?

Good point! I was using Accord.net for some signal analysis needs a while back and recalled it didn't have a permissive license. 

I'm reminded that Math.NET is MIT licensed which is great, so maybe just adding a cookbook recipe showing how to use it for curve fitting plots would be a good start!

**Comment by CoderPM2011** [comment]
This is an example I wrote based on Cookbook.
https://scottplot.net/cookbook/5.0/Regression/

### sample image
![demo](https://github.com/user-attachments/assets/d2ed2258-3dd8-4506-b176-5e4f1466ba59)

### sample code
``` cs
ScottPlot.Plot myPlot = new();

double[] xs = new double[] { 1, 2, 3, 4, 5, 6, 7 };
double[] ys = new double[] { 2, 2, 3, 3, 3.8, 4.2, 4 };

// plot original data as a scatter plot
var sp = myPlot.Add.Scatter(xs, ys);
sp.LineWidth = 0;
sp.MarkerSize = 10;

// calculate the regression line
(double intercept, double slope) = MathNet.Numerics.Fit.Line(xs, ys);

double f(double x)
{
    return slope * x + intercept; // slope-intercept form
}

// plot the regression line
Coordinates pt1 = new(xs.First(), f(xs.First()));
Coordinates pt2 = new(xs.Last(), f(xs.Last()));
var line = myPlot.Add.Line(pt1, pt2);
line.MarkerSize = 0;
line.LineWidth = 2;
line.LinePattern = LinePattern.Dashed;

// note the formula at the top of the plot
double r2 = MathNet.Numerics.GoodnessOfFit.RSquared(ys, xs.Select(x => f(x)));
string formulaWithRSquared = $"y = {slope:F3}x + {intercept:F3} (r²={r2:F3})";
myPlot.Title(formulaWithRSquared);

myPlot.SavePng("demo.png", 400, 300);
```

**Comment by CoderPM2011** [comment]
and an example of a four-order polynomial.

### sample image
![demo](https://github.com/user-attachments/assets/0c421239-6a96-47f9-893f-27a40d88802d)

### sample code
``` cs
ScottPlot.Plot myPlot = new();

double[] xs = new double[] { 1, 2, 3, 4, 5, 6, 7 };
double[] ys = new double[] { 2, 2, 3, 3, 3.8, 4.2, 4 };

// plot original data as a scatter plot
var sp = myPlot.Add.Scatter(xs, ys);
sp.LineWidth = 0;
sp.MarkerSize = 10;

double[] coefficients = MathNet.Numerics.Fit.Polynomial(xs, ys, 4);

// calculate the regression line
(double intercept, double slope) = MathNet.Numerics.Fit.Line(xs, ys);

double f(double x)
{
    return MathNet.Numerics.Polynomial.Evaluate(x, coefficients);
}

double[] fx = xs.Select(x => f(x)).ToArray();

// plot the regression line
var line = myPlot.Add.ScatterLine(xs, fx);
line.MarkerSize = 0;
line.LineWidth = 2;
line.LinePattern = LinePattern.Dashed;

// note the formula at the top of the plot
var superscript = new string[] { "⁰", "¹", "²", "³", "⁴" };
var formulaWithRSquared = new StringBuilder("y = ");
for (int i = coefficients.Length - 1; i >= 0; i--)
{
    if (i < coefficients.Length - 1)
    {
        if (coefficients[i] < 0)
            formulaWithRSquared.Append(" - ");
        else
            formulaWithRSquared.Append(" + ");
    }
    else if (coefficients[i] < 0)
    {
        formulaWithRSquared.Append('-');
    }

    if (i > 0)
        formulaWithRSquared.Append($"{Math.Abs(coefficients[i]):F4}x{superscript[i]}");
    else
        formulaWithRSquared.Append($"{Math.Abs(coefficients[i]):F4}");
}

double r2 = MathNet.Numerics.GoodnessOfFit.RSquared(ys, fx);
formulaWithRSquared.Append($" (r²={r2:F4})");

myPlot.Title(formulaWithRSquared.ToString());

myPlot.SavePng("demo.png", 600, 400);
```

**Comment by swharden** [comment]
* https://scottplot.net/faq/curve-fitting/
* https://swharden.com/blog/2024-08-24-exponential-fit-csharp/
* https://swharden.com/blog/2024-09-14-swarmfit/
