### ISSUE TITLE
FillY plots from datastreamers?

### ISSUE THREAD

**Issue by efeozbek** [ScottPlot/ScottPlot#3735]
Is there a way to cretae FillY plot from two datastreamers in ScottPlot 5.0?

**Comment by swharden** [comment]
I don't think there's anything built in that does that, but you could create your own `DoubleStreamerFill` plot type by copy/pasting the code for `DataStreamer`, modifying it to support two datasets, then grab the code from FillY to fill between two lines. 

This can be done in your project (does not require editing ScottPlot source code), but if you create such a plot type and find it useful you are welcome to share it here and it may be included in a future release so others can use it too! 👍 🚀 

https://scottplot.net/faq/custom-plot-type/
