### ISSUE TITLE
Scatter: issue related to length of connecting lines

### ISSUE THREAD

**Issue by Alfred-GitHub1** [ScottPlot/ScottPlot#3738]
Dear ScottPlot Developers,

I've encountered an issue with the scatter plot line lengths after updating to ScottPlot version 5.0.28. In the previous version of ScottPlot, the plotted lines between data points were displayed differently, and the current version shows an extended line length that I would like to adjust.

Im searching now for 3 Hours and i cant help myself...
Thank you!

**Comment by swharden** [comment]
Hi @Alfred-GitHub1, thanks for reporting this! I'm will mark this as high priority and take a closer look soon.

1) Can you provide a code sample to help us reproduce the issue?

2) A new package was released this morning (5.0.29) so confirm the issue is present in the latest version

Thanks!

**Comment by Alfred-GitHub1** [comment]
I am encountering a persistent issue where only four rows of DateTime ticks are displayed, despite multiple attempts to rectify this using various code snippets from the ScottPlot Cookbook. It appears that the modification methods applied are not yielding the expected increase in the number of tick rows.

For your reference, here is the segment of my code responsible for generating the tick marks:

                   List<DateTime> timestamps = new List<DateTime>();
                   List<long> values = new List<long>();
                   using (var reader = await commandDb.ExecuteReaderAsync()) {
                       while (await reader.ReadAsync()) {
                           timestamps.Add(reader.GetDateTime(2));
                           values.Add(reader.GetInt64(1));
                       }
                   }
                   if (timestamps.Count == 0) {
                       await command.FollowupAsync("No data found for the specified item.");
                       return;
                   }
                   long mostRecentValue = values.LastOrDefault();
                   Plot myPlot = new Plot();
                   myPlot.Axes.Title.Label.Text = $"{chosenCategory}: {chosenId}. Current Value: {FormatNumber(mostRecentValue)}";
                   myPlot.Axes.Title.Label.FontSize = 22f;

                   var xs = timestamps.ToArray();
                   var ys = values.Select(v => (double)v).ToArray();
                   var myScatter = myPlot.Add.Scatter(xs,ys);
                   ScottPlot.Colormaps.Turbo colormap = new();
                   ScottPlot.Color color = Generate.RandomColor(colormap);
                   myScatter.Color = color;
                   myScatter.LineWidth = 3;
                   myScatter.MarkerSize = 10;
                   myScatter.Label = chosenId;
                   myPlot.Axes.DateTimeTicksBottom();
                   myPlot.ShowLegend();
                   myPlot.Axes.Color(ScottPlot.Color.FromHex("#d7d7d7"));
                   myPlot.Grid.MajorLineColor = ScottPlot.Color.FromHex("#404040");
                   myPlot.FigureBackground.Color = ScottPlot.Color.FromHex("#181818");
                   myPlot.DataBackground.Color = ScottPlot.Color.FromHex("#1f1f1f");
                   myPlot.Legend.BackgroundFill.Color = ScottPlot.Color.FromHex("#404040");
                   myPlot.Legend.FontColor = ScottPlot.Color.FromHex("#d7d7d7");
                   myPlot.Legend.OutlineStyle.Color = ScottPlot.Color.FromHex("#d7d7d7");
                   myPlot.Legend.Orientation = Orientation.Horizontal;
                   
                   Thank you

**Comment by swharden** [comment]
@Alfred-GitHub1, thanks for a follow-up! Can you paste a screenshot that shows the undesired behavior? It would be helpful if you can show the correct behavior from the previous version too. Thanks!

**Comment by swharden** [comment]
I adapted your code to be a standalone console application. Can you clarify what the issue is?

```cs
DateTime start = new DateTime(2024, 1, 1);
TimeSpan span = TimeSpan.FromDays(1);
List<DateTime> timestamps = ScottPlot.Generate.DateTime.Consecutive(100, start, span).ToList();
List<long> values = ScottPlot.Generate.RandomWalk(100).Select(x => (long)x).ToList();

ScottPlot.Plot myPlot = new();

myPlot.Add.Palette = new ScottPlot.Palettes.Nord();

var myScatter = myPlot.Add.Scatter(timestamps, values);
myScatter.LineWidth = 3;
myScatter.MarkerSize = 10;

myPlot.Axes.DateTimeTicksBottom();
myPlot.Axes.Color(ScottPlot.Color.FromHex("#d7d7d7"));
myPlot.Grid.MajorLineColor = ScottPlot.Color.FromHex("#404040");
myPlot.FigureBackground.Color = ScottPlot.Color.FromHex("#181818");
myPlot.DataBackground.Color = ScottPlot.Color.FromHex("#1f1f1f");

myPlot.SavePng("test.png", 600, 400).LaunchFile();
```

### ScottPlot 5.0.27

![test](https://github.com/ScottPlot/ScottPlot/assets/4165489/9e8d6242-1a07-4158-8cc4-68d5fd9a11ae)

### ScottPlot 5.0.29

![test](https://github.com/ScottPlot/ScottPlot/assets/4165489/8c472726-b762-4f9f-ab93-83ca80b64ed7)

**Comment by swharden** [comment]
This may be related, but I just fixed a bug https://github.com/ScottPlot/ScottPlot/issues/3736 and will release 5.0.30 within the hour which changes how tick labels are measured. I'm still unsure what your specific issue was, but there's a change this new package will fix it 👍
