### ISSUE TITLE
Feature request: Please add separates methods for switching on/off of Pan and Zoom of x/y axis

### ISSUE THREAD

**Issue by MichaelKuelshammer** [ScottPlot/ScottPlot#3739]
Please add in Scottplot for WPF the separate switching on/off of Panning and Zooming,
for example:

SetPanX(true); // true or false
SetPanY(true);
SetZoomX(true);
SetZoomY(true);

Otherwise you have to handle a lot of events like MouseDown, MouseMove, MouseUp, MouseWheel etc.

**Comment by swharden** [comment]
Hi @MichaelKuelshammer, thanks for the suggestion!

I think you can do this using the strategies outlined here: https://scottplot.net/demo/#custom-mouse-actions

https://github.com/ScottPlot/ScottPlot/blob/74239f7d7d0d26a773c219525a60433573a6370d/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/CustomMouseActions.cs#L47-L68

However the user input system is pretty complicated and not intuitive to customize. #3186 is a high priority open issue that should make this easier in an upcoming release 👍

**Comment by MichaelKuelshammer** [comment]
I believe, that users should program themselves, which keycodes and mouse actions they want to inplement and do the programming for their own.

But I understand, that each people has other ideas :-) 
So I dont want any stress.

How does it „Lightning Chart“ ? Dont they not going the easy way ? Giving it to the user ?
