### ISSUE TITLE
WPF events are much fewer than Windows-Forms Events ?

### ISSUE THREAD

**Issue by MichaelKuelshammer** [ScottPlot/ScottPlot#3740]
I miss for example in WPF the events like AxesChanged() and other ones.

Where is the difference between WPF and Windows Forms, so that these events cannot be implemented ?
Or maybe in one of the following versions ?

**Comment by swharden** [comment]
> I miss for example in WPF the events like AxesChanged() and other ones.

I think these events are not specific to the GUI framework (WinForms, WPF, etc). The same code in the WinForms demo should be able to be copy/pasted into a WPF without requiring modification.

https://github.com/ScottPlot/ScottPlot/blob/74239f7d7d0d26a773c219525a60433573a6370d/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/SharedAxes.cs#L40-L41

https://github.com/ScottPlot/ScottPlot/blob/74239f7d7d0d26a773c219525a60433573a6370d/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/SharedAxes.cs#L52-L62

Let me know if you hit a block though, share the code you've written so far, and we can open this up and take a closer look! 👍

**Comment by MichaelKuelshammer** [comment]
Thx for answering. my boss wants WPF, cause it has more future than Windows Forms. If I would write it for myself, I would write it in WinForms. Much faster to develop.

**Comment by swharden** [comment]
WinForms is great for quick apps but WPF is great for modern looking apps that teams maintain over long periods of time. Either way it sounds ScottPlot works effectively the same across all platforms, so I'm glad to hear your issue was resolved! 👍
