### ISSUE TITLE
Update 5.0.31: ScottPlot.Plottables.Crosshair does not show anymore (also not in "Demo" project)

### ISSUE THREAD

**Issue by fdesordi** [ScottPlot/ScottPlot#3752]
**Issue:** Since the latest update on NuGet the ScottPlot.Plottables.Crosshair does not show anymore on the WPF or WinForms controls.
Version 5.0.23 was still functional.

**ScottPlot Version:** 5.0.31

**Code Sample:** ScottPlot Demo "Show Value Under Mouse" : "https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/ShowValueOnHover.cs"

my sample:
```cs
ScottPlot.Plot myPlot = new();
double X_Median = (myPlot.Axes.Bottom.Max + this.WpfPlotSweep.Plot.Axes.Bottom.Min) / 2;
double Y_Median = (myPlot.Axes.Left.Max + this.WpfPlotSweep.Plot.Axes.Left.Min) / 2;
var Crosshair = myPlot.Add.Crosshair(X_Median, Y_Median);
Crosshair.LineColor = Colors.DarkOrange;
myPlot.SavePng("bug.png");
```

**Comment by fdesordi** [comment]
I found a workaround for this issue: I have to manually set the LineWidth:
```cs
ScottPlot.Plot myPlot = new();
double X_Median = (myPlot.Axes.Bottom.Max + this.WpfPlotSweep.Plot.Axes.Bottom.Min) / 2;
double Y_Median = (myPlot.Axes.Left.Max + this.WpfPlotSweep.Plot.Axes.Left.Min) / 2;
var Crosshair = myPlot.Add.Crosshair(X_Median, Y_Median);
Crosshair.LineColor = Colors.DarkOrange;

Crosshair.LineWidth = 1;

myPlot.SavePng("bug.png");
```

It seems like the default line width now is 0.

**Comment by swharden** [comment]
Thanks for noting this @fdesordi! It is fixed in https://github.com/ScottPlot/ScottPlot/commit/45e90a9eacce88cbd8d58526b883fbac32a83f11 and will be in the next release 🚀
