### ISSUE TITLE
StandardZoomRectangle: make `LineStyle` setter public

### ISSUE THREAD

**Issue by Graat** [ScottPlot/ScottPlot#3754]
**Suggestion:**
From StandardZoomRectangle, unlike the FillColor, the LineStyle cannot be set.

Would it be possible to change line 12 from:
https://github.com/ScottPlot/ScottPlot/blob/1292c69c7663ea7f25ca8d90014f83addf4cca9f/src/ScottPlot5/ScottPlot5/Control/StandardZoomRectangle.cs#L13

to?:
```cs
public LineStyle LineStyle { get; set; } = new() { Color = new Color(255, 0, 0).WithAlpha(200) };
```

**Comment by swharden** [comment]
Sure thing! I won't be able to get to this until tonight, but if you or someone else from the open source community wants to make that change as a pull request, I'd be happy to merge it in next time I'm working on this code base 👍

**Comment by swharden** [comment]
Note that even though it wasn't originally public to set, I think you can still set its properties like "MyZoomRectangle.LineStyle.Color = myNewColor"

**Comment by Graat** [comment]
You're absolutely right! Silly I didn't even think of that. Thanks for the help. :)
