### ISSUE TITLE
Marker.MarkerLineWidth stopped working after v5.0.27

### ISSUE THREAD

**Issue by CD-SailingPerf** [ScottPlot/ScottPlot#3755]
**Issue:** Creating a marker with Shape = ScottPlot.MarkerShape.FilledCircle, setting MarkerLineWidth and MarkerLineColor stopped working after v5.0.27

**ScottPlot Version:** v5.0.31

```cs
ScottPlot.Plot myPlot = new();
ScottPlot.Plottables.Marker mrk = myPlot.Add.Marker(new ScottPlot.Coordinates() { X = 5, Y = 5 });
mrk.Size = 100;
mrk.Color = ScottPlot.Colors.Black.WithAlpha(0.5f);
mrk.MarkerLineWidth = 2;
mrk.MarkerLineColor = ScottPlot.Colors.Black; 
mrk.Shape = ScottPlot.MarkerShape.FilledCircle;
myPlot.SavePng("bug.png");
```

v5.0.27:

![image](https://github.com/ScottPlot/ScottPlot/assets/30892265/d4aff645-2f52-41e7-8280-bfb0eaa52d4b)

v5.0.31:
![image](https://github.com/ScottPlot/ScottPlot/assets/30892265/775fe5f8-23a9-4f65-a07a-22593b9c5180)

**Comment by swharden** [comment]
Hi @CD-SailingPerf, thanks for reporting this! Oof I don't know what I was thinking 😅 The outline width should default to zero, but I accidentally added this extra flag. 

I'll remove it for the next release, but for now this works:

```cs
mrk.MarkerStyle.FillOutline = true;
```

**Comment by swharden** [comment]
> Oof I don't know what I was thinking 😅 

Being kinder to myself, https://github.com/ScottPlot/ScottPlot/pull/3716 was a huge refactor. This flag got added as an intermediate step and I forgot to remove it before release 😇

**Comment by swharden** [comment]
Actually, this is an outstanding deficiency that needs to be resolved. I'll use this issue to track progress toward a solution. Many marker shapes should not render outlines by default (e.g., filled circle), but many marker shapes must render lines by default (e.g., cross).

I'll refactor `MarkerStyle` to use separate `LineStyle` and `OutlineStyle` properties to customize these two distinct use cases, and update the filled marker renderers to use the correct properties.

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/7bc3bbe1-01e0-41e6-a907-ef2d23c91189)

**Comment by swharden** [comment]
```cs
// make lines blue
mp1.MarkerStyle.LineWidth = 2;
mp1.MarkerStyle.LineColor = Colors.Blue;

// make fills light green
mp1.MarkerStyle.FillColor = Colors.Green.WithAlpha(.2);

// make outlines dark green
mp1.MarkerStyle.OutlineColor = Colors.Green;
mp1.MarkerStyle.OutlineWidth = 2;
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/27a4ad28-ebb4-4dfe-92ec-8873654aa0fe)

**Comment by CD-SailingPerf** [comment]
Nice one, thanks!
