### ISSUE TITLE
ScottPlot 5: Stiatistical distribution issue

### ISSUE THREAD

**Issue by linefinc** [ScottPlot/ScottPlot#3756]
**Issue:** 
We are update code from ScottPlot 4 to 5 and we have a very simple graph like https://scottplot.net/cookbook/4.1/category/statistics/#histogram-stdev.

We observed that when we add the Function the function does't take the graph limits.
![M0101](https://github.com/ScottPlot/ScottPlot/assets/3885158/8f6fe5ca-2aad-4588-8d5f-aa7ed1e13ca4)
Our code is the following:
```cs
var probabilityCurve = hist.GetProbabilityCurve(data);
Func<double, double> probabilityCurveDouble = (x) =>
{
	var y = probabilityCurve.Invoke(x);
	return y.HasValue ? y.Value : 0;
};
var function = myPlot.Add.Function(probabilityCurveDouble);
function.MaxX = data.Max();
function.MinX = data.Min();

```

The issue is in the function Add Function not set axis limit 

we try this code
``` cs 
var probabilityCurve = hist.GetProbabilityCurve(data);
Func<double, double> probabilityCurveDouble = (x) =>
{
	var y = probabilityCurve.Invoke(x);
	return y.HasValue ? y.Value : 0;
};
var functionSource = new FunctionSource(probabilityCurveDouble)
{
	RangeX = new CoordinateRange(hist.Min, hist.Max),
};

var function = myPlot.Add.Function(functionSource);

```

the issue remain 

we fixed like that 
``` cs 
double delta = (maxValue - minValue) / 100;
for (double x = minValue; x < maxValue; x += delta)
{
	double x0 = x;
	double x1 = x + delta;

	double? y0 = probabilityCurve.Invoke(x0);
	double? y1 = probabilityCurve.Invoke(x1);

	if (y1 == null || y0 == null)
	{
		continue;
	}

	Coordinates pt1 = new Coordinates(x0, y0.Value);
	Coordinates pt2 = new Coordinates(x1, y1.Value);
	var line = myPlot.Add.Line(pt1, pt2);
	line.MarkerSize = 0;
	line.LineWidth = 2;
	line.LinePattern = LinePattern.Solid;
	line.Color = ScottPlot.Colors.DarkRed;
}
```

**Comment by swharden** [comment]
Hi @linefinc, thanks for reporting this!

The code examples fall a bit short because there's not a program in  this comment I can run on my machine to reproduce the issue... but I think I understand the problem

> The issue is in the function Add Function not set axis limit

It sounds like this is the core problem.

Does setting the function's `MinX` and `MaxX` properties resolve this issue?

https://scottplot.net/cookbook/5.0/Function/FunctionLimitX/
