### ISSUE TITLE
DateTimeFixedInterval not Generating Expected Daily Ticks

### ISSUE THREAD

**Issue by Alfred-GitHub1** [ScottPlot/ScottPlot#3757]
Environment:

ScottPlot Version: ScottPlot 5.0.31

Problem Description:
When attempting to generate a scatter plot with daily tick marks on the X-axis using the DateTimeFixedInterval tick generator, the plot unexpectedly generates ticks at three-day intervals despite explicitly setting the interval for one day. The issue persists even after explicitly setting intervalsPerTick to 1 and regenerating ticks with an appropriate PixelLength.

Steps to Reproduce:

Initialize a Plot object and set up axes and scatter plot data.
Set up the DateTimeFixedInterval tick generator with a one-day interval.
Apply the tick generator to the X-axis.
Call RegenerateTicks providing a pixel width that matches the plot’s actual dimension.
Save or render the plot to observe the tick intervals.
Expected Behavior:
The X-axis should display ticks for each day corresponding to the dates provided in the dataset.

Actual Behavior:
The X-axis displays ticks at three-day intervals instead of daily.

Previously, I was using version 5.0.2, where the spacing between the ticks was perfect. However, after updating, the ticks are now spaced too far apart - sometimes as few as two ticks across the entire plot.

Code to Reproduce:

```cs
Plot myPlot = new Plot();
myPlot.Axes.Title.Label.Text = $"{chosenCategory}: {chosenId}. Current Value: {FormatNumber(prices.Last())}";
myPlot.Axes.Title.Label.FontSize = 22f;
ITimeUnit oneDay = new ScottPlot.TickGenerators.TimeUnits.Day(); 
var dateTimeFixedInterval = new DateTimeFixedInterval(oneDay,intervalsPerTick: 1) { MaxTickCount = 100 };
myPlot.Axes.Bottom.TickGenerator = dateTimeFixedInterval;
PixelLength sizeOfAxis = new PixelLength(1000); 
myPlot.Axes.Bottom.RegenerateTicks(sizeOfAxis);
var xs = timestamps.ToArray();
var ys = prices.ToArray();
var myScatter = myPlot.Add.Scatter(xs,ys);
ScottPlot.Colormaps.Turbo colormap = new();
ScottPlot.Color color = Generate.RandomColor(colormap);
myScatter.Color = color;
myScatter.LineWidth = 3;
myScatter.MarkerSize = 10;
myScatter.Label = chosenId;
myPlot.Axes.DateTimeTicksBottom();
myPlot.ShowLegend();
myPlot.Axes.Color(ScottPlot.Color.FromHex("#d7d7d7"));
myPlot.Grid.MajorLineColor = ScottPlot.Color.FromHex("#404040");
myPlot.FigureBackground.Color = ScottPlot.Color.FromHex("#181818");
myPlot.DataBackground.Color = ScottPlot.Color.FromHex("#1f1f1f");
myPlot.Legend.BackgroundFill.Color = ScottPlot.Color.FromHex("#404040");
myPlot.Legend.FontColor = ScottPlot.Color.FromHex("#d7d7d7");
myPlot.Legend.OutlineStyle.Color = ScottPlot.Color.FromHex("#d7d7d7");
myPlot.Legend.Orientation = Orientation.Horizontal;
string fileName = "Scatter_tmp.png";
string folderPath = "images";
string filePath = Path.Combine(folderPath,fileName);
myPlot.SavePng(filePath,1000,700);
```

**Comment by swharden** [comment]
> the plot unexpectedly generates ticks at three-day intervals despite explicitly setting the interval for one day

I suspect this is because the interval defines the _minimum_ tick distance, and the tick generator decides how many ticks to place on the plot according to the width of their labels so they don't overlap.

For exact control of where ticks are placed, I think the manual tick generator is the way to go.

```cs
using ScottPlot;

Plot myPlot = new();

DateTime firstDay = new(2024, 05, 01);

// high density data
DateTime[] dataPointXs = Generate.ConsecutiveHours(200, firstDay);
double[] dataPointYs = Generate.RandomWalk(dataPointXs.Length);
myPlot.Add.Scatter(dataPointXs, dataPointYs);

// lower density tick positions
DateTime[] tickDates = Generate.ConsecutiveDays(20, firstDay);

// use manual tick generator
ScottPlot.TickGenerators.NumericManual tickGen = new();
myPlot.Axes.Bottom.TickGenerator = tickGen;
foreach (DateTime dt in tickDates)
    tickGen.AddMajor(dt.ToOADate(), dt.Date.ToShortDateString());

myPlot.SavePng("test.png", 600, 400).LaunchFile();
```

![test](https://github.com/ScottPlot/ScottPlot/assets/4165489/de98a740-cfb4-4d7e-886e-6642596ba1c6)

**Comment by Alfred-GitHub1** [comment]
thank you very much :)
