### ISSUE TITLE
Replace data of plottable

### ISSUE THREAD

**Issue by chrislo1976** [ScottPlot/ScottPlot#3760]
**Question:** How to replace data of an existing plottable?

**ScottPlot Version:** 5.0.31 (Avalonia)

**In ScottPlot4 one could do:**

```cs
Scatter.Clear();
Scatter.AddRange(xs, ys);
```

How to achieve that in SC5 ?

**Comment by swharden** [comment]
These links should help 👍 🚀 
https://scottplot.net/demo/#plot-streaming-data
https://scottplot.net/demo/#plot-growing-data
https://scottplot.net/demo/#plot-live-financial-data

**Comment by swharden** [comment]
You can also modify the content of arrays after you've added them to a plot
https://scottplot.net/faq/live-data/#scatter-plot-change-values-in-fixed-length-arrays
