### ISSUE TITLE
Add .Measure() functionality back in

### ISSUE THREAD

**Issue by aespitia** [ScottPlot/ScottPlot#3761]
Suggestion: in a recent SP5 update, the .Measure function now requires a new SKPaint object to be passed in when it didn't use to be.  Prior, you could just give it the text that you wanted it to measure, or if you called .Measure() on a label, it would measure itself.  Would be great to have functionality back.

**Comment by swharden** [comment]
Done! Note that `Measure()` now returns a `MeasuredText` object which has information not just about exact width/height but also recommended line height for multiline strings
