### ISSUE TITLE
VectorField: Add ScaleFactor

### ISSUE THREAD

**Issue by hnMel** [ScottPlot/ScottPlot#3763]
Can Custom Scale Factor from ScottPlot 4 be added to ScottPlot 5?

**Comment by swharden** [comment]
Hi @hnMel, thanks for the question! Here's the ScottPlot 4 feature: https://scottplot.net/cookbook/4.1/recipes/vectorfield_scalefactor/

I like the idea of adding this to ScottPlot 5! I'll mark this "help wanted" in case someone else from the open source community is able to add this feature before I get to it. The lines of code which would need to be modified are probably these, and a good implementation would be to modify them to be like, "if a scale factor property is other than 1.0, create a copy of the data values, multiply them by the scale factor, and pass those values instead"

https://github.com/ScottPlot/ScottPlot/blob/debfb0e14aefc0a123cfd04fbd6ea800bdb39623/src/ScottPlot4/ScottPlot/Plottable/VectorField.cs#L121

https://github.com/ScottPlot/ScottPlot/blob/debfb0e14aefc0a123cfd04fbd6ea800bdb39623/src/ScottPlot4/ScottPlot/Plottable/VectorField.cs#L109

**Comment by swharden** [comment]
```cs
RootedCoordinateVector[] vectors = Generate.SampleVectors();
var vf = myPlot.Add.VectorField(vectors);
vf.MaximumArrowLength = 15;
```

![image](https://github.com/user-attachments/assets/e33d2e0c-c9d4-4080-a423-f02ba10f37d3)
