### ISSUE TITLE
SignalXY: add option for step display

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3764]
SignanXY() in Ver5.0 doesn't have Stepline property

**ScottPlot Version: 5.0.32**

**Code Sample:** 
```cs
ScottPlot.Plot myPlot = new();
/* code to reproduce the bug */
  var signal = scottPlotUC.Plot.Add.SignalXY(xData, y1Data);
signal.Stepline = true;  (this property not exists but it exists in Ver 4.0)
```

**Comment by swharden** [comment]
Hi @kareem469, thanks for the suggestion! It would be great to add a `ConenctStyle` to Signal and SignalXY plots to mimic scatter plots.

https://scottplot.net/cookbook/5.0/Scatter/ScatterStep/

**Comment by kareem469** [comment]
Hi @swharden, thanks for the quick reply. 

When can we expect the ConenctStyle to Signal and SignalXY plots in latest Ver 5.0?

**Comment by swharden** [comment]
> When can we expect the ConenctStyle to Signal and SignalXY plots in latest Ver 5.0?

I've marked this issue "high priority" so it will probably make be available in the next release, likely published over this weekend 👍

**Comment by kareem469** [comment]
once again Thanks, @swharden, it's nice to hear from you. 

I will be waiting for the next release.

**Comment by swharden** [comment]
Added in https://github.com/ScottPlot/ScottPlot/commit/9dc9d397e1159d4965497576c6f8418cc5c842e8 and it works with SignalXY the same way it does with scatter plots

https://scottplot.net/cookbook/5.0/Scatter/ScatterStep/

**Comment by kareem469** [comment]
Just now i have checked. Its working 

Once again, thanks for your support.

Will keep in touch.
