### ISSUE TITLE
SignalXY: How to get the nearest point to the mouse location

### ISSUE THREAD

**Issue by cataclism** [ScottPlot/ScottPlot#3766]
**Question:**
For an application of mine I need to track the value of the Signal function as the mouse moves on the X axis. 

So I tried to extend the sample code to work with a Signal function. 
The problem I'm facing is that I can't find a way to extract the value from the function given the X value of the mouse.

Looking at the documentation it says that I should use the GetNearest method, which unfortunately is not available ( Cannot resolve symbol).
![image](https://github.com/ScottPlot/ScottPlot/assets/69798041/4c4d511e-c3ee-441d-8531-31b73adf42b2)

I tried converting the Signal to a SignalXY, but the resolution is not enough since I only obtain integer values.

So I really don't know hot to take this task home.

Thanks in advance to everyone

**ScottPlot Version:** 5.0.32
** .NETFramework 4.6.2

**Comment by swharden** [comment]
Hi @cataclism, thanks for this question!

To be sure we are starting from the same place, have you seen the code for https://scottplot.net/demo/#show-value-under-mouse ? I think you can do the same thing with a SignalXY plot. I just checked and confirmed it has a GetNearest() function, so your code would look something like

```cs
DataPoint nearest = mySignalXyPlot.Data.GetNearest(mouseLocation, formsPlot1.Plot.LastRender);
```

**Comment by cataclism** [comment]
Hi @swharden , 
Unfortunately I can't use the GetNearest since VS tells me that:
![image](https://github.com/ScottPlot/ScottPlot/assets/69798041/355a479e-d828-4267-9a44-781718e66133)

Yes i've seen that code and I'm using it to obrain the position of the mouse in the plot. 

And maybe I've not been clear but I'd need to find the value of a Signal and not a SignalXY, is that possible?

So given the value of the mouse I need to find the value of the Signal ( not XY ) function, so that I can Add a Marker around that point.

Thanks in advance

**Comment by swharden** [comment]
```cs
using ScottPlot;
using System.Diagnostics;

namespace WinForms_Demo.Demos;

public partial class ShowValueUnderMouseSignalXY : Form
{
    readonly ScottPlot.Plottables.SignalXY MySignal;
    ScottPlot.Plottables.Crosshair MyCrosshair;

    public ShowValueUnderMouseSignalXY()
    {
        InitializeComponent();

        double[] xs = Generate.Consecutive(1000);
        double[] ys = Generate.RandomWalk(1000);
        MySignal = formsPlot1.Plot.Add.SignalXY(xs, ys);

        MyCrosshair = formsPlot1.Plot.Add.Crosshair(0, 0);
        MyCrosshair.IsVisible = false;
        MyCrosshair.MarkerShape = MarkerShape.OpenCircle;
        MyCrosshair.MarkerSize = 15;

        formsPlot1.MouseMove += (s, e) =>
        {
            // determine where the mouse is and get the nearest point
            Pixel mousePixel = new(e.Location.X, e.Location.Y);
            Coordinates mouseLocation = formsPlot1.Plot.GetCoordinates(mousePixel);
            DataPoint nearest = MySignal.Data.GetNearest(mouseLocation, formsPlot1.Plot.LastRender);

            // place the crosshair over the highlighted point
            if (nearest.IsReal)
            {
                MyCrosshair.IsVisible = true;
                MyCrosshair.Position = nearest.Coordinates;
                formsPlot1.Refresh();
                Text = $"Selected Index={nearest.Index}, X={nearest.X:0.##}, Y={nearest.Y:0.##}";
            }

            // hide the crosshair when no point is selected
            if (!nearest.IsReal && MyCrosshair.IsVisible)
            {
                MyCrosshair.IsVisible = false;
                formsPlot1.Refresh();
                Text = $"No point selected";
            }
        };
    }
}
```

**Comment by Cartheme** [comment]
Hi @swharden ,

Your demo takes on the SignalXY. Is there a way to do this with a BarPlot?

Thanks in advance
