### ISSUE TITLE
Plotting Mutiple Digital signals (1s & 0s) one below the other in a signle graph?

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3772]
Why cann't we Plot the Mutiple Digital signals (1s & 0s) one below the other in a signle graph instead of creating mutiple graphs?

Below is the sample graph in which mutiple signals are plotted in a singel graph one below the other.

![image](https://github.com/ScottPlot/ScottPlot/assets/101133645/31066cf3-7a95-4267-8a87-02d9fcf9e198)

**Comment by swharden** [comment]
Hi @kareem469, I believe the figure you showed a screenshot of could be implemented with ScottPlot if you create a custom plot type for displaying binary data https://scottplot.net/faq/custom-plot-type/
