### ISSUE TITLE
How to disable user input panning but permit panning programmatically

### ISSUE THREAD

**Issue by FlyLff** [ScottPlot/ScottPlot#3784]
Using ScottPlot 5.0.34, after I added LockedHorizontal to wpfPlot1.Plot.Axes.Rules, the background code calling the wpfPlot1.Plot.Axes.Pan method was unable to move the horizontal axis. 

I use ScottPlot 4.x.x, by putting wpfPlot1. Configuration. LockHorizontalAxis set to True, to ban the user to move or scale horizontal axis in the interface, I moved the horizontal axis in the background code by using the wpfPlot1.Plot.AxisPan method.
I was unable to implement this in ScottPlot 5.x.x.

**Comment by swharden** [comment]
Hi @FlyLff, that can be achieved like this, but leave out the line about drag pan button:

https://github.com/ScottPlot/ScottPlot/blob/6363e8e37ec42a156e8992501fddd8e8df675462/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/CustomMouseActions.cs#L51-L67

This code is from the demo app: https://scottplot.net/demo/#custom-mouse-actions
