### ISSUE TITLE
Heatmap how to remove legend before re plotting

### ISSUE THREAD

**Issue by mus3na** [ScottPlot/ScottPlot#3788]
**Question:** i need a way to remove legend from HeatMap plot under ScottPlot Version 5. Plot.clear() onle remove chart but legend remaind in existing plot. therefore when i replot new data, number of lagend will increase (each time i refresh, it will add new legend).

**ScottPlot Version:** 5

**Code Sample:** 

       ' Clear plot before reuse
        FormsPlot1.Plot.Clear()

        ' Plot the transposed data as a heatmap
        Dim Color_Map = FormsPlot1.Plot.Add.Heatmap(transposedHeatLoad)
        Color_Map.Colormap = New ScottPlot.Colormaps.Turbo

        ' Add a color bar with representing intensity values
        FormsPlot1.Plot.Add.ColorBar(Color_Map)

The code is in VB.NET for winform
![image](https://github.com/ScottPlot/ScottPlot/assets/55247462/a14cc861-6a93-4821-b4f3-b675b0279498)

**Comment by swharden** [comment]
Hi @mus3na, I think you can remove all those right axis panels by calling:
```cs
FormsPlot1.Plot.Axes.Remove(Edge.Right);
```

Let me know if it doesn't work as expected and we can open this issue back up and take a closer look! 👍

**Comment by mus3na** [comment]
Hi, thanks for the reply.

The code you give below didn't produce result as what i need but it give a better presentation by removig the white space between the intensity image and its scale ruler.

i somehow found a way to completely remove this intensity image and ruler (legend) by resetting the plot before re plotting new data. so its ok to close the issue. my work arround code are as below;

i call this code;

    FormsPlot1.Plot.Clear()
        FormsPlot1.Reset()
        FormsPlot1.Plot.Axes.Remove(Edge.Right)


before re create the plot

        Dim Color_Map = FormsPlot1.Plot.Add.Heatmap(transposedHeatLoad)
        Color_Map.Colormap = New ScottPlot.Colormaps.Turbo
        FormsPlot1.Plot.Add.ColorBar(Color_Map)


Thank you
Hi, thanks
________________________________
