### ISSUE TITLE
DataLogger with AxisScaleLock(true), data/axis limit issue

### ISSUE THREAD

**Issue by bukkideme** [ScottPlot/ScottPlot#3789]
**Issue:**
DataLogger strange behaviour when axis scale lock is active. The data first part is not visible after a while, and when the loop finishes, the Mouse Middle button click works wrong: does not auto-scale the graph so the whole data is visible.

**ScottPlot Version:** 4.1.71

**Code Sample:**

```cs
DataLogger dataLogger = formsPlot1.Plot.AddDataLogger(lineWidth: 3);
double[] arrayY = new double[] { 0, 2, 10, 10, 10, 5, 0, 0, 5, 10 };

//if this is present, the Mouse middle click behaves strange after the plot finished, 
//and the first part of the plot is not visible when the loop finishes
formsPlot1.Plot.AxisScaleLock(true);

for (int i = 0; i < 10; i++)
{
    dataLogger.Add(i * 3000, arrayY[i] * 1000);
    Thread.Sleep(250);
    formsPlot1.Refresh();
}
```

**Comment by swharden** [comment]
Hi @bukkideme, thanks for reporting this! Before I pop the hood on this one and do a deeper dive, check out the overload of `AxisScaleLock()` which accepts a scale mode. I suspect that your issue may be resolved by passing in the correct scale mode. If not, let me know and we can open this back up and take a closer look 👍
