### ISSUE TITLE
Scatter FillY Double Fill

### ISSUE THREAD

**Issue by BendRocks** [ScottPlot/ScottPlot#3791]
**Issue:** (Describe the bug here)
When FillY is enabled with a non-zero FillYValue, the area to be filled is filled twice. When alpha is < 1.0, the result is two shades of the fill color.

**ScottPlot Version:** (What NuGet package are you using?)

5.0.34.0

I cloned the repo and modified the Sandbox.Winforms.Form1.cs

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

This code was put into the Form1 constructor in the Sandbox.Winforms:

```cs
 double[] xs = { 2, 200, 2000, 20000 };
 double[] ys = { -50, 10, -80, -100 };

 // add log-scaled data to the plot
 var sp = formsPlot1.Plot.Add.Scatter(xs, ys);
 sp.LineWidth = 2;
 sp.FillY = true;
 sp.FillYColor = Colors.Blue.WithAlpha(0.5);
 sp.FillYValue = -200;
```

And the resulting output is as shown. Note that alpha is 0.5, so filling it twice changes the apparent color. 

![image](https://github.com/ScottPlot/ScottPlot/assets/24760857/de35e1e9-8165-4ad0-b83a-c3bc3cc35e0f)

Inside Scatter.cs, there is the following around line 135:

https://github.com/ScottPlot/ScottPlot/blob/6cc3bbb5b98b62c35622056f2a9d55f2f3d51f8e/src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs#L134-L162

Note that rectAbove and rectBelow are both drawn. If the 5 lines for rect below are commented out, then the fill is as expected (shown below). So, at first glance, it seems either one or the other should be selected, based on the FillY value being positive or negative. However, there are a lot of considerations here, and I don't understand the breadth of the code base enough to know if such a simple change might have impacts elsewhere. 

![image](https://github.com/ScottPlot/ScottPlot/assets/24760857/150046bf-32c7-4b4b-9118-81fe2e206712)

**Comment by swharden** [comment]
Thanks for reporting this @BendRocks! I believe it is fixed in https://github.com/ScottPlot/ScottPlot/commit/90f05ee8f1fd62b6ae08788ba5a84da7ebfb8988 and will be in the next release 👍 🚀
