### ISSUE TITLE
Require the Draggable Axis lines on all the graphs same like Shared Axes?

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3796]
**Require the Draggable Axis lines on all the graphs same like Shared axes?** 

**ScottPlot Version:5.0.34** 

How to achieve the Draggable Axis lines on all the graphs when lines are moved on any one of the graph same like Shared Axes?

Thanks in Advance.

**Comment by kareem469** [comment]
Can you please provide the sample code for the above requirement to work 👆

**Comment by kareem469** [comment]
> Can you please provide the sample code for the above requirement to work 👆

**Comment by swharden** [comment]
Hi @kareem469, I marked this issue high priority but there are good number of open high priority issues and I typically resolve them bottom to top https://github.com/ScottPlot/ScottPlot/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E2%9A%A0%EF%B8%8F+HIGH+PRIORITY%22 so it may take a little while before I'm able to get to this one
