### ISSUE TITLE
In Shared Axes while zooming Y Axis, only Y1 scale is updating for all the graphs but Y2 scale is not updating

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3800]
**Y2 Scale not updating while zooming Y axis using Shared Axes** 

**ScottPlot Version:5.0.34**

While using Shared Axes when zooming Y Axis, only Y1 scale is updating for all the graphs but Y2 scale is not updating.

**Comment by swharden** [comment]
Hi @kareem469, I think you are referring to https://scottplot.net/demo/#shared-axes

Sharing the X but not Y limits was intentional. You can modify this line to achieve the behavior you are looking for.
https://github.com/ScottPlot/ScottPlot/blob/093994e1b020d2d1f349e4e0a06c9d67e2577b44/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/SharedAxes.cs#L60

**Comment by kareem469** [comment]
Here, the Y1 axis (left side) is updating for all the graphs. But the Y2 axis (right side) is not updating. 

Following is the code sample 

foreach (var plot in plots)
{
    if (plot != sourcePlot)
    {
        AxisLimits axesBefore = destPlot.Plot.Axes.GetLimits();
       
         if(GraphZoomAxisTypes.XY.ToString() == cmbAxisType.Text)
                    plot.Plot.Axes.SetLimits(sourcePlot.Plot.Axes.GetLimits());
         else if(GraphZoomAxisTypes.Y.ToString() == cmbAxisType.Text)
                  plot.Plot.Axes.SetLimitsY(sourcePlot.Plot.Axes.GetLimits());
         else if(GraphZoomAxisTypes.X.ToString() == cmbAxisType.Text)
                  plot.Plot.Axes.SetLimitsX(sourcePlot.Plot.Axes.GetLimits());

        AxisLimits axesAfter = plot.Plot.Axes.GetLimits();
        if (axesBefore != axesAfter)
            plot .Refresh();
       
    }
}

Thanks in advance.

**Comment by swharden** [comment]
> But the Y2 axis (right side) is not updating.

SetLimits() works on the bottom and left axes by default, but there are overloads which let you pass in the right axis and it will adjust that axis.

**Comment by kareem469** [comment]
Hi @swharden

Can you provide the overlords which let me pass in the right axis and it will adjust that axis.

**Comment by swharden** [comment]
> Can you provide the information about the overloads 

I'm on a cell phone at the moment, but if you're using Visual Studio and start typing the method, a tooltip will pop up displaying the different overloads that are available. Ones that accept an `IYAxis` will allow you to pass in ` plot.Plot.Axes.Right`

**Comment by kareem469** [comment]
Hi @swharden 
I am using visual studio. Will try and let you know

**Comment by kareem469** [comment]
Hi @swharden

For the above query, i observed that when Y axis is zoomed, the X axis is zooming for all the graphs but when i zoom only Y axis, then only the graph on which the mouse exists, for that Y2 is also zooming, and for the remaining graphs only Y1 is zooming. 

I wonder how Y1 is zooming for all the graphs at a time and not for Y2?
