### ISSUE TITLE
Adding Signal Data to a Graph in ScottPlot

### ISSUE THREAD

**Issue by bulent017** [ScottPlot/ScottPlot#3803]
**When adding real-time data to Plotter, it always receives it as an array or list. When I add real-time data to Plotter, I do not add it one by one. So I need to create and add a Signal data. Can I do this? I looked at all Chart types.**
example:

double[] data = .....
myPlot.Add.Signal(data);
Does ScottPlot just create a signal data and plot it on the graph?

**Comment by swharden** [comment]
Hi @bulent017, do the code examples here help answer your question? 

- https://scottplot.net/demo/#plot-streaming-data
- https://scottplot.net/demo/#plot-growing-data
- https://scottplot.net/faq/live-data/

**Comment by bulent017** [comment]
No, I looked at the examples here and the github repo. When drawing signals on the graph, it always takes either an array or a list. I am giving an example, I want to do it like plotter.Add.Signal(signal1) after Signal signal1 = new Signal(). But I couldn't find any code example like this. I have looked at the links you gave many times.

**Comment by swharden** [comment]
Hi @bulent017, thanks for following up! I read your original question again and your latest comment and I think the issue is that I do not understand your question.

>  I want to do it like plotter.Add.Signal(signal1) after Signal signal1 = new Signal(). 

Maybe something like this can help?

```cs
Signal signal1 = new Signal();
plotter.Add.Plottable(signal1);
```
