### ISSUE TITLE
Plot: Create `Clear<T>()` as an alias for `Remove<T>()`

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3804]
The same way that GetPlottables<T>() works

https://github.com/ScottPlot/ScottPlot/blob/093994e1b020d2d1f349e4e0a06c9d67e2577b44/src/ScottPlot5/ScottPlot5/Plot.cs#L366-L369

**Comment by UrbaLaba7** [comment]
Might be useful, from my code where need to remove dashed lines and repaint.
`        // Iterate through plot's elements and remove dashed lines
        void RemoveDashedLines(Plot plot)
        {
            for (int i = plot.PlottableList.Count - 1; i >= 0; i--)
            {
                if (plot.PlottableList[i] is Scatter scatter && scatter.LineStyle.Pattern == LinePattern.Dashed)
                    plot.Remove(scatter);
            }
        }`

**Comment by CoderPM2011** [comment]
It seems the same as `Remove<T>()`.

https://github.com/ScottPlot/ScottPlot/blob/093994e1b020d2d1f349e4e0a06c9d67e2577b44/src/ScottPlot5/ScottPlot5/Plot.cs#L419-L426

**Comment by swharden** [comment]
> It seems the same as `Remove<T>()`

Good find! That's the exact function I was looking for and I forgot it was there 😅 

I instinctively reached for `Clear<T>()` so maybe we should add it as an alias to `Remove<T>()` to make it more discoverable

**Comment by swharden** [comment]
resolved in #3820
