### ISSUE TITLE
Heatmap: Left edge does not start at zero

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3806]
Email from Feng Q.

> It’s a bug？The coordinate system range was set, but the drawing exceeded the range of the coordinate system. You developed this control is very practical, very good, thank you very much！

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/2bca3f7f-1def-42c1-a641-3aa21e59754a)

**Comment by swharden** [comment]
Seems to be https://scottplot.net/cookbook/5.0/Heatmap/HeatmapInverted/ which I think is functioning as expected

**Comment by FengQingYangDad** [comment]
Thank you very much for your reply. Both X and Y coordinates are set in this coordinate system, the X coordinates are from 0 to 65, but the actual graph shows that the X-axis appears to start at -0.5. The same XY coordinate system has the phenomenon of outside the set range。

**Comment by swharden** [comment]
Thanks for the clarification @FengQingYangDad! I'll open this issue back up and we can take a closer look shortly and hopefully arrive at a good solution for the next release 👍

**Comment by FengQingYangDad** [comment]
thank you very much！

**Comment by swharden** [comment]
Default behavior is that the lower left cell is _centered_ at (0, 0) resulting in the behavior you observe:

```cs
double[,] data = {
    { 1, 2, 3 },
    { 4, 5, 6 },
    { 7, 8, 9 },
};

myPlot.Add.Heatmap(data);
```

![HeatmapCellAlignment](https://github.com/ScottPlot/ScottPlot/assets/4165489/08b9e099-7069-484d-b9c7-289bfbf51981)

Set cell alignment to lower left for the bottom left corner of the heatmap to be at the origin:

```cs
double[,] data = {
    { 1, 2, 3 },
    { 4, 5, 6 },
    { 7, 8, 9 },
};

var hm = myPlot.Add.Heatmap(data);
hm.CellAlignment = Alignment.LowerLeft;
```

![HeatmapCellAlignment](https://github.com/ScottPlot/ScottPlot/assets/4165489/8789d8b8-f0d4-44e8-9b6f-73c02ab5e1e7)

I'll add a cookbook recipe to make this feature more discoverable 👍
