### ISSUE TITLE
SignalXY: Add `GetPointNearestX`

### ISSUE THREAD

**Issue by cataclism** [ScottPlot/ScottPlot#3807]
It would be awesome to bring back GetPointNearestX of ScottPlot 4.x for SignalXY to be able again to extract the Yvalue of the SignalXY given the Xposition.

I tried to look at the old code that looks like this:

```cs

private (TX x, TY y, int index) GetPointByIndex(int index)
{
    return (Xs[index], Ys[index], index);
}

/// <summary>
/// Return the X/Y coordinates of the point nearest the X position
/// </summary>
/// <param name="x">X position in plot space</param>
/// <returns></returns>
public (TX x, TY y, int index) GetPointNearestX(TX x)
{
    int index = Array.BinarySearch(Xs, MinRenderIndex, MaxRenderIndex - MinRenderIndex, x);
    if (index < 0)
    {
        index = ~index;
    }
    else // x equal to XS element
    {
        return GetPointByIndex(index);
    }
    if (index <= MinRenderIndex) // x lower then any MinRenderIndex
        return GetPointByIndex(MinRenderIndex);
    if (index > MaxRenderIndex) // x higher then MaxRenderIndex
        return GetPointByIndex(MaxRenderIndex);

    TX distLeft = SubstractExp(x, Xs[index - 1]);
    TX distRight = SubstractExp(Xs[index], x);
    if (LessThanOrEqualExp(distLeft, distRight)) // x closer to XS[index -1]
        return GetPointByIndex(index - 1);
    else // x closer to XS[index]
        return GetPointByIndex(index);
}

```

Something similar would be awesome. I don't know however how to extract X and Y from a signalXY of it's even possible

**Comment by MatKinPro** [comment]
Also requesting this for the normal Signal plot.

**Comment by swharden** [comment]
Just noticed this demo seems to be in the demo app, with code

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/55735ab9-8e09-46f3-adbf-658113b3731a)

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/785ef112-e211-41aa-9c4d-7ffa2813c6ae)

**Comment by swharden** [comment]
More specifically, the code to use it seems to be `MySignal.Data.GetNearest()`

https://github.com/ScottPlot/ScottPlot/blob/44ee711df9f646ee82b124e1f98b8a4c5f597fc0/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/ShowValueUnderMouseSignalXY.cs#L34

**Comment by swharden** [comment]
Okay I'm opening this back up because in fairest `GetNearest()` is slow because it triangulates distance to every point (`X` and `Y`), but it could be faster if we added `GetNearestX()` that ignored Y position

**Comment by swharden** [comment]
I'm merging in #3914 which adds both of these features and they will be available in the next release 🚀 

I added this feature just for the scatter plots which use `double` arrays, but I welcome code contributions from the open source community to complete the other data sources https://github.com/ScottPlot/ScottPlot/pull/3914/commits/846b02ce31d69e23464f80f740e02cd383fb7e1d
