### ISSUE TITLE
SignalXY: last point sometimes does not get rendered

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3812]
Perhaps because a binning issue?
![sigxylast](https://github.com/ScottPlot/ScottPlot/assets/4165489/fe13f7f8-ec59-4a7a-b727-6e657cb92166)

**Comment by swharden** [comment]
This is reproducible and only affects "high density mode"

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        int count = 1000;
        double[] xs = Generate.Consecutive(count);
        double[] ys = Generate.RandomWalk(count);
        ys[^1] = -100;

        formsPlot1.Plot.Add.SignalXY(xs, ys);
    }
}
```

**Comment by swharden** [comment]
Interestingly, it's only the very last point, and only about half the frames. It "flickers" as you zoom horizontally.

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/2c3a9ad7-45c3-4c7d-af65-fa89d23b3edd)

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        int count = 1000;
        double[] xs = Generate.Consecutive(count);
        double[] ys = Generate.RandomWalk(count);
        ys[0] = -100;
        ys[499] = -100;
        ys[999] = -100;

        var sig = formsPlot1.Plot.Add.SignalXY(xs, ys);
        sig.MarkerShape = MarkerShape.OpenCircle;
        sig.MarkerColor = Colors.Black;
        sig.MarkerSize = 10;
    }
}
```

**Comment by swharden** [comment]
I'm pretty sure the issue is in here

https://github.com/ScottPlot/ScottPlot/blob/6468dbe93b7cb5dd686183cc0329d1f93fed35b9/src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs#L156-L187

**Comment by swharden** [comment]
I'm thinking the issue is here: https://github.com/ScottPlot/ScottPlot/blob/6468dbe93b7cb5dd686183cc0329d1f93fed35b9/src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs#L170

For the last point, it's possible where the last pixel column contains a single value, so start and stop index positions will be the same

**Comment by BrianAtZetica** [comment]
This fix introduced a bug with rotated SignalXY plots that can be demonstrated with the following code (I'm using the WPF Sandbox here):

'''

        InitializeComponent();

        var amplitude = Generate.Sin();
        double[] time = new double[51];
        for (int i = 0; i < time.Length; i++)
            time[i] = i;

        var signal = WpfPlot1.Plot.Add.SignalXY(time, amplitude, color: ScottPlot.Colors.Black);
        signal.Data.Rotated = true;

'''

It looks like the last point (which should be at X = 0, Y = 51, is being plotted without cooridnate rotation (i.e. at X = 51 and Y = 0). 

![image](https://github.com/ScottPlot/ScottPlot/assets/119825052/a8685519-98a2-48d9-9eab-b275a30ba53d)
