### ISSUE TITLE
NumericOperations: zooming too far into DateTime axes throws exception

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3813]
Need to have Zoom-in & Zoom-out functionality to happen / be managed in Button click options:

ScottPlot Version: 5.0.34

By default, whatever zooming functionality is happening in mouse events, that functionality needs to happen / be managed in button click option (i.e., +, -)

I tried the following code, but it works only when buttons are used for zooming. but when zoomed with mouse events and then used the button, it not working

```cs
double val = 1.0;

private void ZoomIn_Click(object sender, EventArgs e)
{
    
    if (val <= 3.5)
    {
        formsPlot1.Plot.Axes.Zoom(val, val);
        formsPlot1.Refresh();
        val = val + 0.1;
    }
}

private void ZoomOut_Click(object sender, EventArgs e)
{
    if (val > 1.1)
    {
        val = val - 0.1;
         formsPlot1.Plot.Axes.ZoomOut(val, val);
        formsPlot1.Refresh();
       
    }

}
```

**Comment by swharden** [comment]
Hi @kareem469, I may not understand the issue here. 

Is your question "how do I enable `+` and `-` keys to zoom in and out"?

> I tried the following code, but it works only when buttons are used for zooming. but when zoomed with mouse events and then used the button, it not working

This is the part I'm uncertain about

**Comment by kareem469** [comment]
Hi @swharden 

My query is, I want to give provision to the user to use zoomin & zoom-out buttons instead of using mouse events (right & left clicks)

**Comment by KennyTK** [comment]
Hi @kareem469,
```formsPlot1.Plot.Axes.Zoom``` and ```formsPlot1.Plot.Axes.ZoomOut``` are two different functions with slightly different purposes. Could you try using only one or the other and testing?

**Comment by kareem469** [comment]
Hi @KennyTK 

I required both zoomin & zoom out functionality in two different buttons.

And also I want to get the current zoom factor.

**Comment by kareem469** [comment]
Hi @swharden, 

How to get the current zoom factor when zoomed in or out with default mouse events. So that i will use that zoom factor to zoom in or out functionality manually in buttons.

**Comment by kareem469** [comment]
> Reference
???

**Comment by swharden** [comment]
Hi @kareem469, please do not abuse the notification system by posting unnecessary messages (or using @ excessively, especially for when tagging GitHub users who are not even owners of this project)

I really appreciate [KennyTK](https://github.com/KennyTK)'s suggestion in https://github.com/ScottPlot/ScottPlot/issues/3813#issuecomment-2101324495 ❤️  I think that understanding of how `Zoom()` differs from `ZoomOut()` may help you arrive at a solution!

I will leave this issue open until I am able to share a code demonstration for how to zoom in and out with keyboard keys. However, note that I typically respond to messages from my phone so code examples are difficult, and when I am by a computer I prioritize [high priority issues](https://github.com/ScottPlot/ScottPlot/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E2%9A%A0%EF%B8%8F+HIGH+PRIORITY%22) from oldest to newest, so it may take some time before I'm able to address all of these questions 👍

**Comment by swharden** [comment]
Hi @kareem469, thanks for reporting this! I'm going to rename this issue to track fixing this datetime-related bug

**Comment by swharden** [comment]
Following-up, I don't think there's a bug here. When I create an app and give it a DateTime axis, I can zoom out infinitely with no problem.

Like Kenny said, I think the issue is a misunderstanding of now `ZoomIn()` and `ZoomOut()` arguments function.

To make this more discoverable in the future I'm going to throw exceptions immediately if zoom methods are called with zoom factors which are not greater than zero.
