### ISSUE TITLE
Need to set the fixed width for all the graphs irrespective of the Y1 & Y2 axis

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3816]
**Not having the fixed widths and alignment for all the graphs if the graphs contains different Y1 & Y2 axis:**

**ScottPlot Version:5.0.34** (What NuGet package are you using?)

Need to set the fixed width for all the graphs irrespective of the Y1 & Y2 axis

Enclosed the image in which the graphs alignments are not proper

![Grpah](https://github.com/ScottPlot/ScottPlot/assets/101133645/251ea257-260b-4e1e-8b3a-1301fdb91994)

**Comment by swharden** [comment]
See https://scottplot.net/demo/#shared-axes for how to match layouts across controls

**Comment by swharden** [comment]
Hi @kareem469, I don't see any labels cut off in your screenshot.

Note that you can set minimum size for axes if you need more space for large labels, as seen here https://scottplot.net/cookbook/5.0/CustomizingTicks/RotatedTicksLongLabels/

**Comment by kareem469** [comment]
Hi @swharden 

Check the below image 
![Untitled](https://github.com/ScottPlot/ScottPlot/assets/101133645/a90045a1-eaf0-4998-9314-5cc9e959da7c)

**Comment by swharden** [comment]
Thanks for the clarification!

```cs
formsPlot1.Plot.Axes.Bottom.MinimumSize = 50;
formsPlot2.Plot.Axes.Bottom.MinimumSize = 50;
formsPlot3.Plot.Axes.Bottom.MinimumSize = 50;
formsPlot4.Plot.Axes.Bottom.MinimumSize = 50;
``

**Comment by swharden** [comment]
`50` may be too large, but you get the idea 👍

**Comment by kareem469** [comment]
Yup, i got it 👍

**Comment by kareem469** [comment]
In the above image, i want to cutdown the gap between the graphs. 

I tried to set the Top of each graph but the second graph is sendtoback and cutdown. Same for all the below graphs. how to achive this?

**Comment by kareem469** [comment]
> Hi @kareem469, for the middle controls you can:
> 
> ```cs
> formsPlot1.Plot.Axes.Top.IsVisible = false;
> formsPlot1.Plot.Axes.Bottom.IsVisible = false;
> ```
> 
> and it should collapse the space between the top of one plot and the bottom of another.

I tired as per the suggestion, but still there is space between the graphs.

**Comment by kareem469** [comment]
> > Hi @kareem469, for the middle controls you can:
> > ```cs
> > formsPlot1.Plot.Axes.Top.IsVisible = false;
> > formsPlot1.Plot.Axes.Bottom.IsVisible = false;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and it should collapse the space between the top of one plot and the bottom of another.
> 
> I tired as per the suggestion, but still there is space between the graphs.

Hi @swharden, 

Need your help, unable to fix this issue

**Comment by swharden** [comment]
Is it because there is space between the controls when you drag and drop them using the designer? Does placing them inside a table solve your problem?

**Comment by swharden** [comment]
This worked for me. I put 3 FormsPlot controls inside a table and set margins for all of them to 0 using the visual designer

```cs
using ScottPlot;

namespace WinFormsApp1;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        formsPlot1.Plot.Add.Signal(Generate.Sin());
        formsPlot1.Plot.Axes.Bottom.IsVisible = false;

        formsPlot2.Plot.Add.Signal(Generate.Sin());
        formsPlot2.Plot.Axes.Top.IsVisible = false;
        formsPlot2.Plot.Axes.Title.IsVisible = false;
        formsPlot2.Plot.Axes.Bottom.IsVisible = false;

        formsPlot3.Plot.Add.Signal(Generate.Sin());
        formsPlot3.Plot.Axes.Top.IsVisible = false;
        formsPlot3.Plot.Axes.Title.IsVisible = false;
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/373246af-4095-4364-b46e-31fcccb6df75)

**Comment by kareem469** [comment]
I am not getting the alignment as there in the below image. I have used the tablelayoutpanel added the graphs and also set the margins to 0 and set the bottom & top visibility. But still thers is a gap and also the y axis bottom is cutdown little bit


![g1](https://github.com/ScottPlot/ScottPlot/assets/101133645/a09be2cd-e4f5-4b6c-b5e3-8b96a49ddbf6)

**Comment by swharden** [comment]
Hi @kareem469, it sounds like you're getting closer. You are correct to point out that if you have no padding, ticks near the edge will roll off the screen. A solution is to manually place ticks https://scottplot.net/cookbook/5.0/CustomizingTicks/CustomTicks/

I created a high priority issue #3868 to track adding a feature to disallow tick labels a certain number of pixels away from the edge of the data area to make this easier to achieve in the future

**Comment by swharden** [comment]
Following-up, this is presently possible using the existing library:

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        // make ticks go right to the edge of the plot
        formsPlot1.Plot.Axes.Top.IsVisible = false;
        formsPlot1.Plot.Axes.Right.IsVisible = false;

        // make tick labels large to maximize the effect
        formsPlot1.Plot.Axes.Left.TickLabelStyle.FontSize = 24;

        // remove ticks too close to the edge of the plot at the start of each render
        formsPlot1.Plot.RenderManager.RenderStarting += (object? s, RenderPack rp) =>
        {
            // determine the positions where ticks are allowed
            float minDistanceBetweenTickAndTop = 25;
            double maxTickValue = formsPlot1.Plot.Axes.Left.GetCoordinate(minDistanceBetweenTickAndTop, rp.DataRect);
            float minDistanceBetweenTickAndBottom = 25;
            double minTickValue = formsPlot1.Plot.Axes.Left.GetCoordinate(rp.DataRect.Height - minDistanceBetweenTickAndBottom, rp.DataRect);
            CoordinateRange allowedTickRange = new(minTickValue, maxTickValue);

            // remove text from ticks outside the allowed range
            for (int i = 0; i < formsPlot1.Plot.Axes.Left.TickGenerator.Ticks.Length; i++)
            {
                Tick tick = formsPlot1.Plot.Axes.Left.TickGenerator.Ticks[i];
                if (string.IsNullOrEmpty(tick.Label)) continue;
                if (allowedTickRange.Contains(tick.Position)) continue;
                formsPlot1.Plot.Axes.Left.TickGenerator.Ticks[i] = Tick.Major(tick.Position, string.Empty);
            }
        };
    }
}
```

![tick-scroll-off](https://github.com/ScottPlot/ScottPlot/assets/4165489/1de4ad6c-44b8-497f-b41d-adf7da14b532)
