### ISSUE TITLE
FormsPlot: `MouseEnter` and `MouseLeave` events not getting fired

### ISSUE THREAD

**Issue by CD-SailingPerf** [ScottPlot/ScottPlot#3819]
**Issue:**
MouseEnter and MouseLeave events not getting fired.
This may have worked at some point according to this issue, but it now seems broken.
[https://github.com/ScottPlot/ScottPlot/issues/999](https://github.com/ScottPlot/ScottPlot/issues/999)

**ScottPlot Version:** 5.0.34

**Code Sample:** 
```cs
            ScottPlot.WinForms.FormsPlot frmPl = new ScottPlot.WinForms.FormsPlot();
            this.Controls.Add(frmPl);
            frmPl.Dock = System.Windows.Forms.DockStyle.Fill;
            frmPl.MouseEnter += (s, ev) =>
            {
                MessageBox.Show("Mouse enter");
            };
            frmPl.MouseLeave += (s, ev) =>
            {
                MessageBox.Show("Mouse leave");
            };
            frmPl.Refresh();
```

**Comment by swharden** [comment]
Related: #3890

**Comment by swharden** [comment]
Rather than forward all the events, I'm going to expose the `SKControl` so users can add handlers to its mouse events. In the next release this will work:

```cs
if (formsPlot1.SKControl is not null)
{
    formsPlot1.SKControl.MouseEnter += (s, e) =>
    {
        Text = "Mouse enter";
    };

    formsPlot1.SKControl.MouseLeave += (s, e) =>
    {
        Text = "Mouse leave";
    };
}
```

**Comment by brucewedding** [comment]
Just in time. I literally came here to report this. I'm using it to turn the crosshairs off and on. Previously, they would just "stick" wherever they were when the mouse left the plot, leaving an annoying horizontal line.

**Comment by DaveMartel** [comment]
This is marked as closed, but as far as I can see it is still not fixed. I am on the latest release (WinForms and Windows 11).

I see that SKControl is exposed, but I can not seem to bind the mouse events to it.

Any help gratefully accepted
