### ISSUE TITLE
Sandbox: create example projects for ASP .NET (minimal API) and Blazor server

### ISSUE THREAD

**Issue by sazus** [ScottPlot/ScottPlot#3824]
### **Question:**
so I try for adding custom font using the below method in web assembly on blazor.

`ScottPlot.StylersFontStyler.Set(string fontName)`

but it doesn't seem to load the proper font.

Checking developer tool on the browser, I see an interesting situation.

1. The HTML Section Heading elements(H3) set in the razor file are being rendered with the appropriately specified font.([fig1](https://github.com/ScottPlot/ScottPlot/assets/1256304/23e0fe4d-be94-4a26-b677-29a29caa8fa8))

2. ScottPlot's components in the razor file , It only seem to support the `Noto Mono` font.([fig2](https://github.com/ScottPlot/ScottPlot/assets/1256304/6a43b794-347c-4369-86e7-eb4303a5e8ab))
    (ScottPlot component div elements have the appropriate font-family.)

I have implemented a small code using the ScottPlot project's Sandbox -Sandbox.Blazor.WebAssembly.
Please let us know if we are missing any necessary steps to properly pass fonts to ScottPlot components.

**(fig1)**
<img width="500" alt="fig1" src="https://github.com/ScottPlot/ScottPlot/assets/1256304/23e0fe4d-be94-4a26-b677-29a29caa8fa8">
**(fig2)**
<img width="500" alt="fig2" src="https://github.com/ScottPlot/ScottPlot/assets/1256304/6a43b794-347c-4369-86e7-eb4303a5e8ab">

### **ScottPlot Version:** 
- ScottPlot.Blazor v5.0.34
- .NET8.0.0
 
### **Code Sample:**
Small changed at `src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Blazor.WebAssembly/Pages/Quickstart.razor`

```c#
@page "/"
@page "/quickstart"

@using System.Diagnostics
@using System.Reflection
@using System.Xml.Linq
@inject IRecipesService RecipeService

<div class="container">
    <h3>ScottPlot Blazor Quickstart</h3>
    <h3>スコットプロット クイックスタート</h3>
    <div><a href="https://scottplot.net/quickstart/blazor/">https://scottplot.net/quickstart/blazor/</a></div>

    /// Add Scottplot components HERE
    <BlazorPlot @ref="BlazorPlot" Style="width: 600px; height: 400px;" />
</div>

@code {
    BlazorPlot BlazorPlot = new();

    protected override void OnAfterRender(bool firstRender)
    {
        var plot = BlazorPlot.Plot;
　　
        /// Set custom font on ScottPlot
        plot.Font.Set("Noto Sans JP");

        /// Check current font family at componets
        var fontList = string.Join(", ", SkiaSharp.SKFontManager.Default.GetFontFamilies());
        plot.Add.Text("Get font-family lists : " + fontList.ToString(), 10, 10);

        if (firstRender)
        {
            plot.Add.Signal(Generate.Sin());
            plot.Add.Signal(Generate.Cos());

            /// custom fonts are not available and displayed as blank paper
            plot.Title("スコットプロット");
            plot.Font.Automatic();
        }
        base.OnAfterRender(firstRender);
    }
}
```
---
Small changed at `src/ScottPlot5/ScottPlot5 Sandbox/Sandbox.Blazor.WebAssembly/wwwroot/css/app.css`

```Diff

 ?@import url('open-iconic/font/css/open-iconic-bootstrap.min.css');
 + 
 + @font-face {
 +     font-family: 'Noto Sans JP';
 +     src: url('../fonts/NotoSansJP-Thin.ttf');
 + }
   
   html, body {
 -     font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
 +     font-family: 'Noto Sans JP', Helvetica, Arial, sans-serif;
   }
   
   h1:focus {

```

**Comment by aespitia** [comment]
just to confirm, that font is installed on whatever server you're deploying on?  also, if you're installing on a server, you have to make sure to install the font as an admin, and select "install for all users"

**Comment by sazus** [comment]
We are currently running Blazor on the same server/client PC.
On the executing PC, I also install the font as an admin and select "install for all users" .

When running on wasm, I can't seem to get the fonts on the executing PC.
I think the best solution is to be able to use `@font-face` or `font-family` fonts defined on css.

**Comment by aespitia** [comment]
in my instance, i guess i'm generating the image server side, and then serving the image itself

**Comment by swharden** [comment]
I'm going to repurpose this issue to track adding a sandbox app to the main project that demonstrates how to use ScottPlot in server-side projects: ASP .NET (a minimal API that serves a PNG would be cool) and Blazor Server.

Once those projects are in place we can figure out how to use fonts installed on the server to generate those images.

**Comment by swharden** [comment]
> i'd be happy to put something together, since i already have the code for it, since this is how I use SP5 anyway (with angular)

Awesome! Any sandbox projects you are able to contribute would be fantastic. I don't use .NET too much for webby stuff, so I really value contributions from people who are more familiar with idiomatic project structure.

**Comment by sazus** [comment]
> i'd be happy to put something together, since i already have the code for it, since this is how I use SP5 anyway (with angular)

Thank you for your feedback and support.
so I just recently started learning with Blazor, the sandbox project creation is very helpful.

@aespitia 
If I can get some of your knowledge about Blazor, I may be able to contribute to this project in various ways.

**Comment by aespitia** [comment]
PR submitted.

https://github.com/ScottPlot/ScottPlot/pull/3959

**Comment by sazus** [comment]
@aespitia 

Thanks for PR.

Is it possible to render it without converting it to a png file on the server side?

In my application:
- It will bring up a Tooltip by clicking on the plot point.
- And the scrolling the graph. 

I would like to realize above function.

If I want to  realize above function, I want to call it as a component, not as a png file.
Is there no other way but to call it on the client side?

**Comment by aespitia** [comment]
that is interesting, i just use a generated graph in my app, i don't have like a "live stream" application.  i guess you can generate an image and put it in an iframe, then detect the scroll, make an API call and re-render the image with the new parameters?  i don't know, i'm not exactly sure how the regular WPF application works, since I don't use it that way.

**Comment by swharden** [comment]
A minimal API demo was just added to the quickstart section of the website 🚀 

https://scottplot.net/quickstart/api/

I suspect this information is enough such that Blazor Server users can figure out how to include dynamically generated images in their apps, but feel free to edit that page to add any Blazor-specific notes you think would be helpful 👍
