### ISSUE TITLE
Axes: add support for multiplier and offset notation

### ISSUE THREAD

**Issue by zichen-ye** [ScottPlot/ScottPlot#3827]
**Question:** How do I implement 4.0's TickLabelNotation methods in ScottPlot5.0

**ScottPlot Version:** 5.0

```cs
plot.Plot.YAxis.TickLabelNotation(multiplier: true);
```

**Comment by swharden** [comment]
Hi @zichen-ye, I think you are referring to the little numbers in the corner of the axes indicating an offset and/or multiplier:

https://scottplot.net/cookbook/4.1/recipes/ticks_multiplier/

That feature is not currently in ScottPlot 5, but I'll create an issue to track adding it in 👍

**Comment by EricEzaM** [comment]
While this feature could be added in, IMO it is much simpler just to use a custom tick formatter. As a result, you get far more control over how the ticks are formatted, such as if there is a threshold where scientific notation should be used, how it should be formatted (e.g. lowercase or capital `e`, whether it should be `e+5` or just `e5`, etc), and more.

Here is a sample. In this case, I only render in scientific notation if the largest tick on the plot is above 10,000, and I use C# format strings for the notation; [see docs here](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings).

It does do some unnecessary computation of the `largestTickMagnitude` for every tick, which is inefficient, but this is probably only running less than 20 times per render, so it's fine.

```cs
string CustomFormatter(double position)
{
    if (position == 0)
    {
        return "0";
    }

    var largestTickMagnitude = Math.Max(Math.Abs(myPlot.Axes.Left.Range.Min), Math.Abs(myPlot.Axes.Left.Max));
    if (largestTickMagnitude <= 10_000)
    {
        // Too small to require scientific notation
        return position.ToString(CultureInfo.CurrentCulture);
    } 
    
    return $"{position:0.##e0}";;
}
```

https://github.com/ScottPlot/ScottPlot/assets/41730826/e7c92b2f-1911-4875-b827-c024e65d8f84

**Comment by swharden** [comment]
> While this feature could be added in, IMO it is much simpler just to use a custom tick formatter. 

Thanks a great point! Thanks for the example code you shared too.

@zichen-ye is this strategy sufficient to meet your needs?
