### ISSUE TITLE
Cookbook: add recipe showing frameless heatmap

### ISSUE THREAD

**Issue by itsmygam3** [ScottPlot/ScottPlot#3828]
**Question:** For further processing, I need to save the heatmap plot as an image, but when trying to save, white fields are always formed at the edges. How can I fix the code so that I can get an image containing only a graph of a heatmap without extraneous elements?

UPD. At the moment, I found out that the `DataBackground` field from `BackgroundStyle` class is responsible for this frame. I was able to change its color, but I need to completely exclude it.
![image](https://github.com/ScottPlot/ScottPlot/assets/33595058/e10c2fe0-1b56-4178-a9b3-9d533852935b)

**ScottPlot Version:** 5.0.34

**Code Sample:**

```cs
double[,] data = { { 1, 2, 3 }, { 4, 5, 6 }, { 7, 8, 9 } };

formsPlot1.Plot.HideGrid();
formsPlot1.Plot.Layout.Frameless();
formsPlot1.Plot.Add.Heatmap(data);
formsPlot1.Plot.SaveJpeg("bord.jpg", 400, 400);

panel1.Controls.Add(formsPlot1);
```

**Comment by swharden** [comment]
Thanks for reporting this @itsmygam3! I suspect this issue relates to axes taking several pixels even though frameless is enabled, but an not 100% sure yet. I'll take a look at this eventually, but if someone from the open source community is able to take a closer look first and creates a PR to fix the problem, I will be happy to review and merge it in good time 👍

**Comment by swharden** [comment]
I confirmed this is a heatmap issue (not an axis padding issue) because setting the data area background color shows the heatmap is not filling the whole data area

```cs
double[,] data = { { 1, 2, 3 }, { 4, 5, 6 }, { 7, 8, 9 } };

ScottPlot.Plot plot = new();
plot.DataBackground.Color = ScottPlot.Colors.Magenta;
plot.Add.Heatmap(data);
plot.Layout.Frameless();
plot.SaveJpeg("bord.jpg", 400, 400).LaunchFile();
```

![bord](https://github.com/ScottPlot/ScottPlot/assets/4165489/883967e2-5959-4ccf-964d-29bc63f66e74)

**Comment by swharden** [comment]
Actually, I figured it out! Plots have a little bit of padding (margins) around the data area by deafault. Disabling this gets the functionality you're seeking:

```cs
double[,] data = { { 1, 2, 3 }, { 4, 5, 6 }, { 7, 8, 9 } };

ScottPlot.Plot plot = new();
plot.DataBackground.Color = ScottPlot.Colors.Magenta;
plot.Axes.Margins(0, 0); // <------ SET MARGIN TO ZERO
plot.Add.Heatmap(data);
plot.Layout.Frameless();
plot.SaveJpeg("bord.jpg", 400, 400).LaunchFile();
```

![bord](https://github.com/ScottPlot/ScottPlot/assets/4165489/5d066eb3-5e48-42d3-bd35-6dab592fdeff)

I'll leave this issue open to track adding an example to the cookbook
