### ISSUE TITLE
Legend: rendering text labels resets custom typefaces

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3830]
https://github.com/ScottPlot/ScottPlot/discussions/3825#discussioncomment-9433290

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/2958e6e8-2966-46f7-87cf-8f17040e8591)

**Comment by swharden** [comment]
Hi @lasooch, thanks again for suggesting this feature. It has been added in #4043 and will be available in the next release

```cs
SKTypeface customTypeface = SKTypeface.FromFile(ttfFilePath);

plot.Legend.ManualItems.Add(new LegendItem()
{
    LabelText = "Manual Item",
    LabelFontColor = Colors.Blue,
    LabelFontSize = 26,
    LabelTypeface = customTypeface,
});
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/08bc1ec0-8407-49c6-b6f3-a56ce28a3160)

**Comment by lasooch** [comment]
Thank you very much @swharden.
