### ISSUE TITLE
ScatterPlot narrows the horizontal display range coordinate names overlapping issue

### ISSUE THREAD

**Issue by minchen123** [ScottPlot/ScottPlot#3832]
**Question:** (Narrow down the landscape display, and if there is a lot of data, the tick names on the X-axis will overlap,This is also the case in official examples)

**ScottPlot Version:** (4.1.69)

**Code Sample:** 

```cs
double[] dataV = new double[ListY.Length];
double[] yArr = new double[ListY.Length];


ScatterPlot V_ScatterPlot = null;
V_ScatterPlot = V_Plot.Plot.AddScatter(dataV, yArr, Color.Red, 2, markerSize: 2);
V_ScatterPlot.OnNaN = ScatterPlot.NanBehavior.Gap;
V_Plot.Refresh();

```

![20240515102841](https://github.com/ScottPlot/ScottPlot/assets/3364674/275184f7-ff10-4e03-8883-0c7264690177)

**Comment by swharden** [comment]
It looks like this issue relates to ScottPlot 4 which is no longer a target for active development, so I'll close this issue. If someone fixes this and creates a pull request, I'd be happy to review it though 👍

**Comment by swharden** [comment]
Confirmed ScottPlot 5 does not have this issue

![3832](https://github.com/user-attachments/assets/028fa7c7-bd48-4ea4-88bf-62d3cd4932f6)
