### ISSUE TITLE
Vertical line: label text position is incorrect

### ISSUE THREAD

**Issue by VibrationAnalystCN** [ScottPlot/ScottPlot#3836]
**Issue:** (The position of LabelText on the X-axis is incorrect in version 5.0.32/33/34, which was correct in version 5.0.31 and previous versions.)

**ScottPlot Version:** (5.0.32)

```cs
        private static void AddVerticalLine(WpfPlot plot, string model, string type, double freq, Color color)
        {
            var vLine = plot.Plot.Add.VerticalLine(freq, 1, color, LinePattern.Dashed);
            vLine.LabelFontColor = Color.FromARGB(0xC0000000);
            vLine.LabelBorderColor = color;
            vLine.LabelBackgroundColor = Colors.Transparent;
            vLine.LabelText = $"{model} {type}={Math.Round(freq, 3)}Hz"; // Label the line with its position
            vLine.LabelRotation = -90;
            vLine.LabelAlignment = Alignment.MiddleRight;
            vLine.LabelOffsetX = -20;
            vLine.LabelOffsetY = -250;
        }
```
![Plot-5 0 31](https://github.com/ScottPlot/ScottPlot/assets/165245736/fe466eab-a90c-4779-8dbe-f384735703f4)
![Plot-5 0 32](https://github.com/ScottPlot/ScottPlot/assets/165245736/0d352835-8ce3-42bc-94c8-198b4cec4a29)
![Plot-5 0 32-scaleTheX](https://github.com/ScottPlot/ScottPlot/assets/165245736/b4e5bfa8-3876-4909-bbba-e81ecebac8b3)

**Comment by swharden** [comment]
Hi @VibrationAnalystCN, thanks for reporting this!

I suspect it has been fixed in one of the recent merges and will be in the next release. If not, we can re-open this issue and take a closer look 👍 

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        for (int i=0; i< 5; i++)
        {
            var vLine = formsPlot1.Plot.Add.VerticalLine(i, pattern: LinePattern.Dashed);
            vLine.LabelFontColor = Colors.Black;
            vLine.LabelBorderColor = Colors.Black;
            vLine.LabelBackgroundColor = Colors.Gray;
            vLine.LabelText = $"Hello, World!";
            vLine.LabelRotation = -90;
            vLine.LabelOffsetY = -250;
            vLine.LabelOffsetX = -20;
        }
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/6bd7fb3b-da9d-4144-8e95-9cbe81417627)

**Comment by VibrationAnalystCN** [comment]
HI @swharden ,  Thank you for your work, Looking forward to the next version.
