### ISSUE TITLE
SP4: WpfPlot Background Not Setting After Version 4.1.63

### ISSUE THREAD

**Issue by hhuang2013** [ScottPlot/ScottPlot#3837]
**Issue:** WpfPlot Background always keep transparent

**ScottPlot Version:** from 4.1.63

**Code Sample:**

```xaml
    <Grid Background="DarkGray">
        <WpfPlot x:Name="plot" Background="LightCoral" />
    </Grid>
```
 #### With version 4.1.62, the background of WpfPlot is displayed in the specified color (LightCoral in this example).
![image](https://github.com/ScottPlot/ScottPlot/assets/27619643/dc5fa16f-959d-4665-955b-585b9b84604b)

#### After updating to version 4.1.63, setting the Background property no longer affects the plot's background. It remains transparent regardless of the color set. DarkGray is its container's corlor.
![image](https://github.com/ScottPlot/ScottPlot/assets/27619643/d70b69a9-0387-414f-9274-2137ec70fefb)

**Comment by swharden** [comment]
Hi @hhuang2013, it should work if you:

```cs
plot.Plot.Style(figureBackground: Color.LightCoral);
```

See https://scottplot.net/cookbook/4.1/recipes/style_background/

**Comment by hhuang2013** [comment]
Hi @swharden, thanks. 

Yes, ScottPlot.Plot offers background customization for both figures and data. 

However, I'm encountering an issue with WpfPlot specifically. After converting the UserControl to a CustomControl, setting the background property on the WpfPlot doesn't seem to have any effect. It remains transparent regardless of the color I choose.

As a workaround, we can set the background of the container element that holds the WpfPlot control.
