### ISSUE TITLE
Gaps in DateTime cause a problem with Financial plots

### ISSUE THREAD

**Issue by CBrauer** [ScottPlot/ScottPlot#3840]
**Issue:** 
In the real world, financial trade data is usually random in time.
To convert such data to a Time Series that we can work with, we put the data into bins.
This may cause a problem. Gaps of undefined data!

**ScottPlot Version:**
ScottPlot (5.0.34)

**Code Sample:** 
Here is an example that works.  No gaps.
```
public partial class Form1 : Form
{
    readonly ScottPlot.WinForms.FormsPlot formsPlot = new() { Dock = DockStyle.Fill };
    public Form1()
    {
        InitializeComponent();

        formsPlotPanel.Controls.Add(formsPlot);
        DrawCandleChart("FuBar", 20);
    }
    public void DrawCandleChart(string symbol, int n)
    {
        var endDate = DateTime.Now;
        var startDate = endDate.AddDays(-n);
        List<OHLC> ohlcList = Generate.RandomOHLCs(n, startDate);

        // ohlcList[0] = new OHLC(0.0, 0.0, 0.0, 0.0);

        formsPlot.Plot.ScaleFactor = 2;
        formsPlot.Plot.Clear();
        formsPlot.Refresh();

        var candlePlot = formsPlot.Plot.Add.Candlestick(ohlcList);
        candlePlot.Axes.YAxis = formsPlot.Plot.Axes.Right;

        formsPlot.Plot.Axes.DateTimeTicksBottom();

        formsPlot.Plot.Axes.Bottom.Label.Text = symbol;
        formsPlot.Plot.Axes.Bottom.Label.FontName = "Verdana";
        formsPlot.Plot.Axes.Bottom.Label.Bold = false;
        formsPlot.Plot.Axes.Bottom.Label.FontSize = 12;

        formsPlot.Plot.Axes.AutoScale();
        formsPlot.Refresh();
    }
}
```
Here is what the above code produces:
![good](https://github.com/ScottPlot/ScottPlot/assets/1317234/58fe7237-586b-4ec1-b895-9d20e1c69b8f)

Now, uncomment the line: "// ohlcList[0] = new OHLC(0.0, 0.0, 0.0, 0.0);" to produce a gap.
This ressults in:

![bad](https://github.com/ScottPlot/ScottPlot/assets/1317234/9e728dba-8e4c-400e-b053-507f091e92b7)

Please update Cookbook 5 with "How to Plot DateTime Data with Gaps"

Charles

**Comment by swharden** [comment]
Thanks for reporting this @CBrauer! See https://scottplot.net/cookbook/5.0/Finance/FinancialPlotWithoutGaps/ for an example of how to display financial on a non-linear horizontal axis (data without time gaps)

**Comment by swharden** [comment]
Also note that `new OHLC(0.0, 0.0, 0.0, 0.0);` creates an OHLC with the date of Jan 1, 1900. Considering this, I believe the screenshots you posted are the expected behavior.

I think the link above is enough to solve this issue. If not, let me know and we can open this up again and take a closer look 👍
