### ISSUE TITLE
Colorbar: add support for custom tick formatter

### ISSUE THREAD

**Issue by mawbydp** [ScottPlot/ScottPlot#3844]
**Suggestion:**
Add ability to define how the value of the tick marks on a color bar are displayed. 
For example with very large values (10^15+) the labels do not always display properly. It would be good to be able to define the string format for these ticks. 

For example:
```cs
tickLabel= tickValue.ToString("+0.000e00; -0.000e00")
```

![image](https://github.com/ScottPlot/ScottPlot/assets/91740023/e750923d-d69d-47d7-bb8c-8f9f4805fe4f)

**Comment by swharden** [comment]
Hi @mawbydp, thanks for this question! I went to implement this feature and discovered it was already possible so I added a cookbook example:

```cs
double[,] data = SampleData.MonaLisa();

var hm = myPlot.Add.Heatmap(data);
var cb = myPlot.Add.ColorBar(hm);

// create a static function containing the string formatting logic
static string CustomFormatter(double position)
{
    return $"{Math.Round(position / 2.55)} %";
}

// create a custom tick generator using your custom label formatter
ScottPlot.TickGenerators.NumericAutomatic myTickGenerator = new()
{
    LabelFormatter = CustomFormatter
};

// tell the colorbar to use the custom tick generator
cb.Axis.TickGenerator = myTickGenerator;
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/252af79a-face-40b1-9007-be3106489866)
