### ISSUE TITLE
[SP5] ScottPlot.Fonts initializatior has thrown an exception

### ISSUE THREAD

**Issue by cataclism** [ScottPlot/ScottPlot#3848]
I'm developing a Console Library Application using ScottPlot5 and .NETFramework 4.6.2.

If i run my application inside VS as a Windows Application I have no problem.

However when I switch to Class Library to include it as a plugin inside an application i get this error as soon as I try to access the code that uses ScottPlot 5.0.34.

I am using windows and the application in which I want to include it is running in Windows.

I've installed ScottPlot through NuGet.

Inside the references of my project I have this reference that has a warning and I don't know why
![image](https://github.com/ScottPlot/ScottPlot/assets/69798041/7cf9766a-f4bf-42c7-bc01-6cb3a577eb84)

Moreover under packages I have 
![image](https://github.com/ScottPlot/ScottPlot/assets/69798041/64e53871-2afd-4c97-a450-0f3b75db48d3)

and I've changed the properties of SkiaShart.dll to 
![image](https://github.com/ScottPlot/ScottPlot/assets/69798041/3b344d0f-d6a5-40f0-bc2b-0b3e37410065)
but it doesn't help.

**ScottPlot Version:** 5.0.34```

This is what the application in which i want to run the plugin into tells me:

```
************** Testo dell'eccezione **************
System.TypeInitializationException: L'inizializzatore di tipo di 'ScottPlot.Fonts' ha generato un'eccezione. ---> System.TypeInitializationException: L'inizializzatore di tipo di 'SkiaSharp.SKTypeface' ha generato un'eccezione. ---> System.DllNotFoundException: Unable to load library 'libSkiaSharp'.
   in SkiaSharp.LibraryLoader.LoadLocalLibrary[T](String libraryName)
   in System.Lazy`1.CreateValue()
   in System.Lazy`1.LazyInitValue()
   in SkiaSharp.SkiaApi.sk_typeface_ref_default()
   in SkiaSharp.SKTypeface..cctor()
   --- Fine della traccia dello stack dell'eccezione interna ---
   in SkiaSharp.SKTypeface.get_Default()
   in ScottPlot.Fonts.InstalledSansFont()
   in ScottPlot.Fonts..cctor()
   --- Fine della traccia dello stack dell'eccezione interna ---
   in ScottPlot.Label..ctor()
   in ScottPlot.Plottables.Benchmark..ctor()
   in ScottPlot.Plot..ctor()
   in ScottPlot.WinForms.FormsPlotBase..ctor()
   in ScottPlot.WinForms.FormsPlot..ctor()
```

**Comment by swharden** [comment]
> If i run my application inside VS as a Windows Application I have no problem. However when I switch to Class Library to include it as a plugin inside an application i get this error

Hi @cataclism, thanks for reporting this! Without having access to the code of your full application, it's hard to troubleshoot this error. Consider installing the https://www.nuget.org/packages/SkiaSharp.Views.WindowsForms/ package in your "larger app", and maybe that will solve the problem?

**Comment by swharden** [comment]
> What I had to do is to manually copy the libSkiaSharp.dll inside the root folder of the application and by doing so it works.

Thanks for sharing the solution you found! I'm glad you got it working, and hopefully others may benefit from this conversation in the future 👍

**Comment by darfdm** [comment]
Where can I find the libSkiaSharp.dll?
