### ISSUE TITLE
Signal: GetNearest() is slower than expected

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3849]
### Discussed in https://github.com/ScottPlot/ScottPlot/discussions/3847

<div type='discussions-op-text'>

<sup>Originally posted by **Lelick-PMR** May 19, 2024</sup>
Hi all! Firstly, I want to thank the author for the great work done!
Secondly I want to apologize for my English. I write with translator!
Thirdly, I'm not a programmer! But, I urgently needed a program to display graphs from a log file.

I started studying BC Winforms C# + ScottPlot, since ScottPlot is faster than its competitors.

I didn’t know what to choose SP 4 or SP 5?

I decided to try both versions!
**ScottPlot 4**
I used the code from here [#1762](https://github.com/ScottPlot/ScottPlot/discussions/1762)
modifying it a little 
Here's a video, it works great!

https://github.com/ScottPlot/ScottPlot/assets/7281848/5fc3f621-ecb2-4fb6-b6c5-4b8be37f4809

**ScottPlot 5**
I used the code from here [SignalXYDrag.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/SignalXYDrag.cs)
modifying it a little
here's a video, it's slow

https://github.com/ScottPlot/ScottPlot/assets/7281848/450f4a50-66ef-4853-9cca-1ecd3bc9fc0e

```cs
        private void formsPlot1_MouseMove(object? sender, MouseEventArgs e)
        {

            (var signalUnderMouse, DataPoint dp) = GetSignalXYUnderMouse(formsPlot1.Plot, e.X, e.Y); 
                //Cursor = signalUnderMouse is null ? Cursors.Arrow : Cursors.SizeWE;
                HighlightedPoint.IsVisible = signalUnderMouse is not null;

                if (signalUnderMouse is not null)
                {
                    HighlightedPoint.Axes = signalUnderMouse.Axes ;
                    HighlightedPoint.Location = dp.Coordinates;
                    HighlightedPoint.Color = signalUnderMouse.Color;
                    formsPlot1.Plot.Title($"Index {dp.Index} at {dp.Coordinates} ");
                    formsPlot1.Refresh();
                }

                return;

        }

        private (SignalXY? signalXY, DataPoint point) GetSignalXYUnderMouse(Plot plot, double x, double y)
        {
            Pixel mousePixel = new(x, y);

            // --Coordinates mouseLocation = signal.Axes.GetCoordinates(mousePixel);

            foreach (SignalXY signal in plot.GetPlottables<SignalXY>().Reverse())
            {
                Coordinates mouseLocation = signal.Axes.GetCoordinates(mousePixel);

                DataPoint nearest = signal.GetNearest(mouseLocation, formsPlot1.Plot.LastRender);
                if (nearest.IsReal)
                {
                    return (signal, nearest);
                }
            }

            return (null, DataPoint.None);
        }
```

**how can I speed up SP 5 like SP 4?** Thanks!</div>

**Comment by StendProg** [comment]
- ScottPlot5 example uses GetPointNearest**XY**(). It looks for the nearest point on the plane. This can't be solved faster than a full search of the entire array.
- ScottPlot4 example uses GetPointNearest**X**(). It looks for the nearest point on the X axis only. This problem can be solved using a binary search for O(log(N)).

If searching only the X-axis is enough, you can look up the implementation here:
https://github.com/ScottPlot/ScottPlot/blob/d186b6013c098fbb13c9fa35fd84dfffa4450a61/src/ScottPlot4/ScottPlot/Plottable/SignalPlotXYGeneric.cs#L315-L342
