### ISSUE TITLE
New plot type: binary signal

### ISSUE THREAD

**Issue by gzelasco** [ScottPlot/ScottPlot#3851]
Good morning everyone, 

In my WinForms application (NF 4.8, c#) I am using ScottPlot.WinForms for the first time to represent some signals (analog/digital) selected by the user via a treeView Control. I couldn't find any specific suggestions online. I hope I posted the request in the correct place. If not, please let me know where to move it.

**Specifications:**
* In the upper area I must represent the analogue graphs while in the lower one the digital ones for a maximum of 10 signals in total.
* The two graphs must be connected (shared axis) with the possibility of widening/shrinking both axes independently. I noticed that this functionality is natively obtainable by pressing the ALT or CTRL buttons while zooming.
* On the Y axis I have the value of the signals while on the X axis I have a DateTime data (date/time with ms). The sampling of the signal occurs approximately 2/3 times per second.

**Request:**
The question is about digital charts.
How is it possible to represent digital data (binary 0/1)?
I would need to represent it with a step waveform and not a trapezoid. The graph should maintain the previous value (example 0) until it encounters a value of 1 and then rise vertically and not diagonally. At the moment I obviously get a ramp, that is, a line that joins the two points (0/1).
Thank you all for your availability and support.

**ScottPlot Version:** ScottPlot.WinForms 5.0.34

**Code Sample:** 
The example shown is very simple, it represents two signals linked together. 
formsPlot1 will be the analog one while formsPlot2 will be the digital one (which I don't know yet how to represent):

```cs
 private void FillDrawing()
 {
 // plot sample data
 formsPlot1.Plot.Add.Signal(Generate.Sin(51, mult: 1));
 formsPlot2.Plot.Add.Signal(Generate.Sin(51, mult: 100_000));

 // add labels
 formsPlot1.Plot.Axes.Left.Label.Text = "Vertical Axis";
 formsPlot2.Plot.Axes.Left.Label.Text = "Vertical Axis";
 formsPlot1.Plot.Axes.Bottom.Label.Text = "Horizontal Axis";
 formsPlot2.Plot.Axes.Bottom.Label.Text = "Horizontal Axis";

 // use a fixed size for the left axis panel to ensure it's always aligned
 float leftAxisSize = 90;
 formsPlot1.Plot.Axes.Left.MinimumSize = leftAxisSize;
 formsPlot1.Plot.Axes.Left.MaximumSize = leftAxisSize;
 formsPlot2.Plot.Axes.Left.MinimumSize = leftAxisSize;
 formsPlot2.Plot.Axes.Left.MaximumSize = leftAxisSize;

 // when one plot changes update the other plot
 formsPlot1.Plot.RenderManager.AxisLimitsChanged += (s, e) =>
 {
     ApplyLayoutToOtherPlot(formsPlot1, formsPlot2);
 };
 formsPlot2.Plot.RenderManager.AxisLimitsChanged += (s, e) =>
 {
     ApplyLayoutToOtherPlot(formsPlot2, formsPlot1);
 };
 // initial render
 formsPlot1.Refresh();
 formsPlot2.Refresh();
 }

  private void ApplyLayoutToOtherPlot(IPlotControl source, IPlotControl dest)
 {
     AxisLimits axesBefore = dest.Plot.Axes.GetLimits();
     dest.Plot.Axes.SetLimitsX(source.Plot.Axes.GetLimits());
     AxisLimits axesAfter = dest.Plot.Axes.GetLimits();
     if (axesBefore != axesAfter)
     {
         dest.Refresh();
     }
 }
```

**Comment by swharden** [comment]
Hi @gzelasco, this is a pretty advanced issue so I'll leave it open for now and address it more thoroughly in the future. Hopefully the following resources will be useful to you:

> The graph should maintain the previous value (example 0) until it encounters a value of 1 and then rise vertically and not diagonally. At the moment I obviously get a ramp, that is, a line that joins the two points (0/1).

It sounds like you may benefit from creating a _step plot_ https://scottplot.net/cookbook/5.0/Scatter/ScatterStep/

> How is it possible to represent digital data (binary 0/1)?

A step plot is probably a good start, or a SignalXY plot with step display. For advanced control over styling, you can create your own custom plot type for displaying digital signals. https://scottplot.net/faq/custom-plot-type/

Perhaps you (and others) can mimic display styles used by logic analyzer applications. The software from https://www.saleae.com/ is fantastic. If someone from the open source community wishes to create a new plot type specifically for these types of binary signals, I will be happy to review a PR and help along the way!

I'll leave this issue open to track eventual development of this feature, but it's unlikely that I'll create this plot type myself in the near future as I'm currently focusing on the high priority open issues https://github.com/ScottPlot/ScottPlot/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E2%9A%A0%EF%B8%8F+HIGH+PRIORITY%22

Hope it helps!
Scott

**Comment by gzelasco** [comment]
Hi Scott, thank you so much for the very very prompt reply. I will go trying the step plot, as you said is probably a good start. 
I will probably also have to ask you how to set the time value in milliseconds on the X axis (I'm using Ticks) but display labels with complete date (format yyyy-MM-ss HH.mm.ss.fff) maybe with vertical orientation given the size. 
Thank you very much once again, have a nice day!

**Comment by swharden** [comment]
It seems like there hasn't been much movement here so I'll close this issue, but if someone wants to submit a pull request to add this plot type I would be happy to review it in good time 👍
