### ISSUE TITLE
Where is OnNan property in ScottPlot 5?

### ISSUE THREAD

**Issue by MultipleCircles** [ScottPlot/ScottPlot#3854]
**Question:**

I've seen how the "OnNaN" property can be accessed in SP4 (https://github.com/ScottPlot/ScottPlot.NET/blob/main/content/faq/nan.md), but I can't seem to find it anywhere in SP5. Can you help me locate it?

**ScottPlot Version:** 
ScottPlot.WPF 5.0.34

**Code Sample (from SP4):**

```cs
var plt = new ScottPlot.Plot(600, 400);
var scatter1 = plt.AddScatter(xs, ys, Color.Gray);
var scatter2 = plt.AddScatter(xs, ysWithNan, Color.Black);
scatter2.OnNaN = ScottPlot.Plottable.ScatterPlot.NanBehavior.Gap;
```

**Comment by swharden** [comment]
Hi @MultipleCircles, I think this is supported out of the box 👍 

https://scottplot.net/cookbook/5.0/Scatter/ScatterWithGaps/

```cs
ScottPlot.Plot myPlot = new();

double[] xs = Generate.Consecutive(51);
double[] ys = Generate.Sin(51);

// long stretch of empty data
for (int i = 10; i < 20; i++)
    ys[i] = double.NaN;

// single missing data point
ys[30] = double.NaN;

// single floating data point
for (int i = 35; i < 40; i++)
    ys[i] = double.NaN;
for (int i = 40; i < 45; i++)
    ys[i] = double.NaN;

myPlot.Add.Scatter(xs, ys);

myPlot.SavePng("demo.png", 400, 300);
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/f1b3e522-064c-469c-b025-19af59f8a563)
