### ISSUE TITLE
"Show Value On Hover" in plot with multiple scatter traces

### ISSUE THREAD

**Issue by MultipleCircles** [ScottPlot/ScottPlot#3855]
**Question:**

There is a very nice demo of how to use Scatter.Data.GetNearest() to get the nearest point from a single scatter trace in a plot here:
https://github.com/ScottPlot/ScottPlot/issues/3026

Would it be possible to get a demo of how to do the same when the plot contains multiple scatter traces? (i.e., it would pick the nearest point across all scatters in the plot)

Thanks!

**ScottPlot Version:**
ScottPlot.WPF 5.0.34

**Comment by swharden** [comment]
Hi @MultipleCircles, check out the demo app. I think there's an example of this or something very similar... 

https://scottplot.net/demo/

https://github.com/ScottPlot/ScottPlot/blob/d186b6013c098fbb13c9fa35fd84dfffa4450a61/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/ShowValueOnHoverMultiple.cs#L1-L121
