### ISSUE TITLE
Crash when Label text is null

### ISSUE THREAD

**Issue by EricEzaM** [ScottPlot/ScottPlot#3861]
**Issue:**
I accidentally set text to null, got a crash due to exception.
Other places in `Label` do checks for `NullOrEmpty`, but it is missing here in `Render`, causing a null ref exception on `Text.Contains`

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ScottPlot.Label.DrawText(SKCanvas canvas, MeasuredText measured, SKPaint paint, PixelRect textRect, Boolean bottom)
   at ScottPlot.Label.Render(SKCanvas canvas, Pixel px, SKPaint paint, Boolean bottom)
```

**ScottPlot Version:** (What NuGet package are you using?)
5.0.34

**Code Sample:**

```cs
formsPlot1.Plot.Add.Text(null, 0, 0);
```

**Comment by sdpenner** [comment]
I don't see Label as one of the plottable adders.  Is that code sample correct?  Forgive me if I'm missing something...

**Comment by EricEzaM** [comment]
Yeah apologies, my mistake. Its `Add.Text(...)`

**Comment by swharden** [comment]
Thanks for reporting this!

I think the best solution is to add a null check here and return if the string is null.

https://github.com/ScottPlot/ScottPlot/blob/4030eb8c84e7cde4cb1886eec63e97fcccaed767/src/ScottPlot5/ScottPlot5/Primitives/Label.cs#L212-L215

If someone from the community is able to fix this and create a PR before I'm able to get to it, I'd be happy to merge it quickly! 😄
