### ISSUE TITLE
Graphs are getting overlapped when align one below the other

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3863]
> Hi @kareem469, for the middle controls you can:
> 
> ```cs
> formsPlot1.Plot.Axes.Top.IsVisible = false;
> formsPlot1.Plot.Axes.Bottom.IsVisible = false;
> ```
> 
> and it should collapse the space between the top of one plot and the bottom of another.

I tired as per the suggestion, but still there is space between the graphs.

_Originally posted by @kareem469 in https://github.com/ScottPlot/ScottPlot/issues/3816#issuecomment-2104063388_
            

Hi @swharden,
Graphs are getting overlapped.
Need your help, unable to fix this issue.

**Comment by swharden** [comment]
https://github.com/ScottPlot/ScottPlot/issues/3816#issuecomment-2127443059
