### ISSUE TITLE
SP 5: Fastest way to update Heatmap data

### ISSUE THREAD

**Issue by alexisvrignaud** [ScottPlot/ScottPlot#3867]
What is the fastest way to update Heatmap data?
I'm using heatmaps to browse through a 3D volume, with ScottPlot.Avalonia 5. A slider position changes the slice I'm looking at, and I need to update the Heatmap with the same parameters (same zoom, colormap, axis parameters...).

For now, I use a "brute force approach", where I remove the heatmap from the plot, and redo it again.

```        
avaPlot_xslice.Plot.Remove(_heatmap_x);
_heatmap_x = avaPlot_xslice.Plot.Add.Heatmap(slice_x);
_heatmap_x.Colormap = new ScottPlot.Colormaps.Turbo();
avaPlot_xslice.Refresh();
```

Is there a better way to do it?

**Comment by swharden** [comment]
Hi @alexisvrignaud, check out the ScottPlot demo app. I think it demonstrates how to display a heatmap with live, changing data

https://github.com/ScottPlot/ScottPlot/blob/4030eb8c84e7cde4cb1886eec63e97fcccaed767/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/HeatmapLive.cs#L29-L44

**Comment by xichaoqiang** [comment]
if the size of HeatmapData is chage how update it?
