### ISSUE TITLE
Format XAxis with DateTime and milliseconds from List

### ISSUE THREAD

**Issue by gzelasco** [ScottPlot/ScottPlot#3871]
ScottPlot 5.0.3.4, C#

Hi everyone,

I found similar cases online but not my specific case.
I'm using SignalXY to draw an analog signal. 
On the X axis I'm trying to have a DateTime in the format yyyy-MM-dd HH:mm:ss:fff
I populated the X axis array by reading a csv file and these are DateTime values precisely with milliseconds (with sampling approximately twice per second).

The question is: How can I format exisisting values in order to get the required format (yyyy-MM-dd HH:mm:ss:fff)?
I tried with:

```cs
formsPlot1.Plot.Axes.DateTimeTicksBottom();
formsPlot1.Plot.RenderManager.RenderStarting += (s, e) =>
{
     Tick[] ticks = formsPlot1.Plot.Axes.Bottom.TickGenerator.Ticks;
     for (int i = 0; i < ticks.Length; i++)
     {
         DateTime dt = DateTime.FromOADate(ticks[i].Position);
         string label = $"{dt:yyyy-MM-dd HH:mm:ss:fff}";
         ticks[i] = new Tick(ticks[i].Position, label);
     }
};
```

but without success (it replaces all the values with other different values).

I also read about a DateTimeFormat method but I believe it is strictly related to ScottPlot 4.1.
Bear with me but I haven't found any solution online
Thanks so much for the support.

**Comment by swharden** [comment]
Hi @gzelasco, it's a bit of a different strategy but what about plotting data _not_ using DateTime ticks, just having the horizontal axis be milliseconds, then use a custom tick label formatter to convert those millisecond tick labels to DateTime tick labels? This can probably help https://scottplot.net/cookbook/5.0/CustomizingTicks/CustomTickFormatter/

**Comment by gzelasco** [comment]
Hi Scott, thank you again for the timeliness of your response, I wasn't that quick, I apologize. 
I will try your suggestion in the next few days and will definitely let you know. Have a nice day

**Comment by gzelasco** [comment]
Hi Scott, sorry to bore you again.
I tried to follow your advice but I'm probably doing something wrong. This is my code so far:

I populate the XaxisValues array by converting the DateTime value to a double using ToOADate() :
double[] XaxisValues = filteredData.Select(x=> ManagerClass.ConvertSignalDateToDouble(x.DataOra)).ToArray();

Then I implemented and modified the example you provided like this :

string CustomFormatter(double milliseconds)
{
string dt = DateTime.FromOADate(milliseconds).ToString("yyyy-MM-dd HH:mm:ss.fff");
return dt;
}

ScottPlot.TickGenerators.NumericAutomatic myTickGenerator = new ScottPlot.TickGenerators.NumericAutomatic()
{
     LabelFormatter = CustomFormatter
};

formsPlot1.Plot.Axes.Bottom.TickGenerator = myTickGenerator;

Unfortunately on the X axis I don't get the expected dates but other dates generated by the TickGenerator. 
I'll give you an example:

The first date it should convert is 2024-02-14 18.00.00.169
Converted with ToOADate it becomes: 45336.750001956018

Instead this is the value passed to the CustomFormatter: 39999.999260000004
Which is converted (FromOADate) to: 2009-07-05 23:58:56.064

Where am I wrong?
Thanks so much as usual

**Comment by swharden** [comment]
Hi @gzelasco, I modified your original code slightly and it seems to work as expected. I hope this helps!

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/f77a5993-7912-4a0e-902d-cdfbfa4eb483)

```cs
using ScottPlot;

DateTime start = DateTime.Now;

DateTime[] xs = Enumerable.Range(0, 100).Select(x => start.AddSeconds(x)).ToArray();
double[] ys = Generate.RandomWalk(xs.Length);

Plot plt = new();
plt.Add.Scatter(xs, ys);

plt.Axes.DateTimeTicksBottom();
plt.Axes.Bottom.TickLabelStyle.Rotation = -45;
plt.Axes.Bottom.TickLabelStyle.Alignment = Alignment.MiddleRight;
plt.Axes.Bottom.MinimumSize = 150;
plt.Axes.Left.MinimumSize = 50;

plt.RenderManager.RenderStarting += (s, e) =>
{
    Tick[] ticks = plt.Axes.Bottom.TickGenerator.Ticks;
    for (int i = 0; i < ticks.Length; i++)
    {
        DateTime dt = DateTime.FromOADate(ticks[i].Position);
        string label = $"{dt:yyyy-MM-dd HH:mm:ss:fff}";
        ticks[i] = new Tick(ticks[i].Position, label);
    }
};

plt.SavePng("test.png", 600, 500).LaunchFile();
```

**Comment by gzelasco** [comment]
Good morning Scott, thanks again for taking the time to answer me.
I tested your code but I continue to get the same values ​​on the X-axis.
As I said, I retrieve the date and time from a binary file and convert to DateTime + ms in the format yyyy-MM-ss HH:mm:ss.fff.
For the test performed I get 109 DateTime values ​​with relative milliseconds (I attach screenshots from debug mode) and the range goes from 2024-02-14 18:00:00.169 to 2024-02-14 18:00:59.618.
(files attached:
Original_range_starting_datetime.jpg
Original_range_ending_datetime.jpg)

As I reported previously, when the SignalXY chart is displayed, the 109 DateTime values ​​are replaced with 14 other DateTime values ​​ranging from:
2009-07-05 23:58:55 Position = 39999.999247685184
to 2009-07-06 00:00:00 Position= 40000
(file attached: Analog_signalXY.jpg)

It seems that the TickGenerator generates a new range apparently without taking into account the original one.
(files attached:
TickGenerator_starting_datetime.jpg
TickGenerator_ending_datetime.jpg)

Sorry to bore you once again but I really don't know how to solve it.
Thanks again for your availability and support.


![Analog_signalXY](https://github.com/ScottPlot/ScottPlot/assets/110035710/fed6ed6e-0435-48f8-86c6-436af570b5ee)
![Original_range_ending_datetime](https://github.com/ScottPlot/ScottPlot/assets/110035710/eb8f30bb-2926-4c79-a790-f57ef4fe77eb)
![Original_range_starting_datetime](https://github.com/ScottPlot/ScottPlot/assets/110035710/41199fcd-2d1b-485d-b61d-8b137406b1ce)
![TickGenerator_ending_datetime](https://github.com/ScottPlot/ScottPlot/assets/110035710/2f7e8163-c76c-4a6e-9df7-501e1954deab)
![TickGenerator_starting_datetime](https://github.com/ScottPlot/ScottPlot/assets/110035710/2d9ac393-8060-4ca8-83e5-27109389b6e8)

**Comment by swharden** [comment]
> It seems that the TickGenerator generates a new range apparently without taking into account the original one

Indeed, the code above uses the "automatic DateTime tick generator" to automatically generate tick positions and labels. If you want to manually define where ticks go, you can use the "numeric manual" tick generator. You can use ToOADate() and FromOADate() to convert between `double` and `DateTime`, and use a custom tick formatter to do that conversion and display the date format how you like.

https://scottplot.net/cookbook/5.0/CustomizingTicks/CustomTicks/
https://scottplot.net/cookbook/5.0/CustomizingTicks/CustomTickFormatter/

I think this is enough information to help you reach your goal, but if not let me know and we can look into it some more!

**Comment by gzelasco** [comment]
Good morning Scott, Thank you very very much, your support is continuous and flawless. I'll try the new tips as soon as possible. Have a nice day
