### ISSUE TITLE
Avalonia Application Flickering Solution

### ISSUE THREAD

**Issue by randallkrouth** [ScottPlot/ScottPlot#3876]
Have noticed an odd flickering of the application when using ScottPlott.Avalonia 5.034. Using the provided lambda seems to resolve the flickering issue. I added this to a function in my class to refresh the plot and is no longer flickering at this time.

From:
`Dispatcher.UIThread.InvokeAsync(InvalidateVisual, DispatcherPriority.Background);`

To:
`Dispatcher.UIThread.InvokeAsync(() =>
        {
            plot.InvalidateVisual();
        }, DispatcherPriority.Background);`

**Comment by swharden** [comment]
Adding context, the recommended change will be here:

https://github.com/ScottPlot/ScottPlot/blob/4030eb8c84e7cde4cb1886eec63e97fcccaed767/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.Avalonia/AvaPlot.cs#L85-L88

**Comment by bclehmann** [comment]
Hey @randallkrouth is that code change complete? It doesn't compile. There's no variable named `plot` in scope (and if you meant the `Plot` property it doesn't have an `InvalidateVisual` method).

**Comment by randallkrouth** [comment]
Yes, I was holding onto an object in my own class of the AvaPlot class, so in the class itself it would just be `Dispatcher.UIThread.InvokeAsync(() => {InvalidateVisual(); }, DispatcherPriority.Background);`. This was eliminating the flicker for quite some time but recently had noticed it was flickering again but with shorter flickers.
