### ISSUE TITLE
DataLogger: odd behavior when dataset is empty

### ISSUE THREAD

**Issue by TenebrosFR** [ScottPlot/ScottPlot#3880]
**Issue:** After adding a logger X axis is removed and then it crash when zooming if i had froze that axis. Can't find a way to add an axis to it. Adding a bottom axis to the logger doesnt change anything sadly.

**ScottPlot Version:** 5.0.21

**Code Sample:** 
On WPF I've done that.
```cs
 Loaded += Graph.Plot.Add.DataLogger();
```

**Comment by swharden** [comment]
Hi @TenebrosFR, thanks for reporting this!

I discovered the issue relates to the automatic axis management and you can fix this by disabling it until you have data:

```cs
var dl = formsPlot1.Plot.Add.DataLogger();
dl.ManageAxisLimits = false;
```

However I'll make a code change now that will fix this behavior in the next release 👍

**Comment by integracion-integraciondigital** [comment]
Changes made by https://github.com/ScottPlot/ScottPlot/commit/78262f5228db0ad1934787ce96b0568f798100d4 in DataLogger.cs were inadvertedly reverted in https://github.com/ScottPlot/ScottPlot/commit/0db48762150150d6521b71754133040c7a8645d1
