### ISSUE TITLE
How to impose left and right restrictions on the `DateTime Axes`?

### ISSUE THREAD

**Issue by HuShanzhi** [ScottPlot/ScottPlot#3881]
**ScottPlot Version:** ScottPlot5.0

How to limit the range of the `DateTime Axes` when initializing Scottplot? like limiting the `Axes`:
```c#
myPlot.Axes.SetLimits(-100, 150, -5, 5);
```
I would like to start at `2022-12-01 00:00:00` and end at `2022-12-01 00:30:00` on the time axis below.

<img width="1228" alt="截屏2024-05-29 11 09 48" src="https://github.com/ScottPlot/ScottPlot/assets/61410489/94d02e83-de2e-4c38-90b5-00f719b9e158">

**Comment by StendProg** [comment]
Hi @HuShanzhi,

`ScottPlot` uses `OADate` format for `DateTimeAxes`. This is essentially a double variable. You can convert a familiar `DateTime` to `OADate` as follows.
```c#
DateTime from = DateTime.ParseExact("2022-12-01 00:00:00", "yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);
DateTime to = DateTime.ParseExact("2022-12-01 00:30:00", "yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);

myPlot.Axes.SetLimits(from.ToOADate(), to.ToOADate(), -5, 5);
```

**Comment by HuShanzhi** [comment]
> Hi @HuShanzhi,
> 
> `ScottPlot` uses `OADate` format for `DateTimeAxes`. This is essentially a double variable. You can convert a familiar `DateTime` to `OADate` as follows:
> 
> ```cs
> DateTime from = DateTime.ParseExact("2022-12-01 00:00:00", "yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);
> DateTime to = DateTime.ParseExact("2022-12-01 00:30:00", "yyyy-MM-dd HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture);
> 
> myPlot.Axes.SetLimits(from.ToOADate(), to.ToOADate(), -5, 5);
> ```

@StendProg 

Thank you for your reply. It was very helpful !


<img width="1228" alt="截屏2024-05-30 10 52 36" src="https://github.com/ScottPlot/ScottPlot/assets/61410489/7036499d-2e49-44b8-a30f-1940fc7fe25c">

**Comment by HuShanzhi** [comment]
Sorry, I have to reopen this issue because I have a related question about the last two parameters of function `SetLimits()`.

Is there a function like `myPlot.Axes.SetLimits(from.ToOADate(), to.ToOADate(), -5, 5)` to limit the upper and lower limits of the y-axis for `Multiple Axes`？

I have discovered a solution  #850 for Scottplot4.0. Is there a similar method for 5.0?

**Comment by HuShanzhi** [comment]
> Sorry, I have to reopen this issue because I have a related question about the last two parameters of function `SetLimits()`.
> 
> Is there a function like `myPlot.Axes.SetLimits(from.ToOADate(), to.ToOADate(), -5, 5)` to limit the upper and lower limits of the y-axis for `Multiple Axes`？
> 
> I have discovered a solution #850 for Scottplot4.0. Is there a similar method for 5.0?

The problem has been resolved.

```c#
var newYAxis = myPlot.Axes.AddLeftAxis();
newYAxis.Max = 100;
newYAxis.Min = -100;
```
