### ISSUE TITLE
How to Syncronize all the Graphs when Panning Y1 & Y2 Axis

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3882]
**How to Syncronize all the Graphs when Panning Y1 & Y2 Axis** (Ask your question here)

**ScottPlot Version:5.0.33**

I am able to synchronize all graphs when Panning X axis. But not able to get when panning for Y Axis

**Comment by swharden** [comment]
Hi @kareem469, I think you are referencing 

https://scottplot.net/demo/#shared-axes

Note that that demo just links the X axes here:
https://github.com/ScottPlot/ScottPlot/blob/4030eb8c84e7cde4cb1886eec63e97fcccaed767/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/SharedAxes.cs#L60

Use `SetLimits()` or `SetLimitsY()` to also link Y axes

**Comment by kareem469** [comment]
> Hi @kareem469, I think you are referencing
> 
> https://scottplot.net/demo/#shared-axes
> 
> Note that that demo just links the X axes here:
> 
> https://github.com/ScottPlot/ScottPlot/blob/4030eb8c84e7cde4cb1886eec63e97fcccaed767/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/SharedAxes.cs#L60
> 
> Use `SetLimits()` or `SetLimitsY()` to also link Y axes

But i am having different Y-axis scales for each graph. then how can i PAN all graphs for the Y axis?
