### ISSUE TITLE
Update signal wave data.

### ISSUE THREAD

**Issue by sdhongjun** [ScottPlot/ScottPlot#3884]
**Question:** How to update signal data?

**ScottPlot Version:** 5.0.34

**Code Sample:** 

In sp4 I can call `SignalPlot.Update(T[] newData)` method to set new data, but in sp5 the  `ScottPlot.Plottables.Signal` doesn't have `Update` method, how to implement this?

**Comment by swharden** [comment]
Hi @sdhongjun, the easiest way to update the data is to change the values in the array directly. Although this example is for ScottPlot4, the concept is the same in version 5.

https://scottplot.net/faq/live-data/#scatter-plot-change-values-in-fixed-length-arrays

After modifying values in the array, call `FormsPlot1.Refresh()` to force a redraw 👍 

Related: 
* https://scottplot.net/demo/#plot-streaming-data
* https://scottplot.net/demo/#plot-growing-data
