### ISSUE TITLE
Axis under cursor not detected when using ScaleFactor <> 1

### ISSUE THREAD

**Issue by BrianAtZetica** [ScottPlot/ScottPlot#3886]
**Issue:** When a ScaleFactor not equal to 1.0 is applied to a WPF plot, the control does not correclty identify when the cursor is over an axis. This means a user trying to zoom or pan just one axis observes zooming or panning happening in both axes.

**ScottPlot Version:** main branch of repo (5.0.33)

**Code Sample:** (WPF Sandbox with one line added)

```cs
using System.Windows;
using ScottPlot;

namespace Sandbox.WPF;

public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        WpfPlot1.Plot.Add.Signal(Generate.Sin());
        WpfPlot1.Plot.Add.Signal(Generate.Cos());
        WpfPlot1.Plot.ScaleFactor = 2.5;
    }
}

```

**Comment by swharden** [comment]
Hi @BrianAtZetica, thanks for reporting this! It's related to #3469 and I intend to fix it eventually, but today it's not a high priority topic. If you or someone from the community decides to open a PR to fix this, I'd be happy to review it in good time! 🚀

**Comment by swharden** [comment]
>  If you or someone from the community decides to open a PR to fix this

I just saw #3887, awesome! I'll review it shortly 👍
