### ISSUE TITLE
How to add an axis line that in frame's coordinate system so it do not move when zooming or panning?

### ISSUE THREAD

**Issue by danieljfarrell** [ScottPlot/ScottPlot#3888]
**Question:**

I would like to add a cursor line to signal plot similar to how cursor lines work in oscilloscopes.

![image](https://github.com/ScottPlot/ScottPlot/assets/112847/ecb019e9-41f7-4cf3-9afa-5dc0ef16b6ba)

The vertical lines are defined in the coordinate system of the **screen** and not in the coordinate system of the data as the axis line feature of ScottPlot seems to be. Moreover, in an oscilloscope application the cursors report the voltage at the intersection of the signal and the cursor line. When panning of zooming, the cursor remains in the same location relative to the screen.

Is it possible to add a cursor in ScottPlot in the "frame's" coordinate system?

Could you be able to give me some pointers about how I might implement such a feature if needed?

**ScottPlot Version:**

4.1.71

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

No code sample.

**Comment by swharden** [comment]
Hi @danieljfarrell, this seems possible. I'll give you some hints to point you in the right direction and close this issue, but feel free to open it up again if you get stuck and we can take a closer look together.

There are a few potential strategies here, but they all use the same idea of an action firing right before each render that determines where the lines should go (in pixel units), converts that information to coordinate units, then sets the position of the line right before the render.

Here's a quick example:

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        formsPlot1.Plot.Add.Signal(Generate.Sin());
        formsPlot1.Plot.Add.Signal(Generate.Cos());

        var hLine = formsPlot1.Plot.Add.HorizontalLine(0);

        formsPlot1.Plot.RenderManager.RenderStarting += (object? s, RenderPack rp) =>
        {
            PixelRect rect = rp.DataRect; // rectangle where data is drawn
            float yPixel = rect.Height * .25f; // 25% from the top
            double yCoordinate = rp.Plot.Axes.Left.GetCoordinate(yPixel, rect);
            hLine.Position = yCoordinate;
        };
    }
}
```

There may be some edge cases requiring a little extra consideration, but hopefully that's enough to get you started!

![line](https://github.com/ScottPlot/ScottPlot/assets/4165489/ada54055-b5b3-47f5-ac18-77398f3dc5cd)

**Comment by danieljfarrell** [comment]
Hi Scott,

Thank you so much, I can run with that!

Regards,

Daniel
