### ISSUE TITLE
Horizontal line not positioned correctly on Candlechart

### ISSUE THREAD

**Issue by CBrauer** [ScottPlot/ScottPlot#3891]
**Issue:** 

I added a horizontal line to a Candlestick chart to show the previous closing price.
It is not positioned correctly on the chart.

**ScottPlot Version:**
ScottPlot.WinForms" Version="5.0.34"

**Code Sample:**
```
        formsPlot.Plot.ScaleFactor = 2;
        formsPlot.Plot.Clear();
        formsPlot.Refresh();

        var candlePlot = formsPlot.Plot.Add.Candlestick(ohlcData_);
        var plt = candlePlot.Axes.YAxis = formsPlot.Plot.Axes.Right;

        var tfileName = Trades.GetCurrentTfileName();
        var yesterdaysClose = (float) Summary.GetPreviousClose(tfileName, symbol);
        Debug.WriteLine($"Symbol: {symbol}, yesterdaysClose: {yesterdaysClose}");
        var changeColor = (change > 0) ? ScottPlot.Colors.Green : ScottPlot.Colors.Red;
        formsPlot.Plot.Add.HorizontalLine(yesterdaysClose, width: 2, color: changeColor);

        formsPlot.Plot.Axes.DateTimeTicksBottom();

        formsPlot.Plot.Axes.Left.IsVisible = false;
        var company = Symbols.GetCompany(symbol);
        formsPlot.Plot.Axes.Bottom.Label.Text = $"{symbol}: {company}: {change:f2}";
        formsPlot.Plot.Axes.Bottom.Label.FontName = "Verdana";
        formsPlot.Plot.Axes.Bottom.Label.Bold = false;
        formsPlot.Plot.Axes.Bottom.Label.FontSize = 11;

        formsPlot.Plot.Axes.AutoScale();
        formsPlot.Refresh();
```

The Debug.WriteLine produced: "Symbol: COMPX_X, yesterdaysClose: 16735.26".

My plot looks like:

![NASD Chart](https://github.com/ScottPlot/ScottPlot/assets/1317234/71d2c5a8-eb17-4472-86ff-d77b35e285d4)

As you can see, the value of  yesterdaysClose of 16735.26 is not positioned correctly on the chart.

Charles

**Comment by bclehmann** [comment]
If I run (an adjusted form of) your code I do see what you see.

But if I remove the line `formsPlot.Plot.Axes.Left.IsVisible = false;` you see what happened. There's 2 axes which are not the same (and the left axis looks correct).

![image](https://github.com/ScottPlot/ScottPlot/assets/8635304/f7484e2e-c9ca-4c33-96f1-198c662c8e09)

With this code:
```cs
formsPlot.Plot.ScaleFactor = 2;
formsPlot.Plot.Clear();
formsPlot.Refresh();

var ohlcData_ = Generate.RandomOHLCs(50);

var candlePlot = formsPlot.Plot.Add.Candlestick(ohlcData_);
var plt = candlePlot.Axes.YAxis = formsPlot.Plot.Axes.Right;

var yesterdaysClose = ohlcData_[^1].Close;
Debug.WriteLine($"Symbol: foo, yesterdaysClose: {yesterdaysClose}");
formsPlot.Plot.Add.HorizontalLine(yesterdaysClose, width: 2, color: Colors.Cyan);

formsPlot.Plot.Axes.DateTimeTicksBottom();
formsPlot.Plot.Axes.AutoScale();
formsPlot.Refresh();
```

Where the program logged `Symbol: foo, yesterdaysClose: 230.7447787440591` which I believe is correct, if one assumes things are relative to the *left* axis.

This can be fixed if you tell each plottable to use the right axis (they will default to the left axis) with `plottable.Axes.YAxis=formsPlot.Plot.Axes.Right`.  You did this for the candlesticks, but *not* for the vertical line, hence the inconsistency. `Add.HorizontalLine(...)` returns the created line, so you simply have to set `yourLine.Axes.YAxis = formsPlot.Plot.Axes.Right`

But by far the more convenient way to do this if you have several plottables on this axis is to remove the default right axis, and add one which mirrors the left axis:

```cs
 var leftAxis = formsPlot.Plot.Axes.Left;
 formsPlot.Plot.Axes.Remove(Edge.Right); // It will work without this, but it'll look funny
 formsPlot.Plot.Axes.AddRightAxis(new MirroredYAxis(leftAxis, Edge.Right));
```

Then all your plottables can reference the left axis, as they would do by default. You can then continue to make the left axis invisible. Below is an example based on the above code:

```cs
formsPlot.Plot.ScaleFactor = 2;
formsPlot.Plot.Clear();
formsPlot.Refresh();

var ohlcData_ = Generate.RandomOHLCs(50);

var candlePlot = formsPlot.Plot.Add.Candlestick(ohlcData_);
//var plt = candlePlot.Axes.YAxis = formsPlot.Plot.Axes.Right;

var leftAxis = formsPlot.Plot.Axes.Left;
formsPlot.Plot.Axes.Remove(Edge.Right);
formsPlot.Plot.Axes.AddRightAxis(new MirroredYAxis(leftAxis, Edge.Right));

var yesterdaysClose = ohlcData_[^1].Close;
Debug.WriteLine($"Symbol: foo, yesterdaysClose: {yesterdaysClose}");
formsPlot.Plot.Add.HorizontalLine(yesterdaysClose, width: 2, color: Colors.Cyan);

formsPlot.Plot.Axes.DateTimeTicksBottom();

formsPlot.Plot.Axes.Left.IsVisible = false;
formsPlot.Plot.Axes.AutoScale();
formsPlot.Refresh();
```

Which produces the expected result.
![image](https://github.com/ScottPlot/ScottPlot/assets/8635304/70807a02-3ae7-446e-976f-14b956216a5d)

**Comment by bclehmann** [comment]
As an addendum, @swharden we probably ought to better document `MirroredXAxis` and `MirroredYAxis`. I only knew about them because I wrote them, but I imagine they'd be handy in other situations (that's why I wrote them).

**Comment by CBrauer** [comment]
Hi "bclehmann". Thanks for taking time to show me a fix.

**Comment by CBrauer** [comment]
I was too hasty in thanking you.  Your code does not compile!  I get:

![Oops](https://github.com/ScottPlot/ScottPlot/assets/1317234/a6f9d965-3e36-4d28-8df3-db5737d1d9a2)

Charles

**Comment by bclehmann** [comment]
Ah, my apologies, that specific `AddRightAxis()` overload was added on May 14, but there hasn't been a release since May 5. That method will be in the next release.

Instead you can use `formsPlot.Plot.Axes.AddYAxis(new MirroredYAxis(leftAxis, Edge.Right));`

The two methods are essentially the same, all `AddRightAxis` does is check that you actually passed in a right-axis before it does the same thing as `AddYAxis`. Not sure why we offer two options.

**Comment by CBrauer** [comment]
No cigar.  I still get:

![Oops](https://github.com/ScottPlot/ScottPlot/assets/1317234/2444cb22-023b-4935-88ea-65b046810894)

**Comment by bclehmann** [comment]
Ah, my apologies for making you run around like this, but it seems `AddYAxis` is also not on nuget yet. It appears there's not really a good way to add a mirrored axis until the next release. I suppose I got to fancy with it.

I have checked (on 5.0.34 this time) that setting the horizontal line to use the right axis will work properly. You can do this as follows:

```cs
var yourLine = formsPlot.Plot.Add.HorizontalLine(...);
yourLine.Axes.YAxis = formsPlot.Plot.Axes.Right;
```

**Comment by bclehmann** [comment]
It doesn't work because you removed the right axis. You need only take your original code and change the horizontal line to use the right Y axis.

**Comment by swharden** [comment]
I think https://github.com/ScottPlot/ScottPlot/issues/3891#issuecomment-2144006061 resolves this issue, but if not we can open it back up and take a closer look. Thanks for your feedback ben!
