### ISSUE TITLE
SP5: Fix label text wrong position when offset is specified

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3895]
This was opened by @ValeraTychov then closed and I don't have permission to open it, but the solution may be worth creating a new PR for https://github.com/ScottPlot/ScottPlot/pull/3865 (fixes #3836)

Thanks @bclehmann for pointing this out in the Discord #1966

**Comment by bclehmann** [comment]
I created a new PR for it: #3898 

I didn't change a thing, I just downloaded the patch (you can go to `<pr_url>.patch` to download it) and then I applied it
