### ISSUE TITLE
如何绘制不连续的信号图，且间隙处为空

### ISSUE THREAD

**Issue by fff21** [ScottPlot/ScottPlot#3900]
**Question:** 我尝试很多方法，都不能实现图中那种效果。如果你们有好的解决方法，可以帮帮我吗

**Translated:** "I've tried many methods, but can't achieve the effect in the picture. If you have a good solution, can you help me?"

**ScottPlot Version:** 4.1

```cs
plt.XAxis.DateTimeFormat(true);
this.sig1 = plt.AddSignalXY(numericDates, price1);
```

![微信图片_20240604141711](https://github.com/ScottPlot/ScottPlot/assets/130143783/e419a11b-61d0-4aa4-8c23-6c0f63883614)

**Comment by MCF** [comment]
Scatter plots support gaps:

https://scottplot.net/cookbook/5.0/Scatter/ScatterWithGaps/
