### ISSUE TITLE
The value of the mouse position

### ISSUE THREAD

**Issue by xinRedi** [ScottPlot/ScottPlot#3901]
Why is it offset? I am using the WPF.Net framework4.8 Scottplot version 5.0.34
![1717488764186](https://github.com/ScottPlot/ScottPlot/assets/82932045/aa78e61c-3335-4bb9-83e6-6e7fe8fffe5a)
![1717488834274](https://github.com/ScottPlot/ScottPlot/assets/82932045/8fe4eb8d-32e4-40ce-bed3-e63b6bb56107)

**Comment by MCF** [comment]
https://github.com/ScottPlot/ScottPlot/issues/3465#issuecomment-2010669913
