### ISSUE TITLE
Removable menu item

### ISSUE THREAD

**Issue by nilsakesson** [ScottPlot/ScottPlot#3902]
**Suggestion:** (Adding a "Remove" functionality of menu items to handle them separately)

I followed the Custom right click menu demo to get this functionality.

I'm having a drag&drop program where all the plottable content is in a channel list and can be dragged into the plots. When the channel is added to the plot the menu is updated with a "remove signal" option. If the option is clicked the signal is removed but the menu item is still there. To remove it I can only use 
`wpfplot.Menu.Remove() or wpfplot.Menu.Remove()` but then all items are cleared. If there are multiple signals in the plot all of the menu items are removed.

I'm thinking that the 
`plot.Menu.Add` could return an object that could be removed later.

This is my exsisting non working code:

```cs
wpfPlot.Drop += (s, e) =>
{
    if (e.Data.GetDataPresent("ChannelData"))
    {
        if (e.Data.GetData("ChannelData") is ChannelUserControl droppedValues)
        {
            // Plot the new values
            double[] values = droppedValues.Values.ConvertAll(x => (double)x).ToArray();
            var signal = wpfPlot.Plot.Add.Signal(values);
            signal.LegendText = droppedValues.ChannelName;

            // add menu items with custom actions
            wpfPlot.Menu.Add($"Remove {droppedValues.ChannelName}", (wpfPlot) =>
            {
                // remove the signal from the plot
                wpfPlot.Plot.Remove(signal);

                // Remove the option to remove the signal from the menu
                wpfPlot.Menu.Reset();


                // Refresh the plot
                wpfPlot.Refresh();
                // Auto scale the plot
                wpfPlot.Plot.Axes.AutoScale();
            });

            // Refresh the plot
            wpfPlot.Refresh();
            // Auto scale the plot
            wpfPlot.Plot.Axes.AutoScale();
        }
    };
};
```

And this is my suggestion

```cs
wpfPlot.Drop += (s, e) =>
{
    if (e.Data.GetDataPresent("ChannelData"))
    {
        if (e.Data.GetData("ChannelData") is ChannelUserControl droppedValues)
        {
            // Plot the new values
            double[] values = droppedValues.Values.ConvertAll(x => (double)x).ToArray();
            var signal = wpfPlot.Plot.Add.Signal(values);
            signal.LegendText = droppedValues.ChannelName;

            // add menu items with custom actions
            var menuItem = wpfPlot.Menu.Add($"Remove {droppedValues.ChannelName}", (wpfPlot) =>
            {
                // remove the signal from the plot
                wpfPlot.Plot.Remove(signal);

                // remove the option to remove the signal from the menu
                wpfPlot.Menu.Remove(menuItem );

                // Refresh the plot
                wpfPlot.Refresh();
                // Auto scale the plot
                wpfPlot.Plot.Axes.AutoScale();
            });

            // Refresh the plot
            wpfPlot.Refresh();
            // Auto scale the plot
            wpfPlot.Plot.Axes.AutoScale();
        }
    };
};
```

This shows how it doesn't really work for multiple objects in the plot.

![MenuItems](https://github.com/ScottPlot/ScottPlot/assets/87042707/af18ef7e-e870-45d4-8e5b-c0ce22706050)

**Comment by swharden** [comment]
Hi @nilsakesson,

when you add a menu item it gets added to this list:

https://github.com/ScottPlot/ScottPlot/blob/44ee711df9f646ee82b124e1f98b8a4c5f597fc0/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WPF/WpfPlotMenu.cs#L15C34-L15C51

Therefore I think you can do something like:

```cs
wpfPlot.Menu.ContextItems.RemoveAt(index);
```

If this works, it may be worth adding a helper method to that class to allow something like:

```cs
wpfPlot.Menu.RemoveAt(5);
```

or perhaps even

```cs
wpfPlot.Menu.RemoveAt("text of the item to remove");
```

If you decide to add this function and it's helpful, feel free to create a pull request and I'll merge it in! Otherwise I think this information is enough to get you moving. If not, let me know and we can open this issue again and take a closer look together 👍
