### ISSUE TITLE
How to map ScottPlot 4 Configurations to ScottPlot 5: AllowDroppedFramesWhileDragging and ScrollWheelZoom?

### ISSUE THREAD

**Issue by danieljfarrell** [ScottPlot/ScottPlot#3906]
**Question:**

ScottPlot5's new configuration system is very clean, https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/CustomMouseActions.cs

But I am unsure how to map some of the configurations I used in ScottPlot4 to ScottPlot5:

- AllowDroppedFramesWhileDragging
- ScrollWheelZoom

**ScottPlot Version:**

Updating from 4 to 5.0.35

**Code Sample:**

In V4 you could do,

```cs
Configuration.AllowDroppedFramesWhileDragging = true;
Configuration.ScrollWheelZoom = true;
```

**Comment by swharden** [comment]
Hi @danieljfarrell,

> AllowDroppedFramesWhileDragging

ScottPlot 5 uses a new SkiaSharp rendering system so frames are dropped automatically so as to not slow down interactivity

> ScrollWheelZoom 

I think this can be controlled using strategies described on https://scottplot.net/demo/#custom-mouse-actions

**Comment by swharden** [comment]
> ScrollWheelZoom

Actually I think you can change this behavior by doing something like

```cs
formsPlot1.Interaction.Inputs.ZoomInWheelDirection = null;
formsPlot1.Interaction.Inputs.ZoomOutWheelDirection = null;
```

Note that the input binding system is about to get simpler and hopefully more discoverable in the future, but that means the present strategy will change once more. #3186
