### ISSUE TITLE
The mousehover for selecting the Verticle line should cover a wider area.  Currently, it is too precise for the user to select and drag the Verticle line

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3910]
The mousehover for selecting the Vertical line should cover a wider area.  Currently, it is too precise for the user to select and drag the Verticle line

ScottPlot Version:5.0.33

Making it a wider area will be very useful for the user to select and drag the Vertical line easily.

**Comment by swharden** [comment]
Hi @kareem469, 

To give the cursor a wider "hit box", increase the number `10` to a larger value

https://github.com/ScottPlot/ScottPlot/blob/d003f9a1f19aae487cb03a25becc2d54efd0a2e4/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/DraggableAxisLines.cs#L86
