### ISSUE TITLE
X axis labels are getting disappeared when Dragzoomed the graph to maximum

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3913]
X axis labels are getting disappeared when Dragzoomed in the graph to maximum

**ScottPlot Version:** 5.0.33

when drag zoomed in the graph with mouse to maximum, X axis labels getting disappeared.
How to limit the maximum zoom in with x axis labels visible when Dragzoommed-in?

**Comment by swharden** [comment]
Hi @kareem469, a screenshot would really help communicate what the issue is.

The code here may help you solve your problem. It shows how to limit how far in or out the user may zoom: https://scottplot.net/demo/#axis-rules

**Comment by kareem469** [comment]
Hi @swharden 

Before Maximum Zoom 
![image](https://github.com/ScottPlot/ScottPlot/assets/101133645/eea83856-2018-4d4b-89e1-fd6aa3e7d8e9)

After Maximum Zoom 
![image](https://github.com/ScottPlot/ScottPlot/assets/101133645/8291f1d9-c48f-4d2d-a66c-c98375a8e3af)

X-Axis label disappeared after maximum zoomed in

**Comment by swharden** [comment]
Hi @kareem469, there's not enough context to be able to know what's happening here. It looks like the plots are being resized in such a way that makes the data area larger than the control, so some of the data and the lower axis are getting cut off

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/289d97eb-32bc-4575-91e9-5cc78e563919)
