### ISSUE TITLE
Issues with Setting Axis Limits and Zoom Constraints in ScottPlot 5 WPF OHLC (Candlestick) Chart

### ISSUE THREAD

**Issue by Knaackee** [ScottPlot/ScottPlot#3916]
Hello,

thanks for the great work!

I am currently working with ScottPlot 5, specifically using the OHLC (Candlestick) chart in a WPF application. I have encountered a couple of issues that I have been unable to resolve despite extensive searching and experimentation.

### Setting Axis Limits:
I would like to set specific limits for the X and Y axes, but I have not found any clear documentation or examples that demonstrate how to achieve this in the WPF version.
### Zoom Constraints:
I also need to restrict the zoom functionality so that users cannot zoom out beyond a certain point or zoom in too closely. Again, I have not been able to find any guidance on how to implement these constraints.
Could you please provide some guidance or examples on how to set axis limits and apply zoom constraints in the ScottPlot 5 WPF version? Any help or direction would be greatly appreciated.

### Lazy Loading
I implemented Lazy loading which does work, but sometimes i got the following error:

> System.Collections.Generic.KeyNotFoundException: 'The given key 'ScottPlot.AxisPanels.DateTimeXAxis Min=45449,041360098985, Max=45451,914888912106, Span=2,8735288131210837' was not present in the dictionary.' 

at

``` MultiAxisLimitManager.cs 
public void Apply(Plot plot)
{
    foreach (IAxis axis in plot.Axes.GetAxes())
    {
	    axis.Range.Min = RememberedLimits[axis].Min;
	    axis.Range.Max = RememberedLimits[axis].Max;
    }
}
```

Thank you!

**Comment by swharden** [comment]
Hi @Knaackee, thanks for this question!

You may benefit from the code examples in the demo app. Specifically, https://scottplot.net/demo/#axis-rules

https://github.com/ScottPlot/ScottPlot/blob/d003f9a1f19aae487cb03a25becc2d54efd0a2e4/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/AxisRules.cs#L44-L50

Let me know if I misunderstood your question or you're unable to achieve the functionality you're looking for and we can open this issue back up again and take a look together! 👍 🚀

**Comment by Knaackee** [comment]
**Thanks, Scott, for your previous help!** I am now able to load my OHLC data and plot them without any issues. However, I am encountering a problem with an additional method that adds extra plots such as arrows and lines.

Problem Description
I maintain a list of these additional plots. When the x-axis changes (i.e., the start and end dates change), I iterate through this list, remove the existing plots, and generate new ones.

However, when I rapidly zoom in and out or change the x-axis extensively, I occasionally encounter the following exception: ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion. 

Current Attempt to Solve
To address this issue, I tried a debounce Timer and disabling and enabling rendering as follows:

```
wpfPlot.Plot.RenderManager.EnableRendering = false;
while (wpfPlot.Pplot.RenderManager.IsRendering) { }

// Code to remove and regenerate plots

wpfPlot.Plot.RenderManager.EnableRendering = true;
```

Unfortunately, this approach does not solve the problem.

Any ideas?
