### ISSUE TITLE
How to mirror axes?

### ISSUE THREAD

**Issue by wi-fr** [ScottPlot/ScottPlot#3920]
**Question:** To mirror a plot’s vertical axis on the right side of a chart, we currently create the plottable twice. Is there a direct way to achieve this? 

**ScottPlot Version:** ScottPlot Version 5
```cs
ScottPlot.Plottables.Scatter s1 = myPlot.Add.Scatter(dataX, dataY);
ScottPlot.Plottables.Scatter s2 = myPlot.Add.Scatter(dataX, dataY);
s2.IsVisible = false;
s2.Axes.YAxis = myPlot.Axes.Right;
```
We assume, that the ScottPlot.AxisPanels.MirroredXAxis and ScottPlot.AxisPanels.MirroredYAxis  classes exist for precisely for this purpose, but could not figure out how to use them.

**Comment by bclehmann** [comment]
Currently, the way to add your own axis objects is in the code but not yet released. It will be in the next release, which Scott has said he hopes to have out this weekend (see https://github.com/ScottPlot/ScottPlot/issues/3457#issuecomment-2154991555).

Once that release comes out you should be able to just do this:
```cs
var leftAxis = myPlot.Plot.Axes.Left;
myPlot.Plot.Axes.Remove(Edge.Right); // Remove the (invisible) default right axis, otherwise it will look weird
myPlot.Plot.Axes.AddRightAxis(new MirroredYAxis(leftAxis, Edge.Right));
```

This replaces the invisible default right axis with a visible one which mirrors whatever left axis you already have.
