### ISSUE TITLE
Labels of VerticalLine and HorizontalLine are partly cut away when LabelOppositeAxis = true

### ISSUE THREAD

**Issue by saurla** [ScottPlot/ScottPlot#3925]
**Issue:** Label of VerticalLine and HorizontalLine does not fit in the drawing area when using `LabelOppositeAxis = true`. Label is cut so that only part of it is visible. See the label of the lines in the following screenshot which illustrates the problem.

![image](https://github.com/ScottPlot/ScottPlot/assets/24889872/4f973e84-4336-4e38-878d-0b572c7e9bf8)

**ScottPlot Version:** 5.0.34. The bug was introduced in version 5.24 in merge commit https://github.com/ScottPlot/ScottPlot/commit/36ec5f68ebcdae13454e0e20cd33a3c848bd7825. 

**Code Sample:** Bug can be reproduced using the demo `DraggableAxisLines` and adding line `vl.LabelOppositeAxis = true;` after line
https://github.com/ScottPlot/ScottPlot/blob/9c45ada1dd01677e1d3ce6f74f786b8deb07f4a2/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/DraggableAxisLines.cs#L23
and line `hl.LabelOppositeAxis = true;` after line https://github.com/ScottPlot/ScottPlot/blob/9c45ada1dd01677e1d3ce6f74f786b8deb07f4a2/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/DraggableAxisLines.cs#L27

**Cause:** This bug is caused by following check in XAxisBase class which was added in merge commit mentioned earlier:
https://github.com/ScottPlot/ScottPlot/blob/9c45ada1dd01677e1d3ce6f74f786b8deb07f4a2/src/ScottPlot5/ScottPlot5/AxisPanels/XAxisBase.cs#L17-L18
There is similar check for the YAxisBase. Basically this happens when there is no top X axis and right Y axis set. In this case the axis area is set to be too small to fit the Labels.

**Workaround:** The problem can be worked around by setting the SizeWhenNoData property to larger number so that the axis can fit the label.

```
(formsPlot1.Plot.Axes.Top as AxisBase).SizeWhenNoData = 30;
(formsPlot1.Plot.Axes.Right as AxisBase).SizeWhenNoData = 30;
```

**Possible fix:** Bug could be fixed by removing the `!Range.HasBeenSet` check from XAxisBase and YAxisBase. However then all Axes would take extra space always even if there not any range defined for that Axis.

**Comment by swharden** [comment]
Hi @saurla, thanks for reporting this issue! (and the workaround too) 

There isn't a particularly elegant way to solve this issue at the moment, but your workaround works well. Others finding this issue may benefit from noting that the cookbook example demonstrates the following strategy:

```cs
// extra padding on the right and top ensures labels have room
myPlot.Axes.Right.MinimumSize = 30;
myPlot.Axes.Top.MinimumSize = 30;
```

https://scottplot.net/cookbook/5.0/AxisLines/AxisLineLabel/
