### ISSUE TITLE
Customized tick not presently available in SP5

### ISSUE THREAD

**Issue by yosez** [ScottPlot/ScottPlot#3929]
**Suggestion:**
I have migrated my project from SP4 to SP5, but I found it not possible to customize the style of ticks, could you please add this feature in a future version?
Thanks to the team of creating such an accessible lib.

**Comment by swharden** [comment]
Hi @yosez, this cookbook recipe should help you discover how to customize tick style: https://scottplot.net/cookbook/5.0/Styling/AxisCustom/

You can also customize properties like:
```cs
formsPlot1.Plot.Axes.Left.TickLabelStyle.FontSize = 24;
```
