### ISSUE TITLE
Legend: Add option to configure visibility for manually added items

### ISSUE THREAD

**Issue by cataclism** [ScottPlot/ScottPlot#3931]
I think that the title is pretty much self explanatory, but it would be awesome if legend labels could be toggled in visibility, so that in a multi signal scenario, when toggling the signal's visibility, one could also toggle its lable visibility

The utilization could be of the type in a multi signal scenario with a certain visibility condition (suppose that we need to toggle visibility off):

```cs
private LegendItem[] signalLegendItem = new LegendItem[8];
private readonly ScottPlot.Plottables.SignalXY[] signal= new SignalXY[8];

for (int i=0; i<8; i++)
{
      if (visibilityConditionIsMet)
          {
               signalLegendItem.IsVisible=false; 
               signal.IsVisible=false;
          {
}
```
NOTE: 
In here i've used a SignalXy but it applies to any type of signal

**Comment by swharden** [comment]
Hi @cataclism, thanks for the suggestion! I see that axis lines have a property `ExcludeFromLegend`, and it would be a good idea to force all plot types which have legend items to implement this property too. I'll use this issue to track adding this feature 👍

**Comment by swharden** [comment]
Note that one can currently hide items from the legend by setting their `Label` property to `null` or `String.Empty`

**Comment by cataclism** [comment]
Hi @swharden , thanks for the suggestion! However if I do what you said the Legend is as follows:

![image](https://github.com/ScottPlot/ScottPlot/assets/69798041/847c8b73-5508-424c-b6d1-ff062c82ed48)


The name is not there anymore, but the space is still used, is there a way to remove also the unused bits?

**Comment by swharden** [comment]
Hi @cataclism, I'm unable to reproduce the issue you describe

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        var sig1 = formsPlot1.Plot.Add.SignalXY(Generate.Consecutive(51), Generate.Sin(51));
        var sig2 = formsPlot1.Plot.Add.SignalXY(Generate.Consecutive(51), Generate.Cos(51));

        sig1.LegendText = "signal 1";
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/7c9136e0-9738-4a46-a192-3b11d8fdadd9)

Can you share a code example I can run to better understand this issue? Thanks!

**Comment by swharden** [comment]
Hi @cataclism, this should now work:

```cs
signalLegendItem[i].IsVisible = false; // hide a manual item
```

**Comment by cataclism** [comment]
Hi @swharden, you're awesome! Thank you so much ;)
