### ISSUE TITLE
Signal: add the ability to replace the data source

### ISSUE THREAD

**Issue by danieljfarrell** [ScottPlot/ScottPlot#3932]
**Question:** 

I am updating a ScottPlot4 application to ScottPlot5. 

In ScottPlot4 I could update the signal data by doing,

```cs
float[] NewData;
// ... acquire new data
MySignal.Update(NewData);
MySignal.SamplePeriod = NewSamplePeriod;
MySignal.OffsetX = NewXMin;
```

I like the data source approach, it reminds me of Cocoa/UIKit development. Nice.

Is there any example code on:

1. how to setup a Signal plot using a float data source in ScottPlot5? 
2. how to update signal data using data source in ScottPlot5?

**ScottPlot Version:**
5.0.11

**Comment by bclehmann** [comment]
You cannot change out the data source, but that doesn't mean you can't replace the data *in* the data source.

I think doing this will just work:

```cs
List<float> data = new(); // Fill with your data
var sig = plot.Add.Signal(data);

// Modify data in place:
data[0] = newValue;
data.Add(valueToAppend);
```

The only thing you can't do is replace the list with a new one. If you want to do that I would either clear the list and write the contents of the one you're replacing it with, or create your own `ISignalSource` that makes the list writable.

**Comment by swharden** [comment]
Hi [bclehmann](https://github.com/bclehmann), thanks for your feedback!

> You cannot change out the data source, but that doesn't mean you can't replace the data in the data source.

Good point! More about this is here:
https://scottplot.net/faq/live-data/#scatter-plot-change-values-in-fixed-length-arrays

> or create your own ISignalSource that makes the list writable

I'll consider doing this so we don't have to modify the existing default signal sources 🤔

**Comment by swharden** [comment]
Similarly, let's make it easier to replace 2D data in heatmaps (#3941)
