### ISSUE TITLE
In Scottplot winforms, how to enable horizontal scroll for x-axis when zoomed-in?

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3934]
**In Scottplot winforms, how to enable horizontal scroll for x-axis when zoomed-in:**

**ScottPlot Version:5.0.33**

How do I enable horizontal scrolling for the x-axis when zoomed-in, so that the user can easily move around the total graph?

**Comment by swharden** [comment]
I think left-click-drag will scroll, and holding ALT or SHIFT will lock it to horizontal or vertical scrolling.

This behavior can also be enforced by adding an axis rule as described in https://scottplot.net/demo/5.0/#axis-rules
