### ISSUE TITLE
Making Intensities read / write in Heatmap

### ISSUE THREAD

**Issue by sdpenner** [ScottPlot/ScottPlot#3938]
**Suggestion:** 

What would you think about making the Intensities array read / write on the Heatmap chart?  I have a need to update the array and it feels wrong to clear the plots and add a Heatmap back to do that.

Thoughts?

Something like the following...

```cs
    private double[,] _intensities = intensities;

    public double[,] Intensities
    {
        get => _intensities;
        set
        {
            _intensities = value;
            DataRange = Range.GetRange(Intensities);
            Update();
        }
    }
```

**Comment by swharden** [comment]
Hi @sdpenner, see the demo app. There's an example that shows a live heatmap with continuously changing data.

Basically it works by modifying the values in the existing array and requesting `Refresh()` after they change. The plot is never cleared, the heatmap is only added a single time, and no new arrays are ever created.

https://github.com/ScottPlot/ScottPlot/blob/f0279f28c203218415f6f7b0a51606dab76bc36d/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/HeatmapLive.cs#L1-L45
