### ISSUE TITLE
Phasor diagram in a polar coordinate plot

### ISSUE THREAD

**Issue by nilsakesson** [ScottPlot/ScottPlot#3939]
**Question: Is there a way to visualize phasors in a polar coordinate plot? If there is, is there a way to visualize the angles between the phasors in the plo?** (Ask your question here)

**ScottPlot Version: 5.0.35** (What NuGet package are you using?)

**Description:** I'm looking for a way to show the correlation between phasor easy. Preferably with an angle that is between the phasors. Maybe something like 

```
var phasorType = PhasorTypes.Arrow;
var angle1 = 0;
var angle2 = 2*Math.PI/3;

var MyPolarCoordinates = MyPlot.Plot.Add.PolarCoordinates();
var phasor1 = MyPolarCoordinates.AddPhasor(angle1, phasorType);
var phasor2 = MyPolarCoordinates.AddPhasor(angle2, phasorType);

MyPolarCoordinates.AddPhaseDiffrenceText(phasor1, phasor2);

```
And with 6 phasors it would look something like below but maybe with curved angles between the phasors showing the relationship between them.

![image](https://github.com/ScottPlot/ScottPlot/assets/87042707/062f8e30-feac-4f8b-9aad-0bf698f1e82d)

**Comment by swharden** [comment]
Hi @nilsakesson, this is definitely possible by creating a custom plottable that implements `IPlottable` and adding it to your plot.

Some general suggestions are outlined here https://scottplot.net/faq/custom-plot-type/

It's unlikely that I'll create this plot type myself soon, but if you or someone from the community decides to give it a go and creates a class that generates plots like this, I would be happy to include it with ScottPlot in a future release so it's available to everyone. If you get started working on it and get stuck somewhere, you can share what you got so far and I am happy to offer suggestions along the way!

**Comment by CoderPM2011** [comment]
I've been thinking about #4055 for a while.
With some improvements, we should be able to easily implement the plot in this issue.
@swharden Could you provide me with some suggestions?
