### ISSUE TITLE
Disable Zoom on MouseWheel using ScottPlot.WinForms.FormsPlot

### ISSUE THREAD

**Issue by gfarax** [ScottPlot/ScottPlot#3945]
**Question:** Disable Zoom on MouseWheel using ScottPlot.WinForms.FormsPlot

**ScottPlot Version:** ScottPlot 5.0

```cs
// ScottPlot Version 4 works with below code
formsPlot1.Configuration.ScrollWheelZoom = false;
// above property is not available in ScottPlot 5.0
```
How can I disable zoom on?

Thank you in advanced

**Comment by swharden** [comment]
https://scottplot.net/demo/5.0/#custom-mouse-actions 👍

**Comment by gfarax** [comment]
> https://scottplot.net/demo/5.0/#custom-mouse-actions 👍

Great Thank you!!!👍
