### ISSUE TITLE
How to subscribe to an EventHandler in VB.NET?

### ISSUE THREAD

**Issue by BambOoxX** [ScottPlot/ScottPlot#3949]
**Question:** (Ask your question here)

I've been scratching my head about this, and I can't figure a solution. I tried the AI assistant with no avail.
I'm trying to apply the "shared axes" example in VB.NET ScottPlot 5, however, I keep getting a `BC30676` error when writing the equivalent of 
```cs
formsPlot1.Plot.RenderManager.AxisLimitsChanged += (s, e) => CopyLimits(formsPlot1, formsPlot2);
```
AFAIK this should look like
```
AddHandler formsPlot1.Plot.RenderManager.AxisLimitsChanged, AddressOf CopyLimits
```
but that doesn't seem to work because `AxisLimitsChanged` is not an event, but an eventhandler already...

**ScottPlot Version:** (What NuGet package are you using?)

5.0.35 ScottPlot.WinForms

**Comment by swharden** [comment]
Hi @BambOoxX, I don't know much about VB but I asked ChatGPT and it said the following. Does this help you reach a solution? It looks pretty similar to what you did.

---

> write example VB.NET code that subscribes to the "AxisLimitsChanged" EventHandler and calls the "CopyLimits" function when the event is invoked

Sure, here's an example of how you can subscribe to the `AxisLimitsChanged` event handler in VB.NET and call the `CopyLimits` function when the event is invoked:

First, ensure that you have an event defined for `AxisLimitsChanged` and a function called `CopyLimits` that you want to call when the event is fired. Here's a simple example:

```vb.net
Public Class Chart
    ' Define the delegate for the event
    Public Delegate Sub AxisLimitsChangedEventHandler(sender As Object, e As EventArgs)

    ' Define the event
    Public Event AxisLimitsChanged As AxisLimitsChangedEventHandler

    ' Method to raise the event
    Protected Overridable Sub OnAxisLimitsChanged(e As EventArgs)
        RaiseEvent AxisLimitsChanged(Me, e)
    End Sub

    ' This method can be called to change the axis limits and raise the event
    Public Sub ChangeAxisLimits()
        ' Logic to change axis limits
        ' ...

        ' Raise the event
        OnAxisLimitsChanged(EventArgs.Empty)
    End Sub
End Class

Public Class Form1
    Private WithEvents chart As New Chart()

    Public Sub New()
        ' This call is required by the designer.
        InitializeComponent()

        ' Add any initialization after the InitializeComponent() call.
        ' Subscribe to the AxisLimitsChanged event
        AddHandler chart.AxisLimitsChanged, AddressOf Me.CopyLimits
    End Sub

    ' Event handler method
    Private Sub CopyLimits(sender As Object, e As EventArgs)
        ' Logic to copy limits
        MessageBox.Show("Axis limits have changed, copying limits...")
    End Sub
End Class
```

In this example:

1. **Chart Class**: This class defines the `AxisLimitsChanged` event. The `ChangeAxisLimits` method simulates changing the axis limits and raising the event.
2. **Form1 Class**: This is your form where you subscribe to the `AxisLimitsChanged` event of the `Chart` class. The `CopyLimits` method is the event handler that will be called when the event is raised.

### Explanation:
- **Delegate and Event Definition**: The `AxisLimitsChangedEventHandler` delegate and `AxisLimitsChanged` event are defined in the `Chart` class.
- **OnAxisLimitsChanged Method**: This protected method raises the `AxisLimitsChanged` event.
- **ChangeAxisLimits Method**: This public method simulates a change in axis limits and calls `OnAxisLimitsChanged` to raise the event.
- **Form1 Class**: In the constructor, the form subscribes to the `AxisLimitsChanged` event using `AddHandler`. The `CopyLimits` method displays a message box indicating that the axis limits have changed.

When you run this code and call the `ChangeAxisLimits` method of the `chart` object, the `AxisLimitsChanged` event will be raised, and the `CopyLimits` method in `Form1` will be called, showing a message box.

**Comment by BambOoxX** [comment]
Well if I look at e.g. https://stackoverflow.com/questions/28387577/whats-the-correct-way-to-convert-this-event-handler-registration-from-c-sharp-t what I do should work... as long as `AxisLimitsChanged ` is indeed an event, but its not. Is it on purpose ? 

From you ChatGPT code, I can only second that since in the end, the `AddHandler` is applied to an `Event`...
I find it very surprising that there is such a big difference between C# and VB on that point.

**Comment by BambOoxX** [comment]
Ok I found a working solution with `formsPlot1.Plot.RenderManager.AxisLimitsChanged = Function(s, e) CopyLimits(s, e)`
