### ISSUE TITLE
Error when placing components

### ISSUE THREAD

**Issue by DevAnyKR** [ScottPlot/ScottPlot#3950]
**Issue:** (Describe the bug here)
![image](https://github.com/ScottPlot/ScottPlot/assets/110871727/6559e9cf-5a03-4ef9-8b33-55168c7dbc83)

1. Drag&Drop FormsPlot to Form Design
2. Error Popup

**ScottPlot Version:** (What NuGet package are you using?)

5.0.35

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

Visual Studio 2022
.NET Framework 4.8.1
C# WinForm
create new Form2.cs
😢

**Comment by swharden** [comment]
Thanks for reporting this @DevAnyKR! This seems to be a common VisualStudio issue.

Adding the control programmatically should fix this issue! https://scottplot.net/faq/add-winforms-programmatically/
