### ISSUE TITLE
is there anyway can make Signal has different YAxis and YAxis Arrange from top to bottom？

### ISSUE THREAD

**Issue by TinyyMax** [ScottPlot/ScottPlot#3954]
<img width="1527" alt="lQLPJwaxVifd1aHNByrNC-6wOaGvrWSiAlsGWtknpOGgAA_3054_1834" src="https://github.com/ScottPlot/ScottPlot/assets/103832742/b137c236-eafb-4946-a293-a1c3c742d5b8">

![d255050cb4f0ca107f3ba690571fde1](https://github.com/ScottPlot/ScottPlot/assets/103832742/ac6ec389-210b-40a3-8ac4-4058c48bbd62)

**Comment by TinyyMax** [comment]
Hi @swharden ,thanks very much for your answer ,I see #3816 .in that case ,he make 4 ScottPlot in a row .and make them very close  to make them look like one table.
in my case i have 64 channel ,so i have 64 Signal in one table ,and i need to zoom them.
so i mean  if my 64 sinal can have there  own axis and these axis can  arrangement from top to bottom .
but our muti axis is like this 
![image](https://github.com/ScottPlot/ScottPlot/assets/103832742/bb62d6c7-2c24-4e41-a4e9-a44db2b6ee91)

**Comment by TinyyMax** [comment]
i  wish  it look like this 
<img width="402" alt="lQLPKHcc2JkZZlnNAu3NAyOw2Gj1CejyMr8GXWUj1X5sAA_803_749" src="https://github.com/ScottPlot/ScottPlot/assets/103832742/b7cb3417-0d17-4399-a887-485ff1275b38">

**Comment by swharden** [comment]
Hi @TinyyMax, does the code on this page help you find a solution?
https://scottplot.net/demo/5.0/#shared-axes
