### ISSUE TITLE
Some way to limit zoom min and max

### ISSUE THREAD

**Issue by ZSYMAX** [ScottPlot/ScottPlot#3961]
**Suggestion:** (Describe your idea here)
Is that any possible to make function 'ZoomFrac' virtual  in class 'CoordinateRangeMutable' ,I am try to override it to limit zoom min and max, Or there are some way else to implement it.
```cs
    public class MyRange : CoordinateRangeMutable
    {
        public MyRange() : base(double.NegativeInfinity, double.PositiveInfinity)
        {
        }

        public double MinSpan { get; internal set; }
        public double MaxSpan { get; internal set; }

        public override void ZoomFrac(double frac, double zoomTo)
        {
            double spanLeftX = zoomTo - Min;
            double spanRightX = Max - zoomTo;
            var min = zoomTo - spanLeftX / frac;
            var max = zoomTo + spanRightX / frac;

            var abs = Math.Abs(max - min);
            if (abs < MinSpan)
            {
                return;
            }
            else if (abs > MaxSpan)
            {
                return;
            }

            Max = max;
            Min = min;
        }
    }
```
![zoom_limit](https://github.com/ScottPlot/ScottPlot/assets/38749563/5f3ffcad-1985-4c63-b335-88edf315a85f)

**Comment by jpgarza93** [comment]
I was able to achieve this using **Rules**, maybe you can leverage them as well.

My code, for you to visualize it a bit:
```cs
//This rule will set the zoom-in limit to be able to see 3 x-axis samples at all times
XMinimumSpan = new MinimumSpan(
                    xAxis: Plot!.Axes.Bottom,
                    yAxis: Plot!.Axes.Right,
                    xSpan: 3,
                    ySpan: 0);

//This rule will set the zoom-out limit to be able to see 3 times the PlotXRange  set for the x-axis 
XMaximumSpan = new MaximumSpan(
                    xAxis: Plot!.Axes.Bottom,
                    yAxis: Plot!.Axes.Right,
                    xSpan: PlotXRange * 3,
                    ySpan: 0);

Plot!.Axes.Rules.Add(XMinimumSpan);
Plot!.Axes.Rules.Add(XMaximumSpan);
```

There is also a WinForms demo called [AxisRules](https://github.com/ScottPlot/ScottPlot/blob/fb3b1c84af3c361bf1eb8f4286ad1d4e7038afc5/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/AxisRules.cs#L7)

**Comment by ZSYMAX** [comment]
It will scroll the axis range when zoom to max or min span limit @jpgarza93

**Comment by swharden** [comment]
One option is axis rules https://scottplot.net/demo/5.0/#axis-rules

Another option is to use the `Plot.RenderManager.RenderStarting` event to customize the axis limits to apply custom logic just before each render
