### ISSUE TITLE
Pie: Add `Rotation` property

### ISSUE THREAD

**Issue by johndoh** [ScottPlot/ScottPlot#3962]
I found a todo comment in the code for this but I could not find a corresponding issue so I thought I'd create one to prevent the matter being forgotten.

In SP4 the first slice in a pie chart was positioned at the north of the chart.

In SP5 the first slice in a pie chart is positioned at the east of the chart.

Please could it be moved back to north or a 'first position' type option be added?

code ref: https://github.com/ScottPlot/ScottPlot/blob/fb3b1c84af3c361bf1eb8f4286ad1d4e7038afc5/src/ScottPlot5/ScottPlot5/Plottables/Pie.cs#L47-L52

**Comment by swharden** [comment]
Hi @johndoh, thanks for the suggestion! I agree we should make that the default, but also we could add a public property something like `RotationDegrees` to let the user control that as well.

I see that rotation is only applied at this line, so maybe it's as easy as adding 90 here?

https://github.com/ScottPlot/ScottPlot/blob/fb3b1c84af3c361bf1eb8f4286ad1d4e7038afc5/src/ScottPlot5/ScottPlot5/Plottables/Pie.cs#L66
