### ISSUE TITLE
DataLogger: add support for custom line and marker styles

### ISSUE THREAD

**Issue by jpgarza93** [ScottPlot/ScottPlot#3963]
**Suggestion:** Is there a reason why **ScottPlot 5** DataLoggers do not contain Markers (IHasMarker)? I can see they are available in ScottPlot 4. It would be great to toggle between line and exact point representation :)

```cs
// existing line style
DataLogger.LineStyle.Width = 2;
DataLogger.LineStyle...

// add marker style
DataLogger.MarkerStyle.Width  = 2;
DataLogger.MarkerStyle...
```

**Comment by jpgarza93** [comment]
Would adding another LineStyle that doesn't interpolate between data points be a good idea?

https://scottplot.net/cookbook/5.0/Styling/LineStyles/
![image](https://github.com/ScottPlot/ScottPlot/assets/79015116/a9e25bd5-ec4d-4670-b783-3e94984bbd98)

Could it be called `Point` or `MarkersOnly`?

**Comment by swharden** [comment]
I like the idea! It may take me a while before I can get to this, but if you or someone from the community wants to create a PR that mimics the styling options of scatter plots, I'd be happy to review and merge it in good time 👍

**Comment by swharden** [comment]
It looks like this has since been added

https://scottplot.net/cookbook/5.0/Styling/LineStyles/

```cs
LinePattern lp = new([2, 2, 5, 10], 0, "Custom");
```

**Comment by swharden** [comment]
Whoops, I read that too fast... re-opening this one

**Comment by swharden** [comment]
It appears this is possible using the current version of ScottPlot. I'll add a cookbook example demonstrating how to use data logger and streamer because I just noticed it's in the demo app only.

```cs
var dataLogger = myPlot.Add.DataLogger();

// simulate live data streaming in
for (int x = 0; x < 100; x++)
{
    double y = Generate.RandomWalker.Next();
    dataLogger.Add(x, y);
}

dataLogger.MarkerStyle.IsVisible = true;
dataLogger.MarkerStyle.Shape = MarkerShape.FilledCircle;
dataLogger.MarkerStyle.Size = 5;
```

![image](https://github.com/user-attachments/assets/be64760b-c857-4ca1-8db7-55d04bceb033)

**Comment by swharden** [comment]
```cs
var dataLogger = myPlot.Add.DataLogger();

// simulate live data streaming in
for (int x = 0; x < 10; x++)
{
    double y = Generate.RandomWalker.Next();
    dataLogger.Add(x, y);
}

dataLogger.LineStyle.Pattern = LinePattern.Dashed;
```

![image](https://github.com/user-attachments/assets/a7bfcbed-17c3-41c7-bf69-42cc623e917c)
