### ISSUE TITLE
Required to zoomin or zoom out at the verticale line on the graph

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#3966]
** Required to zoomin or zoom out at the verticale line on the graph:

**ScottPlot Version:5.0.33**

When zoomin(0.5,0.5), the graph area is zooming from the center of the graph. But I want to zoom in the area located near the vertical line?

**Comment by swharden** [comment]
Hi @kareem469, 

Rather than calling `ZoomIn()` I recommend calculating exactly what your new axis limits you want to be then use `SetAxisLimits()`
