### ISSUE TITLE
Cookbook: add recipe demonstrating stacked filled line chart

### ISSUE THREAD

**Issue by ghost** [ScottPlot/ScottPlot#3967]
Hi, anyone have a working ScottPlot5 code example of Stacked Filled Line Plot?  The syntax has changed, the the Scottplot 5  cookbook doesn't have this in there.   I've partially got something working, however I've had to comment out the Tools.Pad lines, and don't know what to replace them with,

This is the link to the ScottPlot 4 code:
https://scottplot.net/cookbook/4.1/recipes/polygon_stackedfilledlineplot/

This is what I have so far:
```cs

// create sample data
double[] xsa = [1, 2, 3, 4];
double[] ys1 = [1, 3, 1, 2];
double[] ys2a = [3, 7, 3, 1];
double[] ys3 = [5, 2, 5, 6];

// manually stack plots
ys2a = Enumerable.Range(0, ys2a.Length).Select(x => ys2a[x] + ys1[x]).ToArray();
ys3 = Enumerable.Range(0, ys2a.Length).Select(x => ys3[x] + ys2a[x]).ToArray();

// pad data to turn a line into a shaded region
//xsa = Tools.Pad(xsa, cloneEdges: true);
//ys1 = Tools.Pad(ys1);
//ys2a = Tools.Pad(ys2a);
//ys3 = Tools.Pad(ys3);

// plot the padded data points as polygons
plot.Plot.Add.Polygon(xsa, ys3).LineWidth = 2;
plot.Plot.Add.Polygon(xsa, ys2a).LineWidth = 2;
plot.Plot.Add.Polygon(xsa, ys1).LineWidth = 2;
```

This is the result:

![image](https://github.com/ScottPlot/ScottPlot/assets/143503522/8ee3080d-8831-496c-8bfe-7d69d768a939)

**Comment by MCF** [comment]
Scatter plots support filling under the line.  Perhaps that would be a better choice for solving this problem?

https://scottplot.net/cookbook/5.0/Scatter/ScatterFill/
https://scottplot.net/cookbook/5.0/Scatter/ScatterFillValue/
https://scottplot.net/cookbook/5.0/Scatter/ScatterFillAboveBelow/

(all scatter plot details: https://scottplot.net/cookbook/5.0/Scatter/ )

**Comment by swharden** [comment]
From #4010 

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/860b1a8a-c738-4d3f-b5a4-c64ba5a3808f)

```cs
// create sample data
double[] xs = { 1, 2, 3, 4 };
double[] ys1 = { 1, 3, 1, 2 };
double[] ys2 = { 3, 7, 3, 1 };
double[] ys3 = { 5, 2, 5, 6 };

// shift each plot vertically by the sum of all plots before it
ys2 = Enumerable.Range(0, ys2.Length).Select(x => ys2[x] + ys1[x]).ToArray();
ys3 = Enumerable.Range(0, ys2.Length).Select(x => ys3[x] + ys2[x]).ToArray();

// plot the padded data points as ScatterLine
var sp3 = myPlot.Add.ScatterLine(xs, ys3, Colors.Black);
var sp2 = myPlot.Add.ScatterLine(xs, ys2, Colors.Black);
var sp1 = myPlot.Add.ScatterLine(xs, ys1, Colors.Black);

// set plot style
sp1.LineWidth = 2;
sp2.LineWidth = 2;
sp3.LineWidth = 2;
sp1.FillY = true;
sp2.FillY = true;
sp3.FillY = true;
sp1.FillYColor = Colors.Green;
sp2.FillYColor = Colors.Orange;
sp3.FillYColor = Colors.Blue;

// use tight margins so data goes to the edge of the plot
myPlot.Axes.Margins(0, 0, 0, 0.1);
```

**Comment by CoderPM2011** [comment]
@sharden
This question should be closed.
Because PR has been merged and the questioner has disappeared.
