### ISSUE TITLE
DataLoggerSource does not have a way to reset Min/Max values

### ISSUE THREAD

**Issue by jpgarza93** [ScottPlot/ScottPlot#3969]
**Issue:** 
The [DataLoggerSource](https://github.com/ScottPlot/ScottPlot/blob/fb3b1c84af3c361bf1eb8f4286ad1d4e7038afc5/src/ScottPlot5/ScottPlot5/DataSources/DataLoggerSource.cs#L3) class lacks a method to reset Min/Max values, causing the autoscale feature to work incorrectly.

Using `dataLogger!.Data.Coordinates.RemoveAt(0);` to remove data points from a DataLogger updates render correctly, but does not update the `DataLogger.Data.(Min/Max)` values, resulting in `AvaPlot.Plot.Axes.AutoScale();` not functioning properly.

**ScottPlot Version:**
ScottPlot 5 (Avalonia UI)

**Sample:** 
In my implementation, I add points to a DataLogger every millisecond. Once the count reaches 3000, I start removing the first point and append a new one, maintaining a constant count of 3000 points (this can be changed by the user). In the image below, you can see 3000 coordinates. I stopped recording at 5079 ms, but instead of my XMin being at 2079 (the correct value), it remains at 0 (the value of the first point that no longer exists).

![image](https://github.com/ScottPlot/ScottPlot/assets/79015116/14793571-a9ec-43b7-b5c4-850e76b29412)

**Comment by swharden** [comment]
Hi @jpgarza93, thanks for reporting this!

> I could create a PR to add the following to the DataLoggerSource class?

Your solution looks like a good one! Maybe I'd rename `ClearMinMaxValues()` to `ResetMinAndMaxValues()`? Either way, if you create a PR I'd be happy to review and merge it in good time 👍
