### ISSUE TITLE
Controls: add SVG to right-click save image menu

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3979]
SVG saving is already supported, it's just not in the menu...

**Comment by VibrationAnalystCN** [comment]
right click→Save Image→**save type combobox**，you can select *.SVG

**Comment by VibrationAnalystCN** [comment]
right click→Save Image→**save type combobox**，you can select *.SVG

**Comment by swharden** [comment]
thanks for pointing that out! I don't know how I missed it 😅

https://github.com/ScottPlot/ScottPlot/blob/8f284156bb631088f579614d9e68d9f95f7a17f3/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WinForms/FormsPlotMenu.cs#L85-L96
