### ISSUE TITLE
LinearRegression: add constructor overload that accepts `IEnumerable<Coordinates>`

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3981]
... to make it easier to get a regression line from `List<Coordinates>` instead of requiring `Coordinates[]`

https://github.com/ScottPlot/ScottPlot/blob/fb3b1c84af3c361bf1eb8f4286ad1d4e7038afc5/src/ScottPlot5/ScottPlot5/Statistics/LinearRegression.cs#L14-L24

**Comment by CoderPM2011** [comment]
`Array` themselves implement the `IEnumerable` interface, so `IEnumerable<Cooperatives>` can accept `Cooperatives[]` as a parameter.
Maybe we can just change `Coordinates[]` to `IEnumerable<Coordinates>`?

**Comment by ANGADJEET** [comment]
@swharden Could you please review and approve this PR when you have a chance? It adds a new constructor to the `LinearRegression` class, allowing for easier creation of regression models from coordinate data.

**Comment by swharden** [comment]
Thanks for the tip @CoderPM2011! I modified the open PR #3982 to add this feature and it will be in the next release 🚀
