### ISSUE TITLE
Support any Key for input bindings ?

### ISSUE THREAD

**Issue by BambOoxX** [ScottPlot/ScottPlot#3984]
**Suggestion:** (Describe your idea here)

Right now, in SP5 it seems input bindings only support specific keys as modifiers for e.g. `LockHorizontalAxisKey`. These live in `ScottPlot.Control.Key`. Is there any reason why not any key should be supported. 
For instance I'd like to use the `x` key to lock zooming only in x direction.

**Comment by swharden** [comment]
Hi @BambOoxX, this type of issue is why I want to redesign the interactivity architecture. I'll close this issue and track progress in #3186
