### ISSUE TITLE
GitHub Actions: create action to close inactive draft PRs

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#3988]
if no commits in [2 weeks?] close the issue automatically with a descriptive message that says it can be re-opened by the author if/when it's ready to review

**Comment by KroMignon** [comment]
Hi @swharden, to reopen a PR you must have to right to do it!

**Comment by swharden** [comment]
> Hi @swharden, to reopen a PR you must have to right to do it!

Good to know! I won't implement this action now that I know this is the case 👍
