### ISSUE TITLE
LockedVertical WPF y values gone

### ISSUE THREAD

**Issue by santosoisman** [ScottPlot/ScottPlot#3989]
i was trying to implement LockedVertical Method to WPF because the code written on WinForm version. the code is fine and runable, but the y value is gone. i don't know what is wrong. 

This is my code:

```cs
double[] dataX = { 1, 2, 3, 4, 5 };
double[] dataY = { 1, 4, 9, 16, 25 };
MyScatter = WpfPlot1.Plot.Add.Scatter(dataX, dataY);
MyScatter.LineWidth = 0;
AxisLimits limits = WpfPlot1.Plot.Axes.GetLimits();
ScottPlot.AxisRules.LockedVertical rule = new(WpfPlot1.Plot.Axes.Left, limits.Bottom, limits.Top);
WpfPlot1.Plot.Axes.Rules.Clear();
WpfPlot1.Plot.Axes.Rules.Add(rule);
WpfPlot1.Refresh();
```

Screenshot before adding lockedvertical
![image](https://github.com/ScottPlot/ScottPlot/assets/6329233/8ed3f97f-20a9-418d-85a3-27d1968cf899)

screenshot after adding lockedvertical
![image](https://github.com/ScottPlot/ScottPlot/assets/6329233/5cd2f0ed-3741-41a8-871a-e23ec6b0356d)

When i trying to inspect value from axislimit runtime all value is  infinity 
![image](https://github.com/ScottPlot/ScottPlot/assets/6329233/c567dffb-c56c-4278-b721-3c55513a9d80)

thanks for  response in future.

**Comment by swharden** [comment]
Hi @santosoisman, thanks for this question!

I think the problem is this line:
```cs
AxisLimits limits = WpfPlot1.Plot.Axes.GetLimits();
```

If called before the first render, it will return `NaN`.

I recommend calling `WpfPlot1.Plot.Axes.AutoScale()` before this line to force the axis limits to be calculated before getting the limits. I think that will solve this issue 👍
