### ISSUE TITLE
The Plot getting out of the Plane

### ISSUE THREAD

**Issue by rajbanker986** [ScottPlot/ScottPlot#3991]
Question: I am trying to Plot a Price/Time Scatter Plot and my ScatterPlot Lines are going out of the plane

ScottPlot Version: ScottPlot.WinForms - 5.0.34

Code Sample: This is where I am adding data to Scatter, where dataX and dataY are double List

```
MyScatter = formsPlot1.Plot.Add.Scatter(dataX.ToArray(), dataY.ToArray(), MarkerColor);
MyScatter.MarkerSize = 0;
MyScatter.FillY = true;
MyScatter.FillYValue = dataY.Min();
MyScatter.FillYColor = MyScatter.Color.WithAlpha(.2);
```
Issue:
![Chart_OOB](https://github.com/ScottPlot/ScottPlot/assets/38428723/2dc725b1-a06a-4ad3-85ca-1a9b0d8e4fca)
UI Controls:
![image](https://github.com/ScottPlot/ScottPlot/assets/38428723/7465f601-b2c7-42ff-bb8d-909bca95ccad)

**Comment by swharden** [comment]
Hi @rajbanker986, this works as expected using the current version of ScottPlot

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        var MyScatter = formsPlot1.Plot.Add.Scatter(Generate.Consecutive(51), Generate.Sin(51));
        MyScatter.MarkerSize = 0;
        MyScatter.FillY = true;
        MyScatter.FillYValue = 0;
        MyScatter.FillYColor = MyScatter.Color.WithAlpha(.2);
    }
}
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/5d20560d-83ef-4f49-9631-8c375905b6b4)

I see you are not using the latest version available on NuGet. Perhaps upgrade and see if your issue is resolved?

**Comment by rajbanker986** [comment]
Hello @swharden ,

Updating scottplot.Winforms to the latest stable version helped and I resolved the issue.
Thank you for your help!
