### ISSUE TITLE
CoordinateRect: `BottomRight` has X and Y reversed

### ISSUE THREAD

**Issue by springwheat** [ScottPlot/ScottPlot#3996]
Issue: confuse the X and Y coordinates

ScottPlot Version:5.0.35

Code Sample:
```cs
public Coordinates BottomRight => new Coordinates(Right, Bottom);
```

**Comment by springwheat** [comment]
see CoordinateRect.cs

**Comment by swharden** [comment]
Thanks for reporting this @springwheat! The issue is here:
https://github.com/ScottPlot/ScottPlot/blob/a1831e5d321e577ab24ffb4add41ead12b512aff/src/ScottPlot5/ScottPlot5/Primitives/CoordinateRect.cs#L20

It should be:
```cs
 public Coordinates BottomRight => new(Right, Bottom); 
```

If someone creates a PR to fix this issue, I will merge it in good time 👍
