### ISSUE TITLE
Is there a way to refresh the data without refreshing the chart?

### ISSUE THREAD

**Issue by saklanmazozgur** [ScottPlot/ScottPlot#3998]
**Question:** I'm using a Heatmap. I plot the values ​​on the graph as I show below. When a new value arrives, the graph is not reflected on the screen without refreshing it. If the Refresh command is run on the chart, the previously made settings return to the beginning. Resetting each time a graph is drawn becomes costly. Is there an easier way to do this? I tried changing the first added value but it still needs to be refreshed. Since there is a lot of data coming in, this process needs to be as fast as possible for me.

Thank you.

**ScottPlot Version:** 5.0.34

**Code Sample:**

```cs
private void WriteHeatMap()
{
    var rand = new Random(0);
    double[,] data2D = GenerateRandom2DData(5, 4);


    var plot = HeatmapPlot.Plot;
    var plotTables = plot.PlottableList;

    if (plotTables.Count == 0)
        plot.Add.Heatmap(data2D);
    else
    {
        Heatmap value = new(data2D);
        plotTables[0] = value;
    }
    

    //HeatmapPlot.Plot.Axes.AutoScale();
    //HeatmapPlot.Refresh();
    //HeatmapPlot.Plot.Axes.Margins(0, 0);
}
```

**Comment by swharden** [comment]
Hi @saklanmazozgur, I recommend checking out the "live heatmap" demo

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/cb2de94b-7852-4acd-b3a4-af37ce613b54)

It shows the recommended way of continuously updating heatmap data

https://github.com/ScottPlot/ScottPlot/blob/9f9b1147c9b0280074f5504941a3403e6f002a30/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/HeatmapLive.cs#L1-L45
