### ISSUE TITLE
       scottPlot.Plot.Add.SignalXY(new double[0], new double[0]) Crash

### ISSUE THREAD

**Issue by githubkau** [ScottPlot/ScottPlot#4000]
scottPlot.Plot.Add.SignalXY(new double[0], new double[0]);

crashes with IndexOutOfRangeException.

Scottplot 5.0.35

**Comment by swharden** [comment]
Thanks for pointing this out @githubkau! I fixed this issue in a531cb3 and it will be in the next release 👍
