### ISSUE TITLE
Adding support for font styles

### ISSUE THREAD

**Issue by aespitia** [ScottPlot/ScottPlot#4002]
This suggestion is about adding support for font styles, i believe right now, the font manager in SP5 is hard coded to look at "normal" weight fonts, but if a font has some other settings, they won't get recognized by SP5.

For example, these are different weights supported by windows
https://learn.microsoft.com/en-us/dotnet/api/system.windows.fontweights?view=windowsdesktop-8.0

so hard coding to look for "normal" or "regular" can exclude various font families.

similar to css supporting various font-weight vs font-style.  

for example, i think sp5 has an issue with Arial Narrow
https://learn.microsoft.com/en-us/typography/font-list/arial-narrow

**Comment by swharden** [comment]
I'm in favor of adding this feature, but there hasn't been movement here in a while so I'll close this issue for now and we can take a closer look in the future. If someone wants to create a PR to add this in, I'd be happy to review it in good time!
