### ISSUE TITLE
Update lines

### ISSUE THREAD

**Issue by Aleksi-learn-code** [ScottPlot/ScottPlot#4012]
```cs
var sp1 = plt.Add.HorizontalLine(inask, 1, Colors.FireBrick, LinePattern.Solid);
var sp2 = plt.Add.HorizontalLine(inbid, 1, Colors.BlueViolet, LinePattern.Solid);
```
It adds a new line, so a new line is created with each tick. Is it possible to update lines instead of adding them anew each time? If not, is there a command to delete a specific object (line)?

**Comment by swharden** [comment]
> Is it possible to update lines instead of adding them anew each time?

Indeed! 

```cs
// add the line to the plot
var hLine1= FormsPlot1.Plot.Add.HorizontalLine(42);

// change its position later
hLine1.Y = 123;
FormsPlot1.Plot.Refresh();
```
