### ISSUE TITLE
The scatter plot on FormsPlotGL does not render correctly when the data is too dense

### ISSUE THREAD

**Issue by CoderPM2011** [ScottPlot/ScottPlot#4020]
**Issue:** FormsPlotGL does not render properly when the data is too dense.

**ScottPlot Version:** 5.0.36

**Code Sample:** In WinForms Demo - OpenGL Example

when "Data=Sine Wave, Points=1M, Type=Scatter Plot" is selected.

![image](https://github.com/ScottPlot/ScottPlot/assets/7456441/82320175-8c96-4f05-af47-ffd5d8655f7f)

When you zoom in on the plot, you can see the lines.
![image](https://github.com/ScottPlot/ScottPlot/assets/7456441/d701a416-cefe-49cf-ab3c-d829396e11c1)

**Comment by swharden** [comment]
@CoderPM2011 do you know if this is still an issue? If so let's ping StendProg since they developed the OpenGL control, and maybe they'd have a recommended fix. If not (or if it's low priority) I'm happy closing this for now, and would welcome a PR if someone figures this out 👍
