### ISSUE TITLE
Bar chart with zero value is always align in the middle of graph

### ISSUE THREAD

**Issue by charleshoong97** [ScottPlot/ScottPlot#4021]
**Issue:** (Describe the bug here)
I have created a bar chart and need the Y axis always start with 0, the max value is dynamic.
Using the solution of Plot.Axes.Margins(bottom: 0, top: 1).
It is looking fine whenever there is some value for each of the bar chart.

But once there is no value for each of the bar, which is 0, it started to show negative value at Y Axis.

With value in bar chart:
![image](https://github.com/ScottPlot/ScottPlot/assets/45910910/d414be68-40c0-4c3a-9758-78b179b7b5ee)

With 0 value in bar chart:
![image](https://github.com/ScottPlot/ScottPlot/assets/45910910/aa840f99-43e4-427d-9e80-14eda7139098)

**ScottPlot Version:** (What NuGet package are you using?)
5.0.36

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
Plot.Axes.Margins(bottom: 0, top: 1);
```

**Comment by charleshoong97** [comment]
> > I have created a bar chart and need the Y axis always start with 0, the max value is dynamic.
> > Using the solution of Plot.Axes.Margins(bottom: 0, top: 1).
> 
> Why do you use `Margins()` and not `Limits()`?
> 
> ```cs
> Plot.Axes.AutoScaleX();  // auto scaling the X axis
> Plot.Axes.SetLimitsY(0, 5); // force scaling for the Y axis
> ```
> 
> cf https://scottplot.net/cookbook/5.0/AxisAndTicks/

This solution is only worked if you know your upperlimits.

**Comment by KroMignon** [comment]
> This solution is only worked if you know your upperlimits.

They are easy to find with `ScottPlot`, you only have to use `GetDataLimits()` or yourself get min / max value while filling the graph.
```csharp
Plot.Axes.AutoScaleX();  // auto scaling the X axis
var limits = Plot.Axes.GetDataLimits();
if (limits.Bottom < limits.Top)
   Plot.Axes.SetLimitsY(limits.Bottom, limits.Top); // use data limits when they are not equal
else
   Plot.Axes.SetLimitsY(0, 1); // force scaling for the Y axis when all data are 0
```
