### ISSUE TITLE
Alternately color the spaces between the grids

### ISSUE THREAD

**Issue by seeingistrue** [ScottPlot/ScottPlot#4022]
**Question:** (Ask your question here)
After directly modifying GridStyle.cs and confirming that the filled rectangle was drawn, I modified three files. I created IsVisibleHorizontalSpan and IsVisibleVerticalSpan in DefaultGrid.cs and changed the properties using the calling code in DraggableAxisLines.cs, but it does not work. The code for drawing the rectangle is in GridStyle.cs. What went wrong? Please understand that this is not a well-made code.
This is my first time writing an issue, so I don't know if it's right to write like this. Please let me know if there are any mistakes.
**ScottPlot Version:** (What NuGet package are you using?)
5.0.34
**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

[GridStyle.zip](https://github.com/user-attachments/files/16050128/GridStyle.zip)

**Comment by CoderPM2011** [comment]
I tried to write this in ScottPlot 5.0.36.

I modified `Render()` in `GridStyle.cs`.

I added `RenderGridBackground(rp, xTicksMajor, axis.Edge);` before `RenderGridLines(rp, xTicksMajor, axis.Edge, MajorLineStyle);`

```csharp
private static void RenderGridBackground(
    RenderPack rp, float[] positions, Edge edge)
{
    var starts = new List<Pixel>();
    var ends = new List<Pixel>();

    var pos = new List<float>(positions)
    {
           edge.IsHorizontal()
               ? rp.DataRect.Left
               : rp.DataRect.Bottom,
           edge.IsHorizontal()
               ? rp.DataRect.Right
               : rp.DataRect.Top
    };

    pos.Sort();
    for (int i = 0; i < pos.Count; i++)
    {
        float px = pos[i];

        starts.Add(edge.IsHorizontal()
            ? new Pixel(px, rp.DataRect.Bottom)
            : new Pixel(rp.DataRect.Left, px));

        ends.Add(edge.IsHorizontal()
            ? new Pixel(px, rp.DataRect.Top)
            : new Pixel(rp.DataRect.Right, px));
    }

    for (int i = 1; i < starts.Count; i++)
    {
        if (i % 2 == 0)
        {
            continue;
        }

        Drawing.FillRectangle(
            rp.Canvas,
            new PixelRect(starts[i - 1], ends[i]),
            Colors.Yellow.WithOpacity(0.3));
    }
}
```

The result is like this
![image](https://github.com/ScottPlot/ScottPlot/assets/7456441/ef3f033c-65bc-4836-b92b-ef7c87d05b41)

**Comment by seeingistrue** [comment]
I tried being able to select horizontal, vertical or none, but it didn't work. What I really need is a horizontal background.
![image](https://github.com/ScottPlot/ScottPlot/assets/67356950/fe89908e-9cfd-4035-9234-61d6fc0094d4)

**Comment by seeingistrue** [comment]
The code of DraggableAxisLines.cs was modified and implemented as follows.
![image](https://github.com/ScottPlot/ScottPlot/assets/67356950/415ebcaa-351d-4999-a19d-cebcbbd5d671)
``
        formsPlot1.Plot.Grid.IsVisibleVerticalSpan = false;
	formsPlot1.Plot.Grid.IsVisibleHorizontalSpan = true;
	formsPlot1.Plot.Grid.SpanColor = ScottPlot.Color.FromColor(System.Drawing.Color.FromArgb(10, 0, 0, 255));

``

**Comment by seeingistrue** [comment]
@CoderPM2011 
I didn't know you had given me the full answer, so I was looking for an easy way, but I couldn't, so I tested the code you posted and it works fine. Thank you.

**Comment by swharden** [comment]
I'm merging in #4201 now so things like this will be possible in the next release:

```cs
// add a green data line
var sig = myPlot.Add.Signal(Generate.SquareWaveFromSines());
sig.LineWidth = 3;
sig.Color = new("#2b9433");
sig.AlwaysUseLowDensityMode = true;

// give the plot a dark background with light text
myPlot.FigureBackground.Color = new("#1c1c1e");
myPlot.Axes.Color(new("#888888"));

// shade regions between major grid lines
myPlot.Grid.XAxisStyle.FillColor1 = new Color("#888888").WithAlpha(10);
myPlot.Grid.YAxisStyle.FillColor1 = new Color("#888888").WithAlpha(10);

// set grid line colors
myPlot.Grid.XAxisStyle.MajorLineStyle.Color = Colors.White.WithAlpha(15);
myPlot.Grid.YAxisStyle.MajorLineStyle.Color = Colors.White.WithAlpha(15);
myPlot.Grid.XAxisStyle.MinorLineStyle.Color = Colors.White.WithAlpha(5);
myPlot.Grid.YAxisStyle.MinorLineStyle.Color = Colors.White.WithAlpha(5);

// enable minor grid lines by defining a positive width
myPlot.Grid.XAxisStyle.MinorLineStyle.Width = 1;
myPlot.Grid.YAxisStyle.MinorLineStyle.Width = 1;
```

![GridAlternatingDarkMode](https://github.com/user-attachments/assets/9e897279-d86e-4d04-a2a1-e8174f30709d)
