### ISSUE TITLE
The .NET Maui control fails to display in the sandbox app

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4023]
A .NET Maui ScottPlot package was recently published
* https://www.nuget.org/packages/ScottPlot.Maui/5.0.36
* #4013

It would be really helpful if someone could provide a quickstart guide demonstrating the minimum steps necessary to use it in a new .NET Maui application. Here's the Avalonia quickstart for reference https://scottplot.net/quickstart/avalonia/

If the steps are posted here as a GitHub issue, I can add them to the website in good time 👍

**Comment by ByteSore** [comment]
[MauiQuickstart](https://scottplot.net/quickstart/maui/#maui-quickstart)
Step 1: Install the [ScottPlot.Maui](https://www.nuget.org/packages/ScottPlot.Maui) NuGet package. Linux & MacOS users must take [these additional steps](https://scottplot.net/faq/dependencies).

Step 2: Import the ScottPlot.Maui namespace by adding this to your Window element:

xmlns:ScottPlot="clr-namespace:ScottPlot.Maui;assembly=ScottPlot.Maui"
Your Window element should look something like this:

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        ...
        xmlns:ScottPlot="clr-namespace:ScottPlot.Maui;assembly=ScottPlot.Maui"
>
Step 3: Add a MauiPlot to your layout and give it a unique name

<ScottPlot:MauiPlot x:Name="MauiPlot1" />
Step 4: Plot some data in your start-up sequence

double[] dataX = { 1, 2, 3, 4, 5 };
double[] dataY = { 1, 4, 9, 16, 25 };

MauiPlot1.Plot.Add.Scatter(dataX, dataY);
MauiPlot1.Refresh();

![image](https://github.com/ScottPlot/ScottPlot/assets/376912/6e1168f7-42b1-450b-9914-760c63ce828f)

**Comment by swharden** [comment]
Hi @ByteSore, thanks for following up!

Unfortunately I just can not seem to get this to work 😩 I think I'm doing something really basic that's wrong

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/80db3117-962c-48aa-ad21-89f15861a965)

If it's working in a new .NET MAUI app on your machine, can you share the full `.xaml` and `.xaml.cs` files you're using?

**Comment by swharden** [comment]
The problem may be that `MauiPlot` is a `ContentPage` and perhaps it should be something else?

**Comment by swharden** [comment]
Is this the problem?

https://github.com/ScottPlot/ScottPlot/blob/f1a7b316b1fae08d0ffbdb943bed987629f8bf73/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.Maui/MauiPlot.cs#L82

**Comment by atanubanerjee** [comment]
Hey Scott, thanks for creating ScottPlot! 

I'm trying to use ScottPlot in a .Net Maui app, and getting this same error message with similar code to what's in this issue above. The inner exception is:  InvalidOperationException: Parent of a Page must also be a Page.

Were you able to resolve this, and if so then what should I do to get past this?

**Comment by swharden** [comment]
HI @atanubanerjee, I never figured this one out 😩 

It was super disappointing closing #4065 and https://github.com/ScottPlot/ScottPlot.NET/pull/38 today

Did you make any progress? If we could just figure out this one error message, I'd LOVE to add a QuickStart to the site and a sandbox demo to the main repository! Since I can't even get it to run on my own computer, I don't feel right putting it out there in its present state.

@ByteSore made some encouraging progress (especially in #4065) but our communication stopped just short of having an application I could run

If you or anyone has advice for how to resolve this error and use ScottPlot in a Maui app, I'd love to learn more about how it was done!

**Comment by christianzech** [comment]
Hi @swharden,

I also want to use ScottPlot in a Maui App and run into the same problem. 

> The problem may be that `MauiPlot` is a `ContentPage` and perhaps it should be something else?
I think so. When `MauiPlot` is a `ContentPage`, it will always be _fullscale_ and cannot be added as a control to other pages.
> A page usually occupies all of the screen, or window

I simply changed `ContentPage` to `ContentView`, uncommented line 82 (from your previous post) and added the rendering
` _canvas.PaintSurface += (s, e) =>
 {
     float width = (float)e.Surface.Canvas.LocalClipBounds.Width;
     float height = (float)e.Surface.Canvas.LocalClipBounds.Height;
     PixelRect rect = new(0, width, height, 0);
     Plot.Render(e.Surface.Canvas, rect);
 };`
and the plot is shown as expected inside any page (also in the sandbox app) :)

Whats still missing:
-   scaling 
At least for Android (my case) you cannot read anything in the plot. I still did not understand when and what `DisplayScale` and `DetectDisplayScale()` are used for, changing the values does not help. Setting `Plot.ScaleFactor` solves the problem.
- interaction
You cannot pan, zoom,...

**Comment by swharden** [comment]
https://scottplot.net/quickstart/maui/
