### ISSUE TITLE
How to draw a minute curve using futures data (time series)

### ISSUE THREAD

**Issue by chrisli8899** [ScottPlot/ScottPlot#4024]
**Question:** (Ask your question here)
I want to draw a minute curve using futures prices, but futures prices have both night and day trading data. The dates are not on the same day, and there is a break in between, so the market data cannot be continuous. How can we connect these multiple market segments without any gaps in between? The market opening time is:
21:00-2:30 (next day)
09:00-10:15
10:30-11:30
13:30-15:00
﻿
**ScottPlot Version:** (What NuGet package are you using?)

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples
The market data is displayed as follows：（time,minute data）
21:00,626.6
21:01,626.4
21:02,626.8
21:03,626.6
21:04,627,6
21:05,626.6
21:06,626.7
21:07,626.8
21:08,626.9
21:09,626.9
21:10,626.8
21:11,626.8
21:12,626.3
21:13,625.7
21:14,625.6
21:15,625.2
21:16,624.9
21:17,625.1
21:18,625.2
21:19,624.9
21:20,625.2
21:21,625.5
21:22,625.4
21:23,625.4
21:24,625.3
21:25,625.2
21:26,625.1
21:27,625.3
21:28,625.2
21:29,625.6
21:30,625.4
21:31,625.6
21:32,625.3
21:33,624.8
21:34,624.8
21:35,625.4
21:36,624.9
21:37,624.6
21:38,624.5
21:39,624.5
21:40,624.5
21:41,624.2
21:42,624.5
21:43,624,6
21:44,623.5
21:45,623.4
21:46,623.5
21:47,623.5
21:48,622.7
21:49,622.9
21:50,623.1
21:51,623.7
21:52,624.1
21:53,623.8
21:54,623.5
21:55,623.3
21:56,623.3
21:57,623.1
21:58,622.8
21:59,622.1
22:00,622,6
22:01,622.3
22:02,621.6
22:03,621.5
22:04,621.2
22:05,621.4
22:06,621.1
22:07,621.7
22:08,622.1
22:09,621.5
22:10,621.9
22:11,621.6
22:12,621.3
22:13,620.8
22:14,620.9
22:15,620.3
22:16,619.5
22:17,619.6
22:18,620.1
22:19,620.2
22:20,619.8
22:21,620.3
22:22,620.2
22:23,620.5
22:24,620.3
22:25,620.1
22:26,620.3
22:27,620.8
22:28,620.6
22:29,620.5
22:30,620.6
22:31,620.5
22:32,620.6
22:33,620.3
22:34,620.6
22:35,621,6
22:36,621.1
22:37,621.3
22:38,620.8
22:39,621.1
22:40,620.7
22:41,620.9
22:42,620.7
22:43,620.5
22:44,620.7
22:45,621.3
22:46,621.7
22:47,622.1
22:48,622,6
22:49,622,6
22:50,621.6
22:51,621.8
22:52,621.8
22:53,621.9
22:54,622.1
22:55,621.9
22:56,622,6
22:57,621.8
22:58,622,6
22:59,622.1
23:00,621.7
23:01,621.8
23:02,621.9
23:03,622.2
23:04,622.1
23:05,621.9
23:06,621.8
23:07,621.4
23:08,621.3
23:09,621.2
23:10,621.4
23:11,621.7
23:12,621.9
23:13,621.9
23:14,621.6
23:15,621.4
23:16,621.4
23:17,621.4
23:18,621.6
23:19,621.8
23:20,621.8
23:21,622.2
23:22,622.1
23:23,622.6
23:24,622.5
23:25,622.4
23:26,622.1
23:27,622.4
23:28,622.3
23:29,621.4
23:30,621.3
23:31,621.3
23:32,620.6
23:33,620.4
23:34,620.6
23:35,620.9
23:36,621.5
23:37,621.3
23:38,621.7
23:39,621.9
23:40,621.8
23:41,621.8
23:42,621.9
23:43,622,6
23:44,621.9
23:45,621.8
23:46,621.8
23:47,622.1
23:48,622.4
23:49,622.4
23:50,622.3
23:51,622,6
23:52,621.8
23:53,621.9
23:54,621.7
23:55,622.1
23:56,622.3
23:57,622.4
23:58,622.4
23:59,622.6
00:00,622.5
00:00,622.6
00:01,622.7
00:02,622.6
00:03,622.5
00:04,622.4
00:05,623.3
00:06,623.2
00:07,623.2
00:08,623,6
00:09,623.1
00:10,623.2
00:11,623.4
00:12,623.1
00:13,623.3
00:14,623.4
00:15,623.6
00:16,624.2
00:17,624,6
00:18,623.8
00:19,623.4
00:20,623.6
00:21,623.3
00:22,623.1
00:23,623.1
00:24,623.3
00:25,623.1
00:26,623.3
00:27,622.8
00:28,623,6
00:29,622,6
00:30,622.2
00:31,622.3
00:32,621.7
00:33,621.3
00:34,621.2
00:35,620.9
00:36,621.2
00:37,621.1
00:38,620.9
00:39,620.6
00:40,621.1
00:41,620.7
00:42,620.7
00:43,620.7
00:44,620.8
00:45,621.2
00:46,621.3
00:47,621.5
00:48,621.7
00:49,621.5
00:50,621.4
00:51,621.7
00:52,621.5
00:53,621.5
00:54,621.4
00:55,621.1
00:56,621.3
00:57,621.5
00:58,621.3
00:59,621.3
01:00,620.7
01:01,621.1
01:02,621.1
01:03,621.2
01:04,621.2
01:05,621.5
01:06,621.3
01:07,621.3
01:08,621.4
01:09,621.7
01:10,621.9
01:11,621.8
01:12,621.5
01:13,621.7
01:14,621.7
01:15,622,6
01:16,622.1
01:17,622.3
01:18,622.3
01:19,622.2
01:20,622,6
01:21,622,6
01:22,622.1
01:23,622,6
01:24,622.1
01:25,622.2
01:26,622,6
01:27,622,6
01:28,621.8
01:29,621.8
01:30,622.1
01:31,621.9
01:32,622,6
01:33,621.9
01:34,621.8
01:35,621.8
01:36,621.7
01:37,621.9
01:38,621.9
01:39,622,6
01:40,622.1
01:41,622,6
01:42,622,6
01:43,622.1
01:44,621.9
01:45,622.3
01:46,622.2
01:47,622.3
01:48,622.1
01:49,622.2
01:50,622.1
01:51,621.9
01:52,621.8
01:53,621.9
01:54,621.7
01:55,621.6
01:56,621.6
01:57,621.7
01:58,621.7
01:59,621.6
02:00,621.5
02:01,621.3
02:02,621.6
02:03,621.7
02:04,621.6
02:05,621.6
02:06,621.9
02:07,622.3
02:08,622.1
02:09,622,6
02:10,622.3
02:11,622.7
02:12,622.7
02:13,622.5
02:14,622.3
02:15,622.3
02:16,621.8
02:17,621.8
02:18,622,6
02:19,622.2
02:20,622,6
02:21,621.7
02:22,621.9
02:23,621.8
02:24,621.6
02:25,621.8
02:26,621.5
02:27,621.7
02:28,621.2
02:29,621.6
02:30,621.6
08:59,622.8
09:00,623.6
09:01,623.8
09:02,623.7
09:03,623.7
09:04,624.2
09:05,624,6
09:06,624.2
09:07,624.2
09:08,624.6
09:09,624.9
09:10,624.8
09:11,624.6
09:12,624.2
09:13,624.3
09:14,624.4
09:15,624.3
09:16,624.4
09:17,624.2
09:18,624.1
09:19,623.8
09:20,624.2
09:21,623.9
09:22,623.8
09:23,624.2
09:24,624.1
09:25,624.2
09:26,624.2
09:27,624,6
09:28,624.2
09:29,624.2
09:30,624.1
09:31,624.1
09:32,624.3
09:33,624.2
09:34,624.2
09:35,624.1
09:36,624.2
09:37,624.6
09:38,624.5
09:39,624.2
09:40,624.4
09:41,624.4
09:42,624.2
09:43,623.9
09:44,623.8
09:45,623.9
09:46,624,6
09:47,624.2
09:48,624.2
09:49,624.2
09:50,624.2
09:51,624.4
09:52,624.4
09:53,624.4
09:54,624.4
09:55,624.5
09:56,624.5
09:57,624.4
09:58,624.5
09:59,624.5
10:00,624.5
10:01,624.3
10:02,624.1
10:03,624.1
10:04,624.2
10:05,624,6
10:06,624.2
10:07,624.2
10:08,624.4
10:09,624.6
10:10,624.5
10:11,624.6
10:12,624.7
10:13,624.8
10:14,624.8
10:15,624.8
10:30,624.9
10:31,624.8
10:32,625.1
10:33,624.9
10:34,625,6
10:35,624.8
10:36,624.8
10:37,624.8
10:38,624.7
10:39,624.7
10:40,624.6
10:41,624.7
10:42,624.8
10:43,624.7
10:44,624.8
10:45,624.8
10:46,624.6
10:47,624.7
10:48,624.6
10:49,624.5
10:50,624.4
10:51,624.4
10:52,624.6
10:53,624.5
10:54,624.6
10:55,624.6
10:56,624.7
10:57,624.8
10:58,624.8
10:59,624.7
11:00,624.7
11:01,624.7
11:02,624.5
11:03,624.7
11:04,624.8
11:05,624.8
11:06,624.8
11:07,624.9
11:08,625.1
11:09,625.4
11:10,625.7
11:11,626.1
11:12,626.1
11:13,626.2
11:14,626.2
11:15,626.1
11:16,626.2
11:17,625.9
11:18,626,6
11:19,626,6
11:20,626,6
11:21,625.9
11:22,625.7
11:23,625.8
11:24,625.7
11:25,625.7
11:26,625.6
11:27,625.5
11:28,625.5
11:29,625.8
11:30,625.8
13:30,625.7
13:31,625.6
13:32,625.8
13:33,625.8
13:34,625.9
13:35,625.8
13:36,626,6
13:37,626.1
13:38,626.2
13:39,626,6
13:40,626,6
13:41,625.9
13:42,626,6
13:43,626,6
13:44,626.5
13:45,626.3
13:46,625.9
13:47,626,6
13:48,626.1
13:49,626,6
13:50,626,6
13:51,626.2
13:52,626.4
13:53,626.2
13:54,626.1
13:55,626.2
13:56,626.1
13:57,626.2
13:58,626.4
13:59,626.3
14:00,626.5
14:01,626.2
14:02,626.2
14:03,626.3
14:04,626.2
14:05,625.9
14:06,626,6
14:07,626.4
14:08,626.5
14:09,626.4
14:10,626.5
14:11,626.4
14:12,626.6
14:13,626.6
14:14,626.5
14:15,626.6
14:16,626.6
14:17,626.5
14:18,626.5
14:19,626.5
14:20,626.4
14:21,626.5
14:22,626.5
14:23,626.6
14:24,626.8
14:25,626.9
14:26,626.5
14:27,626.3
14:28,626.5
14:29,626.5
14:30,626.5
14:31,626.5
14:32,626.6
14:33,626.6
14:34,626.9
14:35,626.8
14:36,626.8
14:37,626.8
14:38,626.7
14:39,626.6
14:40,626.5
14:41,626.7
14:42,626.9
14:43,626.9
14:44,626.9
14:45,626.7
14:46,626.8
14:47,626.7
14:48,626.9
14:49,627,6
14:50,626.8
14:51,627,6
14:52,626.9
14:53,626.8
14:54,626.9
14:55,626.7
14:56,626.9
14:57,626.7
14:58,626.7
14:59,626.8
15:00,626.9

```cs
 formsPlot1 = new ScottPlot.WinForms.FormsPlot();
 Controls.Add(formsPlot1);
 formsPlot1.Name = "formsPlot1";
 formsPlot1.Location = new Point(131, 130);
 formsPlot1.Size = new Size(700, 400);
 formsPlot1.TabIndex = 2;
 myPlot = formsPlot1.Plot;
 myPlot.Axes.Left.IsVisible = false;
 myPlot.Axes.Top.IsVisible = false;

 myPlot.Clear();
 var today = DateTime.Now.ToString("yyyyMMdd");
 var fileName = @"D:\PriceTool\data\" + today + @"\sc2408.txt";

 var list = File.ReadAllLines(fileName).ToList();
 list.ForEach(line =>
 {
     var obj = line.Split(',');
     if (DateTime.TryParse(obj[0], out var time))
     {
         dataX.Add(time.ToOADate());
         dataY.Add(double.Parse(obj[1]));
     }
 });
 var myScatter = myPlot.Add.ScatterLine(dataX, dataY);
 myScatter.Axes.YAxis = myPlot.Axes.Right;

 var dtTickAxis = myPlot.Axes.DateTimeTicksBottom();
 if (dtTickAxis.TickGenerator is DateTimeAutomatic dtautoMatic)
 {
     dtautoMatic.LabelFormatter = date => date.ToString("HH:mm");
 }
 formsPlot1.Refresh();
```
![Plot](https://github.com/ScottPlot/ScottPlot/assets/39580381/98f8d41c-9d64-4835-9d77-eb9d9b1e089b)

**Comment by KroMignon** [comment]
Hello @chrisli8899,
perhaps you should better use `ScatterPlot` to be able to add gaps by add `NaN` values (https://scottplot.net/cookbook/5.0/Scatter/ScatterWithGaps/)

```csharp
 formsPlot1 = new ScottPlot.WinForms.FormsPlot();
 Controls.Add(formsPlot1);
 formsPlot1.Name = "formsPlot1";
 formsPlot1.Location = new Point(131, 130);
 formsPlot1.Size = new Size(700, 400);
 formsPlot1.TabIndex = 2;
 myPlot = formsPlot1.Plot;
 myPlot.Axes.Left.IsVisible = false;
 myPlot.Axes.Top.IsVisible = false;

 myPlot.Clear();
 var today = DateTime.Now.ToString("yyyyMMdd");
 var fileName = @"D:\PriceTool\data\" + today + @"\sc2408.txt";

 var list = File.ReadAllLines(fileName).ToList();
 var gapTime = DateTime.Today.AddHours(9);
 list.ForEach(line =>
 {
    var obj = line.Split(',');
    if (DateTime.TryParse(obj[0], out var time))
    {
        // everything old than 15:00 is from the day before
        if (time.Hours > 15)
            dataX.Add(time.AddDays(-1).ToOADate());
        else
        {
            if (time >= gapTime)
            {
                dataX.Add(gapTime.AddSeconds(-1).ToOADate());
                dataY.Add(double.NaN);
                
                // select next gap
                if(gapTime.Hours == 9)
                    gapTime = DateTime.Today.AddHours(10).AddMinutes(30);
                else if(gapTime.Hours == 10)
                    gapTime = DateTime.Today.AddHours(13).AddMinutes(30);
                else
                    gapTime = DateTime.Today.AddHours(24);
            }

            dataX.Add(time.ToOADate());
        }
        dataY.Add(double.Parse(obj[1]));
    }
 });
 var myScatter = myPlot.Add.Scatter(dataX, dataY);
 myScatter.Axes.YAxis = myPlot.Axes.Right;

 var dtTickAxis = myPlot.Axes.DateTimeTicksBottom();
 if (dtTickAxis.TickGenerator is DateTimeAutomatic dtautoMatic)
 {
     dtautoMatic.LabelFormatter = date => date.ToString("HH:mm");
 }
 formsPlot1.Refresh();
```

**Comment by KroMignon** [comment]
@chrisli8899 sorry, I don't know how to do this with `ScottPlot`, I think it should be possible.
Perhaps someone else could help.

**Comment by swharden** [comment]
https://scottplot.net/cookbook/5.0/Scatter/ScatterWithGaps/
