### ISSUE TITLE
SP5 QualityMode LowWhileDragging

### ISSUE THREAD

**Issue by wsxiongguozheng** [ScottPlot/ScottPlot#4026]
**Question:** (SP5：How to set  QualityMode  LowWhileDragging,Because my scatter has a lot of points, causing the drag to stall )

**ScottPlot Version:** (5.0.36)

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
ScottPlot.Plot myPlot = new();
List<double> xs = new List<double>();
List<double> ys = new List<double>();
Random rand = new Random();
for (int i = 0; i < 100000; i++)
{
    xs.Add(i);
    ys.Add(rand.NextDouble());
}
formsPlot1.Plot.Add.Scatter(xs, ys);   
/* a code sample may improve communication */
myPlot.SavePng("bug.png");
```

**Comment by swharden** [comment]
Hi @wsxiongguozheng, 

In ScottPlot 4 the "low quality while dragging" worked by disabling anti-aliasing which significantly sped-up how System.Drawing rendered graphics.

ScottPlot 5 uses SkiaSharp (not System.Drawing) and it doesn't seem to be much affected by Anti-Aliasing. 

If you want to try to recreate this effect anyway, you could use MouseDown and MouseUp events to toggle anti-aliasing like this:

```cs
var myScatterPlot = formsPlot1.Plot.Add.Scatter(xs, ys);   
myScatterPlot.LineStyle.AntiAlias = false;
```
