### ISSUE TITLE
Facing issue while dragging FormPlot on Winform

### ISSUE THREAD

**Issue by TechDeeptiBhardwaj** [ScottPlot/ScottPlot#4029]
**Issue:** System.DllNotFoundException: Unable to load library 'libSkiaSharp'.

**ScottPlot Version:** (5.0.36)

**Code Sample:** NA

Hi Team, 
After adding the ScottPlot nuget package on my project, I am trying to drag the FormsPlot on the user control ,But I am getting the error everytime "System.DllNotFoundException: Unable to load library 'libSkiaSharp'.".
![image](https://github.com/ScottPlot/ScottPlot/assets/147032012/9b1f26ed-9505-4973-96d3-714eb07ab27c)
Kindly lookinto it and let me know how to resolve as I am new to this.
Thanks
Deepti

**Comment by KennyTK** [comment]
Skiasharp is a dependency of Scott Plot. Related https://github.com/ScottPlot/ScottPlot/issues/3300

**Comment by swharden** [comment]
This took a REALLY long time to get right, but we finally got to the bottom of it (#4425, #4362) and it should work better in the next release!

In the meantime, plots may be added to WinForms apps programmatically in situations where Visual Studio can't handle loading assemblies that depend on SkiaSharp: 
https://scottplot.net/faq/add-winforms-programmatically/
