### ISSUE TITLE
SP5 : why not SignalXY can use changing list,like scatter?

### ISSUE THREAD

**Issue by wsxiongguozheng** [ScottPlot/ScottPlot#4030]
**Suggestion:** (Describe your idea here)

```cs
ScottPlot.Plot myPlot = new();
/* a code sample may improve communication */
myPlot.SavePng("bug.png");
```

**Comment by swharden** [comment]
The demo app has two interactive SignalXY examples that should help provide the information needed to achieve this.

Also the draggable scatter line demo is useful to refer to: https://scottplot.net/demo/5.0/#draggable-data-points
