### ISSUE TITLE
When dragging the mouse over the axis area, how do I zoom in and out based on the mouse down point?

### ISSUE THREAD

**Issue by seeingistrue** [ScottPlot/ScottPlot#4031]
**Question:** (Ask your question here)
How do I zoom in and out based on the mouse down point when dragging the mouse over each axis area?

**ScottPlot Version:** (What NuGet package are you using?)
5.0.34

**Comment by swharden** [comment]
I believe this feature has since been added...

Left-click-drag an axis to pan, right-click-drag an axis to zoom 👍
