### ISSUE TITLE
about Scatter with Gaps

### ISSUE THREAD

**Issue by chrisli8899** [ScottPlot/ScottPlot#4032]
**Question:** (Ask your question here)

about Scatter with Gaps,how can we ignore the scale of empty data in the middle? Connect the lines on both sides into a single line，Please refer to the attachment.

**ScottPlot Version:** (What NuGet package are you using?)
last ScottPlot5 
**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
ScottPlot.Plot myPlot = new();
double[] xs = Generate.Consecutive(51);
double[] ys = Generate.Sin(51);

// long stretch of empty data
for (int i = 10; i < 20; i++)
    ys[i] = double.NaN;

// single missing data point
ys[30] = double.NaN;

// single floating data point
for (int i = 35; i < 40; i++)
    ys[i] = double.NaN;
for (int i = 40; i < 45; i++)
    ys[i] = double.NaN;

myPlot.Add.Scatter(xs, ys);

myPlot.SavePng("bug.png");
```

![tt](https://github.com/ScottPlot/ScottPlot/assets/39580381/7e576001-a3b1-473d-8eb8-3804376d4631)

**Comment by KroMignon** [comment]
@chrisli8899 the purpose of Scatter with Gaps **is to have those gaps**.

If you don't want to have them, do not insert NaN values, that's all!

**Comment by chrisli8899** [comment]
I'm sorry for not clarifying my requirements. What I meant was Buttom, x-axis, skipping these scales.
Please refer to the attachment.
thanks.
![ss](https://github.com/ScottPlot/ScottPlot/assets/39580381/446463b9-3a02-41b6-9a85-76c8ea29070b)

**Comment by chrisli8899** [comment]
Perhaps the example I provided above is not very good, please take a look at another example.
https://github.com/ScottPlot/ScottPlot/issues/4024
