### ISSUE TITLE
Unable to access Source property of VectorField class (property has no access modifier)

### ISSUE THREAD

**Issue by lePask** [ScottPlot/ScottPlot#4035]
**Issue:** I want to access the Source property of a VectorField object in order to use the GetNearest method. Since the Source property has no access modifier I can't access it because it is not public.
I'm doing the same thing for a Scatter plot and a SignalXY plot to obtain the nearest point to the mouse position but for a VectorField I'm unable to do it.
I looked in the code and I think the issue is in the missing access modifier for the Source property in the VectorField class. 
<img width="213" alt="image" src="https://github.com/ScottPlot/ScottPlot/assets/19227553/7011524c-6203-46f0-a336-16bd480af7b2">

The Data property in the Scatter class is public and I can access it to call the GetNearest method.
<img width="197" alt="image" src="https://github.com/ScottPlot/ScottPlot/assets/19227553/24fefeb3-49e7-471a-911c-940cf2a9fa5d">
The Data properrt in the SignalXY class is public and I can access it to call the GetNearest method.
<img width="235" alt="image" src="https://github.com/ScottPlot/ScottPlot/assets/19227553/97c38a49-93cb-4c22-ab30-4725fb0b51e0">

**ScottPlot Version:**5.0.36.0

**Comment by swharden** [comment]
> I looked in the code and I think the issue is in the missing access modifier for the Source property in the VectorField class.

On one hand, I'd be happy to merge a pull request that makes these properties public:

https://github.com/ScottPlot/ScottPlot/blob/01515636bc830aeb30c5d651f32270c553eddafc/src/ScottPlot4/ScottPlot/Plottable/VectorField.cs#L14-L16

On the other hand, users must create a `List<RootedCoordinateVector>` and pass it in when calling `Add.VectorField()` so they should already have access to that object so they can probably iterate its contents without requiring making it public inside the VectorField itself
