### ISSUE TITLE
Scatter with DateTime on both X and Y

### ISSUE THREAD

**Issue by MultipleCircles** [ScottPlot/ScottPlot#4038]
**Question:**
I need to make plots where both the X and Y axis are DateTime types.

X-axis, easy: myPlot.Axes.DateTimeTicksBottom();

Y-axis, well -- the AI bot on the main site pointed me to using myPlot.Axes.DateTimeTicksLeft() when i asked it, but that doesn't seem to exist.

What would I need to do to have Y-axis display DateTime as well?

**ScottPlot Version:**
ScottPlot.WPF 5.0.36

**Code Sample:** (directly from AI bot -- .DateTimeTicksLeft() doesn't seem to exist)

```cs
// Create a ScottPlot plot instance
ScottPlot.Plot myPlot = new ScottPlot.Plot();

// Generate your DateTime data
DateTime[] dates = Generate.ConsecutiveDays(100);
double[] ys = Generate.RandomWalk(100);

// Add the scatter plot
myPlot.Add.Scatter(dates, ys);

// Customize the DateTime ticks on the Y-axis
var dtAx = myPlot.Axes.DateTimeTicksLeft(); // or DateTimeTicksRight()

// Save the plot as an image
myPlot.SavePng("demo.png", 400, 300);
```

**Comment by MultipleCircles** [comment]
This seems like it's working as a substitute for .DateTimeTicksLeft():

`myPlot.Axes.Left.TickGenerator = new ScottPlot.TickGenerators.DateTimeAutomatic();`

**Comment by DDiggs91** [comment]
It seems like that we would benefit from introducing a DateTimeYAxis.cs to mirro DateTimeXAxis.cs, then implementing a DateTimeTicksLeft() as requested.
Can I implement? @swharden

**Comment by swharden** [comment]
> It seems like that we would benefit from introducing ... `DateTimeYAxis` and `DateTimeTicksLeft()`

I agree! I will be happy to review and merge a PR in good time. There hasn't been movement here in a while though so I'll close this issue for now 👍
