### ISSUE TITLE
How to monitor the position of the mouse double-click?

### ISSUE THREAD

**Issue by xinRedi** [ScottPlot/ScottPlot#4042]
Hello author, I have many axes now, and I want to achieve an effect. If I double-click on the second left axis, a lot of information such as the color, width and scale of this axis will pop up, I can read the axis information, but I cannot monitor the position of the mouse double-click. I have considered obtaining the pixel clicked at the moment, and then obtaining the pixel width and position of the Y axis. I am trying to determine whether it is within the pixel range of Y axis, but I failed because I could not get the pixel of Y axis. Could you please provide a case?

![123123](https://github.com/ScottPlot/ScottPlot/assets/82932045/f1317dc6-dd1f-45aa-a3af-e3072ab35773)

**Comment by swharden** [comment]
Hi @xinRedi, thanks for this question! Can you clarify exactly where you're double-clicking? Is the spot I marked with an X the location you describe?

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/2a0c032d-1d45-4639-ba89-633832b3e002)

**Comment by swharden** [comment]
Following-up, this code sample should help answer the question! You may have to use a timer to distinguish clicks from double-clicks, and also gate on which mouse button is pressed, but this shows how to determine which axis is under the mouse and how to get its Y position

```cs
using ScottPlot;
using System.Diagnostics;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        IYAxis YAxis1 = formsPlot1.Plot.Axes.Left;
        IYAxis YAxis2 = formsPlot1.Plot.Axes.AddLeftAxis();

        var sig1 = formsPlot1.Plot.Add.Signal(Generate.Sin(mult: 1000));
        sig1.Axes.YAxis = YAxis1;

        var sig2 = formsPlot1.Plot.Add.Signal(Generate.Cos(mult: 0.001));
        sig2.Axes.YAxis = YAxis2;

        formsPlot1.MouseDown += (s, e) =>
        {
            Pixel clickedPixel = new(e.X, e.Y);
            IAxis? clickedAxis = formsPlot1.Plot.GetAxis(clickedPixel);

            if (clickedAxis is null)
            {
                Debug.WriteLine($"Mouse pressed outside all axis panels");
                return;
            }

            double y = clickedAxis.GetCoordinate(clickedPixel.Y, formsPlot1.Plot.RenderManager.LastRender.DataRect);

            if (clickedAxis == sig1.Axes.YAxis)
            {
                Debug.WriteLine($"Mouse pressed over YAxis1 at Y={y}");
            }
            else if (clickedAxis == sig2.Axes.YAxis)
            {
                Debug.WriteLine($"Mouse pressed over YAxis2 at Y={y}");
            }
        };
    }
}
```

**Comment by xinRedi** [comment]
> 接下来，此代码示例应该有助于回答这个问题！您可能需要使用计时器来区分点击和双击，并且还要检查按下哪个鼠标按钮，但这显示了如何确定鼠标下方的哪个轴以及如何获取其 Y 位置
> 
> ```cs
> using ScottPlot;
> using System.Diagnostics;
> 
> namespace Sandbox.WinForms;
> 
> public partial class Form1 : Form
> {
>     public Form1()
>     {
>         InitializeComponent();
> 
>         IYAxis YAxis1 = formsPlot1.Plot.Axes.Left;
>         IYAxis YAxis2 = formsPlot1.Plot.Axes.AddLeftAxis();
> 
>         var sig1 = formsPlot1.Plot.Add.Signal(Generate.Sin(mult: 1000));
>         sig1.Axes.YAxis = YAxis1;
> 
>         var sig2 = formsPlot1.Plot.Add.Signal(Generate.Cos(mult: 0.001));
>         sig2.Axes.YAxis = YAxis2;
> 
>         formsPlot1.MouseDown += (s, e) =>
>         {
>             Pixel clickedPixel = new(e.X, e.Y);
>             IAxis? clickedAxis = formsPlot1.Plot.GetAxis(clickedPixel);
> 
>             if (clickedAxis is null)
>             {
>                 Debug.WriteLine($"Mouse pressed outside all axis panels");
>                 return;
>             }
> 
>             double y = clickedAxis.GetCoordinate(clickedPixel.Y, formsPlot1.Plot.RenderManager.LastRender.DataRect);
> 
>             if (clickedAxis == sig1.Axes.YAxis)
>             {
>                 Debug.WriteLine($"Mouse pressed over YAxis1 at Y={y}");
>             }
>             else if (clickedAxis == sig2.Axes.YAxis)
>             {
>                 Debug.WriteLine($"Mouse pressed over YAxis2 at Y={y}");
>             }
>         };
>     }
> }
> ```
Thank you. I found what I was looking for

var position = e.GetPosition(model.WpfPlot);

Pixel px = new(position.X, position.Y);
IAxis? ax = model.WpfPlot.Plot.GetAxis(px);

if (ax is not null)
{
    ax.Label.Text = System.Random.Shared.NextDouble().ToString();
    model.WpfPlot.Refresh();
}
