### ISSUE TITLE
SP5 Becomes Slow When Calling Font.Automatic() Method (>=5.0.35)

### ISSUE THREAD

**Issue by zxy874175242** [ScottPlot/ScottPlot#4049]
Starting from version 5.0.35, there is a slowdown in SP5 when using the Plot.Font.Automatic() method (as shown in the figure).

In previous versions, the rendering speed was consistently above 500 FPS. However, after version 5.0.35, it suddenly dropped to below 10 FPS (as shown in the figure, from the **Automatic Font Detection** example in the cookbook).

![BillfishQgnhHm](https://github.com/ScottPlot/ScottPlot/assets/49605788/148d323e-31ed-42a9-9381-2467a800f13f)
![BillfishvdXzxx](https://github.com/ScottPlot/ScottPlot/assets/49605788/22306fdd-7af4-45f7-b2f8-725d3df94b35)

I investigated the issue and found that it seems to be related to the SetBestFont() method.

In the method, `FontName = Fonts.Detect(Text);` returns an empty FontName when Text is an empty string, causing an abnormal slowdown.

I added a condition that returns Fonts.Default when Text is empty, and the slowdown disappeared. 
```cs
public void SetBestFont()
{
    Typeface = null;
    // FontName = Fonts.Detect(Text);
    FontName = Text == "" ? Fonts.Default : Fonts.Detect(Text);
}
```

**Comment by swharden** [comment]
Hi @zxy874175242, thanks for reporting this!

I implemented your recommended fix inside the `Fonts.Detect()` method f1a7b316b1fae08d0ffbdb943bed987629f8bf73

I believe this will resolve your issue, but if not let me know and we can open up this issue again and take a closer look 👍
