### ISSUE TITLE
Signal Plot: render artifacts in high density mode

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4050]
I just noticed how different `Signal` and `SignalConst` display for the same dataset... I'm guessing this is some sort of pixel column alignment and/or anti-aliasing issue

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/fe534df4-f3b1-4268-a820-f85d439a693e)

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/0cdc8972-8f4f-46f7-b7f3-64a3edc90ee8)

**Comment by StendProg** [comment]
Hi @swharden,

The problem seems to be this fix https://github.com/ScottPlot/ScottPlot/issues/3665 (https://github.com/ScottPlot/ScottPlot/commit/82f37a44adab3791ab71476f218df38abc624db2). If you remove the addition of the overlap, the signal behaves the same way as SignalConst.

**Comment by swharden** [comment]
Thanks @StendProg! You pointing this out saved a lot of time.

I put that functionality behind a `UsePixelOverlap` flag in case we want to test it further, because I recall the issue underlying #3665 being difficult to reproduce and although it doesn't seem to be happening anymore, I want to keep an eye out for users reporting "flickering" or "disappearing points" in signal plots due to to floating point errors causing points at the edges of pixel columns from getting captured when calculating Y ranges.
