### ISSUE TITLE
Can't put a Bitmap on a Plot anymore with version 5

### ISSUE THREAD

**Issue by vrdriver** [ScottPlot/ScottPlot#4051]
Hi Scott, 
I'm migrating from version 4.1 to version 5, and I'm finding plenty of things in the API very different to version 4. This is probably why I held off. 

I am unable however (at this stage) to put the image from the SpectralGraph up in my Plot. For version 4.1, it wasn't an issue, however now, I'm totally lost as the image format is "ScottPlot.Image".

https://github.com/swharden/Spectrogram

This migration is taking a lot longer than I expected, but I'm down to 154 errors from about 300+ so far.

I'm presently using ScottPlot 5.0.36.

Anyway, here's what I'm working with...

Thanks,
Steve

```cs

// From Scott's SpectralGram

Global.sg = new SpectrogramGenerator(sampleRate, fftSize, stepSize, maxFreq: 3000);
Global.sg.Add(audio);
Global.sg.SetColormap(Colormap.Viridis);

// Just a regular Bitmap from the SpectralGenerator
Bitmap bmp = Global.sg.GetBitmap(intensity: 5);

// This fails
ScottPlot.Image tempbmp = (ScottPlot.Image)bmp.ToSKImage();

//  So does this
ScottPlot.Image tempbmp = bmp;

CoordinateRect rect = new(left: 0, right: img.Width, bottom: 0, top: img.Height);

// V4. worked great.
if ((version4 = true)
{
    // Top
    var imgTop = formsPlot2.Plot.AddImage(bmp, 0, 1);
    imgTop.HeightInAxisUnits = .5;
    imgTop.WidthInAxisUnits = limits.XRange.Max; //.1;
    imgTop.AntiAlias = true;
}

// Version 5 doesn't work at all..
    var imgTop = formsPlot2.Plot.Add.ImageRect(tempbmp, rect);

/*
Error	CS0030	Cannot convert type 'SkiaSharp.SKImage' to 'ScottPlot.Image'	
*/


```

**Comment by swharden** [comment]
Hi @vrdriver, thanks for this question. I'm not sure what you're trying to do though.

Is your question, "How do I display a `System.Drawing.Bitmap` on a plot using ScottPlot 5"?

**Comment by swharden** [comment]
> "How do I display a System.Drawing.Bitmap on a plot using ScottPlot 5"?

Assuming this is the question, here is some sample code which I think will answer it.

If I misunderstood your question let me know and we can open this back up and take a look.

Note that ScottPlot 5 contains ***no references to System.Drawing*** which is why this seems difficult. Microsoft officially dropped cross-platform support for System.Drawing in .NET 6, making this task (and general migration from ScottPlot 4 to ScottPlot 5) especially painful.

```cs
// create a System.Drawing.Bitmap using any strategy
using Spectrogram;
SpectrogramGenerator sg = new(1000, 1024, 100, maxFreq: 3000);
System.Drawing.Bitmap bmp = sg.GetBitmap(intensity: 5);

// convert the System.Drawing.Bitmap to a byte array (or save it to disk)
MemoryStream ms = new();
bmp.Save(ms, System.Drawing.Imaging.ImageFormat.Bmp);
byte[] bitmapBytes = ms.ToArray();

// plot the image from a byte array (or load it from disk);
ScottPlot.Plot plot = new();
ScottPlot.Image img = new(bitmapBytes);
ScottPlot.CoordinateRect rect = new(0, 1, 0, 1);
plot.Add.ImageRect(img, rect);
plot.SavePng("test.png", 600, 400);
```

**Comment by vrdriver** [comment]
Hi Scott, thanks for getting back to me so quickly. 
Yes, that's exactly what I'm aiming for.
This image is what I'm aiming for, and while it worked for 4.1, version 5 doesn't want to play ball.
Here's how it has been working...
![IMG_0437](https://github.com/ScottPlot/ScottPlot/assets/5615487/ea85174e-9feb-46e3-b3e9-cbc4ff324de6)
Cheers,
Steve

**Comment by vrdriver** [comment]
Thanks mate, I will try this out tomorrow. Really appreciate you!

**Comment by swharden** [comment]
> This image is what I'm aiming for, and while it worked for 4.1, version 5 doesn't want to play ball.

Sure thing! 🚀 

Let me know if you hit any snags along the way 👍 

I'll try to create a constructor for `ScottPlot.Image` that accepts a `System.Drawing.Bitmap` and see if I can use compiler directives to make it only available on windows builds

**Comment by swharden** [comment]
Following-up, nope... it looks like I can only use compiler directives to add that feature to .NET Framework projects

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/4e0eb388-517e-44c1-8ede-f48e8bf36ece)

Looks like the recommended way to create a `ScottPlot.Image` from a `System.Drawing.Bitmap` remains:

```cs
System.Drawing.Bitmap bmp = /* ... */
MemoryStream ms = new();
bmp.Save(ms, System.Drawing.Imaging.ImageFormat.Bmp);
byte[] bitmapBytes = ms.ToArray();
ScottPlot.Image img = new(bitmapBytes);
```

**Comment by vrdriver** [comment]
Thanks so much for this Scott. I think it worked (no errors at least). Now to just make the rest of the application to function properly and figure out all the quirks. Cheers. Good to read about your big 'C' diagnosis too. :)
