### ISSUE TITLE
The .NET Maui control fails to display in the sandbox app

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4052]
A .NET Maui control was recently added by @ByteSore in #4013 (see [MauiPlot.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.Maui/MauiPlot.cs)) but the sandbox app which attempts to demonstrate its functionality (see [MainPage.xaml](https://github.com/ScottPlot/ScottPlot/blob/f1a7b316b1fae08d0ffbdb943bed987629f8bf73/src/ScottPlot5/ScottPlot5%20Sandbox/Sandbox.Maui/MainPage.xaml)) is unable to produce a plot:

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/94898e26-f60c-4c36-9d0a-53d41edc5e67)

Does someone with more familiarity with .NET Maui know what the issue is?

Perhaps it relates to this commented-out line?

https://github.com/ScottPlot/ScottPlot/blob/f1a7b316b1fae08d0ffbdb943bed987629f8bf73/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.Maui/MauiPlot.cs#L82

Note that there is an open PR #4023 which aims to fix the sandbox app, but in its present state it still does not work, and any information that can move this forward would be greatly appreciated 🚀

**Comment by swharden** [comment]
Closing as a duplicate of #4023 (I thought that was an open PR and it was actually an open issue - my bad)

**Comment by kudovickij** [comment]
The issue stems from the fact that `MauiPlot` derives from `ContentPage`. A `ContentPage` may be put only in another `ContentPage`. `Grid`, for example, is not a `ContentPage`, so putting the `MauiPlot` into the `Grid` will trigger the `"Parent of a Page must also be a Page"` assert. Here is the minimal generic repro to trigger this assert:
```c#
  <Grid RowDefinitions="*, Auto">
    <TabbedPage>
    </TabbedPage>
  </Grid>
  ```
`MauiPlot` should not be a `ContentPage`, as we already operate within the `ContentPage` (which is our `<PageName>.xaml.cs`). I am not an expert on XAML, perhaps it should be a Layout instead? But definitely not `ContentPage`.

**Comment by ByteSore** [comment]
> The issue stems from the fact that `MauiPlot` derives from `ContentPage`. A `ContentPage` may be put only in another `ContentPage`. `Grid`, for example, is not a `ContentPage`, so putting the `MauiPlot` into the `Grid` will trigger the `"Parent of a Page must also be a Page"` assert. Here is the minimal generic repro to trigger this assert:
> 
> ```cs
>   <Grid RowDefinitions="*, Auto">
>     <TabbedPage>
>     </TabbedPage>
>   </Grid>
> ```
> 
> `MauiPlot` should not be a `ContentPage`, as we already operate within the `ContentPage` (which is our `<PageName>.xaml.cs`). I am not an expert on XAML, perhaps it should be a Layout instead? But definitely not `ContentPage`.

Got it working by now and it's pushed as a PR here: https://github.com/ScottPlot/ScottPlot/pull/4065
