### ISSUE TITLE
Font: automatic font detection fails for strings containing Korean characters

### ISSUE THREAD

**Issue by kimseeho** [ScottPlot/ScottPlot#4054]
**Question:** Korean is not displayed.

## ScottPlot

ScottPlot 4.1.74 | ScottPlot 5.0.36
---|---
![](https://github.com/ScottPlot/ScottPlot/assets/62649457/d4794f38-6e8b-41da-ae25-05453f1a9ed9)|![](https://github.com/ScottPlot/ScottPlot/assets/62649457/76b26358-2446-4c40-8723-387abcf0869a)

```cs
var plt = WpfPlot1.Plot;

// sample data
double[] xs = Generate.Consecutive(51);
double[] sin = Generate.Sin(51);
double[] cos = Generate.Cos(51);

// plot the data
plt.Add.Scatter(xs, sin);
plt.Add.Scatter(xs, cos);

// customize the axis labels
plt.Title("탕후루");
plt.XLabel("좋아요");
plt.YLabel("후루후루");
plt.Font.Automatic();
plt.SavePng("quickstart_scatter.png" , 500 , 300);
```

---

## Raw SkiaSharp

This was DrawText directly with SkiaSharp using `SkiaSharp.Views.WPF` (2.88.8) 

![SkiaSharp_DrawText](https://github.com/ScottPlot/ScottPlot/assets/62649457/9047d4e8-9299-43c7-8ec2-da763ec9be1d)

### MainWindow.xaml
```xml
<Window x:Class="ScottPlot4.X.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:ScottPlot4.X"
        mc:Ignorable="d"
        xmlns:ScottPlot="clr-namespace:ScottPlot.WPF;assembly=ScottPlot.WPF" xmlns:wpf="clr-namespace:SkiaSharp.Views.WPF;assembly=SkiaSharp.Views.WPF"
        Title="MainWindow" Height="450" Width="800">
    <wpf:SKElement x:Name="skia" PaintSurface="skia_PaintSurface"/>
</Window>
```

### MainWindow.xaml.cs
```cs
private void skia_PaintSurface(object sender, SkiaSharp.Views.Desktop.SKPaintSurfaceEventArgs e)
{
    var surface = e.Surface;
    var canvas = surface.Canvas;
    var tf = SKFontManager.Default.MatchCharacter('탕');
    // draw it

    //canvas.Clear(SKColors.White);
    using (SKPaint textPaint =
       new SKPaint
       {
           Typeface = tf,
           IsAntialias = true,
           Style = SKPaintStyle.Fill,
           Color = SKColors.Blue,
           TextSize = 25
       })
    {
        canvas.DrawText("탕후루후루", 120, 50, textPaint);
    }
}
```

**Comment by kimseeho** [comment]
Sorry, but I tested it on 8 PCs and the problem is the same on all of them.
Operating system: Window10, Window11

**Comment by swharden** [comment]
Hi @kimseeho, thank yo for your helpful code samples! 

I modified them a bit and ran them on my machine and things look all right. I'm curious, what font is being selected automatically on your machine?

```cs
using ScottPlot;

Plot plt = new();
plt.Add.Signal(Generate.Sin());
plt.Add.Signal(Generate.Cos());

plt.Title("탕후루");
plt.XLabel("좋아요");
plt.YLabel("후루후루");
plt.Font.Automatic();

Console.WriteLine($"Title font: {plt.Axes.Title.Label.FontName}");
Console.WriteLine($"XAxis font: {plt.Axes.Bottom.Label.FontName}");
Console.WriteLine($"YAxis font: {plt.Axes.Left.Label.FontName}");

plt.SavePng("quickstart_scatter.png", 500, 300);
```

```
Title font: Malgun Gothic
XAxis font: Malgun Gothic
YAxis font: Malgun Gothic
```

![image](https://github.com/ScottPlot/ScottPlot/assets/4165489/a0081a1b-b612-41dd-b930-48922b54ba90)

**Comment by kimseeho** [comment]
FontName : Malgun Gothic


Dear Manager
Currently, I am using Malgun Gothic font, but it doesn't work at all. It doesn't work at all even if I use SetBestFont function or Automatic function.
However, if I use DrawText function using SkiaSharp in ScottPlot, it works very well.

var tf=SKFontManager.Default.MatchCharacter('탕');
using (SKPaint textPaint =
new SKPaint
{
Typeface = tf,
IsAntialias = true,
Style = SKPaintStyle.Fill,
Color = SKColors.Blue,
TextSize = 25
})
{
canvas.DrawText("탕후루후루", 120, 50, textPaint);
}

I wrote this on my phone, so it might be lacking.
It works fine if you write it with SkiaSharp, but please check if you are drawing it using SKPaint.

I created SKPaint and drew it, and it seems that all languages ​​are supported.

var tf = SKFontManager.Default.MatchCharacter('탕');

Among the properties of the SKPaint class,

**Comment by kimseeho** [comment]
please answer me..

**Comment by LeaFrock** [comment]
I find `Font.Detect('汉')`(Chinese) will return `string.Empty` in Blazor WASM too. The default font name is `Noto Mono`.

Do you know the reason? What can we do if the detect fails?

**Comment by swharden** [comment]
The cookbook shows a general purpose font detection strategy:
https://scottplot.net/cookbook/5.0/Internationalization/FontDetection/

Unfortunately I think this topic is outside the scope of ScottPlot (and more in the world of SkiaSharp and system font management) so I probably won't be putting more time into it myself in the short-term.

There hasn't been movement in this issue for a while so I'll close it, but if someone finds a better way to detect the ideal system font given a string, I would be happy to review a pull request that modifies ScottPlot to add this feature 👍

**Comment by LeaFrock** [comment]
I've found a way to solve the font problem and it should be meaningful to add some intro on `IFontResolver` to cookbook.

SkiaSharp loads the default font from its environment. If the environment does not install or support the special font type such as C/J/K, the characters will all display as squares. So, the solution is that we have to import the font we want manually.

One easy way is just embedding the font. Take Blazor WASM and `Microsoft YaHei` as an example, firstly we should add the font file `msyh.ttc` to the client `.proj` file as an embedded resource.

``` xml
  <ItemGroup>
	<EmbeddedResource Include="Fonts\msyh.ttc">
	  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	</EmbeddedResource>
  </ItemGroup>
```

Then it's related to ScottPlot. Write a font resolver as the following,

```csharp
internal sealed class ChineseFontResolver : IFontResolver
{
    public const string DefaultFontName = "Microsoft YaHei";

    public static readonly FrozenDictionary<string, SKTypeface> Fonts = ImportChineseFonts();

    public SKTypeface CreateTypeface(string fontName, bool bold, bool italic)
    {
        if (!Fonts.TryGetValue(fontName, out var font))
        {
            return default;
        }
        return font;
    }

    public static void RegisterScott()
    {
        ScottPlot.Fonts.Default = DefaultFontName;
        ScottPlot.Fonts.FontResolvers.Add(new ChineseFontResolver());
    }

    private static FrozenDictionary<string, SKTypeface> ImportChineseFonts()
    {
        var asm = Assembly.GetExecutingAssembly();
        var resNames = asm.GetManifestResourceNames();
        if (resNames is not { Length: > 0 })
        {
            return FrozenDictionary<string, SKTypeface>.Empty;
        }
        List<SKTypeface> fonts = new(resNames.Length);
        foreach (var name in resNames)
        {
            if (name.EndsWith(".ttc", StringComparison.Ordinal))
            {
                using var fs = asm.GetManifestResourceStream(name);
                var font = SKTypeface.FromStream(fs);
                fonts.Add(font);
            }
        }
        return fonts.ToFrozenDictionary(f => f.FamilyName);
    }
}
```

Run the `ChineseFontResolver.RegisterScott();` only once while app initializing. And we can see that all Chinese characters are  well displayed.

**Comment by LeaFrock** [comment]
There're some other small issues during the solution investigation. But they're in another topic and I'll look into them when I have more free time.
