### ISSUE TITLE
Add "myPlot.Axes.DateTimeTicksBottom()" ,using "GetNearest(mouseCoordinates, plot.LastRender) "  result DataPoint field "IsReal is false" ?

### ISSUE THREAD

**Issue by lee38237489** [ScottPlot/ScottPlot#4056]
In the WPF
1.  
DateTime[] dataX = {
        DateTime.Parse("2024-07-03 12:12:59.100") ,
        DateTime.Parse("2024-07-03 13:13:55.200"),
        DateTime.Parse("2024-07-03 14:11:50.050"),
        DateTime.Parse("2024-07-03 15:11:50.050"),
        DateTime.Parse("2024-07-03 16:11:50.050")};
double[] dataY = { 1, 4, 9, 16, 25 };
**//IsReal of the first line returns false?**
var scatter = myPlot.Add.ScatterLine(dataX, dataY);

var newLeftAxisPoints = new double[] { 2, 6,8, 10, 15 };
**//The IsReal of the second line returns true?**
var axesLeft1 = myPlot.Axes.AddLeftAxis();
var sigLeft1 = myPlot.Add.ScatterLine(dataX, newLeftAxisPoints);
sigLeft1.Axes.XAxis = myPlot.Axes.Bottom;
sigLeft1.LegendText = "New Liner";
axesLeft1.LabelText = sigLeft1.LegendText;

**//After adding ,the field IsReal returend by GetNearest() is false,Why is it not true?**
myPlot.Axes.DateTimeTicksBottom();
scottPlotWpf.Refresh();

2.
**//in mouse double-click evnets and mouse movement evnets(MouseDoubleClick  or MouseMove )**
CoordinateRect rect = myPlot.GetCoordinateRect((float)position.X, (float)position.Y, radius:1);
(var item, DataPoint dataPoint) = GetUnderMouse(myPlot, position.X, position.Y);

var linerNotNull = item is not null;
MtvsHighlightMarker.IsVisible = linerNotNull;
if (linerNotNull)
{
    MtvsHighlightMarker.Location = dataPoint.Coordinates;
    MtvsHighlightMarker.Color = item.Color;
}

wpfPlot.Refresh();

private (Scatter obj, DataPoint dataPoint) GetUnderMouse(Plot plot, double x, double y)
{ 
    Pixel pixel=new (x, y);
    Coordinates mouseCoordinates = myPlot.GetCoordinates(pixel);

    foreach (var item in myPlot.GetPlottables<Scatter>().Reverse())
    {                
        DataPoint dataPoint = item.Data.GetNearest(mouseCoordinates, plot.LastRender);
        if (dataPoint.IsReal)
        {
            return (item, dataPoint);
        }
    }
    return (null, DataPoint.None);
}

**Comment by StendProg** [comment]
Hi @lee38237489,

The `GetNearest()` method not only finds the nearest point, but also checks the distance to it. If the distance exceeds the specified threshold, `DataPoint.None` is returned, which is equivalent to `DataPoint.IsReal == false`. The default value for the threshold is 15 pixels, but you can change it by specifying the 3rd parameter in the `GetNearest()` method.

**Comment by lee38237489** [comment]
HI  @StendProg ,
Thank you for your answer. My question now is that the execution of GetNearest is invalid after adding DateTimeTicksBottom (). You can run my code and you will know how to be confused.

**Comment by StendProg** [comment]
Unfortunately `GetNearest()` works only for the main axes. And you're using an additional axis for the signal, that's the issue. 
It's not easy to add support for additional axes with the current design.
So the problem in this line:
```c#
sigLeft1.Axes.XAxis = myPlot.Axes.Bottom;
```
not in `myPlot.Axes.DateTimeTicksBottom();`

**Comment by lee38237489** [comment]
@StendProg 
Thank you for your guidance, it seems that it needs to continue to be improved.
