### ISSUE TITLE
Add `Tag` property for all plotable objects.

### ISSUE THREAD

**Issue by sdhongjun** [ScottPlot/ScottPlot#4058]
**Suggestion:** (Add `Tag` property for all plotable objects.)

Add `Tag` property can reduce coding for a lot of condition.

```cs
ScottPlot.Plot myPlot = new();

var span = myPlot.Plot.Add.HorizontalSpan(5, 10);
span.Tag = "range1";

var span2 = myPlot.Plot.Add.HorizontalSpan(15, 20);
span2.Tag = "range2";

// MouseMove event can judge from tag
if (curSpan?.Tag.Equals("rang1")) {
   // do something......
}

```

**Comment by KroMignon** [comment]
@sdhongjun there is no good reason to add a Tag property for each plotable object. This will only consume more memory is 99% use cases for nothing.

You could easily replace those tags with a simple Map:
```csharp
ScottPlot.Plot myPlot = new();
var map = new Dictionary<IPlotable, string>();


var span = myPlot.Plot.Add.HorizontalSpan(5, 10);
map.add(span, "range1");

var span2 = myPlot.Plot.Add.HorizontalSpan(15, 20);
map.add(span2,"range2");

// MouseMove event can judge from tag
if ( map.GetValueOrDefault(curSpan).Equals("rang1")) {
   // do something......
}
```

**Comment by sdhongjun** [comment]
Almost all wpf control has `Tag` property, is the easiest way to attatch something to the control, and user can access the attached object directly from `Tag` propery no need more other coding.

**Comment by KroMignon** [comment]
Maybe, but that's not the point.
Again, there is no reason to add a `Tag` property which would be use is some minor cases and only consume memory most of the time.

There are many other ways to build a kind of lookup table to fit your needs without having to add a property.

**Comment by swharden** [comment]
Hi @sdhongjun, thanks for this question! It comes up frequently. See https://scottplot.net/faq/tag/ for a code example that uses a `Dictionary` to pair custom objects with plottables as a safer and more universal alternative to adding an `object?` tag.
