### ISSUE TITLE
The switch function of the legend

### ISSUE THREAD

**Issue by bendanlo** [ScottPlot/ScottPlot#4064]
Why does SP5 not have the function of displaying or not displaying curves in the legend of the point

**Comment by swharden** [comment]
Hi @bendanlo, I'm not sure I understand your question. 

Essentially any plottable with its `LegendText` property set will appear in the legend. Styling options are available via the Plot's `Legend` property. See https://scottplot.net/cookbook/5.0/Legend/ for details.

Total control over legend appearance is even possible by setting legend items manually. See https://scottplot.net/cookbook/5.0/Legend/ManualLegend/ for details.

**Comment by bendanlo** [comment]
我意思在SP5中如何点击一个Legend，可以隐藏某条曲线，再点击那个Legend，这条曲线就又可以显示出来了

**Comment by bendanlo** [comment]
在sp4中好像是有这个功能的，但是SP5中没了
