### ISSUE TITLE
Unifying the ScatterSourceCoordinatesList and ScatterSourceCoordinatesArray

### ISSUE THREAD

**Issue by CoderPM2011** [ScottPlot/ScottPlot#4066]
**Suggestion:** `ScatterSourceCoordinatesList` and `ScatterSourceCoordinatesArray` be unified into a single `ScatterSourceCoordinatesEnumerable`, as there is no actual difference in their internal actions.
This is similar to the suggestion made in https://github.com/ScottPlot/ScottPlot/issues/3981#issuecomment-2184980553

I believe there are many similar types in ScottPlot that could benefit from similar improvements.

```cs
public class ScatterSourceCoordinatesArray(IEnumerable<Coordinates> coordinates) : IScatterSource
{
    private readonly IEnumerable<Coordinates> Coordinates = coordinates;
    ...
```

**Comment by swharden** [comment]
I'll close this for now, but I'd be happy to open this discussion again if someone takes a closer look into it!

I suspect the reason this isn't implemented is because many plot types support `<T>` and it's hard to have generic code that supports both `List<T>` and `double[] T`
