### ISSUE TITLE
Ignore Axis line for AutoScale

### ISSUE THREAD

**Issue by andresod** [ScottPlot/ScottPlot#4067]
**Question:** Is it possible to have horizontal axis line ignored by AutoScaleY ?

**ScottPlot Version:** 5.0.36

Version 4 provides a flag that allows the drawing of an horizontal axis line to be ignored by autoscale:

```cs
            var hline = WP.Plot.AddHorizontalLine(0, color: System.Drawing.Color.DimGray, width: 1, style: LineStyle.Solid);
            hline.IgnoreAxisAuto = true;
            WP.Plot.AxisAutoY();
```
V5 documentation does not mention anything like that for HorizontalLine. I checked the API and couldn't find anything obvious.

PS: performance improvement on V5 is amazing

**Comment by KroMignon** [comment]
@andresod in fact, the functionality is for now not available in `ScottPlot` 5.

I have create a [pull request](https://github.com/ScottPlot/ScottPlot/pull/4069) to port the functionality from `ScottPlot` 4.1 to 5.0.

Maybe it would be available on next release 🚀
