### ISSUE TITLE
Need to use heatmap for risk calculation

### ISSUE THREAD

**Issue by TechDeeptiBhardwaj** [ScottPlot/ScottPlot#4070]
How to use HeatMap for risk calculation

**ScottPlot Version:** 5.0

How to use heatmap for the below type of charts:
![image](https://github.com/user-attachments/assets/2c93cd03-3b8d-40ac-b0a7-43743b335b4a)
Kindly suggest

**Comment by bforlgreen** [comment]
Can this be considered a chart?

I think it would be much easier to present this as a table in UI. Are you using something like WPF?

**Comment by TechDeeptiBhardwaj** [comment]
I used datagridview now for this but somewhere I was looking to implement it using scottplott, will that not be possible?

**Comment by DDiggs91** [comment]
It probably is possible, but its probably not the best method.
Here is some code that could get you started
using ScottPlot;


ScottPlot.Plot myPlot = new();

double[,] data  =
{ 
    { 0, 0, 0, 0, 0, 0},
    { 0, 2, 3, 3, 4, 4},
    { 0, 2, 2, 3, 3, 4},
    { 0, 2, 2, 2, 3, 3},
    { 0, 1, 2, 2, 2, 3},
    { 0, 1, 1, 2, 2, 2},
};
myPlot.Add.Heatmap(data);

myPlot.SavePng("demo.png", 400, 300);

**Comment by swharden** [comment]
Throwing out a simpler idea, consider adding rectangles, then add textboxes on top!

* https://scottplot.net/cookbook/5.0/Shapes/RectangleQuickstart/
* https://scottplot.net/cookbook/5.0/Text/
