### ISSUE TITLE
How to switch to other languages

### ISSUE THREAD

**Issue by Deson999** [ScottPlot/ScottPlot#4071]
**Question:** (How to change the name of the right-click menu to Chinese)

**ScottPlot Version:** (5.0.36)

![image](https://github.com/user-attachments/assets/9e619b69-b284-40ac-8f94-0e5bfabd901b)

Requirement: Only modify the language, keep the functionality unchanged

Thanks

**Comment by swharden** [comment]
Also, https://scottplot.net/demo/5.0/#custom-context-menu
