### ISSUE TITLE
How do I adjust the chart interval?

### ISSUE THREAD

**Issue by GLC-Kazetani** [ScottPlot/ScottPlot#4076]
**Question:** (Ask your question here)
How do I adjust the chart interval?

**ScottPlot Version:** (What NuGet package are you using?)
ScottPlot.WPF 5.0.36

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
            sp.Plot.Axes.SetLimitsY(0.0, 6.0);    // Y:0～6V
```
![2024-07-17 Scottplot](https://github.com/user-attachments/assets/517d2c1e-e7fb-4554-94bc-c9e4edd378df)

**Comment by CoderPM2011** [comment]
You might want to refer to this: https://scottplot.net/cookbook/5.0/CustomizingTicks/

**Comment by GLC-Kazetani** [comment]
Hi, @CoderPM2011
Thank you for your reply!
I was able to format the Y-Axis
Sincerely yours

```CS
            ScottPlot.TickGenerators.NumericAutomatic myTickGenerator = new()
            {
                LabelFormatter = CustomFormatter
            };
            sp.Plot.Axes.Left.TickGenerator = myTickGenerator;

        static string CustomFormatter(double position)
        {
            return position.ToString("0.#0");
        }
```
