### ISSUE TITLE
No Longer Able to Change Bar Width in Version 5.0

### ISSUE THREAD

**Issue by chaojian-zhang** [ScottPlot/ScottPlot#4077]
**Issue:**

The [example code](https://scottplot.net/cookbook/5.0/Bar/) for Bar gives this result:

![Example](https://scottplot.net/cookbook/5.0/images/Quickstart.png?240629072232)

```c#
ScottPlot.Plot myPlot = new();
double[] values = { 5, 10, 7, 13 };
myPlot.Add.Bars(values);

// How to change bar width?
// ...
```

However, it's not clear from the documentation how we can configure bar width.

According to https://scottplot.net/cookbook/4.1/category/plottable-bar-graph/, in version 4, we used to be able to do that:
```C#
// add a bar graph to the plot
var bar = plt.AddBar(values, positions);

// customize the width of bars (80% of the inter-position distance looks good)
bar.BarWidth = (positions[1] - positions[0]) * .8;
```

This change is not listed in https://scottplot.net/faq/version-5.0/

**ScottPlot Version:** 5.0.36

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```c#
ScottPlot.Plot myPlot = new();
double[] values = { 5, 10, 7, 13 };
myPlot.Add.Bars(values);

// How to change bar width?
// ...
```

**Comment by bukowa** [comment]
Trying to find this https://scottplot.net/cookbook/4.1/recipes/bar_datetime/ doc but for 5.0 no luck yet.
