### ISSUE TITLE
How to Remove Default Y Axis?

### ISSUE THREAD

**Issue by chaojian-zhang** [ScottPlot/ScottPlot#4078]
**Question:**

From https://scottplot.net/cookbook/5.0/AxisAndTicks/ it's clear we can use `myPlot.Layout.Frameless();` to hide all axies, but how do we just remove the Y axis?

The code below will raise a `Sequence contains no matching element` error during `plot.SavePng()`:

```C#
plot.Axes.Remove(ScottPlot.Edge.Left);
```

Related: https://github.com/ScottPlot/ScottPlot/issues/1458

**ScottPlot Version:** 5.0.36

**Code Sample:**

```cs
ScottPlot.Plot myPlot = new();
double[] values = { -20, 10, 7, 13 };
var barPlot = myPlot.Add.Bars(values);
myPlot.Axes.Remove(ScottPlot.Edge.Left); // This line will NOT work in current implementation
myPlot.SavePng("demo.png", 400, 300);
```

**Expected:**

![demo](https://github.com/user-attachments/assets/b06cce90-b920-4ce0-acfe-d29176ac3481)

**Use Case:**
The specific scenario I am looking into is for the purpose of a population pyramid where I already displays everything I needed using label and the Y axis doesn't really make sense:

![image](https://github.com/user-attachments/assets/9a728da9-91e6-4a1a-8284-2a9a36903576)

**Comment by CoderPM2011** [comment]
> ![demo](https://private-user-images.githubusercontent.com/7077098/349640466-b06cce90-b920-4ce0-acfe-d29176ac3481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MzI0NTEsIm5iZiI6MTcyMTUzMjE1MSwicGF0aCI6Ii83MDc3MDk4LzM0OTY0MDQ2Ni1iMDZjY2U5MC1iOTIwLTRjZTAtYWNmZS1kMjkxNzZhYzM0ODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjFUMDMyMjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGFiZWM5ZDEwYjY5ODllNzc0ZjlkYjQxZjAzOTBhZWNjY2UxMTM2ODdjYWFmODI2NDZjY2ZhM2ZkNjE3NzU4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZLzSYm3zJtm2OvYn4MVil9gvKIJXOQhzAvPAku1nFek)

You can use the following code to achieve this effect.
``` csharp
myPlot.Axes.Left.MajorTickStyle.Length = 0;
myPlot.Axes.Left.MinorTickStyle.Length = 0;
myPlot.Axes.Left.TickLabelStyle.IsVisible = false;
```
