### ISSUE TITLE
Need Way to Measure Text for Precise Placement

### ISSUE THREAD

**Issue by chaojian-zhang** [ScottPlot/ScottPlot#4079]
**Suggestion:** 

As of version 5.0.23: Need a way to measure text for precise placement. At the moment, according to [doc](https://scottplot.net/cookbook/5.0/Text/), when using `text.LabelAlignment = Alignment.MiddleCenter;` - it doesn't matter what kind of alignment we use, there is no way to precisely place labels. This cause issues when making custom plots.

**Usage Scenario**

For instance, I am making a population pyramid and having difficulty placing "age group" labels:

![image](https://github.com/user-attachments/assets/03cb1d7c-3cf8-4610-ab10-cb83463311f4)

In this case, I wish to place the "age group" label right aligned somewhere to the left of the chart - while making sure I reserve enough space so they are not cut off.

However, as this depends on the font size, it's very tricky to get right, e.g. when using a larger font:

![image](https://github.com/user-attachments/assets/53bf9044-5280-46f9-9459-bfa5b7ef2b50)

Versus a smaller font:

![image](https://github.com/user-attachments/assets/7d8f2757-40b5-44e7-921b-888173019be8)

It's very tricky to get proper margin without knowing how much space the text is going to take. In GDI+, we have [Graphics.MeasureString Method (System.Drawing)](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.graphics.measurestring?view=net-8.0), which is used exactly to accommodate this problem.

Without looking at the source code, it looks like ScottPlot may or may not does it internally - since in documentation for the Bar Chart (https://scottplot.net/cookbook/5.0/Bar/BarValuesHorizontal/) it explicitly added margin just so render isn't clipping:

```cs
// add extra margin to account for label
myPlot.Axes.SetLimitsX(-45, 35);
myPlot.Add.VerticalLine(0, 1, Colors.Black);
```

From the [related Issue](https://github.com/ScottPlot/ScottPlot/issues/3761), `Label` class does have a `Measure` function however it's marked as obsolete:

![image](https://github.com/user-attachments/assets/2520b7c9-82d2-4079-97e5-f83dee717566)

How should we do it then when interacting with `Text`?

**Snippet**

I am using the following function to draw a population pyramid:

```C#
public static void PopulationPyramid(string[] ageGroups, double[] maleData, double[] femaleData)
{
    const int barSize = 0.8;
    const int barGap = 0.1;

    ScottPlot.Plot plot = new();
    CreateDataBars(maleData, plot, true,);     // Male group bar data
    CreateDataBars(femaleData, plot, false);     // Female group bar data

    // Set display range
    const int fontSize = 8; // This part become a myth
    int margin = ageGroups.Select(s => s.Length).Max() * fontSize/6; // Heuristic scale
    double maleMin = maleData.Max();
    plot.Axes.SetLimitsX(-maleMin - margin, +femaleData.Max() + margin / 2); // Include extra margin to account for label // TODO: At the moment there is no reliable way to determine absolute size
    // Labels
    for (int i = 0; i < ageGroups.Length; i++)
    {
        string item = ageGroups[i];
        ScottPlot.Plottables.Text text = plot.Add.Text(item, -maleMin - fontSize/3*2, i * (barSize  + barGap)); // How to calculate precisely?
        text.FontSize = fontSize;
        text.LabelAlignment = ScottPlot.Alignment.MiddleRight;
    }
    
    plot.Add.VerticalLine(0, 1, ScottPlot.Colors.Black);     // Draw division line
    plot.SavePng("Demo.png", 400, 300);

    void CreateDataBars(double[] data, ScottPlot.Plot plot, bool male)
    {
        ScottPlot.Plottables.BarPlot barPlot = plot.Add.Bars(male ? data.Select(d => -d).ToArray() : data);
        int index = 0;
        foreach (ScottPlot.Bar bar in barPlot.Bars)
        {
            // Set position and width
            bar.Size = barSize;
            bar.Position = index * (barSize + barGap);

            // Set label
            bar.Label = bar.Value.ToString();
            index++;
        }
        // Customize label style
        barPlot.Horizontal = true;
        barPlot.LegendText = male ? "Male" : "Female";
    }
}
```

**Related**

* https://github.com/ScottPlot/ScottPlot/issues/3761

**Comment by aespitia** [comment]
i think you can call .Measure() on your text to get the size/dimensions of it

**Comment by chaojian-zhang** [comment]
I can confirm there is no `Measure()` on Text as of version 5.0.36.
Sry forgot to mention my version.

**Comment by aespitia** [comment]
try this:
	string item = ageGroups[i];
		Label txt = new();
		txt.Text = item;
		txt.Measure();

**Comment by chaojian-zhang** [comment]
Thanks for quick reply!

Feels a bit hacky but it works!
