### ISSUE TITLE
Is there no other way to quickly extract Ys or Xs?

### ISSUE THREAD

**Issue by xinRedi** [ScottPlot/ScottPlot#4080]
**Question:** (Is there no other way to quickly extract Ys or Xs?)

**ScottPlot Version:** (Scottplot5)

**Code Sample:**

```cs
   var xignalXys = SelectChartItem.WpfPlot.Plot.GetPlottables<SignalXY>();
   var ys = xignalXys.First().Data.GetType().GetField("Ys", BindingFlags.Instance | BindingFlags.NonPublic);
   var data = ys.GetValue(xignalXys.First().Data) as double[];
```

**Comment by KroMignon** [comment]
@xinRedi it depents how you build your application.

The `Data` field of a `SignalXY` uses `ISignalXYSource` interface. There are 2 implementations of this interface in ScottPlot5: `SignalXYSourceDoubleArray` and `SignalXYSourceGenericArray<TX, TY>`, but you could also use a custom one.

You could do it like this:

```csharp
var xignalXys = SelectChartItem.WpfPlot.Plot.GetPlottables<SignalXY>();

// check if Data implements SignalXYSourceDoubleArray 
if (signallXys.First()?.Data is SignalXYSourceDoubleArray data1)
{
    Console.WriteLine($"First value is {data1.Ys[0]}");
}
// if Data implements SignalXYSourceGenericArray, with X as DateTime and Y double values
else if (signallXys.First()?.Data is SignalXYSourceGenericArray<DateTime, double> data2)
{
    Console.WriteLine($"First value is {data2.Ys[0]}");
}
```

**Comment by xinRedi** [comment]
> ```cs
> is SignalXYSourceDoubleArray data1
> ```

thanks

**Comment by cborgentun** [comment]
Even correcting those obvious typos, this code snippet won't work in 5.0.53.

'SignalXYSourceDoubleArray' does not contain a definition for 'Ys' and no accessible extension method 'Ys' accepting a first argument of type 'SignalXYSourceDoubleArray' could be found (are you missing a using directive or an assembly reference?) on the line accessing data1.Ys.

Remarkably, no warning is issued for accessing data2.Ys.

In the [code](https://github.com/ScottPlot/ScottPlot/blob/0d424d53c90b959bf6752547b43d6858070a0fe5/src/ScottPlot5/ScottPlot5/DataSources/SignalXYSourceDoubleArray.cs#L7), I do see Xs and Ys readonlys for SignalXYSourceDoubleArray so perhaps the fault is entirely mine.

**Comment by cborgentun** [comment]
So, I think I figured it out. SignalXYSourceGenericArray has _public_ Xs and Ys. Dito for SignalXYSourceDoubleArray are _private_. So the code @xinRedi posted can't work. I would like some public way to access the x and y arrays.
