### ISSUE TITLE
Vison4.1.74,Set LineWidth = 0.01F

### ISSUE THREAD

**Issue by Garfieldismiao** [ScottPlot/ScottPlot#4084]
Set LineWidth = 0.1F in Vison4.1.74,actually, LineWidth still is 1。

**Comment by bforlgreen** [comment]
Wouldn't a line width less than one be less than one pixel? so would just end up being blurry?

The recent hair line functionality was added so that lines always appear crisp.

Can you explain what you were expecting? perhaps with some images?

**Comment by Garfieldismiao** [comment]
I wish the lines looked a little thinner

**Comment by swharden** [comment]
Hi @Garfieldismiao, ScottPlot 5 supports this feature

```cs
ScottPlot.Plot plt = new();

double[] xs = ScottPlot.Generate.Consecutive();
var sig1 = plt.Add.ScatterLine(xs, ScottPlot.Generate.Sin(offset: 1));
var sig2 = plt.Add.ScatterLine(xs, ScottPlot.Generate.Sin(offset: 2));
var sig3 = plt.Add.ScatterLine(xs, ScottPlot.Generate.Sin(offset: 3));

sig1.LineWidth = 0.2f;
sig2.LineWidth = 0.5f;
sig3.LineWidth = 1.0f;

plt.HideAxesAndGrid();
plt.SavePng("test.png", 600, 300).LaunchFile();
```

![test](https://github.com/user-attachments/assets/c1800ce9-9d0f-4604-becc-958ea1371f89)
