### ISSUE TITLE
Font: automatic font detection fails for strings containing Korean characters(2)

### ISSUE THREAD

**Issue by kimseeho** [ScottPlot/ScottPlot#4088]
I just modified this part and tested it, and it works well. I fixed it temporarily..Why does this work?

private void ApplyTextPaint(SKPaint paint)
{
    paint.TextAlign = SKTextAlign.Left;
    paint.IsStroke = false;
    paint.Typeface = string.IsNullOrEmpty(Text) ? Fonts.GetTypeface(FontName, Bold, Italic) : SKFontManager.Default.MatchCharacter(Text[0]);
    paint.TextSize = FontSize;
    paint.Color = ForeColor.ToSKColor();
    paint.IsAntialias = AntiAliasText;
    paint.SubpixelText = SubpixelText;
    paint.Shader = null;
}
![TextEdit](https://github.com/user-attachments/assets/b819758b-af1c-4e73-b5cd-3d35532f3bd0)

We are also currently fixing an issue where the crosshair position is displayed incorrectly. thank you

**Comment by swharden** [comment]
https://github.com/ScottPlot/ScottPlot/issues/4054#issuecomment-2458625529
