### ISSUE TITLE
How to use superscript letters in legend text?

### ISSUE THREAD

**Issue by redundancer** [ScottPlot/ScottPlot#4092]
**Question:** (Ask your question here)
How can I use superscript letters in legend text? I would like to use a superscript minus.

**ScottPlot Version:** (What NuGet package are you using?)
5.1

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
ScottPlot.Plot myPlot = new();
var xs = new []{1.0};
ver ys = new []{2.0};
var scatter = plo.Add.ScatterLine(xs, ys);
scatter.LegendText = "a\\u207B"; // Unicode seems not to work.
myPlot.SavePng("bug.png");
```

**Comment by aespitia** [comment]
try this, you might have to specify the font, in this case automatic seems to work.  not all fonts have that character:

ScottPlot.Plot myPlot = new();
var xs = new[] { 1.0 };
var ys = new[] { 2.0 };
var scatter = myPlot.Add.ScatterLine(xs, ys);
myPlot.Font.Automatic();
scatter.LegendText = String.Format("a{0}", "\u207B");

myPlot.SavePng("bug.png", 800,600);

**Comment by bforlgreen** [comment]
I have also found that sometimes, there are multiple versions of the same character under different unicode ids, and some fonts only contain some of those ids. So you have to experiment.
