### ISSUE TITLE
AutoScale doesn't work with multiple data loggers with specific values

### ISSUE THREAD

**Issue by Metheny80** [ScottPlot/ScottPlot#4097]
**Issue:** When using 2 data loggers with specific values, the auto scale (`plot.AutoScale()`) feature does not work correctly.
Parts of one of the graphs are not visible in the plot.
Note: if only data for one of the data loggers is being added, then this issue does not happen (i.e. if you comment out the line ` stockLogger.Add(stockValues[stockIndex++]);` or the line `averagesLogger.Add(averageValues[averageIndex++]);` )

**ScottPlot Version:** 5.0.36

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs

readonly ScottPlot.Plottables.DataLogger stockLogger;
readonly ScottPlot.Plottables.DataLogger averagesLogger;

readonly System.Windows.Forms.Timer UpdatePlotTimer = new() { Interval = 50, Enabled = true };

// Data for first data logger
Coordinates[] stockValues = new double[][] { [45496.660416666666, 554.21], [45496.66111111111, 554.22], [45496.66180555556, 553.96], [45496.6625, 553.37], [45496.663194444445, 553.37], [45496.66388888889, 553.38], [45496.66458333333, 553.46], [45496.66527777778, 553.39], [45496.665972222225, 553.74] }.Select(ds => new Coordinates(ds[0], ds[1])).ToArray();

// Data for second data logger
Coordinates[] averageValues = new double[][] { [45496.65972222222, 554.43], [45496.660416666666, 554.32], [45496.66111111111, 554.2866666666666], [45496.66180555556, 554.205], [45496.6625, 554.038], [45496.663194444445, 553.9266666666666], [45496.66388888889, 553.8485714285714], [45496.66458333333, 553.8], [45496.66527777778, 553.7544444444444] }.Select(ds => new Coordinates(ds[0], ds[1])).ToArray();

int stockIndex = 0;
int averageIndex = 0;


public Form1()
{
    InitializeComponent();

    stockLogger = formsPlot1.Plot.Add.DataLogger();
    averagesLogger = formsPlot1.Plot.Add.DataLogger();


    stockLogger.LegendText = "Stock";
    averagesLogger.LegendText = "Stock Moving Averages";


    RightAxis axis1 = (RightAxis)formsPlot1.Plot.Axes.Right;
    stockLogger.Axes.YAxis = axis1;
    averagesLogger.Axes.YAxis = axis1;

    formsPlot1.Plot.Axes.DateTimeTicksBottom();
    formsPlot1.Plot.Axes.Margins(1, 1);
    axis1.Color(stockLogger.Color);

    formsPlot1.Plot.ShowLegend();



    UpdatePlotTimer.Tick += (s, e) =>
    {
        if (stockIndex < stockValues.Length)
        {
            stockLogger.Add(stockValues[stockIndex++]);
        }
        if (averageIndex < averageValues.Length)
        {
            averagesLogger.Add(averageValues[averageIndex++]);
        }

        formsPlot1.Plot.Axes.AutoScale();
        formsPlot1.Refresh();
    };
}
```

This is how it looks, the blue graph is unexpectedly out of bounds

![image](https://github.com/user-attachments/assets/19d44f97-7b39-4be2-a02a-74782d27bdcb)

**Comment by KroMignon** [comment]
@Metheny80 interesting issue!
I have modified the Sandbox application to add the 2 `DataLogger` and it looks to me like a rounding issue as the moving of the plot also seems to "hang".
![ScottPlot](https://github.com/user-attachments/assets/f8eb820e-7a52-463c-8f04-b131a54f4c01)

**Comment by githubkau** [comment]
I have the same issue. Regards

**Comment by niall895** [comment]
I noticed probably the same issue with plotting live data. I second rounding issue because this doesnt happen when I increment the sine wave in integers.

https://github.com/user-attachments/assets/ae6969d6-5cd9-4929-bd1f-a94264e72ba2
