### ISSUE TITLE
Add a scrollbar to move show data in chart.

### ISSUE THREAD

**Issue by ZhuYajunFly** [ScottPlot/ScottPlot#4100]
Add a scrollbar to move show data in chart.
Because our chart data count usually is more than our screen x-pixel ，if I want show our chart data one point by one pixel, so I should use a scrollbar to move for select data to show in chart.
It look like this,
![PlotWithBar](https://github.com/user-attachments/assets/346ee2c0-05c0-4bb7-8582-eacdb2434c0c)

Of course, we can hide it use move the X axis number by default(default can't show the showed data one feature of approximately located in the overall data  ).

**Comment by bforlgreen** [comment]
Scroll bars are usually implemented at the UI level, e.g WPF, Winforms etc.

So should be fairly easy given the min/max range, and the upper lower/limit

**Comment by ZhuYajunFly** [comment]
I hope a example in cookbook.

**Comment by ZhuYajunFly** [comment]
> I hope a example in cookbook.



> Scroll bars are usually implemented at the UI level, e.g WPF, Winforms etc.
> 
> So should be fairly easy to add given the min/max range, and the upper lower/limit

Thank you ,i hope a example to study it.
