### ISSUE TITLE
Add more chart type like as Bar-chart and Gauge-chart

### ISSUE THREAD

**Issue by ZhuYajunFly** [ScottPlot/ScottPlot#4101]
Add more chart type, it looks like this:
This bar chart can show that the depth of water in the tank.
![Bar1](https://github.com/user-attachments/assets/d08a6bee-a70c-48b9-9386-5c31a1e4a004)
![Bar2](https://github.com/user-attachments/assets/f9fc45cc-a7ba-458d-ab92-a03725a2c906)

This gauge-chart like dash board
![Gauge1](https://github.com/user-attachments/assets/502d7db6-3898-419c-ae70-a1d80d17ca70)
![Gauge2](https://github.com/user-attachments/assets/e3e88af8-b5f0-4064-abfd-b3b9d6c2ec80)

**Comment by aespitia** [comment]
i think the radial gauge can get you close to the speedometer one, and maybe add a background image underneath it?
https://scottplot.net/cookbook/5.0/RadialGauge/

**Comment by ZhuYajunFly** [comment]
> i think the radial gauge can get you close to the speedometer one, and maybe add a background image underneath it?我认为径向仪表可以让你接近速度计，也许在它下面添加一个背景图像？ https://scottplot.net/cookbook/5.0/RadialGauge/

yes,it maybe work,but the background image size is fixed value，our chart usaually is changed.

**Comment by swharden** [comment]
These are interesting ideas! If someone wants to create a working prototype and share it as a pull request, I would be happy to take a closer look and perhaps merge it into an upcoming release 👍 

https://scottplot.net/faq/custom-plot-type/

**Comment by aubreychao** [comment]
你最后是怎么实现的捏？
