### ISSUE TITLE
创建一个示波器正弦实时波要怎么做，还有圆要怎么画呢

### ISSUE THREAD

**Issue by observer2099** [ScottPlot/ScottPlot#4113]
创建一个示波器正弦实时波要怎么做，还有圆要怎么画呢？
我正在做一个声速的测量实验，需要做一个虚拟示波器，我打算用这个控件做示波器波形展示，请问该怎么做？请帮助我，谢谢

---

Google Translate:

> How to create an oscilloscope sine real-time wave, and how to draw a circle

> I am doing a sound speed measurement experiment and need to make a virtual oscilloscope. I plan to use this control to display the oscilloscope waveform. How should I do this? please help me, thank you

**Comment by Deson999** [comment]
> 可以看这里的demo：  https://scottplot.net/demo/5.0/ 

俺是用 https://scottplot.net/cookbook/5.0/Legend/ 这个绘制的波形， 你参考一下哈。
