### ISSUE TITLE
Is it possible to show only the points that have values ​​on the x-axis?

### ISSUE THREAD

**Issue by saklanmazozgur** [ScottPlot/ScottPlot#4118]
**Question:**

Hello, I don't want to show some ticks on the x-axis. I only want the point number corresponding to that value to be visible on the x-axis if there is a value at that point. If I give an example from the photo below; I have values ​​at 0- 0.025 - 0.05 ... points. There is no value at 0.01 on the x-axis, so I don't want it to be visible there. I can use TickGenerator, but it takes integer values. How can I make it take double values?

**ScottPlot Version:**

5.0.34

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
private void WriteLineChart(double[] data)
{
    SignalPlot.Plot.Clear();
    var ticks = Generate.Consecutive(data.Length, 0.025, viewModel.Configure.StartPoint * 0.025);
    var signal = SignalPlot.Plot.Add.Scatter(ticks, data);
    signal.LineWidth = 2;
    signal.Smooth = true;
    signal.MarkerSize = 0;
    SignalPlotRefresh();
}

private void SignalPlotRefresh()
{
    SignalPlot.Refresh();
    SignalPlot.Plot.Axes.AutoScale();
    //SignalPlot.Plot.Axes.Bottom.TickGenerator = new ScottPlot.TickGenerators.NumericFixedInterval(1);
    SignalPlot.Plot.FigureBackground.Color = ScottPlot.Color.FromHex("#00000000");
}


```

![image](https://github.com/user-attachments/assets/b5957101-9bd8-4052-979f-62afa67771b6)

**Comment by epegeot** [comment]
Hello, since the version 5.0.37, `NumericFixedInterval` now takes doubles instead of integers.
