### ISSUE TITLE
Generate.Range()

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4119]
We have generate method that creates N consecutive values, but that's not great if we want to generate a range of numbers. For example, a range between 5 and 10 spaced by 0.05 regardless of what the final count actually is.

**Comment by epegeot** [comment]
Is the goal of this to have a range function like the ones in python (start : double, stop : double, step : double = 1)?
I could handle this if that's what's wanted.

**Comment by swharden** [comment]
resolved in #4122
