### ISSUE TITLE
 scatterPlot5  How do I add data points       （scatterPlot5   如何添加数据点）

### ISSUE THREAD

**Issue by JyenZhou** [ScottPlot/ScottPlot#4120]
In ScottPlot 4, there is the Plot.Update function, but in ScottPlot 5, the API has changed. I have looked at all the examples, and they are all about adding lines, not adding individual points. Does this mean we need to manually redraw the entire plot?

 scatterPlot4 中有 Plot.Update函数 但是scatterPlot5 API改了 我看了所有例程都是添加线的 没有添加点的  难道是需要我们手动整个重绘吗？

**Comment by Deson999** [comment]
请问您是要这个效果的数据点吗 ？？？
![image](https://github.com/user-attachments/assets/0ff4c36e-f26b-4f6c-b7d2-fd9f04610b9c)

**Comment by unpluggedjsy** [comment]
只需要修改元数据再刷新一下就好了，比sp4要简单了其实。
            //准备数据
            var xs = Generate.Consecutive();
            var ys = Generate.Sin();
            //创建Scatter
            TestChart.Plot.Add.Scatter(xs, ys);
            TestChart.Refresh();
            //修改两个数据点再刷新
            ys[10] = 0;
            ys[33] = 0;
            TestChart.Refresh();

![2024-07-31 193213](https://github.com/user-attachments/assets/3628d6a3-d97d-4573-9cbe-112293d088c0)

**Comment by JyenZhou** [comment]
好的 非常感谢！
