### ISSUE TITLE
Is it possible to make ScottPlot:WpfPlotGL run in multiple Standalone Thread Window?

### ISSUE THREAD

**Issue by unpluggedjsy** [ScottPlot/ScottPlot#4126]
Is it possible to make ScottPlot:WpfPlotGL run in multiple Standalone Thread Window?

In my project I need to show some Heatmap in Standalone Thread Window for time-frequency analysis dynamically, so high-performance is required.

But for now I can not run WpfPlotGL in more then two STD windows while WpfPlot can.

I'm using ScottPlot.WPF 5.0.37 ; .NET8

**Comment by swharden** [comment]
Hi @unpluggedjsy, I'm not sure what the answer to your question is! You can give it a try and report back if you like.

Definitely test _not_ using the OpenGL control, because in many cases it isn't meaningfully faster, and it comes with some limitations
