### ISSUE TITLE
DataLogger   Memory inflation and overflow

### ISSUE THREAD

**Issue by 2638662731** [ScottPlot/ScottPlot#4127]
Hello, I am using DataLogger on WPF to display a continuously growing dataset, but when the data reaches a certain amount, the memory will skyrocket until it overflows. Does DataLogger provide a method to delete a specified portion of the data, or a method to remove excess points one by one? Or other solutions? We look forward to your reply

**Comment by KroMignon** [comment]
@2638662731 you could use [`DataStreamer`](https://scottplot.net/demo/5.0/#plot-streaming-data) instead of `DataLogger` to have a fixed size of points for your graphic.

Or perhaps use `DataLogger2`, which is for now experimental, to use a circular buffer to hold the data (cf. #4085)

**Comment by swharden** [comment]
> Does DataLogger provide a method to delete a specified portion of the data, or a method to remove excess points one by one?

No, it's designed to hold "growing" (and never "shrinking") data.

> Or other solutions?

Like Kro suggested, try the data streamer https://scottplot.net/demo/5.0/#plot-streaming-data

Another option is to copy the source code for the `DataLogger` and modify it to suit your needs (deleting or condensing data when the number of points gets extremely large)
