### ISSUE TITLE
How to handle outliers in a BoxPlot?

### ISSUE THREAD

**Issue by redundancer** [ScottPlot/ScottPlot#4131]
How to handle outliers in a BoxPlot?

**Comment by KroMignon** [comment]
@redundancer please be kind enough to give more context about your question.

AFAIK, `ScottPlot` is a signal plotting library. It will help you to show your data in various formats, but will **not** filter them.

**Comment by gtkramer** [comment]
I was wondering the same thing.  The box plots that get generated by ScottPlot 5.0 don't seem to account for outliers in the data set, unless I'm not doing something correctly.  This is the basic code I have:

```
private static void CreateBoxPlot(double[] data, string title, string yLabel, string filename) {
    Plot plot = new();
    plot.Title(title);
    plot.YLabel(yLabel);
    var pop = plot.Add.Population(data);
    pop.Bar.IsVisible = false;
    pop.Box.IsVisible = true;
    plot.Axes.Bottom.TickGenerator = new EmptyTickGenerator();
    plot.SavePng(filename, 1024, 768);
}
```

With this, I get a box plot whose whiskers terminate at the min and max of my data set.  Is there a way to get them to terminate at the 1.5 interquartile range for my data set and then plot dots representing the outliers for all data values that fall outside these whiskers?  Is there maybe some extra population work I need to do for this to happen?

**Comment by swharden** [comment]
Hi @redundancer and @gtkramer, it sounds like you're trying to create box plots where the whiskers mark fractions of quartiles, and perhaps even place markers where outlier values are to produce a figure like this:

![image](https://github.com/user-attachments/assets/3d819366-72e0-40c0-9610-4de79b97e3c6)


You could create a Box manually like this and have full control over all its values:

```cs
using ScottPlot;

Plot myPlot = new();

Box box = new()
{
    Position = 1,
    BoxMin = 3,
    BoxMiddle = 4,
    BoxMax = 5,
    WhiskerMin = 2,
    WhiskerMax = 6,
};

myPlot.Add.Box(box);

myPlot.Axes.SetLimits(-5, 5, 0, 10);
myPlot.SavePng("test.png", 600, 300).LaunchFile();
```

![test](https://github.com/user-attachments/assets/8ca9643b-a10c-4cda-a650-d4aea3473a46)

For now you could use `Add.Marker()` to place outlier symbols, but if you want to add that feature into the `Box.cs` class (it's pretty small and easy to edit) I would be happy to review a pull request in good time and merge that feature into the next release!
