### ISSUE TITLE
When I add.signalXY, the x is the time data, when I have two signals in the chart, the x time span of the two is relatively large, I can remove the position that does not display the data in the middle, so that my two lines can be displayed together in order

### ISSUE THREAD

**Issue by ly13732292973** [ScottPlot/ScottPlot#4132]
When I add.signalXY, the x is the time data, when I have two signals in the chart, the x time span of the two is relatively large, I can remove the position that does not display the data in the middle, so that my two lines ca
![Plot](https://github.com/user-attachments/assets/1b78b3f4-f455-4b0d-8985-fa3f4ed1c270)
n be displayed together in order

It is expected that the white space in the middle can be left undisplayed, and the two lines can be displayed perfectly

**Comment by swharden** [comment]
Hi @ly13732292973,

I don't know much about what your original data is or what it's supposed to look like, so it's hard to give specific feedback as to whether this is the expected output or not.

Are you plotting dates on the horizontal axis? If so, be sure you call the following line before adding data to your plot:

```cs
formsPlot1.Plot.Axes.DateTimeTicksBottom();
```

https://scottplot.net/cookbook/5.0/AxisAndTicks/DateTimeAxisQuickstart/
