### ISSUE TITLE
It is recommended to enhance the chart color filling

### ISSUE THREAD

**Issue by HalChoo** [ScottPlot/ScottPlot#4133]
**Suggestion:** Enhance chart color filling capabilities and performance

I recently noticed the addition of the color gradient fill feature for scatter plots in the latest version of ScottPlot, which is an excellent improvement. This feature addresses a common need in data visualization, such as using gradient colors to represent intensity variations (e.g., weak to strong signals) or to create visually appealing charts.
While integrating ScottPlot into a recent project that required gradient color fills, I thoroughly explored the CookBook (which is impressively detailed - thank you for that resource). I found two relevant sections: one on scatter plot Y-axis color fills, and another on more flexible polygon color filling. However, I encountered some challenges when working with real-time data and large datasets due to performance constraints.
So far, ScottPlot has proven to be powerful and user-friendly in many aspects. However, I believe there's room for improvement in the gradient color fill functionality, particularly in terms of performance and customization options.
Based on these observations, I would like to respectfully suggest the following enhancements:

1. Improved performance for real-time gradient color filling, especially when handling large datasets.
2. More flexible options for customizing gradient fills, such as multi-point gradients or the ability to define custom color scales.
3. Enhanced documentation or examples specifically for implementing efficient gradient fills in high-performance scenarios.

I'm curious if there are any existing methods or workarounds for achieving these goals that I might have overlooked. If not, I believe these improvements would significantly benefit users like myself who are working on projects with demanding visualization requirements.
I understand that implementing such features may be challenging, but I'm confident they would add substantial value to ScottPlot's already impressive capabilities. I'm eager to hear your thoughts on these suggestions and would be happy to provide more details or use cases if needed.
Thank you for your continued work on this excellent library and for considering my feedback, and I'm excited to see how it evolves.

**Comment by KroMignon** [comment]
@HalChoo thanks for your suggestion, 

> Improved performance for real-time gradient color filling, especially when handling large datasets.

I am not really sure that gradient filling + real-time data + large dataset are a good combination!
If you have suggestion about changes in the drawing logic to improve performances, they are welcome 😃 

> More flexible options for customizing gradient fills, such as multi-point gradients or the ability to define custom color scales.

That is already possible, take at look at this PR #3324 

> Enhanced documentation or examples specifically for implementing efficient gradient fills in high-performance scenarios.

Yes, documentation is a never ending story!

**Comment by HalChoo** [comment]
I understand that any change in the environment of a large amount of data needs to be treated with caution. Performance and beauty always need to be chosen. Thanks for your efforts, this is a great project
