### ISSUE TITLE
Heatmap keeps crashing with live data feed 

### ISSUE THREAD

**Issue by MahmoudArabied** [ScottPlot/ScottPlot#4135]
**Issue:** 
I implemented the heatmap to have live data feed every 100msec. It works as expected, but after a while “usually >10minutes” it crashes. 

The exception is as follows:
“An unhandled exception of type 'System.AccessViolationException' occurred in SkiaSharp.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
It is related to this file SkiaSharp\SKCanvas.cs.” 

I debugged the calling stack, I found out that the exception is triggered on calling the “Render” function of Heatmap.cs. After I reviewed the source code of Heatmap.cs, I concluded that “Heatmap.cs” it is not a thread safe. This means if the Bitmap is being updated and called within very short time, it might lead to a data corruption.

I modified the Heatmap.cs source code by introducing a thread lock object. Therefore, accessing the Bitmap object is a thread safe operation. Once I applied these changes, the issue of crashing is fully resolved.

**ScottPlot Version:** 
[ScottPlot.WPF 5.0.37]
(https://www.nuget.org/packages/ScottPlot.WPF/5.0.37)

**Comment by zhengqiwen1997** [comment]
Hello MahmoudArabied,

I am also using heatmap in project, but I am using version 4.1.71, could you please create a PR to fix the issue and let me know it? Thanks very much!

**Comment by MahmoudArabied** [comment]
Hi @zhengqiwen1997 I pulled the changes of Heatmap.cs. and created a PR including the fix.
Have a nice day!

**Comment by swharden** [comment]
Hi @MahmoudArabied and @zhengqiwen1997, thanks for the conversation here and over at #4140!

I recognize that many plot types containing "live data" may exhibit unexpected behavior (or throw an exception) if the underlying data is changed _while_ a render is in progress. This can happen with scatter plots, signal plots, heatmaps, etc. 

The recommended way to update data in async environments is to apply a "render lock" to prevent a new render from starting until you're done modifying the data. For example:

### ScottPlot5
```cs
formsPlot1.Plot.RenderManager.PreRenderLock += (s, e) =>
{
    // perform your dangerous operation here
};
```

### ScottPlot4
```cs
formsPlot1.Plot.RenderLock();
// perform your dangerous operation here
formsPlot1.Plot.RenderUnlock();
```

**Comment by swharden** [comment]
Recognizing ScottPlot 4's API seems to be much simpler than ScottPlot 5, I created an issue #4174 aimed at making the recommended locking strategy more discoverable. I welcome suggestions!

**Comment by swharden** [comment]
Users finding this thread in the future may benefit from the latest information in the ScottPlot FAQ about multi-threading support in interactive graphs with live data: https://scottplot.net/faq/async/
