### ISSUE TITLE
Can ScottPlot support transparent label in the future?

### ISSUE THREAD

**Issue by zhengqiwen1997** [ScottPlot/ScottPlot#4136]
**Suggestion:** 
When I have several lines to plot and the labels associated with the lines. The label would cover the lines if they overlap. Can Scottplot support like the below in the future?
![image](https://github.com/user-attachments/assets/e36554ca-1cda-43a2-9fd3-f00065e1527d)

**Comment by epegeot** [comment]
Hello, you can already have transparent labels in ScottPlot, you can play with the `Legend.BackgroundColor`.
See this code :

```cs
using ScottPlot;

ScottPlot.Plot myPlot = new();

// plottables use the standard X and Y axes by default
var sig1 = myPlot.Add.Signal(ScottPlot.Generate.Sin(51, mult: 0.01));
sig1.Axes.XAxis = myPlot.Axes.Bottom; // standard X axis
sig1.Axes.YAxis = myPlot.Axes.Left; // standard Y axis
myPlot.Axes.Left.Label.Text = "Primary Y Axis";
sig1.LegendText = "Sig 1";

// add a new plottable and tell it to use the custom Y axis
var sig2 = myPlot.Add.Signal(ScottPlot.Generate.Cos(51, mult: 0.01));
sig2.LegendText = "Sig 2";

var legend = myPlot.ShowLegend();

legend.BackgroundColor = Legend.BackgroundColor.WithAlpha(0.5);

myPlot.SavePng("/home/ethan/demo_sp.png", 400, 300);
```

![image](https://github.com/user-attachments/assets/06952d4d-8771-4a24-8a96-b7fefc037223)

I strongly invite you to check all the parameters, you can do quite a lot of customizing

**Comment by zhengqiwen1997** [comment]
Thanks for both of you guys reply. However, I am using version 4.1.7. How to do that in version4?

**Comment by zhengqiwen1997** [comment]
I do the following:
`var legend = plt.Legend(enable: true);
legend.FillColor = Color.Transparent;`

but the fill color of the grey-like transparent is not what I want (the first below), I just want a pure transparent which looks like the second below. How can I do about that:>

![image](https://github.com/user-attachments/assets/e18c1416-aeed-424e-9249-df7338b475c0)

![image](https://github.com/user-attachments/assets/3e25bccb-8198-4e88-837b-941b744fb66b)

**Comment by epegeot** [comment]
I just found out that there is a shadow behind the box, with a `Legend.ShadowCOlor` property. If you change this, you should have the result you want.

@swharden What do you think of putting something in the code so that the shadow is the background but 60% more transparent when we set a new background, it seems like some people (myself included) are confused that some colour remain when setting a transparent background?
