### ISSUE TITLE
Is AxesChanged not supported in ScottPlot5?

### ISSUE THREAD

**Issue by YuuukiA** [ScottPlot/ScottPlot#4137]
**Question:** Is AxesChanged not supported in ScottPlot5?

**ScottPlot Version:** [5.0.37](https://github.com/ScottPlot/ScottPlot/commit/5ccb5e1fa6a1f90798a9e5bd43dd57d25977a87d)

I had used `AxesChanged` event in ScottPlot4 in order to know if axis is changed by mouse operation or not.
I'd like to do the same thing in ScottPlot5.
Would you please tell me how to do it?

**Comment by svrij22** [comment]
Same here, I had to downgrade because I couldn't find the replacement method.

**Comment by Klinkas** [comment]
AvaPlot.Plot.RenderManager.AxisLimitsChanged

**Comment by YuuukiA** [comment]
@Klinkas 
Thank you very much for your comment.
I could solve this.
