### ISSUE TITLE
RealTime Charts

### ISSUE THREAD

**Issue by Bodden007** [ScottPlot/ScottPlot#4138]
Hello. I have already managed to build a simple graph using the wonderful ScottPlot library in WPF.
My goal is to plot a graph in real time from an RS232 device, please tell me which graph is right for me? It seems to me that a data logger graph would be suitable, but I did not find a code example for WPF. My goal is to continuously receive data, save and display their graphs for several hours.

**Comment by Bodden007** [comment]
Oh, I forgot to turn on the timer...

`AddNewDataTimer.Start();
UpdatePlotTimer.Start();`

![2024-08-09_191753](https://github.com/user-attachments/assets/57686ce6-ae47-47fa-80af-1987532df859)

**Comment by swharden** [comment]
Hi @Bodden007, it looks like you are doing the right thing! If there's a question here I'm not understanding, feel free to re-state what it is, but it looks all right to me!

See the related discussion here for considerations about displaying live data from multiple data loggers using right axes:
https://github.com/ScottPlot/ScottPlot/issues/4097
