### ISSUE TITLE
How do disable pan and zoom in ScottPlot 5?

### ISSUE THREAD

**Issue by svrij22** [ScottPlot/ScottPlot#4145]
**Issue:** 

How to disable pan and zoom? It used to be:

Plot.Configuration.Pan = false;
Plot.Configuration.Zoom = false;

I can't find it anywhere in the ScottPlot source code either. Could and AllowPan and AllowZoom be added to the AxesManager?

**ScottPlot Version:** 5.0.37

**Comment by brodbar** [comment]
On WPF it's
```cs
yourPlot.Interaction.Disable();
```
It look like it's the same on WinForms also: [FormsPlotBase.cs, Line: 17](https://github.com/ScottPlot/ScottPlot/blob/5ccb5e1fa6a1f90798a9e5bd43dd57d25977a87d/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.WinForms/FormsPlotBase.cs#L17)

Also see: [IPlotControl.UserInputProcessor](https://scottplot.net/changelog/#:~:text=Controls%3A%20A%20new%20IPlotControl.UserInputProcessor%20has%20been%20created%20to%20replace%20IPlotControl.Interaction%20which%20will%20be%20deprecated%20in%20a%20future%20release.)

**Comment by swharden** [comment]
Related, this is demonstrated in the demo app (and code is available)
https://scottplot.net/demo/5.0/#custom-mouse-actions
