### ISSUE TITLE
When click legend name can invert the visibility of curve.

### ISSUE THREAD

**Issue by ZhuYajunFly** [ScottPlot/ScottPlot#4147]
When click legend name can invert the visibility of curve.
If the curve is hide, make the legend name's text color look more gray, or add a line in the middle on legend name's text.
When a chart contains multiple curves, comparing the differences between individual curves can be particularly useful.

**Comment by ris-work** [comment]
Yes, I would like that as I do have quite a lot of things to display. I think colours repeat every 9-10 entries and I had to randomize the LinePattern or the MarkerStyle. It would be great if I could interactively choose/exclude certain entries.

**Comment by swharden** [comment]
Hi @ZhuYajunFly and @ris-work, thanks for this question! It seems @nilsakesson and @BambOoxX from #3842 may like to see this feature as well. I'm not presently working on this, but if someone wants to implement it I put some notes here to get started: https://github.com/ScottPlot/ScottPlot/issues/3842#issuecomment-2458477860
