### ISSUE TITLE
UserInputProcessor: pan and zoom over axis does not work

### ISSUE THREAD

**Issue by dlampa** [ScottPlot/ScottPlot#4155]
There appears to be a change in behaviour between 5.0.36 and 5.0.37 when using the old `InputBindings` approach when trying to map Zoom functionality to the left mouse button. 

In 5.0.36 the user could zoom to a region of the X/Y axes by left click + drag on the specific axis, or rectangle zoom by click-draging on the plot area. Trying to do the axis-zoom in 5.0.37 either doesn't do anything (if the user hasn't tried to perform a rectangle zoom prior) or redraws the last zoom rectangle (if they attempted rectangle zoom on the chart region prior to click-draging on the axis).

Code:

```csharp
// Define the InputBinding
 private readonly ScottPlot.Control.InputBindings ZoomByDefault = new()
 {
     DragPanButton = ScottPlot.Control.MouseButton.Unknown,
     DragZoomButton = ScottPlot.Control.MouseButton.Left,
     DragZoomRectangleButton = ScottPlot.Control.MouseButton.Left
 };

// Use the InputBinding
Interaction currentInteraction = (Interaction)formPlot.Interaction;
formPlot.Interaction = new Interaction(formPlot) { Inputs = ZoomByDefault, Actions = currentInteraction.Actions };
```

Note that the same behaviour exists with the `UserInputProcessor` as well, when adding both `UserActionResponses.MouseDragZoom` and `UserActionResponses.MouseDragZoomRectangle` ActionResponses bound to the left mouse button.

**Comment by swharden** [comment]
Hi @dlampa, I'll re-state the question as I understand it, then follow-up shortly with a solution if I'm able to find one:

"How can I enable left-click-drag zoom without breaking pan/zoom-over-axis functionality?"

**Comment by swharden** [comment]
Yay, it's not too hard with the new user input system :rocket:

```cs
// remove all existing responses so we can create and add our own
formsPlot1.UserInputProcessor.UserActionResponses.Clear();

// left-click-drag zoom
var panButton = ScottPlot.Interactivity.StandardMouseButtons.Left;
var panResponse = new ScottPlot.Interactivity.UserActionResponses.MouseDragZoom(panButton);
formsPlot1.UserInputProcessor.UserActionResponses.Add(panResponse);
```
