### ISSUE TITLE
Show value on every heatmap cells

### ISSUE THREAD

**Issue by doyenho** [ScottPlot/ScottPlot#4156]
**Suggestion:** 
Have an option to show value on every heatmap cells.

If it would affect performance, just ignore the request.
I could add Text on cells with V5.0.37 already.

**Comment by swharden** [comment]
Hi @doyenho, thanks for this suggestion! I'll add a cookbook example to demonstrate this functionality.

```cs
double[,] data = {
    { 1, 2, 3 },
    { 4, 5, 6 },
    { 7, 8, 9 },
};

var hm = myPlot.Add.Heatmap(data);

for (int y = 0; y < data.GetLength(0); y++)
{
    for (int x = 0; x < data.GetLength(1); x++)
    {
        Coordinates coordinates = new(x, y);
        string cellLabel = data[y, x].ToString("0.0");
        var text = myPlot.Add.Text(cellLabel, coordinates);
        text.Alignment = Alignment.MiddleCenter;
        text.LabelFontSize = 30;
        text.LabelFontColor = Colors.White;
    }
}
```

![image](https://github.com/user-attachments/assets/99332075-245c-4f32-8470-d1d961ffd351)
