### ISSUE TITLE
Error occurs only after installing application: The type initiliazer for 'SkiaSharp.SKTypeface' threw an exception.

### ISSUE THREAD

**Issue by Graat** [ScottPlot/ScottPlot#4157]
**Issue:**
I've been getting this error from my ScottPlot wrapper's constructor:
"Fatal Error: Exception has been thrown by the target of an invocation."
And the inner exception is:
"The type initiliazer for 'SkiaSharp.SKTypeface' threw an exception."

The error trigger on this line in my constructor:
`MyPlot = new WpfPlot();`

Funny thing is, while I'm running it from Visual Studio, it's no issue. After we created a setup wizard and installed the application, then this error pops up.

We've been unable to find a solution, and we were wondering if you had any idea where we might have to look.

**ScottPlot Version:**
Tried both 5.0.34.0 & 5.0.37.0

**Comment by BohdanPylypchenko** [comment]
I have also encountered similar issue.
when trying to add FormsPlot control on form via VS designer, control creation fails with an exception:
![image](https://github.com/user-attachments/assets/4ef07f5b-bbb3-4448-8f95-0bbc0d11eb32)
My project targets .net framework 4.7.2.
According to this [link](https://scottplot.net/faq/add-winforms-programmatically/) the exception can occur when targeting .net framework. The article suggests to create plot control programmatically. Still, will there be a fix for .net framework projects?

**Comment by swharden** [comment]
Hi @Graat and @BohdanPylypchenko

1) I think this has been fixed in #4425 which will be released in the next NuGet package

2) For now, this workaround works for .NET Framework projects where Visual Studio crashes at design time: https://scottplot.net/faq/add-winforms-programmatically/
