### ISSUE TITLE
How to set MinimumTickSpacing like as ScottPlot4?

### ISSUE THREAD

**Issue by YuuukiA** [ScottPlot/ScottPlot#4162]
**Question:** How to set MinimumTickSpacing like as ScottPlot4?

**ScottPlot Version:** 5.0.37

In ScottPlot4, I can set MinimumTickSpacing as the following.
```cs
MyPlot.Plot.XAxis.MinimumTickSpacing(0.02);
MyPlot.Plot.YAxis.MinimumTickSpacing(0.02);
```

--> When zoom graph, tick spacing does not go smaller than 0.02.
![image](https://github.com/user-attachments/assets/a8241321-38e7-48cd-9df5-b45a68125cf3)

I'd like to do the same thing in ScottPlot5.
Would you please tell me how to do it?
Though I have tried as the following, tick spacing goes smaller than 0.02.

```cs
MyPlot.Plot.Axes.Bottom.TickGenerator = new NumericAutomatic() { MinimumTickSpacing = 0.02F };
MyPlot.Plot.Axes.Left.TickGenerator = new NumericAutomatic() { MinimumTickSpacing = 0.02F };
```

**Comment by swharden** [comment]
Users may set the tick density to a lower number to increase spacing between ticks
https://scottplot.net/cookbook/5.0/CustomizingTicks/TickDensity/

Alternatively, hook into the `RenderStarting` event and set every other tick's label to `string.Empty`
https://scottplot.net/faq/render-starting/
