### ISSUE TITLE
Bug when set Plot.Axes.DateTimeTicksBottom()

### ISSUE THREAD

**Issue by mcxufly** [ScottPlot/ScottPlot#4163]
**Issue:** When the image is continually shrunk after DateTimeTicksBottom() is set, the ScottPlot will brake

**ScottPlot Version:** 5.0.37

```cs
ScottPlot.Plot myPlot = new();
myPlot.Plot.Axes.DateTimeTicksBottom();
```

After write the code, continuously shrink the image in the window, the ScottPlot will be broken.
After broken, there is no x-axis and y-axis display only one number

**Comment by swharden** [comment]
Hi @mcxufly, I suspect this has been fixed by #3607 and will be in the next release! 👍
