### ISSUE TITLE
How to set a Scaling Factor (or shift) for multiple Y Axes

### ISSUE THREAD

**Issue by RFBomb** [ScottPlot/ScottPlot#4168]
**Question:** 

I am charting various items, and during design i noticed that you can use the scroll wheel to scroll each axis independently. This is very much a desired functionality for my use case here. But since I will also have quite a few overlapping square waves, I wish to be able to either programmatically set this scaling, or apply an offset to each wave's Y Axis.

**ScottPlot Version:** (What NuGet package are you using?) latest as of 8/21/24

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

N/A, couldn't locate any relevant properties or methods in the library to do the request.

**Comment by swharden** [comment]
> programmatically set this scaling, or apply an offset to each wave's Y Axis.

> apply an offset to each wave's Y Axis

Would "stacked square waves" be the effect you're looking for? There could be a few ways to implement this. Here's a start:

```cs
for (int i = 0; i < 10; i++)
{
    double[] ys = Generate.SquareWave(duty: 0.1 + i / 15.0, high: 0.7);
    var sig = formsPlot1.Plot.Add.Signal(ys);
    sig.Data.YOffset = i;
}

formsPlot1.Plot.HideGrid();

double[] tickPositions = Enumerable.Range(0, 10).Select(x => (double)x).ToArray();
string[] tickLabels = Enumerable.Range(1, 10).Select(x => $"Signal #{x:00}").ToArray();
formsPlot1.Plot.Axes.Left.SetTicks(tickPositions, tickLabels);
```

![image](https://github.com/user-attachments/assets/2092e158-a3bc-47a6-887d-489c04b4347a)

Also consider placing multiple controls: https://scottplot.net/faq/shared-axes/
