### ISSUE TITLE
The font of label is not sharp and clean

### ISSUE THREAD

**Issue by xichaoqiang** [ScottPlot/ScottPlot#4173]
![image](https://github.com/user-attachments/assets/8754af1e-9666-4119-9699-4091b3083d44)

**Comment by aespitia** [comment]
are you using the latest version?  i believe there's an anti alias setting that you can turn off if you wanted to

**Comment by swharden** [comment]
> I believe there's an anti alias setting that you can turn off if you wanted to

Indeed!

```cs
formsPlot1.Plot.Axes.Left.TickLabelStyle.AntiAliasText = false;
formsPlot1.Plot.Axes.Bottom.TickLabelStyle.AntiAliasText = false;
```

AntiAlias on | AntiAlias off
---|---
![test](https://github.com/user-attachments/assets/a7770537-6a81-4894-87f0-81a540c67540)|![test](https://github.com/user-attachments/assets/fa561a55-97f5-4cdb-bcf6-851f20fc9cba)
