### ISSUE TITLE
How to reduce FPS?

### ISSUE THREAD

**Issue by Bodden007** [ScottPlot/ScottPlot#4181]
The frame rate of 300-400 Data logger loads the processor and it is not needed. How do I set the frame rate to 60 or enable vertical sync?

**Comment by Bodden007** [comment]
I have not found a solution to this problem in the documentation, so I am trying this solution.
![ScottPlot_NoSleep](https://github.com/user-attachments/assets/7e0dde00-7e54-4c61-8292-8d51cd154b6d)

Add 
`Thread.Sleep(100);`

![ScottPlot_Example](https://github.com/user-attachments/assets/3c262fe7-155f-4e8d-8e1a-ebad1def4801)
And the CPU usage is not consistently high.

![ScottPlot_Sleep](https://github.com/user-attachments/assets/7157f6e4-54ea-4463-8a21-36af2173d836)

Update DataLogger

`            AddNewDataTimer.Tick += (s, e) =>
            {
                int count = 5;
                Logger1.Add(Walker1.Next(count));
                Logger2.Add(Walker2.Next(count));
            };

            UpdatePlotTimer.Tick += (s, e) =>
            {
             
                Thread.Sleep(100);
                
                if (Logger1.HasNewData || Logger2.HasNewData)
                    WpfPlot1.Refresh();
            };

            Logger1.ViewFull();
            Logger2.ViewFull();`

Maybe there is some right solution, without Sleep?

**Comment by KroMignon** [comment]
> Maybe there is some right solution, without Sleep?

Of course, there is a simple solution, increase the timer period!
