### ISSUE TITLE
In the case of multiple y-axes, using SignalXY, the data points of the second signal plot cannot be captured

### ISSUE THREAD

**Issue by lihaidong111** [ScottPlot/ScottPlot#4192]
In the case of multiple y-axes, using SignalXY will not capture the data point of the second signal plot, and it will be shifted vertically, as if the value refers to Y-axis 2, and the data point is still captured in Y1

Version:5.0.37.0

**Comment by lihaidong111** [comment]
![12](https://github.com/user-attachments/assets/72ac4f41-a950-4480-aab2-5b79b63539ea)

**Comment by lihaidong111** [comment]
![13](https://github.com/user-attachments/assets/7e7c59a9-69a9-493e-b8fc-bf29e50b2211)
![14](https://github.com/user-attachments/assets/1a16e1c3-fb58-49f0-974d-c2cbc7517a76)

**Comment by lihaidong111** [comment]
Scatter capture based on the second Y-axis will be limited to position 0 of the Y-axis, hoping to get the author's attention and reply

**Comment by swharden** [comment]
Hi @lihaidong111, I think your question is the same as described here https://github.com/ScottPlot/ScottPlot/issues/4412 and a solution is provided.

https://github.com/ScottPlot/ScottPlot/issues/4412#issuecomment-2449400029

```cs
for (int i = 0; i < signals.Count; i++)
{
    coordinates.Add(wpfPlot.Plot.GetCoordinates(mousePixel, signals[i].Axes.XAxis, signals[i].Axes.YAxis));
}
```

Let me know if you still have trouble and we can open this issue back up and take a look together! 👍
