### ISSUE TITLE
 Execution error ViewJump & ViewSlide

### ISSUE THREAD

**Issue by Bodden007** [ScottPlot/ScottPlot#4194]
Hello. I'm trying to run a real-time Data Logger. ViewFull works without problems, and View Jump and View Slide are not updated correctly.

```cs
WpfPlot1.Plot.Axes.Bottom.TickGenerator = new ScottPlot.TickGenerators.DateTimeAutomatic();
WpfPlot1.Plot.Axes.DateTimeTicksBottom();
```

```cs
AddNewDataTimer.Tick += (s, e) =>
{
    realTime = DateTime.Now;
    realTimeDouble = realTime.ToOADate();
    Label_1.Content = realTimeDouble.ToString();             
    Thread.Sleep(100);
    Logger1.Add(realTimeDouble, random.Next(0, 100));
    WpfPlot1.Refresh();
};
```

```cs
WpfPlot1.Plot.RenderManager.RenderStarting += (s, e) =>
{

    Tick[] ticks = WpfPlot1.Plot.Axes.Bottom.TickGenerator.Ticks;
    for (int i = 0; i < ticks.Length; i++)
    {
        DateTime dt = DateTime.FromOADate(ticks[i].Position);
        Label_1.Content = $"dt  {dt}";
        string label = $"{dt:hh:mm:ss}";
        ticks[i] = new Tick(ticks[i].Position, label);
    }
};
```

https://github.com/user-attachments/assets/edff81ed-4a12-418d-a023-c1a02f73775f

Please help me figure it out.

**Comment by swharden** [comment]
Hi @Bodden007, first comment is that you can replace that `RenderStarting` code with this:
https://scottplot.net/cookbook/5.0/AxisAndTicks/DateTimeAxisCustomFormatter/

**Comment by swharden** [comment]
lol, ignore that last comment, I got confused 🤪

**Comment by swharden** [comment]
@Bodden007 can you share the code for your button click events? The code I see here seems good.
