### ISSUE TITLE
How can I freeze a signal (DataStreamer) in the chart while modifying their data?

### ISSUE THREAD

**Issue by daniel-calvo-guillen** [ScottPlot/ScottPlot#4196]
**Question:** How can I freeze a signal (DataStreamer) in the chart while modifying their data? 

**ScottPlot Version:** 5.0.37

**Description:** 

We have an Oscilloscope-like application to view the data streamed by our devices. It has four types of trigger: Rolling (DataStreamer works nicely here), Auto, Normal and Single. We'd like to keep using DataStreamer and how it stores and visualizes the data, but somehow freeze the signal until the next trigger event occurs. We can't just stop calling the Refresh() method, as the plot has more plottables that need to be updated (trigger cursor, trigger level) while waiting the trigger condition.

Thanks in advance!
Daniel.

**Comment by swharden** [comment]
> How can I freeze a signal (DataStreamer) in the chart while modifying their data?

Hmm, that's a hard one. Data streamers have a fixed-length array that acts as a circular buffer to store values as they come in, and that array is read from every time `Refresh()` is called. As it's written, I think the only solution is to not call `Add()` if you don't want the plot to be updated.

I think a solution could be for an "incoming data buffer" to be stored on your end that accumulates data when the data streamer is not to be updated, but calls `Streamer.Add()` or `Streamer.AddRange()` to load a bunch of new values all at once when they're ready to be drawn on the screen.

Does that help? 😅 

> We have an Oscilloscope-like application to view the data streamed by our devices

Nice! I'd love to see screenshots if you have any 😎
