### ISSUE TITLE
FillY doesn't always work in ScatterCharts with data gaps

### ISSUE THREAD

**Issue by robeckh** [ScottPlot/ScottPlot#4197]
I would like to use the scatter chart to visualize measured values for a day. I have a list of measured values with a timestamp and the given value. The line is always drawn correctly in all cases, only in the case of data gaps (NaN values) there is a strange behavior when filling the chart. For example, if the chart starts with a NaN Value or ends with a NaN Value, the chart will not be filled. If I remove these spots, the filling works. 
It is the same, if I have a data gap in the middle of my measured values, then it can also happen that the diagram is not filled correctly. 
I hope the sample can help you reproduce:

**ScottPlot Version:** 5.0.37

```cs
string PlottScatter()
{
    var plotValues = new List<PlotValue>()
    {
        new(new DateTime(2024, 08, 06, 7, 50, 0), double.NaN),
        new(new DateTime(2024, 08, 06, 7, 55, 0), 0),
        new(new DateTime(2024, 08, 06, 8, 0, 0), 500),
        new(new DateTime(2024, 08, 06, 8, 5, 0), 600),
        new(new DateTime(2024, 08, 06, 8, 10, 0), 700),
        new(new DateTime(2024, 08, 06, 8, 16, 0), 800),
        new(new DateTime(2024, 08, 06, 8, 20, 0), 900),
        new(new DateTime(2024, 08, 06, 8, 25, 0), 1000),
        new(new DateTime(2024, 08, 06, 8, 30, 0), 1100),
        new(new DateTime(2024, 08, 06, 8, 35, 0), 1200),
        new(new DateTime(2024, 08, 06, 8, 40, 0), 1300),
        new(new DateTime(2024, 08, 06, 8, 45, 0), 1400),
        new(new DateTime(2024, 08, 06, 8, 50, 0), 1500),
        new(new DateTime(2024, 08, 06, 14, 15, 0), 0),
        new(new DateTime(2024, 08, 06, 14, 20, 0), double.NaN),
    };

    var xValues = plotValues.Select(x => x.Timestamp.ToOADate()).ToArray();
    var yValues = plotValues.Select(x => x.Value).ToArray();

    var plot = new Plot();
    var signalScatter = plot.Add.Scatter(xValues, yValues.ToArray());

    var y2Values = GenerateZeroBasedY2Values(yValues.Count());

    plot.Add.FillY(xValues,
        yValues.ToArray(),
        y2Values);

    plot.Axes.DateTimeTicksBottom();
    signalScatter.MarkerSize = 0;
    plot.Axes.Margins(0.004, 0, 0);
    plot.Axes.SetLimitsX((new DateTime(2024, 08, 06, 0, 0, 0).ToOADate()), new DateTime(2024, 08, 07, 0, 0, 0).ToOADate());
    return plot.GetImageHtml(720, 480);
}

static double[] GenerateZeroBasedY2Values(int valueCount)
{
    var fillArray = new List<double>();
    for (var i = 0; i < valueCount; i++)
    {
        fillArray.Add(0);
    }

    return fillArray.ToArray();
}

class PlotValue
{
    public DateTime Timestamp { get; set; }

    public double Value { get; set; }

    public PlotValue(DateTime timestamp, double value)
    {
        Timestamp = timestamp;
        Value = value;
    }
}
```

![image](https://github.com/user-attachments/assets/c772b0f5-d082-4311-b2c8-9ddbf092a1c8)

If you remove the starting and ending NaN Values it will look like this:

![image](https://github.com/user-attachments/assets/d020d1c0-f088-42e7-949a-0de5a3c0b1cb)

To reproduce the other case, add a NaN Value at 08:25 and the chart will no longer be filled

**Comment by swharden** [comment]
Hi @robeckh, I don't intend to implement this fix myself but if you want to look into it I suspect the issue could be resolved by removing NaN values from the data before the fill methods are called in the scatter plot class

https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs

If you or someone else creates a pull request, I'd be happy to review it in good time! 🚀
