### ISSUE TITLE
How to hide minor interval text in the DateTime X Axis

### ISSUE THREAD

**Issue by tsheyu** [ScottPlot/ScottPlot#4199]
I use DateTime X Axis and use customer Tiker format, but it turns out like picture below. So it it possible to hide the Text for Minor Interval. Thanks.

![image](https://github.com/user-attachments/assets/38a7af20-5322-4dfb-90d9-7853a2349c05)
 
```cs
readonly DateTimeFixedInterval interval = new(new Minute(), 5, new Minute(), 1) 
{ 
    // I only want to show the Hour and Minutes and it works for the interval Text
    LabelFormatter = Helper.ScottPlotTimeFormatterHM,  
};
```

**Comment by swharden** [comment]
I think you can use this strategy to check whether a tick has `IsMajor` enabled and if not set its label to `string.Empty`

https://scottplot.net/faq/render-starting/#customizing-automatic-ticks

formsPlot1.Plot.RenderManager.RenderStarting += (object? sender, RenderPack rp) =>
{
    Tick[] ticks = formsPlot1.Plot.Axes.Bottom.TickGenerator.Ticks;
    for (int i = 0; i < ticks.Length; i++)
    {
        if (!ticks[i].IsMajor)
        {
            ticks[i].Label = string.Empty
        };
    }
};
