### ISSUE TITLE
Right Axe - Grid issue

### ISSUE THREAD

**Issue by BlackMamba911** [ScottPlot/ScottPlot#4200]
When using Right axe. The horizontal Grid lines are not visible anymore. Like in the basic demo of candlestick with price on the right

```cs
ScottPlot.Plot myPlot = new();

// add candlesticks to the plot
var prices = Generate.RandomOHLCs(30);
var candles = myPlot.Add.Candlestick(prices);

// configure the candlesticks to use the plot's right axis
candles.Axes.YAxis = myPlot.Axes.Right;
candles.Axes.YAxis.Label.Text = "Price";

// style the bottom axis to display date
myPlot.Axes.DateTimeTicksBottom();

myPlot.SavePng("demo.png", 400, 300);
```

**Comment by swharden** [comment]
for context, the code above produces this

![demo](https://github.com/user-attachments/assets/0c4843df-ad42-4621-8712-49b42d234173)

**Comment by swharden** [comment]
Here we go! 🚀 

```cs
myPlot.Grid.YAxis = myPlot.Axes.Right;
```

![demo](https://github.com/user-attachments/assets/3f4685d5-36eb-44d2-83d5-9ed49cfa28e0)
