### ISSUE TITLE
Customize only Major Tick Label?

### ISSUE THREAD

**Issue by veselinoWiktor** [ScottPlot/ScottPlot#4202]
**Question:** (Ask your question here)
Can I somehow make only the Major Tick Labels be bold?

**ScottPlot Version:** (What NuGet package are you using?)
5.0.37

![Screenshot_56](https://github.com/user-attachments/assets/52e57202-dbc1-4cd2-808e-571219497db5)

In the screenshot, numbers that are in red squares(Major Tick Labels) represent hours and the ones outside represent minutes(Minor Tick Labels). Can I customize only the Major Tick Labels to be Bold or bigger font size.

**Comment by swharden** [comment]
Hi @veselinoWiktor, at the present time there's not an easy way to make different ticks different fonts.

Some customization options are here:
https://scottplot.net/faq/render-starting/#customizing-automatic-ticks

This topic is discussed in another issue and is under active development so I anticipate it will be possible soon. For individually who are really motivated to get this done, the code in this discussion can be extended to add the features immediately without requiring changes in the ScottPlot code:

* https://github.com/ScottPlot/ScottPlot/issues/4385#issuecomment-2452504258
* https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Plottables/FinancialTimeAxis.cs
