### ISSUE TITLE
Color: FromSdColor() and/or new constructor overload

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4209]
There should be an easier way to get a `ScottPlot.Color` from a `System.Drawing.Color`

For now, this works

```cs
ScottPlot.Color.FromARGB(System.Drawing.Color.Blue.ToArgb())
```

**Comment by CoderPM2011** [comment]
How about  "User-defined explicit and implicit conversion operators"?
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/user-defined-conversion-operators

**Comment by swharden** [comment]
> User-defined explicit and implicit conversion operators

That's an interesting strategy! On one hand the code reads elegantly, but on the other hand I think this suffers from a bit of indirection and it may not be super obvious what's happening or where the code is that handles the conversion. In this case I think explicit syntax is probably better than implicit, but thanks for the suggestion!
