### ISSUE TITLE
GetPlotPixelPosition and GetCurrentPlotPixelPosition gone in v5.0.37

### ISSUE THREAD

**Issue by wellsw** [ScottPlot/ScottPlot#4214]
The methods GetPlotPixelPosition and GetCurrentPlotPixelPosition were present in WpfPlotBase.cs in v5.0.36 and earlier. They are no longer in WpfPlotBase.cs starting in v5.0.37. Are there alternate methods to use?

**Comment by swharden** [comment]
This seems like an oversight.

It looks like it was removed here
https://github.com/ScottPlot/ScottPlot/commit/f47668bbcc1a2758bb4011cb336171a8511b7d15#diff-7d0522b99f78c748cf1983f09f7862bf7bcd3e3d50f5a7f1e36584c928144d15

**Comment by swharden** [comment]
Thanks @wellsw! Merging #4458 now and this will be in the next release 👍
