### ISSUE TITLE
Charts in UserControl are not the same clear of axis labels for multiple instances

### ISSUE THREAD

**Issue by ZhuYajunFly** [ScottPlot/ScottPlot#4220]
![image](https://github.com/user-attachments/assets/3ba17a8d-fa9f-4a22-a514-1db7238d9d6f)

Charts in UserControl are not the same clear of axis labels for multiple instances.

And try `Chart.Plot.Axes.AntiAlias(true);` not work.

```
double[] sin = Generate.Sin(420, 30, 0, 4);
Chart.Plot.Add.Signal(sin);
Chart.Plot.Axes.SetLimits(0, 420, -50, 50);
Chart.Plot.Axes.Color(Color.FromHex("#27408B"));
Chart.Plot.Axes.Top.IsVisible = false;
Chart.Plot.Axes.Right.IsVisible = false;
Chart.Plot.Axes.Bottom.IsVisible = false;
Chart.Plot.Axes.AntiAlias(true);
```

![image](https://github.com/user-attachments/assets/51152d84-97da-4049-836a-c5a557473b68)

**Comment by swharden** [comment]
Actually, this may be the same question as https://github.com/ScottPlot/ScottPlot/issues/4173


```cs
formsPlot1.Plot.Axes.Left.TickLabelStyle.AntiAliasText = false;
formsPlot1.Plot.Axes.Bottom.TickLabelStyle.AntiAliasText = false;
```

AntiAlias on | AntiAlias off
---|---
![test](https://github.com/user-attachments/assets/a7770537-6a81-4894-87f0-81a540c67540)|![test](https://github.com/user-attachments/assets/fa561a55-97f5-4cdb-bcf6-851f20fc9cba)
