### ISSUE TITLE
Generate.RandomNumbers does not respect min and max values

### ISSUE THREAD

**Issue by ArchieCoder** [ScottPlot/ScottPlot#4251]
**Issue:**
Using RandomNumbers(10000, 34, 38) will only produce values that are over 38

![image](https://github.com/user-attachments/assets/9474d3c4-fa05-407f-b6f5-23f8ef97cf59)

**ScottPlot Version:** (What NuGet package are you using?)
5.0.39

```cs
var numbers = Generate.RandomNumbers(10000, 34, 38);

**Comment by aespitia** [comment]
I've submitted a PR

**Comment by swharden** [comment]
resolved in #4252
