### ISSUE TITLE
Colors are not respected in a Uno Project on MacOS

### ISSUE THREAD

**Issue by ArchieCoder** [ScottPlot/ScottPlot#4257]
**Issue:** 

In the following code, I use: Red, Dark Orange and Green, but on MacOS, I see Purple, Blue and Green

![image](https://github.com/user-attachments/assets/90988d53-1d72-4010-a441-d84b28241ab4)

MacOS

![image](https://github.com/user-attachments/assets/ae430411-2eac-4199-be9e-4b4ffa81b60b)

PC

![image](https://github.com/user-attachments/assets/b8b3b985-011c-4919-b623-86a642aee537)

**ScottPlot Version:** (What NuGet package are you using?)
5.0.39

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
            var array = new double[]{1, 2, 3};
            var sig1 = WinUIPlot1.Plot.Add.Signal(array);
            //sig1.Axes.XAxis = WinUIPlot1.Plot.Axes.Bottom; // standard X axis
            sig1.Axes.YAxis = WinUIPlot1.Plot.Axes.Left; // standard Y axis
            sig1.Color = Colors.Red;
            WinUIPlot1.Plot.Axes.Left.Label.Text = "Amperage";
            WinUIPlot1.Plot.Axes.Left.Label.ForeColor = Colors.Red;

            WinUIPlot1.Plot.Axes.Bottom.TickLabelStyle.IsVisible = false;
            WinUIPlot1.Plot.Axes.Bottom.MajorTickStyle.Length = 0;
            WinUIPlot1.Plot.Axes.Bottom.MinorTickStyle.Length = 0;

            // create a second axis and add it to the plot
            var yAxis2 = WinUIPlot1.Plot.Axes.AddLeftAxis();
            // add a new plottable and tell it to use the custom Y axis
            var sig2 = WinUIPlot1.Plot.Add.Signal(array);
            //sig2.Axes.XAxis = WinUIPlot1.Plot.Axes.Bottom; // standard X axis
            sig2.Axes.YAxis = yAxis2; // custom Y axis
            sig2.Color = Colors.DarkOrange;
            yAxis2.LabelText = "Voltage";
            yAxis2.LabelFontColor = Colors.DarkOrange;


            // create a second axis and add it to the plot
            var yAxis3 = WinUIPlot1.Plot.Axes.AddLeftAxis();
            // add a new plottable and tell it to use the custom Y axis
            var sig3 = WinUIPlot1.Plot.Add.Signal(array);
            //sig2.Axes.XAxis = WinUIPlot1.Plot.Axes.Bottom; // standard X axis
            sig3.Axes.YAxis = yAxis3; // custom Y axis
            sig3.Color = Colors.Green;
            yAxis3.LabelText = "Power";
            yAxis3.LabelFontColor = Colors.Green;
```

**Comment by agneszitte** [comment]
Hi @swharden, I noticed @ArchieCoder opened this issue and wanted to have your feedback as it is platform-specific to see if it is something to be fixed on the ScottPlot side or the Uno Platform side.

**Comment by kebox7** [comment]
This issue is very similar to the following (inverting red and blue channels):
- #2818
- [Red and blue channels are inverted with Skia.Gtk on M1-based Macs #8580](https://github.com/unoplatform/uno/issues/8580)

Although it is strange, because this issue was closed with the following commit bdf6c57.

**Comment by agneszitte** [comment]
> This issue is very similar to the following (inverting red and blue channels):
> 
> * [SP5 Avalonia: Wrong colors in Android projects #2818](https://github.com/ScottPlot/ScottPlot/issues/2818)
> * [Red and blue channels are inverted with Skia.Gtk on M1-based Macs #8580](https://github.com/unoplatform/uno/issues/8580)
> 
> Although it is strange, because this issue was closed with the following commit [bdf6c57](https://github.com/ScottPlot/ScottPlot/commit/bdf6c57b97cd3f81eb0c1f1a67a4159ccb520a23).

Yeah maybe related to previous https://github.com/unoplatform/uno/issues/8580 (cc @spouliot)

**Comment by spouliot** [comment]
This is generally an issue when the Skia surface is created. 

That could be Uno (because we definitively create some) but it should show up in our own rendering. It could also be created inside ScottPlot with the wrong options. 

Sadly it's not always possible to use the same, _default_ Skia code to target all platforms :( That was the root issue for GTK+ on Apple Silicon Macs.

@ArchieCoder just to be sure was this tested with `netXX-desktop` on Mac ? or `netXX-maccatalyst` ? or `netXX-macos` ?

**Comment by ArchieCoder** [comment]
@spouliot net80-desktop

**Comment by spouliot** [comment]
@ArchieCoder If you use Uno.SDK 5.4.8 and update Skia to `2.88.9-preview.1.1` then it should work. I'll double check that my earlier fix did not influence the results...

```json
  "msbuild-sdks": {
    "Uno.Sdk": "5.4.8"
  },
```

```xml
  <ItemGroup>
    <PackageVersion Include="SkiaSharp" Version="2.88.9-preview.1.1" />
    <PackageVersion Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.9-preview.1.1" />
  </ItemGroup>
```

**Comment by spouliot** [comment]
Seems to works fine with Uno.Sdk `5.5.0-dev.90` too 😄 
So there's less variations on the surface types being used.

**Comment by ArchieCoder** [comment]
@spouliot I tried with both Uno.SDK and both of them have the bug still.

Here is a video of the proof via my OneDrive link: https://1drv.ms/v/s!Aj7hlcEeURZfncBiaWnCikl2CYE7Tw?e=Hc3RmG

**Comment by spouliot** [comment]
@ArchieCoder with the Skia* 2.88.9-preview.1.1 ?

**Comment by spouliot** [comment]
@ArchieCoder Make sure your `*.csproj` has `<PackageReference>` to the Skia* assemblies. Having the `Directory.Packages.props` file with the updated version is not enough to include that specific version inside the app.

**Comment by spouliot** [comment]
For _reasons_ I modified [Uno.Samples/UI/ScottPlot/QuickstartSample/ScottPlotSample](https://github.com/unoplatform/Uno.Samples/tree/master/UI/ScottPlot) to match your original test case.

It works fine with the following changes (and I tested it multiple times to convince myself 😄). However if you don't apply the change to the `.csproj` file an older version of Skia will be included.

```diff
diff --git a/UI/ScottPlot/QuickstartSample/Directory.Packages.props b/UI/ScottPlot/QuickstartSample/Directory.Packages.props
index a6c64339..ba5de551 100644
--- a/UI/ScottPlot/QuickstartSample/Directory.Packages.props
+++ b/UI/ScottPlot/QuickstartSample/Directory.Packages.props
@@ -7,5 +7,7 @@
   -->
   <ItemGroup>
     <PackageVersion Include="ScottPlot.WinUI" Version="5.0.39" />
+    <PackageVersion Include="SkiaSharp" Version="2.88.9-preview.1.1" />
+    <PackageVersion Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.9-preview.1.1" />
   </ItemGroup>
-</Project>
+</Project>
\ No newline at end of file
diff --git a/UI/ScottPlot/QuickstartSample/ScottPlotSample/MainPage.xaml.cs b/UI/ScottPlot/QuickstartSample/ScottPlotSample/MainPage.xaml.cs
index c3140fe6..93027621 100644
--- a/UI/ScottPlot/QuickstartSample/ScottPlotSample/MainPage.xaml.cs
+++ b/UI/ScottPlot/QuickstartSample/ScottPlotSample/MainPage.xaml.cs
@@ -7,8 +7,38 @@ public sealed partial class MainPage : Page
     public MainPage()
     {
         this.InitializeComponent();
-        WinUIPlot1.Plot.Add.Signal(Generate.Sin(51));
-        WinUIPlot1.Plot.Add.Signal(Generate.Cos(51));
+        var array = new double[]{1, 2, 3};
+        var sig1 = WinUIPlot1.Plot.Add.Signal(array);
+        //sig1.Axes.XAxis = WinUIPlot1.Plot.Axes.Bottom; // standard X axis
+        sig1.Axes.YAxis = WinUIPlot1.Plot.Axes.Left; // standard Y axis
+        sig1.Color = Colors.Red;
+        WinUIPlot1.Plot.Axes.Left.Label.Text = "Amperage";
+        WinUIPlot1.Plot.Axes.Left.Label.ForeColor = Color.FromHex("#FF0000"); //new Color(255,0,0); //Colors.Red;
+
+        WinUIPlot1.Plot.Axes.Bottom.TickLabelStyle.IsVisible = false;
+        WinUIPlot1.Plot.Axes.Bottom.MajorTickStyle.Length = 0;
+        WinUIPlot1.Plot.Axes.Bottom.MinorTickStyle.Length = 0;
+
+        // create a second axis and add it to the plot
+        var yAxis2 = WinUIPlot1.Plot.Axes.AddLeftAxis();
+        // add a new plottable and tell it to use the custom Y axis
+        var sig2 = WinUIPlot1.Plot.Add.Signal(array);
+        //sig2.Axes.XAxis = WinUIPlot1.Plot.Axes.Bottom; // standard X axis
+        sig2.Axes.YAxis = yAxis2; // custom Y axis
+        sig2.Color = Colors.DarkOrange;
+        yAxis2.LabelText = "Voltage";
+        yAxis2.LabelFontColor = Colors.DarkOrange;
+
+
+        // create a second axis and add it to the plot
+        var yAxis3 = WinUIPlot1.Plot.Axes.AddLeftAxis();
+        // add a new plottable and tell it to use the custom Y axis
+        var sig3 = WinUIPlot1.Plot.Add.Signal(array);
+        //sig2.Axes.XAxis = WinUIPlot1.Plot.Axes.Bottom; // standard X axis
+        sig3.Axes.YAxis = yAxis3; // custom Y axis
+        sig3.Color = Colors.Green;
+        yAxis3.LabelText = "Power";
+        yAxis3.LabelFontColor = Colors.Green;
         WinUIPlot1.Refresh();
     }
 }
diff --git a/UI/ScottPlot/QuickstartSample/ScottPlotSample/ScottPlotSample.csproj b/UI/ScottPlot/QuickstartSample/ScottPlotSample/ScottPlotSample.csproj
index 413f5adf..edd8104a 100644
--- a/UI/ScottPlot/QuickstartSample/ScottPlotSample/ScottPlotSample.csproj
+++ b/UI/ScottPlot/QuickstartSample/ScottPlotSample/ScottPlotSample.csproj
@@ -42,6 +42,8 @@
 
   <ItemGroup>
     <PackageReference Include="ScottPlot.WinUI" />
+    <PackageReference Include="SkiaSharp" />
+    <PackageReference Include="SkiaSharp.Views.Uno.WinUI" />
   </ItemGroup>
 
 </Project>
```

**Comment by ArchieCoder** [comment]
@spouliot thanks! I was missing this in csproj. Appreciate your fix :)
