### ISSUE TITLE
How can I clear the data from a plot?

### ISSUE THREAD

**Issue by danhi** [ScottPlot/ScottPlot#4259]
I want to redraw a bar chart with new data, but I can't find any way to clear out the old data.

**ScottPlot Version:** 5.0.38 5.0.39

**Code Sample:** 

I use
plotUsage.Plot.Add.Bar(r.startInterval.ToOADate, r.usage)
to add the data, but I can't find a way to clear it so I can chart with new data.

**Comment by ArchieCoder** [comment]
https://discord.com/channels/716448886889381919/1265324963112419428/1265326048443236485

public static class UtilityPlot
{
    public static void Reset(this AxisManager axes)
    {
        if (axes == null) return;

        // Clear the title.
        // The default values come from ScottPlot.Panels.TitlePanel initialization.
        axes.Title.Label.Text = String.Empty;
        axes.Title.Label.FontSize = 16f;
        axes.Title.Label.Bold = true;
        axes.Title.Label.Alignment = Alignment.LowerCenter;

        // Clear the Grids and Axes.
        // The default grid and axes need to be re-added.
        axes.CustomGrids.Clear();
        axes.Remove(Edge.Bottom);
        axes.Remove(Edge.Top);
        axes.Remove(Edge.Left);
        axes.Remove(Edge.Right);
        var iXAxis = axes.AddBottomAxis();
        var iYAxis = axes.AddLeftAxis();
        axes.AddTopAxis();
        axes.AddRightAxis();
        axes.DefaultGrid = new ScottPlot.Grids.DefaultGrid(iXAxis, iYAxis);

        axes.Rules.Clear();
    }
}

**Comment by danhi** [comment]
I'm not sure that this is what I need.  I want to clear the values for the bars that I've added previously, so when I add the new data only that gets drawn (sorry if I'm being dense)

**Comment by danhi** [comment]
In case anyone else needs to do this, what I had to do was remove each bar from the plot:

        For Each pl As Plottables.BarPlot In plotUsage.Plot.GetPlottables(Of Plottables.BarPlot)
            lBars.Add(pl)
        Next
        For Each pl In lBars
            plotUsage.Plot.Remove(pl)
        Next
