### ISSUE TITLE
NuGet add `Copyright` element

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4263]
The MIT license on this repository has a copyright, but the csproj file only contains the MIT license expression. It seems that including a copyright in the nuget package is best practice according to https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices#copyright

I'll probably omit the year for reasons discussed in #3285

**Comment by RFBomb** [comment]
While you are preparing to push this package, would it be possible to have it? Strong name signed as well? 

Currently, any consumers that use strong naming will be unable to use this package unless they strong name it themselves
