### ISSUE TITLE
Side by Side bar chart

### ISSUE THREAD

**Issue by danhi** [ScottPlot/ScottPlot#4266]
**Question:** I want to create a bar chart with two sets of data, that I want displayed side by side.  Is there a way to do this?

**ScottPlot Version:** 5.0.38 / 5.0.39

**Comment by aespitia** [comment]
there are examples in the cookbook here:
https://scottplot.net/cookbook/5.0/Bar/

otherwise, do you mean two completely different bar charts?  if so, you can render two images, and then process the images to merge them side by side to render 1 combined image

**Comment by danhi** [comment]
What I want is one bar chart with two sets of values for the x values.  Is this not possible?

**Comment by aespitia** [comment]
like the one in the sample?
https://scottplot.net/cookbook/5.0/Bar/BarLegend/

**Comment by danhi** [comment]
No, that one plots one  set of values with one value for each of the x axis value (1 .. 9).  What I want is to plot two sets of data with the same x axis value, but have the bars side by side not stacked.

**Comment by CoderPM2011** [comment]
like this?

![image](https://github.com/user-attachments/assets/06cecc71-d9d4-43b1-a3ae-d7e8bae0ff0f)

https://scottplot.net/cookbook/5.0/Bar/GroupedBarPlot/

**Comment by danhi** [comment]
Not really.  What I want is a bar chart with two values for each x axis value, plotted side by side.  Here is an example.

 



 

For every x value there are two side by side bars.  Is this possible with ScottPlot?

**Comment by aespitia** [comment]
i don't think your attachment worked, would be good if you replied through the website?

**Comment by danhi** [comment]
OK, I added it through the website.

**Comment by aespitia** [comment]
that looks like what the above person posted then?
https://scottplot.net/cookbook/5.0/Bar/GroupedBarPlot/

**Comment by danhi** [comment]
I don’t know how I can explain this any clearer.  What this person posted was 1 bar per x value, just grouped in groups of 3 (look at the values in the new statements), not multiple bars with the same x value.  If you don’t know how to do this, please stop posting and maybe someone else will post that does know if this can be done or not.

**Comment by aespitia** [comment]
i don't know what to tell you, using that link above to the cookbook, i made this in about 2 mins.  looks similar to me?

![image](https://github.com/user-attachments/assets/7dc4cf57-1db2-41e0-92df-5a062b4a02e9)

ScottPlot.Plot myPlot = new();

ScottPlot.Palettes.Category10 palette = new();

ScottPlot.Bar[] bars =
{
    // first group
    new() { Position = 1, Value = 2, FillColor = palette.GetColor(0)  },
	new() { Position = 2, Value = 5, FillColor = palette.GetColor(1)  }	,
	
	
	    // second group
    new() { Position = 4, Value = 4, FillColor = palette.GetColor(0)},
	new() { Position = 5, Value = 7, FillColor = palette.GetColor(1)},	
};

myPlot.Add.Bars(bars);

// build the legend manually
myPlot.Legend.IsVisible = true;
myPlot.Legend.Alignment = Alignment.UpperLeft;

// show group labels on the bottom axis
Tick[] ticks =
{
	new(1.5, "2018"),
	new(4.5, "2019"),	
};
myPlot.Axes.Bottom.TickGenerator = new ScottPlot.TickGenerators.NumericManual(ticks);
myPlot.Axes.Bottom.MajorTickStyle.Length = 0;
myPlot.HideGrid();

// tell the plot to autoscale with no padding beneath the bars
myPlot.Axes.Margins(bottom: 0);

**Comment by danhi** [comment]
Either you’re just not looking or you can’t understand my description.  In the example, I assume position is the x value, and if so, all the values in your example are the same.  I want: 

 

// first group
new() { Position = 1, Value = 2, FillColor = palette.GetColor(0) },
new() { Position = 2, Value = 5, FillColor = palette.GetColor(1) } ,

    // second group
new() { Position = 1, Value = 4, FillColor = palette.GetColor(0)},

new() { Position = 2, Value = 7, FillColor = palette.GetColor(1)

 

if you display the x axis values, I assume you would get 1,2,4,5.

**Comment by swharden** [comment]
> or you can’t understand my description

Hi @danhi, it seems the descriptions of what you are trying to achieve have been unable to effectively communicate your goal. If you're still interested in pursuing this, I recommend using something like mspaint to draw a picture of what you want to see, then we can help you achieve it with ScottPlot.

---

_I'm adding a cookbook recipe demonstrating that bars may be created individually, styled extensively, and placed anywhere, so users should be able to make any type of bar plot (grouped, stacked, etc.) without requiring any additional ScottPlot features_

```cs
var myPlot = new ScottPlot.Plot();

ScottPlot.Bar bar1 = new()
{
    Position = 2,
    Value = 5,
};

myPlot.Add.Bar(bar1);

ScottPlot.Bar bar2 = new()
{
    Position = 5,
    Value = 7,
    ValueBase = 2,
    Error = 1,
    FillColor = Colors.Magenta,
    LineWidth = 3,
    LineColor = Colors.Navy,
    FillHatch = new ScottPlot.Hatches.Striped(),
    FillHatchColor = Colors.Magenta.Lighten(.2),
};

myPlot.Add.Bar(bar2);

myPlot.HideGrid();
```

![image](https://github.com/user-attachments/assets/ec38a870-b7b9-42f1-91f0-b4697036a234)
