### ISSUE TITLE
Square Wave Plot

### ISSUE THREAD

**Issue by RFBomb** [ScottPlot/ScottPlot#4267]
**Suggestion:** 
One of the things that I am using this library for is plotting square waves for IO signals, specifically they are on or off statuses.

I am currently using a scatterplot to perform this operation, so what I do is take my input data and extrapolate the extra data in order to get the nice square wave look, by adding in additional points (that do not exist in the data). 

For example, if the state were to change from 0 to 1, I would add in an intermediate point of y=0 where the X value is the same as the X value where Y=1

So this works fine as to what's currently available, but I wonder if a new plot type would make sense here, That can handle that interaction automatically in the rendering phase instead of having additional points introduced into the data set

**Comment by jamaa** [comment]
would a step plot help? https://scottplot.net/cookbook/5.0/Scatter/ScatterStep/

**Comment by RFBomb** [comment]
I didn't even see that in the cookbook! 
I'll play around and close this if it meets the idea, which I believe it will. Thanks!
