### ISSUE TITLE
Histogram IndexOutOfRangeException when value is very close to max value

### ISSUE THREAD

**Issue by haopuchen** [ScottPlot/ScottPlot#4268]
**Issue:** Sometimes when creating a Histogram and a value that is very close but not equal to max value is added to the histogram, `IndexOutOfRange` will be thrown in https://github.com/ScottPlot/ScottPlot/blob/743c9427e63692d31920cc424a0e62b12d6eec4a/src/ScottPlot5/ScottPlot5/Statistics/Histogram.cs#L193-L224 at Line 221.

Potential cause is that the value is smaller than max value, so it'll reach Line 219. But it is very close to max value, so at Line 220 `binsFromMin` may be equal to `Counts.Length` due to calculation precision.

**ScottPlot Version:** 5.0.37.0

**Code Sample:** This example 100% reproduce the issue on my end.

```cs
ScottPlot.Statistics.Histogram hist = new(-2.7298125594007514, 2.3209943194386513, 10, true, false);
hist.Add(2.3209943194386504);
```

**Comment by swharden** [comment]
It seems this issue has been resolved with the newer API #4287

```cs
var hist = ScottPlot.Statistics.Histogram.WithBinCount(
    count: 10,
    minValue: -2.7298125594007514,
    maxValue: 2.3209943194386513);

hist.Add(2.3209943194386504);

Console.WriteLine(string.Join(", ", hist.Counts.Select(x => x.ToString())));
```

```
0, 0, 0, 0, 0, 0, 0, 0, 0, 1
```
