### ISSUE TITLE
Bar With Value Labels

### ISSUE THREAD

**Issue by jikun-eng** [ScottPlot/ScottPlot#4271]
**Question:** ( I would like to ask how to create a bar with value labels in version 5.0.39.
 Since version 5.0.37 was released ScottPlot.Label has been deprecated or renamed to ScottPlot.LabelStyle

![IMG_20240917_214300.jpg](https://github.com/user-attachments/assets/09901546-91c0-42c6-8926-9fff46b97a6b)

)

**ScottPlot Version:** (5.0.39)

**Comment by CoderPM2011** [comment]
like the one in the cookbook?
https://scottplot.net/cookbook/5.0/Bar/BarValues/

**Comment by jikun-eng** [comment]
yes like that, but on windows form application ScottPlot.Label has been deprecated

**Comment by CoderPM2011** [comment]
This cookbook is the current version of the build, so this is actually the code available.
