### ISSUE TITLE
Has someone been able to install ScottPlot 5.0.39 on .NET 8.0 in a WinUI3 Project and make it run smoothly?

### ISSUE THREAD

**Issue by ProgrammerGuy76** [ScottPlot/ScottPlot#4273]
Hello and good evening.

I' m trying to install the last release of this beautiful package (5.0.39) in a WinUI3 Project having .NET 8.0 as "base framework". 
In more than one week, I' ve not been able to accomplish this task.
I' m not an expert of packages, versions, frameworks but in past I made it working (on previous versions and different projects/applications) with simple download/install/customization.
This is not the case with this last package (5.0.39) , WinUI3 Project and .NET 8.0

Recapping, so far I' ve made different trials that I reported below :

A) acted on the .NET Framwork in order to verify if changing it something would be fixed but with negative results.
    So I' ve tried .NET 6.0, .NET7.0 and .NET 8.0 and the software always crashed or given different alarms.

B) tried to install all the previous versions of the library, so from 5.0.38 to 5.0.15: problems were still present

C) changed all the possible target and supported versions from 10.0.17763.0 to 10.0.26100.0: problems again still present

D) tried to manually adapt and modify the main project file: problems not disappeared.

There are several different results depending on the above trials:

-) Often the Error NETSDK1148 has been arised (an assembly has been compiled with a more recent version of SDK.NET.dll)
-) Less often get other Errors

The better result I got (but that does not shown anything and not easy to be replicated) was:

no alarms/warnings/errors/
project running by placing the "plotting control area" inside a StackPanel

On this scenario all the others elemente inside the StackPanel were correctly shown, but not the ScottPlot control one.

So, following the title, I' m wondering if someone has been able to accomplish this task:

to install ScottPlot Package 5.0.39 on a WinUI3 Project based on .NET 8.0 and making it running smoothly.

Many thanks to each one in advance for the precious feedback and suggestions.

**Comment by jpcassano** [comment]
Yes, I have successfully deployed ScottPlot to a .NET 8.0 WinUI3 project. It looks like the latest stable version of the WindowsAppSDK 1.6.240829007 which was just released September 4, 2024 could be causing your issue.  A new ScottPlot.WinUI nuget package that targets the newest WindowsAppSdk needs to be created as the ScotPlot package targets 1.5.240802000. For now, try deleting the WindowsAppSDK nuget package then readd it referencing the Microsoft.WindowsAppSDK version 1.5.240802000 package. Also make sure you are using the ScottPlot.WinUI nuget package not just the ScottPlot package and you should be good to go.

**Comment by ProgrammerGuy76** [comment]
Hello and good morning, I confirm you that it works!
The "trick" for now is the one you cited, install everything as explained in the QuickStart but not update the WindowsAppSDK to the last release 1.6.240829007 but still stop at 1.5.240802000.
Your feedback was very precious to us, many thanks.
