### ISSUE TITLE
How to  Show Partial Array Rendering by set  the x  axis if  use  DataLogger

### ISSUE THREAD

**Issue by chenzhaoting** [ScottPlot/ScottPlot#4276]
**Question:** (Ask your question here)
How to  Show Partial Array Rendering by set  the x  axis if  use  DataLogger
**ScottPlot Version:** (What NuGet package are you using?)
 5.x

**Comment by swharden** [comment]
Hi @chenzhaoting, I don't think that's possible with a data logger, but you can delete points from the front. 

https://github.com/ScottPlot/ScottPlot/pull/4460#issuecomment-2465059225

I added a new cookbook example of this today and it will be published in the next version of the package, likely Sunday evening 👍
