### ISSUE TITLE
Display different legend and label on pie chart

### ISSUE THREAD

**Issue by david-brink-talogy** [ScottPlot/ScottPlot#4281]
**Question:** (Ask your question here)

Is it still possible to use different label and legend text on a Pie chart?  This was originally asked for on #2459, but it no longer seems possible on v5 since Label just sets LegendText.

**ScottPlot Version:** (What NuGet package are you using?)

5.0.39

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
var slice = new PieSlice
{
  Value = 1,
  Label = "label",
  LegendText = "legend"
};
```

**Comment by StendProg** [comment]
Hi @david-brink-talogy,

There is a pending PR #4280 that solves what you are asking for. So the answer is no at the moment, but in the next release it probably will be.
