### ISSUE TITLE
Refresh first, then change the data.The chart will occasionally refresh successfully

### ISSUE THREAD

**Issue by WXWYK** [ScottPlot/ScottPlot#4283]
**Issue:** (Describe the bug here)
Refresh first, then change the data.The chart will occasionally refresh successfully

**ScottPlot Version:** (What NuGet package are you using?)
5.0.39
**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
    double[] data = Generate.RandomWalk(10000);
    double[] xs = Generate.Consecutive(10000);
    wpfPlot1.Reset();
    wpfPlot1.Refresh();
    //await Task.Delay(10);
    wpfPlot1.Plot.Add.SignalXY(xs, data);
```

**Comment by WXWYK** [comment]
The delay time will affect the refresh, How do I get the execution time of wpfPlot1.Refresh() ？

**Comment by swharden** [comment]
> How do I get the execution time of wpfPlot1.Refresh() ？

```
TimeSpan renderTime = formsPlot1.Plot.LastRender.Elapsed;
```

Note too that there is an event you could use to signal when renders occur:

```cs
formsPlot1.Plot.RenderManager.RenderFinished += (s, e) =>
{
    Console.WriteLine(formsPlot1.Plot.LastRender.Elapsed)
};
```

**Comment by swharden** [comment]
Changing data in one thread while a render is happening in another thread can cause race conditions. Check out https://scottplot.net/faq/async/ for strategies to allow changing data in multi-threaded apps 👍

**Comment by WXWYK** [comment]
Thanks for your reply, it was very helpful
