### ISSUE TITLE
Tests: reduce console noise

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4285]
The CI system has an overwhelming amount of console output from the test system.

Update tests to only `Console.WriteLine()` if a test is failing or if a debugger is attached.

**Comment by RFBomb** [comment]
Placing this in the root namespace should work. Any usages of Console will prefer the one defined internally in the assembly over an external one in the System assembly.

```cs
internal static class Console
{
    public static void Write(string value) => Write(value);
    public static void Write<T>(T value)
    {
        if (Debugger.IsAttached)
        {
            System.Console.Write(value);
        }
    }

    public static void WriteLine(string value) => WriteLine<string>(value);
    public static void WriteLine<T>(T value)
    {
        if (Debugger.IsAttached)
        {
            System.Console.WriteLine(value);
        }
    }
}
```

**Comment by swharden** [comment]
Great idea, thanks! 🚀
