### ISSUE TITLE
How to define custom LinePatterns?

### ISSUE THREAD

**Issue by redundancer** [ScottPlot/ScottPlot#4289]
**Question:** (Ask your question here)
There seem to exist only four predefined line patterns (Solid, Dashed, DenselyDashed, Dotted) which is not enough for my use case. Is there any plan to extend the list or is there a recommended way to define my own line patterns?

**ScottPlot Version:** (What NuGet package are you using?)
5.0.39

**Comment by RFBomb** [comment]
You might want to throw support at #4275

**Comment by swharden** [comment]
I'm about to merge #4275, then this will work 👍 

```cs
LinePattern customPattern = new([2, 2, 5, 10], 0, "Custom")
```

**Comment by swharden** [comment]
https://scottplot.net/cookbook/5.0/Scatter/ScatterLinePatterns/
