### ISSUE TITLE
ScottPlot 5: The right axis label is positioned in the middle of the axis in an empty plot

### ISSUE THREAD

**Issue by mikeKuester** [ScottPlot/ScottPlot#4290]
**Issue:** Create an empty plot in WPF and set the label text for the right axis. The text is positioned in the middle of the axis. It should have an offset to the axis that it doesn't overlay the axis.

![image](https://github.com/user-attachments/assets/2148e0e5-f3af-47bd-853f-8e43217969a8)

**ScottPlot Version:** 5.0.39 (also found in 5.0.36)

**Code Sample:**

```cs
ScottPlot.Plot myPlot = new();

myPlot.Plot.XLabel("Horizonal Axis");
myPlot.Plot.Title("Plot Title");
myPlot.Plot.Axes.Left.Label.Text = "Vertical Axis";
myPlot.Plot.Axes.Right.Label.Text = "Vertical Axis (right)";

myPlot.SavePng("bug.png");
```

**Comment by swharden** [comment]
Hi @mikeKuester, this is similar to a recent discussion about title alignment in #4455 however I don't think that's what you're asking so I won't add a similar `FullFigureCenter` flag for axis labels, but I can if you want (or someone can create a pull request and I'll merge that faster).

Instead, I think this is a solution that will work for you

```cs
ScottPlot.Plot myPlot = new();

myPlot.XLabel("Horizonal Axis");
myPlot.Title("Plot Title");
myPlot.Axes.Left.Label.Text = "Vertical Axis (left)";
myPlot.Axes.Right.Label.Text = "Vertical Axis (right)";
myPlot.Axes.Right.MinimumSize = 50; // reserve space even if no plottable uses this axis

myPlot.SavePng("bug.png", 400, 300).LaunchFile();
```

![bug](https://github.com/user-attachments/assets/ce186734-d4f8-4b2c-a52d-21218708c549)

For more, see https://scottplot.net/cookbook/5.0/Layout/
