### ISSUE TITLE
Gradient and Pie chart

### ISSUE THREAD

**Issue by david-brink-talogy** [ScottPlot/ScottPlot#4292]
Do gradients work with pie chart slices?  I confirmed `Gradient.GetShader()` is called, but the pie slices have a solid color fill.

```cs
new PieSlice
{
     Value = 2,
     Label = "Red",
     Fill = new FillStyle
     {
         Color = Colors.Red,
         HatchColor = Colors.Orange,
         Hatch = new Gradient()
     }
}
```

**Comment by swharden** [comment]
Hi @david-brink-talogy, it looks like gradients are not currently supported in `ScottPlot.FillStyle`, but I would be happy to consider adding that feature if somebody creates a pull request! (ideally one that only modifies 1-2 files)

For now it appears only hatch styles are supported in objects that have a `FillStyle` (pie slices, bar plot bars, polygons, etc)

```cs
var pie = formsPlot1.Plot.Add.Pie([5, 4, 6]);
pie.Slices[0].Fill.Hatch = new ScottPlot.Hatches.Striped();
pie.Slices[0].Fill.HatchColor = pie.Slices[0].Fill.Color.Lighten(.2);
```

![image](https://github.com/user-attachments/assets/e68ceacc-10a6-4833-b0a4-9ae3e8694d5b)

**Comment by swharden** [comment]
It looks like someone contributed some code that allows gradients to be used for scatter plot fills https://scottplot.net/cookbook/5.0/Scatter/ScatterFillGradient/

If that logic were copied or moved into `FillStyle`, it could be accessible in many more plot types (like pie charts). I don't intend to look into this myself soon, but if someone gives it a go I would be happy to review a pull request in good time! 🚀
