### ISSUE TITLE
Issues with Y-Axis Behavior in ScottPlot

### ISSUE THREAD

**Issue by shijianoo** [ScottPlot/ScottPlot#4294]
**Question:
1,How can I achieve that when using the mouse to zoom, it only affects the bottom X-axis without impacting the left Y-axis? I would like to be able to drag or zoom the left Y-axis independently with the mouse. I reviewed the demos and attempted to use LockedVertical, but this locks the Y-axis, which is not what I want. I am looking for the final effect as shown in the attached image.
![1](https://github.com/user-attachments/assets/cd6fbf12-54c4-47d6-9bc4-76985f3dcdba)

2,Additionally, how can I make the Y-axis automatically adjust its display range to dynamically expand based on the current view size and the data range shown on the X-axis? I would like the final effect to be as shown in the attached image.
![2](https://github.com/user-attachments/assets/578ebfe6-64e8-400a-812b-538d0b02383e)

3,The example in the image above was implemented using LightningChart, and now I want to replace it with ScottPlot. The image below shows the current effect, where I used LockedVertical, which only allows horizontal stretching while locking the Y-axis (this is not the desired effect).
![3](https://github.com/user-attachments/assets/40c62b05-b3df-4d18-ae6f-8662d731dd4d)

**ScottPlot Version:ScottPlot.WPF 5.0.39

**Code Sample:No code

**Comment by swharden** [comment]
Hi @shijianoo, this issue hasn't had any movement for a long time because there is no sample code, so it's very difficult for others to help offer feedback 😅

Here is sample code to mimic your application that may be used for others to start answering this question

```cs
var sig1 = formsPlot1.Plot.Add.Signal(Generate.Sin(offset: 10));
var sig2 = formsPlot1.Plot.Add.Signal(Generate.Cos());

var leftAxis2 = formsPlot1.Plot.Axes.AddLeftAxis();
sig2.Axes.YAxis = leftAxis2;
```

![image](https://github.com/user-attachments/assets/92ce1eca-7699-46f2-8803-6a3ca390b18e)

**Comment by swharden** [comment]
> How can I achieve that when using the mouse to zoom, it only affects the bottom X-axis without impacting the left Y-axis

Re-stating this question: _How can I disable vertical pan/zoom using multi-axis plots?_

This code should help:

```cs
// disable vertical pan/zoom by locking Y responses to mouse inputs
foreach (var resp in formsPlot1.UserInputProcessor.UserActionResponses)
{
    if (resp is ScottPlot.Interactivity.UserActionResponses.MouseDragPan pan)
    {
        pan.LockY = true;
    }

    if (resp is ScottPlot.Interactivity.UserActionResponses.MouseDragZoom zoom)
    {
        zoom.LockY = true;
    }
}
```


![lockme](https://github.com/user-attachments/assets/891f4eb9-ef2f-4f81-85da-ac82e0b6f110)

**Comment by swharden** [comment]
> Additionally, how can I make the Y-axis automatically adjust its display range to dynamically expand based on the current view size and the data range shown on the X-axis?

Use the `RenderStarting` event to determine what the X limits are of what's in view, then `Axes.SetLimitsY()` according to the data in that X range. https://scottplot.net/faq/render-starting/
