### ISSUE TITLE
Changing point count for DataStreamer by re-creating all plottables isn't 100% effective

### ISSUE THREAD

**Issue by betty-crokker** [ScottPlot/ScottPlot#4299]
**Question:** 
I am creating a series of DataStreamers, each with a certain number of points; the number of points is under user control and when the user changes the number of points, I am implementing this by calling plot.Clear() and then re-creating the DataStreamers.  This works except that (1) it doesn't start the new streamers at the left edge of the plot, and (2) the data is strangely collapsed in the area to the left of where the new data starts displaying (see attached screenshot).
Is there something additional I need to do, to reset the DataStreamer "metadata"?

**ScottPlot Version:** 
5.0.37

**Code Sample:** 

```cs
// Clear any previous plottables
plot.Clear();
Streamers = new DataStreamer[numChannels];
for (int i = 0; i < numChannels; i++)
{
    Streamers[i] = plot.Add.DataStreamer(WindowSize);
    Streamers[i].LineColor = Color.FromHex("#00FFFF");
}
```
![image](https://github.com/user-attachments/assets/424eb9a1-b3a3-44d6-b1b4-ae767907afed)

**Comment by swharden** [comment]
Hi @betty-crokker, thanks for opening this issue, but I'm really struggling to understand the problem. The code you shared is incomplete, so I can't replicate the issue you describe.

It sounds like you have having trouble constructing new `DataStreamer` objects. In this case, it will be helpful to see the code you are using to create them.

I'll close this issue for now, but if you clarify the problem (ideally with code) we can open it back up and take a closer look together 👍
