### ISSUE TITLE
Add a list of labels at the creation of a Pie when giving it a list of doubles

### ISSUE THREAD

**Issue by EnomisG** [ScottPlot/ScottPlot#4300]
**Suggestion:** Add a list of labels at the creation of a Pie when giving it a list of doubles

```cs

double[] _pieValues = new double[];
string[] _pieLabels = new string[];

ScottPlot.Plot myPlot = new();

myPlot.Plot.Add.Pie(_pieValues, _pieLabels);

myPlot.SavePng("bug.png");
```

**Comment by Gauravsinghrajputt** [comment]
assign  me for that i want to do

**Comment by swharden** [comment]
I believe this cookbook example can help you reach your goal!
https://scottplot.net/cookbook/5.0/Pie/PieSliceLabelsAndLegend/
