### ISSUE TITLE
Completely custom x-axis for scatter chart

### ISSUE THREAD

**Issue by polterguy** [ScottPlot/ScottPlot#4303]
**Question:** I'm using your chart, thx for a great job, and I'll need to have completely custom x-axis labels for scatter charts. The is because I don't control the dates coming in, and they might be years, months inside a year, etc - So I'll need to be able to use any arbitrary string values as the labels for the x-axis. How can I accomplish such a thing?

**ScottPlot Version:** 5.0.39

**Code Sample:** This is not working

```sharp
        private static void CreateScatter(Node input, Plot plot)
        {
            // Extracting optional ctor args.
            var dataX = input.Children.FirstOrDefault(x => x.Name == "data-x")?.Children.Select(x => x.GetEx<string>())?.ToArray() ??
                throw new HyperlambdaException("No [data-x] provided to [image.plot]");
            var dataY = input.Children.FirstOrDefault(x => x.Name == "data-y")?.Children.Select(x => x.GetEx<double>())?.ToArray() ??
                throw new HyperlambdaException("No [data-y] provided to [image.plot]");

            // Creating our instance.
            plot.Add.Scatter(dataX, dataY);
        }
```

The above code generates something that looks completely garbled. The below are the arguments which I'm sure you can figure out.

```text
data-x=2018,2019,2020,2021,2022&data-y=6204646000,6103088000,6963761000,7130577000,7558227000
```

**Comment by StendProg** [comment]
Hi @polterguy,

It looks like you are trying to use date-time strings converted to double as X coordinates, which is confusing.

You should parse these strings to DateTime, then convert them to OADateTime. And then use that on the X axis. You can also use arbitrary label formatting as described here:

https://scottplot.net/cookbook/5.0/DateTimeAxes/DateTimeAxisCustomFormatter/

But first you need to get the correct coordinates as described above.

**Comment by polterguy** [comment]
Thx mate, I'll try this and let you know
