### ISSUE TITLE
How to adapt the length of X axis using SquarePreserveY

### ISSUE THREAD

**Issue by GuoBo13** [ScottPlot/ScottPlot#4309]
**Question:** (How to adapt the length of X axis using SquarePreserveY)
I hope that when using SquarePreserveY, the X axis can automatically adjust according to the length of the set value. Now there is a blank area between the X axis zero point and the Y axis zero point. How can I make the X axis and Y axis zero point coincide?
**ScottPlot Version:** (5.0.39)

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples
Here is the code
![捕获1](https://github.com/user-attachments/assets/00953a4f-8233-43e1-9642-bc4ca391f366)
This is the result of running the code
![plot](https://github.com/user-attachments/assets/b384589f-bbf6-47fd-8861-d3c9619c9bd1)

**Comment by swharden** [comment]
Hi @GuoBo13, thanks for this question! I think there may be two strategies

1) use the `RenderStarting` event to `GetAxisLimits()`, modify what you need, then `SetAxisLimits()` according to your goals. https://scottplot.net/faq/render-starting/

2) You could use the axis rules system to do something similar (e.g., prevent panning or zooming below 0) https://scottplot.net/demo/5.0/#axis-rules
