### ISSUE TITLE
Issue with Left Axis Visibility and Y Value Update when Moving Horizontal Line

### ISSUE THREAD

**Issue by Lymosx** [ScottPlot/ScottPlot#4311]
**Issue:** Hello, when I disable the left axis and move the horizontal line to the right, the left axis reappears, and the Y value doesn't get updated. However, when I move the horizontal line to the left, the Y value updates correctly.

**ScottPlot Version:** 5.0.39

![11](https://github.com/user-attachments/assets/e69b6557-5486-47f5-b0fb-f7d7e99e0229)

```cs
        Plot = this.myPlot.Plot;
        _horizontalLine = Plot.Add.HorizontalLine(225, pattern: LinePattern.Solid);

        //Plot.Axes.Left.TickLabelStyle.IsVisible = false;
        Plot.Axes.Left.MajorTickStyle.Length = 0;
        Plot.Axes.Left.MinorTickStyle.Length = 0;

        var prices = Generate.RandomOHLCs(30);
        _candlestickPlot = Plot.Add.Candlestick(prices);
        _horizontalLine.Y = prices.Last().Close;

        //_candlestickPlot.Axes.YAxis = Plot.Axes.Left;
        // Bug?
        _candlestickPlot.Axes.YAxis = Plot.Axes.Right;
```

**Comment by swharden** [comment]
Hi @Lymosx, first of all I think you will be interested in the discussion on #4385 because it seems like we have some similar goals

Regarding the answer to your specific question, I think you need to add a line like this:
```cs
_horizontalLine.Axes.YAxis = Plot.Axes.Right;
```
