### ISSUE TITLE
Supporting. NET 4.8 is necessary.

### ISSUE THREAD

**Issue by Kx4o4** [ScottPlot/ScottPlot#4312]
**Suggestion:** (Describe your idea here)

```cs
ScottPlot.Plot myPlot = new();
/* a code sample may improve communication */
myPlot.SavePng("bug.png");
```

**Comment by LeaFrock** [comment]
It supports NS2.0, which .NET 4.8 should be compatible to.

What's your exact problem?

**Comment by Kx4o4** [comment]
In version 5.0,System.TypeInitializationException Pointing out ScottPlot The initial value setting of Fonts' type caused an exception. System.TypeInitializationException ,Further point out SkiaSharp The initial value setting of SKTypeface's type also caused an exception. System.DllNotFoundException， The specific error is' Unable to load library 'libSkiaSharp' ', indicating that the library file named libSkiaSharp cannot be loaded. In version 4,1 it's good。I compared and found that the dependency is only 4.6.2。My version is 4.8

**Comment by Kx4o4** [comment]
winform

**Comment by kebox7** [comment]
Maybe it's a duplicate.  See #3950, #4255

**Comment by Kx4o4** [comment]
I Added ScottPlot WinForms Control Programmatically，error：Unable to load library 'libSkiaSharp'

**Comment by CoderPM2011** [comment]
If it can be executed directly, but cannot be opened in the designer, then this may be caused by any `libSkiaSharp` methods being called in the `Control`/`Form` constructor.
This problem should actually be caused by `SkiaSharp`.
You can refer to the following https://github.com/mono/SkiaSharp/issues/572#issuecomment-708084007

**Comment by swharden** [comment]
Hi @Kx4o4 and the group,

## The Quickstart Works

Following the steps on the QuickStart guide works for .NET Framework projects (I tried it myself just now)
https://scottplot.net/quickstart/winforms/

## Reproducing this Issue / Fix

I was able to reproduce this error by deleting the "packages" folder and rebuilding the project

```
System.TypeInitializationException: 'The type initializer for 'ScottPlot.Fonts' threw an exception.'
DllNotFoundException: Unable to load library 'libSkiaSharp'.
```

***I fixed this issue by opening the NuGet Package Manager, removing `ScottPlot.WinForms`, and adding it again***

**Comment by swharden** [comment]
Related, I'll try to make a `FormsPlot` just for .NET Framework projects that doesn't crash the designer and track that progress in #4362

It will still crash at runtime 🤷 but hopefully we can design it to fail with a more useful error message.
