### ISSUE TITLE
Dates of candlestick chart

### ISSUE THREAD

**Issue by VladislavPustovarov** [ScottPlot/ScottPlot#4317]
**Question:** How can I see proper dates in sequential mode

**ScottPlot Version:** ScottPlot 5.0.39

```cs
var prices = Generate.RandomOHLCs(30);
var plot = WpfPlot1.Plot.Add.Candlestick(prices);
plot.Sequential = true;
WpfPlot1.Plot.Axes.DateTimeTicksBottom();
WpfPlot1.Refresh();
```

**Comment by swharden** [comment]
Hi @VladislavPustovarov, I think the following recipe will answer this question
https://scottplot.net/cookbook/5.0/Finance/FinancialPlotWithoutGaps/

Related, there is some active discussion about improving this system in #4385 so I anticipate this topic will have a simpler solution soon 👍
