### ISSUE TITLE
PixelLine: add a Center property

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4318]
Something like :
```cs
public Pixel Center => new(/* */);
```
goes around here:
https://github.com/ScottPlot/ScottPlot/blob/6c553f97ebfc768d4ef36985dc851629230d24ed/src/ScottPlot5/ScottPlot5/Primitives/PixelLine.cs#L24-L26

**Comment by brokoli777** [comment]
Hi! I tried adding the property, should it be used anywhere in other parts of the code?
