### ISSUE TITLE
Scalebar: fix rendering artifact

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4329]
I just merged #4328 to address #4319 but there's a rendering artifact due to the L shaped scalebar being drawn as two lines. Using a "path" with 3 points would fix this issue.

The issue can be seen in the cookbook recipe:

https://github.com/ScottPlot/ScottPlot/blob/800aae8bf1e2d79ef7c97f1448253033e76117ca/src/ScottPlot5/ScottPlot5%20Cookbook/Recipes/PlotTypes/ScaleBar.cs#L68-L70

![image](https://github.com/user-attachments/assets/1a4e17fa-0bc1-4ba8-93d0-ea0bf57097b1)

The fix may be implemented here by using `DrawPath` instead of `DrawLine`:

https://github.com/ScottPlot/ScottPlot/blob/800aae8bf1e2d79ef7c97f1448253033e76117ca/src/ScottPlot5/ScottPlot5/Plottables/ScaleBar.cs#L59-L73

**Comment by StendProg** [comment]
To hide the artifact you can increase the line length by 0.5 of the line width.
