### ISSUE TITLE
How to get data area size in pixels (WinForms)

### ISSUE THREAD

**Issue by jwwq** [ScottPlot/ScottPlot#4332]
I want to make the width of the bar in barplot constant in pixels regardless of the chart size, so here is the pseudocode:

```cs
var bar_width = 10;
var num_of_bars = [CHART_DATA_AREA_X_SIZE] / bar_width; 
p.Plot.Axes.SetLimitsX(0, num_of_bars);
```
How can I get the size of the "data area" (excluding axes etc) in pixels?
Thanks!

P.S. If there's a more elegant way to accomplish this, please let me know.

**Comment by StendProg** [comment]
Hi @jwwq,

Try this `p.Plot.LastRender.DataRect.Width`
