### ISSUE TITLE
Controls: update ScaleFactor when DPI scale changes

### ISSUE THREAD

**Issue by tiger2014** [ScottPlot/ScottPlot#4333]
I made a winform project with ScotPlot controller. I have 2 monitors, the crosshair showed incorrectly when the winform windows on any minitor.

![image](https://github.com/user-attachments/assets/15ebe0c7-e667-4b09-97f7-f2ea4b3beaab)
![image](https://github.com/user-attachments/assets/3447a13d-c04d-43cb-a427-23a87395e906)

**Comment by swharden** [comment]
@tiger2014 the bug is on this line I think

![image](https://github.com/user-attachments/assets/ea530c9c-bf2d-4dbc-9b98-2c68cfea51b1)

You should probably multiply those values by `formsPlot.DisplayScale` or even `formsPlot1.DetectDisplayScale()`
