### ISSUE TITLE
SignalXYSourceDoubleArray: Xs must contain only ascending values......

### ISSUE THREAD

**Issue by linqing2005** [ScottPlot/ScottPlot#4336]
**Issue:** When manually moving the current curve outside the visible area, an error will be thrown: Xs must contain only ascending values.....

**ScottPlot Version:** 5.0.9.

**Code Sample:** 
ScottPlot.DataSources.SignalXYSourceDoubleArray: GetPixelsToDrawHorizontally or GetPixelsToDrawVertically.
if (Xs[dataIndexFirst] > Xs[dataIndexLast])
    throw new InvalidDataException("Xs must contain only ascending values. " +
        $"The value at index {dataIndexFirst} ({Xs[dataIndexFirst]}) is greater than the value at index {dataIndexLast} ({Xs[dataIndexLast]})");

**Possible fixes below:**
if (dataIndexFirst > dataIndexLast ||  Xs[dataIndexFirst] > Xs[dataIndexLast])
    return [];

**Comment by swharden** [comment]
Hi @linqing2005, I think this issue has since been resolved.

If not, can you share a code sample that helps us reproduce this error so we can take a closer look? Thanks!
