### ISSUE TITLE
Display X-Axis values as time only, not date and time

### ISSUE THREAD

**Issue by danhi** [ScottPlot/ScottPlot#4338]
**Question:** I add values to the bar plot as date/time, but I want the X-Axis to display as time only.

**ScottPlot Version:** 5.0.38/39

**Code Sample:** <plotname>.plot.add.bar(<datetime>, value>

And the x-axis display displays the date and the time, I want just the time.

**Comment by StendProg** [comment]
https://scottplot.net/cookbook/5.0/DateTimeAxes/DateTimeAxisCustomFormatter/

**Comment by danhi** [comment]
I found that, but can't figure out how to implement it in VB.Net.  I can set a variable to <plot name>.RenderManager.RenderStarting, but can't figure out how to get my code called.  Any tips?

**Comment by swharden** [comment]
https://scottplot.net/faq/render-starting/#customizing-automatic-ticks

**Comment by swharden** [comment]
According to ChatGPT:

> Documentation for a C# library says there is an event called RenderStarting. I am using this library in my VB.NET application. How can I invoke that event?

In VB.NET, you can handle events from a C# library in a similar way to handling events in VB.NET libraries. You don't "invoke" events directly, but you can subscribe to them and write code to run when they are raised by the library. Here’s how you can subscribe to the `RenderStarting` event in your VB.NET application:

### Step 1: Add a Handler for the Event
Assuming `RenderStarting` is an event of an object `renderObject`, you can use the `AddHandler` keyword to connect the event to an event handler subroutine.

```vb.net
' Declare and create an instance of the object (assuming it’s called "RenderObjectType")
Dim renderObject As New RenderObjectType()

' Subscribe to the RenderStarting event
AddHandler renderObject.RenderStarting, AddressOf OnRenderStarting
```

### Step 2: Define the Event Handler Subroutine
This subroutine will be executed whenever the `RenderStarting` event is raised by `renderObject`.

```vb.net
Private Sub OnRenderStarting(sender As Object, e As EventArgs)
    ' Code to execute when RenderStarting is raised
    Console.WriteLine("Render is starting.")
End Sub
```

### Complete Example

Here’s a full example, assuming `RenderObjectType` is the type containing the `RenderStarting` event:

```vb.net
Imports System

Module Module1
    Sub Main()
        ' Create an instance of the object
        Dim renderObject As New RenderObjectType()
        
        ' Attach the event handler
        AddHandler renderObject.RenderStarting, AddressOf OnRenderStarting

        ' Now, when renderObject triggers the RenderStarting event, OnRenderStarting will be called
    End Sub

    ' Define the event handler method
    Private Sub OnRenderStarting(sender As Object, e As EventArgs)
        Console.WriteLine("Render is starting.")
    End Sub
End Module
```

Now, whenever the `RenderStarting` event is triggered by `renderObject`, your `OnRenderStarting` subroutine will run, and you’ll see the message `"Render is starting."` printed to the console. 

### Notes
- The parameters of the event handler method must match the signature of the event. In this case, `RenderStarting` uses `(sender As Object, e As EventArgs)`.
- If `RenderStarting` uses a custom event argument type, replace `EventArgs` with that type in your handler.
