### ISSUE TITLE
"Visualization of 48-Hour Data with Highlighted or Gray Out 6-Hour No-Data Interval"

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#4341]
*Need to show some indication when there is no data between the Start & End records*:

ScottPlot Version:5.0.33

I have 48 hours of data, with a timestamp on the x-axis. The data includes a maximum of 4 records per second, meaning there's one record every 250 milliseconds. However, there's a 6-hour gap within this 48-hour period where no data is available. I want to visually indicate this no-data period on the graph (need to "Gray Out" the areas indicating no data has been recorded). 

Is there provision to gray out the graph for no records as per the below image?

![image](https://github.com/user-attachments/assets/6fb6b129-192e-440b-82e3-7d4a930439d2)

How can I achieve this? Please suggest.

**Comment by StendProg** [comment]
Hi @kareem469,

You can try hiding the area with a gray HorizontalSpan. It should go after Plottables but before the marker line.
https://scottplot.net/cookbook/5.0/AxisSpans/
