### ISSUE TITLE
`ScottPlot.PathStrategies.Straight` class should be made `public`

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4346]
For example,

https://github.com/ScottPlot/ScottPlot/blob/5936757cffe2d15923c8f1dd769f9af7d4997d06/src/ScottPlot5/ScottPlot5/PathStrategies/Straight.cs#L7

**Comment by ceceayo** [comment]
Hi! Looking at your code, it appears only the file you are mentioning (Straight.cs) is an internal class. Is this change a one word change or is there more to it?

**Comment by swharden** [comment]
> Hi! Looking at your code, it appears only the file you are mentioning (Straight.cs) is an internal class. Is this change a one word change or is there more to it?

It looks to be like a 1 word fix! :rocket:

**Comment by swharden** [comment]
I'll leave this open in case @ceceayo (or someone from Hacktoberfest?) wants to get credit for this fix 😄
