### ISSUE TITLE
How to add multiple custom Y-axis without moving the drawing area

### ISSUE THREAD

**Issue by CaiNiaoM** [ScottPlot/ScottPlot#4351]
**Question:** (I inherited YAxisBase and customized a Y-axis. When I add multiple custom Y-axis to the left, the drawing area will constantly shift to the right. Because my Y-axis is sorted vertically, I don't want the drawing area to shift to the right)

**ScottPlot Version:** (5.0.39)

**Code Sample:** 

```cs
for (int channel = 0; channel < 10; channel++)
{
    var leftAxis = new MultiYAxis(10, channel)
    {
        Max = 100,//channel % 2 == 0 ? 100 : 200,
        Min = 0,
        IsVisible = true
    };            
    wpfPlot1.Plot.Axes.AddYAxis(leftAxis);
}
```

![image](https://github.com/user-attachments/assets/4ae28a2d-cc49-491d-bb82-e05266f81886)

**Comment by LUJIAN2020** [comment]
Solved? I had the same problem

**Comment by swharden** [comment]
> I inherited YAxisBase

... but the code isn't provided so I can't evaluate it or give much meaningful feedback 😅😅😅 

![image](https://github.com/user-attachments/assets/36757c90-9e31-4ede-92f3-e36e9564f003)

I'll put a little more time here and see if I can make a reproducible example to get this issue started, otherwise I'll probably close it and we can re-open it if someone can provide a code sample that replicates the issue 👍

**Comment by swharden** [comment]
This code works as expected in a new console app, so I'll close this issue and we can re-open it if needed 👍 

```cs
ScottPlot.Plot plt = new();

for (int channel = 0; channel < 10; channel++)
{
    var leftAxis = new ScottPlot.AxisPanels.LeftAxis()
    {
        Max = 100,
        Min = 0,
        IsVisible = true
    };

    plt.Axes.AddYAxis(leftAxis);
}

plt.SavePng("test.png", 800, 300).LaunchInBrowser();
```

![image](https://github.com/user-attachments/assets/f5839ed3-6578-4d93-91c9-4d7e0bca2fb2)

**Comment by swharden** [comment]
Here's some more info that could help!

The question could be re-stated as: ***How can we have multiple plots in a single window?***

* best answer: Place multiple controls in the window. https://scottplot.net/faq/shared-axes/

* second best answer: If it doesn't have to be interactive you can use `Multiplot` https://scottplot.net/cookbook/5.0/MultiplotRecipes/

* third best answer: If you are highly motivated to make an interactive plot with stacked vertical axes like the original screenshot, you can probably achieve this by creating your own custom `ILayoutEngine` and setting `wpfPlot1.Plot.Layout.LayoutEngine` to use it. You can reference [Automatic.cs](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/LayoutEngines/Automatic.cs) to figure out what to modify to prevent the horizontal shifting, probably by manually setting the `paddingNeededForPanels.Left` value to a custom (small) number)
