### ISSUE TITLE
Help with MultiPlot in Windows Forms

### ISSUE THREAD

**Issue by CBrauer** [ScottPlot/ScottPlot#4355]
**Question:** 
I saw your post: "Multiplot was recently added https://github.com/ScottPlot/ScottPlot/pull/4344",
and I cannot make it work in Windows Forms.

**ScottPlot Version:**
5.0.40

**Code Sample:** 

```
using ScottPlot;
namespace ScottPlot_test;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();
        My_Multiplot();
    }

    public void My_Multiplot()
    {
        formsPlot1.Plot.ScaleFactor = 2;
        formsPlot1.Plot.Clear();
        formsPlot1.Refresh();

        Plot plot1 = new();
        var sig1 = plot1.Add.Signal(Generate.Sin());
        sig1.Color = Colors.Blue;
        sig1.LineWidth = 5;

        Plot plot2 = new();
        var sig2 = plot2.Add.Signal(Generate.Cos());
        sig2.Color = Colors.Red;
        sig2.LineWidth = 5;

        MultiPlot mp = new();
        mp.AddSubplot(plot1, 0, 2, 0, 1);
        mp.AddSubplot(plot2, 1, 2, 0, 1);
        mp.Plots[0].Title("Sine");
        mp.Plots[1].Title("Cosine");
        mp.Render(500, 500);

        formsPlot1.Refresh();
    }
}
```

Here is what I get:
![MultiPlot](https://github.com/user-attachments/assets/a7becf58-776a-4436-838f-b37da6c927c6)

Any help will be greatly appreciated.
Charles

**Comment by swharden** [comment]
Hi @CBrauer, I'll close this issue and continue to track progress in #4345

Note that presently MultiPlot isn't documented, but I'm going to try to modify the cookbook today to show how to use it.

Importantly, note that:
* To create multiple plots in a GUI window, place multiple plot controls on that window. 
  * In WinForms, that means having a `formsPlot1` and `formsPlot2`. 
  * See https://scottplot.net/demo/5.0/#shared-axes for code examples
* To create a single image (like a PNG file) with multiple plots, use `MultiPlot`
  * I'll add this to the cookbook today
  * This is only for flat file images, not interactive controls

Hope it helps! 🚀

**Comment by swharden** [comment]
> I saw your post: "Multiplot was recently added https://github.com/ScottPlot/ScottPlot/pull/4344",

For completeness, note that that page says:

_This is only useful for saving image files. This type of plot is not supported in the user controls. To achieve this type of functionality in an interactive app, place multiple controls on the window._
