### ISSUE TITLE
Scale Bug in Callout Feature

### ISSUE THREAD

**Issue by endeffects** [ScottPlot/ScottPlot#4358]
@swharden There is an issue using callouts with time based candle stick charts

Chart without labels
![image](https://github.com/user-attachments/assets/83df0f40-5607-4298-9194-4b1dfd2d2a83)

Chart with labels
![image](https://github.com/user-attachments/assets/ca935d3e-0940-4143-8684-fe7b1c83ff60)

**ScottPlot Version:** latest

```cs
this.chartPlot.Plot.Clear();
this.chartPlot.Refresh();

this.chartPlot.Plot.Add.Candlestick(candles);

foreach (var label in summary.Labels)
{
    this.chartPlot.Plot.Add.Callout(label.Text, label.Time.ToOADate(), Convert.ToDouble(label.Price), label.Time.ToOADate(), Convert.ToDouble(label.Price));
}

this.chartPlot.Plot.Axes.DateTimeTicksBottom();
this.chartPlot.Plot.Axes.AutoScaleExpand();
this.chartPlot.Plot.HideGrid();
this.chartPlot.Refresh();
```

**Comment by endeffects** [comment]
I noticed that the candles are losing it's datetime x-axis relation

![image](https://github.com/user-attachments/assets/16030368-bd8d-4a30-af04-2a17bf7536b4)

**Comment by swharden** [comment]
Thanks @endeffects! Unfortunately the code you shared wasn't sufficient to reproduce the issue (it's incomplete), but this app demonstrates this issue:

```cs
ScottPlot.Plot myPlot = new();

DateTime[] dates = [new(2024, 01, 01), new(2024, 01, 02), new(2024, 01, 03)];
double[] values = [3, 5, 4];

myPlot.Add.Scatter(dates, values);

for (int i = 0; i < 3; i++)
{
    ScottPlot.Coordinates tip = new(dates[1].ToOADate(), values[1]);
    ScottPlot.Coordinates bdy = tip.WithDelta(0.5, 1);
    myPlot.Add.Callout("test", tip, bdy);
}

myPlot.Axes.DateTimeTicksBottom();
myPlot.SavePng("test.png", 400, 300).LaunchFile();
```

![test](https://github.com/user-attachments/assets/460fc7f7-de10-4cc1-aa81-d3d5df774aa7)

**Comment by swharden** [comment]
Merging #4463 now which fixes this issue. It will be in the next release I intend to push to NuGet on Sunday. Thanks again for reporting this! 🚀 

```cs
ScottPlot.Plot myPlot = new();

DateTime[] dates = [new(2024, 01, 01), new(2024, 01, 02), new(2024, 01, 03)];
double[] values = [3, 5, 4];

myPlot.Add.Scatter(dates, values);

for (int i = 0; i < 3; i++)
{
    ScottPlot.Coordinates tipLocation = new(dates[i].ToOADate(), values[i]);
    ScottPlot.Coordinates textLocation = tipLocation.WithDelta(0.2, -.50);
    var co = myPlot.Add.Callout("test", textLocation, tipLocation);
}

myPlot.Axes.DateTimeTicksBottom();
myPlot.Axes.Margins(0.5, 0.5);
myPlot.SavePng("test.png", 400, 300).LaunchFile();
```

![test](https://github.com/user-attachments/assets/9bdbb06f-6a69-447e-8fdf-0388c8488f2a)
