### ISSUE TITLE
Dependencies for WinForms Application

### ISSUE THREAD

**Issue by VKnightNC** [ScottPlot/ScottPlot#4360]
**Question:** What are the dependencies (i.e. project references) for using ScottPlot in a Winforms Application?  I can build and debug, but when I create the installer and install it, it crashes.  I was going to manually add the dependencies myself, stupid NuGet seems to be missing some of what I think are dependencies, or what are indicated as dependencies (like the skiasharp mac-OS package, which is an empty directory).

**ScottPlot Version:** 5.0.40

Edit:  Offending lib seems to be libSkiaSharp - I have no clue where that resides.  Suggest to list all dependencies of ScottPlot in one place, please!

**Comment by swharden** [comment]
Hi @VKnightNC, if you prepare a set of instructions for special steps required to create an app that get's packaged with an installer let me know and I can create a FAQ page on the website adding those notes!

> Suggest to list all dependencies of ScottPlot in one place, please!

It may be useful to note that this information is available on NuGet:
* https://www.nuget.org/packages/ScottPlot#dependencies-body-tab
* https://www.nuget.org/packages/ScottPlot.WinForms#dependencies-body-tab

**Comment by VKnightNC** [comment]
Classification | PRIVATE

Hey again,

This is what I see when I install the nuget package for SkiaSharp for dependencies, you’ll notice there are two additional dependencies, SkaiSharp.NativeAssets.Win32 and NativeAssets.MacOS.  However, there are no dll’s installed with the nuget package in the “lib” directories, just files named “_._” with size zero bytes.   But there is a dll for the Win32 installed in the “runtime” folder.

***@***.***

Here’s the empty file:
***@***.***


For the ScottPlot nuget package, there is a dependency on “SkiaSharp.NativeAssets.Linux.NoDependencies.2.88.8” but just like the MacOS and Win32 mentioned above, there is no dll in the “lib” directory (only the same “_._” file of size zero bytes), but there is a file named libSkiaSharp.so
***@***.***


I’ve tried including these files as references, but Visual Studio chokes as they’re not recognized as valid dll’s (even the libSkiaSharp.dll).

When I remove then reinstall the nuget packages, it tries to add the MacOS dylib file as a project reference, but it chokes as it’s not recognized as a valid dll:
***@***.***

I can run all this in debug mode from within VS.  I’ve added all these files to the installer package so they get copied to the target installation directory, still not working.  It crashes the first time it tries to instantiate a FormsPlot.

Is there something missing from the NuGet package?  Should I contact the SkiaSharp people?  Seems like they should be valid .NET dll’s.

Vicki
____________________________________
Victoria Knight
She/Her/Hers
Staff Test Platform Engineer, Member of Technical Staff
Advanced Test Development
7628 Thornike Road
Greensboro, NC  27409
E ***@***.******@***.***>
W +1 336.678.5365  M +1 336.455.0852

Innovative solutions that connect, protect and power the planet at qorvo.com<http://www.qorvo.com/>
***@***.******@***.******@***.***<http://www.linkedin.com/company/4851811>
[Text  Description automatically generated]<https://www.qorvo.com/>          ***@***.*** <https://qorvo.sharepoint.com/:f:/r/sites/QorvoQNetIQGroup/Shared%20Documents/General?csf=1&web=1&e=X1vRrz>
