### ISSUE TITLE
Is there any reason for callout to include the origin of the coordinates?

### ISSUE THREAD

**Issue by Koji-Morimoto** [ScottPlot/ScottPlot#4364]
**Question:**
Is there any reason for callout to include the origin of the coordinates?
When I try to draw the smallest rectangle surrounding a point cloud, a rectangle containing the origin is always drawn when the Plot contains a callout.
Even if I do not add the rectangle, if I add a Callout, the range of the horizontal and vertical axes drawn when the Plot is displayed will also include the origin.

**ScottPlot Version:**
ScottPlot.WinForms 5.0.40

**Code Sample:** 
```cs
 FormsPlot plotView = new FormsPlot();
 var rect = plotView.Plot.Add.Rectangle(1, 2, 1, 2);//this rectangle does not contain the origin of coordinate.
 var callout = plotView.Plot.Add.Callout("callout", new Coordinates(10, 10), new Coordinates(15, 15));

  AxisLimits limit = new AxisLimits(plotView.Plot.GetPlottables());
  var limitRect = plotView.Plot.Add.Rectangle(limit.Rect);
  limitRect.FillColor = ScottPlot.Colors.Transparent;
  limitRect.LineWidth = 10;
  limitRect.LineColor = ScottPlot.Colors.Red;
```

This is the result of the code above.
![image](https://github.com/user-attachments/assets/6ebe09a3-0065-47fa-9fdf-39b824421067)

**Comment by swharden** [comment]
Hi @Koji-Morimoto, thanks for reporting this! I think it has been fixed in #4463 as described in #4358 and should work better when I publish the next version on NuGet this weekend 👍
