### ISSUE TITLE
Scottplot 5 How to undo SquareUnits?

### ISSUE THREAD

**Issue by cvdevol** [ScottPlot/ScottPlot#4366]
Is there a simple way to undo SquareUnits?
Also, is there a simple way to undo Autoscale?
(I wish these were settable boolean properties rather than methods)

**Comment by MohammadSadeghSalimian** [comment]
Use this  Plot.Axes.AutoScale();

**Comment by MohammadSadeghSalimian** [comment]
> Is there a simple way to undo SquareUnits? Also, is there a simple way to undo Autoscale? (I wish these were settable boolean properties rather than methods)

Use this  Plot.Axes.AutoScale();

**Comment by cvdevol** [comment]
> > Is there a simple way to undo SquareUnits? Also, is there a simple way to undo Autoscale? (I wish these were settable boolean properties rather than methods)
> 
> Use this Plot.Axes.AutoScale();

Doesn't work.

**Comment by swharden** [comment]
Hi @cvdevol, thanks for this question! Hopping into `SquareUnits()` it looks like it works by adding an axis rule.

https://github.com/ScottPlot/ScottPlot/blob/712d236c2f5142824664832fd58c58f3673ad638/src/ScottPlot5/ScottPlot5/AxisManager.cs#L942-L949

Therefore I'm pretty sure you can undo it with:

```cs
formsPlot1.Plot.Axes.Rules.Clear();
```

However I'll add a helper function to make this possible in the next release:
```cs
SquareUnits(false); // restore default behavior
```
