### ISSUE TITLE
Scottplot5 Horizontal and vertical line plots: Add min max like in scottplot4

### ISSUE THREAD

**Issue by nRoger-Env** [ScottPlot/ScottPlot#4368]
**Suggestion:** for Scottplot5 Horizontal and vertical line plots: Add min max like in scottplot4

**Comment by swharden** [comment]
Thanks for the suggestion! This will be in the next release

```cs
myPlot.Add.Signal(Generate.Sin());
myPlot.Add.Signal(Generate.Cos());

var vLine = myPlot.Add.VerticalLine(24);
vLine.Minimum = -.5;
vLine.Maximum = 0.5;

var hLine = myPlot.Add.HorizontalLine(0.73);
hLine.Minimum = 10;
hLine.Maximum = 40;
```

![image](https://github.com/user-attachments/assets/851beed6-4fd3-4cda-90a2-47680bccbff7)
