### ISSUE TITLE
DataLogger: missing `Clear()` and `GetAxisLimits()`

### ISSUE THREAD

**Issue by h135558** [ScottPlot/ScottPlot#4377]
Seems like accidental removal of functions Clear() and GetAxisLimits() in 5.0.38

src/ScottPlot5/ScottPlot5/Plottables/DataLogger.cs
src/ScottPlot5/ScottPlot5/DataSources/DataLoggerSource.cs

Restored functionality would be great.

**Comment by swharden** [comment]
Hi @h135558, thanks for reporting this!

It looks like #4114 is when `Clear()` was removed. I'll ping @drolevar on this one for feedback before I start modifying that class (but if I don't hear back within a few days I'll give it a go). I suspect methods similar the following can be added below this line:

https://github.com/ScottPlot/ScottPlot/blob/55e9eb4d283d06f71611a4df5d4df72e22545b81/src/ScottPlot5/ScottPlot5/DataSources/DataLoggerSource.cs#L15

```cs
public void Clear()
{
    Coordinates.Clear();
    HasNewData = true; // I'm guessing this should be called
}
```

```cs
public AxisLimits GetAxisLimits()
{
    return Coordinates.Any() 
        ? new AxisLimits(GetRangeX(), GetRangeY()) // Is this the most efficient way to get min/max Y?
        : AxisLimits.NoLimits;
}
```

**Comment by swharden** [comment]
@h135558 I'm adding `Clear()` back as suggested

However, I'm uncertain why you reported `GetAxisLimits()` is missing. It's located here and has logic to know whether it's rotated or not:
https://github.com/ScottPlot/ScottPlot/blob/6bc947c0287e592e00f454e73d220ed020001b06/src/ScottPlot5/ScottPlot5/Plottables/DataLogger.cs#L63-L71

**Comment by h135558** [comment]
> @h135558 I'm adding `Clear()` back as suggested
> 
> However, I'm uncertain why you reported `GetAxisLimits()` is missing. It's located here and has logic to know whether it's rotated or not:
> 
> https://github.com/ScottPlot/ScottPlot/blob/6bc947c0287e592e00f454e73d220ed020001b06/src/ScottPlot5/ScottPlot5/Plottables/DataLogger.cs#L63-L71

I see that it is still available. It has just been moved. My code accessed the function by myDataLogger.Data.GetAxisLimits.Top. Changing it to myDataLogger.GetAxisLimits.Top works.
