### ISSUE TITLE
DataLogger: cant add non-ascend x value data point into DataLogger 

### ISSUE THREAD

**Issue by ZooMEISTER** [ScottPlot/ScottPlot#4382]
**Question:** (Ask your question here)
when i try to add non-ascend x value data point into data logger, i get a exception say its not allowed.
i checked  all issues, found  #3743 which was published at apr 27 says its fixed, so i went to download the 5.0.30 which was released at apr 27, and it works just fine. then i checked all release's update logs after 5.0.30, it seems no one metioned datalogger update on this feature, but i cant take advantage of this feature in the latest version.

**ScottPlot Version:** (What NuGet package are you using?)
5.0.40

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
ScottPlot.Plot myPlot = new();
/
/* a code sample may improve communication */
/
![屏幕截图 2024-10-24 155026](https://github.com/user-attachments/assets/da006d5d-2831-481d-aa14-b5f6d942ad66)

**Comment by StendProg** [comment]
Hi @ZooMEISTER,

The changes you highlighted relate to PR #4114. In this PR, the dataLogger is based on a logic for drawing similar to SignalXY. This allows millions of points to be drawn without performance loss, but imposes a limitation on the ordering of points along the X axis. 
A typical use case for DataLogger I think is data from time, which is always ordered, so this change was easily accepted.

It's hard to say how to meet your request, the original solution is redesigned in place rather than left alone, so there is no easy solution to add an additional DataLogger(Scatter).

**Comment by ZooMEISTER** [comment]
Thank you for your time ! @StendProg 
I wonder if you can give me some tip on plot selection
My requests are, the plot should be able to:
1. display dynamic data and don't need to refresh whole plot every time new data comes in ( like data steamer, but data streamer need to "Plots data as a fixed width line plot" )
2. the non-ascend data value is acceptable for x-axis ( like scatter, but scatter need to redraw whole plot every time new data comes in)
3. its in WPF.

actually the DataLogger before 5.0.38 perfectly meet my request, but after that, the new DataLogger doesn't allow non-ascending x-axis value

**Comment by StendProg** [comment]
> the non-ascend data value is acceptable for x-axis

You have no choice but to use the Scatter rendering.

Here are 4 ways you can go about it, from simple to complex:
1. stay on version 5.0.37, but you will lose the fixes/improvements of the new versions.
2. Use Scatter and implement your own X-axis scale control logic similar to DataLogger, but only in the part you need.
3. Implement a custom `DataLoggerScatter` Plottable based on the 5.0.37 source code and use it in conjunction with the latest version of ScottPlot.
4. Make a Pull Request with `DataLoggerScatter` from step 3 to the main ScottPlot library branch.

**Comment by ZooMEISTER** [comment]
got it, thank you
