### ISSUE TITLE
Finance: Improve support for nonlinear a DateTime axis

### ISSUE THREAD

**Issue by quantfreedom** [ScottPlot/ScottPlot#4385]
(edited by Scott): ~~This issue will track creating a financial charting demo with interactive chart functionality. It will remain a work in progress, but the list below will evolve to include new ideas as they are had and track implementation progress.~~

***(edited by Scott): This issue will track adding an easier way to create financial charts without gaps (traditionally achieved using sequential mode) having a horizontal axis that displays dates and times***

## Feature Ideas

- [ ] Customizable bin times (e.g., 5 seconds, 1 hour, 1 day, etc.)
- [ ] Improved/simplified way to manage horizontal (DateTime) tick labels
- [ ] Dotted lines mark the candle nearest the mouse with snapping
- [ ] Option for zooming to automatically set vertical scale to fit the visible price range
- [ ] Improved management of linked multi-plot windows with price action on top and volume (or other metrics) on bottom
- [ ] Price histogram on vertical axis, presumably placed on the right side of the plot
- [ ] Drag-and-drop manipulation of technical indicators:
   - [ ] Trend line (segment, ray, extended)
   - [ ] Flat line (horizontal or vertical, ray or line)
   - [ ] Cross line
   - [ ] Automatic regression line given a time range
   - [ ] Parallelogram (is there a better name for this?) to highlight a channel of price movement
   - [ ] Triangular pattern
   - [ ] Multi-point lines like bat patterns
   - [ ] Fibonacci levels

### Example: TradingView.com
* https://www.tradingview.com/chart/
* https://tradingview.com/#main-market-summary

![image](https://github.com/user-attachments/assets/77295556-a47e-4086-826d-55e9d1bdbc4e)

### Example: QuantTower

* [advanced features](https://www.loom.com/share/df96252a21ba414f84781bf6bc82e659?sid=6d499784-a612-48c5-a0d9-6e72b21f8352) (video)
* [quantower chart types](https://help.quantower.com/quantower/analytics-panels/chart/chart-types)

![image](https://github.com/user-attachments/assets/fc1765a6-be27-4866-853a-424f624b893b)

**Comment by swharden** [comment]
Hi @quantfreedom, thanks for this issue! I'll edit the text or the original post to include a checklist of desired features we can add to as we think of new ones and check-off as they're completed.

Additional resources:
* https://www.tradingview.com/chart/
* https://tradingview.com/#main-market-summary

**Comment by quantfreedom** [comment]
Oh yeah sorry I forgot to add an actual check list ... ill try to add it later if u haven't added it by then

**Comment by swharden** [comment]
> Oh yeah sorry I forgot to add an actual check list ... ill try to add it later if u haven't added it by then

https://github.com/ScottPlot/ScottPlot/issues/4385#issue-2612362937

boom! 🚀

**Comment by swharden** [comment]
I made a really barebones example to get things started. Most features aren't implemented, but it's something. I'll poke at this a little every few days, but it may be useful to learn from even its its current state

![2024-10-24](https://github.com/user-attachments/assets/e508ad7a-2320-49c8-aa02-f37d2c70b3b2)

I'm putting it as a standalone demo app in the sandbox folder of the ScottPlot solution tracked by this GitHub repository (#4388)

![image](https://github.com/user-attachments/assets/6678ecb0-e877-4caf-953e-66e5e7626534)

**Comment by quantfreedom** [comment]
for the next goals we have the time statistics
![image](https://github.com/user-attachments/assets/6b9ef64c-e21f-43ea-a2c5-4232a7d8771d)

![image](https://github.com/user-attachments/assets/5e1f9f88-615d-480b-b065-55749bf66364)

the overall goal is to add a data grid or list view grid type of chart that will display more detailed information about each candle

we will go into more detail during the next convo

**Comment by swharden** [comment]
Hey @quantfreedom, I updated the sandbox demo based on some of the things we discussed yesterday.

I'm going to put this down for now but will refine it here and there over the next several days.

I don't think it's ready for you to dive into code-wise, but I'll keep trying to refine the API to make this type of thing feel a little more natural to the user and be easier to develop for.

Perhaps something you could do now is to help me come up with a color palette you think is good for your app. I mimicked the screenshots above, but if you Google image search for "trading dark mode" you'll find tons of inspiring screenshots. Figure out what colors you most want, list them here (hex codes are ideal), and I can start developing to use them. Feel free to get a bit creative if you want, and if you come up with something a little bit unique (rather than just copying what's out there) you may be able to use it for branding / brand recognition in the future.

![image](https://github.com/user-attachments/assets/961cf111-1a24-49a3-8648-a46639c7cc55)

**Comment by swharden** [comment]
Merging in #4396 which will improve the background styling

![image](https://github.com/user-attachments/assets/ebd8e3d8-0c64-409e-8a46-1d0bfdf02076)

**Comment by quantfreedom** [comment]
Nice things are looking good!

As far as color palette, vlad and I came to the conclusion that colors and themes and styles will be the literal last thing we do because our one and only goal is to just get the thing working ... so once we get it running we will revisit the idea of styling everything

also for an update for me I am still working on building a base framework for the main chart by following along with a tutorial series, so its slow goings lol.

vlad is working on making it so we have a candle database creator

and then after we get that done we are going to work on getting our api to talk to the whole project so we can start getting realtime data and also maybe even placing trades

once we are done with that we will revisit all the things associated with charting that we need to do. So my assumption is that you will also have some beta versions of the ideas we talked about on the call and we will start to be able to give some good feedback.

**Comment by swharden** [comment]
@quantfreedom, sounds good! Since it sounds like you have some backend steps to work on before you intend to develop the charting component I'll take the foot off the gas getting these features implemented. I'll remove the "high priority" label for this issue but will keep it open and poke at this here and there.

As you get closer to being ready to dive into the charting, let me know and I'll mark this as high priority again and slide it to the top of the stack. I'm really incentivized to do a good job here, but I'd probably be most effective if I'm able to match your momentum when you're ready to dive into the frontend work.

I'll be in touch here and in the Discord, and will post new screenshots here as I slowly add features.

Again, feel free to reach out when you're ready to dive into the charting stuff and I'll put some concentrated time into moving this forward when you're ready 🚀

**Comment by swharden** [comment]
Added improved vertical autoscaling in #4410 

The behavior is nice, but the code is messy and I'll refactor the candlestick plot and axis system to make this easier

![2024-10-30](https://github.com/user-attachments/assets/de56a323-85bb-4491-b9e9-42eaccf0b79e)

**Comment by quantfreedom** [comment]
Okay sounds good. Vlad is also going on a little vacation soon and so we will give you an update in about 2 weeks about what we've done.

I agree with you on the decision to make it a non high priority issue right now but I would say the one actual high priority is the nonlinear x-axis for date times. That is needed as soon as you can so if that could be a high priority and then everything else is regular priority that would be great but I'm not sure what else is on your plate so I'll leave that up to you

Because right now we do have candles that are printed maybe one would be 52 seconds to print and then another one would be 37 seconds then another one would be one minute and the next one would be 40 seconds and so on. So being able to display those would be nice. I know u talked about making the x axis like TV so if u need any testing while ur making it just let me know

**Comment by swharden** [comment]
> the one actual high priority is the nonlinear x-axis for date times

I'll refactor this issue to track adding this one feature and it can make it into the next release, then we can track some of the other features in the original message in new issues as we get closer to being ready to focus on developing them 👍

**Comment by quantfreedom** [comment]
Sounds like a plan!

**Comment by swharden** [comment]
Just realized that this view displays the first day of a month using the month name, then only labels the Monday of the last two weeks of the month. Weird. I'll add an example showing how this can be done and merge it in this afternoon.

![image](https://github.com/user-attachments/assets/881a9d68-d49b-4dfa-9adb-00b182944ca1)

**Comment by quantfreedom** [comment]
Ok and once you have done this i should just update the repo on my computer and test it out myself?

also can you add @vladislavpweetsoft to this issue so he can also see the updates

**Comment by swharden** [comment]
Oh wow it's more complicated than that... some weeks it shows 3 intermediate numbers and some it shows 2, and it all changes based on scale 🤪 

![image](https://github.com/user-attachments/assets/0563035b-3497-4f40-9a79-85c8d5f831eb)

I'll merge in an update in about an hour that shows how to do some of this with new features I'm adding to ScottPlot, then I'll leave it to you guys if you want to work out the logic behind "what scales display what days" and extend it. This should be a great starting point though! I'll take you both when I merge it in and it's ready to evaluate 👍

**Comment by quantfreedom** [comment]
I just love it when new things come at you that you didn't know that you didn't know when coding ... so much fun LOL

Yeah ill look out for that update and check it out as soon as i can

**Comment by quantfreedom** [comment]
@swharden its sad cuz i am the client and the boss ... i am getting hit with stress from both sides LOL

![tenor](https://github.com/user-attachments/assets/b06775c1-dd35-4c3d-8c62-30cd44378f1a)

**Comment by swharden** [comment]
lol, me putting time into this as a way to avoid dealing with 200 open issues 💀 

![image](https://github.com/user-attachments/assets/f61ccf1f-a3a6-487e-b9b6-fae0de03e880)

**Comment by swharden** [comment]
Merging #4420 now, and it will close this issue when it finishes running the automated tests. I'll put this down for now, but I think there's everything you all need here to pick up where I left off, and I'm around if you have any questions 🚀🚀🚀

PS: the OHLC and candle plot API is still a bit sloppy, I can help refine it to something easier to use as we learn more about how it will be used in practice.

Thanks @quantfreedom and @vladislavpweetsoft for your help along the way!

![ticks-date2](https://github.com/user-attachments/assets/5d3933a0-8bed-4891-bf92-cb5ddacb8714)

**Comment by tiger2014** [comment]
the crosshair to show time and Y axis value is very important for stock chart. We always need to identify the time of the current candle.

**Comment by swharden** [comment]
> the crosshair to show time and Y axis value is very important for stock chart. We always need to identify the time of the current candle.

Indeed! I will definitely add that feature to the demo soon. In the mean time, this page describes how such a feature may be realized: https://scottplot.net/demo/5.0/#show-value-under-mouse

**Comment by tiger2014** [comment]
> > the crosshair to show time and Y axis value is very important for stock chart. We always need to identify the time of the current candle.
> 
> Indeed! I will definitely add that feature to the demo soon. In the mean time, this page describes how such a feature may be realized: https://scottplot.net/demo/5.0/#show-value-under-mouse

Thanks!
It is typicaly shown like this in TradingView:
![image](https://github.com/user-attachments/assets/8f77f777-80ac-4f6b-8cdf-a6837995b223)
