### ISSUE TITLE
CDN deployment

### ISSUE THREAD

**Issue by LeaFrock** [ScottPlot/ScottPlot#4390]
**Question:** 

I'm using this lib on a website with Blazor WASM. The default way of build and deployment is copy the published files to the `wwwroot\_content` folder.

Now I want to copy the published files to the CDN. But how to let the dependency links be the CDN URL instead of the local `_contents` folder URL? I don't find any related properties of `BlazorPlot` or any extension methods which can help it.

![1729848549700](https://github.com/user-attachments/assets/ab5c60b8-dbd7-45da-83e8-923f17ab9b36)

**ScottPlot Version:** 5.0.40

**Comment by swharden** [comment]
Hi @LeaFrock, I think the way is to edit `index.html` to point to the location of the resources

https://swharden.com/tmp/sp/11/

Notice my source code especially the `base` reference

```xml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>ScottPlot Blazor Sandbox</title>
    <base href="https://swharden.com/tmp/sp/11/" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="css/app.css" />
    <link rel="stylesheet" href="Sandbox.Blazor.WebAssembly.styles.css" />
```
