### ISSUE TITLE
CICD: Automate build and deployment of the .NET Maui package

### ISSUE THREAD

**Issue by King-Taz** [ScottPlot/ScottPlot#4391]
ScottPlot is incompatible with Maui, at least if it's installed according to the QuickStart. Any ideas? Here's what I get...

<img width="796" alt="Screenshot 2024-10-26 000556" src="https://github.com/user-attachments/assets/666d4d4a-e979-49d3-a833-24ff03deec2f">

<img width="527" alt="Screenshot 2024-10-26 000634" src="https://github.com/user-attachments/assets/79a793be-e413-4839-9bfd-53ada7713eb7">

<img width="554" alt="Screenshot 2024-10-26 000653" src="https://github.com/user-attachments/assets/b7fa35fe-96b3-4a04-be9f-6f7d39d293f7">

**Comment by cosmicDustOfLightLength** [comment]
I have the same issue on MAUI Android

**Comment by swharden** [comment]
Hi @King-Taz and @cosmicDustOfLightLength, thanks for reporting this!

I recreated the issue tonight following the instructions on https://scottplot.net/quickstart/maui/

![image](https://github.com/user-attachments/assets/2bcd7018-1bff-40e4-85c7-ef2c6494a519)

It seems this extension method isn't making it into the default namespace.

https://github.com/ScottPlot/ScottPlot/blob/88e36d93a1dd3691845a0500b7e638784263f532/src/ScottPlot5/ScottPlot5%20Controls/ScottPlot.Maui/Register.cs#L12-L16

I'll ping @KosmosWerner to see if they have advice on what the issue may be! At first glance it seems like this should be working.

**Comment by swharden** [comment]
Interestingly, putting that extension method inside the quickstart app fixes the issue! This is a temporary workaround that can be used while we explore a more permanent solution

```cs
using Microsoft.Extensions.Logging;
using SkiaSharp.Views.Maui.Controls.Hosting;

namespace MauiApp1
{
    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .UseScottPlot() // THIS WORKS
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                });
    		builder.Logging.AddDebug();
            return builder.Build();
        }
    }

    public static class RegisterExtensions // THIS WORKS
    {
        public static MauiAppBuilder UseScottPlot(this MauiAppBuilder builder)
        {
            builder.UseSkiaSharp();
            return builder;
        }
    }
}
```

**Comment by swharden** [comment]
## Temporary solution

Instead of `UseScottPlot()` call `UseSkiaSharp()`

```cs
using Microsoft.Extensions.Logging;
using SkiaSharp.Views.Maui.Controls.Hosting; // THIS IS REQUIRED

namespace MauiApp1
{
    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .UseSkiaSharp() // THIS WORKS
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                });

#if DEBUG
    		builder.Logging.AddDebug();
#endif

            return builder.Build();
        }
    }
}
```

**Comment by swharden** [comment]
@KosmosWerner I'm hitting more issues following the quickstart guide 😅 

Are you available to provide a little insight (or ideally make a PR to fix the quickstart)? I'm not very experienced with MAUI so I really appreciate your insight! Thanks so much!


![image](https://github.com/user-attachments/assets/8bfc7b98-c7ba-46dd-a81a-52937db55c74)

**Comment by KosmosWerner** [comment]
@swharden Hi! I hadn’t noticed this before because I was working with my local version, but it seems the MAUI version isn’t on NuGet yet. We just need to update it so it works as expected.

![image](https://github.com/user-attachments/assets/f3e265d2-0fd2-4651-b47b-c1e66cb0c85e)

**Comment by swharden** [comment]
> @swharden Hi! I hadn’t noticed this before because I was working with my local version, but it seems the MAUI version isn’t on NuGet yet. We just need to update it so it works as expected. 5.0.36 -> 5.0.42

Great catch - Thanks so much! 🙏🙏🙏

The issue is that my CICD pipeline isn't setup to build and publish the Maui package. I'll make that change now and it should go live in a few minutes and we can try again 🤞

**Comment by swharden** [comment]
Note to self: deployment pipeline is running now so if the package doesn't appear soon check the logs here https://github.com/ScottPlot/ScottPlot/actions/runs/11603851692

**Comment by swharden** [comment]
Ah, the Maui package on NuGet didn't have appropriate permissions to auto-deploy.

![image](https://github.com/user-attachments/assets/f10e7816-c8ca-4050-b0b8-d0965cadd5bc)

![image](https://github.com/user-attachments/assets/1f11b4cf-6946-4f98-866d-891fd949929d)

 Fixing now and re-running...

https://github.com/ScottPlot/ScottPlot/actions/runs/11603851692

**Comment by KosmosWerner** [comment]
I just tested it in my project, and now the MAUI package works perfectly 🎉
If there’s any other issue, let me know and I’ll take a look

**Comment by swharden** [comment]
Good to know @KosmosWerner!

For comparison, can you share your project's csproj file?

This is as far as I'm getting 😅 

![image](https://github.com/user-attachments/assets/0f35751e-76ae-4700-aac1-003bf70774f1)

**Comment by KosmosWerner** [comment]
![image](https://github.com/user-attachments/assets/777e3af2-ca5b-4c36-b8fe-73aaaee21651)

I tried removing <WindowsSdkPackageVersion>10.0.19041.34</WindowsSdkPackageVersion>, and I got the error you're showing. With that line, it works

![image](https://github.com/user-attachments/assets/4a4a3f45-3e65-4750-8fd4-edad9ed0cdd0)

**Comment by KosmosWerner** [comment]
I just realized that `<WindowsSdkPackageVersion>10.0.19041.34</WindowsSdkPackageVersion>` is not in the Quickstart; that's the reason for the error. For some reason, SkiaSharp fails if that line is not added 😔 https://github.com/mono/SkiaSharp/issues/2999

https://github.com/ScottPlot/ScottPlot/pull/4320#issue-2582460507

**Comment by King-Taz** [comment]
Thanks, it's working in my Maui app now.  There was one hiccup. 

.UseScottPlot() did not work until I added the extension (as done above)

![image](https://github.com/user-attachments/assets/ce0f9d51-a0d5-4bc9-b60f-e93c58af99ea)


along with .UseSkiaSharp()

![image](https://github.com/user-attachments/assets/fcc42aa3-b901-4447-8b83-aaca7fc05972)


After doing that one time, .UseScottPlot() works without including the extension or the .UseSkiaSharp().

If memory serves, the <WindowsPackageSDK> was in the QuickStart at one time.

![image](https://github.com/user-attachments/assets/c8655877-c73b-4216-abdd-7e395ad42272)

**Comment by KosmosWerner** [comment]
I’m glad it worked! Previously, the `WindowsSdkPackageVersion` part was in the QuickStart, I proposed it in my PR for MAUI https://github.com/ScottPlot/ScottPlot/pull/4320#issue-2582460507 . Maybe it got lost in some update. If there are any issues, feel free to let me know, and I’ll take a look. Just keep in mind that MAUI has some limitations in recognizing mouse buttons or keys, but it should work on mobile.

**Comment by King-Taz** [comment]
I'm plotting some arrows

![image](https://github.com/user-attachments/assets/f72406f1-d8e5-42ef-808f-942486308dbe)

Android (emulator) works well. Windows and iOS has graphic glitch when panning where the arrows momentarily jump (nearly) off-screen. The glitch can be removed in Windows using right-click "autoscale". Since I cannot programmatically fix the glitch using autoscale commands to work in iOS, I had to disable user input with PlotControl.UserInputProcessor.Disable(); 

It would be great to have pan/zoom features, but the app will work without them.
