### ISSUE TITLE
Cookbook: add toggle for GUI framework and improve styling

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4392]
After #4380 start working on these:
- [x] Wrap recipes in a rounded border box or something to make it clear what a single recipe is
- [x] Add recipe permalink icon
- [x] Add category permalink icon
- [x] Add cookbook home icon
- [x] Add recipe source code icon
- [x] Add a toggle to switch between console, WinForms, and WPF, etc.
- [x] Add similar features to the quickstart pages

**Comment by swharden** [comment]
platform switching is live, but there's still work to do to improve the styling

https://scottplot.net/cookbook/5.0/ScottPlotQuickstart/

![image](https://github.com/user-attachments/assets/d77b5afb-cc14-411d-aff9-ce075660a157)

**Comment by StendProg** [comment]
It looks beautiful!
But all tabs are open on Console by default. I think most users are focused on a single platform. And it's not convenient to switch examples every time to say Winforms. It would be convenient to have a global setting, at the top of the page and/or for the whole CookBook. This setting would make the example tabs open by default for the selected platform. At the same time leave the possibility to switch manually each one separately, it does not bother anyone.

**Comment by swharden** [comment]
> It looks beautiful!

Thanks! I'm still working to improve it, but it's a good start 😀

> But all tabs are open on Console by default. I think most users are focused on a single platform. And it's not convenient to switch examples every time to say Winforms. It would be convenient to have a global setting, at the top of the page and/or for the whole CookBook. This setting would make the example tabs open by default for the selected platform. At the same time leave the possibility to switch manually each one separately, it does not bother anyone.

Good idea! I'll probably make it so changing the platform in one recipe sets the platform for all recipes on that page.

I'll also think about what I may be able to do to help it "remember" the setting across pages.

**Comment by swharden** [comment]
It looks a little more like VS code now, which I think is good. I made the background lighter as an alternative to adding lighter dividing lines between buttons.

![image](https://github.com/user-attachments/assets/4ddd83dc-205c-4653-90b1-3488f70f28c2)

**Comment by swharden** [comment]
Hi @StendProg, thanks again for these suggestions! I'm now using client-side storage to persist preferred language settings across page loads. 

Give it a try (you may have to F5 to refresh the page) and let me know if you have any other suggestions for the cookbook in the future! This is looking really nice now.

**Comment by StendProg** [comment]
Hi @swharden.

> This is looking really nice now.

It originally looked very cool, and now it's even more convenient. Selected tab is saved even between sessions, which is more than enough.

As a criticism:
“Edit on Github” is not quite right in meaning. A user would probably want to go to `view`, not `edit`.
The link leads to a general folder instead of a specific recipe. (I don't know how difficult this is to implement).

It would be really cool to add VB.NET as well, but I'm well aware that it's not realizable.

**Comment by swharden** [comment]
> Edit on GitHub

I'll open this issue back up and track adding that feature! Thanks for the suggestion

> It would be really cool to add VB.NET as well

Such a link could probably link to https://converter.telerik.com/ or maybe use whatever they're using to do the conversion ourselves. However I'm sure once we implement that someone will ask about F# too 🙃
