### ISSUE TITLE
after load data or after zoom extends is x-axis mirrored?!

### ISSUE THREAD

**Issue by MarioRosi** [ScottPlot/ScottPlot#4398]
Hello,

i load my datas (is temperature/datetime) and set the bottom axis to dateTimTicks.
But after Refresh() is the x-axis not display and the gaph is in the x-axis mirrored.
When i scale with mousewheel display the date-time and swap the graph correct.
After double-middle-mouse click is zoom extends and display again without x-axis-label and mirrored the graph.

What can i do?!

**ScottPlot Version:** (5.0.40)

```cs
this.TempPlott.BeginInit();
this.TempPlott.Plot.Clear();
foreach (DBSensor sensor in sensoren)
{
    var sensorPlott = this.TempPlott.Plot.Add.Scatter<DateTime, double>(temperaturen[sensor].Item1, temperaturen[sensor].Item2);
    sensorPlott.Color = new ScottPlot.Color(sensor.ColorR(), sensor.ColorG(), sensor.ColorB(), sensor.ColorA());
    sensorPlott.LineWidth = 3;
    sensorPlott.MarkerSize = 3;
}
this.TempPlott.Plot.Axes.DateTimeTicksBottom();
this.TempPlott.Plot.Axes.AutoScale(true);
crossHair = this.TempPlott.Plot.Add.Crosshair(0, 0);
this.TempPlott.EndInit();
this.TempPlott.Refresh();
```

regards Mario

**Comment by StendProg** [comment]
Hi @MarioRosi.


1. Double-check your data.
Especially the year in DateTime.
ScottPlot uses a date range clamp outside the range 100<x<10_000 years. This can lead to strange effects.
It is very hard to say anything further without a test case with the data.

2. Also questionable is the proper use of CrossHair.
You can comment it out to make sure it is not the case.
If it is, the correct thing to do is to set a date value within your date range, and then convert DateTime to OAth format.

```c#
DateTime crosshairTime = DateTime.Now;
crossHair = this.TempPlott.Plot.Add.Crosshair(crosshairTime.ToOADate(), 0);
```

**Comment by MarioRosi** [comment]
Hello,

@2 .  i have changed too calculate center DateTime and center temperatur. Thas is more correctly as 0,0 ;-)
@1.: The data comes from an SQlite DB. All data is currently still Ecxel generated demo data.

For testcase i have change the initial-code, no crosshair, reproducible data:
´´´cs
            this.TempPlott.BeginInit();
            this.TempPlott.Plot.Clear();
            List<double> listDate = new List<double>();
            List<double> listTemp = new List<double>();
            double cuDate = 45593.1;
            double cuTemp = 20.0;
            for (int i=0; i < 20; i++)
            {
                listDate.Add(cuDate);
                listTemp.Add(cuTemp);
                cuDate += .3;
                cuTemp += 10;
            }
            var sensorPlott = this.TempPlott.Plot.Add.Scatter<double, double>(listDate, listTemp);
            sensorPlott.Color = ScottPlot.Colors.Red;
            sensorPlott.LineWidth = 3;
            sensorPlott.MarkerSize = 3;
            this.TempPlott.Plot.Axes.DateTimeTicksBottom();
            this.TempPlott.Plot.Axes.AutoScale(true);
            this.TempPlott.EndInit();
            this.TempPlott.Refresh();
´´´

Result after start or after double-middlemouse-click (falling line, no date label on bottom-axis)
![afterLoad](https://github.com/user-attachments/assets/e32c1e96-a011-457a-a596-6d8eeb3aebe3)
after mouse-wheel its all fine:
![after MouseWheel](https://github.com/user-attachments/assets/5841660f-761b-44ad-878f-c613a2271c14)

what must i do for correctly initial display?

regards Mario

**Comment by StendProg** [comment]
```c#
this.TempPlott.Plot.Axes.AutoScale(true);
```
The first argument of this method indicates the need to invert the X-axis. Which is what you get but really don't want.

Just call `AutoScale()` without the argument.
