### ISSUE TITLE
How can i disable mouse event in wpf

### ISSUE THREAD

**Issue by ZooMEISTER** [ScottPlot/ScottPlot#4402]
**Question:** (Ask your question here)
cant disable mouse event in wpf,

**ScottPlot Version:** (What NuGet package are you using?)
5.0.37

I used this:
```cs
dataCurveChart.UserInputProcessor.IsEnabled = false;
```
but its not working, i can still interact with the plot with my mouse

**Comment by swharden** [comment]
A new package was published tonight.

Let me know if it doesn't work as expected!
