### ISSUE TITLE
Is it possible to only display the years (centered) of a plot with date axis?

### ISSUE THREAD

**Issue by Or8e4m4n** [ScottPlot/ScottPlot#4407]
I believe that there have been recent improvements with date axis. However, I'm not so sure how to customise them. Ideally I would like to only display the years in the **middle** (centered)... of the years. Is it possible to achieve it?

For now I don't really want to refine the label if scrolled in, but why not also showing the months in the middle of the months in the future...

I rendered the chart below using Chart.js on a ASP.NET project :

![{59D3C7E5-8922-4BFD-B820-72487560033B}](https://github.com/user-attachments/assets/2fdfd562-0f83-4b1e-8a9f-d39b46f77c45)

Note that the width of the years takes into consideration the number of the days.

Thanks for you assistance!

**Comment by swharden** [comment]
Hi @Or8e4m4n 

I think you may be able to achieve this effect using manually defined ticks

https://scottplot.net/cookbook/5.0/CustomizingTicks/CustomTicks/

You can create a collection of ticks placed in the middle of each year with a label that is the name of that year.

Note that you can use DateTime's ToOADate() method to convert a DateTime to an X position in double format.

Let me know if this doesn't do the trick and we can open this issue back up and take a closer look together 👍

**Comment by swharden** [comment]
I now realized my solution will replace the ticks entirely and it's not ideal when zoomed in.

I'll reopen this issue and see if I can come up with a solution this evening 👍

**Comment by Or8e4m4n** [comment]
Well, I didn't remember, I already coded something a while ago which I've just slightly improved.

I think I should manually add a tick if for example there is no `dt.Month == 1` and probably deals with the actual year label as minor tick (without the the marker) and duplicate it to the beginning of the year as major with maker but without the label.

I also think it has some issues (shift) when zooming, but maybe am I asking too much!!

PS It is almost the time for me to go to sleep (France), so I'll see it I have some insights during the night...

```
plot.RenderManager.RenderStarting += (s, e) =>
{
    var ticks = bottom.TickGenerator.Ticks;

    // Loops through all ticks.
    for (int i = 0; i < ticks.Length; i++)
    {
        var dt = DateTime.FromOADate(ticks[i].Position);

        var position = 0d;

        var label = string.Empty;

        // Only deals with the first tick of the year.
        if (dt.Month == 1)
        {
            var year = dt.Year;

            var from = new DateTime(year, 1, 1);
            var to = new DateTime(year, 12, 31); // new DateTime(year + 1, 1, 1)

            position = (from.ToOADate() + to.ToOADate()) / 2;

            label = $"{dt:yyyy}";
        }

        ticks[i] = new Tick(position, label);
    }
};
```

**Comment by swharden** [comment]
Hi @Or8e4m4n, without seeing this I created my own implementation and funny how we approached it the same way!

This didn't do the job though, because yes it moved the labels but it also moved the tick marks and grid lines too, so it's not ideal...

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        double[] values = Generate.RandomWalk(10_000);
        DateTime[] dates = Generate.ConsecutiveDays(values.Length);
        formsPlot1.Plot.Add.Scatter(dates, values);
        formsPlot1.Plot.Axes.DateTimeTicksBottom();

        formsPlot1.Plot.RenderManager.RenderStarting += (s, e) =>
        {
            Tick[] ticks = formsPlot1.Plot.Axes.Bottom.TickGenerator.Ticks;
            bool yearScale = int.TryParse(ticks.FirstOrDefault().Label, out _);
            if (yearScale)
            {
                formsPlot1.Plot.Title("Year tick adjustment enabled");
                for (int i = 0; i < ticks.Length; i++)
                {
                    DateTime originalDateTime = DateTime.FromOADate(ticks[i].Position);
                    DateTime newDateTime = new(originalDateTime.Year, 6, 1);
                    double newPosition = newDateTime.ToOADate();
                    ticks[i] = new Tick(newPosition, ticks[i].Label);
                }
            }
            else
            {
                formsPlot1.Plot.Title("Default DateTime ticks");
            }
        };
    }
}
```

![image](https://github.com/user-attachments/assets/8ddd988e-50ab-4c41-ab95-da8439b56dae)

![image](https://github.com/user-attachments/assets/927096fd-3ed8-4dbf-8451-8204320b16c7)

**Comment by swharden** [comment]
Ah, got it! This should do the trick. Very interesting solution!

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        double[] values = Generate.RandomWalk(10_000);
        DateTime[] dates = Generate.ConsecutiveDays(values.Length);
        formsPlot1.Plot.Add.Scatter(dates, values);
        formsPlot1.Plot.Axes.DateTimeTicksBottom();

        formsPlot1.Plot.RenderManager.RenderStarting += (object? s, RenderPack e) =>
        {
            Tick[] ticks = formsPlot1.Plot.Axes.Bottom.TickGenerator.Ticks;
            bool yearScale = int.TryParse(ticks.FirstOrDefault().Label, out _);
            if (yearScale && ticks.Length > 1)
            {
                double tickDelta = ticks[1].Position - ticks[0].Position;
                double pxPerUnit = e.DataRect.Width / formsPlot1.Plot.Axes.Bottom.Range.Span;
                float tickDeltaPx = (float)(pxPerUnit * tickDelta);
                formsPlot1.Plot.Axes.Bottom.TickLabelStyle.OffsetX = tickDeltaPx / 2;
            }
            else
            {
                formsPlot1.Plot.Axes.Bottom.TickLabelStyle.OffsetX = 0;
            }
        };
    }
}
```

![image](https://github.com/user-attachments/assets/325b8b45-fd53-4f36-af5c-234c61564159)

**Comment by Or8e4m4n** [comment]
Thanks Scott, it works fine in WPF. The key element was to shift all the labels at once and not them individually.

Strictly speaking, it not perfectly accurate since there is not the same numbers of days for each year, but it is precise enough though.

Nevertheless, I think they is a minor issue with `ticks.FirstOrDefault().Label` when zooming in too much, but I might be able to adjust it.
