### ISSUE TITLE
How to make a scatter and a custom Plottable render separately ?

### ISSUE THREAD

**Issue by luyingru555** [ScottPlot/ScottPlot#4411]
**Question:** (How to make a scatter and a custom Plottable（implements IPlottable） render separately ?)
 When “Refresh()”function is used, RenderActions will be rendered together, which means scatter and custom Plottable will be rendered together. I want to write a function which need to move the custom Plottable, but it is diffcult to move quickly when the scattet contains lots of points because of the above question. Are there any ways to solve it？

**ScottPlot Version:** (5.0.42)

**ScottPlot Code :** See [http://scottplot.net/faq/repro/ for tips about creating reproducible code samples](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5/Rendering/RenderManager.cs)

```cs

 foreach (IRenderAction action in RenderActions)
 {
     sw.Restart();
     rp.CanvasState.Save();
     action.Render(rp);//When Refresh() function is used, RenderActions will be Rendered together
     rp.CanvasState.RestoreAll();
     actionTimes.Add((action.ToString() ?? string.Empty, sw.Elapsed));
 }
```

**Comment by StendProg** [comment]
HI @luyingru555,

It sounds like you want to propose a layer system. This has been discussed quite recently and is marked as not planned #4405.

First of all make sure you can't use Signal Plottable. If you have the ability to use signals, you won't run into performance issues.

If you are willing to go further, you can create your own Control that has a layer system. I did that once upon a time, the code is very outdated but you can look up the idea #687.

**Comment by luyingru555** [comment]
Thank you for your answer! 
 I'm not sure if I have correctly understood the use of Signal, but it seems that Signal and SignalXY are not quite suitable for custom data on both the X and Y axes. I think I will try the suggestion of using layer.
