### ISSUE TITLE
Feature Request: Add Support for Ternary Diagrams

### ISSUE THREAD

**Issue by manaruto** [ScottPlot/ScottPlot#4413]
I’d like to suggest a new plot for ScottPlot: support for ternary plots. Ternary diagrams are valuable for visualizing data that represents three interdependent components, each summing to a constant (typically 1 or 100%). They’re widely used in fields such as chemistry, geosciences, and environmental science to display compositional data.

https://www.ternaryplot.com/

https://en.wikipedia.org/wiki/Ternary_plot

**Comment by swharden** [comment]
Hi @manaruto, thanks for this suggestion!

I would love to see this feature added to ScottPlot. I don't intend to add this myself in the short term, but you or another member of the open source community could implemented it pretty easily, and if someone creates a pull request I would be happy to review it and merge it into an upcoming release.

The implementation could mimic how polar axes were added. Basically create an `IPlottable` that knows how to draw the axes and also have methods to translate coordinates from triangular space to Cartesian space. If you start by copying the polar axis class and modify the code as needed, it should be feasible to implement without too much effort.

https://scottplot.net/cookbook/5.0/Polar/

https://github.com/ScottPlot/ScottPlot/blob/0d1177bc94dcbaa79678e55d9016c86595e654b2/src/ScottPlot5/ScottPlot5/Plottables/PolarAxis.cs#L1-L267

I'll close this issue for now, but if someone creates a pull request to add this feature we can reference this issue, and if someone wants help while trying to implement this I'm happy to take a look at their work in progress 👍 

## Example Ternary Diagram

![image](https://github.com/user-attachments/assets/fd7947ac-f16f-4df5-a4a0-c30e252f20fa)

**Comment by manaruto** [comment]
I'm happy to share that I implemented the TernaryAxis class, along with two helper classes, TernaryAxisCornerLabel and TernaryAxisEdge, to support customizable ternary plotting capabilities in ScottPlot.

I’ve submitted a pull request with details on usage and customization. Please let me know if there's anything I can improve or refine further!

![ternary plot](https://github.com/user-attachments/assets/e6dabd95-368c-4f70-97f8-c75a2e61a413)
