### ISSUE TITLE
Scatter: fill under line fails when Y offset is used

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4433]
OffsetY = 0 | OffsetY = 3
---|---
![image](https://github.com/user-attachments/assets/51844b8c-f5a3-401e-96a9-ed0765f52848)|![image](https://github.com/user-attachments/assets/14b8b0c9-a54e-46bf-8faa-e3a713c8e6a8)

**Comment by CoderPM2011** [comment]
https://github.com/ScottPlot/ScottPlot/blob/ede0a913b6cedc116392a3f57c1764554a07ab90/src/ScottPlot5/ScottPlot5/Plottables/Scatter.cs#L41

Because the default value of `FillYValue` is `0`, if it is changed to `3`, it will be consistent with `OffsetY = 0`.

like this:
![image](https://github.com/user-attachments/assets/cbc9f670-a263-44ba-9bf0-a7e230a0dc38)

## test code
``` cs
double[] xs = Generate.Consecutive(51);
double[] ys = Generate.Sin(51, offset: 3);

var sp = formsPlot1.Plot.Add.Scatter(xs, ys);
sp.FillY = true;
sp.FillYValue = 3;
sp.FillYColor = sp.Color.WithAlpha(.2);

formsPlot1.Refresh();
```

**Comment by swharden** [comment]
@CoderPM2011 thanks for your feedback! I could have been more clear in my original description though. The offset be behavior I'm referring to is demonstrated in the code below. I welcome feedback about what the most "natural feeling" API is here!

```cs
using ScottPlot;

Plot myPlot = new();

double[] ys = Generate.Sin(100, oscillations: 3);
double[] xs = Generate.Consecutive(100);

for (int i = 0; i < 10; i++)
{
    var sig = myPlot.Add.ScatterLine(xs, ys);
    sig.OffsetX = 3 * i;
    sig.OffsetY = i;
    sig.LineWidth = 2;
    sig.FillY = true;
    sig.FillYColor = sig.LineColor.WithAlpha(0.2);
    sig.FillYValue = sig.OffsetY; // should this be required?
}

myPlot.SavePng("demo.png", 400, 300).LaunchFile();
```

Also it looks like there's an autoscale issue happening here too...

default | FillYValue
---|---
![demo](https://github.com/user-attachments/assets/035c91d8-1a59-438a-831b-d37bf274b867)|![demo](https://github.com/user-attachments/assets/dca2cb67-a029-4f9e-9b6a-493a9badeac2)

For some context, here's a figure for a while back demonstrating the concept using Python and matplotlib

![image](https://github.com/user-attachments/assets/4fb7eabe-bcd1-4283-ba31-d8f60c5f6f5c)

**Comment by swharden** [comment]
Further clarifying the goal,

```cs
// create data points that resemble a "hump"
double[] ys = Generate.Cos(100, oscillations: 0.5, phase: -0.25);
double[] xs = Generate.RangeWithCount(0, 1, ys.Length);
```

```cs
// scatter with no offset
var sp1 = plot.Add.ScatterLine(xs, ys);
sp1.LineWidth = 3;
sp1.LineColor = Colors.Black;
sp1.FillY = true;

// scatter with offset
var sp2 = plot.Add.ScatterLine(xs, ys);
sp2.LineWidth = 3;
sp2.LineColor = Colors.Black;
sp2.FillY = true;
sp2.OffsetX = 2;
sp2.OffsetY = 2;
```

original behavior | desired behavior
---|---
![Test_Scatter_FillAndOffset](https://github.com/user-attachments/assets/38449ea8-2df7-4225-bbe4-9ce02c85b74f)|![Test_Scatter_FillAndOffset](https://github.com/user-attachments/assets/44f41833-0ed5-4cec-94f9-e31f6b54c2f2)
