### ISSUE TITLE
Axes.NumericTicksBottom() needed to revert DateTimeTicksBottom()

### ISSUE THREAD

**Issue by Cassar17** [ScottPlot/ScottPlot#4438]
**Question:**

I have a program in which the user can import excel files and transform the data into a SignalXY plot. This plot may or may not have DateTimeAxis on the bottom, depending on the type of data that the user imported. When the user imports data with DateTime, there's a check that implements the function WpfPlotMain.Plot.Axes.DateTimeTicksBottom(), and it works fine.

The problem is if the user, after importing a DateTime file, decides to then import a new file without datetime. This goes into the "else" condition, in which the main difference is that there's no call to DateTimeTicksBottom(). However, even so, the plot remains attempting to convert the indexes into the DateTime format, causing incorrect labels. I believe this happens because, despite using Plot.Clear(), the plot retains the information that the ticks on the bottom are supposed to be DateTime from the previous iteration.

How can I fix this issue? Is there a way to force the bottom axes to be numeric indexes, much like there's a way to force it to be DateTime?

Example when the user first imports a file with DateTime:
![image](https://github.com/user-attachments/assets/0073616c-cc2a-42fa-9941-176532634e30)
Example when the user, without closing and reopening the app (otherwise it would work fine), opens a file without DateTime:
![image](https://github.com/user-attachments/assets/cdb9fdbd-778c-49ea-8b8b-4647830247aa)
Zooming in:
![image](https://github.com/user-attachments/assets/ea771695-97ac-4b62-869a-3c27bd419acc)

To be clear, there is no issue if the user opens the app and opens the non-DateTime file first, as it correctly shows the indexes on the bottom axis:
![image](https://github.com/user-attachments/assets/fcacd05d-94cb-4915-babc-d4ce2c071753)

**ScottPlot Version:**
5.0.41

**Code Sample:** 
```cs

List<HistoryVector> historyVector = GlobalUtility.Clone(model.HistoryVector);
ScottPlot.Plottables.SignalXY? plotSignal;

WpfPlotMain.Plot.Clear();

double[] YAxis = historyVector.Select(p => p.EixoY).ToArray();

if (model.TimeStamp)
{
	DateTime[] xLabels = historyVector.Select(p => p.EixoX_Time).ToArray();
	plotSignal = WpfPlotMain.Plot.Add.SignalXY<DateTime, double>(xLabels, YAxis);
	WpfPlotMain.Plot.Axes.DateTimeTicksBottom();


}
else
{
	
	double[] XAxis = historyVector.Select(p => (double)p.EixoX).ToArray();
	plotSignal = WpfPlotMain.Plot.Add.SignalXY(XAxis, YAxis);

}
```

**Comment by swharden** [comment]
Hi @Cassar17, thanks for reporting this! I'll use this issue to track adding a helper function like `NumericTicksBottom()` to help reset to the default behavior. Details below will help figuring out how to best do that:

It seems you are using something like this to replace the bottom axis with one that displays dates:

```cs
WpfPlotMain.Plot.Axes.DateTimeTicksBottom();
```

https://scottplot.net/cookbook/5.0/AxisAndTicks/DateTimeAxisQuickstart/

Looking at the code, it removes the default bottom axis and adds a new one:
https://github.com/ScottPlot/ScottPlot/blob/ede0a913b6cedc116392a3f57c1764554a07ab90/src/ScottPlot5/ScottPlot5/AxisManager.cs#L246-L262

We can probably setup default axes by mimicking logic in the constructor of that class

https://github.com/ScottPlot/ScottPlot/blob/ede0a913b6cedc116392a3f57c1764554a07ab90/src/ScottPlot5/ScottPlot5/AxisManager.cs#L127-L145

IMPORTANT: Every plottable (the signalXY plots in your case) has `Axes.XAxis` and `Axes.YAxis` that properties that must be set if the axes change, so changes to the axes _after_ plottables are added to the plot must account for this.

This may be enough information for you to solve this in your own app right away! I'll leave this issue open though to track adding a simpler solution that makes this easier in future versions.

**Comment by Cassar17** [comment]
Thank you for the solution! Although it is quite lenghty, it seems to be working fine. 

For future reference if anyone else is having this issue, this is the updated code:

I also had to remove all the axis, otherwise it would keep generating one on top of another.

```cs

List<HistoryVector> historyVector = GlobalUtility.Clone(model.HistoryVector);
ScottPlot.Plottables.SignalXY? plotSignal;

WpfPlotMain.Plot.Clear();

double[] YAxis = historyVector.Select(p => p.EixoY).ToArray();

if (model.TimeStamp)
{
	DateTime[] xLabels = historyVector.Select(p => p.EixoX_Time).ToArray();
	plotSignal = WpfPlotMain.Plot.Add.SignalXY<DateTime, double>(xLabels, YAxis);
	WpfPlotMain.Plot.Axes.DateTimeTicksBottom();
	if (ThemeType == ThemeType.SoftDark) WpfPlotMain.Plot.Axes.Color(Color.FromHex("F0F0F0F0"));
}
else
{
	WpfPlotMain.Plot.Axes.Remove(Edge.Bottom);
	WpfPlotMain.Plot.Axes.Remove(Edge.Left);
	WpfPlotMain.Plot.Axes.Remove(Edge.Top);
	WpfPlotMain.Plot.Axes.Remove(Edge.Right);

	double[] XAxis = historyVector.Select(p => (double)p.EixoX).ToArray();
	plotSignal = WpfPlotMain.Plot.Add.SignalXY(XAxis, YAxis);

	IXAxis xAxisPrimary = new BottomAxis();
	IYAxis yAxisPrimary = new LeftAxis();

	WpfPlotMain.Plot.Axes.AddXAxis(xAxisPrimary);
	WpfPlotMain.Plot.Axes.AddYAxis(yAxisPrimary);

	IXAxis xAxisSecondary = new TopAxis();
	IYAxis yAxisSecondary = new RightAxis();

	WpfPlotMain.Plot.Axes.AddXAxis(xAxisSecondary);
	WpfPlotMain.Plot.Axes.AddYAxis(yAxisSecondary);

	WpfPlotMain.Plot.Axes.DefaultGrid = new ScottPlot.Grids.DefaultGrid(xAxisPrimary, yAxisPrimary);

	WpfPlotMain.Plot.Grid.MajorLineWidth = 2;
	WpfPlotMain.Plot.Grid.MinorLineWidth = 1;
}

```
