### ISSUE TITLE
User input processor: allow X and Y zoom sensitivity to be distinctly configured

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4443]
Following conversation with @King-Taz and @KosmosWerner in #4416 

> Mouse zoom sensitivity is too high high. Android on the order of 2 or 3. iOS on the order of 20 to 30

**Comment by swharden** [comment]
In the next release, click-drag zoom sensitivity can be changed like this:

```cs
foreach (var response in formsPlot1.UserInputProcessor.UserActionResponses)
{
    if (response is ScottPlot.Interactivity.UserActionResponses.MouseDragZoom zoom)
    {
        zoom.SensitivityX = 10;
        zoom.SensitivityY = 10;
    }
}
```

**Comment by King-Taz** [comment]
Works great! Very nice work!
