### ISSUE TITLE
Need to scale label fontsize dynamically

### ISSUE THREAD

**Issue by King-Taz** [ScottPlot/ScottPlot#4446]
**Question:** Is it possible to get notification from ScottPlot of a change in plot scaling to dynamically scale some labels?

**ScottPlot Version:** 5.0.43 with Maui

**Code Sample:** 
I've tried a couple of approaches ...

```
        MauiPlot.Plot.Renderer.AfterDraw += (plt, dims) =>
        {

        };
```
```
        mauiPlot.Plot.AxisChanged += (s, e) =>
        {

        };
```
and looked through the demos. Can't seem to find how to do this. Any suggestions appreciated!

**Comment by swharden** [comment]
This should help! You can customize font size based on width and/or height of the figure or data area in pixel units

https://scottplot.net/faq/render-starting/#dynamic-styling

**Comment by swharden** [comment]
I will reopen this issue to track adding an extension method to make this easier... But the render pack has a DataRect with a Width you can divide by Axes.GetLimits().Width or something like that to get scale in px/unit

**Comment by King-Taz** [comment]
Yes, GetLimits works well. Just wanted to be sure I wasn't missing something obvious!  Thanks for considering adding this.  Is there a 1 line way to get the X length? I'm using 2 lines
```
                var lmts = MauiPlot1.Plot.Axes.GetLimits();
                var lngth = lmts.XRange.Length;
```

**Comment by swharden** [comment]
Glad you reached a solution!

> I will reopen this issue to track adding an extension method to make this easier... 

Because the DataRect is generated dynamically based on the layout, I probably won't add properties like `PixelsPerUnitX` to RenderPack`, as users can calculate what they want at the time it's needed.

**Comment by King-Taz** [comment]
Completely understandable! I'm of the mindset that if the library is already calculating these quantities, performance is optimized and app is minimized if they're available to users, eliminating repeated calculations over several calls.
