### ISSUE TITLE
Preventing Auto-Scale to Allow Free Navigation in Live Data Plots using a Data Logger 

### ISSUE THREAD

**Issue by annettecort** [ScottPlot/ScottPlot#4449]
Hello everyone! 
I’m using a data logger to plot live data, but I’m trying to disable auto-scaling. I set autoScale to false because I want to move freely around the graph, zoom into specific areas, and zoom out only when I choose. However, it keeps forcing auto-scaling, making it hard to navigate the graph as I’d like.

Ideally, I want it to behave more like other graphing tools where I can freely move around the plot, even with live data updates. Is there a way to accomplish this in ScottPlot, or would another tool be better suited for this?

ScottPlot Version: 5.0.42

**Comment by swharden** [comment]
Hi @annettecort, how are you turning auto scaling off? It should look like this

```cs
var logger = formsPlot1.Plot.Add.DataLogger();
logger.ManageAxisLimits = false;
```

Let me know if that doesn't solve your issue, share the code you have so far, and we can take a closer look!

**Comment by annettecort** [comment]
Hi @swharden, that didn't seem to work. Here are the methods I use to set up my logger and configure my plots.
`    private void SetUpTelemetryPlot()
    {
      this.TelemetryPlot.Plot.Title("Telemetry Graph");
      this.TelemetryPlot.Plot.XLabel("Time");
      this.TelemetryPlot.Plot.YLabel("Values");
      this.TelemetryPlot.Plot.FigureBackground.Color = Color.FromHex("#202020");
      this.TelemetryPlot.Plot.DataBackground.Color = Color.FromHex("#505050");
      this.TelemetryPlot.Plot.Grid.MajorLineColor = Color.FromHex("#FFFFFF");
      this.TelemetryPlot.Plot.Axes.Color(Color.FromHex("#EFEFEF"));
      this.TelemetryPlot.Plot.Axes.Bottom.TickGenerator = new ScottPlot.TickGenerators.DateTimeAutomatic();
      //this.TelemetryPlot.Plot.Axes.AutoScale(false);
    }`

`private void SetupLogger(string telemetryName)
   {
     this.TelemetryPlot.Plot.Clear();
     string color = string.Format("#FF0000");
     this.dataLogger = this.TelemetryPlot.Plot.Add.DataLogger();
     this.dataLogger.LineWidth = 2;
     this.dataLogger.Color = Color.FromHex(color);
     this.dataLogger.LegendText = telemetryName;
     this.dataLogger.ManageAxisLimits = false;
     this.TelemetryPlot.Refresh();
   }`

**Comment by swharden** [comment]
This code works for me... what do you think we are doing differently? I wonder if it's related to calling `SetupLogger()` multiple times?

```cs
```

**Comment by annettecort** [comment]
Hey @swharden, I fixed my code, and the ```logger.ManageAxisLimits = false;`` `actually does work. Thank you for your help!

**Comment by swharden** [comment]
Glad you figured it out! 👍

Good luck with your project! 🚀
