### ISSUE TITLE
using .AddLeftAxis() removes yaxis grid lines, unable to see them with .YAxisStyle.IsVisible = true

### ISSUE THREAD

**Issue by clsferguson** [ScottPlot/ScottPlot#4459]
**Issue:** using .AddLeftAxis() causes .Grid.YAxisStyle.IsVisible to always be false.

**ScottPlot Version:** 5.0.43

**Code Sample:** 

```cs
ScottPlot.Plot myPlot = new();

// Plot some sample data
myPlot.Add.Signal(Generate.Sin());
myPlot.Add.Signal(Generate.Cos());

// Instantiate a custom axis and customize it as desired
ScottPlot.AxisPanels.Experimental.LeftAxisWithSubtitle customAxisY = new()
{
    LabelText = "My Custom Y Axis",
    SubLabelText = "It comes with a subtitle for the axis"
};

// Remove the default Y axis and add the custom one to the plot
myPlot.Axes.Remove(myPlot.Axes.Left);
myPlot.Axes.AddLeftAxis(customAxisY); // grid is not there

myPlot.Grid.YAxisStyle.IsVisible = true; // still doesn't show grid

myPlot.SavePng("bug.png");
```

**Comment by swharden** [comment]
Hi @clsferguson, the missing piece is this:

```cs
myPlot.Grid.YAxis = customAxisY;
```

The grid has to be told which Y axis ticks to use for grid lines. It may seem obvious if there's only 1 Y axis, but it needs to be set manually because when people are adding custom Y axes it's typically adding additional axes, or using grids on the right axis or something.

Hope it helps!
Scott

**Comment by clsferguson** [comment]
> Hi @clsferguson, the missing piece is this:
> 
> ```cs
> myPlot.Grid.YAxis = customAxisY;
> ```
> 
> The grid has to be told which Y axis ticks to use for grid lines. It may seem obvious if there's only 1 Y axis, but it needs to be set manually because when people are adding custom Y axes it's typically adding additional axes, or using grids on the right axis or something.
> 
> Hope it helps! Scott

Yep, that helps!

Thank you.
