### ISSUE TITLE
Curve overlap problem

### ISSUE THREAD

**Issue by Falypio** [ScottPlot/ScottPlot#4493]
**Question:** Hello, the current Signal number is added, the curve will be superimposed, the order, the last added Signal is on the top layer, may I ask how to set the first added Signal as the outermost layer? Like in the picture, I want the red curve to float on top of the yellow curve.

**ScottPlot Version:**ScottPlot 5  WPF
![_17313779378982](https://github.com/user-attachments/assets/5b434559-6458-4fa1-b0ee-434ef3cac464)

**Comment by swharden** [comment]
Hi @Falypio, try this!

https://scottplot.net/cookbook/5.0/PlottableManagement/ChangeOrder/
