### ISSUE TITLE
How to AutoScale vertically to fit the data in the visible horizontal range

### ISSUE THREAD

**Issue by NiRott** [ScottPlot/ScottPlot#4495]
I am using:  

```cs
SP.Plot.Axes.AutoScaleY(SP.Plot.GetPlottables().Where((plottable) => plottable.IsVisible));
```

to display only the plots that are visible at the moment.

When you have a long time series of data and you pan it along, it would be nice if you could apply autoscaling only to the data between `x.left` and `x.right` of the view you currently have and not to all the data.

I haven't found a solution, is there something I'm missing?

**Comment by swharden** [comment]
I'll add an example of this to the demo app!

It's done here so you can glance at the code and get an idea how it works https://github.com/ScottPlot/ScottPlot/issues/4385#issuecomment-2448783106

There's a "continuous auto scale action" you can hook into to add your own logic that runs just before each render

**Comment by swharden** [comment]
That code is specific to OHLCs and candle charts, but the idea will be the same with scatter plots, signal plots, etc.:

https://github.com/ScottPlot/ScottPlot/blob/c0e82541a942d951a538d03247fb3c0d408c9288/src/ScottPlot5/ScottPlot5%20Sandbox/Sandbox.WinFormsFinance/TradingViewForm.cs#L141-L153

**Comment by swharden** [comment]
### Automatically scale vertically to fit data in the horizontal view

![autoscale-vertically](https://github.com/user-attachments/assets/d863f7fa-1414-4771-8858-4e93b58ec2cb)

```cs
public Form1()
{
    InitializeComponent();

    // simulate 1 minute of a 1kHz siganl
    double[] dataValues = Generate.RandomWalk(60_000);
    double sampleRate = 1000;
    double samplePeriod = 1.0 / sampleRate;

    // display the data using a signal plot
    var sig = formsPlot1.Plot.Add.Signal(dataValues, samplePeriod);

    // enable continuous autoscaling with a custom action
    formsPlot1.Plot.Axes.ContinuouslyAutoscale = true;
    formsPlot1.Plot.Axes.ContinuousAutoscaleAction = (RenderPack rp) =>
    {
        // determine the left and right data index in view
        AxisLimits limits = formsPlot1.Plot.Axes.GetLimits();
        int indexLeft = (int)(limits.Left * sampleRate);
        int indexRight = (int)(limits.Right * sampleRate);

        // insure indexes are valid
        indexLeft = NumericConversion.Clamp(indexLeft, 0, dataValues.Length - 1);
        indexRight = NumericConversion.Clamp(indexRight, 0, dataValues.Length - 1);
        if (indexLeft == indexRight)
            return;

        // determine the vertical range of values in the visible range of indexes
        double min = dataValues[indexLeft];
        double max = dataValues[indexLeft];
        for (int i = indexLeft; i <= indexRight; i++)
        {
            min = Math.Min(min, dataValues[i]);
            max = Math.Max(max, dataValues[i]);
        }

        // set vertical axis limits to that range
        rp.Plot.Axes.SetLimitsY(min, max);
    };
}
```

**Comment by swharden** [comment]
https://scottplot.net/demo/5.0/#continuously-autoscale

**Comment by NiRott** [comment]
If you are interested, I have varied your example for several signal plots and a possible Y-offset:  

    // determine the vertical range of values in the visible range of indexes
    double min = double.MaxValue;
    double max = double.MinValue;
    for (int Plots=1; Plots<M.Data.Count; Plots++)
    {
        if (!SignalPlots[Plots-1].IsVisible) continue;
       
            double ThisPlotMin = M.Data[Plots].Slice(indexLeft, indexRight - indexLeft).Min();
            min = Math.Min(min, ThisPlotMin + SignalPlots[Plots - 1].Data.YOffset);
            double ThisPlotMax = M.Data[Plots].Slice(indexLeft, indexRight-indexLeft).Max();
            max = Math.Max(max, ThisPlotMax + SignalPlots[Plots - 1].Data.YOffset);
    }
// set vertical axis limits to that range
double extraMargin=(max - min)*0.05;
SP.Plot.Axes.SetLimitsY(min- extraMargin, max+ extraMargin);

**Comment by cborgentun** [comment]
> M.Data[Plots].Slice(indexLeft, indexRight - indexLeft).Min();

I've been looking for this! To get to the underlying Data arrays from a SignalXY plot! What is M in this context?
