### ISSUE TITLE
Draggable axis line and span bug (duplicate)

### ISSUE THREAD

**Issue by vc815** [ScottPlot/ScottPlot#4497]
Copy the official example, nothing has been modified. After running, when the mouse clicks up, the entire graphic follows the mouse to move together. No matter the left and right mouse buttons, it is invalid. It seems that the control does not release the "up" event of the mouse? There is no problem clicking on the blank, only clicking on Span. After releasing the lift event of the mouse, the image as a whole follows the mouse to move together.
(https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/DraggableAxisSpans.cs)

ScottPlot 5.0.44.0

```cs
using ScottPlot;
using ScottPlot.Plottables;
using ScottPlot.WinForms;
using System;
using System.Linq;
using System.Windows.Forms;

namespace WindowsFormsApp1
{
    public partial class PanleForm : Form
    {
        public PanleForm()
        {
            InitializeComponent();
            // place axis spans on the plot
            formsPlot1.Plot.Add.Signal(Generate.Sin());
            formsPlot1.Plot.Add.Signal(Generate.Cos());

            var vs = formsPlot1.Plot.Add.VerticalSpan(.23, .78);
            vs.IsDraggable = true;
            vs.IsResizable = true;

            var hs = formsPlot1.Plot.Add.HorizontalSpan(23, 42);
            hs.IsDraggable = true;
            hs.IsResizable = true;

            formsPlot1.Refresh();

            // use events for custom mouse interactivity
            formsPlot1.MouseDown += FormsPlot1_MouseDown;
            formsPlot1.MouseUp += FormsPlot1_MouseUp;
            formsPlot1.MouseMove += FormsPlot1_MouseMove;
        }



        public string Title => "Draggable Axis Spans";

        public string Description => "Demonstrates how to create a mouse-interactive " +
            "axis span that can be resized or dragged";

        AxisSpanUnderMouse SpanBeingDragged = null;
        FormsPlot formsPlot1    = new FormsPlot() {  Dock =DockStyle.Fill};
        private void PanleForm_Load(object sender, EventArgs e)
        {


          
            panel1.Controls.Add(formsPlot1);

            // Plot data using the control
            double[] data = ScottPlot.Generate.Sin();
            formsPlot1.Plot.Add.Signal(data);
            formsPlot1.Refresh();
             
        }
        private void FormsPlot1_MouseDown(object sender, MouseEventArgs e)
        {
            var thingUnderMouse = GetSpanUnderMouse(e.X, e.Y);
            if (thingUnderMouse != null)
            {
                Console.WriteLine("MouseDown:" + thingUnderMouse);
                SpanBeingDragged = thingUnderMouse;
                formsPlot1.UserInputProcessor.Disable(); // 在拖拽时禁用平移
            }


        }

        private void FormsPlot1_MouseUp(object sender, MouseEventArgs e)
        {
       
            try
            {
                if (sender == null) return;
                SpanBeingDragged = null;
                ((FormsPlot)sender) .UserInputProcessor.Enable(); // // 启用平移
                ((FormsPlot)sender).Refresh();
                SpanBeingDragged = null;
                Console.WriteLine("MouseUp:"+ SpanBeingDragged);
            }
            catch (Exception ex)
            {

                Console.WriteLine("MouseUp"+ ex.Message);
            }
        
        }

        private void FormsPlot1_MouseMove(object sender, MouseEventArgs e)
        {
            if (SpanBeingDragged is null)
            {
                Console.WriteLine("光标样式");
                // // 没有拖拽任何东西，所以仅根据鼠标下的内容设置光标
                var spanUnderMouse = GetSpanUnderMouse(e.X, e.Y);

                Console.WriteLine("spanUnderMouse"+(spanUnderMouse is null));
                if (spanUnderMouse is null) 
                    Cursor = Cursors.Default;
                else if (spanUnderMouse.IsResizingHorizontally) Cursor = Cursors.SizeWE;
                else if (spanUnderMouse.IsResizingVertically) Cursor = Cursors.SizeNS;
                else if (spanUnderMouse.IsMoving) Cursor = Cursors.SizeAll;
            }
            else
            {
                Console.WriteLine("开始拖拽");
                // // 当前正在拖拽某物，所以更新它
                Coordinates mouseNow = formsPlot1.Plot.GetCoordinates(e.X, e.Y);
                SpanBeingDragged.DragTo(mouseNow);
                formsPlot1.Refresh();
            }
        }

        private AxisSpanUnderMouse GetSpanUnderMouse(float x, float y)
        {
            CoordinateRect rect = formsPlot1.Plot.GetCoordinateRect(x, y, radius: 10);

            foreach (AxisSpan span in formsPlot1.Plot.GetPlottables<AxisSpan>().Reverse())
            {
                AxisSpanUnderMouse spanUnderMouse = span.UnderMouse(rect);
                if (spanUnderMouse != null)
                    return spanUnderMouse;
            }

            return null;
        }
    }
}
```

**Comment by swharden** [comment]
Thanks for reporting this! I think it's the same issue fixed yesterday in https://github.com/ScottPlot/ScottPlot/issues/4481 but a package isn't on NuGet yet 

A temporary fix one-liner is in a comment near the bottom of that page that should do the trick until then

If it doesn't work as expected or misunderstand the issue, let me know and we can open this back up again!

**Comment by vc815** [comment]
Thanks for the reply, I have added plot. UserInputProcessor. ProcessLostFocus () to the mouse click event; drag and drop with the left mouse button, move it, but zoom with the right mouse button, there is a problem again. If you zoom on the span, the whole picture moves in large proportions, and it seems that you still don't lose focus, even if you add plot. UserInputProcessor. ProcessLostFocus () to the mouse up event; Thank you.

**Comment by vc815** [comment]
> Thanks for the reply, I have added plot. UserInputProcessor. ProcessLostFocus () to the mouse click event; drag and drop with the left mouse button, move it, but zoom with the right mouse button, there is a problem again. If you zoom on the span, the whole picture moves in large proportions, and it seems that you still don't lose focus, even if you add plot. UserInputProcessor. ProcessLostFocus () to the mouse up event; Thank you.

**Comment by StendProg** [comment]
Hi @vc815, @swharden

I checked how it works with the nuget package and with the current version of the code.
Yes, the problem is present in 5.0.44 and has been solved in the main branch. But the solution is more complex than one line. in particular #4490 the logic of `ProcessLostFocus` has been seriously changed.

@vc815  I can advise you to wait for the new version, or build your own package if time is running out.

**Comment by swharden** [comment]
> the problem is present in 5.0.44 and has been solved in the main branch

> build your own package if time is running out

I plan to publish a new package tonight 👍

**Comment by swharden** [comment]
I just started the release pipeline and version 5.0.45 be on NuGet in about 30 minutes. If it doesn't work as expected, let me know and we can open this back up and take a closer look together! 🚀

**Comment by vc815** [comment]
ok  thanks
