### ISSUE TITLE
New plot type: wiggle plot

### ISSUE THREAD

**Issue by xichaoqiang** [ScottPlot/ScottPlot#450]
**What can we do to make ScottPlot better?**
A clear and concise description of what we can improve would be helpful.

Can ScottPlot plot this kind figure?Only positive part is filled? Or two parts filled with different color?

![image](https://user-images.githubusercontent.com/30900789/83858351-f18c1a80-a74e-11ea-9501-86b1eb894390.png)

Check the ScottPlot Roadmap to see if your feature is already planned for an upcoming release:
https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md

**Comment by Benny121221** [comment]
These three examples should help you:

- https://swharden.com/scottplot/cookbooks/4.0.35/#plottypes-fill-filled-curve
- https://swharden.com/scottplot/cookbooks/4.0.35/#plottypes-fill-fill-between-curves
- https://swharden.com/scottplot/cookbooks/4.0.35/#plottypes-fill-fill-above-and-below

**Comment by swharden** [comment]
@xichaoqiang, @Benny121221's excellent suggestion is accurate: [`PlotFill()` can be used to fill between two curves](https://swharden.com/scottplot/cookbooks/4.0.35/#plottypes-fill-fill-between-curves). You can set the fill color to solid black using arguments.

I'm curious, what type of data is this? I've never seen a plot like your example before

**Comment by xichaoqiang** [comment]
> solid black

Thanks for your reply. My data is seismic data. And I set the base line to a transparent line?

And can I  plot these filled areas in a vertical direction?

![image](https://user-images.githubusercontent.com/30900789/116807652-ec09a100-ab66-11eb-809f-2d2f4a236017.png)

**Comment by xichaoqiang** [comment]
In other word, I only need the curve line and above and below filled area, the line of above and below filled area is useless for me. How can I set them to empty or transparent.

![图片](https://user-images.githubusercontent.com/30900789/116835865-e3f94200-abf6-11eb-8143-42bdaccaf5eb.png)

![图片](https://user-images.githubusercontent.com/30900789/116835877-f3788b00-abf6-11eb-97aa-5fb3be3736af.png)

**Comment by swharden** [comment]
Hi @xichaoqiang, there's not an easy way to do this presently.

I'm going to re-open this issue to explore if this can be achieved without too much effort. It _seems_ like creating a `Drawing.Tools.PolyLeftAndRight` wouldn't be too much more complex than what's there now 🤔 

https://github.com/ScottPlot/ScottPlot/blob/6dd7005e5f736e2e0a4abb3d0214f22735ac1974/src/ScottPlot/Plot/Plot.Add.cs#L301-L315

**Comment by xichaoqiang** [comment]
Thanks for your reply.This kind of figure is very popular in our seismology community. We call it the wiggle plot.

**Comment by swharden** [comment]
Hi @xichaoqiang, this is unlikely to move quickly. I added it to the triage list in #1028 and will close this issue for now 👍

**Comment by xichaoqiang** [comment]
Hi,@swharden ,I have write the PlotFillRightLeft function. And try with the demo data.
The result seems well. So, can you add this function into PR?


     ```
   [Obsolete("Use AddFill() and customize the object it returns")]
        public (Polygon, Polygon) PlotFillRightLeft(
            double[] xs,
            double[] ys,
            string labelRight = null,
            string labelLeft = null,
            double lineWidth = 1,
            Color? lineColor = null,
            bool fill = true,
            Color? fillColorRight = null,
            Color? fillColorLeft = null,
            double fillAlpha = 1,
            double baseline = 0
            )
        {
            if (xs.Length != ys.Length)
                throw new ArgumentException("xs and ys must all have the same length");

            double[] xs2 = Tools.Pad(xs, padWithLeft: baseline, padWithRight: baseline);
            double[] ys2 = Tools.Pad(ys, cloneEdges: true);

            double[] xs2below = new double[xs2.Length];
            double[] xs2above = new double[xs2.Length];

           

            for (int i = 0; i < xs2.Length; i++)
            {
                if (xs2[i] < baseline)
                {
                    xs2below[i] = xs2[i];
                    xs2above[i] = baseline;
                }
                else
                {
                    xs2above[i] = xs2[i];
                    xs2below[i] = baseline;
                }
            }


            if (fillColorRight is null)
                fillColorRight = Color.Green;
            if (fillColorLeft is null)
                fillColorLeft = Color.Red;
            if (lineColor is null)
                lineColor = Color.Black;

            var polyRight = PlotPolygon(xs2above, ys2, labelRight, lineWidth, lineColor, fill, fillColorRight, fillAlpha);
            var polyLeft = PlotPolygon(xs2below, ys2, labelLeft, lineWidth, lineColor, fill, fillColorLeft, fillAlpha);

            return (polyLeft, polyRight);
        }
```

![image](https://user-images.githubusercontent.com/30900789/154499607-3c63634c-4066-488f-a142-ee5b80b62328.png)

![image](https://user-images.githubusercontent.com/30900789/154499672-d077b501-9986-4b11-a3f4-1909cd0cee82.png)

**Comment by swharden** [comment]
Hi @xichaoqiang, 

Thank you for sharing your progress!  This looks great.

I'll re-open this issue and with the goal of adding this to the `Plot` module, or at least create a cookbook example demonstrating how to achieve this effect.

**Comment by swharden** [comment]
PS: when this is implemented I recommend using colorblind-friendly colors for cookbook examples, such as green and magenta

https://www.nature.com/articles/d41586-021-02696-z

**Comment by xichaoqiang** [comment]
@swharden I try use the plt.AxisAuto(1) with plt.PlotFillRightLeft(), but get wrong result.

```
            var plt = WpfPlot1.Plot;
            plt.Clear();

            Random rand = new Random(0);
            var ys = ScottPlot.DataGen.RandomWalk(rand, 1000, offset: -10);
            var xs = ScottPlot.DataGen.Consecutive(ys.Length, spacing: 0.025);
            //for (int i = 0; i < xs.Length; i++)
            //{
            //    xs[i] = xs[i] * -1;
            //}
            plt.PlotFillRightLeft(ys, xs, fillAlpha: .5, labelRight: "positive", labelLeft: "negative");
            //plt.YAxis.TickLabelNotation(invertSign: true);

            plt.Legend();
            plt.AxisAuto(0);
            WpfPlot1.Refresh();
```

![ScottPlot1](https://user-images.githubusercontent.com/30900789/154599895-39db02ce-6bb1-4dd0-862c-1a755eea0372.png)

```
            var plt = WpfPlot1.Plot;
            plt.Clear();

            Random rand = new Random(0);
            var ys = ScottPlot.DataGen.RandomWalk(rand, 1000, offset: -10);
            var xs = ScottPlot.DataGen.Consecutive(ys.Length, spacing: 0.025);
            //for (int i = 0; i < xs.Length; i++)
            //{
            //    xs[i] = xs[i] * -1;
            //}
            plt.PlotFillRightLeft(ys, xs, fillAlpha: .5, labelRight: "positive", labelLeft: "negative");
            //plt.YAxis.TickLabelNotation(invertSign: true);

            plt.Legend();
            plt.AxisAuto(1);
            WpfPlot1.Refresh();
```

![image](https://user-images.githubusercontent.com/30900789/154599998-c94f1146-a14f-450a-b5a5-8ffc2bb2b8fc.png)

```
            var plt = WpfPlot1.Plot;
            plt.Clear();

            Random rand = new Random(0);
            var ys = ScottPlot.DataGen.RandomWalk(rand, 1000, offset: -10);
            var xs = ScottPlot.DataGen.Consecutive(ys.Length, spacing: 0.025);
            for (int i = 0; i < xs.Length; i++)
            {
                xs[i] = xs[i] * -1;
            }
            plt.PlotFillRightLeft(ys, xs, fillAlpha: .5, labelRight: "positive", labelLeft: "negative");
            plt.YAxis.TickLabelNotation(invertSign: true);

            plt.Legend();
            plt.AxisAuto(0);
            WpfPlot1.Refresh();
```

![image](https://user-images.githubusercontent.com/30900789/154600112-892cee58-8f96-4931-8f50-aa93bafdbccb.png)

```
            var plt = WpfPlot1.Plot;
            plt.Clear();

            Random rand = new Random(0);
            var ys = ScottPlot.DataGen.RandomWalk(rand, 1000, offset: -10);
            var xs = ScottPlot.DataGen.Consecutive(ys.Length, spacing: 0.025);
            for (int i = 0; i < xs.Length; i++)
            {
                xs[i] = xs[i] * -1;
            }
            plt.PlotFillRightLeft(ys, xs, fillAlpha: .5, labelRight: "positive", labelLeft: "negative");
            plt.YAxis.TickLabelNotation(invertSign: true);

            plt.Legend();
            plt.AxisAuto(1);
            WpfPlot1.Refresh();
```
![image](https://user-images.githubusercontent.com/30900789/154600289-5761e4ce-dc50-462a-81f1-c78bc4d9437b.png)

**Comment by swharden** [comment]
Thank you for reporting this! The bug here is that `AxisAuto()` fails if its argument is `1.0`. I'll address this in #1682

```cs
private void numericUpDown1_ValueChanged(object sender, EventArgs e)
{
    formsPlot1.Plot.AxisAuto(horizontalMargin: (double)numericUpDown1.Value);
    formsPlot1.Refresh();
}
```

![zoom-bug](https://user-images.githubusercontent.com/4165489/154611627-5eadd9f2-74f4-4270-b9c1-be1489c66b99.gif)
