### ISSUE TITLE
.NET Interactive Notebook Quickstart does not plot a graph

### ISSUE THREAD

**Issue by Neiwa** [ScottPlot/ScottPlot#4501]
**Issue:** 
Using the [.NET Interactive Notebook Quickstart](https://scottplot.net/quickstart/notebook/#net-interactive-notebook-quickstart) I do not get to see the plot, instead I get a dump of the plt object as output.

**ScottPlot Version:** 5.0.44

**Code Sample:** (as in the above link)

```cs
// Install the ScottPlot NuGet package
#r "nuget:ScottPlot, 5.0.*"

// Setup a custom formatter to display plots as images
using Microsoft.DotNet.Interactive.Formatting;
Formatter.Register(typeof(ScottPlot.Plot), (p, w) => 
    w.Write(((ScottPlot.Plot)p).GetImageHtml(400, 300)), HtmlFormatter.MimeType);

// create sample data
double[] dataX = new double[] { 1, 2, 3, 4, 5 };
double[] dataY = new double[] { 1, 4, 9, 16, 25 };

// plot the data
ScottPlot.Plot plt = new();
plt.Add.Scatter(dataX, dataY);

// display the plot
plt
```

**Comment by swharden** [comment]
Thanks for reporting this @Neiwa!

The important bit of missing info is the error message:
```
Error: (3,13): error CS0619: 'Plot.GetImageHtml(int, int)' is obsolete: 'This method is deprecated. Use GetPngHtml() or GetSvgHtml()'
```

I replaced `GetImageHtml` with `GetPngHtml` and it works as expected

![image](https://github.com/user-attachments/assets/814df941-0ac6-4045-a49c-fcf2343c908c)

I'll update the quickstart page now to reflect this. Thanks again for pointing it out!
