### ISSUE TITLE
Axis: add support for image labels

### ISSUE THREAD

**Issue by Liwr9537** [ScottPlot/ScottPlot#4503]
Recently, I am using scottplot for scientific drawing. When I need to set the unit for the label and legend, I have to use superscript and subscript. I know that some special unicode can be used. But if the content is more complicated, I have no idea what to do. Besides, I need to add some Latex formula into the plot. For example, I want to add -x^{-rho} into the plot.
So, I want to know if there are some ways for me to do so? Will scottplot add this kind of function in the future?

ScottPlot Version: 5.0.43.0

**Comment by bforl** [comment]
I don't have a direct answer for you I'm afraid.

But as work around, could you render the latex to a bitmap and display that? (assuming its not constantly changing)

**Comment by Liwr9537** [comment]
Do you mean that I can turn the latex into the graph and use this graph as the label text or legend? It seams OK in scottplot4, but I do not find this kind of method in scottplot5.

**Comment by swharden** [comment]
I'm merging #4517 now and this feature will be available in the next release!

If you use a third party package to render rich text as a bitmap, you can consume it with ScottPlot and display it anywhere a label is typically displayed

```cs
myPlot.Add.Signal(Generate.Sin(51));
myPlot.Add.Signal(Generate.Cos(51));

// This array holds the bytes of a bitmap. Here it's generated,
// but it could be a byte array read from a bitmap file on disk.
byte[] bytes1 = SampleImages.NoisyText("Horiz", 150, 50).GetImageBytes();
byte[] bytes2 = SampleImages.NoisyText("Vert", 150, 50).GetImageBytes();

// Create a ScottPlot.Image from the bitmap bytes
ScottPlot.Image img1 = new(bytes1);
ScottPlot.Image img2 = new(bytes2);

// Display the image for the bottom axis label
myPlot.Axes.Bottom.Label.Image = img1;
myPlot.Axes.Left.Label.Image = img2;
```

![image](https://github.com/user-attachments/assets/107a3805-1c3e-4ac2-93dc-3548c435c106)
