### ISSUE TITLE
Controls: how can double-click benchmark be disabled?

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4506]
@kareem469 reports in https://github.com/ScottPlot/ScottPlot/discussions/3917#discussioncomment-11237690 that the following does not suppress the double click benchmark:

```cs
formsPlot1.UserInputProcessor.DoubleLeftClickBenchmark(false);
```

This issue will track reproducing this behavior and fixing it.

**Comment by swharden** [comment]
Hi @kareem469, I tested this and confirmed it works as expected

```cs
namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();
        formsPlot1.UserInputProcessor.DoubleLeftClickBenchmark(false);
    }
}
```

Make sure you're using `formsPlot1.UserInputProcessor` and not the obsolete `formsPlot1.Interaction`

**Comment by kareem469** [comment]
Yup. Its working 
thanks 

But for interaction which one to use?

My old code for Ver 5.0.33

 ScottPlot.Control.InputBindings customInputBindings = new ScottPlot.Control.InputBindings
            {
                DragPanButton = ScottPlot.Control.MouseButton.Left,
                DragZoomRectangleButton = ScottPlot.Control.MouseButton.Right,
                DragZoomButton = ScottPlot.Control.MouseButton.Middle,
                ZoomInWheelDirection = ScottPlot.Control.MouseWheelDirection.Up,
                ZoomOutWheelDirection = ScottPlot.Control.MouseWheelDirection.Down,
                // ClickAutoAxisButton = ScottPlot.Control.MouseButton.Right,
                ClickContextMenuButton = ScottPlot.Control.MouseButton.Right,
            };

            ScottPlot.Control.Interaction interaction = new ScottPlot.Control.Interaction(formsPlot1)
            {
                Inputs = customInputBindings,
            };

            formsPlot1.Interaction = interaction;

**Comment by swharden** [comment]
> Yup. Its working - thanks

Yay! 🎉 I'm glad we reached a solution

> But for interaction which one to use?

`UserInputProcessor` is recommended, and `Interaction` will be removed in a future release. The new system is more customizable and has better support for gestures like swipes and multi-touch inputs.

See the https://scottplot.net/demo/5.0/#custom-mouse-actions demo source code to learn how to customize mouse actions using the new `UserInputProcessor`

**Comment by kareem469** [comment]
If I want this formsPlot1.UserInputProcessor.DoubleLeftClickBenchmark(false); functionality in version 5.0.33?

**Comment by kareem469** [comment]
> > in version 5.0.33?
> 
> Why are you using a version that's over 6 months old, when new versions are published almost every weekend?
> 
> https://www.nuget.org/packages/ScottPlot#versions-body-tab

Because i want to change major code updates in my code if i upgrade from 5.0.33 to latest one

**Comment by swharden** [comment]
> Because i want to change major code updates in my code if i upgrade from 5.0.33 to latest one

haha, fair point! I bet https://github.com/ScottPlot/ScottPlot/issues/4506#issuecomment-2485902401 will do the trick, even for older versions. 

Good luck with your project! 🚀

**Comment by kareem469** [comment]
> ```cs
> LabelStyle
> ```

I am getting the following error

Error CS1061 -	'IPlottable' does not contain a definition for 'LabelStyle' and no accessible extension method 'LabelStyle' accepting a first argument of type 'IPlottable' could be found (are you missing a using directive or an assembly reference?)

**Comment by swharden** [comment]
> Error CS1061 - 'IPlottable' does not contain a definition for 'LabelStyle'

Hi @kareem469, I don't have the API memorized for those old versions, but I'm fairly confident that if you look through all the properties of `formsPlot1.Plot.Benchmark` you will find some you can customize to make the benchmark invisible.

**Comment by kareem469** [comment]
Hi @swharden,

I tried hard to find formsPlot1.Plot.Benchmark disable functionality. But unfortunately, I couldn't find it. 😭

**Comment by swharden** [comment]
> Could you please help me to get the formsPlot1.UserInputProcessor.DoubleLeftClickBenchmark(false); in Ver 5.0.33

```cs
formsPlot1.Plot.RenderManager.RenderStarting += (s, e) => formsPlot1.Plot.Benchmark.IsVisible = false;
```
