### ISSUE TITLE
DataStreamer: Improve support for unevenly-spaced data

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#4507]
How is one supposed to initialize a DataLogger with a CircularBuffer after this change? Is the CircularBuffer now obsolete?

_Originally posted by @dlampa in https://github.com/ScottPlot/ScottPlot/issues/4460#issuecomment-2473952205_

**Comment by swharden** [comment]
Hi @dlampa, thank you for this question! I do not think it was our intent to remove support for circular buffers. 

The intent of #4460 was to change `IList` to `List` to allow `RemoveRange()` to be used in data loggers (a plot type designed to accommodate growing datasets). 

Circular buffers make sense for data streamers (a similar plot type designed to hold a fixed number of data points). It seems there were no tests in place that evaluated circular buffers' use in data loggers, so when the change was made and everything compiled and tests passed it didn't raise any alarm bells that functionality was lost.

I see that #4460 removed the "DataLogger2" demo window, which I thought was obsolete because `DataLogger2` is now just `DataLogger`, but I may have been mistaken.

---

Can you remind us why a circular buffer may be recommended for a data logger, and not a data streamer? If this feature is still desired, I'm happy to figure out a way to make sure it gets added back in.

Thanks for your feedback!
Scott

**Comment by dlampa** [comment]
Thanks for responding so quickly @swharden ! I was under the impression that the DataStreamer required evenly spaced data, which is not the case for the DataLogger? See https://github.com/ScottPlot/ScottPlot/issues/2377#issuecomment-1579712821 for ref.
This becomes an issue when wanting to plot a fixed number of points (say last 30 min of data) for which one cannot guarantee even spacing on the time axis, as would often be the case when reading raw values from industrial systems.

**Comment by swharden** [comment]
Thanks for clarifying @dlampa!

For some personal context, I closed 250 issues over the last couple weeks https://scottplotstatsstorage.z20.web.core.windows.net/ and this topic was one of them, so it's very possible that I overlooked some important details in my push to catch up with open issues and pull requests. Now that things have settled back down, I'm looking forward to thinking about this topic in more detail! I really appreciate your feedback along the way, because I can tell this is a topic you've thought a lot about.

I'm thinking out loud on this one, but would there be benefit for a third type of data logger (or data logger source) designed for unevenly spaced time series data? It could keep a circular buffer of `Coordinates` (rather than `double`) so it tracks both the times and values. I wonder if this would make it easier to solve this problem, since the situation you describe doesn't perfectly fit into the existing data streamer or data logger?

> as would often be the case when reading raw values from industrial systems

I'll double-down my support for resolving this in a good way! This is exactly the type of data visualization I'd like to support with ScottPlot, so I'm really interested in finding a solution that feels natural and works as expected.

Thanks for your feedback!

**Comment by dlampa** [comment]
I've definitely noticed the big cleanup! :) Great work!

What you're proposing sounds great - I feel most of the building blocks are already there for something like this. It would be awesome if one could specify a TimeSpan and internally manage the circular buffer of `Coordinates` based on that...

Previously, I've been using a `CircularBuffer` with the DataLogger to approximate this behaviour by specifying a fixed number of points which roughly correspond to a desired time period - and prior to `CircularBuffer` being introduced, I used a `List<double>` for time and for data, and then managed that manually.

**Comment by swharden** [comment]
I created a minimal example to demonstrate the issue. It simulates real-time sensor data but there are random gaps between new data points. The plot _should_ look like a clean sine wave, but because Y values are forced to be displayed using evenly-spaced X positions it doesn't.

```cs
public partial class Form1 : Form
{
    System.Windows.Forms.Timer Timer = new() { Enabled = true, Interval = 10 };

    public Form1()
    {
        InitializeComponent();

        formsPlot1.Plot.Axes.SetLimitsY(-2, 2);

        var streamer = formsPlot1.Plot.Add.DataStreamer(50, 1);
        streamer.MarkerSize = 5;

        Timer.Tick += (s, e) =>
        {
            // skip points randomly so that data is unevenly spaced
            if (Random.Shared.NextDouble() > 0.2)
                return;

            double x = DateTime.Now.Ticks / 1e6;
            streamer.Add(Math.Sin(x));
            formsPlot1.Refresh();
        };
    }
}
```

![dlbad](https://github.com/user-attachments/assets/70b6863a-f56f-4bb1-9394-97e644d64d52)

**Comment by swharden** [comment]
Hi @dlampa, I created a MVP version of a DataStreamerXY in #4518 and am merging it in now. Want to take a look and let me know what you think? 

It uses your `CircularBuffer<T>` but I know I'm not accessing its values efficiently in `Render()` because I threw an `OrderBy()` in there to get this off the ground, but a proper implementation would join segments of the original data using `_start` and `_end` I believe.

Feel free to open a PR if you have suggestions for improvements! I kept this simple and haven't added different data sources or views, but I think this is a pretty strong start and I welcome any feedback you may have from here 🚀 

DataStreamer | DataStreamerXY
---|---
![dlbad](https://github.com/user-attachments/assets/1d8b38ca-0fea-4c7a-97c6-2dc7b7de1585)|![dlbetter](https://github.com/user-attachments/assets/42cb77e4-a17c-4fb5-8289-fb26bed76e17)


```cs
var streamer = formsPlot1.Plot.Add.DataStreamerXY(50);

Timer.Tick += (s, e) =>
{
    // skip points randomly so that data is unevenly spaced
    if (Random.Shared.NextDouble() > 0.2)
        return;

    DateTime x = DateTime.Now;
    double y = Math.Sin(x.Ticks / 1e6);
    streamer.Add(x, y);
    formsPlot1.Refresh();
};
```

**Comment by dlampa** [comment]
Hi @swharden , apologies for not responding sooner! This is great for those requiring a DataStreamer and have unevenly spread data. Thank you so much for the effort!

However, in my case I don't think DataStreamer is the way to go (and please correct me if I'm wrong), because I have to allow the user to scroll around and see some of the measurement history (1h - 72h depending on the context). By default the user would be presented with a view of the last 15 min or so (also varies with the context), with autoupdating axes. While they're looking at the history, plot is still being updated in the 'background', without automatic axis updates - so the latest data is always available, even if not visible.

A simplified example:
![Animation](https://github.com/user-attachments/assets/043b961a-ed20-44bc-82d8-6e06e16a938e)


Where the `CircularBuffer` comes in handy with plots like this is that I don't have to use suboptimal methods of managing the data structure(s) for the plot (e.g. `List.RemoveAt(0)` and so on).

On another note, ordering of the dataset could be achieved with `CircularBuffer.ToArray()` since the data is added to the buffer in chronological order, and `ToArray()` produces the ordered array taking into account the `_start` and `_end` positions via `InternalIndex()`.
