### ISSUE TITLE
How to force a render when the plot is not in focus?

### ISSUE THREAD

**Issue by clsferguson** [ScottPlot/ScottPlot#4508]
**Question:** I have a form that contains a plot. The form watches for changes to my object containing the data. When the data changes, the chart won't update until I move the mouse over it. No matter where and how I put .refresh(). Well, kind of. When the data loads, it jumps but stops. But it doesn't jump to the way it should look.

**ScottPlot Version:** "ScottPlot.WinForms" Version="5.0.43"
![Screen Recording 2024-11-13 163147](https://github.com/user-attachments/assets/95b2e826-5f53-418f-b112-543d4e362fa1)

**Comment by swharden** [comment]
> No matter where and how I put .refresh()

> Well, kind of. When the data loads, it jumps but stops

Can you share the code for the function where you're calling `Refresh()`? Is any code running after `Refresh()` is called?

Without sample code to help me reproduce this issue, it's pretty hard to offer suggestions 😅

**Comment by swharden** [comment]
Thinking outside the box, maybe you could add something like `bool RenderNeeded` in your child form with a `Timer` that routinely checks its value and calls `Refresh()` if it's `true` - maybe that would work?

**Comment by clsferguson** [comment]
here it is.. I'm not super great at githubbing/coding. Just learning! one thing I notice with the benchmark up, the frames don't seem to change at all unless the mouse is over, its like rendering pauses.

`using FracGrapher.Models;
using FracGrapher.Models.Entities.Recorders;
using FracGrapher.Models.Extensions;
using ScottPlot;
using ScottPlot.AxisRules;
using ScottPlot.Plottables;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Forms;

namespace FracGrapher.UI
{
    public partial class FormChart : Form
    {
        private readonly List<SignalXY> _signals = [];
        private Crosshair _crosshair;
        private readonly List<CurveProperties> _curvePropertiesList = [];
        private readonly List<string> _baseLegendTexts = [];

        public FormChart()
        {
            InitializeComponent();

            // Subscribe to change events
            GlobalFields.DataRecordersChanged += GlobalFields_DataRecordersChanged;
            GlobalFields.ProjectInfoChanged += GlobalFields_ProjectInfoChanged;

            // Initialize ScottPlot and set up the chart.
            var plt = formsPlot1.Plot;

            plt.RenderManager.EnableRendering = true;

            plt.Title($"{GlobalFields.ProjectInfo.CompanyName} - {GlobalFields.ProjectInfo.UWI} - {GlobalFields.ProjectInfo.WellName}");

            ScottPlot.AxisPanels.LeftAxis customAxisY = new()
            {
                LabelText = "Pressure (MPa)\nTemperature (°C)",
                PaddingBetweenTickAndAxisLabels = new(20),
            };
            plt.Axes.Remove(plt.Axes.Left);
            plt.Axes.AddLeftAxis(customAxisY);
            plt.Grid.YAxis = customAxisY;

            plt.XLabel("Time");
            plt.Axes.DateTimeTicksBottom();

            plt.Benchmark.IsVisible = true;

            plt.Legend.IsVisible = true;
            plt.Legend.Alignment = Alignment.UpperCenter;
            plt.Legend.Orientation = ScottPlot.Orientation.Horizontal;

            // Initial chart rendering
            UpdateChart();

            formsPlot1.MouseMove += (s, e) =>
            {
                if (_crosshair == null || _signals == null || _signals.Count == 0) return;

                // Determine where the mouse is and get the nearest point
                Pixel mousePixel = new(e.Location.X, e.Location.Y);
                Coordinates mouseLocation = plt.GetCoordinates(mousePixel);

                bool anyPointIsReal = false;
                for (int i = 0; i < _signals.Count; i++)
                {
                    DataPoint nearestPoint = _signals[i].Data.GetNearestX(mouseLocation, plt.LastRender, 500);

                    if (nearestPoint.IsReal)
                    {
                        anyPointIsReal = true;
                        string unit = _curvePropertiesList[i].CurveUnit.GetDisplayString();
                        string baseLegendText = _baseLegendTexts[i];
                        _signals[i].LegendText = $"{baseLegendText}: {nearestPoint.Y:0.0}{unit}";
                    }
                    else
                    {
                        _signals[i].LegendText = _baseLegendTexts[i];
                    }
                }

                // Place the crosshair over the highlighted point
                if (anyPointIsReal)
                {
                    _crosshair.IsVisible = true;
                    _crosshair.Position = mouseLocation;

                    formsPlot1.Refresh();
                }
                if (!anyPointIsReal && _crosshair.IsVisible)
                {
                    _crosshair.IsVisible = false;

                    formsPlot1.Refresh();
                }
            };

        }

        private void UpdateChart()
        {
            // Ensure UI updates are on the UI thread
            if (this.InvokeRequired)
            {
                this.Invoke((MethodInvoker)delegate
                {
                    UpdateChart();
                });
                return;
            }

            // Clear the plot and re-render with updated data
            var plt = formsPlot1.Plot;
            plt.Clear();

            // Re-initialize chart elements as needed (title, axes, etc.)
            plt.Title($"{GlobalFields.ProjectInfo.CompanyName} - {GlobalFields.ProjectInfo.UWI} - {GlobalFields.ProjectInfo.WellName}");

            // Re-run the data collection and plotting code
            RenderChartData(plt);

            // Refresh the plot to display changes
            formsPlot1.Refresh();
        }

        private void RenderChartData(Plot plt)
        {
            // Ensure that DataRecorders is populated
            var recorders = GlobalFields.DataRecorders;

            if (recorders == null || recorders.Count == 0)
            {
                return;
            }

            // Prepare lists to collect all x and y values
            var xDateTime = new List<double>();
            var allYValues = new List<double>();

            // Initialize the crosshair
            _crosshair = plt.Add.Crosshair(0, 0);
            _crosshair.IsVisible = false;
            _crosshair.MarkerShape = MarkerShape.None;
            _crosshair.HorizontalLine.IsVisible = false;

            // Clear existing signals and legend texts
            _signals.Clear();
            _curvePropertiesList.Clear();
            _baseLegendTexts.Clear();

            // For each recorder
            foreach (var recorder in recorders)
            {
                // For each curve property (i.e., curve) in the recorder
                for (int curveIndex = 0; curveIndex < recorder.CurvePropertyList.Count; curveIndex++)
                {
                    var curveProperty = recorder.CurvePropertyList[curveIndex];
                    var xs = new List<double>();
                    var ys = new List<double>();

                    // For each data point set in the recorder
                    foreach (var dataPointSet in recorder.DataPointSets)
                    {
                        if (dataPointSet.DataPointList.Count > curveIndex)
                        {
                            DateTime dateTime = dataPointSet.DateTime;
                            double xValue = dateTime.ToOADate();
                            double yValue = dataPointSet.DataPointList[curveIndex];

                            xs.Add(xValue);
                            ys.Add(yValue);

                            xDateTime.Add(xValue);
                            allYValues.Add(yValue);
                        }
                    }

                    // Plot the data if there are any points
                    if (xs.Count > 0)
                    {
                        var sig = plt.Add.SignalXY(xs.ToArray(), ys.ToArray(), Color.FromColor(curveProperty.CurveColor));

                        string legendText = $"{recorder.RecorderLocationDescription}";
                        sig.LegendText = legendText;

                        _signals.Add(sig);
                        _curvePropertiesList.Add(curveProperty);
                        _baseLegendTexts.Add(legendText);
                    }
                }

                formsPlot1.Refresh();
            }

            // Determine Y-axis maximum
            if (allYValues.Count > 0 && xDateTime.Count > 0)
            {
                double maxYValue = allYValues.Max();

                // Calculate Y-axis maximum: add 10 and round up to the nearest 10
                double yMax = Math.Ceiling((maxYValue + 10) / 10) * 10;

                double xMin = xDateTime.Min();
                double xMax = xDateTime.Max();

                MaximumBoundary rule = new(
                    xAxis: plt.Axes.Bottom,
                    yAxis: plt.Axes.Left,
                    limits: new AxisLimits(xMin, xMax, 0, yMax));

                plt.Axes.Rules.Add(rule);
            }
        }

        private void GlobalFields_DataRecordersChanged(object? sender, EventArgs e)
        {
            UpdateChart();
        }

        private void GlobalFields_ProjectInfoChanged(object? sender, EventArgs e)
        {
            UpdateChart();
        }
    }
}`

**Comment by clsferguson** [comment]
> Thinking outside the box, maybe you could add something like `bool RenderNeeded` in your child form with a `Timer` that routinely checks its value and calls `Refresh()` if it's `true` - maybe that would work?

I will try adding a timer and refresh() just as a trial, see if it ever works

**Comment by swharden** [comment]
>  I'm not super great at githubbing/coding. Just learning!

Wow, it looks like you're doing a fantastic job! You're troubleshooting some pretty complex problems deep in the weeds, and successfully too! Keep up the awesome work! 🚀 🚀 🚀 

> having a timer call refresh() causes constant updating, and works. I'm going to try and dial it in. Thank you.

Yay! I'm happy you were able to reach a solution. I'll update the demo app to demonstrate this so it's easier for others to learn how to solve this problem in the future. 

Thanks again for your question, and for sharing the solution! Best of luck on your projects too ✨ 

Scott

**Comment by swharden** [comment]
Following-up, this example code shows how to refresh a plot in a child window even though the main window is focused. To be honest this works as expected 😅 so @clsferguson I question whether your specific issue is related to some of the other code in your app, which is a lot more complicated than this sample code. Either way, luckily, this works as expected, so I don't think additional documentation is required 😎 

```cs
using ScottPlot;
using ScottPlot.WinForms;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();

        // create an interactive plot to display in another window
        FormsPlot formsPlot = new() { Dock = DockStyle.Fill };
        Form form = new() { Text = "Child Form" };
        form.Controls.Add(formsPlot);
        form.Show();

        // change the data and redraw it (even while this window is focused)
        btnUpdate.Click += (s, e) =>
        {
            formsPlot.Plot.Add.Signal(Generate.RandomWalk(100));
            formsPlot.Plot.Axes.AutoScale();
            formsPlot.Refresh();
        };
    }
}
```

![update](https://github.com/user-attachments/assets/3f805bdd-06c9-4059-abe4-0aeed2ffa326)

**Comment by clsferguson** [comment]
@swharden Breakthrough! So, in my app, I am using the FormsPlotGL. Apparently important information I left out. I have been able to recreate the issue in the demo app. Also, by changing my app to a standard FormsPlot, the issue goes away.

![Screen Recording 2024-11-15 094510](https://github.com/user-attachments/assets/47c6a9d1-a1d5-4f34-b89e-193c98f4678d)

**Comment by clsferguson** [comment]
Yep, moving to a FormsPlot, I removed all the extra Refresh() calls, I removed the timer stuff. There is only the one call now when data is loaded at the end of UpdateChart(). The chart loads as expected and doesn't have the strange issues.
