### ISSUE TITLE
New way to zoom in and out

### ISSUE THREAD

**Issue by LXX1029** [ScottPlot/ScottPlot#4509]
**Suggestion:** (Describe your idea here)
This is a great set of controls,and the author must have put a lot of time and effor into developing it. I have a requirement ,but I have implemented it in the source code and successfully applied it to the project,but I am not sure if this new way of scaling will be accepted by others,like this operation.

![GIF 2024-11-14 9-58-42](https://github.com/user-attachments/assets/080d509a-381e-45f6-affd-a4c08d55b91c)
Draw straight line in the horizontal or vertical direction of the chart,if the height exceeds a certain value or the with exceeds a certain value,draw a rectangle,and then enlarge according to the size of the rectangle,otherwise enlarge according to the size of the line,and generate dashed lines an both ends for range identification.

I was going to commit the code ,but I wasn't sure how it would affect the source code,so I never did. I'll append the code after I changed ZoomRectangle Class.We can consider whether to add this operation.Looking forward to your replay.

**ZoomRectangle.cs**

`using ScottPlot.Drawing;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.InteropServices;
namespace ScottPlot.Renderable
{
    public class ZoomRectangle : IRenderable
    {
        private float X;
        private float Y;
        private float Width;
        private float Height;
        public Color FillColor { get; set; } = Color.FromArgb(50, Color.Red);
        public Color BorderColor { get; set; } = Color.FromArgb(100, Color.Red);
        public Color DotBorderColor { get; set; } = Color.FromArgb(80, Color.Red);
        public bool IsVisible { get; set; } = true;
        public void Clear() => IsVisible = false;

        public void Set(float x, float y, float width, float height) =>
            (X, Y, Width, Height, IsVisible) = (x, y, width, height, true);

        public bool IsDrawRectangle;
        public bool IsDrawHorizontalLine;
        public bool IsDrawVerticalLine;

        public void Render(PlotDimensions dims, Bitmap bmp, bool lowQuality = false)
        {
            if (!IsVisible)
                return;
            using (var gfx = GDI.Graphics(bmp, dims, lowQuality: true, false))
            using (var fillBrush = GDI.Brush(FillColor))
            using (var fillBrush1 = GDI.Brush(BorderColor))
            using (var lineBorderPen = GDI.Pen(BorderColor, 3))
            using (var lineBorderDashPen = GDI.Pen(DotBorderColor, 3, LineStyle.Dot))
            using (var borderPen = GDI.Pen(BorderColor))
            {
                var x1 = X + dims.DataOffsetX;
                var x2 = x1 + Width;
                var y1 = Y + dims.DataOffsetY;
                var y2 = y1 + Height;
                var lineSpace = 18;
                if (Height > 8 && Width >= 4)
                {
                    gfx.FillRectangle(fillBrush, X + dims.DataOffsetX, Y + dims.DataOffsetY, Width, Height);
                    gfx.DrawRectangle(borderPen, X + dims.DataOffsetX, Y + dims.DataOffsetY, Width, Height);
                    this.IsDrawVerticalLine = false;
                    this.IsDrawHorizontalLine = false;
                    this.IsDrawRectangle = true;
                }
                else if (Height >= 0 && Height <= 8)
                {
                    var yMin = (float)dims.GetPixelY(dims.YMin);
                    var xOffset = lineBorderPen.Width / 2;
                    if (Width > 4)
                    {
                        gfx.DrawLine(lineBorderPen, x1 - xOffset, y1 - lineSpace, x1 - xOffset, y1 + lineSpace);
                        gfx.DrawLine(lineBorderDashPen, x1 - xOffset, yMin, x1 - xOffset, y1 + lineSpace);
                    }
                    if (Width >= 8)
                    {
                        gfx.DrawLine(lineBorderPen, x2 + xOffset, y2 - lineSpace, x2 + xOffset, y2 + lineSpace);
                        gfx.DrawLine(lineBorderDashPen, x2 + xOffset, yMin, x2 + xOffset, y2 + lineSpace);
                    }
                    gfx.DrawLine(lineBorderPen, x1, y1, x2, y1);
                    this.IsDrawHorizontalLine = true;
                    this.IsDrawVerticalLine = false;
                    this.IsDrawRectangle = false;
                }
                else if (Width >= 0 && Width <= 8)
                {
                    var xMin = (float)dims.GetPixelX(dims.XMin);
                    var yOffset = lineBorderPen.Width / 2;
                    if (Height > 8)
                    {
                        gfx.DrawLine(lineBorderPen, x1 - lineSpace, y1 - yOffset, x1 + lineSpace, y1 - yOffset);
                        gfx.DrawLine(lineBorderDashPen, xMin, y1 - yOffset, x1 - lineSpace, y1 - yOffset);
                    }
                    if (Height >= 8)
                    {
                        gfx.DrawLine(lineBorderPen, x2 - lineSpace, y2 + yOffset, x2 + lineSpace, y2 + yOffset);
                        gfx.DrawLine(lineBorderDashPen, xMin, y2 + yOffset, x2 - lineSpace, y2 + yOffset);
                    }
                    gfx.DrawLine(lineBorderPen, x1, y1, x1, y2);
                    this.IsDrawVerticalLine = true;
                    this.IsDrawRectangle = false;
                    this.IsDrawHorizontalLine = false;
                }
            }
        }
    }
}
`
**Settings.cs**

` public bool MouseZoomRect(float mouseNowX, float mouseNowY, bool finalize = false)
 {
     float left = Math.Min(MouseDownX, mouseNowX);
     float right = Math.Max(MouseDownX, mouseNowX);
     float top = Math.Min(MouseDownY, mouseNowY);
     float bottom = Math.Max(MouseDownY, mouseNowY);
     float width = right - left;
     float height = bottom - top;

     if (finalize)
     {
         ZoomRectangle.Clear();
         List<PointF> points = new();
         var includePointCount = 0;
         foreach (var plottable in this.Plottables.OfType<IPlottable>())
         {
             if (plottable is ScatterPlot plot)
             {
                 for (var i = 0; i < plot.PointCount; i++)
                 {
                     var pointX = plot.Xs[i];
                     var pointY = plot.Ys[i];
                     points.Add(new PointF { X = XAxis.Dims.GetPixel(pointX), Y = YAxis.Dims.GetPixel(pointY) });
                 }
             }
             if (plottable is SignalPlotXYConst<double, double> signalPlot)
             {
                 for (var i = 0; i < signalPlot.PointCount; i++)
                 {
                     var pointX = signalPlot.Xs[i];
                     var pointY = signalPlot.Ys[i];
                     points.Add(new PointF { X = XAxis.Dims.GetPixel(pointX), Y = YAxis.Dims.GetPixel(pointY) });
                 }
             }
         }
         var yDimsMax = YAxis.Dims.Max;
         var yDimsMin = YAxis.Dims.Min;
         var xDimsMax = XAxis.Dims.Max;
         var xDimsMin = XAxis.Dims.Min;
         if (yDimsMin > points.Max(x => YAxis.Dims.GetUnit(x.Y)) || yDimsMax < points.Min(x => YAxis.Dims.GetUnit(x.Y)))
         {
             return false;
         }
         if (xDimsMin > points.Max(x => XAxis.Dims.GetUnit(x.X)) || xDimsMax < points.Min(x => XAxis.Dims.GetUnit(x.X)))
         {
             return false;
         }

         if (height >= 8 && width >= 4 && ZoomRectangle.IsDrawRectangle)
         {
             includePointCount += points.Count(x => x.X > left && x.X < right && x.Y > top && x.Y < bottom);
         }
         else if (height >= 0 && height <= 8 && ZoomRectangle.IsDrawHorizontalLine)
         {
             includePointCount += points.Count(x => x.X > left && x.X < right && YAxis.Dims.GetUnit(x.Y) < YAxis.Dims.GetUnit(bottom));
                             }
         else if (width >= 0 && width <= 8 && ZoomRectangle.IsDrawVerticalLine) 
         {
             includePointCount += points.Count(x => x.Y > top && x.Y < bottom && x.X < right);
         }

         if (includePointCount == 0)
         {
             return false;
         }
         if (ZoomRectangle.IsDrawRectangle)
         {
             foreach (Axis axis in Axes)
             {
                 if (axis.IsHorizontal)
                 {
                     double x1 = axis.Dims.GetUnit(left);
                     double x2 = axis.Dims.GetUnit(right);
                     axis.Dims.SetAxis(x1, x2);
                 }
                 else
                 {
                     double y1 = axis.Dims.GetUnit(bottom);
                     double y2 = axis.Dims.GetUnit(top);
                     axis.Dims.SetAxis(y1, y2);
                 }
             }
         }
         else if (ZoomRectangle.IsDrawHorizontalLine)
         {
             foreach (Axis axis in Axes)
             {
                 if (axis.IsHorizontal)
                 {
                     double x1 = axis.Dims.GetUnit(left);
                     double x2 = axis.Dims.GetUnit(right);
                     axis.Dims.SetAxis(x1, x2);
                 }
             }
         }
         else if (ZoomRectangle.IsDrawVerticalLine)
         {
             foreach (Axis axis in Axes)
             {
                 if (axis.IsVertical)
                 {
                     double y1 = axis.Dims.GetUnit(bottom);
                     double y2 = axis.Dims.GetUnit(top);
                     axis.Dims.SetAxis(y1, y2);
                 }
             }
         }
     }
     else
     {
         // TODO: dont require data offset shifting prior to calling this
         ZoomRectangle.Set(left - XAxis.Dims.DataOffsetPx, top - YAxis.Dims.DataOffsetPx, width, height);
     }
     return true;
 }`

**Comment by StendProg** [comment]
Hi @LXX1029,

Based on the code provided, you want to make a change to `ScottPlot 4`. If so, you should state this explicitly in your post so as not to cause confusion.
Active development is being done for `ScottPlot 5`. `ScottPlot 4` is also supported, but it is a bit unreasonable to introduce new features for `ScottPlot 4`.

If you meant `ScottPlot 5`:
This looks interesting. I think if you make this behavior configurable/and disabled by default, it would be hard to find an objection.

**Comment by swharden** [comment]
Hi @LXX1029 (and @StendProg!) 👋 

Thanks for this suggestion! I really like your video screenshot demonstrating the idea - it makes it really clear what this code change accomplishes and how it works.

However, it's true that the latest version of ScottPlot has similar functionality when you middle-click-drag over an axis (outside the plot area), as seen here:

![axis zoom](https://github.com/user-attachments/assets/4432a545-608e-46f8-8685-140fb7c36b05)

Because this feature is built into ScottPlot 5 (and new features are no longer being added to ScottPlot 4) I probably won't take action on this recommendation, but I _really_ appreciate you sharing the code above and I think it will be helpful for others who may want to implement this similar to how you did.

Thanks again for sharing this!

> If we implement your solution by default, we either force the user to hit the mouse with pixel accuracy to enable the mode, or we will take away the ability to scale in a very narrow range if we introduce additional boundaries.

PS: This is also a very good observation, and preserving the present behavior (allowing quick zoom into narrow ranges) is probably worth preserving over adding this recommended feature at this time.

**Comment by LXX1029** [comment]
> Hi @LXX1029 (and @StendProg!) 👋
> 
> Thanks for this suggestion! I really like your video screenshot demonstrating the idea - it makes it really clear what this code change accomplishes and how it works.
> 
> However, it's true that the latest version of ScottPlot has similar functionality when you middle-click-drag over an axis (outside the plot area), as seen here:
> 
> ![axis zoom](https://private-user-images.githubusercontent.com/4165489/386422802-4432a545-608e-46f8-8685-140fb7c36b05.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzQ5NjcsIm5iZiI6MTczMTYzNDY2NywicGF0aCI6Ii80MTY1NDg5LzM4NjQyMjgwMi00NDMyYTU0NS02MDhlLTQ2ZjgtODY4NS0xNDBmYjdjMzZiMDUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMDEzNzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWE0YjVjY2JiMGZiN2RmYjRjYjZmMDBhN2M0MzA0YmVjYjM2OTA1N2I1M2Y5Njc5ODliZGRkZWJlYTU2Zjg5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lX7CAvzC8MqjFQ_jLTSWGgp5xZO9nkRzShtpUmK2CM8) [ ![axis zoom](https://private-user-images.githubusercontent.com/4165489/386422802-4432a545-608e-46f8-8685-140fb7c36b05.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzQ5NjcsIm5iZiI6MTczMTYzNDY2NywicGF0aCI6Ii80MTY1NDg5LzM4NjQyMjgwMi00NDMyYTU0NS02MDhlLTQ2ZjgtODY4NS0xNDBmYjdjMzZiMDUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMDEzNzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWE0YjVjY2JiMGZiN2RmYjRjYjZmMDBhN2M0MzA0YmVjYjM2OTA1N2I1M2Y5Njc5ODliZGRkZWJlYTU2Zjg5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lX7CAvzC8MqjFQ_jLTSWGgp5xZO9nkRzShtpUmK2CM8) ](https://private-user-images.githubusercontent.com/4165489/386422802-4432a545-608e-46f8-8685-140fb7c36b05.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzQ5NjcsIm5iZiI6MTczMTYzNDY2NywicGF0aCI6Ii80MTY1NDg5LzM4NjQyMjgwMi00NDMyYTU0NS02MDhlLTQ2ZjgtODY4NS0xNDBmYjdjMzZiMDUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMDEzNzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWE0YjVjY2JiMGZiN2RmYjRjYjZmMDBhN2M0MzA0YmVjYjM2OTA1N2I1M2Y5Njc5ODliZGRkZWJlYTU2Zjg5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lX7CAvzC8MqjFQ_jLTSWGgp5xZO9nkRzShtpUmK2CM8) [ ](https://private-user-images.githubusercontent.com/4165489/386422802-4432a545-608e-46f8-8685-140fb7c36b05.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzQ5NjcsIm5iZiI6MTczMTYzNDY2NywicGF0aCI6Ii80MTY1NDg5LzM4NjQyMjgwMi00NDMyYTU0NS02MDhlLTQ2ZjgtODY4NS0xNDBmYjdjMzZiMDUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMDEzNzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWE0YjVjY2JiMGZiN2RmYjRjYjZmMDBhN2M0MzA0YmVjYjM2OTA1N2I1M2Y5Njc5ODliZGRkZWJlYTU2Zjg5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lX7CAvzC8MqjFQ_jLTSWGgp5xZO9nkRzShtpUmK2CM8)
> 
> Because this feature is built into ScottPlot 5 (and new features are no longer being added to ScottPlot 4) I probably won't take action on this recommendation, but I _really_ appreciate you sharing the code above and I think it will be helpful for others who may want to implement this similar to how you did.
> 
> Thanks again for sharing this!
> 
> > If we implement your solution by default, we either force the user to hit the mouse with pixel accuracy to enable the mode, or we will take away the ability to scale in a very narrow range if we introduce additional boundaries.
> 
> PS: This is also a very good observation, and preserving the present behavior (allowing quick zoom into narrow ranges) is probably worth preserving over adding this recommended feature at this time.

Thanks for responding so quickly @swharden ! You demonstrated a better feature in ScottPlot 5,and I would probably prefer to use the new feature from in ScottPlot 5.Thanks again!!

**Comment by LXX1029** [comment]
> Hi @LXX1029,
> 
> Based on the code provided, you want to make a change to `ScottPlot 4`. If so, you should state this explicitly in your post so as not to cause confusion. Active development is being done for `ScottPlot 5`. `ScottPlot 4` is also supported, but it is a bit unreasonable to introduce new features for `ScottPlot 4`.
> 
> If you meant `ScottPlot 5`: This looks interesting. I think if you make this behavior configurable/and disabled by default, ~it would be hard to find an objection~.
> 
> Updated: `Scotplot 5` already has a pretty good implementation of scaling only one axis if you use hot keys to lock the other. If we implement your solution by default, we either force the user to hit the mouse with pixel accuracy to enable the mode, or we will take away the ability to scale in a very narrow range if we introduce additional boundaries. Anyway, there is a lot to discuss here.

Thanks for responding so quickly! I've seen the new feature,it's better than my demo,I'm more inclined to use the new feature because it's smoother to use.
