### ISSUE TITLE
How to make the ellipse rotate with mouse move ?

### ISSUE THREAD

**Issue by luyingru555** [ScottPlot/ScottPlot#4510]
I want to realize a function the Ellipse can be created when the  mouse down and move ,thus I get the Ellipse.cs in ScottPlot5 ,but there is a deviation when i used canvas.RotateDegrees to rotate, i don't know why?

```cs
The following is the code in Ellipse.cs
 public virtual void Render(RenderPack rp)
    {
        if (!IsVisible || RadiusIsNotFinite)
            return;

        using var paint = new SKPaint();

        rp.Canvas.Translate(Axes.GetPixel(Center).ToSKPoint());
        rp.Canvas.RotateDegrees((float)Rotation);

        float rx = Axes.GetPixelX(RadiusX) - Axes.GetPixelX(0);
        float ry = Axes.GetPixelY(RadiusY) - Axes.GetPixelY(0);

        PixelRect rect = new(-rx, rx, ry, -ry);
        Drawing.FillOval(rp.Canvas, paint, FillStyle, rect);
        Drawing.DrawOval(rp.Canvas, paint, LineStyle, rect);
    }
```

The following  is the code that i realised:
this function is used when mouse down and move ,the Ellipse Size is changed by UpdataEllipse()

```cs
public void UpdataEllipse(Coordinates fixPoint, Coordinates mousePoint)
{
    RadiusY = mousePoint.Distance(fixPoint) / 2;
    RadiusX = RadiusY * Math.Sqrt(1 - E * E);
    Center = new Coordinates((fixPoint.X + mousePoint.X) / 2, (fixPoint.Y + mousePoint.Y) / 2);
    double angleDegrees = Math.Atan2(mousePoint.Y - fixPoint.Y, mousePoint.X - fixPoint.X) * (180.0 / Math.PI);
    Rotation = angleDegrees;

    Debug.WriteLine(Rotation);
    FixPoint = fixPoint;//this is the mouse down position
    MousePoint = mousePoint; this is the mouse move position 
}

protected override void OnRender(DrawingContext drawingContext)
{
    if (WPFPlot == null)
    {
        throw new InvalidOperationException("ScottPlot loading error");
    }
  
    var canvasWidth = (int)WPFPlot.OriginRect.Width;
    var canvasHeight = (int)WPFPlot.OriginRect.Height;

    using SKBitmap bitmap = new SKBitmap(canvasWidth, canvasHeight);
    using SKCanvas canvas = new SKCanvas(bitmap);
    using var paint = new SKPaint
    {
        StrokeWidth = 2,
        IsAntialias = true // 
    };

   // i draw a line between mouse down point  FixPoint and mouse move point  MousePoint to verify the accuracy of the rotation angle
    PixelRect rect1 = new(GetPixel(FixPoint).X, GetPixel(MousePoint).X, GetPixel(FixPoint).Y, GetPixel(MousePoint).Y);
    Drawing.DrawRectangle(canvas, rect1, paint, LineStyle);
    PixelLine pixelLine = new PixelLine(GetPixel(FixPoint), GetPixel(MousePoint));
    Drawing.DrawLine(canvas, paint, pixelLine, LineStyle);

    // it's not easy for me to understand the function of canvas.Translate and   canvas.RotateDegrees
   // the  RotateDegrees  is  not the same as the line
    canvas.Translate(GetPixel(FixPoint).ToSKPoint());
    canvas.RotateDegrees((float)Rotation);
   
    float rx = GetPixelX(RadiusX) - GetPixelX(0);
    float ry = GetPixelY(RadiusY) - GetPixelY(0);
    PixelRect rect = new(-rx, rx, -ry, ry);


    Drawing.DrawOval(canvas, paint, LineStyle, rect);
    Drawing.DrawRectangle(canvas, rect, paint, LineStyle);
     // this is a new Layer I rendered over the Scottplot 
    ImageHelper.DrawImage(drawingContext, bitmap, WPFPlot.Plot.LastRender.DataRect);

}
```

![image](https://github.com/user-attachments/assets/3e8ef7d4-b991-4478-b092-1f91d58a4924)
in the picture the red line is the deviation  , i want the red can coincide with yellow line

**Comment by swharden** [comment]
Hi @luyingru555, thank you for this question!

Unfortunately, there isn't enough information here for me to fully understand your question. I also cannot run the sample code you shared above because it is incomplete.

It sounds like you suspect that ellipse rotation is not accurate. I don't understand much more about your question though 😅 

I will try to create a sample app that lets us evaluate whether ellipse rotation is accurate or not and will share what I find in a follow-up comment here.

**Comment by swharden** [comment]
This seems all right to me! I'll close this issue for now, but let us know if the code below can be modified to demonstrate the issue you're trying to describe and I'll open it back up and we can take a closer look together 👍 

```cs
using ScottPlot;

namespace Sandbox.WinForms;

public partial class Form1 : Form
{
    ScottPlot.Plottables.Ellipse MyEllipse;
    public Form1()
    {
        InitializeComponent();

        // place an ellipse
        Coordinates center = new(3, 3);
        MyEllipse = formsPlot1.Plot.Add.Ellipse(center, radiusX: 3, radiusY: 0.5);
        formsPlot1.Plot.Add.Marker(center);

        // setup initial axis limits
        formsPlot1.Plot.Axes.SquareUnits();
        formsPlot1.Plot.Axes.AutoScale();
        formsPlot1.Plot.Axes.ZoomOut(3);

        // change ellipse rotation using the mouse
        trackBar1.ValueChanged += (s, e) =>
        {
            MyEllipse.Rotation = trackBar1.Value;
            Text = $"Rotation: {trackBar1.Value}º";
            formsPlot1.Refresh();
        };
    }
}
```

![image](https://github.com/user-attachments/assets/930beb80-8f1c-46bd-8dd1-f74c864a4795)

**Comment by swharden** [comment]
This line may be the key:

```cs
formsPlot1.Plot.Axes.SquareUnits();
```

Without it, the plot could be "stretched" so that a angle _in Cartesian space_ is no longer the expected angle _in pixel space_. For example, consider this code which makes a line you'd expect to be at a 45º angle. If you "stretch" the plot, it is no longer 45º on the screen, but it is on the plot

axis with square units | axis with non-square units
---|---
![image](https://github.com/user-attachments/assets/d53067bc-c494-4837-ab2b-297d9a654f6f)|![image](https://github.com/user-attachments/assets/164d1b31-cced-40c5-a57f-6b7640548bd7)

**Comment by luyingru555** [comment]
Is there any way that the plot don't need to stretched without using formsPlot1.Plot.Axes.SquareUnits(), because i draw a ellipse which is not rendered with scottplot . it's diffcult for me to know where SquareUnits() work

**Comment by luyingru555** [comment]
Thank you for your answer!!  this is really the key,  i have resolved the problem
