### ISSUE TITLE
Text does not render on Kylin OS

### ISSUE THREAD

**Issue by pkq520** [ScottPlot/ScottPlot#4511]
**Question:** Hello everyone, I've been using Kylin OS (similar to Unbantu) recently, with the Avalonia framework, drawing pictures, I use ScottPlot version 5.0, it runs fine on win, but the tab of the horizontal and vertical coordinates on the Kirin system is missing, I tried to install libfreetype6 libfontconfig1 fontconfig, but it didn't work, can you give me some help, thank you very much

**ScottPlot Version:** ScottPlot.Avalonia 5.0,45

![1731576667998](https://github.com/user-attachments/assets/c0e1be7b-c23b-47d5-b9ac-d9ab14575df1)
This is the rendering effect on the Kylin operating system, and the horizontal and vertical tabs are gone

.axaml
<StackPanel>
  <ScottPlot:AvaPlot Name="AvaPlot1" Width="400" Height="300"/>
</StackPanel>
.cs
double[] dataX = { 1, 2, 3, 4, 5 };
double[] dataY = { 1, 4, 9, 16, 25 };
AvaPlot avaPlot1 = this.Find<AvaPlot>("AvaPlot1");
avaPlot1.Plot.Add.Scatter(dataX, dataY);
avaPlot1.Refresh();

**Comment by swharden** [comment]
It sounds like you've tried the things suggested on https://scottplot.net/faq/dependencies/

Unfortunately I don't have much else to suggest since I don't have a similar OS installed for me to investigate with ... Perhaps try manually naming a font file to use? https://scottplot.net/cookbook/5.0/Miscellaneous/CustomFontFiles/

**Comment by pkq520** [comment]
Thanks for the reply, but I also tried to run it on a virtual machine with unbantu22.04, also installed the mentioned package, but it still doesn't show up.
![e390a191-2aa3-4691-813e-82d9c84dff78](https://github.com/user-attachments/assets/2d0dc657-e5fa-4dee-9017-5b7aa84d3b5c)

**Comment by pkq520** [comment]
The latest news, Unbantu and Kylin systems can be used, your tips gave me inspiration, you do need to specify fonts manually, you need to use fc-list : family to see the fonts supported by the system, and then something like that:

avaPlot1.Plot.Axes.Bottom.TickLabelStyle.FontName = "Noto Sans Gurmukhi";
avaPlot1.Plot.Axes.Left.TickLabelStyle.FontName = "Noto Sans Gurmukhi";

This way you can bind the font manually. Thanks again.

**Comment by pkq520** [comment]
Another point is that my system name is Kylin, which I said in my previous description as Kirin, if you can, please change the title so as not to mislead people who view it later
