### ISSUE TITLE
Crosshair doesn't hide as expected.

### ISSUE THREAD

**Issue by clsferguson** [ScottPlot/ScottPlot#4515]
**Issue:** Just noticed that a crosshair won't hide under all circumstances. 

**ScottPlot Version:** demo app 5.0.36

**Code Sample:** [Demo code](https://github.com/ScottPlot/ScottPlot/blob/main/src/ScottPlot5/ScottPlot5%20Demos/ScottPlot5%20WinForms%20Demo/Demos/ShowValueUnderMouseSignalXY.cs)

```cs
            if (!nearest.IsReal && MyCrosshair.IsVisible)
            {
                MyCrosshair.IsVisible = false;
                formsPlot1.Refresh();
                Text = $"No point selected";
            }
```

https://github.com/user-attachments/assets/4c11815f-3e83-4659-aa0b-5205a37879fb

**Comment by swharden** [comment]
Hi @clsferguson, thanks for reporting this!

Funny, it works as expected over here...

![4515](https://github.com/user-attachments/assets/d3fb3a84-d251-44b7-b1b5-4cd06f55defb)

Maybe double-check to make sure you're using the latest demo? There's a chance this was a bug that has already been fixed.

It looks like the current demo version is 5.0.45 which is a bit newer than the one you reported trying
https://scottplot.net/demos/ScottPlot-Demo-5.0.45.zip
