### ISSUE TITLE
CandlestickPlot.FallingColor did not set FallingLineStyle.Color

### ISSUE THREAD

**Issue by czastack** [ScottPlot/ScottPlot#4521]
**Issue:** (Describe the bug here)
CandlestickPlot.FallingColor did not set FallingLineStyle.Color. I found the source code is
```
    public Color FallingColor
    {
        set
        {
            FallingFillStyle.Color = value;
            FallingFillStyle.Color = value;
        }
    }
```

**ScottPlot Version:** (What NuGet package are you using?)
5.0.45

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
ScottPlot.Plot myPlot = new();
/* code to reproduce the bug */
var candlePlot = myPlot.Add.Candlestick(prices);
candlePlot.RisingColor = Color.FromHex("#f23645");
candlePlot.FallingColor = Color.FromHex("#089981");
```

**Comment by swharden** [comment]
Great catch @czastack! The bug is here, and I'll fix this today and release a new package tomorrow 🚀 

https://github.com/ScottPlot/ScottPlot/blob/99074c43bab7ed007c549a66ce4f5fbf65b6318e/src/ScottPlot5/ScottPlot5/Plottables/CandlestickPlot.cs#L44-L60
