### ISSUE TITLE
Maui support on .NET 9

### ISSUE THREAD

**Issue by King-Taz** [ScottPlot/ScottPlot#4525]
**Issue:** NET9 upgrade in Maui creates compile issue

**ScottPlot Version:** 5.0.45 (in Net9 Maui)

### XAML
```xml
<Grid ColumnDefinitions="*" RowDefinitions="*" Padding="0,0,0,0" >
    <ScottPlot:MauiPlot x:Name="MauiPlot1" />
</Grid>
```

### Code-Behind
```cs
private void SimpleDrawPhasorPlot()
{
    //Create arrow base coordinates used for all vectors
    Coordinates arrowBase = new(0, 0);

    // create arrow 1
    Coordinates arrow1Tip = new(5, 0);
    CoordinateLine arrow1Line = new(arrowBase, arrow1Tip);

    // add a simple arrow
    var arrow1 = MauiPlot1.Plot.Add.Arrow(arrow1Line);
    arrow1.ArrowFillColor = Colors.Red;
    arrow1.ArrowLineWidth = 0;
    arrow1.ArrowWidth = 5;
    arrow1.ArrowheadLength = 20;
    arrow1.ArrowheadAxisLength = 20;
    arrow1.ArrowheadWidth = 20;
    var dl1 = MauiPlot1.Plot.Add.Text("T(1)", arrow1Tip);
    dl1.LabelFontSize = 28;
    dl1.LabelFontColor = Colors.Black;

    MauiPlot1.Plot.HideGrid();
    MauiPlot1.Plot.Layout.Frameless();

    // Preserve X-axis plot scaling during window size changes
    SquarePreserveX rule2 = new(xAxis: MauiPlot1.Plot.Axes.Bottom, yAxis: MauiPlot1.Plot.Axes.Left);
    MauiPlot1.Plot.Axes.Rules.Clear();
    MauiPlot1.Plot.Axes.Rules.Add(rule2);
}
```

### Compile errors

<img width="1269" alt="Screenshot 2024-11-16 132113" src="https://github.com/user-attachments/assets/a273bdbf-3877-445b-b530-212f43de5b98">

If it matters, please note the change in creating Maui AppShell. The previous method

```cs
MainPage = new AppShell();  // deprecated
```

has been deprecated. New method is

```cs
protected override Window CreateWindow(IActivationState? activationState)
{
    return new Window(new AppShell());
}
```

**Comment by King-Taz** [comment]
Some more information during rebuild
![image](https://github.com/user-attachments/assets/3b3024ee-51f2-44f9-9aad-3ceda81e1596)

**Comment by swharden** [comment]
Hi @King-Taz, I made a new app targeting .NET 9 following the directions on https://scottplot.net/quickstart/maui/ and it seems to work as expected.

Perhaps your question relates more to how to upgrade Maui apps from .NET 8 to .NET 9? If this is the case, the topic may be out of scope of the issues section for this repository.

![image](https://github.com/user-attachments/assets/65e2f5df-a0fb-4800-be79-8b3cea6a27a9)

Either way, hope it helps!

**Comment by King-Taz** [comment]
Thanks for the quick reply and help! This was the issue
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<WindowsSdkPackageVersion>10.0.19041.34</WindowsSdkPackageVersion>
                ...
```
I forgot i added that, should have read the instructions! Have a great weekend!
