### ISSUE TITLE
To plot two data buffers with different time scales and synchronize them on a common X-axis in WinForms ScottPlot

### ISSUE THREAD

**Issue by kareem469** [ScottPlot/ScottPlot#4532]
**To plot two data buffers with different time scales and synchronize them on a common X-axis in ScottPlot:** 

**ScottPlot Version: 5.0.45** 

I have two different time stamp data buffers with different times in msecs, one with 1k size and the other with 5k. Now I want to have common x axis for this in WinForms scottplot graph

**Comment by swharden** [comment]
> I want to have common x axis for this in WinForms scottplot graph

This should help!

https://scottplot.net/demo/5.0/#shared-axes

**Comment by kareem469** [comment]
> > I want to have common x axis for this in WinForms scottplot graph
> 
> This should help!
> 
> https://scottplot.net/demo/5.0/#shared-axes

No, my requirement is to plot the two different x-axis on a single graph

**Comment by swharden** [comment]
Does this example help solve your problem? It shows a second `Right` axis, but the code can be modified to enable the `Top` axis and it should produce the result you're expecting.

https://scottplot.net/cookbook/5.0/MultiAxis/RightAxis/

If not, it may be that I'm misunderstanding your goal. If you could share a screenshot or mspaint drawing of the type of graph you're trying to create, I'd be happy to help you reach your goal.

**Comment by kareem469** [comment]
I have enclosed the screen shot below for your reference. Here the Y-axis has different parameters. And also each parameter having a different X-axis. But here all the parameters X-axis is synchornizing into a single X-axis and plotting the graph

![image](https://github.com/user-attachments/assets/a12176e4-48a0-489a-b1a3-a80f391c7712)
