### ISSUE TITLE
AutoScale and GetAxisLimit Unexpected Behavior

### ISSUE THREAD

**Issue by dellod** [ScottPlot/ScottPlot#4534]
**Issue:** (Describe the bug here)
Hello!

Upon loading a "large" dataset, it was  first seen that AutoScale on FormsPlot was not behaving as expected on the Y axis and was setting the min and max to -11.5 and 11.5, respectively.

![image](https://github.com/user-attachments/assets/164b15f1-a5e5-4f0d-ad92-c2d8842ff455)

After digging a bit more in debugger it was found the Axis limit for Y was being set to infinity and further examining the limits with GetAxisLimit, it was shown that my Y limits were being set to NaN. The actual limits are around -3000 to 3000 with about 5000 data points. In addition, there are also 100 other signals that I have hidden in the plot.

![image](https://github.com/user-attachments/assets/51df8624-843a-4f83-9aef-e39b1db97410)

Note, all the data that I have uploaded has been added as a SignalXY plottable.

Additionally, I have tested this with a variety of other datasets and this is the only time I have seen this issue but that being said, this is most likely the largest set I've used.

**ScottPlot Version:** (What NuGet package are you using?)
5.0.42.0

**Comment by swharden** [comment]
Hi @dellod, thanks for reporting this!

> Additionally, I have tested this with a variety of other datasets and this is the only time I have seen this issue but that being said, this is most likely the largest set I've used.

Could it be that some of the data you plotted contains `NaN`? This seems the most likely way to explain this behavior. 

Double-check to make sure your data doesn't contain NaN and if there's still an issue, write a few lines of code here I can use to reproduce the issue on my end and we can take a closer look together! 👍

**Comment by dellod** [comment]
Thanks for the quick reply!

Yes, after looking more closely at the dataset this is definitely happening on our parsing side when giving the data to the plot. But now I am wondering, if I need to indicate breaks in our dataset, how would I represent the Y value otherwise? For example, the data that I have is over time (seconds) and if at one point the data at the current X time is not present I still need to fill that coordinate with an X value and an empty Y somehow to indicate the gap in data.

This was my first approach as I was referring to the example indicated here: https://www.scottplot.net/cookbook/5.0/Scatter/ScatterWithGaps/

Is this not recommended for SignalXY plots?

**Comment by swharden** [comment]
> if I need to indicate breaks in our dataset, how would I represent the Y value?

> Is this not recommended for SignalXY plots?

I think Scatter plots support data with NaN, but Signal and SignalXY do not. Those plot types are optimized to plot data will tens of millions of points, so doing null checks on every individual data point as renders occur isn't consistent with their performance goals. 

I think you're on the right track for presenting "broken" data lines: either use Scatter plot with NaN, or place multiple signal plots recognizing that each signal plot will appear as its own line.

Hope it helps!
Scott
