### ISSUE TITLE
It would be nice if annotations were not clipped

### ISSUE THREAD

**Issue by CBrauer** [ScottPlot/ScottPlot#4537]
**Suggestion:** 

I noticed that sometimes annotations get clipped.
Here is what I have done:
```cs
ScottPlot.Plot plt = new();
plt.ScaleFactor = 2;
plt.Clear();

double[] xs = new double[] { 1, 2, 3, 4, 5, 6, 7 };
double[] ys = new double[] { 2, 2, 3, 3, 3.8, 4.2, 4 };

// plot original data as a scatter plot
var scatter = plt.Add.Scatter(xs, ys);
scatter.LineWidth = 0;
scatter.MarkerSize = 10;
scatter.Axes.YAxis = plt.Axes.Right;

// calculate the regression line
ScottPlot.Statistics.LinearRegression reg = new(xs, ys);

// plot the regression line
Coordinates pt1 = new(xs.First(), reg.GetValue(xs.First()));
Coordinates pt2 = new(xs.Last(),  reg.GetValue(xs.Last()));
var line = plt.Add.Line(pt1, pt2);
line.Color = Colors.Orange;
line.MarkerSize = 0;
line.LineWidth = 4;
line.LinePattern = LinePattern.Dashed;
line.Axes.YAxis = plt.Axes.Right;

var x1 = xs[^1];
var x2 = x1 + 3.0;
var y = ys[^1] + 1.0;
var targetLine = plt.Add.Line(x1, y, x2, y);
targetLine.Color = Colors.Gray;
targetLine.LineWidth = 2;
targetLine.LinePattern = LinePattern.Solid;
targetLine.Axes.YAxis = plt.Axes.Right;

var pt_start = new Coordinates(x1, y);
var text = $"It would sure be nice if this annotation was visible.";
var annotation = plt.Add.Text(text, pt_start);
annotation.LabelFontSize = 14;
annotation.LabelFontColor = Colors.Black;
annotation.Axes.YAxis = plt.Axes.Right;

// Render the plot
plt.SavePng("../../../scatter_with_limit.png", 800, 800);
```

With the result:
![scatter_with_limit](https://github.com/user-attachments/assets/4aa4d509-f93f-46d3-9706-de8c0b7d779d)
Charles

**Comment by swharden** [comment]
Hi @CBrauer,

Perhaps something like this could help?

```cs
var text = plt.Add.Text(text, pt_start);
text.Alignment = Alignment.UpperRight;
```

Also note that there's an _annotation_ plot type which may be a better fit for your application:

```cs
formsPlot1.Plot.Add.Annotation(text, Alignment.UpperRight);
```

https://scottplot.net/cookbook/5.0/Annotation/AnnotationPositions/

**Comment by CBrauer** [comment]
That gives me:

![scatter_with_limit](https://github.com/user-attachments/assets/5b0e5e4a-e622-4808-bf14-ad7e2e14a865)

That's not what I want.

**Comment by swharden** [comment]
Hi @CBrauer, it seems like `Annotation` may not be what you're looking for, but can you clarify the behavior you would like to see? I know your original post showed a `Text` that was too long for the data area and you indicated that's not what you wanted - but what would you prefer to see? Are you asking about how to create a textbox with "word wrapping"?
