### ISSUE TITLE
About 3D

### ISSUE THREAD

**Issue by 2638662731** [ScottPlot/ScottPlot#4539]
Hello, I have been using ScottPlot for a long time. It is a very useful icon component, but I have not found that it can support 3D related development, such as drawing curves in a 3D coordinate system, etc. I am not sure if the current version supports this feature

**Comment by swharden** [comment]
Hi @2638662731, thanks for this question!

Yes, some progress was made toward 3D plots but development stalled-out a while back. I'd be happy to start putting effort back into this though if you want to work together on it! When you download this repository and run the main solution you'll find a 3D app in the 'sandbox' folder. It shows how far I got, which is a reasonable start, but it could definitely use refinement to the core 3D rendering system before we start building it out further. I'd welcome input if you want to take a look and are interested in collaborating on it!

#2358 has some good discussion

This is the sandbox app I'm referencing. It hasn't been touched in a while, but it's definitely a start!

![3d4](https://github.com/ScottPlot/ScottPlot/assets/4165489/bf6b19e9-83fe-4de0-9940-a4a1153ad022)
