### ISSUE TITLE
Heatmap   SetTicks

### ISSUE THREAD

**Issue by woodynwc** [ScottPlot/ScottPlot#4541]
I am using the Heatmap to display spectral data.  I have  used TickGenerator and RenderManager to successfully make a Y-axis.  I am struggling with the time-based X-axis.  I found this example for a regular chart using SetTicks but that does not seem to be available for a Heatmap chart?    Is there an example of how to convert the heatmap index-based X-axis to show a time-based axis?

```cs
ScottPlot.Plot myPlot = new();
// use manually defined ticks
double[] tickPositions = { 10, 25, 40 };      // I assume that these would be the heatmap array index values?
string[] tickLabels = { "Alpha", "Beta", "Gamma" };
myPlot.Axes.Bottom.SetTicks(tickPositions, tickLabels);
```

**Comment by swharden** [comment]
> I think I found a solution just using ScottPlot.TickGenerators.NumericAutomatic and Plot.Axes.Bottom.TickGenerator and then just make the function return the associated time as needed.

Hi @woodynwc, thanks for your original question, and it seems like you resolved this issue! If you have further questions let me know and we can open this back up.

Tangentially related, see https://github.com/swharden/Spectrogram

**Comment by ziziran** [comment]
> > I think I found a solution just using ScottPlot.TickGenerators.NumericAutomatic and Plot.Axes.Bottom.TickGenerator and then just make the function return the associated time as needed.
> 
> Hi @woodynwc, thanks for your original question, and it seems like you resolved this issue! If you have further questions let me know and we can open this back up.
> 
> Tangentially related, see https://github.com/swharden/Spectrogram

Which one is the better choice  heatmap  or image？  I want the Spectrogram can  scroll  like The DataStreamer plot type，for displaying the latest N values of a streaming dataset.     or where I change the length of  Spectrogram ，for display longer？

`using (var bmpSpecIndexed = spec.GetBitmap(multiplier, cbDecibels.Checked, roll: cbRoll.Checked))
using (var gfx = Graphics.FromImage(bmpSpec))            
{
    gfx.DrawImage(bmpSpecIndexed.ToBitmap(), 0, 0);                   
}`
