### ISSUE TITLE
New plot type: Bracket

### ISSUE THREAD

**Issue by FULL69** [ScottPlot/ScottPlot#4547]
In ScottPlot 4, I used Bracket plottable. I'm starting to use ScottPlot 5, but I haven't found this.
I added an ArrowShape to implement it in this way:

```cs
public class BracketLine : IArrowShape
{
    public void Render(RenderPack rp, PixelLine arrowLine, ArrowStyle arrowStyle)
    {
        float length = arrowLine.Length;

        PixelLine[] lines = [
            new PixelLine(0, 0, 0, -arrowStyle.ArrowheadWidth / 4),
            new PixelLine(0, 0, length, 0),
            new PixelLine(length, 0, length, -arrowStyle.ArrowheadWidth / 4),
            new PixelLine(length/2, 0, length/2, arrowStyle.ArrowheadWidth / 4)
        ];

        rp.CanvasState.Save();
        rp.CanvasState.Translate(arrowLine.Pixel2);
        rp.CanvasState.RotateDegrees(arrowLine.AngleDegrees + 90);

        // origin is the tip, base extends to the right
        Drawing.DrawLines(rp.Canvas, rp.Paint, lines, arrowStyle.LineStyle);

        rp.CanvasState.Restore();
    }
}
```

and  I modified ArrowShape.cs adding BracketLine in enum and adding item in switch:

```cs
ArrowShape.BracketLine => new ArrowShapes.BracketLine(), 
```

![Bracket](https://github.com/user-attachments/assets/ee8573e4-7437-4248-bdec-38cbbfd6def9)

The Cook book  "Arrow Shapes" show it correctly.

**Comment by swharden** [comment]
Hi @FULL69 (ha, nice)

Thanks for this suggestion! Your hacked-in bracket line is really clever - I don't know if I would have thought of that! I got a big kick out of reviewing your sample code.

However, I think it would be a good idea to add a proper bracket plot type to ScottPlot 5. I'll use this issue to track implementing that feature and hopefully it can get added in before tomorrow's release.

Thanks again for this suggestion!
Scott

## ScottPlot 4 "Bracket" for reference

https://scottplot.net/cookbook/4.1/category/plottable-bracket/

![image](https://github.com/user-attachments/assets/e89cf0e2-330c-4534-96dc-a44ed07a147b)

https://github.com/ScottPlot/ScottPlot/blob/01552cd09342841a020c2882dfcb4202a9f5e51a/src/ScottPlot4/ScottPlot/Plottable/Bracket.cs#L1-L168
