### ISSUE TITLE
New plot type: Stacked Range Chart

### ISSUE THREAD

**Issue by quantfreedom** [ScottPlot/ScottPlot#4548]
Don't forget to At the guy and see if he will respond lol ... that would be cool

https://youtu.be/5zBg9pH_6bE?si=aNM7QKs232AuCyr6

**Comment by swharden** [comment]
"A chart where the X axis is a discrete set and the Y axis represents ranges"

![image](https://github.com/user-attachments/assets/776f04e6-5a20-437a-b522-f9d07ed84be1)

**Comment by swharden** [comment]
![image](https://github.com/user-attachments/assets/9dfb84f3-a8cf-4564-be2d-fe8c51c91c8f)

![image](https://github.com/user-attachments/assets/61ab9053-bf8c-485c-ad91-d31f2fe53846)

![image](https://github.com/user-attachments/assets/c50efd4b-9df6-40d6-9003-c76a600e7f2f)

**Comment by swharden** [comment]
> Don't forget to At the guy and see if he will respond lol

with 5 million subs, I'd be impressed if they notice us, but I'll give it a go!

**Comment by swharden** [comment]
Hey @wellcaffeinated I wanted to ping you here to say thanks for yesterday's video about "the chart missing from all spreadsheet software", and to point out that in response to it we're adding this plot type to ScottPlot.NET and it will be in our next release coming out tomorrow 🚀 

The internet can be awesome sometimes. Thanks for what you do to to make it better for everyone!

**Comment by wellcaffeinated** [comment]
@swharden @quantfreedom 

Haha actually that's Henry Reich. I do minutelabs which is associated but different :)

I'll let him know you're planning to add it though!

**Comment by quantfreedom** [comment]
@wellcaffeinated  does henry reich have a github that I can @ him?

**Comment by wellcaffeinated** [comment]
I don't think he does. I told him though

**Comment by swharden** [comment]
This feature is now live! 🚀 


### https://scottplot.net/cookbook/5.0/Bar/RangeChart/

![image](https://github.com/user-attachments/assets/580c5b58-e319-47b6-86a7-f197d70a9359)


### https://scottplot.net/cookbook/5.0/Bar/StackedRangeChart/

![image](https://github.com/user-attachments/assets/6f284b54-ab4c-44ca-a676-c8cebad55392)
