### ISSUE TITLE
Heatmaps for Dummies?

### ISSUE THREAD

**Issue by ecrocombe** [ScottPlot/ScottPlot#4550]
**Question:** I would like to create a heatmap, similar to https://github.com/ScottPlot/ScottPlot/issues/457#issuecomment-642847244
The purpose is to show where PvP kills are occurring in a video game so players can find the "action". 

I have a set of X,Y coordinates ranging from -3500 to 3500 on both axis that I wish to overlay on a 2D map from a video game.

However, I cannot figure out the format of the data that is expected from me.
Could someone please help me? maybe an example?

I am already using this library for other tasks such as charting gameserver performance and when the most players are online, and it has been great, Thank you for all your hard work on this.

**ScottPlot Version:** (What NuGet package are you using?)
5.0.46 (dotnet 8)

**Comment by swharden** [comment]
Hi @ecrocombe, this should help!

```cs
double[,] data = ScottPlot.SampleData.MonaLisa();
var hm = formsPlot1.Plot.Add.Heatmap(data);
hm.Extent = new(-3500, 3500, -3500, 3500);
```

A heatmap of any size can be placed over a "map" of any size by defining its `Extent`

![image](https://github.com/user-attachments/assets/316908f6-9c5f-46e8-a271-ede0a003de10)

**Comment by ecrocombe** [comment]
@swharden 

Thanks for the quick response.

1. Could you please describe the `double[,]` and where i should be placing my co-ordinates? 
2. Also, all the points that do not have any data seem to still create a opaque colour, how can i remove this or set to transparent to reveal the background image?
3. How can I enforce the background image to fit the min/max X,Y cords, currently it is stretching outside of the bounds?

Code:
```
        // Create a new plot
        var plt = new ScottPlot.Plot();

        // Sample Data
        // the 2d map co-ordinates are -3500, 3500, -3500, 3500. 
        // including the 0 index, thats 7001 available spots along each axis
        double[,] data = new double[7001, 7001];

        // Add 3 co-ordinates where a PvP kill occurred on the map
        data[500, 500] = 1;
        data[3500, 3500] = 1;
        data[3600, 3650] = 1;
        
        var hm = plt.Add.Heatmap(data);
        // A heatmap of any size can be placed over a "map" of any size by defining its Extent
        hm.Extent = new(-3500, 3500, -3500, 3500);

        // Customize the plot
        plt.Title("Kill Heatmap");
        plt.XLabel("X Coordinate");
        plt.YLabel("Y Coordinate");

        // add the video game map as the background image
        Image background = new Image("aClQL7Q.png");
        plt.DataBackground.Image = background;
        plt.DataBackground.ImagePosition = ImagePosition.Center;

        // Save the plot as an image
        plt.SavePng("heatmap.png", 1920, 1080);
```
![heatmap](https://github.com/user-attachments/assets/cf517d35-733c-4154-ab7a-4896138e2a72)

**Comment by StendProg** [comment]
Hi @ecrocombe,

The answers to most of your questions are in the Cookbook https://scottplot.net/cookbook/5.0/. Take a little time and look it over. It's simple and clear.

1. Based on how you set HeatMap you can convert game coordinates to heatmap indices as follows:
```c#
i = coordinateX + 3500;
j = coordinateY + 3500;
data[j, i] = 1;
```

Don't forget to check that the indices do not exceed the array boundaries.

Most likely you will need to flip the heatmap by Y during initialization 
```c#
heatmap.FlipVertically = true;
```

2. https://scottplot.net/cookbook/5.0/Heatmap/HeatmapTransparentCells/
or
https://scottplot.net/cookbook/5.0/Heatmap/HeatmapAlphaMap/
4. https://scottplot.net/cookbook/5.0/Images/

Your project looks curious, could you post the final picture here when you get it?
