### ISSUE TITLE
"Open in New Windows" menu

### ISSUE THREAD

**Issue by jacckl** [ScottPlot/ScottPlot#4555]
**Issue:** When I use the "Open in New Windows" menu, the customized right-click menu disappears after closing the new window opened, and the position where the right-click menu opens is not at the mouse position. What's the reason?How can I avoid this problem?

**ScottPlot Version:** ScottPlot.WinForms 5.0.46

**Comment by swharden** [comment]
Hi @jacckl, thanks for reporting this! I believe this has been fixed by #4529 and will be in version 5.0.47 I will publish later today. 

If that doesn't fix the problem let me know and we can open this issue back up and take a closer look together 👍
