### ISSUE TITLE
WPF,If SquareUnits() is used, AutoScale() only works on the X-axis. 

### ISSUE THREAD

**Issue by VibrationAnalystCN** [ScottPlot/ScottPlot#4556]
**Issue:** If SquareUnits() is used, AutoScale() only works on the X-axis. Therefore, if the Y-axis data range is larger than X, some of the Y-axis data cannot be displayed. Version 5.46 has this issue, while version 5.35 has no problem.WPF has this issue, but the console program seems to have no problem.
![Plot](https://github.com/user-attachments/assets/01184f4d-d07d-439e-8c7b-c57888b1abbb)

**ScottPlot Version:** V5.46

**Code Sample:** 

```cs
static double[] Signals(double amplitude, double freq, double phase)
{
    double rad = phase * Math.PI / 180;
    double[] data = new double[1000];
    for (int i = 0; i < 1000; i++)
    {
        data[i] = amplitude * Math.Sin(Math.Tau * freq * (0.001 * i) + rad);
    }
    return data;
}

private void Show_Click(object sender, RoutedEventArgs e)
{
    var sigX = Signals(5, 10, 0); //A sine signal with a single peak value of 5
    var sigY = Signals(7, 10, 90); //A sine signal with a single peak value of 7
    myPlot.Plot.Clear();
    var sig = myPlot.Plot.Add.Scatter(sigX, sigY);
    sig.MarkerShape = ScottPlot.MarkerShape.None;
    myPlot.Plot.XLabel("sigX" ) ;
    myPlot.Plot.YLabel("sigY");
    myPlot.Plot.Axes.AutoScale();
    myPlot.Plot.Axes.SquareUnits(); //If SquareUnits() is used, AutoScale() only works on the X-axis.
    myPlot.Refresh();
}
```

**Comment by StendProg** [comment]
Hi @VibrationAnalystCN,

This change was made to prevent zoom out when resizing Control #4422. 
If you are happy with the old behavior try setting it manually:

```c#
//myPlot.Plot.Axes.SquareUnits();
myPlot.Axes.Rules.Add(new SquareZoomOut( myPlot.Axes.Bottom, myPlot.Axes.Left));
```

**Comment by VibrationAnalystCN** [comment]
> Hi @VibrationAnalystCN,
> 
> This change was made to prevent zoom out when resizing Control #4422. If you are happy with the old behavior try setting it manually:
> 
> ```cs
> //myPlot.Plot.Axes.SquareUnits();
> myPlot.Axes.Rules.Add(new SquareZoomOut( myPlot.Axes.Bottom, myPlot.Axes.Left));
> ```

Thanks to your help, the problem has been resolved.
