### ISSUE TITLE
Histogram: Allow Dynamic Updates to BarPlot

### ISSUE THREAD

**Issue by jpgarza93** [ScottPlot/ScottPlot#4557]
**Issue:**
It appears that in ScottPlot 5, the only way to adjust bars dynamically is to re-create them. Here's the current workaround:

**Proposed Enhancement**
It would be fantastic to have a mechanism to update bar data dynamically, such as passing the data by reference. This way, we could simply call AvaPlot.Refresh() to update the plot without having to recreate the BarPlot each time.

Example:
```
// Create
Histogram = Histogram.WithBinSize(size, leftLimit, rightLimit);
AvaPlot.Plot.Add.Bars(Histogram.Bins, Histogram.Counts);
AvaPlot.Refresh();
```
```
// Update
Histogram.Add(delta);
AvaPlot.Refresh();
```

**ScottPlot Version:** 
ScottPlot 5

**Comment by swharden** [comment]
Hi @jpgarza93, thanks for this suggestion! The new demo I'm adding in #4560 should help make this easier to achieve for future users.

```cs
public partial class LiveHistogram : Form, IDemoWindow
{
    readonly System.Windows.Forms.Timer Timer = new() { Enabled = true, Interval = 20 };
    int Total = 0;

    public LiveHistogram()
    {
        InitializeComponent();

        // create a histogram with 100 bins
        int binCount = 100;
        double[] initialHeights = Generate.Zeros(binCount);
        BarPlot bp = formsPlot1.Plot.Add.Bars(initialHeights);

        // style bars so there are no gaps between them
        foreach(var bar in bp.Bars)
        {
            bar.LineWidth = 0;
            bar.Size = 1;
            bar.FillStyle.AntiAlias = false;
        }

        // prevent AutoScale() from adding space below the bars
        formsPlot1.Plot.Axes.Margins(bottom: 0);

        // simulate live incoming data
        Timer.Tick += (s, e) =>
        {
            int newValueCount = Generate.RandomInteger(50, 100);
            for (int i = 0; i < newValueCount; i++)
            {
                double randomValue = Generate.RandomNormalNumber(mean: 50, stdDev: 10);
                int binIndex = (int)NumericConversion.Clamp(randomValue, 0, binCount - 1);
                bp.Bars[binIndex].Value += 1;
                Total += 1;
            }

            formsPlot1.Plot.Title($"Total: {Total:N0}");
            formsPlot1.Plot.Axes.AutoScale();
            formsPlot1.Refresh();
        };
    }
}
```

![LiveHistogram](https://github.com/user-attachments/assets/42adf530-507e-44df-9002-70fdadd1bf95)

**Comment by jpgarza93** [comment]
It seems like this should be called **live bars**? Is the idea to work on histogram later?

**Comment by swharden** [comment]
Hi @jpgarza93, I don't think I understand your question 😅

Is there additional functionality you're seeking?

This logic could be wrapped into a class called `LiveHistogram` which gets distributed with ScottPlot in the future, but the present solution is available immediately and is fully customizable by the user

**Comment by swharden** [comment]
Extending the previous comment, such a plottable would allow something like this:

```cs
ScottPlot.Statistics.Histogram hist = ScottPlot.Statistics.Histogram.WithBinCount(count: 50, minValue: 0, maxValue: 100);
ScottPlot.Plottables.HistogramPlot histPlot = new(hist);
formsPlot1.Plot.Add.Plottable(histPlot);
```

Creating that plot type and adding it to the plot could wire-up everything automatically by doing the same steps described in https://github.com/ScottPlot/ScottPlot/issues/4557#issuecomment-2496171043 allowing data updates like this:

```cs
histPlot.Add(newValue);
```

... but the effect would be identical to the screenshot above, and it's not obvious how much of an advantage that is. Perhaps it's less code for the user to write, making this worth pursuing?

I'm interested in your thoughts!

**Comment by jpgarza93** [comment]
I’ve been reviewing the live histogram demo from ScottPlot 4, and it seems to achieve dynamic updates by using the Histogram.Add method to modify the histogram data. Here’s the link to the relevant section in the demo:
[HistogramDemo.cs - Line 12](https://github.com/ScottPlot/ScottPlot/blob/e3e99adaa5b592904574778def2c361dd54d5f1c/src/ScottPlot4/ScottPlot.Demo/ScottPlot.Demo.WinForms/WinFormsDemos/HistogramDemo.cs#L12).

What I’m aiming for is functionality similar to ScottPlot 4, where the histogram manages both the counts and bins internally. My goal is to have a BarPlot (or similar visualization) automatically update whenever I add a new value to the histogram.

I hope this explanation makes my intentions clearer.

**Comment by swharden** [comment]
> where the histogram manages both the counts and bins internally

> I hope this explanation makes my intentions clearer

Thanks for clarifying! I'll give this a quick go and see if I can put a MVP into the next release I'll push out later today, then we can add features if/as needed 👍

**Comment by jpgarza93** [comment]
I was thinking that maybe all that would be needed is to have the BarsPlot accept lists as reference objects here:
```
Histogram = Histogram.WithBinSize(size, leftLimit, rightLimit);
AvaPlot.Plot.Add.Bars(Histogram.Bins, Histogram.Counts);
```

**Comment by swharden** [comment]
I'm merging #4561 which adds this new functionality. It's a bit ironic that after all this the user isn't saved much typing when it comes to setting this up... but it definitely takes care of the "what bin does this new value go in" logic 👍 


```cs
public partial class LiveHistogram : Form, IDemoWindow
{
    readonly System.Windows.Forms.Timer Timer = new() { Enabled = true, Interval = 20 };

    public LiveHistogram()
    {
        InitializeComponent();

        var histogram = Histogram.WithBinCount(count: 50, minValue: 0, maxValue: 100);
        var histogramPlot = formsPlot1.Plot.Add.Histogram(histogram);

        // simulate live incoming data
        Timer.Tick += (s, e) =>
        {
            int numberOfNewValues = Generate.RandomInteger(50, 100);
            for (int i = 0; i < numberOfNewValues; i++)
            {
                double randomValue = Generate.RandomNormalNumber(mean: 50, stdDev: 10);
                histogram.Add(randomValue);
            }

            formsPlot1.Plot.Title($"Total: {histogram.Counts.Sum():N0}");
            formsPlot1.Plot.Axes.AutoScale();
            formsPlot1.Refresh();
        };
    }
}
```


![LiveHistogram](https://github.com/user-attachments/assets/42adf530-507e-44df-9002-70fdadd1bf95)

**Comment by jpgarza93** [comment]
This amazing, thank you! 

Yes, i like this part "what bin does this new value go in" :)
