### ISSUE TITLE
Need a custom time format for Plot.Plot.Axes.DateTimeTicksBottom();

### ISSUE THREAD

**Issue by sensboston** [ScottPlot/ScottPlot#4568]
**Question:** I need to show on the bottom X axes time in format "HH:mm:ss.fff"; I don't need a date. I wanna use all advantages of already implemented DateTimeTicksBottom including proper showing on plot scaling.

**ScottPlot Version:** 5.0.47

**Code Sample:** Here is my current attempt to create a custom ticks but I don't like it; also, ticks forms a "black line" when plot scaled and lot of datapoints added :(

```cs
            var firstTimestamp = xData[0];
            var lastTimestamp = firstTimestamp + 1.0;
            var positions = new List<double>();
            var labels = new List<string>();
            for (var t = firstTimestamp; t <= lastTimestamp; t += (1.0 / 86400)) // 1 second = 1/86400 OLE Date
            {
                positions.Add(t);
                labels.Add(DateTime.FromOADate(t).ToString("HH:mm:ss"));
            }
            var tickGenerator = new NumericManual(positions.ToArray(), labels.ToArray());
            Plot.Plot.Axes.Bottom.TickGenerator = tickGenerator;

```

**Comment by StendProg** [comment]
Hi @sensboston 

Take a look at this example:
https://scottplot.net/cookbook/5.0/AxisAndTicks/DateTimeAxisCustomFormatter/

**Comment by sensboston** [comment]
I already tried but this method reduces performance dramatically. I'm displaying signals (at least trying to) every 20 ms.

**Comment by StendProg** [comment]
Maybe you're doing something wrong.
Formatting lines is not a quick operation, but it is not a matter of milliseconds on a modern computer.
I made a measurement, the time to call a handler that applies custom formatting of axis labels takes about 2 `microseconds` (in debug mode).

**Comment by sensboston** [comment]
>Maybe you're doing something wrong.

You're right, my bad: snippet below is working fine, no performance issues found. 

```
            Plot.Plot.RenderManager.RenderStarting += (s, e) =>
            {
                var ticks = Plot.Plot.Axes.Bottom.TickGenerator.Ticks;
                for (int i = 0; i < ticks.Length; i++)
                {
                    var dt = DateTime.FromOADate(ticks[i].Position);
                    ticks[i] = new Tick(ticks[i].Position, $"{dt:HH:mm:ss}");
                }
            };

```
BTW, I'm trying to visualize data structure **Values**:
```
    public double Value 
    {
        get => value;
        set
        {
            this.value = value;
            Values.Add((Timestamp: DateTime.Now.ToOADate(), Value: value));
            OnPropertyChanged(nameof(Value));
            OnPropertyChanged(nameof(Values));
            OnPropertyChanged(nameof(ValuesCount));
        }
    }

    public ObservableCollection<(double Timestamp, double Value)> Values { get; private set; }
        = new ObservableCollection<(double Timestamp, double Value)>();
 ```
 
 Is it possible to provide a real timestamp milliseconds (for the tick label) if plot zoomed enough (i.e. > TimeSpan(second)?

**Comment by sensboston** [comment]
BTW, I really love ScottPlot, and will ask my employer to make a good donation for the project! Thank you guys!

**Comment by sensboston** [comment]
@StendProg, JFYI:I left the app running overnight and collected about 1.5 million data points, after that it takes a long time to open the plot window, about 6-7 seconds. 😞 
BTW, I think, providing a datetime format string for the standard ```Plot.Axes.DateTimeTicksBottom();``` will be a really good feature.

P.S. Yes, I know: I should clone first, make a changes and issue a PR but first I wanna be sure you'll accept this feature and it's not against ScottPlot architecture. Or maybe you have a better solution?

**Comment by sensboston** [comment]
@StendProg , could you please suggest: how can I set density/frequency of bottom axes (X, time)?
Here's my code snippet from ViewModel that toggles between "Live" and "All data" modes:
```
        private void UpdateXAxisLimits()
        {
            if (isLiveMode)
            {
                double latestTime = xData.Count > 0 ? xData.Last() : DateTime.Now.ToOADate();
                double startTime = latestTime - (liveModeTimeSpan / (24 * 3600)); // Convert seconds to OADate
                Plot.Plot.Axes.SetLimitsX(left: startTime, right: latestTime);
            }
            else
            {
                Plot.Plot.Axes.AutoScaleX();    **// <= how can I ask to render, let's say, only 10 ticks from NumericManual ?**
            }
            Plot.Refresh();
        }
```

**Comment by StendProg** [comment]
If the only thing you're not happy with in the default label behavior is the date on the top line, you can simply remove it in the same handler:
```c#
 Plot.Plot.RenderManager.RenderStarting += (s, e) =>
            {
                var ticks = Plot.Plot.Axes.Bottom.TickGenerator.Ticks;
                for (int i = 0; i < ticks.Length; i++)
                {
                    int index = ticks[i].Label.IndexOf('\n');
                    if (index != -1)
                    {
                        ticks[i] = new Tick(ticks[i].Position, ticks[i].Label.Substring(index+1));
                    }
                }
            };
```

> @StendProg, JFYI:I left the app running overnight and collected about 1.5 million data points, after that it takes a long time to open the plot window, about 6-7 seconds. 😞

You are probably using `Scatter` plottable. yes those are big numbers for that. Try `Signal` or `SignalXY`, 1.5 million data points is a very small number for them.

**Comment by sensboston** [comment]
>You are probably using Scatter plottable.
Yes, I do. Thank you for advice! But could you please provide me a short snippet how to dynamically add data to SignalXY, and how to display timestamps on bottom (X) axe? 
I'm really sorry I'm really new to ScottPlot (I've used LiveCharts/Geared before but found ScottPlot is a way better)

**Comment by sensboston** [comment]
Thanks a lot for your help, I really appreciate this! Yeah, it looks a DataLogger fits my needs. But I do have a two more questions (sorry for my stupidity but ScottPlot is kinda complicated and sophisticated library):
- how should I format bottom (X) axe to display "HH:mm:ss.fff"
- how to make DataLogger scroll smoothly in the "live mode"?

I also have additional question about ability to display different signals (with the different Y axes) on the same plot, but I don't like mixing questions 😉

**Comment by sensboston** [comment]
I implemented a proper (I hope so!) formatting of bottom axe
```
        private void InitializePlot()
        {
            dataLogger = Plot.Plot.Add.DataLogger();

            // Add stored values
            foreach (var tuple in signal.Values) 
                dataLogger.Add(tuple.Timestamp, tuple.Value);

            Plot.Plot.Axes.Left.Label.Bold = false;
            Plot.Plot.Axes.Left.Label.FontSize = 12;
            Plot.Plot.Axes.Left.Label.Text = signal.Units;
            Plot.Plot.Axes.Left.TickLabelStyle.FontSize = 10;

            Plot.Plot.Axes.Bottom.Label.Bold = false;
            Plot.Plot.Axes.Bottom.Label.FontSize = 12;
            Plot.Plot.Axes.Bottom.Label.Text = "Time";
            Plot.Plot.Axes.Bottom.TickLabelStyle.FontSize = 10;


            // Set current DPI for the plot: this is important!
            Plot.Plot.ScaleFactor = Helper.GetDisplayScale();

            // Assign the custom tick generator to the bottom axis
            var customTickGenerator = new NumericAutomatic()
            {
                LabelFormatter = position =>
                {
                    var timestamp = unixEpoch.AddSeconds(position);
                    return timestamp.ToString("HH:mm:ss.fff");
                }
            };
            Plot.Plot.Axes.Bottom.TickGenerator = customTickGenerator;
        }
```
but can not get plot scrolling in the "live mode" - don't really understand "why"? 😢 

Here is my code:
```
        private void UpdateXAxisLimits()
        {
            if (IsLiveMode)
            {
                double endTimestamp = dataLogger.Data.Coordinates[dataLogger.Data.Coordinates.Count - 1].X;
                // LiveModeTimeSpan is double and equal number of seconds
                double startTimeStamp = endTimestamp - (LiveModeTimeSpan / 86400.0);
                Plot.Plot.Axes.SetLimitsX(startTimeStamp, endTimestamp);
            }
            else
            {
                // Auto-scale the X-axis
                Plot.Plot.Axes.AutoScaleX();
            }
            Plot.Refresh();
        }
```

As far as I understand ScottPlot sources, it should scroll data in the window.

**Comment by StendProg** [comment]
>but can not get plot scrolling in the "live mode" - don't really understand "why"? 😢

By default, `DataLogger` handles the X-axis scale control itself. And contains several handy strategies.
In particular, sliding the window to the last point can be implemented by a single call during initialization:
```c#
if (IsLiveMode)
{
      dataLogger.ViewSlide(LiveModeTimeSpan / 86400.0);
}
else
{
      // Auto-scale the X-axis
      dataLogger.ViewFull();
}
```
You will only need to call this method once when you actually switch mode.


If you still want to implement your control, you just need to disable axis control:
```c#

dataLogger.ManageAxisLimits = false;
```

**Comment by StendProg** [comment]
> Also could you please point me to the demo showing how to add many signals with the different Y scales (different units) to the same plot?

https://scottplot.net/cookbook/5.0/MultiAxis/

> P.S. I don't know, will my employer donate to Scott, but I wanna say a BIG THANKS! to you for your help and patience, and issue a small donation directly to you: could you provide your PayPal - to buy some sixpack of the good beer this "Turkey Day 🦃"
Happy Thanksgiving! 😄

The usual thank you is more than enough. In fact, I'm exploring the library with you and have learned something useful for myself in the process of this discussion.

If you still have a persistent desire to get someone drunk, then address it to @swharden. His contribution is disproportionately greater.

**Comment by sensboston** [comment]
Thanks a lot!

P.S. Just donated $20: https://checkout.square.site/merchant/VBDXTFSBK657Z/checkout/2BDNQMBGZGPAQRGFYHTDK6IP
