### ISSUE TITLE
AvaloniaUI use cannot set X-axis foreground

### ISSUE THREAD

**Issue by MarkManYUN** [ScottPlot/ScottPlot#4576]
**Question:** (For some reason, I can't set the X-axis foreground color when using AvaloniaUI, but can I set the Y-axis foreground color with style.AxisColor)

**ScottPlot Version:** (ScottPlot.Avalonia 5.0.40)

**Code Sample:** See http://scottplot.net/faq/repro/ for tips about creating reproducible code samples

```cs
   style.LegendBackgroundColor = style.FigureBackgroundColor = style.DataBackgroundColor = new ScottPlot.Color($"#FFFFFF");

   style.AxisColor = style.LegendOutlineColor= style.GridMajorLineColor = style.LegendFontColor = new ScottPlot.Color($"#000000");
```

**Comment by swharden** [comment]
Hi @MarkManYUN, thanks for reporting this!

I noticed you're several versions behind the current version of ScottPlot. Do you know if this issue remains present in the current version?

Thanks for the feedback!

**Comment by swharden** [comment]
No worries! I'm on mobile so I'll be brief but I think you may be able to find what you're looking for here

https://scottplot.net/cookbook/5.0/Styling/

**Comment by MarkManYUN** [comment]
Is it different on WPF than on Avalonia,
``` C#
   var myPlot = plot.Plot;

    // change figure colors
    myPlot.FigureBackground.Color = new ScottPlot.Color("#000000");
    myPlot.DataBackground.Color = new ScottPlot.Color("#1f1f1f");
    // change axis and grid colors
    myPlot.Axes.Color(new ScottPlot.Color("#FF0000"));
    myPlot.Grid.MajorLineColor = new ScottPlot.Color("#404040");

    // change legend colors
    myPlot.Legend.BackgroundColor = new ScottPlot.Color("#404040");
    myPlot.Legend.FontColor = new ScottPlot.Color("#d7d7d7");
    myPlot.Legend.OutlineColor = new ScottPlot.Color("#d7d7d7");

```
The link you gave is the WPF way, I set the corresponding `Axes.Color` according to the example given, but unfortunately it is still the same as before,As shown in the figure.
![Snipaste_2024-11-28_11-40-26](https://github.com/user-attachments/assets/6146ba88-57da-471a-b2a1-80dd2dd760aa)

**Comment by MarkManYUN** [comment]
Try to write a ` Bottom. MajorTickStyle. Color `, still unable to change the Horizontal scale of the default black, In addition, before writing 'myplo.axes.Color(new ScottPlot.Color("#000000"))' is only the Vertical ruler effective, and then wrote the following code to try, but still can not see the effect.
''' C#
    myPlot.Axes.Bottom.MajorTickStyle.Length = 10;
    myPlot.Axes.Bottom.MajorTickStyle.Width = 3;
    myPlot.Axes.Bottom.MajorTickStyle.Color = new ScottPlot.Color("#FF0000");
    myPlot.Axes.Bottom.MinorTickStyle.Length = 5;
    myPlot.Axes.Bottom.MinorTickStyle.Width = 0.5f;
    myPlot.Axes.Bottom.MinorTickStyle.Color = new ScottPlot.Color("#FF0000");
    myPlot.Axes.Bottom.FrameLineStyle.Color = new ScottPlot.Color("#FF0000");
    myPlot.Axes.Bottom.FrameLineStyle.Width = 3;
'''

**Comment by MarkManYUN** [comment]
God, it's amazing, I can change the place, maybe this code has written the Settings at the back, so the previous Settings are invalid
