### ISSUE TITLE
DateTime Axis disappears with custom colors

### ISSUE THREAD

**Issue by mzemljak** [ScottPlot/ScottPlot#4619]
**Issue:** When using DateTimeTicksBottom() with custom Axes.Color() the bottom axis disappears. I'm using the code from https://scottplot.net/cookbook/5.0/DateTimeAxes/DateTimeAxisQuickstart/

Without custom colors:
![image](https://github.com/user-attachments/assets/89bd1b92-74b8-4e4f-b40c-8c47a4c780f2)

With custom colors:
![image](https://github.com/user-attachments/assets/d83dded4-a088-45b9-86d5-4bcbc482b9ea)

With custom colors without DateTimeTicksBottom():
![image](https://github.com/user-attachments/assets/1d4c8f80-cc98-48fd-b69e-364a7f67e416)

**ScottPlot Version:** 5.0.47, Windows 11, .NET Framework 4.8

```cs
  chartPlot.Plot.Add.Palette = new ScottPlot.Palettes.Penumbra();

  //// change figure colors
  chartPlot.Plot.FigureBackground.Color = ScottPlot.Color.FromHex("#000000");
  chartPlot.Plot.DataBackground.Color = ScottPlot.Color.FromHex("#1f1f1f");

  //// change axis and grid colors
  chartPlot.Plot.Axes.Color(ScottPlot.Color.FromHex("#d7d7d7"));
  chartPlot.Plot.Grid.MajorLineColor = ScottPlot.Color.FromHex("#404040");

  DateTime[] dates = ScottPlot.Generate.ConsecutiveDays(100);
  double[] ys = ScottPlot.Generate.RandomWalk(100);
  chartPlot.Plot.Add.Scatter(dates, ys);

  chartPlot.Plot.Axes.DateTimeTicksBottom();
  chartPlot.Plot.Axes.Bottom.MinimumSize = 50;

  chartPlot.Refresh();
```

**Comment by StendProg** [comment]
Hi @mzemljak,

`DateTimeTicksBottom()` actually removes an existing axis and adds a new one. Therefore, all your styling changes are gone.

A simple solution is to adjust the styles after switching the axis to DateTime.
