### ISSUE TITLE
Refactor all controls to use a common back-end

### ISSUE THREAD

**Issue by Benny121221** [ScottPlot/ScottPlot#637]
**What can we do to make ScottPlot better?**
This was originally the intention, however, when the Avalonia module was created for 4.0.39 it was decided that it would be annoying to bump the package version of the rest of ScottPlot. This change would make a move to supporting another platform easier (or indeed updating the WPF and WinForms controls to use `ControlBackend` which would help in maintainability). I think I said I would backport `ControlBackend` to WPF and WinForms when I first created the Avalonia control, 4 months ago.........

The [ScottPlot Roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) may provide additional context regarding current goals and future directions.

**Comment by swharden** [comment]
Hey @Benny121221! 

**A central control backend is still the plan/goal,** but I don't think right now is the best time to be refactoring the controls. The core library is being deeply refactored daily (#578), and I'm devoting all my free time right now to getting the core library stabilized and documented (#572). After that settles down I'll focus my free time to refining the controls, including refactoring toward a central backend that lives in the `ScottPlot` namespace (probably using your [ScottPlot.Avalonia/ControlBackend.cs](https://github.com/swharden/ScottPlot/blob/master/src/controls/ScottPlot.Avalonia/ControlBackend.cs) as a starting point). 

**Advantages of a central control backend are:** it allows controls to be as thin as possible, greatly reduces code duplication across the controls, makes it easy to implement controls for new frameworks (WinUI and MAUI are on the horizon), and makes it easier to test GUI functionality with traditional unit tests.

**My immediate next steps** are refining and documenting multi-axis support, and refactoring the website and documentation away from huge single-page cookbooks toward multi-page, version-specific, auto-generated documentation pages (#572). I'd also like to get most of the website content (minus images) back into source control ([/dev/website](https://github.com/swharden/ScottPlot/tree/master/dev/website)). I think after that would be a good time to start devoting primary focus toward refactoring the controls. I'll update the roadmap soon to reflect this (I recognize it's fallen behind).

**I have two questions that may be worth exploring before refactoring the controls.** If we decide to make a large-scale change to how user controls display plots, it may be good to make the change at the same time we refactor to use a common backend. Those questions are:

* **Can rendering in controls be non-blocking?** It would be excellent if calls to the control's `Render()` method didn't block the UI thread, especially now that we have `plt.RenderLock()` to allow plot manipulation in one thread and UI rendering in another (#609). I started exploring this in [FormsPlotExperimental.cs](https://github.com/swharden/ScottPlot/blob/master/src/controls/ScottPlot.WinForms/FormsPlotExperimental.cs) but shelved that effort to try to get #578 and #572 complete, although I'm interested in figuring this out.

* **Should we manually implement double-buffer rendering?** The creation of Bitmaps is a bit costly. Bitmaps only need to be created when controls are resized, and they could be re-used except that actively drawing on a bitmap gives the appearance of flickering if the screen draws it before a render is complete. A double-buffer rendering system may also be worth exploring: show one bitmap while another one is being drawn on (perhaps in another thread), then switch them after the render completes.

I hope this gives some more context as to the state of the common control backend, where my effort has been going, where I want to devote near-term effort, and what control-related features I'm interested in exploring when I start working on those again. I'm interested to hear your thoughts!

**Comment by swharden** [comment]
> I don't think right now is the best time to be refactoring the controls

I wanted to clarify that I meant it's not a good time _for me_ to be refactoring the controls because I'm largely focused on tasks related to the core library right now. However, the majority of the refactoring that affects the controls is already complete, so if you wanted to have a go at implementing the backend in the WinForms or WPF controls, or exploring some of the advanced control topics listed above, that work could be done in parallel. If not, I'll get around to it eventually, as it's still a strong goal.

I'll go ahead and move `ScottPlot.Avalonia.ControlBackend` to `ScottPlot.Interactive.ControlBackend` (as suggested by your original title) this evening since it makes sense to have that in the primary namespace as it is right now, and it'll be available for challenge by unit tests when the time is right to create those.

**Comment by Benny121221** [comment]
> I don't think right now is the best time to be refactoring the controls.

Fair enough. I wasn't actually suggesting refactoring the WPF or WinForms controls (yet), I'm just thinking of moving the `ControlBackend` from the Avalonia project to the ScottPlot project. Conveniently, just moving the file shouldn't break anything as it's already been moved once (when it was moved to the Avalonia project to prevent having to bump the version).

As for your two questions:

> Can rendering in controls be non-blocking?

I agree this is probably an important goal for the controls. There is perhaps benefit to not making `ControlBackend` part of the main ScottPlot project until this is done as this would necessitate a breaking change.

> Should we manually implement double-buffer rendering?

I could see it being beneficial, I don't know how big the overhead is from creating a new bitmap each time is but I expect it's large given bitmaps take up a fair amount of memory (which in GDI I believe is initialized to white pixels even though in our use case it's going to be filled with whatever the background colour is anyways).

**Warning, I started rambling. I though this was interesting but likely a bad idea.**

> Bitmaps only need to be created when controls are resized

This too, could perhaps be avoided, one could create 2 large bitmaps as buffers. It would probably make sense to make them the size of the largest connected screen, but for argument's sake lets say they're 5000x5000. Since this bitmap is large enough to store any size the window is likely to take up you never need to create more bitmaps. And, if the window stays small you don't have to update most of the bitmap. This does ignore the fact that a user can resize a window to be larger than their screen but there are ways to handle that, such as making it start bigger or resizing it in this event.

Now, this solution is memory inefficient, for my example with a 5000x5000 screen the bitmaps use up 75 megabytes each (not including the bitmap headers, although technically you only need those once if you don't mind fun with pointer trickery, as the headers should be identical for any 5000x5000 bitmap on the same platform). It's also liable to be a lot of work to get going on each platform, as you'll have to trim each bitmap differently for each one. And even more fun, there's a chance that a platform won't have optimized their image rendering particularly well and it may decide to draw (or God forbid copy) the whole 5000x5000 image on every UI update even if the user only sees a 600x400 rectangle.

So, while it's possible, it creates more work on each platform and there could well be platforms on which it makes things worse. It might be worth the effort if ScottPlot supported one platform which handled large cropped images well and if performance was a major concern, but as it is now performance is pretty good even creating a new bitmap on every render. While technically you can minimize it to 2 bitmaps (or 1 of double size) for the lifetime of the plotting control the actual benefit of that is wholly dependent on the platform, which is unlike the case where a new bitmap is only created on resize.

**Comment by swharden** [comment]
### Control Backend Next Moves

> I'm just thinking of moving the ControlBackend from the Avalonia project to the ScottPlot project

I suspect you wrote this before I posted https://github.com/swharden/ScottPlot/issues/637#issuecomment-735963270, but I agree! I plan to do this tonight.

> There is perhaps benefit to not making ControlBackend part of the main ScottPlot project until this is done as this would necessitate a breaking change

Perhaps we could keep the `ControlBackend` that works, and we can keep the `WpfPlot` and `FormsPlot` controls as they are because they all work too. Experimentation could be done in `ControlBackendExperimental`, `FormsPlotExperimental`, etc. This way everything that currently works would keep working while we experiment with these ideas. When ScottPlot 4.1 gets out of pre-release we can delete the old ones and rename the new ones.

It may be unexpectedly easy to create new experimental controls to use the experimental backend, as those controls would be very thin and wouldn't be much effort to maintain along the way as the backend is experimented on.

### Displaying cropped giant plots

This is an interesting idea! It does take a lot of memory though (I'm recalling someone wanted to show 100s of plots #257). Right now (as of ScottPlot 4.1) a new Bitmap is created every time `Render()` is called. How long this actually takes may be worth benchmarking. My thought is that limiting creation of new bitmaps to `Resize()` events would be a big win because that's a rare event. Your suggestion (display a portion of a huge bitmap) would eliminate even that step, but my lean is to consider resizes a rare event so probably not worth optimizing for at this time. Plus if we optimized for 5000px then someone with an 8K monitor will complain shortly after 😆

**Comment by erichiller** [comment]
> * **Can rendering in controls be non-blocking?** It would be excellent if calls to the control's `Render()` method didn't block the UI thread, especially now that we have `plt.RenderLock()` to allow plot manipulation in one thread and UI rendering in another (#609). I started exploring this in [FormsPlotExperimental.cs](https://github.com/swharden/ScottPlot/blob/master/src/controls/ScottPlot.WinForms/FormsPlotExperimental.cs) but shelved that effort to try to get #578 and #572 complete, although I'm interested in figuring this out.
 
Hi guys,
For non-blocking renders I [recently modified the Avalonia control](https://github.com/erichiller/ScottPlot/commit/4f3f1b90f61d52337ba61633b049ed1865b29a52) to render the bitmap in a new `Task`. I might be totally off the direction you were thinking, but if it would be useful, I'm very happy to contribute. I had to do this because the Avalonia control was extremely slow on Linux (_only issues with Linux_, on Windows it performed beautifully).  

I then exposed the same `skipIfCurrentlyRendering` param on Avalonia's `Render` as WPF.

**Comment by Benny121221** [comment]
Hello @erichiller, thank you for your work, I made a couple comments on the linked commit, and I think your changes are a good start.

As for these issues on Linux, I haven't had any myself, so I'm slightly puzzled. It's possible GDI isn't using hardware acceleration on Linux due to some driver trickery? Or if you're running in a VM that often takes a toll.

**Comment by Benny121221** [comment]
By the issues on Linux do you mean sluggish feeling input? I've found this on VMs and WSL (through a custom window server). I have an old desktop running Linux and it doesn't have this problem.

I suspect it could be avoided by rendering less often when dragging so it can catch up. Perhaps Linux fires mouse move events more often or something and a VM cannot keep up.

**Comment by erichiller** [comment]
I'm out of town and brought a laptop but I didn't have any spare Windows licenses - so I quickly installed Ubuntu 20.10, normally I use Windows for desktop things.

> Perhaps Linux fires mouse move events more often or something and a VM cannot keep up.

I was thinking the same, that Linux might be sending more mouse move events, but I don't have a Windows machine ATM to confirm this (next week I will).

The call to `bmp.Save()` inside `BmpImageFromBmp` was taking ~32ms per call, I'm not sure if that's the same as Windows or not. If it is the same, then the suspicion that Linux is sending more mouse move events than Linux seems likely.

Thank you for the comments, I will definitely go through and try the changes as soon as I'm back to my actual machine mid-next-week.

**Comment by swharden** [comment]
I created a project in /dev to test implementation ideas and I think I came-up with an event-driven that works well, but I'm open to thoughts and suggestions

![control](https://user-images.githubusercontent.com/4165489/102724061-b7ddc400-42da-11eb-9a13-2e7648da9302.gif)

The whole WinForms control is small enough to fit on a screen:
https://github.com/swharden/ScottPlot/blob/eea040937a88c33b925ef6408af29e5f24c00166/dev/ControlBackEndDev/SPControl.cs#L6-L39

Some features aren't implemented yet (e.g., interaction with draggable objects), but you can get an idea of where this design is going...

**Comment by swharden** [comment]
I finished this refactor. The user controls are now pretty short:

* **WPF:** https://github.com/ScottPlot/ScottPlot/blob/master/src/controls/ScottPlot.WPF/WpfPlot.xaml.cs
* **WinForms:** https://github.com/ScottPlot/ScottPlot/blob/master/src/controls/ScottPlot.WinForms/FormsPlot.cs
* **Avalonia:** not refactored yet... @Benny121221 do you want to try this or do you want me to? It should be relatively straightforward either way.

Notable changes:
* Control logic is handled by a back-end: [ScottPlot/Control/Backend.cs](https://github.com/ScottPlot/ScottPlot/blob/master/src/ScottPlot/Control/Backend.cs)
* All configuration is achieved by modifying `FormsPlot.Configuration` and `WpfPlot.Configuration`
* The right-click menu plot editor has been removed from the WinForms control
* `Render()` is called automatically when the number of plottables changes (so it rarely needs to be called manually). This functionality can be disabled `Configuration.RenderIfPlottableCountChanges`, and I'm undecided whether to enable this by default or not.

**Comment by Benny121221** [comment]
I'm happy to work on it in the coming days. I would be interested in adding the changes @erichiller made. His fork is on the same license so as I understand it we're free to yoink his modifications. Plus it seems he intended to commit the changes himself anyways.
