### ISSUE TITLE
Do not display hidden plottables in legend

### ISSUE THREAD

**Issue by liang16** [ScottPlot/ScottPlot#688]
Like `ScottPlot.Demo.WPF.WpfDemos.ToggleVisibility`，Could hide the legend？

**Comment by swharden** [comment]
Hi liang16, thanks for a suggestion! I will do this.

note to self: edit this line so only visible plottables are obtained
https://github.com/swharden/ScottPlot/blob/6e9a9ac35254210636be16abecff4ad147f8370e/src/ScottPlot/Plot/Plot.Render.cs#L88

**Comment by swharden** [comment]
I just fixed it and will post a new (pre-release beta) package on NuGet this weekend. Thanks @liang16!
