### ISSUE TITLE
Any xaml example please?

### ISSUE THREAD

**Issue by GF-Huang** [ScottPlot/ScottPlot#689]
![image](https://user-images.githubusercontent.com/4510984/103856575-d53eca80-50ef-11eb-8b9c-81d95e6fef0c.png)

**Comment by StendProg** [comment]
Hi @GF-Huang,
You can check https://github.com/swharden/ScottPlot/blob/master/src/demo/ScottPlot.Demo.Avalonia/CookbookControl.axaml,
I think you need this line:
https://github.com/swharden/ScottPlot/blob/6e9a9ac35254210636be16abecff4ad147f8370e/src/demo/ScottPlot.Demo.Avalonia/CookbookControl.axaml#L5

You will find more examples in https://github.com/swharden/ScottPlot/tree/master/src/demo/ScottPlot.Demo.Avalonia folder.
