### ISSUE TITLE
Tag property is necessary for a plot

### ISSUE THREAD

**Issue by Sedighzade** [ScottPlot/ScottPlot#694]
Add a Tag property to the IPlottable interface.

**Comment by swharden** [comment]
Hi @Sedighzade, 

Thanks for the suggestion! Unfortunately I don't fully understand the goal or use case for this. Can you provide a code example and better describe what you'd like to be able to do if a tag property were added? Thanks!

For reference, here's the current `IPlottable` interface:
https://github.com/ScottPlot/ScottPlot/blob/6e9a9ac35254210636be16abecff4ad147f8370e/src/ScottPlot/Plottable/IPlottable.cs#L3-L29

**Comment by Sedighzade** [comment]
There are cases it is beneficial to attach an extra data to a plot.


```
SignalPlot sp = plt.AddSignal(y);
sp.Tag = myData;
```

**Comment by LogDogg** [comment]
I believe ZedGraph also has this functionality. The property is of type "object" and is not used by the library itself, it's purely for the user. I agree that it would be a useful addition.

**Comment by swharden** [comment]
Thanks for the clarification! The addition would simply be:

```cs
public object Tag { get; set; }
```

I'll explore this idea by adding a demo that shows how to use a `CheckedListbox` to control visibility of individual plot components in a single `FormsPlot` control

**Comment by Benny121221** [comment]
I think I have a potentially more elegant implementation:

Create a generic decorator class which implements IPlottable, something like `TaggedPlottable<T>`. The generic means you don't have to continuously cast to and from `object`. And the decorator means that it only has to be written once.

The only issue with decorators is that because it changes the type it does change the behaviour of code like this: https://github.com/Benny121221/WPlot/blob/master/MainWindow.xaml.cs#L388L399

This is the same issue that prompted #553 to move away from decorators, however I think it's ok in this instance because the user *knows* that they're creating a different type of plottable, so they're bringing any such issues on themself. Whereas with diagnostic mode it happened whenever a certain setting was enabled, which is pretty abstract causality.

**Comment by Benny121221** [comment]
In addition to the implementation details, I'm curious what you intend to store in this tag? When I think of a tag on a plot I think of a tooltip like this:

![image](https://user-images.githubusercontent.com/8635304/104531951-67e9d880-55cc-11eb-8f00-f17cae983253.png)

This is from plotlyjs in case you're curious. The project is https://github.com/Benny121221/WFinance

Is this the sort of tag you're looking for (but with arbitrary data, not necessarily stock related)? Or do you want something more general? I think if you want the latter it might make sense to add the former _anyways_, and then see what we can do about the latter.

Perhaps a tooltip renderable would also be a good plan. I know I'm rambling and this comment is jumping place to place, but I do like the idea of adding an `ITooltippable` which has a method `GetTooltip`, which allows a function to generate a tooltip. This means simple tooltips that simply show the value on hover don't need extra memory, they already have the value.

That was a lot of ideas, I'm not sure how many of them fit nicely in the API, and I'm not even sure that tooltips were the intended usecase.

**Comment by Sedighzade** [comment]
> 
> 
> In addition to the implementation details, I'm curious what you intend to store in this tag? When I think of a tag on a plot I think of a tooltip like this:

My main motivation is to attached business objects ( fetched from a data store ) to the plot, specially when you have multiple trends/plots. Suppose the user has seen a trend and now decides to print the data in a tabular format ( e.g. Excel ). This way you have to go back and fetch the data again from the datastore which is not a good idea in any manner.

**Comment by Benny121221** [comment]
Interesting, I wonder if you'd better be served by creating a class to hold both your tag and your plottable? I think it's confusing for plottables to be holding arbitrary state which may or may not have anything to do with plotting.

**Comment by swharden** [comment]
This is essentially the same topic as #695, so I'll close this issue and work on both controls (listbox and checked listbox) in that issue
