### ISSUE TITLE
What is the best way to add plottables to listboxes?

### ISSUE THREAD

**Issue by Sedighzade** [ScottPlot/ScottPlot#695]
Each plot should have a Name property and the ToString method overrided to return that Name. This way, a plot can be added to list controls directly.
This is specially needed When we want to toggle visibility for multiple plots. Each plot can be added to a CheckedListbox/Listview directly

**Comment by swharden** [comment]
Thanks for the suggestion @Sedighzade! I'll look into this after merging #683.

I'll explore this idea by adding a demo that shows how to use a `CheckedListbox` and `ListView` to control visibility of multiple `FormsPlot` controls.

**Comment by Sedighzade** [comment]
I just added a Name property to the SignalPlot class. 
This is my code I'm using now:


                for (int i = 0; i < ys.GetLength(0); i++)
                {
                    double[] y = ys[i];
                    SignalPlot sp = plt.AddSignal(y);
                    sp.Name = yLable[i];

                    if (i > 1)
                    {
                        var yAxis3 = plt.AddAxis(ScottPlot.Renderable.Edge.Left, i + 2);
                        yAxis3.Label(yLable[i]);
                    }
                    else
                        plt.YAxis.Label(yLable[i]);

                    int index = checkedListBox1.Items.Add(sp);
                    checkedListBox1.SetItemChecked(index, true);
                }
                Plot1.Reset(plt);
                Plot1.Render();

**Comment by Benny121221** [comment]
I like this idea. May I suggest that if no name is specified the name is still guaranteed to be distinct?

i.e. don't simply set it to null or an empty string, but a unique identifier. This could be using [`System.Guid`](https://docs.microsoft.com/en-us/dotnet/api/system.guid?view=net-5.0#methods).

GUIDs have a benefit over just counting up in case someone creates two plottables at the same time in separate threads, with a simple counter those two plottables could have the same ID. The other benefits of GUIDs are mostly related to security, and I don't think they're likely to apply to ScottPlot.

**Comment by Benny121221** [comment]
Hmmm, this gets confusing with the presence of the `Label` property in many of the plottables.

Perhaps we shouldn't muddy the waters, and instead give each plottable an automatically assigned ID.

**Comment by Benny121221** [comment]
I added this ID property in https://github.com/Benny121221/ScottPlot/tree/plottable-id but in the middle of writing it, I noticed that I can't seem to see any benefit to maintaining a list of IDs over maintaining a list of references to plottables.

For what it's worth, I implemented checkbox-based visibility for WPFPlots in https://github.com/Benny121221/ACTelemetry.

I think the `Label` property already serves the function of a name and I think maintaining references already serves the function of maintaining IDs.

Perhaps `Label` should be added to the `IPlottable` interface? It was strange for me to learn that it isn't there, and it would allow people to rely on it being there for an arbitrary `IPlottable`.

**Comment by Sedighzade** [comment]
Well, I don't think so. Title can be very long but name can be very short and descriptive. We can reference Winforms controls here. All controls have Name and Text property at the same time.

**Comment by Sedighzade** [comment]
> I think the Label property already serves the function of a name and I think maintaining references already serves the function of maintaining IDs.

Well, I don't think so. `Label` can be very long but `Name` can be very short and descriptive. We can reference to Winforms controls here. All text controls have Name and Text property at the same time.

> Perhaps Label should be added to the IPlottable interface? It was strange for me to learn that it isn't there, and it would allow people to rely on it being there for an arbitrary IPlottable.

Do all plottables have `Label`? Again, I don't think so. All could have a Name.

**Comment by swharden** [comment]
Hey @Sedighzade and @Benny121221, I see in #704 a `string Label {get; set;}` has been added to `IPlottable`.

What do you think if we change the name to `ID` so its less likely to get confused with "labels" which is the text that many plottables have that appears in the legend?

Also, what about seeding this property with a random value so they're all unique by default?
```cs
public string ID { get; set; } = Guid.NewGuid().ToString();
```

**Comment by Benny121221** [comment]
@swharden The `Label` property in that PR is the same label field that was already on several plottables, the PR simply added it to all `IPlottable`

**Comment by swharden** [comment]
### Storing business objects inside classes of a third party library 

The fundamental topic here is that @Sedighzade pointed-out there's not a great way to add a bunch of plots to a checked listbox. This topic is similar to #694. Much of the discussion is about how to solve this problem, but at its core I think that's the problem. I've been futzing with checked listboxes in WinForms for the last hour, and I agree I haven't found a great way to do this. Even if we fix this issue by adding a `Label` everywhere, there's still a problem of render events not being triggered when checkboxes change. In WinForms, two-way binding is a big problem too.

Agreeing with https://github.com/ScottPlot/ScottPlot/issues/694#issuecomment-760392770, it seems very surprising for users to want to store their application specific business logic objects _inside_ objects of a third party library. This is what @Sedighzade is trying to do (https://github.com/ScottPlot/ScottPlot/issues/694#issuecomment-759724197). It seems like that's inviting deep coupling with a third party library, and doesn't strike me as the best approach to solve this problem... but I know this is a common practice for WinForms tags, and @LogDogg said (https://github.com/ScottPlot/ScottPlot/issues/694#issuecomment-759728778) that ZedGraph even encourages users store their own objects inside of ZedGraph classes. I find this very surprising, and definitely need to research the topic more.

### A checked listbox demo is needed
I think the next step should be for me to create a demo application that connects a checked listbox with a FormsPlot, then we can look closer at the different techniques to wire the two together. All options are on the table (from adding `object Tag` to every plottable to using a custom class holding `string Name`, `bool IsChecked`, and `IPlottable Plottable`). When we look at all the options side by side, it may be easier to decide which is the best approach.

**Comment by swharden** [comment]
What about this for a solution? The basic idea is pretty much what @Benny121221 said in https://github.com/ScottPlot/ScottPlot/issues/694#issuecomment-760392770 demonstrated in code. It uses the 4.1-beta API (which is in preview), but the idea is the same as ScottPlot 4.0.

@Sedighzade are there any limitations or drawbacks to this approach for your use case?

```cs
public class CheckedPlottable
{
    public string Name;
    public bool IsChecked;
    public IPlottable Plottable;
    public override string ToString() => Name;
}
```

```cs
using System;
using System.Windows.Forms;
using ScottPlot;
using ScottPlot.Plottable;

namespace WinFormsFrameworkApp
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            Random Rand = new Random();
            for (int i = 0; i < 10; i++)
            {
                double[] prices = DataGen.RandomWalk(Rand, 100, 10, Rand.Next(100, 200));
                var cp = new CheckedPlottable()
                {
                    Name = $"Stock {i + 1}",
                    IsChecked = true,
                    Plottable = formsPlot1.Plot.AddSignal(prices)
                };
                checkedListBox1.Items.Add(cp, cp.IsChecked);
            }
            formsPlot1.Plot.AxisAuto();
            formsPlot1.Render();
        }

        private void checkedListBox1_ItemCheck(object sender, ItemCheckEventArgs e)
        {
            CheckedPlottable cp = (CheckedPlottable)checkedListBox1.Items[e.Index];
            cp.Plottable.IsVisible = e.NewValue == CheckState.Checked;
            formsPlot1.Render();
        }
    }
}
```

![checked-listbox](https://user-images.githubusercontent.com/4165489/105568158-46dc6280-5d05-11eb-8ca0-837256edce27.gif)
