### ISSUE TITLE
Cookbook source code does not appear when running from source (solution: run tests first)

### ISSUE THREAD

**Issue by saklanmazozgur** [ScottPlot/ScottPlot#697]
I'm running the wpf demo version. In the Source Code field shown as an example, "Could not locate cookbook source code. Run tests to generate it." he is writing.

How can I solve this problem. I did not understand what to run.

Can you help me ? Thank you

**Comment by Benny121221** [comment]
Are you compiling and running from source? If so you can get the source like this:

**Visual Studio:**
1. Click Test > Test Explorer

![image](https://user-images.githubusercontent.com/8635304/104751899-3891b380-5713-11eb-9b00-28dd7c3badb6.png)

2. Click the circled button (Run all tests):

![image](https://user-images.githubusercontent.com/8635304/104752046-67a82500-5713-11eb-8fee-f6e8336d3ea9.png)

**Other IDEs (Windows):**

You can try to get a NUnit-Console 3.12 beta working. 3.11.0 will not work on dotnet-core projects. I wasn't able to get it working unfortunately :/

**Downloading the compiled demo:**

1. Download and extract the demos from here: https://swharden.com/scottplot/demo
2. If any of the source for a demo is unavailable please let me know.

**Comment by saklanmazozgur** [comment]
Thank you so much. Works.

**Comment by saklanmazozgur** [comment]
Hello, the code view issue has been resolved, but I am getting an error writing that I want to add a Colorbar. 

I am getting a missing reference warning. `using ScootPlot;` attached.

I added 4.0.48 version of Nuget packages to my project.

`var plt = new ScottPlot.Plot(600, 400);`

There are not many functions in the plt object.

**Comment by Benny121221** [comment]
I don't believe `Colorbar` is in 4.0.x, if you want to use that plottable you have to use 4.1.3-beta or later. Sorry for the inconvenience.

**Comment by saklanmazozgur** [comment]
I installed version 4.1.3. There is no problem with the setup. But the following piece of code I wrote in version 4.0.48 doesn't work and I don't understand the reason.

`HpsvAxisX_Graphic.plt.Ticks(dateTimeX: true, dateTimeFormatStringX: ("HH.mm.ss"));`


I am getting such a warning. How can I solve the problem.

`Plot.Ticks(bool?, bool?, bool?, bool?, bool?, bool?, Color?, bool?, bool?, bool?, bool?, bool?, bool?, bool?, bool?, bool?, string, float?, float?, bool?, bool?, string, string, bool?, int?, int?, string, string, string, string)' is obsolete: 'Individual axes (e.g., XAxis and YAxis) have their own tick configuration methods`

**Comment by Benny121221** [comment]
Ah a lot of breaking changes were made, I don't know exactly where but that same functionality will exist in another method.

For testing you can use `#pragma warning disable 612,618` to disable the warning.

**Comment by Benny121221** [comment]
It looks like it should be `HpsvAxisX_Graphic.plt.XAxis.TickLabelFormat("HH.mm.ss", true)`, although I haven't tested it so I could be mistaken.

**Comment by saklanmazozgur** [comment]
Thank you the code is working.

**Comment by swharden** [comment]
I put @Benny121221's advice in a more descriptive error message so hopefully this will be easier to figure out in the future 👍 

![image](https://user-images.githubusercontent.com/4165489/105640444-223ed280-5e4c-11eb-822e-3e95a0c2be43.png)

**Comment by saklanmazozgur** [comment]
Thank you for your time and attention.
