### ISSUE TITLE
wpfPlot2.Configuration.AxesChangedEventEnabled

### ISSUE THREAD

**Issue by KlaskSkovby** [ScottPlot/ScottPlot#712]
So i'm doing this WPF app where i have two plots next to eachother. I wanna link the axis of the two plots. 
I downloaded the sourcescode to check out how the linked plot demo was coded.

However i do not have the same options as the demo project
like .Configuration and .Plot
            wpfPlot2.Configuration.AxesChangedEventEnabled = false; // disable this to prevent an infinite loop
            wpfPlot2.Plot.SetAxisLimits(wpfPlot1.Plot.GetAxisLimits());
            wpfPlot2.Render();
            wpfPlot2.Configuration.AxesChangedEventEnabled = true;

My xml code:
<WpfPlot Name="plotWindow" Margin="586,0,-1,0" HorizontalAlignment="Left" Width="415"/>

When i plot a scatterplot is use : 
this.plotWindow.plt.PlotScatter(x,x,x,x,x);       works perfectly

However i can't access 
plotWindow.Configuration
plotWindow.Plot

what am i doing wrong? I'm using the newest scottPlot from nuget.

**Comment by swharden** [comment]
Hi @KlaskSkovby, 

The current master branch of this project is ScottPlot 4.1 which is currently a pre-release beta package on NuGet.

The 4.0 release on NuGet has source code in the 4.0-stable branch. https://github.com/ScottPlot/ScottPlot/tree/4.0-stable The demo code you are looking for is probably in there. Does this help?

**Comment by KlaskSkovby** [comment]
Found the correct demo example, and it works perfekt. 

Thanks for the help and fast responce
