### ISSUE TITLE
WPF is no longer DPI Aware

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#720]
Describe the bug and how we can reproduce it.

Open the mouse tracker demo on WPF on a screen with display scaling that is not equal to 100%. Here's a picture, my apologies for the quality, it's difficult to take a screenshot which includes the mouse cursor:
![image](https://user-images.githubusercontent.com/8635304/106058700-d8095b80-60ae-11eb-936a-904581c057ee.png)

This issue does not affect the WinForms or Avalonia demos.

**Comment by swharden** [comment]
Thanks for reporting this @bclehmann! This is the 4.1 code base, right?

DPI scaling is thorny, and an issue that keeps popping up: #643, #563, #490, #360, #380, #379, #254, #281, #171, #137, #125, #111, #135, #136 I hope that with this new control back end strategy we can fix it "one final time" and it will stay fixed 🤞 

This issue should also track/confirm/fix other features on scaled displays like draggable plottables, middle-click-drag zoom windows, and zooming to the cursor when the mouse wheel is scrolled. Moving between two monitors with different scaling should also be tested. It may be useful to put together a manual checklist of things commonly broken by DPI scaling and use it to facilitate manual testing any time the control code is changed.

PS: We can hold off putting effort into the "highlight point nearest cursor" task, as I'm actively working on a solution for that right now (which will also address #709)

PPS: Nice new handle!

**Comment by bclehmann** [comment]
>  I hope that with this new control back end strategy we can fix it "one final time" and it will stay fixed 🤞

My thinking is a `DPICorrectedInputState` or something like that, which can take an `InputState` class and does all the DPI correction stuff automatically.

> We can hold off putting effort into the "highlight point nearest cursor" task, as I'm actively working on a solution for that right now

Cool 👍 

> PPS: Nice new handle!

Why thank you, so far it hasn't broken _too_ many links.

**Comment by swharden** [comment]
> My thinking is a DPICorrectedInputState or something like that, which can take an InputState class and does all the DPI correction stuff automatically.

I'm reminded some of these features are already in the back-end, they might just not be getting wired-up when the control starts:
https://github.com/ScottPlot/ScottPlot/blob/6e9a9ac35254210636be16abecff4ad147f8370e/src/controls/ScottPlot.Avalonia/ControlBackend.cs#L28-L29

To calculate DPI scale, I used to create a 1px square Bitmap, create a Graphics, then measure it. Something like:
```cs
// warning this is browser programming
Bitmap bmp = new Bitmap(1, 1);
Graphics gfx = Graphics.FromBitmap(bmp);
double dpiScale = gfx / 96; 
```

> Why thank you, so far it hasn't broken too many links.

Easier to break and repair now than to do it later! The name is relatively unique on Google too, so if you turn it into a domain name in the future people will be able to find you easily. Great setup!

**Comment by bclehmann** [comment]
> I'm reminded some of these features are already in the back-end, they might just not be getting wired-up when the control starts:

Those are actually the old backend, the one that only Avalonia used. Avalonia actually does DPI correction itself, so at one point I was doing double the correction and then needed to divide out the `dpiScale` at the end. It was... interesting.

> The name is relatively unique on Google too

Not too unique! Couldn't use blehmann because there's a Bob Lehmann somewhere on github. But thank you, I'd been meaning to change my username for a while.
