### ISSUE TITLE
Upscaling resolution of save as image

### ISSUE THREAD

**Issue by riquich** [ScottPlot/ScottPlot#723]
Hi, first of all thank you for providing this great library and all the effort you are putting onto this.

I have a rather simple task to accomplish, I need to save the plot as image but i need to have it more than regular resolution so that the image can be zoomed in and still retain its crispness. Seems like X/Y pixel count of the produced image is directly related with the current X/Y size of the plot window. So I guess it should somehow be possible to trick and make the plot window like 3840 x 2160 pixel even though my monitor is, say, 1080p. This way the produced image will have a high resolution, at least I believe so.

Thank you for answers in advance

**Comment by StendProg** [comment]
Hi @riquich,

1. You can create new `Plot` object with custom resolution in your save handler. Plot on them the same as you plotted on `Control.plt`. And then save it to file:
```c#
var plt = new Plot(3840, 2160);
plt.PlotSignal(ys);
plt.SetTitle("Saved plot")
plt.SaveFig("Image.png");
```

2. If it hard to apply the same Plottables again, you can copy existing `Control.plt` to new one, and then resize and save it (not tested):
```c#
var plt = FormsPlot1.plt.Copy();
plt.SetSize(3840, 2160);
plt.SaveFig("Image.png");
```

**Comment by riquich** [comment]
Hi @StendProg,

Just tried and it works, thank you so much for rapid reply,

have a nice day !
