### ISSUE TITLE
Tick label disappears when there is only one

### ISSUE THREAD

**Issue by Saklut** [ScottPlot/ScottPlot#724]
ScottPlot 4.0.48
When there is only one tick visible on an axis, it disappears.

![recording (3)](https://user-images.githubusercontent.com/75701536/106323484-c9ba6b80-6277-11eb-9654-f39696dbd5f7.gif)

**Comment by bclehmann** [comment]
Note, this doesn't happen on 4.1.4, but there is this clipping issue:
![image](https://user-images.githubusercontent.com/8635304/106325895-d23f8180-6238-11eb-8c50-c819159a5655.png)

This clipping issue only happens with manually specified tick labels.

**Comment by swharden** [comment]
Thanks for reporting these issues @Saklut and @bclehmann! I took care of both issues and will upload a NuGet package shortly.

The 4.0 tick system is super confusing (it evolved over many months, and has several hacks layered-on as bugs were found), and unfortunately a lot of this complexity was copied into 4.1. I hope to refactor this eventually (with strong tests), and hopefully the new architecture will support for alternative tick strategies like #456 and #394.
