### ISSUE TITLE
Mouseclick event - get coordinates 

### ISSUE THREAD

**Issue by JDE1989** [ScottPlot/ScottPlot#739]
Hello,

I am working on a project that is utilizing ScottPlot. I'm new to this library and have a few questions. With the current version of ScottPlot, is there a way I can modify the mouseclick event?  For example, I would like to click on a given point and get the corresponding coordinates.  Also I'd like to change what happens when a user left-clicks and drags on the chart.  Are these possible with the current version.  If so, how should I approach this? 

Please advise.

**Comment by bclehmann** [comment]
You cannot modify mouseclick event without modifying the control yourself. For 4.1.x (Beta) the controls are in this directory: https://github.com/ScottPlot/ScottPlot/tree/master/src/controls. For 4.0.x they are here https://github.com/ScottPlot/ScottPlot/tree/4.0-stable/src. Note these are different branches.

However, you can add your own click events on top of the ones ScottPlot has. And you can disable certain ScottPlot behaviours with the `control.Configuration` object (4.1.x) or with `control.Configure()` (4.0.x) which would let you disable some of the click-events.

You can get the coordinates of the mouse with `control.GetMouseCoordinates` in both 4.0.x and 4.1.x. You can then loop through your points to get the closest one (4.0.x) or use `scatterPlot.GetPointNearest(x, y)` in 4.1.x.

In 4.0.x there is also the `PlottableScatterHighlight` class which is a normal scatter plot which allows you to use `plot.GetPointNearest(x, y)`

For more information you can look at the "Show Value Under Cursor" demo, which is in both 4.0.x and 4.1.x (although the actual code is different). There are demos for WinForms, WPF, and Avalonia.

**Comment by swharden** [comment]
Hi @JDE1989, 

It sounds like you want a custom action to happen when the user left-clicks somewhere on the plot. @bclehmann answered correctly, and outlined a good strategy for how to do this.

I'll just add that making a custom FormsPlot control to have the custom behavior you want isn't as scary as it sounds. The whole control is about 100 lines long, and it should be very easy to copy and modify to suit your needs.

https://github.com/ScottPlot/ScottPlot/blob/d1ca60aaf12e5198241d25fd9536bf734022123d/src/controls/ScottPlot.WinForms/FormsPlot.cs#L1-L107

Presently left-click-drag is a pretty core function of this library so support for custom left-click actions is unlikely to be implemented soon, but I'd like to make this easier so I added it to the list of triaged features (#716) and can revisit it when some of the bigger active issues settle down.

Thanks for asking! I'll post again here in the future if/when this is implemented.
