### ISSUE TITLE
A Issue about the padding 

### ISSUE THREAD

**Issue by YUXI07** [ScottPlot/ScottPlot#740]
**Describe the Issue:**
   I use it as the initial  Form. I can't achieve my goal without data. Like this:
**Without data:**
![image](https://user-images.githubusercontent.com/56529780/106726267-24234580-6645-11eb-9cca-88982c40f0a5.png)
The LightBlue is the padding that I want to eliminate. But I can eliminate it by adding the data. Like this:
**With data:**
![image](https://user-images.githubusercontent.com/56529780/106726699-a7449b80-6645-11eb-9f98-d95f4aa57783.png)
This is my code and it is the demo about Customize: Figure - No Padding.

```cs
var plt = this.scottPlot.plt;
plt.PlotHLine(2);
plt.Style(figBg: Color.LightBlue);
plt.Style(dataBg: Color.LightYellow);
plt.Ticks(false, false);
plt.Frame(false);
plt.TightenLayout(padding: 0);
scottPlot.Configure(recalculateLayoutOnMouseUp: false);
scottPlot.Render();
```
How can I eliminate the padding except by Adding data?

**Comment by bclehmann** [comment]
If you only want to remove padding you just need this:

```cs
var plt = this.scottPlot.plt;
plt.TightenLayout(padding: 0);
scottPlot.Configure(recalculateLayoutOnMouseUp: false);
scottPlot.Render();
```

To aid understanding, this is what every line in that demo does:

```cs
var plt = this.scottPlot.plt; // Gets the plot object
plt.PlotHLine(2); // Adds a horizontal line on y = 2
plt.Style(figBg: Color.LightBlue); // Sets the figure background to blue
plt.Style(dataBg: Color.LightYellow); // Sets the data background to yellow
plt.Ticks(false, false); // Turns off axis ticks
plt.Frame(false); // Turns off axis outline
plt.TightenLayout(padding: 0); // Removes padding
scottPlot.Configure(recalculateLayoutOnMouseUp: false); // Disables relayouting on release of the mouse buttons (so it doesn't add the padding back)
scottPlot.Render(); // Renders the image
```

**Comment by YUXI07** [comment]
Thank you for your reply. 
You understand my question incorrectly. It can't remove the padding when I don't add any items to the plot. 
If I add items to the plot, the padding would remove successfully.

**Comment by bclehmann** [comment]
> You understand my question incorrectly. It can't remove the padding when I don't add any items to the plot.
> If I add items to the plot, the padding would remove successfully.

I'm not able to replicate this issue on 4.0.48, are you calling `Render()` after you change the padding settings?

**Comment by YUXI07** [comment]
Here is my code without adding any items. The plot is on the SplitContainer .The red is a split of SplitContainer. The dock of the plot is Fill.
![image](https://user-images.githubusercontent.com/56529780/106828797-dac70a80-66c5-11eb-864f-65214d3c7103.png)
```cs
    public partial class frmScottPlot : Form
    {
       
        public frmScottPlot()
        {
            InitializeComponent();

        }

        private void InitScottPlot()
        {


            var plt = this.scottPlot.plt;
            //plt.PlotHLine(2);
            plt.Ticks(false, false);
            plt.Frame(false);
            plt.TightenLayout(padding: 0);
            scottPlot.Configure(recalculateLayoutOnMouseUp: false);
            scottPlot.Render();




        }
       
        private void frmScottPlot_Load(object sender, EventArgs e)
        {

            InitScottPlot();

        }
    }
```
I add an item to the plot and get my goal. Here is my code with items.
![image](https://user-images.githubusercontent.com/56529780/106829253-bf103400-66c6-11eb-92e3-f8f44a13a9a1.png)

```
    public partial class frmScottPlot : Form
    {
       
        public frmScottPlot()
        {
            InitializeComponent();

        }

        private void InitScottPlot()
        {


            var plt = this.scottPlot.plt;
            plt.PlotHLine(2);
            plt.Ticks(false, false);
            plt.Frame(false);
            plt.TightenLayout(padding: 0);
            scottPlot.Configure(recalculateLayoutOnMouseUp: false);
            scottPlot.Render();




        }
       
        private void frmScottPlot_Load(object sender, EventArgs e)
        {

            InitScottPlot();

        }
    }
```

**Comment by YUXI07** [comment]
I want a plot of no padding without any items as my initial Winforms.

**Comment by bclehmann** [comment]
This is my result, the plot on the left is a dummy plot just to fill space.
![image](https://user-images.githubusercontent.com/8635304/106832380-ca277d80-664e-11eb-855e-1a373af30fa2.png)

The background was changed to red to make it easier to see. As far as I can tell they are identical. It would help a lot if you were to include any settings on your `SplitContainer`, as it's quite possible that the padding is coming from the `SplitContainer`, or that the `SplitContainer` is configured in a way that would resize the `FormsPlot` or create padding.

**Comment by YUXI07** [comment]
Hi, I do the same work and here is my result. My result is different from yours. The Left without lines and the Right with a horizontal line.  I only change the ```SplitContainer.backcolor``` to ```Red```.
![image](https://user-images.githubusercontent.com/56529780/106847755-841ff780-66ea-11eb-8f42-de0e65be0f16.png)
```cs
            var plt = this.scottPlot.plt;// 右图
            plt.PlotHLine(2);
            plt.Ticks(false, false);
            plt.Frame(false);
            plt.TightenLayout(padding: 0);
            scottPlot.Configure(recalculateLayoutOnMouseUp: false);
            scottPlot.Render();

            var plt1 = this.formsPlot1.plt; //左图
            //plt1.PlotHLine(2);
            plt1.Ticks(false, false);
            plt1.Frame(false);
            plt1.TightenLayout(padding: 0);
            formsPlot1.Configure(recalculateLayoutOnMouseUp: false);
            formsPlot1.Render();
```
if possible, can I take a look at the code you tested?

**Comment by bclehmann** [comment]
> if possible, can I take a look at the code you tested?

Sure thing.

```cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace TestWF
{
	public partial class Form1 : Form
	{
		public Form1()
		{
			InitializeComponent();
		}

		private ScottPlot.FormsPlot formsPlot1 = new ScottPlot.FormsPlot(new ScottPlot.Plot(200, 200));
		private ScottPlot.FormsPlot formsPlot2 = new ScottPlot.FormsPlot(new ScottPlot.Plot(200, 200));
		private SplitContainer container = new SplitContainer();

		private void InitScottPlot()
		{
			formsPlot1.plt.Ticks(false, false);
			formsPlot1.plt.Frame(false);
			formsPlot1.plt.TightenLayout(padding: 0);
			formsPlot1.Configure(recalculateLayoutOnMouseUp: false);
			formsPlot1.plt.PlotHLine(2);
			formsPlot1.Render();
		}

		private void Form1_Load(object sender, EventArgs e)
		{
			container.Width = 1500;
			container.Height = 800;
			container.SplitterDistance = 500;
			container.BackColor = Color.Red;
			container.BorderStyle = BorderStyle.Fixed3D;

			this.Controls.Add(container);
			container.Panel1.Controls.Add(formsPlot2);
			container.Panel2.Controls.Add(formsPlot1);
			InitScottPlot();
		}
	}
}
```

**Comment by YUXI07** [comment]
I think I find the difference between us. I use the ``` ScottPlot``` by drawing from ToolBox in Vs2019. You use the ``` ScottPlot``` by coding. I get my goals using your method. But I can't get my goals using my methods.
![image](https://user-images.githubusercontent.com/56529780/106861129-50e86300-6700-11eb-9223-2cb3a53aaa54.png)

**Comment by YUXI07** [comment]
Further debugging，I find an amazing phenomenon. I remove the part of your code. So I can't get my goal.
### Before modification
```cs
		private ScottPlot.FormsPlot formsPlot1 = new ScottPlot.FormsPlot(new ScottPlot.Plot(200, 200));
		private ScottPlot.FormsPlot formsPlot2 = new ScottPlot.FormsPlot(new ScottPlot.Plot(200, 200));
```
### After modification
```cs
		private ScottPlot.FormsPlot formsPlot1 = new ScottPlot.FormsPlot();
		private ScottPlot.FormsPlot formsPlot2 = new ScottPlot.FormsPlot(new ScottPlot.Plot(200, 200));
```
## The result
![image](https://user-images.githubusercontent.com/56529780/106865919-c9eab900-6706-11eb-80d7-531f9da83438.png)

### Automatic generated by Visio studio
```cs
		this.formsPlot1 = new ScottPlot.FormsPlot();
```
I think it is my Heart of the matter.

**Comment by bclehmann** [comment]
Huh, wouldn't have thought that would make a difference. Still, if it works then good catch.

**Comment by swharden** [comment]
Hi @YUXI07, thanks for the question and @bclehmann for your help along the way!

**To summarize the problem,** plots weren't rendering framelessly in the FormsPlot control if they were empty, and that this is an an issue that only applies to version 4.0.

**The fix** is to instantiate the FormsPlot control by passing-in a new Plot with a defined size, rather than letting it create one.

I too am puzzled by this solution, but am happy to hear @YUXI07 ended-up with something that gets the job done! 👍
