### ISSUE TITLE
Alt left click zoom

### ISSUE THREAD

**Issue by JS-BGResearch** [ScottPlot/ScottPlot#741]
Is there a way to disable the Alt left click and drag to zoom into an area of a WPF Signal plot?

**Comment by bclehmann** [comment]
### 4.0.x

Not without modifying the control yourself, the relevant code is in https://github.com/ScottPlot/ScottPlot/tree/4.0-stable/src/ScottPlot.WPF

### 4.1.x (Beta)

```cs
wpfPlot.Configuration.MiddleClickDragZoom = false;
```

**Please note, this option is broken!** If this is set it will draw the rectangle as normal, and once it's released it will not zoom and the rectangle will not disappear.

I'll make a PR to address this. I'm glad I tested this before just telling you it would work.

**Comment by JS-BGResearch** [comment]
Thanks for the quick response. 

I've found a simple work around for 4.0.x, if I add an event handler for the plot control's PreviewMouseDown event and set e.Handled to true if the alt keys are pressed, then the feature is disabled.

        private void Plot_PreviewMouseDown(object sender, System.Windows.Input.MouseButtonEventArgs e)
        {
            if ((Keyboard.IsKeyDown(Key.LeftAlt)) || (Keyboard.IsKeyDown(Key.RightAlt)))
            {
                e.Handled = true;
            }
        }

**Comment by bclehmann** [comment]
Interesting, reminds me of the old days of Javascript development where you'd need to sprinkle some `e.preventDefault()` around.

I know @swharden is considering backporting small features from 4.1.x to 4.0.x so it's possible that you get a more official solution before 4.1.x leaves beta.

**Comment by swharden** [comment]
Hey @JS-BGResearch, thanks for the question and sharing your findings! @bclehmann thanks for your input too, and for #742

Since a workaround is found and 4.1 is pretty close to ready, I'll probably leave 4.0 like it is. Setting `e.Handled` to `true` seemed to do the trick, so I'll convert this issue to a discussion and mark that the answer 👍
