### ISSUE TITLE
Issue (memory leak) with ScottPlot library?

### ISSUE THREAD

**Issue by screen-saksrepo** [ScottPlot/ScottPlot#746]
Hi

I'm using ScottPlott Nuget Package as part of a NET CORE 3.1 project to create nice Bitmaps with statistical data.

However, I've found out that whenever I use thelibrary, I got a memory leak that little by little makes my app crash eventually. 

The created  plots, (as new ScottPlot.Plot(600, 400)) seem not to be disposed appropriately, and even though I'm aware of 'past' problems with .NET Core disposing Bitmaps, I think all points out to the library, though to be totally honest, I'm not 100% sure...

This the the **consumer**, the calling function. By using 'using' blocks, I'm disposing them when not used anymore:

```cs
using System.Drawing;
....
using MemoryStream ms = new MemoryStream();
using Bitmap bmp = subtitles.GetConfidenceHistogram();
bmp.Save(ms, ImageFormat.Png);
await File.WriteAllBytesAsync(Path.Combine(outputFolderPath, filenameNoExt + "_histogram.png"), ms.ToArray());
```

This is the called function:

```cs
public Bitmap GetConfidenceHistogram(string Id = null)
{
	return Charts.DrawHistogram(ConfidenceStatistics.Samples, Id);
}
```

which in turn calls the function that eventually creates the plot:

```cs
static public Bitmap DrawHistogram(List<double> Samples, string Id)
{
    var plt = new ScottPlot.Plot(600, 400);
    double[] values = Samples.ToArray();

    if (Samples.Count > 0)
    {
        var hist = new ScottPlot.Statistics.Histogram(values, min: 0, max: 100, binCount: 20);
        plt.PlotBar(hist.bins, hist.countsFrac, barWidth: hist.binSize * 0.9, outlineWidth: 0, fillColor: Color.Red);
    }
    if (Id == null) plt.Title("Subtitle Confidence Data");
    else plt.Title("Subtitle Confidence Data - " + Id);
    plt.YLabel("Frequency (fraction of total)");
    plt.XLabel("Confidence (percent)");
    plt.Axis(null, null, 0, null);
    plt.Grid(lineStyle: ScottPlot.LineStyle.Dot);

    return plt.GetBitmap();
}
```

---

If I changed the first called function to say:

```cs
public Bitmap GetConfidenceHistogram(string Id = null)
{
    return new Bitmap(600, 400);
    // return Charts.DrawHistogram(ConfidenceStatistics.Samples, Id);
}
```

the memory leaks dissappears.

---

If in 'DrawHistogram', I do the Plot thing, but return an empty bitmap:

```cs
return new Bitmap(600,400);
// return plt.GetBitmap();
```

I still do have memory leak. 

Any comments on this would be highly appreciated.
Kind regards

Fernando

**Comment by StendProg** [comment]
Hi @screen-saksrepo,

It looks like you use stable 4.0 version.
You should try 4.1 version. In 4.1, Scott (@swharden) did a great job in exactly this direction. All GDI objects are correctly disposed and should work without memory leaks.
Just try 4.1.5-beta on your project, and write what happened.
