### ISSUE TITLE
XAxis tick labels missing.

### ISSUE THREAD

**Issue by inqb** [ScottPlot/ScottPlot#762]
https://swharden.com/scottplot/cookbooks/4.1.6-beta/category/advanced-axis-features/#manual-tick-labels

cookbooks says:
```cs

// ...
// manually define X axis tick positions and labels
double[] xPositions = { 7, 21, 37, 46 };
string[] xLabels = { "VII", "XXI", "XXXVII", "XLVI" };
plt.XAxis.ManualTickPositions(xPositions, xLabels);

// manually define Y axis tick positions and labels
double[] yPositions = { -1, 0, .5, 1 };
string[] yLabels = { "bottom", "center", "half", "top" };
plt.YAxis.ManualTickPositions(yPositions, yLabels);
// ...
```

and renders as:
![grafik](https://user-images.githubusercontent.com/31213281/107245261-3c250b80-6a2f-11eb-8c81-d256ffcf6a0f.png)

**Comment by swharden** [comment]
Thanks for reporting this @inqb! I fixed it with 565bc14 and it will be in the next NuGet package 👍
