### ISSUE TITLE
Heatmap should throw exception for data larger than Bitmap supports

### ISSUE THREAD

**Issue by Matthias-C** [ScottPlot/ScottPlot#772]
Found this on rendering big datasets in to a heat map.
From my point of view it looks like that the internal plotting runs into an variable limit (i guess singed short (2^15)) and than stretches the last row of data al the way to the end as seen in pictures,

## OK Render less than 2^15 rows in y dimension
![outOK1](https://user-images.githubusercontent.com/1331533/107642693-7f70bb80-6c75-11eb-8ecb-fd3e5ce41c4c.png)
![outOK2](https://user-images.githubusercontent.com/1331533/107642706-826bac00-6c75-11eb-9818-3af39f6b1fa1.png)

## Faild renders at more than 2^15  rows 
![outFail1](https://user-images.githubusercontent.com/1331533/107642677-7a137100-6c75-11eb-952a-5a0e6cfcc175.png)
![outFail2](https://user-images.githubusercontent.com/1331533/107642686-7da6f800-6c75-11eb-8d68-226b8a24e3c5.png)

```cs
[Test]
[TestCase(3768,"outOK1.png")]
[TestCase(32768,"outOK2.png")]
[TestCase(34000,"outFail1.png")]
[TestCase(60000,"outFail2.png")]
        public void ScottplotBoundary( int traceCount ,string path) {
            Random r           = new Random();
            int    sampleCount = 500;
            
            var zData = new double[traceCount, sampleCount];
            for (var i = 0; i < traceCount; i++) {
                for (var i1 = 0; i1 < sampleCount; i1++) {
                    zData[i, i1] = r.NextDouble() ; 
                }
            }
            
            var                plt = new Plot();
            CoordinatedHeatmap hmc = plt.AddHeatMapCoordinated(zData);
            plt.AxisAuto(0, 0);
            plt.SaveFig(path);
        }
```

found on nuget 4-1.6-beta -- running on core 3.1

**Comment by StendProg** [comment]
Hi @Matthias-C,
Heatmap render based on `Bitmap`. Perhaps this is due to its limitations, then there is nothing to be done..
It is also possible that this is somehow related to the use of x86 mode(Any CPU), if you use it try changing it to x64.

**Comment by swharden** [comment]
I suspect @StendProg is right and that this is a limitation of `System.Drawing.Bitmap`.

I haven't tested it, but some information I found on Google suggests the maximum bitmap size is limited by the total number of pixels (not necessarily edge length), and that value is `(2^16/2)*(2^16/2)` or `1,073,741,824` pixels. @StendProg pointed-out that this value may be different on `x86` and `x64` systems, but is also worth testing.

When we conclude what the limitations of `System.Drawing.Bitmap` are, we should check the total number of values when heatmaps are created and throw an exception if more data is passed in than can be represented. If the user really wants to plot more data than this (probably a pretty rare case), they can easily create multiple heatmaps with carefully chosen coordinates so they tile nicely in the data area.

**Comment by Matthias-C** [comment]
thanks for changing the title ... new one is way better.

for now I did some data compression to limit the amount of input data.

```C#
public double[,] RescaleArray(double[,] data, int targetWidth, int targetHeight) {
            int       sourceHeight   = data.GetLength(0);
            int       sourceWidth    = data.GetLength(1);

            double[,] compressedData = new double[targetHeight,targetWidth];
            
            double[] valuesTmp = new double[targetWidth];
            uint[]   countsTmp = new uint[targetWidth];

            double widthScale  = (double)sourceWidth  / targetWidth;
            double heightScale = (double)sourceHeight / targetHeight;

            int yTarget =0;
            
            for (int ySource = 0; ySource < sourceHeight; ySource++) {

                int xTmp =0;
                for (int xSource = 0; xSource < sourceWidth; xSource++) {
                    
                    if (xSource >= widthScale * (xTmp + 1))
                        ++xTmp;
                    valuesTmp[xTmp] += data[ySource,xSource];
                    countsTmp[xTmp] += 1;
                }
                
                if (ySource + 1 >= heightScale * (yTarget + 1))
                {
                    for (int xTarget = 0; xTarget < targetWidth; ++xTarget)
                    {
                        compressedData[yTarget,xTarget] = valuesTmp[xTarget] /  countsTmp[xTarget];
                        valuesTmp[xTarget]               = 0.0;
                        countsTmp[xTarget]               = 0U;
                    }
                    ++yTarget;
                }
            }
            return compressedData;
        }
```

For the moment it's not fully tested, and not well optimised but gets the job done.

**Comment by swharden** [comment]
On my system System.Drawing will throw an error if you try to create an image wider than about 10M pixels or with a total number of pixels above 100M. I see from the screenshot above that with only about 30M pixels it won't throw an exception, but it will produce unpredictable behavior.

I added descriptive exceptions which throw if an edge is greater than 1M points or if the total number of points is greater than 10M. I think this will prevent this issue from occurring unexpectedly in the future.

Users wanting to display extremely large 2D heatmap data should probably investigate efficient image analysis libraries which are optimized for this type of math. This topic is definitely pushing the boundaries of ScottPlot's capabilities and intended scope!

Thanks again for pointing out this issue @Matthias-C

**Comment by StendProg** [comment]
Hi @swharden,
I think this exceptions must be part of optional validation.
I use 2k*2k = 4M bitmaps a lot, and it's very close to provided limits...

**Comment by swharden** [comment]
I came to a compromise and like @StendProg suggested moved the size-checking code into the deep validation method. I also extended the XML documentation for the `AddHeatmap()` methods to indicate rendering may become unpredictable for large arrays with ~10M or more values. 

Thanks again for both of your input!
