### ISSUE TITLE
MouseMove gives the coordinates of the mouse 0,0 until the middle mouse button is pressed on the control (NUGET Package)

### ISSUE THREAD

**Issue by vc** [ScottPlot/ScottPlot#774]
Tried to implement MouseTracker (WinFormsDemos). Library ScottPlot and ScottPlotWinForms was connected from NUGET v4.1.6beta. But after loading the form, UserControl always displays x = 0, y = 0 mouse coordinates. Until you press the middle mouse button on the control. After that the MouseMove event passes the correct mouse coordinates.
I decided to figure out what the problem was and cloned the repository and connected the ScottPlot and ScotPlottWinForms projects to my solution. To my surprise, the above error did not recur. This means that a package in NUGET only has this error.

**Comment by swharden** [comment]
Hey @vc, thanks for reporting this! I worked on the mouse tracking code within the last week, so it's possible this bug has been fixed already. I'm going to publish a NuGet package in the next few minutes here, so when it appears give it a shot and feel free to open this issue if you continue to have an issue!

Scott
