### ISSUE TITLE
start form 0,0 and dont show ys in PlotSignalXY

### ISSUE THREAD

**Issue by behroozbc** [ScottPlot/ScottPlot#775]
hi 

I want show live chart in xs and ys but my chart stop in on 0 like this 

![image](https://user-images.githubusercontent.com/20381616/107846534-bd96e800-6df9-11eb-8c8d-996407d0edc9.png)

### My Code
https://github.com/behroozbc/TestChartXY 

https://github.com/behroozbc/TestChartXY/blob/b00fecf558afb0ee0f7caa6d9175d3b9cd081bce/TestChartXY/MainWindow.xaml.cs#L1-L64

### My System Info
```
Microsoft Visual Studio Community 2019
Version 16.8.5
VisualStudio.16.Release/16.8.5+31005.135
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools 2019   16.8.559.8768
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.559.8768
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.559.8768
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.559.8768
Azure Functions and Web Jobs Tools

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

The name of my extension   Version of my extension
Description of my extension

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
```

**Comment by behroozbc** [comment]
I made this example for same data in ys and xs 
https://github.com/behroozbc/TestChartXY/tree/test_with_same_number

**Comment by StendProg** [comment]
Hi @behroozbc,
`SignalXY` limitation is `xs` must be in accending order.
Use `Scatter` instead.( but it's much more slower).

You can always validate your data with `plt.Validate()` and get exception with description of the discrepancy.

**Comment by behroozbc** [comment]
hi @StendProg 
now xs is ascending but dont solve problem

**Comment by behroozbc** [comment]
@StendProg 
I can find ```plt.Validate()``` in [cookbook](https://swharden.com/scottplot/cookbooks/4.0.47/)

**Comment by StendProg** [comment]
It's still not in accending order because you try to render 100_000 elements Array with latest values all the zeroes.
You can limit the displayed data using MaxRenderIndex:
```c#
var signal = wpfPlot1.plt.PlotSignalXY(xs, ys, color: Color.Red);
...
...
     
      xs[nextDataIndex] = nextDataIndex;
      ys[nextDataIndex] = _random.Next(100) + _random.NextDouble()+nextDataIndex;

      signal.MaxRenderIndex = nextDataIndex;

      nextDataIndex++;
```
>I can't find plt.Validate() in cookbook

It looks like you use stable 4.0 version. Data validation was still poorly developed then, sorry for the false tip.

**Comment by swharden** [comment]
Hi @behroozbc, 

It sounds like you want to create a plot and update its data over time. My recommendation is to look closely at the source code for the demo applications that do this. There are WPF examples for how to update data for fixed size arrays [LiveDataFixed.xaml.cs](https://github.com/ScottPlot/ScottPlot/blob/master/src/demo/ScottPlot.Demo.WPF/WpfDemos/LiveDataFixed.xaml.cs) and another examples for how to plot growing data [LiveDataGrowing.xaml.cs](https://github.com/ScottPlot/ScottPlot/blob/master/src/demo/ScottPlot.Demo.WPF/WpfDemos/LiveDataGrowing.xaml.cs). 

You can start with these working examples and modify them to suit your needs. I hope it helps!

PS: It's on my to-do list to document this task better (https://github.com/ScottPlot/Website/issues/4) because it is commonly asked
