### ISSUE TITLE
AddSignalXYConst display glitch with DateTimeFormat = true

### ISSUE THREAD

**Issue by AlgoExecutor** [ScottPlot/ScottPlot#783]
First: thanks for the amazing work so far! :-)

Since I use the project for the first time I do not exclude that I use it possibly wrong. I have noticed visual differences between AddSignalXY and AddSignalXYConst. After a temporal gap, the values before the gap are displayed resulting in a short spike. I use DateTimeFormat = true for the XAxis. Here are some pictures to see the visual better:
![image](https://user-images.githubusercontent.com/79081847/107930996-070f4080-6f7c-11eb-9618-e5046689220b.png)

Here are in more Detail:
![image](https://user-images.githubusercontent.com/79081847/107931063-18584d00-6f7c-11eb-9e8f-827bf2058a8d.png)

Sometimes disappears when zoomed in:
![image](https://user-images.githubusercontent.com/79081847/107931157-2f973a80-6f7c-11eb-99ad-aadafb832b49.png)

Data looks like this:
2021-02-09T09:12:43.12+01:00;105.44;105.02;
2021-02-09T09:12:58.08+01:00;105.0;104.82;
2021-02-09T09:12:58.09+01:00;104.98;104.84;
2021-02-09T09:13:00.75+01:00;105.0;104.84;
(Blue line is the second value)

Using: **ScottPlot 4.1.6-beta**
```cs
formsPlot.Plot.AddSignalXYConst(xDate.ToArray(), ci.Xetra.Select(x => (double)x.BestBidPrice).ToArray(), label: "Bid");
formsPlot.Plot.AddSignalXYConst(xDate.ToArray(), ci.Xetra.Select(x => (double)x.BestAskPrice).ToArray(), label: "Ask");
formsPlot.Plot.XAxis.DateTimeFormat(true);
formsPlot.Plot.Title($"Test");
formsPlot.Render();
```

Thanks!

**Comment by StendProg** [comment]
Hi @AlgoExecutor,
Thanks for reporting. Can you provide test data to reproduce this bug?
I think ~10 points close to `Detail` area would be enouth.

**Comment by StendProg** [comment]
@AlgoExecutor thank you very much.
You managed to find a very persistent bug that has existed for over a year.
I fix it in #788.

**Comment by AlgoExecutor** [comment]
Wow, thank you very much for the fast fix! :)

**Comment by swharden** [comment]
Thanks @AlgoExecutor and @StendProg! I'm uploading the NuGet package now and it should be live in a few minutes 👍
