### ISSUE TITLE
Allow Array of Markersize in AddScatter

### ISSUE THREAD

**Issue by AlgoExecutor** [ScottPlot/ScottPlot#784]
Currently it looks like in AddScatter the marker size can only be set for the whole series, but not individually. Would it be possible to accept an array of marker sizes so that each marker gets its own size?

`
//current State
 formsPlot.Plot.AddScatter(xDate.ToArray(), ci.Data.ToArray(),
                                          Color.GreenYellow, lineWidth: 0, 5, MarkerShape.filledSquare);

//possible?                                          
 formsPlot.Plot.AddScatter(xDate.ToArray(), ci.Data.ToArray(),
                                          Color.GreenYellow, lineWidth: 0, **markerSize.ToArray()**, MarkerShape.filledSquare);                                          
`

You can currently create the behavior only with the AddPoint methode. However, you do not get a legend entry here.
Maybe it is also a problem for performance if you add a lot of points with AddPoint?

Would be cool if you could do that with AddScatter:
![image](https://user-images.githubusercontent.com/79081847/107948199-d1765180-6f93-11eb-8054-6d82f456cc55.png)

**Comment by swharden** [comment]
Hey @AlgoExecutor! I think I understand your suggestion: use arrays for scatter plots to customize every point. These arrays would be something like:
* `float[] MarkerSize`
* `Color[] MarkerColor`
* `MarkerShape[] MarkerShape`
* `float[] LineWidth`
* `Color[] LineColor`

Having a bunch of arrays to customize every line segment and marker in a scatter plot would get pretty memory intensive and slow to render, so I probably will not do this. Users who want to customize every individual line segment or marker should probably use `AddLine()` and `AddPoint()`, and customize accordingly. 

If a user really wants to customize all these things in a scatter plot, they can pretty easily copy the `ScatterPlot` class and make their own `CustomizedScatterPlot` which does implement all these arrays. It's pretty easy to make your own plot type by implementing `IPlottable` if you need something specific to your application, then you can just and `Add()` it to the plot.

I hope this helps!

**Comment by swharden** [comment]
Actually, A `MarkerSeries` plot type wouldn't be to difficult to create 🤔 

I'll leave this issue open while I consider it. Considering how much work I'm putting into #716 it probably won't be soon, but I could add it to the list of things to consider

**Comment by AlgoExecutor** [comment]
Thank you @swharden. Good brainstorming ;) 
You are right that you could also build your own custom class. For experienced users surely a good way. And as you mentioned, if the effort is not huge I would also be happy with a `MarkerSeries` method ;)

The idea to go over `AddPoint `instead of `ScatterPlot `currently breaks the performance. I can open another ticket about this as well? There is a factor of 4? slowdown when using `AddPoint`.

**Comment by AlgoExecutor** [comment]
For the sake of simplicity, you could also implement the marker size for `AddScatterPoints` only. How much impact would this have on the renderer?

**Comment by AlgoExecutor** [comment]
`AddPoint `can be an alternative as @swharden noted. However, the current problem here is performance. A small measurement shows the following:

![image](https://user-images.githubusercontent.com/79081847/108032843-62503a00-7033-11eb-9738-5e5ab7f7f1b4.png)

Tested with version: **ScottPlot 4.1.7-beta**

Number of points for every series:
1: 1971
2: 4402
3: 2546
5: 278
6: 496

Every point series have its own color / marker and variable size for every marker. Since e.g. `AddScatterPoints `renders faster I thought it would be a good thing to put the variable size for the markers there. Of course it could also indicate a general problem with `AddPoint`?

**Comment by swharden** [comment]
Hey @AlgoExecutor, thanks for this suggestion! I'm currently focusing on some larger immediate goals (documenting the new 4.1 version and getting it out of beta), so I'll add this issue to the triage list (#716) and return to it once some of the more pressing issues are resolved 👍
