### ISSUE TITLE
Marker Transparency

### ISSUE THREAD

**Issue by AlgoExecutor** [ScottPlot/ScottPlot#785]
Would it be possible to support transparency for markers?

**Comment by swharden** [comment]
Hey @AlgoExecutor, thanks for this suggestion! Yeah, this seems like a great idea. More specifically a `MarkerSeries` plot type could be created letting the user customize the color of each marker, and transparency can be configured as part of the color.

I'm currently focusing on some larger immediate goals (documenting the new 4.1 version and getting it out of beta), so I'll add this issue to the triage list (#716) and return to it once some of the more pressing issues are resolved 👍
