### ISSUE TITLE
Creation of own Markers

### ISSUE THREAD

**Issue by AlgoExecutor** [ScottPlot/ScottPlot#786]
Would it be possible to create your own markers? What would be suitable here? Vector or Image support?

**Comment by swharden** [comment]
Hey @AlgoExecutor, thanks for this suggestion! Yes, this has been a personal goal for a long time but I never got around to implementing it. Right now markers are structs, but they should be classes implementing an `IMarker` interface. This would let the user create their own markers and use them in their applications, without requiring modifications to the ScottPlot library.

I'm currently focusing on some larger immediate goals (documenting the new 4.1 version and getting it out of beta), so I'll add this issue to the triage list (#716) and return to it once some of the more pressing issues are resolved 👍
