### ISSUE TITLE
Candlestick Display Error when using DateTime Axis

### ISSUE THREAD

**Issue by AlgoExecutor** [ScottPlot/ScottPlot#793]
Hi @swharden & Team,
it looks like there is a candlestick display problem. Could be something to do with the timestamp? The candles appear quite wide on the image:

![image](https://user-images.githubusercontent.com/79081847/108052413-65a3ef80-704c-11eb-85f1-20bedf8c0678.png)

Here are some Bitcoin data on one minute level:
OHLC: open=48494,97, high=48594,51, low=48494,96, close=48594,51, timestamp=44242,7083333333
OHLC: open=48477,17, high=48533,93, low=48477,17, close=48494,96, timestamp=44242,7076388889
OHLC: open=48470, high=48499,15, low=48460, close=48486,19, timestamp=44242,7069444444
OHLC: open=48442,91, high=48480,15, low=48442,9, close=48470, timestamp=44242,70625
OHLC: open=48425,71, high=48445,98, low=48420,33, close=48442,91, timestamp=44242,7055555556
OHLC: open=48496,52, high=48496,53, low=48420,3, close=48425,71, timestamp=44242,7048611111
OHLC: open=48493,95, high=48498,96, low=48466,27, close=48496,53, timestamp=44242,7041666667
OHLC: open=48427,23, high=48499, low=48424,34, close=48493,95, timestamp=44242,7034722222
OHLC: open=48419,99, high=48475,58, low=48414,14, close=48427,23, timestamp=44242,7027777778
OHLC: open=48382,47, high=48420, low=48382,47, close=48419,99, timestamp=44242,7020833333
OHLC: open=48395,44, high=48421,26, low=48375, close=48382,47, timestamp=44242,7013888889
OHLC: open=48433,62, high=48441,96, low=48379,06, close=48395,44, timestamp=44242,7006944444
OHLC: open=48412,44, high=48466,58, low=48408,36, close=48433,61, timestamp=44242,7
OHLC: open=48455, high=48456,32, low=48392,89, close=48412,43, timestamp=44242,6993055556
OHLC: open=48344,83, high=48455, low=48344,83, close=48454,99, timestamp=44242,6986111111
OHLC: open=48381,26, high=48386,07, low=48300,34, close=48344,83, timestamp=44242,6979166667
OHLC: open=48373,19, high=48432,58, low=48368,75, close=48382,5, timestamp=44242,6972222222

```cs
pData.Add(new OHLC((double)candle.open,
                    (double)candle.high,
                    (double)candle.low,
                    (double)candle.close,
                    candle.opentime));
formsPlot.Plot.AddCandlesticks(pData.ToArray());
formsPlot.Plot.XAxis.DateTimeFormat(true);
formsPlot.Render();
```

Thank you :)

**Comment by AlgoExecutor** [comment]
Forgot to mention the version is: ScottPlot 4.1.8-beta

`AddOHLCs` is also affected by this:
![image](https://user-images.githubusercontent.com/79081847/108056105-25933b80-7051-11eb-8375-13398e2a79e7.png)

**Comment by swharden** [comment]
Hi @AlgoExecutor, thanks for reporting this!

This topic is poorly documented, so I'll leave this issue open to ensure I improve the cookbook to make this easier to figure out.

By default, candlesticks have a width of `1`. When a DateTime axis is used, this means each candle has the width of _one day_. To fix this, you need to change this behavior. I think there are 2 ways to do this. 

### Option 1: Enable Auto-Width

```cs
var fp = formsPlot1.AddCandlesticks(ohlcs);
fp.AutoWidth = true;
```

### Option 2: Define each candle's time span
```cs
foreach(var ohlc in ohlcs)
    ohlc.timeSpan = 1.0 / 24 / 60; // 1 minute
```

I'm coding in the browser, so it's not extensively tested. If you get it working let me know what you did!

**Comment by AlgoExecutor** [comment]
Hi @swharden, thank you for the quick feedback and also for the explanation. That makes some things clearer :-) 
The result for the two options looks like this:

![image](https://user-images.githubusercontent.com/79081847/108106900-d8ce5580-708e-11eb-8d50-c7a92edf2d1f.png)

Option 2 seems the winner. Used in the new screenshot more recent data as before. But this should not matter.
