### ISSUE TITLE
Adding Annotations combined with AxisAuto derivates turn out wierd

### ISSUE THREAD

**Issue by ChrisAtVault** [ScottPlot/ScottPlot#805]
Hey Scott,

I really appreciate ScottPlot especially that it is so easy and simple to handle. I am trying to create a ScatterPlot with user configurable axis. In this scenario the user should be able to show a tooltip for every datapoint in the plot. 

Before adding the tooltips everything looks fine:

![image](https://user-images.githubusercontent.com/79156810/108220569-2900f280-7137-11eb-9f1a-fe687776b71e.png)

But as soon as I add the tooltips and call AxisAuto the scaling between x-axis and y-axis changes and the x-axis goes full banana.

![image](https://user-images.githubusercontent.com/79156810/108220592-30280080-7137-11eb-8957-2b25dfd8d562.png)

Hopefully you have an idea.

Cheers,
Christian

```cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace BugSearch
{
    /// <summary>
    /// A form 1.
    /// </summary>
    ///
    /// <remarks>
    /// Cfortmann, 17.02.2021.
    /// </remarks>
    public partial class Form1 : Form
    {
        /// <summary>
        /// True if is date only, false if not.
        /// </summary>
        bool isDateOnly = true;

        /// <summary>
        /// The pre xs.
        /// </summary>
        DateTime[] preXS;

        /// <summary>
        /// The ys.
        /// </summary>
        double[] ys;

        /// <summary>
        /// Default constructor.
        /// </summary>
        ///
        /// <remarks>
        /// Cfortmann, 17.02.2021.
        /// </remarks>
        public Form1()
        {
            InitializeComponent();
            this.formsPlot1.Plot.XAxis.DateTimeFormat(true);
            int Min = 0;
            int Max = 20;
            Random randNum = new Random();
            ys = Enumerable
                .Repeat(0, 100)
                .Select(i => randNum.NextDouble() * (Max - Min) + Min)
                .ToArray();
            DateTime startTime = DateTime.Parse("11.11.2020 11:12:14");        
            preXS = Enumerable
                .Repeat(0, 100)
                .Select(i => startTime.AddHours(randNum.Next(-250, 250)))
                .ToArray();
            CreatePlot(false);
        }

        /// <summary>
        /// Creates a plot.
        /// </summary>
        ///
        /// <remarks>
        /// Cfortmann, 17.02.2021.
        /// </remarks>
        ///
        /// <param name="isDateOnly">   True if is date only, false if not. </param>
        public void CreatePlot(bool isDateOnly)
        {
            double[] xs;
            if (isDateOnly)
            {
                xs = preXS.Select(x => x.Date.ToOADate()).ToArray();
            }
            else
            {
                xs = preXS.Select(x => x.ToOADate()).ToArray();
            }
            ScottPlot.Plottable.ScatterPlot plt = new ScottPlot.Plottable.ScatterPlot(xs, ys)
            {
                Label = "test",
                Color = Color.Red,
                LineStyle = 0,
            };

            this.formsPlot1.Plot.Add(plt);
            this.RedrawGraph();
        }

        /// <summary>
        /// Event handler. Called by checkedListBox1 for selected index changed events.
        /// </summary>
        ///
        /// <remarks>
        /// Cfortmann, 17.02.2021.
        /// </remarks>
        ///
        /// <param name="sender">   Source of the event. </param>
        /// <param name="e">        Item check event information. </param>
        private void checkedListBox1_SelectedIndexChanged(object sender, ItemCheckEventArgs e)
        {
            switch (e.Index)
            { 
                /*
                case 0:
                    AddMinorGrid(e.NewValue == CheckState.Checked);
                    break;
                case 1:
                    ChangeTickFormat(e.NewValue == CheckState.Checked);
                    break;
                */
                case 2:
                    AddAnnotation(e.NewValue == CheckState.Checked);
                    break;
            }

            this.RedrawGraph();
        }

        /// <summary>
        /// Adds annotation.
        /// </summary>
        /// <para></para>
        /// <remarks>
        /// cfortmann, 04.12.2020.
        /// </remarks>
        public void AddAnnotation(bool isActive)
        {
            if (isActive)
            {
                foreach (var (preX, y) in Enumerable.Zip(preXS, ys))
                {
                    double x;
                    if (isDateOnly)
                    {
                        x = preX.Date.ToOADate();
                    }
                    else
                    {
                        x = preX.ToOADate();
                    }

                    ScottPlot.Plottable.Tooltip toolTip = this.formsPlot1.Plot.AddTooltip(y.ToString(), x, y);
                    toolTip.BorderWidth = 1;
                    toolTip.LabelPadding = 0;
                    toolTip.Font.Size = 10;
                    toolTip.ArrowSize = 8;
                }
            }
            else
            {
                var tooltips = this.formsPlot1.Plot.GetPlottables().OfType<ScottPlot.Plottable.Tooltip>().Select(toolTip => toolTip).ToList();
                tooltips.ForEach(toolTip => this.formsPlot1.Plot.Remove(toolTip));
            }

            this.RedrawGraph();
        }

        /// <summary>
        /// Redraw graph.
        /// </summary>
        ///
        /// <remarks>
        /// Cfortmann, 17.02.2021.
        /// </remarks>
        private void RedrawGraph()
        {
            this.formsPlot1.Plot.AxisAutoY();
            this.formsPlot1.Render();
        }

    ....
    }
}
```

PS: Thanks for your work and keep up with it.

**Comment by swharden** [comment]
Hey @ChrisAtVault, 

I can review this question in more detail later. For now, I spotted you're only calling auto-axis on the vertical axis with `AxisAutoY()`. Is this problem solved by calling `AxisAuto()`?

**Comment by StendProg** [comment]
Hi all,
problem in this line:
https://github.com/ScottPlot/ScottPlot/blob/92ec0558a76795a2fbfc4a54258399522092b074/src/ScottPlot/Plottable/Tooltip.cs#L38
if change it to 
```c#
public AxisLimits GetAxisLimits() => new AxisLimits(double.NAN, double.NaN, double.NaN, double.NaN); 
```
this solve the problem.
But maybe all the same the tooltip should correctly calculate its limits, taking into account the position and size of the label string?

**Comment by ChrisAtVault** [comment]
> Hey @ChrisAtVault,
> 
> I can review this question in more detail later. For now, I spotted you're only calling auto-axis on the vertical axis with `AxisAutoY()`. Is this problem solved by calling `AxisAuto()`?

Hey @swharden,
unfortunately none of the AxisAuto variants solves the problem.

**Comment by bclehmann** [comment]
I agree with @StendProg , the issue is that the `GetAxisLimits` returns all zeros (which is Jan 1, 1900 in OLE dates). This crept in when they were swapped from being `IRenderable` to being `IPlottable` (and thus required a `GetAxisLimits` definition:

Screenshot of git blame:
![image](https://user-images.githubusercontent.com/8635304/108447096-828f1d00-721c-11eb-9dfd-c78883a99151.png)

Unfortunately computing the axis limits is a little finicky as it has to compute the size of the tooltip and whether it flows to the left or to the right, etc, etc. Not too difficult, just messy. Might be a good idea to refactor the computing of the tooltip's vertexes out of `Render` so that it's cleaner.

**Comment by bclehmann** [comment]
I'm realizing now that converting things like the coordinates and sizes of the tooltip in coordinate space necessitates already knowing the axis limits...

I think the best solution is to have the tooltips not be considered at all in the axis calculation, which can be achieved by using `double.NaN` (although I think changing it so that it would accept `null` may be more appropriate). This does mean that auto-axising to cut off a tooltip, but this isn't that much of an issue because tooltips automatically flow rightwards if there isn't enough space on the left. One can consider a multi-pass `AxisAuto` function if this is a concern.

**Comment by ChrisAtVault** [comment]
thank you very much :) This fix works like a charm 👍
