### ISSUE TITLE
How to display DateTime ticks for negative OA date values?

### ISSUE THREAD

**Issue by at2software** [ScottPlot/ScottPlot#806]
There has been quite some discussion regarding DateTime axis rendering and also about OLE Automation date. I hope I haven't missed something, if so please feel free to close this.

How can dates before 30 Dec. 1899 (i.e. negative `DateTime.ToOADate()` values) be displayed? A `WpfPlot` control using v4.1.8-beta, with only this single line on of code 
```plot.Plot.XAxis.DateTimeFormat(true);```
results in this: 
![2021-02-18_15_22_10_24v1 mp4](https://user-images.githubusercontent.com/8616861/108370797-51ebbb00-71fd-11eb-8a4b-3cb87ccdd229.gif)

Consequently, plottables containing negative x values render without ticks and labels when DateTimeFormat is set to `true`, but maybe I'm missing something?

**Comment by StendProg** [comment]
Hi @at2software, Thanks for report, 
I didn't know that OLE date support negative values, but:

I think problem in this line:
https://github.com/ScottPlot/ScottPlot/blob/92ec0558a76795a2fbfc4a54258399522092b074/src/ScottPlot/Ticks/TickCollection.cs#L134

The minimum OLE Automation date is midnight, 1 January 0100.
The ToOADate method throws an OverflowException if the current instance represents a date that is later than MaxValue and earlier than midnight on January1, 0100. 
`However, if the value of the current instance is MinValue, the method returns 0`.
https://docs.microsoft.com/en-gb/dotnet/api/system.datetime.tooadate?view=net-5.0

I think something like this can solve problem:
```c#
low = Math.Max(low, Double.MinValue); 
```
or just comment this line.

**Comment by at2software** [comment]
Thanks again @StendProg this looks promising, will evaluate shortly.

**Comment by swharden** [comment]
Thanks for pointing out the issue @at2software and @StendProg for finding a solution! I merged in #807 and will release a NuGet package later today 👍
