### ISSUE TITLE
How to make a step plot?

### ISSUE THREAD

**Issue by KlaskSkovby** [ScottPlot/ScottPlot#808]
![image](https://user-images.githubusercontent.com/33638395/108392933-76eb2880-7213-11eb-8271-3979b5ba3f04.png)

I upgraded to the lastest version from Github.
It now says that PlotStep is obsolete and that I should use AddScatter instead. 

However AddScatter is not the same as PlotStep

**Comment by swharden** [comment]
Hi @KlaskSkovby, 

It's on my to-do list to make a cookbook example to make this easier to discover. I'm coding in the browser, but I think you can do something like this:

```cs
var sp = plt.AddScatter(xs, ys);
sp.StepDisplay = true;
```

**Comment by KlaskSkovby** [comment]
Thanks, that did the trick

**Comment by adomas-vensas** [comment]
Hi, is it possible to make the polygon plot have steps?
