### ISSUE TITLE
Behavior of AddFill in complex scenarios 

### ISSUE THREAD

**Issue by AlgoExecutor** [ScottPlot/ScottPlot#810]
Hi @swharden & Team,

i have played a little with the function: 
`Polygon AddFill(double[] xs1, double[] ys1, double[] xs2, double[] ys2, Color? color = null)`
It looks like the function is not intended for complex scenarios. That is, a variable number of values on the X-axis or Y-axis. The following errors occur if `xs1 `and `xs2 ` is different:

System.IndexOutOfRangeException: **Index was outside the bounds of the array.**
   at ScottPlot.Plot.AddFill(Double[] xs1, Double[] ys1, Double[] xs2, Double[] ys2, Nullable`1 color)
   at ExchangePlotter.InteractivChart.AddData(ChartInput ci) in d:\Code\ExchangePlotter\InteractivChart.cs:line 78

If the number of `xs1 `and `xs2 ` is equal but `ys1 `and `ys2 `have different amounts, this exception happens:

System.ArgumentException: **Destination array was not long enough. Check destIndex and length, and the array's lower bounds.**
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at ScottPlot.Plot.AddFill(Double[] xs1, Double[] ys1, Double[] xs2, Double[] ys2, Nullable`1 color)
   at ExchangePlotter.InteractivChart.AddData(ChartInput ci) in d:\Code\ExchangePlotter\InteractivChart.cs:line 78

This is not urgent. It would be cool if the number of points for X/Y didn't matter. As long as the areas for `xs1`, `xs2` overlap, interpolation would certainly be possible to find "missing" points on one or the other line to span the polygon. Is probably very complex to implement? I'll leave it here in case someone is bored ;-)

Version: **ScottPlot 4.1.8-beta**

Thanks!

**Comment by bclehmann** [comment]
I'm confused as to what you mean, the following requirements are present:
- `xs1.Length` must be equal to `ys1.Length` or it is not a valid curve.
- Similarly, `xs2.Length` must be equal to `ys2.Length` or it is not a valid curve.

I don't see anything in the code which would necessitate that the length of `xs1` be the same as `xs2` or anything like that.

**Comment by AlgoExecutor** [comment]
Thank you for your feedback @bclehmann. You are right I was a bit confused . `xs1` and `ys1` have the same number of elements as `xs2` and `ys2`. So far so clear and sorry for the confusion.

The case that both lines have different number of input points should be considered. That is my main concern here. As you said, if the minimum number of points is given a polygon should be built. In my case it is about lines with about 20K and 2K points. 

So this is the relevant exception:
System.IndexOutOfRangeException: **Index was outside the bounds of the array.**
   at ScottPlot.Plot.AddFill(Double[] xs1, Double[] ys1, Double[] xs2, Double[] ys2, Nullable`1 color)
   at ExchangePlotter.InteractivChart.AddData(ChartInput ci) in d:\Code\ExchangePlotter\InteractivChart.cs:line 79

**Comment by bclehmann** [comment]
I tried this and I had no issues:

Code: 
```cs
double[] xs = DataGen.Range(0, 10, .1, true);
double[] xs2 = DataGen.Range(0, 20, .1, true);
double[] ys1 = DataGen.Sin(xs);
double[] ys2 = DataGen.Cos(xs2);

plt.AddFill(xs, ys1, xs2, ys2);
```

Result:
![image](https://user-images.githubusercontent.com/8635304/108570779-ecb2cb00-72cb-11eb-811e-61b85af79e7c.png)

In this case `xs1` and `ys1` have length 10, while `xs2` and `ys2` have length 20.

**Comment by AlgoExecutor** [comment]
Thank you @bclehmann for the great support. I checked my code again and found an error on my side :no_mouth:. The result now looks similar to yours. Sorry for the confusion. Here are some more constructive suggestions:

1) Is it possible to cut the area where there is no overlap? In your example after 10 to 20.
2) Is it possible to add the area to the legend via label? 
3) Is it possible to make the area transparent?

Thanks for your patience!

**Comment by AlgoExecutor** [comment]
Addition to point 1) 
I just realize that I have it in my own hands to simply cut off the values in the input. This would be the simple solution. The question would be, why does the function try to calculate a polygon when there is no overlap? Especially relevant at the ends. Here is an example at the beginning:
![image](https://user-images.githubusercontent.com/79081847/108622402-daa26b00-7438-11eb-91c5-3dd65f23b6d9.png)

Since there is no overlap to `xs1`, `ys1 `it seems to use the start & end point for `xs2`, `ys2 `as the basis for the calculation? Kind of puzzles me. I wouldn't plot the range at all, or maybe that makes sense in other scenarios? I can be wrong ;-)

**Comment by bclehmann** [comment]
For 1) It plots between curves by creating a closed polygon out of the two curves. In this situation that polygon intersects itself. The only alternative I can think of is to only create the polygon where the x-value overlap (i.e. ignore the second half of `xs1` and `ys1` in the example I gave). I don't particularly like that alternative because in my mind that's not the behavior I would expect in this situation.

For 2), `AddFill` returns a `PlottablePolygon` which has a `Label` field that you can edit and can show up in the legend.

For 3) I believe you can simply pass in a colour to `AddFill` with whatever degree of opacity you want (i.e. the alpha channel can be set to 0 for full transparency or 255 for full opacity or anywhere in between).

**Comment by AlgoExecutor** [comment]
Thank you @bclehmann for the quick feedback and explanation. Than i think we can close the ticket. I know how i can do it! 👍
