### ISSUE TITLE
Dot Plots, Lollipop and Cleveland Dot Plots

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#817]
**What can we do to make ScottPlot better?**
The dot plot is a version of a bar plot that's easy to draw by hand or on a typewriter:
![image](https://user-images.githubusercontent.com/8635304/108660943-58419780-7488-11eb-855e-fc51f5940f45.png)

These aren't very common in computer-generated graphics as they're generally not as appealing as bar plots. However they have some more interesting cousins:

The lollipop plot is very similar to a bar plot but (arguably) more visually interesting:
![image](https://user-images.githubusercontent.com/8635304/108661463-1b29d500-7489-11eb-9788-3c86333b6d34.png)

And the Cleveland Dot Plot allows plotting pairs of data more clearly than either stacked or side-by-side bar plots:
![image](https://user-images.githubusercontent.com/8635304/108661513-3bf22a80-7489-11eb-9598-6d78c424acb6.png)
![image](https://user-images.githubusercontent.com/8635304/108661533-46acbf80-7489-11eb-81af-04b0984aa4fa.png)

As you can see the Cleveland Dot Plot shows paired data more clearly than the same data in bar plots. Customizable markers would probably be a good idea here as well.

I suggest these as one issue because they're all pretty simple and they're quite similar. Unintuitively, the dot plot may be the hardest one to implement because one has to use an integer number of dots, requiring a way of determining an optimal scale. 

There _is_ a janky way to do this where you use a `TextureBrush` using a tiling image of dots which you can then draw as if it were a bar plot.

It may be difficult to prevent dot plots from flickering when zoomed in and out as the number of dots may change.

The [ScottPlot Roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) may provide additional context regarding current goals and future directions.

**Comment by swharden** [comment]
I like the idea! Let's keep most conversation in #842, but responding to a few things above:

> Unintuitively, the dot plot may be the hardest one to implement because one has to use an integer number of dots, requiring a way of determining an optimal scale.

As noted in https://github.com/ScottPlot/ScottPlot/pull/842#issuecomment-787581391, this would be easier if `DotPlot` were its own plot type that had `int[] values`. It's a pretty uncommon plot type though, so there's probably low motivation to implement it now compared to some of the other possible tasks at hand.

> There is a janky way to do this where you use a TextureBrush using a tiling image of dots which you can then draw as if it were a bar plot.

In general I favor drawing primitive shapes whenever possible. It may be a while off, but eventually I intend to explore options for using different rendering systems (like ImageSharp and SkiaSharp + OpenGL) so ScottPlot can be used in environments that don't support GDI (like Blazor and Xamarin), so avoiding special GDI rendering features will make this easier when that time comes.

**Comment by swharden** [comment]
merged #842
