### ISSUE TITLE
How to deeply copy a plot and show it in a new window

### ISSUE THREAD

**Issue by saklanmazozgur** [ScottPlot/ScottPlot#819]
Hello,

I have a graph with a home screen. I want to open this chart in new window. I can open the chart in a new window, but as data comes to the chart on the home page, the data in the window I just opened is refreshed.

If I don't click on the chart, the renewal doesn't occur. When I click on any point of the graph with the mouse, it prints the data on the main screen.

How can I prevent this? The code I use to open in a new window is as follows.

```
var AxisX_Copy = HpsvAxisX_Graphic.plt.Copy();
AxisX_Copy.Ticks(dateTimeX: true, dateTimeFormatStringX: ("HH.mm.ss"));
AxisX_New_Window = new WpfPlotViewer(AxisX_Copy);
AxisX_New_Window.Show();
```

Note: I do not want the data to be refreshed. The user can view the newly opened graphic as it is.

**Comment by swharden** [comment]
Hi @saklanmazozgur,

It sounds like you want to create a new [`WpfPlotViewer`](https://www.fuget.org/packages/ScottPlot.WPF/4.1.9-beta/lib/netcoreapp3.1/ScottPlot.WPF.dll/ScottPlot/WpfPlotViewer) such that you can call its `Render()` method to force it to redraw after you update the underlying data.

I'm coding in the browser here, but from your code example I think you can do something like this every time your data updates:

```cs
Window SecondaryPlotViewerWindow;

void LanuchPlotInOtherWindow()
{
    var secondaryPlot = originalPlot.plt.Copy();
    secondaryPlot.Ticks(dateTimeX: true, dateTimeFormatStringX: ("HH.mm.ss"));
    SecondaryPlotViewerWindow= new WpfPlotViewer(secondaryPlot);
    SecondaryPlotViewerWindow.Show();
}
```

```cs
void RedrawOtherWindowWithLatestData()
{
    SecondaryPlotViewerWindow.AxisAuto();
    SecondaryPlotViewerWindow.Render();
}
```

Let me know if this helps address your issue, and if you have working code feel free to post it here! I'm interested to learn what you discover.

**Comment by saklanmazozgur** [comment]
Unfortunately I could not. First of all, `AxisAuto  `and `Render  `in the `RedrawOtherWindowWithLatestData ` function are not Window properties. I cannot access those functions. Also I'm not sure how calling these two functions will prevent refreshing.

I said maybe I can do it by calling the `AxisZ_Copy.RenderLock();` function. When I call it this time it freezes on the command to open the chart in new window.


Note: I think I misrepresented myself. I don't want the graph to be refreshed in the newly opened window.

**Comment by swharden** [comment]
> AxisAuto and Render in the RedrawOtherWindowWithLatestData function are not Window properties

Thank you for pointing-out this error! I mentioned that code example was written in the browser, so to answer this properly I'll give it a try in Visual Studio when I have a little more time to look into it further, then post what I discover here.

In case you try to figure it out before I get to it, the main point here is that you can force plots to redraw in the screen by calling the user control's `Render()` method. If you can call your new window's `WpfPlot1.Plot.AxisAuto()` method and `WpfPlot1.Render()` method, your problem will probably be solved.

**Comment by swharden** [comment]
> I said maybe I can do it by calling the AxisZ_Copy.RenderLock(); function. When I call it this time it freezes on the command to open the chart in new window. I think I misrepresented myself. I don't want the graph to be refreshed in the newly opened window.

Hey @saklanmazozgur, "how to force a render in a newly created window" is a topic I will continue to explore (as indicated in my last message), but from your message here it seems this is not actually your goal. Unfortunately I don't fully understand your goal from this description.  Can you re-state your goal differently so I may be able to better understand it?

If your question is "how can I prevent the user from zooming/panning with the mouse?", the user control has a `Configuration` class with public fields that control if/how the user can manipulate the plot, and this may help answer your question.

**Comment by swharden** [comment]
> I have a graph with a home screen. I want to open this chart in new window. I can open the chart in a new window, but as data comes to the chart on the home page, the data in the window I just opened is refreshed. How can I prevent this? The code I use to open in a new window is as follows.

```cs
var AxisX_Copy = HpsvAxisX_Graphic.plt.Copy();
AxisX_Copy.Ticks(dateTimeX: true, dateTimeFormatStringX: ("HH.mm.ss"));
AxisX_New_Window = new WpfPlotViewer(AxisX_Copy);
AxisX_New_Window.Show();
```

Hey @saklanmazozgur, sorry for the triple post. Your question may be "If I plot data from an array and show that plot in a new window, then change the values in that array later, those changes appear in the plot in the new window. How do I prevent this?"

Notice that `HpsvAxisX_Graphic.plt.Copy()` copies the plot (not the data itself), so manipulations to the original data will always appear in all plots that point to that original data source (typically a double array). If you want different plots to point to different data sources (different arrays), don't copy the plot. Instead, create a copy of your data as a new array and plot that in a new window.

I hope this helps!
Scott

**Comment by saklanmazozgur** [comment]
Hello, actually the situation you mentioned in the third post is my problem. Is it possible to add data on the chart directly to an array? Is there an easy way to do this? Because when I type the data the array is running in a separate thread and it will make things difficult for me.

I wondered if there was an easy way to get the data directly in the chart. Thank you for your time.

**Comment by swharden** [comment]
Hi @saklanmazozgur, 

I'm prioritizing some other issues currently so it's unlikely this is going to get solved quickly. I noted this topic in the triage list so it may be gotten to eventually, but for now I'm going to close this issue since I don't have the resources to actively work on it at this time.
