### ISSUE TITLE
 The chart title and axis text look blurry.

### ISSUE THREAD

**Issue by saklanmazozgur** [ScottPlot/ScottPlot#820]
Hello, I have a problem with blurry texts which is a common problem in wpf. Titles and text in graphics look blurry.

Unfortunately, the following commands I applied to textblocks did not have any effect.

```cs
TextOptions.TextFormattingMode="Display" TextOptions.TextRenderingMode="ClearType"
```

![image](https://user-images.githubusercontent.com/4165489/108850566-7fe04f00-75b1-11eb-91f6-e343fc7fb175.png)

**Comment by swharden** [comment]
Hi @saklanmazozgur, 

Text rendering is handled by `System.Drawing` so we don't have much control over how it is rendered. You could disable anti-aliasing [ScottPlot FAQ: Anti-Aliasing](https://swharden.com/scottplot/faq/anti-aliasing/) but this would probably make the image look worse.

A better option could be to not populate the `XLabel`, `YLabel`, and `Title`, but instead surround your `WpfPlot` with actual `Label` elements in your WPF layout. This will give you full control over that text, and is guaranteed to look nice even in conditions that use things like display scaling.

Hope it helps!
Scott
