### ISSUE TITLE
How to set view limits (axis boundaries) in ScottPlot 4.0

### ISSUE THREAD

**Issue by YUXI07** [ScottPlot/ScottPlot#821]
Hi, I can't find a similar code about view limit.

```cs
formsPlot1.Plot.SetViewLimits(0, 50, -1, 1);
```
In scottplot 4.0.48, are there related codes?

**Comment by swharden** [comment]
Hi @YUXI07, 

In ScottPlot 4.0 you can call `Plot.AxisBounds()` to limit the user's ability to zoom out beyond certain limits. Its function signature is:

```cs
public void AxisBounds(double minX = -Infinity, double maxX = Infinity, double minY = -Infinity, double maxY = Infinity)
```

https://www.fuget.org/packages/ScottPlot/4.0.48/lib/netstandard2.0/ScottPlot.dll/ScottPlot/Plot
