### ISSUE TITLE
Add option to customize tick density (add padding to tick labels)

### ISSUE THREAD

**Issue by ChrisAtVault** [ScottPlot/ScottPlot#828]
Hey guys,

I wonder if there is any option for setting the minimal or maximal Tick distance - even though in my current project I am only interested in setting a minimal Tick distance, having both would be pretty neat. 

Using `Plot.XAxis.ManualTickSpacing` does not seem to be the best option as it clashes with zooming in and out. Similar to  #725.

In the picture below `Plot.XAxis.TickLabelFormat($"dd.MM.yy {Environment.NewLine} hh:mm:ss", true)` was used instead of  `Plot.XAxis.ManualTickSpacing`.

Cheers,
Chris 

![image](https://user-images.githubusercontent.com/79156810/109028741-68dd5200-76c2-11eb-8514-ad69ff27b04d.png)
PS: Keep up the good work!!

**Comment by swharden** [comment]
Hi @ChrisAtVault, 

This isn't easy presently, but it's a good idea to add some way for the user to customize this. I think what I would add is `public int TickLabelPadding` which would be extra padding (in pixels) to request for each label (beyond that already determined based on the size of the measured label). It would be `0` by default, but increasing this number would result in tick labels having more space between them.

I'll look into this in more depth in the next few days! 
Note: tick label measurement was recently worked on (#591).

**Comment by bclehmann** [comment]
Worth noting that customizing tick label padding is different from setting a min or max distance between ticks. They're both useful for the same reasons and to a certain extent you can change padding to change the min/max distance between ticks, but they're not the same thing.

**Comment by swharden** [comment]
> Worth noting that customizing tick label padding is different from setting a min or max distance between ticks

Good point! Another option too I almost mentioned originally is we could have a `TickSpacingMultiple` which defaults to `1.0` but increasing it adds more distance. This method still incorporates label size measurements, and it another way to visually separate the labels more.

Maybe we should think more about what metric makes the most sense for the user to tweak, and why exactly the user would want to control spacing. My thinking is that the user really just wants to space-out the labels some more, rather than actually define a distance in pixels, but I'm open to suggestions!

**Comment by ChrisAtVault** [comment]
For instance, I need this option to allow the user to zoom in/out of the plot. As seen in the image attached to the ticket, zooming in/out on a datetime scatterplot with dates as ticklables creates whole lot of unnecessary ticks/major grid lines. 

Being able to set some sort of:
`// minimal/maximal distance between ticks`
`plt.XAxis.TickDistance(MinimalTickDistance: null, MaximalTickDistance: null)`
`plt.XAxis.TickDistance(MinimalTickDistance: null, MaximalTickDistance: null, ScottPlot.Ticks.DateTimeUnit spacingDateTimeUnit)`

Another idea would relate to #597, where one could define the "minimal" major tick:
`var xTicks = plt.GetSettings(false).XAxis.Ticks;`
`xTicks.MajorGridDistance(MinimalDistance: null, MaximalDistance: null)`
`xTicks.MajorGridDistance(MinimalDistance: null, MaximalDistance: null, ScottPlot.Ticks.DateTimeUnit spacingDateTimeUnit)`

**Comment by swharden** [comment]
Hi @ChrisAtVault and @bclehmann, I made some progress in #925

## More Work is Required

Working in the `TickCollection` module today I'm reminded that the tick system could benefit from some refactoring. I'll probably focus on some of the more immediate documentation-related issues for the next few days, but soon I hope to start reworking the tick system to make it easier to implement some of these advanced tick customization features. Some of the requested features above are very difficult to implement at this time, and I think I need to deeply refactor this module before doing a good job adding support for these features. I'm adding this topic to the triage list so I can get to it after ScottPlot 4.1 is released, documented, and stabilized. I added a few extra methods tonight which can get some of the job done now.

## Tick Density
```cs
var plt = new ScottPlot.Plot(600, 400);
plt.AddSignal(DataGen.Sin(51));
plt.AddSignal(DataGen.Cos(51));

plt.XAxis.Label("Lower Density Ticks");
plt.XAxis.TickDensity(0.2);

plt.YAxis.Label("Higher Density Ticks");
plt.YAxis.TickDensity(3);
```
![image](https://user-images.githubusercontent.com/4165489/112920043-2d291400-90d6-11eb-85c2-ec10f637fa6e.png)

## Minimum Tick Spacing
As of right now, DateTime axes are not supported.

```cs
var plt = new ScottPlot.Plot(600, 400);
plt.AddSignal(DataGen.Sin(51));
plt.AddSignal(DataGen.Cos(51));

plt.YAxis.MinimumTickSpacing(1);
plt.XAxis.MinimumTickSpacing(25);
```
![image](https://user-images.githubusercontent.com/4165489/112922281-39af6b80-90da-11eb-82dd-38658d2c709f.png)
