### ISSUE TITLE
Manual tick labels are wrong when some ticks are outside the data area

### ISSUE THREAD

**Issue by ohru131** [ScottPlot/ScottPlot#829]
When the set value goes out of the display area, the position of the manual scale label shifts.

Example of this cookbook
https://swharden.com/scottplot/cookbooks/4.1.6-beta/category/advanced-axis-features/#manual-tick-labels

![OK](https://user-images.githubusercontent.com/79614497/109090095-c8d10880-7755-11eb-9dc0-5d41ff1bd630.png)
![NG](https://user-images.githubusercontent.com/79614497/109090087-c53d8180-7755-11eb-9c97-3ad6f7899946.png)

**Comment by swharden** [comment]
Thanks for pointing this out @ohru131! I think this issue was caused by https://github.com/ScottPlot/ScottPlot/commit/c3959a62e6221891332e46edd52186c115a13cfc#diff-7cd6b7e0052921f4f3505e06626b7bc81231f798c9bba395075ef9daf3a8b513
