### ISSUE TITLE
Improve XML doc strings for OHLC.GetBollingerBands() and OHLC.GetSMA()

### ISSUE THREAD

**Issue by ticool** [ScottPlot/ScottPlot#830]
I got an array of 300 items, when im using GetBollingerBands and GetSMA i need to enter a (int points), the description says "Numbers of points to analyse backwars in time". When i enter 5 i got 295 items in arrays instead of the last 5.

```cs
(double[] xs2, var sma, var bolL, var bolU) = CandlePlot.GetBollingerBands(5);
(double[] xs, double[] ys) = CandlePlot.GetSMA(5);
```

![image](https://user-images.githubusercontent.com/393970/109092362-6390ff00-76e4-11eb-904a-155467dd6a89.png)
![image](https://user-images.githubusercontent.com/393970/109092497-a18e2300-76e4-11eb-9c7e-17aecd125c52.png)

**Comment by swharden** [comment]
I'll explain what's happening a different way, and let me know if this makes sense to you. If there's a way I can describe it in the docs to make it more intuitive, let me know!

First we recall that Bollinger bands just report the moving-window mean (SMA) plus and minus twice the standard deviation. The size of this window indicates how much time is analyzed to create the SMA. If the window is 5, that means each point of the SMA curve will be the average of 5 points (the average of that value and the 4 values before it).

* Assume your OHLC data has `300` points and each represents a day
* `GetBollingerBands(5)` will calculate Bollinger bands _for your whole OHLC dataset_, where every point represents the mean/std of 5 days
* It's not possible to calculate the 5 day mean for the first 5 days, so your output array will be missing the first 5 data points. This is why the output is length 295, not length 300

Does this help answer your question?

**Comment by ticool** [comment]
Ok Great thx for the help ! I used it the wrong way, i tought it returns the last 5 caculated value of my current Bollinger or Sma. It return a new calculated Bollinger or Sma with the defined points,  like when we create a Finance.Bollinger and we set a period : 

![image](https://user-images.githubusercontent.com/393970/109095969-b40b5b00-76ea-11eb-8d5d-065249656086.png)

**Comment by swharden** [comment]
Thanks for reporting this @ticool!

I added more clear XML documentation strings which I hope will make this easier to figure out in the future:

https://github.com/ScottPlot/ScottPlot/blob/1c2e7abc747c0dbba900c149175e7ede7b148502/src/ScottPlot/Plottable/FinancePlot.cs#L254-L270

https://github.com/ScottPlot/ScottPlot/blob/1c2e7abc747c0dbba900c149175e7ede7b148502/src/ScottPlot/Plottable/FinancePlot.cs#L272-L287
