### ISSUE TITLE
Multi-Axis Bar-Line demo or cookbook?

### ISSUE THREAD

**Issue by lonnietc** [ScottPlot/ScottPlot#834]
Hello,

I have recently found the ScottPlot code, cookbook and demo which are an AMAZING piece of work for which I will mind many uses to be sure.

While looking through the information and demo to get a feel for things, I had a current particular interest in mind which is that of a combination Bar-Line multi-axis chart that would could display a bar graph with a line graph that had vertical axes on the left and right, while a time axes on the bottom that unified them both.

Did I miss something in the demo, cookbook, or documentation that showed how to do this as I am sure that it is possible given the capabilities that this wonderful code can do. 

Cheers and have a great day

**Comment by swharden** [comment]
Hi @lonnietc, I'm happy to hear you enjoy ScottPlot!

> combination Bar-Line multi-axis chart that would could display a bar graph with a line graph that had vertical axes on the left and right, while a time axes on the bottom that unified them both.

This should be possible using the left axis (axis index 0) and right axis (axis index 1) to create a bar plot and scatter plot, respectively.

You may find this FAQ section helpful:
https://swharden.com/scottplot/faq/multi-axis/#plot-on-a-secondary-axis

Also this section of the cookbook:
https://swharden.com/scottplot/cookbooks/4.1.9-beta/category/multi-axis/#primary-axes

Let me know if this doesn't get you where you need to do! If you find a solution, you're welcome to follow-up here with the code you created and a screenshot of the output to help future Googlers learn how to do the same 👍
