### ISSUE TITLE
OnAxesChanged issue when resetting datas !

### ISSUE THREAD

**Issue by ticool** [ScottPlot/ScottPlot#835]
HI, i got an interface with 3 graphs in same time. I added the OnAxesChanged so they move together on the X axe !
My problem comes when im trying to change the data  while using this functionality (Clear the array and feedback new datas). Example : My graph data are based on 5min, when i change it to 1min and the OnAxesChanged  is called, there are no more graph rendered. When i comment OnAxesChanged it works fine ?? there is a render in the OnAxesChanged  method and i got others FormsPlot.Render after the datas is changed ! Any ideas ?

```cs
protected override void OnLoad(EventArgs e)
{
    FormsPlots = new List<FormsPlot>{ formsPlot1, formsPlot2, formsPlot3 };
    foreach (var fp in FormsPlots)
        fp.AxesChanged += OnAxesChanged;
}

private void OnAxesChanged(object sender, EventArgs e)
{
    FormsPlot changedPlot = (FormsPlot)sender;
    var newAxisLimits = changedPlot.Plot.GetAxisLimits();

    foreach (var fp in FormsPlots)
    {
        if (fp == changedPlot)
            continue;

        // disable events briefly to avoid an infinite loop
        fp.Configuration.AxesChangedEventEnabled = false;
        fp.Plot.SetAxisLimitsX(newAxisLimits.XMin, newAxisLimits.XMax);
        **fp.Render();**
        fp.Configuration.AxesChangedEventEnabled = true;
    }
}
```

After some tests... I just saw that the time line reset to 1899 i dont know why probably the changedPlot.Plot.GetAxisLimits() is empty ??

**Comment by ticool** [comment]
Normal value

![image](https://user-images.githubusercontent.com/393970/109248665-34e25980-77b4-11eb-95cf-86d2f02e354a.png)

Reset by itself

![image](https://user-images.githubusercontent.com/393970/109248692-43307580-77b4-11eb-9747-e5979806232d.png)

**Comment by ticool** [comment]
I found the solution  !  I just add  formsPlot1.Plot.AxisAuto();  to my first FormsPlot.Render !

**Comment by StendProg** [comment]
Hi @ticool, thanks for report,

Сould you provide an additional code containing the process of updating the data array and the `Plottable` type that you are using? The ScottPlot version will also be very helpful.

**Comment by ticool** [comment]
The problem occurs with the Candlestick graph, the Bar and scatter graph seem to works ! I think the problem comes from resetter value in candlestick graph it reset the X date position to 1899. When i scoll back to 2021 the Candle stick graph looks stretch but the two others look great...

I fix my issue simply by adding if defaultValue.

```cs
            FormsPlot changedPlot = (FormsPlot)sender;
            var newAxisLimits = changedPlot.Plot.GetAxisLimits();

            bool defaultValue = newAxisLimits.XMax == 10 && newAxisLimits.XMin == -10 && newAxisLimits.YMax == 10 && 
            newAxisLimits.YMin == -10;

            if (!defaultValue)
            {
                foreach (var fp in FormsPlots)
                {
                    if (fp == changedPlot)
                        continue;

                    // disable events briefly to avoid an infinite loop
                    fp.Configuration.AxesChangedEventEnabled = false;
                    fp.Plot.SetAxisLimitsX(newAxisLimits.XMin, newAxisLimits.XMax);
                    fp.Render();
                    fp.Configuration.AxesChangedEventEnabled = true;
                }
            }
```

**Comment by ticool** [comment]
![image](https://user-images.githubusercontent.com/393970/110220609-bad96100-7e94-11eb-9b44-63e58edabe4f.png)

![image](https://user-images.githubusercontent.com/393970/110220640-e3f9f180-7e94-11eb-8f20-784bfc193b47.png)

![image](https://user-images.githubusercontent.com/393970/110220656-0be95500-7e95-11eb-933b-0cc93725b636.png)

**Comment by StendProg** [comment]
Hi @ticool,
I assumed that the problem is related to how exactly you update the data, when you call Render on an empty object (After Clear() or something similar) for which it is impossible to calculate the boundaries, the default axis values are used. 0 recalculated in ODateTime just gives the year 1899.
Maybe you should just somehow bypass this moment so that the axis change event is not called for an empty chart. it's hard to say something more without seeing the update process itself, in any case I'm glad that you managed to solve the problem.
