### ISSUE TITLE
Visual Candlestick Border glitch at certain zoom level

### ISSUE THREAD

**Issue by AlgoExecutor** [ScottPlot/ScottPlot#837]
Hello @swharden & Team,

thank you very much for the great work. I like the new candlestick feature to control the wick color :-) 
While playing with the new code I noticed the following: 
After a certain zoom level - when you zoom out - the candle body gets smaller but the border keeps it size. This leads to white areas at the top and bottom of the candle. Here is a picture:
![image](https://user-images.githubusercontent.com/79081847/109383420-b2a68200-78e6-11eb-91e4-9229462cc94e.png)

Zoomed in:
![image](https://user-images.githubusercontent.com/79081847/109383428-bdf9ad80-78e6-11eb-99e6-2e29e969a6d1.png)

The best way to observe this is when Anti Aliasing is turned off.
Version: **ScottPlot 4.1.9-beta**

```cs
var candlePlot = formsPlot.Plot.AddCandlesticks(pData.ToArray());
candlePlot.WickColor = Color.DimGray;
formsPlot.Plot.XAxis.DateTimeFormat(true);
formsPlot.Configuration.Quality = QualityMode.Low;
formsPlot.Render();
```

Thank You :)

**Comment by swharden** [comment]
Hey @AlgoExecutor thanks for reporting this!

I think I fixed it by improving this line:
https://github.com/ScottPlot/ScottPlot/blob/1c2e7abc747c0dbba900c149175e7ede7b148502/src/ScottPlot/Plottable/FinancePlot.cs#L215
It had 1px extra vertical padding that I don't think is required, and seems to have caused this problem

**Comment by AlgoExecutor** [comment]
Thank you @swharden for this quick fix!
