### ISSUE TITLE
Consider using data objects for live plots

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#841]
**The purpose of this issue is to explore the use use of data objects to make it easier to display "live" plots where the data is frequently updated.** This mostly applies to Scatter plots, Signal plots, and Finance plots. Scatter plots will be explored first, and this new implementation may replace `ScatterPlotList`. This topic was initially explored in #815

### Rationale

**ScottPlot users frequently encounter difficulty when trying to figure-out how to update/add data in live plots.** Live plots are possible using tricks as described on the [FAQ: Live Data](https://swharden.com/scottplot/faq/live-data) page. However, this task is difficult because the primary plot types store data in fixed-length arrays and do not have control over when renders occur. Use of a data object would abstract the task of data storage and array management from the user, simplifying this task. It would also improve encapsulation for data management (validation, axis limit detection, min/max detection, and tree management) and separation of concerns (data objects would manage data, plottables would manage style and rendering).

### Data Object Responsibilities
* Store data in private arrays
* `Add()`, `AddRange()`, and `Clear()` methods update/resize/replace arrays as needed
* Data validation (e.g., ensuring data does not contain `double.NaN`)
* Axis limit detection
* Range min/max detection for Signal plottables
* Tree management for SignalConst plottables

### Example Use

```cs
// user stores and interacts with the data object, not the plottable
readonly ScatterData myData = new ScatterData();

void Init()
{
    formsPlot1.Plot.AddScatter(myData);
}

void OnNewData()
{
    myData.AddRange(newXs, newYs);
    formsPlot1.Render();
}
```

**Comment by bclehmann** [comment]
I would hope any implementation would be pretty extensible for the user. Obviously it would be a very good idea to continue to allow arrays, but also to allow a user to create their own data objects (or even be compatible with existing classes). Currently the only requirements for data objects are that they have an indexer taking an integer, i.e. `T this[int i]`, and that they implement `IEnumerable` (for LINQ). It would also be a very good idea for them to implement their own `Count` property, as the one on `IEnumerable` is O(n), and this is a very commonly used property and generally can be grabbed in constant time.

Now if we only want to allow a user to create their own data objects, we can create our own interface:

```cs
interface IDataObject<T>{
    int Count {get;}
    T this[int i];
    IEnumerator<T> GetEnumerator();
    IEnumerator GetEnumerator(); // IEnumerable<T> implements the non-generic IEnumerable for compatibility reasons
}
```

Unfortunately, regular arrays do not implement this interface. There is some witchcraft you can do with reflection or the `dynamic` keyword to mimic duck typing, but I don't think either of those are good ideas. You could create implicit conversions from `T[]` to `MyArrayWrapperClass<T>` or similar which would also allow (a form of) duck typing, which is alright but not ideal as it creates poorer performing code as well as more confusing method signatures and debugger output.

One option which does not involve duck typing is method overloading, which is a fine solution but it does run the same risks with any duplicate or near-duplicate code, a change in one method may not be applied to another. This can be alleviated by having them both delegate to another method, but this likely means either duck typing or conversion as this new method has to handle multiple types. Not ideal, but certainly workable.

Lastly, one could use an existing interface which is compatible with the `Array` class. If you look at the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.array?view=net-5.0) one notices that it implements `System.Collections.IList`, which in my opinion offers an elegant solution. We get all of the properties we hoped to:

- Compatible with normal arrays
- Extensible by the user and the library
- Compatible with existing classes

While it doesn't say it there, in this [article ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/generics-and-arrays)it says arrays which start at zero (in practice almost all of them) also implements `IList<T>`:

> In C# 2.0 and later, single-dimensional arrays that have a lower bound of zero automatically implement IList<T>.

If someone wants to get a live data app running they can just drop in a `List<double>` and not think about it again. If they want to tune something that the `List<T>` class doesn't offer (such as the [allocation algorithm](https://github.com/ScottPlot/ScottPlot/pull/815#discussion_r579897964)) they can write their own reasonably quickly. The `IList<T>` interface is larger than the example `IDataObject` interface I wrote above, but not by too much. What's more, they can use any existing methods that take in `IList<T>` either in the BCL or in third-party libraries without converting.

If you're worried about what to do with fixed or capped-size collections such as circular buffers, calling `Add()` on an array throws an exception. The class implements `IList<T>`, it just treats that operation as invalid. I'm taking this as a cue that this is how Microsoft wants us to treat such things.

**Comment by bclehmann** [comment]
`IList<T>` may not be particularly elegant for heatmaps as they require contiguous memory for their marshalling. Not to mention 2D arrays only implement `IList`. However, I think this is less of a concern as heatmaps are not expected to be resized, and the updating of heatmaps already requires significant copying, so one probably wouldn't gain much.

**Comment by bclehmann** [comment]
A reliable interface would also make `Memory<T>` or `Span<T>` wrapper classes easier to implement. It may also make sense to create an interface for contiguous memory, which would allow heatmaps to use `Memory<T>` or `Span<T>`.

**Comment by swharden** [comment]
The use of data objects (possibly using Memory/Span under the hood) is an important topic I want to explore carefully in the future. For now my focus for the next few weeks will be getting version 4.1 out of data and improving the documentation, so I've added this topic to the triage list and will return to it in the future.

Thank you everyone for your input!
