### ISSUE TITLE
PiePlot with individual text colors

### ISSUE THREAD

**Issue by Timothy343** [ScottPlot/ScottPlot#844]
Hi Scott,
currently the PiePlot class allows individual fill colors, but no font colors.

```
    public PiePlot(double[] values, string[] groupNames, Color[] colors)
    {
        SliceFillColors = colors;
        SliceFont.Color = Color.White;

```
For a good contrast, a possibility to choose proper label colors would be helpful. May I ask you to add this to the class?

**Comment by swharden** [comment]
Hi @Timothy343, thanks for reporting this! I just merged this feature in #883 and will release it on NuGet tonight and it will show up in the cookbook. Thanks for the suggestion!
