### ISSUE TITLE
Example LiveData.

### ISSUE THREAD

**Issue by FoxTes** [ScottPlot/ScottPlot#845]
Hi Scott.
I am trying to plot a graph that displays data (versus time) i.e. analogue of the LiveData type.
Unfortunately, in the new version, I did not find an example.
As an example, I am showing another graph.

Can you find an example somewhere to do the same? Thank!
![constant](https://user-images.githubusercontent.com/55885862/109654795-0d0c4080-7b7c-11eb-8bff-cf499c49f993.gif)

**Comment by swharden** [comment]
Hi @FoxTes,

There is a new FAQ page which describes how to do this with code examples and downloadable working demos. If this doesn't contain the information you need (or is confusing somewhere) let me know!
https://swharden.com/scottplot/faq/live-data/

Also I recognize this is a common task, so I'm exploring ways to possibly make this easier to do in the future (#841)
