### ISSUE TITLE
Plot.Add.AddBarGroups never returns BarPlots

### ISSUE THREAD

**Issue by Timothy343** [ScottPlot/ScottPlot#847]
Hi Scott,
beta 4.1.9 Plot.Add.AddBarGroups never returns its bars.
```cs
        public BarPlot[] AddBarGroups(string[] groupLabels, string[] seriesLabels, double[][] ys, double[][] yErr)
        {
            ...
            BarPlot[] bars = new BarPlot[seriesCount];
            ...
            // bars is never used
            return bars;
        }
```

**Comment by swharden** [comment]
Hi @Timothy343, thanks for reporting this! @rhys-wootton actually found this issue and fixed it in #839 but I haven't uploaded a new package on NuGet yet. I hope to do this within the next few days! In the interim, the best way to use this new feature is to run ScottPlot from the source code in this repo.
