### ISSUE TITLE
Old versions of ScottPlot have poor support for DPI scaling

### ISSUE THREAD

**Issue by jw-suh** [ScottPlot/ScottPlot#853]
Hello again,

while working with the WPF Control I found that both the right and bottom side of the Control are surrounded by empty but reserved space.
![grafik](https://user-images.githubusercontent.com/79658429/110152137-a25c3e80-7de1-11eb-95cb-e58cfcbb2ea0.png)

As you can see in the code, the button group and the scott plot control are nested in a stackpanel, which only takes as much space as it needs.
```cs

    <StackPanel Background="Black" Margin="5,0" Orientation="Horizontal">
        <WpfPlot Padding="0" DockPanel.Dock="Left" Width="1200" Height="900" MinWidth="1000" x:Name="CtrlPlot"/>

        <StackPanel DockPanel.Dock="Left" Background="Green" Orientation="Vertical">
            <Button x:Name="BtnLine0" Style="{StaticResource BtnLineStyle}" MouseLeftButtonUp="BtnLineX_MouseLeftButtonUp">
                <Label x:Name="LblLine0" Content="Foobar 1" Style="{StaticResource LblLineStyle}"/>
            </Button>
            <Button x:Name="BtnLine1" Style="{StaticResource BtnLineStyle}" MouseLeftButtonUp="BtnLineX_MouseLeftButtonUp">
                <Label x:Name="LblLine1" Content="Foobar 2" Style="{StaticResource LblLineStyle}"/>
            </Button>
            <Button x:Name="BtnLine2" Style="{StaticResource BtnLineStyle}" MouseLeftButtonUp="BtnLineX_MouseLeftButtonUp">
                <Label x:Name="LblLine2" Content="Foobar 3" Style="{StaticResource LblLineStyle}"/>
            </Button>
            <Button x:Name="BtnLine3" Style="{StaticResource BtnLineStyle}" MouseLeftButtonUp="BtnLineX_MouseLeftButtonUp">
                <Label x:Name="LblLine3" Content="Foobar 4" Style="{StaticResource LblLineStyle}"/>
            </Button>
            <Button x:Name="BtnLine4" Style="{StaticResource BtnLineStyle}" MouseLeftButtonUp="BtnLineX_MouseLeftButtonUp">
                <Label x:Name="LblLine4" Content="Foobar 5" Style="{StaticResource LblLineStyle}"/>
            </Button>
        </StackPanel>
```

I figured that this in case a bug with the control and not my style since the black area is still mouse interactive. Zooming and panning is still possible inside that 'empty' space. Also the wpf debugging tool shows it as part of the control element.

I tried to remedy this by disabling the legend and the frame but that did not help either.

**Comment by swharden** [comment]
Hi @jw-suh,

It looks like this may be an issue related to display scaling. Are you using the latest version of ScottPlot? (currently ScottPlot 4.1.9-beta)

**Comment by jw-suh** [comment]
Hey @swharden,

well as it turns out, no i wasn't. I was still at 4.1.5-beta. This did fix my problem but I just noticed a new problem. I am not entirely sure if this came from the update or existed before. I'll just add it here to not spam too many issues:

My graph updates every second and at an irregular basis my lines are drawn very pixelated. This only persists until the graph is redrawn. I am rendering 5 scatterplots with 25 points each, so nothing too extensive i think.

Thank you for your help

**Comment by swharden** [comment]
Hi @jw-suh,

I renamed this issue so it describes your first question, and will close it marking the version upgrade as the answer.

It sounds like you are still having some issues related to how the graphs are being drawn (pixelated). Can you describe this problem as a new issue? A screenshot or video would be really helpful to better understand the problem, and including your source code would be extremely helpful too 👍
