### ISSUE TITLE
Scaling is not restored under resizing in equal-scale mode 

### ISSUE THREAD

**Issue by ricecakebear** [ScottPlot/ScottPlot#857]
_ScottPlot 4.1.09-beta_

In order to display some tool path data in an intuitive way, I try to maintain equal scaling of axes of a `WpfPlot` by calling `Plot.AxisScaleLock()`. It turns out that although the scaling is equal under several resizing operations, the shared scaling could not be restored when the plot was restored to some previous size after downsizing, which leaves the object in a smaller state.
<img src="https://user-images.githubusercontent.com/44994232/110421412-6b837280-80d8-11eb-93da-c38a38f1ea13.gif" width="60%" alt="equal-scale issue">
The above gif was recorded with _Polar axis demo_ of _WPF demo 4.0.22_ and the same can be observed with the one of _4.1.09-beta_.
The reason that I tested with _4.0.22_ is that the scaling change shown in #272 does look as expected, which I believe introduced this mode originally.  In fact, in the same _WPF demo 4.0.22_, the _WpfConfig demo_ works in a more natural way and is shown in the following two gifs (as the behavior is different for x and y resizing).

|  |  |
|-------------|-------------|
|![equal scale issue _3](https://user-images.githubusercontent.com/44994232/110425446-54944e80-80df-11eb-8eef-8a1c5a90210f.gif)|![equal scale issue _4](https://user-images.githubusercontent.com/44994232/110425462-58c06c00-80df-11eb-8330-46b3cc6778c3.gif)|

It seems that two demos use different implementations of equal-scale mode. _WpfConfig demo_ uses the previous implementation `Plot.AxisEqual()` where scaling (`UnitsPerPixel`) of y is applied to both axes. And _Polar axis demo_ uses the newer implementation `Plot.EqualAxis` which adopts the larger one, a strategy inherited by the current implementation `Plot.AxisScaleLock()`.
So is it possible to have the option of maintaining equal scale in the old way? Thanks.

**Comment by StendProg** [comment]
Hi @ricecakebear,

I was also very confused by this effect, but:
If you look carefully, `EqualAxis` uses a slightly different approach, when you decrease any of the axes, your UnitPerPixel decreases, i.e. the entire original graph remains visible, by simply being scaled.
`Plot.AxisEqual()` retains the scale, and the visible points may go beyond the boundaries.

Since when you decrease size, information is lost due to which axis the decrease was, when you increase, the effect you described occurs. The problem of preserving the plottable size when decreasing / increasing becomes unsolvable if we want to maintain a behavior that ensures that all visible points are preserved when change plot size. 
At one time, I made a decision that this is more important.

But it is very important to get feedback, thanks for your report. The ideal solution, as always, would be customizable support for both behaviors, but...

**Comment by ricecakebear** [comment]
Yes, it's good to have options. Another two options off the top of my head would be:
1. Leave the scaling alone;
2. If either or both axex are locked (zoom and pan disabled), the shared scaling would be determined by the largest scaling (smallest `UnitsPerPixel`) that preserves the axis limits of the locked axis(axes); otherwise go with option 1 or the other two options that are discussed above.

**Comment by StendProg** [comment]
Hi @ricecakebear,

Unfortunately, I found time to return to this question just now, I made a PR #933 that allows you to select an axis that will be the source of the equal scale. If you select YAxis it will be close to the old `Control` level behavior as you described.
If you can find time for tests, I would be happy to receive feedback from you,

**Comment by swharden** [comment]
Thanks @ricecakebear for the original suggestion and @StendProg for your PR #933! I got unexpectedly busy this last week so I haven't had much time to work on this, but I'm starting to be more free again and I think I came up with a good solution...

I'm adding an enumeration to define the scale mode:

```cs
void AxisScaleLock(bool enable, EqualScaleMode scaleMode = EqualScaleMode.PreserveY) { /* */ }
```

I agree with @ricecakebear that the present default behavior ("zoom out") is astonishing. I'm changing the default scale mode to be preserve Y which is consistent with previous versions of ScottPlot. These screenshots show all the scale modes available:

### AxisScaleLock: Disabled
![resize-disabled](https://user-images.githubusercontent.com/4165489/114253882-4fdee680-997a-11eb-95e3-5f1077a8ddbe.gif)

### AxisScaleLock: Preserve Y
![resize-preserve-y](https://user-images.githubusercontent.com/4165489/114253885-52414080-997a-11eb-80e2-f611468687b4.gif)

### AxisScaleLock: Preserve X
![resize-preserve-x](https://user-images.githubusercontent.com/4165489/114253888-553c3100-997a-11eb-8624-f82bb862b5b0.gif)

### AxisScaleLock: Zoom Out
![resize-zoom-out](https://user-images.githubusercontent.com/4165489/114253891-579e8b00-997a-11eb-845a-04bbd14963a3.gif)
