### ISSUE TITLE
FormsPlot does not contain a definition for 'Plot'

### ISSUE THREAD

**Issue by kayleejacob1** [ScottPlot/ScottPlot#863]
i am tring the example below and getting the error in the topic of this

 double[] dataX = new double[] { 1, 2, 3, 4, 5 };
            double[] dataY = new double[] { 1, 4, 9, 16, 25 };
            formsPlot1.Plot.AddScatter(dataX, dataY);

**Comment by swharden** [comment]
Hi @kayleejacob1,

Ensure you are using the latest (beta / pre-release) version of ScottPlot. When searching packages with NuGet, ensure the "pre-release" checkmark is checked to let you see the latest versions (currently ScottPlot 4.1).

Let me know if this doesn't do the trick!
