### ISSUE TITLE
improve bar plot cookbook example showing custom labels

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#865]
Today I received an email from jess.jones1@yahoo.com

> Hi
> 
> I'm a C# beginner and I want to do the following (if possible) with scottplot.
> 
> I want to plot 600 bars in a bar graph on the X axis. (the height on Y axis is the value of each bar)
However the demo file has numbers on the X axis, but I want each bar to have a label like "bar 1", "bar 2", ... which appears on the X axis. On the Y axis a number can appear, which is the value of each bar.
Further I want the bar graph to have a scrollbar on the X axis to scroll horizontally to view the 600 bars (so I can only view part of the graph by scrolling)
> 
> Is this possible in scottplot and if yes, can you give me a full code example for windows form please?
With my limited C# experience I can't make it reality :(
> 
> Thx
> Jessica

**Comment by swharden** [comment]
(this post is a copy of my response email)

Hi Jessica,

I'm happy to hear you're learning C# and hope you find ScottPlot useful! I understand your problem: When you make a bar plot, bars are placed at 0, 1, 2, 3, etc. but you want those labels to have text labels "bar 1", "bar 2", etc. 

There is a command you can use to apply custom labels to horizontal ticks: `formsPlot1.Plot.XTicks()` - it accepts an array of strings, and those labels get placed at 0, 1, 2, etc. It is available in ScottPlot 4.1 (currently a pre-release package on NuGet).

I recognize this isn't easy to figure out as there isn't currently a cookbook example of this. I created an issue ticket to track progress toward making one https://github.com/ScottPlot/ScottPlot/issues/865

Regarding a scrollbar, unfortunately I do not think this is possible with ScottPlot. Presently ScottPlot is made to create bitmap images small enough to fit on the screen. There might be some highly advanced hacks that could be used to display extremely wide plots, but I recognize that 600 bars with unique labels may not look great because those labels will overlap if you are not very zoomed in. I wish I had a better suggestion, but I can't think of a way to make this very easy. You could try creating a plot that's 10,000 pixels wide and disabling mouse interaction then putting it inside a scrollable panel or something... not sure how well that would work (or if bitmap size is limited) but it may be worth a try. Hope it helps!

Thanks for your email, and let me know if any other questions pop up along the way!
Best,
Scott

**Comment by swharden** [comment]
Ten minutes later I received a response from jess.jones1@yahoo.com

> THANKS FOR NOTHING F***FACE
> YOUR LIBRARY SUCKS

It seems Jessica is having a bad day, and I sincerely hope it gets better for them.

I think this issue is worth completing, as improving bar plot axis label documentation would certainly benefit this library.

**Comment by kddlb** [comment]
Just so you know, that person has been known to harass software developers:

https://twitter.com/migueldeicaza/status/1333217851763810305 (contains homophobic slurs)

**Comment by swharden** [comment]
Hi @kddlb, thanks for the heads-up! At least I now know that I am not the only one who received uncharitable correspondence after attempting to help this individual. I un-hid comment https://github.com/ScottPlot/ScottPlot/issues/865#issuecomment-797803001 to make this information more discoverable for those who may wish to engage with this person the future.

Have a great week!
Scott
