### ISSUE TITLE
ScottPlot/Style.cs Style not working correctly

### ISSUE THREAD

**Issue by oszymczak** [ScottPlot/ScottPlot#866]
/src/ScottPlot/Style.cs

chart.plt.Style(Style.Seaborn);

when you change  To Style.Seaborn
the following gets set 
    existingPlot.Frame(false);
    existingPlot.XAxis.MinorLogScale(true);
    existingPlot.YAxis.MinorLogScale(true);
 
 changing to another Style does not change what has been set in Style.Seaborn.
 
 case (Style.Control):
    existingPlot.Style(
    figureBackground: SystemColors.Control,
    dataBackground: Color.White,
    grid: ColorTranslator.FromHtml("#efefef"),
    tick: Color.Black,
    axisLabel: Color.Black,
    titleLabel: Color.Black
    );
break;

case (Style.Seaborn):
    existingPlot.Style(
    figureBackground: Color.White,
    dataBackground: ColorTranslator.FromHtml("#eaeaf2"),
    grid: Color.White,
    tick: ColorTranslator.FromHtml("#AAAAAA"),
    axisLabel: Color.Black,
    titleLabel: Color.Black
    );
    **existingPlot.Frame(false);
    existingPlot.XAxis.MinorLogScale(true);
    existingPlot.YAxis.MinorLogScale(true);**
break;

**Comment by swharden** [comment]
wow! This is definitely a bug, thanks for reporting it @oszymczak!

I'll remove these lines:
https://github.com/ScottPlot/ScottPlot/blob/1c2e7abc747c0dbba900c149175e7ede7b148502/src/ScottPlot/Style.cs#L125-L127
