### ISSUE TITLE
How to fix bounds of plots that have a linked axis.

### ISSUE THREAD

**Issue by hhfranzo** [ScottPlot/ScottPlot#872]
Hi,

I'm developing an application where I show a stack of 3 plots. These plots are linking the X axis.
I replicated what I found in the examples, but now I have a problem. The plot don't have the vertical bounds aligned and they move according to the values presented in the Y axis. For instance, if the values of plot 1 have 3 digits and plot 2 has 1 digit values, the disallignment of the Y axes occurs.
In the Many Plots example there's the same issue.

How can I force the 3 plots to keep the vertical boundaries aligned and fixed?

Thanks,
Mauro

**Comment by swharden** [comment]
Hey @hhfranzo, does this FAQ page help answer your question?

https://swharden.com/scottplot/faq/shared-axes/

![shared (1)](https://user-images.githubusercontent.com/4165489/111406544-e0424800-86a8-11eb-8b99-35e4f480df38.gif)
