### ISSUE TITLE
Improve user control documentation & demo application

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#887]
**What can we do to make ScottPlot better?**
In #879 it was pointed out that the `Configuration` object is not documented in the cookbook. This makes sense as the cookbook doesn't cover controls, only the plotting API. Perhaps the demo folders (i.e. WPFDemos, AvaloniaDemos, WinFormsDemos) could be better highlighted alongside the cookbook and/or the API documentation?

The [ScottPlot Roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) may provide additional context regarding current goals and future directions.

**Comment by swharden** [comment]
I'm open to suggestions here! I'm definitely focusing heavily on improving documentation of the core ScottPlot module right now, but I recognize this excludes information about how to do special things with the user controls.

I'm thinking the ScottPlot FAQ could be a place to collect information about user control configuration. I've already started making common pages and most of them have links to download example projects. https://swharden.com/scottplot/faq/ and its source code on https://github.com/ScottPlot/Website

I think individual sample projects are less confusing for new users than one big project with many windows/forms as individual examples. I recognize this structure is harder to maintain though. Do you think that a few good/common demo projects combined with the XML documentation would be enough to communicate the important usage information?

 ScottPlot.Control.Configuration on FuGet:
https://www.fuget.org/packages/ScottPlot/4.1.9-beta/lib/netstandard2.0/ScottPlot.dll/ScottPlot.Control/Configuration

**Comment by bclehmann** [comment]
I think the demos are actually pretty good for showing how to use the library with whichever platform. It's just the source code is not very well advertised for them. I think a FAQ is useful for some things like "how do I get the point closest to (x,y)", but I think that duplicating the demos in the FAQ is unnecessary effort. The FAQ does make things easier to find, but the FAQ answer could just be a link to the demos. 

Perhaps a page with a name like "How to use ScottPlot Interactively" which has the demo code displayed nicely (as opposed to this 2 second codepen thingy):

![image](https://user-images.githubusercontent.com/8635304/112027275-a506a580-8afc-11eb-9a2c-67ab234c7787.png)

One doesn't have to go the spoiler route, for example, the dotnet docs have a pretty nice tabbed thingy:

![image](https://user-images.githubusercontent.com/8635304/112027702-0c245a00-8afd-11eb-85c7-841d31492456.png)
![image](https://user-images.githubusercontent.com/8635304/112027715-10507780-8afd-11eb-8e20-dba129273a6c.png)

Let me know what you think.

**Comment by swharden** [comment]
### Website Documentation of User Controls

> Perhaps a page with a name like "How to use ScottPlot Interactively" which has the demo code displayed nicely

There are a few user control sections to the FAQ page, but I'm not satisfied with their discoverability: https://swharden.com/scottplot/faq/#user-control-interactive-behavior

I'm considering breaking apart the demo application and moving that documentation/code into an expanded section of the website (see below)

### Demo Application

> I think the demos are actually pretty good for showing how to use the library with whichever platform

I largely agree. My hesitations are:
* Many of the demos are redundant or unnecessary now
* It's not easy for a new user to get from a demo to its source code
* I wish each demo were its own simple standalone .NET Project
* I want demos to use actual NuGet packages

> I think that duplicating the demos in the FAQ is unnecessary effort

My plan in starting that was to work toward deleting the monolithic demo application in favor of individual demos, each with a FAQ page that could be linked to. For this to be successful the website needs to be better organized, and demos need to be created for all platforms.

Maybe an intermediate option is to make a nice animated GIF of every demo and show them all in a table on the FAQ page? Each demo would then have its own sub-page where you could see the code, see the demo in action, and easily download the demo's source code as a ZIP. Assuming the source code is trivially easy to download and run, distributing a compiled binary may not even be required.

What do you think about these options? On one hand having a bunch of little projects that use NuGet packages could be a maintenance nightmare, but on the other hand if the API is stable it shouldn't be too bad, and we can automate the process of upgrading dependency versions in all the examples.

**Comment by bclehmann** [comment]
I think several small demos could work but it may entail a lot of unnecessary work, and I'm unsure what one would get out of it.

The easiest option is probably a page that for each demo pulls in the source code and if appropriate shows some screenshots or gifs. Because the demo is the whole file we wouldn't even need to do any fancy parsing like is done for the cookbook.

I think offering compiled binaries is important, as a demo serves a showoffy purpose in addition to documentation. One of the good things about the current demos is that you can see what ScottPlot can do without having to compile or download dependencies or anything. Ideally, the compilation of all the demos can be done by a script or github actions anyways.

**Comment by swharden** [comment]
Trying to find the perfect solution here has really killed my productivity for the last few weeks... I'm dissatisfied with the demo application. The technical aspects of the demos are fantastic, but from an educational perspective it's really hard for new users (especially those new to C#) to locate the source code and figure out how to run it. Downloading the whole repository and running the entire project from source is more complexity than I want. However, an easy solution is not immediately apparent. 

Trying to solve this has prevented me from releasing ScottPlot 4.1 for almost a month. To get this un-stuck I'm going to separate the demo application into two programs, then move on and revisit this after 4.1 is released.
* **ScottPlot Cookbook Demo** - This is in a pretty good place. It's probably what most new users are looking for in a demo anyway.
* **ScottPlot Advanced Control Demos** - This will show corner cases and advanced user control functions. Its source code will continue to be part of the big repo, and I'll kick the can and plan to solve this problem later, after 4.1 is released.

**Comment by swharden** [comment]
After thinking about this more, having all-in-one cookbook/control demos on all 3 platforms is too good to give up!

I still haven't figured out how to solve the source code problem, so my interim solution is to redirect everyone to the website https://swharden.com/scottplot/demo and on that page I can add the most current information about how to locate the source code for each of the demos

![image](https://user-images.githubusercontent.com/4165489/118580102-47d64b80-b75d-11eb-9fb8-f815966d21c7.png)
