### ISSUE TITLE
FormsPlot: forward all PictureBox mouse events

### ISSUE THREAD

**Issue by grabul** [ScottPlot/ScottPlot#892]
Due to the refactoring of the WinForm control by adding a picturebox in the FormsPlot user control the mouse events like OnMouseDown are no more forwarded like in the laste stable release.

A fix would be something like this

```cs
private void PictureBox1_MouseDown(object sender, MouseEventArgs e)
{
    Backend.MouseDown(GetInputState(e));
    base.OnMouseDown(e);
}
```

Or is it by intension to remove that?

**Comment by swharden** [comment]
Thanks for mentioning this @grabul!

`OnMouseMove` is forwarded, but it would be good to forward all mouse events too:
- * `OnMouseDown`
- * `OnMouseUp`
- * `OnDoubleClick`
- * `onMouseWheel`

https://github.com/ScottPlot/ScottPlot/blob/591c80560618787b844e7430c9426c70c83900db/src/controls/ScottPlot.WinForms/FormsPlot.cs#L115-L119
