### ISSUE TITLE
Documenting Setup on non-Windows platforms.

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#899]
**What can we do to make ScottPlot better?**
On Linux and on Mac GDI+ does not come preinstalled. NuGet will not install this for you when it fetches System.Drawing.Common. The solution is to use Mono's implementation, which depending on your package manager will involve something similar to this:

```bash
sudo apt install libgdiplus
```

```bash
sudo apt-get install libgdiplus
```

```bash
brew install mono-libgdiplus
```

etc etc

I don't think it's necessary to give a copy-paste command for every apt, apt-get, pacman, dnf, yum, brew, etc as anyone using a certain package manager (should) know how to install things with it. But bringing to attention the fact that they need to install the package is probably a good idea.

The only thing to be wary of is sometimes the package is libgdiplus, and sometimes mono-libgdiplus. The[ git repository](https://github.com/mono/libgdiplus) has build instructions but unfortunately not any for downloading from a package manager that I can find. Which is unfortunate because it would have been a decent idea to just link there instead.

The [ScottPlot Roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) may provide additional context regarding current goals and future directions.

**Comment by bclehmann** [comment]
I made a PR to address this here: https://github.com/ScottPlot/Website/pull/10

**Comment by bclehmann** [comment]
It looks like you fixed this ~2 months ago for Mac: https://github.com/ScottPlot/ScottPlot/blame/master/src/ScottPlot/ScottPlot.csproj#L48

Is this solution a possibility for Linux as well? It doesn't look like CoreCompat offers a package with native builds on MacOS.

For the timebeing this probably makes sense for documenting 4.0.x builds, unless you intend to backport this.

**Comment by swharden** [comment]
It sure took me a while to get to this 😅

I merged your PR and added some new details.

https://github.com/CoreCompat/libgdiplus-packaging has some instructions for MacOS and Linux, so pointing people there is probably a good catch-all for now 👍
