### ISSUE TITLE
How do I label the Y Axis

### ISSUE THREAD

**Issue by Croft5** [ScottPlot/ScottPlot#900]
Hi - This is my first time for using ScottPlot so sorry for the basic question. I am plotting atmospheric pressure against time. I have the graph running and its great, thank you. At the moment the Y axis is showing the pressure in mb, such as 1020 but I need it to show this to 2 places, ie 1020.00. How do I get the labelling on the Y axis to do this?

Thanks

**Comment by FoggyFinder** [comment]
https://swharden.com/scottplot/cookbooks/4.1.2-beta/advanced_axis_features.html#ticks_numericformatstring
