### ISSUE TITLE
WPF Start Quickstart doesnt work

### ISSUE THREAD

**Issue by PassionateDeveloper86** [ScottPlot/ScottPlot#904]
Hey,

I downloaded the actual version of ScottPlot for WPF (4.0.48) and try to add your first quickstart:
https://swharden.com/scottplot/quickstart/#wpf-quickstart

In there it is 

WpfPlot1.Plot.AddScatter(dataX, dataY);

While in my current Version the Property "Plot" is called "plt" and a simple AddScatter is not available, just a Add with a Plottable object.

Is the quickstart not for the current version or am I just missing something?

**Comment by FoggyFinder** [comment]
> This documentation is specific to ScottPlot 4.1 which is currently available as a pre-release package on NuGet
