### ISSUE TITLE
How to restrict X axis view to a range when panning and zooming

### ISSUE THREAD

**Issue by PassionateDeveloper86** [ScottPlot/ScottPlot#920]
Hi,

I have a timegraph as chart in Scottplot.
So everything minus 0 is useless for me. When zooming out, e.g. on a x Axis from 0 to 200, the zoom works like moving the x Axis to -20 to 220 -> I want to avoid going in minus on X Axis and when I zoom out I just wont to zoom on the plus values, e.g. in this example a zoom should move the x axis from 0-200 to 0-240.

**Comment by swharden** [comment]
Hi @PassionateDeveloper86, the `Plot.SetViewLimits()` method may help you achieve this goal. 
https://swharden.com/scottplot/cookbooks/4.1.10-beta/api/plot/#setviewlimits

```cs
myPlot.SetViewLimits(xMin: 0, xMax: 200);
```

Let me know if this doesn't do the trick!
