### ISSUE TITLE
No "Plot" method in FormsPlot?

### ISSUE THREAD

**Issue by Smonoverix** [ScottPlot/ScottPlot#922]
Using VS 2019 (16.9.1), .Net 4.8.0408
Trying to follow instructions for Windows Forms Quickstart.
All goes well until I try to enter the line "formsPlot1.Plot.AddScatter(dataX, dataY);  
Error text is "FormsPlot does not contain a definition for 'Plot'...

Can you tell me what I am not doing correctly?

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using ScottPlot;

namespace MicrobesDataUtility
{
    public partial class PopGraph_1 : Form
    {
        MicrobesDataUtility.Form1 itsParent;

        public PopGraph_1(MicrobesDataUtility.Form1 theParent)
        {
            InitializeComponent();
            itsParent = theParent;
        }

        private void PopGraph_1_Load(object sender, EventArgs e)
        {
            double[] xs = { 1, 2, 3, 4, 5 };
            double[] ys = { 1, 4, 9, 16, 25 };

            formsPlot1.Plot.AddScatter(xs, ys);          
        }
    }
}

**Comment by bclehmann** [comment]
If you're using ScottPlot 4.0.48 you have to use `formsPlot1.plt.PlotScatter`.

`formsPlot1.Plot.AddScatter` is specific to the 4.1.x betas.

**Comment by swharden** [comment]
Thanks for the quick answer @bclehmann!

This is related to #916

I agree this is confusing. I'd love to finalize the cookbook and demo applications, then get ScottPlot out of beta. It's been too long! Maybe this week 🤞
