### ISSUE TITLE
Add support for a custom tick label formatting function

### ISSUE THREAD

**Issue by damiandixon** [ScottPlot/ScottPlot#926]
I'm attempting to move from LiveCharts and I have a custom label formatter to display elapsed time
in the format: DD:HH:mm:ss, where DD is elapsed number of days.

I have found how to do HH:mm:ss using the following:
```
      wpfGridGraphControl.plt.Ticks(dateTimeX: true, dateTimeFormatStringX: "HH:mm:ss");
```
I've looked at the available format strings: https://tinyurl.com/y86clj9k, but there is nothing that seems to help.

Is there any way to implement a truly custom format callback that is passed an x-axis value and returns a string to display at the tick mark?

**Comment by swharden** [comment]
Hi @damiandixon, thanks for the question!

I see your problem - You want to use a custom timestamp tick label format that includes days, but the [Standard numeric format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings) provided by Microsoft can't represent day as a number of days elapsed relative to an arbitrary date.

Your suggested solution is a good one too - add a custom format callback to enhance the user's ability to customize label formats.

Unfortunately I don't think there's an easy way to do this with the code the way it is right now. After getting ScottPlot 4.1 out of beta I intend to refactor the tick module to make tasks like this easier to achieve. I've added this issue to the triage list so we can keep track of it, but it may take me a little while to get to.

### Intermediate Solution

If you want to try implementing this yourself, you may be able to achieve this effect by adding a bit of logic in the top of this function ...

https://github.com/ScottPlot/ScottPlot/blob/822b975be9d4b5f5d1b5057782bcc4f6e0d7740b/src/ScottPlot/Renderable/AxisTicksRender.cs#L78-L82

... which replaces each label in `tc.tickLabels` (a string array) with a custom string based on values described by `tc.tickPositionsMajor` (a double array).

If you don't get to it, I may try this myself in the next day or two to determine how well it works. If this is a good spot where we can insert a custom function to modify tick labels at the last minute, it might be a good stand-in option until the tick module is fully/properly refactored.

**Comment by StendProg** [comment]
Hi there,

@damiandixon I'd like to clarify. Do you want to get the total number of days, which can be more than 31? (because the number of days in a month is described by a simple `dd` format specifier).
Most likely I understood correctly, and the problems cannot be solved without a custom callback.

A good place to inject a new addiction is to add field to `TickCollection`:
```c#
public class TickCollection
{
    ...
    public Func<DateTime, string> manualDtConvertor = null;
    ...
}
```
Then just extend the method `DateTimeTickUnitBase.GetTicksAndLabels`:
```c# 
public class DateTimeTickUnitBase : IDateTimeUnit
{

    public (double[] Ticks, string[] Labels) GetTicksAndLabels(DateTime from, DateTime to, string format, Func<DateTime, string> manualDTConvertor = null)
    {
         DateTime[] ticks = GetTicks(from, to, deltas, maxTickCount);
         string[] labels;
         if (manualDTConvertor is not null)
         {
             labels = ticks.Select(manualDTConvertor).ToArray();
         }
         else
         {
            labels = (format is null) ?
            ticks.Select(t => GetTickLabel(t)).ToArray() :
            ticks.Select(t => t.ToString(format, culture)).ToArray();
          }
         return (ticks.Select(t => t.ToOADate()).ToArray(), labels);    
    }
  }
```
and call it from `TickCollection` methods with this additional param

The only thing that remains unsolved for me is to come up with a convenient API method for setting the field to `TickCollection.manualDtConvertor`. If @swharden  could help me with this, I could arrange all this in the form of a PR.

**Comment by damiandixon** [comment]
Hi @StendProg,

I was looking for Total days, so not limited to a maximum of 31.

In the LiveCharts variant of my application the callback does not display the number of days when the number of hours is less than 24. Makes for a slightly more compact display.

Thanks for looking at this.

**Comment by swharden** [comment]
Refactoring the tick collection to add this feature (and many more) is a prominent deferred task on the triage page #1028 

I'll close this issue for now since there isn't immediate movement on this front, but I hope to revisit this topic after ScottPlot 4.1 is released 👍
