### ISSUE TITLE
How can i use PlottableSignalXY with values that go up and down?

### ISSUE THREAD

**Issue by antithing** [ScottPlot/ScottPlot#927]
Hi! and thanks for this lib, it is very useful.

I have a data array that does not increment upward, for example:

1, 3, 4, 5, 4, 6

I cannot use PlotSignalXY for this, as it requires the values in upward order.

Is there a plot that will work nicely for this kind of data? I would like the points to be connected by a line along the X axis. Something like this:

![image](https://user-images.githubusercontent.com/11506730/113032307-a2085680-9187-11eb-89d5-73f289cac799.png)

I have tried ScatterPlot, and it seems to connect the points randomly, rather than along X.

Thanks!

**Comment by swharden** [comment]
Hi @antithing, would a regular scatter plot solve your problem?
https://swharden.com/scottplot/cookbooks/4.1.11-beta/#plottable-scatter-plot

![image](https://user-images.githubusercontent.com/4165489/113034973-b5ec9200-9160-11eb-8058-7ce98bd9d004.png)

**Comment by StendProg** [comment]
Hi @antithing,
Unfortunately, I did not fully understand what you mean, but I will try to answer anyway.
For `ScatterPlot` or `PlottableSignalXY` you must provide 2 arrays `XValues` and `YValues`.
`PlottableSignalXY` imposes restrictions only on the `XValues`. `YValues` can go whatever you want. The example you gave shows f(x), which means that SignalXY is suitable for this type of signals.
`ScatterPlot` have the same API, but does not impose any restrictions on `XValues`. At the same time, the scatter is quite slow and not always suitable for drawing, especially when it comes to millions of points.

Perhaps you just have data unsorted by `XValue`, and all you need to do is sort it first?
If you gave a small example of how you use the library and what is displayed incorrectly (I think you can also take a small number of points no more than 10), maybe we could come up with something.
The fact that I do not understand what exactly your numbers refer to, you must have 2 arrays of `XValue`s and`YValues`, but you brought only one in example above.

**Comment by swharden** [comment]
> I have tried ScatterPlot, and it seems to connect the points randomly, rather than along X.

It sounds like your best solution may be to sort your Xs and Ys prior to plotting them.  Do you have some example data we could use to better understand this task?

**Comment by antithing** [comment]
Hi @swharden  Thanks for getting back to me. As usual, this issue was due to user error. I had my axes mixed up. :) 

Thank you very much for your replies. Please consider this solved. 

Thanks again!
