### ISSUE TITLE
Histogram normalization

### ISSUE THREAD

**Issue by LB767** [ScottPlot/ScottPlot#930]
This is seemingly back to how it was with `countsFrac` being normalized but `countsFracCurve` not with Scottplot 4.1.11-beta?
Unless I'm being very stupid I'm getting the same behavior I described in issue #624, code below updated to 4.1.11

```csharp
var plt = new ScottPlot.Plot(600, 400);

Random rand = new Random(0);
double[] values = DataGen.RandomNormal(rand, pointCount: 1000, mean: 50, stdDev: 20);
var hist = new ScottPlot.Statistics.Histogram(values, min: 0, max: 100);
        
var bar = plt.AddBar(hist.countsFrac, hist.bins);
bar.BarWidth = hist.binSize * 1.2; // oversize to reduce render artifacts
bar.BorderLineWidth = 0;              

plt.AddScatter(hist.bins, hist.countsFracCurve, lineWidth:2, markerSize:0);         

// decorate the plot
plt.XLabel("Value (-)");
plt.YLabel("Fraction (-)");
plt.SetAxisLimits(yMin: 0);
plt.Grid(lineStyle: LineStyle.Dot);

plt.SaveFig("stats_histogram.png");
```

![stats_histogram](https://user-images.githubusercontent.com/20526358/113143355-552a8b80-922c-11eb-97fc-8e7bf3763bae.png)

**Comment by bclehmann** [comment]
I think the best solution is not to enable normalization on all histograms so much as make it toggleable, as quite often one does want a curve on the interval [0, 1].

Adding something like a `countsFracNormalized` as well as a `countsCurve` from #932 may be getting unwieldy. I wonder if there's a cleaner way to do this.

Perhaps we keep the behaviour where the curve is from [0, 1], and we add a function like `ScottPlot.Tools.NormalizeTo()` such that `countsFracCurve` becomes `Tools.NormalizeTo(hist.countsFrac, 0, h)` where h is the desired height of the mode of the normal distribution.

The height of the mode of the normal distribution is given by 
![image](https://user-images.githubusercontent.com/8635304/113199836-cc5c2180-9224-11eb-836b-e402a46fd1b0.png)
which is approximately 0.4/sigma

Knowing this, one can find a multiplier such that we can arbitrarily rescale the curve. However, this is all leading me to think that the best thing to do might be to move the distribution outside of histograms. We already have functions that can get summary statistics, I think there's a lot of benefit in being able to plot distributions without having to make a histogram out of them. And I think if we have something like that we can add features like `countsCurve` and normalized `countsFracCurve` as well as other distributions like Students-T or Chi-square without cluttering the histogram code.

**Comment by swharden** [comment]
Hi @LB767, thanks for raising this issue! Connecting the dots here, the present behavior is demonstrated by this cookbook example: https://swharden.com/scottplot/cookbooks/4.1.11-beta/category/statistics/#histogram

![image](https://user-images.githubusercontent.com/4165489/113513767-36343e00-9539-11eb-87fa-ea266bf359fc.png)

> best thing to do might be to move the distribution outside of histograms

I definitely agree! There are lots of methods in the `Tools` module that should be in independent better-named modules. Similarly, statistic logic buried inside the `Histogram` and `Population` classes should be easier to access. Refactoring these classes and improving documentation has been added to the triage list (#716)

> make it toggleable

Regardless of what the default behavior is (normalized or not), an ideal solution would be one where the user can define the intended behavior, and this should be in a way that is very easy to discover.

> [Regarding a population statistics module] if we have something like that we can add features like `countsCurve` and normalized `countsFracCurve` as well as other distributions like Students-T or Chi-square without cluttering the histogram code

@bclehmann what level of interest do you have in creating such a module? I'm going to spend the next few days trying to push ScottPlot 4.1 out of beta and working on documentation, so I probably wouldn't get to this for some time. I'd love to model function arguments and documentation after numpy (e.g., [numpy.histogram](https://numpy.org/doc/stable/reference/generated/numpy.histogram.html))

**Comment by LB767** [comment]
All these ideas are great and all but I was just pointing out that `countsFrac` and `countsFracCurve` should either both be normalized or both not normalized for consistency, just like it is in Scottplot 4.0, unless there's a good reason for the different behavior?
The cookbook example you linked uses 2 Y axes and plots `counts` not `countsFrac`, so it's kinda beside the point.

See these lines for the inconsitency:
https://github.com/ScottPlot/ScottPlot/blob/1cc87b85bc2c76a3288cd6c2f516f2816acc3aad/src/ScottPlot/Statistics/Histogram.cs#L70-L72

**Comment by bclehmann** [comment]
My only hesitation on creating a lot of code around distributions is that a lot of distributions have non-trivially implemented functions. For example the CDF of the normal distribution. And for all distributions the inverse of the CDF is very useful for getting random variables from that distribution (see inverse transform sampling), but it is almost always difficult to compute.

Now, all these functions have well known approximations, but my issue is if users are led to believe that they should use our implementation in performance or precision critical situations.

For example, I tried my hand at the inverse of the error function. I could get to accuracy within about 10^-5 with a weak approximation of erf(x) and a lot of Newton's method. mathnet-numerics has a lookup table of different polynomial approximations (presumably from the Taylor Series) and is accurate to about 10^-21 on an infinite precision datatype. Not to mention their version will be much much faster. It would be a massive increase in scope to attempt to provide high accuracy or high performance implementations.

So I guess I'm asking what the middle ground is. Just functions to provide random numbers from a distribution? Or a little more, as the PDF and CDF are useful for histograms.

**Comment by swharden** [comment]
The purpose of this comment is to document the existing functionality/language of the `ScottPlot.Statistics.Histogram` module.

In reviewing this topic I got confused myself, which is a strong indication that this module needs some work. It would greatly benefit from improved public field/property/method names and better XML documentation, and I've added this task to the triage list (#716)

## Random Data

```cs
// create and plot normally-distributed random values
Random rand = new(0);
int pointCount = 10_000;
double[] values = ScottPlot.DataGen.RandomNormal(rand, pointCount, mean: 123, stdDev: 12);
var plt = new ScottPlot.Plot(600, 400);
plt.AddScatterPoints(xs: ScottPlot.DataGen.Consecutive(pointCount), ys: values);
```

![image](https://user-images.githubusercontent.com/4165489/114288019-deff0380-9a39-11eb-8bf2-f32e0a1b778f.png)

## Create a Histogram

```cs
var hist = new ScottPlot.Statistics.Histogram(values);
```

## Histogram Counts

```cs
plt.AddBar(values: hist.counts, positions: hist.bins);
```

![image](https://user-images.githubusercontent.com/4165489/114288024-ec1bf280-9a39-11eb-9bb3-89d6ae7a1cf1.png)

## Curves

```cs
plt.AddScatter(xs: hist.bins, ys: hist.countsFrac, label: "countsFrac");
plt.AddScatter(xs: hist.bins, ys: hist.countsFracCurve, label: "countsFracCurve");
plt.AddScatter(xs: hist.bins, ys: hist.cumulativeFrac, label: "cumulativeFrac");
```

![image](https://user-images.githubusercontent.com/4165489/114288169-04404180-9a3b-11eb-83d2-65535c6905f7.png)

## Next Steps

⚠️ These variable names are pretty bad - they don't clearly describe what they hold, and they don't have good XML documentation. It's not obvious which curves are ideal and which are based on actual data. I'll work to improve this, probably mimicking what matplotlib's histogram module does:

* https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html
* https://matplotlib.org/stable/gallery/statistics/histogram_features.html

**Comment by swharden** [comment]
I made this a little better by adding a `Histogram.probability` field, but a true fix is to greatly refactor the Histogram module to give it more logical naming (and capitalization) across the board.

I also improved the cookbook recipes to make this more obvious: https://swharden.com/scottplot/cookbooks/4.1.12-beta/#statistics

![image](https://user-images.githubusercontent.com/4165489/114334303-4c816180-9b18-11eb-9975-a665a2e9ee69.png)

![image](https://user-images.githubusercontent.com/4165489/114334317-51deac00-9b18-11eb-906d-112bf6ab378a.png)
