### ISSUE TITLE
Histogram normalization #2

### ISSUE THREAD

**Issue by breakwinz** [ScottPlot/ScottPlot#932]
This tool has been a godsend when I saw how easy it is to draw histograms. However when it comes to normal distribution I am finding it confusing on how to scale the normal distribution curve to the scale of the data. 

In the example cookbook for normal distribution histogram the histogram bars are using scaled fractional y values. However I want to use the real frequency of the bins. So lets say theres 10 values in total: 
1, 3, 3, 4, 4, 4, 5, 5, 6, 7, 
as we can see 4's appear 3 times, so instead of fractional count which shows 0.33 I use the real frequency meaning it give a y-value of 3.

The issue is theres is only an option for using countsFracCurve for the normal distribution curve. There is no countCurve method which allows the normal distribution curve scale with the non fractional histogram.

I hope this make sense. Please add a countCurve which does the same thing as countsFracCurve but without the fractional bit. Or please advise if I am missing something

**Comment by swharden** [comment]
Thanks for the suggestion @breakwinz!

> There is no countCurve method which allows the normal distribution curve scale with the non fractional histogram

This topic is very similar to #390. I'll add a quick solution into the Histogram module and release a new package later today, but long-term I'll try to improve this by moving statistical calculations out of the Histogram module and into some type of static statistics class so the methods that perform the calculations can be accessed directly (with better documentation and improved user control over behavior). Refactoring these methods is currently in the triaged tasks list #716 but it's unclear how soon that will happen

**Comment by swharden** [comment]
I'll track progress on this issue in #930
