### ISSUE TITLE
How can I omit plotting zero values in the array

### ISSUE THREAD

**Issue by jsr1611** [ScottPlot/ScottPlot#947]
Dear Scott,

I am plotting growing live data (using fixed array data structure) and if I don't have data for certain plots, I am skipping it by `continue`ing it in the loop. 
But, I feel like it is still plotting those as zero thus making the plot look not so good.
How can I omit plotting those zero values in the array? I want to plot only non-zero values.
Here is the snapshot of the charts.
![image](https://user-images.githubusercontent.com/38090036/113618805-229cea80-9693-11eb-85fa-1b126dbbc15a.png)

I am using 4.0.42.0 version.

I have multiple charts and multiple lines in each chart. Sometimes I have data for all charts, and it plots them nicely. But when I have data for certain charts, and not for all of them, I don't update the relevant array value (which is by default is 0 I guess), and this array index then produces this issue.

Any help would be appreciated!
Jimmy

**Comment by swharden** [comment]
Hi @jsr1611, 

Plotting data with gaps can be difficult with ScottPlot. This topic is discussed on https://swharden.com/scottplot/faq/data-gaps/ - briefly line plots must be a single continuous line, so to show gaps in data you must create multiple line plots.

> I want to plot only non-zero values

If this is truly your goal, your solution may be relatively simple with LINQ:
```cs
double[] data1 = {5, 2, 0, 0, 0, 8, 4, 6, 0, 0, 9, 2, 0, 4, 6};
Console.WriteLine("data 1: " + string.Join(", ", data1));

double[] data2 = data1.Where(x => x != 0 ).ToArray();
Console.WriteLine("data 2: " + string.Join(", ", data2));
```

```
data 1: 5, 2, 0, 0, 0, 8, 4, 6, 0, 0, 9, 2, 0, 4, 6
data 2: 5, 2, 8, 4, 6, 9, 2, 4, 6
```

You could just plot the `data2` array

Let me know if this helps!

**Comment by jsr1611** [comment]
Dear Scott, I couldn't implement what you described above as I already have declared the 100_000 sized array of doubles and I was filling it with the data read from my sensor devices. It is becoming difficult to manage all of those nested arrays. Instead, what I did is fill that cell with double.NaN. It kind of worked this way: 
![image](https://user-images.githubusercontent.com/38090036/114658524-ea4d7a00-9d2c-11eb-982e-8b002fd65c44.png)
 
But I still have those connecting lines that go beyond the chart and reappear when I have data. 
Do you think I can implement your solution with live charts ? Do I have to extend the rendering time for that? Because data retrieval interval is 1 second, and it means I will have only one data at a time and I think for the above case I need to collect some data at least and then check if contains 0s. Is it this way?
Finally, I should render every certain period of time so that I can check if the data is distributed or there are some outliers, right?

Thank you.

**Comment by swharden** [comment]
Hi @jsr1611, 

### How to plot data with gaps

ScottPlot is not currently designed to be able to make scatter plots with gaps in the data. Each scatter plot is designed to be displayed as one continuous line. Strategies for plotting discontinuous data (data with gaps) are discussed in this FAQ page: https://swharden.com/scottplot/faq/data-gaps

However, I recognize plotting data with gaps is a common goal, and this has been a question that has emerged many times before! I started an issue to track progress toward figuring-out how to implement support for scatter plots with gaps in the data (#976).

### Support for `double.NaN`

> Instead, what I did is fill that cell with double.NaN

> But I still have those connecting lines that go beyond the chart and reappear when I have data

If you find a strategy that works for you, keep using it! I wanted to note though that as of today, ScottPlot does not support datasets that contain `double.NaN` (or infinity).

### How to plot live data

> Do you think I can implement your solution with live charts ? Do I have to extend the rendering time for that? Because data retrieval interval is 1 second, and it means I will have only one data at a time and I think for the above case I need to collect some data at least and then check if contains 0s. Is it this way?

Some strategies for plotting live and updating data can be found on this FAQ page: https://swharden.com/scottplot/faq/live-data

Briefly, I think 1 update a second is very reasonable, and should work well! You can set-up a timer to update the graph every second (checking for outliers, etc.)

I think this answers all of your questions so I'll close this issue now, but if there are more or if my answers were insufficient feel free to open it again 👍
