### ISSUE TITLE
Text BackgroundColor not rendered in 4.1.11

### ISSUE THREAD

**Issue by PassionateDeveloper86** [ScottPlot/ScottPlot#952]
Hi,

I render a bunch of labels into my plot:

  AppData.I.MainMeasurement.Labels.ForEach(x =>
            {
                x.PlotRef = AppData.I.Chart.Plot.AddText(x.Text, x.X, x.Y);
                ((Text)x.PlotRef).BackgroundColor = System.Drawing.Color.Black;
                ((Text)x.PlotRef).Font.Color = x.TextColor;
                ((Text)x.PlotRef).Font.Size = x.FontSize;
            });

Even the ScottPlot.Text has a BackgroundColor Property, setting it has not effect:

![grafik](https://user-images.githubusercontent.com/20551244/113834791-8571ad00-978b-11eb-801a-a39ba7bd8b72.png)

**Comment by bclehmann** [comment]
Hello, you should be able to set the `BackgroundFill` property like this:

```cs
((Text)x.PlotRef).BackgroundFill = true;
```

This will cause the `Text` class to respect the `Font.BackgroundColor` property.

**Comment by PassionateDeveloper86** [comment]
Worked! Thank you.
