### ISSUE TITLE
How to display a defined time range when using DateTime axis

### ISSUE THREAD

**Issue by Croft5** [ScottPlot/ScottPlot#953]
Hi,

I am plotting atmospheric pressure over time (Barograph).
I currently have the time period set to 12 hours and the axis both auto scale.
It works really well and yesterday I discovered that I can scroll and zoom but only within the time period that I set.
Is there a way of keeping older data (more than 12 hours) so I can scroll back as needed?

Thanks

**Comment by bclehmann** [comment]
Hello, would you mind sending the relevant portion of your application? I'm unsure how you managed to limit yourself to a 12 hour time period in the first place, if there's data from before the beginning of that period it should be plotted if it is present once you zoom out or pan backwards. Provided you haven't used things like `minRenderIndex` to prevent that.

**Comment by Croft5** [comment]
Hi Benjamin,

This is very kind of you, thanks.
Its my first time using ScottPlot so do excuse my lack of knowledge.
Here is the relevant section of code (I hope)...


    public class MainWindow : Window
    {
        public MainWindow()
        {
            DataContext = new MainWindowViewModel();

            InitializeComponent();
#if DEBUG
            this.AttachDevTools();
#endif
        }

        /// <summary>
        /// How much time is shown on the graph
        /// </summary>
        TimeSpan GraphDuration => TimeSpan.FromHours(48);
        /// <summary>
        /// How often we read the pressure
        /// </summary>
        TimeSpan ReadingFrequency => TimeSpan.FromMinutes(5);
        /// <summary>
        /// How many decimal places to show on the X Axis
        /// </summary>
        /// <remarks>
        /// F2: Two decimal places. F3: Three decimal places
        /// </remarks>
        string XAxisFormat = "F2";
        /// <summary>
        /// What colour are the grid lines
        /// </summary>
        /// <remarks>
        /// Use Paint to figure out the red, green and blue values
        /// </remarks>
        System.Drawing.Color GridLinesColor => System.Drawing.Color.FromArgb(red: 150, green: 150, blue: 150);

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);

            // Prepare sensor
            Sensor = new BMP3.Sensor();
            Sensor.Initialise();

            // Take first reading
            var viewModel = DataContext as MainWindowViewModel;
            UpdateViewModel(viewModel);

            // Prepare graph
            Graph = this.Find<AvaPlot>("avaPlot1");
            int numberOfElements = (int)(GraphDuration.TotalSeconds / ReadingFrequency.TotalSeconds);
            double[] dataX = new double[numberOfElements];
            double[] dataY = new double[numberOfElements];

            for (int counter = 0; counter < numberOfElements; ++counter)
            {
                dataX[counter] = viewModel.ReadingTime.ToOADate();
                dataY[counter] = viewModel.Pressure;
            }

            Series = Graph.plt.PlotScatter(dataX, dataY);
            Graph.plt.Ticks(numericFormatStringY: XAxisFormat, dateTimeX: true, dateTimeFormatStringX: "HH:mm");
            Graph.plt.Grid(color: GridLinesColor);
            UpdateAxis(viewModel.ReadingTime);
            Graph.Render();

            // Set refresh frequency
            RefreshTimer.Interval = TimeSpan.FromMilliseconds(100);
            RefreshTimer.Tick += RefreshTimer_Tick;
            RefreshTimer.Start();
        }

        private void RefreshTimer_Tick(object sender, EventArgs e)
        {
            Log.Information("Starting tick");
            try
            {
                var viewModel = DataContext as MainWindowViewModel;
                bool hasNewReading = UpdateViewModel(viewModel);

                if (hasNewReading)
                {
                    Log.Information("Updating Graph");
                    Array.Copy(Series.xs, 1, Series.xs, 0, Series.xs.Length - 1);
                    Array.Copy(Series.ys, 1, Series.ys, 0, Series.ys.Length - 1);
                    Series.xs[Series.xs.Length - 1] = viewModel.ReadingTime.ToOADate();
                    Series.ys[Series.ys.Length - 1] = viewModel.Pressure;
                    UpdateAxis(viewModel.ReadingTime);

                    Log.Information("Rendering Graph");
                    Graph.Render();
                }
                Log.Information("Ending tick");
            }
            catch(Exception error)
            {
                Log.Fatal("Unhandled exception {0}", error);
                throw error;
            }
        }

        private bool UpdateViewModel(MainWindowViewModel viewModel)
        {
            viewModel.CurrentTime = DateTime.Now;

            // Update the reading once the duration set by ReadingFrequency has passed
            if (viewModel.ReadingTime + ReadingFrequency <= viewModel.CurrentTime)
            {
                viewModel.Pressure = Sensor.ReadPressure();
                viewModel.ReadingTime = RoundTime(viewModel.CurrentTime);

                return true;
            }
            else
            {
                return false;
            }
        }

        private DateTime RoundTime(DateTime currentTime)
        {
            if (currentTime.Second > 30)
            {
                // Round up to the next minute
                return currentTime.AddSeconds(60 - currentTime.Second);
            }
           else if (currentTime.Second > 0)
            {
                // Round down to the previous minute
                return currentTime.AddSeconds(currentTime.Second * -1);
            }
            else
            {
                // Already rounded to a minute
                return currentTime;
            }
        }

        private void UpdateAxis(DateTime readingTime)
        {
            // Adjust X axis to current duration, latest reading on the right
            Graph.plt.Axis(x1: (readingTime - GraphDuration).ToOADate(), x2: readingTime.ToOADate());
            Graph.plt.AxisAutoY();
        }

        private DispatcherTimer RefreshTimer { get; set; } = new DispatcherTimer();
        private BMP3.Sensor Sensor { get; set; }
        private AvaPlot Graph { get; set; }
        private ScottPlot.PlottableScatter Series { get; set; }
        private int readingIndex = 0;
    }
}

In this one I am testing a 48 hour window, but it would be best to have a 12 hour window on view but with the data held for many hours longer.
On a traditional paper barograph, it shows a month but lacks the resolution to see the passage of fronts which are just a few MB of pressure difference.

Thanks for the help, Dave

**Comment by bclehmann** [comment]
You're window is restricted to a specific timeframe on this line in `UpdateAxis`:

```cs
Graph.plt.Axis(x1: (readingTime - GraphDuration).ToOADate(), x2: readingTime.ToOADate());
```

One option is to allow changing `GraphDuration` so that it can be an arbitrary range. Depending on your app that could be a slider or similar. Another option is to stop calling `UpdateAxis` so that the user is free to see a wider axis.
