### ISSUE TITLE
Possible to use winforms version with beta?

### ISSUE THREAD

**Issue by breakwinz** [ScottPlot/ScottPlot#954]
Is it possible to use the winforms scottplot with the latest version of the beta?
I am getting an error where winforms plot is looking for version 4.0.48 when adding the control to my main form and will cancel the action.

I want the features of beta but struggling to figure out how to use it in conjuction with winforms

**Comment by bclehmann** [comment]
Hello, you need both ScottPlot 4.1.11 and ScottPlot.Winforms 4.1.11.

**Comment by breakwinz** [comment]
Thanks. Where can i find winforms version 4.1.11. Apologies I cannot find it, i must be missing something?

**Comment by breakwinz** [comment]
Apologies, I have now found it
