### ISSUE TITLE
Consider renaming AddHeatMapCoordinated

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#955]
**What can we do to make ScottPlot better?**
I think `AddHeatmapCoordinated` is better because it matches the capitalization used everywhere else. `AddCoordinatedHeatmap` is another good option, especially as the type is `CoordinatedHeatmap`, not `HeatmapCoordinated`.

The [ScottPlot Roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) may provide additional context regarding current goals and future directions.

**Comment by StendProg** [comment]
Hi @bclehmann,
You're absolutely right, it's just a mistake.
But fixing it is no longer so easy, at least you need to leave the old version marked `obsolete` with a migration hint. I think already many projects that reference to the current version.
As for changing the word order, then the logical grouping with `AddHeatmap` is broken. I once considered current option.

If we go further, then in fact `CoordinatedHeatmap` is not much differs from the original `Heatmap`. And it would be quite reasonable to combine both behaviors into one object. I chose a separate type just so as not to break the original behavior. Maybe you, as an author, will be able to summarize everything together.

**Comment by bclehmann** [comment]
> As for changing the word order, then the logical grouping with AddHeatmap is broken.

Good point, I think that's more important than matching the name of the type. The type could be renamed instead? Still, the word order is a minor issue.

> But fixing it is no longer so easy, at least you need to leave the old version marked obsolete with a migration hint. I think already many projects that reference to the current version.

CoordinatedHeatmaps have not made their way into a non-beta build, so I don't think this is strictly necessary. Although it would certainly be considerate to at least give a migration hint.

As for merging the two into one class, I think that's the best solution here. I think a boolean property such as `StretchToFill` would suffice? Perhaps we could even take an enum to specify from amongst many different scaling options? Such as stretching one axis, cropping, zooming, etc.

**Comment by StendProg** [comment]
> The type could be renamed instead? Still, the word order is a minor issue.

We can rename it, just `CoordinatedHeatmap` sounds more natural even to me. For types, logical grouping is not as important as for API methods (imho).

> Although it would certainly be considerate to at least give a migration hint.

It is very annoying when, after updating a third-party library, the working code stops compiling. And an additional hint on what to do very much smoothes this moment. I just reminded that we must not forget about this opportunity.

> As for merging the two into one class, I think that's the best solution here. I think a boolean property such as StretchToFill would suffice? Perhaps we could even take an enum to specify from amongst many different scaling options? Such as stretching one axis, cropping, zooming, etc.

All these options branches immediately come to mind and the fact that they can be resolved through polymorphism using sets of classes. Which is contrary to the original message. It is important that from the outside it looks like one simple class to the user. And inside it may be and makes sense to build a hierarchy of inheritance. It is difficult to say anything more detailed without diving into the task.

**Comment by bclehmann** [comment]
I added this in #963.

I am intrigued by your suggestions on potential refactoring of the heatmap code but I think that would be better suited to another PR where one can explore more options, while allowing #963 to stay mostly just a simple rename and migration hint.
