### ISSUE TITLE
4.1.11: Scale of graph gets screwed up when using "AddHorizontalLine" or "AddVerticalLine"

### ISSUE THREAD

**Issue by breakwinz** [ScottPlot/ScottPlot#957]
I am drawing histograms followed the tutorial in the cookbook,  it works great. However, when I do not use the vertical and horizontal line feature this is how scottplot shows: 

![image](https://user-images.githubusercontent.com/4165489/114254160-c8927280-997b-11eb-9150-5b3e695f0b88.png)

However when adding this:

```cs
Plot.AddHorizontalLine(0);
Plot.AddVerticalLine(0);
```

Then this is what appears on first glance:
![image](https://user-images.githubusercontent.com/4165489/114254171-d2b47100-997b-11eb-99d4-bdca5809f2eb.png)

and this is what appears when i zoom into my data:
![image](https://user-images.githubusercontent.com/4165489/114254177-d942e880-997b-11eb-81b2-38068182ad0d.png)

Am I missing something or is this bug?

**Comment by StendProg** [comment]
Hi @breakwinz,

It looks like you do not want the `HLines/VLines` to affect axis limits calculation.
To solve this problem, you can use the solution from the first paragraph: 
https://github.com/ScottPlot/ScottPlot/issues/643#issuecomment-738117885

**Comment by breakwinz** [comment]
Thanks @StendProg Are you sure this is applicable to 4.1.11?

Following your code
PlottableVLine Class does not exist for me. However I can make the PlottableVLineNoLimits inherit from ScottPlot.Plottable.VLine. However then the next issue becomes GetLimits() does not exist within those classes.

**Comment by StendProg** [comment]
> Following your code
PlottableVLine Class does not exist for me. However I can make the PlottableVLineNoLimits inherit from ScottPlot.Plottable.VLine. However then the next issue becomes GetLimits() does not exist within those classes.

Apologies for the slight misleading information. There are a lot of naming optimizations in 4.1, but they're not all that different.
```c#
public class PlottableVLineNoLimits : VLine
{
  public override AxisLimits GetAxisLimits() => new AxisLimits(double.NaN, double.NaN, double.NaN, double.NaN);
}

public class PlottableHLineNoLimits : HLine
{
  public override AxisLimits GetAxisLimits() => new AxisLimits(double.NaN, double.NaN, double.NaN, double.NaN);
}
```
Should be applicable to 4.1.11-beta (browser programming) 

I think it would be a good idea to add an helper decorator to the codebase that allows you to disable the calculation of axis limits for an arbitrary `IPlottable`. I'll see how difficult it is one of these days.

**Comment by swharden** [comment]
Hi @breakwinz, @StendProg's advice is excellent. I think you have here what you need to solve your problem, but if not feel free to re-open this issue.

Note that I just made some simpler histogram cookbook examples tonight and you may find them helpful https://swharden.com/scottplot/cookbooks/4.1.12-beta/#statistics
