### ISSUE TITLE
ScottPlot 4.1 needs "open in new window" right-click menu option

### ISSUE THREAD

**Issue by ademkaya** [ScottPlot/ScottPlot#958]
Hello;

In the previous version I use (it was 4.0.48 I believe) there was "open in a new window" choice when we right click on the graph. It was so useful for me because I was able to enlarge the graph. Now I updated in to 4.1.11 and saw that It was removed.

Could you add it back in future revisions ?
Thank you.

Screenshot from 4.0.48 demo
![2](https://user-images.githubusercontent.com/4140956/114148118-1da19a80-9922-11eb-9d40-6cd9dd586e6f.png)

screenshot from 4.1.11
![3](https://user-images.githubusercontent.com/4140956/114148367-56417400-9922-11eb-8545-f13a3be1ed03.png)

**Comment by swharden** [comment]
Hi @ademkaya, thanks for noting this! This was an oversight in the transition from ScottPlot 4.0 to 4.1. I'll add this to the triage list #716 and fix it before I remove the "beta" tag from this new version

**Comment by swharden** [comment]
Thanks for the quick fix @bclehmann! For some reason I thought this would be a lot more complex. A true/deep fix means solving #819, but this is a strong improvement as it is so thanks!
