### ISSUE TITLE
How to shade a span underneath a curve

### ISSUE THREAD

**Issue by breakwinz** [ScottPlot/ScottPlot#959]
Axis span feature is great to highlight the range of standard deviations using histograms and normal distribution. But would be even better if its possible to set limits as to how far it goes on the opposite axis.

Example: I set a axis span on x-axis for 2 standard deviations which highlights the portion of my histogram which would fall there. However the axis span goes to infinity on the y-axis now. It would be nice to be able to limit this to only show under the normal distribution curve. 

Willing to draw a picture if explanation is not clear

**Comment by bclehmann** [comment]
I believe you can mimic this behaviour by plotting polygons. You can do this with `PlotPolygon` in 4.0.x, or `AddPolygon` in 4.1.x.

**Comment by swharden** [comment]
Hi @breakwinz, 

> Willing to draw a picture if explanation is not clear

I'm guessing you're trying to create a figure like this:

![image](https://user-images.githubusercontent.com/4165489/114254495-b6193880-997d-11eb-9613-01b59fb001c6.png)

I think @bclehmann has the right idea! You can use a polygon to achieve this. However, ScottPlot 4.1 (beta / pre-release) also has an `AddFill()` method which might do the trick too (it really just creates a polygon under the hood).

https://swharden.com/scottplot/cookbooks/4.1.11-beta/category/plottable-fill/#fill-under-curve

If you figure out how to do this, I'd love to see the code you came up with! This might be a useful example to add to the cookbook.
