### ISSUE TITLE
New plot type: BubblePlot

### ISSUE THREAD

**Issue by fgma** [ScottPlot/ScottPlot#960]
**Before asking a question** see if it is already answered in:
* [ScottPlot Cookbook](http://swharden.com/scottplot/cookbook)
* [ScottPlot Demo Application](http://swharden.com/scottplot/demo)

**Indicate what you have tried:**
I'm currently in the process of porting some matplotlib code to ScottPlot. So far I really like it. Thanks for building such a great library!

I'm currently using latest stable version of ScottPlott but I can switch to beta if there are options available there. I need to plot circles and circle sector to visualize some data. There seems to be no direct method to do so. 

I tried plotting a point but the diameter is based on pixels not the axis. I've also seen the demo with _many polygons_ where a circle is manually constructed using a polygon. Is there an easier way to do so?

**Comment by swharden** [comment]
Hi @fgma, thanks for this issue!

I'm happy you enjoy ScottPlot! Matplotlib is a fantastic library, and it was a major inspiration for ScottPlot.

I'm guessing you're trying to create a plot like this. It would be nice if you could control the size of the circles in axis units (not in pixel units), and customize each circle's fill color, border color, border thickness, transparency, etc.

![image](https://user-images.githubusercontent.com/4165489/114254625-7e5ec080-997e-11eb-82cf-a27acc471ccc.png)

At this moment, there's not an easy way to do this with ScottPlot! I'm surprised I hadn't thought to implement this previously. @bclehmann is this a plot type you may be interested in making while I work on some of the other triaged tasks? It would great if we could get this into the cookbook before the big 4.1 release. Architecture wise I'm thinking it should be its own plot type and not a child an existing type (scatter plot is tempting, but has too much cruft). I'm curious to hear your thoughts if you are interested in pursuing this!

**Comment by bclehmann** [comment]
@swharden I would like to work on this but I don't know how busy I might be with finals coming up. So I can make no guarantees.

**Comment by bclehmann** [comment]
As an aside, heatmaps can be used to represent similar information to bubble plots. I don't know if that would be appropriate for your use case.

So far, my understanding of a bubble plot looks something like this, please correct me if I'm wrong:
- Represents 3-D data, i.e. a position and a magnitude
- Magnitude is expressed through bubble diameter and perhaps colour
- An `AddBubble` method may be useful in addition to an `AddBubblePlot` method
    - Analogous to how we have `AddPoint` alongside `AddScatter`

**Comment by swharden** [comment]
> I would like to work on this but I don't know how busy I might be with finals coming up

@bclehmann it reminded me a bit of the lollipop plots so I thought it seemed like it would be up your alley! Definitely focus on your academic/career stuff, and I'm sure this task will be around when you have free time again. If I get the time to work on this I'll make a PR and start working on it there so check there before you begin... but it's not like I've been getting to the bottom of any of my to-do lists lately so something tells me this task will still be floating around when you're free again!

In the interim, maybe this issue is a good place to collect specifications for what this plot type can do. I'm thinking each bubble should have these properties, and they should all be independent of each other, and all units are in axis space (not pixel space):
* x position
* y position
* radius
* fill color
* border color
* border size

**Comment by fgma** [comment]
Hi, great idea for a new feature. My actual use case is a bit different from your ideas. I'm using ScottPlot to visualize geometric objects similar to a very simplified CAD software or a floorplan. But I could easily use it like you suggested. It would be great to have direct access for drawing a single circle similar to a polygon as this is needed anyway for the bubble plot.

**Comment by swharden** [comment]
Oops, this was released already and I forgot to close this issue.
https://swharden.com/scottplot/cookbooks/4.1.13-beta/#plottable-bubble
Thanks again to everyone who contributed to this!
