### ISSUE TITLE
How to completely lock the plot. No scrolling/zooming/panning

### ISSUE THREAD

**Issue by breakwinz** [ScottPlot/ScottPlot#974]
- ScottPlot Version: 4.1.12
- Operating System: W10
- Is it a GUI app? What platform? WinForms 

How do i completely disable the function to pan/zoom/scroll for a plot?
I use AxisAuto() to scale the plot appropriately once I have added all the plottables. I thereafter want to disable all the zooming/panning etc. I thought of setting AxisLimits to the current value of Y and X axis scale. But there is no GetCurrentAxis or similar. Note it needs to disable the zooming/panning for all axisindexes.

Bonus: How do I get rid of the "Help" menu when right clicking. As the user might start asking: "why does it say in help i can zoom, but it doesnt work?"

Great tool honestly, had so much success with it past few days. Well done

**Comment by breakwinz** [comment]
So I can use GetAxisLimits on each y-axis index once the view is in a state where I want to to stay, the plot only zooms in and out when panning

But unfortunately SetViewLimits only applies to the primary axisindexes. Y-axisindex 2 is still being modified when moving around beyond what I want to limit it to, causing the scale between yaxis1 and yaxis2 to mess up

**Comment by breakwinz** [comment]
Go into Formsplot.Configuration and all the settings are there :) Now to figure out the contextmenu customisation

**Comment by swharden** [comment]
> Go into `Formsplot.Configuration` and all the settings are there

You got it!

> Now to figure out the contextmenu customization

You may find this helpful: https://swharden.com/scottplot/faq/right-click-menu

Let me know if you still have questions! Good luck 🚀
