### ISSUE TITLE
Scatter plot - support for plotting data with gaps?

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot#976]
This is an extremely common task/question, and was most recently brought-up in #947. There isn't a great way to do this with ScottPlot right now. This topic has its own FAQ page https://swharden.com/scottplot/faq/data-gaps

![image](https://user-images.githubusercontent.com/4165489/114712148-c292ed80-9cfd-11eb-995e-00477d91da9d.png)

I know we go back and forth on how to handle `double.NaN`, but perhaps scatter plots could be modified in some way to recognize when lines start and stop (separated by `NaN`), and call `System.Drawing.DrawLines()` multiple times. Implementing this properly may also solve other problems related to `NaN`, and be an alternative to adjusting min and max render index 🤔

**Comment by jsr1611** [comment]
#985

**Comment by swharden** [comment]
I'm going to close this since I'm not actively working on it, but it's triaged high priority so I hope to support this soon
