### ISSUE TITLE
Use ObjectPool for GDI+ Objects

### ISSUE THREAD

**Issue by bclehmann** [ScottPlot/ScottPlot#978]
**What can we do to make ScottPlot better?**
We could potentially improve performance with [`ObjectPool<T>`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.objectpool.objectpool-1?view=dotnet-plat-ext-5.0) by reducing allocations and collections. This does mildly complicate things in two ways:
- We cannot assume that any object has any of its members set to its default because it comes from the pool, it was not newly constructed
    - One can create a new `PooledObjectPolicy<T>` class to run something when `Return()` is called, which could reset the state to sensible defaults instead of having to do it manually everywhere
- We need to manually call `ObjectPool.Return()` to give the object back
    - We could do this automatically by creating a wrapper class that implements `IDisposable` and then call `Return()` in the dispose method. This allows using `using` blocks

There is a `LeakTrackingObjectPool<T>` class which I assume returns objects to which there are no references back to the pool, but it is undocumented.

Lastly, all this referenced an API in the .NET Platform Extensions, i.e. it's in a NuGet package. I know you're not keen on adding dependencies but this does kind of blur the line between being part of the standard library. In any event, it's not difficult to create your own `ObjectPool` class, there's even an article on it in the docs: https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/how-to-create-an-object-pool

The [ScottPlot Roadmap](https://github.com/swharden/ScottPlot/blob/master/dev/roadmap.md) may provide additional context regarding current goals and future directions.

**Comment by bclehmann** [comment]
```

**Comment by bclehmann** [comment]
With N = 20:

```
Includes startup time because ¯\_(ツ)_/¯

Before:
12.137002229690552
11.26367974281311
10.335201263427734
10.450330018997192
11.072436094284058
10.582040548324585
10.643038511276245
11.391994953155518
10.816736698150635
10.530665636062622
11.259594440460205
10.657943725585938
10.763400554656982
11.562257528305054
10.662458419799805
10.695979833602905
11.650984287261963
11.00367021560669
10.795217752456665
11.226184606552124

After:

10.620888710021973
11.259387254714966
10.504619121551514
10.339058637619019
10.833833932876587
10.36064076423645
10.415626525878906
11.372222185134888
10.455325365066528
10.344213962554932
11.021204471588135
10.396629095077515
10.364850282669067
11.316555500030518
10.422507286071777
10.335057258605957
10.942654609680176
10.521931409835815
10.39275574684143
11.434144020080566
```

![image](https://user-images.githubusercontent.com/8635304/114776165-65179480-9d2f-11eb-9943-139ac54919ca.png)

I think the reason the peaks often line up even though the runs are at different time is because they get put into the same turbo behaviour because the workload is similar. I though that was cool.

I used this python script to log it:

```py
import time
import os

with open("log.txt", "w") as file:
	for i in range(20):
		start = time.time()
		os.system("dotnet test --filter Name=Test_scatter_10kPoints --no-build --nologo")
		end = time.time()
		
		file.write(str(end - start))
		file.write("\n")
```

**Comment by bclehmann** [comment]
My testing branch: https://github.com/bclehmann/ScottPlot/tree/ObjectPool-testing

I only added it for ScatterPlots, maybe there'd be more benefit for plottables which use more GDI+ objects

**Comment by StendProg** [comment]
Hi @bclehmann,
I really liked your idea from an architectural point of view, it looks very interesting.
But in practice, I think all this added complexity and the difficulties you described are not worth the tiny payoff.
Of the minuses, I want to add one more, GDI objects can be used only in the thread in which they were created. And if you want to share different objects across the pool between different poltables, then this will make everything much more complicated, and put an end to multithreading.

It would be possible to return to the previous option of storing GDI objects by the Plotables themselves and more carefully approach their disposing. I think this option is also not worth it.
I like the current option, in reality the overhead is not so big, but you can use different threads and be sure that there will be no leakage of GDI objects.

> It's hard to draw anything conclusive from preliminary testing, I'll look into scripting tests so I can actually collect a decent sample. Unfortunately it looks like it's very annoying to script dotnet test

https://github.com/dotnet/BenchmarkDotNet
I haven't tried it myself, but it looks very promising.

**Comment by bclehmann** [comment]
> GDI objects can be used only in the thread in which they were created

Yikes, I hadn't known that. I suppose one could get around that by using `[ThreadStatic]`, but I think that might increase overhead on short-lived threads.

**Comment by swharden** [comment]
## Adoption

> mildly complicate things

> I really liked your idea from an architectural point of view, it looks very interesting.
> But in practice, I think all this added complexity and the difficulties you described are not worth the tiny payoff.

> GDI objects can be used only in the thread in which they were created

This topic has been great to read about and consider! However I agree, at this time I definitely favor simplicity over performance optimizations that aren't big wins.

I'm reminded of a talk by Venkat Subramaniam
https://www.youtube.com/watch?v=4MEKu2TcEHM

Also, one day I hope to cut the `System.Drawing` dependency entirely from the core library. At that time, maybe a custom renderer would be a better place to manage objects in this way, since conceivably all GDI objects would be in a single class.

## Plot

What program was used to make this? It looks like Excel but I didn't think they used those tableau colors.

![image](https://user-images.githubusercontent.com/8635304/114776165-65179480-9d2f-11eb-9943-139ac54919ca.png)

Since your test was Python, I may have expected matplotlib

```py
import matplotlib.pyplot as plt
plt.figure(figsize=(6, 3))
plt.grid(alpha=.5, axis='y')
plt.plot(before, label="before")
plt.plot(after, label="after")
plt.legend()
plt.savefig("test.png")
```

![test](https://user-images.githubusercontent.com/4165489/118426119-9f5eb380-b698-11eb-9b75-49df42234917.png)
