### ISSUE TITLE
FormsPlot control does not appear in the Toolbox

### ISSUE THREAD

**Issue by aims66** [ScottPlot/ScottPlot#979]
### Your Environment
- ScottPlot Version: 4.0.48, 4.1.12
- Operating System: Win10
- Is it a GUI app? What platform? WinForms
    - Platforms include WinForms, WPF, and Avalonia

Describe the bug and how we can reproduce it.
ScottPlot.WinForms controls do not appear in the Toolbox in the Microsoft Visual Studio Community 2019, Version 16.9.4 (April 13, 2021).

**Comment by swharden** [comment]
Hi @aims66, after installing ScottPlot with NuGet ***rebuild the project*** and perhaps restart visual studio - does this fix the problem?

**Comment by aims66** [comment]
Hi Scott,

I made this multiple times. 
It works well in VS v. 16.7.3.

**Comment by swharden** [comment]
> It works well in VS v. 16.7.3.

I assume this means the problem has been resolved! 👍

**Comment by 1Dodeo1** [comment]
Hello!
What about VS 2022? Would you please tell how to solve it there?

**Comment by ed-graham** [comment]
As of December 2023 the FormsPlot control does _not_ appear in the tool box for Visual 2022 Community Edition.

**Comment by ed-graham** [comment]
> > It works well in VS v. 16.7.3.
> 
> I assume this means the problem has been resolved! 👍

The control is visible in the tool box as of December 2023 using Visual Studio 2022 Community edition.  However, you must make sure you install the **ScottPlot.WinForms** package and not the _ScottPlot_ package.

**Comment by swharden** [comment]
Following-up, here is some more information that may help WinForms users https://scottplot.net/faq/add-winforms-programmatically/

**Comment by andopa** [comment]
Allow me please to follow-up aswell.

I am experiencing the problem 
- on two different machines (Windows 10 Enterprise and Pro) 
- with VS 2019 v16.11.34
- in VB.NET windows forms applications (.NET Framework 4.8.2)
- with the latest ScottPlot.WinForms version 5.0.21 and 4.1.71

Neither rebuilding the project, nor resetting the toolbox, nor restartung VS and Windows did help.
Is there any other hint or a new solution found yet?

**Comment by swharden** [comment]
Hi @andopa, I think this is a VS2019 issue, but this strategy can work: https://scottplot.net/faq/add-winforms-programmatically/#add-a-scottplot-inside-a-panel

**Comment by andopa** [comment]
Thank you @swharden, this method works!
However, I was hoping to be able to conveniently select the control from the toolbox.

**Comment by swharden** [comment]
> However, I was hoping to be able to conveniently select the control from the toolbox.

haha, I hear you 😇 I think this is a Visual Studio bug, not a ScottPlot bug. I think it relates to using packages that support 32-bit and 64-bit platforms in 32-bit versions of Visual Studio (which 2019 is I think)... unfortunately I don't think there's much I can do from our end 🤷
